trilinos/Trilinos

- packages/xpetra/doc/build_docs
Makes sure the script doesn't fail if `html` isn't present.
> Xpetra: `rm -rf html`

- packages/zoltan2/scripts/xml2dox.py
Makes sure that xml2dox.py work with newer Python versions too.
> Zoltan2: use Python's xml.etree instead of elementtree

- packages/pamgen/mesh_spec_lt/pamgen_element_dictionary.C
@jwillenbring 
@trilinos/pamgen
- Removed second extern in C file that was already in h.
- Please refer to issue #66 for full summary of patch
Signed-off-by: bddavid <davidson@txcorp.com>
> Pamgen Package Warnings Fixes

- packages/thyra/core/src/interfaces/operator_solve/fundamental/Thyra_SolveSupportTypes.hpp
Fixes Sandia bug https://software.sandia.gov/bugzilla/show_bug.cgi?id=6401.
> thyra: remove excessive indentation in parameters output

- cmake/ctest/drivers/ATTB/ATTBDevEnv.cmake
- packages/teuchos/numerics/test/BLAS/default_blas_rot.cpp
This commit disables the extreme value tests and re-enables the ROTG tests on hansen.
> Disable testing for edge cases for ROTG (Trilinos #211)

- packages/rol/example/PDE-OPT/TOOLS/PDE_FEM.hpp
- packages/rol/example/PDE-OPT/adv-diff-react/data.hpp
- packages/rol/example/PDE-OPT/elasticitySIMP_topologyOptimization/filter.hpp
- packages/rol/example/PDE-OPT/poisson/data.hpp
- packages/rol/example/PDE-OPT/stefan-boltzmann/data.hpp
These examples were broken by a recent commit to Tpetra that added
a MatrixMarket reader for graphs.  The Tpetra MatrixMarket readers
and writers are all templated on the matrix type (even the vector
readers and writers), and the ROL examples were templating them
on the vector type.
> ROL: Fixed examples that failed to build

- packages/intrepid2/refactor/src/Shared/Intrepid2_Types.hpp
Albany would not compile, with errors for multiple definitions of Intrepid2::Parameters::Epsilon, Threshold, and Tolerance.
This change successfully compiled, but I got rid of the platform-dependent epsilon.
> Intrepid2/refactor: workaround for static params

- packages/intrepid2/refactor/src/Discretization/FunctionSpaceTools/Intrepid2_FunctionSpaceToolsDef.hpp
Wrong type name was used in F_evaluate -- was inField instead of inCoeff
> Intrepid2/refactor: fix type name in FST evaluate

- packages/triutils/src/Trilinos_Util_iohb.cpp
On FreeBSD 10, which uses clang as its default compiler, the Triutils package will not compile if C++11 is enabled.  This is because on that system, when building on 64-bit machines the "sys/_null.h" header defines NULL not as 0, but as either "nullptr", "__null", "0L", or "(void *) 0" depending on how it's being included.  Peppered throughout packages/triutils/Trilinos_Util_iohb.c is this sort of pattern:
```
char somearray[somesize];
somearray[someindex] = (char) NULL;
```
which is clearly intended to null-terminate a string.  This fails to compile, because one is casting a 64-bit pointer down to 8 bits, and clang hates that (but only when invoked with -std=c++11).  
Changing these uses of "NULL" to uses of the null character '\0' allows Trilinos_Util_iohb.cpp to compile just fine, and …
> Fix triutils for FreeBsd

- packages/zoltan2/test/driver/test_driver.cpp
- packages/zoltan2/test/helpers/AdapterForTests.hpp
- packages/zoltan2/test/helpers/UserInputForTests.hpp
- packages/zoltan2/test/helpers/Zoltan2_ComparisonHelper.hpp
Removes deletes in the ComparisonHelper by converting the coordinate input adapter to use an RCP pattern.
> Zoltan2 test driver memory deletes

- packages/intrepid/src/Discretization/Basis/Intrepid_HDIV_TRI_In_FEMDef.hpp
- packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_HEX_Cn_FEMDef.hpp
- packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_TRI_Cn_FEMDef.hpp
Fixes for HGRAD bases on hexahedra and triangles.
> Intrepid HGRAD Bases: avoid potential buffer overrun, eliminate extraneous console output, and avoid exceptions thrown when run in Debug mode

- cmake/ctest/TrilinosCTestDriverCore.generic.jenkins.cmake
- cmake/ctest/drivers/rhel6-x86_64/ctest_linux_nightly_jenkins_zoltan2.cmake
This is the initial setup for running Zoltan2 cdash tests.
Adds the TrilinosCTestDriverCore for Jenkins testing.
Used a CUSTOM_ENV_VARIABLES flag to define places where that
file has custom changes for the initial testing and setup.
Adds the Zoltan2 script for running a single Jenkins job.
Currently we are testing these by setting the Jenkins parameters
in a script and then calling the ctest script.
> Zoltan2: Initial cdash testing setup for Zoltan2

- packages/sacado/src/Sacado_cmath.hpp
Eliminate preprocessor directive by moving
the two "defined" directives into the
statement in which they are used.
This allows for Trilinos to build on Windows (packages required for Xyce) with Intel and the Intel MKL.
Intel throws a warning about "defined" is always false in a macro expansion in Microsoft mode. This macro appears to only be used in this file, so I simply moved the macro into the statement in which it is used.
Moved from pull request #633
> Sacado_cmath.hpp: Change_preprocessor_directive

- packages/sacado/src/Sacado_cmath.hpp
Change to all one ifdef statement, as Windows
compiles complain about "defined" always being
false in a macro expansion.
Resubmitting to the 12.6 branch because that is what is currently built for Xyce.
> Sacado_cmath.hpp: Refactor_preprocessor_ifdef

- packages/tpetra/core/src/Tpetra_Details_Environment.cpp
- packages/tpetra/core/src/Tpetra_Details_Environment.hpp
- packages/tpetra/core/test/CMakeLists.txt
- packages/tpetra/core/test/Environment/CMakeLists.txt
- packages/tpetra/core/test/Environment/Environment_UnitTests.cpp
Adds Tpetra::Details::Environment singleton class:
- query system for environment variables
- cache retrieved environment variables
- cache default variables on instantiation (TPETRA_DEBUG,
TPETRA_USE_BLAS)
- setting environment variables capability is disabled
Commit also provides an updated method of loading configuration files
with the checkin-test.py script, allowing configuration files to have
extensions different than '.py'
Addresses: #654, #684, #688
Build/Test Cases Summary
Enabled Packages: TpetraCore, Ifpack2, Belos, Amesos2, Zoltan2, Xpetra, MueLu, Stokhos, Sacado
Disabled Packages: SEACAS,STK,Shards,FEI,ROL,Moertel,Panzer,ThreadPool,OptiPack,Rythmos,Intrepid,PyTrilinos
0) MPI_DEBUG => passed: passed=515,notpassed=0 (11.04 min)
> @trilinos/tpetra Query environment variables with Tpetra

- packages/teuchos/numerics/src/Teuchos_MatrixMarket_split.cpp
- packages/teuchos/numerics/test/MatrixMarket/MatrixMarket_Raw_InOutTest.cpp
Issue #892 demonstrates that the @trilinos/teuchos and @trilinos/tpetra 
MatrixMarket file reader will fail to read MatrixMarket files with consecutive 
spaces in the banner.  This commit fixes that problem.
Issues: #892
Notify: @mhoemmen
> Provides resolution for Issue #892

- packages/shylu/basker/test/CMakeLists.txt
- packages/shylu/basker/test/amesos2_interface_coverage_test.cpp
This commit partially addresses Trilinos Github issue #919
A test from amesos2_interface_coverage_test.cpp (4, 4 threads test) results
in intermittent runtime failures (seg faults).
Test failure is independent of #649 and can be temporarily disabled to
prevent blocking of that issue while permanent fix is underway.
basker/test/CMakeLists.txt file modified to fix inconsistent naming of tests
which prevented amesos2 coverage tests from compiling.
> ShyLUBasker: Fix CmakeLists file and disable a unit test

- packages/amesos2/test/solvers/Basker_UnitTests.cpp
- packages/amesos2/test/solvers/SolverFactory.cpp
- packages/shylu/basker/src/basker_order_scotch.hpp
This commit address Trilinos Github Issue #747
Added parameter list when testing shylubasker to set options,
particularly for control of the thread count when testing a matrix
that is too small for a given number of threads
This is prep to move towards using an xml file to test for multiple
matrices
modified:   packages/amesos2/test/solvers/Basker_UnitTests.cpp
modified:   packages/amesos2/test/solvers/SolverFactory.cpp
modified:   packages/shylu/basker/src/basker_order_scotch.hpp
> Amesos2 Basker: Add param list when testing shylubasker

- packages/tpetra/kernels/perf_test/spmv/OpenMPDynamic_SPMV.hpp
- packages/tpetra/kernels/perf_test/spmv/OpenMPSmartStatic_SPMV.hpp
- packages/tpetra/kernels/perf_test/spmv/OpenMPStatic_SPMV.hpp
- packages/tpetra/kernels/perf_test/spmv/test_crsmatrix.cpp
Adds three tests to TPetra SpMV Benchmark so that comparisons to OpenMP can be made directly:
- **OpenMP Static** which executes SpMV using a static OpenMP schedule
- **OpenMP Dynamic** which executes SpMV using a purely dynamic OpenMP schedule
- **OpenMP Smart-Static** which executes SpMV using a Non-Zero Balancer over threads and a static schedule.
These results were shown way back in July/August but we in custom implementations, this pull-request merges these into the TPetra benchmark so that comparisons between implementations can be made with new compilers and software stacks.
> Implementation Direct OpenMP Implementation Comparison in TPetra SpMV Benchmark

- packages/tpetra/kernels/perf_test/spmv/OpenMPSmartStatic_SPMV.hpp
- packages/tpetra/kernels/perf_test/spmv/test_crsmatrix.cpp
@mhoemmen does this get what you need for not having OpenMP enabled?
> Fix TPetra SpMV Benchmark when OpenMP is Not Enabled during Compilation

- packages/isorropia/src/epetra/Isorropia_EpetraMatcher.cpp
GCC 6.2.0 correctly points out that the
indentation here is misleading.
in this case the behavior is the same
either way, but for subtle reasons.
this commit should silence the warning.
> Isorropia: fix indentation warning

- packages/intrepid2/refactor/src/Shared/Intrepid2_RealSpaceToolsDef.hpp
This is needed to help resolve gahansen/Albany#34
These changes allow some of the Intrepid2
RealSpaceTools to accept something like
Kokkos::View<const double*> as right-hand-side
arguments.
One must use the non_const_value_type to avoid
declaring local variables that are not modifiable.
I'm not certain that these changes account
for all RealSpaceTools, however.
> Intrepid2: accept const values in RealSpaceTools

- packages/tpetra/core/test/inout/CooMatrix.cpp
The test passes by creating a throwaway `Tpetra::Map` at the beginning
of the test so that Kokkos initializes.
Addresses: #1056
> @trilinos/tpetra Resolves failing test on Darwin mentioned in #1056

- packages/zoltan2/test/unit/models/GraphModel2ndAdjsFromAdjs.cpp
Environment was missing proper constructor with comm.
> Zoltan2: Fix GraphModel2ndAdjsFromAdjs unit test

- packages/intrepid2/refactor/src/Shared/Intrepid2_ArrayToolsDefDot.hpp
value_type shouldn't be taken from one of the input
views because they may have `const ScalarT` as their
value_type. instead take it from the output view.
this is needed to resolve gahansen/Albany#34
@mperego @kyungjoo-kim
> Intrepid2: ArrayToolsDefDot: fix for const ScalarT

- packages/amesos/src/Amesos_Scalapack.cpp
This is a follow-up to 69c2781d7c1b.
* packages/amesos/src/Amesos_Scalapack.cpp (Amesos_Scalapack::Solve):
Use 'EPETRA_CHK_ERR' rather than 'assert' for checks with side-effects.
> Amesos: Scalapack: Fix assertions with side-effects.

- cmake/TPLs/FindTPLParMETIS.cmake
This pull request changes how ParMETIS' version is checked at configure time. Rather than compiling and running a binary, the check is now a compile time error if the version is insufficient. This will allow the test to work on systems where Trilinos is cross compiled.
fixes #937
@trilinos/framework @bartlettroscoe @bmpersc
> Change CMake check for ParMETIS version to compile time

- packages/amesos2/src/Amesos2_Basker_def.hpp
- packages/amesos2/src/Amesos2_KLU2_def.hpp
- packages/amesos2/src/basker/basker_decl.hpp
- packages/amesos2/src/basker/basker_def.hpp
- packages/amesos2/test/solvers/Basker_UnitTests.cpp
- packages/amesos2/test/solvers/KLU2_UnitTests.cpp
This address Github issue #1127
At the end of numericFactorization_impl, whether using Basker or KLU,
the status_ lu_nnz_ variable is set via the setNnzLU( args ) method;
this is done at the end of numericFactorization as these solvers allow
for pivoting, which could cause a discrepency in the number of
non-zeros reported after symbolicFactorization compared to
numericFactorization.
> Amesos2: Expose getNnzLU in Basker and KLU

- packages/minitensor/src/MiniTensor_Storage.h
@lxmota  this fixes the Clang build in the Albany CDash:
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=49925
> MiniTensor: add needed diagnostic push pragma

- packages/minitensor/src/MiniTensor_Solvers.h
There is code in the Albany CrystalPlasticity
model that directly accesses this boolean, and
got broken by f001af9.
This commit fixes the build.
@lxmota this fixes today's Albany CDash failures:
http://my.cdash.org/viewBuildError.php?buildid=1155248
> MiniTensor: give protected access to bool failed

- packages/teko/src/Tpetra/Teko_InterlacedTpetra.cpp
this variable does need to be defined if
the assert() call will be using it, so
it needs to be protected by the same
condition that controls assert(),
which is NDEBUG
Trilinos develop failed to compile in the Albany CDash:
http://my.cdash.org/viewBuildError.php?buildid=1158196
> Teko: fix compile error introduced by e728fc0

- packages/rol/src/sol/function/ROL_Distribution.hpp
- packages/rol/src/step/interiorpoint/ROL_InteriorPointPenalty.hpp
- packages/rol/src/utils/ROL_GaussChebyshev3Quadrature.hpp
- packages/rol/src/zoo/ROL_HS5.hpp
- packages/teuchos/core/src/Teuchos_ConfigDefs.hpp
@trilinos/rol 
Added some defines to enable using the M_PI constant.
Changed a gcc-specific 'xor' to standard c++ operator ^.
> Issue #1178 (ROL build failure on Windows)

- packages/zoltan/src/matrix/matrix_operations.c
This additional code just checks for the
precondition described in the comment of
the function.
If users declared diagonal terms twice,
this function used to segfault.
This change should produce a more helpful
error message so users know what they've
done wrong.
> Zoltan: add error checking in Matrix_Mark_Diag

- packages/zoltan2/src/problems/Zoltan2_Solution.hpp
Adds virtual destructor base class Zoltan2_Solution.hpp to avoid warnings for PartitioningSolution.
> Zoltan2: Fix non virtual destructor for PartitioningSolution (#1186)

- packages/tpetra/core/src/Tpetra_Details_libGemm.cpp
These functions cannot call Teuchos GEMM
for std::complex unless Teuchos has actually
instantiated that GEMM.
> Tpetra: #ifdefs for new cgemm/zgemm (#1200)

- packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp
- packages/teuchos/parameterlist/test/yaml/YamlParameterList.cpp
This commit solves two issues, both of which
fall into the category of "the type of a
parameter would change if written to YAML
and read back into Teuchos":
1. numbers with quotes around them would
not be interpreted as strings
(which is necessary to ensure strings
remain string-typed even if they happen
to just contain a number)
2. the API that takes only a filename
would print integer-valued doubles
in integer format (YAML has no other way
of distinguishing double and int, so I
added std::scientific to ensure all doubles
get formatted differently from ints)
While fixing item (2), I added the precision
settings discussed in #1181.
There is no way for users to change those settings
from the API that takes only a file name, so
high precision seems like a good default. …
> Teuchos: ensure YAML scalar types are preserved

- packages/minitensor/src/MiniTensor_Utilities.h
@lxmota I think this include is needed to properly compile a code that only includes `MiniTensor.h` and nothing else.
> MiniTensor: include Teuchos_ScalarTraits.hpp

- packages/tpetra/core/src/Tpetra_Details_iallreduce.hpp
GCC 7 needs more explicit
inclusion of <functional>
see #1286 
> Tpetra: fix for #1286

- packages/shylu/basker/src/basker_order.hpp
ShyLUBasker failed to properly solve multiple matrices when reusing
symbolic factorization results. This PR fixes the problem, addressed in
issue #1289.
Bug reported by Heidi Thornquist
> ShyLUBasker: Fix related to issue #1289

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Package: @trilinos/tpetra
Review: @mhoemmen
Test Summary:
100% tests passed, 0 tests failed out of 286
Label Time Summary:
Amesos2    =   2.67 sec (5 tests)
Belos      =  33.89 sec (9 tests)
Ifpack2    =  92.74 sec (32 tests)
Stokhos    = 102.15 sec (28 tests)
Tpetra     =  63.24 sec (125 tests)
Zoltan2    =  55.90 sec (87 tests)
Total Test time (real) =  95.06 sec
> Replace `throw char*` with call to `TEUCHOS_TEST_FOR_EXCEPTION`

- cmake/ctest/drivers/parameterized/ctest_linux_nightly_generic.cmake
The parameterized build needs to set the cdash track via the Trilinos_TRACK
property to be able to set the cdash track to something other than the three
blessed values ("Nightly", "Experimental", "Continuous").
Tribits can also change things based on the value of CTEST_TEST_TYPE.
- if CTEST_TEST_TYPE is Experimental, Tribits will override Trilinos_TRACK and set it to Experimental.
- if CTEST_TEST_TYPE is Nightly, Tribits pulls in other stuff
Since it's best to keep CTEST_TEST_TYPE to one of the three blessed values, we'll hard-wire it to
use Nightly for now.  In the future, we may need to update this to something more generic.
This relates to issues #1294, #1298 
Additional relevant information can be found in [Tribits issue 189](https://github.com/TriBITSPub/TriBITS/issues/189)
> Framework: Updating parameterized cdash track

- packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp
@kddevin : Can you look over these two potential fixes for issue 183 ? Both have pros and cons.
One use lno_t for calling AMD other uses SuiteSparse_long for AMD but has to downgrade the permutation as perm in OrderingSolution uses lno_t. Both will resolve #183 for now. There is an ifdef in the code that splits these two options.
> Two potential fixes for issue 183, just for review purposes.

- packages/teuchos/comm/src/Teuchos_CommHelpers.cpp
This silences a deprecation warning from C++11 compilers.
> Teuchos: don't use std::auto_ptr if C++11 is on

- packages/teuchos/numerics/test/LAPACK/cxx_main.cpp
Fixes typename build error for CXX11 off in Teuchos LAPACK test.
> Teuchos: Fix LAPACK test typename for CXX11 off (#1208)

- packages/zoltan/src/include/zoltan_types.h
@zoltan 
Replaced "WIN32" in zoltan_types.h with the correct version "_WIN32". See [Visual Studio Predefined Macros](https://msdn.microsoft.com/en-us/library/b0084kay.aspx) for more information. This is also consistent with what is used elsewhere in zoltan (like src/zz/zz_util.c and src/Utilities/Timer/timer.h).
> Zoltan: Fix incorrect windows macro.

- packages/tpetra/core/test/CrsMatrix/assembleElement.cpp
@trilinos/tpetra: Fixing comparison between signed/unsigned int in assembleElement test.
To Review: @mhoemmen
> Fix for CDash build warnings/errors for @trilinos/tpetra assembleElement test

- packages/ifpack2/src/Ifpack2_ILUT_def.hpp
Making both specializations inline silences warnings
about the unused <double> specialization
> Ifpack2: silence ilutDefaultDropTolerance warning

- packages/teuchos/core/src/Teuchos_CommandLineProcessor.cpp
- packages/teuchos/core/test/CommandLineProcessor/cxx_main.cpp
Depending on whether help option was before or after some arguments on
the command line, it could affect the output. Specifically, the provided
command line values of other parameters could appear as the default ones
in the help output.
This patch fixes (or works around) the problem by first searching
through the parameters to find if help option is present.
Fix #585.
> Teuchos: fix the default values for help option for CommandLineProcessor

- packages/teuchos/parser/example/Calc.cpp
- packages/teuchos/parser/src/CMakeLists.txt
- packages/teuchos/parser/src/Teuchos_MathExpr.cpp
- packages/teuchos/parser/src/Teuchos_MathExpr.hpp
- packages/teuchos/parser/test/unit_tests.cpp
This PR is mostly for book-keeping and visibility purposes, as I think I can safely merge in changes that only affect TeuchosParser so long as it remains EX.
The "Calc" example was turned into a built-in language in TeuchosParser, by adding the ternary operator, boolean expressions for the ternary operator, and arbitrary numbers of function call arguments. The reason for this is that this language should be sufficient for cases like STKExprEval, and can form a common basis for codes that need to specify boundary and initial conditions. The language makes no requirements on the types of expressions or what code is used to evaluate them, and yet we can provide a common parser.
> TeuchosParser: add and test MathExpr language

- packages/ifpack2/src/Ifpack2_Details_Amesos2Wrapper_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestAdditiveSchwarz.cpp
Ifpack2's Amesos2Wrapper (_def, line 480) sometimes didn't detect the need to
create local versions of X and Y to pass to Amesos2. In
distributed AdditiveScwharz with overlap, this logic incorrectly
thought the problem was serial and did not create local views of X and Y.
> Ifpack2: Fix #560 (bug in Amesos2Wrapper)

- packages/tpetra/core/src/Tpetra_Details_getEntryOnHost.hpp
This typedef is only used inside the
`#ifdef CUDA` blocks, so move it into
those blocks.
> Tpetra: fix unused typedef warning

- cmake/ctest/drivers/parameterized/ctest_linux_nightly_generic.cmake
Per our discussion in this morning's framework team standup, I'm disabling anasazi tests that show up as unstable in nightly testing to clean up the dashboard.  
This references Trilinos issue #1393
> Framework: Disabling two unstable Anasazi tests

- cmake/ctest/drivers/apollo/cron_driver.sh
- cmake/ctest/drivers/kokkos-dev/cron_driver.sh
- cmake/ctest/drivers/perseus/cron_driver.sh
ctest allows oversubscription so OMP_PROC_BIND=false allows OS to
load-balance.
This commit can be changed once ctest properly sets process mask.
> Kokkos: Set OMP_PROC_BIND=false for Kokkos integration testing

- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
2feb2e75 removed HAVE_DEBUG protection from
a call to
TEUCHOS_TEST_FOR_EXCEPTION_CLASS_FUNC
which means tfecfFuncName needs to be defined
in all cases now.
addresses #1528
> Tpetra: CrsGraph insertInd... tfecfFuncName

- cmake/ctest/drivers/parameterized/ctest_linux_nightly_generic.cmake
Disabling Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 in the parameterized build because it's unstable.
@trilinos/anasazi References issue #1393
> Framework: Disabling unstable Anasazi test.

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
In this case, the variable is only used
in debug mode, so it should only be
defined in debug mode
> Tpetra: fix another tfecfFuncName warning

- packages/amesos2/src/Amesos2_Umfpack_FunctionMap.hpp
This removes extern declarations not needed since umfpack.h
is included.
> Amesos2: Remove extern declarations #1584

- packages/amesos2/test/adapters/Epetra_MultiVector_Adapter_UnitTests.cpp
- packages/amesos2/test/adapters/Epetra_RowMatrix_Adapter_UnitTests.cpp
- packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp
In Amesos2, fixed adapter unit tests (#1495) (Tpetra_CrsMatrix, Epetra_RowMatrix and Epetra_MultiVector). In general, the failures were caused by the tests trying to compare global indices against local indices, when the matrices/vectors were distributed on two or more MPI ranks.
Normally I wouldn't make formatting changes, but I replaced some mixed tabs+spaces with just spaces (without changing indentation) to be consistent. I can revert that part if necessary.
> Amesos2: Fixed *Petra adapter unit tests

- packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp
As discussed previously, here is my little patch to remove the warnings stemming from the deprecated function call used in '''xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp'''
It follows what @mhoemmen did in Tpetra so I feel somewhat confident that it should be ok?
As it is my first attempt at using kokkos feel free to educate me : )
> Xpetra blockcrs fix to remove build warning

- packages/ml/matlab/mlmex.cpp
ML Matlab interface fix for > R2016a:
From R2016a on the macro MX_API_VER does not exist in matrix.h anymore.
This fix has been suggested on 
https://de.mathworks.com/matlabcentral/answers/274084-how-to-determine-mex-api-version
and works for me.
> ML Matlab interface:  in R2016a MX_API_VER does not exist anymore

- packages/ml/matlab/CMakeLists.txt
These lines are a one to one copy from the MueLu project that enable proper build of the Matlab interface on macOS without any manual user modifications.
> Tweak ML Matlab build for macOS

- packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
This fixes a warning about a shadowed variable name.
Personally, I think the need to pass a value to `packValueCount` is really causing more trouble than its worth. I don't see a scenario in which a value-dependent packing scheme would give any benefit, and I suspect not all users of `packValueCount` correctly call it for such a change.
> Tpetra: silence warning about shadowed gid var

- packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
There may be a more systematic resolution via
issue #1672, but for now this quick patch
will silence the warning
> Tpetra: quick fix for shadowed variable warning

- packages/teuchos/parser/src/Teuchos_string.hpp
This causes a compile error with GCC 4.4.7
[#1688]
> Teuchos: remove typename that was outside template

- packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
'diagmod' is only used in one #ifdef case,
so move it into that case
> Ifpack2: silence unused variable warning

- packages/teuchos/parser/gen/gen_Teuchos_chartab.cpp
- packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp
- packages/teuchos/parser/src/Teuchos_chartab.cpp
- packages/teuchos/parser/src/Teuchos_chartab.hpp
On some platforms (e.g. POWER8), char is unsigned as
opposed to signed by default.
The TeuchosParser 'chartab' was constructed using signed
chars, and although some templated checks were put in
place for the case of unsigned chars, there was one
missing (a check for the value to be more than SCHAR_MAX).
This would cause an out-of-bounds access to 'chartab'.
The 'chartab' generator program has been enhanced to specifically
use signed chars and to provide a size macro that the
templated checks can use to restore safety.
[#1698]
I'll likely just start the checkin script for this.
> TeuchosParser: fix 'chartab' tests for unsigned char

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Guard unused `const char tfecFuncName[]` with `#ifdef HAVE_TPETRA_DEBUG`
Addresses: #1701
Build/Test Cases Summary
Enabled Packages: TpetraCore
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Forward Packages
1) MPI_RELEASE_SHARED_OPENMP_PT => passed: passed=1509,notpassed=0 (83.61 min)
> Tpetra: Silence unused variable warning.

- packages/epetraext/src/inout/EpetraExt_HDF5.cpp
This was pointed out by GCC's "maybe uninitialized variable" warning (`memspace_id` would be closed uninitialized if the loop iterates zero times). However, it seems to be a legitimate bug in closing this handle, i.e. it seems like it is only closing the last created handle but it should close all of them. I suspect the old code leaks memory.
> EpetraExt: fix memspace handle closing

- packages/nox/src-loca/src/LOCA_Stepper.C
- packages/nox/src-loca/src/LOCA_Stepper.H
- packages/piro/src/Piro_LOCASolver.hpp
- packages/piro/src/Piro_LOCASolver_Def.hpp
This proposed changes to LOCA and Piro are necessary for the implementation of the Schwarz alternating method in Albany, specifically LCM.
This is really important for LCM, as the Schwarz method is currently being used for production runs in concurrent multiscale calculations for coupling small scale microstructure to macroscopic models.
I understand that they are not the cleanest changes, in that they expose some internals, but they are needed.
> lcm-mods: Modifications required for Schwarz alternating method in Albany (LCM)

- packages/panzer/adapters-stk/test/stk_interface_test/tSquareQuadMeshFactory.cpp
Removed lines with TEST_ASSERT(unsigned integral type >= 0) because
that's not actually testing anything.
> Panzer:  Remove Unnecessary TEST_ASSERT()s

- packages/tpetra/core/test/CrsMatrix/Albany182.cpp
There were semicolons after two macro definitions which
after the expansion resulted in two semicolons at the
end of the statement. This allows this code to compile
with warnings-as-errors on.
> Albany182.cpp: remove extra semicolons.

- cmake/ctest/drivers/parameterized/ctest_linux_nightly_generic_sierra.cmake
While investigating the build failures it was
determined that sierra no longer uses the library.
> ctest_linux_nightly_generic_sierra.cmake: remove claps

- packages/pamgen/mesh_spec_lt/pamgen_mesh_specification.C
- packages/pamgen/src/parse_routines.C
The token checks I believe are actual
bugs which were spotted by newer compiler
warnings.
Also two unused variables are removed.
not sure who to mention besides @jgfouca
> Pamgen: fix compiler warnigns and bugs

- packages/epetra/src/Epetra_BlockMap.cpp
- packages/epetra/src/Epetra_CrsGraph.cpp
- packages/epetra/src/Epetra_CrsMatrix.cpp
These changes do alter the prints (braces were missing), but I don't think I changed anything that alters the actual linear algebra values at all.
These changes have the same motivation (fewer warnings from newer GCC versions) and effect (different printouts in some cases) as #1767.
> Epetra: fix more indentation warnings (some bugs)

- packages/tpetra/core/test/MatrixMatrix/CMakeLists.txt
Setting the number of MPI processes to 4 for this test to fix an issue shown in the CDash run:
https://testing.sandia.gov/cdash/testDetails.php?test=42290438&build=3183867
Error Message:
```
p=0: *** Caught standard std::exception of type 'std::runtime_error' :
Test requires exactly 4 MPI ranks.
```
Fixes issue #1907
> MueLu: TpetraCore_MatrixMatrix_UnitTests Fix

- packages/kokkos/core/src/Kokkos_Serial.hpp
- packages/kokkos/core/src/impl/Kokkos_Serial.cpp
Kokkos::Serial::is_initialized always
returned one, which breaks the way that
libraries decide to call Kokkos::initialize
and Kokkos::finalize, causing memory leaks.
I am patching this in Trilinos immediately
because the Kokkos promotion is taking too long.
Once the Kokkos promotion is done, users
are encouraged to instead call the long-awaited
Kokkos::is_initialized function instead.
@crtrott @dsunder @mhoemmen 
I need this now to stop memory leaks.
Unless there is strong pushback, I'll start the checkin script on this.
> Kokkos: patch kokkos/kokkos#1184

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
A few months back I whipped up a handful of issue and merge requests templates to use in some of my GitLab projects.  Unfortunately GitHub only allows a single template for either issues or pull requests, so I've consolidated the ones I've used before and tried to make them generic enough that they apply to bug reports, feature requests, documentation issues, discussions, or just arbitrary tasks.  These templates were pieced together taking inspiration from various best practices examples I found around the web, but I'm afraid I didn't keep track of my sources when putting them together.
On the pull request side of things, it would be a good idea for us to actually fill out CONTRIBUTING.md so contributors know what's expected of them.  Perhaps this is part of the ongoing pull request …
> Add Issue and Pull Request Templates

- CONTRIBUTING.md
As per #1823, the basics of creating an issue, working it, and submitting a pull request are now here.  We'll likely want to refine what's in here though.  For instance:
* Do we want developers with push-access to Trilinos to use a fork anyway?
* Do we want to specify a feature branch naming convention?
* Do we care if contributors update their feature branches via `merge`s or `rebase`s?
* Should there be more detail in the **Feedback** section?
Note that these changes assume #1822 gets merged into `develop`, as the detailed instructions for filling out new issues and pull requests are contained in those templates.
> Resolves "Fill out CONTRIBUTING.md"

- packages/ml/src/Utils/ml_MultiLevelPreconditioner_Smoothers.cpp
@trilinos/ml
With GCC 6.3.0 I get a warning
stating that '-pedantic' is not
an option that controls warnings.
Changing this to '-Wpedantic' silences
the warning
Trilinos should ideally build without warnings on relevant compilers, and the pragma changed is specifically intended to silence a warning so it is especially problematic if it instead emits one
A quick spot check was done with an Albany-supporting build of Trilinos.
The checkin script will provide more thorough testing.
> ML: fix GCC diagnostic pragma

- packages/muelu/src/Utils/MueLu_MutuallyExclusiveTime.cpp
- packages/muelu/src/Utils/MueLu_MutuallyExclusiveTime.hpp
This class seems to be explicitly instantiated
for only two types as 'TagName'.
It also has static member variables.
Because it has static member variables,
either explicit instantiation declarations
must be given (in the case of explicit instantiation),
or the definition of the static member must be
provided in the header file.
I went with explicit instantiation declarations.
In addition, I separated the definitions of the
methods and static variables since they don't
need to be visible anywhere besides the translation
units doing explicit instantiation.
In this case its just one cpp file, so I put the
definitions there.
This is a small victory for reduced compile times
by including less headers and parsing less code.
If instantiations are wanted elsewhere in the future,
the cpp file can …
> MueLu: fix instantiation of MutuallyExclusiveTime

- packages/fei/base/fei_FEDataFilter.cpp
Previous to this change, the nodal loop would continue if the node was
a shared node and was not attached to the local element. This continue
was causing issues in parallel when the nodal data was being synched across
processor after a FETI solve when the run involved element death.
This created many issues and support tickets in the Sierra system that
we have been working through for a long time.
This was a great team effort with Alan, Kendall, Mike, and Patrick.
Alan and Kendall will work on pushing this change to Trilinos.
@trilinos/fei
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
- [x ] No new compiler warnings were …
> Modify the getNodalFieldSolution function in FEI.

- packages/teuchos/kokkoscompat/src/KokkosCompat_Details_KokkosInit.cpp
First, include `<functional>` in a file that uses `std::ref`. This error was being hidden by excessive includes in `Teuchos_ConfigDefs`, which @mhoemmen has been cleaning up. The need was revealed ultimately by this Albany dashboard:
http://my.cdash.org/viewBuildError.php?buildid=1324432
In addition, I noticed a function working around the lack of `Kokkos::is_initialized`, and changed it to call that function now that it exists.
This change is required due to cleanups in the core of Teuchos to avoid compilation errors and also required for correct Kokkos initialization behavior (see kokkos/kokkos#1184).
None yet, will rely on new PR testing system or checkin script.
> Teuchos KokkosCompat: missing include, Kokkos::is_initialized

- cmake/ctest/drivers/parameterized/ctest_linux_nightly_generic_sierra.cmake
The default is to turn off Kokkos cuda but we need it.
> ctest_linux_nightly_generic_sierra.cmake: add flag for cuda

- packages/sacado/src/Kokkos_DynRankView_Fad_Contiguous.hpp
- packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
Fixes issue #2020.
A test demonstrating the compile error was added to the test suite and now passes.  Tested with Serial, OpenMP, and Cuda execution spaces.
- [x ] I have added tests to cover my changes.
> Sacado:  Fix dynamic-to-static view assignment for contiguous layout.

- cmake/ctest/drivers/parameterized/ctest_linux_nightly_generic_sierra.cmake
Not sure why this would resolve gethostname while c11 will not.
Changed the s standard to use from c11 to c11 with gnu extensions. This was needed to resolve gethostname and matches sierras normal behavior.
This was tested by compiling the failing ml_util.c.o object with the new standard and then configuring/compiling all of ml with it as well.
> ctest_linux_nightly_generic_sierra.cmake: change the c standard to gnu11

- packages/amesos2/cmake/Dependencies.cmake
- packages/amesos2/src/Amesos2_KLU2.cpp
- packages/amesos2/src/Amesos2_Util.hpp
Two changes:
1. Amesos2 depends on Tpetra, which depends on Kokkos, however Amesos2
has optional dependency on Kokkos; change this from optional to required
dependency.
2. Compiling without ETI when using Amesos2 could result in errors as seen
in issue #1987, for example unable to convert between std::complex<float>*
and Kokkos::complex<double>*
Add specialization to getStdCplxType to properly select common type for
reinterpret_cast in these cases
Fixes for issue #1987.
1. Make Kokkos a required dependency in Amesos2 rather than optional (Tpetra is already a required dependency)
2. Add missing specialization to getStdCplxType to properly select common type for
reinterpret_cast in these cases.
1. Amesos2 depends on Tpetra, which depends on Kokkos, however Amesos2
has …
> Amesos2: Fix for issue #1987

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_MatchConditions.hpp
- packages/panzer/adapters-stk/test/periodic_bcs/periodic_bcs.cpp
- packages/panzer/adapters-stk/test/periodic_bcs/periodic_mesh.cpp
Added an option to use relative tolerances in Panzer periodic BC matching rather than absolute. For example, one can replace "y-all 1e-8: right;left" with "y-all 1e-8, relative: right;left" and the matching will use a tolerance of 1e-8*(length of domain in x direction).
For problems with small length scales, we've seen errors arise if the matcher tolerance is larger than the mesh size.
Added tests to periodic_mesh and periodic_bcs unit tests. Tests validity of input strings, and checks that when an absolute tolerance fails for a small length scale mesh, the relative tolerance succeeds.
> Panzer: Relative tolerance for periodic bcs

- packages/tpetra/core/example/Finite-Element-Assembly/typedefs.hpp
@mhoemmen 
Changed the NodeType typedef in the Finite Element Mesh assembly example per my conversation today with @mhoemmen.
Mark and I discussed this change today on a teleconference.
Consultation with @mhoemmen and compiled/tested on my workstation.
> Tpetra: FEMA Example update

- packages/nox/src-loca/src/LOCA_Stepper.C
- packages/nox/src/NOX_Exceptions.H
@trilinos/thyra, @trilinos/nox
As per the discussion in #1608, a `LinearOpApplyFailed` exception was added to Thyra, documented with the `LinearOpBase::apply()` routine, and then caught in LOCA's `Stepper` to be treated as a solve failure, such that LOCA can back up, reduce its step size, and then keep on working.
A simulation in Charon ran into a case where a Schur complement calculated as part of a preconditioner was singular, but instead of treating that as a solve failure, LOCA and the simulation just bailed.
* Closes #1608
Trying out the new pull request auto-tester.
> Haven't checked on the compiler warnings yet, but I'll do that soon.
> Resolves "NOX:  Treat Exception as Solve Failure"

- packages/thyra/adapters/epetra/src/Thyra_EpetraThyraWrappers.cpp
- packages/thyra/adapters/epetra/test/TestThyraDebugHang.cpp
@trilinos/thyra Fix the nonconst overload of Thyra::get_Epetra_MultiVector, so that it no longer hangs in debug mode, when some (but not all) MPI processes have zero rows.  #1941 related to the const overload of Thyra::get_Epetra_MultiVector; #2061 relates to the nonconst overload.  This commit fixes #2061.  It also improves the #1941 unit test to exercise both overloads; the test passes.
@trilinos/thyra @micahahoward
Fixes #2061.
* Closes #2061 
* Related to #1941 
Clang 3.9, debug build.
> Thyra: Fix #2061

- packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
- packages/tpetra/core/test/Behavior/Behavior_Named.cpp
- packages/tpetra/core/test/Behavior/Behavior_Off.cpp
- packages/tpetra/core/test/Behavior/Behavior_On.cpp
Changes the separator for named variants of `TPETRA_DEBUG` and `TPETRA_VERBOSE` from ":" to ","
This change allows specifying [debug,verbose] for namespace qualified names.
@mhoemmen, I had intended for this to be the behavior when I initially committed the code (I believe we even spoke about it), but the initial separator of ":" was never changed to ",".
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Enabled packages: Tpetra, MueLu, Ifpack2
Compiler: clang 4.0, openmpi 1.10.3
All built tests pass
> Tpetra: Change named Tpetra::Behavior::[debug,verbose] separator from ":" to ","

- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
In Drekar's TSC, we needed the stepper info. Making this small change in
Tempus prevents a lot of "hacks" in Drekar. I also suspect others might
find it useful
[All tests passed](https://github.com/trilinos/Trilinos/files/1549465/all_test.txt)
This is basically the same PR. Sorry for the inconvenience.
> This allows inherited TSC to be populated with proper Parameters

- cmake/ProjectCompilerPostConfig.cmake
- doc/build_ref/TrilinosBuildReferenceTemplate.rst
cmake/ProjectCompilerPostConfig.cmake now invokes the kokkos
build system to get additional compiler information that is useful for
advanced architectures.  This enables the useful information that Kokkos
calculates can be more widely available.
> Use new kokkos functionality

- packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
- packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
- packages/tpetra/core/test/Behavior/Behavior_Named.cpp
For named query of `TPETRA_DEBUG`, return `true` if and only if the name appears in `TPETRA_DEBUG`.
Built on RHEL6 with sems gcc-4.9.3 software stack.  All Tpetra tests pass
> Tpetra: Change to default return value from a named query of TPETRA_DEBUG

- packages/teuchos/parser/src/Teuchos_Reader.cpp
Checks whether the file stream to parse actually opened successfully, via `TEUCHOS_TEST_FOR_EXCEPTION`.
Without this change, if the file doesn't exist, users would get an error saying that parsing the first character had failed. It is more appropriate that they get an error indicating the file could not be opened in the first place.
> Teuchos: Reader should check success of file open

- packages/belos/epetra/src/BelosEpetraAdapter.cpp
- packages/ml/src/Utils/ml_MultiLevelPreconditioner.h
- packages/teuchos/core/src/Teuchos_RCPNode.cpp
- packages/teuchos/core/src/Teuchos_RCPNode.hpp
- packages/teuchos/core/src/Teuchos_TestForException.cpp
- packages/teuchos/core/src/Teuchos_TestForException.hpp
- packages/teuchos/core/src/Teuchos_Workspace.cpp
- packages/teuchos/core/test/MemoryManagement/CMakeLists.txt
- packages/teuchos/core/test/MemoryManagement/testTeuchosRCPNodeImplDestructTerminate.cpp
- packages/teuchos/core/test/MemoryManagement/testTeuchosTestForTermination.cpp
- packages/teuchos/doc/build_docs
- packages/teuchos/doc/index.doc
- packages/thyra/core/src/support/operator_vector/client_support/Thyra_DetachedVectorView.hpp
@trilinos/thyra 
@trilinos/ml 
@lxmota 
From the first commit message:
This is the foundation for fixing #1303.
First, the macro TEUCHOS_TEST_FOR_TERMINATION
is introduced, which calls std::terminate()
instead of throwing an exception.
I think std::terminate() is the most appropriate
exit call here, because it is exactly what the
compiler would have done anyway. In particular,
the warnings we were getting said
"warning: throw will always call terminate() [-Wterminate]"
As such, if we explicitly call std::terminate ourselves,
we are preserving the existing behavior while silencing
the warning.
TEUCHOS_TEST_FOR_TERMINATION takes stream message code,
and that message will be sent to std::cerr.
This commit also replaces all calls in Teuchos, Belos, Thyra, …
> Stop throwing from destructors

- packages/teuchos/core/src/Teuchos_RCPNode.cpp
It seems certain compilers are smart enough
to realize that no code will ever call
RCPNodeInfo's default constructor, and it
is therefore pointless to define it.
To make this clear, I've changed its definition
to be "= delete;" (C++11 !) and changed the
one place where RCPNodeInfo is constructed to
use emplace_hint, which really isn't too
critical but may improve performance a bit.
This change resolves this warning on GCC 4.9.3 and 5.4.0:
```
src/Trilinos/packages/teuchos/core/src/Teuchos_RCPNode.cpp(73): warning: function "::RCPNodeInfo::RCPNodeInfo()" was declared but never referenced
```
A build of Teuchos passed regression tests
> Teuchos: try to silence RCPNodeInfo() warning

- packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp
- packages/teuchos/parameterlist/src/Teuchos_YamlParser_decl.hpp
- packages/teuchos/parameterlist/test/yaml/YamlParameterList.cpp
- packages/teuchos/parser/src/Teuchos_Reader.cpp
As shown in #2090, having an un-indented comment right after a block scalar would cause the text of that comment to become part of the block scalar. I first added a test to confirm that the block scalar content was not what we want, and coded a trimming procedure to remove such trailing things from block scalars.
Without this fix, comments cannot be safely placed after a block scalar.
* Closes #2090 
A build of Teuchos passed all tests, including the new one that specifically reproduces #2090.
> Teuchos: Fix YAML comment-after-block-scalar bug

- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
There was an extra nonmember ctor implementation in the impl file with an invalid input parameter. Probably a cut-n-paste error.
> Tempus: fix ETI builds #2109

- packages/kokkos/core/src/Kokkos_Core.hpp
- packages/kokkos/core/src/impl/Kokkos_Core.cpp
- packages/kokkos/core/unit_test/CMakeLists.txt
- packages/kokkos/core/unit_test/Makefile
- packages/kokkos/core/unit_test/UnitTest_PushFinalizeHook.cpp
- packages/kokkos/core/unit_test/UnitTest_PushFinalizeHook_terminate.cpp
Fix https://github.com/kokkos/kokkos/issues/714 by adding a new 
function: Kokkos::push_finalize_hook.  It lets users set function(s)
to be called in Kokkos::finalize, BEFORE Kokkos finalizes anything.  I
also added unit tests that ensure the following:
1. Kokkos::finalize actually calls the finalize hooks.
2. Kokkos::finalize calls the functions in reverse (LIFO) order.
That is, it calls them backwards from the order in which they
were added, just as std::atexit does.
3. If a finalize hook throws an uncaught exception, then
Kokkos::finalize calls std::terminate, just as std::atexit does.
This commit patches Trilinos, using the same changes made in Kokkos
pull request https://github.com/kokkos/kokkos/pull/1319 .  That pull
request was merged into Kokkos:develop, so it will overwrite this …
> Kokkos: Add Kokkos::push_finalize_hook function & tests

- packages/teuchos/core/src/Teuchos_RCPNode.cpp
- packages/teuchos/parser/src/Teuchos_YAML.cpp
Silence some warnings by separating code and replacing a functor with a lambda.
These warnings pop up in CUDA builds of Trilinos.
This is all towards the lofty goal of compiling with `-Werror`.
A CUDA build of Trilinos I have emits no Teuchos warnings, and a non-CUDA build passes all Teuchos tests.
> Teuchos warnings

- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_mkl2phase_impl.hpp
This pull requests disables the compilation of MKL-2phase-based SpGEMM method in kokkoskernels.
It is not used as a default methods, and compilation will be turned on for the next kokkoskernels promotion.
@mhoemmen
Description
The compilation was failing when MKL is enabled. This is already fixed in KokkosKernels's develop branch. Current fix in trilinos is to disable the compilation for the TPL which is not executed as a default method.
> Kokkoskernels: spgemm disabling mkl flag on mkl2phase.

- cmake/std/sems/SEMSDevEnv.cmake
Remove erroneous trailing '}'.
Prior to this change, we were unable to successfully configure Trilinos on crf450 using CMake v3.10.1.
By using this change on crf450 to configure Trilinos using CMake v3.10.1.
- [] All new and existing tests passed.
> Fix find library for ptscotch on SEMS machines

- packages/kokkos/core/unit_test/CMakeLists.txt
- packages/kokkos/core/unit_test/UnitTest_PushFinalizeHook_terminate.cpp
Fix #2147.  This relates to a Kokkos test that has a special pass condition.
Thanks to @bartlettroscoe for explaining how to fix it.
I used `TRIBITS_ADD_ADVANCED_TEST` per @bartlettroscoe 's instructions.
The test was failing on the Dashboard.
I tested locally, with both MPI and non-MPI ("serial") builds.
> Kokkos: Fix #2147

- cmake/load_sems_dev_env.sh
Forces the `sems-gcc/4.8.4` module to be loaded before any `sems-intel` modules, working around the fact that those Intel modules point to an old, unsupported version of GCC.
Several users have reported Trilinos compile failures due to this problem with the SEMS modules. This mitigates that issue at least for users and automated tests which use the script being modified.
* Related to #2128 #2172 #2142 
Nothing yet
> SEMS intel workaround

- packages/muelu/src/CMakeLists.txt
[#2170]
Fixes the double-slash that actually matters for #2170
Prevents link errors in CUDA builds with RDC on.
* Closes #2170 
No testing yet, will use autotester
> MueLu: remove the important double slash

- packages/teuchos/parser/example/Calc.cpp
- packages/teuchos/parser/src/Teuchos_MathExpr.cpp
- packages/teuchos/parser/src/Teuchos_MathExpr.hpp
- packages/teuchos/parser/test/unit_tests.cpp
@bathmatt 
@eric-c-cyr 
Add some new syntax to the `Teuchos::MathExpr` language such that you can now assign values to variables. There are no types, so one does:
```
a = sin(x);
b = cos(x);
a * b^2 + b * a^2
```
Where previously one would have to have done:
```
sin(x) * cos(x)^2 + cos(x) * sin(x)^2
```
This is part of what is needed to have a user-friendly and Kokkos-parallel evaluation framework for Sandia applications, which initially will live in the Panzer package.
> Teuchos: allow assignments in MathExpr Language

- cmake/ProjectCompilerPostConfig.cmake
This change ensures CMake configuration will stop with an error condition if the Kokkos Makefile system for architecture-specific flag setup fails in any way.
Combined with kokkos/kokkos#1364 , this improves usability in a common case where the Makefile fails to properly detect the NVCC compiler.
> Framework: error out if Kokkos settings detection fails

- packages/thyra/core/src/interfaces/operator_vector/fundamental/Thyra_VectorBase.hpp
This was confusing to some developers so this is an attempt to be more clear.
> Thyra: Improve documentation for VectorBase::clone_v()

- packages/teuchos/comm/src/Teuchos_CTimeMonitor.cpp
- packages/teuchos/core/src/Teuchos_TestForException.cpp
- packages/teuchos/core/src/Teuchos_any.hpp
- packages/teuchos/core/test/MemoryManagement/Any_UnitTests.cpp
- packages/teuchos/core/test/MemoryManagement/CMakeLists.txt
- packages/teuchos/parameterlist/src/Teuchos_ParameterEntry.hpp
- packages/teuchos/parser/example/Calc.cpp
- packages/teuchos/parser/src/Teuchos_set.hpp
From the first commit message:
```
By using C++11 template metaprogramming, we can
continue to support the comparison and print
extensions of Teuchos::any while still having
a safe compilation path in the case that the
held type doesn't have comparison or print operators.
Exceptions will be thrown if an unsupported operation
is attempted.
We can even automatically detect whether types
have this support by using SFINAE techniques.
This safely allows users to hold types in
Teuchos::any that don't have both comparison and
print operators.
```
As `Teuchos::any` is used more and more via `Teuchos::Reader`, I am frequently encountering cases that require defining comparison and print operators for objects that don't have them. This is especially bad design when those types are …
> Lift Teuchos::any restrictions by metaprogramming

- packages/intrepid2/doc/Doxyfile
Intrepid2 doxygen was pointing to old directory structure (refactor). This fixes the paths.
> Intrepid2: fix doxygen file paths

- packages/anasazi/src/AnasaziTraceMin.hpp
- packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
- packages/tpetra/core/src/Tpetra_Map_decl.hpp
**NOTE**: the PR is against `trilinos-release-12-12-branch`
This is a set of 3 patches required to compile ForTrilinos. Two of them (Anasazi and Tpetra SWIG fix) were backported from `develop` upstream. One (Tpetra MatrixMarket) was newly created and just fixes the compilation issues. The problem was fixed upstream too (see, for example, 45ffbb25237981ea9b3c1bb0677f473ad54e14ca) but slightly changed the interface (including variables) which would require further changes in ForTrilinos later. The patch itself is trivial here.
@bmpersc @jwillenbring @trilinos/framework
> Backport patches to 12.12 branch required for ForTrilinos

- packages/panzer/adapters-stk/test/panzer_workset_builder/hdiv_basis.cpp
- packages/panzer/adapters-stk/test/periodic_bcs/periodic_bcs.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Tpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Epetra_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_BCStrategy_Dirichlet_AuxConstant.hpp
- packages/panzer/mini-em/src/closures/MiniEM_BCStrategy_Dirichlet_AuxConstant_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_BCStrategy_Dirichlet_Constant_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_ClosureModel_Factory_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_MassMatrix.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_MassMatrix_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_WeakGradient.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_WeakGradient_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell_impl.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
This PR removes a number of warnings in Panzer, mostly in the Mini-EM subpackage.  Most were unused parameter warnings, which were fixed by `/* commenting out */` the appropriate parameters in the function definitions.  Some where unused variable warnings, in which case the variable declarations were simply removed.  @egphill, can you look specifically at these removed lines and make sure they don't need to stick around?
It's hard to tell if changes are adding new warnings if Trilinos spits out thousands of them.  This is just cleaning up our little piece of the pie.
`ctest` shows all Panzer tests are passing on my machine.
> Remove Panzer Warnings

- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.hpp
- packages/panzer/disc-fe/src/Panzer_WorksetContainer.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScalarToVector_decl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScalarToVector_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_VectorToScalar_decl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_VectorToScalar_impl.hpp
This is a change that indicates a broader problem with the "two path" worksets. Basically, the *Descriptor version of the needs, and the PureBasis, IntegrationRule versions. The primary contribution of this merge is to make sure the applyOrientation works for *Descriptor version. All panzer tests pass.
> Workset changes for handling the Basis/IntegrationDescriptor Interfaces

- packages/PyTrilinos/example/exLOCA_Chan_Jac.py.in
@wfspotz
Minor change in exLOCA_Chan_Jac.py.in
`except Exception, e:`
in 
`except Exception as e:`
three times. This is (I think) the only example with this problem. All the other examples already have this syntax.
> Pytrilinos: fix except in pytrilinos loca example

- packages/muelu/doc/Tutorial/src/xml/s6_export.xml
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
Allow to print "Nullspace" and "Coordinates" to files from the advanced xml input deck.
In the 'expert' xml interface (Tobias' style), the parameter list 'DataToWrite' controls output of quantities to files. Now, we can also print 'Nullspace' and 'Coordinates'. This has been available in the simple xml-file for quite a while.
Now, xml parameters for printing level matrices, prolongators, and restrictors are consistently named "A", "P", and "R". A deprecation warning is issued if the advanced xml input uses its old parameter names.
* Closes #2260 
- ctest passes on my machine
- Correct behaviour of new output capability has been verified locally
> MueLu: print data in advanced xml mode (#2260)

- packages/muelu/doc/Tutorial/CMakeLists.txt
- packages/muelu/doc/Tutorial/src/CMakeLists.txt
- packages/muelu/doc/Tutorial/tex/CMakeLists.txt
- packages/muelu/test/unit_tests/ParameterList/MLParameterListInterpreter/CMakeLists.txt
This fixes the ninja warnings produced in #2245.
I think the fix for the duplicate copy of the the file `laplace2d.cpp` is rock solid.
The fix for the duplicate copy of the the file  `ml_ParameterList.xml` is a little more uncertain.  I don't understand how it was supposed to work the way it was.   Do the MueLu unit tests read the file `ml_ParameterList.xml` out of the direcrtory `${MueLu_BINARY_DIR}/example/ParameterList/`?  That is the only way this would make sense.
> Fix duplicate copy targets caught by Ninja (#2245)

- packages/teuchos/core/cmake/Teuchos_config.h.in
- packages/teuchos/core/src/Teuchos_Time.cpp
Fix #2271 by doing the following:
- Remove KOKKOS_ENABLE_PROFILING redundant #cmakedefine from
Teuchos_config.h
- Do not include Kokkos_Core.h in Teuchos_Time.cpp; use forward
declarations for Kokkos::Profiling::{push, pop}Region instead, to
improve build time
@vbrunini
> Teuchos: Fix #2271

- packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp
- packages/panzer/disc-fe/src/Panzer_SubcellConnectivity.cpp
#2279 pointed out [these warnings-as-errors failures on CDash](https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3400850).  This PR should clean those up.  Specifically there were
*  extraneous semicolons, and
*  signed vs unsigned comparisons.
Some applications apparently depend on those warnings-as-errors builds being clean.
* Closes #2282
* Part of #2279
It hasn't yet&mdash;using the @trilinos-autotester.
> Panzer Warnings-As-Errors Cleanup

- packages/trilinoscouplings/examples/ml/NonlinML/FiniteElementProblem.cpp
- packages/trilinoscouplings/examples/ml/NonlinML/ml_nox_1Delasticity_example.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE_Epetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE_Tpetra.cpp
Change to the example code to remove compiler warnings.  Because this is examples some information was left in comments of behind ifdefs instead of simple deletion.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of
> examples: fix compiler warnings for #2281

- cmake/TPLs/FindTPLParMETIS.cmake
`FindTPLParMETIS` to look for metis header and library.  Previously, it looked only for the library.
spack installs packages in isolated prefixes; `FindTPLParMETIS` finds the library, but not the header in this case.  
* Closes #2199
> Zoltan2: FindTPLParMETIS - look for metis header and library

- packages/sacado/src/KokkosExp_View_Fad.hpp
- packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp
- packages/sacado/src/Kokkos_LayoutContiguous.hpp
- packages/sacado/src/Kokkos_LayoutNatural.hpp
- packages/sacado/src/Sacado_Traits.hpp
- packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
- packages/stokhos/src/sacado/kokkos/Kokkos_View_Utils.hpp
- packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
- packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
- packages/stokhos/test/Performance/FadMPAssembly/fenl_functors.hpp
- packages/stokhos/test/Performance/MPAssembly/fenl_functors.hpp
Changes to the deep_copy implementation in Kokkos are incompatible with
the existing implementation of deep_copy in Sacado. This is due in part
to custom layouts in Sacado that are not recognized by Kokkos.
The changes in this commit handle the layout issue and revise the assign
method of Sacado's ViewMapping to properly convert View's of (nested)
Fad types into Kokkos Views (with additional dynamic ranks) to use the
new deep_copy implementation in Kokkos.
This PR is needed due to changes in Kokkos deep_copy (currently on Kokkos' develop branch) that are incompatible with the existing implementation in Sacado
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to Kokkos integration testing for the next Kokkos snapshot into Trilinos
* Part of 
* Composed …
> Sacado: Modifications for deep_copy

- packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp
- packages/teuchos/parameterlist/test/yaml/YamlParameterList.cpp
[#2306]
Please see issue #2306 . I also did some unrelated cleanup.
@bathmatt requested that there should be an error (exception) thrown when the same name shows up twice in the same ParameterList. This is a useful debugging tool to catch user error.
* Closes #2306
A custom build of Teuchos passed all tests.
> Teuchos: throw exception at duplicate YAML names

- packages/nox/test/epetra/Thyra/Thyra_Heq.C
- packages/teuchos/core/src/Teuchos_LocalTestingHelpers.hpp
- packages/teuchos/core/src/Teuchos_TestingHelpers.hpp
- packages/teuchos/core/test/UnitTest/vector_UnitTests.cpp
**CC:** @trilinos/nox, @fryeguy52
This updates the test NOX_Thyra_Heq so that it clearly shows why the test passes or fails.  This currently still fails for the Intel 17.4 compiler but at least now we can see how this test is behaving on differnet platforms.
Before, the test just showed:
```
************************************************************************
-- Nonlinear Solver Step 16 -- 
||F|| = 6.500e-08  step = 1.000e+00 (Converged!)
************************************************************************
************************************************************************
-- Final Status Test Results --
Converged....OR Combination -> 
**...........Finite Number Check (Two-Norm F) = Finite
Converged....AND Combination -> 
Converged....F-Norm = 6.749e-09 < 1.000e-08 …
```
> Update NOX_Thyra_Eq test to clearly show why it passes or fails

- packages/anasazi/src/AnasaziMultiVecTraits.hpp
Fix #2323.
@trilinos/anasazi
Fix the signature of the `Anasazi::MultiVecTraits::CloneView` overload that takes `Teuchos::Range1D`, to be consistent with the overload that takes `std::vector`.
This does not actually affect the build, since the default implementation of `Anasazi::MultiVecTraits` intentionally cannot and should never be able to compile.  However, the default implementation documents the interface that traits class specializers must implement, so it is important to get right.
* Closes #2323
> Anasazi: Fix #2323

- doc/build_ref/TrilinosBuildReferenceTemplate.rst
- packages/kokkos/cmake/kokkos_settings.cmake
This fixes the problem with KOKKOS_ARCH described in #2230.
This is an update to Kokkos itself under Trilinos which gets shapshotted in to Trilinos.  But I will create a PR on the kokkos/kokkos git repo itself so that the snapshot does not overwrite this change.
> 2330 fix kokkos arch list

- packages/muelu/doc/Tutorial/src/xml/s6_export.xml
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
This reverts commit c8fee91b237732f38d8d87d6aa08691e535991d6.
The original fix was pre-mature. Since it cannot be fixed in reasonable time now, we better revert it.
* Closes #2260 
* Follows #2261 
```ctest``` passes locally on my machine.
> Revert "MueLu: printf data in xml-expert-mode (#2260)"

- packages/panzer/disc-fe/src/responses/Panzer_ResponseEvaluatorFactory_ExtremeValue.hpp
- packages/panzer/disc-fe/src/responses/Panzer_ResponseEvaluatorFactory_ExtremeValue_impl.hpp
- packages/panzer/disc-fe/src/responses/Panzer_ResponseEvaluatorFactory_Functional_impl.hpp
- packages/panzer/disc-fe/src/responses/Panzer_ResponseScatterEvaluator_ExtremeValue_impl.hpp
To help identify the response type on the evaluated field to help
prevent a bug when `Functional` and `ExtremeValue` responses are use at
the same time on the same field.
Before, a single node was shared and depending on the order the response
sublist for two types were added, the result would be different (correct
for the first response but wrong for the second one).
This should help fix that.
In Drekar, when using the `Functional` response type and `Max Value`/`Min Value` on the same field name, e.g `TEMPERATURE`, it turned out that the ordering mattered. Later, it was discovered that both response types just used the field name so they would just end up sharing the same node on the DAG.
- Here, the `Max Value`/`Min Value` response sublists are added first to compute …
> Panzer: add (optional) prefix to response field name

- packages/tpetra/doc/FAQ.txt
Add work-around for "Error 127" kokkos-kernels CUDA build link error to Tpetra's FAQ.
See Trilinos/packages/tpetra/doc/FAQ.txt.
This pull request ONLY affects Tpetra's documentation.
It does not touch source code files.
See the following GitHub issue:
https://github.com/trilinos/Trilinos/issues/2141
and the following detailed instructions:
https://tribits.org/doc/TribitsBuildReference.html#enabling-the-usage-of-resource-files-to-reduce-length-of-build-lines
Thanks to @bartlettroscoe for the instructions!
> Tpetra: Add "Error 127" CUDA build work-around to FAQ

- packages/tpetra/core/src/Tpetra_Import_Util2.hpp
- packages/tpetra/core/test/ImportExport2/CMakeLists.txt
- packages/tpetra/core/test/ImportExport2/ImportExport2_CrsSortingUtils.cpp
- packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
Specialization of `sortCrsEntries` and `sortAndMergeCrsEntries` that don't
sort/merge CRS values.  The procedures will be used by `Tpetra::CrsGraph::transferAndFillComplete`.
* Part of: #2267
Tpetra tests pass locally with GCC 6.4/openmpi 3.0
> Tpetra: Sort and merge specializations for Tpetra::CrsGraph

- packages/tpetra/core/example/Additive-Schwarz-Halo/AdditiveSchwarzHalo.cpp
- packages/tpetra/core/example/Additive-Schwarz-Halo/CMakeLists.txt
- packages/tpetra/core/example/CMakeLists.txt
This adds an additive Schwarz test to Tpetra
All tests done with Trilinos/sampleScripts/Sandia-SEMS/test_tpetra_sandia
```
Running on machine: shepard
Repository Status:  b91ac77ae4d4d0e0da116748a28146933d07c028 Tpetra: Adding an additive Schwarz test
Configure-Only: [ False ] Build-Only: [ False ] Report-To-CDash: [ False ]
Shepard
Calling: /ascldap/users/crtrott/Trilinos/sampleScripts/Sandia-SEMS/configure-testbeds-tpetra-jenkins &> configure.out
Calling: make -j 32 &> build.out
Calling: ctest &> test.out
*********************************
Build:
Warnings:  0
Errors:    0
Test:
Failed:    0
Timeout:   0
Not Run:   0
*********************************
Result: PASSED
*********************************
```
```
Running on machine: white
WARNING!! THE FOLLOWING CHANGES ARE …
```
> Tpetra: Adding an additive Schwarz test

- packages/phalanx/scripts/replacePhalanxEvaluatorMacros.py
Created a new Python script to replace the various Phalanx `Evaluator` macros with their contents.
DrekarBase#22 pointed out that Doxygen documentation wasn't being generated for classes created with the `PHX_EVALUATOR_CLASS` macro.  There is a way to tell Doxygen to expand all macros as it processes the code, but this was motivation to see how hard it would be to simply swap out all the macros with their respective contents.
The script was run on all `*.*pp` files in `DrekarBase`, and all the tests are still passing.
Closes #2322 
The `AT:  WIP` label is added just to tell @trilinos-autotester not to bother testing this PR.
> Phalanx:  Resolve "Replace PHX_EVALUATOR_CLASS Macros"

- packages/seacas/libraries/aprepro_lib/apr_scanner.cc
This really needs to be fixed in SEACAS proper but this is a quick workaround
that will get us going with Nina + CUDA for ATDM builds of Trilinos.
This addresses #2359.
> Remove '#line 1' as workaround for Ninja + CUDA rebuilds (#2359)

- packages/panzer/disc-fe/src/Panzer_Evaluator_DomainInterface.cpp
- packages/panzer/disc-fe/src/Panzer_Evaluator_DomainInterface.hpp
@rppawlo, would you please review this?
Added getDomain() to DomainEvaluator.  Made domain arguments and results have type of DomainType.
Some subclasses of panzer::Evaluator_WithBaseImpl which will use the new domain support need to be able to query the domain; that's why we need getDomain().  Changing from int to the enum type when there are domain arguments provides richer semantics, allowing the compiler to complain when mistakes are made.
> Changes to Panzer in support of domains.

- packages/tpetra/core/example/Finite-Element-Assembly/MeshDatabase.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.cpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.cpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.cpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.cpp
- packages/tpetra/core/example/Finite-Element-Assembly/typedefs.hpp
@mhoemmen 
Moving example code into functions to get rid of the error messages caused by the d'tor of `RCP<Tpetra::Map<...>>` being called after `Tpetra::finalize()`.  This was happening because they were both in the same scope.
Fixed by moving the actual tasks into an `execute()` function.
- We might break this up later but that's a different issue ;)
@mhoemmen created issue #2372 to add a message to the d'tor if it's called after `finalize()` has been called to improve clarity.
* Closes #2370
* Related to #2372
- Tested on local machine.
- Tested on White.
> Tpetra: FEM Assembly - move code into functions

- packages/kokkos/Makefile.kokkos
- packages/kokkos/core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp
- packages/kokkos/core/src/Kokkos_Array.hpp
- packages/kokkos/core/src/Kokkos_Macros.hpp
- packages/kokkos/core/src/Kokkos_MemoryPool.hpp
- packages/kokkos/core/src/Kokkos_Pair.hpp
- packages/kokkos/core/src/impl/Kokkos_TaskQueue.hpp
- packages/kokkos/core/src/impl/Kokkos_ViewTile.hpp
- packages/kokkos/core/unit_test/TestTaskScheduler.hpp
@etphipp 
@rppawlo 
@bathmatt 
@crtrott 
CUDA 9 emits an incorrect warning for
defaulted device functions.
This warning mislead Kokkos into marking
them wrong, causing code crashes.
This change introduces a workaround
(only under CUDA 9) which ensures correct
behavior and prevents warnings.
Makefile.kokkos will now add a warning
suppression flag to KOKKOS_CXX_FLAGS
when compiling with CUDA 9, so that Kokkos
users can do the right thing with defaulted
functions and not get warnings.
This means Trilinos users who use KOKKOS_ARCH
will have that flag automatically added
to their build.
Currently ShyLU/Tacho crashes because `Kokkos::MemoryPool` is marked wrong for CUDA, and Sacado code emits lots of warnings under CUDA 9. This change should fix both things. …
> Kokkos: fix defaulted functions with CUDA 9

- packages/kokkos-kernels/perf_test/batched/KokkosBatched_Test_LU_Cuda.cpp
Replace with KOKKOS_INLINE_FUNCTION following Kokkos changes in PR #2393
Necessary to prevent compilation errors when perf_tests are built
Replace KOKKOS_INLINE_FUNCTION_DEFAULTED with KOKKOS_INLINE_FUNCTION following PR #2393
#2393
> KokkosKernels: Replace KOKKOS_INLINE_FUNCTION_DEFAULTED

- packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp
**CC:** @trilinos/teuchos, @mhoemmen 
This PR branch improves the outputting of some of the Teuchos type conversion code unit tests and it fixes a problem with a safeAs() test on power8 systems.  This addresses issue #2407.
Now, building and running with:
```
./TeuchosCore_TypeConversions_UnitTest.exe --test=stringToReal --details=ALL
```
passes as shown below on two systems.
With this change, on my Linux machine crf450 the unit test output shows:
```
1. asSafe_stringToReal_UnitTest ... 
minLD = -1.19e+4932
minusOneLD = -1
maxLD = 1.19e+4932
...
sizeof_long_double = 16
sizeof_double = 8
max_exponent10_long_double = 4932
max_exponent10_double = 308
Testing converting from 'long double' to 'double' that does not fit ...
Test that code {valD = asSafe<double>(valToString(minLD));} throws …
```
> 2407 fix safe as check power8

- packages/tpetra/core/src/CMakeLists.txt
- packages/tpetra/core/src/Tpetra_Core.cpp
- packages/tpetra/core/src/Tpetra_Details_mpiIsInitialized.cpp
- packages/tpetra/core/src/Tpetra_Details_mpiIsInitialized.hpp
- packages/tpetra/core/src/Tpetra_Details_printOnce.cpp
- packages/tpetra/core/src/Tpetra_Details_printOnce.hpp
- packages/tpetra/core/src/Tpetra_Map_def.hpp
- packages/tpetra/core/test/CMakeLists.txt
- packages/tpetra/core/test/Core/CMakeLists.txt
- packages/tpetra/core/test/Core/initialize_tpetra_inits_kokkos.cpp
- packages/tpetra/core/test/Core/initialize_tpetra_inits_mpi.cpp
- packages/tpetra/core/test/Core/initialize_tpetra_inits_mpi_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_mpi.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_mpi_and_provides_comm.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_mpi_tpetra_inits_kokkos.cpp
- packages/tpetra/core/test/Map/CMakeLists.txt
- packages/tpetra/core/test/Map/Map_no_warn_on_pre_finalize_destruction.cpp
- packages/tpetra/core/test/Map/Map_warn_on_post_finalize_destruction.cpp
- packages/tpetra/core/test/Platform/issue_434_already_initialized.cpp
Make `Tpetra::Map`'s destructor print a useful warning, on Process 0 of the Map's communicator only, if users finalized Kokkos before Map's destructor was called.  This fixes #2372.  Also fix an issue with `Tpetra::initialize` when the user called `MPI_Init` before `Tpetra::initialize` was called.
This PR supersedes #2403 and #2412.
NOTE TO REVIEWERS: This looks like a lot to review, but most of the changes are new tests.  The tests declare the invariants for `Tpetra::initialize`, `Tpetra::finalize`, and `Tpetra::getDefaultComm`, with respect to MPI and Kokkos initialization and finalization.  Reading the tests will make those invariants clear.
See #2372 discussion.  Make error messages less cryptic and help users avoid incorrect behavior.
* Closes #2372 
I tested …
> Tpetra: Fix #2372

- commonTools/test/utilities/changedPackages.bash
Reenabling PR testing for Ifpack2, MueLu and Anasazi tests.
Adding top-level CMakeLists.txt file to the set of files to which changes cause all packages to build for PR testing.
The tests for Ifpack2, MueLu and Anasazi were disabled previously for pull-request testing, but now need to be reenabled prior to the full PR testing roll-out.
* Related to 
#2317, #2312, #1155
I previously tested reenabling the tests for PR testing for Ifpack2, MueLu, and Anasazi on my fork of Trilinos. I tested multiple times because the previous errors with Anasazi occurred only occasionally.
Also, I tested on my fork to ensure that the change to test the top-level CMakeLists.txt file also worked properly by submitting a dummy pull request with a white-space change to that file.
- [ x] My …
> Update changedPackages.bash to add additional package tests to PR testing

- packages/tpetra/core/example/Finite-Element-Assembly/CMakeLists.txt
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_Element.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_MeshDatabase.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_commandLineOpts.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_main.cpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_utility.hpp
Addressing requested updates to FEM Assembly from @mhoemmen from PR #2443.
- Algorithm Types (**one** is required):
- --with-insert-global-indices
- --with-local-element-loop
- --with-total-element-loop
- Static/Dynamic Profile Selector
- --with-StaticProfile (DEFAULT) 
- --with-DynamicProfile
rather than non-const version.
* Closes #2453 
* PR Testing
* GPU on White
* Local workstation
> Tpetra: Requested Updates to FEM Assembly

- packages/shylu/shylu_node/tacho/example/Tacho_ExamplePerfTest.cpp
- packages/shylu/shylu_node/tacho/src/Tacho_Util.hpp
serial space can be disabled and it causes a compile error. this pr fixes the problem.
> Shylu/Tacho - fix a problem due to disabled serial space

- cmake/std/BasicCiTestingSettings.cmake
**CC:** @trilinos/xpetra, @trilinos/muelu, @mhoemmen, @trilihos/framework
Since the ATDM APPs enable these, so should the CI and auto PR builds.  When
that changes, we can remove this.  This is one of the parts of #2462.
I tested this with:
```
$ ./checkin-test-sems.sh --enable-all-packages=on --local-do-all
```
and it passed the full CI build and I verified that experimental Xpetra and MueLu code are enabled.  See details below.
<details>
<summary>
<b>DETAILS</b> (chick to expand)
</summary>
I tested this branch locally with:
```
$ ./checkin-test-sems.sh --enable-all-packages=on --local-do-all
```
```
passed: Trilinos/MPI_RELEASE_DEBUG_SHARED_PT: passed=2587,notpassed=0
Tue Mar 27 22:04:18 MDT 2018
Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota Enabled …
```
> Enable Xpetra and MueLu Experimental in standard CI build (#2317, #2462)

- packages/teko/tests/unit_tests/tDiagonallyScaledPreconditioner.cpp
CC: @trilinos/teko 
This small increase in the error tolerance allows the
tDiagonallyScaledPreconditioner_application_test_row_tpetra_UnitTest unit test
to pass on the ATDM build Trilinos-atdm-hansen-shiller-gnu-opt-serial.  See #2475.
> Loose error tol from 5e-14 to 5.5e-14 for gnu-opt-serial on hansen/shiller (#2475)

- packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
@trilinos/Tpetra
This PR fixes the implementation of Tpetra::Details::MultiVectorCloner
The method 'clone' had a compiler error. Since it was never used (in the whole library), it went under the radar.
This fixes issue #2470 
* Closes #2470 
I added a unit test inside `MultiVector_UnitTests.cpp`
> Tpetra: Fixed bug in MultiVectorCloner and added a unit test for the cloner.

- packages/teuchos/comm/test/Time/CMakeLists.txt
- packages/teuchos/comm/test/Time/TimeMonitor_UnitTests.cpp
CC: @trilinos/teuchos 
This addresses #2487 and actually fixes the test on a bunch of platforms.  For more details, see https://github.com/trilinos/Trilinos/issues/2487#issuecomment-377648679 and the commit message logs.  It should be pretty clear from that.
> 2487 fix timemonitor unittests mpi 3

- packages/kokkos/core/unit_test/TestTeamVector.hpp
Disable instances of a test which request a hardcoded number of
32 CUDA threads per warp, because with debugging
enabled the CUDA kernel uses too many registers
and can only run on 16 threads per warp max.
This test is failing in key ATDM build configurations
kokkos/kokkos#1514, kokkos/kokkos#1513, #2471
> Kokkos: disable failing CUDA+DEBUG test

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_decl.hpp
- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
Using KokkosKernels sparse matrix addition kernels in
TpetraExt::MatrixMatrix::add(). Removed the now redundant
copies of these kernels in Tpetra.
> Tpetra: use KokkosKernels addition (and remove redundant copies of these kernels in Tpetra)

- cmake/std/atdm/ride/tweaks/CUDA-DEBUG-CUDA.cmake
- cmake/std/atdm/ride/tweaks/GNU-DEBUG-OPENMP.cmake
These tests randomly fail with massive diffs.  Very strange behavior.  See #2473 for history and more details.
> Disable 3 Anasazi tests that randomly fail in debug builds on white/ride (#2473)

- packages/ifpack/src/Ifpack_METISPartitioner.cpp
METIS_EstimateMemory is deprecated (and removed) in METIS 5.x.
Manual: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/manual.pdf (see Table 2)
> Ifpack: Remove redundant METIS_EstimateMemory call

- packages/tpetra/core/test/inout/ReadTriples.cpp
Fix Tpetra test build by avoiding use of `long long` when `Teuchos_ENABLE_LONG_LONG_INT` is `OFF`.  The latter should never be `OFF` anyway, since Teuchos now requires C++11 and `long long` comes with C++11, but some users have that option `OFF` in their scripts for legacy reasons.  It takes less time to fix the build issue than to tell several users to read the configure script output.
* Closes #2498 
* Related to #2495 #2496 
I set `Teuchos_ENABLE_LONG_LONG_INT:BOOL=OFF`, enabled OpenMP, and disabled Serial (in both Kokkos and Tpetra).  I then tested with GCC 4.9.3 in both debug and release modes (dynamic shared libraries and ETI enabled for both).
> Tpetra: Fix #2498

- packages/muelu/src/Misc/MueLu_StructuredLineDetectionFactory_decl.hpp
- packages/muelu/src/Misc/MueLu_StructuredLineDetectionFactory_def.hpp
This change removes a dependency on coordinates which is not required since
in the structured case we only care about the "ijk" layout, not the actual
coordinates...
This small change was made during some further testing of the structured line detection algorithm for the case of uncoupled structured aggregation.
removing unnecessary dependency will make it easier for application to use this algorithm.
There are already test in MueLu for this feature and they are passing.
> MueLu: small change to structured line detection algorithm

- packages/sacado/src/Sacado_DynamicArrayTraits.hpp
There have been build failures for Sacado with Cuda on showing up on the
dashboard, e.g.,
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3483315
where Kokkos::shfl_*() functions aren't being found.  I can't reproduce
this on my machine, so I am trying to see if adding an explicit include
for the Kokkos header that defines them fixes it.
> Sacado:  Add explicit include for Cuda/Vectorization.hpp

- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector_impl.hpp
Updated Panzer's `Integrator_CurlBasisDotVector` `Evaluator` such that it can `CONTRIBUTE` to some other `Evaluator`.  Compile time argument checking is enforced through the main constructor, but backward compatibility is maintained via a `ParameterList` constructor that defaults to the `EVALUATES` style and delegates to the main constructor.
This should allow us to refactor things such that these `Evaluator`s contribute the result of the integration to some other `Evaluator`, rather than storing the result such that it'll later be used in a `Sum`, for instance.
* Closes #1890
Passes Panzer/Drekar/Charon tests on my RHEL7 machine.  Passes Panzer tests on ride/cuda/opt (didn't test Drekar/Charon there).
> Resolve "Panzer:  Update Integrator_CurlBasisDotVector"

- packages/panzer/adapters-stk/example/CurlLaplacianExample/Example_CurlLaplacianEquationSet_impl.hpp
- packages/panzer/adapters-stk/example/MixedPoissonExample/Example_MixedPoissonEquationSet_impl.hpp
- packages/panzer/adapters-stk/example/PoissonExample/Example_PoissonEquationSet_impl.hpp
- packages/panzer/adapters-stk/example/PoissonInterfaceExample/Example_PoissonEquationSet_impl.hpp
- packages/panzer/adapters-stk/tutorial/siamCse17/myEquationSetImpl.hpp
- packages/panzer/adapters-stk/tutorial/step01/Step01_EquationSet_Projection_impl.hpp
- packages/panzer/adapters-stk/tutorial/step02/Step02_EquationSet_Projection_impl.hpp
- packages/panzer/disc-fe/src/Panzer_EquationSet_DefaultImpl_decl.hpp
- packages/panzer/disc-fe/src/Panzer_EquationSet_DefaultImpl_impl.hpp
- packages/panzer/disc-fe/test/equation_set/user_app_EquationSet_Energy_impl.hpp
- packages/panzer/disc-fe/test/equation_set/user_app_EquationSet_MeshCoords_impl.hpp
- packages/panzer/disc-fe/test/ugi_rig/user_app_EquationSet_Energy_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell_impl.hpp
`Evaluator` was misspelled in `buildAndRegisterResidualSummationEvalautor`.
> Panzer:  Typo Fix

- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Change how an ArrayView of an ArrayRCP is created in multijagged
migration.  For whatever reason, the previous way it was being
built was causing a MueLu unit test to fail.  See issue #2536.
The Zoltan2 and MueLu unit tests pass locally with this change.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/2537)
> Zoltan2: MJ migration: fix ArrayView construction

- packages/panzer/adapters-stk/example/CurlLaplacianExample/Example_ClosureModel_Factory_impl.hpp
- packages/panzer/adapters-stk/example/CurlLaplacianExample/Example_CurlLaplacianEquationSet_impl.hpp
- packages/panzer/adapters-stk/example/MixedPoissonExample/Example_ClosureModel_Factory_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell_impl.hpp
This switches all uses of `panzer::Integrator_CurlBasisDotVector` from the `EVALUATES` style (which is the default when using the `ParameterList` constructor) to the `CONTRIBUTES` style.
We'll save the memory that was previously needed to store the result of the integral before summing it into another `Evaluator`.
* Closes #2527 
* Follows #1890 
* Part of #1575 
Passes `ctest` on my RHEL7 machine.
> Resolves "Panzer:  Use CONTRIBUTES-Style Integrator_CurlBasisDotVector"

- packages/panzer/adapters-ioss/src/Panzer_IOSSConnManager_impl.hpp
- packages/panzer/adapters-stk/src/Panzer_STKConnManager_impl.hpp
- packages/panzer/adapters-stk/src/Panzer_STK_ParameterListCallbackBlocked_impl.hpp
- packages/panzer/adapters-stk/src/Panzer_STK_ParameterListCallback_impl.hpp
- packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory_impl.hpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
Remove compiler warnings:
* Unused variable (looked like a copy/paste error).
* Switch statement fallthrough was intentional but wasn't marked as such.
In order to ensure that new changes don't add compiler warnings, we need to try our best to keep Panzer building warning-free.
Passes `ctest` on my RHEL7 machine.
> Panzer:  Fix Compiler Warnings

- packages/sacado/src/Sacado_ScalarFlopCounter.cpp
Remove break statements that immediately follow return statements.
These were generating warnings in a CUDA 8 build with GCC 5.4.0
> Sacado: remove unreachable break statements

- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestAmesos2solver.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp
Fix Ifpack2::BlockRelaxation's test instantiations for the case when `GlobalOrdinal=int` is disabled.
See comment here:
https://github.com/trilinos/Trilinos/pull/2515#issuecomment-379865709
* Related to #74, #2548
> Ifpack2: Fix #2520

- packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp
- packages/teuchos/parameterlist/test/yaml/YamlParameterList.cpp
This keeps the top-level name given
to a ParameterList in the input YAML
file throughout the update process,
and eventually writes it to an output
YAML file if that is the workflow.
Right now if users read in a YAML file like:
```yaml
Albany:
some param: 5
```
The resulting ParameterList is called `ANONYMOUS` instead of `Albany`, so if the PL is written to file it becomes:
```yaml
ANONYMOUS:
some param: 5
```
These changes preserve the name throughout the process.
> Teuchos: preserve name of PL during update

- packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
- packages/ifpack2/src/Ifpack2_LinePartitioner_decl.hpp
- packages/ifpack2/src/Ifpack2_LinePartitioner_def.hpp
- packages/muelu/test/scaling/sa_with_Ifpack2_line_detection.xml
This pull request is fixing a templating issue for the multivector of coordinates passed to Ifpack2 when the line partitioner is being used.
This will allow MueLu users to access the line detection algorithm implemented for Block Relaxation in Ifpack2. This is useful as a smoother in certain situations. 
* Closes #2551 
* Follows #2520 #2523 
A unite test in MueLu is using this capability and now passes for both double and std::complex<double>
> Ifpack2 coordinates scalar template

- packages/panzer/adapters-stk/example/MixedPoissonExample/Example_MixedPoissonEquationSet_impl.hpp
- packages/panzer/adapters-stk/example/PoissonExample/Example_PoissonEquationSet_impl.hpp
- packages/panzer/adapters-stk/example/PoissonInterfaceExample/Example_BCStrategy_Interface_NeumannMatch_impl.hpp
- packages/panzer/adapters-stk/example/PoissonInterfaceExample/Example_BCStrategy_Interface_WeakDirichletMatch_impl.hpp
- packages/panzer/adapters-stk/example/PoissonInterfaceExample/Example_BCStrategy_Neumann_Constant_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar_impl.hpp
- packages/panzer/disc-fe/test/equation_set/user_app_EquationSet_Energy_impl.hpp
- packages/panzer/disc-fe/test/equation_set/user_app_EquationSet_MeshCoords_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_MassMatrix_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_WeakGradient_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell_impl.hpp
Analogous to #2527.  `Integrator_BasisTimesScalar` was refactored as part of #1575.  This changes any uses of the class to use the new compile-time checked constructor, and anywhere possible the objects were switched from the `EVALUATES` to the `CONTRIBUTES` style.
Decreased memory usage.
* Related to #2535, #2526, #2527
* Part of #1575 
`ctest` "passes" on my RHEL7 machine.  There are a number of Drekar failures, but they were present on `develop` as well, so they probably don't have anything to do with these changes.
> Panzer:  Use CONTRIBUTES-Style Integrator_BasisTimesScalar

- cmake/ProjectCompilerPostConfig.cmake
Disable Kokkos profiling when the TPL `DLlib` is disabled.
Kokkos profiling requires `DLlib`, currently if one disables `DLlib` then there are link failures in Kokkos because profiling remains enabled.
* Closes kokkos/kokkos#1422
Tested in a custom build that `-DTPL_ENABLE_DLlib:BOOL=OFF` causes Kokkos profiling to be disabled.
> Kokkos disable profiling if DLlib is disabled

- packages/tpetra/core/src/CMakeLists.txt
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsGraph.cpp
- packages/tpetra/core/src/Tpetra_Details_packCrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine.cpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
- packages/tpetra/core/test/CrsGraph/CMakeLists.txt
- packages/tpetra/core/test/CrsGraph/CrsGraph_PackUnpack.cpp
- packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
CrsGraph::transferAndFillComplete is new, independent code.  However, there were
some function name clashes in packCrsMatrix and packCrsGraph.  So, I moved implementation
details of each to a new namespace so that they could have consistent naming.  The
same goes for unpackAndCombineCrsMatrix and unpackAndCombineCrsGraph.
* Part of #2267 
Tpetra tests pass with GCC 6.4, openmpi 3.0.0, openmp
> Tpetra: Implementation of CrsGraph::transferAndFillComplete

- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Import_Util2.hpp
Albany builds (compiled without ETI) exposed some circular dependencies
associated with `Tpetra_Import_Util2.hpp` that surfaced with 47e569d.
My previous local testing did not show the failure.  On completely wiping my
build directory and using some Albany configure files, I was able to reproduce
the build error.
The fix involved removing an include of Tpetra_CrsMatrix_decl.hpp
and Tpetra_CrsMatrix.hpp from Tpetra_Import_Util2.hpp and then cleaning up some
downstream code that inadvertently included `Tpetra_CrsMatrix.hpp` through
`Tpetra_Import_Util2.hpp`.
Related to: #2574, 47e569d
> Tpetra: Fix for #2574

- cmake/RepositoryDependenciesSetup.cmake
CC: @trilinos/shylu
This also results in a hard failure if ShyLU_NodeTacho is explicitly enabled
but RDC is not enabled.  This just moved the configure error up earlier.
This also helps get us closer to #2464.
This addresses #2580.
> Disable ShyLU_NodeTacho when RDC is not enabled with CUDA (#2580)

- packages/teuchos/parser/src/Teuchos_MathExpr.cpp
- packages/teuchos/parser/src/Teuchos_MathExpr.hpp
- packages/teuchos/parser/test/unit_tests.cpp
Add a function to return all symbols in a MathExpr string, including those that are only acted on by the call operator.
Previously, symbols which were only acted on by the call operator were not retrievable, and users need a way to get them too.
> Teuchos: allow getting all MathExpr symbols

- cmake/std/atdm/ride/tweaks/CUDA-DEBUG-CUDA.cmake
- cmake/std/atdm/ride/tweaks/GNU-DEBUG-OPENMP.cmake
**CC:** @fryeguy52, @trilinos/anasazi 
This reverts commit 2e9da0c931e8c11c60d194e8a64d13e6e8697213, reversing
changes made to c828f5ad7f9ccef1d148839aaf65d6236ca172d5.
The merge branch in PR #2517 should allow these tests to pass now.
This should resolve #2473.  We will just need to to observe these tests passing.
Note that this just impacts the tests that run in the ATDM Trilinos builds and does not impact any actual code in Trilinos at all or any of the auto PR builds.
I tested this on white with:
```
$ bsub -x -I -q rhel7F -n 16 \
./checkin-test-atdm.sh cuda-debug gnu-debug-openmp \
--enable-all-packages=off --no-enable-fwd-packages \
--enable-packages=Anasazi --local-do-all
...
PASSED (NOT READY TO PUSH): Trilinos: white24
Mon Apr 23 11:55:40 MDT 2018
Enabled Packages: Anasazi
Build …
```
> Revert "Merge pull request #2501 from bartlettroscoe/2473-disable-random-failing-anasazi-tests" (#2473)

- cmake/load_sems_dev_env.sh
@trilinos/framework, @fryeguy52 
It was requested that we use GCC 4.9.3 headers instead of GCC 4.8.4 headers with Intel 17.0.1 builds of
Trilinos (see #2317 and #2463).
I tested it locally.
> Use GCC 4.9.3 headers with Intel 17.0.1 (#2463, #2317)

- cmake/std/atdm/rhel6/environment.sh
**CC:** @trilinos/nox, @fryeguy52 
This solved the timeouts for the NOX test suite (#2628) for me on ceerws1113.
Before this change, on ceerws1113, when I ran:
```
$ ./checkin-test-atdm.sh gnu-opt-openmp \
--enable-all-packages=off --no-enable-fwd-packages \
--enable-packages=NOX --local-do-all
```
it produced the ctest output:
```
93% tests passed, 7 tests failed out of 105
Label Time Summary:
NOX    = 7002.16 sec (105 tests)
Total Test time (real) = 1050.16 sec
The following tests FAILED:
71 - NOX_LOCA_TcubedTP_MPI_2 (Timeout)
72 - NOX_LOCA_TcubedTP_stratimikos_MPI_2 (Timeout)
77 - NOX_LOCA_BrusselatorHopf_MPI_2 (Timeout)
80 - NOX_LOCA_BrussXYZT_Sequential_MPI_2 (Timeout)
81 - NOX_LOCA_BrussXYZT_SequentialIPS_MPI_2 (Timeout)
82 - NOX_LOCA_BrussXYZT_SequentialOPS_MPI_2 (Timeout)
84 - …
```
> Don't bind MPI Ranks to process to solve OpenMP timeouts (#2628)

- cmake/ctest/drivers/gaia/single_ci_iter.sh
- cmake/ctest/drivers/gaia/trilinos_ci_sever.sh
I modified the gaia-specific scripts `single_ci_iter.sh` and `trilinos_ci_sever.sh` so that they would run on Gaia. There was an issue with the `readlink` command not supporting `-f` and not producing required output. My solution might be overly simplistic.
This is the next step in getting Gaia set up as a CI server
* Part of #891
> PyTrilinos: Set up CI scripts to run on Gaia

- cmake/std/PullRequestLinuxDriver.sh
- cmake/std/PullRequestLinuxIntelTestingSettings.cmake
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
Note that this will not yet enable the intel build as
the autotester does not yet have the configuration. It
just provides the files needed.
* Part of issue #2463
I set up an autotesterinstance pointed at my fork and created a PR from this branch to develop on my fork.  The results can be seen at https://github.com/prwolfe/Trilinos/pull/2 and https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-2-test&field2=buildstarttime&compare2=84&value2=NOW
> New Driver script and intel config file for PR testing

- packages/kokkos-kernels/src/sparse/KokkosSparse_CrsMatrix.hpp
- packages/kokkos/containers/src/Kokkos_StaticCrsGraph.hpp
These are chagnes to support a view of crs matrices on cuda. The same changes have already been accepted into the kokkos and kokkos-kernels repositories. So any new snapshop will retain these changes. We need them added before the next kokkos sync to support work in panzer.
> Kokkos/Kokkos-Kernels: support view of crs matrices on cuda

- cmake/std/atdm/README.md
**CC:** @fryeguy52, @eric-c-cyr 
Add troubling shooting section and fixing some other problems with cmake/std/atdm/README.md file
A user ran into a problem with their ~/.gitconfig file and the version of git loaded by Trilinos/cmake/std/atdm/load-env.sh (see #2652).  I added this section to try to address that problem for future users.
I viewed the rendered Markdown on GitHub on my branch.
> Add troubleshooting section and warning about git versions and ~/.gitconfig files

- packages/stokhos/src/CMakeLists.txt
- packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits.hpp
- packages/stokhos/test/UnitTest/CMakeLists.txt
- packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest_MaskTraits.cpp
@etphipp 
Add Mask class for ensemble type class. 
The class allows masked operations on ensemble values and allows boolean reduction such as AND, OR, and XOR.
The pull request includes a UnitTest cpp file that tests the functionalities of the class.
It allows the writing of comparisons for ensemble type in a way which is consistent with usual scalar types.
It allows the writing of if-else statement based on masked operations such that it is still consistent with usual scalar types. 
None
It has been tested using Teuchos UnitTest and
```
ctest -R Stokhos_SacadoMPVectorUnitTestMaskTraits_MPI_1
Test project /Users/kimliegeois/dev/TrilinosB
Start 49: Stokhos_SacadoMPVectorUnitTestMaskTraits_MPI_1
1/1 Test #49: Stokhos_SacadoMPVectorUnitTestMaskTraits_MPI_1 ...   Passed …
```
> Stokhos: Add Stokhos_MP_Vector_MaskTraits.hpp and its UnitTest

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Remove call to getGlobalNumDiags in CrsMatrix::describe
Related to: #2630
Removed call to getGlobalNumDiags in CrsMatrix::describe
Remove deprecated code warnings
Tpetra tests run/passed locally with gcc 7.2.0, openmpi 3.0.0.
> Tpetra: Remove call to getGlobalNumDiags in CrsMatrix::describe

- cmake/std/atdm/ride/environment.sh
**CC:** @trilinos/belos , @trilinos/anasazi, @etphipp
This appears to fix almost all of the failing Belos and Anaszzi tests on 'white' (see #2454 2454)
I tested this one 'white' using:
```
$ cd ~/Trilinos.base/BUILD/WHITE/CHECKIN/
$  bsub -x -I -q rhel7F -n 16 \
./checkin-test-atdm.sh all --enable-packages=Belos,Anasazi --local-do-all
```
This returned:
```
1) gnu-debug-openmp => passed: passed=145,notpassed=0 (4.31 min)
2) gnu-opt-openmp => passed: passed=146,notpassed=0 (6.30 min)
3) cuda-debug => passed: passed=145,notpassed=0 (10.72 min)
4) cuda-opt => FAILED: passed=145,notpassed=1 => Not ready to push! (13.36 min) …
```
> Use netlib BLAS and LAPACK instead of OpenBLAS 1.2.19 on white/ride (#2454)

- cmake/ProjectCompilerPostConfig.cmake
Move "-x cuda" and friends
over to add_compile_options() instead of
CMAKE_CXX_FLAGS.
The flag "-x cuda" will break linkage if passed to the linker, and the
other one will cause warnings.
This happens if one tries to compile Trilinos in CUDA mode using Clang's
built-in CUDA compilation.
A custom Clang-CUDA build of Kokkos and Teuchos passes tests.
> Framework: handle special Clang CUDA flags

- packages/belos/src/BelosBiCGStabSolMgr.hpp
- packages/belos/src/BelosBlockCGSolMgr.hpp
- packages/belos/src/BelosBlockGmresSolMgr.hpp
- packages/belos/src/BelosFixedPointSolMgr.hpp
- packages/belos/src/BelosGCRODRSolMgr.hpp
- packages/belos/src/BelosGmresPolySolMgr.hpp
- packages/belos/src/BelosPCPGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp
- packages/belos/src/BelosPseudoBlockStochasticCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockTFQMRSolMgr.hpp
- packages/belos/src/BelosRCGSolMgr.hpp
- packages/belos/src/BelosTFQMRSolMgr.hpp
Change all belos solver manager defaults from static const to static constexpr.
This prepares for PR #2483 to avoid static initialization order conflicts.
The purpose of these changes is to prepare for premain
registration for the new DII system. The statics were
causing some initialization order issues that could
sometimes seg fault the managers when they were constructed.
Some older clang versions fail on the linkage of
the constexpr when calling the set method for ParameterList.
Using a static_cast seems to work around this though
the cast is simply assignining the constexpr to their
original type. I'm anticipating that would be removed eventually.
Using c++17 resolves this.
Note this PR is being used to test #2483 now and seems to
resolve all the static linkage issues …
> Belos: Change all default parameters to be constexpr (#2483)

- packages/muelu/test/unit_tests/BlockedRepartition.cpp
This commit provides a simple fix to the error in the BlockedRepartition
unit test when std::complex is on. This should remove the last error on the
dashboard related to PR #2561 
Simple cast of value in parameter list from `double` to `SC` ensuring proper type for `std::complex` builds
This fixes a failing test
* Closes #2664 
The test suite of `MueLu` was run with `-D Trilinos_ENABLE_COMPLEX:BOOL=ON` to make sure that the test now passes for complex builds
> MueLu: fix #2664 for std::complex using a cast in parameter list

- cmake/std/atdm/toss3/environment.sh
Provides a more verbose error message when you select a non-supported compiler for the `toss3` system.  For example:
```
. cmake/std/atdm/load-env.sh gnu
Hostname 'serrano-login2' matches known ATDM host 'serrano' and system 'toss3'
ATDM_CONFIG_TRILNOS_DIR = /home/rabartl/Trilinos.base/Trilinos
Setting default compiler and build options for JOB_NAME='gnu'
Using chama compiler stack GNU to build DEBUG code with Kokkos node type SERIAL
***
*** ERROR: COMPILER=GNU is not supported on this system!
***
***
*** ERROR: Environment setup was not successful, see above errors!
***
````
Hopefully this will help users see the problem sooner.
> Provide better error message when compiler is not supported (TRIL-200)

- packages/muelu/test/unit_tests/BlockedRepartition.cpp
@csiefer2 @jhux2 
In unit test BlockedRAPFactoryWithDiagonal a multivector holding coordinates is created as RCP<MultiVector>, this has been modified to RCP<MultiVector<double,LO,GO,NO> > in order to avoid bad cast when the multivector is extracted from MueLu levels.
We need to fix this unit test.
* Closes 2664
I configured locally on of the builds that fails on the dashboard, compiled and ran the MueLu unit tests. They all passed including `BlockedRAPFactoryWithDiagonal`
> MueLu: fix 2664 by using appropriate type for coordinate multi-vector

- packages/tempus/src/Tempus_AdjointSensitivityModelEvaluator_decl.hpp
- packages/tempus/src/Tempus_SolutionState_impl.hpp
- packages/tempus/src/Tempus_TimeDerivative.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyIntegralController.hpp
- packages/tempus/src/Thyra_AdjointLinearOpWithSolveFactory.hpp
- packages/tempus/src/Thyra_AdjointPreconditioner.hpp
- packages/tempus/src/Thyra_AdjointPreconditionerFactory.hpp
- packages/tempus/src/Thyra_BlockedTriangularLinearOpWithSolveFactory.hpp
- packages/tempus/src/Thyra_MultiVectorLinearOp.hpp
- packages/tempus/src/Thyra_MultiVectorLinearOpWithSolveFactory.hpp
- packages/tempus/src/Thyra_MultiVectorPreconditioner.hpp
- packages/tempus/src/Thyra_MultiVectorPreconditionerFactory.hpp
- packages/tempus/src/Thyra_ReuseLinearOpWithSolveFactory.hpp
- packages/tempus/src/Thyra_ReusePreconditionerFactory.hpp
- packages/tempus/src/Thyra_ScaledIdentityLinearOpWithSolve.hpp
- packages/tempus/src/Thyra_ScaledIdentityLinearOpWithSolveFactory.hpp
Deal with a number of Tempus doxygen warnings:
*  Equation errors.
*  End of list marker without any list.
*  Disconnects between _decl and _impl files.
*  Etc.
Email from @ccober6:
> Hi all,
> 
> I have doxygen warnings that I can not track down, and wondered if you had any thoughts.  I get many of the following type warnings:
> 
> /Users/ccober/myOffice/Trilinos/packages/tempus/src/Thyra_AdjointLinearOpWithSolveFactory.hpp:88: warning: End of list marker found without any preceding list items
> 
> Here is what I know so far
>  * They only occur in Thyra_* files (Thats why I am asking Eric about this.)
>  * They occur on /** \brief . */
>  * Adding a short text to the brief fixes it.
>  * Removing the dot “.” fixes it.
>  * A dot “.” ends the brief.
> 
> Is this "brief …
> Tempus:  Fix Doxygen

- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-debug-openmp-panzer.sh
- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-debug-openmp.sh
- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-opt-openmp-panzer.sh
- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-opt-openmp.sh
- cmake/ctest/drivers/atdm/toss3/local-driver.sh
- cmake/std/atdm/README.md
- cmake/std/atdm/toss3/environment.sh
**CC:** @fryeguy52 
This appears to mostly fix the problems with running tests on 'serrano' as reported in #2699.  I changed the arguments passed to `mpiexec` and I changed from `srun` to `salloc`.   I basically followed the guidelines at:
* https://computing.sandia.gov/platforms/cts1/submitting_jobs
exactly as stated.
I ran the Jenkins driver locally for Panzer and it produced:
```
100% tests passed, 0 tests failed out of 156
Label Time Summary:
Panzer    = 1257.04 sec*proc (156 tests)
Total Test time (real) = 162.90 sec
Panzer: File '' does NOT exist so all tests passed!
Panzer: Skipping running memory checking tests due to CTEST_DO_MEMORY_TESTING='FALSE'!
Done with the incremental building and testing of Trilinos packages!
TRIBITS_CTEST_DRIVER_ERROR_QUEUE is empty. All is well.
See …
```
> Fix running of tests on 'serrano' for ATDM Trilinos builds

- cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake
**CC:* @trilinos/teko, @eric-c-cyr 
This makes the remaining unit tests in the test `Teko_testdriver_tpetra_MPI_1`
pass.  This addresses #2712. This is the same "fix" as for issue #2652 which
was for GCC 6.1.0.
I tested this locally as described in the "Steps to Reproduce" in #2712.
The full output from the passing tests after the commit is shown below.
<details>
<summary>
<b>Teko_testdriver_tpetra_MPI_1 passing tests output:</b> (click to expand)
</summary>
````
Kokkos::OpenMP::initialize WARNING: OMP_PROC_BIND environment variable not set
In general, for best performance with OpenMP 4.0 or better set OMP_PROC_BIND=spread and OMP_PLACES=threads
For best performance with OpenMP 3.1 set OMP_PROC_BIND=true
For unit testing set OMP_PROC_BIND=false …
```
> Set Teko_DISABLE_LSCSTABALIZED_TPETRA_ALPAH_INV_D=TRUE for GCC 4.8.4 + OpenMP build (#2712)

- cmake/std/atdm/toss3/environment.sh
CC: @fryeguy52, @jmgate 
The instructions on the 'serrano' support page say that these arguments should
go before the -np argument, not after the --n arugment.  I am hoping this will fix
some of the failures we are seeing as described in #2699.
Also, I changed the -np argument to --n to match exactly what the 'serrano'
support page says to do.
On serrano, I ran:
```
$ ./checkin-test-atdm.sh intel-opt-openmp --enable-packages=Rythmos,MueLu --configure --build
$ salloc -N1 --time=00:20:00 --account=fy150090 \
./checkin-test-atdm.sh intel-opt-openmp --enable-packages=Rythmos,MueLu --test
```
That returned:
```
PASSED (NOT READY TO PUSH): Trilinos: serrano-login5
Thu May 10 17:30:21 MDT 2018
Enabled Packages: Rythmos, MueLu
0) …
```
> Move the mpiexec args before -np not after (#2699)

- cmake/std/atdm/README.md
- cmake/std/atdm/checkin-test-atdm.sh
- cmake/std/atdm/rhel6/environment.sh
See the commits log messages.  Good stuff.
Locally on crf450 I ran:
```
$ ./checkin-test-atdm.sh gnu-opt-openmp --enable-packages=Teuchos --local-do-all
```
and it returned
```
PASSED (NOT READY TO PUSH): Trilinos: crf450.srn.sandia.gov
Thu May 10 16:55:41 MDT 2018
Enabled Packages: Teuchos
1) gnu-opt-openmp => passed: passed=131,notpassed=0 (0.92 min)
```
> Use cmake 3.11 1 and ninja for RHEL ATDM Trilinos build

- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-debug-panzer.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-debug.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-opt-panzer.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-gnu-debug-openmp-panzer.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-gnu-opt-openmp-panzer.sh
Some random module failures on 'ride' require that we demote all of these
builds on 'ride' back to the "Specialized" CDash Track/Group so that they will
not spam Trilinos developers (and me) with CDash error emails.
By putting in an 'if' statement, I allow the Jenkins drivers on 'ride' to set:
export Trilinos_TRACK=Specialized
but the builds on 'white' can still submit to the "ATDM" CDash Track/Group.
See:
* https://software-sandbox.sandia.gov/jira/browse/TRIL-208
> Allow previously "ATDM" promoted builds on 'ride' to be demoted (TRIL-208)

- packages/tpetra/core/src/Tpetra_Details_makeOptimizedColMap.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
- packages/tpetra/core/test/ImportExport/CMakeLists.txt
- packages/tpetra/core/test/ImportExport/Issue_2198.cpp
* Fix #2564 (split #2198 test so at least some of it always runs, even though some of it requires 5 MPI processes)
* Fix #2753 (makeOptimizedColMap and makeOptimizedColMapAndImport)
@trilinos/tpetra @alanw0 
* Closes #2564, #2753 
Locally, on my workstation.
> Tpetra: Fix #2564 and #2753

- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-debug-openmp-panzer.sh
- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-opt-openmp-panzer.sh
- cmake/std/atdm/README.md
- cmake/std/atdm/toss3/environment.sh
- cmake/std/atdm/toss3/tweaks/INTEL-DEBUG-OPENMP.cmake
This PR contains several fix-ups for the builds on 'serrano'.  See the set of commits for what the changes are.  There are good descriptions in the log messages in those.
However, the big things are:
* Disable the Panzer test `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3` for intel-debug-openmp builds (#2751, commit 652a011)
* Try to fix failing tests by setting `KOKKOS_ARCH=BDW` (1a271e5) and switch to `mpiexec --bind-by socket` (e1944ed)  (#2699)
* Enabled the usage of Ninja (297cf26)
* Related to: #2751, #2699 
I tested this locally on 'serrano' using:
```
$ ./checkin-test-atdm.sh intel-opt-openmp \
--enable-packages=Kokkos,Panzer --allow-no-pull --configure --build --send-email-to=
$ salloc -N1 --time=0:20:00 --account=fy150090 \ …
```
> Tril 200 serrano fixups

- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrixSolveOp.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_RowGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_RowMatrix_decl.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp
- packages/tpetra/core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp
* Per #2630, deprecate isLowerTriangular and isUpperTriangular
* Per #581, deprecate CrsMatrixSolveOp and remove all `CrsMatrix::localSolve` calls from Tpetra's tests
* Remove spurious deprecation warnings due to #2630 deprecations, for when CrsMatrix's and BlockCrsMatrix's deprecated methods call CrsGraph's deprecated methods
* Part of #581, #2630
> Tpetra: Deprecate is{Lower,Upper}Triangular per #2630; deprecate CrsMatrixSolveOp per #581; remove spurious warnings

- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-debug-openmp-panzer.sh
CC: @fryeguy52, @jmgate 
This build was 100% passing today on 'serrano' as shown at:
* https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=3525281
and therefore is being promoted to the "ATDM" CDash Track/Group.
> Promote 100% passing Trilinos-atdm-toss3-intel-debug-openmp-panzer build (TRIL-200)

- packages/epetra/src/Epetra_CrsGraph.cpp
- packages/epetra/src/Epetra_CrsMatrix.cpp
- packages/epetra/src/Epetra_Export.cpp
- packages/epetra/src/Epetra_FECrsGraph.cpp
- packages/epetra/src/Epetra_FECrsMatrix.cpp
- packages/epetra/src/Epetra_Import.cpp
These were caught by GLIBCXX's debug mode and the deal.II test suite.
Writing `&v[0]` when `v` is an empty `std::vector` is not permissible when running GCC in debug mode. Using `v.data()` provides the same result and avoids the issue. If I have understood the documentation correctly, Epetra requires C++11 so change should be okay. This fixes a lot of test failures in deal.II (with GCC debugging) where, for various reasons, our multigrid code deals with empty Epetra objects.
I ran the test suite on my workstation (albeit without all packages installed) with this patch and all tests passed.
See also dealii/dealii#6622.
> Epetra: Use v.data() instead of &v[0].

- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
This guard makes sure that MueLu_Epetra is enabled before include the MueLu_AztecEpetraOperator.hpp header.
This is will allow the new builds that set `MueLu_ENABLE_Epetra=OFF` to compile `TrilinosCouplings` without problems
* Closes #2786 
I did a local build of the with the configure-testbed-jenkins configuration to check that everything compiles properly
> TrilinosCouplings: adding guard in exmaple_maxwell.cpp

- cmake/ctest/drivers/atdm/ride/local-driver.sh
Given data from past runs, this should result in less frequent crashing of the
'bsub' command.  This will also just speed up the build by about a factor of 2
and speed up running the tests by about 25%.
I tested this locally on 'white' with:
```
$ time env \
JOB_NAME=Trilinos-atdm-white-ride-cuda-debug \
WORKSPACE=$PWD \
Trilinos_PACKAGES=Kokkos,Teuchos \
CTEST_TEST_TYPE=Experimental \
CTEST_DO_UPDATES=OFF \
CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=FALSE   ~/Trilinos.base/Trilinos/cmake/ctest/drivers/atdm/smart-jenkins-driver.sh \
&> console.out
```
and it showed that it used the all-at-once approach.
> Switch all builds on 'white' and 'ride' to use all-at-oce approch (TRIL-198)

- cmake/ctest/drivers/atdm/toss3/local-driver.sh
Now that the new testing-vm.sandia.gov site is sending out emails, I think
this is a safe thing to do.  I am hoping this will help to avoid timeouts in
the sbatch command running the tests on 'serrano'.
I did not test this.  But this was a copy-and-paste from the other driver scripts for 'white'/'ride' that was tested and it is an extremely safe change.
> Switch to all-at-once approach for 'toss3' builds on 'serrano' (TRIL-200, #2699)

- cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-opt-openmp-panzer.sh
This is so that we can set up Jenkins builds on 'chama' to submit to
'Specialized' CDash group at first, even though these builds may be going to
the "ATDM" CDash group on 'serrano'.
This was not tested but it is super safe and was copied from another tested script.
> Allow Trilinos_TRACK to be overridden in Jenkins driver (TRIL-200)

- packages/epetra/example/petra_power_method/cxx_main.cpp
- packages/epetra/src/Epetra_CrsGraph.cpp
- packages/epetra/src/Epetra_CrsMatrix.cpp
- packages/epetra/src/Epetra_Export.cpp
- packages/epetra/src/Epetra_FECrsGraph.cpp
- packages/epetra/src/Epetra_FECrsMatrix.cpp
- packages/epetra/src/Epetra_FEVector.cpp
- packages/epetra/src/Epetra_Import.cpp
- packages/epetra/src/Epetra_Import_Util.cpp
- packages/epetra/src/Epetra_Util.h
- packages/epetra/test/FusedImportExport/cxx_main.cpp
- packages/epetra/test/FusedImportExport_LL/cxx_main.cpp
Follow-up to #2783: we can get the same effect with a utility function instead of a new C++11 feature.
I verified that I can successfully run all Epetra tests with and without C++11. This also fixes the original problem with GCC's debug mode.
This was not too hard to put together (just a bit of search and replace).
> Epetra: Add a utility function to get a std::vector's buffer.

- cmake/ctest/drivers/atdm/ctest-s-driver-config-build.sh
- cmake/ctest/drivers/atdm/ctest-s-driver.sh
- cmake/ctest/drivers/atdm/utils/setup_env.sh
- cmake/std/atdm/ride/environment.sh
Updated ATDM Trilinos builds on 'white' and 'ride' to use manually installed CMake 3.11.2 and Ninja 1.8.2 (which supports CMake Fortran builds).  I also did some refactoring to remove duplication.   See the commit log messages and diffs.  There are not many changes here.
There is hope that this will address several issues.
* The ninja module load failures in the Jenkins builds on 'ride' (see [TRIL-208](https://software-sandbox.sandia.gov/jira/browse/TRIL-208)). 
* Crashing of 'bsub' on 'white' and 'ride' (see [TRIL-198](https://software-sandbox.sandia.gov/jira/browse/TRIL-198)). (Hoping the new libuv implementation of the ctest test job runner may magically fix the problems with 'bsub' crashing while running tests with ctest -S.)
I did quite a bit of manual testing for …
> Tril 198 cmake 3.11.2 ninja 1.8.2

- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp
Replacing `MultiVectorFiller` with `FEMultiVector` in FE assembly examples.
* Closes #2756 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Tpetra tests pass locally: gcc 7.2, openmpi 3.0.0
> Tpetra: replacing MultiVectorFiller with FEMultiVector

- cmake/ctest/drivers/atdm/TrilinosCTestDriverCore.atdm.cmake
This is needed so that the ctest -S drvier with ninja will have '-k 99999'
passed in to show all build errors, which we want for ctest -S builds and
submits to CDash.
See the comment in the file in the commit for more details.
This is needed so that ATDM Trilinos builds show all of their errors.
I tested this locally with the Jenkins driver and I say that the '-k 99999' argument is included.
> Fix setting CTEST_BUILD_FLAGS for ctest -S driver (TRIL-171)

- cmake/ctest/drivers/atdm/shiller/local-driver.sh
- cmake/ctest/drivers/atdm/utils/setup_env.sh
- cmake/std/atdm/README.md
- cmake/std/atdm/shiller/environment.sh
I installed CMake 3.11.2 and Fortran-capable Ninja 1.8.2 under my home dir on 'hansen' and 'shiller' and opened up permissions to allow anyone to use.  I then updated the ATDM Trilinos configuration on 'hansen' and 'shiller' to use these.
I then updated the Jenkins ctest -S driver to use the all-at-once approach on these machines.
I also had to switch to 'salloc' instead of 'srun' (see commit c9ccf7d).
This allows using the all-at-once approach which should be much faster.  I am doing this primarily to reduce time running on 'hansen' which is now past capacity  and can't run all of the builds currently defined on it (after adding the CUDA 9.0 builds as part of #2706).
I tested this locally on 'hansen' and 'shiller' with the checkin-test-sems.sh script.  I tested the …
> Use manually installed cmake 3.11.2 ninja 1.8.2 on hansen/shiller

- cmake/std/atdm/ride/environment.sh
Since these executables only run on 'white' and 'ride', we needed to move
these into a subdir.
Done because these only work on 'white' and 'ride', not other machines (see 03de0f3).  For more details, see [TRIL-209](https://software-sandbox.sandia.gov/jira/browse/TRIL-209).
I tested this locally on 'white' with the checkin-test-atdm.sh script:
```
$ bsub -x -Is -q rhel7F -n 16 \
./checkin-test-atdm.sh cuda-opt --enable-packages=Kokkos --local-do-all
```
```
Tue May 29 13:33:15 MDT 2018
Enabled Packages: Kokkos
1) cuda-opt => passed: passed=27,notpassed=0 (4.64 min)
```
I tested this on …
> Move cmake-3.11.2 and ninja-1.8.2 to white-ride/ subdir (TRIL-209)

- cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake
CC: @trilinos/shylu, @trilinos/framework 
The addresses #2691.
These disables will allows this build to be promoted to the CI build and an
auto PR build (see #2462).
ShyLU developers have not been able to reproduce and fix yet.  Temporarily disabling in this one (and only this one) build is the best option.  The GCC 4.9.3 serial Kokkos auto PR build will still run these tests.
* Addresses: #2691,
* Related to: #2462, #2317 
While on this branch, I tested this as described in the "Steps to Reproduce" section in #2691 on my CEE LAN machine 'ceerws1113' and the configure output showed:
```
Processing enabled package: ShyLU_DD (FROSch, Tests, Examples)
-- ShyLU_DDFROSch_test_frosch_laplacian_epetra_2d_gdsw_MPI_4: NOT added test because …
```
> Temp disable three ShyLU_DD tests for this OpenMP build (#2691)

- cmake/std/PullRequestLinuxDriver.sh
- cmake/std/PullRequestLinuxIntelTestingSettings.cmake
Testing revealed I had copied and modified the driver script instead of the configuration make file.  That was a mess when attempting to re-create a build for testing.  This seems better and also does not duplicate the info in the GCC base configuration.
Teted by following the PR build recreation steps.  I need this to verify that all the failing tests are covered as well.
> Correct Intel configuration before I messed everyone up (hopefully)

- cmake/ctest/drivers/sems_ci/ctest_linux_mpi_debug_shared_pt_ci.sems.cmake
- cmake/ctest/drivers/sems_ci/single_ci_iter.sh
- cmake/std/sems/checkin-test-sems.sh
- project-checkin-test-config.py
CC: @trilinos/framework, @fryeguy52, @mhoemmen, @ibaned
Switches the default checkin-test-sems.sh build and post-push CI build to use updated GCC 4.8.4 + OpenMPI 1.10.1 + OpenMP configuration.
This enables OpenMP for the GCC 4.8.4 and this matches the GCC 4.8.4 we agreed to for the auto PR build in #2317.
* Related to: #2317, #2462
I ran the full CI build on my machine 'crf450' with:
```
$ ./checkin-test-sems.sh --enable-all-packages=on --local-do-all
```
That returned:
```
Enabled Packages: 
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Packages
Hostname: crf450.srn.sandia.gov
Source Dir: /home/rabartl/Trilinos.base/Trilinos/cmake/tribits/ci_support/../../..
Build Dir: /home/rabartl/Trilinos.base/BUILDS/CHECKIN/MPI_RELEASE_DEBUG_SHARED_PT_OPENMP
CMake Cache Varibles: -GNinja …
```
> Switch default checkin-test-sems.sh build and post-push CI build to use updated GCC 4.8.4 + OpenMPI 1.10.1 + OpenMP configuration

- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-8.0-debug.sh
- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-8.0-opt.sh
- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-9.0-debug.sh
- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-9.0-opt.sh
- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-debug-panzer.sh
- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-opt-panzer.sh
From a copy-and-paste these were hard-coded to send to the "ATDM" CDash
Track/Group.  But these should not be promoted yet so I had the Jenkins jobs
set CTEST_TEST_TYPE=Experimental which overrides that.  Now these will go to
"Specializezd" by default, unless overridden in the Jenkins job.
I also got rid of 'export ATDM_CONFIG_USE_MAKEFILES=ON' which is a non-op
since the var name was changed to ATDM_CONFIG_USE_NINJA a while ago.
* Part of: #2706  
I did not test this, but this was a copy and pasted from a script that was tested.  And this change is very simple with almost zero chance of breaking anything.
> Send CUDA 9.0 builds to "Specialized" CDash Track/Group and remove old var (#2706)

- cmake/ctest/drivers/atdm/serrano/drivers/Trilinos-atdm-serrano-intel-opt-openmp-panzer.sh
- cmake/std/atdm/toss3/environment.sh
The commits are self explanatory.
I tested that the exported function `atdm_run_script_on_compute_node` can be used in child process scripts.
> Some small 'serrano' updates for the ATDM Trilinos configuration

- cmake/std/PullRequestLinuxDriver.sh
this was left in Experimental where I had it for testing.
While the URL we give back from the autotester does not
rely on the group, this looks bad and is incorrect.
> PullRequestLinuxDriver.sh: correct cdash group

- packages/kokkos/core/src/Kokkos_CopyViews.hpp
- packages/kokkos/core/unit_test/CMakeLists.txt
- packages/kokkos/core/unit_test/Makefile
- packages/kokkos/core/unit_test/TestViewCopy.hpp
- packages/kokkos/core/unit_test/cuda/TestCudaHostPinned_ViewCopy.cpp
- packages/kokkos/core/unit_test/cuda/TestCudaUVM_ViewCopy.cpp
- packages/kokkos/core/unit_test/rocm/TestROCmHostPinned_ViewCopy.cpp
view_copy fix in Kokkos deep_copy and unit tests added.
Debugging and fix with @crtrott and @dsunder.
Issue exposed by failing Panzer examples reported in #2827.
This PR is a patch created from kokkos/kokkos#1653.
modified:   ../src/Kokkos_CopyViews.hpp
modified:   CMakeLists.txt
modified:   Makefile
new file:   TestViewCopy.hpp
new file:   cuda/TestCudaHostPinned_ViewCopy.cpp
new file:   cuda/TestCudaUVM_ViewCopy.cpp
new file:   rocm/TestROCmHostPinned_ViewCopy.cpp
> kokkos: view_copy fix

- packages/teuchos/comm/test/UnitTesting/CMakeLists.txt
Commit e9be88c070b2093f16f43f0697bc4936ed87e621 is self-explanatory.  I tested this locally with the standard CI build and verified that the startup banner is gone.
> Suppress GlobalMPISession starup banner to avoid regex problems (#2863)

- packages/ifpack2/example/RelaxationWithEquilibration.cpp
- packages/tpetra/core/src/Tpetra_Details_EquilibrationInfo.hpp
- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_decl.hpp
Add an Ifpack2 example that demonstrates a complete linear solver:
- Belos iterative solver
- Ifpack2 preconditioner (optional)
- Equilibration (optional), using new Tpetra capabilities I added recently
@trilinos/ifpack2 @trilinos/tpetra @trilinos/belos 
This is an example, not a new feature.  It's not clear where a feature would go in Trilinos.
Sierra (specifically Fuego) really really needs row scaling.  It works great with their AztecOO solves.
Locally, with various command-line options.
> Ifpack2 + Belos + equilibration demo

- packages/xpetra/sup/Utils/Xpetra_TripleMatrixMultiply.hpp
Set striding information in the triple matrix product. This should resolve issues that arise when using strided maps, triple matrix product and MueLu's repartitioning.
> Xpetra: Set striding information in triple matrix product

- packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp
Addresses issue #2866 - moved the test_traits structs out of the
anonymous namespace to a non-anonymous namespace
Tested by building Trilinos sub-packages without errors using the reproducer steps of #2866 on Shiller.
> Amesos2: Fix namespace issue with cuda in adapter tests

- packages/ifpack2/src/CMakeLists.txt
- packages/ifpack2/src/Ifpack2_Details_OverlappingRowGraph_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_OverlappingRowGraph_def.hpp
- packages/ifpack2/src/Ifpack2_Details_RowGraph.hpp
- packages/ifpack2/src/Ifpack2_Details_RowMatrix.hpp
- packages/ifpack2/src/Ifpack2_Details_throwBecauseDeprecated.cpp
- packages/ifpack2/src/Ifpack2_Details_throwBecauseDeprecated.hpp
- packages/ifpack2/src/Ifpack2_DiagonalFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_DiagonalFilter_def.hpp
- packages/ifpack2/src/Ifpack2_DropFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_DropFilter_def.hpp
- packages/ifpack2/src/Ifpack2_LocalFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_LocalFilter_def.hpp
- packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_decl.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
- packages/ifpack2/src/Ifpack2_RILUK_def.hpp
- packages/ifpack2/src/Ifpack2_ReorderFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_ReorderFilter_def.hpp
- packages/ifpack2/src/Ifpack2_SingletonFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_SingletonFilter_def.hpp
- packages/ifpack2/src/Ifpack2_SparsityFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_SparsityFilter_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestHelpers.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_RowGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_RowMatrix_decl.hpp
@trilinos/ifpack2 @trilinos/tpetra 
- Fix #2869 (`Tpetra::RowGraph::supportsRowViews` was not marked virtual)
- Fix some deprecated warnings relating to #2630 that show up in Ifpack2
- #2869 relates to host-only CrsGraph access code, that accesses CrsGraph through RowGraph virtual methods; fixing it could improve MueLu performance
- @ibaned [reported Albany being swamped](https://github.com/trilinos/Trilinos/issues/2630#issuecomment-393869243) with deprecated warnings; this PR should reduce the number of warnings Albany and other applications see
* Related to #2869 
* Part of #2630 
With Clang, on MacOS X
These changes do technically break backwards compatibility, in that users of Ifpack2 subclasses of `Tpetra::RowGraph` and `Tpetra::RowMatrix` may no longer call methods deprecated by …
> Ifpack2,Tpetra: Fix #2869, & fix some #2630 deprecated warnings 

- cmake/ctest/drivers/atdm/chama/drivers/Trilinos-atdm-chama-intel-debug-openmp-panzer.sh
- cmake/ctest/drivers/atdm/chama/drivers/Trilinos-atdm-chama-intel-debug-openmp.sh
- cmake/ctest/drivers/atdm/chama/drivers/Trilinos-atdm-chama-intel-opt-openmp-panzer.sh
- cmake/ctest/drivers/atdm/chama/drivers/Trilinos-atdm-chama-intel-opt-openmp.sh
The 'panzer' builds whese were copy and pasted to go to the "ATDM" CDash
Track/Group but they are not passing so that is not right.
@fryeguy52, I did this before your PR #2284 posted.   The changes in this PR allow for overriding `Trilinos_TRACK` in the outer Jenkins job if needed short term.
I did not test this but the changes are very simple and I copy and pasted this from other working scripts.
> Change all 'chama' builds to go to "Specialized" CDash Track/Group (TRIL-200)

- packages/muelu/src/Graph/MueLu_Aggregates_decl.hpp
- packages/muelu/src/Graph/MueLu_Aggregates_def.hpp
- packages/muelu/src/Graph/MueLu_CoupledAggregationCommHelper_decl.hpp
- packages/muelu/src/Graph/MueLu_CoupledAggregationCommHelper_def.hpp
- packages/muelu/src/Utils/MueLu_AggregationExportFactory_def.hpp
- packages/xpetra/src/CMakeLists.txt
- packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.cpp
- packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp
- packages/xpetra/src/MultiVector/Xpetra_MultiVectorFactory.hpp
- packages/xpetra/test/MultiVector/MultiVector_UnitTests.cpp
@trilinos/muelu @trilinos/xpetra 
Adding interface for IntMultiVector in Xpetra, this will be used in overlapping aggregates.
This will allow structured aggregates to have sufficient data stored in case of piece-wise linear interpolation prolongator
* Blocks #2687, #2577, #2230
The Xpetra unit test for MultiVector has been expended to test for `Scalar=int` and `Scalar=long long int` which tests the added interface.
> MueLu: overlapping aggregates

- packages/muelu/src/Interface/MueLu_FactoryFactory_decl.hpp
- packages/muelu/src/MueCentral/MueLu_FactoryManager_decl.hpp
- packages/muelu/src/MueCentral/MueLu_FactoryManager_def.hpp
- packages/muelu/utils/paramlist/convertToKokkos.py
Allows to build the `*_kokkos` factories from the extended interface. All factories are accesible by their full name, e.g. `NullspaceFactory_kokkos`. The script `convertToKokkos.py` is an attempt at converting xml input files to Kokkos.
Closes Issue #2663
> MueLu: Build Kokkos version of factories from extended input format

- packages/amesos2/src/Amesos2_EpetraCrsMatrix_MatrixAdapter_def.hpp
- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_def.hpp
- packages/amesos2/src/Amesos2_SolverCore_def.hpp
Remove warnings generated when building with `gcc-7.3.0`.  Specifically:
* Unused parameters.
* Intentional fallthrough in a `switch` statement.
Just hoping for a cleaner build.
Letting the @trilinos-autotester do its thing.
> Amesos2:  Remove Build Warnings

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
RefMaxwell was using an array of type magnitudeType to compute the norms
of the coordinates array, which is of type double.  This changes the
array to be of the proper type.
> MueLu:  Fix RefMaxwell for when magnitudeType != double

- packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp
Adding the proper calls to extractView in the Xpetra_EpetraIntMultiVector
interface.
Fixing the call to extractView in getLocalView from Xpetra_EpetraIntMultiVector
This is a bug, it needs to be fixed for builds that have `Xpetra_ENABLE_kokkos_refactor=ON`
* Closes #2905 
This fix locally builds with said configure flag turned on, I also ran Xpetra's unit tests and some tests in MueLu for good measure.
> Xpetra: fix 2905

- packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_BlockedTpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp
- packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp
Remove `unused parameter` warnings seen when compiling with `gcc-7.3.0`.
Just wanting to see a cleaner build.
Letting the @trilinos-autotester do its thing.
> Panzer:  Remove Unused Parameter Warnings

- packages/phalanx/src/Phalanx_DataLayout_DynamicLayout.cpp
- packages/phalanx/src/Phalanx_DataLayout_MDALayout_Def.hpp
- packages/phalanx/src/Phalanx_DimTag.cpp
- packages/phalanx/src/Phalanx_Evaluator_UnmanagedFieldDummy.hpp
- packages/phalanx/src/Phalanx_Evaluator_Utilities.hpp
- packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl_Def.hpp
- packages/phalanx/src/Phalanx_Print_Utilities.hpp
- packages/phalanx/test/AliasedFields/AliasedFields_TestEvaluators.hpp
- packages/phalanx/test/AssemblyHeatFluxFad/evaluators/Evaluator_Constant_Def.hpp
- packages/phalanx/test/AssemblyHeatFluxFad/evaluators/Evaluator_Density_Def.hpp
- packages/phalanx/test/AssemblyHeatFluxFad/evaluators/Evaluator_EnergyFlux_Fourier_Def.hpp
- packages/phalanx/test/AssemblyHeatFluxFad/evaluators/Evaluator_FEInterpolation_Def.hpp
- packages/phalanx/test/AssemblyHeatFluxFad/evaluators/Evaluator_NonlinearSource_Def.hpp
- packages/phalanx/test/UnmanagedFields/Field/Field_TestEvaluators_Def.hpp
- packages/phalanx/test/UnmanagedFields/KokkosView/View_TestEvaluators_Def.hpp
- packages/phalanx/test/UnmanagedFields/MDField/MDField_TestEvaluators_Def.hpp
- packages/phalanx/test/Utilities/Evaluator_MockDAG_Def.hpp
Remove `unused parameter` warnings generated with `gcc-7.3.0`.
Just wanting a clean build.  My head's really foggy with sickness today, but cleaning up warnings is something I can manage.
Just letting the @trilinos-autotester do its thing.
> Phalanx:  Remove Unused Parameter Warnings

- packages/anasazi/epetra/util/ModeLaplace/BlockPCGSolver.h
Remove `unused parameter` warning generated by `gcc-7.3.0`.
Just working on a cleaner build.
Letting the @trilinos-autotester do its thing.
> Anasazi:  Remove Unused Parameter Warning

- packages/aztecoo/src/Epetra_MsrMatrix.h
@trilinos/aztecoo 
Remove compiler warning by explicitly calling base class copy constructors.
Just hoping for a cleaner build.  In this case the way things were originally written left the meaning unclear, which is why `gcc-7.3.0` is warning about it.
@trilinos-autotester
> AztecOO:  Remove Copy Constructor Compiler Warning

- cmake/std/atdm/chama/environment.sh
- cmake/std/atdm/serrano/environment.sh
- cmake/std/atdm/toss3/environment.sh
The toss3/environment.sh script was setting 
```
export ATDM_CONFIG_KOKKOS_ARCH=BDW
```
which is correct for serrano but not for chama.  `ATDM_CONFIG_KOKKOS_ARCH` is now set in the serrano/environment.sh and chama/environment.sh scripts
This fixes illegal instruction errors on `chama` when I do local builds of various packages.  
Previously all tests would fail due to illegal instruction error, with this change the tests pass again.  I tested this with a build of Kokkos and a build of Thyra
```
cd BUILD_DIR/
export TRILINOS_DIR=/gscratch/jfrye/Trilinos
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh $JOB_NAME
cmake \
-DTrilinos_ENABLE_Thyra=ON \
$TRILINOS_DIR
make -j16
ctest -j16 -VV …
```
> Set KOKKOS_ARCH differently for chama and serrano in ATDM config

- packages/kokkos/Makefile.kokkos
Remove `-L$PWD` from `KOKKOS_LDFLAGS` and `KOKKOS_CXXLDFLAGS` if Kokkos is being built by CMake.
EMPIRE is currently patching Kokkos to remove these lines, presumably because they break their build. @bathmatt let us know about this.
> Kokkos: Don't add -L$PWD when building with CMake

- cmake/std/atdm/README.md
- cmake/std/atdm/ride/tweaks/CUDA-DEBUG-CUDA.cmake
- cmake/tribits/core/package_arch/TribitsAddTest.cmake
CC: @trilinos/kokkos, @trilinos/kokkos-kernels, @fryeguy52 
This PR disables a couple of the more expensive individual unit tests for a Kokkos and KokkosKernels test for just the `cuda-debug` build on just 'white'/'ride'.  This addresses the last of the errors related to #2827.
As part of this, I extended TriBITS to support a [<fullTestName>_EXTRA_ARGS cache var](https://tribits.org/doc/TribitsDevelopersGuide.html#adding-extra-commandline-arguments-externally-tribits-add-test) that allows you to append arbitrary command-line arguments to specific tests added with [TRIBITS_ADD_TEST()](https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-add-test).  I used this to add the `--gtest_filter` arguments to disable the specific unit tests.
I also included a commit fixing some typos in a …
> Selective disables of a few individaul unit tests in Kokkos and KokkosKernels for cuda-debug build on 'white' and 'ride'

- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-opt.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-gnu-opt-openmp.sh
- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-9.0-debug.sh
- cmake/ctest/drivers/atdm/shiller/drivers/Trilinos-atdm-hansen-shiller-cuda-9.0-opt.sh
- cmake/std/atdm/ride/tweaks/CUDA-DEBUG-CUDA.cmake
- cmake/std/atdm/shiller/tweaks/CUDA_COMMON_TWEAKS.cmake
- cmake/std/atdm/shiller/tweaks/GNU-DEBUG-SERIAL.cmake
- cmake/std/atdm/shiller/tweaks/GNU-RELEASE-SERIAL.cmake
* Some selective disable of tests (see the commits)
* Promoting some passing builds (see the commits)
See: #2925, #2919, #2990, #2826, and [TRIL-198](https://software-sandbox.sandia.gov/jira/browse/TRIL-198)
Clean up the ATDM Trilinos dashboard.
I ran configure on 'hansen' and 'white' for all of the builds using:
```
$ ./checkin-test-atdm.sh all --enable-packages=Stratimikos,Belos --configure
```
and verified that the correct tests were disabled for the correct builds.
> Some selective disables and promotion of some ATDM T

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
- packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
Add a max_levels flag to limit the depth of timer levels printed in report() for StackedTimer output
> Teuchos: add max levels to StackedTimer output options

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
This two character change significantly improves readability of stacked timer output when there are many nested levels present. Shamelessly lifted for @ibaned 's kokkos space time stack.
> Teuchos: improve stacked timer output

- cmake/ctest/drivers/atdm/shiller/local-driver.sh
- cmake/std/atdm/README.md
The commits and the updated text in the README.md file are self-explanatory but in short you need to allocate jobs on 'hansen' with `srun` and not `salloc`.
If you use `salloc`, SLURM runs the jobs on the login node 'hansen01' but thinks it is running it on a compute node.  If you use `srun`, it runs the job correctly on a compute node.  Crazy.
This is what was likely causing all of the test timeouts and strange behavior that we have been seeing lately on 'hansen' documented in issues #2925, #2919 and #2913.
On 'hansen' I ran:
```
$ time env \
JOB_NAME=Trilinos-atdm-hansen-shiller-gnu-debug-serial \
WORKSPACE=$PWD \
Trilinos_PACKAGES=Kokkos,Teuchos \
CTEST_TEST_TYPE=Experimental \
CTEST_DO_UPDATES=OFF \
CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=FALSE \ …
```
> Use 'srun' and not 'salloc' on hansen/shiller

- packages/shylu/shylu_node/hts/src/shylu_hts_impl_def.hpp
Add `const` to extern BLAS arguments. This is intended to fix the
Sierra-Trilinos integration.
A planned additional fix is to default to calling BLAS through Teuchos. This
entails an additional un-inlinable hop; thus, a compile-time option will be
provided to use the current 1-hop code path.
> ShyLU/HTS: Partially fix #2942.

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
- packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
- packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp
The fraction calculation for the "Remainder" of each block was using a parent_time from one level too high.
Also added a warning (that can be disabled) that discusses when a remainder calculation can be incorrect. This can happen when a timer does not exist on every MPI process in the communicator. A good example of this is for timing boundary condition operations. These timers might only be called if elements in the sideset exists on a particular MPI process.
> Teuchos: fix remainder fraction calculation in StackedTiimer

- packages/xpetra/src/Utils/Xpetra_Parameters.hpp
> Xpetra: Fix wrong instantiation enum

- packages/panzer/disc-fe/src/Panzer_L2Projection.hpp
- packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
Some cleanup of panzer objects.
> panzer cleanup

- cmake/std/PullRequestLinuxDriver.sh
- cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake
- cmake/std/PullRequestLinuxGCC4.9.3TestingSettings.cmake
- cmake/std/PullRequestLinuxIntelTestingSettings.cmake
- cmake/std/sems/PullRequestGCC4.8.4TestingEnv.sh
This takes in the existing cmake GCC scripts and changes them to depend
on a single default and simply add changes as needed.  Right now the
4.9.3 does no additional setup and the 4.8.4 adds OpenMP requirements.
I also added the OPENMP_NUM_THREAD variable to the 4.8.4 environment
setup and changed the driver script to use those changes.
Note that the new builds will not actually be enabled until the Jenkins jobs are modified to the same driver script we currently use for the Intel job.
* Closes #2788 
- [ x ] My change requires a change to the documentation.
- [ x ] No new compiler …
> Add OpenMP to the 4.8.4 build

- packages/tpetra/core/src/Tpetra_Details_EquilibrationInfo.hpp
- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
- packages/tpetra/core/test/CrsMatrix/Equilibration.cpp
Add Inf, NaN, zero diagonal entry, and zero row sum (I'm using the AztecOO term; this is actually a one-norm, that is, a sum of absolute values) detection to Tpetra::computeRowAndColumnNorms.  This imitates and improves upon AztecOO's zero row sum detection.
@trilinos/ifpack2 @trilinos/tpetra @vbrunini 
Aria and Fuego want this.
* Closes #2968 
Locally.  I added tests for all the different error conditions that the routine checks.
> Tpetra: Fix #2968

- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
- packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap.hpp
- packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp
I also cleaned up some code in Xpetra's `EpetraCrsMatrix`. I am really confused by what that code did (constructing domain map through removing duplicate entries in row map?)
> Muelu: use 4 map constructor for Kokkos-based TentativePFactory

- cmake/std/atdm/README.md
- cmake/std/atdm/shiller/environment.sh
This setup has a problem of having tests run on top of each other using the
same cores with the GCC 4.9.3 serial executables.  I tried passing different
sets of arguments into 'mpiexec' but that just resulted in "There are not
enough slots available in the system" errors for a bunch of tests.  See #2976
for more details.
The only successful solution to ths problem will likely be an extension to
ctest to control process and thread affinity and a close collaboration with
MPI as described in #2422 and:
* https://gitlab.kitware.com/snl/project-1/issues/17#note_422034
I also fixed the path for cmake and ninja in my home directory to point to
/home/rabartl/.  On the login this can be /ascldap/users/rabartl/ but on the
compute nodes, that directory does not exist.  This fixes …
> Reduce ctest from 16 to 8 for serial GCC builds and fix path to cmake and ninja on hansen/shiller (#2976)

- packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_MicroBenchmark.cpp
Merge of the Tpetra::MultiVector sync cleanup into develop.  This should have *no* effect except on CUDA.  Both ATDM apps cleared the merge as OK.
> Tpetra multivector sync cleanup

- packages/sacado/example/CMakeLists.txt
- packages/sacado/example/high_order_example.cpp
This adds a new Sacado example that demonstrates the computation of high-order directional derivatives with nested Fad objects.  It demonstrates correctness by also computing a full high-order derivative tensor that is multiplied against the directions through the multivariate chain rule.
> Sacado:  Example demonstrating computing a high-order derivative with Fad

- packages/stokhos/src/CMakeLists.txt
- packages/stokhos/src/sacado/kokkos/Stokhos_Sacado_Kokkos_MathFunctions.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS_binary_func_tmpl.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS_binary_op_tmpl.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS_ops.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS_unary_func_tmpl.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS_unary_op_tmpl.hpp
The SFS specialization is a specialization of Sacado::MP::Vector for the StaticFixedStorage storage type and doesn't use expression templates.  The hope is the compiler can do a better job autovectorizing the overloaded operators since it doesn't have to optimize through the expression-template hierarchy.  
This was implemented a while ago, but has been disabled and so quit working.  This pull request gets it working again.  Mostly this is copying various things I have added to the main
MP::Vector implementation to the SFS specialization.  There is now a
define in Stokhos_ConfigDefs.h that determines whether it is used
(default is off).  I also redid how the overloaded operators are defined
so that the relevant pragmas can be used.  If you turn it on, everything
in my build appears to …
> Stokhos:  Get SFS specialization of MP::Vector working again.

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
In the ParameterListInterpreter, one should use parameterList instead of
constParameterList so that it could be updated to indicate that the
parameter has been read.
> MueLu: fix incorrect "unused parameter" warning

- packages/domi/test/MDArray/MDArray_Performance_UnitTests.cpp
I'm not sure how the namespace could be changed to fix this
as it appears that the nvidia 8.0.44 compiler is simply
assuming that anonymous namespaces are in the same reference
as non-namespaced items.  Odd.
@trilinos/domi 
This just renames a variable to avoid a conflict with the CUDA compiler
The code would not compile on CUDA 8.0.44 without resolving this.
> rename dim* to MDAdim* to avoid name conflict with the CUDA compiler

- packages/belos/xpetra/src/Belos_Details_Xpetra_registerSolverFactory.cpp
Resolve failing Maxwell3D tests when Tpetra_INST_INT_INT was off.
This fixes faulty logic in the Belos Xpetra DII macros for auto registration of the solvers.
If Tpetra_INST_INT_INT was off and Epetra was on,
then DII would not register the Tpetra cases.
Resolves failing Maxwell3D tests for some builds.
Local testing and a sems check up to package MueLu passes.
Note on a basic SEMS test I'm seeing MueLu_UnitTestsEpetra_MPI_4 fail for develop already. That appears to be a separate issue.
> Belos: Fix MueLu Xpetra DII for Tpetra_INST_INT_INT off

- packages/sacado/src/KokkosExp_View_Fad.hpp
- packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp
- packages/sacado/src/Kokkos_DynRankView_Fad.hpp
- packages/sacado/src/Kokkos_DynRankView_Fad_Contiguous.hpp
- packages/sacado/src/Kokkos_LayoutContiguous.hpp
- packages/sacado/src/Kokkos_LayoutNatural.hpp
- packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
- packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
Changes to Kokkos::View specialization for Fad scalar types to allow Kokkos::resize() to work, including a reproducing unit test.  See issue #3017 for description of the problem and commits logs for changes to fix it.
> Sacado fixes for issue #3017

- cmake/std/atdm/ATDMDevEnvSettings.cmake
The test `MueLu_UnitTestsTpetra_MPI_4` is failing on openmp builds this will disable that test until it can be fixed
Issue: #3035 
I confirmed with local builds that this will disable the test `MueLu_UnitTestsTpetra_MPI_4`
> Disable failing MueLu test in ATDM openmp builds

- packages/muelu/research/mmayr/composite_to_regions/src/main.cpp
Check whether the user provided the mandatory command line arguement ```--xml=<path_to_xml_file>``` and throw an error if it is missing.
Minor additional fix: Correct error check for file name when reading myCompositeMap_* on each proc.
Addressing #3062 
* Follows #2805 
* Closes #3062
> Check for Command Line Argument (Fix #3062)

- packages/tpetra/core/src/Tpetra_Core.cpp
- packages/tpetra/core/src/Tpetra_Core.hpp
- packages/tpetra/core/test/Core/CMakeLists.txt
- packages/tpetra/core/test/Core/ScopeGuard_tpetra_inits_kokkos.cpp
- packages/tpetra/core/test/Core/ScopeGuard_tpetra_inits_mpi.cpp
- packages/tpetra/core/test/Core/ScopeGuard_tpetra_inits_mpi_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_mpi.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_mpi_and_provides_comm.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_mpi_tpetra_inits_kokkos.cpp
Tpetra now has a ScopeGuard class, analogous to `Kokkos::ScopeGuard` and `Teuchos::GlobalMPISession`.  This fixes #2459.  I also added tests for all possible cases of MPI and/or Kokkos initialization.
Scope guards ensure safe finalization even if an exception is thrown.
* Closes #2459 
Locally, with MPI enabled.
> Tpetra: Fix #2459 (add ScopeGuard)

- packages/phalanx/src/Phalanx_MDField_Utilities_Def.hpp
- packages/sacado/src/Sacado_CacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRCacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRFad_GeneralFad.hpp
- packages/sacado/src/Sacado_ELRFad_Ops.hpp
- packages/sacado/src/Sacado_ELRFad_SFad.hpp
- packages/sacado/src/Sacado_Fad_DFad_tmpl.hpp
- packages/sacado/src/Sacado_Fad_GeneralFad.hpp
- packages/sacado/src/Sacado_Fad_Ops.hpp
- packages/sacado/src/Sacado_Fad_SFad.hpp
- packages/sacado/src/Sacado_Fad_SFad_tmpl.hpp
- packages/sacado/src/Sacado_Fad_SLFad_tmpl.hpp
- packages/sacado/src/Sacado_Fad_ViewFad_tmpl.hpp
- packages/sacado/src/Sacado_MathFunctions.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_ExprAssign.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_MathFunctions.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_ViewFad.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_ViewStorage.hpp
- packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
Requested by @CamelliaDPG.  This provides overloads of Kokkos::atomic_add() for all Fad types.  It also implements operator&() for ViewFad, allowing you to do things like 
```
Kokkos::atomic_add(&v(i,j,k),x);
```
Note that because of this overload, ViewFad::operator&() does not return ViewFad*, which required a small change in Phalanx.  Since you could only safely take the address of a ViewFad in limited situations, I am hoping this kind of change is not needed in many places.
> Add support for Kokkos::atomic_add() with Sacado Fad types

- packages/tpetra/core/example/Additive-Schwarz-Halo/AdditiveSchwarzHalo.cpp
- packages/tpetra/core/example/Lesson01-Init/index.doc
- packages/tpetra/core/example/Lesson01-Init/lesson01_mpi_on_its_own.cpp
- packages/tpetra/core/example/Lesson01-Init/lesson01_mpi_only_through_Tpetra.cpp
- packages/tpetra/core/example/Lesson01-Init/lesson01_no_mpi.cpp
- packages/tpetra/core/example/Lesson02-Map-Vector/lesson02_init_map_vec.cpp
- packages/tpetra/core/example/Lesson02-Map-Vector/lesson02_read_modify_vec.cpp
- packages/tpetra/core/example/Lesson02-Map-Vector/lesson02_read_modify_vec_kokkos.cpp
- packages/tpetra/core/example/Lesson03-Power-Method/lesson03_power_method.cpp
- packages/tpetra/core/example/Lesson05-Redistribution/lesson05_redistribution.cpp
- packages/tpetra/core/example/Lesson06-Custom-Operator/lesson06_custom_operator.cpp
- packages/tpetra/core/example/Lesson07-Kokkos-Fill/01_init.cpp
- packages/tpetra/core/example/Lesson07-Kokkos-Fill/02_problem.cpp
- packages/tpetra/core/example/Lesson07-Kokkos-Fill/03_fill.cpp
- packages/tpetra/core/example/Lesson07-Kokkos-Fill/04_tpetra.cpp
- packages/tpetra/core/example/Lesson07-Kokkos-Fill/05_solve.cpp
- packages/tpetra/core/example/advanced/Benchmarks/blockCrsMatrixMatVec.cpp
- packages/tpetra/core/example/advanced/Benchmarks/import.cpp
- packages/tpetra/core/example/advanced/Benchmarks/localView.cpp
- packages/tpetra/core/example/advanced/Benchmarks/vector.cpp
- packages/tpetra/core/example/utilities/compareMaps.cpp
Use the new `Tpetra::ScopeGuard` initialization and finalization class (see #2459, fixed in PR #3067) in Tpetra's examples and tutorial.  Update the text in Tpetra's tutorial to refer to ScopeGuard.
`Tpetra::ScopeGuard` is easier to use.  It also ensures that `Kokkos::initialize` sees all the command-line arguments, without needing complicated capture machinery (as `Teuchos::GlobalMPISession` does for the unit tests).
* Follows #2459 
Mac, Clang, OpenMPI 3.0.0.  Changes only affect TpetraCore examples.
> Tpetra: Use ScopeGuard in examples

- packages/kokkos/bin/nvcc_wrapper
- packages/rol/example/burgers-control/example_01.hpp
CC: @trilinos/rol, @dridzal (ROL package lead)
Fixes the ROL CUDA build failure described in #3072.  The fix was trivial (not sure why other compilers did not catch this or at least prove a warning).
I also included a commit to add debug print info for `nvcc_wrapper` (see kokkos/nvcc_wrapper#19 and kokkos/nvcc_wrapper#20).
ROL was not building for a CUDA build (see #3072).  We wold like an auto PR CUDA build that includes all Primary Tested packages and ROL is a PT package (see #2464).  Also, SPARC uses ROL and adding support for SPARC means testing ROL on all of the platforms where SPARC uses ROL and CUDA is an important build on many of those platforms.
I tested this on 'white' with:
```
$ cd ~/Trilinos.base/BUILD/WHITE/CUDA/CUDA-DEBUG/
$ source …
```
> Fix ROL CUDA build failure (#3072)

- cmake/std/PullRequestLinuxCommonTestingSettings.cmake
- cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake
- cmake/std/PullRequestLinuxGCC4.9.3TestingSettings.cmake
- cmake/std/PullRequestLinuxGCCTestingSettings.cmake
- cmake/std/PullRequestLinuxIntelTestingSettings.cmake
- cmake/std/sems/PullRequestGCC4.8.4TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnv.sh
Note that this commit include disabling tests documented
in issue #2712 and #2691 and that those should be re-enabled
when those issues are resolved.
This moves both of the gcc PR builds forward to openmpi 1.10.1 (the intel still uses mpich).
In addition I renamed the common settings file and the gcc 4.9.3 settings file now includes that common file so it can set the mpi option "--bind-to none" without impacting the mpich build.
The openMP build failed during testing due to incompatible openmpi versions. Rather than attempt to get it to work we decided that moving forward was a much better option (1.10 is still pretty old...)
* Related to #2691 #2712 
To test this we needed to bypass the bootstrapping issue, so this branch was set as the target branch and a whitespace …
> GCC PR configs - move from openmpi 1.6.5 to 1.10.1

- cmake/ctest/drivers/atdm/rhel6/local-driver.sh
This env is using CMake 3.11.1 and we are submitting to
testing-vm.sandia.gov/cdash/ which can handle the all-at-once data so there is
no reason not to switch to the all-at-once appraoch.
> Use all-at-one config, build, test, submit for rhel6 machines (TRIL-199)

- cmake/ctest/drivers/atdm/sems_gcc-7.2.0/drive_linux_mpi_sems_atdm_7.2.0.sh
- cmake/std/sems/atdm/load_atdm_7.2_dev_env.sh
This small PR switches the ATDM SEMS-based GCC 7.2.0 build to use CMake 3.11.1 and use the all-at-once approach with ctest/cdash.  This should be the last ATDM Trilinos build to be swtiched over to the all-at-once approach.
CMake 3.11.1 is faster at running tests than CMake 3.10.1 and most of the other ATDM Trilinos builds are using CMake 3.11.1.
The all-at-once approach is faster at configure, build, and running tests and displays results better on CDash.
I ran this locally on crf450 using:
```
time env \
>  CTEST_DASHBOARD_ROOT=$PWD \
>  Trilinos_PACKAGES=Kokkos,Teuchos \
>  CTEST_TEST_TYPE=Experimental \
>  CTEST_DO_SUBMIT=OFF \
>  CTEST_DO_UPDATES=OFF \
>  CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=TRUE \
> ~/Trilinos.base/Trilinos/cmake/ctest/drivers/atdm/sems_gcc-7.2.0/d …
```
> Switch ATDM SEMS 7.2.0 build to use CMake 3.11.1 and all-at-once approach

- packages/amesos2/example/ComplexSolve_WithTranspose.cpp
- packages/amesos2/example/MultipleSolves_File.cpp
- packages/amesos2/example/NewAdapter/Amesos2_NewMatrixAdapter_decl.hpp
- packages/amesos2/example/NewAdapter/Amesos2_NewMultiVecAdapter_decl.hpp
- packages/amesos2/example/SimpleSolve.cpp
- packages/amesos2/example/SimpleSolveNonContigMap.cpp
- packages/amesos2/example/SimpleSolve_File.cpp
- packages/amesos2/example/SimpleSolve_WithParameters.cpp
- packages/amesos2/example/TwoPartSolve.cpp
- packages/amesos2/example/quick_solve.cpp
- packages/amesos2/example/quick_solve_epetra.cpp
- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_decl.hpp
- packages/amesos2/src/Amesos2_MatrixTraits.hpp
- packages/amesos2/src/Amesos2_VectorTraits.hpp
- packages/amesos2/test/adapters/CrsMatrix_Adapter_Consistency_Tests.cpp
- packages/amesos2/test/adapters/Epetra_MultiVector_Adapter_UnitTests.cpp
- packages/amesos2/test/adapters/Epetra_RowMatrix_Adapter_UnitTests.cpp
- packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp
- packages/amesos2/test/adapters/Tpetra_MultiVector_Adapter_UnitTests.cpp
- packages/amesos2/test/solvers/Basker_UnitTests.cpp
- packages/amesos2/test/solvers/KLU2_UnitTests.cpp
- packages/amesos2/test/solvers/MUMPS_UnitTests.cpp
- packages/amesos2/test/solvers/SolverFactory.cpp
- packages/amesos2/test/solvers/Solver_Test.cpp
- packages/amesos2/test/solvers/Solver_Test_Basker.cpp
- packages/amesos2/test/solvers/Superlu_Solve_Tests.cpp
- packages/amesos2/test/solvers/Superlu_UnitTests.cpp
- packages/amesos2/test/tklu_simple/tklu_simple.cpp
@trilinos/amesos2 @trilinos/tpetra
Purge all use of `Tpetra::DefaultPlatform` from Amesos2 source, tests, and examples.  Use `Tpetra::ScopeGuard` where appropriate.
This relates to #57 and will help ensure more consistent Tpetra initialization and choice of defaults.
* Related to #57 
> Amesos2: Purge use of Tpetra::DefaultPlatform

- packages/tpetra/core/src/Tpetra_Vector_decl.hpp
- packages/tpetra/core/src/Tpetra_Vector_def.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
Add a default constructor to Vector.  Make Tpetra's tests exercise the default constructors of both MultiVector and Vector.
* Closes #3078 
> Tpetra: Fix #3078 (add default constructor for Vector)

- cmake/std/PullRequestLinuxIntelTestingSettings.cmake
@trilinos/framework, @trilinos/rol 
This test randomly fails in the Intel auto PR build (see #3103) and just blocked my PR merge #3100.
Tests should not randomly fail in PR builds.
I did not.  That is why here is auto PR testing :-)
> Disable randomly failing ROL test in Intel PR build (#3103)

- cmake/std/atdm/ride/environment.sh
- cmake/tribits/doc/build_ref/TribitsBuildReferenceBody.rst
- doc/build_ref/TrilinosBuildReferenceTemplate.rst
CC: @trilinos/stokhos 
The main contribution of the PR is that is fixes the build error for the stokhos_muelu lib in #3069.  It also contains updated build-reference documentation on the causes (see commits).
We need the build error #3069 to be fixed and we want to provide documentation so that other people can avoid this.
I tested this locally on `white` as described below.  The full build of Stokhos passes now but there are several test failures.  (But we will create new GitHub issues for those once this posts to CDash after the merge.)
<details>
<summary>
<b>DETAILED TEST RESULTS:</b> (click to expand)
</summary>
Testing on 'white':
```
$ cd ~/Trilinos.base/BUILD/WHITE/CUDA/CUDA-DEBUG/
$ . load-env.sh
Hostname 'white11' matches known ATDM host 'white' and system 'ride' …
```
> 3069 white cuda debug stokhos build error

- packages/anasazi/tpetra/example/CustomStatusTest/LOBPCGCustomStatusTest.cpp
- packages/anasazi/tpetra/example/TraceMinDavidson/TraceMinDavidsonGeneralizedEx.cpp
- packages/anasazi/tpetra/example/TraceMinDavidson/TraceMinDavidsonLaplacianEx.cpp
- packages/anasazi/tpetra/example/TraceMinDavidson/TraceMinDavidsonSpecTransEx.cpp
- packages/anasazi/tpetra/example/TraceMinDavidson/TraceMinDavidsonUserOpEx.cpp
- packages/anasazi/tpetra/test/BlockDavidson/cxx_main_complex.cpp
- packages/anasazi/tpetra/test/BlockDavidson/cxx_main_lap.cpp
- packages/anasazi/tpetra/test/BlockKrylovSchur/cxx_main_complex.cpp
- packages/anasazi/tpetra/test/BlockKrylovSchur/cxx_main_lap.cpp
- packages/anasazi/tpetra/test/IRTR/cxx_main_complex.cpp
- packages/anasazi/tpetra/test/IRTR/cxx_main_lap.cpp
- packages/anasazi/tpetra/test/LOBPCG/cxx_main_complex.cpp
- packages/anasazi/tpetra/test/LOBPCG/cxx_main_doublefloat.cpp
- packages/anasazi/tpetra/test/MVOPTester/MultiVecTraitsTest2.cpp
- packages/anasazi/tpetra/test/MVOPTester/cxx_main.cpp
- packages/anasazi/tpetra/test/OrthoManager/cxx_main_complex.cpp
- packages/anasazi/tpetra/test/OrthoManager/cxx_main_tsqr.cpp
- packages/anasazi/tpetra/test/TraceMin/cxx_main_standard_noprec.cpp
- packages/anasazi/tpetra/test/TraceMinDavidson/cxx_main_standard_noprec.cpp
@trilinos/anasazi @trilinos/tpetra
Purge use of Tpetra::DefaultPlatform from Anasazi's Tpetra tests and examples.
> Anasazi: Purge use of Tpetra::DefaultPlatform from tests & examples

- packages/piro/test/CMakeLists.txt
CC: @trilinos/piro, @mperego, @rppawlo, @fryeguy52 
This commit changes behavior to only add the test `Piro_AnalysisDriverTpetra_MPI_4` is ROL is enabled.
The Piro test suite should run and pass no matter what subset of optional upstream packages are enabled or disabled.
I just did a local configure using the instructions provided at in #3115 and (after adding `-DTrilinos_TRACE_ADD_TEST=ON`) the configure output showed:
```
-- Piro_AnalysisDriverTpetra: NOT added test because EXCLUDE_IF_NOT_TRUE Piro_ENABLE_ROL='OFF'!
```
When the PR testing runs, we will verify that this test is enabled and passes in the standard PR builds.
> Only add test Piro_AnalysisDriverTpetra_MPI_4 if ROL is enabled (#3115)

- packages/ifpack2/example/ex1.cpp
- packages/ifpack2/src/Ifpack2_Factory_decl.hpp
- packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
- packages/ifpack2/test/belos/AdditiveSchwarzRILUK/Test.cpp
- packages/ifpack2/test/belos/belos_extprec_solve.cpp
- packages/ifpack2/test/belos/belos_solve.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_SolverFactory.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTest234.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestAdditiveSchwarz.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestAdditiveSchwarzBug5963.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestContainerFactory.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestDenseSolver.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestFactory.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestHelpers.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRBILUK.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRILUK.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSGSMT.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessRILUK.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestTriDiSolver.cpp
- packages/ifpack2/test/vanka/TomVankaTest.cpp
@trilinos/ifpack2 @trilinos/tpetra
Purge use of Tpetra::DefaultPlatform from tests & examples.
> Ifpack2: Purge use of Tpetra::DefaultPlatform from tests & examples

- packages/belos/tpetra/test/BlockCG/test_bl_cg_complex_hb.cpp
- packages/belos/tpetra/test/BlockCG/test_bl_cg_hb.cpp
- packages/belos/tpetra/test/BlockCG/test_bl_cg_hb_multiprec.cpp
- packages/belos/tpetra/test/BlockCG/test_pseudo_bl_cg_hb.cpp
- packages/belos/tpetra/test/BlockCG/test_pseudo_stochastic_cg_hb.cpp
- packages/belos/tpetra/test/BlockGmres/test_bl_gmres_hb.cpp
- packages/belos/tpetra/test/BlockGmres/test_bl_gmres_hb_df.cpp
- packages/belos/tpetra/test/FixedPoint/test_fp_hb.cpp
- packages/belos/tpetra/test/LinearSolverFactory/CustomSolverFactory.cpp
- packages/belos/tpetra/test/LinearSolverFactory/LinearSolverFactory.cpp
- packages/belos/tpetra/test/LinearSolverFactory/SolverFactory.cpp
- packages/belos/tpetra/test/MVOPTester/cxx_main_complex.cpp
- packages/belos/tpetra/test/MultipleSolves/MultipleSolves.cpp
- packages/belos/tpetra/test/OrthoManager/belos_orthomanager_tpetra.cpp
- packages/belos/tpetra/test/OrthoManager/belos_orthomanager_tpetra_benchmark.cpp
- packages/belos/tpetra/test/OrthoManager/belos_orthomanager_tpetra_util.hpp
@trilinos/belos @trilinos/tpetra 
Purge use of `Tpetra::DefaultPlatform` from Belos' tests and examples.  Fix build warnings in Belos' Tpetra tests.
> Belos: Purge use of Tpetra::DefaultPlatform; fix build warnings

- packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.hpp
When compiled using Charm++'s Adaptive MPI, MPI's `atexit` is redfined via a macro, in AMPI's mpi.h at
https://github.com/UIUC-PPL/charm/blob/charm/src/libs/ck-libs/ampi/ampi.h#L46.
This commit prevents the following error:
```
<trilinos>/packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.hpp: In static membe
r function ‘static Teuchos::TableFormat& Teuchos::PerformanceMonitorBase<T>::format()’:
<ampi>/charm/bin/../include/mpi.h:34:21: error: expected primary-expression before ‘do’
#define atexit(...) do {atexit(__VA_ARGS__); atexit((void (*)())ampiMarkAtexit);} while(0)
^
<trilinos>/packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.hpp:225:16: note: in
expansion of macro ‘atexit’
(void) atexit(freeTableFormat);
^~~~~~ …
```
> Avoid error when MPI's atexit is redefined via a macro

- packages/teuchos/comm/src/Teuchos_TimeMonitor.cpp
Changed an exception type in `catch` to be a reference.
GCC 8.0 warns about not catching polymorphic exception classes by reference, even if they go unused.
Allows the Teuchos sub-packages I use to build without warnings under GCC 8.0 (with no non-default warning flags specified).
> Teuchos: fix GCC 8.0 warning

- packages/tpetra/core/src/Tpetra_Details_makeOptimizedColMap.hpp
- packages/tpetra/core/test/ImportExport/Issue_2198.cpp
- packages/tpetra/core/test/ImportExport/MakeOptColMap.cpp
minor changes to address #3129 
consistent return arguments in std::pair
removed unused and/or unneeded arguments
simplify interface
make test on mac, clang compiler
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] These changes break backwards compatibility.
> Tpetra:  Issue3129 makeOptimizedColMapAndImport

- packages/tpetra/core/inout/Tpetra_Details_CooMatrix.hpp
- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_decl.hpp
- packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests0.cpp
- packages/tpetra/core/test/CrsMatrix/Equilibration.cpp
- packages/tpetra/core/test/CrsMatrix/Regression/Albany182.cpp
- packages/tpetra/core/test/ImportExport/ImportExport_ImportConstructExpert.cpp
- packages/tpetra/core/test/ImportExport/ImportExport_UnitTests.cpp
- packages/tpetra/core/test/Map/Map_UnitTests.cpp
- packages/tpetra/core/test/Map/NegativeBaseIndexTest.cpp
- packages/tpetra/core/test/inout/CooMatrixImpl.cpp
These changes remove compiler warnings in Tpetra code and tests that were reported in builds using clang on a mac.  Most warnings related to unused variables or shadow declarations.
Trying to keep the compilation clean.
Extensive build of Tpetra through MueLu, Ifpack2, Xpetra, etc., on mac and linux.
All tests passed except         
230 - MueLu_Maxwell3D-Tpetra-Stratimikos_MPI_4 (Failed)
This test also failed in equivalent develop branch testing.
> Tpetra:  clean up warnings reported by clang

- packages/galeri/test/bug_5851.cpp
- packages/muelu/example/advanced/memory/Tpetra1DLaplace.cpp
- packages/muelu/matlab/bin/muemex.cpp
- packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp
- packages/muelu/matlab/src/MueLu_MatlabUtils_def.hpp
- packages/muelu/research/q2q1/Q2Q1.cpp
- packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_TekoSmoother_decl.hpp
- packages/muelu/test/simple1D/amesos2StandAlone.cpp
@trilinos/muelu @trilinos/galeri @trilinos/tpetra
Purge use of `Tpetra::DefaultPlatform` from MueLu and Galeri.
Linux, GCC, OpenMPI.
> MueLu,Galeri: Purge use of Tpetra::DefaultPlatform

- packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp
- packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Tpetra_main.cpp
- packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.hpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.hpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE_Tpetra.cpp
@trilinos/trilinoscouplings @trilinos/tpetra 
Purge use of `Tpetra::DefaultPlatform` from TrilinosCouplings.
Linux, GCC, OpenMPI.
> TrilinosCouplings: Purge use of Tpetra::DefaultPlatform

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/Misc/MueLu_StructuredLineDetectionFactory_def.hpp
- packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_decl.hpp
- packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
Repartitioning using Zoltan2 only allowed the use of coordinate based repartitioning. This PR adds the option to use other, graph-based partitioners such as Scotch or ParMetis through Zoltan2. The default behavior is not changed.
This allows repartitioning without having coordinates. I have not done any timing runs, but graph partitioning might be more expensive, so the setup cost might go up. On the other hand, graph partitioning minimizes the number of edge cuts, so we could potentially see faster solves.
> MueLu repartitioning: Allow use of graph partitioners

- packages/teuchos/comm/contrib/plotStackedTimers.py
The script parses log files containing stacked timer output. The information is displayed using a hierarchical pie chart. The top-level timers are in the center of the chart, lower levels towards the outside. The angle of the different segments corresponds to the time spent in the total time for the timer. The name and exact time for the timer under the mouse cursor are displayed at the top of the window. The user can narrow the results to a timer and its children by clicking on it, and zoom out using right clicks.
The script relies on a publicly available python package: https://github.com/klieret/pyplot-hierarchical-pie
The package is under BSD 3-Clause License.
> Teuchos: Add script for parsing and analysis of stacked timer output

- cmake/std/atdm/ride/environment.sh
CC: @fryeguy52, @nmhamster 
This loads the developer pack module:
devpack/20180308/openmpi/2.1.2/gcc/7.2.0/cuda/9.0.176
and the updated moudle:
netlib/3.8.0/gcc/7.2.0
I took out the logic for yaml-cpp because the updated devopack does not load
any yaml-cpp module and the ATDM Trilinos build does not need it.
I took out the moudle load for binutils/2.27.0 since the updated devpack
module loads and updated binutils/2.30.0 module which should address the build
errors for the stokhos_muelu library in #3069.
The env on 'white' was updated and all of the ATDM Trilinos builds on 'white' have been gone for the last several days.  This gets the builds back up so that we can see what is going on with these.  See [TRIL-215](https://software-sandbox.sandia.gov/jira/browse/TRIL-215).
I tested this …
> Update for 'white' upgrade to CUDA 9.2 driver (TRIL-125)

- packages/teuchos/core/src/Teuchos_TestForException.cpp
Send output to `std::cerr` all in one string to try to avoid jumbled output.
I also fixed a typo that I noticed in a comment not related to this code in
this file.
This might fix the randomly failing test TeuchosCore_testTeuchosTestForTermination_2_MPI_4 for the CUDA builds on platform 'hansen' (see #3163).
I just did a local build on my machine to make sure the code builds and passes all of the TeuchosCore tests (which it did).  The real test will take place over the coming weeks and months to see if this test fails anymore.
> Try to address jumbled output for terminate message (#3163)

- packages/shylu/shylu_dd/bddc/src/shylu_CoarseSpaceBDDC.h
- packages/shylu/shylu_dd/bddc/src/shylu_ConstraintsBDDC.h
- packages/shylu/shylu_dd/bddc/src/shylu_DofManager.h
- packages/shylu/shylu_dd/bddc/src/shylu_PartitionOfUnityBDDC.h
- packages/shylu/shylu_dd/bddc/src/shylu_PreconditionerBDDC.h
- packages/shylu/shylu_dd/bddc/src/shylu_WeightsBDDC.h
- packages/shylu/shylu_dd/bddc/src/shylu_ZoltanPartition.h
- packages/shylu/shylu_dd/bddc/test/SolverBDDCTest.C
- packages/shylu/shylu_dd/bddc/test/SolverBDDCTestSimple.C
- packages/shylu/shylu_dd/core/test/iterative_solver_interface_test.cpp
- packages/shylu/shylu_dd/core/test/shylu_factor_test.cpp
- packages/shylu/shylu_dd/core/test/tpetra_interface_test.cpp
- packages/shylu/shylu_node/basker/example/Solve.cpp
@trilinos/shylu @trilinos/tpetra
Purge use of `Tpetra::DefaultPlatform` from ShyLU code, tests, and examples.
* Blocks #57 
Linux, GCC, OpenMPI.
> ShyLU: Purge use of Tpetra::DefaultPlatform

- cmake/std/atdm/ride/tweaks/GNU-DEBUG-OPENMP.cmake
This test is run with a debug-openmp on other platforms and the test in the
gnu-opt-openmp build runs fine on this machine so this is not much of a
testing loss.
We really need to get away from these full debug-debug builds across all of
these platforms.
See #3168.
On 'white' I ran:
```
$ ./checkin-test-atdm.sh gnu-debug-openmp --enable-packages=KokkosKernels --configure
```
and the configure output showed:
```
-- KokkosKernels_sparse_openmp_MPI_1: NOT added test because KokkosKernels_sparse_openmp_MPI_1_DISABLE='ON'!
```
That is enough of a test.
> Disable KokkosKernels_sparse_openmp_MPI_1 in gnu-debug-openmp on white/ride (#3168)

- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
@trilinos/panzer @trilinos/tpetra
Purge all use of the now deprecated Tpetra::DefaultPlatform class from Panzer.  If you want the default Node type, say `Tpetra::Map<>::node_type`.
* Blocks #3114
> Panzer: Remove all use of Tpetra::DefaultPlatform

- packages/zoltan2/src/problems/Zoltan2_PartitioningProblem.hpp
Made trivial changes intended to fix two reported compiler warnings generated by gcc8.1.
I do not have easy access to gcc 8.1, but tests still pass using older compilers.
> Zoltan2:  fix compiler warning from gcc8.1

- packages/stratimikos/adapters/amesos2/test/test_single_amesos2_tpetra_solver.cpp
- packages/stratimikos/adapters/amesos2/test/test_single_amesos2_tpetra_solver.hpp
- packages/stratimikos/adapters/amesos2/test/test_single_amesos2_tpetra_solver_driver.cpp
- packages/teko/examples/BuildPreconditioner/example-driver-belos.cpp
- packages/teko/src/Teko_ConfigDefs.hpp
- packages/teko/src/Tpetra/Teko_TpetraThyraConverter.cpp
- packages/teko/tests/Test_Utils.cpp
- packages/teko/tests/testdriver_tpetra.cpp
- packages/teko/tests/unit_tests/tDiagnosticLinearOp.cpp
- packages/teko/tests/unit_tests/tDiagonallyScaledPreconditioner.cpp
- packages/teko/tests/unit_tests/tInverseFactoryOperator.cpp
- packages/teko/tests/unit_tests/tIterativePreconditionerFactory.cpp
- packages/teko/tests/unit_tests/tLU2x2InverseOp.cpp
- packages/teko/tests/unit_tests/tReorderBlocking.cpp
@trilinos/stratimikos @trilinos/teko @trilinos/tpetra
Purge use of Tpetra::DefaultPlatform from Stratimikos and Teko.  This replaces #3114.
Mac, Clang, OpenMPI 3.0.0; Linux, GCC, OpenMPI.
> Stratimikos,Teko: Purge use of Tpetra::DefaultPlatform

- packages/anasazi/tpetra/example/TraceMinDavidson/CMakeLists.txt
- packages/anasazi/tpetra/example/TraceMinDavidson/TraceMinDavidsonGeneralizedEx.cpp
- packages/anasazi/tpetra/example/TraceMinDavidson/TraceMinDavidsonLaplacianEx.cpp
- packages/ifpack2/test/belos/CMakeLists.txt
- packages/ifpack2/test/belos/belos_extprec_solve.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp
@trilinos/ifpack2 @trilinos/anasazi 
Ifpack2: Fix #3139; work around #3192
- Ifpack2 now builds with `Tpetra_INST_INT_INT=OFF`; this fixes #3139
- Removed `Tpetra_INST_INT_INT=ON` requirement from an unrelated test
- Found a likely Epetra64 bug (#3192) and worked around it
Anasazi: Remove `Tpetra_INST_INT_INT` requirement from examples
Remove `Tpetra_INST_INT_INT AND NOT Anasazi_ENABLE_TSQR` requirement.
For `Tpetra_INST_INT_INT`, see #2548.
Fix #3139; work around #3192; work on #2548.
* Closes #3139 
* Related to #3192 
* Part of #2548 
Linux, GCC, OpenMPI.
> Ifpack2,Anasazi: Fix #3139; remove Tpetra_INST_INT_INT=ON requirement from Anasazi examples

- packages/teko/src/Teko_Utilities.cpp
getInvDiagonalOp would only work on linear ops with underlying Epetra or Tpetra CRS matrices, so this would fail if you tried to get the inverse diagonal of a Thyra diagonal linear op. All I did was get the vector from the diagonal linear op and return a new diagonal linear op formed from its reciprocal.
This situation came up in EMPIRE, so this is a small change to address it.
Checked that this doesn't break any existing Teko tests. Also demonstrated that the same convergence is obtained in EMPIRE when compared to Ifpack2's inverse diagonal preconditioner.
> Teko: getInvDiagonalOp for Thyra::DiagonalLinearOpBase

- packages/teuchos/comm/contrib/plotStackedTimers.py
- Change regexp to match integer valued times and percentages as well
- HPie expects the value for parent nodes to be given excluding the
values of the children.
* Addresses #3190
> Teuchos: Fix issues in plotting script for stacked timers

- cmake/std/atdm/ride/environment.sh
Get this CUDA 9.0 build on 'white' working again by switching from the GCC 7.2.0 compiler to the 4.8.5 compiler.  This is part of the effort to get things working after the upgrade of 'white' (see [TRIL-215](https://software-sandbox.sandia.gov/jira/browse/TRIL-215)).
We have not had a successful CUDA build on 'white' since 7/17/2018.  This to get that CUDA build running again while the Test Bed team fixes the CUDA 9.0 build env to work with GCC 7.2.0.
I tested this on 'white' with:
```
$ bsub -x -Is -q rhel7F -n 16 \
./checkin-test-atdm.sh cuda-opt --enable-packages=Kokkos --local-do-all
```
> Fix CUDA 9.0 build with module tweak (TRIL-215)

- cmake/std/atdm/mutrino/tweaks/INTEL-DEBUG-OPENMP.cmake
- cmake/std/atdm/mutrino/tweaks/INTEL-RELEASE-OPENMP.cmake
The executables are built in a parallel build, but they are
really serial so when run there is some extra info that is
output to stderr which ends up messing with the textual comparison
with the expected "gold" output files.  For now disable the tests
until can figure out a better way of running them.
This should address #3183.
> Disable failing SEACAS tests on Mutrino (#2815)

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
- packages/panzer/mini-em/example/BlockPrec/main.cpp
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell2D.xml
- packages/panzer/mini-em/src/closures/MiniEM_ClosureModel_Factory_TemplateBuilder.hpp
- packages/panzer/mini-em/src/closures/MiniEM_ClosureModel_Factory_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_GaussianPulse.hpp
- packages/panzer/mini-em/src/closures/MiniEM_GaussianPulse_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_InversePermeability.hpp
- packages/panzer/mini-em/src/closures/MiniEM_InversePermeability_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_Permittivity.hpp
- packages/panzer/mini-em/src/closures/MiniEM_Permittivity_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_MassMatrix.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_MassMatrix_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell_impl.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
- Fix zero diagonals in RefMaxwell (2,2) block by default. Usually this is not necessary, but some problems with periodic BCs it seems to be a requirement.
- Add command line options to MiniEM for running 2D and periodic problems.
- Allow permeability and permittivity to vary spatially.
- Fix issue in RefMaxwell Epetra code path by allowing non-matching maps
> MiniEM & RefMaxwell changes

- cmake/ctest/drivers/atdm/mutrino/drivers/Trilinos-atdm-mutrino-intel-debug-openmp-KNL.sh
- cmake/ctest/drivers/atdm/mutrino/drivers/Trilinos-atdm-mutrino-intel-opt-openmp-KNL.sh
@fryeguy52 
The tests on the KNL build are taking an absurd amount of time but let's see
if we can get them to complete in 9 hours!  AT the old timeout of 5 hours it
the debug build ran 1504 out of 1801 tests so I am hopeful this will allow
them to complete.
This is only taking up one compute node on 'mutrino' so this is not such a
crime at this point.
This is being driven by [TRIL-196](https://software-sandbox.sandia.gov/jira/browse/TRIL-196)
Want to see if we can get these tests to complete to see if there are errors.  We can fix the runtime problem later.
I did not test this but the changes are simple and super safe and can only impact these two KNL build (which are just "Specialized" builds currently).
> Increase KNL testing timeout from 5 to 9 hours (TRIL-196)

- packages/nox/src-lapack/NOX_LAPACK_Vector.C
A NOX/LOCA user was seeing strange behavior when using the LAPACK
interface, which I tracked down to inconsistent vector sizes because
operator=() doesn't copy the vector's size.  I guess this was
technically incorrect usage on his part, but I don't see any reason why
the following shouldn't work:
NOX::LAPACK::Vector x;
x = NOX::LAPACK::Vector(100);
With this change, this will now work as expected.
> NOX:  Copy vector size in NOX::LAPACK::Vector::operator=()

- packages/sacado/src/Kokkos_LayoutContiguous.hpp
Removed ambiguous partial specializations of inner_layout<> for
LayoutContiguous, that were causing compiler errors with clang.  For
issue #3195.
> Sacado:  Fix partial specialization of inner_layout<> for Clang.

- cmake/std/atdm/shiller/tweaks/INTEL-DEBUG-OPENMP-HSW.cmake
- cmake/std/atdm/shiller/tweaks/INTEL-DEBUG-SERIAL-HSW.cmake
- cmake/std/atdm/shiller/tweaks/INTEL-RELEASE-OPENMP-HSW.cmake
- cmake/std/atdm/shiller/tweaks/INTEL-RELEASE-SERIAL-HSW.cmake
@trilinos/piro, @fryeguy52, @rppawlo (Trilinos Nonlinear Algorithms Product Lead)
With KOKKOS_ARCH=HSW now being set for these Intel builds, this test diffs
badly just like for the GNU builds.  Therefore, it is being disabled in these
builds as well (see #2474).
Need to clean up failing tests in promoted ATDM builds.
On 'shiller' I ran:
```
intel-debug-openmp-HSW intel-debug-serial-HSW intel-opt-openmp-HSW intel-opt-serial-HSW \
--enable-packages=Piro --configure
```
which returned:
```
PASSED (NOT READY TO PUSH): Trilinos: shiller01
Tue Aug  7 14:58:51 MDT 2018
Enabled Packages: Piro
0) MPI_RELEASE_DEBUG_SHARED_PT_OPENMP => Test case MPI_RELEASE_DEBUG_SHARED_PT_OPENMP was not run! => Does not affect push readiness! (-1.00 …
```
> Disable test Piro_MatrixFreeDecorator_UnitTests_MPI_4 in Intel builds (#2474)

- packages/ifpack2/adapters/thyra/Thyra_Ifpack2PreconditionerFactory_def.hpp
- packages/ifpack2/src/Ifpack2_BandedContainer_def.hpp
- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
- packages/ifpack2/src/Ifpack2_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_Container.hpp
- packages/ifpack2/src/Ifpack2_DiagonalFilter_def.hpp
- packages/ifpack2/src/Ifpack2_DropFilter_def.hpp
- packages/ifpack2/src/Ifpack2_LinearPartitioner_def.hpp
- packages/ifpack2/src/Ifpack2_LocalFilter_def.hpp
- packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
- packages/ifpack2/src/Ifpack2_ReorderFilter_def.hpp
- packages/ifpack2/src/Ifpack2_SingletonFilter_def.hpp
- packages/ifpack2/src/Ifpack2_SparseContainer_def.hpp
- packages/ifpack2/src/Ifpack2_SparsityFilter_def.hpp
Compiling Trilinos with gcc-7.2.0 yields quite a number of unused parameter warnings.  This PR comments out parameter names in function definitions to avoid those warnings.
Just trying to get closer to a clean build.
Ifpack2 still builds just fine.  Letting the @trilinos-autotester do its thing.
These changes were made via a script I wrote.  I've looked over them, but something might've gone wrong that I didn't catch.
> Ifpack2:  Remove Unused Parameter Warnings

- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
This is a speculative change that these values were uninitialized. This is work that @krcb and others did in exploring some bugs.
Added an initialization for normal directions to zero. The normal is allocated as a 3-vector; however, all values can be used. This ensures that the values are initialized to zero appropriately.
> Panzer: Fix for apparently uninitialized values

- packages/tempus/test/DIRK/CMakeLists.txt
- packages/tempus/test/DIRK/Tempus_DIRK_Combined_FSA.cpp
- packages/tempus/test/DIRK/Tempus_DIRK_FSA.hpp
- packages/tempus/test/DIRK/Tempus_DIRK_Staggered_FSA.cpp
For issue #3256.
This splits apart the Combined and Staggered FSA DIRK tests so that each
test only runs a single time integration method (so now 10 separate
tests).  This was done by adding the method to run as a command-line
argument, and if the argument is not supplied, all of the methods are
run.
> Tempus:  Split apart DIRK FSA tests to reduce test run time.

- packages/sacado/src/Sacado_ConfigDefs.h
Apparently clang defines __GNUC__ too.
> Sacado:  Fix macro logic for enabling the new design for clang.

- packages/sacado/test/TestSuite/NestedFadUnitTests.hpp
Depending on what random numbers you got in the nested Fad test, you
could get NaNs in the second derviatives on some machines/compilers.
This fixes that by supplying a fixed seed.
@mhoemmen or @rppawlo, would one of you guys mind approving this?
> Sacado:  Fix possible NaNs in CppUnit nested Fad test

- packages/nox/src-loca/src-lapack/LOCA_LAPACK_Group.C
@trilinos/nox 
Merging #3240 caused a build failure in LOCA if you happen to have `Teuchos_ENABLE_COMPLEX=ON`.  This PR makes it such that the particular file doesn't emit unused parameter warnings, but will still compile with that flag on.
Just trying to get closer to a clean build.
Builds fine for me.  Letting @trilinos-autotester do its thing.
@trilinos/framework, do we want `Teuchos_ENABLE_COMPLEX=ON` for the PR builds?
> NOX:  Fix Build Problem from 3c24e90

- cmake/std/atdm/mutrino/environment.sh
@trilinos/framework @bartlettroscoe 
Change atdm KNL build on mutrino to use `OMP_NUM_THREADS=2` previously it was set to 16.  This change in local testing of the panzer test suite caused the tests to run in about 1/2 of the time.
The panzer tests were being run in about 1/2 the time in the Empire KNL build on mutrino.  This is to get the ATDM build to finish in a comparable time
I tested this locally by runnig tests with the two different values for `OMP_NUM_THREADS`
with `OMP_NUM_THREADS=2` Total Test time is 132.80 sec
```
ctest -j8 -R PanzerAdaptersSTK_CurlLaplacianExample
Test project /lscratch1/jfrye/SRC_AND_BUILD/BUILD
Start 133: PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4
Start 132: PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-3
1/5 Test #132: …
```
> ADTM KNL build on mutrino to use OMP_NUM_THREADS=2

- packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp
- packages/teuchos/parameterlist/test/yaml/YamlParameterList.cpp
This is a fix of a previous change, which would ensure
that if the YAML file read:
mycode:
param1: foo
That the top-level ParameterList would be named "mycode"
instead of "ANONYMOUS".
This change ensures that that is propagated to the names
of all subparameters, e.g. "mycode -> param1" instead of
"ANONYMOUS -> param1".
This prevents user confusion in seeing "ANONYMOUS" despite never writing it in their input file.
> Teuchos: ensure all YAML params get root name

- cmake/std/atdm/ride/environment.sh
CC: @trilinos/teuchos, @trilinos/kokkos, @fryeguy52 
Removes `--mca orte_abort_on_non_zero_status 0` from `srun` command (i.e. one-line change).
This `srun` option was causing tests that call `abort()` on purpose to not terminate when `abort()` is called.  That option was set by recommendation by the Test Bed team to address the `bsub` crashes but it did not seem to work for that (see [TrIL-198](https://software-sandbox.sandia.gov/jira/browse/TRIL-198?focusedCommentId=21012&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21012)).  It seems that the old MPI in that env ignored that option but this new MPI in this env does not :-)
This option was causing some Teuchos tests (see #3287) and Kokkos tests (see #3291) that call `abort()` on purpose to just hang …
> Remove --mca orte_abort_on_non_zero_status 0 from srun on white/ride (#3287, #3291)

- packages/muelu/research/mmayr/composite_to_regions/src/createInput.m
- packages/muelu/research/mmayr/composite_to_regions/src/main.cpp
- packages/muelu/research/mmayr/composite_to_regions/src/mk1DRegionFile.m
- packages/muelu/research/mmayr/composite_to_regions/src/mk2DAppData.m
- packages/muelu/research/mmayr/composite_to_regions/src/mk2DRegionFile.m
- packages/muelu/research/mmayr/composite_to_regions/src/mkAppData.m
- packages/muelu/research/mmayr/composite_to_regions/src/mkCompositeMap.m
- packages/muelu/research/mmayr/composite_to_regions/src/mkMatrixFile.m
- packages/muelu/research/mmayr/composite_to_regions/src/mkRegionsPerGID.m
- packages/muelu/research/mmayr/composite_to_regions/src/muelu_structured.xml
- packages/muelu/research/mmayr/composite_to_regions/src/readRegionFile.m
- packages/muelu/research/mmayr/composite_to_regions/src/regionToProcMap.m
All region-related data files are now written into a user-specified subdirectory to keep the directory structure clean.
* Specify path directory for region data files in Matlab script `createInput.m`
as well as on the command line (command line argument --regDataDir)
* Save/read all region-related input data from this directory
* Rename file `readRegionalFile.m` to `readRegionFile.m` to avoid Matlab warning
Keeping the directory structure clean and moving problem specific output to a subdirectory.
* Closes #3061 
* Related to #2709 
Results of toy problems did not change. However, there is no actual test yet.
> Write region data files into subdirectory (#3061)

- packages/panzer/adapters-stk/test/projection/projection.cpp
- packages/panzer/disc-fe/src/Panzer_L2Projection.hpp
- packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
Application needs access to the target DOF Manager in the L2 projection class.
> Panzer: added global indexer accessor to L2 projection class

- cmake/std/PullRequestLinuxDriver.sh
@trilinos/framework, @rppawlo 
Adds back a missing 'fi' statement got deleted accidentally when resolving a merge conflict.
This should fix this script for PR testing.
Current PRs are crashing due to this (e.g. #3300, #3301).  Therefore, it is urgent to get this merged. 
I did not test this. I fixed this by inspection.  It is a one-line change.
> Fix missing 'fi' statement (#3133)

- packages/panzer/dof-mgr/src/Panzer_IntrepidFieldPattern.cpp
- packages/panzer/dof-mgr/src/Panzer_IntrepidFieldPattern.hpp
- packages/panzer/dof-mgr/test/field_pattern/tFieldPattern2.cpp
Application needed access to underlying basis from field pattern.
> Panzer: add basis accessor to FieldPattern

- cmake/ctest/drivers/atdm/README.md
- cmake/ctest/drivers/atdm/waterman/drivers/Trilinos-atdm-waterman-cuda-9.2-debug.sh
- cmake/ctest/drivers/atdm/waterman/drivers/Trilinos-atdm-waterman-cuda-9.2-opt.sh
- cmake/ctest/drivers/atdm/waterman/drivers/Trilinos-atdm-waterman-gnu-debug-openmp.sh
- cmake/ctest/drivers/atdm/waterman/drivers/Trilinos-atdm-waterman-gnu-opt-openmp.sh
- cmake/ctest/drivers/atdm/waterman/local-driver.sh
- cmake/std/atdm/README.md
- cmake/std/atdm/utils/get_known_system_name.sh
- cmake/std/atdm/waterman/all_supported_builds.sh
- cmake/std/atdm/waterman/environment.sh
- cmake/std/atdm/waterman/tweaks/ALL_COMMON_TWEAKS.cmake
- cmake/std/atdm/waterman/tweaks/CUDA_COMMON_TWEAKS.cmake
CC: @fryeguy52, @mhoemmen, @nmhamster 
This PR branch adds set of GCC and CUDA 9.2 builds for 'waterman' (see [TRIL-213](https://software-sandbox.sandia.gov/jira/browse/TRIL-213)).
The Test Bed machine 'waterman' is an important ATS-2-like test machine for the 'Sierra' machine and ATDM codes need to be able to run on that platform and they need Trilinos builds to do that.
I tested this locally on 'waterman' with both the `checkin-test-atdm.sh` script and the smart Jenkins driver.
On 'watermain' I did:
```
$ bsub -x -Is -n 20 ./checkin-test-atdm.sh all --enable-packages=Kokkos --local-do-all
```
and it passed showing with:
```
PASSED (NOT READY TO PUSH): Trilinos: waterman2
Wed Aug 15 16:30:39 MDT 2018
Enabled Packages: Kokkos
0) …
```
> New ATDM Trilinos 'waterman' builds (TRIL-213)

- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
Fix  #3304
Unnecessary return type (probably typo from when I change the operator as a static function) produces an warning which turns into an error in sierra build.
I confirmed the error is gone in my workstation using gcc pull request script.
> Ifpack2 - remove return type from Ifpack2_BlockTriDiContainer_impl.hpp

- packages/tempus/src/Tempus_StepperBackwardEuler_decl.hpp
- packages/tempus/src/Tempus_StepperBackwardEuler_impl.hpp
- packages/tempus/src/Tempus_StepperOptimizationInterface.hpp
- packages/tempus/test/BackwardEuler/Tempus_BackwardEulerTest.cpp
This PR adds a transient full-space optimization interface to be
used with packages such as ROL with its DynamicConstraint interface.  An
implementation of the interface is provided by BackwardEuler only
(currently).  A test that the interface computes what one would expect
for BackwardEuler is also provided.  The idea is to then implement ROL's
DynamicConstraint interface using Tempus, and then continue to develop
and refine the interface.
The interface should easy to implement for any multistep method.  It is not yet clear how multistage, 1-step methods should be handled.  This PR also does nothing with the objective, since Tempus has no interface for integrating responses (as far as I can tell).
> Tempus:  Add potential full-space optimization interface.

- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
Definition of one importAndFillComplete overload and one exportAndFillComplete overload, both for CrsMatrix, included default values of function arguments.  The default values were already declared in the function declarations above in the same header file.  This commit fixes that.  Thanks @spdomin and @rppawlo for reporting!  I was able to reproduce the build errors with Mac Clang, and I tested the fix there as well.
* Closes #3332 
Mac Clang, OpenMPI.
> Tpetra: Fix #3332 (build errors on Mac Clang)

- packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_decl.hpp
- packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_def.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
- packages/muelu/test/maxwell/Maxwell.xml
- packages/muelu/test/maxwell/Maxwell_complex.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell2D.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellOpenMP.xml
- packages/trilinoscouplings/examples/scaling/Maxwell.xml
- Allow to use RefMaxwell as preconditioner or as standalone solver.
- Correctly interpret 'use kokkos refactor' parameter.
- Show hierarchy label in multigrid summary. (Helpful, when there are multiple of them.)
- Allow different pre- and postsmoothers on finest level of RefMaxwell. (E.g. forward/backward GS)
> MueLu RefMaxwell updates

- cmake/std/atdm/waterman/environment.sh
CC: @fryeguy52, @mhoemmen, @kddevin, @rppawlo 
Switches from OpenMPI 3.1.0 to OpenMPI 2.1.2 env on Power9 'waterman'.  We were told by @nmhamster today that OpenMPI 3.1 really does not work on the Power9 (and is a known issue apparently) and to use the OpenMPI 2.1.2 env instead.
This appears to fix a bunch of failing tests including those in #3344, #3331 and perhaps others.
On 'white' I ran:
```
$ bsub -x -Is -n 20 \
./checkin-test-atdm.sh cuda-opt-Power9-Volta70 \
--enable-packages=Kokkos,Teuchos,Zoltan2,Ifpack2,Tpetra,SEACAS,Panzer \
--local-do-all
```
```
99% tests passed, 2 tests failed out of 645
Subproject Time Summary:
Ifpack2    = 646.49 sec*proc (36 tests)
Kokkos     = 475.50 sec*proc (27 tests)
Panzer     = 7880.59 sec*proc (158 tests)
SEACAS     =  24.01 …
```
> Switch from OpenMPI 3.1.0 to 2.1.2 on 'waterman' (TRIL-213)

- packages/panzer/mini-em/example/BlockPrec/main.cpp
- packages/panzer/mini-em/example/BlockPrec/solverMLRefMaxwell.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell2D.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellOpenMP.xml
- packages/panzer/mini-em/src/closures/MiniEM_ClosureModel_Factory_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_Conductivity.hpp
- packages/panzer/mini-em/src/closures/MiniEM_Conductivity_impl.hpp
- packages/panzer/mini-em/src/closures/MiniEM_InversePermeability.hpp
- packages/panzer/mini-em/src/closures/MiniEM_InversePermeability_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_CurlCurl.cpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_CurlCurl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_CurlCurl_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSetFactory.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_OperatorRequestCallback.cpp
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
- Add conductivity term. (Defaults to zero.)
- Build Schur complement directly instead of approximating it.
- Solve sub-blocks of EM system one-by-one instead of using a block-preconditioner.
- Solve face mass matrix using diagonal preconditoner instead of multigrid.
> MiniEM changes

- cmake/std/PullRequestLinuxDriver.sh
Started at -j22 and was overloading memory on 142
This moves to -j18 which will hopefully be a good data point.
The -j22 when running two jobs on 142, 143, and 144 runs the node out of memory and swaps pretty hard.  The expectation is that this will actually produce faster runs by eliminating or reducing the swapping. We should bisect to a good point based on direct observations.
> Start of testing to determine what level of -j is acceptable

- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
Fixing a bug by adding the appropriate typedef.
This fixes a build issue in MueLu when kokkos is enabled
* Closes #3378 
Local build is now successful with `KOKKOS_REFACTOR=ON`
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] These changes break backwards compatibility.
> MueLu: fix #3378

- packages/teuchos/numerics/src/Teuchos_BLAS.cpp
- packages/teuchos/parameterlist/src/CMakeLists.txt
- packages/teuchos/parameterlist/src/Teuchos_XMLPerfTestArchive.cpp
- winsock2.h should be lowercase on case-sensitive fs
- link ws2_32 with cmake rather than the msvc-specific macro
> Allow base packages to build with MinGW

- packages/epetraext/src/inout/EpetraExt_HDF5.cpp
- packages/epetraext/src/inout/EpetraExt_HDF5.h
- packages/epetraext/test/inout/CMakeLists.txt
- packages/epetraext/test/inout/EpetraExt_HDF5_UnitTest.cpp
@trilinos/EpetraExt
Nested groups are not handled correctly in EpetraExt_HDF5. These groups are denoted by `/Group A/Group B/Group C/data`. Writing and reading from these groups actually works fine, just the `IsContained` method, which only does some safety checks, does not handle them correctly.
I also added a missing const while I was working on the code anyway.
Reason why one might need this is when writing a data structure which contains an array of `Epetra_Vectors`. Doing this without nested groups would look like a mess since all data is sorted alphabetically.
A new unit test file was added and tests were added to confirm the behaviour of the changed functionality.
> EpetraExt: Recursively check for existing HDF5 groups

- packages/teko/src/Teko_Utilities.cpp
Teko's explicitAdd wouldn't work if a sub-block of either of the block matrices being added was a Thyra zero operator. These changes allow for that case.
This came up in EMPIRE where a jacobean was constructed by summing two block matrices. In one of the sub-blocks, a Thyra zero op was being added to a wrapped Tpetra CRS matrix, and it broke.
All existing Teko tests still pass. A branch of EMPIRE has verified that the above mentioned sum is successful.
> Teko explicitAdd with zero ops

- cmake/std/atdm/waterman/tweaks/CUDA-OPT-POWER9-VOLTA70.cmake
- cmake/std/atdm/waterman/tweaks/GNU-OPT-OPENMP-POWER9-VOLTA70.cmake
Disable the test:
Piro_MatrixFreeDecorator_UnitTests_MPI_4
On the builds:
Trilinos-atdm-waterman-gnu-opt-openmp
Trilinos-atdm-waterman-cuda-9.2-opt
@trilinos/framework, @bartlettroscoe 
the test `Piro_MatrixFreeDecorator_UnitTests_MPI_4` has been failing consistently on waterman builds and the agreed course of action is to disable the test for these two builds see issue: #2474
> Disable piro test that is failing on waterman ATDM builds

- packages/panzer/adapters-stk/test/projection/projection.cpp
- packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
Added computation of mass matrix for vector DOFs to L2Projection. This really just amounted to using basis_vector instead of basis_scalar in a few places.
This provides a nice, simple interface to construct mass matrices for HCurl and HDiv fields now.
I added a test to the projection unit test that uses L2Projection to build an HCurl mass matrix. It's on a uniform quad mesh, so I know exactly what the mass matrix should look like, so I construct the mass matrix that way as well. The matrices are the same to a tolerance of 1e-14.
> Panzer hcurl mass from l2projection

- cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP_env.sh
- cmake/std/sems/get_default_modules.sh
@dridzal, @mhoemmen
The default SEMS env should match the env used in the post-push CI build.
This change should have been made when the CI build was updated to use OpenMPI
1.10.1.
NOTE: This also updates the default CMake to 3.11.1.
This should resolve the errors reported in #3407.
STK no longer supports OpenMPI 1.6.5 (see #3407)
I just loaded the env manually with:
```
$ . cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP_env.sh
$ module list
Currently Loaded Modulefiles:
1) sems-env
2) atdm-env
3) sems-python/2.7.9
4) atdm-cmake/3.11.1
5) sems-git/2.10.1
6) atdm-ninja_fortran/1.7.2
7) sems-gcc/4.8.4
8) sems-openmpi/1.10.1
9) sems-boost/1.63.0/base
10) sems-zlib/1.2.8/base
11) sems-hdf5/1.8.12/parallel
12) sems-netcdf/4.4.1/exo_parallel
13) sems-parmetis/4.0.3/parallel …
```
> Switch SEMS env default to match GCC 4.8.4 OpenMPI 1.10.1 CI build (#3407)

- packages/pamgen/src/CMakeLists.txt
- packages/pamgen/src/Random.h
- USE_MATH_DEFINES macro is needed for the bessel functions j0/j1
- seems mingw has the same rand/srand apis than msvc
> Allow pamgen to compile with MinGW

- packages/seacas/applications/explore/CMakeLists.txt
The `explore` executable was not being installed in a Trilinos build due to an incorrect logic
in the CMakeLists.txt file.  In SEACAS, the `explore` executable is also symlinked to `grope` which was the previous name of the `explore` executable.  This symlink is not installed in a Trilinos build, but the logic to avoid this also incorrectly included not installing the `explore` executable also.
> SEACAS: Install explore on all systems; symlink on SEACAS only

- packages/stk/stk_io/stk_io/IossBridge.cpp
- packages/stk/stk_io/stk_io/OutputParams.hpp
- packages/stk/stk_io/stk_io/SidesetTranslator.hpp
- packages/stk/stk_io/stk_io/StkIoUtils.cpp
- packages/stk/stk_io/stk_io/StkMeshIoBroker.cpp
- packages/stk/stk_io/stk_io/StkMeshIoBroker.hpp
- packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp
This imports stk development as of
commit e27c191218c3e6412114091434afae1417cb74d0
Author: Alan Williams <william@sandia.gov>
Date:   Sun Sep 9 13:03:52 2018 -0600
Add ifdefs for MPI_VERSION in stk CommNeighbors class.
CommNeighbors uses MPI_Neighbor* functions, which only exist in
MPI implementations which support the MPI 3 standard. In the case
of building with an MPI implementation older than that (which is
rare, but Trilinos still has a build for OpenMPI 1.6),
the code will still build but a run-time error will occur,
stating that the user must use a newer MPI if they wish to use
the stk CommNeighbors class.
Change-Id: I365923bb52ae6aef5ef73dd69470d104b650c357
Reviewed-on: https://sierra-git.sandia.gov:4443/349628
Tested-by: Mark E Hamilton <sierra@sandia.gov>
Reviewed-by: Kendall …
> Import of stk development from Sierra stream

- cmake/std/atdm/ride/environment.sh
issue: #3288
switch the netcdf module that is loaded for the builds on ride/white
to address some failing tests on white/ride
> Chnage the ATDM build on ride/white to use different netcdf

- packages/nox/src/NOX_Solver_SingleStep.C
- packages/nox/test/epetra/Thyra/Thyra_SingleStepSolver_1D.C
Minor fix to SingleStep solver so that the ls tolerance can be set from main solver plist. It was passing  the wrong sublist to stratimikos resulting in the default tolerance was always being used.
> NOX: Fix single step parsing

- cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP_env.sh
- cmake/std/sems/checkin-test-sems.sh
It was passing in the arguments to checkin-test-sems.sh to the soruce script
which is not what you want.  This is a silly bash behavior.  It should be
fixed in all use cases now.
> Fix checkin-test-sems.sh

- packages/nox/src-thyra/NOX_LineSearch_SafeguardedDirection.cpp
- packages/nox/src-thyra/NOX_LineSearch_SafeguardedDirection.hpp
- packages/nox/src/CMakeLists.txt
- packages/nox/src/NOX_GlobalData.C
- packages/nox/src/NOX_GlobalData.H
- packages/nox/src/NOX_LineSearch_MoreThuente.C
- packages/nox/src/NOX_LineSearch_MoreThuente.H
- packages/nox/src/NOX_LineSearch_Polynomial.C
- packages/nox/src/NOX_LineSearch_Polynomial.H
- packages/nox/src/NOX_LineSearch_SafeguardedStep.C
- packages/nox/src/NOX_LineSearch_SafeguardedStep.H
- packages/nox/src/NOX_LineSearch_Tensor.C
- packages/nox/src/NOX_LineSearch_Tensor.H
- packages/nox/src/NOX_LineSearch_Utils_Counters.C
- packages/nox/src/NOX_LineSearch_Utils_Counters.H
- packages/nox/src/NOX_SolverStats.hpp
- packages/nox/src/NOX_Solver_TensorBased.C
- packages/nox/src/NOX_Solver_TensorBased.H
Added a statistics block to global data. Have all line searches now logging statistics to this.
> NOX: aggregate line search statistics

- packages/nox/src/NOX_Abstract_PrePostOperator.H
- packages/nox/src/NOX_PrePostOperator_Vector.C
- packages/nox/src/NOX_PrePostOperator_Vector.H
- packages/nox/src/NOX_Solver_AndersonAcceleration.C
- packages/nox/src/NOX_Solver_InexactTrustRegionBased.C
- packages/nox/src/NOX_Solver_LineSearchBased.C
- packages/nox/src/NOX_Solver_PrePostOperator.H
- packages/nox/src/NOX_Solver_SingleStep.C
- packages/nox/src/NOX_Solver_TrustRegionBased.C
- packages/nox/test/basic/NOX_PrePostOperatorVector.C
Add an observer that triggers in the solver->step() method just before the solution is updated. Required by an application that needs to modify the update.
> NOX: add observer for solution update

- packages/stk/stk_io/stk_io/IossBridge.cpp
- packages/stk/stk_unit_tests/stk_io/UnitTestWriteSTKMesh.cpp
- packages/stk/stk_util/stk_util/parallel/CommNeighbors.cpp
This imports development as of the commit
commit 9803baddc8e8cdf021c51385b263d1dfcbde8e8a
Author: David Glaze <djglaze@sandia.gov>
Date:   Tue Sep 11 16:09:14 2018 -0600
StkIo: fix issue with inconsistent number of nodeset variables
Change-Id: If0ee587658259585a67a0e0e6cee0d1ed52eba1c
Reviewed-on: https://sierra-git.sandia.gov:4443/349695
Reviewed-by: Alan B Williams <william@sandia.gov>
Tested-by: David Jason Glaze <djglaze@sandia.gov>
and is designed to fix issue #3377
@trilinos/stk 
* Closes #3377 
- [ x ] I have added tests to cover my changes.
> Import stk development from the sierra stream

- packages/tpetra/core/test/Blas/CMakeLists.txt
- packages/tpetra/core/test/Blas/gemm.cpp
@trilinos/tpetra @trilinos/framework 
One Tpetra test was timing out in the ATDM gcc-debug-openmp environment.  I split that test into four tests.
I do not understand why the original test took twice as long to run in the ATDM environment on white than in my environment using the ATDM scripts (see times in #3417) .  But I don't have time or interest to investigate right now.  This change allows the ATDM team to make progress.
#3417 
mac osx clang
> Tpetra:  Broke one test into four to avoid timeouts in ATDM environment #3417

- packages/epetra/cmake/Epetra_config.h.in
While this is just good practice in most cases, it is
critical in getting the builds to work with sierra's
build system,
> This commit just adds a Redundant Include Guard to Epetra_config.h.in

- packages/kokkos-kernels/unit_test/sparse/Test_Sparse_spgemm.hpp
Address Trilinos issue #3438, incorporates part of fix from
PR kokkos/kokkos-kernels#290
@trillinos/kokkos-kernels
> KokkosKernels: Fix for spgemm unit_test mkl macro

- sampleScripts/Sandia-SEMS/test_tpetra_sandia
In Tpetra's test script, updated modules used on white.
These modules use OpenMPI 2 and Cuda 9.2 
All tests pass as of 9/18/18.
> Tpetra:  Updated modules for tests on white.

- cmake/std/atdm/ride/environment.sh
Here, just the MPI implementation is swapped out but the TPLs for OpenMPI
3.1.0 remain (because they have not been built for the GCC 7.2.0 + OpenMPI
2.1.2 + CUDA 9.2).  It is not clear how this can work but it is all that we
can do without the TPLs properly built for this env.
I also switched to the GCC 7.2.0 + OpenMPI 2.1.2 + CUDA 9.2 env for the GNU
non-CUDA build just to be consistent.
We want the `Ifpack2_BlockTriDiContainerUnitAndPerfTests_MPI_4` test failure to go away described in #3290.  It looks like OpenMPI 3.1.0 is not doing the right thing with CUDA memory but OpenMPI 2.1.2 appears to be.
On 'white' I ran:
```
$ bsub -x -Is -n 20 ./checkin-test-atdm.sh  all \
--enable-packages=Kokkos,Ifpack2,SEACAS,Panzer --local-do-all
```
and all of the builds and tests …
> Swap out OpenMPI 3.1.0 for OpenMPI 2.1.2 on white/ride (#3290)

- packages/kokkos-kernels/unit_test/sparse/Test_Sparse_spgemm.hpp
Removes spgemm cusparse testing as it also fails from kokkoskernels and it is not tested in spotcheck. To make trilinos nightly tests running, we need to remove this from trilinos and solve the problem in kokkoskernels. 
#3438
> KokkosKernels - remove cusparse testing in spgemm.

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
Fix round-off issue in the std dev calculation for StackedTimer.
> Resolved roundoff issue in stddev calc

- packages/PyTrilinos/src/Teuchos_Comm.i
- packages/PyTrilinos/test/testTeuchos_Comm.py.in
When `MPI4PY` was enabled, the `Teuchos.MpiComm`was built without a constructor. This was due to some subtle interplay between extensions to the `Teuchos.MpiComm` constructors and the `%ignore`-ing of others. This branch fixes that problem.
PyTrilinos was not working with `MPI4PY` enabled. Now it does. This allows users to pass an `mpi4py` `MPI_Comm` object to a `PyTrilinos.Teuchos.MpiComm` constructor, which in turn allows for sub-communicators.
Closes #3461 
Automated testing has not been set up for PyTrilinos, but I have tested it on my MacBook Pro.
> PyTrilinos: Fix Teuchos MpiComm constructor when MPI4PY enabled

- packages/PyTrilinos/src/Tpetra.i
- packages/PyTrilinos/src/gen_teuchos_rcp.py.in
- packages/PyTrilinos/test/testTeuchos.py.in
Tpetra classes that were moved to the `Tpetra::Classes` namespace broke the PyTrilinos wrappers for Tpetra. This update fixes those wrappers
`PyTrilinos.Tpetra` now builds and its tests pass.
* Closes #3450 
Automatic testing for PyTrilinos has not been set up yet, but the tests pass on my MacBook Pro.
> PyTrilinos: Fix wrappers for Tpetra classes moved to Classes namespace

- packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov_parameters.hpp
Fix Clang 3.8.1 build issues.
* Closes #3486 
Linux, GCC 4.8.4, OpenMPI 1.10.1.
> Belos: Fix #3486 (Clang 3.8.1 build)

- cmake/ctest/drivers/apollo/cron_driver.sh
- cmake/ctest/drivers/artemis/cron_driver.sh
- cmake/ctest/drivers/enigma/cron_driver.sh
- cmake/ctest/drivers/geminga/cron_driver.sh
- cmake/ctest/drivers/perseus/cron_driver.sh
- cmake/ctest/drivers/ride/cron_driver.sh
- cmake/ctest/drivers/rocketman/cron_driver.sh
- cmake/ctest/drivers/shiller/cron_driver.sh
- cmake/ctest/drivers/trappist/cron_driver.sh
Changes over to CMake 3.10+ on all CTest/CDash drivers (see the individual commits for more details).
The only references that I can find to CMake versions that using SEMS are:
```
$ cd Trilinos/
$ find cmake/ctest/ -type f -exec grep -nH cmake {} \; \
grep -v "[.]cmake" | grep "\(2[.]8\|3[.]\)" | grep -v "3[.]10[.]3" | grep -v "3[.]11[.]" | sort
cmake/ctest/drivers/apollo/jenkins_driver.sh:39:module load cmake/2.8.11
cmake/ctest/drivers/artemis/jenkins_driver.sh:39:module load cmake/2.8.11
cmake/ctest/drivers/ictinus/cron_driver.sh:29:export PATH=/Users/jmwille/install/git/bin:/Users/jmwille/install/cmake-2.8.4/bin:/Users/jmwille/install/gcc-4.4.6/openmpi-1.4.3/bin:/
cmake/ctest/drivers/perseus/jenkins_driver.sh:39:module load cmake/2.8.11 …
```
> 1761 change to cmake 3.10

- cmake/load_sems_dev_env.sh
- cmake/std/sems/get_default_modules.sh
Allow to use other shells when using `cmake/load_sems_dev_env.sh`.
Both bash and zsh seem to work.
Addresses Issue #3515
> CMake: Make sems script POSIX compatible

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Small fix to `transferAndFillComplete`: Avoid dereferencing null pointer.
> Tpetra transferAndFillComplete: Avoid dereferencing of null-pointer

- cmake/std/PullRequestLinuxDriver.sh
We are seeing more issues when communicating to github
so I am adding a retry loop.
This adds a loop to retry fetching the source branch from GitHub. We see this failure infrequently.
This was tested by setting up an autotester that looked at PR's into this branch on my fork and creating a whitespace commit on a throw-away branch. The resulting PR can test the driver script as the target branch.
> PullRequestLinuxDriver.sh: add a retry loop for the github fetch

- cmake/std/atdm/ATDMDevEnvSettings.cmake
- cmake/std/atdm/README.md
- cmake/std/atdm/chama/environment.sh
- cmake/std/atdm/load-env.sh
- cmake/std/atdm/load_matching_env.sh.in
- cmake/std/atdm/mutrino/environment.sh
- cmake/std/atdm/rhel6/environment.sh
- cmake/std/atdm/serrano/environment.sh
- cmake/std/atdm/shiller/environment.sh
- cmake/std/atdm/toss3/environment.sh
- cmake/std/atdm/utils/set_build_options.sh
- cmake/std/atdm/waterman/environment.sh
@bathmatt, @jmgate, @fryeguy52 
Install the ATDM configuration scripts to allow loading it from and installation of Trilinos. See the updated README.md file for details.
I also renamed the env var set in atdm/load-env.sh from JOB_NAME to
ATDM_CONFIG_JOB_NAME.  This is to avoid confusing and other problems with the
unnamespaced var JOB_NAME which is set by Jenkins.  This does not change the
behavior of the CTest -S jenkins drivers that directly read from JOB_NAME.
EMPIRE requires that the Trilinos install base directory have a file called `configure.sh` that can be sourced in order to load the env needed to use that installation of Trilinos.   This allows that by configuring with:
```
-D CMAKE_INSTALL_PREFIX=<install-prefix> \
-D ATDM_INSTALLED_ENV_LOAD_SCRIPT_NAME=configure.sh \
```
This …
> Add install of ATDM env scripts, rename JOB_NAME to ATDM_CONFIG_JOB_NAME (#2689)

- packages/muelu/test/unit_tests_kokkos/MueLu_TestHelpers_Common_kokkos.hpp
- packages/muelu/test/unit_tests_kokkos/SaPFactory_kokkos.cpp
Follow-up fix for PR #3419. Set the output stream correctly in MueLu's Kokkos refactor unit tests.
> MueLu: Fix wrong method to set output stream

- cmake/std/PullRequestLinuxDriver.sh
must dereference shell variables when used.
Broke PR #3527
> PullRequestLinuxDriver.sh: correct syntax error

- packages/amesos/src/Amesos_Superludist.cpp
- packages/amesos/test/TestOptions/TestSuperludist.cpp
This issue is with xsdk build of trilinos with latest superlu_dist [version 5.4.0
This patch fixes this issue for me.
Either a merge  - or  a more appropriate patch - that gets the trilinos build working with superlu_dist v5.4.0 would be great!
This incompatibility also prevents petsc from using trilinos with superlu_dist-v5.4.0
cc: @keitat  as xsdk liaison to trilinos - please follow-up on this issue - and fill up all the necessary trilinos requirements  so that PR gets accepted or this incompatibility is resolved via a different patch
cc: @jwillenbring, @curfman
> superlu_dist: compile fix for v5.4.0

- cmake/std/atdm/mutrino/tweaks/ALL_BUILDS.cmake
@trilinos/seacas, @gsjaardema 
The commands run fine when run manually but for some reason ctest refuses to
run these and reports a:
```
Unable to find required file: CMND_PATH-NOTFOUND
```
error.
It was requested to disable these tests.
Tests have been failing for some time and it is desired to disable them (see https://github.com/trilinos/Trilinos/issues/3496#issuecomment-425243790).
I tested this on 'mutrino' by running:
```
$ cd ~/Trilinos.base/BUILDS/MUTRINO/CHECKIN/
$ ./checkin-test-atdm.sh intel-opt-openmp-HSW intel-opt-openmp-KNL \
--enable-packages=SEACAS --configure
```
The showed the correct disables:
```
$ find . -maxdepth 2 -name "configure.out" -exec grep -nH "NOT added" {} \; | grep "_DISABLE" | grep exodus | grep -v "unit_tests"
./intel-opt-openmp-KNL/configure.out:409:-- …
```
> Disable four exodus SEACAS tests failing with Not Run on mutrino (#3496)

- packages/PyTrilinos/src/PyTrilinos_IFPACK_Headers.hpp
As per #3245 and #3441, the file `PyTrilinos_IFPACK_Headers.hpp` includes a mis-capitalized `IFPACK_ConfigDefs.h`.
Builds correctly on Mac OS X because the file system is case-insensitive, but fails to build on other platforms.
* Closes #3245, #3441 
Unfortunately, only on my MacBook Pro, so the test is incomplete.
> PyTrilinos: Ifpack capitalization fix

- cmake/std/atdm/ride/environment.sh
CC: @trilinos/seacas, @fryeguy52
This changes to use a new consistent GCC 7.2.0 + OpenMPI 2.1.2 + CUDA 9.2 + TPLs env on 'white' and 'ride'.  Before this, on 'white' we were using OpenMPI 2.1.2 to compile and link libraries and execuables in Trilinos but were linking against TPLs built with OpenMPI 3.1.0 (see #3290).  This new set of modules uses OpenMPI 2.1.2 for the TPLs as well to create a 100% consistent env.
@nmhamster noted that he had to reduce the compiler optimization level of HDF5 from `-O3` to `-O2` or you get a could SEACAS tests that fail, as described in #3288.  (So the problem in #3288 was not the NetCDF configuration but was the HDF5 compiler options).
It was not good to be using a mixture of OpenMPI 2.1.2 and OpenMPI 3.1.0 on 'white'.  And we need to use OpenMPI 2.1.2 to …
> Switch to new devpack/20180521/openmpi/2.1.2/gcc/7.2.0/cuda/9.2.88 env on 'white' and 'ride' (#3290)

- packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp
- packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
@trilinos/tpetra @trilinos/kokkos-kernels @kddevin @kyungjoo-kim 
`KokkosBlas::dot` for 1-D Views gave incorrect complex dot product results, due to incorrect assumptions about the Fortran ABI for complex return values.  This made Tpetra tests fail with complex enabled.  I fixed this by patching kokkos-kernels not to use the BLAS for those functions.
NOTE: I have not yet patched kokkos-kernels.  https://github.com/kokkos/kokkos-kernels/issues/307 discusses various ways to fix the issue.  I would prefer to let kokkos-kernels developers decide how to do that in a more permanent way.
Salinas uses Tpetra with complex arithmetic.
* Closes #3493
* Related to https://github.com/kokkos/kokkos-kernels/issues/307 
Mac, Clang, OpenMPI.
> kokkos-kernels: Fix #3493 (incorrect dot product results & segfaults for complex Tpetra::MultiVector)

- packages/PyTrilinos/src/NOX.__init__.i
Removes includes of non-existent `NOX_Version.h`
* Closes #3548 
On my MacBook Pro with PyTrilinos, NOX, and NOX prerequisites enabled, with the exception of Tpetra (see #3456)
> PyTrilinos: Remove includes of NOX_Version.h

- packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter_Def.hpp
It does not make sense to call the observer when a particular Tempus
step did not complete successfully. Adding logic to only call observer
upon successful completion of Tempus step.
Feature request by @bartgol for Albany.
Run Piro and Albany tests.
> Piro: adding feature request for Tempus when called through Piro.

- packages/anasazi/src-rbgen/RBGen_Filter.hpp
- packages/tpetra/core/inout/Tpetra_MatrixIO.cpp
- packages/tpetra/core/src/Tpetra_Export_def.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
@trilinos/anasazi
Replace bind1st and bind2nd by lambda functions.
As of C++11 `std::bind1st` and `std::bind2nd` are deprecated and removed in the C++17 standard.
In particular, `libc++` doesn't contain them anymore if compiling with `std=c++17`. They can be replaced by simple lambdas.
I compiled Trilinos.
This PR requires C++11
> Replace bind1st and bind2nd by lambdas

- packages/anasazi/src-rbgen/RBGen_Filter.hpp
- packages/tpetra/core/inout/Tpetra_MatrixIO.cpp
- packages/tpetra/core/src/Tpetra_Export_def.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
Cherry-pick PR #3571 into 12.14 release, by request of @masterleinad.
Original commit message: "Avoid bind1st and bind2nd" (in Anasazi and Tpetra).
> Cherry-pick PR #3571 into 12.14 release

- packages/PyTrilinos/src/gen_teuchos_rcp.py.in
A build script `get_teuchos_rcp.py` was not parsing the location of the `mpi.h` header accurately on all systems. These changes make that parsing exercise more robust.
Reported in #3215 
* Closes #3215
This has only been tested in an environment where it was already working. So it did not introduce any build errors, but it should help fix what it was intended to fix.
> PyTrilinos: Parse MPI version properly

- packages/tempus/src/Tempus_StepperDIRK_impl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
To hopefully catch an over/under-flow bug in the comparison `err > 1.0`
[All Tempus tests are passing](https://github.com/trilinos/Trilinos/files/2439833/Tuesday-2018-10-02-15_45-build_tempus_dev-test.log)
> Tempus: add `abs` guard around embedded error estimator

- cmake/std/atdm/waterman/tweaks/CUDA-9.2-DEBUG-CUDA-POWER9-VOLTA70.cmake
- cmake/std/atdm/waterman/tweaks/CUDA_COMMON_TWEAKS.cmake
- cmake/std/atdm/waterman/tweaks/GNU-DEBUG-OPENMP-POWER9.cmake
@trilinos/framework @bartlettroscoe 
This disables the test `PanzerAdaptersSTK_MixedPoissonExample-ConvTest-Hex-Order-3` on the atdm waterman builds:
* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-waterman-cuda-9.2-opt
see #2751 
This also disables a unit test that is timing out in the test `KokkosKernels_sparse_serial_MPI_1` on the atdm waterman builds:
* Trilinos-atdm-waterman-cuda-9.2-debug
* Trilinos-atdm-waterman-gnu-debug-openmp
see #3438 and #2964 
`KokkosKernels_sparse_serial_MPI_1` does not timeout anymore on these builds when I tested it
Trilinos-atdm-waterman-cuda-9.2-debug
```
7/8 Test #6: KokkosKernels_sparse_serial_MPI_1 ...   Passed  230.71 sec
```
Trilinos-atdm-waterman-gnu-debug-openmp
```
6/7 Test #5: KokkosKernels_sparse_serial_MPI_1 ...   Passed  217.19 sec …
```
> Atdm waterman disables

- packages/PyTrilinos/example/exIsorropia.py.in
- packages/PyTrilinos/src/Isorropia.Epetra.i
- packages/PyTrilinos/test/testIsorropia.py.in
- packages/PyTrilinos/test/testTeuchos_RCP.py.in
When I test `PyTrilinos.Isorropia` objects, I now use a ParameterList that sets the Zoltan `debug_level` to `0`.
This makes testing output cleaner.
* Closes #3586 
I built a PyTrilinos with all packages enabled and ran the Isorropia tests directly from the command-line (as opposed to using `ctest`).
> PyTrilinos: Suppress Zoltan Debugging Output

- PackagesList.cmake
@trilinos/pumi
Fixes https://github.com/SCOREC/core/issues/187 when built against https://github.com/SCOREC/core/commit/7b56bcbaea90ad3ff81679358264c029ec0b0fcb (or later).
The PUMI `lion` package was modified to add control over all print statements to conform with XSDK policy M11.  `lion` did not have the necessary TriBITS support files defined which resulted in the Trilinos build failing.
* Closes  https://github.com/SCOREC/core/issues/187
A build with and without `LION_COMPRESS` enabled was successful on SCOREC RHEL7 workstations using the following environment and configure scripts:
envRhel7.sh
```
module load \
cmake/3.12.1-wfk2b7e \
gcc/7.3.0-bt47fwr \
mpich/3.2.1-niuhmad \
openblas/0.3.2-nro36nb \
boost/1.68.0-6n3iupn \
parmetis/4.0.3-int64-ssgv6kc \
netcdf/4.6.1-7m62oeb
``` …
> PUMI: add package 'lion'

- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp
- packages/kokkos-kernels/src/batched/KokkosBatched_Util.hpp
This fix allows the use of complex float #3574. It also fixes an error in unit test. FYI: the error is converting data type.
> kokkos kernels - add complex float static assert testing

- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPipeline.hpp
- packages/shylu/shylu_node/hts/src/shylu_hts_impl_def.hpp
@trilinos/shylu @trilinos/belos 
@kyungjoo-kim , this might not fully build until the kokkos-kernels SIMD fixes have come in (see #3574).
> ShyLU, Belos: Fix build errors when Scalar=complex<float> is enabled

- packages/zoltan2/test/helpers/UserInputForTests.hpp
This header caused multiple unit test compilations
to fail when warnings-as-errors was enabled as the
size() function has a parameterized retrun type. I
change to the typedef used in Teuchos to determine
the function return type.
> zoltan2: remove warning from unit tests

- cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake
- cmake/tribits/ctest_driver/TribitsCTestDriverCoreHelpers.cmake
Fixes `TRIBITS_CTEST_DRIVER()` when passing `in ${PROJECT_NAME}_EANBLE_ALL_PACKAGES=ON` and `${PROJECT_NAME}_EXCLUDE_PACKAGES=<pkg0>,<pkg1>,...`.   This is well unit tested in TriBITSPub/TriBITS#269.
Technically this does break backward compatibility for the all-at-once mode but it does not touch the packages-by-package mode.  But the impact of this behavior change should only be good.
Without this fix, the Trilinos "Clean" builds are broken because the inner configure does not disable PyTrilinos (see https://github.com/trilinos/Trilinos/issues/1761#issuecomment-429112174).
This is well tested in TriBITS.  See TriBITSPub/TriBITS#269.  The Trilinos PR testing system currently does not use `TRIBITS_CTEST_DRIVER()` so it does not need to be tested as part of Trilinos PR …
> TRIBITS_CTEST_DRIVER(): Correctly pass in excluded package disables for all-at-once approach

- cmake/std/atdm/shiller/environment.sh
CC: @jmgate, @fryeguy52 
Looks like 'shiller' does not mount /home at /ascldap/users/ while 'hansen'
does (where we run ATDM Trilinos builds).  This is fixed by switching to
/home/rabartl/ which works on both 'hanen' and 'shiller'.
Builds on 'shiller' can't find CMake 3.11.2 without this change.  Needed for EMPIRE adoption as per https://software-sandbox.sandia.gov/jira/browse/TRIL-222.
On this branch I on 'shiller' I did:
```
$ . cmake/std/atdm/load-env.sh gnu-opt-openmp
Hostname 'shiller01' matches known ATDM host 'shiller' and system 'shiller'
ATDM_CONFIG_TRILNOS_DIR = /home/rabartl/Trilinos.base/Trilinos
Setting default compiler and build options for ATDM_CONFIG_JOB_NAME='gnu-opt-openmp'
No KOKKOS_ARCH specified so using system default
Using hansen/shiller compiler stack GNU to build …
```
> Fix path to cmake on 'shiller' (TRIL-222)

- cmake/ExtraRepositoriesList.cmake
NOTE: There is no @trilinos/sundance team and there is no `Sundance` label to attach
It looks like the configure fo Sundance against Trilinos 'develop' has been
failing since 6/1/207 (see #3611).  Also, Sundance development appears to be
dead (the last commit to the 'master' branch was back in 6/27/205).
Therefore, it makes sense to stop including Sundance against the list extra
repos that Trilinos is tested against.
Switching to the all-at-once mode in #1761 resulted in the Sundance configure failure bringing down building and testing of any Trilinos packages in the build `Linux-GCC-4.9.3-openmpi-1.8.7_Debug_DEV_Werror` build (see #3611).
I did not test it.  But PR testing will build and test every PT package because of the file that I modified.
> Remove Sundance from list of extra repos (#3611, #1761)

- PackagesList.cmake
Since Sundance has not configured correctly against Trilinos 'develop' in 16
months and has not had a commit in about 3 years (see #3611), it seems
reasonble to remove Sundance an an offically supported Trilinos "inserted
package".
But if someone wants to get Sundance working against Trilinos 'develop', they
can always add Sundance as an extra repo and extra package.  Since there are
no down-stream dependencies on Sundance in Trilinos, nothing would be lost.
This would be a trivial thing to set up.
The current motiviation for making this change is to clean up a nightly
Trilinos build that has an existing clone of Sundance and is failing to
configure (see #3611).
Having Sundance still defined as an inserted package is breaking the WError build (see #3611).
I did not …
> Remove inserted package Sundance (#3611)

- cmake/std/atdm/waterman/tweaks/CUDA_COMMON_TWEAKS.cmake
Re-enables test disabled as part of #3340.
> revert disable of panzer Curl test on waterman #3340

- packages/sacado/example/view_example.cpp
This test is failing for Intel builds for some reason (see #3639).  It only fails
with Intel, and only with high optimization.  Trivial changes to the
kernel make it pass, like adding a print statement or the temporary I
added here.  Smells like an optimization bug.
@fryeguy52 @bartlettroscoe
> Fix view example with Intel compiler for issue #3639

- cmake/std/atdm/README.md
- cmake/std/atdm/cee-rhel6/environment.sh
- cmake/std/atdm/sems-rhel6/environment.sh
- cmake/std/atdm/utils/get_num_cores_on_machine.sh
@fryeguy52 
See commits for details but this sets the parallel build and test level based on the number of cores on the given rhel6 system.
We don't want to overload a given rhel6 machine like what happened with the 'sems-rhel6' builds over the last two days (see https://software-sandbox.sandia.gov/jira/browse/TRIL-228).
I tested with a subset of packages for the 'sems-rhel6' and 'cee-rhel6' builds.
>  Set parallel build level based on cores on machine for 'sems-rhel6' and 'cee-rhel6' builds (TRIL-228)

- cmake/std/PullRequestLinuxDriver.sh
Sample PR to ensure that the force-merge of #3650 does not cause problems with normal PR testing since we touched the `PullRequestLinuxDriver.sh` file.
The force-merge was required due to the chicken-and-egg issue with that script referenced in #3625.  
@prwolfe @jwillenbring 	We aren't intending to merge this, but my edit was to just stick a comment into `PullRequestLinuxDriver.sh` to reference the issue #3625 so if this gets merged it won't really cause any issues... it might even be useful to merge 🤷‍♂️
> Framework: Add sample comment for autotester script

- cmake/std/atdm/waterman/tweaks/CUDA-9.2-DEBUG-CUDA-POWER9-VOLTA70.cmake
@trilinos/kokkos, @fryeguy52 
Now that this test is running and passing in the new build Trilinos-atdm-waterman-cuda-9.2-release-debug (see #3659 and #3633), it is fine to disable this in this full -O3 build.
Failing timing out tests provide no value and cluster up the dashboard with red.  See #3336 and #3633 for motivation.
On 'waterman' I ran:
```
$ ./checkin-test-atdm.sh cuda-9.2-debug-Power9-Volta70 --enable-packages=Kokkos --configure
```
and the configure output showed:
```
-- KokkosContainers_UnitTest_Serial_MPI_1: NOT added test because KokkosContainers_UnitTest_Serial_MPI_1_DISABLE='ON'!
```
> Disable timing-out test KokkosContainers_UnitTest_Serial_MPI_1 in 'waterman' cuda-9.2-debug build (#3336)

- packages/seacas/libraries/exodus/src/ex_utils.c
Recent changes did not fully test all possible #ifdef combinations.  This patch fixes some bad cut/paste inside an #ifdef for non-netcdf-4 builds.
> EXODUS: Fix compile error due to bad cut/paste

- packages/belos/epetra/test/BlockCG/CMakeLists.txt
- packages/belos/epetra/test/BlockCG/test_pseudo_cg_hb.cpp
- packages/belos/src/BelosCGIter.hpp
- packages/belos/src/BelosPseudoBlockCGIter.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/tpetra/test/BlockCG/CMakeLists.txt
- packages/belos/tpetra/test/BlockCG/test_pseudo_bl_cg_hb.cpp
The issue #3338 is the failure of the Tpetra pseudo-block CG test on an important test platform.
There are two issues, one the _STEQR provided by the LAPACK libraries
on that platform is seg faulting and, two, the general condition estimate
computation performed by single-vector/pseudo-block CG is generally wrong.
The condition estimate computation is now implemented for the single-vector
CG kernel, when it wasn't before. Furthermore, it is corrected for the
pseudo-block CG kernel, where it was wrongly storing information when
there was more than one right-hand side.  The LAPACK routine being used to
perform the condition estimation computation is _PTEQR, which has no issues
on the test platform of concern to #3338.
Tests have been fixed for the Tpetra pseudo-block CG, so …
> Fixes condition estimate computation to address issue #3338

- packages/anasazi/epetra/test/OrthoManager/cxx_main.cpp
- packages/anasazi/test/MVOPTester/MyMultiVec.hpp
- packages/anasazi/test/MVOPTester/MySDMHelpers.hpp
- packages/belos/src/BelosMVOPTester.hpp
- packages/belos/src/BelosOrthoManagerTest.hpp
- packages/belos/test/MVOPTester/MyMultiVec.hpp
- packages/teuchos/numerics/src/Teuchos_SerialDenseHelpers.hpp
While addressing issue #2473, I found other places where a random serial dense
matrix was used and expected to be the same in parallel.  The synchronization
method that was used to address the issue in Anasazi has been moved to the
Teuchos serial dense helpers file so that other packages can use this utility
in the generation of tests.  In particular, this utility needed to be integrated
into the MVOP testers for Belos and Anasazi, as well as the Belos orthogonalization
tester.
The assumption that a call to generate a random variable will return the same
value on all processors is false and could have unknown consequences for testing.
While it is unknown if any random failures can be tracked to these changes at this
time, previous issues with Anasazi have been caused by this bad …
> Fixes randomization issue with Teuchos::SerialDenseMatrix in parallel

- cmake/ctest/drivers/trappist/CMakeLists.txt
- cmake/ctest/drivers/trappist/ctest_linux_nightly_mpi_experimental_openmp_refactor_muelu_trappist.gcc.cmake
There are currently no nightly build for KOKKOS_OPENMP_REFACTOR reporting to the dashboard so I am adding one on trappist
> MueLu: adding a KOKKOS_REFACTOR_OPENMP nightly build on trappist

- packages/muelu/example/ParameterList/MLParameterList.cpp
- packages/muelu/test/maxwell/CMakeLists.txt
- Xpetra's CRS matrix does not implement `setAllValues` using Kokkos views for Epetra, so the test shouldn't run.
- Do not run ML parameter test w/ kokkos refactor
Addresses part of #3717
> MueLu tests: Do not run Epetra test w/ kokkos refactor

- cmake/std/PullRequestLinuxDriver.sh
This is a nightmare to get tested as we don't have a good way to
test bash off-line and github almost never hits this fetch error.
I need to either set up a testing framework or better move to
python and unit test it. Grrr...
On my fork in base PR
> PullRequestLinuxDriver.sh: modify the retry loop to actually check numbers

- cmake/std/atdm/README.md
Non-bash developers like @csiefer2 have been gotten tripped up by this.  Hopefully this helps.
> ATDM: Add mention of needing to use bash -l for non-bash users

- packages/stokhos/src/Stokhos_RecurrenceBasisImp.hpp
- packages/stokhos/test/UnitTest/Stokhos_HermiteBasisUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_LanczosUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_NormalizedLegendreBasisUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_Sparse3TensorUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_UnitTestHelpers.hpp
The LAPACK function STEQR doesn't appear to work on IBM Power systems.  In #3658 a solution was found by replacing STEQR with PTEQR, which seems to not have problems on this platform.  This PR replaces usage of STEQR with PTEQR in Stokhos.  However this isn't completely trivial because PTEQR is for symmetric, positive-definite systems where STEQR is for symmetric, indefinite systems (and therefore is a completely different algorithm, which is probably why it works when STEQR doesn't).  So to use PTEQR I had to compute a shift to make the system positive definite.  This caused a few tests to fail due to numerical differences with very tight tolerances, so I had to loosen some of those tolerances to get things to pass.  After these changes, all of the Stokhos tests pass on white.  For issue …
> Replace STEQR with PTEQR in Stokhos for issue #3542

- packages/piro/src/Piro_RythmosSolver.hpp
- packages/piro/src/Piro_RythmosSolver_Def.hpp
Just adding a simple getter  to the solver for Drekar to observers.
> Piro: add getter to access nonlinear solver

- cmake/std/atdm/README.md
I found some typos in this text.
> Fix some typos in about <system_name> and 'cee-rhel6' and 'sems-rhel6' envs

- cmake/std/atdm/waterman/environment.sh
The build Trilinos-atdm-waterman-cuda-9.2-release-debug has been crashing the
last several days and not submitting results to CDash.  I reduced the build
level on Jenkins for this buil to 64 and it retured build results today.
Hopefully reducing this build level to 64 for all builds will avoid these
build crashes.
WE don't like build crashes.  We like results on CDash.
I did not directly test this commit.  The change is trivial and super safe.
> Decrease parallel build level on 'waterman' from 128 to 64 (ATDV-63)

- packages/panzer/adapters-stk/example/CurlLaplacianExample/CMakeLists.txt
- packages/panzer/adapters-stk/example/CurlLaplacianExample/main.cpp
- packages/panzer/adapters-stk/example/MixedPoissonExample/CMakeLists.txt
- packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp
This PR adds multiblock support and corresponding tests for the CurlLaplacian and MixedPoisson example problems. This is to make sure we are testing orientation tools for edge/face bases when multiple element blocks are present. See #3785 for details.
> Panzer multiblock tests

- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
Removing implementation of getLocalMatrix and setAllValues from Xpetra::TpetraCrsMatrix specializations on <SC,int,int,EpetraNode> and <SC,int,long long,EpetraNode>
Fixing a specialization in Xpetra CrsMatrix
This fixes some build errors on the dashboard...
* Closes #3804
> Xpetra: fix issue #3804

- packages/seacas/libraries/exodus/src/ex_create_group.c
- packages/seacas/libraries/exodus/src/ex_open.c
- packages/seacas/libraries/exodus/src/ex_open_par.c
- packages/seacas/libraries/exodus/src/ex_utils.c
Fix build of exodus library if some of the NetCDF variants (such as no HDF5 or no PNetCDF/CDF5 capability) are used.  Fixes #3663.
> EXODUS: Fix so builds with NetCDF variants (no hdf5 and/or cdf5)

- packages/kokkos-kernels/src/graph/KokkosGraph_graph_color_d2.hpp
Removing a dummy comment added in that got merged in by mistake.
I will merge this to remove the dummy comment that shouldn't have been merged in.  
Before I merge it in, I want to look at the testing results in the auto-tester system before I merge it, so do not set AT:AUTOMERGE on this.
> Framework: Removing dummy comment for Kokkos-Kernels Testing

- cmake/std/PullRequestLinuxDriver-Test.sh
- cmake/std/PullRequestLinuxDriver.sh
This splits the PR test driver script into two scripts:
1. PullRequestLinuxDriver.sh
- This script is the first that should be called by auto-testing jobs.  It handles merging the source branch into the target branch.
- The `version` of this script that is run will the one that lives on the _target_ branch.
2. PullRequestLinuxDriver-Test.sh
- This script is called by (1) and handles actually running the test.
- The `version` of this script that is run will be the result of the _source_ branch merged into the _target_ branch.
This reduces the _chicken-and-egg_ (see #3625) problem when updating the testing system.  Specifically, in the past updating the `PullRequestLinuxDriver.sh` script gave a false sense of security when the autotester completed since it only ran the …
> Framework: split PR driver script

- cmake/ctest/drivers/trappist/CMakeLists.txt
- cmake/ctest/drivers/trappist/ctest_linux_nightly_mpi_release_tpetra_trappist.gcc.cmake
Adding a nightly build that enables complex in Tpetra.
I am seeing some tests failures in MueLu today and I am guessing that they are being introduced by upstream packages. So to make sure of that I want to test Tpetra.
Plus it seems to me that a complex build of Tpetra wouldn't be a bad idea.
* Related to #3823
> Tpetra: adding a new nightly build to avoid problems reported in issue #3823

- packages/tpetra/core/test/MultiVector/MultiVector_MicroBenchmark.cpp
This partially addresses issue #3823 reported by @lucbv.
@crtrott provided this fix which allows Tpetra to compile in Cuda builds
with complex enabled.
In a Cuda build with complex<RealType> enabled, the lambda body in a
Kokkos::parallel_for should capture Kokkos::complex<RealType> values,
not std::complex types.
Built without compilation errors on White Kepler nodes with Cuda_Serial enabled.
Configuration script below:
```
export TRILINOS_DIR=/ascldap/users/ndellin/IntegrationTests/Trilinos
module purge
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cuda-9.2-opt-Kepler37
module swap cmake/3.9.6 cmake/3.12.3
PACKAGE1=Tpetra
cmake \
-GNinja \
-DTrilinos_ENABLE_TESTS:BOOL=ON \ …
```
> tpetra: Fix types in MultiVector_MicroBenchmark with complex enabled

- packages/sacado/src/Kokkos_DynRankView_Fad.hpp
With Sacado_ENABLE_HIERARCHICAL_DFAD=ON, as was turned on in PR #3800 in
ATDM builds, a build error (#3845) was seen in the unit tests that disable the
View specializations for Fad, since `is_dynrankview_fad_contiguous<>` is
used without being defined.  I moved the default definition of this
trait class so that it is always defined, which fixed the build errors in my
CUDA build.
> Sacado:  Fix build errors reported in issue #3845.

- cmake/std/atdm/mutrino/tweaks/ALL_BUILDS.cmake
- cmake/std/atdm/ride/tweaks/CUDA-9.2-RELEASE-CUDA-POWER8-KEPLER37.cmake
- cmake/std/atdm/ride/tweaks/CUDA_COMMON_TWEAKS.cmake
- cmake/std/atdm/ride/tweaks/GNU-RELEASE-OPENMP-POWER8.cmake
- cmake/std/atdm/serrano/tweaks/INTEL-DEBUG-OPENMP-BDW.cmake
- cmake/std/atdm/serrano/tweaks/INTEL-RELEASE-OPENMP-BDW.cmake
- cmake/std/atdm/shiller/tweaks/CUDA_COMMON_TWEAKS.cmake
- cmake/std/atdm/shiller/tweaks/GNU-RELEASE-OPENMP-HSW.cmake
- cmake/std/atdm/shiller/tweaks/GNU-RELEASE-SERIAL-HSW.cmake
- cmake/std/atdm/shiller/tweaks/INTEL-DEBUG-OPENMP-HSW.cmake
- cmake/std/atdm/shiller/tweaks/INTEL-DEBUG-SERIAL-HSW.cmake
- cmake/std/atdm/shiller/tweaks/INTEL-RELEASE-OPENMP-HSW.cmake
- cmake/std/atdm/shiller/tweaks/INTEL-RELEASE-SERIAL-HSW.cmake
- cmake/std/atdm/waterman/tweaks/CUDA-9.2-RELEASE-CUDA-POWER9-VOLTA70.cmake
- cmake/std/atdm/waterman/tweaks/GNU-RELEASE-OPENMP-POWER9.cmake
@trilinos/panzer, @trilinos/piro, @fryeguy52 
Commits to remove `Piro_MatrixFreeDecorator_UnitTests_MPI_4` test disables as per #2474 and add `PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4` test disables for CUDA builds on 'white/ride' and 'hansen/shiller' as per #3579.
We agreed to enable this Piro test everywhere (see #2474) and we agreed to disable this Panzer test for CUDA builds on 'white/ride' and 'hansen/shiller' (see #3579).
I did local configures of Panzer on 'white' using
```
$ ./checkin-test-atdm.sh cuda-9.2-opt-Power8-Kepler37 --enable-packages=Piro,Panzer --configure
$ grep _DISABLE cuda-9.2-opt-Power8-Kepler37/configure.out 
...
-- Setting default PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-4_DISABLE=ON
...
-- …
```
> Remove Piro disable for #2474 and add Panzer disable for #3579

- packages/tempus/src/Tempus_SolutionHistory_decl.hpp
Closes #3847 
Add warning if workingState is null.
Users can request the workingState when it is not valid. This gives them a warning that it is not valid.
> Tempus: Add warning about workingState equal to null.

- packages/sacado/example/template_container_example.cpp
- packages/sacado/src/KokkosExp_View_Fad.hpp
- packages/sacado/src/Sacado_trad.hpp
- packages/sacado/src/Sacado_trad2.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_ViewStorage.hpp
1.  Fix use of uninitialized variable in template container example.
2.  Fix missing KOKKOS_INLINE_FUNCTION macro in View specializations.
3.  Fix enum-in-bool-context warning in new Fad design.
4.  Fix warning about use of "=" in "==" context in Rad.
5.  Fix warning about missing operator delete in Rad.
> Sacado:  Fix various compiler warnings.

- packages/tempus/src/Tempus_SolutionHistory_decl.hpp
- packages/tempus/src/Tempus_SolutionHistory_impl.hpp
Closes #3883 
New warning needs ability to turn off.
Too much output in places.
> Tempus: Add ability to quiet warning about workingState equal to null.

- packages/amesos2/src/Amesos2_MUMPS_def.hpp
Error message:
```
trilinos/src/packages/amesos2/src/Amesos2_MUMPS_def.hpp:278:37: error: redeclaration of 'Teuchos::TimeMonitor redistTimer'
Teuchos::TimeMonitor redistTimer(this->timers_.vecRedistTime_);
^
trilinos/src/packages/amesos2/src/Amesos2_MUMPS_def.hpp:246:26: note: 'Teuchos::TimeMonitor redistTimer' previously declared here
Teuchos::TimeMonitor redistTimer( this->timers_.vecRedistTime_ );
```
Necessary condition for cmake configure is to enable explicitly Amesos2_ENABLE_MUMPS=ON. Using the combination TPL_ENABLE_MUMPS=ON and Trilinos_ENABLE_Amesos2=ON will show a message that Amesos2_ENABLE_MUMPS is set to ON, when in reality it will not be set to ON (didn't dig into that issue though).
> Amesos2: Compile error with MUMPS

- packages/muelu/research/luc/region_algorithms/CMakeLists.txt
- packages/muelu/research/mmayr/composite_to_regions/src/main.cpp
- packages/muelu/research/mmayr/composite_to_regions/src/mk2DRegionFile.m
- packages/muelu/research/mmayr/composite_to_regions/src/muelu_structured.xml
- packages/muelu/research/mmayr/composite_to_regions/src/shadow_caseFifteen.m
- packages/muelu/research/mmayr/composite_to_regions/src/shadow_caseTen.m
Enable regional multigrid code to 
- form a composite operator on the coarsest level
- perform a direct solve on the coarsest level (based on this composite operator)
We usually want to use the regional framework for the fine and intermediate levels in order to exploit data locality and structuredness of the regions. However, on the coarsest level, a direct solve is required which in turn requires a composite operator. Furthermore, a coarse level operator can be used as a starting point for building an (unstructured) algebraic MG hierarchy on top of a region hierarchy. This allows to do true HHG-type problems.
* Closes #2798 
Runs locally for small problems.
> Composite coarse level operator and direct solve

- packages/ifpack2/src/Ifpack2_ILUT_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestILUT.cpp
@trilinos/ifpack2 @vbrunini 
Ifpack2::ILUT::setParameters no longer uses try - catch as control logic.
* Closes #3903
> Ifpack2::ILUT::setParameters: Fix #3903

- packages/panzer/adapters-stk/example/CMakeLists.txt
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/CMakeLists.txt
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_BCStrategy_Dirichlet_Constant.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_BCStrategy_Dirichlet_Constant_impl.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_BCStrategy_Factory.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_ClosureModel_Factory.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_ClosureModel_Factory_TemplateBuilder.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_ClosureModel_Factory_impl.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_CurlLaplacianEquationSet.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_CurlLaplacianEquationSet_impl.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_CurlSolution.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_CurlSolution_impl.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_EquationSetFactory.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_SimpleSource.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_SimpleSource_impl.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/convergence_rate.py
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/main.cpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_IntrepidBasisFactory.hpp
- packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
- packages/panzer/disc-fe/src/Panzer_PureBasis.cpp
- packages/panzer/disc-fe/src/Panzer_PureBasis.hpp
Adapted CurlLaplacianExample into a mixed version that uses both HCurl and HDiv elements in 3D or HCurl and HVol elements in 2D.
Exposed HVol basis type and defined its basis values. Modified L2Projection to allow HVol elements.
Previously HVol elements were allowed in Panzer only through the Const basis option. This was restricted to zeroth order and did not use the HVOL basis value transformation for defining the basis. This change keeps the Const basis but adds the option to use arbitrary order HVol elements on 2D meshes.
The z component of an HDiv DOF should use an HVol basis in 2D. This is necessary for arbitrary order electromagnetics in 2D.
Added the test example MixedCurlLaplacianExample. This is the same test as CurlLaplacianExample except it's in mixed form …
> Panzer: allow HVol elements

- packages/zoltan/example/Fortran/classicMakefile
An external user asked how to build the F90 example provided in zoltan/example/Fortran, using a standard makefile.
This PR adds classicMakefile similar to that in the C examples.
The new file archives the makefile that I was able to make work correctly, so I won't have to rediscover it someday for someone else.
I tested this makefile on vesper (linux) with an autotools build; all good.
This change does not impact any internal users, as they build zoltan without Fortran and with Cmake.
In fact, the autotester has nothing to do for this PR.
No backward compatibility changes.
> Zoltan fortran example classicMakefile for use with autotools

- packages/belos/src/BelosCGSingleRedIter.hpp
The single-reduction CG throws an error when trying to solve a system with the exact solution as initial guess. (This happens for my time-dependent problem. Both solution and forcing term are zero on the first time step.) 
With the proposed change, this trivial solve costs two all-reduces, one for the inner product and one for the convergence check.
> Belos CGSingleRed: Do not bug out when system is already solved

- packages/tempus/test/ExplicitRK/CMakeLists.txt
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_Combined_FSA.cpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_FSA.hpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_Staggered_FSA.cpp
- packages/tempus/test/IMEX_RK_Partitioned/CMakeLists.txt
- packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_Partitioned_Combined_FSA.cpp
- packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_Partitioned_FSA.hpp
- packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_Partitioned_Staggered_FSA.cpp
As was done with the DIRK tests a while ago, split apart the Explicit RK
and Partitioned-IMEX FSA tests to make them run shorter, and therefore
less likely to timeout in debug builds.
> Tempus:  Split apart ERK and IMEX FSA tests to reduce timeouts.

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
- packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
- packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp
This PR adds the capability to align the stacked timer output into columns. Currently this aligns the columns against all timers. We might also add the ability to align only within a level.
Example from drekar:
```
Drekar: Total Time:                                                                                                                                         0.246002                 [1]  {min=0.245948   , max=0.246097   , std dev=6.58034e-05} <2, 1, 0, 0, 1>
|   panzer::SquareQuadMeshFactory::buildUncomittedMesh():                                                                                                   0.00153242  - 0.62293%   [1]  {min=0.00150515 , max=0.00156354 , std dev=3.01706e-05} <2, 0, 0, 0, 2>
|   panzer::SquareQuadMeshFactory::completeMeshConstruction(): …
```
> Teuchos: stacked timer can optionally align output

- packages/anasazi/src/AnasaziBlockKrylovSchur.hpp
- packages/anasazi/src/AnasaziGeneralizedDavidson.hpp
- packages/belos/src/BelosBlockGCRODRSolMgr.hpp
- packages/belos/src/BelosGCRODRSolMgr.hpp
This commit modifies the use of LAPACK GEES/GEEV in solvers that employ this method such that they determine the optimal lwork size before allocating the work vector. This should not be necessary, but the Intel MKL 18.0.[0-3] library has a known bug that can cause this method to seg fault due to bad memory access, when the optimal size is not used. This was fixed in MKL Update 4, as documented here:
https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-bug-fixes-list
Since there is a concern that the MKL 18.0.2 library that is on the ATDM platforms
will be in use for the near-term, the interactions with the LAPACK calls to GEES/GEEV
in Anasazi and Belos will be modified.
This commit addresses the issues in bugs #3497 and #3499, except for the …
> Modify the use of LAPACK GEES/GEEV in the Belos and Anasazi solvers for Intel MKL 18.0.2

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
@trilinos/tpetra @crdohrm 
* Closes #3948
> Tpetra: Fix #3948 (build warnings for unused typedefs)

- cmake/std/atdm/ATDMDevEnvSettings.cmake
- cmake/std/atdm/ride/tweaks/CUDA-9.2-RELEASE-CUDA-POWER8-KEPLER37.cmake
@trilinos/framework , @bartlettroscoe 
This pull request disables some PanzerAdaptersSTK tests for some ATDM builds.  The tests:
* PanzerAdaptersSTK_MixedCurlLaplacianExample
* PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1
* PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-2
* PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Quad-Order-3
* PanzerAdaptersSTK_CurlLaplacianExample-ConvTest-Quad-Order-2
are disabled for **all cuda** builds.
The test:
* PanzerAdaptersSTK_MixedCurlLaplacianExample-ConvTest-Tri-Order-1 
is disabled on `Trilinos-atdm-white-ride-cuda-9.2-opt`
#3939 
#3950 
Local testing on ride shows that these tests are disabled for cuda builds but not the gnu builds
> Atdm ride panzer disable

- packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_def.hpp
- packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp
As pointed out in issue #3946, MueLu does not build with `Scalar=float` or `Scalar=complex<float>`. 
I do not think that MueLu has supported using float in the past.
With the above changes, the build goes through as long as 
```
-D MueLu_ENABLE_TESTS=OFF 
-D MueLu_ENABLE_EXAMPLES=OFF
```
I would be surprised if MueLu actually worked though. The reason is that we have a lot of spots were coordinates are hard-coded to double. For an actual fix, we would need to go through and replace all occurrences with `ScalarTraits<Scalar>::magnitudeType`.
> MueLu: Fix some float build issues

- packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
- packages/panzer/mini-em/example/BlockPrec/main.cpp
- packages/panzer/mini-em/example/BlockPrec/maxwell-blob-R0.xml
- packages/panzer/mini-em/example/BlockPrec/maxwell-blob-R1.xml
- packages/panzer/mini-em/example/BlockPrec/maxwell-blob-R2.xml
- packages/panzer/mini-em/example/BlockPrec/maxwell-blob-R3.xml
- packages/panzer/mini-em/example/BlockPrec/maxwell-blob-R4.xml
- packages/panzer/mini-em/example/BlockPrec/solverCG.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell2D.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellOpenMP.xml
@trilinos/panzer @jjellio 
This PR adds separate input files for the different blob meshes, and deduplicates the RefMaxwell solver input files. Instead of maintaining redundant solver files for all combinations of linear algebra, spatial dimension and node type, we keep one complete solver file and only apply the changes that are necessary for different combinations. This should make it easier to maintain the solver..
> MiniEM: Input file simplifications

- packages/teuchos/remainder/src/CMakeLists.txt
- packages/teuchos/remainder/src/Trilinos_LinearSolverSetupFailure.hpp
- packages/teuchos/remainder/test/CMakeLists.txt
- packages/teuchos/remainder/test/LinearSolverSetupFailure/CMakeLists.txt
- packages/teuchos/remainder/test/LinearSolverSetupFailure/LinearSolverSetupFailure.cpp
@trilinos/teuchos @trilinos/nox @trilinos/stratimikos @trilinos/thyra 
@jmgate requested that I add an exception class to Teuchos, so that NOX and Stratimikos / Thyra can share a common exception class for reporting failure in setup of a linear solver.  I consulted with @jmgate on 03 Dec 2018 to scope the work.  This commit adds the requested class, Trilinos::LinearSolverSetupFailure, as well as a unit test.
This commit fixes #3983, and works towards resolving #1608.
Note that this PR does _not_ add a subpackage to Teuchos, as discussed here: https://github.com/trilinos/Trilinos/issues/1608#issuecomment-377358361 .  That is a separate issue.  Furthermore, adding subpackages has the potential to break downstream applications' builds.
* Closes #3983 
* Blocks #1608
> Teuchos: Fix #3983 (see #1608)

- cmake/std/atdm/waterman/all_supported_builds.sh
@fryeguy52 
This matches the changes that I forgot to make in commit ab6fbffd8617141792d18e8a98a12b167ae8bf0b.
Need to be able to use [ctest-s-local-test-driver.sh](https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#ctest-s-local-test-driversh) on 'waterman'.
I ran both `checkin-test-atdm.sh` and `ctest-s-local-test-driver.sh` on 'waterman' (see https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-237).
> Update all_supported_builds.sh file to support ctest-s-local-test-driver.sh (TRIL-212)

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
If the options supplied by users are inconsistent, the cleanup needs
to happen before alignments are computed.
> Teuchos: fix stacked timer output

- packages/panzer/adapters-stk/example/PoissonInterfaceExample/main.cpp
- packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp
- packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
#3968
Changes to each package are in separate commits.
Thanks to Mark Hoemmen for the tpetra fix!
> Tpetra: fix race condition in transfers with AbsMax for CUDA_AWARE_MPI

- packages/aztecoo/src/az_gmres_condnum.c
@trilinos/aztecoo
MKL has a bug: If you give DGEEV a suboptimal but still correct LWORK, it corrupts memory.  This commit adds a work-around to AztecOO that does an LWORK query to allocate the optimal amount of memory.  This may affect performance of GMRES condition number estimation a little bit.  (It could speed up or slow down; not sure, and depends on the restart length.)
* Closes #4006 
* Related to #3497
> AztecOO: Fix #4006 (suboptimal LWORK for DGEEV triggers MKL bug)

- packages/phalanx/CMakeLists.txt
Closes #3995 
If panzer is not enabled, phalanx by default will not allow multiple evaluators to be registered that evaluate the same field. We have to allow multiple registration when panzer is enabled due to a design issue.
> Phalanx default option for multiple evaluator field registration

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
- packages/muelu/src/Rebalancing/MueLu_RebalanceTransferFactory_def.hpp
@trilinos/muelu @pwxy 
Fix for issue #3991: The problem was that dumping did not work if either
- coordinates or nullspace were dumped after rebalancing,
- level sequences other than {0,1,2,..} were used, e.g. {2}.
Also fix missing Zoltan headers in RefMaxwell.
> MueLu: Fix export data

- packages/tpetra/CMakeLists.txt
- packages/tpetra/core/test/Comm/CMakeLists.txt
- packages/tpetra/core/test/Comm/cudaMpi_CanaryTest.cpp
For issue #3405 
These changes add logic to CMake's configuration, increasing the number of locations in which ompi_info is found.  The changes allow ompi_info to be found for ATDM builds on white.
ATDM builds did not set MPI_CXX_COMPILER; instead, they set CMAKE_CXX_COMPILER.  The new logic looks for ompi_info in the same directory as CMAKE_CXX_COMPILER.
I also added a test program, cudaMpi_CanaryTest.cpp.  It exercises MPI with CUDA directly, without any Kokkos or Trilinos data structures.  If this test fails with a given MPI installation (e.g., OpenMPI3 on white), the problem is likely with MPI, not with Tpetra.  Is there a better place in Trilinos for such tests, rather than in the packages?  Do we need a "stableSystemPackage" that includes tests like these, which have no dependence …
> Tpetra:  Added extra CMake logic for setting Tpetra_ASSUME_CUDA_AWARE_MPI

- cmake/std/PullRequestLinuxDriver-Test.sh
Updated one of the error message outputs from the PR driver script to be a little
more descriptive of what happened above simply "the error was 42".
> Framework: Improve missing environment error message

- packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
There is a bug if panzer runs on multi blocks where all the blocks are not on all the MPI ranks.  This fixes the two that I found... Not sure if they are complete, doubt they are..
@rppawlo @eric-c-cyr can one of you look this over and accept?
> Fixed some issues with panzer not working for multi blocks

- packages/muelu/research/mmayr/composite_to_regions/src/muelu_structured.xml
There has been an XML-file issue that prevented us from doint more
than two levels in the fully structured HHG case. This fixes it.
* Closes #2798 
Fully structured 1D and 2D HHG-type examples run with multiple levels.
@lucbv These are the changes we made during our phone call on Monday.
> MueLu/HHG: fix structured xml file to work with multiple levels

- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.hpp
- packages/panzer/disc-fe/src/Panzer_PointValues2.hpp
- packages/panzer/disc-fe/src/Panzer_PointValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/Panzer_WorksetContainer.cpp
- packages/panzer/disc-fe/src/Panzer_Workset_Builder.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_BasisValues_Evaluator_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_PointValues_Evaluator_impl.hpp
This PR converts all calls to Intrepid2 to use subviews. The workset concept is used to control memory usage. The last workset may not be full. That means the actual number of cells is not always equal to workset size. Intrepid2 always uses the extent (workset size) for their loops leading to extra operations on dummy cells. In the past, we just iterated on the full extent, but some applications now enable FPE trapping by default. Switching to subviews fixes the extent correctly.
> Panzer: use subviews for Intrepid2 methods

- packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp
This test, unlike the two other orthogonalization tests, generates a biorthogonal
basis.  When all the dimensions are summed up, the orthogonal constraints in this
test are twice the size of the other two tests.  Using random vectors, it would be
more likely that a degenerate basis could be constructed by this test.  Since the
objective of the test to make sure that the orthogonalization methods in Anasazi can
construct a biorthogonal basis, the size of the basis is not as much the point.
So, the dimension of each component of this test have been halved because of the
biorthogonality.  This seems to eliminate random failures that were observed on the
CEE, and are the subject of the bug #3585 .
This should address the random failures in #3585.
On CEE, where the test …
> Reducing subspace sizes due to biorthogonal basis construction for #3585

- packages/epetra/src/Epetra_Export.h
- packages/epetra/src/Epetra_Import.h
- packages/epetra/src/Epetra_Util.cpp
Auto-PR for SHA ca1e86e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4072)
> Epetra: add method to get pointer to Distributor in Import and Export classes

- packages/tpetra/CMakeLists.txt
Forbid inconsistent CMake options about `Scalar=float`, `std::complex<double>`, and `std::complex<float>`, that could cause build errors downstream (in Thyra or Stratimikos).
* Closes #4080 
* Related to #4059
> Tpetra: Fix #4080

- packages/kokkos/core/src/impl/Kokkos_Atomic_Generic.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
@trilinos/kokkos @trilinos/tpetra 
Fix #4094 by patching Kokkos to fix https://github.com/kokkos/kokkos/issues/1951.
Fix some Tpetra build warnings.
Build with `Scalar=complex<double>` enabled was broken.
* Closes #4094 
* Is blocked by https://github.com/kokkos/kokkos/issues/1951 
It's blocked in a sense; we need to fix Kokkos, else this is only a temporary fix that will get clobbered on the next Kokkos-to-Trilinos promotion.
Linux, GCC 4.9.3, OpenMP, OpenMPI 1.10.1.
> Kokkos,Tpetra: Fix #4094

- packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests_Swap.cpp
There were some `#if 0` blocks in the test which needed to be changed to use `Tpetra::Details::Behavior::verbose()` for consistency.
This PR is convenient as well for testing changes to PR jobs on Jenkins for @trilinos/framework for #4065 =) .
> Tpetra: Clean up CrsGraph::Swap testing

- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6-clang-5.0.1-openmpi-1.10.2-serial-static-opt.sh
- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6-gnu-4.9.3-openmpi-1.10.2-serial-static-opt.sh
- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6-gnu-7.2.0-openmpi-1.10.2-serial-static-opt.sh
- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6-intel-17.0.1-intelmpi-5.1.2-serial-static-opt.sh
@trilinos/framework, @srajama1, @rppawlo, @kddevin, @jwillenbring, @mperego 
As of today, these four 'cee-rhel6' builds are 100% clean.  As these match the
SPARC CI builds, these are important builds to elevate and maintain.
NOTE: The the intel-18.0.2 build is still not clean due to the problems with
MKL GEEV() as described in issues #3499 and #3914 so we can't promote that
build yet.
NOTE: Since these builds are run by a cron job on my CEE RHEL6 machine 'ceerws1113', the promotion has to be done in the driver scripts.
These are the only builds so far that protect SPARC's configuration of Trilinos (see [TRIL-212](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-212)) and these match SPARC's CI builds so these are critical to promote and maintain.
Not tested.  The changes are …
> Promoting 100% clean 'cee-rhel6' builds to 'ATDM' CDash group (TRIL-212)

- packages/panzer/adapters-stk/example/MixedPoissonExample/Example_SineSource_impl.hpp
- packages/panzer/adapters-stk/example/MixedPoissonExample/analyze_performance.py
- packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp
- packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.cpp
- packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOF_Functors.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOF_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_decl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_impl.hpp
This converts all functors for the MixedPoisson example to use hierarchic evaluators. Additionally it adds optional kernels for using shared memory where appropriate.
> Panzer: improve performance of assembly evaluators on cuda

- packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests_Swap.cpp
Responding to comments from @mhoemmen from PR #4089, I've changed usages of `Teuchos::RCP<Teuchos::Comm<int>>` to `Teuchos::RCP<const Teuchos::Comm<int>>`.
The function signature on my generator now looks like:
```C++
template<class LO, class GO, class Node>
Teuchos::RCP<Tpetra::CrsGraph<LO, GO, Node> >
generate_crsgraph(Teuchos::RCP<const Teuchos::Comm<int>> & comm,
const std::vector<std::pair<GO, GO>>   & gbl_edges,
const std::vector<std::pair<GO, int>>  & gbl_row_owners,
const size_t                             gbl_num_columns,
const bool                               do_fillComplete=true)
```
ctest output is:
```
$ ctest -R "CrsGraph_UnitTests_Swap" -VV
<snip/>
189: p=0 | 1. CrsGraph_int_long_Kokkos_Compat_KokkosSerialWrapperNode_Swap_UnitTest ...
189: p=0 |  >>> CrsGraph::swap() Unit …
```
> Tpetra: Cleanup on the CrsGraph::Swap Test

- packages/common/Doxyfile
This PR removes obsolete Doxyfile options so they don't show up as warnings when you build Trilinos' documentation.
Warning-free compilation makes me happy.
I'm using `doxygen-1.8.14` (looks to be about a year old).
> Remove Deprecated Doxygen Options

- packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
- packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
- packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp
Added more timers in the code, found a place where you had N^2 operations, fixed that in one place, 
Timing differences
```
|   L2Projection::Build Mass Matrix: 248.589 - 30.1226% [1] {min=248.585, max=248.593, std dev=0.00586798} <1, 0, 0, 0, 0, 0, 0, 0, 0, 1>
|   |   panzer_stk::generateLocalMeshInfo: 124.846 - 50.2217% [1] {min=122.894, max=126.797, std dev=2.75999} <1, 0, 0, 0, 0, 0, 0, 0, 0, 1>
```
down to
```
|   L2Projection::Build Mass Matrix: 10.451 - 2.89238% [1] {min=10.4492, max=10.4528, std dev=0.00256631} <1, 0, 0, 0, 0, 0, 0, 0, 0, 1>
|   |   panzer_stk::generateLocalMeshInfo: 7.51236 - 71.882% [1] {min=7.47739, max=7.54733, std dev=0.0494508} <1, 0, 0, 0, 0, 0, 0, 0, 0, 1>
```
> added some timers, fixed an N^2 issue in itialization

- packages/belos/src/BelosBlockGmresSolMgr.hpp
- packages/belos/tpetra/test/BlockGmres/test_bl_gmres_hb.cpp
The flexible Gmres variant is accessed through the block Gmres solver manager.
The current logic in that solver will throw an error if there is no right
preconditioner specified in the linear problem.  If the right preconditioner is not specified, then this
solver manager could just employ an unpreconditioned block Gmres iteration.
Furthermore, the solver manager did not effectively handle the situation when the linear
problem has a left preconditioner.  That is being addressed in this commit.  A modified Tpetra test covers the change from flexible to unpreconditioned Gmres when a right preconditioned is not supplied.
A user experience with this solver found it unhelpful that the solver threw an error and there is a natural resolution that the solver can take to address …
> Modify logic in block Gmres solver to address bug #4128

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
- packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
- packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp
Some applications are writing unit testing scripts that rely on StackedTimer data. This commit adds queries and overrides of Timer values to help support unit testing of the StackedTimer for both Trilinos and within the applications.
Also cleaned up some inconsistent naming conventions.
> Stacked timer unit testing support

- cmake/std/atdm/README.md
- cmake/std/atdm/utils/get_known_system_name.sh
CC: @jmgate, @fryeguy52 
These match the 'serrano' system (which needs to be renamed to 'cts1' at some
point).  This was requested by EMPIRE in the GitLab issue
em-plasma/buildscripts#114.
This should work on both the login and compute nodes on 'eclipse' and 'ghost'.
I guess people want to build and run on other CTS-1 systems 'eclipse' and 'ghost' as per:
* https://cee-gitlab.sandia.gov/EM-Plasma/BuildScripts/issues/114
I tested on 'eclipse' with:
```
$  cat src_default_env.sh
#!/bin/bash
source cmake/std/atdm/load-env.sh default
$ ./src_default_env.sh
Hostname 'eclipse-login9' matches known ATDM host 'eclipse' and system 'serrano'
Setting compiler and build options for buld name 'default'
Using toss3 compiler stack INTEL to build DEBUG code with Kokkos node type SERIAL
...
$  salloc -N1 …
```
> Add support for CTS-1 machines 'eclipse' and 'ghost' (em-plasma/buildscripts#114)

- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_gnu-7.2.0_openmpi-1.10.2_serial_shared_opt.sh
This build was 100% passing after the switch from static to shared libs.
Therefore, we can promote back to the 'ATDM' CDash group.
> Return 100% passing cee-hrl6-gnu-7.2.0 to 'ATDM' CDash group (TRIL-212)

- packages/zoltan/src/include/zoltan_types.h
Minor change meant to remove compiler warnings described in #4032 
Build without warnings
Built/run on linux workstation.
I was unable to reproduce warnings using gcc 7.2, so I do not know that this change will remove them.  This change was recommended by @mhoemmen
> zoltan:  Minor change addressing #4032

- packages/tempus/src/Tempus_SolutionHistory_impl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
- packages/tempus/src/Tempus_StepperForwardEuler_decl.hpp
- packages/tempus/src/Tempus_StepperImplicit_decl.hpp
- packages/tempus/src/Tempus_StepperLeapfrog_decl.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAForm_decl.hpp
- packages/tempus/src/Tempus_StepperOperatorSplit_decl.hpp
- packages/tempus/src/Tempus_StepperStaggeredForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_TimeStepControl_impl.hpp
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref.xml
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref2.xml
- packages/tempus/test/Integrator/Tempus_IntegratorTest.cpp
Replaced the usage std::numeric_limits::max() for the default values
as it can cause FPEs.  Rebaselined the Integrator tests as it checks
the default values.
All tests pass on MacOS.
#4169 
Replaced std::numeric_limits<Scalar>::max() with 1.0e+99, and std::numeric_limits<int>::max() with 1000000000.
Avoid FPEs.
All test pass on MacOS.
> Tempus: Fixed some FPEs.

- cmake/ctest/drivers/windows/README.md
- cmake/ctest/drivers/windows/create_windows_package.bat
- cmake/ctest/drivers/windows/task_driver_windows.bat
@csiefer2 
Upgrading the Trilinos nightly build on Windows to use CMake 3.12.0
Issue #4154 
The Windows build is currently trying to use CMake 3.8.1, which is no longer sufficient.
I did some sanity testing of the CMake installation in general.
I requested a review from @bmpersc because he recently fixed the system so it properly runs tests again and we discussed these further changes.
> Issue #4154 Upgrading Windows nightly build to CMake 3.12.0

- packages/teuchos/core/src/Teuchos_ScalarTraits.cpp
> Made nan's quiet to hide FPEs

- packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_decl.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp
- packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_decl.hpp
- packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp
- packages/muelu/test/structured/structured_2dof.xml
- packages/muelu/test/structured/structured_3dof.xml
- packages/muelu/test/unit_tests/StructuredAggregationFactory.cpp
This PR modifies the prolongatorGraph output from structured aggregation.
Instead of getting a node based graph it now returns a dofs based graph.
This means that in the new format, the prolongator graph can be used to call the constructor of the prolongator matrix directly.
This has the advantage of reducing some overhead and it also simplifies the implementation of the geometric interpolation factory.
* Closes #4173 
All the tests in MueLu have been run and passed
> MueLu: modifying structured aggregation to compute graph of prolongator

- packages/tpetra/core/src/Tpetra_DistObject_def.hpp
- packages/tpetra/core/src/Tpetra_Util.hpp
@trilinos/tpetra @kddevin @csiefer2 @trilinos/muelu 
sorry for brevity, I have to type this on phone, could someone plz review and label as auto merge?  Thanks :-) 
* Closes #4199
> Tpetra: Fix #4199

- packages/teuchos/comm/src/Teuchos_DefaultSerialComm.hpp
- packages/teuchos/core/src/Teuchos_Describable.cpp
- packages/teuchos/core/src/Teuchos_RCPNode.cpp
- packages/teuchos/core/src/Teuchos_ScalarTraits.cpp
- packages/teuchos/core/src/Teuchos_StrUtils.cpp
- packages/teuchos/numerics/src/Teuchos_Flops.cpp
- packages/teuchos/numerics/src/Teuchos_LAPACK.cpp
- packages/teuchos/numerics/src/Teuchos_MatrixMarket_Banner.cpp
- packages/teuchos/numerics/src/Teuchos_Object.cpp
- packages/teuchos/parameterlist/src/Teuchos_StandardConditionXMLConverters.cpp
- packages/teuchos/parameterlist/src/Teuchos_StandardDependencyXMLConverters.cpp
- packages/teuchos/parameterlist/src/Teuchos_StandardDependencyXMLConverters.hpp
- packages/teuchos/parameterlist/src/Teuchos_StandardFunctionObjectXMLConverters.hpp
- packages/teuchos/parameterlist/src/Teuchos_StandardValidatorXMLConverters.cpp
- packages/teuchos/parameterlist/src/Teuchos_XMLParameterListWriter.cpp
- packages/teuchos/parameterlist/src/Teuchos_XMLParser.cpp
- packages/teuchos/parser/src/Teuchos_MathExpr.cpp
- packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp
Compiling Trilinos with all warning on with gcc-7.2.0 yields a ton of unused parameter warnings.  This PR comments out the parameter names in function definitions to avoid those warnings.
Just hoping for a clean build one day&hellip;
> Teuchos:  Remove Unused Parameter Warnings

- packages/minitensor/src/MiniTensor_LinearAlgebra.t.h
- packages/minitensor/src/MiniTensor_Utilities.i.h
@trilinos/minitensor @khpierson
This hopefully fixes #4220.  I haven't tested this with NVCC yet; I just removed the redundant `break` statements as indicated in the warnings.
* Closes #4220
> MiniTensor: Attempt to fix #4220

- packages/belos/epetra/src/BelosEpetraOperator.h
- packages/belos/src/BelosBiCGStabIter.hpp
- packages/belos/src/BelosBlockCGIter.hpp
- packages/belos/src/BelosCGIter.hpp
- packages/belos/src/BelosCGSingleRedIter.hpp
- packages/belos/src/BelosFixedPointIter.hpp
- packages/belos/src/BelosLSQRIter.hpp
- packages/belos/src/BelosMinresIter.hpp
- packages/belos/src/BelosOrthoManagerFactory.hpp
- packages/belos/src/BelosPCPGIter.hpp
- packages/belos/src/BelosPseudoBlockCGIter.hpp
- packages/belos/src/BelosPseudoBlockTFQMRIter.hpp
- packages/belos/src/BelosRCGIter.hpp
- packages/belos/src/BelosRCGSolMgr.hpp
- packages/belos/src/BelosSolverManager.hpp
- packages/belos/src/BelosStatusTestGenResSubNorm.hpp
- packages/belos/src/BelosTFQMRIter.hpp
When compiling with all warning turned on with gcc-7.2.0, I see these `unused-parameter` warnings all over the place.  Commenting out the parameter names in the function definitions usually does the trick.
Just trying to get to a cleaner build.
> Belos:  Remove Unused Parameter Warnings

- packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_DistObject_def.hpp
- packages/tpetra/core/test/HashTable/FixedHashTableTest.cpp
- packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
@trilinos/tpetra @trilinos/teuchos
Tpetra's ImportExport2_UnitTests and FixedHashTable tests now pass.
Tpetra::Details::getArrayViewFromDualView and a TeuchosKokkosCompat
function now uses the work-around required by Teuchos::ArrayView's
constructor in a debug build.  ImportExport2_UnitTests no longer
redefines that function.
I also added TPETRA_VERBOSE output to CrsMatrix communication
functions and CrsMatrix's transferAndFillComplete, and replaced a
HAVE_TPETRA_DEBUG region in transferAndFillComplete with a run-time -
controlled debug mode check.
* Closes #4225
> Tpetra,Teuchos: Fix #4225

- packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp
Fixiing mismatched virtual functions definitions. This could be a real error but somehow it works with other compilers and PR tests.  
#4221 
As the error shows up from SRN machines with a clang compiler and this is not detected from PR tests, I cannot attempt to reproduce the error myself. From the error message, I matched the function signatures and hope that it will solve the problem.
> Tpetra - fix warning error from mismatched virtual functions

- packages/zoltan2/src/directory/Zoltan2_Directory.hpp
- packages/zoltan2/src/directory/Zoltan2_Directory_Impl.hpp
- packages/zoltan2/test/directory/CMakeLists.txt
- packages/zoltan2/test/directory/directoryTest_Impl.hpp
- packages/zoltan2/test/directory/directoryTest_KokkosSimple.cpp
Repairs issues from PR #1533 for directory work.
Resolved CUDA tests and Albany link failure. 
Restore CUDA builds and Albany build.
On white:
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh cuda-9.2-gnu-7.2.0-release-debug
$ cmake \
-GNinja \
-DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_Zoltan2=ON \
$TRILINOS_DIR
$ bsub -x -Is -q rhel7F -n 16 ctest -j16
On clang parallel and serial.
> Fix CUDA and Albany builds from prior PR #1533

- packages/teuchos/core/src/Teuchos_ArrayView.hpp
- packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp
- packages/teuchos/kokkoscompat/test/CMakeLists.txt
- packages/teuchos/kokkoscompat/test/linkTest.cpp
- packages/teuchos/numerics/test/LAPACK/cxx_main.cpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
@trilinos/tpetra @trilinos/kokkos @trilinos/teuchos 
This fixes a few Teuchos issues, and one Tpetra issue.  The Tpetra fix is actually a work-around for kokkos-kernels issues.  @kyungjoo-kim might have some fixes there; see e.g., https://github.com/kokkos/kokkos-kernels/pull/373.
This may be "results impacting," because it affects how Tpetra computes dot products for complex Scalar types.  In particular, the work-around always uses `complex<double>` as the accumulator type.  This should improve accuracy for the `Scalar=complex<float>` case.
* Closes #4250, #4234, #4249, #3823
> Fix #4250, #4234, #4249, and #3823

- packages/zoltan2/src/algorithms/Zoltan2_Algorithm.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_CoordinatePartitioningGraph.hpp
- packages/zoltan2/src/problems/Zoltan2_PartitioningSolution.hpp
- packages/zoltan2/src/util/Zoltan2_StridedData.hpp
- packages/zoltan2/test/partition/CMakeLists.txt
- packages/zoltan2/test/partition/MultiJaggedTest.cpp
- packages/zoltan2/test/partition/mj_int_coordinates.cpp
- packages/zoltan2/test/unit/util/StridedData.cpp
Enables MJ partitioner to work with integer coordinates:  #4212 
- MJ requires floating point calculations for determining cuts
- MJ previously used the User's scalar_t for cuts, which was problematic when scalar_t was int
- Fix defines mj_scalar_t to be the user's scalar_t if it is a floating point type; otherwise, mj_scalar_t is float
- If mj_scalar_t differs from the user's scalar_t, coordinates are copied to mj_scalar_t arrays.
Also, removed templated types from coordinateModelPartBoxes.  #4211 
- coordinateModelPartBoxes store cut information computed by Zoltan2; their storage should not depend on the user's data types
-  changed storage in coordinateModelPartBoxes to be double
-  these changes were needed to enable fixing #4212 
-  removing the template parameters …
> Zoltan2:  Enable MJ to work with int coordinates

- packages/muelu/test/scaling/Driver.cpp
- packages/muelu/test/vardofpernode/VarDofDriver.cpp
Needed to instantiate `MueLu::Utilities` on `real_type` instead of `Scalar` to handle coordinates.
Also removed a couple warnings caused by unused variables.
As explained in issued #4263 the MueLu Driver does not build properly with complex enabled.
This is blocking a Trilinos promotion in Sierra
* Closes #4263 
I did a local build that was successful
> MueLu: fix issue #4263

- packages/zoltan2/src/util/Zoltan2_ImbalanceMetricsUtility.hpp
@kddevin This will fix the imbalance metrics weak ptr issue for the ongoing work. We need to create tests to cover code using useDegreeAsWeight, so I think we could either merge this and follow up with testing or add tests to this PR.
Ongoing work is using this code and there is an error causing a weak dangling ptr.
mac parallel and serial tests
> Zoltan2: Fix dangling weak ptr

- packages/TriKota/CMakeLists.txt
- packages/TriKota/cmake/Dependencies.cmake
@trilinos/trikota
Initial pass at addressing trilinos/Trilinos#4270: disable Dakota's
ROL interface when building under trilinos/packages/TriKota.
Rationale: Would prefer to have Dakota use ROL as provided by
Trilinos, but creates a circular package dependence due to ROL's
optional use of TriKota. As ROL may remove dependence on Dakota sparse
grid at some point, better to workaround this for now.
Also cleanup TriKota's interface to Dakota's CMake based on changes in
the last few Dakota versions.
Addresses #4270 
Tested through make and ctest phases with this config (note requires upstream changes to ROL submitted separately).
```
cmake \
-DCMAKE_BUILD_TYPE=RELEASE \
-DCMAKE_INSTALL_PREFIX=../install \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DTrilinos_ENABLE_TESTS:BOOL=ON \ …
```
> TriKota: Disable Dakota's ROL interface

- cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
I am disabling one additional Tpetra test that started failing so that we can baseline a set of passing tests to begin to clean up the remaining failures so that other build/test issues don't backslide.
After getting the CUDA PR infrastructure changes through to master, one test started failing when we turned the CUDA testing on at the dev->master level
Issue #2464 
I did not test this change, but rather am basing the specific disable on this mornings dev->master [test results](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4469798&filtercount=2&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and)
> Disable Tpetra test for CUDA PR build

- cmake/std/PullRequestLinuxGCC4.9.3TestingSettingsSERIAL.cmake
Disabled Fortran for the automated GCC 4.9.3 SERIAL build.
This should address Issue #4238 . There are several projects and OSX users that disable Fortran when building Trilinos. This will make sure there is a Fortran-less configuration and PR build running to cover that.
Had this branch built successfully by Jenkins. [Everything builds and tests successfully](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4474639).
> Disable Fortran for 4.9.3 SERIAL build Fix Issue #4238

- packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp
- packages/anasazi/epetra/test/OrthoManager/cxx_mattest.cpp
- packages/anasazi/src/AnasaziBlockDavidsonSolMgr.hpp
- packages/anasazi/src/AnasaziIRTR.hpp
- packages/anasazi/src/AnasaziSIRTR.hpp
- packages/belos/src/BelosLSQRIter.hpp
- packages/rol/adapters/teuchos/test/function/test_01.cpp
- packages/rol/example/dense-hessian/example_01.cpp
- packages/rythmos/src/Rythmos_ExplicitRKStepper_def.hpp
- packages/rythmos/src/Rythmos_RKButcherTableau.hpp
- packages/stokhos/src/Stokhos_GSReducedPCEBasisBaseImp.hpp
- packages/stokhos/src/Stokhos_GramSchmidtBasisImp.hpp
- packages/stokhos/src/Stokhos_MonomialProjGramSchmidtPCEBasis2Imp.hpp
- packages/stokhos/src/Stokhos_ProductLanczosGramSchmidtPCEBasisImp.hpp
- packages/stokhos/test/UnitTest/Stokhos_GramSchmidtUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_HermiteBasisUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_LanczosUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_LegendreBasisUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_NormalizedHermiteBasisUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_NormalizedLegendreBasisUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_StieltjesUnitTest.cpp
- packages/tempus/src/Tempus_RKButcherTableau.hpp
- packages/teuchos/numerics/example/DenseMatrix/cxx_main.cpp
- packages/teuchos/numerics/example/DenseMatrix/cxx_main_sym.cpp
- packages/teuchos/numerics/example/LAPACK/cxx_main.cpp
- packages/teuchos/numerics/src/Teuchos_SerialBandDenseMatrix.hpp
- packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp
- packages/teuchos/numerics/src/Teuchos_SerialSymDenseMatrix.hpp
- packages/teuchos/numerics/test/DenseMatrix/cxx_main.cpp
@trilinos/<teamName> (Several affected)
See Issue #4258 for details
Closes Issue #4258 
Yes, using GCC 4.8.4 PR setup with Teuchos enabledand HDF5 disabled (includes all forward and optional packages affected).
- [? ] My change requires a change to the documentation.
- [ x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
- [ X] These changes break backwards compatibility.
> Issue4258 remove teuchos sdmatrix inheritance

- packages/muelu/research/mmayr/composite_to_regions/src/main.cpp
- packages/muelu/research/mmayr/hhg/hhg_driver.cpp
- packages/muelu/src/Utils/MueLu_PerfUtils_def.hpp
- packages/muelu/test/scaling/Driver.cpp
- packages/muelu/test/structured/structured_3dof.xml
to SGS, which will work properly on complex problems.
Also silencing a few compiler warnings related to unused variables.
The `MueLu_Structured_Elasticity3D` test fails when `Scalar=std::complex<double>` this is due to the choice of a Chebyshev smoother that does not complex numbers.
This is part of a clean-up of MueLu for `Scalar=std::complex<>` for Sierra promotion (see issue #4263) and for an auto-tester build (see issue #2426). Of course also to have the pleasure of running all the tests without problem when `std::complex<>` is enabled : )
* Closes 
* Blocks #2426 #4263
* Part of #2426
A local run with the new xml parameters has been performed and the test now passes without problems.
> MueLu: switching smoother in structured driver for 3D elasticity

- packages/sacado/src/Sacado_Fad_GeneralFad.hpp
One loop in GeneralFad wasn't correct for Cuda with hierarchical
parallelism.  This would only affect computations with a passive scalar
(i.e., variable declared as a Fad but had a zero-length derivative
array).
> Sacado:  Fix loop for hierarchical.

- cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
CC: @trilinos/framework 
Reverts trilinos/Trilinos#4293
As per https://github.com/trilinos/Trilinos/issues/4257#issuecomment-460704262, this test should now be passing in all of the CUDA builds.
As this test is protecting ATDM, I added the `ATDM` label.  It is important that the PR builds protect the ATDM builds to the greatest extent they can.
> Revert "Disable Tpetra test for CUDA PR build"

- packages/zoltan2/src/directory/Zoltan2_Directory.hpp
- packages/zoltan2/src/directory/Zoltan2_Directory_Impl.hpp
- packages/zoltan2/test/directory/CMakeLists.txt
- packages/zoltan2/test/directory/directoryTest_Impl.hpp
- packages/zoltan2/test/directory/directoryTest_KokkosSimple.cpp
This is a follow up PR to clean up a few issues from PR #4252.
It restores a missing zoltan2 test.
It restored the directory to use Kokkos unordered map (now host space) anticipating we'll be implementing parallel forms in the future.
It cleans up some of the directory hash code to avoid a global static method definition.
Tested on white cuda.
Tested on mac clang parallel and serial.
> Zoltan2: Restore Zoltan2 test and Kokkos unordered map

- packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOF_Functors.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_impl.hpp
This commit removes all use of deprecated kokkos features in panzer. Next kokkos promotion will remove these features as noted by @ndellingwood in email below.
https://github.com/kokkos/kokkos/wiki/DeprecationPage
Hi Roger,
While prepping for the next Kokkos+KokkosKernels promotion I saw several Panzer tests were failing with Cuda in the Trilinos develop branch (SHA 80e2cb3) when configuring with KOKKOS_ENABLE_DEPRECATED_CODE=OFF (none of them failed with deprecated code on, as expected). These failures must have slipped in after the previous promotion, but are not caused by any recent updates in Kokkos. The runtime failures seem to be caused by view(s) being constructed somewhere with more arguments than dynamic rank (e.g. View<double*> v(“v”, N, M); would trigger such an error with …
> Panzer: remove use of kokkos deprecated features

- packages/zoltan2/src/util/Zoltan2_GraphMetricsUtility.hpp
- packages/zoltan2/test/driver/CMakeLists.txt
- packages/zoltan2/test/driver/driverinputs/CMakeLists.txt
- packages/zoltan2/test/driver/driverinputs/chacoGraphMetricsTestNoDistribute.xml
- packages/zoltan2/test/driver/driverinputs/chacoGraphMetricsTestNoGraph.xml
- packages/zoltan2/test/driver/driverinputs/chacoGraphMetricsTestNoGraphNoDistribute.xml
When some processors have no IDs to partition or no graph edges, the graph metrics calculation core-dumped or caused a hang.  The culprit was attempts to compute the address of element 0 of an ArrayView of length zero.  I added tests for zero-length arrays before the attempted accesses.
Test Zoltan2_zoltanCompare.exe failed in the metric computation for input graph nograph (which doesn't have edges).  These changes allow Zoltan2_zoltanCompare.exe to succeed.
* Related to   #1533 
New tests are added that exercise the graph metrics in these conditions:
chacoGraphMetricTestNoGraph.xml -- tests graph metric computation on graph with no edges
chacoGraphMetricTestNoGraphNoDistribute.xml -- tests on graph with no edges and all input on rank 0 …
> zoltan2:  fixed ArrayView usage in graph metrics' directory calls

- packages/muelu/test/scaling/Driver.cpp
- packages/muelu/test/scaling/MatrixLoad.hpp
Currently the driver creates a specialized solver manager depending on input parameters.
This change will allow us to call any solver from belos, hence generalizing the driver.
Adding "belos" as a solver and adding a new clp option: belosType to actually specify which belos solver to call.
This will allow to test performance of multiple RHS solves especially with Block Gmres vs. PseudoBlock Gmres
* Closes #4358
Locally built and tested, this seem to work just fine.
> MueLu: modifying test/scaling/Driver.cpp to use Belo::SolverFactory and to accept multivector as RHS.

- cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
This will enable Complex Doubles in the GCC 7.2.0 build
Addresses Issue #2426 PR testing should enable complex by default
This has been tested to develop a number of times. The issues have been worked out and enabling complex doubles is ready to go.
https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4504696
> Issue 2426 Enable Complex Doubles

- packages/teuchos/core/src/Teuchos_Array.hpp
- packages/teuchos/core/src/Teuchos_ArrayView.hpp
- packages/teuchos/core/src/Teuchos_ArrayViewDecl.hpp
- packages/teuchos/core/test/MemoryManagement/ArrayView_UnitTests.cpp
- packages/teuchos/core/test/MemoryManagement/ArrayView_test.cpp
- packages/teuchos/core/test/MemoryManagement/Array_UnitTests.cpp
- packages/teuchos/core/test/MemoryManagement/Array_test.cpp
- packages/teuchos/core/test/MemoryManagement/Ptr_test.cpp
`Teuchos::Array` and `Teuchos::ArrayView` now have a `.data()` method, for
compatibility with `std::vector` and other C++ Standard Library classes
(as of C++11), as well as `Kokkos::View`.
I took the liberty to use `std::vector::data` in the implementation of
`Teuchos::Array` instead of `&vec[0]`, and to replace a few instances of `0`
(in a pointer context) with `nullptr`.  Note that the Teuchos Memory 
Management Classes always return `nullptr` if the array length is zero;
`std::vector` does _not_ promise that.
By analogy with `std::shared_ptr<T[]>`, I did _not_ add a `.data()` method
to `Teuchos::ArrayRCP`.  The whole point of the new methods is to
increase compatibility with the C++ Standard Library.  Here is a table
of correspondences between Teuchos Memory …
> Teuchos::{Array,ArrayView} Fix #2749

- packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp
- packages/amesos2/test/solvers/SolverFactory.cpp
This removes Tpetra::DynamicProfile from unit tests in amesos2
Deprecation of DynamicProfile in Tpetra's effect on downstream packages
Since this is a change in unit testing, the affected unit tests have been rerun to ensure that they are no longer using the deprecated code path.  Tests conducted on linux 2.6.32.
> Issue 4283: Amesos2 staticprofile

- packages/muelu/test/scaling/MatvecKernelDriver.cpp
Modifying the call to MatrixLoad in MatvecKernelDriver.cpp to comply with the new interface.
The interface change led to MatrixKernelDriver.cpp not building.
* Closes #4358 
I did a local build with the correct configuration to trigger a build of MatvecKernelDriver.cpp
> MueLu: fix matvec kernel driver

- packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_kokkos_decl.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_kokkos_def.hpp
- packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp
- packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp
- packages/muelu/test/unit_tests/Smoothers/BlockedSmoother.cpp
- packages/muelu/test/unit_tests/Utilities.cpp
- packages/muelu/test/unit_tests_kokkos/IndexManager_kokkos.cpp
Forgot to add a forward declaration that triggers the correct definition of a short name in MueLu.
silencing warning from IndexManager_kokkos.cpp by removing unused declartion of GOInvalid.
silencing warning in CreatePreconditioner.cpp due to instantiation guards and variable early declaration.
silencing compiler warning in unit_tests/Utilities.cpp and unit_tests/Smoothers/Blocked{Smoothers,DirectSolver}.cpp due to pedantic comparison of a size_t variable with 0
See above.
This will fix an issue that is blocking a Cuda build of Sierra
* Closes #4334 
Local build and tests were run on MueLu after fix.
> MueLu: fix for issue #4334

- cmake/ctest/drivers/atdm/TrilinosCTestDriverCore.atdm.cmake
We need to be testing a single consistent version of Trilinos across all ATDM
Trilinos builds.  Making this change does that.
NOTE:  `AT: AUTOMERGE` is **NOT** set because I want to control when this branch gets merged so taht I can update the various Jenkins and cron drivers in coordination with this.
See [TRIL-260](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-260).
I tested this locally on 'crf450' with:
```
$ cd /home/rabartl/Trilinos.base/BUILDS/ATDM/JENKINS/
$ mkdir exp
$ cd exp/
$ ln -s ~/Trilinos.base/Trilinos .
$ env JOB_NAME=Trilinos-atdm-sems-rhel6-gnu-debug-serial \
WORKSPACE=$PWD \
CTEST_TEST_TYPE=Experimental \
Trilinos_PACKAGES=Kokkos,Teuchos \
/Trilinos/cmake/ctest/drivers/atdm/smart-jenkins-driver.sh
```
This looks to have …
> Change from 'develop' to 'atdm-develop-nightly' branch (TRIL-260)

- packages/muelu/src/Utils/MueLu_AlgebraicPermutationStrategy_def.hpp
Changed the type of some variables from `Scalar` to `Teuchos::ScalarTraits<Scalar>::magnitudeType` to avoid issues related reductions using: REDUCE_MIN/MAX operations that are not well defined when `Scalar=std::complex<>`.
This cleans-up the code and potentially fixes a bug
* Closes #3492
A local build was done with `Scalar=std::complex<>` has been performed
> MueLu: clean-up MueLu_AlgebraicPermutationStrategy_def.hpp for #3492

- packages/belos/tpetra/test/MVOPTester/cxx_main_complex.cpp
@trilinos/belos  
This removes Tpetra::DynamicProfile from unit tests in belos
Deprecation of DynamicProfile in Tpetra's effect on downstream packages
Since this is a change in unit testing, the affected unit tests have been rerun to ensure that they are no longer using the deprecated code path.  Tests conducted on linux 2.6.32.
> Issue 4283: transition Belos to using Tpetra::StaticProfile

- cmake/ctest/drivers/atdm/TrilinosCTestDriverCore.atdm.cmake
CC: @fryeguy52, @mhoemmen 
The reasons for making this name change are:
* Avoid these branches coming up in GitHub PR creation when looking to change
from 'master' to 'develop'.
* Allow for more flexibility in case in the future we want to update from
'master' instead of 'develop'.
* Shorten the names of the branches because, why not.
See above.
> Change name of branches from 'atdm-develop-nightly' to 'atdm-nightly' (TRIL-260)

- packages/zoltan2/src/algorithms/partition/Zoltan2_TaskMapping.hpp
- packages/zoltan2/src/util/Zoltan2_GraphMetricsUtility.hpp
- packages/zoltan2/test/unit/util/findUniqueGids.cpp
@trilinos/zoltan2 @trilinos/stk @alanw0 
Matched directory template parameters to the arguments in directory.update() calls.
@trilinos/stk reported compilation errors with (the equivalent of) Tpetra_INST_INT_LONG=ON.  The errors were due to incorrect ordering of the template parameters in two directory typedefs.
Built and run on linux workstation with Tpetra_INST_INT_INT=OFF and Tpetra_INST_INT_LONG=ON.
Also built and run on linux workstation with default Tpetra instantiations.
Enabled Tpetra_INST_INT_LONG testing in findUniqueGIDs.cpp.
- [x ] I have added tests to cover my changes.
> Zoltan2:  fix directory builds with Tpetra_INST_INT_LONG

- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_decl.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Fix #4392 by rewriting `Ifpack2::OverlappingRowMatrix::apply` to call `Tpetra::CrsMatrix::apply` directly for the two CrsMatrix objects in OverlappingRowMatrix, instead of rerolling `CrsMatrix::apply` in a slow and sequential way.  Fix potential issues with `Tpetra::MultiVector`'s offset view constructor that came up as a result of this fix.  This may also address #4353.
* Closes #4392 
* Related to #4353
> Ifpack2::OverlappingRowMatrix::apply: Fix #4392

- packages/sacado/src/Sacado_CacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRCacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRFad_Ops.hpp
- packages/sacado/src/Sacado_Fad_DFadTraits.hpp
- packages/sacado/src/Sacado_Fad_DMFadTraits.hpp
- packages/sacado/src/Sacado_Fad_DVFadTraits.hpp
- packages/sacado/src/Sacado_Fad_ExpressionTraits.hpp
- packages/sacado/src/Sacado_Fad_Ops.hpp
- packages/sacado/src/Sacado_Fad_Ops_Fwd.hpp
- packages/sacado/src/Sacado_Fad_SFadTraits.hpp
- packages/sacado/src/Sacado_Fad_SLFadTraits.hpp
- packages/sacado/src/Sacado_Fad_SimpleFadTraits.hpp
- packages/sacado/src/Sacado_Fad_ViewFadTraits.hpp
- packages/sacado/src/Sacado_MathFunctions.hpp
- packages/sacado/src/Sacado_Traits.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_ExpressionTraits.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_GeneralFadTraits.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_MathFunctions.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Ops_Fwd.hpp
- packages/sacado/test/TestSuite/FadUnitTests.hpp
- packages/sacado/test/TestSuite/NestedFadUnitTests.hpp
- packages/stokhos/src/sacado/kokkos/vector/Fad/Sacado_Fad_Exp_MP_Vector.hpp
Related to issue #2008.  Recently Sacado's overloads of std::pow() were
changed to use if_then_else() to support use of Sacado with STK's SIMD
type, instead of the ternary operator to check when the base is equal to
0.  However when using if_then_else(), both branches are always
evaluated, and so a FPE can be generated even though the value isn't
used.  This changes the implementation by adding two specializations of
the PowerOp expression template, one for SIMD and one for everything
else, where only the SIMD one uses if_then_else().  This requires any
SIMD type that wants to pick up that implementation specialize
Sacado::IsSimdType<>.
@bartgol @vbrunini
> Sacado:  Add specializations so pow() only uses if_then_else for simd types

- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_def.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/CMakeLists.txt
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/ParameterLists/CMakeLists.txt
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/ParameterLists/ParameterList_TwoLevelPreconditioner_GDSW_muelu.xml
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Stokes_HDF5/main.cpp
- Laplace problem: Adding tests to use MueLu as a coarse level solver within FROSch's GDSW
- Adding a more thorough error check to address #4208 
- Stokes problem: read file name of HDF5-file from the command line
We want to try MueLu as coarse level solver for FROSch's GDSW. This starts with Laplace, but we aim at Stokes (or similar) problems in the end.
* Closes #4208  
I added an Epetra and a Tpetra test for the Laplace problem. Both pass locally.
> ShyLU/FROSch: use Muelu in Laplace problem

- packages/teuchos/core/src/Teuchos_RCPNode.hpp
- packages/tpetra/core/src/Tpetra_Distributor.cpp
- packages/tpetra/core/src/Tpetra_Distributor.hpp
`Tpetra::Distributor` would always fill `indicesFrom_` with 0, 1, ..., `totalReceiveLength_-1`. This was not only a waste of time, it would unnecessarily make all reverse-mode communication take the slow path. (Reversing a Distributor swaps `indicesTo_` and `indicesFrom_`. A nonempty `indicesTo_` tells Distributor to take the slow path. If `indicesFrom_` is just 0, 1, ..., `totalReceiveLength_-1`, then Distributor does not need to take the slow path.)
Note that `Epetra_MpiDistributor` comments out the code that fills `indices_from_`, and claims that doing so fixes reverse communication.
@vbrunini found that applying my patch for fixing this made Aria's post-solve communication of the solution vector of the ViewFactor system a lot faster on 2 GPUs.
* Closes #4412 
* …
> Tpetra::Distributor: Fix #4412 (don't fill indicesFrom_)

- cmake/ctest/drivers/atdm/ride/local-driver.sh
A bunch of tests timeout when running on 'white27', like happened on
'white25'.  When that happens, we loose all of our test results on CDsah
because it times out the bsub job before it can finish. (And we would not want
the test results even if it did subit to CDash.)  The 'white' admins removed
'white25' from the LSF queue on 'white' but they did not remove 'white27'.  See [TRIL-253](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-253).  
Hopefully this commit will eliminate the problem (it looks like it should).
I tested this manually on 'white' by running:
```
$ cd /home/rabartl/Trilinos.base/BUILD/WHITE/JENKINS/
$  env Trilinos_PACKAGES=Kokkos,Teuchos \
CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=FALSE \
./ctest-s-local-test-driver.sh gnu-7.2.0-openmp-debug …
```
> Exclude from running on 'white27' (TRIL-253)

- packages/muelu/src/Misc/MueLu_RAPFactory_def.hpp
- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_SaPFactory_def.hpp
- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
- packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Import_Util2.hpp
- Small fix to make sure that new TAFC is used everywhere in `Tpetra::MatrixMatrix`
- Add override parameter for iallreduce, in case the user knows that new TAFC will work
- Add code path for import without importer (Thanks, @DrBooom )
- Rework how kernel parameters are passed from MueLu.
> Tpetra: TAFC

- packages/stokhos/src/CMakeLists.txt
- packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
- packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
Adding method to replace the diagonal of a CrsMatrix
This addition is required to refactor the HHG driver in MueLu using Xpetra instead of Epetra.
* Closes #4202
* Blocks #4084
A new unit-test has been added to `Xpetra_CrsMatrix`
> Xpetra: replace matrix diagonal

- cmake/std/PullRequestLinuxDriver-Test.sh
Updating PR test driver script to use the `PULLREQUEST_CDASH_TRACK` parameter, if it exists.
I'd like to let this run through tests before we merge the gitlab update to the autotester to add the parameter in, and then rerun the tests once that sees them.
@jwillenbring fyi.
> Parameterized pr cdash track

- cmake/ctest/drivers/atdm/ride/local-driver.sh
The build Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug has 11 tests that
timeout when run on node 'white26' that don't timeout when run on 'white24'.
Therefore, we will assume that 'white26' is not working correctly so we are
excluding it from the pool of nodes to run jobs on 'white'.
NOTE: At this point, we have removed nodes 'white25' (removed from the queue
by the 'white' admins), 'white26' and 'white27'.  Not sure how many nodes that
leaves.
I tested this on 'white' using:
```
$ cd /home/rabartl/Trilinos.base/BUILD/WHITE/JENKINS/
$ env Trilinos_PACKAGES=Kokkos,Teuchos \
CTEST_START_WITH_EMPTY_BINARY_DIRECTORY=FALSE CTEST_DO_SUBMIT=OFF \
./ctest-s-local-test-driver.sh gnu-7.2.0-openmp-debug
***
*** ./ctest-s-local-test-driver.sh  gnu-7.2.0-openmp-debug
***
ATDM_TRILINOS_DIR = …
```
> Exclude using the node 'white26' (TRIL-253)

- packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp
Fix type in MueLu_LocalLexicographicIndexManager_def.hpp for more consistency and to help with Albany build.
Albany has a build error in MueLu because of this issue.
* Closes #4334 
Local build and tests have been run.
> MueLu: modifying type in LocallexicographicIndexManager fix issue #4334

- packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
@trilinos/tpetra  @mhoemmen 
This saved ~50% of our load complete time in a 2 GPU run. Not a huge difference overall, but worthwhile.
> Tpetra: Don't initialize scratch views in UnpackCrsMatrixAndCombineFunctor

- packages/zoltan2/src/algorithms/color/Zoltan2_AlgSerialGreedy.hpp
- packages/zoltan2/src/directory/Zoltan2_Directory.hpp
- packages/zoltan2/src/problems/Zoltan2_OrderingSolution.hpp
- packages/zoltan2/test/order/orderingScotch.cpp
@trilinos/<zoltan2> @ZUUL42 
Small changes to remove compiler warnings in #3178 
Added test of Separator Tree values in orderingScotch.cpp test, to remove compiler warning about unused TreeTab.
Removed unused variable in AlgSerialGreedy coloring.
#3178 
- [ x] I have added tests to cover my changes.
> zoltan2:  removing warnings for #3178

- packages/muelu/src/MueCentral/MueLu_FactoryManager_def.hpp
- packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
- packages/muelu/test/longlong/CMakeLists.txt
Fix issue #4439. When no particular Zoltan2 algorithm is requested, we default to MultiJagged. In that case we also need to ask for "repartition: heuristic target rows per process".
> MueLu: Fix Issue #4439

- packages/kokkos-kernels/unit_test/CMakeLists.txt
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_abs.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_asum.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_axpy.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_dot.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_mult.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_nrm2.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_nrm2_squared.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_nrminf.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_reciprocal.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_scal.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_sum.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_abs.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_axpby.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_axpy.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_dot.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_mult.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_nrm2.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_scal.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_team_update.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_update.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas2_gemv.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas2_team_gemv.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp
#4394 
PR test suffers from long kokkos kernels testing duration. We reduce unit test problem sizes
For level 3 operations, remove 1024,1024,2048 combinations
For level 3 operations, remove 132231 problem sizes
For level 1 operations, remove 132231 problem sizes
For team level operations, remove 132231 and reduce 1024 problem sizes to 124. It does not make sense that a single team process 132231 and 1024 size problem sizes. Team-level operations are mostly for small-mid size problems. It should not bigger than 1000.
> Reduce test problem sizes

- cmake/std/sems/PullRequestCuda9.2TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnvSERIAL.sh
- cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh
- cmake/std/sems/PullRequestGCC7.3.0TestingEnv.sh
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
Not all of the test configurations were setting `OMP_NUM_THREADS`, so this adds that to the configurations.
Setting `OMP_NUM_THREADS=2` initially, @jwillenbring will check with a few folks to see if setting this to 4 won't oversubscribe our systems. If that's fine, I'll update this to set it to 4.
Relates to #4394
> Framework: Adding OMP_NUM_THREADS to PR Testing

- packages/sacado/src/Sacado_CacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRCacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRFad_Ops.hpp
- packages/sacado/src/Sacado_Fad_Ops.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp
- packages/sacado/test/TestSuite/NestedFadUnitTests.hpp
Most Sacado overloads of pow() check for a zero base, and return zero
instead of evaluating the derivative even though in many situations this
isn't technically correct (since the derivative is often not defined
there).  In PR #4380, I changed this behavior for the pow(Fad,Const)
case, where I use a different formula.  This was causing NaN's in
Charon's Jacobian evaluation, so this commit restores the previous
behavior (which again is technically not correct).
> Sacado:  Check for zero base in pow(Fad,Const)

- packages/muelu/src/Misc/MueLu_CoordinatesTransferFactory_kokkos_def.hpp
- packages/muelu/test/structured/CMakeLists.txt
- packages/muelu/test/structured/structured_interp_kokkos.xml
- packages/muelu/test/structured/structured_interp_sa_kokkos.xml
- packages/muelu/test/structured/structured_tentative_kokkos.xml
This adds logic in the CoordinateTransferFactory_kokkos to allow user to perform structured aggregation and hand-off the aggregates to tentative P factory.
Also added xmls and tribits test to check that it all works fine.
This is mainly adding test coverage which is a good thing?
I ran the tests locally and they passed
> MueLu: fixing CoordinateTransferFactory_kokkos for structured aggregation

- packages/teko/src/Teko_Utilities.cpp
Previously the passed in graph was ignored. This lead to problems
if you believed the data was being reused and also was a potential
performance issue
@trilinos/teko
> Teko: Fixing explicit add to reuse memory if requested by user

- packages/pamgen/example/pamgen_test_driver.c
- packages/pamgen/parser/parser.C
- packages/pamgen/src/parse_routines.C
- packages/pamgen/src/parse_routines.h
> Pamgen: Adding parse error (rather than segfault) if you put two geometries in one mesh

- packages/amesos2/src/Amesos2_MUMPS.cpp
This PR is a follow up of [this broken PR](https://github.com/trilinos/Trilinos/pull/4409).
We use Tpetra ETI helper macros to instantiate all necessary combinations.
> Amesos2: Missing explicit instantiations for MUMPS

- cmake/std/atdm/waterman/all_supported_builds.sh
The supported build is gnu-opt-openmp not gnu-debug-openmp.
> Fix waterman/all_supported_builds.sh list

- packages/muelu/adapters/stratimikos/Thyra_XpetraLinearOp_def.hpp
Remove an unneeded copy in the apply of `Thyra::XpetraLinearOp`. As far as I can see, we are copying data inplace. Taking this statement out seems to work. Let's see what the autotester thinks..
> Stratimikos Xpetra adapter: Remove superfluous copy in apply

- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt.sh
Temporary mitigation for #4486 
These Panzer build failures are bring down the SPARC Trilinos Integration
testing since they seem to be causing the install of Trilinos to not occur and
therefore the clang-5.0.1 build of SPARC can't pick this up.  Therefore, these
build failures have taking out SPARC Trilinos Integration testing.  Since
SPARC does not use Panzer and EMPIRE does not build with clang-5.0.1 on CEE
RHEL6, disabling Panzer in this build does not harm anything (other than
disabling the only automated clang testing of Panzer).
Once the build failures can be fixed, we can re-enable this.
I tested this on 'ceerws1113' using:
```
$ ./ctest-s-local-test-driver-cee-rhel6.sh cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt
```
which posed the configure to CDash shown …
> Disable Panzer in clang-5.0.1 build for now (#4486)

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
@trilinos/tpetra @vbrunini @micahahoward
1. Fix #4417: MultiVector unpack with INSERT or REPLACE CombineModes (they do the same thing w/ MV) no longer uses atomic updates, even in parallel.
2. Fix #4418: MultiVector unpack now only does atomic updates (for _any_ CombineMode) if the execution space's `concurrency() > 1`.
Atomic updates are expensive.  We found that removing them increased performance, especially on GPUs.  #962 would check the Export / Import for duplicate unpack LIDs.  That would work and could still work after these changes, and probably would not add much to Export / Import setup time.  However, it would be more complicated to implement.
* Closes #4417, #4418 
* Related to #962 
Mac, Clang, OpenMPI.  We've also tested the #4418 fix on GPUs in Aria.
> Tpetra::MultiVector: Fix #4417 and #4418

- packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
- packages/kokkos/core/src/impl/Kokkos_Atomic_Generic.hpp
This pull request mirrors https://github.com/kokkos/kokkos/pull/1997.
In particular, some of the `Kokkos::atomic_*` could not be used for types with a non-trivial default constructor.
This change is required to allow using the respective functions with, e.g. `std::complex<float>`.
Fixed https://github.com/kokkos/kokkos/issues/1964.
The changes were tested in https://github.com/kokkos/kokkos/pull/1997  and compiling [deal.II](https://github.com/dealii/dealii/) with `CUDA` support in `Trilinos` and `complex` scalar types proceeds further.
> Kokkos: Allow for types with non-trivial constructors in Kokkos_Atomic*

- cmake/std/PullRequestLinuxDriver-Test.sh
This should help with the occasional failures on the 141-4 series.
> Change memory request from 1.7G per cpu to 1.8G

- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt.sh
Allow the enable of Panzer that was removed in commit  cb0da4ae99b539dedc176cd14038fbea182150c7 (see addresses #4486).
Panzer now builds and passes tests.
I tested this with on 'ceerws1113' with:
```
$ ./checkin-test-atdm-cee-rhel6.sh cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt  \
--enable-packages=Panzer --local-do-all
```
which returned:
```
PASSED (NOT READY TO PUSH): Trilinos: ceerws1113
Tue Feb 26 15:00:10 MST 2019
Enabled Packages: Panzer
1) cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt => passed: passed=173,notpassed=0 (24.69 min)
```
> Allow Panzer testing in cee-rhel6 clang-5.0.1 build

- commonTools/framework/clean_workspace/Modules.py
- commonTools/framework/clean_workspace/clean_all_jobs
- commonTools/framework/clean_workspace/clean_all_jobs.py
- commonTools/framework/clean_workspace/clean_sentinel.py
- commonTools/framework/clean_workspace/clean_workspace
- commonTools/framework/clean_workspace/clean_workspace.py
- commonTools/framework/clean_workspace/unittests/test_Modules.py
- commonTools/framework/clean_workspace/unittests/test_clean_all_jobs.py
- commonTools/framework/clean_workspace/unittests/test_clean_sentinel.py
- commonTools/framework/clean_workspace/unittests/test_clean_workspace.py
- commonTools/framework/clean_workspace/util.py
These scripts will do a few things to improve jenkins
space usage.
'clean_workspace --force %s' will clean the build products
from the %s directory but not remove the clones. I expect
this to be useful after a job runs
'clean_workspace %s' will lok up the last time this workspace
was cleaned, compare that to the last time a clean request
was issued, and call make clean in the passed diretory if
needed. We can place this at the start of the job and have it
always check.
'clean_all_jobs' will just reset the date that the clean_workspace
jobs use. I expect we will create a jenkins job to be launched
by hand that does this.
Still needed is a way to remove all workspaces that are not
actively being built - clones and all. I have seen a few
groovy scripts that will do this, but those must be …
> New scripts for getting jenkins to clean up (somewhat)

- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-shared-release-debug-pt.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-shared-release-debug.sh
- cmake/ctest/drivers/atdm/waterman/drivers/Trilinos-atdm-waterman-cuda-9.2-rdc-shared-release-debug.sh
Related to #2598, #4501, #4502 
Since SPARC does shared CUDA builds, adding these builds makes sense.  There
is also some hope this will fix some of the link errors.
I tested this as described below.
On 'ride' I ran:
```
$ env ./ctest-s-local-test-driver.sh cuda-9.2-gnu-7.2.0-rdc-shared-release-debug-pt
***
*** ./ctest-s-local-test-driver.sh  cuda-9.2-gnu-7.2.0-rdc-shared-release-debug-pt
***
Hostname 'ride6' matches known ATDM host 'ride' and system 'ride'
Setting compiler and build options for buld name 'default'
Using white/ride compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL and KOKKOS_ARCH=Power8
Running builds: …
```
> Add some CUDA RDC shared builds (#2598, TRIL-262)

- cmake/std/atdm/sems-rhel6/all_supported_builds.sh
- cmake/std/atdm/sems-rhel6/environment.sh
None of the ATDM APPs need support for gnu-6.1.0 anymore. They are all using
gnu-7.2.0.  See [TRIL-263](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-263).
Now the default compiler and the default gnu compiler are gnu-7.2.0 on
'sems-rhel6'.
I tested this on my machine 'crf450' with:
```
$ ./checkin-test-atdm.sh all --enable-packages=Kokkos,Teuchos --local-do-all
```
```
PASSED (NOT READY TO PUSH): Trilinos: crf450.srn.sandia.gov
Mon Mar  4 09:26:54 MST 2019
Enabled Packages: Kokkos, Teuchos
1) sems-rhel6-gnu-7.2.0-openmp-debug => passed: passed=164,notpassed=0 (1.55 min)
2) sems-rhel6-gnu-7.2.0-openmp-release => passed: passed=164,notpassed=0 (0.41 min)
3) sems-rhel6-gnu-7.2.0-openmp-release-debug => passed: …
```
> Remove testing of gnu-6.1.0 builds and make gnu-7.2.0 the default (TRIL-263)

- commonTools/framework/clean_workspace/clean_all_jobs.py
The class is set up to allow me to test the script,
but that means the python interpreter doesn't see
anything to run when the script is called at the
command line.
> Add a main method to this python script

- packages/muelu/research/mmayr/hhg/Xpetra_RegionMatrix_decl.hpp
Ifpack2 requires to either include both Ifpack2_OverlappingRowMatrix_decl.hpp and Ifpack2_OverlappingRowMatrix_def.hpp or simply Ifpack2_OverlappingRowMatrix.hpp that is generated during ETI.
I am going with the second option but the first one might be more robust when ETI is OFF?
The current code does not compile properly because of this bug
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
A local build triggering the defect has been performed and after the modification is applied the defect is resolved.
> MueLu: modifying included file in hhg driver

- packages/triutils/src/CMakeLists.txt
@trilinos/triutils 
Moving Trilinos_Util_svbrres.cpp into the list of objects to be built only when Epetra is enabled due to its dependence on Trilinos_Util_dusmm.cpp (there is call to DGEMM that triggers this dependence).
When building trilinos with Epetra=OFF the linker errors because of an undefined reference to `Trilinos_Util_dusmm`
* Follows #4386
A local build with Epetra=OFF has been successful
> TriUtils: modifying CMakeLists.txt to avoid undefined reference with Epetra=OFF

- cmake/std/atdm/ATDMDisables.cmake
- cmake/std/atdm/ride/all_supported_builds.sh
CC: @trilinos/tpetra, @mhoemmen, @fryeguy52 
The ATDM customer SPARC needs TSQR enabled (see #4526).   Here, I just allowed the enable of `TpetraTSQR` so that the ATDM Trilinos builds can test it and will install it.
I tested in all of the builds on 'ride' shown below and everything passed.   This tested on 'gnu-7.2.0' and 'cuda-9.2-gnu-7.2.0'.  This did not test on 'clang' or 'intel' but I think that is a pretty small risk.  I think at this point, it is okay to go ahead and turn on `TpetraTSQR` and see what happens across all of the ATDM Trilinos builds.  If there are any new failures triggered by this, we can create new ATDM Trilinos GitHub issues for these.
NOTE: I also cleaned up the set of "supported" builds to only be the "Promoted" ATDM Trilinos builds we are currently running and …
>  Allow enable of TpetraTSQR in ATDM Trilinos builds (#4526)

- packages/belos/tpetra/src/Belos_Details_Tpetra_registerSolverFactory.cpp
- packages/belos/tpetra/test/Native/diagonal_matrix.cpp
- packages/belos/tpetra/test/Native/nonsymm_matrix.cpp
@trilinos/belos @jhux2 @iyamazaki 
Make sure that the new (pipelined and communication-avoiding) Tpetra-specific solvers get registered (at run time) with `Belos::SolverFactory`.  Once this change lands, we will be able to remove that registration from Nalu.  (Registration is idempotent; double registration is harmless.)
> Belos: Fix #4544

- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
Last a few commits that I made for Ifpack2 cause slowness in SPARC. The reason for the slowness is surprisingly from some template instanciations. I cannot precisely explain why. Previously we use macros for blockwise specialization and I changed it to template implementation for doing the same thing. After changing it back to macro expressions, it recovers the previous performance. Sigh Sigh Sigh....  Mystery.... 
This is tested on Apollo and @vbrunini confirmed that it is fixed on SPARC.
> Fix for Ifpack2 that causes SPARC slowness. 

- packages/muelu/research/mmayr/composite_to_regions/src/CMakeLists.txt
- packages/muelu/research/mmayr/composite_to_regions/src/main.cpp
Remove the dependency of the MueLu HHG driver on `Trilinos_ENABLE_ML` as in fact ML is not required and used.
This brings the MueLu HHG driver one step closer to a cleaner configuration.
Build and tests pass locally.
> MueLu/HHG: Remove dependency on ML package

- packages/amesos2/src/Amesos2_Superlu_TypeMap.hpp
This fixes an issue when enabling SuperLU and Umfpack with complex
double types enabled. Addresses issue #4563
Issue reported by Sam Browne.
Tested with gcc/6.5 and mpich on MacOSX High Sierra
```
#!/bin/bash
TRILINOS_DIR=${PWD}/../..
TPL_PATH=/Users/ndellin/Research/TPL/GCC6.4
BLAS_PATH=${TPL_PATH}/BLAS-3.6.0
LAPACK_PATH=${TPL_PATH}/lapack-3.6.1
SCOTCH_PATH=${TPL_PATH}/scotch_6.0.3
PARMETIS_PATH=${TPL_PATH}/parmetis-4.0.3/install
METIS_PATH=${TPL_PATH}/metis-5.1.0/install
SUPERLU_PATH=${TPL_PATH}/SuperLU_4.3
SUPERLU_DIST_PATH=${TPL_PATH}/SuperLU_DIST_4.2
SS_PATH=${TPL_PATH}/SuiteSparse-4.1.0
export INSTALL_LOCATION=${PWD}/install
rm -rf CMake*
cmake \
-D Trilinos_EXTRA_LINK_FLAGS:STRING="" \
-D CMAKE_BUILD_TYPE:STRING=release \
-D Trilinos_ENABLE_OpenMP:BOOL=OFF \
-D …
```
> Amesos2: Update SuperLU TypeMap

- cmake/std/atdm/README.md
- cmake/std/atdm/sems-rhel7/all_supported_builds.sh
- cmake/std/atdm/sems-rhel7/environment.sh
This makes the Intel compiler run much much faster on the machines 'cortado' and 'ascicgpu15' where this was tested.
I tested this on 'ascicgpu15' using:
```
sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug \
--enable-packages=Kokkos,Teuchos --local-do-all --wipe-clean
```
```
PASSED (NOT READY TO PUSH): Trilinos: ascicgpu15
Thu Mar  7 09:51:48 MST 2019
Enabled Packages: Kokkos, Teuchos
1) sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug => passed: passed=164,notpassed=0 (6.78 min)
```
So the intel build is still slow compared to the other builds but not 42 minutes slow like shown [here](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-264?focusedCommentId=26200&page=com.atlassia …
> Fix the default Intel compiler license server for 'sems-rhel7' env (TRIL-255)

- packages/teko/src/Teko_ReorderedLinearOp.cpp
- packages/teko/src/Teko_ReorderedLinearOp.hpp
Previously this printed the useless "ReorderedLinearOp" string. Now
it has information about the underlying operator.
Changed the describe method
Trying to debug something and this didn't worked and slowed down the process.
> Teko: Adding a "describe" method to the ReorderedLinearOp

- packages/amesos2/src/Amesos2_PardisoMKL_FunctionMap.hpp
- packages/amesos2/src/Amesos2_PardisoMKL_TypeMap.hpp
Addresses issue #4458
Tested on blake testbed
`module load cmake/3.12.3 intel/compilers/18.1.163 openmpi/2.1.2/intel/18.1.163`
`salloc -N 1`
```
TRILINOS_DIR=${PWD}/../..
TRILINOSINSTALLDIR=${PWD}/install
BUILDTYPE=release
rm -f CMakeCache.txt
rm -rf CMakeFiles
export BLAS_LIBRARIES="-mkl;${MKLROOT}/lib/intel64/libmkl_intel_lp64.a;${MKLROOT}/lib/intel64/libmkl_intel_thread.a;${MKLROOT}/lib/intel64/libmkl_core.a"
export LAPACK_LIBRARIES=${BLAS_LIBRARIES}
cmake \
-D Trilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES:BOOL=ON \
-D CMAKE_INSTALL_PREFIX:PATH=${TRILINOSINSTALLDIR} \
-D CMAKE_BUILD_TYPE:STRING=${BUILDTYPE} \
-D TPL_ENABLE_MPI:BOOL=ON \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Teuchos_ENABLE_STACKTRACE:BOOL=ON \
-D …
```
> Amesos2: pardiso fixes

- cmake/TPLs/FindTPLSuperLU.cmake
- packages/amesos2/src/Amesos2_Superlu_TypeMap.hpp
- packages/amesos2/src/Amesos2_Superludist.cpp
Amesos2: Fix for superludist when float is enabled
Remove float and complex<float> from ETI since superludist only
implements double and complex<double>
Should address issue #3566
Tested on MacOSX HighSierra, gcc/6.5, mpich, superludist 5.2.2
> Issue 3566

- packages/xpetra/src/Map/Xpetra_MapFactory.hpp
- packages/xpetra/src/Map/Xpetra_TpetraMap.hpp
- packages/xpetra/test/Map/Map_UnitTests.cpp
This simply adds a path in Xpetra to construct a map using a Kokkos::View
This is part of the overall kokkos refactor work in Xpetra
This will allow greater performance in downstream packages that rely on Xpetra and are performing code refactor with kokkos
* Closes #4576 
I did a local build with and without Epetra and both builds were successful.
I also added a new unit-test that builds a map using the new constructor and checks that the data stored in it is reasonable.
> Xpetra: implementation of new Xpetra map constructor to resolve issue #4576

- cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
While this runs in about 10 seconds on CPU machines it is running
anywhere from 400-600 on CUDA equipment.  This needs to be properly
triaged and repaired before re-enabling it.
@trilinos/rol 
Disabled this test until the ROL team can address it. This will allow other teams to get pull requests tested in a reasonable time frame.
Since this is just a test disable I expect that the PR testing is the best way to confirm it works as expected.
> This disables the ROL_NonlinearProblemTest_MPI_4 test for cuda testing

- cmake/TPLs/FindTPLSuperLU.cmake
- packages/amesos2/src/Amesos2_Superludist.cpp
Remove float and complex<float> from ETI since suplerludist only
implements double and complex<double>
> Amesos2: Fix for superludist when float is enabled

- cmake/ctest/drivers/sems_ci/README
- cmake/ctest/drivers/sems_ci/trilinos_ci_sever.sh
This will test to see how long we can go just rebuilding Trilinos without requiring a rebuild from scratch.  This will show how fast incremental rebulids can be with Trilinos using just 16 cores.
I tested this locally with:
```
$  env  \
Trilinos_PACKAGES=Kokkos,Teuchos \
CTEST_DO_UPDATES=OFF \
TRILINOS_CI_SKIP_EMAILS=1 \
./Trilinos/cmake/ctest/drivers/sems_ci/trilinos_ci_sever.sh &> trilinos_ci_sever.out
```
and
```
$  env  \
Trilinos_PACKAGES=Kokkos,Teuchos \
CTEST_DO_UPDATES=OFF \
TRILINOS_CI_SKIP_EMAILS=1 \
TRILINOS_CI_DO_INITIAL_REBUILD=1 \
./Trilinos/cmake/ctest/drivers/sems_ci/trilinos_ci_sever.sh &> trilinos_ci_sever.out
```
and it looked like it was doing the right thing (not an initial rebuild at first and doing an initial rebuild from …
> Change post-push CI server to only rebuild by default (#482)

- packages/sacado/src/Sacado_CacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRCacheFad_Ops.hpp
- packages/sacado/src/Sacado_ELRFad_Ops.hpp
- packages/sacado/src/Sacado_Fad_Ops.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp
- packages/sacado/test/TestSuite/NestedFadUnitTests.hpp
- packages/stokhos/src/sacado/kokkos/vector/Fad/Sacado_Fad_Exp_MP_Vector.hpp
My change of the formula for differentiating std:pow(x,y) with constant
y seems to be causing some numerical stability issues (which is
surprising because it just replaces x^y/x with x^{y-1}).  So I am
reverting that change and going back to the old formula.  I still want
to understand why it is problematic, but it is impacting a customer, so
I am changing it now anyway.  See here for the relevant discussion:
https://cee-gitlab.sandia.gov/Charon/tcad-charon/issues/96#note_179767
> Sacdo:  Fix std::pow(Fad,Const) again.

- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_decl.hpp
- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
- packages/tpetra/core/test/CrsMatrix/Equilibration.cpp
Per request by @vbrunini, add Tpetra:::computeRowOneNorms function.  @vbrunini wants to use it just for left-side scaling of a matrix.  @ikalash may appreciate this, as it closes #240 more directly than the current `Tpetra::computeRowAndColumnOneNorms` function, without additional computation or communication (if you only want to scale on the left).
* Closes #4542 
* Related to #240
> Tpetra: Fix #4542 (add computeRowOneNorms)

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_DistObject_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_ReplaceDiagonal.cpp
@trilinos/tpetra @trilinos/framework 
Fix some Tpetra build warnings that block building with warnings as errors.
> Tpetra: Fix build warnings

- cmake/std/atdm/common/toss3/environment.sh
- cmake/std/atdm/sems-rhel6/environment.sh
- cmake/std/atdm/sems-rhel7/environment.sh
This just unloads the sems-python module that is automatically loaded by the sems-boost module on the rhel6 and rhel7 systems
having this python loaded is annoying to developers and I don't think we need it
I ran builds on rhel6, rhel7, and chama and they seem fine 
@bartlettroscoe do you have any concerns about doing this? Scot requested this on his behalf and other empire folks
> unload sems-python after loading sems-boost

- cmake/std/atdm/sems-rhel6/environment.sh
This is the right thing to do and this shows how to explictly set which libs you use to try to get around a problem with Spack-installed shared library files (not for this env but for an 'spack-rhel6' env).
This changes just the libs for HDF5 and Netcdf.  The pnetcdf lib had to stay *.a because SEMS does not install a *.so for that lib.
I tested this on 'crf450' with:
```
$ cd /home/rabartl/Trilinos.base/BUILDS/ATDM/CHECKIN
$ ./checkin-test-atdm.sh  \
sems-rhel6-gnu-7.2.0-openmp-static-release-debug \
sems-rhel6-gnu-7.2.0-openmp-shared-release-debug \
sems-rhel6-intel-17.0.1-openmp-release \
--enable-packages=SEACAS --enable-fwd-packages --local-do-all
```
which returned:
```
PASSED (NOT READY TO PUSH): Trilinos: crf450.srn.sandia.gov
Wed Mar 13 17:13:06 MDT 2019
Enabled Packages: SEACAS …
```
> Explicitly use *.so or *.a libs for shared or static builds for 'sems-rhel6' env (CDOFA-41)

- cmake/std/PullRequestLinuxCommonTestingSettings.cmake
- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
Ifpack2 blodk tridiag solver fails when kokkos bound check is enabled. I put an additional index guard in extract routine. 
#4597 
Tested on white P100.
@jjellio @jhux2
> Ifpack2 - for the testing with kokkos bound check

- packages/teuchos/CMakeLists.txt
@trilinos/teuchos @trilinos/framework @theguruat12 @rrdrake 
Make it possible to cross-compile Teuchos and downstream packages with `Scalar=float` enabled.
* Closes #4600
> Teuchos: Fix #4600

- cmake/std/atdm/cee-rhel6/environment.sh
Since this is not an OpenMP build, removed all of the OpenMP env vars and set
--bind-to none.  This reduced runtime from 45 minutes to 10 minutes.
> Reduce test wallclock time for cee-rhel6 gnu-7.2.0 build (TRIL-243)

- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
- packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap.hpp
`setObjectLabel` for matrix objects now applies the label to both the wrapper and the underlying matrix object. 
@pwxy
> Xpetra: Apply labels to wrapper and underlying object

- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_decl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_decl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_impl.hpp
Refactor `panzer::Integrator_GradBasisTimesScalar` such that it supports `CONTRIBUTES`-style evaluation.  Also Kokkos-ify the `evaluateField()` routine.  Closes #1893.
See the discussion in #1575.
CTest passes on my RHEL7 machine.
> Resolves "Panzer:  Update Integrator_GradBasisTimesScalar"

- cmake/std/atdm/cee-rhel6/all_supported_builds.sh
SPARC does not need this build and since the gnu-7.2.0 build's test suite was
made to run fast (see [TRIL-269](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-269)), we don't need to compare against the old
gnu-4.9.3 build anymore (see [TRIL-243](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-243))
Note that I did not remove the env for the GNU 4.9.3 build in case someone
wants to test it locally.
NOTE: The automated builds that submit to CDash will automatically get updated with this one change because a local cron job with a script the reads this file will get called.
> Remove build cee-rhel6_gnu-4.9.3_openmpi-1.10.2_serial_shared_opt from nighlty testing (TRIL-243)

- packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp
@trilinos/belos @jjellio @hkthorn @vbrunini @iyamazaki 
Change `Belos::PseudoBlockGmresSolMgr`'s default orthogonalizer from DGKS (modified Gram-Schmidt with careful checks) to ICGS (classical Gram-Schmidt, repeated unconditionally).
1. Get better performance with default settings
2. Make Belos behave like AztecOO out of the box
* Closes #994
> Belos: Fix #994 (make ICGS default orthogonalizer for GMRES)

- packages/thyra/adapters/tpetra/src/Thyra_TpetraThyraWrappers_decl.hpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraThyraWrappers_def.hpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_decl.hpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp
- packages/thyra/adapters/tpetra/test/TpetraThyraWrappers_UnitTests.cpp
Fixes #4616
@trilinos/thyra
This PR adds a getter to Thyra::TpetraVectorSpace, to retrieve the underlying Tpetra::Map.
All other Thyra::TpetraXYZ wrappers allow this behavior. While for (Multi)Vector such behavior is bypassable (via methods of base classes returing local data), the Map's capabilities are not accessible via base classes.
* Closes 4616
I added a check in `TpetraThyraWrappers_UnitTests.cpp`, to check that the map wrapped in a newly created Thyra::TpetraVectorSpace was indeed the same as the original Tpetra::Map
> ThyraTpetraAdapters: Added getter for Tpetra::Map in Thyra::TpetraVectorSpace

- cmake/std/atdm/sems-rhel7/environment.sh
This is needed to get EMPIRE's Intel builds up and running again.  @bathmatt can fill in the details as to what's going wrong and why this fixes it.  Might be related to #4038 and #3914.  See also 
[this article from Intel regarding the bug](https://software.intel.com/en-us/articles/intel-math-kernel-library-intel-mkl-2018-bug-fixes-list).
> **Note:**  We can revert this once we update to intel-18.0.5+.
This is holding up EMPIRE's CI testing.
> Temporary Fix for Intel MKL Bug

- cmake/std/PullRequestLinuxDriver-Test.sh
This is in response to several MueLu build failures
on full builds. Since this likely will relieve some
swapping it should help time on full builds or be a
wash. Might make small/medium builds a bit slower.
We will need to monitor to see if this is enough and let the MueLu team know whats going on.
> move from 1.8G/core to 2.1

- cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt.sh
- cmake/std/atdm/cee-rhel6/environment.sh
This uses MPI and OpenMP settings discovered by Brad King (Kitware) that massively improve the runtime of the ATDM Trilinos test suite for the build `Trilinos-atdm-cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt` bringing down the time from currently over 2 hours as shown [here](https://testing.sandia.gov/cdash-dev-view/index.php?project=Trilinos&parentid=4769282) to less than 9 minutes (see below).
This also seems to have fixed the timing out tests reported in #4251 #4260, and #4262. 
NOTE: The following tests FAILED:
1477 - STKBalance_stk_balance_MPI_4 (Failed)
1478 - STKBalance_stk_balance_m2n_MPI_4 (Failed)
But these tests also fail in the promoted cee-rhel6-intel-17.0.1 build so there is no reason to block the promotion of this build.
I tested this on 'ceerws1113' where the …
> Improve cee-rhel6 intel-18.0.2 OpenMP test suite runtimes (#4251, #4260, #4262)

- packages/sacado/src/KokkosExp_View_Fad.hpp
- packages/sacado/src/Kokkos_DynRankView_Fad.hpp
- packages/sacado/src/Sacado_Fad_ViewStorage.hpp
- packages/sacado/src/mpl/Sacado_mpl_for_each.hpp
Comment out unused parameters in function definitions to avoid `-Wunused-parameter` warnings.
Clean build.
> Sacado:  Remove Unused Parameter Warnings

- packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_Cn_FEM_ORTHDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_Cn_FEM_ORTHDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_C0_FEMDef.hpp
- packages/intrepid2/src/Discretization/Integration/Intrepid2_Cubature.hpp
- packages/intrepid2/src/Shared/Intrepid2_PointToolsDef.hpp
- packages/intrepid2/src/Shared/Intrepid2_Utils.hpp
> Intrepid2:  Remove Unused Parameter Warnings

- packages/nox/src/NOX_Observer.hpp
- packages/nox/src/NOX_Observer_Log.cpp
- packages/nox/src/NOX_SolverStats.hpp
@trilinos/nox 
Comment out unused parameters in function definitions to avoid
Clean build.
> NOX:  Remove Unused Parameter Warnings

- packages/piro/src/Piro_TempusSolver_Def.hpp
Piro: fixing Albany compilation error by replacing setInitialState()
with initializeSolutionHistory() per recent changes in Tempus.
> Piro tempus solver albany fix

- packages/zoltan/src/include/zoltan_cpp.h
> Zoltan:  Remove Unused Parameter Warnings

- packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp
- packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_FECrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Comment out unused parameters in function definitions to avoid
Clean build.
> Tpetra:  Remove Unused Parameter Warnings

- packages/zoltan2/src/algorithms/Zoltan2_Algorithm.hpp
- packages/zoltan2/src/algorithms/order/Zoltan2_AlgAMD.hpp
- packages/zoltan2/src/algorithms/order/Zoltan2_AlgNatural.hpp
- packages/zoltan2/src/algorithms/order/Zoltan2_AlgRCM.hpp
- packages/zoltan2/src/algorithms/order/Zoltan2_AlgRandom.hpp
- packages/zoltan2/src/algorithms/order/Zoltan2_AlgSortedDegree.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgParMA.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgParMETIS.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgPuLP.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgScotch.hpp
- packages/zoltan2/src/algorithms/partition/Zoltan2_MultiJagged_ReductionOps.hpp
- packages/zoltan2/src/algorithms/zoltan/Zoltan2_AlgZoltan.hpp
- packages/zoltan2/src/algorithms/zoltan/Zoltan2_AlgZoltanCallbacks.hpp
- packages/zoltan2/src/directory/Zoltan2_Directory_Comm.cpp
- packages/zoltan2/src/environment/Zoltan2_IntegerRangeList.hpp
- packages/zoltan2/src/input/Zoltan2_Adapter.hpp
- packages/zoltan2/src/input/Zoltan2_GraphAdapter.hpp
- packages/zoltan2/src/models/Zoltan2_CoordinateModel.hpp
- packages/zoltan2/src/models/Zoltan2_GraphModel.hpp
- packages/zoltan2/src/models/Zoltan2_IdentifierModel.hpp
- packages/zoltan2/src/problems/Zoltan2_OrderingProblem.hpp
- packages/zoltan2/src/problems/Zoltan2_Problem.hpp
- packages/zoltan2/src/util/Zoltan2_EvaluateBaseClass.hpp
> Zoltan2:  Remove Unused Parameter Warnings

- packages/tempus/src/Tempus_StepperImplicit_impl.hpp
In the relative norm calculation, the denominator is not check if
it is zero during the consistency check.  Fix it.
All Tempus tests pass.
#4698
Passes all tests on a Mac platform.
> Tempus: Fix Divide by Zero

- packages/teuchos/parameterlist/src/Teuchos_VerboseObjectParameterListHelpers.cpp
Currently, VerboseObject provides an option to allow output to be redirected to a file. Unfortunately, this feature results in every MPI process opening/writing the file, which is not typically what an OStream is used to accomplish. For file output, this implementation leads to extreme performance degradation with large parallel jobs.
This patch accomplishes two things:
1) It restricts file opening/writing to a single MPI process.
The implementation of this is problematic, because VerboseObject's sublist reader has no access to any Comm. Ideally, the interface should be refactored to allow a comm to be passed, so that the logic
can use the com to enforce which rank writes output.
For now, the implementation guards the use of Teuchos::GlobalMPISession to obtain the …
> Teuchos: VerboseObject fix filestreams

- packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
- packages/tpetra/core/src/Tpetra_Details_DualViewUtil.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
- packages/tpetra/core/test/FEMultiVector/FEMultiVector_UnitTests.cpp
- Remove use of C++11 thread stuff from `Tpetra::Details::Behavior`.
- Fix Tpetra build warnings observed on the Dashboard
1. GCC annoyingly requires linking with libpthread in order for that stuff to work.  GCC apparently generates code that crashes, if Trilinos was not built with libpthread support.  I consider that a GCC bug, but we have to work around.
2. `std::call_once` etc. only help with thread safety of code that uses `std::thread` threads.  They don't help with other thread models, like OpenMP (or even Pthreads).  This reduces the value of this feature.
* Closes #4729
> Tpetra: Fix #4729

- packages/pamgen/extra_functions/pamgen_extras.cpp
- packages/pamgen/mesh_spec_lt/im_ex_c_interface.C
- packages/pamgen/mesh_spec_lt/im_ex_c_interface_l.C
- packages/pamgen/mesh_spec_lt/im_ne_c_interface.C
- packages/pamgen/mesh_spec_lt/im_ne_c_interface_l.C
- packages/pamgen/rtcompiler/Function.C
- packages/pamgen/rtcompiler/RTC_OperatorRTC.hh
- packages/pamgen/rtcompiler/RTC_ValueRTC.hh
- packages/pamgen/rtcompiler/RTC_VariableRTC.hh
- packages/pamgen/src/element_density_function.C
- packages/pamgen/src/geometry_transform.C
- packages/pamgen/src/inline_mesh_desc.C
- packages/pamgen/src/inline_mesh_desc.h
- packages/pamgen/src/radial_trisection_inline_mesh_desc.C
@trilinos/pamgen 
Clean build.
> Pamgen:  Remove Unused Parameter Warnings

- packages/nox/test/epetra/LOCA_Brusselator_xyzt/brussXYZT_bdsdt.C
Closes #4725 
Test was taking 75 Newton steps to converge. Enabling line search drops this to 23 steps and makes it robust on intel compilers.
> Nox: fix brusselator for intel compiler

- cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
This sets Werror for SEACAS.
This is work toward #3178 turning Werror on for all packages.
Allowed by work from Issue #4514 & PR #4518.
> Set Werror for SEACAS

- commonTools/framework/clean_workspace/clean_workspace.py
- commonTools/framework/clean_workspace/unittests/test_clean_all_jobs.py
- commonTools/framework/clean_workspace/unittests/test_clean_workspace.py
the --force-clean flag had two conflicting names
and the final   make command (make -C %s clean)
failed in an infinite recursion.  I just modified
it to cd to the directory first and then run 'make clean'
tested with the unit tests and I created a directory, built and used both the date and force options to clean it.
> clean_workspace: correct flag and make command

- packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
- packages/tpetra/core/inout/Tpetra_MatrixIO_def.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_RowMatrix_def.hpp
- packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests0.cpp
- packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests_Swap.cpp
- packages/tpetra/core/test/CrsMatrix/Bug5978.cpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests_Swap.cpp
- packages/tpetra/core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp
- packages/tpetra/core/test/RowMatrixTransposer/main.cpp
- packages/tpetra/core/test/TpetraUtils_MatrixGenerator.hpp
Deprecate `Tpetra::CrsGraph` and `Tpetra::CrsMatrix` constructors that take `ArrayRCP<const size_t>` for the maximum number of entries per row.  Replace them with `ArrayView<const size_t>` constructors.
Deprecation deadline for the next Trilinos release is coming soon.  Also, I can't get any other PRs through PR testing, so I might as well try something.
* Closes #4680
> Tpetra: Fix #4680

- packages/belos/tpetra/src/solvers/Belos_Tpetra_Cg.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_CgPipeline.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_CgSingleReduce.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_Gmres.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPipeline.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresS.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_SolverManager.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_SolverManagerBase.hpp
- packages/tpetra/core/src/Tpetra_Details_allReduceView.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
- packages/tpetra/core/test/MultiVector/CMakeLists.txt
- packages/tpetra/core/test/MultiVector/MV_reduce_strided.cpp
@trilinos/tpetra @trilinos/belos @vbrunini 
This PR supersedes PR #4648.  I've extracted out the parts of #4648 that are actual bug fixes rather than optimizations.  Here they are:
- Fix #4639 (an actual correctness bug in `Tpetra::MultiVector::reduce` that hindered solving #4626)
- Fix #4633 (a strange thing in `Tpetra::MultiVector` that could lead to bugs, especially with `FEMultiVector`)
- Clean up a few things in Belos
The part of PR #4648 I did _not_ include here is the fix for #4626.  That triggers a likely Intel compiler bug in PR tests, which is why I'm not including it.  I have a multiple-step work-around in progress; see PR #4734 for the start of that.
* Closes #4639, #4633 
* Blocks #4626 
* Related to #4640, #4648, #4734 
With and without CUDA.
> Tpetra: Fix #4633 & #4639

- packages/tempus/src/Tempus_StepperNewmarkExplicitAForm_impl.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAForm_impl.hpp
This PR addressed the following Albany issue https://github.com/SNLComputation/Albany/issues/461 by fixing floating point exceptions in some of the Newmark steppers.  These were only showing up in a debug build with FPE checking on. 
All Tempus tests pass, as do all Albany Tempus tests with the fix.
> Tempus fix fpes

- packages/belos/tpetra/src/BelosMultiVecTraits_Tpetra.hpp
- packages/tpetra/core/src/Tpetra_Details_StaticView.hpp
@trilinos/belos @trilinos/tpetra @vbrunini 
Make the Tpetra specialization of Belos::MultiVecTraits use static CUDA allocations for temporary local MultiVectors (e.g., for `Tpetra::MultiVector::multiply` results).  The fix always creates contiguous allocations, so it does not depend on the fix for #4639 in PR #4747 (merged into develop yesterday).
This change supersedes PR #4648, which in turn superseded PR #4640.
We've seen this improve GPU performance in solves.
* Closes #4626 
* Related to #4648, #4734, #4640
> Belos: Fix #4626 (Tpetra specialization of MultiVecTraits)

- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt-pbp.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-shared-release-debug-pt.sh
- cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-release-debug-pt.sh
- cmake/std/atdm/ATDMDevEnvAllPtPackages.cmake
Now that the system automatically adjusts for all Primary Tested packages with the '-pt' and '_pt' matching, we don't need the file ATDMDevEnvAllPtPackages.cmake anymore.  (Related to #4502.)
Also, we don't need the build:
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt-pbp.sh
anymore because the all-at-once build will pass now.
I tested this on 'ride' with:
```
./ctest-s-local-test-driver.sh cuda-9.2-gnu-7.2.0-rdc-release-debug-pt
***
*** ./ctest-s-local-test-driver.sh  cuda-9.2-gnu-7.2.0-rdc-release-debug-pt
***
Hostname 'ride6' matches known ATDM host 'ride' and system 'ride'
Setting compiler and build options for buld name 'default'
Using white/ride compiler stack …
```
> Remove file ATDMDevEnvAllPtPackages.cmake (#4502)

- packages/sacado/src/parameter/Sacado_ParameterLibraryBase.hpp
Needed for, e.g., unit-tests in codes that need to recreate the
parameter library every test, but use a singleton library.
> Sacado:  Add method to clear parameter library.

- packages/nox/src-loca/src/LOCA_Description.H
- packages/nox/src-loca/src/LOCA_Stepper.C
- packages/nox/src-loca/src/LOCA_Stepper.H
Previously the LOCA Stepper didn't compute any eigenvalues on the final
target step when LOCA attempts to hit the parameter bound.  I added
another parameter, "Compute Eigenvalues On Target Step", to enable this.
I didn't just use the existing parameter, "Compute Eigenvalues", because
that would change LOCA's default behavior when computing eigenvalues,
and was unsure of the consequences for existing applications.
> LOCA:  Add parameter and logic to compute eigenvalues on target step.

- cmake/std/atdm/sems-rhel7/environment.sh
use the new intel 18.0.5 mkl module on sems-rhel7 builds.  They still will use the intel-17 compiler but with the 18.0.5 mkl
mkl-17 has been discovered to be the cause of test failures.  This was fixed in 18.0.5
On a sems rhel7 login machine I ran:
```
JOB_NAME=Trilinos-atdm-sems-rhel7-intel-17.0.1-openmp-complex-shared-release-debug
source $TRILINOS_SRC_DIR/cmake/std/atdm/load-env.sh $JOB_NAME
cmake \
-GNinja \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake,cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake \
-DTrilinos_ENABLE_ALL_PACKAGES=ON \
$TRILINOS_SRC_DIR
make NP=16
ctest -j8
```
and had all tests pass:
```
100% tests passed, 0 tests failed out of 2078
Subproject Time Summary:
Amesos2          =   7.59 …
```
> change the atdm sems-rhel7 env to use mkl-18.0.5

- cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
- packages/domi/src/Domi_MDMap.hpp
- packages/domi/src/Domi_MDVector.hpp
@trilinos/domi
This sets Werror for Domi in the GCC 7.2.0 PR build and makes a couple minor changes to take care of errors Werror creates.
This is work toward #3178 turning Werror on for all packages and takes care of [these issues](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=4623048) for Domi from #4506.
> Werror domi fix

- packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_avail.hpp
- packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
@trilinos/tpetra @trilinos/belos @vbrunini 
This PR supersedes PR #4636.
Trilinos' snapshot of kokkos-kernels in order to fix #4630.
Thanks to Kyungjoo and Victor for feedback.
Tpetra builds and passes tests with these changes.
* Closes #4630 
* Related to #4626
> Kokkos-kernels: Fix #4630

- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
CC: @trilinos/tpetra 
This allows SPARC to build again without requiring any changes to SPARC.
Should not this Xpetra function be deprecated as well?
> Remove usage of deprecated Tpetra::CrsMatrix constructor (#4770)

- packages/tpetra/core/src/Tpetra_Details_StaticView.hpp
CC: @trilinos/tpetra 
This one unused var warning brings down the entire1 -Werror builds of SPARC.
I tested this with SPARC and it fixed the build.
```
$ env  \
ATDM_TRIL_SPARC_BUILDS_LIST=cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt \
ATDM_TRIL_SPARC_USE_OFFICAL_INSTALL=1 \
ATDM_TRIL_SPARC_ATDM_USE_INSTALL_DIR=/projects/atdm_devops/trilinos_installs/2019-03-30 \
ATDM_TRIL_SPARC_SKIP_NATIVE_BUILD=1 \
./sparc-tril-dev-scripts/run_builds_and_tests.sh
```
and it passed with:
```
97% tests passed, 7 tests failed out of 278
```
> Remove unused var (#4789)

- cmake/std/PullRequestLinuxDriver-Test.sh
This is hopefully temporary as we know it will slow down
the PR testing - particulary in the moderate case where
smaller subsets are being built. This is needed due to
the large size of some MueLu objects and libraries when
building all of Trilinos. Later efforts should place a
ulimit on compile processes to keep this kind of
expansion in check.
* Related to #4696
> Change PR testing from 2.1G to 3G per core
