trilinos/Trilinos

packages/muelu/test/meshtying/CMakeLists.txt, packages/muelu/test/meshtying/MortarSurfaceCoupling_DofBased.cpp
While doing something unrelated, I noticed this test had a build failure when complex is enabled. I fixed that, and then made these tests only run with float/double, since they need to read real-valued MatrixMarket files.
=> Fix build of MortarSurfaceCoupling with complex

packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h, packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmTextMeshFixture.h, packages/stk/stk_unit_test_utils/stk_unit_test_utils/TextMeshUtils.hpp
@alanw0 @tasmith4 
Fixes compilation error on Summit.  See #10113.
=> SEACAS: STK: compile fixes under cuda 11.4.2 gcc 10.2

packages/muelu/src/Utils/MueLu_AlgebraicPermutationStrategy_def.hpp
Localize creation of host views in AlgebraicPermutationStrategy.
=> MueLu: Reorder AlgebraicPermutationStrategy memory access

packages/tpetra/core/example/Lesson04-Sparse-Matrix-Fill/index.doc
=> Tpetra: Documentation update

packages/muelu/src/Transfers/PCoarsen/MueLu_IntrepidPCoarsenFactory_def.hpp, packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp
=> MueLu: Localize host view access in more spots

packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_decl.hpp, packages/xpetra/sup/Matrix/Xpetra_Matrix.hpp, packages/xpetra/sup/StridedMap/Xpetra_StridedMap_decl.hpp
=> Xpetra: Deprecated methods instead of deleting them

packages/rol/adapters/tpetra/src/function/ROL_TpetraBoundConstraint.hpp, packages/rol/adapters/tpetra/src/vector/ROL_TpetraMultiVector.hpp, packages/rol/adapters/tpetra/test/vector/test_01.cpp, packages/rol/example/PDE-OPT/0ld/TOOLS/PDE_FEM.hpp, packages/rol/example/PDE-OPT/0ld/adv-diff-react/data.hpp, packages/rol/example/PDE-OPT/0ld/elasticitySIMP_topologyOptimization/filter.hpp, packages/rol/example/PDE-OPT/0ld/poisson/data.hpp, packages/rol/example/PDE-OPT/0ld/stefan-boltzmann/data.hpp, packages/rol/example/PDE-OPT/0ld/stoch-adv-diff/data.hpp, packages/rol/example/PDE-OPT/TOOLS/sysbuilder.hpp, packages/rol/src/utils/ROL_ScalarMinimizationTest01.hpp, packages/rol/test/elementwise/test_02.cpp
@trilinos/rol
Removes Tpetra deprecated code.
Closes #10242
=> ROL: Remove calls to deprecated Tpetra code

cmake/ctest/drivers/lightsaber/CMakeLists.txt
=> Ctest: Fixing typo for lightsaber

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Fix #5572 
Weaver tested. Let's see other testbeds and downstream cases.
=> Tpetra - remove unscoped using Teuchos rcpFromRef

packages/intrepid2/src/Projection/Intrepid2_ProjectionTools.hpp, packages/intrepid2/unit-test/Projection/CMakeLists.txt
Remove UVM from projection tools. This still does not enable de rham test (test itself is not uvm free there).
#10259 is partially resolved. 
@CamelliaDPG I think that this approach is better than #10320 
weaver tested
=> Enabling CUDA test of projection tools.

packages/tpetra/core/test/MultiVector/CMakeLists.txt, packages/tpetra/core/test/MultiVector/Vector_offsetViewCtor.cpp
(#8309). Just a few minor changes were needed to make it build and pass
on Serial and Cuda, with and without MPI.
=> Tpetra: fix Vector_offsetViewCtor test

packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_decl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_decl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_impl.hpp
Runtime failure in drekar test due to view of views issue in one of the integrators.
Fixes the issue
=> Panzer: fix issue with gcc 11 and view of views

cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_debug_nouvm_ascicgpu031_crs.cmake, cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_debug_uvm_deprecated_ascicgpu031_crs.cmake, cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_debug_uvm_nodeprecated_ascicgpu031_crs.cmake, cmake/ctest/drivers/lightsaber/ctest_linux_experimental_mpi_release_float_lightsaber.cmake
=> Ctest/Drivers: Testing updates for ascicgpu031 and lightsaber

cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.crs.cmake, cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.sake.cmake
=> Cmake: Fixing nightlies

packages/tpetra/core/test/MultiVector/CMakeLists.txt
=> Tpetra: Making cmake happy

packages/tpetra/scripts/PerformanceTesting/spock/configureBuild.sh, packages/tpetra/scripts/PerformanceTesting/spock/crontab, packages/tpetra/scripts/PerformanceTesting/spock/launch.sh, packages/tpetra/scripts/PerformanceTesting/spock/load_modules.sh, packages/tpetra/scripts/PerformanceTesting/spock/pushResults.sh, packages/tpetra/scripts/PerformanceTesting/spock/runPerfTests.sh
Track performance on AMD architectures.
N/A
=> Tpetra: add performance testing for ORNL spock

packages/ifpack2/test/belos/CMakeLists.txt, packages/ifpack2/test/belos/belos_solve.cpp, packages/ifpack2/test/belos/build_precond.hpp, packages/ifpack2/test/belos/build_problem.hpp
Adds command-line options ``--with_stacked_timer`` (default: without)
and ``--problem_name="XYZ"`` to set the top-level timer name
(this will also be the top-level Watchr plot title).
Default behavior is unchanged, although I did change some existing
timer names for clarity: "init" -> "Init preconditioner" and
"precond" -> "Compute preconditioner".
I had to refactor things a bit to make StackedTimer include the precond setup, but exclude the I/O (which often dominates the total time). I combined the two functions that were in build_problem.hpp, and then moved the few lines for precond creation into main().
SierraTF would like nightly performance testing of some problems, and this driver is perfect for doing that, it just needed the Watchr support.
=> Ifpack2: add StackedTimer/Watchr to Ifpack2_tif_belos

cmake/std/PullRequestLinuxDriver.sh
PR testing is failing on cloud nodes due to an absolute path to python3. This PR removes the path and relies on the sems-python instead.
Tested by running this change through the testing infrastructure.
=> cmake/std/PullRequestLinuxDriver.sh: Use sems-python

packages/panzer/disc-fe/src/Panzer_IntrepidBasisFactory.hpp, packages/panzer/disc-fe/test/evaluator_tests/dof_basistobasis.cpp
This reverts commit 91e56fc5dca78b5f0bd430d707cc7301943acf4e.
This is breaking some application builds. Need to resolve issues with
topology numbering in DOF Manager for Cn basis.
=> Revert "Panzer: Use HGRAD_*_Cn instead of HGrad_*_C2"

packages/ifpack2/src/Ifpack2_Details_CrsArrays.hpp, packages/ifpack2/src/Ifpack2_Details_FastILU_Base_decl.hpp, packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp, packages/ifpack2/src/Ifpack2_Details_Fic_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Fildl_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Filu_decl.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
@trilinos/shylu, @trilinos/ifpack2 
This PR is an attempt to update ShyLU FastILU to run without deprecated code and UVM (on CUDA GPU)
- https://github.com/trilinos/Trilinos/issues/10087
- https://github.com/trilinos/Trilinos/issues/10080
I tested without deprecated code and without UVM on Weaver, but have not tested performance..
=> ShyLU_node, FastILU : updating FastILU without deprecated code & UVM

packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp, packages/panzer/dof-mgr/src/Panzer_Filtered_GlobalIndexer.cpp, packages/panzer/dof-mgr/src/Panzer_GlobalIndexer_Utilities.cpp, packages/panzer/dof-mgr/src/Panzer_GlobalIndexer_Utilities_impl.hpp, packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp, packages/panzer/mini-em/src/solvers/MiniEM_DiscreteGradient.hpp
Add Node template argument in spots to fix compile errors on ORNL crusher.
Partial fix for #10448.
@trilinos/panzer @cgcgcg 
Fixes compile errors on ORNL Crusher.
=> Panzer: fix HIP compile errors

packages/muelu/adapters/xpetra/MueLu_Maxwell1_def.hpp, packages/muelu/doc/UsersGuide/masterList.xml, packages/muelu/doc/UsersGuide/paramlist_hidden.tex, packages/muelu/src/Interface/MueLu_HierarchyManager.hpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/src/MueCentral/MueLu_MasterList.cpp, packages/muelu/src/Rebalancing/MueLu_RebalanceAcFactory_def.hpp, packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp, packages/muelu/test/maxwell/CMakeLists.txt, packages/muelu/test/maxwell/Maxwell_Reitzinger_repart.xml, packages/xpetra/src/Map/Xpetra_EpetraMapFactory.cpp, packages/xpetra/src/Map/Xpetra_MapFactory_decl.hpp, packages/xpetra/src/Map/Xpetra_MapFactory_def.hpp
Issue: #10407
Tests: New one added
Stakeholder feedback: Via email
=> MueLu: Support for Repartitioning in Maxwell1

packages/framework/pr_tools/PullRequestLinuxDriver.sh
On some ats2 node, /tmp/$USER does not exist which makes nvcc sad. See https://github.com/trilinos/Trilinos/issues/10428#issuecomment-1109956415.
Related to #10428.
This was tested manually by running mkdir on ats2.
=> packages/framework: Always create tmp dir for nvcc

packages/kokkos-kernels/src/sparse/KokkosSparse_spiluk_handle.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_sptrsv_symbolic_impl.hpp
Patch with improvements to kokkos-kernels' spiluk and sptrsv routines for testing by Sierra
@srajama1 @vqd8a @jhux2 @jennloe 
Already tested and merged into kokkos-kernels
=> Kp precond

packages/ifpack2/src/Ifpack2_Details_CrsArrays.hpp, packages/ifpack2/src/Ifpack2_Details_FastILU_Base_decl.hpp, packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp, packages/ifpack2/src/Ifpack2_Details_Fic_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Fic_def.hpp, packages/ifpack2/src/Ifpack2_Details_Fildl_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Fildl_def.hpp, packages/ifpack2/src/Ifpack2_Details_Filu_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Filu_def.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
This PR fixes the build errors with complex scalar typee
=> Ifpack2/ShyLU_node, FastILU : fix build errors with complex scalar type

packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C
The symbol specifying whether a CGNS library build is parallel or not has moved locations from 3.4.0 (or earlier) to 4.X.  Code in Iocgns_DatabaseIO.C was relying on the new location. Fixed so that it will find the definition for all versions.
=> Seacas fix bad cgns symbol detect

packages/tpetra/core/src/Tpetra_BlockView.hpp
The application reports compiler failure due to unguarded unroll pragma. This fixes the issue.
@crdohrm This is the Nathan's patch.
=> Tpetra - unroll guard Nathan's patch

cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake
Since the autotester came back online, we have been having issues with a few Zoltan tests failing in the Intel 17.0.1 PR test build.
With these disabled, we will be able to get a couple PRs through that will update the Intel 19.0.5 PR test build to use the new SEMS spack-cm TPLs. That build will then have Scotch and all test functional. The current Intel 19 build does not, which is why it only is used in the Master Merge test build set.
Once the updated Intel 19 build is in place we plan to retire Intel 17, making this test disable effectively a temporary thing.
Should unblock #10009, #10406, Master Merge
=> Framework: Disable 3 Zoltan tests in the Intel 17.0.1 build

packages/muelu/matlab/bin/CMakeLists.txt, packages/muelu/matlab/bin/matlab, packages/muelu/matlab/bin/muemex.cpp, packages/muelu/matlab/tests/ApplyMueLu/ApplyUnitTest.m, packages/muelu/matlab/tests/ApplyMueLu/CMakeLists.txt, packages/muelu/matlab/tests/Brick/CMakeLists.txt, packages/muelu/matlab/tests/CustomP/CMakeLists.txt, packages/muelu/matlab/tests/JacobiSmooth/CMakeLists.txt, packages/muelu/matlab/tests/PCoarsen/CMakeLists.txt, packages/muelu/matlab/tests/ReentrantDemo/CMakeLists.txt, packages/muelu/matlab/tests/UnsmoothedP/CMakeLists.txt
Brings back the ability to choose the Belos solver in the XML parameter list. The "solver" parameter in the "MueLu" list can be either "CG" or "GMRES". This requires using the muelu/matlab/bin/matlab wrapper to launch MATLAB. "GMRES" is now the default solver.
=> MueLu MueMex: re-enable multiple Belos solvers

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
Compatibility update for kokkos and kokkos-kernels post 3.6.00
See kokkos/kokkos-kernels#1367
Resolve compatibility issues with kokkos and kokkos-kernels post-3.6.00
Local testing with intel/18 build on Blake
=> tpetra: update value_type and const_value_type used in checks

packages/compadre/examples/CMakeLists.tribits.cmake
@trilinos/compadre 
@trilinos/discretizations 
Timeouts on tests are too short for Trilinos testbed.
=> Update to Compadre Test Timeouts

packages/stk/stk_balance/stk_balance/balanceUtils.cpp, packages/stk/stk_integration_tests/cmake_install_test/stk_test_app/src/test_stk_io.cpp, packages/stk/stk_integration_tests/cmake_install_test/stk_test_app/test_stk_app.cpp, packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp, packages/stk/stk_mesh/stk_mesh/base/BulkData.hpp, packages/stk/stk_mesh/stk_mesh/base/MeshBuilder.cpp, packages/stk/stk_mesh/stk_mesh/base/MeshBuilder.hpp, packages/stk/stk_unit_test_utils/stk_unit_test_utils/CMakeLists.txt, packages/stk/stk_unit_tests/stk_mesh/UnitTestMeshBuilder.cpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp
=> STK: Snapshot 05-04-22 17:49

packages/teuchos/core/src/Teuchos_ArrayRCPDecl.hpp, packages/teuchos/core/src/Teuchos_ArrayViewDecl.hpp
=> Teuchos: fix doxygen

packages/sacado/test/GTestSuite/googletest/googlemock/docs/cook_book.md
Trying to fix https://github.com/trilinos/Trilinos/runs/6219271680?check_suite_focus=true.  Stackoverflow indicates a white space might fix it (https://stackoverflow.com/q/58628805).  Reported in #10511.
=> Sacado: try to fix doc rendering error

packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
=> TrilinosCouplings: Minor driver fixes

cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake
Intel 17 tests are failing on 3 that were turned off in develop after the 13.4 branch split off.
This will pull those disables in.
=> Disable 3 tests for Intel 17 - Zoltan

packages/ifpack2/src/Ifpack2_Hiptmair_decl.hpp, packages/ifpack2/src/Ifpack2_Hiptmair_def.hpp, packages/muelu/adapters/xpetra/MueLu_Maxwell1_def.hpp, packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory.cpp, packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt, packages/panzer/mini-em/example/BlockPrec/main.cpp, packages/panzer/mini-em/example/BlockPrec/maxwell-1stOrder.xml, packages/panzer/mini-em/example/BlockPrec/maxwell-pthOrder.xml, packages/panzer/mini-em/example/BlockPrec/maxwell2D.xml, packages/panzer/mini-em/example/BlockPrec/solverCG.xml, packages/panzer/mini-em/example/BlockPrec/solverGMRES.xml, packages/panzer/mini-em/example/BlockPrec/solverMueLuMaxwellHO.xml, packages/panzer/mini-em/example/BlockPrec/solverMueLuMaxwellHOCuda.xml, packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml, packages/panzer/mini-em/src/closures/MiniEM_Conductivity_impl.hpp, packages/panzer/mini-em/src/closures/MiniEM_InversePermeability_impl.hpp, packages/panzer/mini-em/src/closures/MiniEM_TensorConductivity_impl.hpp, packages/panzer/mini-em/src/eqn_sets/MiniEM_OperatorRequestCallback.cpp, packages/panzer/mini-em/src/eqn_sets/MiniEM_OperatorRequestCallback.hpp, packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp, packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp, packages/panzer/mini-em/src/solvers/MiniEM_HigherOrderMaxwellPreconditionerFactory.cpp, packages/panzer/mini-em/src/solvers/MiniEM_HigherOrderMaxwellPreconditionerFactory.hpp, packages/panzer/mini-em/src/solvers/MiniEM_Interpolation.hpp, packages/panzer/mini-em/src/solvers/MiniEM_Utils.cpp, packages/panzer/mini-em/src/solvers/MiniEM_Utils.hpp, packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp
Assemble and solve higher order finite elements in MiniEM.
- Ifpack2: Allow to pass transpose P to Hiptmair, add timers.
- MiniEM: Assemble higher order strong ops and interpolations, pass it to MueLu.
=> MiniEM: Add higher order discretizations

packages/panzer/mini-em/src/closures/MiniEM_Conductivity_impl.hpp, packages/panzer/mini-em/src/closures/MiniEM_InversePermeability_impl.hpp, packages/panzer/mini-em/src/closures/MiniEM_TensorConductivity_impl.hpp
Fix EMPIRE's Trilinos promotion.
=> MiniEM: Fix lambda capture issues in evaluators

.gitmodules, cmake/std/trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py, packages/framework/get_dependencies.sh, packages/framework/pr_tools/PullRequestLinuxDriverTest.py, packages/framework/pr_tools/trilinos_pr.ini, packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py, packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py, packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py, packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py, packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py
Update PR driver paths to point to `packages/framework/GenConfig`.
Tested via Trilinos_PR_testproject.
=> packages/framework/pr_tools: Use GenConfig submodule

packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp, packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
Need to disable some safety checks in certain application classes
New test added to ViewOfViews unit test.
=> Phalanx: more utilities for empire

packages/stratimikos/src/CMakeLists.txt
@trilinos/stratimikos 
Install was missing auto-generated headers added in PR #10507
=> Stratimikos: Glob auto-generated headers

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp, packages/panzer/adapters-stk/test/stk_interface_test/tPamgenMeshFactory.cpp
This is the conversion that was previously pushed on the stk-snapshot branch, I have now closed that other pull-request and opened this one with the same change and also rebased on today's develop branch.
=> Convert Panzer to use MeshBuilder instead of constructing BulkData.

packages/shylu/shylu_node/tacho/src/Tacho.hpp, packages/shylu/shylu_node/tacho/src/Tacho_CrsMatrixBase.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_CholSupernodes_Serial.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_GemmTriangular_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemm_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemv_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemv_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Herk_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Herk_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_LDL_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_LDL_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_LU_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_LU_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Lapack_External.cpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Lapack_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_SupernodeInfo.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveLowerChol.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveLowerLDL.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveLowerLU.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsm_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsm_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsv_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsv_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Util.hpp, packages/shylu/shylu_node/tacho/unit-test/Tacho_TestUtil.cpp
AMD solver component layer is added and runs with MI50 on caraway. 
Compiled and runs on MI50 of caraway.
=> Tacho solver for and

packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
This PR re-organizes symbolic phase of FastILU to reduce the setup time. It also adjust some default parameters.
=> FastILU : reshuffle symbolic

packages/kokkos-kernels/src/Kokkos_ArithTraits.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_HIP.hpp
@trilinos/tpetra @trilinos/kokkos-kernels 
Fixes build errors when using the HIP backend and complex scalars.
* Closes #10612 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of
=> Tpetra/KokkosKernels: Fix #10612 (HIP + complex build)

packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py
See TRILFRAME-356.
Manually via replays: [cdash link](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-__UNKNOWN__-test-rhel7_sems-gnu-7.2.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework-111&field3=buildstamp&compare3=61&value3=20220622-1729-Experimental).
=> packages/framework: Show ctest output in consoles

packages/muelu/cmake/MueLu_config.hpp.in, packages/muelu/test/scaling/MatvecKernelDriver.cpp
Issue: #10660
Tests: This is a test
=> MueLu: Adding more options to matvec driver

packages/stk/stk_balance/stk_balance/balanceUtils.cpp, packages/stk/stk_balance/stk_balance/balanceUtils.hpp, packages/stk/stk_balance/stk_balance/internal/Zoltan2ParallelGraph.cpp, packages/stk/stk_balance/stk_balance/internal/privateDeclarations.cpp, packages/stk/stk_balance/stk_balance/setup/DefaultSettings.hpp, packages/stk/stk_balance/stk_balance/setup/Parser.cpp, packages/stk/stk_balance/stk_balance/setup/Parser.hpp, packages/stk/stk_integration_tests/cmake_install_test/run_cmake_stk_user_facing, packages/stk/stk_io/stk_io/StkMeshIoBroker.cpp, packages/stk/stk_io/stk_io/StkMeshIoBroker.hpp, packages/stk/stk_mesh/stk_mesh/base/EntityProcMapping.hpp, packages/stk/stk_mesh/stk_mesh/base/FieldBase.cpp, packages/stk/stk_mesh/stk_mesh/base/FieldBase.hpp, packages/stk/stk_mesh/stk_mesh/base/FieldParallel.cpp, packages/stk/stk_mesh/stk_mesh/base/NgpReductions.hpp, packages/stk/stk_performance_tests/stk_mesh/CommunicateFieldData.cpp, packages/stk/stk_unit_tests/stk_balance/UnitTestCommandLineParsing.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestEntityProcMapping.cpp, packages/stk/stk_unit_tests/stk_util/parallel/UnitTestParallelComm.cpp, packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp, packages/stk/stk_util/stk_util/parallel/CouplingVersions.hpp, packages/stk/stk_util/stk_util/parallel/DataExchangeUnknownPatternBlocking.hpp, packages/stk/stk_util/stk_util/parallel/DataExchangeUnknownPatternBlockingBuffer.hpp, packages/stk/stk_util/stk_util/parallel/DataExchangeUnknownPatternNonBlocking.cpp, packages/stk/stk_util/stk_util/parallel/DataExchangeUnknownPatternNonBlocking.hpp, packages/stk/stk_util/stk_util/parallel/DataExchangeUnknownPatternNonBlockingBuffer.hpp, packages/stk/stk_util/stk_util/parallel/ParallelComm.hpp, packages/stk/stk_util/stk_util/parallel/ParallelReduce.cpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp
=> STK: Snapshot 06-23-22 06:43

packages/muelu/test/scaling/MatvecKernelDriver.cpp
Issues: #10660
Tests: This is one
=> MueLu: More performance test improvements

packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_def.hpp
I was talking with @pohm01 and realized that there I left some formatting issues in RegionRFactory. I ran a reindent script to clean it up so he hopefully doesn't have to deal with my mess.
N/A
=> MueLu: Fix formatting issues with RegionRFactory

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp, packages/ifpack2/src/Ifpack2_Experimental_RBILUK_decl.hpp, packages/ifpack2/src/Ifpack2_ReorderFilter_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
- Don't use Teuchos::OrdinalTraits::invalid() in device code
- Fix definition of impl_scalar_type in RBILUK. impl_scalar_type != scalar_type. This was causing std::complex to be used in Tpetra::GEMM which is device code.
- Don't use KOKKOS_LAMBDA for a TeamThread loop body
=> Ifpack2/Tpetra: Fix some warnings on Cuda

packages/muelu/test/scaling/MatvecKernelDriver.cpp
Issue: #10712
Test: This is a test
=> MueLu: Adding fence to MatvecKernelDriver

packages/panzer/mini-em/example/BlockPrec/maxwell-large.xml
This should fix failures in the performance runs with MiniEM.
=> Panzer MiniEM: Fix input file for performance tests

packages/stokhos/src/sacado/kokkos/vector/belos/Belos_TpetraAdapter_MP_Vector.hpp, packages/stokhos/test/UnitTest/tpetra_mat_vec.cpp
@etphipp 
This PR adresses #10703 and #10696.
These changes are tested in `stokhos/test/unitTest/tpetra_mat_vec.cpp` and `stokhos/test/unitTest/TpetraCrsMatrixMPVectorUnitTest.cpp`.
=> Stokhos: adresses #10703 and #10696

packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp
=> Panzer MiniEM: Fix memory spaces for discrete curl

packages/ifpack2/CMakeLists.txt, packages/ifpack2/src/Ifpack2_LocalFilter_def.hpp, packages/ifpack2/src/Ifpack2_Relaxation_def.hpp, packages/ifpack2/src/Ifpack2_TriDiContainer_def.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp
Fix the CMake logic for the Ifpack2 debug option, and the option for QD TPL in Ifpack2.
The cache variables that control cmakedefines in config headers
put the package name in all caps (``$PACKAGE_NAME_UC`` in tribits).
Then fix 2 issues when ``Ifpack2_ENABLE_DEBUG=ON``:
- Bug in LocalFilter debug checks - the map isLocallyFitted checks
were backwards. If ``map2.isLocallyFitted(map1)``, map1 is a subset of map2,
not the other way around. For example, ``colMap.isLocallyFitted(domainMap)`` is
typically true but ``domainMap.isLocallyFitted(colMap)`` is not.
Added a comment to this function in Tpetra::Map to make this easier to understand in future.
- Fix a simple build error in a debug snippet of TriDiContainer.
=> Ifpack2: fix build+test with Ifpack2_ENABLE_DEBUG

packages/tpetra/core/example/advanced/Benchmarks/CrsMatrixMatVec.cpp
The current Matvec benchmark test in Tpetra does not allow to read in a matrix from file which is highly annoying when trying to do comparisons with other codes for performance.
No particular stakeholder but that will help us keep track of performance improvement/regression
Adding that feature in and tested it locally.
=> Tpetra: adding matrix market reading option to Matvec test

packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_decl.hpp, packages/xpetra/src/Headers/Xpetra_UseShortNamesScalar.hpp, packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp, packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp
=> Xpetra: Expanding Tpetra::BlockCrs report

packages/ifpack2/test/belos/build_problem.hpp
This PR adds an option to import a row map from a given matrix market file. It is required for testing for Sierra milestone.
=> Ifpack2: importing rowmap option

packages/framework/ini-files/config-specs.ini
Converting Clang 10.0.0 PR build to use C++17 standard
=> Add C++17 standard for Clang 10.0.0 PR build

packages/framework/ini-files/config-specs.ini
Converting GCC 7.2.0 and GCC 7.2.0 serial PR builds to use C++17 standard
=> Add C++17 standard for GCC 7.2.0 and GCC 7.2.0 serial

packages/framework/ini-files/config-specs.ini
Will not enable all packages on all PR in cuda 11 build
=> cuda 11.4.2 don't run all packages in PR

packages/panzer/mini-em/src/closures/MiniEM_Conductivity_impl.hpp
Fixes issue #10773.  Thanks for @cgcgcg for suggesting how to fix this.
Fixes compile failure on ORNL/spock (HIP).
Verified this locally on ORNL/Spock.
=> Panzer: MiniEM: fix HIP compile error

packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp, packages/intrepid2/src/Shared/Intrepid2_CellTopology.hpp
Fix shadow warnings seen in Sierra integration builds
=> Intrepid2: Fix a few shadow warnings.

packages/stokhos/src/sacado/kokkos/vector/belos/Belos_TpetraAdapter_MP_Vector.hpp, packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp
@etphipp
This PR solves #10740.
These changes are tested in `packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp`.
=> Solves #10740

packages/muelu/test/vardofpernode/CMakeLists.txt, packages/muelu/test/vardofpernode/driver_EminDistLapl.xml
This is a capability that I haven't seen explicitly used, but @rstumin and I want to preserve it, so I turned it into a test. This is part of a collection of upcoming emin-related PRs.
Works on my machine Vaporwave 🙂
=> MueLu: Add a test for distance Laplacian with emin

packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
Remove unneeded Kokkos fences, view initializations. To make sure kernels are still run in proper sequence without the fences, specify the execution space on every RangePolicy (instead of using default space). Also replace a sort_crs_matrix with sort_crs_graph, since in symbolic the matrix values haven't been initialized yet.
Still keep the fences after the top-level functions that users can call directly (initialize, compute, apply) so that initTime/computeTime/applyTime remain accurate. Also keep fences before other timing measurements (but these are guarded by ``#ifdef FASTILU_TIMER``).
Performance improvements
This could benefit performance on Sierra milestone problems.
Tested by running from the Ifpack2+Belos driver: RCM + FastILU + Host trsv, and METIS + FastILU + …
=> ShyLU FastILU: simple optimizations

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
When the two RefMaxwell subproblems are too large to be rebalanced onto subcommunicators, this needs to be handled to avoid a crash.
=> MueLu RefMaxwell: Fix donut bug

packages/muelu/doc/UsersGuide/masterList.xml, packages/muelu/doc/UsersGuide/options.tex, packages/muelu/doc/UsersGuide/options_aggregation.tex, packages/muelu/doc/UsersGuide/paramlist.tex, packages/muelu/doc/UsersGuide/paramlist_hidden.tex, packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp, packages/muelu/test/unit_tests_kokkos/UncoupledAggregationFactory_kokkos.cpp
In UncoupledAggregationFactory_kokkos, add two MIS-2 based aggregation schemes. Enable with "aggregation: coloring algorithm" = "mis2 coarsening" or "mis2 aggregation". "coarsening" is more aggressive (fewer, larger aggregates), and works the same as ViennaCL's AMG. "aggregation" is less aggressive and more similar to MueLu's serial agg (it creates secondary aggregates similar to Phase2A/2B).
Both are deterministic, and both require a structurally symmetric local matrix (like all D2 coloring based algorithms, so any user of UncoupledAggregationFactory_kokkos was already dealing with this requirement).
Add unit tests for both algorithms.
Adds a faster and higher quality aggregation scheme for Kokkos refactor. Also deterministic, unlike the existing D2 coloring algorithms …
=> MueLu: integrate MIS-2 based aggregation

packages/muelu/example/basic/mg-gpu.xml, packages/muelu/example/basic/set3-mg-chebyshev.xml, packages/muelu/example/basic/set3-mg-gs.xml, packages/muelu/example/basic/set3-mg-jacobi.xml, packages/muelu/example/basic/set3-mg-sgs-reuse.xml, packages/muelu/example/basic/set3-mg-sgs.xml, packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp, packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- Utilities_kokkos: The double, int, int version was always using the host implementation.
- Update input decks for Stratimikos examples to use deterministic aggregation.
=> MueLu_Utilities_kokkos: GetMatrixDiagonalInverse Kokkos impl for all GO

packages/teuchos/parser/src/Teuchos_Grammar.cpp, packages/teuchos/parser/src/Teuchos_Graph.cpp, packages/teuchos/parser/src/Teuchos_Language.cpp, packages/teuchos/parser/src/Teuchos_Parser.cpp, packages/teuchos/parser/src/Teuchos_Reader.cpp, packages/teuchos/parser/src/Teuchos_Table.hpp, packages/teuchos/parser/src/Teuchos_make_lalr1_parser.cpp, packages/teuchos/parser/src/Teuchos_regex.cpp
@bartlettroscoe @ndellingwood 
#10845
* Closes #10845
@ibaned is concerned TeuchosParser as a whole is technical debt
None
=> Fix TeuchosParser for C++17

packages/sacado/src/Kokkos_LayoutContiguous.hpp, packages/sacado/src/Kokkos_LayoutNatural.hpp, packages/sacado/src/Sacado_DynamicArrayTraits.hpp, packages/teuchos/core/src/Teuchos_GlobalMPISession.cpp
Fixes some use of deprecated capabilities in Kokkos
=> Fix some deprecations

packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml, packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
The change should fix a regression picked up by the performance tests.
=> Panzer MiniEM: Adjust rebalancing targets for RefMaxwell sub-problems

CMakeLists.txt
Add citation message to end of Trilinos CMakeLists.txt file
Closes https://github.com/trilinos/Trilinos/issues/7423
=> Add citation message to CMakeLists.txt

packages/tpetra/core/src/Tpetra_FECrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_FEMultiVector_decl.hpp
closes: #10800
Adding documentation per #10800
=> Fix for 10800

packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
This enables building against Kokkos/develop
* Closes #10826 
@csiefer2: As the stakeholder: @micpowe approves.
N/a
=> Tpetra: Fix a deprecated call to Kokkos::parallel_scan

packages/framework/ini-files/config-specs.ini
Update to C++17 standard for the new CUDA 11 build.
=> Change to C++17 standard for new CUDA 11 build

packages/tpetra/core/CMakeLists.txt, packages/tpetra/core/test/KokkosIntegration/CMakeLists.txt
Issue: #10844
Stakeholder feedback: Waiting
Tests:This is one
=> Tpetra: configure option to disable Kokkos integration test

packages/panzer/disc-fe/src/evaluators/Panzer_DOF_PointValues_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_EdgeBasis_impl.hpp, packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl.hpp, packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl_Def.hpp, packages/phalanx/test/AssemblyHeatFluxFad/evaluators/Evaluator_Density.hpp, packages/phalanx/test/AssemblyHeatFluxFad/evaluators/Evaluator_Density_Def.hpp
Remove deprecated code for 14.0 release
N/A
Tested in AssemblyHeatFluxFad unit test
=> Phalanx: remove deprecated code

cmake/ctest/drivers/lightsaber/ctest_linux_experimental_mpi_release_float_lightsaber.cmake
=> Drivers: Cutting lightsaber float build down until it works

cmake/ctest/drivers/geminga/ctest_linux_nightly_serial_debug_valgrind_muelu_geminga.cmake, packages/ml/src/MLAPI/MLAPI_Aggregation.cpp, packages/ml/src/MLAPI/MLAPI_DistributedMatrix.h, packages/ml/src/MatrixFree/ml_MatrixFreePreconditioner.cpp, packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp, packages/ml/test/LevelWrap/LevelTest.cpp, packages/ml/test/MatrixFree/MatrixFree.cpp, packages/ml/test/MultiLevelPreconditioner_Restart/MultiLevelPreconditioner_Restart.cpp, packages/ml/test/MultiLevelPreconditioner_Sys/MultiLevelPreconditioner_Sys.cpp, packages/ml/test/ValidateParams/cxx_main.cpp
Issue: #10945
Tests: Yes, lots
=> Drivers/ML: Fixing memory leaks and other valgrind errors

packages/muelu/test/unit_tests/InverseApproximationFactory.cpp
Issue: #10946
Tests: This is one
=> MueLu: Fixing complex issue

packages/ifpack2/src/Ifpack2_Relaxation_def.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
- In FastILU, update headers and namespaces for KokkosKernels utility functions (sort, transpose)
- In Ifpack2, get rid of custom volatile join() function in parallel_reduce functor. This doesn't need a join() at all since it's a simple sum-reduce.
Verified that Ifpack2 tests built and passed with FastILU enabled
=> 3.7 promotion fixes - ifpack2/fastilu

packages/teuchos/core/src/Teuchos_StrUtils.hpp, packages/teuchos/parameterlist/src/Teuchos_StandardParameterEntryValidators.cpp, packages/teuchos/parameterlist/test/ParameterList/cxx_main.cpp, packages/tpetra/core/inout/Tpetra_DistributionLowerTriangularBlock.hpp
@trilinos/teuchos @trilinos/tpetra 
- Teuchos: Add missing function definitions for `setLongLongParameter`, `getLongLongParameter`.
- Teuchos: Remove declaration of `envSubstitute` that is missing a definition.
- Tpetra: Add a missing include.
=> Teuchos fix

packages/amesos2/src/Amesos2_Superlu_def.hpp, packages/amesos2/src/Amesos2_Tacho_decl.hpp, packages/amesos2/src/Amesos2_Tacho_def.hpp
This PR updates the Amesos2's Tacho interface
-  release memory with destructor, 
- use DummySchedular, and 
- add more timers
Being tested on Summit with FROSch/Albany
=> Amesos2 : update Tacho interface

cmake/ctest/drivers/geminga/ctest_linux_nightly_serial_debug_valgrind_muelu_geminga.cmake
Issue: #10945 
Tests: n/a
Thanks to Ross for the 'how to fix it' instructions
=> Drivers: Fixing Geminga valgrind tests

packages/framework/ini-files/config-specs.ini
Run KokkosKernels batched gemm unit test in serial
@trilinos/kokkos @trilinos/framework 
Reduce test time of KokkosKernels unit tests.
Via the AutoTester.
=> packages/framework/ini-files:

packages/epetra/test/CrsMatrix/cxx_main.cpp, packages/epetra/test/CrsMatrix_LL/cxx_main.cpp, packages/epetra/test/RowMatrixTransposer/cxx_main.cpp, packages/epetra/test/SerialDense/cxx_main.cpp, packages/epetra/test/SerialDense_LL/cxx_main.cpp, packages/epetra/test/Vector/cxx_main.cpp, packages/epetraext/test/Permutation/cxx_main.cpp, packages/epetraext/test/Permutation_LL/cxx_main.cpp, packages/ifpack/test/AztecOO/aztecoo_solve.cpp, packages/ifpack/test/AztecOO/read_matrix.cpp
=> Epetra/EpetraExt/Ifpack: Valgrind cleanup

packages/panzer/adapters-stk/example/main_driver/CMakeLists.txt
Tribits raises a warning about an unparsed argument in a Panzer test definition.
=> Panzer: Fix test invocation

packages/amesos2/src/Amesos2_SolverCore_def.hpp
@trilinos/<Amesos2>
This PR fixes a compilation issue for Amesos2 on HIP with complex type.
This PR is related to:
* #10963
=> amesos2(fix): compilation error on hip with complex

packages/muelu/research/caglusa/Tpetra_BlockedMap_decl.hpp, packages/muelu/research/caglusa/Tpetra_BlockedMap_def.hpp, packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_kokkos_decl.hpp, packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
=> Xpetra&MueLu: Fix warnings about Kokkos include

packages/tpetra/core/src/Tpetra_Details_DeepCopyCounter.cpp, packages/tpetra/core/src/Tpetra_Details_DeepCopyCounter.hpp, packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
=> Tpetra: Adding Kokkos::deep_copy() counter via KokkosP interface

packages/muelu/test/maxwell/CMakeLists.txt, packages/muelu/test/unit_tests/Hierarchy.cpp, packages/muelu/test/unit_tests/ParameterList/ParameterListInterpreter.cpp, packages/muelu/test/unit_tests/RAPShiftFactory.cpp, packages/muelu/test/vardofpernode/CMakeLists.txt
Addresses github issue #10941.
Cleaning up nightly dashboard.
Part of #10949.
N/A
Reproduced failures in local build, confirmed that this PR fixes them.
=> MueLu: add test guards if no direct solver

packages/muelu/src/Interface/MueLu_MLParameterListInterpreter_def.hpp, packages/muelu/test/maxwell/Maxwell3D.cpp, packages/muelu/test/maxwell/ReitzingerPFactory.cpp, packages/muelu/test/scaling/Driver.cpp, packages/muelu/test/scaling/ImportPerformance.cpp, packages/muelu/test/scaling/TAFCPerformance.cpp, packages/muelu/test/vardofpernode/VarDofDriver.cpp
=> MueLu: Silence warnings

packages/framework/ini-files/config-specs.ini
Issue: #10883
Tests: This
I opted for the "Turn Everything Back On and See What Doesn't Work" approach.
=> Framework: Enabling Ifpack2/MueLu PR tests w/ UVM off

packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPipeline.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/FROSch_TpetraPreconditioner_decl.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/FROSch_TpetraPreconditioner_def.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/Thyra_FROSchFactory_def.hpp, packages/shylu/shylu_dd/frosch/src/CMakeLists.txt, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/CMakeLists.txt, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/ParameterLists/CMakeLists.txt, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/ParameterLists/ParameterList_RGDSWPreconditioner_Klu_Tpetra.xml, packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_decl.hpp, packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp, packages/stratimikos/adapters/belos/src/Thyra_BelosTpetrasSolverAdapter.hpp, packages/stratimikos/cmake/Dependencies.cmake, packages/stratimikos/test/CMakeLists.txt, packages/stratimikos/test/stratimikos_jacobi_tpetra.xml
@trilinos/stratimikos @trilinos/shylu
This PR aims to
- add Belos Tpetra GMRES solvers to Stramikos Belos adapter
- update FROSch Stramikos interface to call Belos Tpetra solvers
This is a cleaned-up redo of [11023](https://github.com/trilinos/Trilinos/pull/11023).
=> Stramikos & FROSch : add Belos Tpetra solvers

packages/muelu/src/Transfers/Matrix-Free/MueLu_MatrixFreeTentativePFactory_kokkos_def.hpp, packages/muelu/src/Transfers/Matrix-Free/MueLu_MatrixFreeTentativeP_kokkos_def.hpp
Fix issues on complex<double>.
=> MueLu MF Prolongator: Fix complex issues

packages/muelu/src/Misc/MueLu_FilteredAFactory_def.hpp
Fixes failing test MueLu_DriverDiagonalModifications_MPI_1 in no-UVM build, reported in https://github.com/trilinos/Trilinos/issues/10883.
Fix suggested by Sean Miller @ AMD.
Fixes test that fails in no-UVM build.
N/A
I was able to reproduce the error locally and confirmed this PR fixes the error.
=> MueLu: fix failing test with no UVM

packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp, packages/teko/tests/unit_tests/tDiagnosticLinearOp.cpp
- Teko: Bump up a relative tolerance that was pretty strict.
- Ifpack2: Fix concurrent access on host and device in BlockRelaxation
=> Teko&Ifpack2: Fix test for no-UVM builds

packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Compatibility update when kokkos' deprecated code is disabled
- Replace pointer-type with Kokkos::View for array reductions
- Delete unneeded (duplicate) join overloads with volatile quantifiers
Compatibility update for disabled deprecated code in kokkos kokkos/kokkos#4756
Compatibility update when kokkos' deprecated code is disabled
Local testing to confirm successful compilation in host (serial) build with intel/19 with kokkos' develop branch and deprecated code disabled; will rely on AT for feedback of testing with Trilinos' develop branch
=> zoltan2: compatibility update for array reductions

packages/shylu/shylu_node/tacho/src/impl/Tacho_SupernodeInfo.hpp
Compatibility update for disable of kokkos deprecated code
@trilinos/tacho @trilinos/shylu 
Successfully compile with Kokkos' deprecated code disable
NA
Locally testing confirmed successful compilation with Kokkos' deprecated code disabled; AT for more testing
=> tacho: remove volatile qualifiers from join method

packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
OverlappingRowMatrix needs to keep track of unique GIDs to add to the column map of the next overlap level. It was doing this with linear search in an unsorted array, for O(N^2) time. Instead, use unordered_set to keep track of unique GIDs to reduce this part to O(N).
Major speedup in AdditiveSchwarz preconditioner initialize, when overlap level > 0.
Reduces OverlappingRowMatrix construction time in SierraTF abnormal energy surrogate problem from 159 s to 6.8 s. Overall AdditiveSchwarz init time speedup by 2.04x.
Tested by Ifpack2 unit tests and Ifpack2_AdditiveSchwarz test.
=> Ifpack2: fix performance bug in OverlappingRowMatrix

packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
Apply [KokkosKernels PR #1553](https://github.com/kokkos/kokkos-kernels/pull/1553) to fix issue #11041.
See the KokkosKernels PR and the Trilinos issue for details.
Changes are identical to the KokkosKernels PR so this shouldn't cause any promotion merge issues later.
=> KokkosKernels: Fix #11041 (patch KK #1553)

packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangents_impl.hpp
Needs scratch space equal to team size.
=> Panzer: fix scratch space allocation in GatherTangents

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp, packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
Issue:#10748
Tests:Aready done
Stakeholder feedback:n/a
=> Xpetra: Replacing Placeholder code with actual BlockCrs SpGEMM

packages/muelu/src/Utils/MueLu_Utilities_decl.hpp, packages/muelu/src/Utils/MueLu_Utilities_def.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_RowMatrixTransposer_decl.hpp, packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp, packages/tpetra/core/src/Tpetra_RowMatrixTransposer_fwd.hpp, packages/tpetra/core/test/Block/BlockCrsMatrix.cpp, packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
Issue: #10748
Tests: Added to Tpetra
=> Tpetra/MueLu: Adding BlockCrsTransposer and removing placeholder code

packages/stk/stk_ngp_test/stk_ngp_test/ngp_test.cpp
Compatibility update for disable of kokkos deprecated code Necessary for kokkos@4.0 release, see kokkos/kokkos#5134
@trilinos/stk 
Compatibility update for disable of kokkos deprecated code Necessary for kokkos@4.0 release, see kokkos/kokkos#5134
Since stk is snapshot to Trilinos this PR can be closed if changes can be included in the next snapshot (I'm unfamiliar with the process for PRs or similar to the code base)
=> stk: remove use of Kokkos::finalize_all

packages/tpetra/core/test/MatrixMatrix/FECrs_MatrixMatrix_UnitTests.cpp
=> Tpetra: Removing floating point hard-equality check in test

packages/belos/tpetra/src/BelosMultiVecTraits_Tpetra.hpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraMultiVector_def.hpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraVector_def.hpp
@trilinos/belos @trilinos/thyra @trilinos/tpetra 
Revert PR #10991 to give us time to track down the issue.
https://github.com/trilinos/Trilinos/pull/10991#issuecomment-1270089527
=> Revert PR 10991

packages/amesos2/test/adapters/Epetra_RowMatrix_Adapter_UnitTests.cpp
Fixes failures like this:
https://testing.sandia.gov/cdash/test/146234472
=> Amesos2: Fix failing Epetra test

packages/stk/stk_io/stk_io/IossBridge.cpp, packages/stk/stk_io/stk_io/ProcessSetsOrBlocks.cpp, packages/stk/stk_io/stk_io/SidesetTranslator.hpp, packages/stk/stk_math/stk_math/StkPlane.hpp, packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp, packages/stk/stk_mesh/stk_mesh/base/MetaData.hpp, packages/stk/stk_mesh/stk_mesh/base/SideSetEntry.cpp, packages/stk/stk_mesh/stk_mesh/base/SideSetEntry.hpp, packages/stk/stk_mesh/stk_mesh/base/SideSetHelper.cpp, packages/stk/stk_mesh/stk_mesh/base/SideSetHelper.hpp, packages/stk/stk_mesh/stk_mesh/base/SideSetUtil.cpp, packages/stk/stk_mesh/stk_mesh/base/SidesetUpdater.cpp, packages/stk/stk_mesh/stk_mesh/base/SidesetUpdater.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshModification.cpp, packages/stk/stk_performance_tests/stk_mesh/timer.hpp, packages/stk/stk_simd/stk_simd_view/simd_view.hpp, packages/stk/stk_unit_test_utils/stk_unit_test_utils/algorithmTimer.hpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestBulkData.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestChangeParts.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestGhostingWithModification.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestSideSet.cpp, packages/stk/stk_unit_tests/stk_util/algorithmTimerTest.cpp, packages/stk/stk_unit_tests/stk_util/parallel/UnitTestParallelVectorConcat.cpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp
=> STK: Snapshot 10-14-22 07:12

cmake/ctest/drivers/lightsaber/cron_driver.sh
Update to lightsaber driver since something decided to hate csh
=> Ctest/Drivers: Update to lightsaber

packages/rol/adapters/tpetra/src/vector/ROL_TpetraMultiVector.hpp
Compatibility update following kokkos@3.7
See kokkos/kokkos#4077 kokkos/kokkos#5194
@trilinos/rol 
Compatibility update needed to compile with Kokkos' deprecated code disabled
=> rol: remove volatile from join in ROL_TpetraMultiVector.hpp

packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_decl.hpp, packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp, packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp, packages/ifpack2/src/Ifpack2_Parameters.cpp, packages/muelu/src/Utils/MueLu_TimeMonitor.cpp, packages/tpetra/core/src/Tpetra_Details_Profiling.cpp, packages/tpetra/core/src/Tpetra_Details_Profiling.hpp
These changes address three things:
- MueLu: Adding parameter for aggregation in AMG to reuse coloring results from a previous iteration.
- Ifpack2: Adding parameter to use native SpMV/blas kernels instead of fused SpMV kernel for applying Chebyshev smoother (noticeable performance difference on GPUs with vendor libraries).
- Tpetra: Adding fix for Kokkos profiling regions, which can otherwise cause incorrect results with tracing tools.
=> MueLu: Adding parameters to control performance and tracing of AMG

packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
Problem manifested under HIP in RefMaxwell.  Thanks to @cgcgcg for suggesting fix.
Fixes #11164.
@trilinos/muelu @trilinos/panzer 
Fixes a performance test under HIP.
N/A
Reproduced error locally, verified that patch resolved.
=> MueLu: fix simultaneous host/device access

packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/FROSch_TpetraPreconditioner_decl.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/FROSch_TpetraPreconditioner_def.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/Thyra_FROSchFactory_decl.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/Thyra_FROSchFactory_def.hpp, packages/shylu/shylu_dd/frosch/src/Adapters/Thyra_FROSchLinearOp_def.hpp, packages/shylu/shylu_dd/frosch/src/InterfaceSets/FROSch_DDInterface_def.hpp, packages/shylu/shylu_dd/frosch/src/InterfaceSets/FROSch_EntitySet_def.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_IPOUHarmonicCoarseOperator_def.hpp, packages/shylu/shylu_dd/frosch/src/Tools/FROSch_ExtractSubmatrices_def.hpp, packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp, packages/shylu/shylu_dd/frosch/test/LocalPartitionOfUnityBasis/main.cpp, packages/shylu/shylu_dd/frosch/test/Overlap/main.cpp, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/CMakeLists.txt, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/ParameterLists/CMakeLists.txt, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/ParameterLists/ParameterList_RGDSWPreconditioner_Klu_Half.xml, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/main.cpp, packages/stratimikos/adapters/belos/src/Thyra_BelosTpetrasSolverAdapter.hpp
This PR adds an option to use `HalfPrecisionOperator`
- The option is implemented just for `RGDSW` and `TwoLevel` Preconditioner
- FROSch is also updated to remove some compiler warnings
=> FROSch : add option to use HalfPrecisionOperator

cmake/ctest/drivers/lightsaber/cron_driver.sh
=> Ctest: lightsaber update

packages/stokhos/src/sacado/kokkos/Kokkos_View_Utils.hpp, packages/stokhos/src/sacado/kokkos/pce/Sacado_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp
Changes suggested by @maartenarnst for compiling Stokhos on HIP.
=> Stokhos:  Fixes for compiling on HIP

packages/ifpack2/src/Ifpack2_Details_CrsArrays.hpp, packages/ifpack2/src/Ifpack2_Details_FastILU_Base_decl.hpp, packages/shylu/shylu_dd/frosch/src/InterfaceSets/FROSch_DDInterface_def.hpp, packages/shylu/shylu_dd/frosch/src/InterfaceSets/FROSch_InterfaceEntity_def.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_AlgebraicOverlappingOperator_decl.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_AlgebraicOverlappingOperator_def.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_GDSWCoarseOperator_decl.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_IPOUHarmonicCoarseOperator_decl.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_RGDSWCoarseOperator_def.hpp, packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_FROSchPreconditioner_def.hpp, packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_Ifpack2PreconditionerTpetra_decl.hpp, packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_Ifpack2PreconditionerTpetra_def.hpp, packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_ThyraPreconditioner_def.hpp, packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_ThyraSolver_def.hpp, packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_decl.hpp
This PR adds an option to call Zoltan2 before local ILU
=> Frosch : add an option to call Zoltan2 before local ILU

.github/ISSUE_TEMPLATE/bug_report.md
Updating bug_report.md template, switch from @trilinos/<PackageName> to @trilinos/package_name 
requested on [TRILINOSHD-223](https://sems-atlassian-son.sandia.gov/jira/projects/TRILINOSHD/queues/custom/122/TRILINOSHD-223)
=> updating bug_report.md template instructions

packages/muelu/utils/misc/pullBuilds.py
Adds a script that allows to pull information for failing tests off of CDash.
=> MueLu: Add AT PR script

cmake/ctest/drivers/lightsaber/cron_driver.sh
=> Ctest: Lightsaber updates

packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp, packages/ifpack2/src/Ifpack2_Details_UserPartitioner_def.hpp, packages/muelu/test/scaling/CMakeLists.txt
=> Ifpack2: fix bug when import/export not needed to combine overlap when performing block relaxation in serial

cmake/ctest/drivers/lightsaber/ctest_linux_experimental_mpi_release_float_lightsaber.cmake
=> Lightsaber: Enable Float+Double to allow for multiprecision

cmake/ctest/drivers/lightsaber/ctest_linux_experimental_mpi_release_float_lightsaber.cmake
=> Lightsaber: Modify package enables for multiprecision

packages/ifpack2/example/BlockTriDi.cpp
Issue: #11195
Tests: Improving one
=> Ifpack2: Upgrading BlockTriDi example

cmake/ctest/drivers/lightsaber/ctest_linux_experimental_mpi_release_float_lightsaber.cmake
=> Lightsaber: Enable Stratimikos examples & tests

packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_LDL_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Factory.hpp
This PR tries fixing the segfaults encountered calling LDLt with multiple CUDA streams.
There seems to be an bug computing the workspace size..
=> Tacho : fix segfalut with LDLt using multiple CUDA streams

packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HCURL_TET.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HDIV_TET.hpp, packages/intrepid2/unit-test/Discretization/Basis/HGRAD_HEX_C1_FEM/test_02.hpp, packages/intrepid2/unit-test/Discretization/Basis/HGRAD_LINE_C1_FEM/test_01.hpp, packages/intrepid2/unit-test/Discretization/Basis/HGRAD_QUAD_C1_FEM/test_01.hpp, packages/intrepid2/unit-test/Discretization/Basis/HGRAD_QUAD_C2_FEM/test_01.hpp
@CamelliaDPG @mperego 
Fix shadow warnings in builds of Sierra.
=> Intrepid2: fix shadow variables

README.md
Add a commit from master into develop that is now blocking master merge.
None required. The conflicting commit is in the README.md file.
=> Update develop for master merge

Version.cmake
Incrementing version number for release.
xSDK needs an updated release for their 0.8 release.
xSDK is requesting an updated release now that all necessary patches have been merged to the 13.4 branch.
The patches to this branch were tested by the xSDK.
=> Update Version.cmake for 13.4.1 patch release

packages/aztecoo/src/az_precond.c
@trilinos/aztecoo
Fixes misleading indentation pointed out in #11237.
Whitespace change only.
=> AztecOO: fix misleading indentation

packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp
Can't getHostView from indices_wdv nor values_wdc while the device view used to create them lives on.
`TPETRA_VERBOSE=1` on GPU execution is not covered by automatic tests.
=> tpetra: drop device views before requesting host in `TPETRA_VERBOSE=1`

packages/tpetra/core/src/Tpetra_Details_temporaryViewUtils.hpp
match the number of args to layout ctor (2) corresponding to dynamic rank of (to be created) the View change needed to resolve runtime errors post kokkos@3.7.00 cross-reference #11264
See #11264 
Confirmed tests passed in local build, AT will do the rest
=> tpetra: toLayout routine compatibility update

packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotTensorTimesVector_impl.hpp
move kernel label to first argument of Kokkos::parallel_for
Minor change to allow Panzer to compile with Kokkos' develop branch and eventual 4.0 release
Confirmed this change resolved compilation error in local build, AT will handle the rest
=> panzer: update to remove use of deprecated code

packages/trilinoscouplings/examples/scaling/CMakeLists.txt, packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp, packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp, packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp, packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn.cpp, packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
Certain examples in TrilinosCouplings require MueLu but weren't properly guarded. Added missing Teuchos comm and set.h includes.
Fixed a few warnings.
Addresses failures reported in #11239 and https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-491.
@rppawlo 
@srbdev 
Fixes compiler failures in proposed PR Testing for CUDA 11.4.2.
I was able to reproduce the dashboard errors on ascicgpu030, and verified that this PR fixes the issues.
=> TrilinosCouplings: check if MueLu enabled

packages/stokhos/src/CMakeLists.txt
=> Add missing Stokhos_StorageHelpers.hpp to sources list

packages/stk/stk_integration_tests/stk_io/IntegrationTestStkIo.cpp, packages/stk/stk_io/stk_io/IossBridge.cpp, packages/stk/stk_mesh/stk_mesh/base/MetaData.cpp, packages/stk/stk_mesh/stk_mesh/base/MetaData.hpp, packages/stk/stk_tools/stk_tools/mesh_clone/MeshClone.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestPartAlias.cpp, packages/stk/stk_unit_tests/stk_tools/mesh_clone/UnitTestMeshClone.cpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp
=> STK: Snapshot 11-28-22 08:16

packages/tempus/doc/index.doc, packages/tempus/examples/00_Basic_Problem/00_Basic_Problem.cpp, packages/tempus/examples/01_Utilize_Thyra/01_Utilize_Thyra.cpp, packages/tempus/examples/02_Use_ModelEvaluator/02_Use_ModelEvaluator.cpp, packages/tempus/examples/02_Use_ModelEvaluator/CMakeLists.txt, packages/tempus/examples/02_Use_ModelEvaluator/VanDerPol_ModelEvaluator_02.cpp, packages/tempus/examples/02_Use_ModelEvaluator/VanDerPol_ModelEvaluator_02.hpp, packages/tempus/examples/CMakeLists.txt, packages/tempus/src/Tempus_IntegratorAdjointSensitivity_decl.hpp, packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp, packages/tempus/src/Tempus_TimeEventComposite.hpp
Add new example to show how to use ModelEvaluator for Tempus explicit and implicit ODEs.
Provide more documentation.
* Closes #11294 
Passes all test on MacOS
=> Tempus: Example Problem to Use ModelEvaluator

packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_FaceBasis_impl.hpp
Remove some uvm from face basis dirichlet residual
=> Panzer: remove uvm from face basis dirichlet residual

packages/amesos2/src/Amesos2_Superlumt_def.hpp, packages/sacado/test/performance/advection/advection_hierarchical_dfad.cpp, packages/sacado/test/performance/advection_const_basis/advection_hierarchical_dfad.cpp, packages/sacado/test/performance/fenl_assembly/TestAssembly.cpp, packages/sacado/test/performance/mat_vec/fad_kokkos_mat_vec_perf.cpp, packages/sacado/test/performance/mat_vec/mat_vec.cpp, packages/sacado/test/performance/mat_vec/mat_vec_hierarchical_dfad.cpp
Update concurrency call to non-static usage
Address issue #11331 for compatibility with kokkos/kokkos#5655
AT will handle the testing
=> Amesos2,Sacado: Update calls to concurrency calls to non-static member functions

packages/framework/ini-files/config-specs.ini
https://github.com/trilinos/Trilinos/issues/7441
Tested locally up to configure:
```
(rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp) $ grep -i kokkos_enable_serial CMakeCache.txt 
Kokkos_ENABLE_SERIAL:BOOL=OFF
```
=> packages/framework: Disable kokkos serial in gcc 8.3.0 build

packages/ifpack2/example/BlockTriDi.cpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp
This now correctly works with my single-processor version of the dump from the app.
Issue: #11195 
Tests: This is one.
=> Ifpack2: More changes for BlockTriDi example

packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp
=> Panzer MiniEM: Do not use Kokkos View for host only data

packages/ifpack2/example/BlockTriDi.cpp
=> Ifpack2: Improvements to BlockTriDi example

packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_SupernodeInfo.hpp
This PR aims to fix workspace size for symLU.
@shardest
It is now using the maximum number of rows and columns, which could overestimates the workspace size..
=> Tacho : workspace size for symLU

packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
=> Tpetra: Fixing performance regression

CMakeLists.txt, launch-c.in, launch-cxx.in
Trilinos is a massive codebase often building for hours at a time.  However, changes are often incremental and fairly redundant.  Adding [ccache](https://ccache.dev/) would drastically reduce the amount of time required per-build. This PR adds some minimal supporting changes and somehow fell off our internal boards unmerged.
=> ccache preliminary support

packages/percept/src/percept/mesh/mod/smoother/GenericAlgorithm_total_element_metric.hpp
Percept fails to compile on EAS3.
N/A
=> Percept: fix for compiling on HIP

packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/supported-envs.ini
Evaluate ASCDO MVP.
Locally. Details provided upon request.
Related to #11352.
=> packages/framework: Add ascdo gnu 12.1.0 builds

packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp, packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp, packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp, packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp, packages/ifpack2/src/Ifpack2_ILUT_def.hpp, packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestChebyshev2.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessRILUK.cpp
=> Ifpack2: Silence shadow warnings

packages/belos/kokkos/example/BlockCGKokkosExFile.cpp, packages/belos/kokkos/example/BlockGmresKokkosExFile.cpp, packages/belos/src/BelosMinresSolMgr.hpp, packages/belos/tpetra/src/BelosTpetraTestFramework.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_Cg.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_CgPipeline.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_CgSingleReduce.hpp, packages/nox/src-loca/src-lapack/LOCA_BorderedSolver_LAPACKDirectSolve.C, packages/nox/src-loca/src/LOCA_DerivUtils.C, packages/nox/src-loca/src/LOCA_MultiContinuation_ArcLengthGroup.C, packages/nox/src-loca/src/LOCA_MultiContinuation_NaturalGroup.C, packages/nox/src-loca/src/LOCA_TurningPoint_MinimallyAugmented_Constraint.C, packages/nox/src/NOX_Multiphysics_Solver_FixedPointBased.C, packages/stratimikos/adapters/belos/test/LOWSFactory/Thyra_Belos_StatusTest_UnitTests.cpp, packages/stratimikos/doc/parameterList/createValidParameterList.cpp, packages/stratimikos/test/galeri_xpetra_driver.cpp
@trilinos/belos @trilinos/nox @trilinos/stratimikos 
For NOX, I ran out of steam. There are still a lot of shadow warnings in the tests and examples, but the library should build quietly now.
=> Belos,Nox,Stratimikos: Silence warnings

packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
Removed some shadow warnings.
Become free of shadow warnings.  This is a request from Sierra.
* Related to #11412 
Passed local testing.
=> Tempus: Enable Shadow Warnings

packages/ifpack2/src/Ifpack2_ReorderFilter_def.hpp
Finish up one more shadow warning
#11418
=> Ifpack2: remove last ifpack2 shadow warnings

packages/kokkos-kernels/CHANGELOG.md, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
Fixup to resolve performance regression previously resolved by #11074 not included with #11347 
AT will handle
=> KokkosKernels: Performance fixup from #11074

packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory.cpp, packages/panzer/disc-fe/src/Panzer_SubcellConnectivity.hpp
Fix issues #11408 and TRILINOSHD-236
=> Panzer fix bugs

packages/teko/src/NS/Teko_ALOperator.cpp, packages/teko/src/NS/Teko_PCDStrategy.cpp, packages/teko/src/Teko_BlockLowerTriInverseOp.cpp, packages/teko/src/Teko_BlockUpperTriInverseOp.cpp, packages/teko/src/Teko_BlockedReordering.cpp, packages/teko/src/Teko_GaussSeidelPreconditionerFactory.cpp, packages/teko/src/Teko_JacobiPreconditionerFactory.cpp, packages/teko/src/Teko_LU2x2DiagonalStrategy.cpp, packages/teko/src/Teko_LU2x2InverseOp.cpp, packages/teko/src/Teko_ReorderedLinearOp.cpp, packages/teko/src/Tpetra/Teko_TpetraHelpers.cpp, packages/teko/tests/Test_Utils.cpp, packages/teko/tests/Test_Utils.hpp, packages/teko/tests/src/Tpetra/tBlockedTpetraOperator.cpp, packages/teko/tests/src/Tpetra/tStridedTpetraOperator.cpp, packages/teko/tests/src/Tpetra/tTpetraOperatorWrapper.cpp, packages/teko/tests/unit_tests/tIterativePreconditionerFactory.cpp, packages/teko/tests/unit_tests/tRequestInterface.cpp, packages/tpetra/core/inout/Tpetra_Details_CooMatrix.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
=> Tpetra+Teko: Silence shadow warnings

packages/panzer/mini-em/example/BlockPrec/maxwell.xml
=> MiniEM: Remove leftover augmentation solver operator

packages/shylu/shylu_node/basker/src/shylubasker_order_scotch.hpp, packages/shylu/shylu_node/basker/src/shylubasker_types.hpp
Address issue #11446
Address issue #11446
=> shylubasker: rename KOKKOS_NOINIT macro

packages/PyTrilinos/src/Tpetra.i, packages/adelus/src/BlasWrapper_copy.hpp, packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Interlaced.hpp, packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp, packages/teuchos/kokkoscompat/src/KokkosCompat_View_def.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp, packages/xpetra/src/Vector/Xpetra_Vector.hpp
It is not legal to reach into the `Kokkos::Impl::` namespace
See https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Compatibility.html
Did not actually test
=> Hands off `Kokkos::Impl::if_c`

packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/tpetra/Stokhos_Tpetra_MP_Vector.hpp, packages/tpetra/core/compat/CMakeLists.txt, packages/tpetra/core/compat/Kokkos_BufferMacros.hpp, packages/tpetra/core/compat/Kokkos_LinAlgVersion.hpp, packages/tpetra/core/compat/Kokkos_MultiVectorKernelOps.hpp, packages/tpetra/core/compat/Kokkos_NodeAPIConfigDefs.hpp, packages/tpetra/core/compat/Kokkos_Version.hpp
Issue: #11459
Tests: Yes
There's still more to do (for a later PR), but I figured I'd at least get ye olde AT running on this to see what happens.
=> Tpetra: Beginning deprecation of files that start with Kokkos_

packages/muelu/src/Headers/LO-GO-NO.tmpl, packages/muelu/src/Headers/MueLu_UseShortNamesOrdinal.hpp, packages/muelu/src/Headers/MueLu_UseShortNamesScalar.hpp, packages/muelu/src/Headers/Non-Templated.tmpl, packages/muelu/src/Headers/SC-LO-GO-NO.tmpl, packages/xpetra/src/Headers/Xpetra_UseShortNamesOrdinal.hpp, packages/xpetra/src/Headers/Xpetra_UseShortNamesScalar.hpp
@trilinos/xpetra @trilinos/muelu 
Silence warnings about unused short names. Requires C++17, so cannot merge yet.
=> Xpetra&MueLu: Stop warnings about unused short names

packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer.hpp
Previously the Zoltan2 coloring interface required allocating multivectors with numbers of columns equal to the number of colors so that reconstructMatrix() could reconstruct the whole matrix.  However, when the number of colors is large, the seed and compression multivectors can consume large amounts of memory (easily greater than the matrix itself).  This change allows computing the seed matrix and processing of colors in chunks of a user-chosen size, allowing the multivectors to only need a number of columns equal to the chunk size. This was a fairly simple change and is backwards compatible with processing all colors at once.  It does require the user to write a loop around the process of computing the seed matrix, computing the compression matrix (user-defined), and reconstructing …
=> Zoltan2:  Allow coloring interface to process only chunks of colors at a time

cmake/ctest/drivers/rocketman/cron_driver.sh
Hopefully fixes rocketman avatar build.
=> Rocketman: Pull in changes to base repo

cmake/ctest/drivers/geminga/valgrind_suppressions.txt
Memory leak warnings in system libraries could make it more difficult to identify leaks in Trilinos itself.
N/A
Will evaluate when the next nightly Valgrind testing runs.
=> Testing: geminga: suppress valgrind warnings about leaks in system perl library

packages/framework/ini-files/config-specs.ini
fix new gcc-8.3.0 sems-v2 builds for PR testing
=> Fix for 2 gcc-8.3.0 new PR builds

packages/adelus/example/adelus_driver.cpp
Prefer `std::chrono` to get a random seed.
adelus @srajama1
=> Adelus: Do not use `Kokkos::Impl::clock_tic`

packages/muelu/test/scaling/MatrixLoad.hpp
Enable MueLu's Driver to read a matrix from file and parallelize using a uniform distributed map.  This is useful when there's no row map file.
N/A
=> MueLu: read matrix and parallelize without requiring rowmap file

packages/trilinoscouplings/examples/scaling/TrilinosCouplings_Statistics.hpp
This actually appears to be a bug.  It appears that the variable `ratio` was intended to be modified within a for-loop, and then used afterwards.  However, it was declared within the loop (hence the shadow), and thus never changing the outer declared variable's value.
I also replaced a bunch of tabs with spaces.
@csiefer2 @trilinos/trilinoscouplings 
* Blocks #11497.
N/A
=> TrilinosCouplings: resolve shadow warning

packages/piro/src/Piro_SteadyStateSolver_Def.hpp, packages/piro/test/Main_AnalysisDriver_Tpetra.cpp, packages/piro/test/MockModelEval_A_Tpetra.cpp, packages/piro/test/MockModelEval_A_Tpetra.hpp, packages/piro/test/MockModelEval_B_Tpetra.cpp, packages/piro/test/MockModelEval_B_Tpetra.hpp
@trilinos/piro
Piro adjoint sensitivity computation was broken if ROL was not enabled. This PR fixes this.
This PR addresses https://github.com/sandialabs/Albany/issues/867.
=> Piro: fix sensitivity computation when ROL is not enabled

packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
@csiefer2
@ndellingwood 
Fix kokkos/kokkos#5815
=> Tpetra: refactor atomic maximum absolute value of scalar (compatibility with Kokkos)

.mailmap
Change the spelling of my name in ``.mailmap``. This gets used for commit author, and overrides what I set in ``git config --global user.name``.
=> Fix .mailmap name

packages/tempus/src/Tempus_TimeEventList_impl.hpp, packages/tempus/src/Tempus_TimeEventRangeIndex_impl.hpp, packages/tempus/src/Tempus_TimeEventRange_impl.hpp
Fix uninitialized values.
* Closes  #11538 
Will have @crockatt look it over.
Passed local runs of Tempus tests.
=> Tempus:  Uninitialized value referenced before assignment

packages/muelu/doc/MueLu_DoxygenDocumentation.hpp
@cgcgcg @lucbv @pohm01
I was tokenizing MueLu when Chris noticed some of us were missing from the `DoxygenDocumentation.hpp` :)
=> MueLu: Update authors in DoxygenDocumentation

packages/shylu/shylu_node/basker/src/mwm2.hpp
Issue: n/a
Tests: n/a (comment only)
Stakeholder feedback: I hope not!
=> ShyLU: Sometimes the "f" matters

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
Issue: #11510
Tests: Pass
Stakeholder feedback: Discussion on Kokkos slack, See also #11510
@dalg24
=> Tpetra: Remove use of deprecated Kokkos code

packages/ifpack2/src/Ifpack2_Hiptmair_def.hpp, packages/ml/examples/Maxwell/ml_read_maxwell.cpp, packages/ml/src/Operator/ml_operator.c, packages/ml/src/Operator/ml_operator.h, packages/ml/src/Smoother/ml_smoother.c, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp, packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp, packages/muelu/src/Operators/MueLu_Maxwell_Utils_decl.hpp, packages/muelu/src/Operators/MueLu_Maxwell_Utils_def.hpp, packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp, packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp, packages/muelu/src/Utils/MueLu_Utilities.cpp, packages/muelu/test/maxwell/Maxwell3D.cpp, packages/muelu/test/maxwell/ReitzingerPFactory.cpp
Issue: #11214
Tests: Passes customer test
=> MueLu/Ifpack2/ML: Improvements to Maxwell1

packages/muelu/test/scaling/Driver.cpp
Correct a logic error affecting reset of StackTimers for multiple runs (aka reruns). Allow number of reruns to set from command line.
Add option to add suffix to rerun output files.
Add option to add prefix to rerun output files.
Addresses #11522 
N/A
N/A
=> MueLu: driver rerun updates

packages/muelu/doc/UsersGuide/abstract.tex, packages/muelu/doc/UsersGuide/mueluguide.tex
Add authors, fix some affiliations.
Specify month and year for Trilinos in abstract, rather than Trilinos release number.
Updating author list in user's guide.
N/A
N/A
=> MueLu: update user's guide

packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp
Issue: #11214
Tests: Application run
Stakeholder feedback: Gitlab
=> MueLu: Fixing Maxwell1 for the all Dirichlet node case

packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp, packages/tpetra/core/inout/MatrixMarket_TpetraNew.hpp, packages/tpetra/core/test/inout/MatrixMarket_Tpetra_CrsMatrix_InOutTest.cpp
Issue: #11563
Test: new test added
=> Tpetra: Adding a per-process matrix reader/writer

packages/muelu/src/Operators/MueLu_Maxwell1_decl.hpp
Issue: #11214
Tests: n/a
Issue revealed via valgrind
=> MueLu: Maxwell1 initialization fix

packages/ifpack2/example/CMakeLists.txt
Put Ifpack2 BlockTriDiagonalSolver example in both BASIC and PERFORMANCE categories so that it will be built in performance testing builds.
This executable is needed in performance testing builds to run the SPARC problem.
=> Ifpack2: block tridi example category

INSTALL.rst
User Support Ticket(s) or Story Referenced: TRILFRAME-544
We want to have a stated policy about compiler support to which we can point customers.
#11431
=> Framework: Update INSTALL to have supported compilers/MPIs section

CMakeLists.txt, packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/supported-envs.ini
Build/test GNU 8.3.0 for nightly build using C++20
=> Tril frame 539

packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp, packages/shylu/shylu_node/tacho/src/Tacho_CrsMatrixBase.hpp, packages/shylu/shylu_node/tacho/src/Tacho_Driver.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp, packages/shylu/shylu_node/tacho/unit-test/Tacho_Test.hpp
This PR aims to fix issues using multiple streams on an AMD GPU
- On an AMD GPU, we seem to require a separate handle for each stream.
Tested on MI100.
On an NVIDIA GPU, we still use one handle for all the streams.
=> Tacho : fix issues with multiple streams on AMD GPU

TPLsList.cmake, cmake/TPLs/FindTPLCDT.cmake
Added `CDT` into TPLsList and a corresponding `FindTPLCDT.cmake` file.
CDT is a newly added dependency for a STK module, STK_MiddleMesh.
This change is necessary for the latest STK snapshot: #11599.
=> Adding in CDT into the TPLsList

packages/minitensor/src/MiniTensor_TensorBase.i.h
@lxmota
@ndellingwood
Fix #11511
Haven't actually tested.  @lxmota plz review and make sure it still does what you want.
=> MiniTensor: Avoid `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST` macro

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp, packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp
Added overload of setAllValues() that accepts a KokkosSparse::CrsMatrix.
Added free function that removes zeros from an existing Tpetra::CrsMatrix.
Added two options to damped Jacobi kernel, $(I-\omega * D^{-1} * A)*P$
1) to enable removal of too-small entries
2) threshold for determining which entries are too small
**This depends on Kokkos 4.0.**
Applications sometimes produce matrices that explicitly store zero entries, and it can be advantageous to remove them, for example, in preconditioner setup.
Added unit tests.
=> Tpetra remove zeros from CrsMatrix

packages/muelu/doc/MueLu_DoxygenDocumentation.hpp, packages/muelu/test/interface/ParameterListInterpreter.cpp, packages/muelu/test/unit_tests/Hierarchy.cpp
I suppressed a couple more warnings related to `system` and `mkstemp` calls. I also updated Matthias' affiliation in the `DoxygenDocumentation` to reflect his correct affiliation.
The snow finally subsided in Detroit, but I'm still waiting to hopefully get on a plane soon. :)
=> MueLu: Suppress more system and mkstemp warnings, update affiliations

packages/muelu/utils/misc/sendBuilds.sh
@cgcgcg 
A complementary script to the `pullBuilds.py` script to help a little more. It's essentially just a wrapper for `mail`, but makes my life easier by putting it in the same directory :stuck_out_tongue:
=> MueLu: Add sendBuilds.sh utils/misc script

packages/muelu/test/scaling/JacobiKernelDriver.cpp, packages/muelu/test/scaling/MMKernelDriver.cpp, packages/muelu/test/scaling/MatvecKernelDriver.cpp, packages/muelu/test/scaling/TwoMatrixMMKernelDriver.cpp, packages/muelu/test/unit_tests/RegionMatrix.cpp
@cgcgcg 
* Related to #11643
Tested in our own OpenMP + MKL, Cuda 12 without UVM + CuSparse, Cuda 12 with UVM + CuSparse, and HIP builds, as described in #11643. Not sure all changes will be tested by the Trilinos pipelines because not sure there are MKL or HIP pipelines.
=> MueLu: Fixes for MKL and cuda 12 (#11643)

packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
Fix build errors when ``Sacado::MP::Vector`` is used as the scalar type in the FastILU family of preconditioners.
Fixes #11656 .
The modified code is tested in Ifpack2.
=> ShyLU/Ifpack2: fix #11656 (FastILU w/ Sacado)

packages/muelu/research/graham/CMakeLists.txt, packages/muelu/research/graham/mf_example_01.cpp
@trilinos/muelu @cgcgcg 
This fixes the bug in the experimental build introduced by #11664, but hopefully it actually fixes #11660.
I have confirmed that MueLu experimental builds correctly with this.
=> MueLu: Fix abstract type in matrix-free

Version.cmake
Trilinos 14.0 is ready for release.  Need the versions to be ready for the tag.
=> Update versions in anticipation of 14.0 release

packages/stk/stk_integration_tests/mock_apps/StkMesh.hpp, packages/stk/stk_integration_tests/mock_apps/mock_aria.cpp, packages/stk/stk_integration_tests/mock_apps/mock_fuego.cpp, packages/stk/stk_integration_tests/mock_apps/mock_salinas.cpp, packages/stk/stk_integration_tests/mock_apps/mock_sparc.cpp, packages/stk/stk_io/stk_io/IossBridge.cpp, packages/stk/stk_mesh/stk_mesh/base/Bucket.hpp, packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp, packages/stk/stk_mesh/stk_mesh/base/FieldBLAS.cpp, packages/stk/stk_mesh/stk_mesh/base/FieldBLAS.hpp, packages/stk/stk_mesh/stk_mesh/base/FieldBase.cpp, packages/stk/stk_mesh/stk_mesh/base/FieldRestriction.hpp, packages/stk/stk_mesh/stk_mesh/base/SkinMeshUtil.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/ParallelInfoForGraph.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/ParallelInfoForGraph.hpp, packages/stk/stk_performance_tests/stk_mesh/ChangeEntityPartPerfTest.cpp, packages/stk/stk_performance_tests/stk_mesh/ManyBlocksSidesetsPerformance.cpp, packages/stk/stk_performance_tests/stk_mesh/multi_block.cpp, packages/stk/stk_performance_tests/stk_mesh/multi_block.hpp, packages/stk/stk_transfer/stk_transfer/ReducedDependencyGeometricTransfer.hpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestChangeParts.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestFieldImpl.cpp, packages/stk/stk_util/stk_util/parallel/CouplingVersions.cpp, packages/stk/stk_util/stk_util/parallel/CouplingVersions.hpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp
=> STK: Snapshot 03-14-23 07:20 from Sierra 5.13.1-89-g47f02a9c

packages/piro/src/Piro_PerformAnalysis.cpp
@trilinos/piro
Fix bug introduced in #11649 to avoid compilation error when Trilinos is built with Teko disabled.
Closes #11670.
=> Piro: fix compilation error when Teko is not enabled

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Provides finer timing granularity to TAFC (Transfer And Fill Complete), which is running on host.
N/A
Enabled only when Tpetra MMM timings are enabled.
Necessary first step to address #11689.
=> Tpetra: add more timers to transferAndFillComplete

packages/shylu/shylu_node/tacho/src/impl/Tacho_Lapack_Team.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeChol.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeLDL.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeLU.hpp
This PR aims to catch the invalid pivots encountered during the team factorization of Tacho.
=> Tacho : catch invalid pivots in teamed factorization

packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
=> zoltan2: Workaround c++20 deprecation of implicit this capture via [=].

packages/amesos2/example/SimpleSolve_IR.cpp, packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp, packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp, packages/amesos2/src/Amesos2_Superludist_def.hpp
This PR fixes compilation errors with complex scalar types. It also extend an example to test new options added to SuperLU_DIST with [PR #11480](https://github.com/trilinos/Trilinos/pull/11480)
=> Amesos2::SuperLU_DIST: fix compilation errors with complex scalar

packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp
=> MueLu Utilities: Fix compile issue on HIP

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
Running on Intel GPUs using SYCL.
Running the `Ifpack2` unit tests with `Kokkos_ENABLE_SYCL=ON`.
=> Ifpack2: Fix tests for SYCL

packages/stokhos/src/sacado/kokkos/Stokhos_StaticFixedStorage.hpp
Update corresponding to kokkos/kokkos#5854
Update to enable Trilinos to compile against kokkos' develop branch (currently the eventual 4.1 release)
Local nightly testing issues resolved; AT will add testing
=> stokhos: update include for compatibililty with kokkos

packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_ArithTraits_MP_Vector.hpp
Compatibility update with kokkos/kokkos-kernels#1748
Enable compilation of Stokhos with Kokkos versions 4.0 and post-Kokkos@4.0
AT
=> stokhos: remove ArithTraits from Details namespace post Kokkos@4.0

packages/muelu/test/scaling/Driver.cpp
=> MueLu: Adding CPU memory diagnostic to Driver

packages/stokhos/src/sacado/kokkos/pce/belos/Belos_TpetraAdapter_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/pce/ifpack2/Stokhos_Ifpack2_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_ArithTraits_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_Blas1_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_InnerProductSpaceTraits_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_MV_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/amesos2/Amesos2_Basker_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/belos/Belos_TpetraAdapter_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_ArithTraits_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_InnerProductSpaceTraits_MP_Vector.hpp
Remove ArithTraits from Details namespace post Kokkos@4.0 part 2 - more extensive then I realized in previous PR
Compatibility update with kokkos/kokkos-kernels#1748
AT, currently testing a local build with Kokkos+KokkosKernels develop branches
=> stokhos: remove ArithTraits from Details namespace post Kokkos@4.0 pt2

packages/intrepid2/unit-test/Projection/test_project_fields.hpp
Minor bugfix to test. Thanks @cgcgcg for reporting it.
=> Intrepid2: bugfix to project-field test

packages/muelu/src/Interface/MueLu_FactoryFactory_decl.hpp, packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_decl.hpp, packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedDirectSolver_def.hpp, packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp
So far the blocked direct method for the coarse level solve always used the default KLU implementation, which is not optimal.
Making it possible to select the direct solver type for the blocked solve via the xml-file to choose e.g. Superlu_dist.
Monolithic multigrid for fluid-structure-interaction.
Interesting for @mayrmt @Max-pert
=> MueLu: Enable explicit blocked direct solver type

packages/panzer/disc-fe/src/evaluators/Panzer_GatherNormals_decl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherNormals_impl.hpp
Fixes regression tests in empire for UVM=OFF builds
No test in panzer test exercises this evaluator. It was added for empire use only. Will add a unit test in a separate commit. This allows empire to make progress on uvm removal.
=> Panzer: remove uvm from gather normals

packages/phalanx/test/Kokkos/CMakeLists.txt, packages/phalanx/test/Kokkos/tKokkosScalarFunctionsFad.cpp
Add application use case as a performance test
=> Phalanx scalar functions

packages/phalanx/test/Kokkos/tKokkos.cpp
Use case from application that uses the new CAS capabilities in kokkos.
=> Phalanx: Add kokkos acceptance unit test for online stddev algorithm

packages/stk/stk_ngp_test/stk_ngp_test/GlobalReporter.cpp, packages/stk/stk_util/stk_util/ngp/NgpSpaces.hpp
Reverts trilinos/Trilinos#11728.
See https://github.com/trilinos/Trilinos/issues/11728#issuecomment-1502412238
=> Revert "STK: Fix compiling with SYCL"

packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp, packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp
This seems reasonable, but I'll wait for @rstumin's feedback.
=> MueLu: Set "aggregation: match ML phase2a" in ML2MueLu translation

packages/ml/src/Utils/ml_utils.c
This changes _MSC_VER with _WIN32 macro to check Windows platform.
_MSC_VER is specific for MSVC toolchain and not defined in mingw
based toolchain. So, this fixes the following compiler error with
mingw clang.
Trilinos/packages/ml/src/Utils/ml_utils.c:1965:9: error: call to undeclared function 'gethostname'
Trilinos/packages/ml/src/Utils/ml_utils.c:1966:68: error: call to undeclared function 'getpid'
Trilinos/packages/ml/src/Utils/ml_utils.c:1973:9: error: call to undeclared function 'sleep'
Also remove the MSVC specific pragma directive. ws2_32 library is
already mentioned in corresponding CMakeLists.txt file.
This fixes compiling with clang 16 in mingw toolchain.
=> ML: Fix checking Windows platform for non-msvc toolchain

packages/muelu/test/scaling/CMakeLists.txt
Allows `MueLu_Driver.exe` to be installed.
This is useful for MueLu developers and users.
n/a
I've verified this works locally.
=> MueLu: make driver test installable

packages/intrepid2/src/Shared/Intrepid2_Data.hpp
Remove detritus from working around bugs in old versions of the Intel Classic compiler that are no longer supported in Trilinos.
Spurred by inspection I was doing as part of reviewing kokkos/kokkos#5906
=> Intel ICE workaround removal

TPLsList.cmake, cmake/TPLs/FindTPLmpi_advance.cmake, packages/tpetra/core/cmake/Dependencies.cmake, packages/tpetra/core/cmake/TpetraCore_config.h.in
=> TPL / Tpetra: Adding support for mpi_advance

packages/muelu/src/Utils/MueLu_PerfModels_decl.hpp, packages/muelu/src/Utils/MueLu_PerfModels_def.hpp, packages/muelu/test/scaling/MatvecKernelDriver.cpp
=> MueLu: Performance Model improvements

packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/supported-envs.ini, packages/framework/pr_tools/LaunchDriver.py
Resurrect previous ATS2 genconfig build, but with newer compiler/cuda/mpi. See TRILFRAME-110 for more information.
=> TRILFRAME-110 to resurrect ATDM ATS2 build

packages/piro/src/CMakeLists.txt, packages/piro/src/Piro_PerformAnalysis.cpp, packages/piro/src/Piro_ProductModelEval.hpp, packages/piro/src/Piro_SteadyStateSolver_Def.hpp, packages/piro/src/Piro_ThyraProductME_Constraint_SimOpt.hpp, packages/piro/src/Piro_ThyraProductME_Objective_SimOpt.hpp, packages/piro/test/CMakeLists.txt, packages/piro/test/Main_AnalysisDriver_Tpetra.cpp, packages/piro/test/Main_ThyraSolver_Tpetra.cpp, packages/piro/test/MockModelEval_B_Tpetra_2_parameters.cpp, packages/piro/test/MockModelEval_B_Tpetra_2_parameters.hpp, packages/piro/test/_input_Analysis_ROL_ReducedSpace_TrustRegion_HessianBasedDotProduct_2_parameters.xml
This PR adds a Piro::ProductModelEvaluator that combines together multiple parameters into one so that API that supports one parameter such as ROL can be used with multiple parameters.
This PR adds a test with 2 parameters.
@mperego
=> Piro: Add ProductModelEvaluator for steady state problems and a test with 2 parameters.

packages/anasazi/epetra/src-rbgen/RBGen_StSVD_RTR.cpp
=> Fix a warning in Anasazi that prevents from building Teko warning free

packages/stokhos/src/sacado/kokkos/vector/KokkosBlas2_gemv_MP_Vector.hpp
Call non-static member function for KOKKOS_VERSION >= 4.1 Compatibililty update with kokkos/kokkos#5836
Resolve compatibility compilation issues with Kokkos versions post 4.0.0
AT; Resolved issues with local builds
=> stokhos: call Kokkos concurrency instead of static impl_thread_pool_size

packages/muelu/research/graham/mf_example_01.cpp
@trilinos/muelu @pohm01 
Just some minor cleanups with the matrix-free driver that I had sitting around, like fixing the non-multigrid route and adding some more multigrid settings.
=> MueLu: Clean ups for matrix-free example 01, fix Belos route

packages/stk/stk_unit_tests/stk_util/environment/UnitTestReportHandler.cpp, packages/stk/stk_util/stk_util/util/ReportHandler.hpp
Errors have been reported in the nalu code-base due to this, so we'll remove it and put it back in later once we've diagnosed and fixed the issue.
=> STK: temporarily revert the ThrowAssert/ThrowRequire deprecation.

packages/ifpack2/src/Ifpack2_DatabaseSchwarz_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
Use magnitude type, not double, since you can't directly multiply ``complex<float>`` by double
#11845
=> Ifpack2: fix build with complex<float>

packages/ifpack2/example/BlockTriDi.cpp
=> Ifpack2: fix block tridi example on 1 rank

packages/seacas/libraries/aprepro_lib/apr_aprepro.cc, packages/seacas/libraries/aprepro_lib/aprepro.h
Eliminate memory leak due to file(s) not being closed at end of run.
=> Seacas eliminate memory leak

packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer_Zoltan2.hpp, packages/zoltan2/core/src/models/Zoltan2_GraphModel.hpp, packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp
=> Zoltan2: Update TpetraCrsColorer's Zoltan2 version

packages/panzer/disc-fe/src/evaluators/Panzer_GatherNormals_decl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherNormals_impl.hpp
=> Panzer: fix gather normals

packages/piro/src/Piro_PerformAnalysis.cpp, packages/piro/src/Piro_ProductModelEval.hpp, packages/piro/src/Piro_ThyraProductME_Objective_SimOpt.hpp
@ikalash 
This PR fixes #11848 . I tried it on my workstation with and without Teko and the tests passed in both cases.
=> Piro: fix issue #11848

packages/framework/ini-files/config-specs.ini
Disable ROL_example_PinT_parabolic-control_AugmentedSystem_test_MPI_2 in PR testing, with the blessing of the ROL developers.
Reported in issues #11621, #11874, and #11654.
@trilinos/framework @trilinos/rol @cwpearson
=> Framework: disable ROL test for PR testing

packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp, packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp, packages/tpetra/core/src/Tpetra_Details_normImpl.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Making some fixes to our code for proper runs with SYCL backend
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
ECP
Tested on ANL machines with oneAPI compilers.
=> Tpetra sycl updates

packages/amesos/test/Test_KLU/cxx_main.cpp
@trilinos/amesos 
The new dashboard for memory leaks in Trilinos has identified an issue in the Amesos tests.  This is being addressed with this commit.
https://trilinos-cdash.sandia.gov/index.php?project=Trilinos#!/%23DynamicAnalysis
Mac OSX GCC12 / RHEL7 Intel 19.x
=> Amesos: Cleanup memory leak in KLU test

packages/tpetra/core/compat/Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.cpp, packages/tpetra/core/compat/cmake/Tpetra_KokkosClassic_DefaultNode_config.h.in, packages/tpetra/core/src/Tpetra_Details_ExecutionSpaces.cpp, packages/tpetra/core/src/Tpetra_Details_ExecutionSpaces.hpp, packages/tpetra/core/src/Tpetra_Details_ExecutionSpacesUser.hpp, packages/tpetra/core/test/Spaces/SpaceUser.cpp, packages/tpetra/core/test/Spaces/Spaces.cpp
Some fixes for build errors with SYCL. Makes Tpetra lib and all tests build for INTEL_PVC arch.
This is just about getting things to build. Most things seem to actually run, but not all. For example, TpetraCore_Bug10008_MPI_4 segfaults.
=> Tpetra: SYCL build fixes

packages/anasazi/epetra/test/Epetra64Driver/build_simple_matrices.hpp, packages/belos/epetra/test/Epetra64Driver/build_simple_matrices.hpp, packages/belos/epetra/test/Epetra64Driver/cxx_main.cpp
@trilinos/belos @trilinos/anasazi
The new dashboard for memory leaks in Trilinos has identified an issue in the Epetra64 testing in Anasazi and Belos. This is being addressed with this commit.
https://trilinos-cdash.sandia.gov/index.php?project=Trilinos#!/%23DynamicAnalysis
Mac OSX GCC12 / RHEL7 Intel 19.x
=> Anasazi/Belos: Cleanup memory leaks in Epetra64 testing

packages/ifpack2/example/BlockTriDi.cpp
Adding more logic to generate 3D matrices and have the block size as command line parameter. The driver still fails in some cases for unknown reasons at this time. One big issue at the moment is that only the y direction gets distributed across MPI ranks...
This work allows us to reproduce more closely the use case for the BlockTriDiagSolver
Tested on Frontier
=> Ifpack2 BlockTriDi: updating example

packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer.hpp
This fixes the calculation of the offset for coloring BlockCrs when processing the colors in chunks.
=> Zoltan2:  Fix calculation of color offset for BlockCrs

packages/tpetra/core/src/Tpetra_Details_checkView.hpp
Compatibility update for kokkos/kokkos#6120
Solution provided by @dalg24 in kokkos/kokkos#6141
Resolve compilation issues with Kokkos develop branch
Confirmed compilation succeeds with local builds; AT will handle more extensive testing
=> Tpetra: Compabibility update to check*ViewValidity template parameters

packages/ifpack2/example/BlockTriDi.cpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
The timers of the BlockTriDi solver were not accurate due to some missing fences.
This PR adds fences in the solver *only* if `HAVE_IFPACK2_BLOCKTRIDICONTAINER_TIMERS` is defined.
=> Ifpack2: Add fences for the BlockTriDi timers

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Fixes failures in panzer unit tests for UVM=ON builds caused by PR #11734 
A couple of panzer unit tests were failing due to changes in #11734 
The issue was that there were two deep copies that were changed from using the two-argument version to the three-argument version. There is a big difference between the two. The two-arg fences automatically, while the three-arg does not. This broke UVM builds. This commit adds back the fences. Only the first deep_copy on line 1232 was needed to fix the panzer tests. But I'm pretty sure the second one (line 1260) needs the explicit fence as well (panzer testing was just not using this path). I'm not sure if we have unit tests that trigger the switch from host to device (switch testing from line 1232 to 1260). Maybe tpetra team can …
=> Tpetra: fix UVM builds for recent execution space instance change

packages/nox/examples/lapack/NOX_SimpleExamples/Rosenbrock.C, packages/nox/test/epetra/1Dfem/1DfemAztecSolverPrecRecompute.C
A couple more fixes for the return value mentioned in issue #11530.
@trilinos/nox
=> NOX: fix return value on unit tests

packages/sacado/src/new_design/Sacado_Fad_Exp_Atomic.hpp
For issue #11924 
Thanks @romintomasetti!
=> Sacado:  Fix obvious build error on HIP

packages/stokhos/src/sacado/kokkos/pce/Sacado_UQ_PCE_Imp.hpp
For issue #11877
@eugeneswalker
@kuberry
=> Stokhos:  Add missing KOKKOS_INLINE_FUNCTION to fix build errors on HIP

packages/tpetra/core/test/Utils/StaticView.cpp
Issue: #11917
Tests: n/a
Stakeholder feedback: See #11917
=> Tpetra: Changes to StaticView for Kokkos PTHREAD to THREADS change

packages/muelu/research/caglusa/Tpetra_HierarchicalOperator_decl.hpp
Fixes a build error in research code.
=> MueLu hierarchical: Fix build error

packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp, packages/muelu/src/Utils/MueLu_Utilities_def.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_decl.hpp, packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp, packages/zoltan2/test/sphynx/Sphynx_Research_Driver.cpp
@trilinos/xpetra @trilinos/muelu @trilinos/zoltan2 
Fixes some issues discovered in an int-int build.
=> Xpetra,MueLu,Zoltan2: Fix build errors

packages/muelu/src/MueCentral/MueLu_FactoryManager_def.hpp
Issue: #11214
Tests: n/a
Stakholder feedback: n/a
=> MueLu: Enabling better dumps for Maxwell1

packages/framework/ini-files/config-specs.ini
User Support Ticket(s) or Story Referenced: TRILFRAME-378
Needed for nightly build
=> Framework: Add a spec for all packages + complex<float>

Version.cmake
Version number update post 14.2 release.
=> trilinos-release-14-2-branch-update

packages/muelu/doc/UsersGuide/masterList.xml, packages/muelu/doc/UsersGuide/paramlist.tex, packages/muelu/doc/UsersGuide/paramlist_hidden.tex, packages/muelu/src/MueCentral/MueLu_MasterList.cpp, packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp, packages/muelu/src/Operators/MueLu_Maxwell_Utils_decl.hpp, packages/muelu/src/Operators/MueLu_Maxwell_Utils_def.hpp
=> MueLu: Another round of Maxwell1 Cleanup

packages/muelu/src/MueCentral/MueLu_FactoryManager_def.hpp, packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp, packages/muelu/src/Operators/MueLu_Maxwell_Utils_decl.hpp, packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp, packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp, packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_decl.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_def.hpp, packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_decl.hpp, packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_def.hpp, packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp, packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
Issue: #11214
Tests: application
Stakeholder feedback: application
=> MueLu: Yet another round of Maxwell1 fixes

packages/muelu/src/Transfers/BlockedTransfers/MueLu_ReorderBlockAFactory_decl.hpp, packages/muelu/src/Transfers/BlockedTransfers/MueLu_ReorderBlockAFactory_def.hpp
If the reordering string is empty we run into problems e.g. if I have cases where I just want to split a matrix and don't want a reordering at all. This might happen in fluid problems splitting the matrix into velocity and pressure parts.
On the way I did some minor cleanup.
Not sure if in the future it would make sense to separate functionalities of splitting and reordering (in some sense splitting is also some kind of reordering :smile:).
Related to physics-based block-preconditioning.
Also interesting for @mayrmt @Max-pert
=> MueLu: Small updates on ReorderBlockAFactory

packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp, packages/muelu/utils/misc/makepr.sh
Issue: #11214
Tests: application
Stakeholder Feedback: 'Nice' - Allen
=> MueLu: Next Maxwell1 fix

packages/muelu/doc/UsersGuide/masterList.xml, packages/muelu/doc/UsersGuide/options_aggregation.tex, packages/muelu/doc/UsersGuide/paramlist.tex, packages/muelu/doc/UsersGuide/paramlist_hidden.tex, packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp, packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/src/MueCentral/MueLu_MasterList.cpp, packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp
Issue: #11214
Tests: Already there
=> MueLu: Adding ML style aggregate threshold scaling

packages/tpetra/core/src/Tpetra_BlockView.hpp
@trilinos/teptra
I know that MSVC isn't in your test matrix, but the attached commit makes some simple changes such that  some extra packages can be compiled on MSVC for Windows.
As far as I know `__restrict` should be the same as `__restrict__` on GCC, so nothing should change.
All packages should continue to build as before with your testing matrix.
=> Tpetra: Some changes to build with MSVC

packages/muelu/test/scaling/MatvecKernelDriver.cpp
Issue: #10660
Tests: This is one
=> MueLu: Fixing minor bug in MatvecKernelDriver

packages/panzer/adapters-stk/cmake/Dependencies.cmake, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Quad8ToQuad4MeshFactory.cpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_QuadraticToLinearMeshFactory.cpp, packages/panzer/adapters-stk/test/stk_interface_test/tPamgenMeshFactory.cpp
=> Panzer : Remove deprecated STK code.

packages/seacas/libraries/aprepro_lib/apr_aprepro.cc
=> APREPRO: Fix "if" instead of "else if" in arg parsing

packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/supported-envs.ini
@ccober6 
Want CXX20 build/testing for future CXX standard adoption.
=> Framework: Fix CXX20 build

packages/seacas/libraries/ioss/src/Ioss_Compare.C, packages/seacas/libraries/ioss/src/Ioss_ElementTopology.C, packages/seacas/libraries/ioss/src/Ioss_GroupingEntity.C, packages/seacas/libraries/ioss/src/Ioss_Property.C, packages/seacas/libraries/ioss/src/main/CMakeLists.txt
Previous snapshot had a bad commit which had mistakenly changesd some !string1.compare(string2) into `string1 == string2`.  Fixed those and added two tests that will catch this in the future.
=> IOSS: Fix bad changes from !compare to !=

packages/stk/stk_doc_tests/stk_transfer/howToUseGeometricTransfer.cpp, packages/stk/stk_doc_tests/stk_transfer/howToUseReducedDependencyGeometricTransfer.cpp, packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp, packages/stk/stk_mesh/stk_mesh/base/BulkData.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshCommVerify.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshImplUtils.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshImplUtils.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshModLogObserver.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshModLogObserver.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshModification.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshModification.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/Visitors.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/check_comm_list.cpp, packages/stk/stk_performance_tests/stk_util/perfCommBufferV.cpp, packages/stk/stk_performance_tests/stk_util/perfTagManager.cpp, packages/stk/stk_unit_tests/stk_balance/UnitTestBalanceNodes.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestAura.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestAuraToShared.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestBulkData.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestCEONodes.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestGhostingWithShared.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestMeshModLogObserver.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestModificationEnd.cpp, packages/stk/stk_unit_tests/stk_mesh/face_creation/element_graph/UnitTestElemElemGraph.cpp, packages/stk/stk_unit_tests/stk_util/environment/UnitTestCPUTime.cpp, packages/stk/stk_unit_tests/stk_util/util/UnitTestThrowMacros.cpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp, packages/stk/stk_util/stk_util/registry/stk_version_gen.sh, packages/stk/stk_util/stk_util/util/ReportHandler.hpp
=> STK: Snapshot 07-17-23 09:42 from Sierra 5.15.2-314-g7c2d5cc9

packages/framework/ini-files/config-specs.ini
The test ROL_test_algorithm_TypeP_CompareTypeU_MPI_1 is failing in PR testing.  This commit disables it.
See issue #12068.
@trilinos/framework @trilinos/rol 
This test is causing PR failures in unrelated packages.
I've verified locally that this commit disables the unit test in question.
=> Framework: ROL: disabling randomly failing test

packages/ifpack2/src/Ifpack2_ILUT_decl.hpp, packages/ifpack2/src/Ifpack2_ILUT_def.hpp, packages/ifpack2/src/Ifpack2_Parameters.cpp, packages/ifpack2/src/Ifpack2_RILUK_def.hpp, packages/ifpack2/test/unit_tests/CMakeLists.txt, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestILUT.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessILUT.cpp
Make parallel ILUt algorithm implement in Kokkos-Kernels available through Ifpack2.
Includes a single-rank unit test.
=> Ifpack2: interface to par_ilut in Kokkos-Kernels

packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS_ops.hpp
Pre-emptive pattern-match in Sacado_MP_Vector_SFS_ops.hpp to that in stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_ops.hpp
@trilinos/stokhos @etphipp 
AT
=> stokhos: guard math_functions.h header based on cuda version

packages/muelu/test/scaling/MueLu_PerfModelReporter.hpp
=> MueLu: Adding proc specific output for performance model

packages/muelu/src/Utils/MueLu_PerfModels_def.hpp
=> MueLu: Fix for Cuda in PerfModel

packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_decl.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp, packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
Improve performance of TransferAndFillComplete.
Addresses #11693 and #11694.
Relies on existing unit tests.
=> Tpetra: move unpack and combine to device in TAFC

packages/framework/ini-files/config-specs.ini
Add build for TRILFRAME-578
As discussed in operational leaders meeting today, want a PR with deprecated code disabled.
=> Framework: Add deprecated-off nopackages config

packages/tpetra/core/src/Tpetra_Details_Behavior.cpp, packages/tpetra/core/src/Tpetra_Details_Behavior.hpp, packages/tpetra/core/src/Tpetra_Details_DeepCopyTeuchosTimerInjection.cpp
Issue: #12106
Test: n/a
Stakeholder feedback: Long MueSlack discussions
=> Tpetra: Adding verbose mode for Kokkos::deep_copy timer injection

packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp, packages/tpetra/core/src/Tpetra_Details_DeepCopyTeuchosTimerInjection.cpp
=> MueLu/Tpetra: More deep copy counting cleanup

packages/muelu/src/Misc/MueLu_CoordinatesTransferFactory_def.hpp
=> MueLu: Removing H2D/D2H transfers in CoordinatesTransferFactory for Scalar PDEs

packages/stokhos/test/UnitTest/Stokhos_SDMUtilsUnitTest.cpp, packages/stokhos/test/UnitTest/Stokhos_UnitTestHelpers.hpp
@etphipp 
Proposed fix for issue #12157.
=> Stokhos: fixing issue #12157

packages/zoltan2/core/src/input/Zoltan2_Adapter.hpp, packages/zoltan2/core/src/input/Zoltan2_TpetraRowMatrixAdapter.hpp
=> Zoltan2: Fix CUDA UVM=ON issues with Zoltan2_TpetraRowMatrixAdapter

packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Output.h
Warnings being emitted should be fixed.
Build and run shylu tests.
=> Fix warnings coming from this header.

packages/anasazi/epetra/src-rbgen/RBGen_AnasaziPOD.cpp, packages/anasazi/epetra/src-rbgen/RBGen_BurkardtFileIOHandler.cpp, packages/anasazi/epetra/src-rbgen/RBGen_EpetraCrsMatrixFileIOHandler.cpp, packages/anasazi/epetra/src-rbgen/RBGen_LapackPOD.cpp, packages/anasazi/epetra/src-rbgen/RBGen_MatrixMarketFileIOHandler.cpp, packages/anasazi/epetra/src-rbgen/RBGen_NetCDFFileIOHandler.cpp
The recent PR merged in by @hkthorn to Anasazi broke RBGen.  This PR fixes the problem.
=> Fixing compiling of RBGen 

packages/adelus/src/Adelus_mytime.hpp
This PR adds inline to the two functions in Adelus: ```get_seconds``` and ```showtime``` to fix the errors of multiple definitions in Gemma
The Gemma team confirmed this fixes the errors.
=> Adelus: Add inline to get_seconds and showtime functions

packages/adelus/src/CMakeLists.txt
@trilinos/adelus 
This PR is to add ```Adelus_global_comm.hpp``` in the headers list after the merge of #12168 
The Gemma team confirmed this change fixed the "Adelus_global_comm.hpp not found" error
=> Adelus: Include Adelus_global_comm.hpp in Trilino build

packages/muelu/doc/UsersGuide/masterList.xml, packages/muelu/doc/UsersGuide/paramlist_hidden.tex, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp, packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/src/MueCentral/MueLu_MasterList.cpp, packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp, packages/muelu/test/unit_tests/UncoupledAggregationFactory.cpp
=> MueLu: Adding ML compatibility support for Phase2b aggregation

packages/anasazi/src/CMakeLists.txt
Fix for https://github.com/trilinos/Trilinos/pull/12166
=> Anasazi: Add AnasaziGlobalComm.hpp to CMake source files

packages/muelu/src/Rebalancing/MueLu_RebalanceAcFactory_def.hpp, packages/muelu/src/Rebalancing/MueLu_RepartitionFactory_def.hpp
=> MueLu: Adding finer grained profiling regions for H2D/D2H diagnosis

cmake/SimpleTesting/README.md, cmake/SimpleTesting/cmake/ctest-CTestConfig.cmake, cmake/SimpleTesting/cmake/ctest-cdash-setup.cmake, cmake/SimpleTesting/cmake/ctest-common.cmake, cmake/SimpleTesting/cmake/ctest-driver.cmake, cmake/SimpleTesting/cmake/ctest-functions.cmake, cmake/SimpleTesting/cmake/ctest-stage-build.cmake, cmake/SimpleTesting/cmake/ctest-stage-configure.cmake, cmake/SimpleTesting/cmake/ctest-stage-coverage.cmake, cmake/SimpleTesting/cmake/ctest-stage-test.cmake, cmake/SimpleTesting/cmake/ctest-submit.cmake, cmake/SimpleTesting/img/CMake-structure.graffle, cmake/SimpleTesting/img/CMake-structure.pdf, cmake/SimpleTesting/img/CMake-structure.png, packages/framework/pr_tools/PullRequestLinuxDriver.sh
These changes allow for the code from [SimpleTestingRefactor repo](https://gitlab-ex.sandia.gov/trilinos-devops-consolidation/code/SimpleTestingRefactor/-/tree/main) to be tested within the Trilinos PR system.
=> Framework: Add SimpleTesting to Trilinos

packages/tpetra/CMakeLists.txt, packages/tpetra/core/guide/src/Obtaining/Building.rst
We don't use them and they're not consistent with the ETI_NODES
Issue: #12106
Tests: n/a
=> Tpetra: Removing the incorrect ETI_DEVICES

packages/shards/doc/Doxyfile
@trilinos/shards
Change location of generated Doxygen tag file for `Shards` package so that it is aligned with what other packages do.
=> shards: update Doxyfile for tag file

packages/tpetra/core/src/Tpetra_Details_Random.cpp
Resolve compilation errors with Hip backend and rocm toolchains
Fix compilation errors with Hip
=> Tpetra_Details_Random.cpp: Spelling fix HipSpace->HIPSpace

packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
Issue:#12273
Tests: Tested CUDA with and without UVM
=> Tpetra: Fix to WrappedDualView which should (in theory) help support GH/MI300

packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_decl.hpp, packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp, packages/muelu/src/Utils/MueLu_PerfModels_def.hpp
- Allow nullspace of dim>1.
- Scale shift term proportionally to matrix diagonal.
- Kokkosify.
=> MueLu:  Improvements for pseudo-inverse in Amesos2Smoother

CMakeLists.txt, RELEASE_NOTES
See #10345 and #12104
* Closes #10345 
* Closes #12104
=> Famework: Change defaults for Trilinos-specific CMake flags

packages/amesos2/src/Amesos2_Factory.cpp, packages/amesos2/src/Amesos2_Factory.hpp, packages/amesos2/src/Amesos2_Kokkos_View_Copy_Assign.hpp, packages/amesos2/src/Amesos2_SolverCore_decl.hpp, packages/amesos2/src/Amesos2_Superlu_decl.hpp, packages/amesos2/src/Amesos2_Tacho_decl.hpp
We're currently working on a bug of `KLU2`. I made these changes while working on it. Here they are, for free :smile:
It is basically some missing `override` and some `const std::string&`.
=> amesos2: solve style and performance warnings

.github/workflows/tpetra_muelu_label_to_project.yml
As requested by @jhux2  in #12282
=> Actions: Update tpetra_muelu_label_to_project.yml to add Labels based on Title

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
Attempt to fix https://github.com/trilinos/Trilinos/issues/11349
=> Tpetra: throw when requesting off-rank offsets in non-fill-complete graph

packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp, packages/shylu/shylu_dd/frosch/src/Tools/FROSch_ExtractSubmatrices_def.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp
Update for compatibility following kokkos/kokkos-kernels#1974
@trilinos/tpetra @cwpearson @csiefer2 @brian-kelley 
Minor compatibility update with kokkos-kernels develop branch
Locally compiled; AT will test the rest
=> tpetra: compatibility update with kokkos-kernels

packages/amesos2/CMakeLists.txt, packages/amesos2/cmake/Amesos2_config.h.in, packages/amesos2/src/Amesos2_Factory.hpp, packages/amesos2/src/Amesos2_KokkosCrsMatrix_MatrixAdapter_def.hpp, packages/amesos2/src/Amesos2_KokkosMultiVecAdapter_decl.hpp, packages/amesos2/src/Amesos2_Kokkos_View_Copy_Assign.hpp, packages/amesos2/src/Amesos2_Meta.hpp, packages/amesos2/src/Amesos2_MultiVecAdapter_def.hpp, packages/amesos2/src/Amesos2_PardisoMKL_TypeMap.hpp, packages/amesos2/src/Amesos2_PardisoMKL_decl.hpp, packages/amesos2/src/Amesos2_PardisoMKL_def.hpp, packages/amesos2/src/Amesos2_SolverTraits.hpp, packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp, packages/amesos2/src/Amesos2_Util.hpp, packages/amesos2/src/Amesos2_Version.cpp, packages/amesos2/test/adapters/CrsMatrix_Adapter_Consistency_Tests.cpp, packages/amesos2/test/adapters/Epetra_MultiVector_Adapter_UnitTests.cpp, packages/amesos2/test/adapters/Epetra_RowMatrix_Adapter_UnitTests.cpp, packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp, packages/amesos2/test/adapters/Tpetra_MultiVector_Adapter_UnitTests.cpp, packages/amesos2/test/solvers/Basker_UnitTests.cpp, packages/amesos2/test/solvers/KLU2_UnitTests.cpp, packages/amesos2/test/solvers/MUMPS_UnitTests.cpp, packages/amesos2/test/solvers/STRUMPACK_UnitTests.cpp, packages/amesos2/test/solvers/ShyLUBasker_UnitTests.cpp, packages/amesos2/test/solvers/Superlu_UnitTests.cpp, packages/stokhos/src/sacado/kokkos/pce/amesos2/Amesos2_Solver_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/amesos2/Amesos2_Basker_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/amesos2/Amesos2_Solver_MP_Vector.hpp
I'm still working on that bug I mentioned in #12209.
I've removed old type traits that are now fully supported by C++17. Enjoy!
@iyamazaki
=> amesos2(cleaning): removing old type traits that are not supported by C++17

packages/tempus/src/Tempus_ExplicitTemplateInstantiation.hpp, packages/tempus/test/BDF2/Tempus_BDF2Test.cpp, packages/tempus/test/BackwardEuler/Tempus_Test_BackwardEuler_CDR.cpp, packages/tempus/test/HHTAlpha/Tempus_HHTAlphaTest.cpp, packages/tempus/test/TestModels/CDR_Model.cpp, packages/tempus/test/TestModels/CDR_Model_Functors.hpp, packages/tempus/test/TestModels/CDR_Model_Tpetra_decl.hpp, packages/tempus/test/TestModels/CDR_Model_Tpetra_impl.hpp
=> Tempus: Implement `CDR_Model_Tpetra` and use it for `BackwardEuler` and `BDF2`

packages/belos/tpetra/test/BlockCG/CMakeLists.txt, packages/belos/tpetra/test/BlockCG/test_pseudo_cg_indefinite.cpp
@hkthorn
This PR creates a Tpetra version of the `pseudo_cg_indefinite` test.
=> Belos: add Tpetra pseudo_cg_indefinite test

packages/ifpack2/example/RelaxationWithEquilibration.cpp, packages/ifpack2/src/Ifpack2_MDF_def.hpp, packages/ifpack2/src/Ifpack2_ReorderFilter_def.hpp, packages/ifpack2/test/belos/tpetra_native.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessILUT.cpp, packages/shylu/shylu_node/cmake/Dependencies.cmake, packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
A recent PR to ifpack2 had build errors with complex doubles but passed CI because the relevant ShyLU subpackage was marked as experimental. This build error later impacted a user. We decided that this subpackage should be promoted to "primary tested" (PT) in order to avoid this in the future.
I will watch the cdash link for the CI run and confirm that FILU tests are present.
=> ShyLU::FastILU promote to primary tested (PT)

packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp
@etphipp @ndellingwood 
Fixes #12352.
=> stokhos: fixes #12352

packages/framework/ini-files/config-specs.ini, packages/piro/src/Piro_PerformAnalysis.cpp, packages/piro/test/CMakeLists.txt, packages/piro/test/Main_AnalysisDriver_Tempus.cpp
@trilinos/piro
@mperego 
This PR decouples MassSpringDamperModel to be run with only one MPI rank.
=> Piro: Decouple MassSpringDamperModel from the rest

packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp, packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp, packages/ifpack2/src/Ifpack2_RILUK_def.hpp, packages/ifpack2/test/belos/CMakeLists.txt, packages/ifpack2/test/belos/schwarz.xml
Issue: #12273
Tests: Added
Stakeholder feedback: MueChat with @jhux2
=> Ifpack2: Adding improved AdditiveSchwarz diagnostics

packages/tpetra/core/src/Tpetra_DistObject_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Issue: #12273
Stakheolder feeback: @jhux2 used the open hands emjoji
Tests: n/a
=> Tpetra: Improved ProfilingRegion naming for data xfer diagnostics

packages/piro/src/Piro_ThyraProductME_TempusFinalObjective.hpp
@trilinos/piro
@ikalash 
Fix #12374.
=> Piro: build without Teko

packages/nox/src-loca/src-thyra/LOCA_Thyra_Group.C, packages/nox/src-loca/src-thyra/LOCA_Thyra_Group.H, packages/nox/src-loca/src/LOCA_Extended_MultiAbstractGroup.C, packages/nox/src-loca/src/LOCA_Extended_MultiAbstractGroup.H, packages/nox/src-thyra/NOX_PrePostOperator_RowSumScaling.C, packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.cpp, packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.hpp, packages/nox/src/NOX_Abstract_Group.C, packages/nox/src/NOX_Abstract_Group.H, packages/tempus/src/Tempus_WrapperModelEvaluatorBasic_decl.hpp
=> NOX/LOCA/Tempus: changes to use Householder constraints with Tempus transient 

packages/tpetra/CMakeLists.txt, packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp, packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp, packages/tpetra/core/src/Tpetra_Details_DistributorPlan.hpp, packages/tpetra/core/src/Tpetra_Distributor.cpp, packages/tpetra/core/test/ImportExport2/CMakeLists.txt, packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp, packages/tpetra/core/test/MPIAdvance/AllToAll.cpp, packages/tpetra/core/test/MPIAdvance/AllToAllV.cpp, packages/tpetra/core/test/MPIAdvance/NeighborAllToAllV.cpp, packages/tpetra/core/test/MPIAdvance/NeighborAllToAllW.cpp, packages/tpetra/core/test/MPIAdvance/NeighborLocalityAllToAllV.cpp, packages/tpetra/core/test/MPIAdvance/NeighborPartLocalityAllToAllV.cpp
Prerequisites: 
@mikethebos @bienz2 @csiefer2
=> Tpetra: MPIAdvance AllToAll and Neighborhood AllToAllV

packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp
Issue: #12381
Stakeholder feedback: @ikalash please test!
Test: n/a
Well, I can't reproduce your issue directly.  But this looks like it should fix it.
=> Ifpack2: Hopefully fixing LCM Issue

packages/teuchos/numerics/src/Teuchos_LAPACK.cpp
=> Teuchos: Fix LARND with Kokkos::complex<double>

packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
Issue: #11214
Stakeholder feedback: Fixes the application
Tests: pass
=> Ifpack2: Adding BC-respecting initial guess for Chebyshev eigenvalue estimation

packages/muelu/test/perf_tests_kokkos/KokkosKernels.cpp
Resolve compilation errors following upstream removal of iostream, see kokkos/kokkos#6482
Resolve compilation errors with Kokkos develop branch following header include cleanup in https://github.com/kokkos/kokkos/issues/6482
AT
=> muelu: upstream iostream removal fix

packages/stk/stk_util/stk_util/parallel/DeletionGroup.cpp, packages/stk/stk_util/stk_util/util/AlignedAllocator.cpp
Resolve compilation errors following upstream removal of iostream, see kokkos/kokkos#6482
@trilinos/stk @alanw0 @ldh4 
Resolve compilation errors with Kokkos develop branch following header include cleanup in kokkos/kokkos#6482
Tested in local cuda build, AT will handle rest
=> stk: upstream iostream removal fix

packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_FE.hpp
Clean this up a bit before TUG 2023
Built-in tests
=> Tpetra: clean up finite element assembly example

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
Issue: #12273 
Stakeholder feedback: MueLu Standup discussion
Tests: n/a
=> Tpetra: Adding Kernel Labels

packages/framework/get_dependencies.sh, packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/environment-specs.ini, packages/framework/ini-files/supported-systems.ini
This adds ini configuration files so that genconfig/loadenv can work inside of a container where the environment is already setup.  There are also changes to get-dependencies.sh so that it will take --container as an option in addition to --srn and --son
=> Framework: Container changes

packages/ifpack2/src/Ifpack2_Hiptmair_decl.hpp, packages/ifpack2/src/Ifpack2_Hiptmair_def.hpp, packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
Issue: #11214
Stakeholder feedback: Discussions w/ @cgcgcg
Tests: pass
=> MueLu/Ifpack2: Allowing Hiptmair+Chebyshev to set the matrix eigenvalue instead of recomputing

packages/tpetra/core/src/Tpetra_DistObject_def.hpp
The labeling of methods in `Tpetra::DistObject` was wrong, as @csiefer2 and I discovered while debugging.
See #12106 
N/A
Confirmed locally that this is now correct.
=> Tpetra: fix labels

packages/intrepid2/unit-test/Projection/test_convergence_PYR.hpp
Fix to allow compilation with `Intrepid2_KEEP_EXPERIMENTAL_NAMESPACE:BOOL=OFF`, see #12141.
=> Intrepid2: fix namespace of Pyramid projection test

packages/phalanx/src/Phalanx_DataLayout_MDALayout.hpp, packages/phalanx/src/Phalanx_DataLayout_MDALayout_Def.hpp
Compile issues with gcc 12 on blake: https://github.com/trilinos/Trilinos/issues/12418
Also want to move to modern c++. Parameter packs allow for significant reduction in code.
Phalanx and Panzer tests all pass with this change. Looks like this is a backwards compatible change for the libraries.
Need to test against apps before pushing. DO NOT SET AUTOMERGE!
=> Phalanx: refactor MDALayout to use variadic templates

packages/muelu/doc/UsersGuide/update_params.sh, packages/muelu/src/MueCentral/MueLu_MasterList.cpp
=> MueLu: Removing superfluous output

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_decl.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp, packages/tpetra/core/src/Tpetra_Import_Util2.hpp, packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
Remove an unnecessary device-to-host copy.
N/A
Confirmed locally.
=> Tpetra: remove another deep_copy

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp
Issue: #12016
Stakeholder feedback: Email with @jhux2
Tests: n/a
=> Tpetra: Adding profiling region for FHT::init and Tpetra::Map

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_decl.hpp, packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
Part of #12106.   Grew organically out of discussions with @csiefer2.
N/A
No
=> Tpetra: add helpful profile region

cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc-cuda.cmake, cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc.cmake
Try to silence warnings like this one:
https://testing.sandia.gov/cdash/test/167232684
=> Geminga: Attempt to silence chatty MPI

packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp
#12472 
Tested on weaver using instructions found in #12472
=> MueLu RefMaxwell: Fix use of scalar type for complex

.github/workflows/PR-gcc-openmpi.yml, packages/framework/ini-files/config-specs.ini
This will enable a containerized build through github actions. The idea is that it will be run for all PR
=> Framework: yml file to enable a gcc-openmpi container build that can run for PR

packages/muelu/test/unit_tests/Smoothers/BlockedSmoother.cpp
Tiny tolerance fix for BlockSmoother tests.
=> MueLu BlockSmoother: One more tolerance fix for float

packages/muelu/doc/UsersGuide/update_params.sh, packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp, packages/muelu/src/MueCentral/MueLu_MasterList.cpp
=> MueLu: fix ML2Muelu translator issue arising in ALEGRA

RELEASE_NOTES, Version.cmake
=> Framework: Trilinos 15 version update

packages/tpetra/core/src/Tpetra_Import_Util2.hpp, packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
T/F reported overflows for GIDs that are greater than the 32-bit limit. I was able to reproduce locally.  This fixes the issue (big thanks to Tyler V. for pointing one location out).
Test will follow in separate PR.
Issue reported by application.
Reports that this fixes their issue when applied locally.  We'll know at the next integration testing.
Tested locally, will commit unit test in separate PR.
=> Tpetra: fix overflow issue

packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessILUT.cpp
=> Ifpack2: loosen ParILUT test tolerance

packages/compadre/src/tpl/KokkosBatched_SolveUTV_TeamVector_Internal_Compadre.hpp
@trilinos/compadre @kuberry @mperego 
Fix compilation error with kokkos@4.2.00
=> compadre: fix scope typo with Kokkos::printf

packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
=> MueLu: fix translation of ML aux:enable to dist lap

RELEASE_NOTES, Version.cmake
Update versions after 15.0 release for develop.
DO NOT MERGE prior to #12526 and the release being finalized.
=> Framework: Post 15.0 version update

packages/panzer/mini-em/example/BlockPrec/MiniEM_helpers.cpp
Simplify the logic for setting default solver parameters. Fixes issue on HIP.
=> Panzer MiniEM: Simplify default solver PLs

packages/muelu/test/scaling/CMakeLists.txt
Add check for convergence for some scaling driver based tests.
Even if tests fail to converge, ctest reports the test as passing.
N/A
I confirmed locally that with this change, a test that doesn't converge is reported as failing.
=> MueLu: add convergence check for some scaling driver tests

packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp
=> MueLu RefMaxwell: Handle another corner case

packages/belos/tpetra/test/BlockGmres/test_resolve_gmres_hb.cpp
This test performs a linear solve multiple times using the mechanisms for resetting solvers provided by Belos.  The solution vectors computed by each solve are compared.  However the comparison uses absolute error instead of relative error.  This commit modifies the comparison, which will make it more robust for multi-threaded/CUDA testing.
* Closes #12501
ascicgpu030 using MPI/GCC/CUDA setup from #12501
=> Belos:  Modifies solution vector comparison in Belos_Tpetra_resolve_gmres_hb_{0,1}_MPI_4

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp, packages/tpetra/core/src/Tpetra_Map_decl.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp, packages/xpetra/src/BlockedMap/Xpetra_BlockedMap_decl.hpp, packages/xpetra/src/BlockedMap/Xpetra_BlockedMap_def.hpp, packages/xpetra/src/Map/Xpetra_EpetraMap.hpp, packages/xpetra/src/Map/Xpetra_EpetraMapFactory.cpp, packages/xpetra/src/Map/Xpetra_MapFactory_decl.hpp, packages/xpetra/src/Map/Xpetra_Map_decl.hpp, packages/xpetra/src/Map/Xpetra_TpetraMap_decl.hpp, packages/xpetra/src/Map/Xpetra_TpetraMap_def.hpp, packages/xpetra/sup/StridedMap/Xpetra_StridedMap_decl.hpp, packages/xpetra/sup/StridedMap/Xpetra_StridedMap_def.hpp
Issue: #12273
Stakeholder feedback: Discussions with @cgcgcg
Tests: Serial and Cuda
=> Tpetra/Xpetra/MueLu: Fixes to allow MueLu::TentativePFactory_kokkos to not do coordinate map calculations on host

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
Do not allocate views associated to the Schur complements if the number of sublines per line is not at least 2.
=> Ifpack2: Do not allocate views associated to the Schur complements if the number of sublines per line is not at least 2

packages/PyTrilinos2/CMakeLists.txt, packages/PyTrilinos2/scripts/gather_includes.py
=> PyTrilinos2 : Fix the include logic broken since the creation of kokkos/algorithms/src/sorting

packages/seacas/libraries/chaco/util/chaco_random.h, packages/seacas/libraries/chaco/util/random.c
The previous change fixed the undefined behavior, but introduced an assertion failure.  Reverting the change until can look in more detail as to how best to fix the UB.
=> CHACO: Revert unsigned changes

packages/stokhos/src/sacado/kokkos/pce/Sacado_UQ_PCE_Imp.hpp
This should fix compiling and running the `Stokhos` tests using `SYCL`
=> Stokhos: Fix tests for SYCL

packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp
Add the option to pass the number of sublines per line inside a parameterlist
=> Ifpack2: Add the option to pass the number of sublines per line inside a parameterlist

packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp, packages/amesos2/test/adapters/Tpetra_CrsMatrix_Adapter_UnitTests.cpp, packages/amesos2/test/solvers/SolverFactory.cpp
This PR try fixing the issues encountered while linking with CUDA-enabled SuperLU_DIST.
Hopeful fix for [xSDK issue](https://github.com/xsdk-project/xsdk-issues/issues/235), @cgcgcg.
=> Amesos2 : CUDA-enabled Superlu_DIST

packages/framework/pr_tools/PullRequestLinuxDriverTest.py, packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py
I messed up the argparse declaration and then ignored what I kind of knew was a failure in the tests.  Fix it here.
User Support Ticket(s) or Story Referenced: TRILFRAME-607
=> Framework: Fix argument from bool -> string

packages/panzer/adapters-stk/src/Panzer_STK_WorksetFactory.cpp, packages/panzer/disc-fe/src/Panzer_AssemblyEngine_impl.hpp, packages/panzer/disc-fe/src/Panzer_FieldManagerBuilder.cpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherBasisCoordinates_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherIntegrationCoordinates_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp, packages/panzer/mini-em/example/BlockPrec/main.cpp, packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_SchurComplement_impl.hpp, packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_WeakGradient_impl.hpp
Updated some kernels to use team and mdrange policies
Added extra timers for assembly
assembly tests in mini-em exercise the modified kernels
=> Panzer: Assembly improvements

packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp
Factor coarse grid matrix during setup, not during the first solve.
=> MueLu Amesos2Smoother: Call numericFactorization during setup

packages/kokkos/core/src/Kokkos_HostSpace.hpp
Propagates the change from
https://github.com/kokkos/kokkos/pull/6653
=> Kokkos: Silence warning

packages/belos/tpetra/test/BlockCG/test_resolve_cg_hb.cpp
The unconditional output of "Number of iterations" is resulting in some test failures (#12628).  This is because the output stream from various processors is colliding with the output of the "Result: TEST PASSED" output.  So the test appears to fail.
OSX GCC 13.x serial / parallel
=> Belos: Adds conditional statement to "Number of iterations" unconditional output

packages/panzer/disc-fe/src/Panzer_VectorTemplateIterator.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherBasisCoordinates_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherIntegrationCoordinates_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp, packages/phalanx/src/Phalanx_TemplateIterator.hpp
cuda 12 compile errors and warnings
=> Panzer cuda 12 fixes

packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools_Metis.cpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools_Metis.hpp
This PR tries fixing the build issue with METIS when METIS is build with 64-bit integer
=> Tacho : fix build issue with Metis

.github/workflows/muelu_clang_format.yml
It will post a link to the patch file in a comment, so people can actually find it.
=> Workflow: Upgrade to MueLu Clang Formatter

cmake/tribits/core/std_tpls/FindTPLCUDA.cmake
This change is necessary to prevent linker errors in codes calling to Cuda Driver API routines
Compatibility update need for kokkos, see kokkos/kokkos#6693
@trilinos/tribits @bartlettroscoe
=> tribits: add CUDA::cuda_driver target in FindTPLCUDA.cmake

packages/teuchos/numerics/src/Teuchos_MatrixMarket_CoordDataReader.hpp, packages/teuchos/numerics/src/Teuchos_MatrixMarket_generic.hpp
Unused variables caught in Sierra builds.
=> Teuchos: remove unused variables in MatrixMarket utilities

packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C2_FEM.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_QUAD_C2_FEM.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_WEDGE_C2_FEM.hpp, packages/intrepid2/src/Projection/Intrepid2_LagrangianInterpolation.hpp, packages/intrepid2/src/Projection/Intrepid2_ProjectionStruct.hpp, packages/intrepid2/src/Projection/Intrepid2_ProjectionTools.hpp, packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefTensor.hpp
Fix compiler warning (no return statement) and finally remove the Experimental namespace used for projections
=> Intrepid2: remove Experimental namespace and fix warnings

packages/muelu/test/unit_tests_kokkos/Regression.cpp
Add another H2D regression test that specifically covers aggregation.
=> MueLu: Add H2D count for aggregation

packages/muelu/test/unit_tests_kokkos/LWGraph_kokkos.cpp
Fix compilation error on HIP #12691
=> MueLu LWGraph_kokkos unit test: Fix bug

packages/panzer/mini-em/example/BlockPrec/main.cpp, packages/teuchos/comm/src/Teuchos_StackedTimer.cpp, packages/teuchos/comm/src/Teuchos_StackedTimer.hpp, packages/teuchos/comm/test/StackedTimer/CMakeLists.txt, packages/teuchos/comm/test/StackedTimer/stacked_timer4.cpp
MiniEM needs to print a FOM for acceptance testing.
=> Teuchos/Panzer: add FOM in mini-em for acceptance testing

packages/muelu/utils/trilinos-clang-format
Alternative clang-format script
=> MueLu: Adding alternative clang-format script

cmake/std/atdm/van1-tx2/environment.sh
- Load correct CMake version for both arm-20 and arm-22
- For arm-22, most TPLs were removed from sparc-dev so load them manually.
Trilinos perf test build (which enables all the common TPLs) configs and builds cleanly with both arm-20 and arm-22 now.
This will also fix the nightly performance build (failed for the last 3 days)
=> Fix Stria (van1-tx2) ATDM environments

packages/tempus/examples/03_Intro_SolutionState/03_Intro_SolutionState.cpp, packages/tempus/src/Tempus_StepperNewmarkImplicitAForm_decl.hpp, packages/tempus/test/TestModels/SteadyQuadraticModel_decl.hpp
Fix a couple errors
- Duplicate section name
- Formatting issue caused by the recent clang-format changes
Get github.io doxygen running.
Passes local building of doxygen and ctests.
=> Tempus: Fix Doxygen Issues

packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp, packages/panzer/mini-em/example/BlockPrec/main.cpp, packages/panzer/mini-em/example/BlockPrec/maxwell-analyticSolution.xml
Check that the L2 error is below a set threshold when running the input deck with a known analytic solution.
=> Panzer MiniEM: Assert that error in analytic example is below threshold

packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp
Hopefully this will fix #12721.
=> MueLu UncoupledAggregationFactory: Kokkosify OnePt Map

packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp
=> Panzer: change access type for scatter

packages/tpetra/core/compat/Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.hpp
@csiefer2 
@ndellingwood 
Did not work and was removed in Kokkos develop
See https://github.com/kokkos/kokkos/pull/6791
=> Tpetra: Remove all references to `Kokkos::Experimental::HBWSpace`

packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools_Metis.cpp
Attempt to address issue #12743
Resolve compilation errors for case mentioned in #12743 
Confirmed code now compiles in local build; AT should test more broadly
=> tacho: modify how amd_order uses integral type to call trilinos_amd_*

packages/piro/src/Piro_ProductModelEval.hpp, packages/piro/test/Main_ThyraSolver_Tpetra.cpp
@trilinos/piro
Sensitivities were not computed when using the `ProductModelEvaluator` class. No errors were triggered because sensitivities tests are skipped when sensitivities are not computed.
This PR fixes the issue and add checks to ThyraSolver test to error out if sensitivities are not computed.
Note, hessian-vec products are also not computed and need to be fixed in a subsequent PR.
This PR fixes the computation of sensitivities in Albany
It Passes Piro tests and Albany tests
=> Piro: Fix ProductModelEvaluator

packages/panzer/disc-fe/src/Panzer_IntegrationValues2.hpp, packages/panzer/disc-fe/src/Panzer_IntrepidOrientation.cpp, packages/panzer/disc-fe/src/Panzer_L2Projection.cpp, packages/panzer/disc-fe/src/Panzer_L2Projection.hpp
Improve performance of mass matrix assembly tools for vector bases
=> Panzer: vector basis mass matrix

packages/kokkos-kernels/example/wiki/sparse/KokkosSparse_wiki_bsrmatrix.cpp
@trilinos/KokkosKernels
Minor fix for a missing inclusion when building with 
`KokkosKernels_ENABLE_EXPERIMENTAL=ON`
Follows from KokkosKernels PR: https://github.com/kokkos/kokkos-kernels/pull/2113
=> KokkosKernels: Adding iostream include statement to source file

packages/framework/ini-files/config-specs.ini
Want to use up-to-date options to enable UVM.
#12622
There will be build errors in Stokhos and MueLu.  This will allow MueLu and Stokhos developers to work on these issues prior to adding a PR build.
=> Framework: UVM updates

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
Let's see if this passes the AT...
=> Tpetra: Fix fillComplete in matrix addition

packages/muelu/test/unit_tests/Utilities.cpp
This test relied on the fact that Epetra and Tpetra would generate the same random numbers. This seems to have diverged at some point. Instead of trying to fix it, let's just copy the data from one to the other.
=> MueLu: Fix EpetraVsTpetra test

packages/teko/src/Teko_Utilities.cpp, packages/teko/tests/src/tExplicitOps_tpetra.cpp, packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp
@trilinos/tpetra @trilinos/teko 
- Tpetra: Add a test that catches the issue fixed in #12765.
- Teko: Add a test that reproduces an issue in `explicitAdd` found in EMPIRE for aliased arguments.
- Teko: Fix the issue in `explicitAdd`.
=> Tpetra, Teko: SpAdd issues

RELEASE_NOTES
@trilinos/framework @trilinos/amesos2 @trilinos/ifpack2 @trilinos/kokkos-kernels @trilinos/muelu @trilinos/panzer @trilinos/pytrilinos2 @trilinos/rol @trilinos/teko @trilinos/tpetra 
If I missed something that should be mentioned, please feel free to add.
=> Add draft of release notes for 15.1

RELEASE_NOTES
Add links to relevant PRs to release notes.
=> Add URLs to release notes

packages/framework/ini-files/config-specs.ini
Adding a build-only UVM CUDA line for Albany.
=> Framework: Add PR UVM build config

packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
Possible fix for https://github.com/trilinos/Trilinos/issues/12773
=> Tpetra_Details_Behavior.cpp: add missing <array> include

RELEASE_NOTES, Version.cmake
Updating version strings of develop branch to `15.2.0-dev` after `15.1.0` release.
- #12776 
**^^ DO NOT MERGE THIS PR BEFORE ABOVE IS MERGED AND THE RELEASE IS FINALIZED**
- [TRILFRAME-618](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-618)
=> Framework: Post 15.1.0 version update

packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp
@trilinos/stratimikos 
`MvTimesMatAddMv` computes $V := \alpha AB + \beta v$ where $\alpha$ and $\beta$ are scalars, $A$ and $V$ are multivectors and $B$ is a dense matrix. 
For the case that $B$ is 1x1 we can compute $V := (\alpha B_{0,0}) A + \beta V$ instead.
This mirrors what is done for the Belos-Tpetra adapter.
=> Stratimikos Belos adapter: Handle special case for MvTimesMatAddMv

Version.cmake
Update version on 15.1 branch to 15.1.1
=> Framework: Update to version 15.1.1

packages/ifpack2/test/belos/CMakeLists.txt, packages/muelu/test/interface/CMakeLists.txt, packages/muelu/test/maxwell/CMakeLists.txt
Some tests failed with Zoltan2Core=OFF due to missing dependency checks.
See
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=60137
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=60543
=> Ifpack2&MueLu: Add missing dependency checks

packages/framework/ini-files/config-specs.ini
This updates the containerized build for the new github actions gcc 10.3 openmpi 4.1.6 environment
=> Framework: updated container gcc openmpi build for github

packages/muelu/test/unit_tests_kokkos/Regression.cpp
=> MueLu DeepCopy Regression test: Set counts for UVM

packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/environment-specs.ini, packages/framework/ini-files/supported-envs.ini
Include an environment configuration entry that works with the AUE containerized environment. This will be used to make sure Trilinos' works in those containerized environments.
- [TRILFRAME-622](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-622)
- Confirmed working via s Trilinos Nightly build using this genconfig entry inside an AUE container
=> Framework: AUE environment genconfig entry

packages/muelu/test/unit_tests/ParameterList/ParameterListInterpreter/BlockCrs1.xml, packages/muelu/test/unit_tests/ParameterList/ParameterListInterpreter/BlockCrs2.xml, packages/muelu/test/unit_tests/Regression.cpp, packages/muelu/test/unit_tests_kokkos/Regression.cpp
Set counts for the non-Kokkos code path as well....
=> MueLu: Set counts for Regression test

.github/workflows/title_to_mention.yml
=> Github Action: Automatically mention ROL team on ROL issues

packages/seacas/libraries/ioss/cmake/Dependencies.cmake
Updated the test in the dependencies to work with projects the build Trilinos internally such that the PROJECT_NAME is not Trilinos.  Did the logical thing of searching for project name == Seacas...
=> SEACAS: Fix fmt dependencie for Trlinos

packages/kokkos-kernels/lapack/tpls/KokkosLapack_svd_tpl_spec_decl.hpp
Snapshot of kokkos-kernels.git from commit 7eb49945cc93d28437bd1d6eb7…da418ad87678ed
From repository at git@github.com:kokkos/kokkos-kernels.git
At commit:
commit 7eb49945cc93d28437bd1d6eb7da418ad87678ed
Author: Nathan Ellingwood <ndellin@sandia.gov>
Date:   Fri Apr 5 13:06:34 2024 -0600
KokkosLapack_svd_tpl_spec_decl: defer to MKL spec when LAPACK also enabled
Resolves redefintion of struct SVD compilation errors with both MKL and LAPACK are enabled
Reported by @maartenarnst in https://github.com/trilinos/Trilinos/issues/12891
Co-authored-by: brian-kelley <brian.honda11@gmail.com>
(cherry picked from commit 5bf5474dcc02d7c9cd25e9c9adb377c7c62a49fc)
Resolve compilation errors when enabling MKL and LAPACK TPLs, as reported in #12891
Reproduced issue in a local …
=> kokkos-kernel: fix compilation errors in builds enabling MKL and LAPACK TPLs simultaneously

packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
Recent changes broke UVM build
Closes #12900 
N/A
=> Panzer: fix basis values for uvm

packages/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_avail.hpp
Patch created from kokkos/kokkos-kernels#2176
Add guard for cusparse spmv_mv_tpl_spec_avail
Addresses linker errors for builds with magma enabled and cusparse disabled
Patch to fix issue https://github.com/kokkos/kokkos-kernels/issues/2175
@glhenni and @vqd8a 
Confirmed fix in a local build for https://github.com/kokkos/kokkos-kernels/issues/2175
=> kokkos-kernels: apply patch fix for magma

packages/panzer/adapters-stk/example/main_driver/energy-ss-tp.xml, packages/panzer/adapters-stk/example/main_driver/main_driver.cpp, packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgVector_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_CellExtreme_impl.hpp, packages/panzer/disc-fe/src/responses/Panzer_ResponseScatterEvaluator_ExtremeValue_impl.hpp
Some responses were never updated for UVM removal. These are now fixed and tests added as needed.
Test was added to cover the CellAverageVector. A test for CellExtremeValue will be added once #12310  is merged.
=> Panzer: response updates for cuda

packages/stk/CHANGELOG.md, packages/stk/stk_integration_tests/cmake_install_test/build_stk_user_facing, packages/stk/stk_search/stk_search/CMakeLists.txt, packages/stk/stk_util/stk_util/Version.hpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp
@trilinos/stk
Fixing broken stk_search install targets
=> STK: Snapshot 04-22-24 10:53 from Sierra 5.19.2-926-gd0a856d5

packages/nox/src-thyra/NOX_Observer_ReusePreconditioner.cpp, packages/nox/src-thyra/NOX_Observer_ReusePreconditioner.hpp, packages/nox/src-thyra/NOX_Observer_ReusePreconditionerFactory.cpp, packages/nox/src-thyra/NOX_Observer_ReusePreconditionerFactory.hpp, packages/nox/src-thyra/NOX_Thyra_Group.C, packages/nox/src-thyra/NOX_Thyra_Group.H, packages/nox/src/CMakeLists.txt, packages/nox/test/tpetra/Tpetra_1DFEM.cpp, packages/panzer/adapters-stk/example/main_driver/CMakeLists.txt, packages/panzer/adapters-stk/example/main_driver/energy-ss-tp-delay-prec.xml, packages/panzer/adapters-stk/example/main_driver/main_driver.cpp, packages/panzer/adapters-stk/example/main_driver/user_app_NOXObserverFactory.hpp, packages/panzer/disc-fe/test/closure_model/CMakeLists.txt, packages/panzer/disc-fe/test/closure_model/user_app_ClosureModel_Factory_impl.hpp, packages/panzer/disc-fe/test/closure_model/user_app_TSquaredModel.hpp, packages/panzer/disc-fe/test/closure_model/user_app_TSquaredModel_impl.hpp, packages/panzer/dof-mgr/test/fe_assembly/test_fe_projection.hpp, packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
Applications would like to reuse a preconditioner across nonlinear iterations and across time steps. This PR adds a nox observer that controls when to update the preconditioner with new matrix values. New tests are in nox and this capability has been added to the panzer main driver example.
nox 1dfem unit tests and panzer main driver delay prec example
=> Nox preconditioner reuse

packages/kokkos-kernels/blas/tpls/KokkosBlas2_syr2_tpl_spec_decl_blas.hpp, packages/kokkos-kernels/blas/tpls/KokkosBlas2_syr_tpl_spec_decl_blas.hpp, packages/kokkos-kernels/blas/tpls/KokkosBlas_Host_tpl.cpp, packages/kokkos-kernels/blas/tpls/KokkosBlas_Host_tpl.hpp
Fix for https://github.com/trilinos/Trilinos/issues/12962
@ndellingwood Mind looking at this MR (or adding someone else)? Thanks!
=> Kokkos-kernels Resolve compilation error pertaining to cher, zher, cher2, and zher2 usage

packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/main.cpp
=> FROSch: Adding watchr output support for perf test

packages/teuchos/parameterlist/src/Teuchos_ParameterList.cpp, packages/teuchos/parameterlist/test/ParameterList/ParameterList_UnitTests.cpp
https://github.com/trilinos/Trilinos/issues/12968
There is a new test called `modify_CopiesModifiers` in ParameterList_UnitTests.cpp.
=> Recursively copy modifiers to the users parameter list.

packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools_Metis.cpp
…not be resolved
@trilinos/Tacho
@iyamazaki 
Build broken on ARM/macOS. Would be nice to catch this with a CI build/test config on the Trilinos side...
<!---
If applicable, let us know how this merge request is related to any other open
issues or pull requests:
=> Tacho: fix missing constexpr in amd_order usage

packages/seacas/applications/slice/Slice.C
Change requested by sparc to make it easier to spawn the `slice` code until IOSS provides the needed line decomposition support.
=> SLICE: Make easier for sparc to spawn slice

packages/teko/src/NS/Teko_SIMPLEPreconditionerFactory.cpp, packages/teko/src/NS/Teko_SIMPLEPreconditionerFactory.hpp, packages/teko/tests/src/tSIMPLEPreconditionerFactory_tpetra.cpp, packages/teko/tests/src/tSIMPLEPreconditionerFactory_tpetra.hpp
@trilinos/teko
@cgcgcg
Similar to https://github.com/trilinos/Trilinos/pull/12675
=> Teko: Add ability to use preconditioned sub-solves in Teko NS SIMPLE

packages/ifpack2/example/BlockTriDi.cpp
This PR reorganizes the timers of the Ifpack2 BlockTriDi driver to reduce the portion of the remainder timer of the nightly perf test.
This is done by postposing the construction of `stackedTimer` to be just before the region of interest of the code and by adding a `Norm` timer.
Extra timers have been added as well that are only reported when running without `useStackedTimer`.
=> Ifpack2: Add timers for potentially costly regions of the driver

packages/intrepid2/src/Shared/Intrepid2_Data.hpp, packages/intrepid2/unit-test/MonolithicExecutable/DataTests.cpp
This adds support for taking the transpose when performing a mat-vec using Intrepid2::Data objects.
The motivating use case is from Camellia, where we are using Intrepid2's sum factorization support, and want to compute the dot product of a vector containing known data with gradient of an Intrepid2 basis function; the natural/efficient way to do this is to incorporate the vector data into the basis transformation, by multiplying the vector transpose times the Jacobian matrix.  This is equivalent to multiplying the transpose of the matrix by the vector, which is what we support in this PR.
We have added a test to `DataTests.cpp` which exercises a rank-4 mat-vec use case similar to the one in Camellia.
=> Intrepid2: add support to Data for taking the transpose of a matrix when performing a mat-vec.

.github/PULL_REQUEST_TEMPLATE.md
Clarify the instructions in the comments.  (I didn't know PRs could be added to release notes.)
Make "related issue" part of the body rather than in a comment.
N/A
N/A
=> Clarify PR template

packages/teko/src/NS/Teko_SIMPLEPreconditionerFactory.cpp, packages/teko/tests/src/tSIMPLEPreconditionerFactory_tpetra.cpp
=> Teko: Fix clang-format

packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
This is an optimization to bypass a launch-latency bound interface in Intrepid2. Currently, if Intrepid2 is passed a cell indexed array for `Intrepid2::CellTools::setJacobian` or `Intrepid2::CellTools::mapToPhysicalFrame` it will run a separate `Intrepid2::Basis::getValues` call per cell. For large cell counts this becomes very slow as millions of (GPU) kernel launches stack up one after the other.
To get around this we introduced a new path for when uniform points are an option. This is not available for CV and Surface integration schemes.
@rppawlo This is an alternative to the Intrepid2 changes I was making (see https://github.com/seanofthemillers/Trilinos/tree/intrepid2_parallel_getValues). I'm currently seeing a 200x speedup in workset generation in MiniEM with HIP …
=> Panzer: IntegrationValues2 optimization

packages/belos/doc/DoxyfileWeb, packages/belos/epetra/example/BlockGmres/BlockGmresEpetraGaleriEx.cpp, packages/belos/epetra/example/BlockGmres/BlockPrecGmresEpetraGaleriEx.cpp, packages/belos/src/BelosBiCGStabSolMgr.hpp, packages/belos/src/BelosBlockCGSolMgr.hpp, packages/belos/src/BelosBlockGmresSolMgr.hpp, packages/belos/src/BelosGCRODRSolMgr.hpp, packages/belos/src/BelosGmresPolySolMgr.hpp, packages/belos/src/BelosLSQRStatusTest.hpp, packages/belos/src/BelosPCPGSolMgr.hpp, packages/belos/src/BelosPseudoBlockCGSolMgr.hpp, packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp, packages/belos/src/BelosPseudoBlockTFQMRSolMgr.hpp, packages/belos/src/BelosRCGSolMgr.hpp, packages/belos/src/BelosTFQMRSolMgr.hpp, packages/belos/tpetra/example/BlockGmres/BlockGmresTpetraGaleriEx.cpp
A user commented on #6370 about where to get tutorial information.  The Doxygen examples are useful for illustrating how to use the Belos solvers and can serve as tutorial material.  In review, it was noticed that the Tpetra examples are not being picked up by the Doxygen documentation for Belos, so that is being corrected.
No testing, this is documentation.
=> Belos:  Fix Doxygen documentation to include Tpetra examples

packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/supported-envs.ini
Adds a spec in config-specs.ini for a new build we are going to use as the first non blocking PR build
https://sems-atlassian-son.sandia.gov/jira/secure/RapidBoard.jspa?rapidView=164&projectKey=TRILFRAME&view=detail&selectedIssue=TRILFRAME-625
=> Framework: Gcc8 sems v2 pr build

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Issue: #13037 
Stakeholder feedback: @ikalash 
Tests: n/a
=> Tpetra: Fixing  #13037

.github/workflows/clang_format.yml
Should fix the permission problem
=> Actions: Update clang_format.yml

packages/muelu/src/Operators/MueLu_MultiPhys_def.hpp
@trilinos/MueLu
@rstumin  
@jhux2
=> MueLu: Minor Tweaks to MultiPhys

.github/workflows/clang_format.yml
Going to fix clang for real this time
=> Actions: Pull Requests are Issues... Except when they aren't

packages/ifpack2/src/Ifpack2_RILUK_decl.hpp
=> Ifpack2: Tiny fix for extra tokens at end of #endif directive

packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/supported-envs.ini
This build is to be added as a non-blocking PR test to test its stability on RHEL8 machines. 
- #13070 
- #13067 
- #13074
- [TRILFRAME-647](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-647)
Locally built and tested this build on a RHEL8 machine.
=> Framework: Add RHEL8 GCC OpenMPI configuration

packages/teko/src/Teko_BlockLowerTriInverseOp.cpp, packages/teko/src/Teko_BlockLowerTriInverseOp.hpp, packages/teko/src/Teko_BlockUpperTriInverseOp.cpp, packages/teko/src/Teko_BlockUpperTriInverseOp.hpp, packages/teko/src/Teko_HierarchicalGaussSeidelPreconditionerFactory.cpp, packages/teko/src/Teko_HierarchicalGaussSeidelPreconditionerFactory.hpp, packages/teko/tests/src/tSIMPLEPreconditionerFactory_tpetra.cpp
=> Teko: Add sub-solve capability in hierarchical Block Gauss-Seidel

RELEASE_NOTES
List additional changes in release notes.
=> Additions to release notes

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp
Fixes #13076
Replicated on an Intel based mac with apple clang, and checked that this fixes this error:
```
[ 86%] Linking CXX shared library libifpack2.dylib
Undefined symbols for architecture x86_64:
"Teuchos::RCP<Tpetra::CrsGraph<int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > > Tpetra::getBlockCrsGraph<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Tpetra::CrsMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, int const&, bool)", referenced from:
Ifpack2::BlockRelaxation<Tpetra::RowMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, …
```
=> Tpetra: add getBlockCrsGraph free function to ETI

packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp, packages/ifpack2/src/Ifpack2_RILUK_decl.hpp
makeLocalFilter was copy-pasted verbatim from RILUK (private static member) to RBILUK_def (free function). #13118 was because this also caused ambiguous name lookup.
Instead, just make the function public static in RILUK so that it can replace all usages of the copy in RBILUK.
Verified the fix on ascicgpu
* Closes #13118
=> Ifpack2: Fix #13118 and cleanup copy-pasted function

packages/anasazi/src/AnasaziMVOPTester.hpp, packages/belos/src/BelosMVOPTester.hpp, packages/thyra/core/test/operator_vector/DefaultProductVectorSpace_UnitTests.cpp, packages/thyra/core/test/operator_vector/DefaultSpmdMultiVector_UnitTests.cpp
@trilinos/thyra @trilinos/belos @trilinos/anasazi 
Minor changes to Thyra, Belos, Anasazi unit tests that were flagged by Valgrind:
https://sems-cdash-son.sandia.gov/cdash/viewDynamicAnalysis.php?buildid=88114
https://sems-cdash-son.sandia.gov/cdash/viewDynamicAnalysis.php?buildid=88098
https://sems-cdash-son.sandia.gov/cdash/viewDynamicAnalysis.php?buildid=88099
=> Thyra,Belos,Anasazi: Fix valgrind findings

packages/epetra/ReleaseNotes.txt
The release notes had some garbage "hidden" characters.
=> Epetra: Garbage Characters

packages/ifpack2/src/Ifpack2_Parameters.cpp
Closes https://github.com/trilinos/Trilinos/issues/13136 (for now).
I have not exhaustively checked if we are missing any other parameters.
=> Add missing parameters in `Ifpack2::getValidParameters()`

packages/seacas/libraries/ioss/src/Ioss_Field.h, packages/seacas/libraries/ioss/src/Ioss_Utils.C
Remove use of `fmt` include file in installed ioss include file -- can only currently use fmt internally in seacas due to use of embedded fmt library instead of fmt as a TPL.
* Closes #13134
=> IOSS: Remove use of fmt in installed header

packages/seacas/libraries/ioss/src/Ioss_Region.h
REmove hopefully the last include of a fmt header in a public seacas include file.
* Closes #13155
=> IOSS: Fix another include of fmt header

packages/teuchos/comm/src/Teuchos_StackedTimer.hpp, packages/teuchos/core/src/Teuchos_Time.cpp
compatibility update with kokkos/kokkos#7096
avoid "conflicts with a previous declaration" errors and undefined linker issues
@trilinos/teuchos @bartlettroscoe 
compatibility update with kokkos/kokkos#7096
avoid "conflicts with a previous declaration" and undefined linker issues
* Closes kokkos/kokkos#7101
Local build with kokkos/kokkos@53b3202
=> teuchos: rename namespace Profiling->Tools for kokkos-tools

packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
@trilinos/Panzer
Right now `IntegrationValues2::evaluateEverything` is recomputing the Jacobian many times, when it should only be computed once. These changes are meant to fix the issue.
=> Panzer: Remove extensive recomputing of Jacobian from IntegrationValues2

packages/teko/src/Teko_DiagnosticPreconditionerFactory.cpp, packages/teko/src/Teko_DiagnosticPreconditionerFactory.hpp, packages/teko/tests/unit_tests/tDiagnosticLinearOp.cpp
This allows usage of preconditioned iterative solves within diagnostic blocks.
=> Teko: Add preconditioned iterative solves to diagnostic preconditioner factory

packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
This PR fixes the Tacho build issue with CUDA12 (`CUSPARSE_MV_ALG_DEFAULT` has been replaced with `CUSPARSE_SPMV_ALG_DEFAULT`).
@crdohrm 
Tested on Vortex with CUDA 11.2 and CUDA 12.
=> Tacho : support for CUDA 12

packages/belos/src/BelosLinearProblem.hpp, packages/ifpack2/src/Ifpack2_AdditiveSchwarz_decl.hpp, packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp, packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp, packages/ifpack2/src/Ifpack2_RILUK_decl.hpp, packages/ifpack2/src/Ifpack2_RILUK_def.hpp
=> Belos + Ifpack2 performance improvements and fix #13098

packages/ifpack2/example/BlockTriDi.cpp
Add the option to skip the reading of the line file to use block Jacobi instead of block TD
=> Ifpack2: add an option to skip the reading of the line file

packages/tpetra/core/src/Tpetra_FECrsMatrix_decl.hpp
Issue: #13189
Tests: n/a
Stakholder feedback: @avfav1235
=> Tpetra: Fixing Doxygen for FECrsMatrix

packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
With this PR, CuSparse CSR is re-created for each SpMV/SpMM call.
Tested on H100 and V100.
This seems to have been causing on H100 (the performance impact seems to be small enough, at least for our test matrix).
=> Tacho : Re-create CuSparse CSR for each SpMV/SpMM call

packages/amesos/src/Amesos.cpp, packages/amesos/src/Amesos_CssMKL.cpp, packages/amesos/src/Amesos_CssMKL.h, packages/amesos/test/Test_Detailed/cxx_main.cpp
@trilinos/amesos
This PR adds ``Amesos::Create`` interface to CSS MKL
Added CSS MKL to ``Test_Detailed``
=> Amesos : add Amesos::Create interface to CSS MKL

packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
If a user specifies:
```
IOSS_PROPERTIES="OUTPUT_FIELD_METADATA=NO"
```
Then the enhanced field metadata will not be written to the output file.  This can workaround a bug found in Paraview for certain instances where the metadata causes an issue reading the file.
@tcfisher 
=> IOSS: Add property to control enhanced field metadata output

packages/ifpack2/src/Ifpack2_Hypre_def.hpp, packages/muelu/test/scaling/CMakeLists.txt, packages/muelu/test/scaling/MatvecKernelDriver.cpp
Sets up matvec performance test.
=> MueLu: Set up matvec performance test

packages/teuchos/parameterlist/src/Teuchos_ValidatorMaps.hpp, packages/thyra/core/src/support/operator_vector/client_support/Thyra_describeLinearOp_def.hpp
@trilinos/teuchos @trilinos/thyra
Fix includes of headers into themselves.
=> Teuchos & Thyra: Include fixes

packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp
Because every-rank-output of the same message is evil.
Issue: #12935 
Test: This
Stakeholder feedback: See pending approval by @cgcgcg
=> Tpetra: Restricting test output to rank-0

packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C
This unused variable is causing some builds that require warning-free compiles to fail.
=> Eliminate Unused variable

packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp
* Closes #13259
Albany reported warning-free build broken
=> Ifpack2: fix sign compare warning (#13259)

Version.cmake
Update Version.cmake for Trilinos 16.0 Release.
=> Framework: update Version.cmake for Trilinos 16.0.0

Version.cmake
=> Framework: update Version.cmake for dev branch

packages/muelu/example/basic/set1-cg.xml, packages/muelu/example/basic/set1-gmres.xml, packages/muelu/example/basic/set2-sgs1.xml, packages/muelu/example/basic/set2-sgs3.xml, packages/muelu/example/basic/set3-mg-mtgs.xml, packages/muelu/example/basic/set3-mg-mtsgs.xml
@cgcgcg
Sync of MueLu's examples/basic for the ATPESC 2024 track 5 hands-on demonstration
=> MueLu: Update ATPESC input decks

packages/muelu/example/basic/Simple.cpp, packages/muelu/test/scaling/Driver.cpp, packages/muelu/test/scaling/DriverCore.hpp
=> MueLu: Add option to compute eigenvalue and condition number estimates to Driver

packages/ifpack2/src/Ifpack2_RILUK_def.hpp, packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
@trilinos/tpetra @trilinos/ifpack2
=> Tpetra&Ifpack2: Silence warnings

packages/tpetra/core/test/CrsMatrix/CMakeLists.txt, packages/tpetra/core/test/CrsMatrix/CrsMatrix_MatvecFence.cpp
Just so we know where we are....
=> Tpetra: Add test that counts fences in matvec

packages/phalanx/example/FiniteElementAssembly/PrintValues.hpp, packages/phalanx/example/FiniteElementAssembly/auxiliary_tests/Example_FEM_LinearObjectFactory_AuxTest.cpp, packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp, packages/phalanx/test/Kokkos/tKokkos.cpp, packages/phalanx/test/Kokkos/tKokkosViewOfViews.cpp, packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
Testing against kokkos develop (will be the upcoming 4.4 release) found hangs in ViewOfViews. Needed to fix the copy ctors and assignment ops. 
Fixes #13281
Tests are now passing with kokkos 4.4. Added a few new tests to cover more use cases.
=> Phalanx: fixes for kokkos release 4.4

packages/sacado/test/performance/fenl_assembly/BoxElemFixture.hpp, packages/sacado/test/performance/fenl_assembly/BoxElemPart.cpp, packages/sacado/test/performance/fenl_assembly/BoxElemPart.hpp, packages/sacado/test/performance/fenl_assembly/HexElement.hpp, packages/sacado/test/performance/fenl_assembly/fenl_functors.hpp, packages/sacado/test/performance/fenl_assembly_view/BoxElemFixture.hpp, packages/sacado/test/performance/fenl_assembly_view/BoxElemPart.cpp, packages/sacado/test/performance/fenl_assembly_view/BoxElemPart.hpp, packages/sacado/test/performance/fenl_assembly_view/HexElement.hpp, packages/sacado/test/performance/fenl_assembly_view/fenl_functors.hpp
=> Sacado: Update Kokkos File Headers

packages/stokhos/test/Performance/FadMPAssembly/BoxElemFixture.hpp, packages/stokhos/test/Performance/FadMPAssembly/BoxElemPart.cpp, packages/stokhos/test/Performance/FadMPAssembly/BoxElemPart.hpp, packages/stokhos/test/Performance/FadMPAssembly/HexElement.hpp, packages/stokhos/test/Performance/FadMPAssembly/VectorImport.hpp, packages/stokhos/test/Performance/FadMPAssembly/fenl_functors.hpp, packages/stokhos/test/Performance/MPAssembly/BoxElemFixture.hpp, packages/stokhos/test/Performance/MPAssembly/BoxElemPart.cpp, packages/stokhos/test/Performance/MPAssembly/BoxElemPart.hpp, packages/stokhos/test/Performance/MPAssembly/HexElement.hpp, packages/stokhos/test/Performance/MPAssembly/VectorImport.hpp, packages/stokhos/test/Performance/MPAssembly/fenl_functors.hpp
=> Stokhos: Update Kokkos File Headers

packages/teuchos/kokkoscomm/src/Kokkos_MpiTypeTraits.hpp, packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp, packages/teuchos/kokkoscompat/src/KokkosCompat_TMM.hpp, packages/teuchos/kokkoscompat/src/KokkosCompat_View.cpp, packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp, packages/teuchos/kokkoscompat/src/KokkosCompat_View_def.hpp, packages/teuchos/kokkoscompat/test/linkTest.cpp
=> Teuchos: Update Kokkos File Headers

packages/adelus/src/Adelus_solve.hpp
This PR is to fix the reported unstable pipelined communication issue in the back solve. It is now changed to broadcasting current column per iteration instead.
The Gemma team has confirmed this fixes the issue.
=> Adelus: Fix unstable commnication pattern in back solve

packages/tpetra/core/ext/CMakeLists.txt
Issue: #12935
Tests: n/a
Stakeholder feedback: As the stakeholder, I approve.
=> Tpetra: Fixing cmake logic error

packages/muelu/test/unit_tests/Regression.cpp, packages/muelu/test/unit_tests_kokkos/Regression.cpp
#13310, but I haven't verified yet that that fixes the issue.
=> MueLu: Fix regression test logic

packages/krino/krino/unit_tests/CMakeLists.txt, packages/stk/stk_doc_tests/stk_mesh/CMakeLists.txt, packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
=> STK: Interim update to turn off flaky test

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp, packages/pamgen/test/rtc_test/rtcompiler-test.cc, packages/panzer/adapters-stk/test/interpolation/interpolation.cpp, packages/panzer/disc-fe/src/Panzer_Interpolation.cpp, packages/panzer/dof-mgr/src/Panzer_GlobalIndexer.hpp, packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DynRankView.cpp, packages/trilinoscouplings/examples/scaling/example_CVFEM.cpp
@trilinos/muelu @trilinos/panzer @trilinos/trilinoscouplings @trilinos/pamgen 
See #13308.
=> MueLu, Panzer, TrilinosCouplings, Pamgen: Fix warnings

packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
Fix another use of space accessibility
=> Phalanx: another use of space accessibility

packages/tpetra/core/test/CrsMatrix/CrsMatrix_MatvecFence.cpp
This PR fixes Trilinos issue #13292.
=> Fix: Trilinos issue #13292

packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
Use TACHO_HAVE_CUSPARSE in addition to KOKKOS_ENABLE_CUDA at cusparse handle destruction
Match guarding with the handle creation
Fix compilation issue when Cuda is enabled but Cusparse is not enabled
Confirmed in local build that compilation errors were resolved
=> tacho: match macro names at construction/destruction of handles

packages/ifpack2/src/Ifpack2_BlockComputeResidualVector.hpp, packages/ifpack2/src/Ifpack2_BlockHelper.hpp, packages/ifpack2/src/Ifpack2_BlockHelper_Timers.hpp, packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_decl.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp
This PR adds extra (optional) timers and fences to the Ifpack2 BTD solvers and add a parallel implementation of the Tpetra function createMeshMap.
=> Ifpack2 (and Tpetra): refined timers and parallel createMeshMap

packages/teko/src/CMakeLists.txt, packages/teko/src/Teko_DiagonalPreconditionerFactory.cpp, packages/teko/src/Teko_PreconditionerFactory.cpp
Build diagonal preconditioner when Epetra=OFF.
=> Teko: Build DiagonalPreconditionerFactory for Tpetra

packages/panzer/adapters-stk/example/main_driver/CMakeLists.txt, packages/panzer/adapters-stk/example/main_driver/energy-ss-point-calc.xml, packages/panzer/adapters-stk/example/main_driver/main_driver.cpp, packages/panzer/disc-fe/src/responses/Panzer_ResponseScatterEvaluator_Probe.hpp, packages/panzer/disc-fe/src/responses/Panzer_ResponseScatterEvaluator_Probe_impl.hpp
Recovers the old point evaluator, gets it running on cuda and adds unit tests.
main driver now has a test for this evaluator
=> Panzer: add point evaluator

packages/teko/src/Teko_DiagonalPreconditionerFactory.cpp
=> Teko: Silence warning

packages/muelu/test/unit_tests_kokkos/CoalesceDropFactory_kokkos.cpp
=> MueLu: Fix CoalesceDropFactory_kokkos unit test w/ Cuda UVM

packages/framework/ini-files/config-specs.ini
Let's see if this passes the AT..
=> Framework: Remove package exceptions for warnings-as-errors

packages/teko/src/Teko_BlockDiagonalInverseOp.cpp, packages/teko/src/Teko_BlockDiagonalInverseOp.hpp, packages/teko/src/Teko_JacobiPreconditionerFactory.cpp
This is required as ifpack2::relaxation preconditioners do not support beta != 0.
=> Teko: Use implicit operator for Block Jacobi

packages/tpetra/core/src/Tpetra_Import_Util2.hpp
Fix for https://github.com/trilinos/Trilinos/issues/13373
=> Tpetra: missing fence in lowCommunicationMakeColMapAndReindex

packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.C
A change to seacas prior to the latest snapshot into Trilinos broke the serialized_io case in which only a subset of the ranks can do I/O at one time.  If there is a global collective call inside the section in which serialized io is active, then there will be a hang or exception. 
Fixed this case and verified that it is no longer throwing the exception.
* Closes #13389
=> IOSS: Fix serialize io issue in timestep query

packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp, packages/sacado/src/Kokkos_LayoutContiguous.hpp, packages/sacado/src/Kokkos_LayoutNatural.hpp
Kokkos compatibility update following https://github.com/kokkos/kokkos/pull/7256
@trilinos/sacado @etphipp 
Compatibility update to resolve compilation issues with kokkos@develop (post-4.4.00) branch
=> sacado: update Kokkos_ViewMapping.hpp location

packages/intrepid2/src/Cell/Intrepid2_CellData.hpp, packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp, packages/intrepid2/src/Cell/Intrepid2_CellTools.hpp, packages/intrepid2/src/Cell/Intrepid2_CellToolsDefInclusion.hpp, packages/intrepid2/src/Discretization/Integration/Intrepid2_IntegrationToolsDef.hpp, packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp, packages/intrepid2/src/Shared/Intrepid2_Types.hpp, packages/intrepid2/src/Shared/Intrepid2_Utils.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_ViewStorage.hpp
This PR fixes potential issue with Intrepid2 inclusion tests when the points are not of double type. See discussion in PR #13385 (thanks @MalachiTimothyPhillips for pointing this out).
This PR should also fix code that is deprecated in c++20 standard (Issue #12786).
* Closes #12786
=> Intrepid2: fix C++20 deprecated code and potenttial type mismatch issue

packages/phalanx/test/DagManager/DagManagerTest.cpp, packages/phalanx/test/EvaluatorMacros/EvaluatorMacrosTest.cpp, packages/phalanx/test/EvaluatorMacros/EvaluatorWithMacros.hpp, packages/phalanx/test/EvaluatorMacros/EvaluatorWithMacros_Def.hpp, packages/phalanx/test/Utilities/Evaluator_MockDAG.hpp, packages/phalanx/test/Utilities/Evaluator_MockDAG_Def.hpp, packages/rtop/src/support/RTOpPack_SPMD_apply_op_decl.hpp
=> RTOps,Phalanx: fixes for cpp20

packages/seacas/applications/epu/epu.C, packages/seacas/applications/exodiff/edge_block.C, packages/seacas/applications/exodiff/exo_block.C, packages/seacas/applications/exodiff/face_block.C, packages/seacas/applications/nem_spread/pe_input.C, packages/seacas/libraries/ioss/src/Ioss_DecompositionUtils.C, packages/seacas/libraries/ioss/src/Ioss_DynamicTopology.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.C, packages/seacas/libraries/ioss/src/main/cgns_decomp.C, packages/seacas/libraries/ioss/src/visualization/cgns/Iovs_cgns_DatabaseIO.C, packages/seacas/libraries/suplib_cpp/iqsort.C
This should allow building seacas using a c++20 compiler.  Verified on CEE and Mac
=> Changes for building with c++20

packages/tpetra/core/test/CrsMatrix/CrsMatrix_MatvecFence.cpp
Modify the expected instance counts for OpenMP in CrsMatrix_MatvecFence.cpp Compatibility update for KOKKOS_VERSION >= 40499, corresponding to https://github.com/kokkos/kokkos/pull/7245
Update test to pass with kokkos@develop in OpenMP build
Local testing with gcc/8.5.0 and OpenMP + Serial backends enabled to confirm test passes
=> tpetra: modify expected instance fence counts in MatvecFence

.github/workflows/clang_format.yml
Bring DoozyX/clang-format in line with kokkos.
@trilinos/framework @ndellingwood 
=> Framework: hotfix for DoozyX/clang-format

packages/framework/ini-files/config-specs.ini, packages/framework/ini-files/environment-specs.ini, packages/framework/ini-files/supported-envs.ini
Want to restore a nightly for C++20 compatibility checks (@rppawlo specifically was asking about this).
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-672
=> Framework: CXX20 gcc container config

.github/workflows/tpetra_muelu_label_to_project.yml
Fix  MueLu and Tpetra project locations
github changed where projects are located
N/A
N/A
=> Trilinos: fix project actions

packages/tpetra/CMakeLists.txt
=> Tpetra: fix typo: atre -> are

packages/seacas/applications/cpup/cpup.C, packages/seacas/libraries/ioss/src/exodus/Ioex_ParallelDatabaseIO.C
@vbrunini 
This fixes or works-around a problem with a particular version of the NVCC compiler.
=> SEACAS: Kluge/Fix for NVCC compiler error and warning

.github/workflows/per-commit.yml, commonTools/test/utilities/check-commit-signoffs.sh
Want a DCO check without a manual override button.
=> Framework: DCO guarantee

packages/stk/CHANGELOG.md, packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp, packages/stk/stk_mesh/stk_mesh/base/BulkData.hpp, packages/stk/stk_mesh/stk_mesh/base/FEMHelpers.cpp, packages/stk/stk_mesh/stk_mesh/base/FEMHelpers.hpp, packages/stk/stk_mesh/stk_mesh/base/NgpFieldBLAS.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/NgpFieldBLASImpl.hpp, packages/stk/stk_search/stk_search/morton_lbvh/CoarseSearchMortonLBVH.hpp, packages/stk/stk_unit_test_utils/stk_unit_test_utils/MeshUtilsForBoundingVolumes.cpp, packages/stk/stk_unit_tests/stk_mesh/ngp/ngpFieldBLASTest.cpp, packages/stk/stk_unit_tests/stk_search/UnitTestCoarseSearch.cpp, packages/stk/stk_util/stk_util/Version.hpp, packages/stk/stk_util/stk_util/parallel/CMakeLists.txt, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp
=> STK: Snapshot 09-30-24 18:31 from Sierra 5.21.5-353-g60799ad8

packages/tpetra/core/src/Tpetra_Details_KokkosCounter.cpp, packages/tpetra/core/src/Tpetra_Details_KokkosTeuchosTimerInjection.cpp
Compatibility update with kokkos@develop changes merged in kokkos/kokkos#7394
@trilinos/tpetra @csiefer2 
Resolve compilation errors with kokkos@develop branch
Tested with local build to confirm compilation errors resolved
=> tpetra: compatibility update with KOKKOS_VERSION>=40499

packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C
@tcfisher 
The line decomposition option opens an intermediate file to do the line decomposition modifications.  The integer API size of this file read/write was not matching the integer API size of the routine that called the decomposition which was casuing a field size mismatch for some operations.
Fixed so the integer size matches which should solve the SPARC issue.
[COMPSIMHD-18566](https://asc-jira.sandia.gov/browse/COMPSIMHD-18566)
=> IOSS: Fix single-rank file open  integer size

packages/sacado/src/KokkosExp_View_Fad.hpp, packages/sacado/src/Kokkos_DynRankView_Fad.hpp, packages/sacado/src/Kokkos_View_Fad_Fwd.hpp, packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp, packages/stokhos/src/sacado/kokkos/pce/Kokkos_View_UQ_PCE_Fwd.hpp, packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp, packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp
Compatibility update corresponding to kokkos/kokkos#7339
In this PR, previous use of `Impl::MirrorType</* ... */>::view_type` is guarded for Kokkos versions < 4.4.99 Usage is replaced with `Kokkos::Impl::MirrorViewType</* ... */>::dest_view_type`
Existing usage of `Kokkos::Impl::MirrorViewType</* ... */>::view_type` was not changed
Attempt to address issue #13517 
Co-authored-by: Paul Zehner <paul.zehner@cea.fr>
Co-authored-by: Damien L-G <dalg24@gmail.com>
@trilinos/sacado @trilinos/stokhos @etphipp 
Resolve compilation errors with kokkos@develop branch
Local testing of cuda build confirmed compilation errors resolved
=> sacado,stokhos: remove use of Kokkos::Impl::MirrorType

.github/workflows/AT2.yml, .github/workflows/spack.yml
Updated workflows utilizing AT2 infrastructure by removing the pull_request_review event triggers and adding a workflow concurrency check that will cancel and in-progress workflows for the same PR.
AT2 updated the process for approving non-Sandian workflows by requiring a Sandian to hit 're-run' on the workflow jobs instead of requiring them to 'Approve' the PR itself to trigger an approved run on the AT2 system.
These changes are made based on AT2 documentations for their recommended workflow file: https://sems-atlassian-son.sandia.gov/confluence/display/SEMSKB/How+to+Trigger+Pull+Request+Tests+with+Autotester2
Will test the behavior of AT2 CI changes in this PR and monitor its results.
=> Framework: Update workflows using AT2

packages/kokkos-kernels/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp, packages/kokkos-kernels/sparse/src/KokkosSparse_sptrsv_handle.hpp, packages/kokkos-kernels/sparse/unit_test/Test_Sparse_sptrsv.hpp
@trilinos/kokkos-kernels @jgfouca 
Bug fix patch of kokkos/kokkos-kernels#2376
@jgfouca 
See kokkos/kokkos-kernels#2376
=> kokkos-kernels: Block Sptrsv fixes (kokkos/kokkos-kernels#2376)

packages/muelu/research/regionMG/test/structured/CMakeLists.txt
=> MueLu regionMG: Fix for Python CMake logic

packages/amesos2/src/Amesos2_Tacho_decl.hpp, packages/amesos2/src/Amesos2_Tacho_def.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Base.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Factory.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
This PR moves the workspace allocation to symbolic from numeric.
=> Tacho : move workspace allocation to symbolic from numeric

packages/teuchos/core/src/Teuchos_ConstNonconstObjectContainer.hpp
=> Teuchos: Delete ConstNonconstObjectContainer::count method

packages/shylu/shylu_node/basker/src/shylubasker_decl.hpp, packages/shylu/shylu_node/basker/src/shylubasker_def.hpp, packages/shylu/shylu_node/basker/src/shylubasker_thread.hpp, packages/shylu/shylu_node/basker/src/shylubasker_util.hpp
resolve compilation errors with printRHS and printSOL
resolve compilation errors with printRHS and printSOL
Locally tested
=> shylubasker: remove unused code

.github/workflows/AT2.yml, .github/workflows/spack.yml
This PR fixes a syntax issue with the non-blocking Trilinos spack PR test that I introduced in a previous PR.
- #13528
=> Framework: Fix broken Trilinos Spack action

packages/panzer/mini-em/example/BlockPrec/solverMueLu.xml, packages/panzer/mini-em/example/BlockPrec/solverMueLuEpetra.xml
=> Panzer MiniEM: Propagate parameter change from MueLu

packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_impl.hpp
=> Panzer :: Var wasn't getting initialized

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
Remove unused variable fixing failing warnings.
* Closes #13605
=> MueLu: Remove unused variable

packages/amesos2/src/Amesos2_EpetraCrsMatrix_MatrixAdapter_def.hpp, packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp, packages/shylu/shylu_node/basker/src/shylubasker_decl.hpp, packages/shylu/shylu_node/basker/src/shylubasker_error_manager.hpp, packages/shylu/shylu_node/basker/src/shylubasker_nfactor_blk.hpp, packages/shylu/shylu_node/basker/src/shylubasker_nfactor_col2.hpp, packages/shylu/shylu_node/basker/src/shylubasker_order.hpp, packages/shylu/shylu_node/basker/src/shylubasker_order_btf.hpp, packages/shylu/shylu_node/basker/src/shylubasker_order_scotch.hpp, packages/shylu/shylu_node/basker/src/shylubasker_sfactor.hpp, packages/shylu/shylu_node/basker/src/shylubasker_structs.hpp, packages/shylu/shylu_node/basker/src/shylubasker_thread.hpp, packages/shylu/shylu_node/basker/src/shylubasker_types.hpp, packages/shylu/shylu_node/basker/src/shylubasker_util.hpp
This PR adjusts the memory pre-allocation in symbolic.
=> ShyLU - Basker : tune memory pre-allocation

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp, packages/tpetra/core/src/Tpetra_Distributor.hpp
Until we can diagnose segfaults reported wrt PR #13598.
This reverts commit 7eb5fe535ba8dd8bcd0172292e7b19c194c1c852, reversing changes made to e20e3cddc5391f2e148f4a4cf88f127badcdd457.
Segfaults reported in MiniEM.
N/A
@skennon10 confirmed that reverted this MR fixes observed segfaults.
=> Tpetra: revert TAFC changes

packages/nox/src-petsc/NOX_Petsc_Group.C
@trilinos/NOX
Simple typos https://github.com/trilinos/Trilinos/issues/13621
* Closes #13621
=> fix unenclosed brackets.

packages/muelu/example/basic/Simple.cpp, packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp, packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp, packages/muelu/test/scaling/Driver.cpp, packages/muelu/test/scaling/DriverCore.hpp, packages/muelu/test/unit_tests/Utilities.cpp
This simplifies solving systems where Dirichlet conditions have only been enforced on matrix rows.
=> MueLu: Add function to enforce boundary condtions on initial guess

packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py
=> Framework: Fix unit test

packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
Fixes https://github.com/trilinos/Trilinos/issues/13596
=> Ifpack2: KOKKOS_CUSPARSE_SAFE_CALL -> IFPACK2_DETAILS_CUSPARSE_SAFE_CALL

packages/muelu/test/unit_tests_kokkos/Regression.cpp
Fix regression counts on Cuda with UVM=ON.
=> MueLu: Fix regression counts

.github/workflows/AT2.yml
Want dashboard name to be aligned with build configuration.
=> Framework: Correct AT2 uvm name

packages/panzer/adapters-stk/test/evaluator_tests/CMakeLists.txt, packages/panzer/adapters-stk/test/evaluator_tests/tpetra_blocked_scatter_dirichlet_residual.cpp, packages/panzer/adapters-stk/test/evaluator_tests/tpetra_blocked_scatter_residual.cpp, packages/panzer/adapters-stk/test/evaluator_tests/tpetra_scatter_dirichlet_residual.cpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_BlockedTpetra.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_BlockedTpetra_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Tpetra_decl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Tpetra_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp
Continue to update Panzer's tangent capabilities by refreshing Tpetra Dirichlet residual scatters.
=> Panzer tangents: ScatterDirichletResiduals Tpetra

packages/muelu/src/Graph/MatrixTransformation/MueLu_CutDrop.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_DroppingCommon.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_MatrixConstruction.hpp
Refactor `blockSize>1` case in CoalesceDrop to avoid build+run issues.
=> MueLu: Refactor coalesce drop kokkos

packages/tempus/src/Tempus_TimeEventRange_decl.hpp, packages/tempus/src/Tempus_TimeEventRange_impl.hpp, packages/tempus/unit_test/Tempus_UnitTest_TimeEventRange.cpp
Fix for bug found in #13692.
* Related to #13692
=> Tempus: fix type limits

README.md
If anyone wants more badges, we can get more badges.
=> README.md: More badges!

packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
=> Panzer BasisValues2: Remove undefined method

packages/amesos2/src/Amesos2_Superlu_def.hpp
Broadcast `info2` to avoid the deadlock in case of `Equil` failure
- https://github.com/trilinos/Trilinos/issues/13743
=> Amesos2::SuperLU broadcast info2

packages/amesos2/src/Amesos2_Factory.hpp, packages/muelu/src/MueCentral/MueLu_VerbosityLevel.cpp, packages/panzer/adapters-stk/src/Panzer_STK_WorksetFactory.cpp, packages/panzer/mini-em/src/solvers/MiniEM_Interpolation.cpp, packages/panzer/mini-em/src/solvers/MiniEM_Utils.cpp, packages/teko/src/Teko_GaussSeidelPreconditionerFactory.cpp, packages/teko/src/Teko_InverseLibrary.cpp, packages/xpetra/src/MultiVector/Xpetra_MultiVectorFactory_def.hpp
@trilinos/xpetra @trilinos/panzer @trilinos/amesos2 @trilinos/teko 
Just a couple of "unreachable return" warnings.
=> Silence warnings

packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
Silence a shadow warning that gets printed pretty often.
=> Stokhos: Silence shadow warning

packages/amesos2/src/Amesos2_EpetraCrsMatrix_MatrixAdapter_decl.hpp, packages/amesos2/src/Amesos2_TpetraCrsMatrix_MatrixAdapter_def.hpp
It addresses issues with matrix-gather
- fix the out-of-bound access with empty local subdomain
- return the gathered matrix with sorted row indexes when column-major
- https://github.com/trilinos/Trilinos/issues/13737 by @spdomin
=> Amesos2 : matrix-gather update

packages/amesos2/src/Amesos2_Superlu_FunctionMap.hpp, packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp
This resolves issues on rzadams.
=> Amesos2: Fix Amesos2 + SuperLU issue coming from EMPTY macro

packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp
=> MueLu CoalesceDropFactory_kokkos: Add cut-drop using material-aware coarsening

packages/belos/src/BelosCGIteration.hpp
This fixes https://github.com/trilinos/Trilinos/issues/13796.
=> Belos: Add virtual dtor to `CGIterationStateBase`

.github/workflows/AT2.yml
The submit to cdash looks for GENCONFIG_BUILD_NAME in the environment to properly upload some files we are expecting to be uploaded
=> Framework: export GENCONFIG_BUILD_NAME for AT2 jobs

packages/shylu/shylu_node/tacho/unit-test/Tacho_TestDenseLinearAlgebra.hpp
https://github.com/kokkos/kokkos/pull/7716 proposes to deprecate the ability to access `DualView`'s `h_view` and `d_view` members directly since modifying the allocations can get perturbed the `DualView`'s internal status. This pull request replaces all places in `ShyLU` that use these members directly, in most places, verbatim with `view_device` resp. `view_host`.
Related to https://github.com/kokkos/kokkos/pull/7716.
Signed-off-by: Daniel Arndt <arndtd@ornl.gov>
=> ShyLU: Don't access DualView's [h|d]_view directly

packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
Field metadata is causing some issues.  Only outputting if requested instead of by default.
* Closes #13795
=> SEACAS: Default field metadata output to false

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp, packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp, packages/tpetra/core/src/Tpetra_Map_decl.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp
This reverts commit fcf14593a5a6478e9d1f5504d0f3dc21658e8244, reversing changes made to 984b94330897d4b083e34f2d295e1d56a41a0a78.
Regressions detected in performance testing:
ATS2, MiniEM
RZadams & Tioga
MiniEM 4 ranks, 4 ranks
MueLu setup-solve, 1/4 ranks
Tpetra FE Assembly, 4 ranks
Signed-off-by: Jonathan Hu <jhu@sandia.gov>
Performance dashboard regressions
N/A
N/A
=> Tpetra: revert 13714

packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp, packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp, packages/muelu/test/scaling/Driver.cpp, packages/muelu/test/scaling/DriverCore.hpp, packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt, packages/panzer/mini-em/example/BlockPrec/MiniEM_helpers.cpp, packages/panzer/mini-em/example/BlockPrec/MiniEM_helpers.hpp, packages/panzer/mini-em/example/BlockPrec/main.cpp, packages/panzer/mini-em/example/BlockPrec/solverMueLuBarrier.xml
- MueLu: Steal simple CG from Tpetra and hook it up in the MueLu driver.
- MueLu: Use timed barriers in RefMaxwell when "sync timers" == "true"
- MueLu: Fix overflow in CoaleseDrop
- Panzer MiniEM: Add test with barriers
=> MueLu & MiniEM: More barriers

packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
Regressions observed in Tpetra FE Assembly test on Hops and Vortex due to PR #13778.  See discussion in https://github.com/trilinos/Trilinos/pull/13820.
*  #13778 
Fix verified locally on Hops.
=> Tpetra: fix performance regressions

.github/workflows/spack.yml
Want the CDash name to reflect which PR was tested.
=> Framework: Clarify Spack cdash name

packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
Forgot to disable the field metadata output in the last change.  It is still causing isssues in some applications and paraview.
=> IOSS: Disable field meta data output

packages/shylu/shylu_node/basker/src/mwm2.hpp, packages/shylu/shylu_node/basker/src/shylubasker_order_scotch.hpp, packages/shylu/shylu_node/basker/test/amesos2_interface_test.cpp
Fix some compiler warnings, and also errors with float
=> ShyLU-Basker : fix compile errors/warnings (e.g., with float)

packages/stk/stk_topology/stk_topology/topology_type.hpp
Fixes compiler error with rocm 6.1.3 on Frontier.
This is temporary until the next STK snapshot.
* Related to #13867.
Approved by STK developers (see #13867).
=> STK: swap macro order

packages/muelu/adapters/tpetra/MueLu_ShiftedLaplacian_decl.hpp, packages/muelu/src/Utils/MueLu_Utilities.cpp, packages/muelu/test/scaling/DriverCore.hpp, packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp, packages/teuchos/numerics/src/Teuchos_SerialSymDenseMatrix.hpp, packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix_def.hpp, packages/xpetra/src/Map/Xpetra_MapFactory_def.hpp, packages/xpetra/src/Matrix/Xpetra_CrsMatrixWrap_def.hpp
@trilinos/teuchos @trilinos/xpetra @trilinos/muelu 
- Changes from #13841 minus things that depend on `<filesystem>`.
- Type fix in MueLu DriverCore.
- Xpetra: silence a warning
=> Teuchos, Xpetra, MueLu: Small fixes

packages/shards/src/Shards_CellTopology.hpp
@trilinos/shards 
Remove two methods without implementation.
=> Shards: Remove unimplemented methods

packages/amesos2/src/Amesos2_ShyLUBasker_FunctionMap.hpp, packages/amesos2/src/Amesos2_ShyLUBasker_TypeMap.hpp, packages/amesos2/test/solvers/ShyLUBasker_UnitTests.cpp, packages/shylu/shylu_node/basker/src/mwm2.hpp, packages/shylu/shylu_node/basker/test/amesos2_interface_test.cpp
This PR enables complex test in `ShyLUBasker_UnitTests` of Amesos2  and fix compile errors in ShyLU-Basker.
- Tested by enabling`float`, `complex double`, and `complex float`
=> ShyLU-Basker : compile errors with complex variables

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp, packages/panzer/adapters-stk/test/stk_interface_test/CMakeLists.txt, packages/panzer/adapters-stk/test/stk_interface_test/tExodusIossProperties.cpp
* this allows the app to configure Ioss behavior
* added a unit test that sets the MAXIMUM_NAME_LENGTH property for Exodus
=> Panzer: add a variant of setupExodusFile() with a vector<IossProperty> arg

Version.cmake
With the release of Trilinos 16.1.0 in #13861, bump the current development version to 16.2.0-dev.
- [TRILFRAME-705](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-705)
=> Framework: Update development branch version to 16.2.0-dev

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp, packages/panzer/disc-fe/src/Panzer_FaceToElement_impl.hpp
Performance improvements for large scale runs.
Reduced the number of conn manager construction calls.
N/A
=> Panzer: performance improvements for exodus reader and DG workset constructiton path

packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
I'm removing this since I saw it in a trace and it's not needed.
=> MueLu Ifpack2Smoother: Skip generation of unneeded PL.

packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp, packages/shylu/shylu_node/tacho/src/Tacho_Driver.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol_External.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol_Internal.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol_Serial.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Lapack_Team.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Base.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Serial.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeChol.hpp, packages/shylu/shylu_node/tacho/unit-test/Tacho_TestSolver.cpp
This PR adds user options for chol
- specify if transpose should be stored, explicitly
- replace tiny pivots
=> Tacho : solver option for chol

packages/tpetra/core/src/Tpetra_Details_DistributorActor.cpp, packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp, packages/tpetra/core/src/Tpetra_DistObject_def.hpp
Track receive and send requests in separate arrays. Delay Waitall call for sends until after unpack.
=> Tpetra: Track recv and send requests separately

packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_decl.hpp
Issue: #13492
Test: N/A
Stakeholder feedback: Via email from @jrobbin
=> Tpetra: Update TpetraExt_TripleMatrixMultiply_decl.hpp Docs

packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_decl.hpp
Issue: https://github.com/trilinos/Trilinos/issues/13492
Test: N/A
Stakeholder feedback: Comments on #13910 
See @jhux2's comments on #13910
=> MueLuL Update TpetraExt_TripleMatrixMultiply_decl.hpp docs

packages/framework/ini-files/config-specs.ini
- Remove options for removed packages.
- Attempt to reenable some tests.
=> Reenable disabled tests

.github/workflows/AT2.yml
Now that the wiki page is more up-to-date and hopefully helpful, point at it from each AT2 job summary.  Also add the GenConfig ID in-line.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-703
=> Framework: Improve AT2 summary info

packages/muelu/test/scaling/MatrixMatrixMultiply.cpp
Issue: #13473
Test: Yes
Stakeholder feedack: As stakeholder, I approve.
=> MueLu: Improving reproducibility in test

packages/amesos2/src/Amesos2_Superlu_def.hpp, packages/muelu/src/Utils/MueLu_KokkosTuningInterface.cpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
Fix a few shadow and pedantic warnings.
@trilinos/muelu @trilinos/amesos2 @trilinos/tpetra 
* #11497 
N/A
See shadow warning build on dashboard.
=> Tpetra: Amesos2: MueLu: fix warnings

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
Issue: #13941
Test: n/a
Stakeholder feedback: @crtrott @jjellio approve
=> Tpetra: Removing old C++14 support code which breaks C++20 compiles

packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
=> Panzer: Silence warnings

packages/muelu/test/scaling/CMakeLists.txt
Issue: https://github.com/trilinos/Trilinos/issues/13961
Test: This
Stakeholder feedback: As the stakeholder, I approve
See #13962 for similar Tpetra test
=> MueLu: Making SetupSolve perf test scale up

packages/muelu/test/scaling/CMakeLists.txt, packages/muelu/test/unit_tests/MueLu_Test_ETI.hpp
Improve performance testing
* Part of #13961 and #10660.
I am the stakeholder.
Tested locally on Aurora.
=> MueLu: small fixes for Aurora testing

packages/muelu/test/scaling/CMakeLists.txt
Issue:#13961 
Test: This
Stakeholder feedback: As the stakeholder, I approve of myself.
=> MueLu: Fixing one-character typo

packages/amesos2/src/Amesos2_Superlu_def.hpp, packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp
@trilinos/shylu @trilinos/amesos2 
Self-evident
* #11497 
Unnecessary
N/A
=> FROSch: Amesos2: silence warnings

packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp
Fixes compilation bug in OrientationTools
* Closes #13135
=> Intrepid2, fix compiler bug (issue 13135)

packages/muelu/test/perf_tests_kokkos/KokkosKernels.cpp, packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp, packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp, packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
@trilinos/muelu @trilinos/shylu 
Reduce warnings
N/A
N/A
N/A
=> ShyLU: MueLu: Fix warnings

packages/amesos2/example/GappedMtxGIDs-1proc.cpp, packages/amesos2/src/Amesos2_Superludist_decl.hpp, packages/amesos2/src/Amesos2_Superludist_def.hpp, packages/amesos2/src/Amesos2_Util.hpp, packages/amesos2/test/CMakeLists.txt, packages/amesos2/test/solvers/CMakeLists.txt, packages/amesos2/test/solvers/Solver_Test.cpp, packages/amesos2/test/solvers/superludist_gapped_test.xml
call `reindex` from SuperLU_DIST
* [13987](https://github.com/trilinos/Trilinos/issues/13987)
=> Amesos2: reindex for SuperLU_DIST

packages/amesos2/example/SimpleSolve_File.cpp, packages/amesos2/src/Amesos2_Superludist_def.hpp, packages/amesos2/test/solvers/Superludist_UnitTests.cpp
This fixes the bug in the previous PR [13990](https://github.com/trilinos/Trilinos/pull/13990)
Updated example and test.
=> Amesos2 SuperLU_Dist : fix contig rowmap for contig GIDs reindex

packages/muelu/src/Graph/Containers/MueLu_LWGraphBase.hpp, packages/muelu/test/perf_tests_kokkos/KokkosKernels.cpp
- Compatibility update needed with Kokkos_ENABLE_DEPRECATED_CODE_4=OFF
- StaticCrsGraph from Kokkos_StaticCrsGraph.hpp moved to kokkos-kernels in KokkosSparse_StaticCrsGraph.hpp in KokkosSparse namespace
These changes (along with #14014) allowed me to build muelu with `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF`
* Requires #14014 in order to build with `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF`
Tested locally in a build with gcc/12 and OpenMP+Serial backends enabled
=> Muelu: deprecated code fixes

packages/amesos2/test/solvers/shylubasker_test.xml, packages/shylu/shylu_node/basker/src/shylubasker_scalar_traits.hpp
The header was needed when `Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON` to resolve errors of type `Trilinos/packages/shylu/shylu_node/basker/src/shylubasker_scalar_traits.hpp:124:36: error: 'ScalarTraits' is not a member of 'Teuchos'`
Tested in a local build with gcc/12
=> shylubasker: add missing Teuchos_ScalarTraits.hpp

packages/amesos2/test/solvers/Tacho_UnitTests.cpp, packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp, packages/shylu/shylu_node/tacho/src/Tacho_MatrixMarket.hpp
add complex tests for Tacho unit-test in Amesos2
=> Amesos2 Tacho : add complex tests

packages/muelu/src/Graph/MatrixTransformation/MueLu_ClassicalDropping.hpp
Issue: #14030
Tests: n/a
Stakeholder feedback: As the Stakeholder, I approve
=> MueLu: Fixing docs and misleading variable names

packages/stokhos/test/Performance/KokkosSpMM/TestSpMM.hpp, packages/stokhos/test/Performance/MPVectorKernels/TestSpMv.hpp, packages/stokhos/test/Performance/PCEMeanMultiply/TestMeanMultiply.hpp, packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixMPVectorUnitTest.hpp, packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixUQPCEUnitTest.hpp
@trilinos/stokhos @etphipp 
- Compatibility update needed with Kokkos_ENABLE_DEPRECATED_CODE_4=OFF
- StaticCrsGraph from Kokkos_StaticCrsGraph.hpp moved to kokkos-kernels in KokkosSparse_StaticCrsGraph.hpp in KokkosSparse namespace
These changes (along with https://github.com/trilinos/Trilinos/pull/14014) allowed me to build stokhos with `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF`
* Requires https://github.com/trilinos/Trilinos/pull/14014 in order to build with `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF`
Tested locally in a build with gcc/12 and OpenMP+Serial backends enabled
=> stokhos: namespace updates for moved Kokkos_StaticCrsGraph.hpp

packages/galeri/src-xpetra/Galeri_StencilProblems.hpp, packages/galeri/src-xpetra/Galeri_XpetraMatrixTypes.hpp, packages/galeri/src-xpetra/Galeri_XpetraParameters.hpp, packages/galeri/src-xpetra/Galeri_XpetraProblemFactory.hpp, packages/muelu/test/helmholtz/Helmholtz1D.cpp, packages/muelu/test/helmholtz/Helmholtz2D.cpp, packages/muelu/test/helmholtz/Helmholtz3D.cpp, packages/muelu/test/helmholtz/HelmholtzFEM2D.cpp, packages/muelu/test/helmholtz/HelmholtzFEM3D.cpp, packages/muelu/test/scaling/MatrixLoad.hpp
This matches what's available in Galeri with Epetra.
Supports finishing MueLu's tutorial.
#10638 
That is I.
Checked locally by hand.
=> MueLu: Galeri: Recirc2D matrix type for Tpetra

packages/ifpack2/adapters/thyra/Thyra_Ifpack2PreconditionerFactory_def.hpp, packages/ifpack2/src/Ifpack2_Details_Factory_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp, packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_decl.hpp, packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_def.hpp, packages/ifpack2/src/Ifpack2_Factory_decl.hpp, packages/muelu/adapters/CMakeLists.txt, packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_def.hpp, packages/muelu/src/Operators/MueLu_Maxwell1_decl.hpp, packages/muelu/src/Operators/MueLu_RefMaxwell_decl.hpp, packages/stratimikos/adapters/amesos2/src/Thyra_Amesos2LinearOpWithSolveFactory_def.hpp, packages/teuchos/parameterlist/src/Teuchos_StandardParameterEntryValidators.cpp, packages/teuchos/parameterlist/src/Teuchos_StandardParameterEntryValidators.hpp, packages/teuchos/parameterlist/test/Validators/Validator_UnitTest.cpp
@trilinos/teuchos @trilinos/ifpack2 @trilinos/amesos2 @trilinos/muelu 
Improve validation and defaults for Ifpack2, Amesos2 and MueLu adapters to Stratimikos.
=> Ifpack2, Amesos2, MueLu: Stratimikos adapter changes

.github/workflows/clang_format.yml
=> Actions: Give clang-format action a better name

packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
There is some bad interaction between the enhanced field metadata and ParaView in some instances.  Until fixed, disabling the enhanced field metadata output.
=> SEACAS/IOSS: Disable the enhanced field metadata

packages/muelu/example/basic/Stratimikos.cpp
Avoid segfault when user specifies their own matrix.
=> MueLu Stratimikos example: Don't set nullptrs in user list

packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp, packages/amesos2/src/Amesos2_TpetraCrsMatrix_MatrixAdapter_def.hpp, packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp, packages/amesos2/test/solvers/Superlu_UnitTests.cpp, packages/shylu/shylu_node/basker/src/shylubasker_decl.hpp, packages/shylu/shylu_node/basker/src/shylubasker_def.hpp, packages/shylu/shylu_node/basker/src/shylubasker_order.hpp, packages/shylu/shylu_node/basker/src/shylubasker_order_btf.hpp, packages/shylu/shylu_node/basker/src/shylubasker_solve_rhs.hpp, packages/shylu/shylu_node/basker/src/shylubasker_structs.hpp
This PR contains our initial effort to thread-parallel ShyLU-Basker's nested-dissection's forward/backward solve.
=> ShyLU-Basker : threaded solve

packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_decl.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_DistanceLaplacianDropping.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_MatrixConstruction.hpp, packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp, packages/muelu/test/unit_tests_kokkos/CMakeLists.txt, packages/muelu/test/unit_tests_kokkos/CoalesceDropFactory_kokkos.cpp, packages/muelu/test/unit_tests_kokkos/Galeri.cpp, packages/muelu/test/unit_tests_kokkos/MueLu_TestHelpers_kokkos.hpp
Allow running CoalesceDropFactory_kokkos using distance Laplacian and multiple DoFs per node.
=> MueLu: CoalesceDropFactory_kokkos for multiple DoFs/node

packages/shylu/shylu_node/tacho/src/impl/Tacho_SupernodeInfo.hpp
Add a check to avoid out-of-bound access
=> Tacho : check to avoid out-of-bound access

packages/stk/CHANGELOG.md, packages/stk/CMakeLists.txt, packages/stk/stk_mesh/stk_mesh/base/HostField.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/EntityGhostData.hpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshCommVerify.cpp, packages/stk/stk_performance_tests/stk_mesh/NgpFieldAccess.cpp, packages/stk/stk_performance_tests/stk_mesh/perfParts.cpp, packages/stk/stk_performance_tests/stk_mesh/perfSidesetPolarity.cpp, packages/stk/stk_search_util/stk_search_util/PointProjection.cpp, packages/stk/stk_transfer_util/stk_transfer_util/CMakeLists.txt, packages/stk/stk_transfer_util/stk_transfer_util/spmd/GeometricTransferOptions.hpp, packages/stk/stk_transfer_util/stk_transfer_util/spmd/SimpleTransfer.cpp, packages/stk/stk_transfer_util/stk_transfer_util/spmd/SimpleTransfer.hpp, packages/stk/stk_unit_test_utils/stk_unit_test_utils/CMakeLists.txt, packages/stk/stk_unit_tests/stk_mesh/UnitTestAura.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestBulkData.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestFieldAsync.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestFieldBytesAccess.cpp, packages/stk/stk_unit_tests/stk_mesh/UnitTestFieldSynchronization.cpp, packages/stk/stk_unit_tests/stk_transfer_util/UnitTestMockSimpleTransfer.cpp, packages/stk/stk_util/stk_util/Version.hpp, packages/stk/stk_util/stk_util/registry/ProductRegistry.cpp, packages/stk/stk_util/stk_util/util/FPExceptions.hpp
=> STK: Snapshot 06-09-25 09:12 from Sierra 5.25.3-133-gd77dca46

packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp, packages/shylu/shylu_node/tacho/src/Tacho_MatrixMarket.hpp
Add an option to read RHS from a matrix-market file
=> Tacho : option to read RHS from a file

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp, packages/muelu/test/scaling/CMakeLists.txt, packages/muelu/test/scaling/SpMVPerformance.cpp
@trilinos/ifpack2 @trilinos/ifpack2 
- Ifpack2: Silence some warnings
- MueLu: Always build SpMVPerformance executable and fix it
=> MueLu & Ifpack2: Fixes

packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_main.cpp, packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp
Add min, max, and histogram output to stacked timers.  This could be useful in tracking down anomalous behavior.
N/A
I am the stakeholder.
Confirmed with local build and existing tests.
=> Tpetra: more detailed timings

.github/workflows/clang_format.yml, packages/galeri/.clang-format, packages/galeri/example-tpetra/CrsMatrix_Tpetra.cpp, packages/galeri/example-tpetra/LinearProblem_Tpetra.cpp, packages/galeri/example-tpetra/Map_Tpetra.cpp, packages/galeri/example-xpetra/XpetraMap.cpp, packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp, packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp, packages/galeri/src-xpetra/Galeri_HelmholtzFEM2DProblem.hpp, packages/galeri/src-xpetra/Galeri_HelmholtzFEM3DProblem.hpp, packages/galeri/src-xpetra/Galeri_MapTraits.hpp, packages/galeri/src-xpetra/Galeri_MatrixTraits.hpp, packages/galeri/src-xpetra/Galeri_MultiVectorTraits.hpp, packages/galeri/src-xpetra/Galeri_Problem.hpp, packages/galeri/src-xpetra/Galeri_Problem_Helmholtz.hpp, packages/galeri/src-xpetra/Galeri_StencilProblems.hpp, packages/galeri/src-xpetra/Galeri_StencilProblems_Helmholtz.hpp, packages/galeri/src-xpetra/Galeri_VectorTraits.hpp, packages/galeri/src-xpetra/Galeri_VelocityModel.hpp, packages/galeri/src-xpetra/Galeri_XpetraCartesian.hpp, packages/galeri/src-xpetra/Galeri_XpetraMaps.hpp, packages/galeri/src-xpetra/Galeri_XpetraMatrixTypes.hpp, packages/galeri/src-xpetra/Galeri_XpetraMatrixTypes_Helmholtz.hpp, packages/galeri/src-xpetra/Galeri_XpetraParameters.hpp, packages/galeri/src-xpetra/Galeri_XpetraProblemFactory.hpp, packages/galeri/src-xpetra/Galeri_XpetraProblemFactory_Helmholtz.hpp, packages/galeri/src-xpetra/Galeri_XpetraUtils.hpp, packages/galeri/test/VerySimple/cxx_main.cpp, packages/galeri/test/VerySimple/cxx_main_tpetra.cpp, packages/galeri/test/bug_5851.cpp
- Enable clang-format for Tpetra & Xpetra parts of Galeri
- Fix timer labels in Kokkos code path to match non-Kokkos timers
=> Galeri: clang-format & timer labels

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_CrsGraphTransposer_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
If I was too aggressive in removing things, please let me know.
=> Tpetra: Remove old Kokkos-Kernels code

packages/muelu/src/Graph/MatrixTransformation/MueLu_ClassicalDropping.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_DistanceLaplacianDropping.hpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
Helps if we parse these parameters...
=> MueLu: Add missing parsing of new CoalesceDropFactory_kokkos params

packages/galeri/src-xpetra/Galeri_XpetraUtils.hpp
Speed up problem construction.
=> Galeri: Build coordinates on device

packages/tempus/test/BDF2/CMakeLists.txt, packages/tempus/test/BackwardEuler/CMakeLists.txt
Attempt to avoid some timeouts.
=> Tempus: Switch BDF2_CDR and BackwardEuler_CDR to run in serial

packages/muelu/src/Graph/MatrixTransformation/MueLu_ClassicalDropping.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_CutDrop.hpp, packages/muelu/src/Graph/MatrixTransformation/MueLu_DistanceLaplacianDropping.hpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- Make it easier to understand dropping.
- Fix sign error in cut-drop with a signed SoC measure.
=> MueLu CoalesceDropFactory_Kokkos: Improve debug output

packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
Stakeholder feedback: As the stakeholder, I approve
=> TrilinosCouplings: Remembering to initialize/finalize Kokkos

packages/tpetra/core/example/Lesson03-Power-Method/lesson03_power_method.cpp, packages/tpetra/core/example/Lesson05-Redistribution/lesson05_redistribution.cpp
Upon reading the tutorials to learn using Trilinos, I found some minor typos.
N/A
=> fixing some minor typos in tutorials

packages/belos/tpetra/example/SolverFactory/CMakeLists.txt, packages/belos/tpetra/example/SolverFactory/SolverFactoryTpetraGaleriEx.cpp
Add some Belos stand-alone tests for performance. These tests will post to the Sandia internal performance tracking dashboard. The test run in the default BASIC category did not change.
=> Belos: Add performance tests

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
Reverts trilinos/Trilinos#14241
I accidentally put master as the target branch for that PR, and it auto-merged as soon as tests passed (no reviews or anything).
=> Revert "Ifpack2: use empirical heuristic for Schur sublines"

packages/belos/tpetra/example/SolverFactory/CMakeLists.txt, packages/belos/tpetra/example/SolverFactory/SolverFactoryTpetraGaleriEx.cpp
Change size of problems for Belos performance tests.
=> Belos: Adjust size of performance tests

packages/belos/src/Belos_Details_EBelosSolverType.cpp, packages/belos/tpetra/example/SolverFactory/CMakeLists.txt
Use "Single-reduce CG" as solver name, similar to "Flexible GMRES".
=> Belos: Expose single-reduce CG via alias in solver factory

packages/panzer/adapters-stk/test/panzer_workset_builder/exodus_workset_builder_internal_sideset_check.cpp
eliminate warning
* Closes 14271
=> panzer removed unused typedef to eliminate warning 14271

packages/rtop/test/ops_lib/ROpMinIndex_UnitTests.cpp, packages/rtop/test/ops_lib/ROpMin_UnitTests.cpp, packages/rtop/test/ops_lib/ROpNorm1_UnitTests.cpp, packages/rtop/test/ops_lib/ROpNormInf_UnitTests.cpp, packages/rtop/test/ops_lib/ROpSum_UnitTests.cpp
@trilinos/rtop
clean up warnings
* Closes 14265
=> rtop removed unused typedefs to eliminate warnings 14265

packages/adelus/src/Adelus_x_solve.hpp
removed unused typedef to eliminate warning
@trilinos/adelus 
eliminate warning
* Closes 14263
=> adelus unused typedef warning

packages/ifpack2/src/Ifpack2_Factory.cpp
Revealed by https://github.com/trilinos/Trilinos/pull/14300.
@trilinos/ifpack2 @csiefer2 
* #14300 
N/A
N/A
=> Ifpack2: fix apparent macro error

packages/amesos2/src/Amesos2_Kokkos_Impl.hpp
This typo leads to compilation error when Kokkos Threads backend is used
=> fix typo of typename KokkosThreadsWrapperNode in Amesos2.

packages/stratimikos/adapters/amesos2/src/Thyra_Amesos2LinearOpWithSolveFactory_def.hpp, packages/stratimikos/adapters/amesos2/src/Thyra_Amesos2Types.cpp, packages/stratimikos/adapters/amesos2/src/Thyra_Amesos2Types.hpp, packages/stratimikos/adapters/amesos2/test/CMakeLists.txt
@trilinos/stratimikos 
Add Amesos2 interface to CSS
- Add test in adapter/amesos2/test
=> Stratimikos : Add Amesos2 interface to CSS

packages/amesos2/example/SimpleSolve_File.cpp, packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp, packages/shylu/shylu_node/basker/src/shylubasker_decl.hpp, packages/shylu/shylu_node/basker/src/shylubasker_def.hpp, packages/shylu/shylu_node/basker/src/shylubasker_nfactor.hpp, packages/shylu/shylu_node/basker/src/shylubasker_nfactor_blk.hpp, packages/shylu/shylu_node/basker/src/shylubasker_nfactor_col.hpp, packages/shylu/shylu_node/basker/src/shylubasker_nfactor_col2.hpp, packages/shylu/shylu_node/basker/src/shylubasker_nfactor_diag.hpp, packages/shylu/shylu_node/basker/src/shylubasker_solve_rhs.hpp, packages/shylu/shylu_node/basker/src/shylubasker_structs.hpp, packages/shylu/shylu_node/basker/src/shylubasker_util.hpp
Adds option to use worker threads for nested factorization
- Turned off the default parameter for MWM
=> ShyLU-Basker : worker-thread for nestted factorization

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
A code comment was incorrectly using doxygen markup
I am a stakeholder.
N/A
=> Tpetra: fix doxygen

packages/teuchos/numerics/src/Teuchos_MatrixMarket_Raw_Adder.hpp
=> Teuchos: mark Teuchos::MatrixMarket::Raw::Element::operator== and operator!= as const to avoid C++20 warnings

packages/intrepid2/unit-test/MonolithicExecutable/ProjectedGeometryTests.cpp
=> Intrepid2 ProjectedGeometryTests: Loosen tolerance

packages/teuchos/numerics/src/Teuchos_MatrixMarket_Raw_Graph_Adder.hpp, packages/zoltan2/core/src/algorithms/partition/Zoltan2_TaskMapping.hpp, packages/zoltan2/core/src/directory/Zoltan2_Directory.hpp, packages/zoltan2/core/src/util/Zoltan2_GraphMetricsUtility.hpp
=> Zoltan2/Teuchos: Mark additional operator>, operator==, etc. as const

packages/tpetra/core/example/Lesson07-Kokkos-Fill/05_solve.cpp
Issue: #14383 Stakeholder feedback: Personal communication from Damien
Test: This
=> Tpetra: Removing old code

packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp, packages/muelu/src/Utils/MueLu_TimeMonitor.cpp
Fixes failures observed by Albany.
=> MueLu: Fix stacked timer usage

packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
=> Tpetra: Removing SYCL technical debt

packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp
Use hashmap instead of atomics. Might still be buggy, let's see what the AT says.
=> MueLu: Use hashmap in MIS2

packages/stk/stk_expreval/stk_expreval/Function.hpp
This PR is attempt to resolve an error encountered testing with cuda/12.2 and rocm/6.2.1 w/ c++20 enabled
Error snip:
```
/root/Trilinos/packages/stk/stk_expreval/stk_expreval/Function.hpp:285:33: error: use of undeclared identifier 'DBL_MIN'
1 error generated when compiling for gfx90a.
```
@alanw0 @ldh4 
This change resolved the compilation errors I saw in my local builds
=> stk: replace DBL_MIN with numeric_traits min

packages/ifpack2/src/Ifpack2_BlockComputeResidualAndSolve.hpp, packages/ifpack2/src/Ifpack2_BlockComputeResidualVector.hpp, packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp, packages/sacado/src/KokkosExp_View_Fad.hpp, packages/sacado/src/Kokkos_DynRankView_Fad.hpp
@trilinos/sacado @trilinos/muelu @trilinos/ifpack2 @vbrunini 
Build errors with trilinos/develop in Sierra. For example
* complex type instantiation
* some instantiations of Sacado functions need update for `Kokkos::View<>::traits`
* host-only View constructor calls in `__host__ __device__` functions
=> Fixes for Sierra ROCm build from Kokkos promotion to 4.7

packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp, packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp, packages/galeri/src-xpetra/Galeri_HelmholtzFEM2DProblem.hpp, packages/galeri/src-xpetra/Galeri_HelmholtzFEM3DProblem.hpp
Replace `Teuchos::SerialDenseMatrix` with `Kokkos::View`.
=> Galeri Elasticity&HelmholtzFEM: Use Kokkos Views

packages/muelu/test/scaling/CMakeLists.txt
This PR reduces the size of some of the elasticity based `MueLu` unit-tests to reduce memory footprint.
@cgcgcg
=> MueLu: Refactor size of some elasticity tests

packages/tpetra/core/src/Tpetra_Details_Random_def.hpp
fix -Werror in AT2 / openmp jog
Fix for
```
2025-09-17T05:53:24.1393171Z ../../runner/_work/Trilinos/Trilinos/packages/tpetra/core/src/Tpetra_Details_Random_def.hpp:47:9: error: typedef 'using pool_type = class Kokkos::Random_XorShift64_Pool<DeviceType>' locally defined but not used [-Werror=unused-local-typedefs]
```
=> tpetra: remove unused typdef

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_Details_KokkosCounter.cpp, packages/tpetra/core/src/Tpetra_Details_KokkosCounter.hpp, packages/tpetra/core/src/Tpetra_DistObject_decl.hpp, packages/tpetra/core/src/Tpetra_DistObject_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp, packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
Remove clang-format on/off.
Issue: https://github.com/trilinos/Trilinos/issues/14419
=> Tpetra: Remove clang-format directives

packages/tpetra/core/src/Tpetra_Details_Ialltofewv.cpp
=> tpetra: ialltofewv: supply missing extent to view ctor

packages/amesos2/src/Amesos2_Tacho_def.hpp, packages/amesos2/src/Amesos2_Util.hpp, packages/amesos2/test/solvers/CMakeLists.txt, packages/amesos2/test/solvers/Solver_Test.cpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp
Trying to fix the local matrix allocation issue for calling Tacho with multiple MPIs.
- Issue [14441](https://github.com/trilinos/Trilinos/issues/14441)
- added a new test
=> Amesos2 Tacho: local matrix allocation issue

packages/teko/src/Tpetra/Teko_TpetraThyraConverter.cpp
=> Teko: Use user-facing Tpetra::Access tags in Thyra multivector conversion code

packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp, packages/shylu/shylu_node/tacho/src/Tacho_Driver.hpp, packages/shylu/shylu_node/tacho/src/Tacho_MatrixMarket.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools_Metis.cpp
add an option to select a graph algorithm type
Tested with build with/without Metis
=> Tacho : expose option to select graph algorithm type 

packages/shylu/shylu_node/tacho/src/Tacho_CuSolver.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Util.hpp
To remove compiler warnings from Tacho
- [14480](https://github.com/trilinos/Trilinos/issues/14480)
=> Tacho : to remove compiler warnings

packages/muelu/test/helmholtz/Helmholtz2D.cpp, packages/muelu/test/unit_tests/CMakeLists.txt
The Helmholtz2D test did not set its `success` flag. I am not sure how this passed testing.
FYI @ndellingwood
=> MueLu Helmholtz test: Set success flag

packages/zoltan2/test/core/driver/CMakeLists.txt, packages/zoltan2/test/core/driver/driverinputs/CMakeLists.txt, packages/zoltan2/test/core/driver/driverinputs/galeriTestsPerformance16.xml, packages/zoltan2/test/core/driver/driverinputs/galeriTestsPerformance4.xml, packages/zoltan2/test/core/driver/test_driver.cpp, packages/zoltan2/test/core/helpers/Zoltan2_ComparisonHelper.hpp, packages/zoltan2/test/core/helpers/Zoltan2_ProblemFactory.hpp
Modify the test driver to report stacked timers. Add a performance test so that we can start tracking behavior across systems and time.
=> Zoltan2: Add performance tests

packages/amesos2/example/SimpleSolve_File.cpp, packages/amesos2/src/Amesos2_MUMPS_def.hpp, packages/amesos2/src/Amesos2_cuSOLVER_FunctionMap.hpp, packages/amesos2/src/Amesos2_cuSOLVER_decl.hpp, packages/amesos2/src/Amesos2_cuSOLVER_def.hpp
Update timers for MUMPS and cuSolver.
=> Amesos2 : timers (MUMPS & cuSolver)
