packages/kokkos-kernels/src/graph/impl/KokkosGraph_Distance1Color_impl.hpp
packages/kokkos-kernels/src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp

Patch in KokkosKernels #1528 and #1530. 1528 fixed MIS2 aggregation being possibly non-deterministic, and fixed valgrind conditional on uninitialized value warnings. 1530 fixed valgrind warnings in EB D1 coloring.
Fixes https://github.com/kokkos/kokkos-kernels/issues/1646 .
The MIS2 changes are a re-application of #11017 . Fixes non-determinism (a real bug) and also valgrind uninitialized value warnings.
The D1 EB changes have been in KokkosKernels develop for a while, but never in Trilinos. There didn't seem to be an actual bug here, but patching this will help make the nightly geminga build with valgrind run cleanly.

KokkosKernels: fix MIS2 agg determinism, valgrind

---

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp

Want to enable shadowing warnings as errors in as many packages as possible.
#11397

Tpetra: Fix last shadowing warning

---

packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/supported-envs.ini

Add clang-11 configuration to the ini PR/MM files that uses the sems v2 tpls.  This will greatly improve the usability of rhe ini files by reducing our dependence on two systems
see these results on cdash which show builds passing all tests using the PR/MM infrastructure on nightly builds
https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Nightly&field2=buildstarttime&compare2=83&value2=2023-01-18&field3=buildstarttime&compare3=84&value3=2023-01-20&field4=buildname&compare4=63&value4=sems-v2

add congfig for clang 11 sems v2 build

---

packages/seacas/libraries/ioss/src/Ioss_StructuredBlock.h
packages/seacas/libraries/ioss/src/Ioss_ZoneConnectivity.h
packages/seacas/libraries/ioss/src/heartbeat/Iohb_DatabaseIO.C
packages/seacas/libraries/ioss/src/heartbeat/Iohb_Layout.C
packages/seacas/libraries/ioss/src/heartbeat/Iohb_Layout.h

SEACAS uses the lib{fmt} library for output, but that library is not yet a Trilinos TPL, so external packages using Trilinos are not required to have the lib{fmt} include files available.
SEACAS in Trilinos uses lib{fmt} as a header-only library and there is an embedded version in SEACAS/Trilinos.
This commit removes all fmt-related includes from header files so applications using Trilinos do not need to have the fmt include files.

SEACAS: Remove uses of fmt in include files

---

packages/framework/ini-files/config-specs.ini

SIERRA builds with shadowing warnings/errors and in the past has been hit with shadowing warnings from Trilinos.  Turn on shadowing errors in Trilinos to try and keep everything cleaner.
User Support Ticket(s) or Story Referenced: [TRILFRAME-376](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-376)

Framework: Enable shadow warnings everywhere we use -Wall

---

packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_FE.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_utility.hpp

Works around performance regression in Kokkos 3.7.0 where taking a ``Kokkos::subview`` of a **managed** view inside a kernel (executing on Serial execution space) is slower than with **unmanaged**. This caused the ``3.2) ElementLoop (Matrix)`` component of the FEM assembly performance test to get about 50% slower (from ~8s to ~12s) on the Intel compiler, CTS-1 build. 
https://github.com/kokkos/kokkos/issues/5581 was about this, and I put a non-Tpetra standalone reproducer there. A fix was proposed and put in Kokkos develop which resolved the slowdown for the reproducer and which seemed to fix this Tpetra issue as well. However, recently I was not able to reproduce this fixing the Tpetra issue. So this workaround uses unmanaged views explicitly to speed ``subview`` back …

Tpetra: work around subview of managed view slowdown

---

packages/adelus/src/Adelus_factor.hpp
packages/adelus/src/BlasWrapper_copy.hpp

It is not legal to use `Kokkos::Impl::throw_runtime_exception()`.
Throw `std::runtime_error` instead.
adelus @srajama1

Adelus: Do not use `Kokkos::Impl::throw_runtime_exception`

---

packages/intrepid2/unit-test/Discretization/Integration/test_01.hpp

Remove extraneous Kokkos finalize form an Intrepid2 tests. 
It will throw an error with Kokkos 4.

Intrepid2: remove extraneous Kokkos finalize

---

packages/seacas/libraries/aprepro_lib/apr_getline_int.c
packages/seacas/libraries/ioss/src/Ioss_Getline.C
packages/seacas/libraries/supes/ext_lib/getline_int.c

Aprepro, suplib, and IOSS all contain an embedded getline function that defined a `new_termios` and `old_termios` global symbol which could cause conflicts on some platforms.  Changed each instance to a new name that is unique for each use.

SEACAS: Make getline termios symbols unique across uses

---

packages/muelu/test/scaling/Driver.cpp
packages/muelu/test/scaling/MatrixLoad.hpp

In the case of multiple runs using the same matrix data, ensure the base timer is restarted.
Add timers for coordinate and RHS reading.
Fixes #11522.
It's very handy to be able to gather stacked timer data from the MueLu driver when using its "rerun" capability
with large matrix data files.
N/A
Verified bug locally and that this PR fixes it.

MueLu: fix stack timer usage with reruns

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake
cmake/ctest/drivers/rocketman/ctest_linux_nightly_mpi_release_muelu_rocketman.cmake

@cgcgcg 
Rocketman nightlies are struggling to build Ifpack1 and Amesos1 due to errors related to SuperLU. These builds really don't need the Epetra stack, and I'd rather just see if the build succeeds without the Epetra stack as opposed to troubleshooting an issue that may potentially require me to rebuild SuperLU.

Cmake: Remove Epetra stack from Rocketman testing

---

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

Closes #11331
@csiefer2 
@ndellingwood

Tpetra: fixup Kokkos compatibility `ExecSpace::concurrency()` not a static member function

---

packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
packages/teuchos/comm/src/Teuchos_StackedTimer.hpp

- In doxygen for ``StackedTimer::reportWatchrXML()``, document the optional ``TRILINOS_GIT_SHA`` environment variable (just a comment change)
- Add a new variable ``WATCHR_BUILD_DATE`` to override the build date in the report filename and the XML header of the report. If unset, the date is just when the build happened (this is the current behavior). This lets us run on a Trilinos version from the past, and have the date on the report match the date of the version.
This is needed because some recent performance dashboard data was generated from incorrect builds and needs to be regenerated.
Tested by running a performance test and outputting Watchr reports - once with the default date (today), and once with the date overridden. This created two separate reports with the …

Teuchos: StackedTimer Watchr documentation, date override

---

packages/compadre/src/Compadre_Typedefs.hpp

Fixes an omission in the `COMPADRE_KOKKOS_VERSION_MAJOR` when >= 4.
Thank you @ndellingwood!

Fix Compadre typedef for Kokkos >= 4.0.0

---

packages/ifpack2/example/BlockTriDi.cpp

Lets the Ifpack2_BlockTriDiagonalSolver be used to drive performance tests that are plotted in Watchr. Adds ``--withStackedTimer`` option to enable stacked timers, and ``--problemName="..."`` option to put a description of the matrix/problem in the Watchr plot title.
Also fix an issue in flat timer mode (``--withoutStackedTimer``) where the "Total" timer would always read 0, because it was never stopped.
Tested by comparing new and old flat timer output, and then by running with stacked timer and outputting a Watchr report.

Ifpack2: BlockTriDi StackedTimer/Watchr support

---

packages/teuchos/numerics/src/Teuchos_BLAS.cpp
packages/teuchos/numerics/src/Teuchos_BLAS_wrappers.hpp
packages/teuchos/numerics/src/Teuchos_LAPACK.cpp
packages/teuchos/numerics/src/Teuchos_LAPACK.hpp
packages/teuchos/numerics/src/Teuchos_LAPACK_wrappers.hpp

Commit:
2425baf8 packages/teuchos/numerics/src/Teuchos_BLAS_wrappers.hpp (James Elliott         2022-09-12 15:33:51 -0700 269)
breaks `apple-clang` builds of Teuchos numerics when combined with `openblas`.
The reason is an illegal cast from `float _Complex` to `std::complex<float>` and `double _Complex` to `std::complex<double>`.
```sh
[ 48%] Building CXX object packages/teuchos/numerics/src/CMakeFiles/teuchosnumerics.dir/Teuchos_BLAS.cpp.o
/Users/pakuber/Compadre/Trilinos-new/packages/teuchos/numerics/src/Teuchos_BLAS.cpp:336:12: error: implicit conversion from '_Complex float' to 'float' is not permitted in C++
return CDOT_F77(&n, x, &incx, y, &incy);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/pakuber/Compadre/Trilinos-new/packages/teuchos/numerics/src/Teuchos_BLAS_wrappers.hpp:155:21: …
```

Blas complex cast fix

---

packages/shylu/shylu_node/tacho/unit-test/CMakeLists.txt

When Shylu's tests are enabled, it pulls in a copy of gtest. Gtest has a flag INSTALL_GTEST that defaults to ON. If the shylu tests are enabled, gtest will get installed along with trilinos. This can conflict with an application's version of gtest. We need to change this default to OFF. This use case is documented in the gtest and tells users to do this. I've just copied this change from sacado which is also pulling in gtest but was setting the default correctly.

Shylu: disable gtest install

---

packages/muelu/research/graham/mf_example_01.cpp

@cgcgcg @pohm01
I'm moving pieces of my matrix-free multigrid code into MueLu incrementally so that collaborators can use it. `example_01` is a 1D Laplacian. This will make it easier for everybody to keep track of updates. This is intentionally not built at the moment, as some pieces later have dependencies on Intrepid2/STK/Panzer, and those dependencies will have to be managed carefully or simply not built.
I recently switched everything from Tpetra to Xpetra, so there are a couple cleanup actions needed in future PRs, but I'm ignoring that for now.

MueLu: Add Matrix-Free 1D Laplacian Multigrid

---

packages/framework/ini-files/config-specs.ini

Timing out in the nightly runs, and we really want to re-enabled the Intel PR build.
@ccober6 told me that he thought the other builds provided enough test coverage to disable these for Intel.
We want to re-enable the PR/MM Intel build, but if it runs on the same machine where another set of tests is running, I don't want these tests to time out spuriously.

Framework/Tempus: Disable resource-hungry Tempus tests for Intel PR/MM builds

---

packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp

Adding missing fences following async deep_copy calls to ensure copy completes before handoff to send This resolves a test failure in TpetraCore_Issue1454 with Cuda-Aware MPI in cuda/11.4.2 builds without UVM
Resolve test failure
Tested with cuda/11.4.2, uvm off, and Cuda-Aware MPI (sems modules)

tpetra: add missing fences for async deep_copy use

---

packages/framework/ini-files/config-specs.ini

Want Intel builds re-enabled, and the existing configuration is a bit wonky with the move from sems-dev to sems modules.  I tested this with the new environment specs, and it built correctly for me.  Note that MKL is not enabled, since there were some more errors, but I figure it's better to get the Intel build back and iterate later to get MKL in use again.

Framework: Use spack TPLs for Intel

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

This PR updates the Block Tridiagonal Solver to use `Kokkos::Experimental::partition_space` instead of `cudaStream`.
This PR has been tested on V100 and MI250.
The performance on V100 are the same as the ones of the previous implementation.

Ifpack2: Use Kokkos::Experimental::partition_space instead of cudaStream

---

packages/anasazi/src/AnasaziBasicOrthoManager.hpp

@trilinos/anasazi
@trilinos/solvers
@jhux2 
Fix unused variable causing Sierra build warnings with clang

Anasazi: Fix unused variable causing build warnings

---

packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp

@jhux2 
Closes #11590 and fixes errors with Clang 9.

MueLu: Fix use of dependent template name in MueLu_Hierarchy_def.hpp

---

packages/sacado/src/new_design/Sacado_Fad_Exp_Atomic.hpp

Replaces the prior implementation using Kokkos functionality that is going away.  Also moves them closer to Kokkos-compliance by removing usage of active execution space macros.
@crtrott @dalg24

Sacado:  Reimplement Sacado's atomic overloads using desul atomics

---

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Matcher.cpp

Seeing tpetra throws in periodic bc. Thought we had all of these out of the code, but running at scale on cuda has revealed some new ones. Tpetra switches execution spaces based on problem size for some operations (and whether cuda aware mpi is enabled), so this only occurs if on cuda with a big enough problem. Not sure how to test this without adding special flags to tpetra to exercise the path for small problem sizes.
Fixes empire's issue.

Panzer: release local views to avoid tpetra throw

---

packages/seacas/libraries/aprepro_lib/apr_getline.cc
packages/seacas/libraries/ioss/src/Ioss_Getline.C

Fix symbol clash with termio global variables.  Move to blank namespace.

Seacas fix symbol clash

---

cmake/ctest/drivers/lightsaber/cron_driver.sh

Use the defaults CMake which is newer. Add a couple of additional modules to match the env used for other nightly builds.

Lightsaber: Use newer CMake

---

packages/xpetra/CMakeLists.txt

CC: @cgcgcg 
This fixes an Albany Trilinos build configuration issue that resulted in a broken Trilinos build.  When you overide an optional package enable like Xpetra_ENABLE_EpetraExt=OFF that was ON, you also need to set the related macro name var HAVE_XPETRA_EPETRAEXT=OFF (which TriBITS automatically sets by default before processing the packages) which is used in the generation of the Package's <Package>_Config.h file.
I was able to reproduce the reported build error reported by @cgcgcg before this change and verified that it fixed the build of Xpetra after this change.

Xpetra: Set HAVE_XPETRA_EPETRAEXT=OFF when no Epetra support

---

packages/framework/ini-files/config-specs.ini

Suspect this was causing test timeouts due to improper MPI process binding.
User Support Ticket(s) or Story Referenced: TRILFRAME-546
Lots of tests seem to take longer than they should have with this specific build.  Once I realized they were using the default OpenMPI binding, I went to see how to add the --bind-to none argument, and imagine my surprise when I saw that all of the other OpenMPI lines were using this flag (except for CUDA, which I've also changed here).

Framework: Pass --bind-to none for all OpenMPI builds

---

INSTALL.rst

I missed this when I upgraded the minimum CMake version `cmake_minimum_required()` in `Trilinos/CMakeLists.txt`.
Should hopefully be the last of #10355.

Upgrade to CMake 3.23 (#10355)

---

packages/muelu/test/scaling/MatrixLoad.hpp
packages/muelu/test/viz/AggExport.cpp

I saw some warnings about `fscanf` unused returns and `system` unused returns originating from `MatrixLoad.hpp` and `AggExport.cpp` like the one below. I fixed them :)
```
/home/graham/Programming/cpp/Trilinos/Trilinos-source/packages/muelu/test/scaling/MatrixLoad.hpp:295:19: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
295 |             fscanf(fp,"%d %d %d\n",&nBlks, &nRows, &nnzs);
|             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Note: While I placed asserts at the start of the file parsing in `MatrixLoad.hpp`, I did not continue by placing asserts inside the main loops. In principle, they should be inside the loop, but I would rather not sacrifice performance on …

MueLu: Fix fscanf and system warnings

---

packages/kokkos-kernels/CMakeLists.txt
packages/kokkos-kernels/cmake/kokkoskernels_components.cmake
packages/kokkos-kernels/example/gmres/test_prec.cpp
packages/kokkos-kernels/perf_test/CMakeLists.txt
packages/kokkos-kernels/sparse/src/KokkosSparse_MatrixPrec.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_Preconditioner.hpp

from commit 1ae5b7ddca97342733eb18284220dc58fa3b5c1a
From repository at git@github.com:kokkos/kokkos-kernels.git
At commit:
commit 1ae5b7ddca97342733eb18284220dc58fa3b5c1a
Author: Luc Berger-Vergiat <lberge@sandia.gov>
Date:   Mon Mar 6 10:36:04 2023 -0700
GMRES: fixing some type issues related to memory space instantiation
Basically one wants to be very careful about only instantiating View
or other object with an execution space only as it might generate a
memory type mismatch down the road
@lucbv @rppawlo 
Fixups to KokkosKernels 4.0 including:
* Fix GMRES compilation issue reported by @rppawlo - cross-ref kokkos/kokkos-kernels#1719
* CMake: Introduce KOKKOSKERNELS_ALL_COMPONENTS_ENABLED variable and some cache-related fixups - cross-ref …

Snapshot of kokkos-kernels.git - fixups to 4.0

---

packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory.hpp

Found some use of Epetra in the ModelEvaluator that is not protected by ifdef. Broke the build of empire unit testing when epetra is disabled.
Fixes issue for EMPIRE
N/A

Panzer: Epetra deprecation

---

packages/teko/tests/CMakeLists.txt
packages/teko/tests/src/tLSCIntegrationTest_tpetra.cpp

- Flag `--kokkos-threads` is deprecated, use `--kokkos-num-threads` instead.
- Fix testdriver_tpetra test that failed when Epetra is disabled.

Teko: Fix warnings and test

---

packages/framework/ini-files/config-specs.ini

Comapdre fixed shadowing warnings, so enable them as errors now to prevent recurrences.
User Support Ticket(s) or Story Referenced: #11497
@trilinos/compadre 
Want to prevent future shadowing warnings.

Framework: Enable shadowing errors in more fixed packages

---

packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/supported-envs.ini

At a testbed meeting, it was suggested that we add OpenMP to a recent clang build using the llvm OpenMP runtime (not GCC). This will help prepare Trilinos for future architectures.
The SEMS clang supports OpenMP, so you just need to enable OpenMP (how do you do that in general: Trilinos_ENABLE_OPENMP or Kokkos_ENABLE_OPENMP?)
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-1

add OpenMP to a recent clang build using the llvm OpenMP runtime (not GCC)

---

packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationInstallation.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py

I want nightly CDash jobs to work the way that CDash expects.  So, make the build name for nightly jobs be the same, and 
set the model to nightly.  For this, "nightly jobs" means "any job not in the track 'Pull Request'".
Long-term we probably do not want to use the PR framework for nightly builds (doesn't make a whole lot of sense), but since we do at the moment, this change helps us move towards more sensible output.
This will enable the historical graphs and other analysis of night-to-night runs on CDash.

Framework: Change CDash settings for nightly jobs

---

packages/teuchos/core/src/Teuchos_StringIndexedOrderedValueObjectContainer.hpp
packages/teuchos/core/src/Teuchos_any.hpp
packages/teuchos/parameterlist/src/Teuchos_ParameterEntry.cpp
packages/teuchos/parameterlist/src/Teuchos_ParameterEntry.hpp
packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp
packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp
packages/teuchos/parameterlist/test/ParameterList/ParameterEntry_UnitTest.cpp
packages/teuchos/parser/src/Teuchos_MathExpr.cpp

@trilinos/Teuchos
Adding missing move semantics, see https://github.com/trilinos/Trilinos/issues/11481.
* https://github.com/trilinos/Trilinos/issues/11481
Tested for `OpenMP`, `Cuda 12`, and `ROCm 5.4`.

teuchos(fix): add missing move constructors for Teuchos::any and Teuchos::ParameterEntry

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp

Kokkos Kernels added the requirement that input matrices of spgemm need to be sorted. Tpetra's `Multiply` routines with transposed argument were creating non-sorted matrices.

Tpetra: Transpose fix

---

packages/kokkos-kernels/sparse/src/KokkosSparse_spgemm_symbolic.hpp

(Temporary) In SpGEMM, disable the check that the input matrices are sorted if the KokkosKernels (non-TPL) implementation is going to be called. This impl does not actually require sorted inputs. Tpetra's MatrixMatrix::Multiply logic needs some nontrivial changes to have a sorted B, but that will be the long-term fix for #11655.
With this change, all Panzer-MiniEM tests pass in an OpenMP+Debug build (develop branch had 6 failures).

KokkosKernels: temp. fix for #11655

---

packages/muelu/research/graham/mf_example_01.cpp

@trilinos/muelu @cgcgcg 
When I swapped over the main routine to use the testing template instantiation framework, I forgot to swap the typedefs over as well, so builds with GO!=long long were failing. Related to #11660.

MueLu: Fix matrix-free for GO!=long long

---

packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_CholSupernodes_Serial.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_CholSupernodes_SerialPanel.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemm.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_GemmTriangular_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemm_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemv.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemv_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Herk.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Herk_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LDL.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LDL_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LU.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LU_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeChol.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeLDL.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeLU.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsm.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsm_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsv.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsv_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Util.hpp

This PR removes the deprecated `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` in Tacho
* Closes https://github.com/trilinos/Trilinos/issues/11508
Being tested on Weaver with CUDA & Host builds

Tacho : remove KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*

---

packages/teuchos/core/src/Teuchos_BigUIntDecl.hpp

While testing Fedora 38 (beta) it was determined that teuchos was missing an include for `<cstdint>`.  This was added where required.
While testing building Trilinos 13-0-1 with GCC 13 it was determined that there were missing include files.  The following adds the includes where needed for `develop` but probably doesn't fix the older versions.
Related to issue #11674

teuchos: Add missing <cstdint> include in teuchos for GCC 13

---

Version.cmake
packages/framework/ini-files/config-specs.ini

Once Trilinos 14.0 is released, want develop/master to reflect that 14.0 was the most recent release.
Wait for #11644 to be merged first.

Framework: Update versions to reflect 14.0 release

---

packages/sacado/src/new_design/Sacado_Fad_Exp_Atomic.hpp

The shfl operations were moved out of the Experimental namespace for Hip with the 4.0 release PR #11600, this update is to resolve compilation errors with the Hip backend
Resolve compilation errors with Hip backend and rocm compilers

sacado: move shfl out of Experimental namespace for Hip

---

packages/stokhos/cmake/Dependencies.cmake

We often build Trilinos for Xyce with “optional” packages and capabilities disabled, so we sometimes come across necessary headers that aren’t installed when they need to be.  I did come across an issue with that in Stokhos.
The Kokkos_StaticCrsGraph.hpp file is included in several files in stokhos/src/kokkos, which is in the KokkosContainers subpackage. That is an optional dependency in the Dependencies.cmake file, so those headers are not installed if optional dependencies are not included.  The result is a build failure in Xyce because, when Stokhos is enabled, that header is not found.  By moving KokkosContainers to a required dependency, this build failure goes away.
I have tested the changes against Xyce, using an installed version of Trilinos and the build issue …

Moves KokkosContainers from an optional to a required dependency

---

packages/epetra/src/Epetra_CrsGraph.cpp

Epetra's CrsGraph previously only checked if an LID was valid with `if(LID != -1)`, which did not cover the case where local indices overflow, as seen in #10249. This addresses it by instead defining `LID > -1` to be valid, so it will now throw on overflows.
Closes #10249.

Epetra: Throw if CrsGraph indices are negative

---

packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/supported-config-flags.ini

To guarantee quality with Trilinos even if legacy (Epetra) stack components are disabled.  To this end, adding a nightly test line to evaluate build/test status with said stack disabled.
The following packages from the Epetra stack are explicitly disabled for any new `ALL-NO-EPETRA` build:
- Amesos
- Domi
- Epetra
- EpetraExt
- FEI
- Ifpack
- Intrepid
- Komplex
- Moertel
- ML
- Piro
- Rythmos
- TriKota
The two new builds added to nightly runs are `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all-no-epetra` and `rhel7_sems-gnu-8.3.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_all-no-epetra`.
This PR resolves JIRA …

Framework: Add nightly build with Epetra stack disabled

---

packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp

It was always improper to hold on to these host views, but SpMV with communication overlap exercises this now.
Part of https://github.com/trilinos/Trilinos/pull/10926

Tpetra: Drop host views before apply, since apply may use the device.

---

packages/amesos2/src/Amesos2_SolverCore_def.hpp
packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp
packages/amesos2/src/Amesos2_Superludist_decl.hpp
packages/amesos2/src/Amesos2_Superludist_def.hpp

Currently the `SuperLU_dist` interface of `Amesos2` allows no row permutation as pre-ordering method. For certain type of matrices a row pre-ordering is a necessary step to be able to factorize the matrix without running into errors. This adds the `LargeDiag_MC64` row permutation option, even though it might be a sequential bottleneck in the algorithm.
Enhancing the `SuperLU_dist` interface of `Amesos2`
Joint work with @vryy and @mayrmt 
See also #11469.

Amesos2: Add row permutation option to SuperLU_dist

---

packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
packages/tpetra/core/test/inout/CMakeLists.txt
packages/tpetra/core/test/inout/Issue11704.cpp

Instead of updating the row-pointer array only when we find a non-zero, use the previously-computed `numEntriesPerRow`. This prevents us from missing any rows after the last non-zero.
Resolve https://github.com/trilinos/Trilinos/issues/11704

Tpetra: set all row-pointer entries in readSparse

---

packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp

In ``Tpetra::removeCrsMatrixZeros``, skip the fill-complete if there were no zeros to remove in the local matrices of all ranks (it cannot be skipped on only some ranks, because expertStaticFillComplete might do collectives, so all ranks must participate).
* Closes #11671 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Tested in Tpetra: CrsMatrix_UnitTests4

Tpetra: early exit from CRS remove zeros

---

packages/intrepid2/src/Shared/Intrepid2_Utils.hpp

Compatibility update with Kokkos with eventual 4.1 release
Co-authored-by: Damien L-G <dalg24+github@gmail.com>
Update to enable Trilinos to compile against kokkos' develop branch (currently the eventual 4.1 release)
Local nightly testing issues resolved; AT will add testing

intrepid2: compatibility update has_rank_member

---

packages/muelu/src/Operators/MueLu_RefMaxwell_decl.hpp
packages/muelu/test/meshtying/MeshTyingBlocked_SimpleSmoother.cpp

Nalu was seeing some link errors in MueLu. (Reported in #11719.)
I don't understand what in particular triggers this and the build script looks innocent to me:
https://github.com/NaluCFD/Nalu/blob/master/build/do-configTrilinos_release
I was able to reproduce the link errors using the build script and 
```
-DMueLu_ENABLE_TESTS=ON \                                                                                                                                                                                                                                                                                                                                                       
-DMueLu_ENABLE_EXAMPLES=ON \
```
The changes in this PR seem to fix the issue.

MueLu: Fix build issues seen in Nalu build

---

packages/amesos2/src/Amesos2_Lapack_decl.hpp
packages/amesos2/src/Amesos2_MatrixTraits.hpp

Fix build errors caused by host functions (conversion between std::complex and Kokkos::complex) being called in device code (some copy/conversion functor in Kokkos_CopyViews.hpp). Even though the copy in question was only ever executed on host, the functor body was getting compiled for both host and device.
The fix was to just add a typedef ``Amesos2::MatrixTraits<Matrix>::impl_scalar_type``, and use that as the value type for views in ``Amesos2::Lapack``. 
Allows amesos2 to build cleanly when HIP and complex are enabled. This issue was reported directly by a Sandia user of Trilinos and I was able to replicate it easily on Caraway (edit: this was before I saw the issues about it)
Note: only hipcc seems to treat "calling host from host/device" as an error by default - on …

Amesos2: fix build with HIP, complex enabled

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp
packages/tpetra/core/src/CMakeLists.txt
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp

Fix all Tpetra tests in a build with both Cuda and OpenMP nodes enabled.
Most issues were caused by non-thread-safe WrappedDualView functions being used in host-parallel kernels. Fixed this by disabling the WrappedDualView "sync path" parallel kernels. As a side effect this reduces a bit of overhead by skipping the reference-count checks.
In SpGEMM-Jacobi, the issues were just that the Kokkos default device was being used for temporary views, so it was trying to use e.g. CudaSpace views inside an OpenMP kernel. Fixed by using the Node's device type for those views.
Fixes some actual bugs - non-thread-safe WrappedDualView functions were being used inside parallel kernels.
See #10569 - getting this configuration to work was requested by @romintomasetti 
Yes, all changes …

Tpetra: fix tests with both Cuda & OpenMP

---

TPLsList.cmake
cmake/TPLs/FindTPLROCBLAS.cmake
cmake/TPLs/FindTPLROCSPARSE.cmake
packages/kokkos-kernels/cmake/Dependencies.cmake

This PR aims to add rocblas and rocsparse as some tpls for Trilinos.
That will permit to drive the corresponding kokkos-kernel options directly from Trilinos.
#11359
#10640

Added ROCBLAS and ROCSPARSE Dependencies for Kernels package

---

packages/stokhos/cmake/Dependencies.cmake

The Kokkos_StaticCrsGraph.hpp file is included in several files in stokhos/src/kokkos, which is in the KokkosContainers subpackage. That is an optional dependency in the Dependencies.cmake file, so those headers are not installed if optional dependencies are not included.  The result is a build failure in Xyce because, when Stokhos is enabled, that header is not found.  By moving KokkosContainers to a required dependency, this build failure goes away.

Stokhos: Moves KokkosContainers from an optional to a required dependency

---

packages/muelu/test/unit_tests/MueLu_Test_ETI.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_main.cpp
packages/tpetra/core/src/CMakeLists.txt
packages/tpetra/core/src/Tpetra_Core.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
packages/tpetra/core/src/Tpetra_Details_DeepCopyTeuchosTimerInjection.cpp
packages/tpetra/core/src/Tpetra_Details_DeepCopyTeuchosTimerInjection.hpp

Issue: #11767
Tests: Added to FEM Assembly
Stakeholder feedback: F2F discussions w/ Glusa.
You can do this in one of three ways:
1. Specifically call a function to turn it on
2. Use a command-line argument via the MueLu ETI Helper
3. Use the  TPETRA_TIME_KOKKOS_DEEP_COPY environment variable.
Kokkos Profiling hooks FTW

Tpetra: Adding support for Kokkos::deep_copy tracking via Teuchos timers

---

packages/muelu/test/unit_tests/Hierarchy.cpp

Closes #11773.
I have no clue if this will even be noticed by testing since I assume testing enables the majority of packages, but I think this is the best way to fix the test on builds without Zoltan2.

MueLu: Guard repartition option in hierarchy write unit test by HAVE_MUELU_ZOLTAN2

---

packages/stk/stk_ngp_test/stk_ngp_test/GlobalReporter.cpp
packages/stk/stk_util/stk_util/ngp/NgpSpaces.hpp

@trilinos/stk
This pull request fixes compiling `Trilinos with `STK` using `Kokkos`' SYCL` backend for support of `Intel` GPUs needed by ATDM.
Compiling `Trilinos` with `STK` with `Kokkos`' `SYCL` backend.

STK: Fix compiling with SYCL

---

packages/ifpack/src/Ifpack_Hypre.cpp
packages/ifpack/src/Ifpack_Hypre.h
packages/ifpack/utils/parseHypre.py
packages/ifpack2/src/Ifpack2_Hypre_FunctionParameters.hpp
packages/ifpack2/src/Ifpack2_Hypre_decl.hpp
packages/ifpack2/src/Ifpack2_Hypre_def.hpp
packages/ifpack2/utils/parseHypre.py

@trilinos/ifpack @trilinos/ifpack2 
A recent change in Hypre exposed a bug in both the Ifpack and the Ifpack2 interfaces to Hypre:
- functions with args "double, int" were treated as "int, double" but because so far there was not such function this didn't result in compile errors.
https://github.com/xsdk-project/xsdk-issues/issues/213

Ifpack+Ifpack2: Fix Hypre interfaces

---

packages/ifpack2/doc/UsersGuide/ifpack2guide.bib
packages/ifpack2/doc/UsersGuide/options.tex
packages/ifpack2/src/Ifpack2_Details_Chebyshev_Weights.hpp
packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestChebyshev2.cpp
packages/muelu/test/interface/default/Output/MLsmoother4_tpetra.gold
packages/muelu/test/interface/default/Output/default_e3d_tpetra.gold
packages/muelu/test/interface/default/Output/default_p2d_tpetra.gold
packages/muelu/test/interface/default/Output/default_p3d_tpetra.gold
packages/muelu/test/interface/default/Output/driver_drekar1_np4_tpetra.gold
packages/muelu/test/interface/default/Output/driver_drekar1_tpetra.gold
packages/muelu/test/interface/default/Output/driver_drekar2_np4_tpetra.gold
packages/muelu/test/interface/default/Output/driver_drekar2_tpetra.gold
packages/muelu/test/interface/default/Output/smoother12_tpetra.gold
packages/muelu/test/interface/default/Output/smoother13_tpetra.gold
packages/muelu/test/interface/default/Output/smoother5_tpetra.gold
packages/muelu/test/interface/default/Output/smoother9_tpetra.gold
packages/muelu/test/interface/kokkos/Output/MLsmoother4_tpetra.gold
packages/muelu/test/interface/kokkos/Output/default_e3d_tpetra.gold
packages/muelu/test/interface/kokkos/Output/default_p2d_tpetra.gold
packages/muelu/test/interface/kokkos/Output/default_p3d_tpetra.gold
packages/muelu/test/interface/kokkos/Output/driver_drekar1_np4_tpetra.gold
packages/muelu/test/interface/kokkos/Output/driver_drekar1_tpetra.gold
packages/muelu/test/interface/kokkos/Output/driver_drekar2_np4_tpetra.gold
packages/muelu/test/interface/kokkos/Output/driver_drekar2_tpetra.gold
packages/muelu/test/interface/kokkos/Output/smoother12_tpetra.gold
packages/muelu/test/interface/kokkos/Output/smoother13_tpetra.gold
packages/muelu/test/interface/kokkos/Output/smoother5_tpetra.gold
packages/muelu/test/interface/kokkos/Output/smoother9_tpetra.gold

@jhux2 @csiefer2
#11721 
Add in fourth-kind Chebyshev polynomial smoothing, which in certain cases may outperform the first-kind Chebyshev polynomial smoothers.
* Closes #11721 
Added test coverage through `packages/ifpack2/test/unit_tests/Ifpack2_UnitTestChebyshev2.cpp`

Ifpack2: Add implementation of fourth-kind chebyshev polynomial smoothers

---

packages/panzer/adapters-stk/example/PoissonInterfaceTpetra/main.cpp

The Poisson interface test was failing the trilinos sync in empire. Kokkos::finalize was being called twice (in the dtor of GlobalMPISession and then again at the end of main). ctest was always declaring this test a success based o screen output ("TEST PASSED") even though kokkos was throwing an exception for calling finalize at the very end of main.

Panzer: fix Poisson interface test

---

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

Needed before execution-space instance enabled import/export for SpMV communication-computation overlap: https://github.com/trilinos/Trilinos/pull/10926
Replaces https://github.com/trilinos/Trilinos/pull/11736, which was made against master and got an autotest attached to it that couldn't pass

Tpetra: execution space instances in MultiVector unpackAndCombine

---

.github/workflows/title_to_mention.yml

This should dramatically cut down on the mentions.
In the current version, it would check the title *and* the label every time a label was added.  Now it will only check the title on open.

Actions: Cleanup to the automentioner

---

packages/stratimikos/src/Stratimikos_LinearSolverBuilder_def.hpp

CC: @alanw0, @rppawlo, @csiefer2, @hpacella 
This fixes a build error for a configuration reported by @alanw0 for a build related to STK for a particular set of optional package builds.  (There was no GitHub Issue created for this error.)
This is related to the changes in PR:
* #11739 
which is part of:
* #11730 
I was able to reproduce the build error:
```
In file included from /ascldap/users/rabartl/Trilinos.base2/Trilinos/packages/stratimikos/src/Stratimikos_LinearSolverBuilder.cpp:46:
/ascldap/users/rabartl/Trilinos.base2/Trilinos/packages/stratimikos/src/Stratimikos_LinearSolverBuilder_def.hpp:620:41: error: use of undeclared identifier 'Tpetra'
Thyra::Ifpack2PreconditionerFactory<Tpetra::CrsMatrix<Scalar>>>(),
^
/ascldap/users/rabartl/Trilinos.base2/Trilinos/packages/stratimikos/src/ …
```

Add missing include of Tpetra_CrsMatrix.hpp (#11730)

---

packages/tpetra/core/src/CMakeLists.txt
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_Details_WrappedDualView.cpp
packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp

In #11679, the WDV "sync path" was disabled when in a host-parallel region. However, it turns out that ``Serial::in_parallel()`` always returns false, so ``Kokkos::parallel`` kernels running on Serial would still suffer the overhead of WDV tracking. This brings back the explicit enable/disable of WDV tracking. This means a few more lines of boilerplate, but it fixes perf regression #11820, and as a bonus makes the fillComplete in FEAssembly perf test 20% faster than before #11679.
Fix major performance regression
* Closes #11820 
* Blocks 
* Follows #11679 
* Precedes 
* Related to 
* Part of 
* Composed of

Tpetra: fix #11820

---

packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp
packages/xpetra/src/MultiVector/Xpetra_MultiVector_decl.hpp
packages/xpetra/src/Vector/Xpetra_EpetraIntVector.hpp

@trilinos/muelu @maxfirmbach 
This should resolve most of the issues related to #11806. There were missing implementations for `getDeviceLocalView` and `getHostLocalView` for `Xpetra::EpetraIntMultiVectorT` and `Xpetra::EpetraIntVectorT`, which caused the reported runtime errors. I believe these errors were introduced by #11726, as we now use `Xpetra::LOVector` and `Xpetra::LOMultiVector` types as members in the `Aggregates` class.
I don't think anything tests the Epetra stack anymore, but I went from 67 failing MueLu tests in the supplied configuration to 34 failing MueLu tests. That sounds bad, but a lot of the tests in the supplied configuration fail with errors like:
```
11:   Error: running in Tpetra mode, but MueLu with Amesos2 was disabled during the configure stage.
11:   Please …
```

Xpetra: Add getLocalView implementations to EpetraInt Vector and MultiVector

---

packages/amesos2/src/Amesos2_MUMPS_FunctionMap.hpp
packages/amesos2/src/Amesos2_MUMPS_decl.hpp
packages/amesos2/src/Amesos2_MUMPS_def.hpp

This PR updates Amesos2_MUMPS code to remove the deprecated codes.
* https://github.com/trilinos/Trilinos/issues/11813
```
Start 1: Amesos2_KLU2_UnitTests_MPI_2
1/7 Test #1: Amesos2_KLU2_UnitTests_MPI_2 .........................   Passed    1.50 sec
Start 2: Amesos2_KLU2_Solver_Test_MPI_2
2/7 Test #2: Amesos2_KLU2_Solver_Test_MPI_2 .......................   Passed    1.79 sec
Start 3: Amesos2_LAPACK_Solver_Test_MPI_4
3/7 Test #3: Amesos2_LAPACK_Solver_Test_MPI_4 .....................   Passed    1.60 sec
Start 4: Amesos2_MUMPS_UnitTests_MPI_4
4/7 Test #4: Amesos2_MUMPS_UnitTests_MPI_4 ........................   Passed    1.55 sec
Start 5: Amesos2_SolverFactory_UnitTests_MPI_4
5/7 Test #5: Amesos2_SolverFactory_UnitTests_MPI_4 ................   Passed    1.57 sec
Start …
```

Amesos2_MUMPS : remove deprecated code

---

packages/amesos2/src/Amesos2_MUMPS_TypeMap.hpp
packages/amesos2/src/Amesos2_MUMPS_decl.hpp
packages/amesos2/src/Amesos2_MUMPS_def.hpp

This PR fixed errors compiling Amesos2::MUMPS with complex scalar type
https://github.com/trilinos/Trilinos/issues/10667
```
Start 1: Amesos2_KLU2_UnitTests_MPI_2
1/7 Test #1: Amesos2_KLU2_UnitTests_MPI_2 .........................   Passed    1.68 sec
Start 2: Amesos2_KLU2_Solver_Test_MPI_2
2/7 Test #2: Amesos2_KLU2_Solver_Test_MPI_2 .......................   Passed    2.09 sec
Start 3: Amesos2_LAPACK_Solver_Test_MPI_4
3/7 Test #3: Amesos2_LAPACK_Solver_Test_MPI_4 .....................   Passed    1.62 sec
Start 4: Amesos2_MUMPS_UnitTests_MPI_4
4/7 Test #4: Amesos2_MUMPS_UnitTests_MPI_4 ........................   Passed    2.07 sec
Start 5: Amesos2_SolverFactory_UnitTests_MPI_4
5/7 Test #5: Amesos2_SolverFactory_UnitTests_MPI_4 ................   Passed    1.65 sec …
```

Amesos2_MUMPS : fix compilation with complex scalar type

---

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/test/unit_tests/Hierarchy.cpp

This is a more appropriate resolution for #11773/#11774. The `#ifdef` logic in `ParameterListInterpreter` was a little messy, as evidenced by an `#ifdef HAVE_MPI` nested inside an `#ifdef HAVE_MPI`, which I also removed. Now the ParameterListInterpreter will turn repartitioning off and print an appropriate warning if the user does not have both MPI and Zoltan/Zoltan2.
Therefore, I don't think I need to guard repartitioning in the hierarchy test with `HAVE_MPI` or `HAVE_MUELU_ZOLTAN2` since that logic now falls on the `ParameterListInterpreter`.
Previous behavior: If the user requests repartitioning and does not have MPI, it will print a warning and turn repartitioning off. If the user requests repartitioning and has MPI enabled but does not have Zoltan2 enabled, it will …

MueLu: Update ParameterListInterpreter to disable repartitioning if Zoltan/Zoltan2 are unavailable

---

packages/tpetra/.clang-format
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
packages/tpetra/core/src/Tpetra_Details_ExecutionSpaces.cpp
packages/tpetra/core/src/Tpetra_Details_ExecutionSpaces.hpp
packages/tpetra/core/src/Tpetra_Details_ExecutionSpacesSlot.hpp
packages/tpetra/core/src/Tpetra_Details_ExecutionSpacesUser.hpp
packages/tpetra/core/test/CMakeLists.txt
packages/tpetra/core/test/Spaces/CMakeLists.txt
packages/tpetra/core/test/Spaces/SpaceUser.cpp
packages/tpetra/core/test/Spaces/Spaces.cpp

Adds `Tpetra::Details::ExecutionSpaces` namespace with a variety of free functions to create and cache Kokkos execution space instances. In this PR, only `Kokkos::Cuda` execution space instances are special-cased for performance, but all backends are supported.
Adds `Tpetra::Details::ExecutionSpaces::User` which a Tpetra object can inherit from, which provides a couple utility functions to access execution space instances and scope those instances to the lifetime of the object.
Makes `Tpetra::CrsMatrix` a `Tpetra::Details::ExecutionSpaces::User` but since `Tpetra::CrsMatrix` is otherwise unchanged, has no impact on its behavior.
Adds a `.clang-format` file generated by clang-format-8 in the LLVM style (`clang-format-8 --style=LLVM --dump-config`) for a consistent format …

Tpetra: Add `Tpetra::Details::Spaces`, `...::Slot`, and `...::User`

---

packages/panzer/adapters-stk/test/periodic_bcs/periodic_32bit_int_limit.cpp

remove use of scope guard in unit test. kokkos is already initialized in the global mpi session object
Closes #11856

Panzer: remove kokko scope guard from unit test

---

packages/aztecoo/src/az_aztec.h
packages/aztecoo/src/az_util.c

@trilinos/aztecoo
Summary of changes:
* Correct signatures of the functions AZ_manage_memory, AZ_allocate and AZ_realloc;
* Correct type of the size field of the mem_ptr and widget structs;
* Correct types of some local variables;
* Correct conversions of/to integer types.
Issue #10334
N/A

aztecoo: Fix memory corruption in the AZ_pgmres function

---

packages/anasazi/epetra/util/ModeLaplace/ModeLaplace1DQ1.cpp
packages/anasazi/src/AnasaziFactory.hpp
packages/anasazi/thyra/example/MVOPTester/CMakeLists.txt
packages/anasazi/thyra/test/MVOPTester/CMakeLists.txt

The new dashboard for memory leaks in Trilinos has identified an issue in the Anasazi utiltity that generates test problems for the eigensolver.
https://trilinos-cdash.sandia.gov/index.php?project=Trilinos#!/%23DynamicAnalysis
While checking this issue, I noticed a build warning in the solver factory and potential issues in building the Thyra examples and tests.
This commit addresses all these minor issues.
OSX GCC12 / RHEL7 Intel 19.x

Anasazi: Minor cleanup to address build warnings and memory leaks

---

packages/stokhos/src/sacado/kokkos/pce/tpetra/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels_UQ_PCE.hpp
packages/stokhos/src/sacado/kokkos/vector/Kokkos_Parallel_MP_Vector.hpp
packages/stokhos/src/sacado/kokkos/vector/tpetra/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels_MP_Vector.hpp
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp

Needed before execution-space instance enabled import/export for SpMV communication-computation overlap: https://github.com/trilinos/Trilinos/pull/10926

Tpetra: execution space instances in MultiVector packAndPrepare

---

packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp

Mark various overridden MultiVector functions `override`, which will issue an error if the DistObject interface changes.
This also silences `-Winconsistent-override` warnings.

Tpetra: Mark MultiVector functions as override to silence warnings

---

packages/teuchos/core/src/Teuchos_Utils.cpp

`sprintf` is deprecated in macOS 13, and issues warnings like this during the build:
```
.../Trilinos/packages/teuchos/core/src/Teuchos_Utils.cpp:107:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
std::sprintf(s, "%g", x);
```
`snprintf` has been available since c++11 and is a suitable replacement in this circumstance.

Teuchos: sprintf -> snprintf in Teuchos_Utils.cpp

---

packages/epetra/src/Epetra_Object.h

@trilinos/epetra 
`sprintf` is deprecated in macOS 13, and issues warnings like this during the build:
```
warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
```
`snprintf` has been available since c++11 and is a suitable replacement in this circumstance.

Epetra: sprintf -> snprintf in Epetra_Object.h

---

packages/framework/ini-files/config-specs.ini

Clean up NVIDA warnings in Trilinos, as requested by @crtrott . See TRILFRAME-396 for more details.
* Follows #7346

Add NVIDIA warnings-as-errors build to nightly testing

---

packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp

@trilinos/ml 
This was issuing a warning in one of my builds
See https://github.com/trilinos/Trilinos/issues/11881 for discussion of why `snprintf` may be preferable to`sprintf` in this context.

ML: sprintf -> snprintf

---

packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp
packages/trilinoscouplings/examples/fenl/CMakeLists.txt
packages/trilinoscouplings/examples/fenl/SampleGrouping.hpp
packages/trilinoscouplings/examples/fenl/fenl_functors.hpp
packages/trilinoscouplings/examples/fenl/fenl_functors_pce.hpp
packages/trilinoscouplings/examples/fenl/fenl_impl.hpp

FENL hasn't been built since the Tpetra Kokkos Refactor macro was removed from Tpetra but not FENL.  This gets the code running again with updates to Kokkos.

TrilinosCouplings:  Get FENL running again.

---

packages/nox/test/epetra/1Dfem/1DfemStratimikos.C

`success` is initialized to `false` and only changed if `TEUCHOS_STANDARD_CATCH_STATEMENTS()` catches.  `success` should be set based on the solver status.  The other versions of the 1DfemStratimikos tests already do this.
@trilinos/nox
Discovered while investigating MPI exit hangs discussed in https://github.com/trilinos/Trilinos/issues/11530
Related to https://github.com/trilinos/Trilinos/issues/11530

NOX: fix exit status of 1DfemStratimikos test

---

packages/trilinoscouplings/cmake/Dependencies.cmake
packages/trilinoscouplings/examples/fenl/fenl_utils.cpp
packages/trilinoscouplings/examples/fenl/main_ensemble.cpp

I could have replaced this with the Dakota TPL, but that would still need to be maintained, and it is unclear if this code even still works, so I decided to just remove it completely.
@ccober6

TrilinosCouplings:  Remove usage of TriKota from FENL

---

packages/seacas/libraries/ioss/src/Ioss_SmartAssert.C
packages/seacas/libraries/ioss/src/main/cgns_decomp.C
packages/seacas/libraries/ioss/src/main/sphgen.C
packages/seacas/libraries/ioss/src/utest/Utst_map.C
packages/seacas/libraries/ioss/src/utest/Utst_structured_decomp.C
packages/seacas/libraries/ioss/src/utest/Utst_structured_decomp_rocket.C
packages/seacas/libraries/ioss/src/utest/Utst_utils.C

This should get rid of the warnings showing up during the nvidia builds.

Eliminate nvidia warnings

---

packages/belos/tpetra/test/TFQMR/test_tfqmr_hb.cpp

While investigating MPI exit hangs discussed in https://github.com/trilinos/Trilinos/issues/11530 we found that some unit tests were declaring success (and passing the teuchos unit test harness  based on printing the string "TEST PASSED") yet still returning non-zero exit codes to mpi. The non-zero exit code is one possible path to triggering the mpi hangs.
success is initialized to false and only changed if the TEUCHOS_STANDARD_CATCH_STATEMENTS() catches. success should be set based on the solver status.
Related to https://github.com/trilinos/Trilinos/issues/11530

Belos: fix return value on unit test

---

packages/ifpack2/src/Ifpack2_DatabaseSchwarz_def.hpp

@trilinos/ifpack2 @cgcgcg
This speeds up the `Compute()` phase of `DatabaseSchwarz` by at least 8%-10% based on 1M DOF runs I was testing on Attaway thanks to a comment made by @rstumin earlier today.
This breaks out of the compression check loop if the accumulated difference already exceeds the tolerance, which helps immensely, especially as the patch size increases. There should be almost no performance hit because even the most basic branch prediction will handle this in an efficient manner.

Ifpack2: Speed up DatabaseSchwarz::Compute

---

packages/fei/unit_tests_base/CMakeLists.txt
packages/fei/unit_tests_base/fei_ubase.cpp

temporary disable of unit test causing an issue in #11530

FEI: temporarily disable failing unit tests

---

packages/tpetra/core/src/Tpetra_ConfigDefs.hpp
packages/xpetra/src/Headers/Xpetra_ConfigDefs.hpp

`std::binary_function` (https://en.cppreference.com/w/cpp/utility/functional/binary_function) has been deprecated since C++11 and removed in C++17. Recent compilers like `clang 16` don't include this class anymore in their STL implementation.
std::binary_function only provides aliases for `first_argument_type`, `second_argument_type`, and `result_type` which the classes in question already provide anyway.
* Related to #11920
Compiling Trilinos with Tpetra and clang-16.

 Xpetra: Don't use std::binary_function 

---

packages/sacado/src/KokkosExp_View_Fad.hpp
packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp

@trilinos/sacado @trilinos/stokhos 
sacado, stokhos: add exec space instances to allocate_shared
Attempt to resolve #11890
Co-authored-by: Christian Trott <crtrott@sandia.gov>
Also referenced in kokkos/kokkos#6158
These changes have been through a couple rounds of nightly testing and resolve the `Stokhos_KokkosViewMPVectorUnitTest_Cuda_MPI_1` and `Stokhos_KokkosCrsMatrixMPVectorUnitTest_Cuda_MPI_1` failures in Cuda builds with UVM enabled
AT will test more extensively

Sacado, Stokhos: resolve issue #11890

---

packages/tpetra/core/src/Tpetra_ConfigDefs.hpp

`std::binary_function` (https://en.cppreference.com/w/cpp/utility/functional/binary_function) has been deprecated since C++11 and removed in C++17. Recent compilers like `clang 16` don't include this class anymore in their STL implementation.
std::binary_function only provides aliases for `first_argument_type`, `second_argument_type`, and `result_type` which the classes in question already provide anyway.
Compiling Trilinos with Tpetra and clang-16.

Tpetra: Don't use std::binary_function

---

packages/common/auxiliarySoftware/SuiteSparse/src/KLU/Include/trilinos_klu_internal.h

When using OpenMP directly in the KLU wrapper, include omp.h. Previously, this relied on omp.h being included somewhere else (like through Kokkos) but this doesn't always work.
Fixes build errors. KLU wrapper made OpenMP calls without having included omp.h.
* Closes #11867
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
See thread on #11867 
Not a code behavior change

TrilinosSS: include <omp.h> (Fix #11867)

---

packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp

@iyamazaki 
Clang's leak sanitizer was reporting this memory leak in some Sierra tests.
Tested a clang build with Ifpack2 FastILU enabled locally.

fastilu: Fix memory leak.

---

packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp
packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS.hpp

Allows, e.g., static_cast<int>(x) where x is an ensemble, since this is something Kokkos-Kernels does.  Elsewhere in Trilinos we have relied on Teuchos::as<>, but Kokkos-Kernels can't rely on that.
@jhux2

Stokhos:  allow explicit conversions of ensembles to integral types

---

demos/simpleBuildAgainstTrilinos/README.md

@ndellingwood
Fixes #11955
Added explicit mention of needing to pass in compatible compilers to CMake.  This example can't get compilers from `find_package(Trilinos)` for CUDA builds (see https://github.com/trilinos/Trilinos/issues/11955#issuecomment-1584933666).

Improve simpleBuildAgainstTrilinos/README.md

---

packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp

Having singletons doesn't play nicely with the construction of the special prolongator.

MueLu RefMaxwell: Accept "aggregation: phase3 avoid singletons"

---

packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp

Fix for
```
.../Trilinos/packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp:551:16: warning: 'checkSizes' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual bool checkSizes (const Tpetra::SrcDistObject& source);
```

Tpetra: mark `BlockMultiVector::checkSizes` as `override`

---

packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp

Silences warnings like:
```
In file included from .../packages/tpetra/core/src/Tpetra_RowMatrixTransposer_LONG_LONG_INT_LONG_LONG_SERIAL.cpp:67:
In file included from ...packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp:46:
In file included from .../build/packages/tpetra/core/src/Tpetra_BlockCrsMatrix.hpp:1:
In file included from .../packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp:49:
.../packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp:577:3: warning: 'packAndPrepare' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
packAndPrepare
```

Tpetra: mark `BlockMultiVector::{packAndPrepare, unpackAndCombine}` as override

---

packages/intrepid2/src/Cell/Intrepid2_CellTools.hpp
packages/intrepid2/src/Cell/Intrepid2_CellToolsDefRefToPhys.hpp

@trilinos/intrepid2 @mperego
The `Intrepid2` function `mapToPhysicalFrame` allows to map coordinates of points in the reference domain (input) to coordinates in the physical domain (output). We would like to be able to pass in the input coordinates with a const value type. However, this is not currently possible because the value type is passed to a basis factory which expects a non const value type.  
This PR solves this issue by using `std::remove_const_t`.
This change was discussed with @CamelliaDPG at EUTug 2023.

Intrepid2: Pass non const value type to mapToPhysicalFrame.

---

packages/kokkos/cmake/kokkos_install.cmake

* Fix windows symlink configure issue
symlink creation requires elevated privileges
* Update cmake/kokkos_install.cmake
---------
Bug patch to Trilinos

Fix windows symlink configure issue (#6241)

---

packages/phalanx/src/Phalanx_Evaluator_WithBaseImpl_Def.hpp
packages/phalanx/src/Phalanx_Field.hpp
packages/phalanx/src/Phalanx_Field_Def.hpp
packages/sacado/src/KokkosExp_View_Fad.hpp
packages/sacado/src/Kokkos_DynRankView_Fad.hpp

fix deprecation warnings from kokkos 4.1 release in phalanx and sacado

Phalanx/Sacado: Fix kokkos 4.1 deprecation warnings

---

packages/kokkos-kernels/ode/CMakeLists.txt

In CMake, don't export the binary directory kokkos-kernels/ode as an include dir. It doesn't exist since the ODE component has no auto-generated ETI files.
Patch of https://github.com/kokkos/kokkos-kernels/pull/1892.
This will fix errors in PR testing like this one at https://trilinos-cdash.sandia.gov/test/29606177 :
```
Found Tpetra!  Here are the details: 
Tpetra_DIR = /scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/cmake_packages/Tpetra
-- Configuring done
CMake Error in CMakeLists.txt:
Imported target "Tpetra::all_libs" includes non-existent path
"/scratch/trilinos/jenkins/ascic164/workspace/Trilinos_PR_intel-2021.3/pull_request_test/packages/kokkos-kernels/ode"
in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
* The path was …
```

KokkosKernels: remove non-existant include dir

---

packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedGaussSeidelSmoother_def.hpp
packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedJacobiSmoother_def.hpp
packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BraessSarazinSmoother_def.hpp
packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_IndefBlockedDiagonalSmoother_def.hpp
packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_SimpleSmoother_def.hpp
packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_UzawaSmoother_def.hpp
packages/muelu/test/unit_tests/Smoothers/BlockedSmoother.cpp
packages/xpetra/src/BlockedCrsMatrix/Xpetra_ReorderedBlockedCrsMatrix.hpp

If we enter the `BlockedSmoothers` with a reordered/nested matrix, things go wrong in the `Apply()` method if it is called with plain `MultiVector` objects.
It is essential to first do a blocking with a plain `BlockedMap` and afterwards do a reordering based on the `ReorderManager` if the operator is nested. Currently the first step can't be done in a correct way if a nested map is applied, due to a reordered operator.
Thus changing the initial processing of the vectors in the `Apply()` method of each `BlockedSmoother`.
This might not be the perfect way to do this, but it worked for me quite well.
Related to physics-based block-preconditioning.
Also interesting for @mayrmt and @Max-pert

MueLu: Adjust vector processing in blocked smoother Apply() method

---

packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp
packages/tpetra/core/src/Tpetra_Details_Blas.hpp
packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
packages/tpetra/core/src/Tpetra_Details_copyConvert.hpp
packages/tpetra/core/src/Tpetra_Details_fill.hpp
packages/tpetra/core/src/Tpetra_Details_getEntryOnHost.hpp
packages/tpetra/core/src/Tpetra_Details_leftScaleLocalCrsMatrix.hpp
packages/tpetra/core/src/Tpetra_Details_normImpl.hpp
packages/tpetra/core/src/Tpetra_Details_rightScaleLocalCrsMatrix.hpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
packages/tpetra/core/test/HashTable/FixedHashTableTest.cpp

Use ``Kokkos::ALL_t`` instead of ``Kokkos::Impl::ALL_t``, and ``Kokkos::View::rank`` instead of ``Kokkos::View::Rank``.
Also fix a minor warning out of printf from using the wrong format specifier.
Fix a bunch of ``-Wdeprecated-declarations`` warnings. Along with #12003 this fixes all the deprecated warnings in Tpetra after the Kokkos/KokkosKernels 4.1 release.

Tpetra/Teuchos: don't use deprecated Kokkos::Impl::ALL_t, View::Rank

---

packages/seacas/libraries/exodus/src/ex_create_par.c
packages/seacas/libraries/exodus/src/ex_open_par.c

Some mpi-io implementations have a fixed length maximum of ~256 characters for the filename + path.  They sometimes prepend some other information, so there are cases where the maximum available is ~250 characters.  We are hitting close to those limits on some jenkins or other runs with long paths...

EXODUS: Fix for mpi-io with fixed-length path limit

---

packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp

Part of the continuing ML/MueLu harmonization project.  Previously, you couldn't make the nodal aggregation hierarchy sort rows of the coarse A matrices.  This is problematic since Phase 2b aggregation is sensitive to row ordering.  This PR addresses that issue.
Issue: #11214 
Tests: n/a

ML: Adding sorting support for Maxwell1

---

packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp
packages/intrepid2/src/Shared/Intrepid2_TensorPoints.hpp
packages/intrepid2/src/Shared/Intrepid2_TensorViewIterator.hpp

@mperego
@ndellingwood 
Kokkos is looking at deprecating `Kokkos::vector` and may want to emit warnings when that header is included.
Moreover, these header includes are unnecessary since `Kokkos::vector` is currently not actually used in Intrepid2 (nor anywhere else in Trilinos as far as I can tell).
* Related to kokkos/kokkos#6252
N/A

Intrepid2: Avoid including `<Kokkos_Vector.hpp>` header

---

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp

Lazily copy row pointers from device to host, for both packed and unpacked.
In CrsGraph, this can avoid an eager host allocation and/or device-to-host copy. It also improves performance on CudaUVMSpace (or any other Kokkos SharedSpace) by using separate allocations for the host and device rowptrs. Since the data is immutable, this is better than having the same memory pages get passed back and forth at each access.
* Closes #11959 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
<!--- 
Anything else we need to know in evaluating this merge request

Tpetra: fix #11959

---

packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
packages/phalanx/test/Kokkos/CMakeLists.txt
packages/phalanx/test/Kokkos/tKokkosFencing.cpp
packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp

Add support for exec space instances in View of Views.
New unit tests added to ViewOfViews in Phalanx.

Phalanx: exec space instance support in view-of-views

---

packages/framework/pr_tools/PullRequestLinuxDriver.sh
packages/framework/pr_tools/PullRequestLinuxDriverMerge.py
packages/framework/pr_tools/PullRequestLinuxDriverTest.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/jenkinsenv/TrilinosJenkinsEnv.py
packages/framework/pr_tools/trilinosprhelpers/jenkinsenv/unittests/test_TrilinosJenkinsEnv.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverMerge.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py

Won't have access to source_branch any more.
Switch to sha-based merging (not a big deal probably) to do the testing.
Remove the checks around what branches can/cannot be merged to master branch (github rules should take care of this automatically by only allowing the automated system to merge into master branch).
Also removed check for branch tip != SHA1, because that's not possible if we only use the SHA1.  The thing that cancels PR runs and makes you run a new one if it finds changes on the branch after a run starts should handle this issue.
User Support Ticket(s) or Story Referenced: TRILFRAME-573
New autotester is changing its interface a bit, and want to be ready for when it rolls out.

Framework: Remove need for source_branch in all PR scripts

---

packages/intrepid2/src/Shared/Intrepid2_DataCombiners.hpp

Fixes #12037 by replacing a lambda with a functor.
This fixes a failing test.

Intrepid2: fix for #12037.

---

packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp
packages/sacado/src/Kokkos_DynRankView_Fad_Contiguous.hpp
packages/sacado/test/UnitTests/Fad_KokkosTests.hpp

Calling subview() with LayoutContiguous<LayoutLeft> can result in  invalid indexing when the returned view is LayoutStride.  This is because the implementation assumes the right-most index is the fad dimension for all layouts except LayoutLeft, including LayoutStride.  However, if the original view was LayoutLeft, this isn't correct.  I fixed this by interchanging the dimensions in the LayoutStride case.  I also added a test to verify it is correct now by checking the indexing in numerous subview cases.
Also fixed a few uses of deprecated Rank.
Thanks to @rppawlo  for reporting this.

Sacado: Fix subview() for LayoutContiguous<LayoutLeft> views

---

packages/seacas/libraries/exodus/include/exodusII.h
packages/seacas/libraries/exodus/include/exodusII_int.h
packages/seacas/libraries/exodus/src/ex__put_homogenous_block_params.c
packages/seacas/libraries/exodus/src/ex_put_all_var_param_ext.c
packages/seacas/libraries/exodus/src/ex_put_attr_param.c
packages/seacas/libraries/exodus/src/ex_put_block_params.c
packages/seacas/libraries/exodus/src/ex_put_concat_all_blocks.c
packages/seacas/libraries/exodus/src/ex_put_concat_elem_block.c
packages/seacas/libraries/exodus/src/ex_put_init_ext.c
packages/seacas/libraries/exodus/src/ex_put_map_param.c
packages/seacas/libraries/exodus/src/ex_put_reduction_variable_param.c
packages/seacas/libraries/exodus/src/ex_put_variable_param.c

There are some older versions of netCDF that do not include the `nc_def_var_fill` call.  To avoid breaking the builds
of people using those versions, made the recent change that called that function only present if the netcdf library has the call enabled.

EXODUS: Need to check whether nc_def_var_fill is defined in netCDF

---

packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp

Closes #12053 
UVM=ON builds were failing.

Phalanx: fix exec space instance init for UVM=ON

---

packages/seacas/applications/aprepro/aprepro.C
packages/seacas/libraries/aprepro_lib/CMakeLists.txt
packages/seacas/libraries/aprepro_lib/apr_aprepro.cc
packages/seacas/libraries/aprepro_lib/apr_test.cc

Recent changes to reduce duplicate parsing code and hopefully make parsing more robust broke the short-argument parsing of --include / -I.  This fixes that and adds a test to make sure it keeps working.  Also extend the use of the include path to apply to input file specified on the execution command line.

APREPRO: Fix -I parsing; use include_path on input file

---

packages/stratimikos/example/tpetra/CMakeLists.txt

Fixes #11983
@trilinos/stratimikos @trilinos/amesos2 
The example fails when Amesos2 was enabled, but not Klu2.

Stratimikos: Enable Amesos2 example only when Klu2 is available

---

packages/phalanx/src/Phalanx_Kokkos_Tools_CheckStreams.cpp
packages/phalanx/src/Phalanx_Kokkos_Tools_CheckStreams.hpp
packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp

Utility to enforce that certain functions don't use the default cuda execution space instance. Relies on kokkos-tools callbacks.
unit tests added in phalanx

Phalanx: add utils to enforce non-default streams via kokkos-tools

---

packages/stokhos/src/kokkos/Stokhos_Multiply.hpp
packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
packages/stokhos/src/sacado/kokkos/pce/Kokkos_View_UQ_PCE_Fwd.hpp
packages/stokhos/src/sacado/kokkos/pce/Kokkos_View_UQ_PCE_Utils.hpp
packages/stokhos/src/sacado/kokkos/pce/tpetra/Tpetra_Details_fill_UQ_PCE.hpp
packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp
packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Interlaced.hpp
packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp
packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_SFS.hpp
packages/stokhos/src/sacado/kokkos/vector/tpetra/Tpetra_Details_fill_MP_Vector.hpp

For PR #11840.
Also remove deprecated use of View::Rank.

Stokhos:  Make integral conversion available to expressions, not just Vectors

---

cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc-cuda.cmake

Remove the deprecated UVM flag, see
https://testing.sandia.gov/cdash/build/11578770/configure

Geminga: Remove deprecated flag

---

packages/framework/ini-files/config-specs.ini
packages/framework/pr_tools/PullRequestLinuxDriverMerge.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverMerge.py

If it exists as a ref on source_remote, check it out as such.  This allows passing a branch or a SHA as a ref.
User Support Ticket(s) or Story Referenced: TRILFRAME-567
Nightly/scheduled runs tend to use branch names as opposed to SHAs.

Framework: Fix checkouts of branches

---

packages/framework/ini-files/config-specs.ini

add rhel7_sems-intel-2021.3-sems-openmpi-4.0.5_release-debug_shared_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-off_all.  This is a smoke test for disabling deprecated code.
See [TRILFRAME-578](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-578) for more details.
As any user of Trilinos, I do not want to use deprecated code.
As a Trilinos package developer, I do not want to be allowed to use deprecated code within other Trilinos packages.

add build with deprecated off

---

packages/kokkos-kernels/common/src/KokkosKernels_BlockHashmapAccumulator.hpp
packages/kokkos-kernels/common/src/KokkosKernels_HashmapAccumulator.hpp
packages/kokkos-kernels/common/src/KokkosKernels_Macros.hpp
packages/kokkos-kernels/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp

To fix HashmapAccumulator (used in spgemm, graph coarsening) on Ada & Hopper architectures.
See https://github.com/kokkos/kokkos-kernels/pull/1927 for original PR and https://github.com/kokkos/kokkos-kernels/issues/1891 for the original issue.
Spgemm and graph coarsening unit tests were failing on Hopper, but now they pass.

KokkosKernels: patch in PR 1927

---

packages/panzer/adapters-stk/src/evaluators/Panzer_STK_GatherFields_impl.hpp
packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgQuantity_impl.hpp
packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgVector_impl.hpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
packages/panzer/adapters-stk/test/gather_scatter_evaluators/gs_evaluators.cpp
packages/panzer/adapters-stk/test/stk_interface_test/tPamgenMeshFactory.cpp
packages/panzer/adapters-stk/test/stk_interface_test/tPointLocationSearch.cpp
packages/panzer/adapters-stk/test/stk_interface_test/tSTKInterface.cpp

This essentially removes all usage of the template parameters beyond just the datatype in `stk::mesh::Field`s.  This makes setting the size of a `Field` a run-time configuration option through calls to `stk::mesh::put_field_on_mesh()` and keeps the datatype (double, int, etc.) a compile-time configuration option.  Functions like `stk::mesh::MetaData::declare_field()` and `stk::mesh::MetaData::get_field()` now just pass the datatype as a template parameter instead of the whole templated `Field` type itself.
The `stk::mesh::MetaData::use_simple_fields()` method is called early in `MetaData` construction to force the new behavior, to prevent any accidental regressions and to ensure that any auto-registered `Field`s (like coordinates) will be sized consistently by things like …

Converted Panzer to the new STK simple_fields workflow

---

packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_decl.hpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp

Reverts trilinos/Trilinos#12036, due to problems downstream in Empire.

Revert "Tpetra: move unpack and combine to device in TAFC"

---

packages/framework/ini-files/config-specs.ini

Spec was inheriting from another that was non-working.  Correct it to align with older MPI modules.

Framework: Correct spec inheritance for CXX20 build

---

packages/framework/pr_tools/LaunchDriver.py
packages/framework/pr_tools/PullRequestLinuxDriver.sh
packages/framework/pr_tools/SetKokkosDevelop.sh

As a Kokkos/KokkosKernels developer, I want Trilinos developers to know about issues with integrating a newer version of these core packages as early as possible, to decrease the effort of a single person overseeing the integration.
As a Trilinos developer, I want the most current Kokkos/KokkosKernels as is feasible to enable new capability.
As a Trilinos customer, I want the most current version of all packages as soon as possible, particularly for use on advanced new platforms.
See TRILFRAME-571 for more details.

Add option to test against develop for kokkos and kokkos-kernels packages

---

packages/tpetra/core/compat/Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.hpp

@trilinos/tpetra @csiefer2 
For all other GPU backends supported by `Tpetra`, i.e., `Cuda` and `HIP`, the memory space for the wrapper node is a device native space anymore, not a shared space. This discrepancy for `SYCL` causes issues in a lot of places that are not ready to use mixed memory spaces, also see https://github.com/trilinos/Trilinos/pull/12119.
This pull request makes sure that the `SYCL` implementation is conforming and also uses a device memory space for the wrapper node.
* Related to #12119 
Compiling `Trilinos` with `Belos` and all required dependencies.

Tpetra: Use Kokkos::Experimental::SYCLDeviceUSMSpace for KokkosSYCLWrapperNode

---

packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasisFamily.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasisFamily.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_IntegratedLegendreBasis_HGRAD_PYR.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_LegendreBasis_HVOL_PYR.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_LegendreBasis_HVOL_PYR_ETI.cpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_LegendreBasis_HVOL_TRI.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_PyramidCoords.hpp
packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HGRAD.hpp
packages/intrepid2/unit-test/MonolithicExecutable/BasisCardinalityTests.cpp
packages/intrepid2/unit-test/MonolithicExecutable/SubBasisInclusionTests.cpp
packages/intrepid2/unit-test/Orientation/CMakeLists.txt
packages/intrepid2/unit-test/Orientation/eti/test_orientation_PYR_QuadFace_newBasis_ETI.in
packages/intrepid2/unit-test/Orientation/eti/test_orientation_PYR_TriFace_newBasis_ETI.in
packages/intrepid2/unit-test/Orientation/test_orientation_HEX_newBasis.hpp
packages/intrepid2/unit-test/Orientation/test_orientation_PYR_QuadFace_newBasis.hpp
packages/intrepid2/unit-test/Orientation/test_orientation_PYR_TriFace_newBasis.hpp

This PR adds an arbitrary-order, hierarchical basis for H(vol) on the pyramid.  This follows #12079, which added hierarchical bases for H(grad) on the pyramid.
Additionally, this PR adds "sub-basis inclusion" tests for both H(vol) and H(grad) on the pyramid, and orientation tests against H(grad) on the pyramid.
This PR includes "sub-basis inclusion" tests for both H(vol) and H(grad) on the pyramid, and orientation tests against H(grad) on the pyramid.  It also adds a simple basis cardinality test for the new H(vol) basis.
Additionally, I have done offline comparison with the ESEAS implementation of this basis, testing up to 10th order, with excellent agreement.  I hope to include these tests with Intrepid2 soon; this has been prevented previously by the license for …

Intrepid2 add H(vol) hierarchical pyramids

---

packages/ifpack2/src/Ifpack2_MDF_def.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestMDF.cpp
packages/kokkos-kernels/sparse/impl/KokkosSparse_mdf_impl.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_mdf.hpp

Fixes issue with ambiguous MDF unit with multiple valid permutations so that it is not sensitive to locale (order of operations, etc).

ifpack2: fix ambiguous MDF unit test

---

packages/framework/pr_tools/PullRequestLinuxDriver.sh

Hotfix for PR https://github.com/trilinos/Trilinos/pull/12126. See link for context.
Remove leading `.` to execute script correctly.

Fix to call SetKokkosDevelop.sh correctly

---

packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
packages/muelu/test/interface/CreateOperator.cpp
packages/muelu/test/scaling/ComboPDriver.cpp

@trilinos/muelu @cgcgcg 
Fixes irksome messages while compiling MueLu.
Introduced by #12006
```
In file included from /home/graham/Programming/cpp/Trilinos/Trilinos-build/packages/muelu/src/Utils/ExplicitInstantiation/ETI_MueLu_CoalesceDropFactory.cpp:55:
/home/graham/Programming/cpp/Trilinos/Trilinos-source/packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp: In member function ‘void MueLu::CoalesceDropFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Build(MueLu::CoalesceDropFactory<Scalar, LocalOrdinal, GlobalOrdinal, Node>::Level&) const’:
/home/graham/Programming/cpp/Trilinos/Trilinos-source/packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp:336:5: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
336 | …
```

MueLu: cleanup errors

---

packages/adelus/src/Adelus.hpp
packages/adelus/src/Adelus_global_comm.hpp

@trilinos/adelus 
This PR is part of the initiative to phase out the use of `MPI_COMM_WORLD` in Trilinos.

Adelus: Don't use hardcoded `MPI_COMM_WORLD`

---

packages/anasazi/epetra/src-rbgen/RBGenDriver_EpetraMV.cpp
packages/anasazi/epetra/src-rbgen/RBGen_AnasaziPOD.cpp
packages/anasazi/epetra/src-rbgen/RBGen_BurkardtFileIOHandler.cpp
packages/anasazi/epetra/src-rbgen/RBGen_EpetraCrsMatrixFileIOHandler.cpp
packages/anasazi/epetra/src-rbgen/RBGen_LapackPOD.cpp
packages/anasazi/epetra/src-rbgen/RBGen_MatrixMarketFileIOHandler.cpp
packages/anasazi/epetra/src-rbgen/RBGen_NetCDFFileIOHandler.cpp
packages/anasazi/src/AnasaziBasicOutputManager.hpp
packages/anasazi/src/AnasaziGlobalComm.hpp
packages/anasazi/src/ModalAnalysisSolvers/AMGOperator.cpp

This PR is part of the initiative to phase out the use of `MPI_COMM_WORLD` in Trilinos.

Anasazi: Add global MPI communicator that can be used instead of hardcoded `MPI_COMM_WORLD`

---

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp

- In packed storage, locally indexed case, just use the extent of lcl indices for ``getLocalNumEntries()``
- In ``allocateIndices()``, use the return value of ``computeOffsetsFromCounts`` functions instead of reading from rowptrs
- Fix bug in ``computeOffsetsFromConstantCount()`` where incorrect total was returned
- In ``CrsGraph::getLocalAllocationSize()``, use the lengths of indices views instead of reading from host rowptrs
- In ``CrsMatrix::allocateValues()`` use the graph's allocated size instead of reading from rowptrs
Makes it possible to skip the device->host copy of packed rowptrs, in an ordinary ``CrsGraph::fillComplete``.
* Closes #12148
* Blocks 
* Follows #12009
* Precedes
* Related to 
* Part of 
* Composed of

Tpetra: fix #12148 - avoid CrsGraph rowptrs D->H

---

packages/rol/src/oed/utilities/OED_SplitComm.hpp

@trilinos/rol 
This PR is part of the initiative to phase out the use of MPI_COMM_WORLD in Trilinos.

ROL: SplitComm allow for user to pass custom communicator

---

packages/panzer/adapters-stk/src/Panzer_STK_IOClosureModel_Factory.cpp

Support scaling factors in the stk io closure model factory
Required by Charon. Thanks to @glhenni for submitting this patch!

Panzer: add scaling factors to the stk io closure model factory

---

packages/nox/src/CMakeLists.txt
packages/nox/src/NOX_Description.H
packages/nox/src/NOX_GlobalComm.H
packages/nox/src/NOX_Utils.C

@trilinos/nox
Introduce `Global_MPI_Comm` global variable that defaults to `MPI_COMM_WORLD` and use it instead of the hardcoded `MPI_COMM_WORLD`. This PR includes also method which allows for the change of the global communicator. 

NOX: Remove use of hardcoded MPI_COMM_WORLD from NOX package

---

packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_CrsMatrix_UQ_PCE.hpp
packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_CrsMatrix_MP_Vector.hpp

KokkosKernels 4.2 will add some new overloads for spmv that accept execution space instances. The Stokhos specializations for spmv, where Scalar is PCE or MPVector, won't have those yet. So make sure that the existing Stokhos specializations still work by calling a Stokhos implementation (and not a KokkosKernels implementation).
Prevent crashes and possible build errors when the future KokkosKernels 4.2 release is being tested.
* Closes https://github.com/kokkos/kokkos-kernels/issues/1959
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
The spmv specializations are tested in ``Stokhos_KokkosCrsMatrixUQPCEUnitTest`` and ``Stokhos_KokkosCrsMatrixMPVectorUnitTest``.

Stokhos: update for new KokkosSparse::spmv overloads

---

packages/nox/src/NOX_Utils.C

@trilinos/nox 
In our application code, we have found non-decimal-format print out of convergence history.
Example:
```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0  0x1.6f991b49cf45ep-6       0x0p+0       0x0p+0
1  0x1.d567c9ebbe25p-31       0x1p+0  0x1.3e6aa2bad478cp-29
2  0x1.458b21e21267ep-30       0x1p+0  0x1.eb966c999c6dcp-54 (Converged!)
************************************************************************
```
This PR fixes it.

NOX: Fix font and formatting in screen output

---

packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_CrsMatrix_UQ_PCE.hpp
packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_CrsMatrix_MP_Vector.hpp

PR #12190 failed to fix KokkosSparse::spmv for Sacado scalar types (issue https://github.com/kokkos/kokkos-kernels/issues/1959), when building with Kokkos/KokkosKernels develop branch.
This actually fixes that issue (tested with develop and master KokkosKernels) and is quite a bit cleaner (though it uses version macros that can be taken out for the 4.2 release). Instead of trying to have a full set of spmv overloads with enable_ifs to match Sacado types, just have overloads for the actual impl (taking an exec space, controls and a rank tag) because all other overloads in KokkosKernels funnel down to those.
Fix incompatibility between Stokhos and KokkosKernels develop branch, in advance of the KokkosKernels 4.2 release.
* Closes …

Stokhos: fix KokkosKernels #1959

---

packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp
packages/kokkos-kernels/sparse/unit_test/Test_Sparse.hpp
packages/kokkos-kernels/sparse/unit_test/Test_Sparse_extractCrsDiagonalBlocks.hpp

This PR matches changes in kokkos-kernels https://github.com/kokkos/kokkos-kernels/pull/1947 which adds a utility function to extract diagonal blocks from a CRS matrix into separate CRS matrices

KokkosKernels: extract diagonal blocks from a CRS matrix into separate CRS matrices

---

packages/amesos2/src/Amesos2_Basker_def.hpp
packages/amesos2/src/Amesos2_Cholmod_def.hpp
packages/amesos2/src/Amesos2_KLU2_def.hpp
packages/amesos2/src/Amesos2_Lapack_def.hpp
packages/amesos2/src/Amesos2_MUMPS_def.hpp
packages/amesos2/src/Amesos2_PardisoMKL_def.hpp
packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp
packages/amesos2/src/Amesos2_Superlu_def.hpp
packages/amesos2/src/Amesos2_Umfpack_def.hpp

This PR uses a ternary to shorten the implementation of conditionals involving the `is_contiguous` flag in Amesos2.
@ndellingwood 
This change seeks to help the readability of the code.
* Related to #11578

Amesos2: Use ternary in conditionals involving is_contiguous.

---

packages/ifpack2/test/unit_tests/Ifpack2_UnitTestMDF.cpp

This change fixes the dashboard failures observed when Trilinos is built without epetra or with float instead of double. See https://github.com/trilinos/Trilinos/issues/11934 for more information.

Ifpack2: fix dashboard failures in MDF unit tests

---

commonTools/test/utilities/check-mpi-comm-world-usage.py

Fix the issue where base branch is out of sync with Trilinos' develop branch. This results in false positives (removed files or removed lines of `MPI_COMM_WORLD` are reported since they're still present on base branch).
I also removed the local (uncommited) execution part, since it can produce incorrect results.

Framework: Update `detect-mpi-comm-world` GitHub action

---

packages/belos/epetra/src/BelosEpetraUtils.cpp
packages/belos/src/BelosGlobalComm.hpp
packages/belos/src/BelosOutputManager.hpp
packages/belos/src/CMakeLists.txt

Introduce `Global_MPI_Comm` global variable that defaults to `MPI_COMM_WORLD` and use it instead of the hardcoded `MPI_COMM_WORLD`. This PR includes also method which allows for the change of the global communicator.

Belos: Remove use of hardcoded MPI_COMM_WORLD

---

cmake/SimpleTesting/img/CMake-structure.graffle
cmake/SimpleTesting/img/CMake-structure.pdf
cmake/SimpleTesting/img/CMake-structure.png

Some LFS objects from SimpleTestingRefactor got added.
@vbrunini 
We don't want to get involved with git LFS at the moment.

Framework: Remove LFS image objects

---

packages/zoltan2/core/src/util/Zoltan2_ImbalanceMetrics.hpp

@egboman 
When using large weights, the current Zoltan table does not have room and prints all the numbers without spacing, making it difficult to read. This adds space and reduces precision for large numbers, changing the table from something like this:
Imbalance Metrics: (8 existing parts)
min        max        avg   imbalance
object count (2)142062.0000173118.0000158268.1250      1.0938
normed weight (2)5747604.06736730017.01836214345.1864      1.0830
weight 0 (2)     0.2493     0.3263     0.2891      1.1290
weight 1 (2)     1.2349     1.5900     1.4277      1.1136
weight 2 (2)3907548.64324589655.98794238875.5000      1.0828
weight 3 (2)     5.3724     5.9525     5.5874      1.0654
weight 4 (2)4210736.63914916853.77834540803.0623      1.0828
To this:
Imbalance Metrics: (8 existing …

Update zoltan table formatting

---

.github/workflows/detect-git-lfs.yml
commonTools/test/utilities/check-lfs-oids.sh
commonTools/test/utilities/check-mpi-comm-world-usage.py

Adding LFS pointers causes headaches with GitHub quotas and some downstream customers doing mirroring.

Framework: Add action to prevent LFS files from being added

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Import_Util2.hpp

This should increase the speed of MueLu by a nice amount on GPU platforms : )
There is no reason to not perform the sort and merge of csr entries on device.
This code should increase the performance of Tpetra and MueLu on GPU architectures.
* Closes #11696 
* Blocks 
* Follows 
* Precedes 
* Related to #11689 
* Part of 
* Composed of 
Tested on Crusher

Tpetra: device version of sort_and_merge_crs

---

packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp

In ``DistributorActor::doPosts``, make sure each message length in bytes (sendCount) can be represented in 32-bit int. This is needed because the Teuchos MPI wrappers and MPI itself represent send and recv counts as int.
In #12118 reproducer, this is the output now:
```
p=0 |   nnz_per_row = 20
p=0 |   rpt_size = 18808798
p=0 |   ent_size = 376175940
p=0 |   val_size = 376175940
p=1 |   num_rows = 18808797
p=1 |   nnz_per_row = 20
p=1 |   rpt_size = 18808798
p=1 |   ent_size = 376175940
p=1 |   val_size = 376175940
p=0 |   my_local_num_rows = 18808797  my_global_num_rows = 18808797
p=1 |   my_local_num_rows = 0  my_global_num_rows = 18808797
p=0 |   I make it here...
p=1 |   I make it here...
p=0: *** Caught standard std::exception of type 'std::logic_error' : …
```

Tpetra: Fix #12118 (adding checks)

---

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
packages/tpetra/core/src/Tpetra_Details_makeColMap_def.hpp
packages/tpetra/core/src/Tpetra_Details_residual.hpp
packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_Map_def.hpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

Issue: #12106
Tests: n/a
Adding labels to Tpetra calls to Kokkos::fence(); fixing replication logic bug in CrsMatrix::applyTranspose() which lead to an extra fence call

Tpetra: Adding labels to Kokkos::fence(), fixing bug

---

packages/epetraext/src/inout/EpetraExt_HDF5.cpp

@trilinos/epetraext
Introduce `Global_MPI_Comm` global variable that defaults to `MPI_COMM_WORLD` and use it instead of the hardcoded `MPI_COMM_WORLD`. This PR includes also method which allows for the change of the global communicator.

EpetraExt: Remove use of hardcoded MPI_COMM_WORLD

---

packages/zoltan/src/Utilities/Communication/comm_default.c

Zoltan: Remove `inline` specifier from `comm_default.c` functions to avoid warnings

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp

This provides further performance improvements on device for TAFC and simplifies the code.
It's also a step toward full device execution of TAFC where it constructs the CrsMatrix.
That's an important update as the data associated with the CrsMatrix is potentially quite large and moving it back and forth on host and device is really a performance issue.
* Closes 
* Blocks 
* Follows #11751 
* Precedes 
* Related to 
* Part of #11689 
* Composed of 
N/A
Tested on weaver with complex enabled.

Tpetra: remove unnecessary copy to host in TAFC

---

packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
packages/tpetra/core/src/Tpetra_Details_KokkosTeuchosTimerInjection.cpp

This adds a second level of verbosity. One level includes only source & destination, the second includes source, destination, and size.
Motivation: In parallel, sizes may differ per MPI process, thus leading to different timer labels.

Tpetra: modify deep copy tracking

---

packages/zoltan2/core/src/problems/Zoltan2_PartitioningSolution.hpp

@egboman 
When using Zoltan2 to do runtime mesh rebalancing, there are a couple statements printing to std::cout every time we rebalance, which we want to avoid when running Sierra. This changes those to print to the env_ using the same logging level as similar outputs in that call stack.

Remove std::cout printing from Zoltan2 rebalance call

---

packages/ifpack2/doc/UsersGuide/options.tex
packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_decl.hpp
packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
packages/ifpack2/src/Ifpack2_RILUK_decl.hpp
packages/ifpack2/src/Ifpack2_RILUK_def.hpp
packages/ifpack2/test/belos/CMakeLists.txt
packages/ifpack2/test/belos/test_2_RILUK_2streams_nos1_hb.xml
packages/ifpack2/test/belos/test_2_RILUK_4streams_nos1_hb.xml
packages/ifpack2/test/belos/test_4_RILUK_2streams_nos1_hb.xml
packages/ifpack2/test/belos/test_4_RILUK_4streams_nos1_hb.xml

This PR is to add a code path of using stream interfaces of KK SPILUK and KK SPTRSV in Ifpack2 RILUK and local triangular solver, respectively. Basically, a domain on each MPI process is divided to some sub-domains, each of which is handled by SPILUK and SPTRSV on a stream. These streams run concurrently.
Tested with ```Ifpack2_tif_belos``` tester and Sierra T/F matrix ```abnormal_system_surrogate_with_gpu_rowmap-energy_fast_ilu_solver-np-16-time-292.78-solve_count-0``` on 16 MPI processes (4 MPI processes per node, V100 GPUs)
| Streams per MPI process | No stream | 2 | 4 | 9 |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Init preconditioner (seconds) | 6.35349 | 6.08481 | 5.39639 | 3.66621 |
| Compute preconditioner (seconds) | …

Ifpack2: add option to use stream interfaces of KK SPILUK and KK SPTRSV in RILUK and local triangular solver

---

packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp

The diagFact view is Real, not Scalar, so must be assigned to Reals.
Code did not build when complex doubles are enabled.
Built and ran ifpack2 tests that use shylu with `-DTrilinos_ENABLE_COMPLEX_DOUBLE=ON`

Shylu::FastILU fix for complex types

---

packages/tpetra/core/src/Tpetra_Details_Hash.hpp

Remove some unused parameters in `Tpetra_Details_Hash.hpp`
Using any of these functions will already emit a compile-time error, so this just reduces spurious warnings.

Tpetra: cleanup: unused parameters in Tpetra_Details_Hash.hpp

---

packages/tpetra/core/src/Tpetra_Details_Random.cpp
packages/tpetra/core/src/Tpetra_Details_Random.hpp
packages/tpetra/core/src/Tpetra_Import_Util2.hpp

We need these changes to be able to compile `Tpetra` with the `SYCL` backend.
- `printf` can't be used in `SYCL` kernel code and the code is using both `printf` and `Kokkos::abort` which is redundant since `Kokkos::abort` already prints the error message. A workaround for using `printf` in `SYCL` kernel code is to use `KOKKOS_IMPL_DO_NOT_USE_PRINTF`. In the upcoming release, we have `Kokkos::printf` as a portable alternative.
- All `SYCL` classes in `Kokkos` are still in the `Experimental` namespace.
* Closes https://github.com/trilinos/Trilinos/issues/12277
Compiling `Trilinos` with `Tpetra` on the testbed systems at ANL.

Tpetra: Fix compiling with SYCL

---

packages/teuchos/comm/src/Teuchos_StackedTimer.hpp

The `error_out` function can be referenced from other shared objects (likely via instantiations of the class defined in the same header). As such, it must be exported to avoid link errors on Windows. For example, I see the following in a windows build of tpetra:
```
/opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/tpetra.dir/objects.a(Tpetra_Details_DeepCopyTeuchosTimerInjection.cpp.obj):Tpetra_Details_DeepCopyTeuchosTimerInjection.cpp:(.text+0x279): undefined reference to `Teuchos::error_out(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
```
This PR fixes this by adding the appropriate export annotation.
Build-test in …

teuchos: Add missing export annotation for windows

---

packages/intrepid2/src/Cell/Intrepid2_CellGeometry.hpp
packages/intrepid2/src/Cell/Intrepid2_CellGeometryDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasisFamily.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasisFamily.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HDIV_PYR.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HDIV_PYR_ETI.cpp
packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HDIV.hpp
packages/intrepid2/src/Projection/Intrepid2_ProjectionStructDef.hpp
packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHDIV.hpp
packages/intrepid2/unit-test/MonolithicExecutable/BasisCardinalityTests.cpp
packages/intrepid2/unit-test/MonolithicExecutable/CMakeLists.txt
packages/intrepid2/unit-test/MonolithicExecutable/CellGeometryTests.cpp
packages/intrepid2/unit-test/MonolithicExecutable/SubBasisInclusionTests.cpp
packages/intrepid2/unit-test/Orientation/test_orientation_PYR_QuadFace_newBasis.hpp
packages/intrepid2/unit-test/Orientation/test_orientation_PYR_TriFace_newBasis.hpp
packages/intrepid2/unit-test/Projection/CMakeLists.txt
packages/intrepid2/unit-test/Projection/eti/test_convergence_PYR_ETI.in
packages/intrepid2/unit-test/Projection/test_convergence_PYR.hpp

This PR adds an arbitrary-order, hierarchical basis for H(div) on the pyramid.  This follows #12079, which added hierarchical bases for H(grad) on the pyramid, and #12136, which added bases for H(vol).
This PR also adds support in CellGeometry for a pyramidal subdivision of regular hexahedral meshes, and support for a rudimentary node numbering within CellGeometry.  This is in support of new projection convergence tests, so far implemented for H(grad) and H(vol).  H(div) support for such projections actually requires H(curl) bases to be implemented as well; those will be coming in a subsequent PR.
Additionally, this PR adds orientation tests against H(div) on the pyramid.
This PR has orientation and basis cardinality tests for the new H(div) basis.  The new …

Intrepid2: add hierarchical bases for H(div) pyramids

---

packages/teko/src/Teko_PreconditionerFactory.cpp

@trilinos/teko
The TEKO_HAVE_EPETRA switch controls whether ProbingPreconditionerFactory gets compiled, but not all includes of this header were appropriately guarded by the preprocessor macro. Correct this to fix the compilation of teko with TEKO_HAVE_EPETRA disabled.
Build testing in the `!TEKO_HAVE_EPETRA` case was performed locally. This patch should not affect any runtime behavior.
Found while attempting to enable `Teko` in the Julia distribution of Trilinos at https://github.com/JuliaPackaging/Yggdrasil/pull/7386.

teko: Guard ProbingPreconditionerFactory by TEKO_HAVE_EPETRA

---

packages/amesos2/src/Amesos2_Kokkos_View_Copy_Assign.hpp
packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp
packages/ifpack2/src/Ifpack2_Details_ScaledDampedResidual_def.hpp
packages/panzer/disc-fe/src/Panzer_Workset.cpp

@trilinos/amesos2 @trilinos/ifpack2 @trilinos/panzer 
Fixes some deprecation warnings of the type
`warning: 'Rank' is deprecated: Use rank instead. [-Wdeprecated-declarations]`.
N/A
Verified in local build.

Fix warning 'Rank' is deprecated

---

packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp

@trilinos/tpetra @jhux2 
Fix an uninitialized dummy variable used passed as a const reference—detected in Tpetra template instantiations, in clang builds in Sierra.

Tpetra: fix uninitialized const ref complaints from clang 14 compiler

---

RELEASE_NOTES

Follow-on from PR:
* #12258 
Hopefully this improved release note will help customers transition to Trilinos using the standard GNUInstallDirs module.  I also added a mention that Trilinos may only support GNUIntallDirs in the future so customers should get used to working with it.
Hopefully this will help customers avoid situations like:
* sandialabs/albany#982

Improve release note for using GNUInstallDirs by default (#12104)

---

packages/belos/tpetra/test/GCRODR/CMakeLists.txt
packages/belos/tpetra/test/GCRODR/test_block_gcrodr.cpp
packages/belos/tpetra/test/GCRODR/test_gcrodr_complex_hb.cpp
packages/belos/tpetra/test/GCRODR/test_gcrodr_hb.cpp

@hkthorn 
This PR updates the following tests:
_Note: currently, the following tests cannot be converted due to their use of a preconditioner (the original examples use Ifpack; however, including IfPack2 creates a circular dependency with Belos)_
- `test_prec_gcrodr_hb.cpp`

Belos: add Tpetra GCRODR test

---

packages/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp

This was a fix in Kokkos Kernels that did not make it into Trilinos
Fix for https://github.com/trilinos/Trilinos/issues/12296

KokkosKernels: fix block_layout type alias in RocSparse TPL

---

packages/tpetra/core/src/Tpetra_Details_fill.hpp

Issue: n/a
Test:n/a
Stakeholder feedback: Email
```
.../Trilinos/vortex/Trilinos/packages/tpetra/core/src/Tpetra_Details_fill.hpp: In function 'void Tpetra::Details::Blas::fill(const ExecutionSpace&, const ViewType&, const ValueType&, IndexType, IndexType)':
.../Trilinos/vortex/Trilinos/packages/tpetra/core/src/Tpetra_Details_fill.hpp:81:31: error: 'pair' was not declared in this scope
auto X_j = Kokkos::subview (X, Kokkos::pair{IndexType(0), numRows}, Kokkos::pair{IndexType(0), numCols});
^~~~
.../Trilinos/vortex/Trilinos/packages/tpetra/core/src/Tpetra_Details_fill.hpp:81:31: note: suggested alternatives:
/my/path/gcc/gcc-8.3.1/rh/usr/include/c++/8/bits/stl_pair.h:208:8: note:   'std::pair'
struct pair
```

Tpetra: Fixing vortex compile issue

---

packages/stokhos/src/sacado/kokkos/vector/tpetra/Stokhos_Tpetra_Utilities_MP_Vector.hpp
packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp
packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

Hi @etphipp,
In the mean time, @romintomasetti and I have looked more into the problem with running `Amesos2` solvers with ensembles on GPU with more than one MPI rank (issue #12279).
This PR is a proposed fix.
Running `Amesos2` solvers with ensembles is tested in `stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp`. 
The existing pipeline typically runs fine, and issue #12279 doesn't show up. It seems the reason is that this test selects only one `Amesos2` solver, 
depending on which ones the user enabled and an order of preference. When the user activated `basker`, that's the one that `Stokhos` chooses.
For `basker`, the code goes into the specialisation of `basker` for ensembles -> no problem.
However, when `Amesos2` is compiled without `basker` but with e.g. `klu2`, …

Stokhos (fixes #12279): construct flattened vector by copy constructing WDV

---

packages/belos/tpetra/example/TFQMR/CMakeLists.txt

This example uses the BelosTpetraTestFramework, which uses Triutils to read input files. 
Therefore the example requires a guard for Triutils.  This has been reported to cause build errors like
those in issue:
https://github.com/trilinos/Trilinos/issues/12333
OSX Clang serial / parallel

Belos:  Adds Triutils guard to TFQMR example

---

packages/pamgen/extra_functions/pamgen_extras.cpp
packages/pamgen/extra_functions/pamgen_global_comm.h
packages/pamgen/src/CMakeLists.txt

@trilinos/pamgen
Introduce `Global_MPI_Comm` global variable that defaults to `MPI_COMM_WORLD` and use it instead of the hardcoded `MPI_COMM_WORLD`. This PR includes also method which allows for the change of the global communicator.

Pamgen: Remove use of hardcoded MPI_COMM_WORLD

---

packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp

- Projection was incorrect for nullspaces of dim>1.
- Check for non-contiguous map was insufficient. 
(I saw this for a small problem where MueLu only set up a direct solver, and the input matrix had a non-contiguous   rowmap.)

MueLu_Amesos2Smoother: Fixes for projection and non-contiguous maps

---

cmake/RepositoryDependenciesSetup.cmake

I tested and confirmed that stk-balance builds and runs with Global-Ordinal = int.
Technically I didn't confirm that stk-balance is ok with Global-Ordinal = unsigned. I attempted to build that way, but Tpetra won't allow it. Tpetra has compile-time checks for signed-ness and won't compile.
There is no *known* reason why stk-balance
wouldn't work with unsigned, if it were allowed
through Zoltan2/Tpetra.

Remove guard that disables stk-balance if Tpetra Global-Ordinal=int

---

packages/aztecoo/src/az_old_matvec_mult.c
packages/aztecoo/src/md_wrap_mpi_c.c

@trilinos/aztecoo
~~Introduce  `az_global_mpi_comm` global variable that defaults to `MPI_COMM_WORLD` and use it instead of hardcoded `MPI_COMM_WORLD`.~~
This PR is part of the initiative to phase out the use of `MPI_COMM_WORLD` in Trilinos.
EDIT: 
See https://github.com/trilinos/Trilinos/pull/12163#issuecomment-1737863375

AztecOO: Don't use hardcoded `MPI_COMM_WORLD` in `AztecOO` code

---

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp

Issue: #11214
Tests: Already there
Fixing two bugs in Maxwell1.  The first was a map inconsistency issue which shows up in parallel.  This was a the-code-is-wrong bug.  The second was an inconsistency in the tie-break polarity vs. ML.  These are both fixed in this PR

MueLu: Fixing two Maxwell1 bugs

---

packages/phalanx/test/Kokkos/tKokkosScalarFunctionsFad.cpp

CUDA did not like an implicit lambda capture in constexpr if. Have to capture variables for the first time outside of the constexpr if in device lambdas.

Phalanx: fix unit test for cuda 12

---

packages/ifpack/src/euclid/guards_dh.h
packages/ifpack/src/euclid/mat_dh_private.c

@trilinos/ifpack
~~Introduce `Global_MPI_Comm` global variable that defaults to `MPI_COMM_WORLD` and use it instead of the hardcoded `MPI_COMM_WORLD`. This PR includes also method which allows for the change of the global communicator.~~
See comments:
- https://github.com/trilinos/Trilinos/pull/12193#discussion_r1339098111
- https://github.com/trilinos/Trilinos/pull/12193#discussion_r1339162430

Ifpack: Remove use of hardcoded MPI_COMM_WORLD

---

packages/galeri/CMakeLists.txt
packages/galeri/example-tpetra/CMakeLists.txt
packages/galeri/example-tpetra/CrsMatrix_Tpetra.cpp
packages/galeri/example-tpetra/LinearProblem_Tpetra.cpp
packages/galeri/example-tpetra/Map_Tpetra.cpp
packages/galeri/test/VerySimple/CMakeLists.txt
packages/galeri/test/VerySimple/cxx_main_tpetra.cpp

@jhux2 
This PR updates Galeri tests to use Tpetra instead of Epetra. Tests and table/notes written by @thearusable 
Tests found under the `test`, `example*` directories.
| Folder          | Epetra Tests (Main file name)          | Conversion Status                        |
|-----------------|-------------------------------|---------------------------------|
| test/VerySimple | cxx_main.cpp                            | **Partial**                     |
| example             | Map.cpp                                      | **Full**                         |
| example             | CrsMatrix.cpp                             | **Partial**                        |
| example             | VbrMatrix.cpp                            | **NO**                          |
| example …

Galeri: add Tpetra tests

---

CMakeLists.txt
packages/common/auxiliarySoftware/SuiteSparse/src/CMakeLists.txt
packages/zoltan/src/CMakeLists.txt

Reverts:
* trilinos/Trilinos#12362
This change breaks the installed ZoltanConfig.cmake file as per:
* #12371

Revert "Framework: Enable CMAKE_LINK_LIBRARIES_ONLY_TARGETS"

---

packages/nox/src-loca/src-thyra/LOCA_Thyra_Group.C
packages/nox/src-thyra/NOX_Solver_PseudoTransient.cpp
packages/nox/src-thyra/NOX_Thyra_Group.C
packages/nox/src-thyra/NOX_Thyra_Group.H
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.cpp
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.hpp
packages/tempus/src/Tempus_StepperBackwardEuler_impl.hpp
packages/tempus/src/Tempus_StepperDIRK_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
packages/tempus/src/Tempus_StepperImplicit_decl.hpp
packages/tempus/src/Tempus_StepperImplicit_impl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluator.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorBasic_decl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorBasic_impl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorPairIMEX.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorPairIMEX_Basic_decl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorPairIMEX_Basic_impl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorPairPartIMEX_Basic_decl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorPairPartIMEX_Basic_impl.hpp
packages/tempus/src/Tempus_WrapperModelEvaluatorSecondOrder_decl.hpp

Tempus's WrapperModelEvaluators tended to construct InArgs internally and use them in the evalModelImpl().  This caused issues with other packages (e.g., NOX and LOCA) that might have changed/added values to the inArgs.  To avoid copying items from the inArgs from the argument list into the WrapperModelEvaluator::InArgs, the WrapperModelEvaluator::createInArgs was improved to return a complete InArgs.
Changed the setForSolve() interface from passing in inArgs/outArgs to passing in Tempus pieces of the inArgs/outArgs (x, xDot, time, and time derivative information), which are used within the WrapperModelEvaluators.
Eliminated all of the setInArgs() and setOutArgs() functions as this should be done through setForSolve().  Replaced getInArgs() and getOutArgs() with createInArgs() and …

Tempus: Change Usage of InArgs/OutArgs

---

CMakeLists.txt

Need default settings for TriBITS to be set prior to TRIBITS_PROJECT() call.
User Support Ticket(s) or Story Referenced: N/A
Want to ensure cleaner Trilinos configurations with respect to TPLs, and the previous change didn't get this setting turned on in the correct spot.
This may re-introduce #12376
Technically I think that #12376 tests and confirms this is working.

Framework: Fix location of TriBITS default var

---

packages/belos/tpetra/test/BlockGmres/CMakeLists.txt

Resolve missing header error when Triutils is not enabled: "fatal error: Trilinos_Util_iohb.h: No such file or directory"
@trilinos/belos @hkthorn 
Resolve compilation errors when Triutils is not enabled:
```
Trilinos-kp/packages/belos/tpetra/src/BelosTpetraTestFramework.hpp:56:10: fatal error: Trilinos_Util_iohb.h: No such file or directory
56 | #include "Trilinos_Util_iohb.h"
|          ^~~~~~~~~~~~~~~~~~~~~~
```
Local testing, AT

belos: guard BlockGmres tests that require Triutils

---

packages/teuchos/comm/src/Teuchos_DefaultMpiComm.hpp
packages/teuchos/comm/src/Teuchos_EReductionType.hpp
packages/teuchos/comm/src/Teuchos_MpiReductionOpSetter.hpp
packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp

This follows up PR #12307 to address another round of missing exports. I didn't make any efforts to systematically try to indentify what should be exported. Rather, these are the symbols that the compiler complains about in a Trilinos build with sufficient enabled components to build charon (which uses a fair number of Trilinos packages).
Build test in https://github.com/JuliaPackaging/Yggdrasil/pull/7534. Runtime not impacted.

teuchos: Add more missing Windows export annotations

---

packages/belos/src/BelosSolverFactory.hpp
packages/belos/tpetra/test/LinearSolverFactory/CustomSolverFactory.cpp

Custom solver factories can be provided to the default solver factory
that contains classic Belos solvers.  Once a custom solver factory is
added, it is available to all other solver factories.  However, this
requires that any custom solver factories are cleared from the default
solver factory to avoid memory leaks.  This issue resulted in the
failure of the custom solver factory test under a debug build, as shown
in issue #11137.
A new method has been added to the solver factory base class to clear
any custom solver factories that have been registered with it.  The
new method is used in the custom solver factory test, enabling clean
execution under a debug build.
OSX Clang Serial / MPI

Belos:  Add method to clear custom solver factories

---

packages/nox/test/epetra/MultiPhysics/Problem_Manager.C
packages/panzer/adapters-stk/src/Panzer_STKConnManager.cpp
packages/panzer/adapters-stk/src/responses/Panzer_STK_ResponseEvaluatorFactory_SolutionWriter.hpp

Fix deprecated functions in c++17 standard in Panzer and NOX.
Add debug check to panzer connection manager to make sure topologies are consistent.

Panzer and NOX cleanup

---

packages/rol/src/oed/utilities/OED_SplitComm.hpp

@trilinos/rol 
Currently, the use of `MPI_COMM_WORLD` blocks the dev->master promotion. This is a perfectly reasonable use of it, so let's set the hint.

ROL: Allow use of MPI_COMM_WORLD as default arg

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase1Algorithm_def.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp
packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp
packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp

Issue: #11214
Tests: App
ML does not consider boundary neighbors to be 'aggregated' in the context of Phase1 aggregation for root node selection.  MueLu did.  Adding the option to do things more ML-style

MueLu: Adding ML-compatability option for Phase1 Aggregation

---

packages/kokkos-kernels/sparse/src/KokkosKernels_Controls.hpp

Match a change made in kokkos-kernels upstream 86d8371fdb3d528095a86635b9add53a36bb516e
The next kokkos-kernels snapshot will include this change

KokkosKernels: controls: don't print a noisy warning

---

CMakeLists.txt
packages/TrilinosInstallTests/CMakeLists.txt
packages/TrilinosInstallTests/find_package_Trilinos/CMakeLists.txt
packages/TrilinosInstallTests/find_package_Trilinos/hello.c
packages/TrilinosInstallTests/find_package_Trilinos/hello.cpp

Enhance find_package(Trilinos) test to catch issues like #12371
Turning on LINK_LIBRARIES_ONLY_TARGETS caused an issue with a downstream customer when we did not set up the installation correctly with respect to imported targets.
#12362 
#12371 
#10081 
Tested with the changes from #12362 and it immediately caught the issue.

Framework: Enhance find_package(Trilinos) test

---

packages/tpetra/core/src/Tpetra_Import_Util2.hpp

Iterate over domainMap efficiently on device using local map ``getGlobalElement(lid)``, instead of getting a host view of GIDs and copying that to device. This avoids a copy and is faster if the domain map is contiguous (where ``getGlobalElement()`` is just an addition).
Covered by several CrsMatrix unit tests: Bug10008_2, Bug10008_3, Bug8447.

Tpetra: in TAFC iterate over domainMap efficiently

---

packages/teuchos/core/src/Teuchos_Array.hpp
packages/teuchos/core/src/Teuchos_TestingHelpers.hpp
packages/teuchos/core/src/Teuchos_UnitTestHelpers.hpp
packages/teuchos/core/test/MemoryManagement/Array_UnitTests.cpp
packages/teuchos/core/test/MemoryManagement/Array_test.cpp

Allow Array class to be constructed from std::initializer_list
Requested by ParameterList users
New test added to Array tests

Teuchos: support initializer_list construction in Array class

---

packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp
packages/panzer/dof-mgr/src/Panzer_DOFManager.hpp
packages/panzer/dof-mgr/src/Panzer_DOFManager_Functors.hpp

@rppawlo 
This PR declares certain member functions of `Panzer_DOFManager` as `virtual`. This allows overriding these functions with alternative implementations, such as versions that may do more work on device.
On the side, the call to the functor `Panzer_DOFManager_Functors.hpp` is changed from a RangePolicy to a MDRangePolicy. I can revert this change if you prefer.
* Related to issue #12380.

Make functions virtual in Panzer_DOFManager.

---

.github/CODEOWNERS

Also remove commented lines.
Want a valid CODEOWNERS now that we can re-enable CODEOWNERS capability.
* Closes #11812

Framework: Remove deleted packages from CODEOWNERS

---

packages/tpetra/core/compat/Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.hpp

- ``Node::is_serial``: is it Kokkos::Serial?
- ``Node::is_cpu``: is it a CPU-like device? (default memspace is HostSpace)
- ``Node::is_gpu``: is it a GPU-like device? (default memspace is something other than HostSpace)
Possible solution to issue discussed at Tpetra meeting. Instead of having to compare the node or execution space to every possible case (with ifdefs to check if types like ``Kokkos::Serial`` even exist), this lets users check the Node for common properties more easily.
@csiefer2 comments: Basically, I only want to see the words "HIP" "CUDA" and "SYCL" in Trilinos code where it is absolutely necessary for performance.  We have a lot of boilerplate where this stuff is littered through Trilinos right now, which makes adding new backends way harder then it …

Add some constexpr traits to Tpetra Node types

---

packages/ifpack2/src/Ifpack2_BlockComputeResidualVector.hpp

This fixes a large performance regression seen in SPARC after the kokkos-3.6.01 promotion, see issue kokkos/kokkos#6533.
@srajama1 @kliegeois

ifpack2: Remove Kokkos::subview calls from ComputeResidualVector kernel.

---

CMakeLists.txt
cmake/CallbackSetupExtraOptions.cmake

Need to process CXX standard after a potential CONFIGURE_OPTIONS_FILE has been processed.  This manifested a small bug where the configure message about which CXX standard was being used showed 17 even though the entry in the Trilinos_CONFIGURE_OPTIONS_FILE read 20 (and in fact it did use 20).
Want diagnostic messages to align with the actual behavior.
Tested using `-DTrilinos_CONFIGURE_OPTIONS_FILE` and it now behaves correctly.

Framework: Relocate CXX standard setup

---

packages/muelu/src/Interface/MueLu_MLParameterListInterpreter_def.hpp
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/MueCentral/MueLu_FactoryManager_decl.hpp
packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp
packages/muelu/test/interface/CreateOperator.cpp
packages/muelu/test/interface/ParameterListInterpreter.cpp
packages/tpetra/core/compat/Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.hpp
packages/tpetra/core/src/Tpetra_Details_KokkosTeuchosTimerInjection.cpp
packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp

- Fix ``Node::is_gpu``, ``is_cpu``: assume that ``Kokkos::Experimental::HBWSpace`` is also a possible default memory space of a CPU-like execution space.
- Use ``Node::is_serial`` to decide whether a Kokkos version of something should be used, vs. serial
- Use ``Tpetra::Details::Spaces::is_gpu_exec_space<ES>()`` to also simplify some logic, in places where a Node type is not available (like in WrappedDualView)
Out of the possible places that @cgcgcg and @csiefer2 listed in #12284 , this takes care of all the easy improvements. There are some others, like Tpetra_Details_Random.cpp, where we manually ETI things for different backends. These cases can also be simplified, but it's a different kind of thing.
Fix an issue noticed by @lucbv  - some CPU architectures like KNL or …

Tpetra, MueLu: use new Node traits to simplify code

---

packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsMatrix.hpp

@etphipp 
A while ago, we had seen in issue #11398 that the cuSparse's alg defaults for SPMV/SPMM depend on the cuSparse version. 
This PR is a fix that follows what was done in e.g. `KokkosSparse_spmv_tpl_spec_decl.hpp` to address the same issue. 
Fixes #11398.

Stokhos(fixes #11398): Set alg defaults depending on cusparse version

---

packages/tpetra/CMakeCuda.txt

Issue: #12451 
Stakeholder feedback: Verified supported versions on Kokkos slack
Tests: n/a
We don't support CUDA 7.5 any more, so we can clean up a lot of that logic.

Tpetra: Cleaning up CUDA cmake logic (part 1)

---

packages/tpetra/core/src/Tpetra_Import_Util2.hpp

@trilinos/tpetra @csiefer2 @brian-kelley @jhux2 
Resolve compilation error with SYCL backend (printf still broken)

tpetra: guard printf use with sycl

---

packages/muelu/doc/UsersGuide/options.tex

We talked about eventually just pointing to the Kokkos-kernels documentation when we allow the options to pass straight through. Until then, we should still document these options correctly.
Closes #12410

MueLu: Update coloring documentation

---

packages/framework/ini-files/config-specs.ini
packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_BlockCrsMatrix.hpp
packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CooProductTensor.hpp
packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_SimpleTiledCrsProductTensor.hpp
packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_SymmetricDiagonalSpec.hpp
packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_TiledCrsProductTensor.hpp
packages/stokhos/src/sacado/kokkos/vector/Kokkos_Parallel_MP_Vector.hpp

Compatibility update needed for kokkos following kokkos/kokkos#6544
Address kokkos/kokkos#6561
Co-authored-by: Damien L-G <dalg24+github@gmail.com>
Thanks @dalg24 for suggested update!
@trilinos/stokhos @etphipp 
Resolve compilation errors with Cuda backend
**Local test (stokhos only) with sems-cuda/11.4.2**:
```
...
98% tests passed, 1 tests failed out of 66
Label Time Summary:
Stokhos    = 132.16 sec*proc (66 tests)
Total Test time (real) =  74.11 sec
The following tests FAILED:
45 - Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda_MPI_4 (Failed)
Errors while running CTest
```
where Stokhos_TpetraCrsMatrixUQPCEUnitTest_Cuda_MPI_4 is known failure #12427 
**Configuration**:
```
module purge
module load sems-gcc/8.5.0 sems-cuda/11.4.2 sems-cmake sems-git sems-openmpi/4.1.4 sems-ninja
export …
```

stokhos: revise use of Cuda impl routines from kokkos

---

packages/phalanx/example/FiniteElementAssembly/evaluators/IntegrateDiffusionTerm_Def.hpp
packages/phalanx/example/FiniteElementAssembly/evaluators/IntegrateSourceTerm_Def.hpp
packages/phalanx/example/FiniteElementAssembly/evaluators/ProjectGradientToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly/evaluators/ProjectValueToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/IntegrateDiffusionTerm_Def.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/IntegrateSourceTerm_Def.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/ProjectGradientToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/ProjectValueToQP_Def.hpp
packages/phalanx/src/Phalanx_Evaluator_UnmanagedFieldDummy.hpp
packages/phalanx/src/Phalanx_MDField.hpp
packages/phalanx/test/Field/MDField_Compiletime.cpp
packages/phalanx/test/UnmanagedFields/MDField/UnmanagedMDFieldTest.cpp

Fix long standing issue with MDFields and GPUs. MDField contains an RCP member. RCP is not used on device, but lambda class capture would generate a compiler warning if the MDField copy ctor was used on device. This commit hides the host members (the RCP) so that the copy ctors on device do not generate warnings.
All code is under test in the Phalanx repo. New test were added for a corner case that a Panzer test picked up (in MDField_Compiletime and UnmanagedField tests).

Phalanx fix mdfield cuda warnings

---

packages/ifpack2/src/Ifpack2_LocalFilter_def.hpp
packages/ifpack2/src/Ifpack2_MDF_def.hpp
packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp
packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp

Fix valgrind errors coming from ifpack2. Also remove trailing whitespaces from a couple shylu headers.
Valgrind errors were showing up on the dashboard after some ifpack2 tests were promoted to nightly.
Fixes #12379
Ran a few tests with valgrind to confirm valgrind errors are fixed.

Fix valgrind errors for ifpack2 tests

---

packages/amesos2/src/Amesos2_MUMPS_def.hpp

Commit [cdb2ce](https://github.com/trilinos/Trilinos/commit/cdb2cecfde2688a7f6f947694eb02e3f18d50c5c) introduced a bug which appears in Amesos2 if build with MUMPS support. The `do_get` function call misses a comma.
Apparently there are no tests for Amesos2 with MUMPS support. Otherwise this would not have passed in the first place.

Amesos2 mumps bugfix - Missing comma in function call

---

packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp
packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp

- Change a parameter value in RefMaxwell's default list to match previous behavior.
- Revert change to trigger coarse solver factorization during setup. EMPIRE and Albany reported issues.

MueLu RefMaxwell: Fix issue in default parameterlist

---

packages/tempus/test/IMEX_RK_Partitioned/CMakeLists.txt
packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_Partitioned_Combined_FSA_Tangent.cpp
packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_Partitioned_Staggered_FSA.cpp
packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_Partitioned_Staggered_FSA_Tangent.cpp

IMEX RK Partitioned FSA tests in debug mode were occasionally running too long, when resources were loaded.  Splitting up these tests into individual tests based on using dfdp as the tangent or not.
Note that anything between these delimiters is a comment that will not appear
in the pull request description once created. Most areas in this message are
commented out and can be easily added by removing the comment delimiters.
* Closes #12506

Tempus: Split Up IMEX RK Partitioned FSA Tests

---

packages/piro/test/CMakeLists.txt
packages/piro/test/Piro_TempusSolver_AdjointSensitivitySinCosUnitTests.hpp
packages/piro/test/Piro_TempusSolver_AdjointSensitivitySinCos_Explicit_UnitTests.cpp
packages/piro/test/Piro_TempusSolver_AdjointSensitivitySinCos_Implicit_UnitTests.cpp
packages/piro/test/Piro_TempusSolver_SensitivitySinCos_Combined_FSA_Tangent_UnitTests.cpp
packages/piro/test/Piro_TempusSolver_SensitivitySinCos_Combined_FSA_UnitTests.cpp
packages/piro/test/Piro_TempusSolver_SensitivitySinCos_FSA.hpp
packages/piro/test/Piro_TempusSolver_SensitivitySinCos_Staggered_FSA_Tangent_UnitTests.cpp
packages/piro/test/Piro_TempusSolver_SensitivitySinCos_Staggered_FSA_UnitTests.cpp

These tests in debug mode were occasionally running too long, when resources were loaded.  Splitting up these tests into individual tests is reduce likelihood of timing out.
* Closes #12515

Piro: Split Up Tempus Solver Sensitivity Tests

---

packages/tpetra/CMakeCuda.txt
packages/tpetra/CMakeLists.txt

Tpetra will now set Tpetra_ASSUME_GPU_AWARE_MPI to true unless automatic detection or the user indicates otherwise. Previously, the default value was false.
Addresses #12468.
Most HPC platforms have GPU-aware MPI.  The existing logic (which I didn't really change) is fragile and assumes an OpenMPI-based variant.
Discussions with @csiefer2.
Tested with local cmake configuring.

Tpetra: assume gpu-aware mpi

---

packages/tempus/src/Tempus_StepperDIRK_decl.hpp

Fix and improve getAlpha(dt) function.  It would only return alpha(0,0) instead of alpha(i,i).
* Closes #12511

Tempus: Fix DIRK getAlpha

---

CTestConfig.cmake

The submits to testing-dev.sandia.gov/cdash don't work from some machines at SNL. Therefore, we will disable for now until this can be fixed.  (See commit message).

Disable secondary submit to testing-dev.sandia.gov

---

packages/piro/src/Piro_TempusSolver_Def.hpp

This PR fixes an error in the Piro/Tempus logic, which was causing the Newmark Parameters to not be read in from input file when specified.

Piro: correcting logic so that Beta and Gamma parameters are properly

---

packages/ifpack2/test/unit_tests/Ifpack2_UnitTestILUT.cpp

Update to resolve potential memory corruption errors due to size mismatches between data and unmanaged Views in normImpl routine Reported in #12505
@trilinos/ifpack2 @jhux2 @brian-kelley 
Resolve potential memory corruption errors
See e.g. 
https://github.com/trilinos/Trilinos/pull/12505#issuecomment-1805061390
https://github.com/trilinos/Trilinos/pull/12505#issuecomment-1811197533
Local testing, AT

ifpack2: match size of norms* Views to MV in ILUT test

---

packages/compadre/src/Compadre_LinearAlgebra.cpp
packages/compadre/src/tpl/KokkosBatched_SolveUTV_TeamVector_Internal_Compadre.hpp

@trilinos/compadre
This fixes compiling `Compadre` with `SYCL` enabled. `SYCL` doesn't support `printf` in device code directly and we are introducing `Kokkos::printf` in the 4.2.0 release
* Related to #12420 and #12428
Compiling `Trilinos` with `Compadre` enabled and `Kokkos+SYCL`.

Compadre: Fix printf for SYCL

---

packages/ifpack/utils/parseHypre.py
packages/ifpack2/src/Ifpack2_Hypre_FunctionParameters.hpp
packages/ifpack2/src/Ifpack2_Hypre_decl.hpp
packages/ifpack2/src/Ifpack2_Hypre_def.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestHypre.cpp
packages/ifpack2/utils/parseHypre.py

Before this change, `Ifpack2::Hypre` was implemented the same no matter what template types were used. But Hypre gets compiled only for one combination of Scalar & Ordinal. This change should handle cases where we enable multiple combinations of types.
Also fixes the scripts that generate the header for the `HYPRE_*` functions. Every now and then that file was invalid C++.

Ifpack2 Hypre: Only instantiate interface for hypre enabled options

---

packages/sacado/src/new_design/Sacado_Fad_Exp_Atomic.hpp

@trilinos/Sacado
This fixes compiling with `Sacado` and `Kokkos+SYCL`. Clearly, it's not the best solution to just abort for unsupported functionality but at least this lets us compile.
The support for arbitrary size atomics for `Kokkos+SYCL` depends a lot on compiler versions and it's not clear to me what the best solution is as of now.
* Related to #12420 and #12428
Compiling `Trilinos` with `Sacado` and `Kokkos+SYCL`.

Sacado: Fix compiling with SYCL

---

packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp

@trilinos/Sacado
Checking for `in_parallel` to possibly initialize a `View` in serial (after allocating) instead of calling `parallel_for` is not portable and the respective function doesn't have a `KOKKOS_FUNCTION` annotation. We are considering deprecating `in_parallel` and it seems that it's not needed here anyway.
* Related to https://github.com/kokkos/kokkos/issues/6032 and https://github.com/kokkos/kokkos/pull/6582.

Sacado: Remove in_parallel() use

---

packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
packages/teko/src/Teko_DiagonalPreconditionerFactory.cpp

@trilinos/teko @trilinos/muelu 
- Teko: Add missing include.
- MueLu ML2MueLuParameterTranslator: Only set "match ML" params once.

MueLu&Teko: fixes

---

packages/framework/ini-files/environment-specs.ini

Now that we have open environment specs checked in, add the ones for the nightly GenConfig-based OneAPI build.

Framework: Add specs for nightly container build

---

packages/shylu/shylu_node/tacho/src/Tacho.hpp

@trilinos/Shylu
This fixes compiling `Shylu` with `SYCL` enabled in `Kokkos`.
* Related to #12420 and #12428
Compiling `Trilinos` with `Shylu` and `Kokkos+SYCL`.

Shylu: Fix compiling with SYCL

---

packages/belos/tpetra/test/BlockCG/CMakeLists.txt
packages/belos/tpetra/test/BlockCG/test_bl_cg_complex_hb.cpp
packages/belos/tpetra/test/BlockCG/test_bl_cg_hb.cpp
packages/belos/tpetra/test/BlockCG/test_bl_cg_hb_multiprec.cpp
packages/belos/tpetra/test/BlockCG/test_pseudo_cg_hb.cpp
packages/belos/tpetra/test/BlockCG/test_pseudo_stochastic_cg_hb.cpp
packages/belos/tpetra/test/BlockCG/test_resolve_cg_hb.cpp

@hkthorn 
This PR updates the following tests:
This PR converts the following tests:
- `test_pseudo_cg_indefinite.cpp` (see https://github.com/trilinos/Trilinos/pull/12281)
_Note: currently, the following tests cannot be converted due to their use of a preconditioner (the original examples use Ifpack; however, including IfPack2 creates a circular dependency with Belos)_
- test_bl_pcg_set_res
- test_bl_pcg_hb
- test_pseudo_pcg_hb
- test_pseudo_stochastic_pcg_hb

Belos: add Tpetra BlockCG test

---

packages/ifpack2/example/BlockTriDi.cpp
packages/ifpack2/src/Ifpack2_BlockComputeResidualVector.hpp
packages/ifpack2/src/Ifpack2_BlockHelper.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp

This PR replaces #12344 (that has been reverted by #12449) and includes an extra commit 28bb23680ca186325491257a785c086b88345dd7 that fixes the observed performance regression of #12344 that was due to:
```
static constexpr int vector_length = 1; //DefaultVectorLength<btdm_scalar_type,memory_space>::value;
static constexpr int internal_vector_length = 1; //DefaultInternalVectorLength<btdm_scalar_type,memory_space>::value;
```
The above has been fixed and other issues have been observed and fixed in this PR:
1. `packindices_schur` is now a 2D view,
2. `Kokkos::deep_copy(e_scalar_values, Kokkos::ArithTraits<btdm_magnitude_type>::zero());` is added to make sure that we do not use values of the previous application of the solver,
3. two kernels `SingleZeroingTag` and …

Ifpack2: Schur complement for BTD

---

packages/tpetra/core/example/Finite-Element-Assembly/CMakeLists.txt

FE perf tests use an 8192^2 quad mesh (9-pt stencil). When running on one vortex rank (V100 16GB), memory allocations fail reliably.
This is the only nightly performance test that fails reliably. Right now, the perf test builds are running "ctest || true" so that failures won't kill the whole Jenkins job. But after removing this, the "ctest" command can be expected to be successful 100% of the time. This way, if the Jenkins job fails, we can tell at a glance if any tests are failing.

Tpetra: remove FE assembly 1 rank test

---

packages/muelu/test/unit_tests/ParameterList/ParameterListInterpreter.cpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_decl.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp

**In Tpetra**
- Fix https://github.com/trilinos/Trilinos/issues/12565: in Add that takes C as output argument, resume fill on
C before calling sumIntoGlobalValues. Then fillComplete it again
before returning.
- Correct documentation for Add version that adds A into B.
- say that B must not be fill complete (this was already asserted in
the function, so won't break user code)
- don't say 'currently not functional' because it works fine
and is tested
- Split Add version that takes A,B,C into 2 overloads
- Backwards compatible
- Before, took RCP by value.
- Now, one takes const RCP& (adding into existing C) and the other takes RCP& (adding
into existing C, or creating C if it's null on input). The
documentation is updated and needs no warning saying "this …

Fix #12565 and Tpetra::MatrixMatrix::Add in general

---

packages/intrepid/src/Shared/Intrepid_Types.hpp
packages/intrepid2/src/Shared/Intrepid2_TensorViewIterator.hpp
packages/intrepid2/src/Shared/Intrepid2_Types.hpp

This should fix compiling all the `Intrepid*` tests using `SYCL`. Note that `SYCL` requires explicitly specifying the underlying type for all enums used in device code.

Intrepid2: Fix enums for SYCL

---

packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorerUtils.hpp
packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
packages/zoltan2/test/core/TpetraCrsColorer/Bug9500.cpp
packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp

This should fix compiling `Zoltan2` and its tests using `SYCL`.

Zoltan2: Fix compiling with SYCL

---

packages/framework/pr_tools/PullRequestLinuxDriver.sh

Seeing too many OOM errors from the Intel compiler (and even the Gnu one sometimes).
Seeing repeated OOM errors in Intrepid2 ( @trilinos/intrepid2 )
#12571

Framework: Increase mem/core from 3 to 4 Gb

---

packages/muelu/test/scaling/Driver.cpp

``--watchr-problem-name="..."`` lets the Watchr plot name be customized easily. The default is still "MueLu Setup-Solve N ranks".
Makes it easier to add performance tests with using the MueLu driver.
Tested by running Driver with default settings, with a custom problem name, and with ``--help``.

MueLu: add --watchr-problem-name option to Driver

---

packages/compadre/src/Compadre_Operators.hpp
packages/compadre/src/Compadre_Quadrature.hpp

@trilinos/compadre
This should fix compiling all the `Compadre` tests using `SYCL`. Note that `SYCL` requires explicitly specifying the underlying type for all enums used in device code.

Compadre: Fix enums for SYCL

---

packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp

Handle a corner case in RefMaxwell rebalancing more gracefully. If some rank has no entries, don't force assign any partition there.

MueLu RefMaxwell: Handle another corner case for rebalancing

---

packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp

Fencing stream check not working if gpu device id is not equal to 0. Temporarily disabling.

Phalanx: temporary disable of failing test

---

packages/framework/ini-files/config-specs.ini

This is in response to #12391 and will set `--mca btl vader,self` for builds with openmpi 
#12391 
After building and running `ctest -VV` I see:
```
Test command: /projects/sems/install/rhel7-x86_64/sems/compiler/gcc/8.3.0/openmpi/1.10.1/bin/mpirun "--bind-to" "none --mca btl vader,self" "-np" "1" "/scratch/jfrye/build/TRILFRAME-608-disable-tcp/packages/tempus/test/IMEX_RK/Tempus_IMEX_RK_Combined_FSA_Tangent.exe"
```

Framework: Explicitly disable tcp for PR testing with openmpi 

---

packages/intrepid2/src/Shared/Intrepid2_Utils.hpp

This should fix compiling with `SYCL` using `Intrepid2`.

Intrepid2: Fix compiling with SYCL

---

packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py

No need to ; join something that's already passed as a ;-joined string.

Framework: Correct list/string joining

---

packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefTensor.hpp
packages/intrepid2/unit-test/Discretization/Integration/test_util.hpp

When moving from Intrepid to Intrepid2, Sierra noticed substantial performance degradation in one of their performance tests.  The most egregious offender was `HGRADtransformGRAD`, which ultimately calls `ArrayTools::Internal::matvecProduct()`.  The functor called by the latter involved Kokkos subviews and a fair amount of run-time branching.
This PR reimplements that functor to eliminate both the use of subviews and the run-time branching, in favor of compile-time template specializations of the functor, combined with logic that selects the appropriate specialization prior to the launch of the parallel kernel.  In our testing with parameters intended to reproduce Sierra's performance tests, this results in a roughly 3x speedup, with performance that outperforms the …

Intrepid2: Optimizations for pullbacks (among others)

---

.github/PULL_REQUEST_TEMPLATE.md

Add a reminder about adding the release notes label to the PR template.

GitHub PR template: Add reminder about release notes

---

.git-blame-ignore-revs

@trilinos/muelu applied clang-format to `packages/muelu`, but we don't want to see these changes listed in `git blame`.
The new file has the two commits that should be ignored.
In order to use it, do a 
```
git config blame.ignoreRevsFile .git-blame-ignore-revs
```

Ignore commits with changes from clang format

---

cmake/ProjectCompilerPostConfig.cmake
packages/framework/ini-files/config-specs.ini

Always use `-fp-model=precise` when building with Intel OneAPI C++ compiler.  We need it, or else tests fail.  Also multiple downstream customers have discovered this when using the newer Intel compiler.
Users should not have to know magic flags to use when building Trilinos.
https://github.com/trilinos/Trilinos/issues/12470
I tested this with the old (classic) Intel compiler and a OneAPI (nextgen) one.  Behavior was as expected.

Framework: Add '-fp-model=precise' when using OneAPI compiler

---

packages/framework/ini-files/config-specs.ini

Several tests run too long in debug mode while the platform is loaded causing timeout failures. Disabling them. Reviewing recent runtimes, disabled tests that ran longer than about 5 minutes. These are only disabled for debug builds so still getting coverage with other builds.
Reduce the number of random timeouts.
* Closes #12623 
* Related to #12622

Tempus: Disable Tests That Run Too Long

---

packages/teuchos/comm/test/Comm/DefaultMpiComm_UnitTests.cpp

Test output was tripping up ctest.  Test is actually passing.
See failure at https://trilinos-cdash.sandia.gov/viewTest.php?onlyfailed&buildid=1324385.
N/A
Will verify on nightly dashboard.

Teuchos: remove spurious test output

---

packages/belos/doc/index.doc
packages/belos/src/BelosRCGSolMgr.hpp
packages/belos/src/BelosStatusTestGenResSubNorm.hpp

@hkthorn
Minor fixes to Doxygen comments:
- Seeks to solve two "duplicate anchor" warnings (causes problems when importing the tag file when using "warn as error").
- Add missing closing \f$ (to avoid that Doxygen considers everything that follows as a LaTeX comment). 
Joined work with @romintomasetti.

Belos: Avoid duplicate doxygen anchors. Add missing closing \f$.

---

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ReitzingerPFactory_def.hpp

Issue: #11214
Stakeholder feedback: Test now runs
Test: n/a
[![Check MueLu clang-format](https://github.com/trilinos/Trilinos/actions/workflows/muelu_clang_format.yml/badge.svg)](https://github.com/trilinos/Trilinos/actions/workflows/muelu_clang_format.yml)

MueLu: Removing superfluous check for ranks without edges .

---

packages/teuchos/core/src/Teuchos_CommandLineProcessor.cpp
packages/teuchos/core/test/CommandLineProcessor/CMakeLists.txt
packages/teuchos/core/test/CommandLineProcessor/Teuchos_CLP_Remove_Quotes.cpp

Many tests in Tempus fail due to parsing between tribits, ctest and MacOS 14 that finally leaves an argument with a single double quote, i.e.,
TRIBITS_ADD_TEST(
ExplicitRK_Combined_FSA
NAME "ExplicitRK_Combined_FSA_RK_Forward_Euler"
ARGS "--method=\"RK Forward Euler\""
NUM_MPI_PROCS 1
)
When using ctest on a Mac, the --method arugment becomes 'RK Forward Eule' and the test fails.  The string making it to Teuchos::remove_quotes() is '"RK Forward Euler' which removes the double quote and the 'r'. Modifying Teuchos::remove_quotes() to remove a leading double quote and/or a trailing double quote fixes this issue.
Note: If the test is run directly, either
% /opt/homebrew/bin/mpiexec "-np" "1" "/Users/ccober/myOffice/Tempus-Project/Trilinos_build/packages/tempus/test/ExplicitRK/Tempus_ExplicitRK …

Teuchos: Handle non-matching quotes in CLP on Mac

---

packages/framework/get_dependencies.sh

If we want to relocate the project, the paths need to be at least relative enough to move 'Trilinos'. Concrete use case is if we mount an existing code project into a container.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-617
Tested in a container and with one build on my workstation

Framework: Use relative paths for .ini symlinks

---

packages/framework/pr_tools/PullRequestLinuxDriverMerge.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverMerge.py

The current pull request testing system will perform a fast-forward merge whenever possible on the topic and target branches being merged for testing. 
The default behavior for [GitHub Actions merges](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github) is to never allow a fast-forward merge with the `--no-ff` option. This change will follow the same convention for AutoTester pull request testing.
Additional motivation is to consistently have a merge commit for the TriBITS repo version configure output for every pull request test. 
- TriBITSPub/TriBITS#597
[TRILFRAME-614 story comment](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-614?focusedCommentId=6180 …

Framework: force no fast-forward merges for pull request testing

---

packages/teko/src/Epetra/Teko_BlockedEpetraOperator.cpp
packages/teko/src/Epetra/Teko_StridedEpetraOperator.cpp
packages/teko/src/Teko_Utilities.cpp
packages/teko/src/Teko_Utilities.hpp
packages/teko/src/Tpetra/Teko_BlockedTpetraOperator.cpp
packages/teko/src/Tpetra/Teko_StridedTpetraOperator.cpp

When > 10 subblocks are present, there's no way to disambiguate between the output for $A_{11,1}$ and $A_{1,11}$. This PR adds a trivial `_` character to seperate the entries in the various `*::WriteBlocks` functions.
@trilinos/Teko
@cgcgcg

Add seperator for subblock numbering for outputting Teko block matrices

---

cmake/std/atdm/van1-tx2/all_supported_builds.sh
cmake/std/atdm/van1-tx2/custom_builds.sh
cmake/std/atdm/van1-tx2/custom_builds_unit_tests.sh
cmake/std/atdm/van1-tx2/environment.sh

and make it the default, over armclang 20.1, as that version will be phased out soon, when the main nodes are updated to TOSS4.
For example:
``stria-arm-release`` and ``stria-default-release`` both load the arm/22.1 environment now.
``stria-arm-20-release`` and ``stria-arm-20.1-release`` still load arm/20.1.
Also updated the ATDM config test for van1-tx2.
BTW, there is also arm/21.0 installed, but not a corresponding sparc-dev to load all the TPLs. Loading the 22.1 version and then swapping just the compiler might work if that's needed, but I didn't try it.
Couple of reasons:
- arm20.1 will be dropped when Stria's gets updated to TOSS4
- arm20.1 compiler currently has an issue preventing it from being used
Added ATDM config tests, also made sure the correct modules …

Framework: Add van1-tx2 ATDM environment for armclang 22.1

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

When using the Schur complement approach, some values were implicitly reused from one setup phase to another.
This was a bug and it is fixed by zeroing out the `scalar_values_schur` view.

Ifpack2: Zero out the scalar_values_schur not to reuse values of a previous setup phase

---

packages/ifpack2/src/Ifpack2_Parameters.cpp

Add "schwarz: reordering list" as a valid Ifpack2 parameter. This fixes #12658.

Ifpack2: add reordering sublist to valid parameters

---

packages/amesos2/test/solvers/MUMPS_test.xml
packages/kokkos-kernels/lapack/tpls/KokkosLapack_magma.hpp
packages/rol/example/PDE-OPT/thermal-fluids/input_ex04.xml

@trilinos/kokkos-kernels @trilinos/amesos2 @trilinos/rol

Kokkos-Kernels,Amesos2,ROL: Fix tiny issues

---

.github/workflows/clang_format.yml

The clang-format action did not work correctly for PRs from forks. This change appears to fix that.

Attempt to fix clang-format workflow

---

packages/teko/src/Teko_Utilities.cpp
packages/teko/tests/src/tExplicitOps_tpetra.cpp
packages/teko/tests/src/tExplicitOps_tpetra.hpp

Have the explicitAdd in Teko reuse the existing operator pointer if possible (when the sparsity pattern is unchanged).
The goal is to reuse the setups of Ifpack2 smoothers when using reuse options in MueLu.
Reuse of Ifpack2 smoothers, such as additive schwarz, rely on the underlying operator pointer being the same
(see: https://github.com/trilinos/Trilinos/blob/9665b8ef28ce53e3a47ad2243fdcb33b73ff49f4/packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp#L1754).
(Note: MueLu does not check this and will happily report that it is reusing the smoother setup while ifpack2 is actually rebuilding the smoother from scratch.)
This fix allows MueLu and Ifpack2 to reuse the smoother setup.
It also contains some updates to the block detecting logic for the explicitAdd.

Teko: explicitAdd reuse existing operator if possible

---

packages/muelu/test/unit_tests/CMakeLists.txt
packages/muelu/test/unit_tests/Regression.cpp
packages/muelu/test/unit_tests_kokkos/CMakeLists.txt
packages/muelu/test/unit_tests_kokkos/Regression.cpp

Adds unit tests that count the number of deepcopies for Hierarchy setup and a single iteration, once for the non-Kokkos code path and once for the Kokkos code path.

MueLu: Add H2D regression test

---

packages/ifpack2/test/unit_tests/Ifpack2_SolverFactory.cpp

Adds a check that verifies that the preconditioners correctly split between symbolic and numeric phases.
@vbrunini Does this match what you requested? If so, it should be easy enough to match this pattern for other solvers/preconditioners.

Ifpack2: Check that symbolic/numeric phases are respected

---

cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake
cmake/tribits/core/utils/TribitsGitRepoVersionInfo.cmake
cmake/tribits/ctest_driver/TribitsAddDashboardTarget.cmake
cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake
cmake/tribits/doc/build_ref/TribitsBuildReferenceBody.rst
cmake/tribits/doc/guides/TribitsCoreDetailedReference.rst
cmake/tribits/examples/TribitsExampleProject2/packages/package1/test/CMakeLists.raw.cmake
packages/framework/ini-files/config-specs.ini

This TriBITS snapshot pulls in updates to TriBITS 'master' from the TriBITS PRs:
* TriBITSPub/TriBITS#598 (The main motivation for this TriBITS snapshot)
* TriBITSPub/TriBITS#599

Update TriBITS snapshot 2024-01-24 and set Trilinos_SHOW_GIT_COMMIT_PARENTS=ON for PR builds

---

packages/stk/stk_ngp_test/stk_ngp_test/GlobalReporter.cpp
packages/stk/stk_ngp_test/stk_ngp_test/GlobalReporter.hpp
packages/stk/stk_ngp_test/stk_ngp_test/Reporter.hpp
packages/stk/stk_ngp_test/stk_ngp_test/ngp_test.cpp

@trilinos/stk
This should fix compiling and running all the `STK` tests using `SYCL`. Note that the `SYCL` doesn't support virtual device functions (yet).

STK: Implement Reporter without virtual

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_decl.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
packages/tpetra/core/src/Tpetra_CrsGraphTransposer_def.hpp
packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp

PR kokkos/kokkos-kernels#1962 introduced API updates to the spadd_* routines This is allowed as spadd resides in the Experimental namespace, but requires propagating backward-compatibility breaking changes to Trilinos
Resolve kokkos/kokkos-kernels#2089
@trilinos/tpetra @brian-kelley @csiefer2
Fix compilation errors with kokkos-kernels@develop branch
Locally tested Tpetra in a Cuda build on Weaver (rhel8 queue) with this configuration:
```bash
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/weaver
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh weaver-cuda-11.2-opt
export OMPI_CXX="$KOKKOS_PATH/bin/nvcc_wrapper"
cmake \
-D CMAKE_CXX_FLAGS='-g' \
-D CMAKE_CXX_STANDARD="17" \
-D CMAKE_INSTALL_PREFIX=$PWD/install \
-D …
```

tpetra: update spadd_* api for KOKKOSKERNELS_VERSION >= 40299

---

packages/ifpack2/test/unit_tests/Ifpack2_SolverFactory.cpp
packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp
packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp

A few asserts were using the wrong views. There were many parallel_fors that were using the default exec space even when ExecSpace for the class was set to Serial. This was causing GPU kernels to try to access Serial views
Fixes #12685 
Tested `./Ifpack2_SolverFactory.exe --details=ALL` on weaver with both Serial and GPU exec spaces enabled. I confirmed the error from #12685 occurs before the fixes in this PR and goes away when these fixes are applied.

Fix Shylu GPU/Serial issues

---

packages/framework/ini-files/config-specs.ini

Want the GenConfig spec to accurately reflect the build configuration.  If it says no-complex, complex should not be enabled.
Closes #12686

Framework: Remove complex from all declared non-complex configs

---

doc/build_ref/TrilinosBuildReferenceTemplate.rst

@ndellingwood 
@trilinos/???
The memkind third-party library was there to support the `Kokkos::Experimental::HBWSpace` exclusively.
It was broken for a long time and has been removed in https://github.com/kokkos/kokkos/pull/6791

Build documentation: remove mention of "memkind" as a Kokkos TPL

---

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
packages/panzer/adapters-stk/test/projection/projection.cpp
packages/panzer/disc-fe/src/Panzer_BasisDescriptor.cpp
packages/panzer/disc-fe/src/Panzer_BasisDescriptor.hpp
packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
packages/panzer/disc-fe/src/Panzer_IntrepidOrientation.cpp
packages/panzer/disc-fe/src/Panzer_IntrepidOrientation.hpp
packages/panzer/disc-fe/src/Panzer_L2Projection.cpp
packages/panzer/disc-fe/src/Panzer_L2Projection.hpp
packages/panzer/disc-fe/src/Panzer_PureBasis.hpp
packages/panzer/disc-fe/src/Panzer_WorksetContainer.cpp
packages/panzer/mini-em/src/solvers/MiniEM_Interpolation.hpp
packages/panzer/mini-em/src/solvers/MiniEM_MatrixFreeInterpolationOp.cpp

Improve multiple mass matrix assembly by reusing workset information where possible and moving to lazy evalaution in workset construction.
projection test modified to test the lazy construction path
<!---

Panzer improve mass matrix assembly

---

packages/teko/cmake/Dependencies.cmake
packages/teko/src/Teko_BlockInvDiagonalStrategy.cpp
packages/teko/src/Teko_BlockInvDiagonalStrategy.hpp
packages/teko/src/Teko_GaussSeidelPreconditionerFactory.cpp
packages/teko/src/Teko_JacobiPreconditionerFactory.cpp
packages/teko/tests/src/tBlockJacobiPreconditionerFactory_tpetra.cpp
packages/teko/tests/src/tBlockJacobiPreconditionerFactory_tpetra.hpp

@trilinos/teko
These changes allow to use preconditioned iterative solvers for the diagonal blocks of block Jacobi and Gauss-Seidel.
For example:
```xml
<ParameterList name="BGS">
<Parameter name="Type" type="string" value="Block Gauss-Seidel"/>
<Parameter name="Use Upper Triangle" type="bool" value="true"/>
<Parameter name="Inverse Type 1"  type="string" value="Amesos2"/>
<Parameter name="Inverse Type 2"  type="string" value="itSolver"/>
<Parameter name="Preconditioner Type 2"  type="string" value="prec"/>
</ParameterList>
<ParameterList name="itSolver">
<Parameter name="Type" type="string" value="Belos"/>
<Parameter name="Solver Type" type="string" value="Pseudo Block GMRES"/>
</ParameterList>
<ParameterList name="prec">
<Parameter name="Type" type="string" value="Ifpack2"/>
<Parameter …
```

Teko: Enable preconditioned sub-solves in block Jacobi and Gauss-Seidel

---

packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp
packages/xpetra/src/CrsGraph/Xpetra_CrsGraph.hpp
packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp
packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp
packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_def.hpp
packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_decl.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_decl.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_def.hpp

- Xpetra: Expose getLocalDiagOffsets and getLocalDiagCopy with Kokkos views
- MueLu: Fix #12736 and use Kokkos views in GetMatrixDiagonal

Xpetra&MueLu: Fix for diagonal extraction

---

packages/framework/ini-files/config-specs.ini

Build directories were jumping in size massively.  Previously, this setting seemed to have no effect, but after the merge of https://github.com/trilinos/Trilinos/pull/12707, the `-g` flag started showing up on compile lines (correctly).  Remove that setting from `configs-specs.ini` to get builds back to where they were before.
* Closes #12732 
I ran the configuration `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-off_all` with and without the change.  Without the change (at version https://github.com/trilinos/Trilinos/commit/9f40ed4121e6ebcd7df6b6510b9942c2106bae54) the build directory was over 600GB before the build was even completed.  With this change, the completed build …

Framework: Disable debug symbols

---

cmake/tribits/ci_support/CDashAnalyzeReportRandomFailures.py
cmake/tribits/ci_support/CDashQueryAnalyzeReport.py
cmake/tribits/core/package_arch/TribitsPackageDefineDependencies.cmake
cmake/tribits/doc/guides/TribitsGuidesBody.rst

Brings in TriBITS PRs:
* TriBITSPub/TriBITS#603 (main reason for updating this snapshot)
* TriBITSPub/TriBITS#602
* TriBITSPub/TriBITS#598

TriBITS snapshot 2024-02-13

---

packages/amesos2/CMakeLists.txt

We want to allow enabling Amesos2's Tacho interface when CUDA/HIP is enabled.
With
````
-D Trilinos_ENABLE_ShyLU_NodeTacho:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
````
or with
````
-D Trilinos_ENABLE_ShyLU_NodeTacho:BOOL=ON \
-D Trilinos_ENABLE_Amesos2:BOOL=ON \
-D   Amesos2_ENABLE_ShyLU_NodeTacho:BOOL=ON \
````
we get
````
-- NOTE: Disabling Amesos2_ENABLE_ShyLU_NodeTacho because CUDA or HIP is enabled in Kokkos
````
[PR 12291](https://github.com/trilinos/Trilinos/pull/12291) replaced:
````
IF (Trilinos_ENABLE_ShyLU_NodeTacho AND NOT Kokkos_ENABLE_CUDA AND NOT Kokkos_ENABLE_HIP)
SET(Amesos2_HAVE_TACHO ON)
ELSE()
SET(Amesos2_HAVE_TACHO OFF)
ENDIF()
````
with
````
IF (Kokkos_ENABLE_CUDA OR Kokkos_ENABLE_HIP)
tribits_disable_optional_dependency(ShyLU_NodeTacho …
```

Amesos2 : remove "Disabling Amesos2_ENABLE_ShyLU_NodeTacho because CUDA or HIP is enabled in Kokkos"

---

packages/nox/src-epetra/NOX_Epetra_MatrixFree.C
packages/nox/test/epetra/NOX_Operators/test.C

@rppawlo
This PR fixes issue #12715 , and adds a couple of tests to exercise the `Backward` and `Centered` difference modes for `NOX::Epetra:MatrixFree`.
* Closes issue #12715 
In the very first commit 77495f1, this PR adds checks to trigger the issue, then resolves the issue in the next commit 57041c3.
All commits after the first two of the PR are just very small tidying up of the code to make it easier to follow and avoid similar issues; please feel free to review and accept/reject those commits as needed as they are not essential to the PR.
Some of these commits might improve performance by making use of a single `update()` call and reducing intermediate copies or passes over the vectors.
I just want to draw your attention to the fact that I've assumed that a sequence like this:
```c++ …
```

NOX: add tests, fix NOX::Epetra::MatrixFree for backward difference (12715)

---

packages/krino/krino/CMakeLists.txt

Setting `-DTrilinos_ENABLE_Krino=ON` `-DTrilinos_ENABLE_TESTS=OFF` `-DTrilinos_ENABLE_Gtest=OFF` yielded build errors finding gtest headers, which showed that Krino tests were still being built. Disable them conditionally with the
`TRIBITS_ADD_TEST_DIRECTORIES()` macro (note that this is the correct thing do to as per
https://tribits.org/doc/TribitsUsersGuide.html#tribits-add-executable-and-test)
Want to be able to disable the build of test executables in Krino with `-DTrilinos_ENABLE_TESTS=OFF`.  I need to do this to add a build-only PR line.
Tested my local build with this change and the test executable did not get built (which was the expected behavior).

Krino: Do not process krino tests if testing is disabled

---

packages/muelu/research/caglusa/Xpetra_HierarchicalOperator_decl.hpp
packages/muelu/research/graham/mf_example_01.cpp
packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp
packages/muelu/test/interface/CreateOperator.cpp
packages/muelu/test/scaling/MatrixLoad.hpp

- Fix a bad view in `GetMatrixDiagonal`. #12767 
- Silence some warnings.
- Fix build errors in research code.

MueLu: Fixes

---

cmake/SimpleTesting/cmake/ctest-cdash-setup.cmake
cmake/SimpleTesting/cmake/ctest-common.cmake
cmake/SimpleTesting/cmake/ctest-functions.cmake
packages/framework/pr_tools/PullRequestLinuxDriver.sh
packages/framework/pr_tools/PullRequestLinuxDriverTest.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py

Current build names posted to CDash use GenConfig build name strings which are unreadable at a glance when trying to differentiate between build lines. The build names should only include "special" attributes of the GenConfig strings to be more easily readable. 
This will be trialed with the nightly builds first.
- Jenkins nightly jobs have new env variable `DASHBOARD_BUILD_NAME`
- This env variable is read by the PR scripts somewhere and uses this value when posting to the CDash track `Nightly`
- [TRILFRAME-620](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-620)
- `test_TrilinosPRConfigurationBaseBuildNameNightlyTrack`
- `TrilinosFrameworkTests` testing all related Trilinos PR scripts touched by these changes

Framework: Rename nightly builds with custom dashboard name

---

packages/zoltan/src/hier/hier.c
packages/zoltan/src/phg/phg_build_calls.c

Addresses issues #12729 and #12730.
The fix to #12729 is likely not exercised by tests, as I can't seem to find any that set `NUM_LID_ENTRIES` to zero.
The fix to #12730 should be exercised by existing hierarchical partitioning tests.

Zoltan: fix crashes in phg and hierarchical partitioning

---

packages/ifpack2/src/Ifpack2_SparseContainer_decl.hpp
packages/ifpack2/src/Ifpack2_SparseContainer_def.hpp
packages/ifpack2/test/belos/CMakeLists.txt
packages/ifpack2/test/belos/test_BlockRelaxationAmesos2_calore1_mm.xml

Attempt to reorganize the symbolic/numerical setup of SparseContainer.
It is still on host, but this lets us call initialize on each block during symbolic setup (for BlockRelaxation) and addresses [Issue#12789](https://github.com/trilinos/Trilinos/issues/12789).

ifpack2 : reorganize symbolic/numeric setup of SparseContainer 

---

packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp
packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.cpp
packages/sacado/test/performance/mat_vec/common.hpp
packages/sacado/test/performance/mat_vec/driver.cpp
packages/sacado/test/performance/mat_vec/fad_kokkos_mat_vec_perf.cpp
packages/sacado/test/performance/mat_vec/mat_vec.cpp
packages/sacado/test/performance/mat_vec/mat_vec_hierarchical.cpp
packages/sacado/test/performance/mat_vec/mat_vec_hierarchical_dfad.cpp

Doing some performance testing of sacado and panzer kernels on MI250s. Needed to update some code for HIP backend.
sacado mat_vec and all panzer hierarchic parallelism tests

Sacado/Panzer: updates for HIP performance testing

---

packages/panzer/mini-em/example/BlockPrec/MiniEM_helpers.cpp
packages/panzer/mini-em/example/BlockPrec/maxwell-large.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLu.xml
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
packages/panzer/mini-em/src/solvers/MiniEM_HigherOrderMaxwellPreconditionerFactory.cpp
packages/panzer/mini-em/src/solvers/MiniEM_Interpolation.cpp
packages/panzer/mini-em/src/solvers/MiniEM_Interpolation.hpp
packages/teko/src/Teko_Utilities.cpp
packages/teko/src/Teko_Utilities.hpp

- Improve assembly of interpolation operators such as discrete gradient and curl and transfers for p-multigrid.
- Skip assembly of operators that are just scalar multiples of each other.

Panzer MiniEM: Refactor interpolations, assemble fewer operators

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

This PR adds a logic to automatically deduce a suitable number of subparts per part.
The logic relies on a local minimization of the number of flops per worker of the solve phase.
By default, this logic is now used except if the user provides a  number of subparts per part.

Ifpack2: add getAutomaticNSubparts

---

packages/framework/ini-files/config-specs.ini

PR blocks are unused (big mistaken assumption on my part).  We use no-package-enables for PR builds.  So, change the UVM no-package-enables to disable the tests, and remove all of the pr blocks.  This will prevent PRs from trying to build tests/examples in UVM-on builds and erroring out.
Allows for using the configuration `rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_uvm_deprecated-on_no-package-enables` for a new PR build.

Framework: Remove PR naming blocks

---

packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py

Recently renamed dashboard build names for the Nightly track by using a custom string set with `DASHBOARD_BUILD_NAME` environment variable inside Nightly Jenkins jobs. Nightly Kokkos Integration build names should follow this as well.
- #12760 
- [TRILFRAME-620](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-620)
`test_TrilinosPRConfigurationBaseBuildNameKokkosTrack`
`TrilinosFrameworkTests` testing all related Trilinos PR scripts touched by these changes

Framework: Rename Kokkos nightly integration builds with custom dashboard name

---

packages/panzer/mini-em/src/solvers/MiniEM_Interpolation.cpp

Fix compile error when UVM=ON as seen in #12802.

Panzer MiniEM interpolation: Fix memory spaces

---

packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_CrsMatrix_UQ_PCE.hpp
packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_CrsMatrix_MP_Vector.hpp

Update the stokhos/sacado overloads of ``KokkosSparse::spmv`` in preparation for the KokkosKernels 4.3 release.
This fixes ``Stokhos_KokkosCrsMatrixUQPCEUnitTest_Cuda_MPI_1`` and ``Stokhos_KokkosCrsMatrixMPVectorUnitTest_Cuda_MPI_1`` runtime failures when building against Kokkos and KokkosKernels develop.
See discussion here: https://github.com/kokkos/kokkos-kernels/issues/2130#issuecomment-1979339518
@ndellingwood 
KK 4.3 includes some changes to the interface of spmv (Controls is replaced by SPMVHandle). If the KK version is at least 40299 (4.3 prerelease) then make the spmv overloads for sacado types follow the new interface.
Tested on kokkos-dev2, cuda 11.4.2
- this PR as-is
- this PR built with develop branch kokkos, kokkos-kernels
There are 2 existing failures in …

Stokhos: prepare for KokkosKernels 4.3 spmv refactor

---

packages/xpetra/src/Operator/Xpetra_TpetraHalfPrecisionOperator.hpp

@xpetra
@jhux2 
https://github.com/trilinos/Trilinos/issues/12820

Xpetra: Add missing const qualifiers to getDomainMap and getRangeMap

---

packages/framework/ini-files/config-specs.ini

Need this configuration to have a nightly build that replicates PR.  In this particular case, it's for adding a CUDA Kokkos+KokkosKernels develop integration line.

Framework: Add nightly cuda config

---

packages/panzer/mini-em/example/BlockPrec/solverMueLuCuda.xml

Less robust than using a full multigrid hierarchy, but faster on out test problems.

Panzer MiniEM: Use truncated MG hierarchies on GPU

---

packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_AlgebraicOverlappingOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_decl.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_decl.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_OverlappingOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_SchwarzOperator_decl.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_SumOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzPreconditioners/FROSch_GDSWPreconditioner_decl.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzPreconditioners/FROSch_RGDSWPreconditioner_decl.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzPreconditioners/FROSch_TwoLevelPreconditioner_decl.hpp
packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_Amesos2SolverTpetra_def.hpp
packages/shylu/shylu_dd/frosch/src/Tools/FROSch_ExtractSubmatrices_decl.hpp
packages/shylu/shylu_dd/frosch/src/Tools/FROSch_ExtractSubmatrices_def.hpp

This PR moves some symbolic codes from the numerical phase of FROSch to the symbolic:
- Symbolic factorization of K_{I,I}

Frosch : symbolic / compute setups

---

packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp

* `Tpetra::MatrixMarket::Writer` wasn't complaining when the output stream could not be opened. Therefore the writer was finishing its work without actually writing anything. Now, opening the output stream is safe and throws if the output stream could not be opened (all ranks throw as for `Tpetra::MatrixMarket::Reader` using a MPI broadcasting).
* `Tpetra::MatrixMarket::Reader` was safe but had the safety code copy-pasted all over the place. Made a function to centralize that aspect.

Tpetra: (matrix market) make writer safer and reader less copy-pasted

---

packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
packages/panzer/mini-em/example/BlockPrec/MiniEM_helpers.cpp
packages/panzer/mini-em/example/BlockPrec/MiniEM_helpers.hpp
packages/panzer/mini-em/example/BlockPrec/main.cpp
packages/panzer/mini-em/example/BlockPrec/solverMueLuCuda.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuTruncated.xml

Allows to select whether the multigrid preconditioner should be set up with truncated hierarchies.
The option is disabled by default, meaning that a full hierarchy will be set up.

Panzer MiniEM: Make truncating MueLu hierarchies optional

---

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_MatrixApplyHelper.hpp
packages/tpetra/core/src/Tpetra_Details_residual.hpp

- Integrate SPMVHandle (for KokkosKernels 4.3+), enabling reuse of matrix analysis
- Rework how int-typed rowptrs are handled. Now works for BlockCrsMatrix too, and rocsparse can be used (not just cusparse)
This adds a new helper struct ``Tpetra::Details::MatrixApplyHelper`` which deals with the rowptrs and SPMVHandles (one for the int-rowptr typed matrix and one for the standard local device matrix). This is temporary - in KokkosKernels 4.4, int will become the default rowptr type so we can get rid of the helper and replace it with a simple SPMVHandle.
- Performance improvements for ``CrsMatrix::apply`` and ``BlockCrsMatrix::apply``.

Tpetra: matrix apply TPL improvements

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

@jjellio 
This PR fixes #12132 by using `assumeMpiIsGPUAware()` to deduce if GPU Aware MPI can be used or if the data needs to be copied to host before/after sending/receiving respectively.
The branch has been tested on V100 using:
```
TPETRA_ASSUME_GPU_AWARE_MPI=0 \
mpirun -np 4 Ifpack2_BlockTriDiagonalSolver.exe  \
--withoutOverlapCommAndComp  --matrixType=Laplace3D  \
--blockSize=11  --nx=64  --ny=32  --nz=64  \
--sublinesPerLine=1  --tol=0  --numIters=2  --withStackedTimer
```
and
```
TPETRA_ASSUME_GPU_AWARE_MPI=1 \
mpirun -np 4 Ifpack2_BlockTriDiagonalSolver.exe  \
--withoutOverlapCommAndComp  --matrixType=Laplace3D  \
--blockSize=11  --nx=64  --ny=32  --nz=64  \
--sublinesPerLine=1  --tol=0  --numIters=2  --withStackedTimer
```
Before this fix, the run with …

Ifpack2: Use assumeMpiIsGPUAware in BTDS

---

packages/seacas/libraries/exodus/src/ex_put_concat_elem_block.c
packages/seacas/libraries/ioss/src/Ioss_Region.h
packages/seacas/libraries/ioss/src/Ioss_StructuredBlock.h
packages/seacas/libraries/ioss/src/Ioss_ZoneConnectivity.h
packages/seacas/libraries/ioss/src/main/io_info.C

Remove uses of the lib::fmt include files in ioss header files that are installed and used by external clients.  Since lib::fmt is used only as an embedded library in the Trilinos instantiation of SEACAS/IOSS, the installed include files cannot reference fmt files.
Also protect the use of the `nc_def_var_fill` function since it only appears in later versions of the netCDF library or in earlier versions that use the netcdf-4 (HDF5) capability.

SEACAS: fix bad commits

---

packages/ifpack2/example/BlockTriDi.cpp
packages/ifpack2/src/Ifpack2_BlockRelaxation_decl.hpp
packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp
packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_decl.hpp
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp

This PR enables the usage of the BlockTriDiagonal Solver (BTDS) for cases where the matrix is stored as a `CrsMatrix` and not a `BlockCrsMatrix`.
In that situation, the setup phase of the solver will first convert the `CrsMatrix` to a blocked one and then the usual setup of the BTDS is performed.
While the `CrsMatrix` to `BlockCrsMatrix` conversion was first relatively costly, a kokkosficiation (included in this PR) of `convertToBlockCrsMatrix` allowed to significantly improve the performance of the conversion.
The features of this PR will be used in the Matrix dependent semi-coarsening algebraic multigrid (MDSC-AMG) for Albany Land Ice  simulations.
@trilinos/tpetra ( for the `convertToBlockCrsMatrix`)
The PR includes extra tests to cover the new features.

Ifpack2: Add support for pointwise matrices in BTDS and parallelize the crs to block conversion

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

This PR fixes #12871 and #12132 using a different approach than the merged PR #12864 that introduces the issue #12871.
In #12864 if a GPU aware MPI is not used, every nonblocking sends and receives use a mirror view on host to do the message passing.
However, this requires new blocking points after a nonblocking receive and before copying the data back to the device view and those points were not included in #12132.
Instead, this PR uses an approach that does not introduce extra blocking points and uses the existing ones encountered before `copy<ToMultiVector>` to copy the data from the host to the device.
Similarly, the copy from device to host is done just after `copy<ToBuffer>`.
This branch has been tried on Caraway MI210 and the issue of #12871 is gone with this branch. …

Ifpack2: Fix #12871

---

packages/stokhos/test/UnitTest/Stokhos_KokkosArrayKernelsUnitTest_OpenMP.cpp
packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixMPVectorUnitTest_OpenMP.cpp
packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixUQPCEUnitTest_OpenMP.cpp
packages/stokhos/test/UnitTest/Stokhos_KokkosViewFadMPVectorUnitTest_OpenMP.cpp
packages/stokhos/test/UnitTest/Stokhos_KokkosViewMPVectorUnitTest_OpenMP.cpp
packages/stokhos/test/UnitTest/Stokhos_KokkosViewUQPCEUnitTest_OpenMP.cpp
packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest_OpenMP.cpp
packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixUQPCEUnitTest_OpenMP.cpp

@etphipp 
Several `OpenMP` versions of `Stokhos`'s unit tests override the flags that are passed to `Kokkos::initialize`. They hardcode a number of OpenMP threads that they deduce from calls to `get_available_numa_count()` and `get_available_threads_per_core()`. Many of these unit tests use MPI, e.g. 4 MPI ranks. An issue is then that when these unit tests run on a single CPU, and all the MPI ranks are thus on this CPU, we have oversubscription.
For example, in our group, we run the trilinos tests on a workstation with a single cpu (16 cores/32 threads). We see these Stokhos tests asking for 4 * 32 threads. This has never caused a noticeable issue until recently. We updated our OpenMPI and one of these unit tests slowed down very significantly. The issue went away when …

Stokhos: Initialize Kokkos from cml args in unit tests in stokhos

---

packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
packages/muelu/src/Misc/MueLu_RAPFactory_def.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp
packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
packages/tpetra/core/src/Tpetra_Details_residual.hpp

@trilinos/tpetra @trilinos/muelu 
GPU related changes:
- Tpetra: Make use of TPL provided spmv in `Tpetra::residual` a runtime option
- MueLu: Don't set `Klu` options for non-Klu solvers (e.g.CuSOLVER)
- MueLu: Fix bad PL with Tpetra matrixmatrix options
- MueLu: Only warn in setup about levels without smoother/coarse solver. Fixes #8955

Tpetra,MueLu: GPU fixes

---

packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp
packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_decl.hpp
packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp
packages/thyra/core/src/interfaces/operator_vector/fundamental/Thyra_VectorSpaceBase_decl.hpp

@trilinos/belos @trilinos/thyra 
The Thyra adapter for Belos does the following in `MvTransMv`:
- "alias" the SerialDenseMatrix $c$ for the result to a cached MV $C$, copying the contents of $c$ to $C$,
- computing $C:=\alpha A^T B$,
- copying $C$ to $c$.
The deepcopy in the first step is not required.

Belos-Thyra adapter: Eliminate a deepcopy from MvTransMv

---

packages/tpetra/core/src/Tpetra_LocalCrsMatrixOperator_def.hpp
packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp

And make ``LocalCrsMatrixOperator::applyImbalancedRows`` just call the default spmv algorithm for now.
A merge path implementation exists in KokkosKernels but currently has an issue preventing it from being used (NaNs are not handled correctly).
Avoid warnings from using functions now deprecated in Kokkos/KokkosKernels 4.3.0.

Tpetra: fix a couple of deprecated warnings

---

packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/environment-specs.ini
packages/framework/ini-files/supported-envs.ini

Add a configuration entry to GenConfig that is meant for a general gcc-serial container configuration. This config will be used with a gcc-serial container to mimic the existing `Trilinos_PR_gcc-8.3.0-serial` PR test, but using the new AutoTester2 system and GitHub Actions.
This configuration is based on this existing configuration `rhel7_sems-v2-gnu-8.3.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables`.
- [TRILFRAME-629](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-629)
- Configured, built, and tested this configuration with an prototype gcc-serial container with no issues.

Framework: Add gcc-serial container config

---

packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C

The file Iocgns_Utils.C needs macros defined in cgnsconfig.h but was not including it directly. Adding this include fixes the nightly performance build on Stria.
Fixes this build error on Stria with cgns/3.4.0 loaded and enabled as TPL:
```
.../Trilinos/packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C:3038:2: error: "Not defined..."
#error "Not defined..."
^
```
The context for this error is:
```
3032 #if CG_BUILD_HDF5
3033   unsigned major;
3034   unsigned minor;
3035   unsigned release;
3036   H5get_libversion(&major, &minor, &release);
3037   fmt::print(config, "\t\tHDF5 enabled ({}.{}.{})\n", major, minor, release);
3038 #else
3039 #error "Not defined..."
3040 #endif
```
cgnsconfig.h is the file that contains ``#define CG_BUILD_HDF5 1``. I checked that the …

SEACAS Iocgns: add missing cgnsconfig.h include

---

.github/workflows/AT2.yml

Framework is beginning to convert and mimic existing Jenkins jobs to utilize GitHub Actions through the AutoTester2 (AT2) platform. This will mimic the existing `Trilinos_PR_gcc-8.3.0-serial` Jenkins job to a GitHub Actions workflow job that will run on the spawned gcc-serial containerized runner by the AT2 platform.
Follows:
- #12800 
- #12845
- #12902 
- [TRILFRAME-629](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-629)
This PR will serve as the workflow trigger to test the gcc-serial job.

Framework: Add gcc-8.3.0-serial job to AT2 workflow

---

packages/teuchos/core/src/Teuchos_LocalTestingHelpers.hpp
packages/teuchos/core/src/Teuchos_TestingHelpers.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp

Fixes #12898 , and adds a testing macro ``TEST_ABSOLUTE_COMPARE_FLOATING_ARRAYS( a1, a2, tol )``
to Teuchos that might be useful in other contexts.
Tested by first enabling the nondeterministic cuSPARSE SpMV algorithm, making `` TpetraCore_CrsMatrix_UnitTests4_MPI_4`` fail just like in #12898. Then applied these changes and checked that the test now passes.

Tpetra: Fix #12898, Teuchos: absolute float array compare

---

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp

@jhux2 
This PR fixes the pts->block conversion by using GIDs instead of relying on local IDs.

Tpetra: use GIDs to convert from point matrix to block matrix

---

packages/kokkos-kernels/sparse/impl/KokkosSparse_trsv_impl.hpp

@jhux2 @csiefer2 
This should fix the immediate issue with #12928. I think adding some additional unit test coverage for this corner case would also be beneficial.

ifpack2/kokkos-kernels: Early return in kokkos kernels sparse trsv in the event numRows == 0

---

packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_decl.hpp
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp

@csiefer2 observed that the pt to block converter failed in some cases.
This PR adds an option to use either local or global IDs for the conversion.
The failing case now work again when using local IDs.

Tpetra: fix converter bug

---

packages/tpetra/core/test/PerformanceCGSolve/CMakeLists.txt
packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp

Tpetra: Adding beefy CPU perf test options

---

packages/seacas/libraries/exodus/CMakeLists.txt

When doing a static library build, but still also building a shared exodus library, the library was being installed in a different area than what is expected by the exodus.py script that is using the shared library.  
This change seems to fix that issue and the exodus.py can correctly find the shared exodus library

SEACAS: Fix library naming

---

packages/kokkos-kernels/blas/tpls/KokkosBlas_Cuda_tpl.cpp
packages/kokkos-kernels/blas/tpls/KokkosBlas_Magma_tpl.hpp
packages/kokkos-kernels/blas/tpls/KokkosBlas_magma.hpp
packages/kokkos-kernels/blas/tpls/KokkosBlas_tpl_spec.hpp
packages/kokkos-kernels/lapack/tpls/KokkosLapack_Magma_tpl.hpp
packages/kokkos-kernels/lapack/tpls/KokkosLapack_gesv_tpl_spec_decl.hpp

Resolve issues with Magma and Cuda singleton multiple definitions Reported in kokkos/kokkos-kernels#2175
Patch generated from kokkos/kokkos-kernels#2176
Resolve compilation errors
@vqd8a 
Local testing in a Cuda Trilinos build with Magma enabled

kokkos-kernels: fix singleton multiple definitions

---

packages/tpetra/core/test/PerformanceCGSolve/CMakeLists.txt

This breaks the PERFORMANCE tests, because TriBITS does _not_ like having two tests with the same name.  Needs to get fixed.
Issue: #12935 
Stakeholder feedback:  As the stakeholder, I approve
Tests: This

Tpetra: Removing copy-pasta error

---

packages/nox/src-thyra/NOX_Observer_ReusePreconditioner.cpp
packages/nox/src-thyra/NOX_Observer_ReusePreconditioner.hpp
packages/nox/src-thyra/NOX_Observer_ReusePreconditionerFactory.cpp
packages/nox/test/tpetra/Tpetra_1DFEM.cpp

For efficiency, one might want to reuse the preconditioner over multiple nonlinear solves. If we have multiple stages in a DIRK method, this can be useful for reusing the same preconditioner for all solves within the time step. Previous work allowed reuse within a nonlinear solve. This adds reuse across multiple nonlinear solves.
new tests added to tpetra 1dfem

NOX: Reuse prec across multiple nonlinear solves

---

_config.yml
packages/nox/src/NOX_LineSearch_Polynomial.H

fix doxygen for nox - an equation is broken in newer versions of doxygen

Nox fix doxygen

---

packages/tpetra/core/src/Tpetra_Details_Behavior.cpp

Set behavior variable ``TPETRA_FUSED_RESIDUAL`` to OFF by default if a sparse TPL (cusparse, rocsparse, or MKL) is enabled. This improves performance of ``Tpetra::Details::residual`` compared to the Tpetra implementation of the fused residual.
The default is still ON if no TPLs are enabled.
#12982 
Will fix major performance regression reported by Sierra
Tested locally by building with cuSPARSE enabled, running the Ifpack2+Belos driver with Jacobi (which calls residual) and looking at the Kokkos profiling regions

Tpetra: use non-fused residual if TPLs available

---

packages/panzer/disc-fe/src/evaluators/Panzer_CellExtreme_impl.hpp

This functor causes a hang when compiling with cuda 12. There is a ticket in to nvidia for this. We can eventually revert this for later releases.
N/A

Panzer: fix cuda 12 compiler issue

---

packages/belos/src/BelosBlockCGSolMgr.hpp
packages/belos/src/BelosBlockGmresSolMgr.hpp
packages/belos/src/BelosPCPGSolMgr.hpp
packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp
packages/belos/tpetra/test/BlockGmres/CMakeLists.txt
packages/belos/tpetra/test/BlockGmres/test_bl_gmres_hb.cpp

Some of the solver managers, which use orthogonalization, have been modified to use the orthogonalization factory.  This modification created a bad piece of logic if the user provided the orthogonalization coefficient parameter for the DGKS orthogonalization class.  This coefficient was to be inserted into a parameter list object that was passed to the orthogonalization factory.  Unfortunately, this parameter list object was a null pointer, so providing that parameter would have caused the solver to abort.
This has been fixed for the affected solver managers and a block GMRES test has been modified to ensure that this fix adequately addresses the logic error (at least for block GMRES).
* Closes #12998 
OSX GCC13.x

Belos: Fixes null parameter list usage with orthogonalization factory

---

packages/seacas/scripts/exodus3.in.py

This fixes the exodus.py copyTransfer function when adding additional variables to a database that already has variables on it.
Fix the `copyTransfer` function when there are additional element/node/... variables being added onto an existing set of the same type of variables.

SEACAS: Fix exodus3.py copyTransfer

---

packages/intrepid2/src/Shared/Intrepid2_Polylib.hpp
packages/intrepid2/src/Shared/Intrepid2_Types.hpp
packages/intrepid2/unit-test/performance/StructuredIntegration/StructuredIntegrationPerformance.cpp

This PR adds support for StructuredIntegrationPerformance to save calibration results to file, and load calibrations from file.  It also increases `Intrepid2::MaxOrder`, the maximum polynomial reconstruction order supported by Intrepid2, from 8 to 10.
The tests exercise polynomial orders up to `MaxOrder`.

Intrepid2 StructuredIntegrationPerformance: add support for calibration from file

---

packages/kokkos-kernels/blas/tpls/KokkosBlas1_dot_tpl_spec_avail.hpp
packages/kokkos-kernels/blas/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp

It performs worse than our native impl.
See https://github.com/kokkos/kokkos-kernels/pull/2206 for details (this PR applies exactly the same changes)
@ndellingwood Heads up about another patch (this one probably shouldn't wait for the next release either)
Changes in KokkosKernels 4.3.0 enabled TPLs for ``KokkosBlas::dot`` in more cases. This was good for HIP/rocBLAS, but it turned out to be bad for CUDA/cuBLAS. This showed up on the performance dashboard for PerformanceCGSolve. I separately used the KK dot perftest to check CUDA versions 11.2, 11.8 and 12.0 and for all of them, cuBLAS dot was slower than KK native.
Fixes #12982. Turns out axpby was fine - the axpby time just appeared to increase because of kernels being async. But loading the Kokkos simple kernel …

KokkosKernels: disable cuBLAS dot wrapper

---

packages/kokkos-kernels/sparse/impl/KokkosSparse_spmv_spec.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_spmv.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_spmv_handle.hpp
packages/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_bsrmatrix_tpl_spec_decl.hpp
packages/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_mv_tpl_spec_decl.hpp
packages/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp

Fix ``Tpetra::CrsMatrix::apply`` performance regressions caused by https://github.com/kokkos/kokkos-kernels/pull/2126 and #12852. Calls cusparse spmv ALG2 for imbalanced matrices in CUDA versions <= 11.2.1.
KokkosKernels changes are the same as https://github.com/kokkos/kokkos-kernels/pull/2204 but this shouldn't wait for the next release.
apply is well tested for correctness.
For performance, here is a before/after for 1000-iteration CG run with an SierraTF abnormal energy problem, on Vortex. This matrix triggers the imbalanced row condition in Tpetra. The total solve time for develop branch was 3.48s, but with this PR is 1.73s.

Tpetra/KokkosKernels: fix apply/spmv performance regressions

---

packages/tpetra/core/test/Comm/gpuAwareMpi.cpp

No such thing as SYCLSpace :)
Fix build with SYCL backend enabled.  Improves compilation and testing on Sunspot/Aurora at ALCF for Office of Science FASTMath/OASYS project.

Tpetra: fix SYCL mem space name in test

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

@trilinos/ifpack2 @kliegeois 
This MR fixes a missed printf statement that wasn't wrapped in a `IFPACK2_BLOCKTRIDICONTAINER_USE_PRINTF` leading to unwanted printing to `stdout` in apps using the container.

ifpack2: add missing print guard in blocktridiagcontainer

---

packages/muelu/src/Transfers/BlockedTransfers/MueLu_SubBlockAFactory_def.hpp

Currently only Xpetra style maps are retrieved from the map extractor inside the subblock factory. If Thyra style maps are used, the GID numbering is wrong (e.g. not starting at 0 and wrong offset). 
* Related to #12665
Relevant for fully monolithic multigrid for multi-physics problems.
@mayrmt

Muelu: Add Thyra style submaps to subblock factory

---

packages/tpetra/core/src/Tpetra_Details_leftScaleLocalCrsMatrix.hpp
packages/tpetra/core/src/Tpetra_Details_rightScaleLocalCrsMatrix.hpp
packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp

Modest GPU performance improvements when using matrix equilibration.
There are tpetra unit tests for all of these kernels, TpetraCore_Equilibration_MPI_4 and TpetraCore_CrsMatrix_LeftRightScale_MPI_4.

Tpetra: Add team parallelism to a couple kernels associated with matrix equilibration

---

packages/ifpack2/src/Ifpack2_BlockComputeResidualVector.hpp
packages/ifpack2/src/Ifpack2_BlockHelper.hpp
packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp

This PR adds the option to use point crs matrices with BTDS without converting them to block ones explicitly.
This has been tried on Weaver and on Intel CPUs.

Ifpack2: add the option to use a point crs matrix with BTDS

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

When `num_teams == 0`, a floating point exception error is faced in `costSolveSchur`.

Ifpack2: Fix a floating point exception error when num_teams=0

---

packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp

In PerformanceCGSolve:
- Add untimed warmup apply (explained below)
- Add fences between kernels so that all time is attributed to the correct sub-timer
- Without a fence in between, time spent in the spmv kernel would spill over into the dot timer.
- Without a warmup apply, the very high cost of the initial rocSPARSE spmv means that the spmv time increased overall for the number of calls done by this test (76).
**In the long run rocSPARSE is 32% faster per call, but with the 1-rank CG matrix it will only break even after 228 apply calls.** It's impossible to know how many applies will be done ahead of time without the user telling us through the spmv handle. There are already options related to this:
- ``SPMV_FAST_SETUP`` calls native instead of rocsparse
- …

Tpetra: get accurate timing in CG perf test

---

packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/supported-envs.ini

Need to support all PR configurations on RHEL8 as machines transition.
I ran a build + test on one of the new RHEL8 machines, and two Pliris random vector tests fail.  Everything else passes.  Those same two tests fail with CUDA, ATS2, and our GCC + OpenMPI container, so I've disabled them here as well.

Framework: Add Clang RHEL8 configuration

---

packages/tpetra/core/src/Tpetra_Details_KokkosCounter.cpp
packages/tpetra/core/src/Tpetra_Details_KokkosCounter.hpp
packages/tpetra/core/test/CrsMatrix/CMakeLists.txt
packages/tpetra/core/test/CrsMatrix/CrsMatrix_ApplyUsesTPLs.cpp

This adds a unit test that ensures certain configurations of Tpetra's `CrsMatrix::apply` use vendor math libraries by default. The tested configurations are
* CUDA + CUSPARSE, LO=int, SCALAR=float/double
* HIP + ROCSPARSE, LO=int, SCALAR=float/double
We periodically introduce regressions in this area that we'd like to avoid.

Tpetra: check that CrsMatrix::apply uses TPLs when expected

---

.github/workflows/AT2.yml

As a Trilinos developer, I want to easily replicate AT2 builds.  This requires me to know what image was used for an AT2 run.  I want that information displayed in a way that is easy for me to find.

Framework: Display image used for AT2 run

---

packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py

If the track name contains "Pull Request", we want the build name formatted with the PR "style".  Now we can have multiple Pull Request groups (for example, a non-blocking one that allows us to preview new configurations)!
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-625

Framework: Use PR-format build name based on group

---

packages/teuchos/CMakeLists.txt
packages/teuchos/comm/test/Time/TimeMonitor_UnitTests.cpp
packages/teuchos/core/cmake/Teuchos_config.h.in
packages/teuchos/core/src/Teuchos_Time.cpp

If ``Teuchos_TIMER_KOKKOS_FENCE=ON``, then call ``Kokkos::fence()`` in Timer start() and stop() methods.
- This option is off by default as it could hurt performance, especially for an application using multiple concurrent exec space instances
- Turning it on requires Kokkos be enabled
Neither Teuchos timers nor Kokkos profiling regions fenced before, so non-blocking kernels might be launched while one timer is active but spend most of their actual execution time in another. #13048 fixed an example of this by adding fences directly: in PerformanceCGSolve, time spent in spmv kernels was showing up in the dot subtimer.
This option could be enabled in the Trilinos nightly performance builds so that we measure kernel times more accurately (at the expense of a slight …

Teuchos: add option to Kokkos::fence in timers

---

packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp

Now if fences around timers are desired, ``Teuchos_TIMER_KOKKOS_FENCE=ON`` can be turned on (nightly performance builds have this on now)
* Follows #13058 (option to fence on all Teuchos timers)
* Removes the fences that were added in #13048

Tpetra: remove fences from PerformanceCGSolve

---

packages/framework/pr_tools/LaunchDriver.py

We have our GPU systems marked as RHEL7 even though they are RHEL8 because we want to use the RHEL7 stack (until we have all of the new configurations working).  This prevents the newer machines from being recognized as RHEL8, and running configurations only for RHEL8.
As a solution, trust the user who specified the configuration to know what they are doing on a specific machine.  This follows what is already done with the GenConfig call (we use --force there).
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-646
I did not test this manually, but I did look at the signature for `DetermineSystem` and used the keyword argument specified by its docstring.

Framework: Force genconfig system for DetermineSystem

---

packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp
packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_decl.hpp
packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
packages/ifpack2/src/Ifpack2_RILUK_decl.hpp
packages/ifpack2/src/Ifpack2_RILUK_def.hpp
packages/ifpack2/test/belos/CMakeLists.txt

@trilinos/ifpack2 @jhux2 @vqd8a @brian-kelley 
Improved stream ILU performance for Sierra. Starting to look at some new problems on H100, these changes in total give a ~6x speedup in preconditioner compute for a particular problem using AdditiveSchwarz with overlap 1 and RILUK with fill level 1 and 20 streams.
#9720

Ifpack2 AdditiveSchwarz & RILUK performance improvements

---

packages/tpetra/core/test/CrsMatrix/CrsMatrix_ApplyUsesTPLs.cpp

For some versions of cusparse, KokkosKernels spmv_mv doesn't use cusparseSpMM because it gives incorrect results. For these versions, skip the check that a TPL was used in Tpetra. This only applies to cusparse and the multiple vectors case.
For reference, the versions of cuSPARSE that are never used are:
- CUSPARSE_VERSION < 10301
- CUSPARSE_VERSION == 11702
Just a change to a test. My workstation happens to have CUDA 11.6 with ``CUSPARSE_VERSION == 11702`` installed, so this test was failing for me but this PR skips the failing check.

Tpetra: skip test that spmv_mv used cusparse

---

packages/teuchos/CMakeLists.txt

Fix default for option to fence in Teuchos timers (copy-paste mistake)

Fix mistake in #13058: cmake option default

---

packages/kokkos-kernels/sparse/impl/KokkosSparse_spmv_impl.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_spmv_handle.hpp
packages/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv.hpp

Fix logic around merge path with TPLs
``SPMV_MERGE_PATH`` is not always a native algorithm, but it was incorrectly taking the native/fallback codepath. Add ``SPMV_NATIVE_MERGE_PATH`` to cover that case specifically. Test this new option in the spmv unit tests.
* Fixes issue reported directly from Aria, where the nan overwriting behavior was not happening because the cuSPARSE should have been taken, but the native merge path was running instead 
@vbrunini 
This PR adds testing for the new algorithm option ``SPMV_NATIVE_MERGE_PATH`` in KokkosKernels.
#13090 will add testing in Tpetra also.

KokkosKernels: patch in #2240

---

packages/tpetra/core/test/CrsMatrix/CrsMatrix_ApplyUsesTPLs.cpp

Kokkos Kernels 4.3.1 updated the profiling region labels for SpMV TPL usage.

tpetra: test: look for Kokkos Kernels 4.3.1 TPL region labels

---

packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory.cpp
packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory.hpp
packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory_impl.hpp

Drekar needs some panzer capabilities that are currently disabled when epetra is disabled. This will add back what they need.

Panzer: changes requested by Drekar for epetra removal

---

packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py

Some PR machines are marked RHEL7 by `supported-systems.ini` but we want to run RHEL8 configurations on those machines without yet changing the machine's system designation. 
Solution is to force the environment load step of LoadEnv in Trilinos' PR scripts to bypass the supported-systems check. This relies trust on the user configuring PR jobs to use the correct configuration, however, with non-blocking PR tests (which is what this is targeting), those configurations should already get tested before being put in place as a production configuration.
- [TRILFRAME-651](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-651)
- #13062 
- #13067 
Manually used LoadEnv to test that this is the correct way to inject the `--force` argument when creating a `LoadEnv` …

Framework: Force LoadEnv to use the system found in the build name

---

packages/panzer/dof-mgr/test/cartesian_topology/CMakeLists.txt
packages/panzer/dof-mgr/test/cartesian_topology/CartesianConnManager.cpp
packages/panzer/dof-mgr/test/cartesian_topology/CartesianConnManager.hpp
packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr.cpp
packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DG.cpp
packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DynRankView.cpp
packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_HighOrder.cpp
packages/panzer/dof-mgr/test/cartesian_topology/tCartesianTop.cpp

@rppawlo 
This PR makes minor updates to the `CartesianConnMgr` and `CartesianDOFMgr`:
- use of nested namespaces
- use of new functions such as `Teaches::make_rcp`
- re-enable tests `tCartesianTop` and `tCartesianDOFMgr` after updates such as eliminating use of `FieldContainer`
- replace `std::vector` storage with host view storage in `CartesianConnMgr`
- delete overlap between `tCartesianDOFMgr` and `tCartesianDOFMgr_DynRankView`
- use of `Brick` in various names in `tCartesianTop` 
This PR is preparatory work to prepare for using these tests for device `Conn` and `DOF` managers.

Panzer: Minor updates to `CartesianConn/DOFMgr`

---

packages/framework/ini-files/config-specs.ini

Want new Clang configuration usable.  This test was previously disabled, so carry that forwards.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-650

Framework: Finalize RHEL8 Clang build (disable failing test)

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp

In ``CrsMatrix::apply``, if beta==0 and y contains NaNs or Infs, these should be overwritten with the value alpha*A*x (not just multipled by 0, which would result in more NaNs in the final result).
Test this for both the normal and imbalanced row paths, with single and multiple columns.
Panzer MiniEM and other applications like Aria depend on this behavior but it wasn't sufficiently tested. See #13089 for more info
This is mostly a change to tests. The one change in code is to never use merge path unless the matrix's node is Cuda and cuSPARSE is enabled (before, the node==Cuda check was missing). This change is tested by the new tests.

Tpetra: test that CrsMatrix::apply overwrites NaNs

---

packages/tpetra/core/src/Tpetra_Details_makeColMap_def.hpp
packages/tpetra/core/src/Tpetra_Details_makeOptimizedColMap.hpp
packages/tpetra/core/src/Tpetra_Util.hpp

Following the merge of #13082, we observed performance regression in Tpetra nightly performance tests.
This PR enables the usage of a stable sort (slower and requires extra memory) only when constructing the column map, otherwise a (unstable) shell sort is used as before #13082.

Tpetra: Use a stable sort only for makeColMap and makeOptimizedColMap

---

packages/zoltan2/test/core/unit/input/XpetraMultiVectorInput.cpp

Replace the use of char* code with a std::string in the readChacoGraphHeaderInfo routine
This resolves compilation errors with cuda/12.4+gcc/13.2.0 with c++20:
```
/home/ndellin/Trilinos/packages/zoltan2/test/core/unit/input/XpetraMultiVectorInput.cpp(179): error: no operator ">>" matches these operands
operand types are: std::basic_istream<char, std::char_traits<char>> >> char *
issHeader >> nIDs >> nEdges >> code;
```
The `char* code` variable is not used outside of the `readChacoGraphHeaderInfo` routine, so it was removed from the function signature and the corresponding input variables were removed as well, replaced by use of `std::string s_code` variable within the routine to receive the istringstream input and for comparison (via c_str())
@trilinos/zoltan2 @egboman 
Change made to …

zoltan2: replace use of char* code with std::string with istringstream

---

packages/PyTrilinos/doc/UsersGuide/biblio.bib
packages/ifpack/doc/UsersGuide/biblio.bib

These bib files had non-UTF-8 encoded characters (e.g., umlaut). Placed them with the latex equivalent.
@trilinos/ifpack 

ifpack: Fix-Non-UTF-8-Encoded-Characters

---

CMakeLists.txt
packages/framework/ini-files/config-specs.ini

I noticed that our no-epetra builds were warning about building Triutils even though it was deprecated.  Use the list of deprecated packages in `CMakeLists.txt` to disable those packages, instead of duplicating that information in `config-specs.ini`.
I ran the following configures:
`cmake -DTrilinos_ENABLE_ALL_PACKAGES=ON -DTrilinos_DISABLE_DEPRECATED_PACKAGES=ON ..` -- all packages that are not deprecated were enabled.
`cmake -DTrilinos_ENABLE_ALL_PACKAGES=ON -DTrilinos_DISABLE_DEPRECATED_PACKAGES=ON -DTrilinos_ENABLE_Epetra ..` -- all packages that are not deprecated were enabled, and I got configure-time warnings that I had attempted to enable a deprecated package despite turning them off.

Framework: Unify deprecated packages list

---

packages/tempus/test/BackwardEuler/Tempus_Test_BackwardEuler_OptInterface.cpp

Building Tempus tests fails with 
```
<snip>/tempus/test/BackwardEuler/Tempus_Test_BackwardEuler_OptInterface.cpp:148:5:
error: no matching function for call to 'V_VmV'
Thyra::V_VmV(dfdx_mv.ptr(), *dfdx_mv, *dfdx_mv2);
^~~~~~~~~~~~
<snip>/thyra/core/src/support/operator_vector/client_support/Thyra_VectorStdOps_decl.hpp:459:6:
note: candidate template ignored: could not m
atch 'VectorBase' against 'MultiVectorBase'
void V_VmV( const Ptr<VectorBase<Scalar> > &z, const VectorBase<Scalar>& x,
^
<snip>/tempus/test/BackwardEuler/Tempus_Test_BackwardEuler_OptInterface.cpp:149:12:
error: no member named 'norms' in namespace 'Thyra'
Thyra::norms(*dfdx_mv, Teuchos::arrayViewFromVector(nrms));
~~~~~~~^
<snip>/tempus/test/BackwardEuler/Tempus_Test_BackwardEuler_OptInterface.cpp:162:5 …
```

Tempus: fix missing include in backward euler test

---

CMakeLists.txt
packages/framework/ini-files/config-specs.ini

Want an updated deprecated packages list.
Reverting to previous methodology for deprecated package disablement because the new approach from #11310 does not work with how we pass around files.  The configuration options end up in a file that is included via `Trilinos_CONFIGURE_OPTIONS_FILE` which is not included until we enter TriBITS, so I can't use the values in the root-level CMakeLists.txt.

Framework: Deprecated packages

---

packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/supported-envs.ini

Need this environment for running the Framework unit tests.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-653
https://cee-gitlab.sandia.gov/trilinos-project/srn-ini-files/-/merge_requests/76
I ran the config + tests, and the only one that failed was because I don't have pytest-cov installed.  The scripts should take care of that for us, so this should be good to go (odds are, at least).

Framework: Add RHEL8 Anaconda3 configuration

---

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp

This pull request fixes the hanging Tpetra tests @ndellingwood was observing in https://github.com/kokkos/kokkos/issues/7092 after https://github.com/kokkos/kokkos/pull/7080. `Tpetra` calls in multiple places non-KOKKOS_FUNCTION functions from parallel constructs. Some of them allocate and deallocate data or call `Kokkos::fence`. This leads to hangs even with the `Serial` backend that now ensures that kernels submitted to the same execution space instance from multiple threads are not running concurrently.
This pull request either makes sure that data is not allocated via a `View` (which fences when deallocating) or replaces parallel constructs with serial for-loops.
* Closes https://github.com/kokkos/kokkos/issues/7092
Running the respective Tpetra tests with the …

Tpetra: Fix hanging tests after Serial thread-safety fixes 

---

packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py

I turned up the build/test console verbosity without really thinking about what this meant for our Jenkins console output storage.  Long story short, we're running out of space. Automatically detect whether we're using Jenkins or not to dynamically adjust the verbosity.

Framework: Drop verbosity level under Jenkins

---

packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp

Now have to manually delete the inner views of a host-host mirror of a view-of-views. See Kokkos issue 7092 for details: https://github.com/kokkos/kokkos/issues/7092 
covered in view of view tests.

Phalanx: Fix for kokkos serial changes

---

packages/ifpack2/example/BlockTriDi.cpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

@tmranse observed a memory error with the BTDS with Schur complement on a specific case.
This PR fixes the issue and adds an option for the Ifpack2 driver to use only one file for all MPI ranks.

Ifpack2: fix a bad memory access on V100

---

packages/muelu/src/Graph/MatrixTransformation/MueLu_AmalgamationFactory_decl.hpp
packages/muelu/src/Graph/MatrixTransformation/MueLu_AmalgamationFactory_def.hpp
packages/muelu/test/unit_tests/AmalgamationFactory.cpp

There are some edge cases, were the offset for a strided map is not set correctly or at all, when using block matrix conversions from `Xpetra` to `Thyra` and vice-versa. Thus this MR proposes to calculate the offset from scratch similar to the `Xpetra::StridedMap` constructor with user-defined non-contiguous (arbitrary) distribution (Definition at line [269](https://docs.trilinos.org/dev/packages/xpetra/doc/html/Xpetra__StridedMap__def_8hpp_source.html#l00269) of file [Xpetra_StridedMap_def.hpp](https://docs.trilinos.org/dev/packages/xpetra/doc/html/Xpetra__StridedMap__def_8hpp_source.html)). 
* Closes #12665
* Related to #13023 
Relevant for block preconditioning with `Teko` for multi-physics problems and using `MueLu` to approximate the single field inverses.
@mayrmt

MueLu: Adapt offset calculation in amalgamation

---

packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Tpetra_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_Tpetra_decl.hpp
packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp
packages/panzer/dof-mgr/src/Panzer_DOFManager.hpp
packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
packages/phalanx/src/design/Phalanx_KokkosViewOfViews.hpp
packages/phalanx/src/design/README.txt
packages/phalanx/src/design/tPhalanxViewOfViews.cpp
packages/phalanx/test/Kokkos/tKokkosClassOnDevice.cpp
packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp

Changes to the kokkos serial backend in https://github.com/kokkos/kokkos/pull/7080 was causing deadlock in the destructor of  a host-host view-of-views as reported in https://github.com/kokkos/kokkos/issues/7092. A short term fix that required users to call a function to free the inner host-host view was added in  https://github.com/trilinos/Trilinos/pull/13188. This commit cleans up the v-of-v and provides a long term fix so that users don't have to call the free function. Also did some cleanup on the naming and removed some older alternate experimental versions of v-of-v.
Fixed.
All the v-of-v tests.

Phalanx/Panzer: long term fix to view-of-views for kokkos serial backend changes

---

packages/tpetra/core/example/advanced/Benchmarks/import.cpp
packages/tpetra/core/example/advanced/Benchmarks/vector.cpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_Util.hpp
packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp

- comparing signed vs. unsigned
- template specialization written incorrectly
- Comm pointer null in benchmarks when Epetra not enabled
- calling std::vector methods in device code
* Supersedes the Tpetra changes in #13192
* Part of #13107 
Albany wants to build Trilinos warning-free. Only the sign-compare warning actually affected that build, the others were things that showed up in my own local build with a newer GCC.

Tpetra: fix warnings

---

packages/belos/src/BelosStatusTestGenResSubNorm.hpp

@hkthorn
This PR fixes a missing $ in a latex docstring.
Found and tested by compiling the `Belos` `doxygen` doc using "warn as error".

Belos: Fix missing $ in latex docstring

---

packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/supported-envs.ini

Had some issues with the OpenMPI 4.1.4 stack disappearing.  4.1.6 is the preferable version anyway, so update to use that.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-652
I built and ran the full tests on my blade, and everything passed.

Framework: Update config for RHEL8 Intel PR

---

packages/teuchos/core/src/Teuchos_Exceptions.hpp
packages/teuchos/core/src/Teuchos_any.hpp
packages/teuchos/parameterlist/src/Teuchos_ParameterEntry.hpp
packages/teuchos/parameterlist/test/ParameterList/ParameterList_UnitTests.cpp

@trilinos/teuchos @bartlettroscoe
<del>As discussed in #13204, here is a simple example in a unit test that won't compile due to the `static_assert` for an `enum class` in the ParameterEntryValidator. <del>
<del>I have added a separate `static_assert` for checking printability and comparability to split the check during debugging.<del>
As highlighted in #13204 there are use cases for non-printable parameter list entries. This PR enables them by removing the compile time `static_assert()` and now throws a more meaningful runtime error message when trying to print a `ParameterList` with non-printable entries. Appropriate unit tests have been added for `std::vector<int>` and `enum class`. 
#13204

Teuchos: Enable non-printable parameter list entries

---

packages/teko/src/Teko_HierarchicalGaussSeidelPreconditionerFactory.cpp
packages/teko/src/Teko_HierarchicalGaussSeidelPreconditionerFactory.hpp
packages/teko/tests/src/tSIMPLEPreconditionerFactory_tpetra.cpp

Motivation: it's really awkward to need to specify a full block Jacobi or block Gauss-Seidel solver in the context of the hierarchical block Gauss-Seidel solver. This PR automatically 'un-boxes' the block matrix to the single sub-block, allowing a user to directly use MueLu, Ifpack2, Belos, or Amesos2 to solve the sub-block.

Teko: Auto 'un-box' single sub-block hierarchical blocks

---

packages/belos/src/BelosCGSingleRedIter.hpp

The single reduce CG uses two MVs to hold its vector data. Different operations act on single vectors or sub-MVs. In particular, there is a call to `MvTransMv` for MVs $S=[W_0, W_1]$ and $T=[W_0,W_2]$ where $W$ is a MV with 3 columns. This call was slow on GPUs because it ran on a MV with non-constant stride. By reordering $W$ we now have $S=[W_0, W_1]$ and $T=[W_1,W_2]$ instead.

Belos CGSingleRedIter: Reorder memory so that MvTransMv arguments have constant stride

---

packages/xpetra/src/CMakeLists.txt

@cgcgcg @mayrmt 
PR https://github.com/trilinos/Trilinos/pull/13191 breaks our in-house solver build with the following error:
```shell
/usr/bin/ld: ../../../src/libmuelu.a(ETI_MueLu_SaPFactory.cpp.o): in function `Xpetra::IteratorOps<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::Jacobi(double, Xpetra::Vector<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Xpetra::Matrix<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Xpetra::Matrix<double, int, int, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> > const&, Teuchos::RCP<Xpetra::Matrix<double, int, int, …
```

Xpetra: Add IteratorOps to CMake

---

packages/muelu/src/Operators/MueLu_MultiPhys_decl.hpp
packages/muelu/src/Operators/MueLu_MultiPhys_def.hpp

Break builds if they were still configured with removed variable `MueLu_ENABLE_KOKKOS_REFACTOR`

MueLu MultiPhys: Fix includes

---

packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp

Phalanx vov unit test was failing for cuda uvm. Needed to swap the space accessibility arguments.
Fixes broken UVM tests in vov

Phalanx: fix vov for CUDA UVM

---

packages/PyTrilinos2/LICENSE
packages/TrilinosInstallTests/LICENSE
packages/adelus/LICENSE
packages/amesos2/LICENSE
packages/amesos2/src/KLU2/LICENSE
packages/amesos2/src/basker/LICENSE
packages/anasazi/LICENSE
packages/belos/LICENSE
packages/galeri/LICENSE
packages/ifpack2/LICENSE
packages/intrepid2/LICENSE
packages/minitensor/LICENSE
packages/muelu/LICENSE
packages/pamgen/LICENSE
packages/panzer/LICENSE
packages/phalanx/LICENSE
packages/tempus/LICENSE

Add missing License Identifier to LICENSE files.  This is just a one-line addition to multiple packages.

Add-License-Identifier

---

packages/muelu/src/Graph/Containers/MueLu_LWGraphBase.hpp
packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_decl.hpp
packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_def.hpp
packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp
packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_decl.hpp
packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp
packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp
packages/muelu/test/unit_tests_kokkos/CoalesceDropFactory_kokkos.cpp
packages/muelu/test/unit_tests_kokkos/MueLu_TestHelpers_kokkos.hpp

Changes in preparation for refactoring of `CoalesceDropFactory_kokkos` and then merge with `CoalesceDropFactory`.
- bugfix: `CoalesceDropFactory_kokkos` did not detect boundary conditions for scalar equations with `dropTol > 0`.
- Kokkosify `GetMatrixMaxMinusOffDiagonal`.
- Add a method to `LWGraph_kokkos` to copy it to host.
- Prepare `NotayAggregationFactory` for using `LWGraph_kokkos`.
- Add a new unit test for `CoalesceDropFactory_kokkos`.

MueLu: Prep for CoalesceDrop refactor

---

packages/ifpack2/src/Ifpack2_ILUT_decl.hpp
packages/ifpack2/src/Ifpack2_ILUT_def.hpp

L_rowmap and U_rowmap are in/out parameters to par_ilut_numeric and therefore can be changed by that call. If they do change, they will no longer accurately reflect the original A. This PR ensures that L_rowmap and U_rowmap will be restored to original symbolic values in case ILUT::compute is called again.
Aria was trying to use ILUT and having problems due to multiple compute calls.
I will have Aria devs test this.

Ifpack2: Fix repeat calls to ILUT::compute

---

packages/tempus/src/Tempus_SolutionHistory_impl.hpp
packages/tempus/unit_test/Tempus_UnitTest_SolutionHistory.cpp

When a timestep fails, the failing workingState solution was reused as it might be a good guess for the nonlinear solver and could help with performance.
However if the failing workingState failed with NaNs, it was never reset and the workingState would continue to have NaNs after failure. The new behavior is to reset the workingState to the last time step, currentState.  This will be more robust in this case.
Stakeholder had the situation where the timestep failed with NaNs.  Although the timestep was halved, the solution had NaNs which continued to the next solution, causing another failure.  Thus the timestep crashed until the problem stopped.
@rppawlo tested this and found it resolved the issue.
Added to a unit test to cover this situation.

Tempus: Change Recovery State

---

packages/ifpack2/src/Ifpack2_ILUT_def.hpp

This is a follow-on to #13309. There was a minor problem with that PR because it did not take into account that the size of L and U rowmap might have changed, which could lead to a failure to deep_copy. This PR adds a resize so that it won't fail.
We confirmed 13309 fixes some tests but others were still broken with deep_copy failures. This PR will fix that.
Related to #13309

ILUT: Must resize before copy

---

packages/panzer/adapters-stk/example/PoissonExample/compareWithGold_Curvilinear.py
packages/panzer/adapters-stk/example/PoissonExample/main.cpp

PoissonExample test was failing with gcc 12. Area calculation needed a minor change.
adapters-stk/examples/PoissonExample

Panzer: fix PoissonExample area calc for gcc 12

---

packages/framework/ini-files/config-specs.ini

Begin enabling as much warnings-as-errors as possible back into Trilinos, beginning with `-Werror=sign-compare -Werror=unused-variable -Werror=parentheses`.
With the introduction of deprecated package header warnings in #12828, `-Werror` had to be turned off from several PR testing configurations (gcc-serial, gcc-openmpi, & gcc-openmpi-openmp). Since then, we cannot be confident that Trilinos can compile with minimal warnings related to all currently supported packages. See Related Issues section for more context on how this began.
Enabling these warnings in this PR is likely to cause several build errors across several packages that need to be fixed individually by the packages' maintainers. To give time for package developers to resolve the new warnings-as-errors …

Framework: Enable additional warnings-as-errors in Trilinos

---

packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Base.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_SupernodeInfo.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_ExtractCRS.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeChol.hpp

This PR replaces the views used to store CRS with subviews.
Tested on V100 and Mi250.
Tacho uses a view of structures (one structure per level). Previously, we used views in the structure to store CRS, which could have lead to memory leak.

Tacho : memory-management for SpMV option

---

packages/amesos2/test/solvers/Solver_Test.cpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp

Fix `-Werror=unused-variable` breaking PR_gcc-openmpi-openmp builds, crept in with #13318 and encountered in PRs #13334 and https://github.com/trilinos/Trilinos/pull/13332
```
https://github.com/trilinos/Trilinos//blob/d8badb3e29a5693d5ec638d02da83d32d261cee8/workspace/PR_gcc-openmpi-openmp/Trilinos/packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp#L2059 :17: error: unused variable 's0' [-Werror=unused-variable]
auto &s0 = _h_supernodes(_h_level_sids(pbeg));
```
The compilation errors likely contributed to `TrilinosInstallTests_doInstall` test failures in the `rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables` jobs with output: …

tacho: fix unused variable triggering -Werror

---

packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp

On Stria, https://github.com/trilinos/Trilinos/pull/13052 caused a ~20% performance regression in the CGSolve performance test that is fixed by forcing
`getLocalMatrixDevice` to always be inlined. Restrict the fix to the specific toolchain where the problem was observed.
This was probably caused by a refactor of the `MatrixApplyHelper` struct that changed the compiler's inlining decision for `getLocalMatrixDevice`.

Tpetra: Force CrsMatrix::getLocalMatrixDevice to be inlined on ARM.

---

packages/framework/get_dependencies.sh

Seeing a number of AT issues where we fail to check out configs from our internal GitLab.
Tried this out manually with a known-bad git that always returns failure, and the output (and xtrace) seemed to behave as expected.

Framework: Retry git operations for AutoTester

---

packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

Add use a LIDs option to use LID for the explicit `convertToBlockCrsMatrix ` and a `are_same` to skip the serial loop `loop_over_local_elements`.

Ifpack2: add use a LIDs option and a `are_same` to skip serial 

---

packages/ifpack2/src/Ifpack2_BlockComputeResidualVector.hpp
packages/ifpack2/src/Ifpack2_BlockHelper.hpp
packages/ifpack2/src/Ifpack2_BlockHelper_Timers.hpp
packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp

As discussed in #12358, when using nested `TEUCHOS_FUNC_TIME_MONITOR` we have a variable shadowing.
This PR fixes that by using `TEUCHOS_FUNC_TIME_MONITOR_DIFF` instead.
Issue #12358 can be closed once this PR is merged.

Tpetra and Ifpack2: Use `TEUCHOS_FUNC_TIME_MONITOR_DIFF` instead of `TEUCHOS_FUNC_TIME_MONITOR`

---

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Quad8ToQuad4MeshFactory.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_QuadraticToLinearMeshFactory.cpp
packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp
packages/panzer/disc-fe/src/Panzer_TpetraVector_ReadOnly_GlobalEvaluationData_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp
packages/panzer/mini-em/src/solvers/MiniEM_FullDarcyPreconditionerFactory.cpp
packages/piro/src/Piro_ThyraProductME_Constraint_SimOpt.hpp
packages/stratimikos/src/Stratimikos_LinearSolverBuilder_def.hpp

@trilinos/stratimikos @trilinos/panzer 
Silence some warnings (Shadowed variables, unused typedefs).

Stratimikos, Piro, Panzer: Silence warnings

---

packages/ifpack2/example/CMakeLists.txt
packages/tpetra/core/test/PerformanceCGSolve/CMakeLists.txt

This PR modifies the Performance CG test of Tpetra to use a loop over number of ranks.
This PR adds 4 new performance tests for the BTDS that use Galeri generated matrices.

Ifpack2 (and Tpetra): use while loop for Ctest perf tests

---

packages/kokkos-kernels/cmake/kokkoskernels_eti_offsets.cmake

Revert the change in 4.4.0 release (https://github.com/kokkos/kokkos-kernels/pull/2140) that made int the default offset type instead of size_t. This is because Tpetra still uses size_t for CrsGraph and CrsMatrix local data structures.
This change is only about speeding up compilation time; instantiating for offset=size_t means that Tpetra can actually use the functions compiled into the KokkosKernels library. Tpetra's special codepaths in ``CrsMatrix::apply``, ``BsrMatrix::apply`` and ``MatrixMatrix::multiply`` using offset=int will still work.
Speed up compilation times. Right now, we are instantiating KokkosKernels for types that the Tpetra stack doesn't use (except for the few exceptions above). For the types that Tpetra does use, we are instantiating the …

KokkosKernels: restore size_t as default offset

---

packages/ifpack2/example/CMakeLists.txt

After first results of PR #13375 in the nightly perf tests, I observed that the number of ranks were not displayed correctly.
This PR fixes it and adds mesh sizes to the test name, this would allow to add other mesh sizes later without losing the history.
I verified that the generated files are as expected now.

Ifpack2: Add the number of ranks in the problemName

---

packages/seacas/libraries/ioss/src/Ioss_Field.h
packages/seacas/libraries/ioss/src/Ioss_Region.h
packages/seacas/libraries/ioss/src/Ioss_StructuredBlock.h
packages/seacas/libraries/ioss/src/Ioss_Utils.C
packages/seacas/libraries/ioss/src/Ioss_ZoneConnectivity.h
packages/seacas/libraries/ioss/src/main/io_info.C

The latest snapshot added the use of lib::fmt includes in externally accessible include files.  Since fmt is not a published TPL dependency, any client using those include files will fial.
* Closes #11487

Seacas fix fmt use in external include

---

packages/percept/src/percept/mesh/mod/smoother/GenericAlgorithm_total_element_metric.hpp

@trilinos/percept
Adding host/device attributes to Percept calls to enable compilation with ROCm.
@rppawlo I'm not sure who manages Percept, but this triggered our CI system. Actually, I'm curious, does this issue also trigger CUDA?

Percept: Adding host/device attributes to function in header

---

packages/sacado/src/Kokkos_LayoutContiguous.hpp

Fixes https://github.com/kokkos/kokkos/issues/7258. `Sacado` defines `ContiguousLayout` in the `Kokkos` namespace, see
[trilinos/Trilinos@2ad2602/packages/sacado/src/Kokkos_LayoutContiguous.hpp#L30-L74](https://github.com/trilinos/Trilinos/blob/2ad26029e5e3592de143b1640480382a296c401a/packages/sacado/src/Kokkos_LayoutContiguous.hpp#L30-L74)
and specializes `std::is_same` for this class, see [trilinos/Trilinos@2ad2602/packages/sacado/src/Kokkos_LayoutContiguous.hpp#L76-L87](https://github.com/trilinos/Trilinos/blob/2ad26029e5e3592de143b1640480382a296c401a/packages/sacado/src/Kokkos_LayoutContiguous.hpp#L76-L87). 
Both of these aren't legal usage of `Kokkos` or the `std` namespace.
Thus, changing all `std::is_same<>::value` to `std::is_same_v`led to a bunch of problems …

Sacado: Band-aid fix for LayoutContiguous

---

packages/kokkos-kernels/sparse/src/KokkosSparse_spadd_handle.hpp

SpAdd handle: delete sort_option getter/setter. Patch of https://github.com/kokkos/kokkos-kernels/pull/2296
SpAdd handle was originally a copy-paste of the spgemm handle way back in #122, and included get_sort_option() and set_sort_option() from spgemm. But these try to use the member bool sort_option, which doesn't exist. Somehow these functions never produced compile errors until someone tried to call them.
Fixes build errors on Sunspot (and probably Aurora as well) on some newer oneapi toolchains.
Fixes a reference to a member variable that doesn't exist. On most compilers, the functions with the problem don't get compiled at all until they're called. But on some recent Intel oneapi compilers, this causes a build error.
Reported by @jczhang07 for PETSc (he was …

KokkosKernels: patch #2296

---

packages/sacado/src/Kokkos_LayoutContiguous.hpp

For intel icpc compilers use inline constexpr rather than static constexpr for is_same_v specialization introduced in #13392 This is to workaround intel ICE issues that should not be related to the change but occur when building Trilinos with or without Kokkos' develop branch
Error output sample:
```
/home/ndellin/trilinos/Trilinos/packages/sacado/test/UnitTests/ConditionalReturnTypeTest.cpp(48): internal error: assertion failed at: "il.c", line 10434 in trans_unit_for_source_corresp
```
@trilinos/sacado @etphipp 
Resolve compilation issues with intel icpc
Tested that this resolves compiler errors with Trilinos (no kokkos update) and Trilinos with kokkos@develop

sacado: workaround icpc ice with is_same_v

---

packages/kokkos-kernels/common/src/KokkosKernels_SimpleUtils.hpp
packages/kokkos-kernels/common/src/KokkosKernels_Utils.hpp
packages/kokkos-kernels/perf_test/sparse/CMakeLists.txt
packages/kokkos-kernels/perf_test/sparse/KokkosSparse_sort_crs.cpp
packages/kokkos-kernels/sparse/impl/KokkosSparse_sort_crs_impl.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_SortCrs.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_Utils.hpp

The changes exactly match this KokkosKernels PR (its description has some performance measurements): kokkos/kokkos-kernels/pull/2293. The highlight is that for Sierra TF's abnormal_energy matrix, this improves performance of sort_crs_matrix by 6.3x on V100.
sort_crs_matrix being very slow for irregular matrices was directly reported by @vbrunini for Sierra TF. But this will give an uplift for other applications running on GPUs with either very regular, or very irregular matrices (see the KK PR for details).
All sort_crs_ functions are tested in KokkosKernels sparse unit tests.

KokkosKernels: improve CRS sorting performance

---

packages/piro/src/Piro_PerformAnalysis.cpp
packages/piro/src/Piro_TempusIntegrator.hpp
packages/piro/src/Piro_TempusIntegrator_Def.hpp
packages/piro/src/Piro_TempusSolver.hpp
packages/piro/src/Piro_TempusSolver_Def.hpp
packages/piro/src/Piro_ThyraProductME_Tempus_FinalObjective.hpp
packages/piro/test/Main_AnalysisDriver_Tempus.cpp
packages/piro/test/_input_Analysis_ROL_ReducedSpace_Transient.xml
packages/piro/test/_input_Analysis_ROL_ReducedSpace_Transient_2_parameters.xml
packages/piro/test/_input_Analysis_ROL_ReducedSpace_Transient_Integrated_Response_MSD.xml
packages/piro/test/_input_Analysis_ROL_ReducedSpace_Transient_MSD.xml
packages/piro/test/_input_Analysis_ROL_Tempus_Transient_MSD.xml

Previously `ThyraProductME_TempusFinalObjective` did not override virtual member functions of `ROL::Objective`.
This PR changes that and fixes the evaluation of the objective function and gradient for `ThyraProductME_TempusFinalObjective`.
The PR adds as well couple of improvements to perfanalysis for transient problems to check gradients either after or before the optimization.
For the Tempus driven problem, I checked the accuracy of the gradient before optimization using the ROL `checkGradient` function which looked good.

Piro: update perfanalysis for transient analysis and modify `ThyraProductME_TempusFinalObjective` to override member functions

---

packages/intrepid2/src/Cell/Intrepid2_CellDataDef.hpp

Fix changes in #13394 that introduced an issue with deducing the type when using float instead of double as `ScalarType`.

Intrepid2: Explicitly cast pt0 + pt1 - 1 term in intrepid2 to ScalarType

---

.github/workflows/AT2.yml
packages/framework/ini-files/config-specs.ini
packages/framework/pr_tools/PullRequestLinuxDriver.sh
packages/framework/pr_tools/PullRequestLinuxDriverTest.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py

The 'Update' column on CDash is red when we make a local change to a source file.  This could be confusing to end users.  It appears that we do not need to make that modification when running through the PR scripts, because they pass the `--force` option to GenConfig (end users WILL have to do that, but that's expected).  So remove that sed command, cleaning the dashboard.
I also started cleaning up the options to the PR scripts, since a lot of stuff is marked required but not REALLY needed.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-665
I tested the changes in a container and the update column reported successfully.  I also tested the later changes (CLI cleanup) and they worked too.

Framework: Fix AT2 update column

---

.github/workflows/AT2.yml

Current behavior of GitHub Actions with the AutoTester2 workflow is that there is a case where duplicate run will happen when the workflow is triggered by different events. Below are the following GitHub Actions cases that need to be accounted for:
Use case 1:
- Sandian 1 submits PR or pushes commit to PR (`pull_request` event)
- AT2 workflow runs and passes
- Sandian 2 submits a review approval triggering the workflow (`pull_request_review` event)
- AT2 workflow runs again with no changes made to the code, using extra resources
(Desired result is to not run and respect the first result)
Use case 2:
- Non-sandian submits PR (`pull_request` event)
- AT2 workflow runs, but fails due to workflow being triggered by non-sandian
- Sandian approves PR triggering the workflow …

Framework: Fix duplicate AutoTester2 runs with a dependent pre-check job

---

packages/amesos2/src/Amesos2_Umfpack_FunctionMap.hpp
packages/amesos2/src/Amesos2_Umfpack_TypeMap.hpp
packages/minitensor/src/MiniTensor_Geometry.h
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Base.hpp

Fix some HIP build errors when enabling Kokkos_ENABLE_IMPL_HIP_UNIFIED_MEMORY=ON

Fix some build errors with HIP unified memory

---

packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp
packages/teuchos/parameterlist/test/ParameterList/ParameterList_UnitTests.cpp

This PR is a minor change to how a parameter's value is passed to `ParameterList::set`.
Currently, the parameter value is passed by const ref. This PR changes this to passing by universal ref.
The intent of this change is to allow move semantics along the chain of calls that is made when setting a parameter.
This change is consistent with a similar change made to `ParameterEntry`'s constructor a while ago in:
- https://github.com/trilinos/Trilinos/commit/68a1cd7e39c247553a7e111dcd2507fa4270f51d

Teuchos: pass `value_in` to `tpl::set` by universal ref

---

packages/piro/src/Piro_PerformAnalysis.cpp
packages/piro/src/Piro_ThyraProductME_Tempus_FinalObjective.hpp
packages/piro/test/Main_AnalysisDriver_Tempus.cpp

This PR fixes the FinalObjective which makes the Piro Tempus driven test pass the checkGradient after the optimization (it passed before the optimization before but not after).
The PR makes the associated test more strict in term of the value check.
The PR fixes the Tempus redirection as well. Before the file was created but was empty.

Piro: update FinalObjective and fix the tempus redirection

---

packages/phalanx/src/Phalanx_TemplateIterator.hpp
packages/phalanx/test/TemplateManager/TemplateManagerTest.cpp

Needed to compile phalanx with gcc 15.
New test added to template manager unit test to trigger a failure with older gcc compilers

Phalanx: fix for gcc 15

---

packages/seacas/libraries/ioss/src/Ioss_Region.C

Remove shadow variable added during topology modification merge.
* Closes #13429

IOSS: Fix shadow variable in region

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp

Sorts the inputs to KokkosSparse::spgemm when Kokkos Kernels is going to use the cuSparse TPL.
Kokkos Kernels doesn't really provide a good way to access this information, nor for Tpetra to provide whether or not the matrix is sorted.
Fix for https://github.com/trilinos/Trilinos/issues/13339
Related Kokkos Kernels issue https://github.com/kokkos/kokkos-kernels/issues/2194
See unmerged https://github.com/trilinos/Trilinos/pull/11709, where it was proposed for Tpetra to always sort a matrix before giving it to Kokkos Kernels.

Tpetra MatrixMatrix: sort for cuSparse

---

packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp
packages/teuchos/parameterlist/test/ParameterList/ParameterList_UnitTests.cpp

@rppawlo
@MalachiTimothyPhillips
This PR is a fix that follows: 
- https://github.com/trilinos/Trilinos/pull/13409
In that PR, the templated set method of `Teuchos::ParameterList` was replaced with a version that passes the parameter value by universal reference, along with a fallback to cover legacy use cases in which the parameter type is hardcoded at the call site, and hence not deduced.
However, after merging that PR, compilation errors arose in user code in use cases in which the parameter value is set via a user defined conversion function.
Thus, this PR adds a test to cover such use cases. And it proposes a fix to the fallback method.

Teuchos: fix templated set method of `ParameterList`

---

packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp

@etphipp 
@pzehner 
This PR refactors the `Stokhos` specialisation of `Kokkos::create_mirror` for `View` of `MP::Vector`. This refactoring is motivated by recent changes in `Kokkos` in:
- https://github.com/kokkos/kokkos/pull/7061
In that `Kokkos` PR, additional constraints were imposed in the public interface of `Kokkos::create_mirror` and `Kokkos::create_mirror_view`. In particular, the version of `Kokkos::create_mirror_view` that takes a `Kokkos::Impl::ViewCtorProp` now no longer works with views with a non-void `specialize` trait.
This PR thus adds to Stokhos a specialisation of `Kokkos::create_mirror` that takes a `Kokkos::Impl::ViewCtorProp`. Then, all other overloads are refactor to map to that version. And, in the end, a specialisation of …

Stokhos: refactor `create_mirror` specialisation for `View` of `MP::Vector`

---

packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp

@csiefer2 reported hip compiler error for MI300 with unified memory. 
Kokkos 4.4 includes support for hip unified memory space. Needed to add a workaround for interoperability of unified memory host mirror views used in intrepid_host_basis->getValues() calls.

Panzer: fix basis values for hip unified memory

---

packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp

@etphipp
This PR modifies the `Stokhos` specialisation of the `deep_copy` overload that takes an execution space instance and copies between two views. 
The `Stokhos` specialisation works by calling the `Kokkos` implementation with views of `FlatArrayType` type. However, currently, the `Stokhos` specialisation discards the passed execution space instance. Instead, it passes a default execution space instance to the `Kokkos` implementation. Thus, the deep copy operation is ultimately not enqueued in the right stream.  
The change made in this PR is thus to let the `Stokhos` specialisation pass the received execution space instance to the `Kokkos` implementation.
(Just for context, our code calls `create_mirror_view` at some point using view constructor …

Stokhos: use exec instance in `deep_copy` of `View` of `MP::Vector`

---

.github/workflows/AT2.yml
cmake/SimpleTesting/cmake/ctest-cdash-setup.cmake
cmake/SimpleTesting/cmake/ctest-functions.cmake
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py

https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-664
As a Trilinos developer, I want the information from the AT2 system to be as clear as possible, and use a database-based reporting system (CDash).
Hyperlink needs to be “easy to find/use”. Subjective, but I suggest it being at the very last step of the action as a “here is stuff you may find useful about this actions run”
- Image name
- CDash link (perhaps modify PullRequest… to print the link to a file, then cat it here?)
- Link to ”working with containers” wiki articles?
- Link to “working with containers at Sandia (e.g. proxy variables)” wiki article?
- ”Global” Cdash link – link with filter that shows ALL builds for this PR via “Build name contains PR-XXXXX” or something like that
* Closes …

Framework: Enhance CDash reporting

---

packages/stokhos/CMakeLists.txt
packages/stokhos/cmake/Stokhos_config.h.in
packages/stokhos/src/sacado/kokkos/pce/Stokhos_Sacado_Kokkos_UQ_PCE.hpp

Adds Stokhos_ENABLE_DEPRECATED_CODE option (default is ON), and the PCE scalar type can only be enabled if Stokhos_ENABLE_DEPRECATED_CODE=ON. If off, and the PCE scalar type is enabled, cmake errors out.  Also prints a cmake warning if deprecated code is on and the PCE scalar type is on, and copius compiler warnings.

Stokhos:  Deprecate the PCE scalar type

---

packages/seacas/applications/cpup/cpup.C

This fixes a build issue in current Trilinos related to lib::fmt use.
There is a different fix in current SEACAS, but this will address the current problem in SPARC until I can do a larger snapshot commit.
@vbrunini 
The lib::fmt formatter output requires a formatter which is present, but there is no include for ZoneGridConnectivity and BoundaryCondition classes in this file, so they are an incomplete type.  There is a better fix in standalone SEACAS which will be snapshotted in soon, but this fixes the immediate problem with a minimally intrusive chagne.

Fix incomplete type in fmt formatter

---

packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp

Issue: #13473
Test: packCrsGraph/packCrsMatrix now pass, ImportExport2 test now compiles
Stakeholder Feedback:  As the stakeholder, I approve.
Also, adding some kernel labels.

Tpetra: Fixing AMD Unified Memory issue in packCrs[Graph|Matrix] test / ImportExport2 test compile error

---

packages/belos/tpetra/example/Orthog/TpetraOrthogEx.cpp
packages/belos/tpetra/src/BelosMultiVecTraits_Tpetra.hpp
packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp

To reduce the number of allocations which are expensive in Cuda builds.
Trying to improve SPARC solve performance when using the Ifpack2 block tridiagonal as a preconditioner for Belos GMRES.

belos: Use a pooling strategy for Tpetra MultiVectors.

---

CONTRIBUTING.md

Want to ensure that developers can find instructions about DCO signoff requirement.

Framework: Add DCO instructions

---

packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp

This PR removes the Tacho compile warnings seen on MI300 GPU.

Tacho : compile warnings on Mi300

---

.github/workflows/AT2.yml

This is part of the effort to transition existing CI builds from AutoTester to AutoTester2 (AT2). This PR adds a new AT2 job that replicates the Framework Python tests run by `anaconda` AutoTester build.
The job utilizes a Framework Python container for its test environment.
- [TRILFRAME-670](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-670)
Adding this new job requires testing that the implemented AT2 container spawner for the Python container is working and for this added AT2 job to run successfully within that container. With that, I've tested:
- Framework Python AT2 container spawner is working ([Python runners can be seen here](https://github.com/trilinos/Trilinos/settings/actions/runners))
This PR will test whether the job can be picked up and run …

Framework: Add Framework tests AT2 job

---

packages/kokkos-kernels/batched/dense/impl/KokkosBatched_SVD_Serial_Internal.hpp
packages/kokkos-kernels/batched/dense/unit_test/Test_Batched_SerialSVD.hpp

Fix batched serial SVD hanging for some inputs.
This fixes the kernel and adds some new test cases.
See https://github.com/kokkos/kokkos-kernels/pull/2345 for original PR.
@vbrunini 
Fixes SVD hanging in 2 matrices that @vbrunini found.
Fixes issue 
* Closes https://github.com/kokkos/kokkos-kernels/issues/2344
This adds test cases that replicated the original issue, and these are now passing.

KokkosKernels: patch PR 2345

---

packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_GDSWCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_IPOUHarmonicCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_RGDSWCoarseOperator_def.hpp

This PR fixes some issues with multiple blocks
- computeExtention with multiple blocks
- No coarse function on some blocks
```
Start  1: ShyLU_DDFROSch_test_interfacepartitionofunity_DIM2_TPETRA_MPI_4
1/66 Test  #1: ShyLU_DDFROSch_test_interfacepartitionofunity_DIM2_TPETRA_MPI_4 .........................................   Passed    4.75 sec
Start  2: ShyLU_DDFROSch_test_interfacesets_DIM2_CSCommCrsMatrix_TPETRA_MPI_4
2/66 Test  #2: ShyLU_DDFROSch_test_interfacesets_DIM2_CSCommCrsMatrix_TPETRA_MPI_4 .....................................   Passed    4.35 sec
Start  3: ShyLU_DDFROSch_test_interfacesets_DIM2_CSCommCrsGraph_TPETRA_MPI_4
3/66 Test  #3: ShyLU_DDFROSch_test_interfacesets_DIM2_CSCommCrsGraph_TPETRA_MPI_4 ......................................   Passed    3.91 sec …
```

FROSch : fix issues with multiple blocks

---

packages/sacado/src/Sacado_Fad_VectorImp.hpp

@etphipp
When compiling with `clang`, we get the warning:
```
/opt/Trilinos/.../include/Sacado_Fad_VectorImp.hpp:88:66: error: ISO C++ requires the name after '::~' to be found in the same scope as the name before '::~' [clang-diagnostic-dtor-name]
88 | Sacado::Fad::Vector< OrdinalType, Sacado::Fad::DVFad<ValueType> >::
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
|                                                                  ::Vector
11957 warnings and 1 error generated.
``` 
This PR solves this issue by putting this piece of code explicitly in the namespace `Sacado::Fad`. 
Note that I've tried fixing it the other way around by writing something like 
```
~Vector<OrdinalType, Sacado::Fad::DVFad<ValueType>()
```
That works with `clang`, but …

Sacado: Fix clang -Wdtor-name warning

---

packages/kokkos-kernels/sparse/impl/KokkosSparse_sort_crs_impl.hpp
packages/kokkos-kernels/sparse/src/KokkosSparse_SortCrs.hpp

Matching patch for https://github.com/kokkos/kokkos-kernels/pull/2353/
A performance regression in `KokkosSparse::sort_crs_matrix` was introduced in https://github.com/trilinos/Trilinos/pull/13401, where `sort_crs_matrix` was changed to use `Kokkos::Experimental::sort_by_key` in certain cases. 
One of the MueLu setup performance tests catches one of those cases:
```bash
muelu/test/scaling/MueLu_Driver.exe" "--stacked-timer" "--nx=120" "--ny=120" "--nz=120" "--matrixType=Laplace3D"
```
On MI300 this manifested as a ~60x slowdown in Tpetra's matrix transpose because `sort_by_key` is only fast on AMD when Kokkos can use the rocThrust TPL, which Trilinos does not support. This PR also preemptively attempts to avoid falling in to the same trap on SYCL. For CUDA, Thrust …

KokkosKernels: match #2353

---

packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C

The default field metadata output is causing problems in some applications.
Disabling by default until problems can be determined. 
The field metadata output can be enabled through the IOSS property `OUTPUT_FIELD_METADATA=YES`
@spdomin @alanw0 @tokusanya

IOSS: Turn of field metadata output by default

---

packages/stokhos/src/sacado/kokkos/vector/KokkosBlas2_gemv_MP_Vector.hpp

Let FTAD do its job, do not interfere.
@etphipp
@ndellingwood

Stokhos: Do not specify template arg when using Kokkos atomics

---

packages/framework/pr_tools/PullRequestLinuxDriver.sh
packages/framework/pr_tools/PullRequestLinuxDriverTest.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py

I modified some argument handling logic recently to clean things up and enable extra configure arguments more cleanly, and it appears I caused an issue where the Kokkos builds stopped showing up in the correct group on CDash.
Fixes bug introduced in #13427
I tested manually and confirmed that the issue was present without this change, and works as expected with this change.

Framework: Fix kokkos integration cdash group

---

packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase1Algorithm_def.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_def.hpp
packages/nox/test/tpetra/1DFEM_Functors.hpp
packages/sacado/test/performance/fenl_assembly/fenl_functors.hpp
packages/sacado/test/performance/fenl_assembly_view/fenl_functors.hpp
packages/shylu/shylu_node/basker/src/shylubasker_thread.hpp
packages/stk/stk_performance_tests/stk_mesh/calculate_centroid.hpp
packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
packages/trilinoscouplings/examples/fenl/fenl_functors.hpp

`Kokkos::atomic_{increment,decrement}` have been deprecated.
This PR is mostly a search and replace with `atomic_{inc,dec}`.  (**edit** the inc/dec atomic functions are available since 4.0, these changes are backward compatible with respect to Kokkos)
In the Sacado and TilinosCoupling FENL performance tests/example, I qualified all uses of Kokkos atomic functions.
Please note that opening the Kokkos namespace is not legal (see https://kokkos.org/kokkos-core-wiki/ProgrammingGuide/Compatibility.html)
cc @ndellingwood

Fixup `Kokkos::atomic_{inc,dec}[rement]`

---

packages/ifpack2/src/Ifpack2_Experimental_RBILUK_decl.hpp
packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp

This should greatly improve the performance of RBILUK::apply since we don't have to do the trsv on sequential host.
Built and tested `Ifpack2_RBILUK_hb_belos_block_serial_MPI_1` on mappy.

RBILUK: Use new KK::sptrsv block support instead of KK::trsv

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
packages/tpetra/core/src/Tpetra_Distributor.hpp

@trilinos/tpetra @jhux2
Converts transfer and fill complete to use Kokkos to make it performance portable.
- Related to
- #11689 
- #12297.
N/A
Covered by existing unit tests.

Tpetra: Transfer and fill complete refactor

---

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp

replace use of Kokkos impl_* routine, preemptive change in case internal impl routines become private members
Preemptive change in case internal impl routines become private members
Related to https://github.com/kokkos/kokkos/issues/7495
AT

tpetra: replace use of impl_dualview_is_single_device

---

packages/framework/ini-files/config-specs.ini

attempt to resolve the cuda_graph.diamond subtest failure in nightly integration testing track
The https://trilinos-cdash.sandia.gov/test/66394774 test fails on the nightly integration testing track but has not demonstrated the failure in kokkos CI/nightly testing. This is an attempt/experiment to see if running the test in serial resolves the issue
This won't really get tested, with respect to the failure, until it hits the nightly integration testing track - @trilinos/framework is there a preferred or alternative way to early-test this type of change with the nightly integration testing job?

config-specs: set Kokkos_CoreUnitTest_Cuda1 to run serial

---

packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/Utils/MueLu_AggregateQualityEstimateFactory_decl.hpp
packages/muelu/src/Utils/MueLu_AggregateQualityEstimateFactory_def.hpp
packages/muelu/test/interface/default/EasyParameterListInterpreter/aggregatequalities.xml
packages/muelu/test/interface/default/FactoryParameterListInterpreter/aggregatequalities.xml
packages/muelu/test/interface/default/Output/aggregatequalities_epetra.gold
packages/muelu/test/interface/default/Output/aggregatequalities_tpetra.gold
packages/muelu/test/unit_tests/AggregateQualityEstimateFactory.cpp

Using the aggregate quality calculation results in several executions of `AggregateQualityEstimateFactory` and thus also triggering the aggregation process several times.
This MR proposes to make it a transfer factory as several other utility factories already are (e.g. aggregate output), means it only gets executed once during the RAPFactory call per level.
@cgcgcg

MueLu: Make AggregateQualityEstimateFactory a transfer factory

---

packages/sacado/src/Kokkos_DynRankView_Fad.hpp

This PR is a refactor which aims to remove the use of `Kokkos::Impl::DynRankViewFill` in `sacado`. This struct is not tested and not used in Kokkos since 2021, and will be removed by kokkos/kokkos#7520.
This PR was successfully tested against `sacado` tests.

Remove the use of `Kokkos::Impl::DynRankViewFill` in Sacado

---

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/Utils/MueLu_AggregationExportFactory_decl.hpp
packages/muelu/src/Utils/MueLu_AggregationExportFactory_def.hpp

The export of the aggregates triggers the aggregation process several times. This MR fixes the issue by telling the aggregate export, which factory it should use for `Graph` and `Aggregates`.
@cgcgcg @jhux2

MueLu: Tell aggregate export about Graph and Aggregates

---

packages/framework/pr_tools/PullRequestLinuxDriver.sh

Complete oversight that this was not already on.
Want ccache everywhere that we can (especially for PR).
`module load sems-ccache` works on the RHEL8 machine I was testing.

Framework: Enable CCache on RHEL8

---

packages/intrepid2/src/Cell/Intrepid2_CellData.cpp

In PR #13437, the `Basis` class switched from employing a `shards::CellTopology` (as member `basisCellTopology_`) to storing the `unsigned shards::CellTopology::key` corresponding to the `CellTopology` (as member `basisCellTopologyKey_`).   The method `getCellTopologyData()` returns a `CellTopologyData*` for a given `shards::CellTopology::key`.  However, it does not do so for `Node` cell topologies.  This breaks a subclass Camellia implements for defining basis functions on a vertex.
This PR adds support for `Node` cell topologies in `Intrepid2::getCellTopologyData()`.

Intrepid2: support shards::Node in getCellTopologyData().

---

.github/workflows/AT2.yml

Will allow us to better compare AT1 vs. AT2 performance and evaluate if we're ready to move builds onto the new system.

Framework: Match CPU parallelism with AT1 args

---

.github/workflows/AT2.yml

Want to use the new variables for image names, because `AT2_IMAGE_FULLPATH` is what used to be in `AT2_IMAGE` (`AT2_IMAGE` will be only the basename of the image from now on).
https://gitlab-ex.sandia.gov/trilinos-project/trilinos-containers/-/merge_requests/25

Framework: Use new container env vars

---

packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp

Dirichlet boundary detection is not working properly for numDofsPerNode > 1 in the non-kokkos distance laplacian dropping.
This fixes the issue and removes additional conditions from the printing statement.

MueLu: Fix boundary detection for non-kokkos distance laplacian dropping

---

packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_decl.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_def.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp
packages/muelu/test/interface/kokkos/Output/operator_solve_1_np1_tpetra.gold
packages/muelu/test/interface/kokkos/Output/operator_solve_1_np4_tpetra.gold
packages/muelu/test/interface/kokkos/Output/operator_solve_5_np1_tpetra.gold
packages/muelu/test/interface/kokkos/Output/operator_solve_5_np4_tpetra.gold
packages/muelu/test/interface/kokkos/Output/operator_solve_6_np1_tpetra.gold
packages/muelu/test/interface/kokkos/Output/operator_solve_6_np4_tpetra.gold
packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp
packages/muelu/test/unit_tests_kokkos/Regression.cpp

Compute `aggWeight` in phase 2b locally for each unaggregated node instead of globally for all nodes of a given color. Since code pah is very similar for "random" and "deterministic" paths, merge them into one templated method.

MueLu: Fix for phase 2b

---

packages/nox/src-thyra/NOX_Thyra_Group.C
packages/panzer/disc-fe/src/Panzer_ModelEvaluator_impl.hpp

@trilinos/nox @trilinos/panzer 
Charon is using the nox and loca groups as building blocks for a new solver algorithm. Added a safety check for a null vector in panzer that was triggered by their use case. Also temporarily disabled a throw in nox group logic that was forcing the Jacobian update to be handled explicitly by the user. It will now do an implicit update if needed.
Changes are to code that is covered under current unit tests.

NOX,Panzer: minor changes to logic for a new Charon solver

---

packages/panzer/adapters-stk/test/evaluator_tests/tpetra_blocked_scatter_residual.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_BlockedTpetra.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_BlockedTpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp

Part 3 of our tangent capability upgrade. This MR updates the `ScatterResidual_BlockedTpetra` evaluator and `GatherTangents_BlockedTpetra`.

Panzer tangent scatter blocked tpetra

---

packages/epetraext/src/transform/EpetraExt_AMD_CrsGraph.cpp
packages/ifpack/src/Ifpack_CrsRiluk.cpp
packages/trilinoscouplings/src/epetraext/EpetraExt_Isorropia_CrsGraph.cpp

@trilinos/ifpack @trilinos/epetraext 
The transition from Epetra->Tpetra for Xyce includes several intermediate steps, including moving to newer compilers and introducing a global ordinal type that is 64-bit.  This effort has uncovered a few issues in some Trilinos classes that need to be addressed so that we can continue this transition.  This includes:
- Change AMD transformation in EpetraExt to be correct for 64-bit global ordinals
- Fix memory allocation in Ifpack CrsRiluk preconditioner to not seg-fault if a subdomain is allocated zero rows
- Fix Isorropia transformation in EpetraExt to be a no-op for 64-bit global ordinals
These changes have been used to correct regression test failures for Xyce on
FreeBSD / MPI+Clang 18
OSX / MPI+Clang15

Some small fixes necessary for the Xyce Epetra->Tpetra transition

---

cmake/ProjectCompilerPostConfig.cmake
packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_def.hpp

- MueLu: Silence "reorder" warning.
- Add "reorder" as promoted warning so that we error out in the future.

Add "reorder" as promoted warning

---

.github/workflows/AT2.yml
packages/framework/pr_tools/PullRequestLinuxDriver.sh
packages/framework/pr_tools/PullRequestLinuxDriverTest.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py

Want dashboard build names to be simultaneously clear/concise and descriptive, so that users can understand which build is which at a glance.  To that end, new format is:
`PR-<pull-request-number>_<image-basename>_<release-or-debug>_<static-or-shared>_<optional-special-characteristics>`
Image basename is fairly descriptive, e.g. `ubi8-gcc-10.3.0-openmpi-4.1.6` (usually it's a combination of the OS, compiler, and MPI).
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-684

Framework: Update at2 build names

---

packages/zoltan2/core/src/algorithms/order/Zoltan2_AlgMetis.hpp

Compilers emit warnings such as
```
/tmp/trilinos/packages/zoltan2/core/src/algorithms/order/Zoltan2_AlgMetis.hpp:158:80: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
throw std::runtime_error(std::string("METIS_NodeND returned info = " + info));
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/tmp/trilinos/packages/zoltan2/core/src/algorithms/order/Zoltan2_AlgMetis.hpp:158:80: note: use array indexing to silence this warning
throw std::runtime_error(std::string("METIS_NodeND returned info = " + info));
^
&                               [     ]
```
and it seems the intention was to append `info` (as string) to the string literal instead of advancing the string literal pointer by some integer and converting to a `std::string`. Converting …

Zoltan2: Fix runtime_error message with METIS

---

packages/shylu/shylu_node/tacho/CMakeLists.txt

To solve some issues with required libraries, we now require RocBLAS, RocSparse, and RocSolver TPLs for building Tacho with HIP backend.
- https://github.com/trilinos/Trilinos/issues/13636

Tacho : require RocBLAS, RocSparse, and RocSolver for HIP backend

---

cmake/ProjectCompilerPostConfig.cmake
packages/framework/ini-files/config-specs.ini

@dc-snl 
In analyzing an internal customer (RAMSES) configuration for Trilinos, I noticed they were passing `-Wno-uninitialized`.  I wanted to see if we could add that warning to our PR configurations to help guard against warnings/errors that they had previously seen, and ideally obviate the need for them to pass that flag as part of their configuration.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-680
I tested this with a GCC 8.5.0 build and everything built cleanly.

Add `uninitialized` to promoted warnings list

---

cmake/TPLs/FindTPLBLAS.cmake
cmake/TPLs/FindTPLLAPACK.cmake
cmake/tribits/common_tpls/FindTPLBLAS.cmake
cmake/tribits/common_tpls/FindTPLLAPACK.cmake
packages/framework/ini-files/config-specs.ini

@trilinos/framework @bartlettroscoe 
This allows to use OpenBLAS for BLAS and LAPACK without additional configuration.

TPLs BLAS and LAPACK: Add OpenBLAS to library names

---

packages/framework/ini-files/config-specs.ini
packages/framework/pr_tools/LaunchDriver.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py

EXTRA_CONFIGURE_ARGS can now be used to pass extra flags to our build scripts.
Also had to remove FORCE flag from `Trilinos_ENABLE_TESTS` (in config-specs.ini) so that we are able to override it.
See https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-674

Framework: Add support for using EXTRA_CONFIGURE_ARGS env variable

---

packages/framework/ini-files/config-specs.ini

The section `CUDA11-RUN-SERIAL-TESTS` was renamed to `CUDA-RUN-SERIAL-TESTS`.

Framework: Hotfix for config.ini section change

---

packages/adelus/src/Adelus_forward.hpp

This PR is to fix the out-of-bounds access on the RHS in the forward function. This happens when there are some ranks having less RHS rows than others. The fix is to wrap the ```parallel_for``` below line 107 in the condition ```if(curr_lrid < RHS.extent(0)){...}```
The Gemma team confirm this fixes the issue.

Adelus: Fix out-of-bound access on RHS in forward

---

packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp

Panzer fails to compile on MI300A after upgrade to kokkos 4.5. They renamed an internal macro that panzer uses.
N/A

Panzer: fix for changes in kokkos 4.5 for MI300A

---

packages/amesos2/src/Amesos2_Tacho_decl.hpp
packages/amesos2/src/Amesos2_Tacho_def.hpp
packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/main.cpp
packages/shylu/shylu_node/tacho/cmake/Tacho_config.h.in
packages/shylu/shylu_node/tacho/example/Tacho_ExampleDriver.hpp
packages/shylu/shylu_node/tacho/src/Tacho_CrsMatrixBase.hpp
packages/shylu/shylu_node/tacho/src/Tacho_Driver.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemm.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemv.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools_Metis.cpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_GraphTools_Metis.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Herk.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LDL.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LU.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LU_External.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LU_Internal.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_LU_Serial.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Lapack_Team.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Base.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Serial.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_SymbolicTools.cpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_SymbolicTools.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_ExtractCRS.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeLU.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsm.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsv.hpp

This PR adds some new features to Tacho
- Tolerance to replace tiny pivots for team LU
- Internally compress graph based on "DoFs per node" for symbolic
- Use AMD if Metis is not enabled

Tacho : new options (dofs-per-node, pivot-tol, amd)

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/options_smoothing_and_coarse.tex
packages/muelu/doc/UsersGuide/paramlist.tex
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp

I think our preference would be to use the KLU solvers as the default coarse grid solver. We've experienced issues where the SuperLU based coarse grid solvers will throw in a parallel-inconsistent manner, leading to a deadlock.

MueLu: Use KLU as default coarse grid solver

---

packages/framework/ini-files/config-specs.ini
packages/intrepid2/unit-test/MonolithicExecutable/CMakeLists.txt

Frequent timeouts on GCC/OpenMPI Debug Shared configuration in PR testing, and before it was marked serial for CUDA had repeated failures there as well (though those were not timeouts).
It repeats often enough that I do wonder if this is exposing a code issue, but debugging that is outside of my area of expertise unfortunately.

Intrepid2: Serialize unit test

---

packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp

To fix an error on H100.
Tested on H100, V100, and Mi250, and also with OpenMP

Tacho : return value from team-factor

---

.github/workflows/AT2.yml
packages/framework/get_dependencies.sh

GenConfig has released its repositories on GitHub. Our Framework scripts should utilizes these repositories instead of the versions hosted on internal repositories. This effort also contributes to the eventual release of our Framework containers.
Manually tested this script on SRN and in our containerized environment and was able to load existing configurations.
Further testing should be observed in the CI.

Framework: Update get_dependencies.sh script to use open-sourced repo

---

.github/workflows/AT2.yml

Change main workflow name from AT2-EXPERIMENTAL back to AT2. Mark those individual runs that are anticipated to be transitioned to required as no longer EXPERIMENTAL.

Framework: Rename AT2 builds to indicate production-readiness

---

packages/framework/ini-files/config-specs.ini
packages/kokkos-kernels/CHANGELOG.md
packages/kokkos-kernels/CMakeLists.txt
packages/kokkos-kernels/master_history.txt
packages/kokkos/CHANGELOG.md
packages/kokkos/CMakeLists.txt
packages/kokkos/Makefile.kokkos
packages/kokkos/README.md
packages/kokkos/containers/src/Kokkos_DynRankView.hpp
packages/kokkos/core/unit_test/TestAtomicViews.hpp
packages/kokkos/core/unit_test/TestViewBadAlloc.hpp
packages/kokkos/master_history.txt
packages/kokkos/scripts/docker/Dockerfile.gcc
packages/kokkos/scripts/docker/Dockerfile.hipcc
packages/kokkos/scripts/docker/Dockerfile.kokkosllvmproject
packages/kokkos/scripts/docker/Dockerfile.nvcc
packages/kokkos/scripts/docker/Dockerfile.nvhpc
packages/kokkos/scripts/docker/Dockerfile.openmptarget
packages/kokkos/scripts/docker/Dockerfile.sycl
packages/kokkos/tpls/mdspan/include/experimental/__p0009_bits/config.hpp
packages/kokkos/tpls/mdspan/include/experimental/__p2630_bits/submdspan_mapping.hpp
packages/tpetra/CMakeLists.txt

@trilinos/kokkos @trilinos/kokkos-kernels 
Snapshot Kokkos Ecosystem patch release 4.5.1 to Trilinos
Various CI and nightly testing

Kokkos + KokkosKernels Promotion To 4.5.1

---

RELEASE_NOTES
cmake/ProjectCompilerPostConfig.cmake
packages/framework/ini-files/config-specs.ini

Trilinos should have the cleanest compile output currently possible and prevent introducing as many warnings as possible in the future.
I looped over a (theoretically) complete list of warnings that are supported by GCC 10 and checked which of them do not occur anywhere in Trilinos (non-deprecated packages only).

Draft: Framework: Promote all clean warnings

---

packages/intrepid2/src/Projection/Intrepid2_ProjectionTools.hpp

Address issue https://github.com/kokkos/kokkos-kernels/issues/2456#issuecomment-2540665787
@trilinos/intrepid2 @mperego 
Address compatibility update discussed in https://github.com/kokkos/kokkos-kernels/issues/2456

intrepid2: compatibility update with kokkos-kernels

---

packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_Cn_FEM/CMakeLists.txt

Repeated compile failures building `Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_test_02_CUDA_DFAD_DFAD` ([example](https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=343224)).  With the approach of the AT2 CUDA build being transitioned to production, we need the line clean.
Same paradigm as used elsewhere.
I did some diagnosis on this, since it was apparently succeeding to build with the AT1 configuration/machine, and I didn't want to disable it if at all possible.  The load numbers on the AT2 machine show the CPU spiking to over 100%, but only for 1-2 minutes.  When I checked one of the AT1 machines, I saw the same spike, but only to about 60%.  This makes sense, since the parallelism for these machines is higher, given that they have …

Intrepid2: Disable test

---

packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter.hpp
packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter_Def.hpp
packages/piro/src/Piro_TempusIntegrator.hpp
packages/piro/src/Piro_TempusIntegrator_Def.hpp
packages/piro/src/Piro_TempusSolver.hpp
packages/piro/src/Piro_TempusSolver_Def.hpp
packages/piro/src/Piro_TransientSolver_Def.hpp
packages/piro/test/CMakeLists.txt
packages/piro/test/MockModelEval_A_Tpetra.cpp
packages/piro/test/Piro_TempusSolver_UnitTests.cpp
packages/piro/test/Piro_Test_MockTempusObserver.hpp
packages/piro/test/_input_tempus_be_nox_solver.yaml

This PR does two main things:
1. In TempusSolver, allow to pass the user-provided observer directly to the tempus integrator (if compatible). That is, if the user-provided `Piro::ObserverBase` pointer also happens to inherit from `Tempus::IntegratorObserverBasic`, then don't create a `ObserverToTempusIntegrationObserverAdapter` (to wrap it into a tempus-compatible one), but just use it directly. That is because the user-provided
2. In TransientSolver: avoid copying the final solution into the outArgs last response (a copy of the solution) if incompatible. This can happen if mesh adaptivity happened during the time integration. In this case, the gx_out response (the last response) would have a vector space corresponding to the initial mesh, which would not be compatible with the current …

Piro: tempus/transient solver mods.

---

packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_HEX_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_QUAD_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TET_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TRI_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_HEX_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_QUAD_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TET_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TRI_In_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_LINE_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_QUAD_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_HEX_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_LINE_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_QUAD_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TET_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TRI_Cn_FEMDef.hpp

@mperego @CamelliaDPG 
This PR fixes "implicit by-copy capture of this is deprecated" warnings when compiling `Intrepid2` after:
- https://github.com/trilinos/Trilinos/pull/13437
The PR Trilinos#13437 uses lambdas that capture class variables, but the implicit capture of `this` is deprecated. When we compile with `nvcc` with `cuda` 12.6 and `gcc` 13.3 as the host compiler and C++20 standard, we get compilation errors. 
This PR is a proposed solution with "capture with initializer".

fix(Intrepid2): implicit by-copy capture of this is deprecated warnings

---

packages/framework/get_dependencies.sh
packages/framework/normalize_git_repo_url.py

* [TRILINOSHD-278](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-278)
This addresses the problem where someone has an existing GenConfig repo clone before the GenConfig repos got moved to GitHub and tries to run the get_dependencies.py tool and gets a strange error message.  This PR updates the get_dependencies.py to check that the remote URL of the base GenConfig repo is correct and errors out with a good error message if it does not.
This also normalizes the comparison of the remote URLs too allow for developers to use the git@ protocol to do development on the GenConfig repos and still be able to run the get_dependencies.py as part of there development and testing workflow.
NOTE: The new utility script `normalize_git_repo_url.py` is maintained with …

Check for changed GenConfig remote URL and error out

---

packages/teuchos/core/test/MemoryManagement/RCP_Performance_UnitTests.cpp

Should fix #13728 and #8648 once and for all.  (See https://github.com/trilinos/Trilinos/issues/13728#issuecomment-2595614872).

Increase default maxRcpRawObjAccessRatio from 13.5 to 20.0 (#8648, #13728)

---

packages/thyra/core/src/support/operator_vector/client_support/Thyra_DefaultMultipliedLinearOp_decl.hpp
packages/thyra/core/src/support/operator_vector/client_support/Thyra_DefaultMultipliedLinearOp_def.hpp

@trilinos/thyra 
Caching of intermediate vectors for `MultipliedLinearOp` to avoid reallocation during timestepping.

Thyra DefaultMultipliedLinearOp: Caching of intermediate vectors

---

.github/workflows/AT2.yml
commonTools/framework/github_issue_creator/create_trilinos_github_test_failure_issue_unit_tests.py

Want the names to be up-to-date as early as possible so that users will have the correct checks on their branches _before_ the check is required.

Framework: AT2 name update

---

packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_Factory.hpp
packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp

This PR enables `variant 3` solve with OpenMP
Tested `variant 3` of chol & lu with Cuda (V100), Hip (Mi250), and OpenMP.
It is based on a simple sequential SpMV.

Tacho : variant-3 solve with OpenMP

---

cmake/ProjectCompilerPostConfig.cmake
packages/rol/adapters/sacado/test/test_01.cpp
packages/rol/src/algorithm/ROL_OptimizationSolver.hpp

@trilinos/rol 
Add in missing default in switch-case to report that `TYPE_P` is not supported in `OptimizationSolver`.
This closes https://github.com/trilinos/Trilinos/issues/13765.
I should clarify that there's still the issue of hooking up `TYPE_P` in the `OptimizationSolver`, which I have added as https://github.com/trilinos/Trilinos/issues/13767.

ROL: Fix missing switch-case compilation error in OptimizationSolver

---

cmake/ProjectCompilerPostConfig.cmake

If the compiler in use is not GCC, disabling GCC warnings can cause compile errors.
#13744 
I configured with and without the GCC compiler and the output looked as expected.

Framework: Only disable GCC warnings for GCC

---

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp

The comparison fixed here was always true. The context makes it clear that the code meant to compare the current object with `graph`.
The `Tpetra` unit tests passed with this change.
Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

Tpetra: Fix typo in CrsGraph<LocalOrdinal, GlobalOrdinal, Node>::isIdenticalTo()

---

packages/seacas/libraries/exodus/src/ex_get_init_ext.c
packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.C

Fixes to SEACAS-Snapshot-01-2025 

---

packages/belos/src/BelosBlockCGIter.hpp
packages/belos/src/BelosBlockCGSolMgr.hpp
packages/belos/src/BelosCGIter.hpp
packages/belos/src/BelosCGIteration.hpp
packages/belos/src/BelosCGSingleRedIter.hpp
packages/belos/src/BelosPseudoBlockCGIter.hpp
packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
packages/stokhos/src/sacado/kokkos/vector/belos/Belos_PseudoBlockCGIter_MP_Vector.hpp

Before this change the CG variants set only the initial residual vector from the problem in the `CGIterationState` structure.
The `Z`, `P` and `AP` member variables were not set. All auxiliary vectors were reallocated on every solve in the `CGIteration` class. 
With this change, all auxiliary vectors are members of the state and are reused or reallocated on subsequent solves.

Belos CG: Caching of state vectors

---

packages/epetra/doc/Doxyfile.options
packages/epetra/doc/DoxyfileWeb
packages/epetra/doc/build_docs
packages/epetra/src/Epetra_BasicRowMatrix.h
packages/epetra/src/Epetra_CrsMatrix.h
packages/epetra/src/Epetra_FastCrsMatrix.h
packages/epetra/src/Epetra_InvOperator.h
packages/epetra/src/Epetra_Operator.h
packages/epetra/src/Epetra_RowMatrix.h
packages/epetra/src/Epetra_SerialDenseOperator.h
packages/epetra/src/Epetra_SerialDenseSVD.h
packages/epetra/src/Epetra_VbrMatrix.h

Fixes several doxygen build errors, along with the needed paths to EXAMPLE_PATH to find the missing
tutorial code.
Removed build of epetra/thyra since it no longer exists.
Commented out the build of "Epetra Package Browser (Single Doxygen Collection)", which is currently broken, but no one noticed/needed.
@trilinos/epetra 
Fix broken doxygen pages not including example code.
* Closes #13785

Epetra: Missing Tutorial Code

---

packages/amesos2/example/SimpleSolve_File.cpp
packages/amesos2/test/solvers/CMakeLists.txt
packages/amesos2/test/solvers/shylubasker_test.xml
packages/shylu/shylu_node/basker/src/shylubasker_decl.hpp
packages/shylu/shylu_node/basker/src/shylubasker_def.hpp
packages/shylu/shylu_node/basker/src/shylubasker_matrix_decl.hpp
packages/shylu/shylu_node/basker/src/shylubasker_matrix_def.hpp
packages/shylu/shylu_node/basker/src/shylubasker_nfactor_col2.hpp
packages/shylu/shylu_node/basker/src/shylubasker_order.hpp
packages/shylu/shylu_node/basker/src/shylubasker_sfactor.hpp
packages/shylu/shylu_node/basker/src/shylubasker_tree.hpp
packages/shylu/shylu_node/basker/src/shylubasker_types.hpp
packages/shylu/shylu_node/basker/test/amesos2_interface_coverage_test.cpp
packages/shylu/shylu_node/basker/test/singular_matrix_check.cpp

Setup the data-structure for nested-dissection factorization of big block in symbolic.

ShyLU-Basker : move ND data-struc setup to symbolic

---

packages/amesos2/src/Amesos2_KLU2_def.hpp
packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp
packages/amesos2/src/Amesos2_TpetraCrsMatrix_MatrixAdapter_def.hpp

It adds a logic to handle the GIDs in colMap, that are not in rowMap.
- https://github.com/trilinos/Trilinos/issues/13774

Amesos2 : matrix-gather when colMap does not match rowMap

---

packages/ifpack2/example/CMakeLists.txt
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

In BlockTriDi's ExtractAndFactorize kernels that use scratch, fall back to level 1 when there isn't sufficient level 0.
Ifpack2's block TriDi and block Jacobi should work for block sizes to and including 32. For relatively large block sizes like 27, many GPUs didn't have enough shared memory per block for the numeric setup (extract+factorize). When there isn't enough shared, this PR falls back to level 1 scratch.
The level 0 and level 1 cases are instantiated separately to make sure there is no performance hit to the original level 0 case.
No issue for this, was reported by email
Issue reported directly by @jewatkins for SPARC.
Added testing with the maximum block size of 32. Verified that the level 1 scratch code path is taken on nvidia and amd gpus in this test.

Ifpack2: BlockTriDi fix for large blocks

---

packages/muelu/src/Operators/MueLu_Maxwell1_def.hpp
packages/muelu/src/Operators/MueLu_RefMaxwell_decl.hpp
packages/muelu/src/Operators/MueLu_RefMaxwell_def.hpp

- Use async communication in RefMaxwell
- Fix an overflow issue in CoalesceDrop

MueLu: Async comm in RefMaxwell

---

packages/belos/tpetra/src/BelosMultiVecTraits_Tpetra.hpp

https://github.com/kokkos/kokkos/pull/7716 proposes to deprecate the ability to access `DualView`'s `h_view` and `d_view` members directly since modifying the allocations can get perturbed the `DualView`'s internal status. This pull request replaces all places in `Belos` that use these members directly, in most places, verbatim with `view_device` resp. `view_host`.
Related to https://github.com/kokkos/kokkos/pull/7716.
Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

Belos: Don't access DualView's [h|d]_view directly

---

packages/zoltan2/core/src/input/Zoltan2_BasicKokkosIdentifierAdapter.hpp
packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
packages/zoltan2/test/core/partition/mj_backwardcompat.cpp

https://github.com/kokkos/kokkos/pull/7716 proposes to deprecate the ability to access `DualView`'s `h_view` and `d_view` members directly since modifying the allocations can get perturbed the `DualView`'s internal status. This pull request replaces all places in `Zoltan2` that use these members directly, in most places, verbatim with `view_device` resp. `view_host`.
Related to https://github.com/kokkos/kokkos/pull/7716.
Signed-off-by: Daniel Arndt <arndtd@ornl.gov>

Zoltan2: Don't access DualView's [h|d]_view directly 

---

packages/muelu/src/Utils/MueLu_Utilities_decl.hpp

@trilinos/muelu @cgcgcg @mayrmt 
The changes made in #13784 breaks our `4C`-multiphysics build with `Trilinos`. Thus this PR fixes the one, old leftover `Tpetra` cast construct.
* Follows #13784

[MueLu] Fix toTpetra operator cast

---

packages/tpetra/core/test/CrsMatrix/Equilibration.cpp

Issue: #13159Test: YesStakeholder Feedback: n/a

Tpetra: Adding test for symmetric equlibration

---

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

https://github.com/trilinos/Trilinos/pull/13823 didn't inlcude the patch in https://github.com/trilinos/Trilinos/pull/13820#issuecomment-2667128984. Since `view_[host|device]` will return by `const&` in the future and returns by value right now, assigning to it isn't intended. Instead you would create a new `DualView` from existing Views.
@jhux2 tested this in https://github.com/trilinos/Trilinos/pull/13820#issuecomment-2667217874.

Tpetra: Fix assignment to DualView::view_[host|device]

---

packages/ifpack2/src/Ifpack2_BlockComputeResidualVector.hpp
packages/ifpack2/src/Ifpack2_BlockHelper.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

Improve GPU performance of BlockTriDi residual kernel, especially on AMD MI300A.
- Separately instantiate the BlockCrs and non-BlockCrs kernel implementations on GPU, instead of having a runtime branch inside the kernel.
- Merge the Async and Overlap tagged kernels since they are almost the same (only difference is how to decide whether to load LHS from ``x`` or ``x_remote``). This reduces code but also means any optimization only needs to be written in one place (#13610 only added optimizations for the Overlap tag and would have needed to be duplicated to the Async version).
- Incorporate changes by @seanofthemillers in #13610
- Precompute A, x entry offsets to reduce levels of indirection and cache pressure
- Remove unnecessary team barriers
Also fixed some invalid …

Ifpack2: BlockTriDi/Block Jacobi residual improvements

---

.github/workflows/AT2.yml

Want to directly provide the container recipe for the images used for each AutoTester2 job.
Adds a GitHub Actions Marketplace action for uploading artfiacts inside GitHub Runners to the GitHub Actions workflow interface. The added step uploads files from a specific directory inside the containers meant for generated artifacts.
https://github.com/actions/upload-artifact
- trilinos/containers#10
- trilinos/containers#11
- [TRILFRAME-691](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-691)
- Self-testing through AT2. Before merging, observe that the AT2 GitHub Actions jobs provides an artifact Dockerfile

Framework: Add upload-artifact step to AT2 jobs

---

packages/muelu/src/Utils/MueLu_AggregationExportFactory_def.hpp

Small fix to properly visualize the material tensor for aggregates in .vtu format.
Need to recreate .gold files for visualization testing.
@cgcgcg

MueLu: Fix aggregate material visualization

---

packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp
packages/muelu/test/unit_tests_kokkos/CoalesceDropFactory_kokkos.cpp

The non-Kokkos code path does this and the Kokkos code path matched this behavior. There doesn't seem to be a good reason for it, so we relax this in the Kokkos code path.

MueLu: Do not hard code "aggregation: dropping may create Dirichlet"

---

packages/teko/src/Tpetra/Teko_BlockingTpetra.cpp
packages/teko/src/Tpetra/Teko_BlockingTpetra.hpp
packages/teko/src/Tpetra/Teko_TpetraBlockedMappingStrategy.cpp
packages/teko/src/Tpetra/Teko_TpetraBlockedMappingStrategy.hpp

I've observed that `Teko::TpetraHelpers::BlockedTpetraOperator::RebuildOps` is slow in comparison to the other steps in a Teko preconditioner.
For example, consider the following benchmarking code.
```cpp
auto dof_block_gids = ...;
auto dof_blocked_matrix =
Teuchos::rcp(new Teko::TpetraHelpers::BlockedTpetraOperator(dof_block_gids, A));
constexpr int ntrials = 10;
const auto tStart = MPI_Wtime();
for (int i = 0; i < ntrials; ++i)
{
dof_blocked_matrix->RebuildOps();
}
const auto tElapsed = MPI_Wtime() - tStart;
std::cout << "time per trial: " << tElapsed / ntrials << "\n";
```
For a 57,640 DOF system with 4,135,524 nnz and 15 subblocks takes 0.88s per `RebuildOps` call.
This PR reduces that time to 0.074s per call.

Teko: Improve Tpetra subblock re-assembly performance

---

cmake/tribits/core/std_tpls/FindTPLMPI.cmake

This returns backwards compatibility for how MPI is found (see #13839) that was caused by #13840.  If you want to use `find_package(MPI)` by default, you can configure Trilinos is with `-D MPI_ALLOW_PACKAGE_PREFIND=TRUE`.
See commit log messages for more details.
Addresses #13839

Set MPI_ALLOW_PACKAGE_PREFIND=FALSE by default (#13839)

---

RELEASE_NOTES

First pass for release 16.1.
https://github.com/trilinos/Trilinos/pulls?q=is%3Apr+is%3Aclosed+label%3A%2216.1+release+note%22
@ccober6 @rppawlo @jhux2 @mperego @sebrowne Please add/remove items as you see fit.
Ideally, we will be ready to merge this before 3/15 COB.

Adding to release notes for 16.1

---

packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp

A couple of fixes:
1. remove the duplication of ids in ownedPlusSharedGIDs. It was being filled with owned nodes and shared nodes. But shared nodes include shared-and-owned as well as shared-but-not-owned. So now it only contains owned and shared-but-not-owned.
2. The nnzPerRow array being given to FECrsGraph was the same length as the ownedMap, but is now the same length as the ownedPlusSharedMap. This allows the example to run correctly in parallel.
Also streamlined some of the stk usage.

Update the stk poisson example.

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_def.hpp
packages/tpetra/core/test/CrsMatrix/CMakeLists.txt
packages/tpetra/core/test/CrsMatrix/CrsMatrix_getLocalDiagCopy.cpp

Adding a new unit-test that covers code path for fillComplete and fillActive states. The code paths that handled both these cases is now merged and follows the fillComplete case as a staticCrsGraph is assumed when calling getLocalDiagCopy.
After integration of Kokkos 4.4 the host backend is enforcing more thread safety especially around view creation/allocation. This eventually leads to a hang in CrsMatrix::getLocalDiagCopy when the Matrix is fillActive.
* Closes #13498 
SPARC is using this feature
A new test: CrsMatrix_getLocalDiagCopy is testing both isFillActive == true and == false cases.
The test hangs with a fillActive matrix before this PR

Tpetra: CrsMatrix getLocalDiagCopy hang, see issue #13498

---

packages/framework/ini-files/config-specs.ini

Discussed with @cgcgcg and @rppawlo.  Decided to disable this test for now, will reevaluate later.  It is failing reliably in our containerized CI runs on 2xA100 machines.
This disables the single reliably-failing Panzer test for the new CI A100 configuration (required to move to AT2).

Panzer: Disable failing test

---

packages/thyra/adapters/tpetra/src/Thyra_TpetraLinearOp_def.hpp

@trilinos/thyra
I commented out a fence in the Thyra-Tpetra adapter since it doesn't make sense to me. Let's see if the AT thinks that it was actually necessary.

Thyra: Comment out fence in Tpetra operator apply

---

packages/seacas/libraries/exodus/src/ex_utils.c

* Protect the calling of a function that was not introduced until after netCDF 4.4.  This is causing a link failure in codes that are using older versions of netCDF
* Closes #13898

EXODUS: Protect use of function not introduced until 4.4.1

---

cmake/SimpleTesting/README.md
cmake/SimpleTesting/cmake/ctest-common.cmake
cmake/SimpleTesting/cmake/ctest-functions.cmake
cmake/SimpleTesting/cmake/ctest-stage-configure.cmake
cmake/SimpleTesting/cmake/ctest-stage-test.cmake
packages/framework/pr_tools/PullRequestLinuxDriver.sh
packages/framework/pr_tools/PullRequestLinuxDriverTest.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py
packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py
packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py

Note that I also did some misc. cleanup on the PR script option handling (having to run it manually for this process pointed out some issues) and cleaned up an unused code path in the SimpleTesting logic.
If a submission to CDash fails, that's a bummer, but it does not on its own need to halt the ability to merge a PR.  That can be handled by the exit status of the configure/build/test.
Affected https://github.com/trilinos/Trilinos/pull/13804
JIRA issue: https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-704
I set the CDash upload URL to something invalid in an attempt to induce a submission error, and was successful.  The old code propagated a bad exit value, the new code is zero.

Framework: Ignore ctest submit errors

---

packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp
packages/shylu/shylu_node/basker/src/shylubasker_types.hpp

This PR tries to fix ShyLU-Basker's error-handling issues which cause deadlock when called with multiple MPIs.
- it also added an 'Amesos2' parameter to turn on/off replace-zero-pivots

ShyLU-Basker : error handling

---

cmake/get-tribits-mainline-merge-commits.sh
cmake/tribits/CHANGELOG.md
cmake/tribits/core/common/TribitsCMakePolicies.cmake
cmake/tribits/examples/RawHelloWorld/CMakeLists.txt
cmake/update-tribits-snapshot.sh
demos/simpleBuildAgainstTrilinos/CMakeLists.by_package.cmake
demos/simpleBuildAgainstTrilinos/CMakeLists.txt
packages/TrilinosInstallTests/find_package_Trilinos/CMakeLists.txt

CC: @sebrowne 
Addresses:
* #13731
This PR contains some commits that allow Trilinos to configure, build, and pass (all but 3) tests for the a recent version of CMake 4.0 on the 4.0 release branch (after the merge of [CMake MR 10489](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/10489)).
I installed CMake `v4.0.0-rc4-34-g68475b77d2` (called `v4.0.0-rc4-g68475b77d2` by `cmake --version`) by locally (see details below on how that was installed) and did a configure and `make dashboard` to submit to:
* https://trilinos-cdash-qual.sandia.gov/index.php?project=Trilinos&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=cee-build030&field2=buildname&compare2=61&value2=clang-instru-coverage&field3=buildstamp&compare3=61&value3=20250321-1930-Experimental …

Port Trilinos to CMake 4.0.0 (#13731)

---

.github/workflows/AT2.yml
.github/workflows/codeql.yml
.github/workflows/spack.yml

Branch specifications limited the scope that these workflows could run on. (i.e. Release branch PR testing) This results in an inconsistent testing environment for PR targeting a non-master/develop branch.
Noticed in the following PR
- #13889

Framework: Remove target branch limitations for AT2 workflows

---

.github/workflows/AT2.yml

Add files to artifacts that will help reproduce PR CI runs.  It doesn't appear that we're having any space issues so far, so adding a few small test files should be okay.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-703

Framework: Add artifacts to help with reproducing runs

---

packages/teko/src/Tpetra/Teko_BlockingTpetra.cpp

On GPU platforms, https://github.com/trilinos/Trilinos/pull/13843 is still not sufficient to get good sub-block reassembly times.
Using the same benchmarking code, but now also measuring the initial sub-block assembly times:
```cpp
auto dof_block_gids = ...;
auto dof_blocked_matrix =
Teuchos::rcp(new Teko::TpetraHelpers::BlockedTpetraOperator(dof_block_gids, A));
{
constexpr int ntrials = 10;
const auto tStart = MPI_Wtime();
for (int i = 0; i < ntrials; ++i)
{
dof_blocked_matrix = Teuchos::rcp(new Teko::TpetraHelpers::BlockedTpetraOperator(dof_block_gids, A));
}
const auto tElapsed = MPI_Wtime() - tStart;
std::cout << "time per trial, assembly: " << tElapsed / ntrials << "\n";
EXPECT_TRUE(dof_blocked_matrix->testAgainstFullOperator(100, tol));
}
{
constexpr int ntrials = 10;
const auto …
```

Teko: Perform as much of the sub-block reassembly operation on the device as possible

---

.github/workflows/AT2.yml

As a Trilinos Framework member, I want to output ccache stats for each AT2 job to monitor ccache usage for each build.
- [TRILFRAME-692](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-692)

Framework: Add ccache stats output to AT2 jobs

---

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_Details_determineLocalTriangularStructure.hpp
packages/tpetra/core/src/Tpetra_Details_getGraphDiagOffsets_decl.hpp
packages/tpetra/core/src/Tpetra_Details_getGraphDiagOffsets_def.hpp
packages/tpetra/core/src/Tpetra_Details_getGraphOffRankOffsets_decl.hpp
packages/tpetra/core/src/Tpetra_Details_getGraphOffRankOffsets_def.hpp
packages/tpetra/core/src/Tpetra_Details_getNumDiags.hpp
packages/tpetra/core/test/CrsGraph/DetermineLocalTriangularStructure.cpp
packages/tpetra/core/test/Utils/TpetraUtils_WrappedDualView.cpp
packages/tpetra/core/test/Utils/TpetraUtils_WrappedDualViewFixture.hpp
packages/tpetra/core/test/Utils/TpetraUtils_WrappedDualViewMicrobench.cpp

It's deprecated in Kokkos and adopted by Kokkos Kernels

Tpetra: Kokkos::StaticCrsGraph -> KokkosSparse::StaticCrsGraph

---

packages/framework/ini-files/config-specs.ini

Want to avoid test timeouts in CI.
[Here](https://sems-cdash-son.sandia.gov/cdash/index.php?project=Trilinos&date=2025-04-01&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda&field2=groupname&compare2=63&value2=Pull) are the relevant failures that I've seen recently in the new AT2-based CUDA builds:

Framework: Update list of tests to run serially with CUDA

---

packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp
packages/belos/tpetra/example/BlockGmres/BlockGmresTpetraGaleriEx.cpp
packages/belos/tpetra/example/SolverFactory/SolverFactoryTpetraGaleriEx.cpp
packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
packages/ifpack2/src/Ifpack2_IlukGraph.hpp
packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
packages/ifpack2/src/Ifpack2_RILUK_def.hpp
packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestChebyshev2.cpp

Avoid some deprecation warnings.

Ifpack2: Change namespace for symbols that Kokkos-Kernels moved out of Experimental

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp

Fixes a compile error when Tpetra is configured with `Tpetra_ENABLE_MMM_Timings=ON`.

Tpetra: Fix leftover from switch to profiling regions

---

packages/xpetra/src/CrsGraph/Xpetra_CrsGraph.hpp
packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp

Xpetra: Use Kokkos-Kernels include instead of deprecated Kokkos header

---

cmake/SimpleTesting/cmake/ctest-common.cmake

Want to have a more comprehensive look at how many warnings are in Trilinos packages.
This will allow for a better overall view as to the state of current warnings work (e.g. how many packages have shadow warnings).
https://github.com/trilinos/Trilinos/issues/11497

Framework: Increase warning limit

---

packages/muelu/src/Operators/MueLu_MultiPhys_decl.hpp
packages/muelu/src/Operators/MueLu_MultiPhys_def.hpp

This adds material property information for the individual subblocks in the `MultiPhys` class.

MueLu: Add material vector information into MueLu multiphysics class

---

packages/tpetra/core/CMakeLists.txt
packages/tpetra/core/cmake/TpetraCore_config.h.in
packages/tpetra/core/src/Tpetra_Details_DistributorActor.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorPlan.hpp
packages/tpetra/core/src/Tpetra_Distributor.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_getLocalDiagCopy.cpp
packages/tpetra/core/test/Distributor/Distributor_UnitTests.cpp

Start work on splitting the posting of recvs and sends. The goal is to post recvs, then launch packing kernels and then post sends. This should result in less copies within MPI since the likelihood of unexpected messages is decreased.
What this PR does:
- Remove the duplication between 3 argument and 4-argument variants of `doPosts`. The difference between the code paths was how the offsets are computed, but everything else is the same. The offset computation is now in the overloaded `getImportViewLimits`, `getExportViewLimits` methods.
- Split into `doPostRecvs` and `doPostSends`. Currently nothing outside of the `DistributorActor` calls these methods, but rather the now trivial `doPosts`.
- Remove `Tpetra_ENABLE_Distributor_Timings` and replace the corresponding timers …

Tpetra DistributorActor: Split Recvs and Sends

---

packages/muelu/src/Operators/MueLu_MultiPhys_decl.hpp
packages/muelu/src/Operators/MueLu_MultiPhys_def.hpp

Motivation:
I have a use-case where I construct a custom block Jacobi smoother where, for each diagonal subblock, I use the smoother from the subblock level AMG setup.

MueLu: Add optional OmitSubblockSmoother argument to MultiPhys class

---

packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_decl.hpp
packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp

@trilinos/ifpack2 @vdq8a @GaleAxiom @romintomasetti 
Fixes #13970.

Ifpack2: Ifpack2: local trsv cusparse spec selector missing impl_scalar_type (fixes #13970)

---

.github/workflows/AT2.yml
packages/framework/ini-files/config-specs.ini

Want to add a configuration and PR test for OneAPI-2024 (required for new Kokkos 4.6).
#13878 
Testing shows the following tests failing (mostly due to numerical tolerances, but the Intrepid2 ones may be because of Intel MKL):
```
The following tests FAILED:
266 - Sacado_GTestSuite_MPI_1 (Failed)                  Sacado
637 - Zoltan_ch_simple_zoltan_parallel (Failed)         Zoltan
1541 - Ifpack2_MTGS_belos_MPI_1 (Failed)                 Ifpack2
1542 - Ifpack2_MTSGS_belos_MPI_1 (Failed)                Ifpack2
1544 - Ifpack2_MTGS_belos_muelu_MPI_4 (Failed)           Ifpack2
1572 - Ifpack2_SGSMT_compare_with_Jacobi_MPI_4 (Failed)  Ifpack2
2040 - Intrepid2_unit-test_Orientation_test_orientation_PYR_QuadFace_newBasis_Serial_DOUBLE_MPI_1 (Failed) Intrepid2
2041 - …
```

Framework: Add OneAPI PR build

---

packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp
packages/muelu/src/Utils/MueLu_Utilities.cpp

When using blocked structure within MueLu it is convenient to pass the null space candidates as "user data" when using MueLu with Stratimikos.
* #7929

MueLu: Add support for "Nullspace[1-9]" user data input

---

packages/phalanx/example/FiniteElementAssembly/LinearObjectFactory.hpp
packages/phalanx/example/FiniteElementAssembly/PrintValues.hpp
packages/phalanx/example/FiniteElementAssembly/auxiliary_tests/Example_FEM_LinearObjectFactory_AuxTest.cpp
packages/phalanx/test/Field/MDField_Runtime.cpp
packages/phalanx/test/Kokkos/tKokkos.cpp

- This removes use of bracket operator in DynRankView for rank greater than 1. See https://github.com/kokkos/kokkos/pull/7457. Phalanx implemented this due to requirements in intrepid2.
- Fix for moving CrsGraph and CrsMatrix from Kokkos to KokkosSparse.
Multiple tests covered the deprecations and are updated for changes.

Phalanx: fix use of deprecated kokkos 4 code

---

packages/framework/ini-files/config-specs.ini
packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HDIV_PYR.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_PyramidCoords.hpp
packages/intrepid2/src/Shared/Intrepid2_PointToolsDef.hpp
packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp
packages/intrepid2/unit-test/Orientation/test_orientation_PYR_QuadFace_newBasis.hpp
packages/intrepid2/unit-test/Orientation/test_orientation_PYR_TriFace_newBasis.hpp

Intrepid2: Fix #13945
This PR addresses both #13945 and a number of issues with the H(div) pyramid basis and tests against it revealed in the course of fixing the test failures.
#13881 
Closes #13945 
@sebrowne I have confirmed in the context of the Docker container referred to in #13881 that these changes allow the PYR_QuadFace, PYR_TriFace orientation tests to be re-enabled (i.e., they pass there).

Intrepid2: fix 13945 (MKL Failures PYR_QuadFace, PYR_TriFace)

---

packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp
packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyBasis.hpp
packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHCURL.hpp
packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHGRAD.hpp
packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefL2.hpp
packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefContractions.hpp
packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefDot.hpp
packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefTensor.hpp
packages/intrepid2/src/Shared/Intrepid2_Kernels.hpp
packages/intrepid2/src/Shared/Intrepid2_RealSpaceToolsDef.hpp
packages/intrepid2/unit-test/MonolithicExecutable/AnalyticPolynomialsMatchTests.cpp
packages/intrepid2/unit-test/MonolithicExecutable/TensorViewFunctorTests.cpp
packages/intrepid2/unit-test/Shared/RealSpaceTools/test_01.hpp

This PR uses the `access` method to access Dynamic Rank Views with more indices than the view rank.
Accessing views using the `operator()` with more indices than the view rank will soon result in a runtime error in debug mode

Intrepid2: use "access" for accessing DynRankView

---

packages/panzer/adapters-stk/cmake/Dependencies.cmake
packages/panzer/adapters-stk/src/Panzer_STKConnManager.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
packages/panzer/adapters-stk/test/stk_interface_test/tLineMeshFactory.cpp

Large scale runs were seeing excessive communication during mesh construction.
All functions are exercised in the adapters-stk tests.

Panzer: improve mpi communication in mesh initialization

---

.github/workflows/cdash_urls.yml

@trilinos/framework @sebrowne @achauphan 
The URL to the CDash with build results is somewhat hidden and only becomes available once the first build finishes.
With this change a comment is added to newly opened PRs with the link to the results.
It seems to be somewhat tricky to get the comment to work for PRs from forks when the trigger is `pull_request`. Instead, I now use `pull_request_target`. This means that the action will only run if the workflow file is in the target of the PR (i.e. usually `develop`).
I tested this by opening a dummy PR against the branch of this PR: https://github.com/trilinos/Trilinos/pull/13981

Add comment with CDash urls to PRs

---

packages/framework/ini-files/config-specs.ini

When looking at CI failures in #13985, @gsjaardema observed the following configure error with the cuda11 check:
```
CMake Error at cmake/tribits/core/package_arch/TribitsAdjustPackageEnables.cmake:1010 (message):
***
*** ERROR: Setting Trilinos_ENABLE_SEACASExo2mat=OFF which was 'ON' because SEACASExo2mat has a required library dependence on disabled package Matio!
***
```
This error should not have happened with our current configuration, because we set `Trilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES` to `ON` in `config-specs.ini`.  However, that config block was not getting included in this particular configuration.  Much like I did with the Intel check configuration, this change makes the rest of our container config blocks adopt a "common" ish syntax, which …

Framework: Uniformize container configs

---

packages/panzer/adapters-stk/src/Panzer_STK_SetupUtilities.cpp

ORNL team was seeing issues with internal sidesets.
The workset builder was failing to collect all elements/sides for an interior bc if the face/edge was owned by a different mpi process than the cell.
Closes #13717 
ORNL team verified this change fixes their issue.
A unit test is under development and will be added this week in a separate PR.

Panzer: fix interior bc issue

---

packages/teko/src/Teko_AdaptivePreconditionerFactory.cpp
packages/teko/src/Teko_AdaptivePreconditionerFactory.hpp
packages/teko/src/Teko_PreconditionerFactory.cpp
packages/teko/tests/CMakeLists.txt
packages/teko/tests/unit_tests/tAdaptivePreconditionerFactory.cpp

This adds a feature in Teko to use an adaptive sub-block solver.
If the relative residual is larger than a user-specified constant, $`\dfrac{\vert\vert b - A M_A^{-1} b\vert\vert}{\vert\vert b\vert\vert} > \varepsilon`$, then the next preconditioner/solver in the sequence is used. After a user specified number of steps, the adaptive sub-block solver transitions back to the initial solver.
Example input:
```xml
<ParameterList name="temperature_solver">
<Parameter name="Type" type="string" value="Adaptive"/>
<Parameter name="Target Residual Reduction" type="double" value="0.1"/>
<Parameter name="Inverse Type 1" type="string" value="gmres"/>
<Parameter name="Preconditioner Type 1" type="string" value="dd_0_ilu_0_pc"/>
<Parameter name="Inverse Type 2" type="string" value="gmres"/>
<Parameter …
```

Teko: Add adaptive sub-block solver option

---

.github/workflows/AT2.yml

@rppawlo noticed when trying to reproduce some CI failures that `packageEnables.cmake` was not included in the artifacts.  Remedy that by running the copy artifacts step even if the previous step fails.

Framework: Always copy ci artifacts

---

packages/nox/src/NOX_Solver_SingleStep.C
packages/nox/src/NOX_Solver_SingleStep.H

@trilinos/nox @rppawlo 
The current implementation of `NOX::Solver::SingleStep` is dependent on the behavior of `getNewton()` method of a particular group. The call to `getNewton()` throws an exception for certain groups if they check that the Newton vector has been computed prior to the corresponding call. Surprisingly, not all groups do this: `NOX::Epetra::Group` and `NOX::Petsc::Group` have this check (i.e. may throw an exception), but `NOX::Thyra::Group` and `NOX::LAPACK::Group` simply return the vector with no checks performed. The proposed modification makes `NOX::Solver::SingleStep` independent from this implementation detail.
* Closes #14016

NOX: Make `Solver::SingleStep` independent on the group's `getNewton()` implementation

---

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_checkLaunchBlocking.hpp
packages/tpetra/core/src/Tpetra_Details_crsMatrixAssembleElement.hpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_decl.hpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp

Compatibility updates to resolve compilation errors when setting `Kokkos_ENABLE_DEPRECATED_CODE_4=OFF`
* call `concurrency()` as non-static member function , see https://github.com/kokkos/kokkos/issues/5655
* replace `Kokkos::atomic_assign` with `Kokkos::atomic_store` , see https://github.com/kokkos/kokkos/pull/7458
* drop `volatile` qualifier , no longer needed see https://github.com/kokkos/kokkos/pull/5412
* also see https://github.com/kokkos/kokkos/issues/4077, https://github.com/kokkos/kokkos/pull/4931, https://github.com/kokkos/kokkos/issues/1554, https://github.com/kokkos/kokkos/issues/5194, https://github.com/kokkos/kokkos/pull/5215
* update DualView interface (type) used in `unpackAndCombineIntoCrsArrays` function input args , see …

Tpetra: updates for disabled kokkos deprecated code

---

packages/ifpack2/src/Ifpack2_BlockComputeResidualAndSolve.hpp
packages/ifpack2/src/Ifpack2_BlockHelper.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

More performant paths for block Jacobi case inside BTDS (GPU only, BlockCrs only).
- Fuses residual and diagonal solve into one kernel
- Inverts diagonal blocks completely in shared memory before writing them back out. This would double the shared mem requirement per team, so to compensate the vector length is halved.
Compared to #13805, this gives between 9% (bs = 7) and 33% (bs = 11) speedup on the overall solve and about 1.9x speedup in numeric setup for both block sizes. **Note:** this was measured on a single GPU run, so the speedup only applies to local computation. Multi-rank runs will speed up less due to time spent doing communication.
Follows #13805
Will ask SPARC team to evaluate.
Tested in Ifpack2_BlockTriDiContainerUnitAndPerfTests, and ran this on OpenMP, …

Ifpack2: Fused block jacobi

---

.github/workflows/per-commit.yml
commonTools/test/utilities/check-not-modify-legacy-packages.sh

Discussed with operational leadership yesterday and a desire to prohibit changes to deprecated packages was expressed.  Commits that change deprecated (soon to-be deleted packages) should be flagged for additional scrutiny, and prohibited by default.

Framework: Add a new check to prevent changing deprecated packages

---

packages/nox/src/NOX_Solver_SingleStep.C

@trilinos/nox @rppawlo
This division results in UB if `normF_0=0`. Normally, if that happens, this means that the user has made a mistake setting up his numerical model. A particular user code that uses `NOX::Solver::SingleStep` could probably provide a meaningful output on this, but it may have no chance to do so since the program may silently die when trying to be the output inside `NOX::Solver::SingleStep::printUpdate()`.

[NOX] Check for a zero denominator when computing relative norm in `NOX::Solver::SingleStep`

---

packages/galeri/src-xpetra/Galeri_XpetraMatrixTypes.hpp

As the title states, as gcc 13.3.0 complains. Other stencil types already do it the same way.

Galeri: Silence compiler warnings

---

packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp
packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
packages/tpetra/core/src/Tpetra_Details_DistributorActor.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_Distributor.cpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
packages/tpetra/core/test/CrsMatrix/Bug8794.cpp

The order of steps for `beginTransfer` and `endTransfer` is:
- `copyAndPermute`
- `packAndPrepare`
- `doPost`
- `doWaitsRecvs`
- `unpackAndCombine`
- `doWaitsSend`
After splitting `DistributorActor::doPosts` into `doPostRecvs` and `doPostSends` in PR #13934, this PR allows to reorder the steps as follows:
- `doPostRecvs`
- `packAndPrepare`
- `doPostSends`
- `copyAndPermute`
- `doWaitsRecvs`
- `unpackAndCombine`
- `doWaitsSend`
The motivation for this is to decrease the number of unexpected messages that MPI sees by separating receives and sends and to allows MPI to make progress while local work is performed. The new behavior can be enabled by setting the environment variable `TPETRA_GRANULAR_TRANSFERS=ON`. By default this behavior is off.

Tpetra: Reorder operations in transfer

---

packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorPlan.hpp
packages/tpetra/core/src/Tpetra_Distributor.cpp
packages/tpetra/core/src/Tpetra_Distributor.hpp

* Makes `TPETRA_DEFAULT_SEND_TYPE` accept a string rather than an int.
* Adds `Tpetra::Details::distributorSendTypes`.
* Deprecates `Tpetra::distributorSendTypes`. I think this should have always been in `Details` anyway, since it interacts with some enums in `Details`.
Also:
* all valid send type enums were generated in two places. Consolidated to a common function.
Fix for https://github.com/trilinos/Trilinos/issues/14115

accept `TPETRA_DEFAULT_SEND_TYPE` behavior as string

---

packages/teko/src/Tpetra/Teko_TpetraBlockedMappingStrategy.cpp
packages/teko/tests/src/Tpetra/tBlockedTpetraOperator.cpp

Essentially forgot to avoid the import/export since we no longer need to map noncontig vectors to contig vectors.

Teko: Fix import/export bug related to single block Teko assembly

---

packages/tpetra/core/src/Tpetra_Distributor.cpp

Not sure why my compiler complained about it, but not the autotester.
```
/workspace/trilinos/source/packages/tpetra/core/src/Tpetra_Distributor.cpp: In member function 'virtual Teuchos::RCP<const Teuchos::ParameterList> Tpetra::Distributor::getValidParameters() const':
/workspace/trilinos/source/packages/tpetra/core/src/Tpetra_Distributor.cpp:162:36: error: 'distributorSendTypes' was not declared in this scope; did you mean 'Tpetra::Details::distributorSendTypes'?
162 |     Array<std::string> sendTypes = distributorSendTypes ();
|                                    ^~~~~~~~~~~~~~~~~~~~
|                                    Tpetra::Details::distributorSendTypes
In file included from /workspace/trilinos/source/packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp:14, …
```

Tpetra: Add missing namespace

---

packages/pliris/src/x_factor.c
packages/pliris/src/xlu_solve_new.c

@trilinos/pliris
This is the default C standard for GCC 15 - see also
https://gcc.gnu.org/gcc-15/porting_to.html#c23-fn-decls-without-parameters
* N/A
N/A
Not sure how to do this in this context.

Make Pliris compatible with C23.

---

doc/build_ref/TrilinosBuildReferenceTemplate.rst

Removing old and no longer supported Kokkos configuration options. Point to Kokkos build guide and modify table to reflect equivalency between Trilinos and Kokkos options.
Keeping the documentation up to date.
Related to issue #14057 
* Closes #14057

Documentation: updating and cleaning the build guide.

---

packages/tpetra/core/src/Tpetra_Details_DistributorActor.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp

Removes an opportunity to make a mistake

Tpetra: `default` the DistributorActor copy-ctor

---

packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp
packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp

On host the fused kernel is clearly beneficial so we pick that implementation by default, while on GPU the TPLs are faster so we go with Kokkos Kernels implementation.
A performance regression has been observed on CTS-2 machines after the merge of PR #14124 this change should bring back performance on CPU while keeping the improvements on GPU.
No related issue
Tested on Blake

Ifpack2: Chebyshev Kernel spmv heuristic

---

packages/muelu/test/scaling/CMakeLists.txt
packages/muelu/test/scaling/Driver.cpp

When running the MueLu driver with reruns > 1, one encounters:
```
Number of iterations performed for this solve: 231
SUCCESS:  Belos converged!
p=0: *** Caught standard std::exception of type 'std::runtime_error' :
/scratch/malphil/trilinos-devel/Trilinos/packages/teuchos/comm/src/Teuchos_StackedTimer.cpp:28:
Throw number = 1
Throw test that evaluated to true: true
Base_Timer:stop Failed timer not running
```
This PR fixes that issue. Thanks, @cgcgcg!

Fix multiple reruns in the MueLu Driver

---

packages/seacas/libraries/ioss/src/Ioss_Map.C
packages/seacas/libraries/ioss/src/Ioss_Version.h

Minor fix to previous refactor of global_to_local parallel error reporting.  There was an unintended change in behavior in the previous changes.  This has been remedied.
All sierra tests now pass.  One test showed the incorrect behavior and it now passes.

IOSS: Fix map error reporting refactor; update version

---

packages/muelu/src/Graph/MatrixTransformation/MueLu_ClassicalDropping.hpp
packages/muelu/src/Graph/MatrixTransformation/MueLu_DistanceLaplacianDropping.hpp
packages/muelu/test/unit_tests_kokkos/CoalesceDropFactory_kokkos.cpp

The distance Laplacian has off-diagonal entries $-1/d(x,y)^2$, not $1/d(x,y)^2$. This matters for criteria that take the sign into account...

MueLu: Fix another sign error in RS distance Laplacian

---

packages/sacado/src/new_design/Sacado_Fad_Exp_StaticFixedStorage.hpp

This reverts commit 5fdfeb46f0bb9507d95fc5100cefc56c87928b77.
The original commit broke the ability to wrap SFad<> with a Kokkos view. View storage begins with dx_ so it makes sense for SFad<> to follow the same ordering:
https://github.com/trilinos/Trilinos/blob/develop/packages/sacado/src/new_design/Sacado_Fad_Exp_ViewStorage.hpp#L82
This change was made to work around a compiler bug for a machine we no longer support so it should be okay to revert.

Sacado: Revert "Sacado:  Reorder SFad<> val and dx fields for stria"

---

packages/amesos2/src/Amesos2_TpetraCrsMatrix_MatrixAdapter_def.hpp

Remove shadow warnings before turning shadow warnings on in framework.
* Closes 14233

Amesos2:  Removed repeated typedef to remove shadow warning.

---

packages/zoltan/src/lb/lb_init.c
packages/zoltan/src/zz/zz_gen_files.c

Removed 3 declarations to remove 3 shadow warnings.
Cleaning up shadow warnings before turning shadow warnings on in framework.
* Closes 14228

Zoltan:  Shadow warnings

---

packages/pamgen/mesh_spec_lt/pamgen_mesh_specification.C
packages/pamgen/src/inline_mesh_desc.C
packages/pamgen/src/inline_mesh_desc.h

Removed repeated typedef in first file.
Added P in front of private part of class in second and third files..
@trilinos/pamgen 
Removing shadow warnings before turning those warnings on in framework.
* Closes 14230

Pamgen:  Changes to remove shadow warnings.

---

packages/tpetra/core/src/CMakeLists.txt
packages/tpetra/core/src/Tpetra_Details_DistributorActor.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorPlan.hpp
packages/tpetra/core/src/Tpetra_Details_Ialltofewv.cpp
packages/tpetra/core/src/Tpetra_Details_Ialltofewv.hpp
packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_Distributor.cpp
packages/tpetra/core/test/ImportExport2/CMakeLists.txt

This introduces an opt-in MPI-based implementation for all-to-few communication patterns, enabled via the `"Ialltofewv"` send type. The implementation uses Kokkos to support GPU-aware MPI.
FYI @searhein
This implementation has been demonstrated to speed up all-to-one and all-to-few communication patterns by several orders of magnitude under certain configurations:
This is a CPU run on Broadwell using MPICH. Groups of bar graphs are 144, 256, 512, and 1024 ranks.
The left-most bar of each group is upstream Trilinos. The right-most bar uses this new implementation (the middle bar can be ignored).
Another CPU run on Sapphire Rapids using MPICH. Groups of bar graphs are 128, 256, 512, and 1025 nodes.
"Ialltofewv" is this implementation. "naive" is a combination of MPI_Isend …

Tpetra: Add "Ialltofewv" send type

---

packages/panzer/adapters-stk/example/main_driver/CMakeLists.txt
packages/panzer/adapters-stk/example/main_driver/energy-load-cell-data.xml
packages/panzer/adapters-stk/example/main_driver/main_driver.cpp
packages/panzer/adapters-stk/example/main_driver/user_app_ClosureModel_Factory_STK.hpp
packages/panzer/adapters-stk/example/main_driver/user_app_ClosureModel_Factory_STK_TemplateBuilder.hpp
packages/panzer/adapters-stk/example/main_driver/user_app_ClosureModel_Factory_STK_impl.hpp
packages/panzer/adapters-stk/example/main_driver/write_exodus_initial_condition.cpp
packages/panzer/adapters-stk/src/Panzer_STK_MeshAccessor.hpp
packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory.hpp
packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory_impl.hpp
packages/panzer/adapters-stk/src/evaluators/Panzer_STK_GatherExodusCellDataToIP.cpp
packages/panzer/adapters-stk/src/evaluators/Panzer_STK_GatherExodusCellDataToIP.hpp
packages/panzer/adapters-stk/src/evaluators/Panzer_STK_GatherExodusCellDataToIP_impl.hpp
packages/panzer/disc-fe/src/Panzer_ClosureModel_Factory_TemplateManager.hpp
packages/panzer/disc-fe/test/closure_model/user_app_ClosureModel_Factory_impl.hpp
packages/panzer/disc-fe/test/closure_model/user_app_InitialConditionEvaluator.hpp

Application requires that extra fields stored in the exodus restart file be available in assembly DAG. Added evaluator and factory to support this use case for scalars that are constant in each cell.
Addresses the issue
New test added to adapters-stk/example/main_driver/energy-load-cell-data.xml

Panzer: load exodus cell data for auxiliary fields

---

packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest_MaskTraits.cpp

C++20 considers additional permutations for comparison operators that caused a compile error due to ambiguity. This seems to avoid that.

Stokhos: Fix compile error due to ambiguous operator==

---

packages/galeri/src-xpetra/Galeri_MapTraits.hpp

@trilinos/galeri
I end up hitting compilation errors like:
```
[ 72%] Building CXX object packages/belos/tpetra/example/SolverFactory/CMakeFiles/Belos_SolverFactory_Tpetra_Galeri_Ex.dir/SolverFactoryTpetraGaleriEx.cpp.o
In file included from /tscratch/malphil/muelu-weak-scaling-solid-voltage/Trilinos/packages/galeri/src-xpetra/Galeri_XpetraCartesian.hpp:19,
from /tscratch/malphil/muelu-weak-scaling-solid-voltage/Trilinos/packages/galeri/src-xpetra/Galeri_XpetraMaps.hpp:31,
from /tscratch/malphil/muelu-weak-scaling-solid-voltage/Trilinos/packages/belos/tpetra/example/SolverFactory/SolverFactoryTpetraGaleriEx.cpp:17:
/tscratch/malphil/muelu-weak-scaling-solid-voltage/Trilinos/packages/galeri/src-xpetra/Galeri_MapTraits.hpp: In instantiation of 'static …
```

Galeri: Resolve compilation error in Galeri_MatpTraits.hpp

---

packages/framework/pr_tools/PullRequestLinuxDriver.sh

#14210 updated our `ctest-driver` to use a different `CTest` function for coverage collection and processing with `gcov`. Manual reproduction of those changes resulted in coverage result posting properly to CDash. However, any automated job that configured ccache, failed to replicate the manual result.
The issue is with the ccache variable `CCACHE_BASEDIR` and `gcov`:
- https://gitlab.kitware.com/cmake/cmake/-/issues/21138
This PR attempts to resolve this issue by just not using ccache for the coverage build perform with our Nightly process. Since these jobs run at a time with less congestion, the wall time increase from not using ccache should be fine.
- [TRILFRAME-23](https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-23)
These changes were tested and …

Framework: Skip ccache configuration when performing coverage build

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/MueCentral/MueLu_MasterList.cpp

Change the default value of "fuse prolongation and update" to `true`.
https://github.com/trilinos/Trilinos/blob/12e921ffd3a8ff0791269788d106deb39bba0237/packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp#L1103-L1113

MueLu: Change default value of "fuse prolongation and update"

---

packages/galeri/src-xpetra/Galeri_XpetraUtils.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp
packages/tpetra/core/src/Tpetra_Map_decl.hpp
packages/tpetra/core/src/Tpetra_Map_def.hpp

@trilinos/tpetra @trilinos/galeri @trilinos/muelu @trilinos/ifpack2 
- Galeri: Skip unneeded call to `getLocalElementList`.
- Tpetra: Run `locallySameAs` on device.
- MueLu: Use Tpetra method in `MapsAreNested`, don't construct importer in `GetOverlappedDiagonal` on single rank
- Ifpack2: Fix bug in `BlockTriDiContainer::peformSymbolicPhase`

Tpetra, Galeri, MueLu, Ifpack2: Small performance improvements

---

packages/tpetra/core/src/Tpetra_Details_DistributorActor.cpp
packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp

From this:
```
Tpetra::Distributor: doPostsIalltofewvImpl
Tpetra::Distributor: doWaitsIalltofewv
```
To this (the way other labels are)
```
Tpetra::Distributor::doPostsIalltofewvImpl
Tpetra::Distributor::doWaitsIalltofewv
```

Tpetra: standardize ialltofewv profiling labels

---

packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/args.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/base.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/chrono.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/color.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/compile.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/format-inl.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/format.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/os.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/ostream.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/printf.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/ranges.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/std.h
packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/xchar.h

Older version of lib::fmt was not building using latest ROCM-7.0 release.  See https://github.com/sandialabs/seacas/issues/573
https://github.com/sandialabs/seacas/issues/573
@jjellio Tested the build on LLNL RZ using ROCM-7.0

Seacas update embedded fmt to 11.2.0

---

.github/workflows/AT2.yml

Accidentally updated the dashboard build name of the non-uvm AT2 cuda build to indicate that it was a uvm enabled build. Reverted that change and update the correct dashboard build name for the uvm-enabled AT2 cuda build.
- #14358

Framework: Fix AutoTester2 cuda-uvm CDash build name

---

packages/muelu/example/basic/Stratimikos.cpp
packages/muelu/src/Graph/MueLu_AggregationAlgorithmBase.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_decl.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_def.hpp
packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp

This avoids issues when phases are skipped on some ranks because all nodes are already aggregated.

MueLu UncoupledAggregationFactory: Perform communication in setup routine

---

packages/belos/kokkos/src/BelosKokkosAdapter.hpp
packages/belos/tpetra/test/BiCGStab/test_bicgstab_diag.cpp
packages/belos/tpetra/test/BlockGmres/test_bl_gmres_diag.cpp
packages/belos/tpetra/test/MINRES/test_minres_diag.cpp
packages/belos/tpetra/test/MultiMatrixSolve/test_pseudo_gmres_multidiag.cpp
packages/belos/tpetra/test/TFQMR/test_tfqmr_diag.cpp

These changes resolved compilation errors in OpenMP+Serial build using gcc/12.2.0 with c++20, errors had messages like below:
```
Trilinos/packages/belos/tpetra/test/TFQMR/test_tfqmr_diag.cpp:90:30: error: expected unqualified-id before 'int'
90 |     DiagonalOperator2<ST,MV>(int n_in, int min_gid_in, ST v_in)
```
@trilinos/belos @hkthorn 
Resolve some compilation issues I ran into testing with c++20
Manual testing on weaver testbed with gcc/12.2.0 and c++20 enabled (OpenMP+Serial backends)

belos: fixes for gcc/12.2.0 and c++20

---

.github/workflows/AT2.yml
packages/framework/ini-files/config-specs.ini
packages/framework/ini-files/environment-specs.ini
packages/framework/ini-files/supported-envs.ini
packages/kokkos-kernels/sparse/src/KokkosSparse_spmv.hpp
packages/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv.hpp

Kokkos 5.0 will require C++20, which necessitates upgrading from CUDA 11 to CUDA 12.
https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-720
I ran a build and all tests on trilogpu01 (2xA100).  I had to fix one build error (included in this PR) in Krino.  The test failures are as follows:
- @trilinos/ifpack2  `Ifpack2_unit_tests_MPI_4`
cudaMisalignedAddress error.
- @trilinos/intrepid2 `Intrepid2_unit-test_Discretization_Basis_HGRAD_TRI_Cn_FEM_test_02_CUDA_DOUBLE_DOUBLE_MPI_1`
Not really sure based on the output I see, but we did disable this test (we deliberately did not add it in the CMakeLists.txt) for CUDA11.  It fails reliably.
- @trilinos/rol `ROL_test_elementwise_TpetraMultiVector_MPI_4`
This was disabled for CUDA11, runtime error

Framework: Add CUDA 12 PR build

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/MueCentral/MueLu_HierarchyUtils_decl.hpp
packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/src/Operators/MueLu_MultiPhys_def.hpp
packages/muelu/src/Transfers/Generic/MueLu_CombinePFactory_def.hpp
packages/muelu/test/scaling/comboP.xml

Motivation behind this is to enable a sub-block to use an identity prolongator to ensure that each sub-block reaches the intended `coarse: max size`.
For example, a two-block case may generate coarse-grid sizes that are much too large solely because one sub-block reaches the `coarse: max size` much faster:
```
--------------------------------------------------------------------------------
---                            Multigrid Summary MultiPhys (0,0)             ---
--------------------------------------------------------------------------------
Number of levels    = 7
Operator complexity = 1.58
Smoother complexity = 1.74
Cycle type          = V
level  rows     nnz       nnz/row  c ratio  procs
0  8127945  73105753  8.99                  2048
1  2477335  28298001  11.42 …
```

MueLu: Add option to use max levels for 'multigrid algorithm: combine'

---

packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_decl.hpp
packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp
packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
packages/ifpack2/src/Ifpack2_Parameters.cpp
packages/muelu/src/Utils/MueLu_UtilitiesBase_def.hpp
packages/muelu/test/scaling/Driver.cpp
packages/muelu/test/scaling/DriverCore.hpp

- Ifpack2 Chebyshev: Allocate auxiliary vectors during `compute`.
- MueLu Driver: Hook up RCM reordering
- MueLu: Refactor `EnforceInitialCondition` so that it avoids an allocation 
- MueLu Driver: add option for sacrificial setup

Ifpack2, MueLu: alloc changes

---

packages/tpetra/core/src/Tpetra_Details_KokkosCounter.cpp
packages/tpetra/core/src/Tpetra_Details_KokkosTeuchosTimerInjection.cpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_ApplyUsesTPLs.cpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_MatvecFence.cpp

Issue: #14419
Test: n/a
I also re-enabled clang-format for one file and it totally got rearranged.

Tpetra: Removing ifdefs for no-long-supported Kokkos/KokkosKernels versions

---

.github/workflows/pre_commit_comment.yml
.github/workflows/pre_commit_run.yml
.gitignore
.pre-commit-config.yaml

This PR adds a replacement for the clang-format workflow.
- It splits the workflow into two. One workflow checks the PR with read permissions. The second workflow posts results.
- The formatting check now uses pre-commit. This simplifies adding additional code checks and also allows to run checks locally before pushing them.
- I have tested the workflow in a fork. The `pre_commit_comment` workflow file needs to be on the default branch. So it won't work until then. Once we can see the new system working, I will remove the old clang_format workflow.

Use pre-commit

---

packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_decl.hpp
packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp

We don't want this:
https://github.com/trilinos/Trilinos/blob/fc8b0561871d5092aae01aa4a425729dc4471538/packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp#L323-L325
since it reallocates the DualView sync views every single time.

Ifpack2 Chebyshev: Skip repeated vector construction in non-native spmv code path

---

packages/stokhos/src/sacado/kokkos/vector/KokkosBlas2_gemv_MP_Vector.hpp
packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp

avoid warnings in c++20 builds (cuda, hip) of the form: "warning: implicit capture of 'this' with a capture default of '=' is deprecated "
@trilinos/stokhos @trilinos/zoltan2 
Avoid warnings of deprecated code of type
`warning: implicit capture of 'this' with a capture default of '=' is deprecated ` in build with c++20, more detailed snippets:
**stokhos**
```
/root/Trilinos/packages/stokhos/src/sacado/kokkos/vector/KokkosBlas2_gemv_MP_Vector.hpp:127:32: warning: implicit capture of 'this' with a capture default of '=' is deprecated [-Wdeprecated-this-capture]
127 |                     tmp_sum += A_(jj + j_min, i) * x_(jj + j_min);
|                                ^
/root/Trilinos/packages/stokhos/src/sacado/kokkos/vector/KokkosBlas2_gemv_MP_Vector.hpp:126:53: note: add an explicit capture …
```

stokhos,zoltan2: lambda capture by ref instead of value

---

packages/krino/krino/unit_tests/CMakeLists.txt

@trilinos/krino @drnobleabq 
Split up unit tests to avoid timeout issues #14516 
See here for the time it takes for the individual tests in a debug build:
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlypassed&buildid=791234&filtercount=1&showfilters=1&field1=testname&compare1=63&value1=Krino
I guess the monolithic test took just about 10 mins.

Krino: Split up unit tests

---

packages/zoltan2/core/src/input/Zoltan2_TpetraRowMatrixAdapter.hpp

It looks like there is a plain wrong loop range used. This caused a failure in a debug build with Kokkos develop due to out-of-bounds access. 
`localVals` is initialized to a length of `getLocalMaxNumRowEntries()` while when interrated over a range of `nnz` which is `getLocalNumEntries()` of a Tpetra Matrix.

Looks like an invalid loop index in a Zoltan2 class

---

packages/tpetra/core/example/advanced/Benchmarks/blockCrsMatrixMatVec.cpp

As far as I can tell that type is always 1D. Defined in Tpetra_BlockMultiVector_decl.hpp:160
This failed to compile with the new View implementation.

Tpetra: fix invalid Kokkos::View CTOR call
