trilinos/Trilinos

packages/zoltan2/src/algorithms/partition/Zoltan2_AlgParMA.hpp

This commit updates Zoltan2's interface for recent changes in ParMA's ghost balancer API.

set face weights for ghost balancer

---

packages/zoltan2/src/models/Zoltan2_GraphModel.hpp

Zoltan2: Fix memory leak.

---

LICENSE

I guess this is the right one?

The previous link was broken

---

packages/shylu/core/src/epetra/shylu_factor.cpp
packages/shylu/core/test/shylu_factor_test.cpp

This pull request is one of a set of pull requests being submitted to resolve #634.

Shylu: Fix warnings unused vars (#634)

---

packages/intrepid/src/Shared/Intrepid_RealSpaceToolsDef.hpp

This pull request is one of a set of pull requests being submitted to resolve #634.

Intrepid: Fix unsigned signed warning (#634)

---

sampleScripts/checkin-test-using-sems-modules.sh

Fixing file extension typo in sample config script

---

packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_def.hpp
packages/shylu/basker/src/basker_error_manager.hpp
packages/shylu/basker/src/basker_matrix_decl.hpp
packages/shylu/basker/src/basker_matrix_def.hpp
packages/shylu/basker/src/basker_matrix_view_def.hpp
packages/shylu/basker/src/basker_nfactor.hpp
packages/shylu/basker/src/basker_nfactor_blk.hpp
packages/shylu/basker/src/basker_nfactor_blk_inc.hpp
packages/shylu/basker/src/basker_nfactor_col.hpp
packages/shylu/basker/src/basker_nfactor_col2.hpp
packages/shylu/basker/src/basker_nfactor_col_inc.hpp
packages/shylu/basker/src/basker_nfactor_diag.hpp
packages/shylu/basker/src/basker_order.hpp
packages/shylu/basker/src/basker_order_btf.hpp
packages/shylu/basker/src/basker_order_scotch.hpp
packages/shylu/basker/src/basker_sfactor.hpp
packages/shylu/basker/src/basker_sfactor_inc.hpp
packages/shylu/basker/src/basker_solve_rhs.hpp
packages/shylu/basker/src/basker_sswrapper.hpp
packages/shylu/basker/src/basker_structs.hpp
packages/shylu/basker/src/basker_thread.hpp
packages/shylu/basker/src/basker_tree.hpp
packages/shylu/basker/src/basker_util.hpp
packages/shylu/basker/src/shylubasker_decl.hpp
packages/shylu/basker/src/shylubasker_def.hpp

@srajama1  For review purposes. 
Changes to ShyLU Basker and Amesos2 for performance improvement during solve.

Basker solve

---

packages/belos/src/BelosSolverFactory.hpp

This changes PR #841 to develop branch.  Found as part of investigating #817.

Fixed indentation that caused doxygen to generate incorrect html.

---

packages/shylu/basker/src/basker_matrix_def.hpp
packages/shylu/basker/src/basker_nfactor.hpp
packages/shylu/basker/src/basker_nfactor_blk.hpp
packages/shylu/basker/src/basker_nfactor_blk_inc.hpp
packages/shylu/basker/src/basker_nfactor_col.hpp
packages/shylu/basker/src/basker_nfactor_col2.hpp
packages/shylu/basker/src/basker_nfactor_col_inc.hpp
packages/shylu/basker/src/basker_nfactor_diag.hpp
packages/shylu/basker/src/basker_nfactor_inc.hpp
packages/shylu/basker/src/basker_order.hpp
packages/shylu/basker/src/basker_order_btf.hpp
packages/shylu/basker/src/basker_order_scotch.hpp
packages/shylu/basker/src/basker_sfactor.hpp
packages/shylu/basker/src/basker_sfactor_inc.hpp
packages/shylu/basker/src/basker_solve_rhs.hpp
packages/shylu/basker/src/basker_structs.hpp
packages/shylu/basker/src/basker_thread.hpp
packages/shylu/basker/src/basker_util.hpp
packages/shylu/basker/src/mwm2.hpp
packages/shylu/basker/src/shylubasker_decl.hpp
packages/shylu/basker/src/shylubasker_def.hpp
packages/shylu/basker/test/amesos2_interface_coverage_test.cpp
packages/shylu/basker/test/amesos2_interface_test.cpp
packages/shylu/basker/test/basker_test.cpp
packages/shylu/basker/test/basker_test_inc.cpp

@srajama1 
This pull request contains changes in ShyLU Basker to remove warnings in printf statements and fixes for compile failures when debug mode enabled. 
While making changes to remove warnings I also did some formatting cleanup, hopefully this doesn't clutter the code comparison too badly...

Basker warnings and debug

---

packages/stk/stk_balance/stk_balance/internal/Vertices.cpp
packages/stk/stk_balance/stk_balance/internal/privateDeclarations.cpp
packages/stk/stk_classic/stk_adapt/stk_adapt/sierra_element/StdMeshObjTopologies.cpp
packages/stk/stk_classic/stk_mesh/stk_mesh/baseImpl/FieldBaseImpl.cpp
packages/stk/stk_classic/stk_percept/stk_percept/RunEnvironment.cpp
packages/stk/stk_classic/stk_percept/stk_percept/function/StringFunction.cpp
packages/stk/stk_classic/stk_percept/unit_tests/UnitTestTopoCheck.cpp
packages/stk/stk_classic/stk_percept/unit_tests/mainsh.cpp
packages/stk/stk_classic/stk_search/stk_search/BoundingBox.hpp
packages/stk/stk_classic/stk_usecases/app/UseCase_driver.cpp
packages/stk/stk_classic/stk_usecases/linsys/LinsysUseCase_driver.cpp
packages/stk/stk_classic/stk_util/stk_util/diag/Env.cpp
packages/stk/stk_classic/stk_util/stk_util/diag/PrintTable.cpp
packages/stk/stk_classic/stk_util/stk_util/diag/Trace.cpp
packages/stk/stk_classic/stk_util/stk_util/unit_test_support/GeneratedMesh.cpp
packages/stk/stk_classic/stk_util/unit_tests/util/UnitTestMarshal.cpp
packages/stk/stk_io/example/io_topology.cpp
packages/stk/stk_learning/GameOfLife/NoGhostGameofLife.cpp
packages/stk/stk_mesh/stk_mesh/base/BulkData.hpp
packages/stk/stk_mesh/stk_mesh/base/SetOwners.hpp
packages/stk/stk_mesh/stk_mesh/base/SkinMesh.cpp
packages/stk/stk_mesh/stk_mesh/baseImpl/elementGraph/SideSharingUsingGraph.cpp
packages/stk/stk_topology/stk_topology/topology.cpp
packages/stk/stk_unit_tests/stk_mesh/UnitTestBulkData_new.cpp
packages/stk/stk_unit_tests/stk_mesh/UnitTestModificationEnd.hpp
packages/stk/stk_unit_tests/stk_mesh/UnitTestPartitions.cpp
packages/stk/stk_unit_tests/stk_mesh/face_creation/skin_mesh/UnitTestSkinMeshCoincidentElements.cpp
packages/stk/stk_unit_tests/stk_util/parallel/UnitTestGenerateIds.cpp
packages/stk/stk_unit_tests/stk_util/util/UnitTestMarshal.cpp

Fixing double semi-colons which produce unnecessary warning muddling `-Werror` runs.
@trilinos/stk

stk: ;; -> ;

---

packages/intrepid2/core/src/Cell/Intrepid2_CellToolsDef.hpp
packages/intrepid2/core/src/Discretization/Basis/Intrepid2_BasisDef.hpp
packages/intrepid2/core/src/Discretization/FunctionSpaceTools/Intrepid2_FunctionSpaceToolsDef.hpp
packages/intrepid2/core/src/Shared/Intrepid2_RealSpaceToolsDef.hpp

This pull request is one of a set of pull requests being submitted to resolve #634.

Intrepid2: Fix signed/unsigned warnings. (#634)

---

packages/tpetra/kernels/src/stage/graph/KokkosKernels_Handle.hpp
packages/tpetra/kernels/src/stage/graph/KokkosKernels_Utils.hpp
packages/tpetra/kernels/src/stage/graph/impl/KokkosKernels_SPGEMM_impl.hpp

Albany's build was broken by the recent commits to Trilinos master,
this commit is needed to fix it:
http://my.cdash.org/viewBuildError.php?buildid=1111394
@trilinos/tpetra @ikalash @agsalin

KokkosKernels: fix installed header includes

---

packages/common/auxiliarySoftware/SuiteSparse/src/CMakeLists.txt

@srajama1 @jwillenbring @tawiesn  This addresses #996

Fix a link error in TrilinosSS for shared builds.

---

packages/thyra/core/src/interfaces/nonlinear/model_evaluator/fundamental/Thyra_ModelEvaluator.hpp
packages/thyra/core/src/interfaces/nonlinear/model_evaluator/fundamental/Thyra_ModelEvaluatorBase_decl.hpp
packages/thyra/core/src/interfaces/nonlinear/model_evaluator/fundamental/Thyra_ModelEvaluatorBase_def.hpp
packages/thyra/core/src/support/nonlinear/model_evaluator/client_support/Thyra_DefaultNominalBoundsOverrideModelEvaluator.hpp
packages/thyra/core/src/support/nonlinear/model_evaluator/client_support/Thyra_DirectionalFiniteDiffCalculator_decl.hpp
packages/thyra/core/src/support/nonlinear/model_evaluator/client_support/Thyra_DirectionalFiniteDiffCalculator_def.hpp
packages/thyra/core/test/nonlinear/UnitTests/ModelEvaluatorBase_UnitTests.cpp
packages/thyra/core/test/nonlinear/models/Thyra_DummyTestModelEvaluator_decl.hpp
packages/thyra/core/test/nonlinear/models/Thyra_DummyTestModelEvaluator_def.hpp

Issue #1008 
@bartlettroscoe can you review? Checkin test script passed.

Thyra: added support for x_dot_dot

---

packages/rythmos/src/Rythmos_RKButcherTableau.hpp
packages/rythmos/src/Rythmos_ThetaStepper_def.hpp

This pull request is one of a set of pull requests being submitted to resolve #634.

Rythmos: Removed unused var and shadowed typedef (#634)

---

packages/zoltan2/src/algorithms/zoltan/Zoltan2_AlgZoltan.hpp
packages/zoltan2/test/partition/partitioningTree.cpp

This commit fixes warnings for the partitionTree unit test but does not change any code behavior.

Zoltan2: Fix partition tree unit test warnings

---

packages/rol/src/sol/function/ROL_Distribution.hpp
packages/rol/src/sol/function/distribution/ROL_Arcsine.hpp
packages/rol/src/sol/function/distribution/ROL_Cauchy.hpp
packages/rol/src/sol/function/distribution/ROL_Gaussian.hpp
packages/rol/src/sol/function/distribution/ROL_Logistic.hpp
packages/rol/src/sol/function/distribution/ROL_RaisedCosine.hpp
packages/rol/src/sol/sampler/ROL_MonteCarloGenerator.hpp
packages/rol/src/sol/sampler/SROM/ROL_CDFObjective.hpp
packages/rol/src/sol/sampler/SROM/ROL_PointwiseCDFObjective.hpp
packages/rol/src/utils/ROL_Fejer2Quadrature.hpp
packages/rol/src/utils/ROL_GaussChebyshev1Quadrature.hpp
packages/rol/src/utils/ROL_GaussChebyshev2Quadrature.hpp
packages/rol/src/utils/ROL_GaussChebyshev3Quadrature.hpp
packages/rol/src/zoo/ROL_HS5.hpp
packages/teuchos/core/src/Teuchos_ScalarTraits.hpp
packages/teuchos/core/src/Teuchos_ScalarTraitsDecl.hpp

@trilinos/rol 
Based on discussion in #1179, add pi() to Teuchos::ScalarTraits and replaced M_PI in ROL with this new function. Addresses #1178.

ROL: Replace M_PI with Teuchos::ScalarTraits

---

packages/anasazi/src/AnasaziBlockKrylovSchur.hpp
packages/teuchos/numerics/src/Teuchos_BLAS.cpp
packages/teuchos/numerics/src/Teuchos_BLAS.hpp
packages/teuchos/numerics/src/Teuchos_LAPACK.cpp
packages/teuchos/numerics/src/Teuchos_LAPACK.hpp
packages/teuchos/numerics/src/Teuchos_LAPACK_wrappers.hpp
packages/teuchos/numerics/test/LAPACK/cxx_main.cpp

This PR is a work in progress to address issue #1208. Initially, this addresses the Teuchos::LAPACK interface.

Teuchos Numerics API Refactor

---

packages/amesos2/src/Amesos2_Basker_def.hpp
packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_decl.hpp
packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_def.hpp
packages/amesos2/src/Amesos2_KLU2_def.hpp
packages/amesos2/src/Amesos2_MultiVecAdapter_decl.hpp
packages/amesos2/src/Amesos2_MultiVecAdapter_def.hpp
packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_decl.hpp
packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp
packages/amesos2/src/Amesos2_VectorTraits.hpp
packages/amesos2/src/CMakeLists.txt
packages/amesos2/src/KLU2/Include/klu2.h
packages/amesos2/src/KLU2/Include/klu2_version.h
packages/amesos2/src/KLU2/Source/klu2_solve.hpp
packages/amesos2/src/KLU2/Source/klu2_tsolve.hpp
packages/shylu/basker/src/basker_order.hpp
packages/shylu/basker/src/shylubasker_trilinos_decl.hpp

@srajama1 For review purposes; performance improvements addressing issue #1274

Feature 1274 try2

---

packages/muelu/src/Interface/FacadeClasses/MueLu_Facade_BGS2x2_decl.hpp
packages/muelu/src/Interface/FacadeClasses/MueLu_Facade_BGS2x2_def.hpp
packages/muelu/src/Interface/FacadeClasses/MueLu_Facade_Simple_decl.hpp
packages/muelu/src/Interface/FacadeClasses/MueLu_Facade_Simple_def.hpp
packages/muelu/src/Interface/FacadeClasses/MueLu_Facade_decl.tmpl
packages/muelu/src/Interface/FacadeClasses/MueLu_Facade_def.tmpl
packages/muelu/src/Interface/FacadeClasses/gen_facade.sh

PR from topics branch instead of develop since I have another open PR on it (the develop branch).
The build/test cases summary from ceerws1106 (using the standard SEMs checkin script):
Build/Test Cases Summary
Enabled Packages: MueLu
Disabled Packages: PyTrilinos,Claps,TriKota,FEI,Moertel,STK,SEACAS,ThreadPool,OptiPack,Rythmos,Intrepid,ROL,Panzer
Enabled all Forward Packages
0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=138,notpassed=0 (58.20 min)

MueLu: Fix "pointer being freed was not allocated" error

---

packages/sacado/src/Sacado_DynamicArrayTraits.hpp

@etphipp this should help with #1368

Sacado: stdint.h needed for uint32_t

---

cmake/std/sems/checkin-test-sems.sh
packages/tpetra/core/src/Tpetra_Details_packCrsMatrix.hpp

Tpetra: Removing incorrect error check.

---

packages/tpetra/core/test/CrsMatrix/CrsMatrix_PackUnpack.cpp

Tpetra: Fix warnings-as-errors in test

---

packages/tpetra/core/src/Tpetra_Details_packCrsMatrix.hpp

Review: @mhoemmen 
Addresses: #1395 
Build/Test Cases Summary
Enabled Packages: TpetraCore
Disabled Packages: PyTrilinos,Claps,TriKota
Enabled all Forward Packages
0) MPI_RELEASE_DEBUG_SHARED_PT => passed: passed=1469,notpassed=0 (40.28 min)

Tpetra: Move check for bad export LIDs out of if(debug) branch.

---

packages/amesos/src/Amesos_Umfpack.cpp

The codes now broadcast in a manner which mimics the setup for Klu.
This was a potential strategy for fixing 1108 but would need to be tested.

Amesos: Add error code broadcasting for Umfpack #1108

---

packages/pamgen/mesh_spec_lt/im_ne_c_interface_l.C
packages/pamgen/mesh_spec_lt/pamgen_im_ne_nemesisI_l.h
packages/pamgen/mesh_spec_lt/pamgen_mesh_specification.h
packages/pamgen/src/calc_decomp_cuts.C
packages/pamgen/src/inline_mesh_desc.C
packages/pamgen/src/inline_mesh_desc.h
packages/pamgen/src/inline_mesh_driver_lt.C

These changes are providing the necessary data for
MueLu's geometric multigrid algorithm to run

Pamgen: Changes needed to get ijk info from mesh

---

packages/panzer/adapters-stk/test/face_to_elem/Panzer_Relations.cpp
packages/panzer/adapters-stk/test/panzer_workset_builder/CMakeLists.txt
packages/panzer/adapters-stk/test/panzer_workset_builder/workset_container.cpp
packages/panzer/disc-fe/src/Panzer_Workset.hpp
packages/panzer/disc-fe/src/Panzer_WorksetContainer.cpp
packages/panzer/disc-fe/src/Panzer_WorksetContainer.hpp

1) This works by taking each descriptor, hashing and then for each
workset covered by that descriptor adding a integer to it.
2) Fixed a warning in a test
Corresponds to issue #1539

Panzer: Adding workset identifiers with a unit test

---

cmake/ctest/drivers/windows/create_windows_package.bat

This commit is aimed at addressing #1163. The new script creates a zip package on Windows.

Windows MSVC package script

---

cmake/ctest/drivers/windows/README.md

Added a README file for the Windows MSVC testing scripts.

Windows testing docs

---

commonTools/test/utilities/changedPackages.bash
packages/muelu/src/Interface/MueLu_HierarchyManager.hpp

This is a utility file for detecting which packages changed for pull request testing. We plan to rewrite this in Python, but will use this version for now.

add changedPackages.bash

---

packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp

ML: silence misleading indentation warning

---

packages/muelu/src/Misc/MueLu_SchurComplementFactory_def.hpp

this 'zero' variable doesn't seem to be
used anywhere at all.

MueLu: silence unused variable warning

---

packages/panzer/adapters-stk/example/square_mesh/square_mesh_bc.cpp

This is to try to address an intermittent failure seen by @dridzal in the ROL nightlies. I've not recreated the issue, but it appears to be some sort of collision with regard to the file system.

Adding a "_bc" postfix to an exodus file

---

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp

Tpetra: silence some warnings

---

packages/aztecoo/src/Epetra_MsrMatrix.cpp
packages/aztecoo/src/az_util.c
packages/epetra/src/Epetra_VbrMatrix.cpp

The misleading indentation warning found
a legitimate bug in these print statements.
Not sure who to mention... @alanw0 @sconde ?

Epetra & AztecOO: Fix some warnings

---

packages/teuchos/comm/src/Teuchos_CTimeMonitor.cpp
packages/teuchos/core/src/Teuchos_TestForException.cpp
packages/teuchos/parameterlist/src/Teuchos_StandardDependencies.cpp
packages/teuchos/parameterlist/src/Teuchos_StandardDependencies.hpp

I just tried to compile on my Mac for the first time in a while, saw these and fixed them.
Unfortunately I can't access CEE resources till the end of this week, so its unlikely I'll be able to checkin test these before then.
Just putting up the PR for safe keeping.

silence OS X Clang warnings

---

packages/shylu/shylu_dd/frosch/src/InterfaceSets/FROSch_DDInterface_def.hpp
packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp
packages/shylu/shylu_dd/frosch/test/CMakeLists.txt
packages/shylu/shylu_dd/frosch/test/TestLaplacian_Tpetra/main.cpp

This is a workaround for the issue with Tpetra's import/export; see #1752.

Workaround for Tpetra issue #1752. Enabling Tpetra test

---

packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeneralGeometricPFactory_def.hpp

MueLu: remove some unused variables

---

packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_BlockedEpetra_Hessian_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_BlockedEpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Epetra_Hessian_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Epetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Tpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_BlockedEpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_Epetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_Tpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedEpetra_Hessian_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedEpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Epetra_Hessian_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Epetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Tpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedEpetra_Hessian_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedEpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Epetra_Hessian_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Epetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_impl.hpp
packages/panzer/disc-fe/src/responses/Panzer_ResponseScatterEvaluator_Functional.hpp
packages/panzer/disc-fe/src/responses/Panzer_ResponseScatterEvaluator_Probe.hpp
packages/panzer/dof-mgr/src/Panzer_UniqueGlobalIndexer.hpp
packages/panzer/dof-mgr/src/Panzer_UniqueGlobalIndexer_Utilities_impl.hpp
packages/panzer/dof-mgr/test/dofmngr_test/tFilteredUGI.cpp

This is @bathmatt's take on resolving #1853.

Resolves "Clean up panzer indexer memory"

---

packages/anasazi/src/AnasaziTraceMin.hpp

Anasazi: fix compilation issue when Epetra=OFF

---

packages/tpetra/core/src/Tpetra_Map_decl.hpp

Tpetra: mask some code that SWIG parser hiccups on

---

packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp

Teuchos: name all PLs read from YAML

---

packages/kokkos/core/src/Kokkos_Parallel.hpp

See kokkos/kokkos#1219 for full background. Basically, if a user defines a function called `parallel_for` in their own namespace, there are cases in which Kokkos can unintentionally call it. This pull request prevents that from happening, which causes very subtle errors when it does.
Prevents Kokkos from unintentionally calling user-defined `parallel_for` and `parallel_scan` functions.
* Related to kokkos/kokkos#1219 kokkos/kokkos#1220 kokkos/kokkos#1221
The user application which triggered this bug has been recompiled and re-tested against a patched version of Kokkos. The checkin script will be run shortly.

Kokkos: hot patch for ADL conflict

---

packages/phalanx/example/FiniteElementAssembly/CommandLineParser.hpp
packages/phalanx/example/FiniteElementAssembly/FiniteElementAssembly.cpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/FiniteElementAssembly_DeviceDag.cpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/FiniteElementAssembly_MixedFieldTypes.cpp
packages/phalanx/src/Phalanx_DAG_Manager.hpp
packages/phalanx/src/Phalanx_DAG_Manager_Def.hpp

Adding more options to performance tests

Phalanx: adding more options to performance tests

---

packages/panzer/disc-fe/test/core_tests/basis.cpp

The new layout for local element matrices was added to panzer disc-fe core tests.

Added local matrix array test for issue #1607

---

packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Epetra_impl.hpp

The call to `Jac->ReplaceMyValues()` needed the global ID count and not the size of the local ID array as an argument.
Closes #2032.

Resolves "Panzer:  Commit c468d41b Breaks Charon"

---

packages/phalanx/example/FiniteElementAssembly_DeviceDag/analyze_performance.py

Adding a python script to phalanx that creates performance plots from example output.

Phalanx: adding script to analyze example output #2012

---

packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp
packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp
packages/muelu/test/scaling/Driver.cpp

Galeri muelu fix

---

packages/phalanx/example/FiniteElementAssembly/CommandLineParser.hpp

minor change to default policy parameters

Phalanx: change test defaults

---

packages/intrepid2/src/Cell/Intrepid2_CellTools.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_COMP12_FEMDef.hpp

Simply uncommented a couple of lines to enable Composite TET when building HGRAD bases. This functionality is needed by Albany.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 

Intrepid2: Uncomment lines for Composite Tet in Cell Tools

---

packages/panzer/disc-fe/src/Panzer_IntrepidBasisFactory.hpp

Fixed bug where the wrong basis was being constructed

---

packages/panzer/disc-fe/src/evaluators/Panzer_DOF.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOF.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOF_impl.hpp

Also removed all "decl" headers from DOF evaluators
1) Modifying the DOF evaluator with descriptor interface
1) Modifying the DOFGradient evaluator with descriptor interface
3) Modifying the DOFCurl evaluator with descriptor interface
4) Modifying the DOFDiv evaluator with descriptor interface

Panzer: Updating DOF evaluators to work with a descriptor/tag constructor

---

packages/panzer/disc-fe/src/evaluators/Panzer_DOF.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOF_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Sum.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_Sum.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Sum_impl.hpp

Also removed the decls as these are no longer explictly instantiated

Panzer: Adding a descriptor/tag interface to a few more evaluators

---

packages/phalanx/scripts/evaluatorUsage

This is a work-in-progress PR just so @rppawlo can get eyes on this script as I continue to develop it.
* Closes #2134 
* Related to #1575
So far I run `ctest` in my Drekar, Charon, or base build directories, then run `evaluatorUsage` on the `Testing/Temporary/LastTest.log` and look at the results.

[WIP]  Resolves "Phalanx:  Evaluator Usage Script"

---

packages/panzer/disc-fe/src/lof/Panzer_BlockedTpetraLinearObjFactory.hpp
packages/panzer/disc-fe/src/lof/Panzer_BlockedTpetraLinearObjFactory_impl.hpp

Modified a handful of functions and exposed a few more capabilities in the blocked Tpetra LOF

Panzer: Modest changes to the blocked tpetra LOF exposing features

---

packages/tempus/src/Tempus_Integrator.hpp
packages/tempus/src/Tempus_IntegratorAdjointSensitivity_decl.hpp
packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
packages/tempus/src/Tempus_IntegratorObserverBasic_decl.hpp
packages/tempus/src/Tempus_IntegratorObserverBasic_impl.hpp
packages/tempus/src/Tempus_IntegratorObserverComposite_decl.hpp
packages/tempus/src/Tempus_IntegratorObserverComposite_impl.hpp
packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_decl.hpp

moving Tempus output into the observers so it would be easy to change
out by applications
* Closes #2119 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
[All tests passed](https://github.com/trilinos/Trilinos/files/1604672/all_test.txt)

Tempus: move integrator output to observer

---

packages/tempus/src/Tempus_TimeStepControl_decl.hpp

Make the TimeStepControl members protected instead of private
New external TSC classes are now deriving from this class.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Tempus: make TimeStepControl members protected

---

packages/phalanx/example/FiniteElementAssembly/PrintValues.hpp
packages/phalanx/example/FiniteElementAssembly/evaluators/ProjectGradientToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly/evaluators/ProjectValueToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/analyze_performance.py
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/IntegrateDiffusionTerm.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/IntegrateDiffusionTerm_Def.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/IntegrateSourceTerm.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/IntegrateSourceTerm_Def.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ProjectGradientToQP.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ProjectGradientToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ProjectValueToQP.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ProjectValueToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ScatterResidual_Def.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ZeroContributedField.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ZeroContributedField_Def.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/ProjectGradientToQP_Def.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/ProjectValueToQP_Def.hpp
packages/phalanx/src/Phalanx_DAG_Manager_Def.hpp
packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp

Added specializations for all evaluators in the device dag example
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Phalanx: specialize for eval types in Device DAG #2012

---

packages/tpetra/core/src/Tpetra_Import_decl.hpp
packages/tpetra/core/src/Tpetra_Import_def.hpp

This commit rewrites Tpetra::Import::setUnion to use std algorithms to find,
shift, remove, order, etc. the union target GIDs.  Many raw loops, sorts,
merges, etc. were removed.  The resulting code is simpler to follow and will,
hopefully, make optimizations more easy to determine/implement.
@mhoemmen, @csiefer2
See  #2108 
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #2108 
* Composed of 
RHEL6, SEMS gcc-4.9.3, openmpi

Tpetra: rewrite of Tpetra::Import::setUnion

---

packages/phalanx/example/FiniteElementAssembly/PrintValues.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ProjectGradientToQP_Def.hpp

* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Phalanx: remove debug print statement

---

packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
packages/tempus/src/Tempus_IntegratorObserverBasic_impl.hpp

Was outputing at every time step and this could possibly have slowed down Albany's tests
[Verbose output for the Explicit RK test before the fix](https://github.com/trilinos/Trilinos/files/1639804/after_verbose_explicit_rk.txt) vs 
[Verbose output for the Explicit RK test before the fix](https://github.com/trilinos/Trilinos/files/1639810/tempus_explicit_rk.txt)
* Closes #2163

Tempus: (fix) output integrator info at interval specified

---

packages/panzer/adapters-stk/test/evaluator_tests/CMakeLists.txt
packages/panzer/adapters-stk/test/evaluator_tests/domain_interface.cpp
packages/panzer/disc-fe/src/Panzer_Evaluator_DomainInterface.cpp
packages/panzer/disc-fe/src/Panzer_Evaluator_DomainInterface.hpp
packages/panzer/disc-fe/src/Panzer_Workset.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Evaluator_WithBaseImpl.hpp

Add domain support to evaluators via a mix-in interface
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Panzer: add domain support to evaluators #2165

---

packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Tpetra_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Tpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_VectorToScalar_impl.hpp

I sped up several panzer evaluators gather/scatter and vector to scalar, by using parallel fors.  
Suggesting either @jmgate or @rppawlo 
This gained a factor of 5 in runtime for the EMPIRE application
Using gcc/opt/debug with openMP I got 
100% tests passed, 0 tests failed out of 114

Parallel tpetra scatter gather

---

packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter_Def.hpp
packages/piro/src/Piro_TempusSolver_Def.hpp

when setting tempus observer, first clear the vector of observers to avoid adding multiple copies of the piro tempus obsevers.
also define integrator output in TempusObserver here since the composite
vector is cleared.
@trilinos/piro @trilinos/tempus 
* Closes #2163 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
**NOTE: still need to be tested with Albany**

Piro: before adding observer to Tempus, first clear the composite vector

---

packages/panzer/core/src/Panzer_Version.hpp

Resolves "Test git.git-like Workflow"

---

packages/tempus/src/Tempus_TimeStepControlStrategyComposite.hpp

Tempus will only add strategies that have been implemented in Tempus.
The idea is that extra sublist in the `Time Step Control Strategy` will
be validated and added by applications. So to avoid Segmentation faults,
only nonnull strategies should be added to the vector.
I only caught this when I started using the strategies in Drekar.
Tempus really shouldn't have to remove the sublists of strategies. So this will avoid segfaults. Unless there is smarter way to go about this.
* Closes 
* Blocks [Drekar](https://github.com/rppawlo/DrekarBase/pull/41)
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
All tests are passing.

Tempus: only add nonnull(strategies) to TSCS

---

packages/panzer/mini-em/example/BlockPrec/main.cpp

I was asked to add the ability to read a file into mini-EM for more realistic runs and faster mesh building.  This does that, I tested but don't want to upload a mesh file to test.  Any idea on how to test this?  Should we just run with this?
@jhux2 thought you'd be interested,

Added flag to read filename into mini-EM using exodus file

---

.github/CODEOWNERS

The discussion in #2013 details a number of examples in which the wrong team is being automatically requested to review PRs.  GitHub support has yet to get back to us with any ideas as to what's going on.  At this point, I'm wondering if blank lines between code owners matter to GitHub's parsing of the file.

CODEOWNERS Changes

---

packages/panzer/mini-em/example/BlockPrec/main.cpp

Proposing a fix for the time integrator in the mini-em BlockPrec example, based on running one iteration of Newton's method inside the time loop.  In principle, one could add a for-loop to run a full Newton solve here, but it is not needed because the example problem is linear. 
Bug fix for Trilinos issue #2241.
Built locally and ran ctest in the only affected directory.

Bug fix for Trilinos issue #2241.

---

packages/nox/src-thyra/NOX_Thyra_Group.C
packages/nox/src-thyra/NOX_Thyra_Group.H
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.cpp
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.hpp
packages/nox/src/NOX_Solver_SingleStep.C
packages/nox/src/NOX_Solver_SingleStep.H
packages/nox/test/tpetra/ME_Tpetra_1DFEM_def.hpp
packages/tempus/src/Tempus_StepperImplicit.hpp

1. Improved flexibility wrt external preconditioner use. The NOX-Thyra support was modified to allow for an external preconditioner to be set but delay the update of the matrix coefficients. This was a feature in the nox-epetra support that never got duplicated in the nox-thyra support.
2.  Fixed an inefficiency in the use of nox in tempus where some solver objects were being rebuilt every time step.
3. Added ParameterList validation to the SingleStep solver and added a parameter to ignore linear solver convergence failures. An application was requesting a very tight tolerance that was not always met, but the progress it made was more than good enough for convergence of the time step. This is off by default. This an option in the other solvers that was not in single step. …

NOX/Tempus: performance improvements and prec flexibility #2252

---

packages/shylu/shylu_node/hts/src/shylu_hts.cpp

This commit addresses Trilinos issue #2280, warning-as-error causes by
the 'usused' variable
Commented out 'unused' variable causing warning-as-error reported by issue #2280
Commented out static int 'unused' variable in shylu_hts.cpp
Address issue #2280 
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Autotester will test

shylu_hts: comment out 'unused' variable in .cpp

---

packages/trilinoscouplings/src/ml/NonlinML/nlnml_preconditioner1.cpp
packages/trilinoscouplings/src/ml/NonlinML/nlnml_preconditioner_utils.cpp

Fix #2281 (build warnings in TrilinosCouplings).  It's hard to figure out how to set up TrilinosCouplings so it actually tests the thing -- I built TrilinosCouplings with ML enabled, but that didn't seem to enable the code.
@trilinos/ml @trilinos/muelu

TrilinosCouplings: Fix #2281

---

packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_decl.hpp
packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp
packages/stokhos/src/sacado/kokkos/pce/tpetra/Tpetra_CrsMatrix_UQ_PCE_def.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_decl.hpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_def.hpp
packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
packages/tpetra/core/src/Tpetra_RowMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_Vector_decl.hpp
packages/tpetra/core/src/Tpetra_Vector_def.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_PackUnpack.cpp

Fix #2290.  I only made tiny changes to Ifpack2 (edited 23 Feb 2018: and Stokhos).  Almost all the changes were in Tpetra.
@trilinos/tpetra @trilinos/ifpack2 (ed. 23 Feb 2018: @trilinos/stokhos )
WARNING: This will break code (e.g., Nalu) that does forward declarations of Tpetra classes.

Tpetra,Ifpack2,Stokhos: Fix #2290

---

packages/nox/test/tpetra/Tpetra_MultiVectorOpsTests.cpp
packages/panzer/adapters-stk/test/local_mesh/PanzerSTK_UnitTest_BuildMesh.cpp
packages/panzer/mini-em/example/BlockPrec/main.cpp

Issue 2282

---

packages/teuchos/core/src/Teuchos_BigUInt.hpp

[#2316]
Fixes what seems to be a legitimate uninitialized variable bug pointed out by compiler warnings.
This change is required because the code as-is can use uninitialized data in some cases.
* Closes #2316 
A custom build of Teuchos passes tests.

Teuchos: Fix uninitialized variable

---

packages/panzer/mini-em/example/BlockPrec/main.cpp

- closes #2257 
@egphill can you review?

if'ed out gradient calc when it's not needed

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp

Fix #2334 by removing the Teuchos::as call from the (potentially CUDA device) kernel.

Tpetra: Fix #2334

---

cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake
cmake/tribits/core/package_arch/TribitsProjectImpl.cmake

Adds a better error message for in-source build attempt.  See #2324.

2324 improve in source error message

---

packages/shylu/shylu_node/tacho/src/TachoExp_NumericTools.hpp
packages/shylu/shylu_node/tacho/unit-test/Tacho_TestCrsMatrixBase.hpp

These signed/unsigned comparison warnings
caused build failures in the warnings-as-errors
builds.  This shoue resolve issue #2280
* Closes #2280

shylu_node: correct warnings.

---

packages/thyra/adapters/epetra/test/UnitTests/EpetraLinearOpParallel_UnitTests.cpp
packages/thyra/adapters/epetra/test/UnitTests/EpetraLinearOpTestHelpers.hpp
packages/thyra/adapters/epetra/test/UnitTests/EpetraLinearOp_UnitTests.cpp
packages/thyra/adapters/epetra/test/UnitTests/EpetraThyraWrappers_UnitTests.cpp

These were causing failures in the warning-as-errors
builds.  Basically this moves one function that is
only in a single test into that source file and
splits another into a second header. This allows us
to share the test fixture where needed witout having
unused functions for the compiler to complain about.
closes issue #2286
* Closes 2286

Correct warnings in the test code

---

packages/ml/examples/Advanced/ml_user_aggr.cpp
packages/ml/examples/MatrixFormats/ml_AztecMsr.cpp
packages/ml/test/ValidateParams/cxx_main.cpp

ML: cleanup warnings by commenting out unused variables

---

packages/panzer/adapters-ioss/src/Panzer_IOSSConnManager.hpp

Test EMPIRE/Trilinos Co-Development Wor... (#2384)

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp

@trilinos/tpetra Possible fix for #2382.
@micahahoward

Tpetra: Possible fix for #2382

---

packages/nox/test/epetra/1Dfem/1DfemPrePostOperator.C

@trilinos/nox 
@rppawlo 
Fixes new failure on the dashboard:
https://testing-vm.sandia.gov/cdash/testDetails.php?test=44264658&build=3369951
This was due to changes in Pull Request #2377. Forgot to initialize some new counters to zero, and this wasn't getting picked up in either my testing or the pre-merge auto testing
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

NOX: Forgot counter initialization in updated PrePostOperator test

---

packages/nox/src-thyra/NOX_Thyra_Group.C
packages/nox/src-thyra/NOX_Thyra_Group.H
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.cpp
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.hpp
packages/nox/src/NOX_Solver_SingleStep.C
packages/nox/src/NOX_Solver_SingleStep.H
packages/nox/test/epetra/Thyra/CMakeLists.txt
packages/nox/test/epetra/Thyra/Thyra_SingleStepSolver_1D.C

We have a use case where an application externally computes the Jacobian and would like to reuse it in the SingelStep solver. We need the capability to set the Jacobian on the group and tell the group that it is already up to date wrt the solution vector. Then need the SingleStep solver to be aware of this "fixed Jacobian" that it should not update.
@trilinos/nox 
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

NOX: allow for external fixed Jacobian in SingleStep solver #2394

---

packages/panzer/dof-mgr/src/Panzer_UniqueGlobalIndexer.hpp

@rppawlo can you merge this, the other one wasn't in a parallel region.

Removed teuchos as for static cast

---

packages/panzer/adapters-ioss/src/Panzer_IOSSConnManager_impl.hpp

Demo Workflow (#2417)

---

packages/tempus/src/Tempus_StepperImplicit_decl.hpp

Fixes Drekar tests failing for implicit and IMEX. 

Tempus: default "Zero Initial Guess"

---

packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp

Use Tpetra::Details::getEntryOnHost in Tpetra::Details::computeOffsets*
where appropriate.  getEntryOnHost avoids UVM access issues by using
fences where appropriate.
Improve GPU correctness.  
* Closes #2416 
Locally, I tested with CUDA 8 and gcc.

Tpetra: Fix #2416 (Tpetra::Details::computeOffsets* UVM)

---

packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp

This fixes the asSafe() test for the cuda builds on 'shiller' described in https://github.com/trilinos/Trilinos/issues/2407#issuecomment-374319847.  This should fix #2407 once and for all.
I tested this locally on 'shiller' (same system as 'hansen') with:
```
$ srun ./checkin-test-atdm.sh cuda-opt gnu-opt-serial intel-opt-serial \
--ctest-options="-j16 -R TeuchosCore_TypeConversions_UnitTest" \
--enable-packages=TeuchosCore --local-do-all
```
```
PASSED (NOT READY TO PUSH): Trilinos: shiller03
Tue Mar 20 13:14:06 MDT 2018
Enabled Packages: TeuchosCore
1) cuda-opt => passed: passed=1,notpassed=0 (2.07 …
```

Fix long double string to double conversion on shiller (#2407)

---

packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp

MueLu: enable mj_premigration_option by default for Zoltan2

---

packages/kokkos/cmake/kokkos_options.cmake

Add `Volta70` and `Volta72` to the list of CMake options for `KOKKOS_ARCH`.
Without this, one can't properly compile Trilinos for Volta.
* Closes [#2432]
* Follows kokkos/kokkos#1478

Add Volta options to CMake

---

packages/panzer/disc-fe/src/Panzer_TypeAssocMap.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_CellAverage_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Sum.hpp

Minor fixes to get rid of cuda compiler warnings.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Panzer: fixes for cuda

---

packages/shylu/shylu_node/tacho/src/Tacho_Lapack_Team.hpp
packages/shylu/shylu_node/tacho/src/Tacho_MatrixMarket.hpp
packages/shylu/shylu_node/tacho/src/Tacho_NumericTools.hpp
packages/shylu/shylu_node/tacho/src/Tacho_SupernodeInfo.hpp
packages/shylu/shylu_node/tacho/unit-test/Tacho_TestDenseByBlocks.hpp

Tacho fix when kokkos bound check 

---

cmake/std/atdm/ride/tweaks/CUDA-DEBUG-CUDA.cmake
cmake/std/atdm/ride/tweaks/GNU-DEBUG-OPENMP.cmake
cmake/std/atdm/utils/checkin-test-atdm-single.sh

**CC:** @trilinos/teuchos 
This addresses #2410.  See the commit log.

2410 disable lapack tests ride debug

---

packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp

Fixing the issue uncovered in #1649.

MueLu: fix a bug in merging Zoltan2 parameter lists

---

packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp
packages/kokkos-kernels/unit_test/CMakeLists.txt
packages/tpetra/core/example/BlockCrs/Tpetra_TestBlockCrsMeshDatabase.hpp

This fixes the remaining issues with a Trilinos build of the Tpetra stack that has Kokkos bounds checking enabled. There was an off-by-one error when constructing subviews to supply as begin/end arrays. Also, the `dgemm_double` test is very slow with bounds checking on, so until it is modified such that it runs faster, I've added code to disable it when bounds checking is on.
This helps Trilinos pass all tests with Kokkos bounds checking enabled, with is an ATDM goal.
* Part of #2439 
A custom build of Trilinos passes the tests which formerly failed as identified by #2439

KokkosKernels & Tetra fixes for KOKKOS_ENABLE_DEBUG

---

cmake/std/sems/checkin-test-sems.sh

Add missing cmake/std/sems/SEMSDevEnv.cmake for the complex SEMS.
Added missing cmake/std/sems/SEMSDevEnv.cmake for complex SEMS.
This will restore complex SEMS to run.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Created this branch, pulled to SEMS machine, and then tested a simple run with Teuchos enabled. This would previously fail to configure and now passes.

Fix complex sems (#2468)

---

packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp
packages/trilinoscouplings/examples/scaling/CMakeLists.txt
packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp
packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.cpp
packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.hpp
packages/trilinoscouplings/examples/scaling/muelu_structured_aggregation.xml

The new example is almost identical to the unstructured example except for
small extra data that needs to be collected and passed to MueLu in order
to the structured algorithms.
These changes add a new example in TrilinosCouplings that will be used to test new structured algorithm developed in MueLu
There is no easy way to test this type of algorithm anywhere else since most tests/examples do not provide structured meshes information
The example has been run in serial and parallel

TrilinosCouplings: adding a new example to use structured algorithm in MueLu

---

packages/stokhos/src/sacado/kokkos/vector/muelu/BelosXpetraAdapterMultiVector_MP_Vector.hpp
packages/stokhos/src/sacado/kokkos/vector/muelu/Stokhos_MueLu_MP_Vector.hpp

Needed for MP::Vector scalar type when ensemble reduction is enabled.

Stokhos:  Add specialization of Belos::MultiVecTraits for Xpetra.

---

packages/minitensor/src/MiniTensor_Solvers.h
packages/minitensor/src/MiniTensor_Solvers.t.h

* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Changes to MiniTensor

---

packages/fei/base/fei_FEDataFilter.cpp

This was failing in warning-as-error builds and the if
statement was not clear.  This quiets the compiler and
make the fact that we are checking to see if the returned
pointer is not null explicit.
@trilinos/fei 
* Closes #2279
Replicated warnings-as-error-builds locally

Fix FEI build issue (warning-as-errors)

---

cmake/ctest/drivers/atdm/README.md
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-debug-openmp-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-debug-openmp.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-debug-serial-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-debug-serial.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-opt-openmp-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-opt-openmp.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-opt-serial-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-opt-serial.sh
cmake/ctest/drivers/atdm/rhel6/local-driver.sh
cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-debug-openmp-panzer.sh
cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-debug-openmp.sh
cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-opt-openmp-panzer.sh
cmake/ctest/drivers/atdm/toss3/drivers/Trilinos-atdm-toss3-intel-opt-openmp.sh
cmake/ctest/drivers/atdm/toss3/local-driver.sh
cmake/std/atdm/README.md
cmake/std/atdm/rhel6/all_supported_builds.sh
cmake/std/atdm/rhel6/environment.sh
cmake/std/atdm/toss3/all_supported_builds.sh
cmake/std/atdm/toss3/environment.sh
cmake/std/atdm/utils/get_known_system_name.sh

@bartlettroscoe can you review this?
Added scripts to build and test the ATDM configuration of trilinos on new machines.  This makes it easy to reproduce builds on these platforms.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
The scripts were run on toss3 and rhel6 machines and were successful in building, testing, and submitting results to cdash.
- [] These changes break backwards compatibility.

Scripts for building and testing the ATDM configure of trilinos on toss3 machines and on sems rhel6 machines

---

cmake/ProjectCompilerPostConfig.cmake

Installs the `kokkos_generated_settings.cmake` file.
This file can be useful for downstream users of Trilinos to see details of how Kokkos was configured.

Framework: install kokkos_generated_settings.cmake

---

packages/xpetra/src/Operator/Xpetra_TpetraOperator.hpp

Hopefully helping w/ Enigma Fails

Auto-PR for SHA 692fef5

---

cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-intel-opt-openmp-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-intel-opt-openmp.sh
cmake/std/atdm/rhel6/environment.sh
cmake/std/atdm/utils/get_known_system_name.sh

We need to load the sems git 2.10 module because the defeult versiuon is too old for the repo update to work
changes the "site" on cdash for all rhel6 sems builds to be "sems-rhel6"
@bartlettroscoe - please review when you get a chance
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

small changes to atdm configuration on sems rhel6 machines

---

cmake/ctest/drivers/gaia/README
cmake/ctest/drivers/gaia/TrilinosCTestDriverCore.sems.cmake
cmake/ctest/drivers/gaia/ctest_darwin_mpi_debug_pytrilinos_ci.sems.cmake
cmake/ctest/drivers/gaia/single_ci_iter.sh
cmake/ctest/drivers/gaia/trilinos_ci_sever.sh

First attempt at setting up a CI driver for PyTrilinos on my Mac Pro Gaia
Provide first nightly testing of PyTrilinos, and apparently first Mac for Trilinos CI testing
* Part of #891 
Not ready for testing yet. Pull request is to facilitate collaboration

PyTrilinos: Set up a CI driver for testing PyTrilinos

---

cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc-cuda.cmake

Auto-PR for SHA 599312b

---

packages/teuchos/CMakeLists.txt

Edit: autocorrected incorrectly to `tempus`, changed to `teuchos`
See #2547

Teuchos: support ancient CMake versions

---

cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-debug-openmp-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-debug-serial-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-opt-openmp-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-gnu-opt-serial-panzer.sh
cmake/ctest/drivers/atdm/rhel6/drivers/Trilinos-atdm-rhel6-intel-opt-openmp-panzer.sh

All of the ATDM panzer builds on the SEMS rhel6 machines passed last night so we are promoting them to the "ATDM" track on cdash
see results at:
https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=-atdm-rhel6&field2=buildname&compare2=63&value2=-panzer
@bartlettroscoe please review when you get a chance
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Promoting rhel6 atdm panzer builds to ATDM track on cdash

---

packages/teuchos/core/src/Teuchos_CommandLineProcessor.hpp
packages/teuchos/core/src/Teuchos_OrdinalTraits.hpp

I missed a few `#ifdef`s for `long long`, which caused nightly tests to fail if they were turning `long long` off in their CMake configuration.
See #2589

Teuchos: remove latent checks for long long

---

packages/panzer/dof-mgr/test/cartesian_topology/CartesianConnManager_impl.hpp

Thanks to Aram M. for pointing this out.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

Panzer: fix clang compile

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp

Tpetra: make sort optional for LTG

---

packages/muelu/test/scaling/MMKernelDriver.cpp

@csiefer2 
@csiefer2 
1) Randomized run order of kernels
2) added command line options to enable and disable specific kernels (default behavior is to enable all)
3) Added verbose output for Matrix, Vector, and template parameters actually used. (E.g., Scalar = double (size 8))
4) Modifications use C++11 (std::shuffle, std::random_device, auto, etc..) - Should not be an issue since Trilinos requires C++11
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of

MueLu: Tweaks to MatrixMatrix driver

---

packages/muelu/test/maxwell/Maxwell3D.cpp

Auto-PR for SHA 9946663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/2610)

MueLu: fix test

---

.github/PULL_REQUEST_TEMPLATE.md

This is what I came up with after our discussion on Wednesday. It looks better to me and is much slimmer without actually removing the less used pieces but instead leaves them in the comments.
Darts welcome ;->

Restructure PR template

---

packages/muelu/test/scaling/MMKernelDriver.cpp

MueLu: Missing header fixes

---

packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp
packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/options_general.tex
packages/muelu/doc/UsersGuide/paramlist.tex
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/Interface/MueLu_HierarchyFactory.hpp
packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/src/Utils/MueLu_Monitor.hpp

Permits to prefix all print-outs and timers of a given hierarchy with a label.
A hierarchy is is labeled using the string parameter `hierarchy label` in the xml input file, or when the operator used to create the hierarchy has a label.
Example of Teuchos timer output with labels `RefMaxwell (1,1)` and `RefMaxwell (2,2)`:
```
MueLu: RefMaxwell (1,1): UncoupledAggregationFactory: Algo "Phase 2b (expansion)" (sub, total, level=0)                                           8.988e-05 (1)              
MueLu: RefMaxwell (1,1): UncoupledAggregationFactory: Algo "Phase 3 (cleanup)" (sub, total)                                                       3.505e-05 (1)              
MueLu: RefMaxwell (1,1): UncoupledAggregationFactory: Algo "Phase 3 (cleanup)" (sub, total, level=0) …
```

MueLu: Labeled hierarchies

---

packages/muelu/test/scaling/CMakeLists.txt

Auto-PR for SHA 8a3b155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/2617)

Enable MMKernelDriver test in serial

---

packages/muelu/utils/misc/isawesome.sh

MueLu: More github utils

---

packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp
packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp

Auto-PR for SHA 8e6c2a1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/2627)

Xpetra: fix CUDA warnings

---

packages/zoltan2/test/unit/models/GraphModel.cpp

@trilinos/tpetra @trilinos/zoltan2 
Replaced calls to Tpetra's getNodeNumDiags() and getGlobalNumDiags() with code to compute the number of diagonals as needed.  
Tpetra plans to deprecate/remove getNodeNumDiags and getGlobalNumDiags.
#2630 
Tested on my mac
- [ x] I have added tests to cover my changes.

zoltan2:  removed getNodeNumDiags() for #2630

---

packages/muelu/research/max/XpetraSplitting/Xpetra_MatrixSplitting.hpp
packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp
packages/xpetra/src/CrsGraph/Xpetra_CrsGraph.hpp
packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp
packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph.hpp
packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp
packages/xpetra/src/RowGraph/Xpetra_RowGraph.hpp
packages/xpetra/src/RowMatrix/Xpetra_RowMatrix.hpp
packages/xpetra/src/RowMatrix/Xpetra_TpetraRowMatrix.hpp
packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap.hpp
packages/xpetra/sup/Matrix/Xpetra_Matrix.hpp
packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
packages/xpetra/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp

Xpetra/MueLu: Commits related to #2630

---

packages/muelu/test/unit_tests/Adapters/AmgxOperatorAdapter.cpp

MueLu: Disabling AMGx tests in parallel

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/src/Misc/MueLu_ThresholdAFilterFactory_decl.hpp
packages/muelu/src/Misc/MueLu_ThresholdAFilterFactory_def.hpp
packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
packages/panzer/mini-em/example/BlockPrec/main.cpp
packages/panzer/mini-em/example/BlockPrec/solverDefaultsRefMaxwell.xml
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
packages/trilinoscouplings/examples/scaling/Maxwell.xml
packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix.hpp
packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp

Addition of a basic Kokkos code path to RefMaxwell.
The changes to code outside of MueLu's RefMaxwell are fairly limited.

MueLu: RefMaxwell Kokkos refactor

---

packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_BlockedTpetra.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_BlockedTpetra_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp

Kokkosify the blocked tpetra gather/scatter in #2497 
Tested on CUDA/P100, KNL and Broadwell.
Closes #2497 

Issue 2497 final

---

packages/panzer/adapters-stk/test/stk_connmngr/tEpetraLinearObjFactory.cpp
packages/panzer/adapters-stk/test/stk_connmngr/tSquareQuadMeshDOFManager.cpp
packages/panzer/adapters-stk/test/stk_connmngr/tSquareTriMeshDOFManager.cpp
packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp
packages/panzer/dof-mgr/src/Panzer_Filtered_UniqueGlobalIndexer_impl.hpp
packages/panzer/dof-mgr/test/dofmngr_test/tFilteredUGI.cpp

Fix for the tie-break rule used by Panzer.

Panzer: Tie-break fix

---

packages/tpetra/tsqr/src/Tsqr_CombineNative.hpp

TSQR: Fix #2668

---

packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_Element.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp

Assemble RHS in finite element assemble examples 
So examples are more complete
* Closes #2660
Tpetra tests pass locally with gcc7.2.0/openmpi3.0.0

Tpetra: Assemble RHS in finite element assemble examples (#2660)

---

packages/panzer/disc-fe/src/Panzer_FaceToElement.hpp
packages/panzer/disc-fe/src/Panzer_FaceToElement_impl.hpp

fix some cuda warnings for FaceToElement object

Panzer: fix cuda warnings in FaceToElement

---

packages/tpetra/core/test/ImportExport/ImportBug5430Test.cpp

@trilinos/tpetra Fix #2681: Don't create Kokkos::View (or things that contain them) at main() scope, since their destructors will get called before Kokkos::finalize gets called.  The test was otherwise fine.  As soon as I moved the objects to be created and destroyed before Kokkos::finalize was called, the test passed.

Tpetra: Fix #2681 (test randomly timing out w/ CUDA)

---

sampleScripts/Sandia-SEMS/configure-testbeds-jenkins-all

Set MueLu_ENABLE_Epetra=OFF
See issue #2319 for discussion regarding this setting.

Update Kokkos integration testing script

---

packages/panzer/disc-fe/src/Panzer_ZeroSensitivities.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp

Kokkosify Scatter Dirichlet BCs for Blocked Tpetra
Also contains a commit to fix some cuda warnings in the ZeroSensitivities functions.
Passes on OpenMP and CUDA
Clean on valgrind

Issue 2697

---

packages/panzer/mini-em/example/BlockPrec/main.cpp
packages/panzer/mini-em/src/closures/MiniEM_ClosureModel_Factory_impl.hpp

Total EM energy is printed to screen as a sanity check to make sure the app is
running correctly.
Also printing energy/dt^2 which should be approximately the same over different parameter regimes.
Both metrics should increase quickly up to ten time-steps and then level out by twenty time-steps.
Computing 1/2(epsilon*||E||^2 + 1/mu*||B||^2) as a response.
Anyone running the app can check the diagnostics to see if the app is running properly.

Added a total electromagnetic energy diagnostic to mini-em

---

packages/muelu/doc/Tutorial/src/MueLu_Agg2VTK.py
packages/muelu/doc/Tutorial/src/hands-on.py
packages/muelu/doc/Tutorial/tex/prepareTexTutorial.py
packages/muelu/research/q2q1/status.py
packages/muelu/research/tawiesn/crada/genFiles.py
packages/muelu/src/Interface/FacadeClasses/escapeXMLfile.py
packages/muelu/utils/analysis/albany_log2yaml.py
packages/muelu/utils/analysis/analysis.py
packages/muelu/utils/analysis/drekar-aztec-analysis.py
packages/muelu/utils/analysis/drekar-aztecoo-log2yaml.py
packages/muelu/utils/analysis/drekar-belos_log2yaml.py
packages/muelu/utils/analysis/log.py
packages/muelu/utils/analysis/log2yaml.py
packages/muelu/utils/analysis/muelu_log2yaml.py
packages/muelu/utils/analysis/tableau.py
packages/muelu/utils/genClass/genClass.py

Muelu: script cleanup

---

packages/tempus/src/Tempus_StepperFactory.hpp

Tempus: List available Steppers if requested one is not found.

---

packages/rythmos/src/Rythmos_StepperBase_decl.hpp

@trilinos/rythmos 
explicitly set `Rytmos::StepperBase`  `isEmbeddedRK_ = false` as default.
Needed for Drekar RK stepper ramping
All tests passed

Rythmos: set `isEmbeddedRK_ = false` as default

---

packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_commandLineOpts.hpp

Small change, I'm just adding a `--repetitions=N` argument to FEM Assembly examples to enable repetition in the Finite Element Mesh Assembly example of N times in a single run for timings.  
Default = 1.

Tpetra: Add repetition capability to FEM Assembly Examples

---

packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorLocalDeepCopy.hpp

Tpetra: Adding label to LocalDeepCopy

---

packages/ifpack2/src/Ifpack2_Relaxation_decl.hpp
packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp

Ifpack2: Removing Experimental guards around Multithreaded GS

---

packages/tempus/src/Tempus_RKButcherTableau.hpp
packages/tempus/src/Tempus_RKButcherTableauBuilder_impl.hpp
packages/tempus/src/Tempus_StepperDIRK_decl.hpp
packages/tempus/src/Tempus_StepperDIRK_impl.hpp
packages/tempus/src/Tempus_StepperFactory.hpp
packages/tempus/src/Tempus_StepperImplicit_decl.hpp
packages/tempus/src/Tempus_TimeStepControlStrategyPID.hpp
packages/tempus/src/Tempus_TimeStepControl_impl.hpp
packages/tempus/test/DIRK/Tempus_DIRKTest.cpp
packages/tempus/test/DIRK/Tempus_DIRK_SinCos.xml
packages/tempus/test/DIRK/Tempus_DIRK_VanDerPol.xml
packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp

Adds embedded  DIRK capability to Tempus.
Add adaptive time stepping capability.
* Closes 
* Blocks 
* Is blocked by #2219 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
All tests passing. DIRK test has been updated to include embedded DIRK.
[Wednesday-2018-02-14-16_25-build_tempus_dev-test.log](https://github.com/trilinos/Trilinos/files/1725995/Wednesday-2018-02-14-16_25-build_tempus_dev-test.log)

Embedded dirk

---

packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.cpp
packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.hpp
packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp

Added an unsorted pair merge algorithm and set up the code to to call that if the lists aren't sorted.

Added unsorted merge function

---

packages/muelu/utils/analysis/analysis.py
packages/muelu/utils/analysis/muelu_log2yaml.py

Introduces command line filtering in `setup_timers`. And fixes the update in `transitions` python package.
No testing required.

Muelu analysis update

---

cmake/ctest/drivers/atdm/README.md

some edits to the documentation on how to add a new ATDM system
Visual inspection of the document on my fork

edits to ATDM 'add new system' documentation

---

packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp

Ifpack2: Minor improvements to Chebyshev (Take 2)

---

packages/muelu/test/scaling/Driver.cpp

MueLu: Add more cuda diagnostic control

---

packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp
packages/ifpack2/src/Ifpack2_Relaxation_def.hpp

Ifpack2: More timer fixes

---

packages/rol/src/status/ROL_StatusTest.hpp

ROL Trilinos Sync 24-May-2018 for Drekar

---

packages/zoltan2/sampleScripts/configure_blake

The script added loads necessary modules and sets cmake configuration settings appropriately in order to successfully build Trilinos on the blake platform.
This change allows a blake user to quickly set up a Trilinos development environment.
I have built Trilinos using this script, and run the tests on blake to verify that everything was working. All tests passed, and Trilinos built successfully.

zoltan2: Added a configuration script that can be used to build Trilinos on blake

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp

Removes shadow warnings and sign/unsigned comparison. It passes seq and cuda build.

Removes warnings Ifpack2. 

---

packages/xpetra/sup/Utils/Xpetra_TripleMatrixMultiply.hpp

Fix issue with undefined variable when Epetra specialization of triple matrix product is used without Tpetra.

Xpetra: Fix triple matrix product for epetra builds

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

this fixes issue #2871 and will build ifpack2 with complex. as PR testing does not support complex, PR testing here should pass.

Ifpack2 - put complex into instanciataion list

---

packages/intrepid2/src/Orientation/Intrepid2_OrientationDef.hpp

These were triggering in almost every panzer kernel.

Intrepid2: remove shadow warnings #2878

---

packages/teuchos/comm/src/Teuchos_StackedTimer.hpp

Teuchos: Integrating Kokkos Profiling into StackedTimer

---

packages/muelu/test/scaling/Driver.cpp

MueLu: Adding equilibration option to Driver

---

cmake/ctest/drivers/dorksaber/sendTestSummary.sh

And now to watch the autotester needlessly chew on this...

Ctest/Drivers: dorksaber email update

---

packages/muelu/test/scaling/CMakeLists.txt
packages/muelu/test/scaling/JacobiKernelDriver.cpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp

MueLu/Tpetra: Jacobi Scaling driver + improved timers & algorithm control

---

packages/muelu/test/scaling/JacobiKernelDriver.cpp

MueLu: Slight diagnostic improvement in JacobiKernelDriver

---

packages/muelu/test/scaling/Driver.cpp

MueLu: Workaround for #2894

---

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp

Add no-QR option for nullspaces of dimension > 1 to `MueLu_TentativePFactory_kokkos`.
The current QR implementation allocates too much scratch memory for RefMaxwell runs on Cuda which leads to an error. Disabling the QR altogether can circumvent this issue until we have a better Kokkos QR. The default behavior has not been changed.

MueLu TentativePFactory_kokkos: Add no-QR option for NSDim>1

---

packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp
packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixUQPCEUnitTest.hpp

Stokhos:  Remove unused typedefs in some tests.

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp
packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp

Tpetra: More option renaming fixes

---

packages/seacas/libraries/ioss/src/generated/Iogn_GeneratedMesh.C
packages/seacas/libraries/ioss/src/generated/Iogn_GeneratedMesh.h

The `{}` initializer on `rotmat` was causing issues on the IBM compiler. Making `rotmat` a std::array of std::array's eliminates need for initializer and should eliminate issues on IBM. See #2789 

Eliminate need for initializer for rotmat

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp

MueLu: fix RefMaxwell compilation on CUDA

---

packages/muelu/test/scaling/CMakeLists.txt
packages/muelu/test/scaling/TwoMatrixMMKernelDriver.cpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp

MueLu: Yet another thread scaling test

---

cmake/std/PullRequestLinuxGCCTestingSettings.cmake
cmake/std/sems/PullRequestGCC4.8.4TestingEnv.sh
cmake/std/sems/PullRequestGCC4.9.3TestingEnv.sh
cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh

This will close issue #2065
Scotch is in use in multiple downstream applications

PullRequestLinuxGCCTestingSettings.cmake: add scotch to all PR builds

---

packages/muelu/test/scaling/CMakeLists.txt
packages/muelu/test/scaling/MatvecKernelDriver.cpp

MueLu: Another kernel test

---

packages/muelu/test/scaling/Driver.cpp

MueLu: More Driver upgrades

---

cmake/ctest/drivers/rocketman/cron_driver.sh
cmake/ctest/drivers/rocketman/crontab

Auto-PR for SHA 06a04b2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/2971)

update rocketman scripts

---

packages/belos/xpetra/src/Belos_Details_Xpetra_registerSolverFactory.cpp

Fixes compile errors when Tpetra was disabled.
Small modification so the new DII Xpetra code will work for Epetra on, Tpetra off.
Fix compilation.

Belos: Fix DII for Tpetra off (#2483)

---

packages/muelu/test/scaling/Driver.cpp

In 726134efcb the behaviour of the Driver was changed to not do any solves by default. This restores the previous behaviour.

Muelu: restore driver behaviour to do at least one solve

---

packages/muelu/src/Rebalancing/MueLu_RepartitionHeuristicFactory_def.hpp

I checked this locally and it does the right thing. I would appreciate an extra pair of eyes to make sure I'm not missing corner cases.

Muelu: fix #2977

---

cmake/ctest/drivers/dorksaber/sendTestSummary.sh

Ctest: Changing email on dorksaber driver

---

cmake/ctest/drivers/rocketman/sendTestSummary.sh

Auto-PR for SHA 85103a3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/2992)

testing: rocketman: fix path spec

---

cmake/ctest/drivers/rocketman/TrilinosCTestDriverCore.rocketman.gcc.cmake

Auto-PR for SHA 675d1b2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/2997)

Specify blas/lapack locations for rocketman

---

packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp

@trilinos/tpetra @mhoemmen 
First draft of local transpose multithreading.
Related to #2236.
Things I'm not sure about (and have not thought much):
1. While the class is called `RowMatrixTranposer`, it really only works for crs matrices. Should the row matrix path in local transpose be removed?
2. I'm not sure about using all those atomics.
3. I assume it would be nice to do 2-level parallelism.
4. The tests pass but I'm not sure if I'm running them right. I did add OMP_NUM_THREADS to environment when running, but maybe I need to do more.

Tpetra: multithread local matrix transpose

---

packages/minitensor/src/MiniTensor_Storage.h

@trilinos/minitensor
Marked several functions as KOKKOS_INLINE_FUNCTIONS who had callers that were also KOKKOS_INLINE_FUNCTIONS. Previously, this caused a lot of problems when building in debug with RDC=on.
Compile time errors using minitensor::Tensor<double,3>, for example. These errors could only be fixed by marking these methods as KOKKOS_INLINE_FUNCTIONS.
- [ x] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.
@mhoemmen @ibaned 
https://github.com/trilinos/Trilinos/issues/1264

Mark minitensor storage functions as KOKKOS_INLINE_FUNCTIONS [had callers that were KOKKOS_INLINE_FUNCTIONS]

---

packages/teuchos/comm/src/Teuchos_RawParameterListHelpers.cpp
packages/teuchos/comm/src/Teuchos_RawParameterListHelpers.hpp
packages/teuchos/comm/test/ParameterList/ParameterList_UnitTest_Parallel.cpp

Teuchos: Adding capability to broadcast & update parameterlists

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/src/Utils/MueLu_AvatarInterface.cpp
packages/muelu/src/Utils/MueLu_AvatarInterface.hpp

MueLu: More Avatar interface placeholders

---

packages/muelu/src/Utils/MueLu_AvatarInterface.cpp
packages/muelu/src/Utils/MueLu_AvatarInterface.hpp

MueLu: More Avatar Updates

---

cmake/ctest/drivers/rocketman/ctest_linux_nightly_mpi_release_muelu_rocketman.cmake

Auto-PR for SHA cea9f5e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3025)

testing: rocketman: add cdash testing track spec

---

packages/teuchos/parameterlist/src/Teuchos_YamlParser.cpp
packages/teuchos/parameterlist/test/yaml/YamlParameterList.cpp

See #3023 for user issue,
this PR adds both a reproducing unit test
and a fix to the YAML ParameterList builder.
This PR fixes and adds a test for flow-style maps in YAML files defining a Teuchos ParameterList.
As seen in #3023, users find it useful to be able to express parameters in flow style.
Also I never intended for this to not work, so in some sense it is an oversight bug.
A custom build of Teuchos passed all unit tests including the one added.

Fix YAML flow maps

---

packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp

Getting rid of a shadowing definition of "ac_status" that was accidentally added when implementing OpenMP LTG triple product.
Luckily this one was benign (in the parallel versions ac_status is declared inside the loop over R's rows).

Tpetra: fix shadow warning (#3038)

---

packages/panzer/adapters-stk/test/model_evaluator/response_residual.cpp

needed a slight change to tolerance

Panzer: fix failing test #3064

---

packages/belos/epetra/test/BlockCG/CMakeLists.txt

The random right hand side vector used to perform these tests can sometimes require
a few more iterations of preconditioned CG than normal.  Normal is about 87 and the
maximum iterations is set at 100.  Some random right hand sides require 104 iterations.
It is not an issue with the solver, but the linear system being solved.  Thus, this
commit increases the maximum iterations to 110 to give the preconditioned CG solver
more iterations if the right hand side vector is not as easy to solve for.
This will address the test failures in issues #2920 and #3007 
This has been tested on White/Ride and addresses the test failures that were observed on those platforms.

Increase maximum number of iterations to address issues #2920 and #3007

---

packages/anasazi/src/AnasaziStatusTestResNorm.hpp
packages/anasazi/src/AnasaziStatusTestWithOrdering.hpp

User issue with missing header include (Teuchos_LAPACK.hpp) in AnasaziStatusTestResNorm file.  Found header in different residual norm header that does not use Teuchos::LAPACK, so header was moved.
Fixes build error for user.
OS X laptop, serial build, GCC 7.x compiler.

Adding Teuchos_LAPACK header to address build issue #3040

---

packages/amesos2/test/solvers/Basker_UnitTests.cpp
packages/amesos2/test/solvers/ShyLUBasker_UnitTests.cpp

This is a follow up to #3094 by @mhoemmen to pattern match Tpetra
changes (relevant to issue #57) made by PR #3094 to a unit test file
added after that PR was submitted.

Amesos2: Update ShyLUBasker tests for Tpetra changes

---

packages/piro/src/Piro_NOXSolver.hpp
packages/piro/src/Piro_NOXSolver_Def.hpp
packages/piro/src/Piro_PerformAnalysis.cpp
packages/piro/src/Piro_SteadyStateSolver.hpp
packages/piro/src/Piro_SteadyStateSolver_Def.hpp
packages/piro/test/CMakeLists.txt
packages/piro/test/Main_AnalysisDriver_Tpetra.cpp
packages/piro/test/MockModelEval_A_Tpetra.cpp
packages/piro/test/MockModelEval_A_Tpetra.hpp
packages/piro/test/_input_Analysis_ROL_AdjointSensitivities.xml
packages/piro/test/_input_Analysis_ROL_AdjointSensitivities_Tpetra.xml
packages/piro/test/_input_Analysis_ROL_Tpetra.xml
packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective.hpp
packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp

Piro: Implemet adjoint sensitivities for Piro::NoxSolver (Thyra stack). Issue #3088
The adjoint system is solved by implicitly transposing the Jacobian operator and its preconditioner operator (thanks to @bartlettroscoe for the helping me with this).
This contains also a fix for update logic in ROL Thyra adapter, as well as a fix to allow Belos Thyra adapter to correctly select left/right preconditioner by @bartlettroscoe .

Piro Thyra Sensitivities

---

packages/shylu/shylu_dd/frosch/test/CMakeLists.txt

This PR disables the three tests causing trouble; cf. #3106.

Disabling three critical tests.

---

cmake/std/atdm/chama/tweaks/INTEL-DEBUG-OPENMP.cmake
cmake/std/atdm/chama/tweaks/INTEL-RELEASE-OPENMP.cmake
cmake/std/atdm/serrano/tweaks/INTEL-DEBUG-OPENMP.cmake
cmake/std/atdm/serrano/tweaks/INTEL-RELEASE-OPENMP.cmake

These tests used a bad norm comparison that was causing the test to
look like it failed, when it didn't.  These tests were disabled by
commits cbb56a7 and 5be802c, and are being manually enabled again.
The resolve tests were using a bad norm approximation to determine whether the same linear system, solved again by the same solver object, resulted in the same answer.  This comparison has been fixed to be the correct norm and exact norm, not an approximation.
The tests with this bad comparison were failing on Chama and Serrano and were turned off on those platforms for ATDM (issue #2965 ).  Now that the tests have been fixed, they can be re-enabled.
Belos tests were failing on Chama and Serrano, now they are not.  So the tests can be enabled again.
On Chama and Serrano …

Re-enabling Belos tests on Chama/Serrano that were failing.

---

packages/panzer/adapters-stk/test/local_mesh/PanzerSTK_UnitTest_BuildMesh.cpp
packages/panzer/adapters-stk/test/stk_connmngr/tDOFManager2_SimpleTests.cpp
packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp
packages/panzer/mini-em/src/eqn_sets/MiniEM_OperatorRequestCallback.cpp
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp

Remove use of Tpetra::DefaultPlatform from Panzer

Panzer: remove use of Tpetra::DefaultPlatform #3119

---

packages/rol/example/PinT/tanks/CMakeLists.txt

@trilinos/rol 
Another bug fix related to Trilinos issue #3045.
Trilinos issue #3045.
Trilinos check-in tests, performed in ROL-Trilinos and in the Trilinos fork.

ROL Trilinos Sync 17-Jul-2018

---

packages/muelu/test/perf_tests_kokkos/Redirection.cpp

Auto-PR for SHA c87c9f7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3144)

MueLu: fix compile failure in tests

---

packages/muelu/adapters/CMakeLists.txt
packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_decl.hpp
packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_def.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/src/Misc/MueLu_RAPFactory_def.hpp
packages/muelu/src/Misc/MueLu_ThresholdAFilterFactory_decl.hpp
packages/muelu/src/Misc/MueLu_ThresholdAFilterFactory_def.hpp

- Forward hierarchy label to Tpetra in RAPFactory: Important when several MueLu hierarchies are built
- Fix performance bug in Thyra-RefMaxwell factory
- Make shifted Laplacian experimental (Issue #2608)
- Fix build error in RefMaxwell when Epetra in on, but no matching Tpetra instantiation is available (Issue #3032)

MueLu: RefMaxwell diverse

---

packages/muelu/research/mmayr/composite_to_regions/src/CMakeLists.txt
packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_def.hpp
packages/muelu/test/scaling/MatvecKernelDriver.cpp
packages/muelu/test/unit_tests/BlockedRepartition.cpp

Auto-PR for SHA 63e4204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3161)

Fix issue#3035

---

packages/ifpack2/doc/UsersGuide/options.tex
packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp

Also fixed the actual default BlockRelaxation container type
(set in getValidParameters()) from "TriDi" to "Dense" to match the documentation,
comments and value set in the constructor.
In options.tex for the Ifpack2 user's guide, added brief documentation for the BlockRelaxation parameters that were missing. Did not add the "schwarz: ..." options, which are valid (added to list in BlockRelaxation::getValidParameters()) but whose values are never used, so there is no reason for users to care about them.
The section of the user's guide about BlockRelaxation was out of date and it was necessary to look at source code to find the full set of valid parameters and their meanings.

Ifpack2: updated block relaxation options in user's guide (Fix #971)

---

packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp

TrilinosCouplings: Merge to muelu-avatar branch

---

packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_decl.hpp
packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_def.hpp
packages/muelu/src/Graph/StructuredAggregation/MueLu_IndexManager_decl.hpp
packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_decl.hpp
packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp
packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_GlobalLexicographicIndexManager_decl.hpp
packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_GlobalLexicographicIndexManager_def.hpp
packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_decl.hpp
packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp
packages/muelu/src/Graph/StructuredAggregation/uncoupled/MueLu_UncoupledIndexManager_decl.hpp
packages/muelu/src/Graph/StructuredAggregation/uncoupled/MueLu_UncoupledIndexManager_def.hpp
packages/muelu/test/unit_tests/StructuredAggregationFactory.cpp
packages/xpetra/src/CrsGraph/Xpetra_CrsGraphFactory.hpp
packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp

Added CRS graph containing coarsening data for linear interpolation with structured aggregation.

MueLu: crs coarse data

---

packages/muelu/test/scaling/Driver.cpp

Auto-PR for SHA 47d8a9b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3187)

Update MueLu Driver

---

packages/muelu/test/unit_tests/Adapters/BelosAdapters.cpp
packages/muelu/test/unit_tests/GeneralGeometricPFactory.cpp

Auto-PR for SHA deb829b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3197)

fix MueLu testing (try 2)

---

cmake/std/GCC-4.8.4-OpenMPI-1.10.1-MpiReleaseDebugSharedPtOpenMP.cmake
cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake
cmake/std/PullRequestLinuxIntelTestingSettings.cmake
cmake/std/atdm/ATDMDevEnvSettings.cmake

Auto-PR for SHA 62fa666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3172)

reenable MueLu unit tests w/ Tpetra and OpenMP

---

packages/muelu/test/maxwell/Maxwell3D.cpp

Auto-PR for SHA 7401ff1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3200)

Modify MueLu Maxwell test

---

packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
packages/tempus/src/Tempus_Interpolator.hpp

A couple small changes needed while creating a reduced-space interface for ROL with Tempus.

Small Tempus fixes to support ROL-Tempus interface

---

packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml

- Fix malformed input XML for MiniEM
- Add additional CMake guards for tests requiring Epetra support from MueLu
* Addresses #3182

MiniEM fixes

---

cmake/std/atdm/README.md

CC: @fryeguy52, @gsjaardema 
Hopefully this documentation will allow any Trilinos developer to selectively
disable tests for the ATDM Trilinos builds.
Hopefully this documentation will allow a Trilinos developer to disable tests
as part of #3183 but this will be used in many future issues as well.
Likely the best way to review this documentation update is with the GitHub rendering of the new section at:
* https://github.com/bartlettroscoe/Trilinos/blob/3183-disable-tests-info/cmake/std/atdm/README.md#disabling-failing-tests
Need to provide information so that regular Trilinos developers can correctly disable tests for specific ATDM Builds and platforms.  An immediate motivating example is #3183.
I read over the document and clicked links at:
* …

Add documentation on how to disable tests (#3183, TRIL-171)

---

packages/muelu/src/Misc/MueLu_RAPFactory_def.hpp
packages/muelu/test/unit_tests/RAPFactory.cpp

Auto-PR for SHA 0037842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3221)

Fix zero-diagonal problem

---

packages/piro/src/Piro_NOXSolver_Def.hpp
packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective.hpp

@trilinos/piro @trilinos/rol 
Fix for enabling compilation with Clang 6. Added template keyword in Piro::NOXSolves when calling template member function of a Teuchos::ParameterList.
Also fixed a typo in ROL::ThyraProductME_Objective constructor that was generating a warning.
Closes issue #3157

Piro fix for building with Clang 6

---

packages/panzer/dof-mgr/src/Panzer_UniqueGlobalIndexer_EpetraUtilities_impl.hpp
packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp

@trilinos/panzer @trilinos/xpetra 
* Fix issue in creation of Epetra coordinates in Panzer.
* Fix bug in Xpetra's `MultiVector::scale` for Epetra.
* Addresses #3176, #3247

Bug fixes for MiniEM+MueLu-RefMaxwell+Epetra

---

packages/tempus/src/Tempus_Stepper.hpp
packages/tempus/src/Tempus_StepperOperatorSplit_impl.hpp

A simple change to allow StepperOperatorSplit to work without a ModelEvaluator.
EMPIRE will have two steppers that do not have an ModelEvaluator.  Tempus should still work in this situation.
Have tested on my Mac and it passes all tests.

Tempus: Allow StepperOperatorSplit to run without any ModelEvaluators.

---

packages/tempus/src/Tempus_StepperOperatorSplit_decl.hpp
packages/tempus/src/Tempus_StepperOperatorSplit_impl.hpp

Tempus: Adding method to set the temp state.

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/src/Misc/MueLu_RAPFactory_def.hpp
packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp

Auto-PR for SHA 797d3d0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3294)

MueLu: fix for EMPIRE segfault

---

packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.cpp
packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.h
packages/ml/src/Utils/ml_epetra_utils.cpp
packages/ml/test/RefMaxwell/cxx_main.cpp

PLEASE DO NOT MERGE.
I need to check another app first.  I just want to get the autotester baking...

ML: Refmaxwell Fixes

---

packages/trilinoscouplings/examples/scaling/CMakeLists.txt
packages/trilinoscouplings/examples/scaling/HybridIntrepidPoisson2D_Pamgen_Tpetra_main.cpp
packages/trilinoscouplings/examples/scaling/HybridIntrepidPoisson3D_Pamgen_Tpetra_main.cpp
packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson2DExample.cpp
packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson2DExample.hpp
packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson3DExample.cpp
packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson3DExample.hpp
packages/trilinoscouplings/examples/scaling/muelu_hybrid_aggregation_2D.xml
packages/trilinoscouplings/examples/scaling/muelu_hybrid_aggregation_3D.xml
packages/trilinoscouplings/examples/scaling/muelu_structured_aggregation.xml

The addition of a driver for MueLu's hybrid aggregation
A good example of how to set up and call MueLu's hybrid aggregation

Trilinos couplings hybrid examples

---

packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp

Replace deprecated Kokkos::View::dimension_0() with View::extent_0().

Tpetra: replace deprecated View::dimension_0

---

packages/tempus/src/Tempus_SolutionState_decl.hpp
packages/tempus/src/Tempus_SolutionState_impl.hpp
packages/tempus/src/Tempus_StepperOperatorSplit_impl.hpp

SolutionData is everything except the metaData.  This is useful when one needs to keep the metaData in-place (i.e., currentState and workingState with their timestep and index) but need the solution (x, xdot, xdotdot) and related data (StepperState, PhysicsState) to be swapped.
No new test has been added to Tempus to cover this, but has been tested in EMPIRE.

Tempus: Add function to swap solutionData between states.

---

packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_SumOperator_def.hpp

Fix for the bug reported in issue #3326.

ShyLU: Adding namespace std to cerr

---

cmake/std/PullRequestLinuxDriver.sh

These are not the ones causing us issues, but they were also not
what they need to be.

PullRequestLinuxDriver.sh: change proxy environment variables per CEE

---

packages/muelu/test/helmholtz/Helmholtz1D.cpp
packages/muelu/test/helmholtz/Helmholtz2D.cpp
packages/muelu/test/helmholtz/Helmholtz3D.cpp
packages/muelu/test/helmholtz/HelmholtzFEM2D.cpp
packages/muelu/test/helmholtz/HelmholtzFEM3D.cpp

more fix for the Helmholtz tests.

MueLu: Fix#3378

---

packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_decl.hpp

This seems to be the final fix needed, this ones takes care of a very special path in MueLu_Zoltan2Interface...

MueLu: fix #3378

---

packages/tempus/src/Tempus_StepperBDF2_impl.hpp
packages/tempus/src/Tempus_StepperBackwardEuler_impl.hpp
packages/tempus/src/Tempus_StepperDIRK_decl.hpp
packages/tempus/src/Tempus_StepperDIRK_impl.hpp
packages/tempus/src/Tempus_StepperExplicitRK_decl.hpp
packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
packages/tempus/src/Tempus_StepperForwardEuler_decl.hpp
packages/tempus/src/Tempus_StepperForwardEuler_impl.hpp
packages/tempus/src/Tempus_StepperHHTAlpha_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_Partition_decl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_decl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
packages/tempus/src/Tempus_StepperImplicit_impl.hpp
packages/tempus/src/Tempus_StepperLeapfrog_decl.hpp
packages/tempus/src/Tempus_StepperLeapfrog_impl.hpp
packages/tempus/src/Tempus_StepperNewmarkExplicitAForm_decl.hpp
packages/tempus/src/Tempus_StepperNewmarkExplicitAForm_impl.hpp
packages/tempus/src/Tempus_StepperNewmarkImplicitAForm_impl.hpp
packages/tempus/src/Tempus_StepperNewmarkImplicitDForm_impl.hpp
packages/tempus/src/Tempus_StepperOperatorSplit_impl.hpp
packages/tempus/src/Tempus_StepperTrapezoidal_impl.hpp

@trilinos/@tempus
Several Steppers did not call some set* functions, thus
Steppers might not be fully initialized.  Biggest offender
was DIRK.
#3400
This was noted when a DIRK stepper was not completely initialized, especially the solver.
It passes all current tests.

Tempus: Ensure Steppers get fully initialized.

---

packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_def.hpp
packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp
packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_decl.hpp
packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp

This PR implements a piece-wise linear interpolation transfer operator in GeometricInterpolationPFactory
This allows us to use piece-linear interpolation in MG which is more accurate than piece-wise constant interpolation
* Closes #3179
* Related to #3227 #2230
This has been tested using trilinosCouplings examples

MueLu geometric interpolation linear

---

packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
packages/zoltan2/src/problems/Zoltan2_MatchingProblem.hpp
packages/zoltan2/src/problems/Zoltan2_PartitioningSolution.hpp
packages/zoltan2/test/correctness/zoltanCompare.cpp
packages/zoltan2/test/driver/test_driver.cpp
packages/zoltan2/test/helpers/PrintData.hpp
packages/zoltan2/test/helpers/Zoltan2_ComparisonHelper.hpp
packages/zoltan2/test/partition/APFMeshAdapterTest.cpp
packages/zoltan2/test/partition/MultiJaggedTest.cpp
packages/zoltan2/test/partition/PartitionAndParMATest.cpp
packages/zoltan2/test/partition/TaskMappingProblemTest.cpp
packages/zoltan2/test/partition/TaskMappingSimulate.cpp
packages/zoltan2/test/partition/TaskMappingTest.cpp
packages/zoltan2/test/partition/rcbPerformanceZ1.cpp
packages/zoltan2/test/partition/taskMappingTest3.cpp
packages/zoltan2/test/scaling/rcbPerformance.cpp
packages/zoltan2/test/scaling/rcbPerformanceZ1.cpp
packages/zoltan2/test/temp/multivectorTest.cpp
packages/zoltan2/test/temp/paramTest.cpp
packages/zoltan2/test/unit/environment/AllParameters.cpp
packages/zoltan2/test/unit/input/XpetraCrsMatrixInput.cpp
packages/zoltan2/test/unit/models/CoordinateModel.cpp
packages/zoltan2/test/unit/models/GraphModel.cpp
packages/zoltan2/test/unit/util/Metric.cpp

On white, some files that compile fine elsewhere had compilation errors.  All errors were fixed by replacing cout with std::cout, endl with std::endl, and cerr with std::cerr.
Need to compile on white.
Built on white with gcc 7.2 and cuda 9.2

Zoltan2:  fixed some trivial compile errors on white

---

packages/nox/src/NOX_Solver_SingleStep.H
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp

cleaning up a few comments in doxygen documentation

NOX/Panzer: Cleanup comments

---

packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp

This PR follows-up on #3368.
There, one Tpetra test failed when SCALAR=FLOAT, because of tolerances used for comparisons. @csiefer2 suggested the tolerance changes that are incorporated into this one test.
The test now passes with SCALAR = FLOAT or DOUBLE.

Tpetra follow-up to #3368

---

packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp

Problem is described in #3417 
The possible explanation of this problem is a compiler bug. ``const int`` variable is changed in the middle of a function.
#3417 
I tested on white with the ATDM script. All tpetra tests are passed.
This error comes from a POWER system and it is not revealed from the previous PR test nor from x86 systems as the PR test does not include POWER systems.

Fix (workaround) DGEMM issue in kokkos kernels.

---

packages/nox/src-thyra/NOX_Thyra_Group.C
packages/nox/src-thyra/NOX_Thyra_Group.H
packages/nox/src/NOX_Abstract_Group.C
packages/nox/src/NOX_Abstract_Group.H
packages/nox/test/epetra/Thyra/Thyra_SingleStepSolver_1D.C

first step towards better statistics gathering in nox solvers

Nox: add linear solver statistics to nox group

---

packages/muelu/test/unit_tests/Smoothers/BlockedDirectSolver.cpp

MueLu: Fixing ifdef guards

---

packages/teuchos/parameterlist/src/Teuchos_ParameterList.cpp
packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp
packages/teuchos/parameterlist/test/ParameterList/ParameterList_UnitTests.cpp

Created unit test to test ParameterLists with the same entries but different orderings.
Added extra ParameterLists entry for the `haveSameValues` unit test to ensure that ordering is being tested.
* Suggested reviewer: @bartlettroscoe 
* Package: @trilinos/Teuchos
* Resolves: Issue #3319 

Teuchos:  Created function to compare ParameterLists independent of ordering.

---

packages/nox/test/epetra/Brusselator/Example.C

NOX: fix brusselator test for serial build #3449

---

packages/panzer/adapters-stk/example/MixedPoissonExample/Example_MixedPoissonEquationSet_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp
packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_CurlCurl_impl.hpp

Refactors `panzer::Integrator_DivBasisTimesScalar` such that it now has a compile-time-argument-checking constructor which enables its use as a `CONTRIBUTES`-style `Evaluator`.  Also Kokkos-ifies the `evaluateFields()` routine.
Closes #1891 
Memory savings&mdash;see #1575.
Panzer/Drekar/Charon tests pass on my RHEL7 machine.

WIP:  Resolve "Panzer:  Update Integrator_DivBasisTimesScalar"

---

packages/amesos/src/Amesos_Superludist.cpp
packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp

This issue comes up with trilinos build with superlu_dist-6.0 [via xsdk] - and this patch fixes this issue.
cc: @jwillenbring

compile fixes for superlu_dit 6.0

---

packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
packages/muelu/test/unit_tests/Hierarchy.cpp

Auto-PR for SHA c9ce310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3498)

MueLu: improve unit test run times under CUDA

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/Misc/MueLu_RAPFactory_decl.hpp
packages/muelu/src/Misc/MueLu_RAPShiftFactory_decl.hpp
packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp
packages/muelu/src/MueCentral/MueLu_FactoryManager_def.hpp
packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/src/Utils/MueLu_Utilities.cpp
packages/muelu/test/unit_tests/RAPShiftFactory.cpp

MueLu: RAPShiftFactory, Take 3

---

packages/muelu/test/scaling/Driver.cpp

MueLu: Fixes to MueLu Driver to get complex stuff working

---

packages/muelu/test/unit_tests/CMakeLists.txt

Auto-PR for SHA 7f00aca
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3517)

MueLu: split unit tests into separate executables

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp

Tpetra: SpGEMM reuse mod

---

packages/muelu/test/scaling/CMakeLists.txt

Auto-PR for SHA 3b57c07
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3527)

MueLu: fix dashboard failures

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp

Auto-PR for SHA e5e47d7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3537)

MueLu: Xpetra: change behavior of fix zero diagonals

---

packages/trilinoscouplings/examples/ml/NonlinML/FiniteElementProblem.cpp

Auto-PR for SHA 00b5da7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3568)

TrilinosCouplings: fix issue #3551

---

packages/anasazi/src-rbgen/RBGen_Filter.hpp

@trilinos/anasazi @ikalash @davydden 
TODO cherry-pick into the 12.14 release branch once merged into develop.
NOTE these changes might not get exercised in pull request testing.
* Closes #3576

Anasazi: Fix #3576

---

packages/anasazi/src-rbgen/RBGen_Filter.hpp

@trilinos/anasazi @ikalash 
Cherry-pick my fix for #3576 (see PR #3584) into the 12.14 release branch. 
* Related to #3576, #3584

Anasazi: Fix #3576 in 12.14 release branch

---

packages/amesos/src/Amesos_Superludist.cpp
packages/amesos/test/TestOptions/TestSuperludist.cpp

@trilinos/amesos 
@balay 
This is a PR to apply the changes from PR #3209 to the trilinos-release-12-14-branch.
See PR #3209.

superlu_dist: compile fix for v5.4.0 on 12.14 branch

---

packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_impl.hpp

Switch `Integrator_GradBasisCrossVector` to support `CONTRIBUTES`-style evaluations, and Kokkos-ify.
Closes #1892 
I've tested Panzer locally.  We'll see how the @trilinos-autotester does.
Once this PR has been reviewed and approved, I will squash before merging.

Resolves "Panzer:  Update Integrator_GradBasisCrossVector"

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesTensorTimesVector.cpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesTensorTimesVector.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesTensorTimesVector_impl.hpp
packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
packages/panzer/mini-em/example/BlockPrec/main.cpp
packages/panzer/mini-em/example/BlockPrec/maxwell.xml
packages/panzer/mini-em/example/BlockPrec/maxwell2D.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell2D.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellOpenMP.xml
packages/panzer/mini-em/src/closures/MiniEM_ClosureModel_Factory_impl.hpp
packages/panzer/mini-em/src/closures/MiniEM_RandomForcing.hpp
packages/panzer/mini-em/src/closures/MiniEM_RandomForcing_impl.hpp
packages/panzer/mini-em/src/closures/MiniEM_TensorConductivity.hpp
packages/panzer/mini-em/src/closures/MiniEM_TensorConductivity_impl.hpp
packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_CurlCurl_impl.hpp
packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_MassMatrix_impl.hpp
packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell.hpp
packages/panzer/mini-em/src/eqn_sets/MiniEM_EquationSet_Maxwell_impl.hpp
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp

- Move hard coded MiniEM problem parameters to an input XML file.
- Add a Panzer evaluator `BasisTimesTensorTimesVector` and use it for a tensorial conductivity.
- Add random RHS to MiniEM.

MiniEM updates

---

packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_kokkos_def.hpp

Auto-PR for SHA 0ce4b35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3643)

MueLu: fix phase 3 aggregation under CUDA

---

cmake/std/PullRequestLinuxDriver.sh

@jwillenbring 	
Adding a debugging print to print out the contents of `JOB_BASE_NAME` in the GCC 4.9.3 SERIAL build script.

Framework: Debugging Dev->Master script

---

packages/teuchos/numerics/src/Teuchos_LAPACK.cpp
packages/teuchos/numerics/src/Teuchos_LAPACK.hpp
packages/teuchos/numerics/src/Teuchos_LAPACK_wrappers.hpp
packages/teuchos/numerics/test/LAPACK/cxx_main.cpp

The _PTEQR LAPACK method computes the eigenvalues of a positive-definite
symmetric tridiagonal matrix.  Several more LAPACK routines have been
added to the test, while debugging the LAPACK test failures on ride/white/waterman (see #2410).
Adding wrapper for _PTEQR to LAPACK to compute the eigenvalues of a positive-definite symmetric tridiagonal matrix.  Have extended LAPACK test to include more LAPACK wrappers.  It is, by no means, exhaustive.  Modest improvement at best.
The LAPACK test needs improvements and Belos needs a LAPACK routine for computing eigenvalues that will work on ride/white/waterman for the condition estimation computation.
Locally, using OS X and GCC 7.x compilers.

Commit updated LAPACK wrapper, with _PTEQR, expanded LAPACK test

---

packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_kokkos_def.hpp

Auto-PR for SHA 4e14f43
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3654)

MueLu: another aggregation Phase3 fix

---

packages/ml/src/Comm/ml_comm.c
packages/ml/src/Comm/ml_comm.h
packages/ml/src/Main/ml_struct.c
packages/ml/src/Main/ml_struct.h

Fix to allow user-supplied MPI_Comm in the C-API.
@trilinos/<ML>
Request review by @csiefer2 
The C-API for MLCreate was hard-coded to use MPI_COMM_WORLD which breaks MPMD uses.
Closes Issue #3565
I ran the application code in MPMD code to verify the previous error is no longer encountered.

ML: Issue 3565

---

cmake/std/PullRequestLinuxDriver.sh

@jwillenbring 	
@prwolfe 	
Resolves #3673

Framework: Bugfix on PullRequestLinuxDriver for SERIAL Tests

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake

Ctest: Rocketman experimental build fix

---

packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp
packages/muelu/test/unit_tests/Hierarchy.cpp

Auto-PR for SHA 7eb129a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3667)

MueLu: fix test that hangs under CUDA

---

packages/belos/epetra/test/FixedPoint/CMakeLists.txt
packages/belos/epetra/test/FixedPoint/test_fp_hb.cpp
packages/belos/src/BelosFixedPointIter.hpp
packages/belos/tpetra/test/FixedPoint/CMakeLists.txt
packages/belos/tpetra/test/FixedPoint/test_fp_hb.cpp

Add code path for right preconditioning in the Belos fixed point solver.
Addresses #3582

Belos fixed point solver: Allow right preconditioning

---

packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_Cn_FEM.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_Cn_FEM.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TET_Cn_FEM.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TET_Cn_FEMDef.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TRI_Cn_FEM.hpp
packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_TRI_Cn_FEMDef.hpp

Auto-PR for SHA a16f337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3685)

Intrepid2: fix CUDA warnings

---

packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_TRI_C2_FEM.hpp
packages/intrepid/src/Discretization/Basis/Intrepid_HGRAD_TRI_C2_FEMDef.hpp
packages/intrepid2/unit-test/Discretization/Basis/HDIV_TET_In_FEM/test_01.hpp
packages/piro/test/Piro_MatrixFreeDecorator_UnitTests.cpp

@trilinos/intrepid 
This pull request addresses test failures in Piro and Intrepid2 reported in issues #3633 and #2474 and #3681, and due to tight tolerances.

Minor fixes in Piro, Intrepid and Intrepid2

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake

Ctest: More rocketman

---

packages/teko/src/Teko_Utilities.cpp

Found a couple little bugs in the Teko utilities. First, a typo in the Tpetra version of explicit triple matrix product read in one of the input matrices wrong. Second, the blocked op version of explicit add was not writing to the supplied destination operator, but creating an RCP to a brand new linear op.
Discovered these bugs in using Teko tools in EMPIRE.
All existing Teko tests pass. These capabilities give the expected result in EMPIRE now.

Fixes for teko utilities

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake

Ctest: More rocketman fixes

---

packages/muelu/src/Rebalancing/MueLu_RepartitionFactory_def.hpp

Update `MpiTypeTraits` used in repartitioning for large unsigned global ordinals.
MueLu does not build if a user uses `unsigned long` or `unsigned long long` as global ordinals.

Muelu update mpi traits

---

packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter.hpp
packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter_Def.hpp
packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
packages/tempus/src/Tempus_IntegratorObserver.hpp
packages/tempus/src/Tempus_IntegratorObserverBasic_decl.hpp
packages/tempus/src/Tempus_IntegratorObserverBasic_impl.hpp
packages/tempus/src/Tempus_IntegratorObserverComposite_decl.hpp
packages/tempus/src/Tempus_IntegratorObserverComposite_impl.hpp
packages/tempus/src/Tempus_IntegratorObserverLogging_decl.hpp
packages/tempus/src/Tempus_IntegratorObserverLogging_impl.hpp
packages/tempus/src/Tempus_SolutionHistory_impl.hpp
packages/tempus/test/Observer/Tempus_ObserverTest.cpp

Made changes to reduce confusion related to
IntegratorObserver::acceptTimeStep().  acceptTimeStep() checked if
the timestep should be accepted or failed and promoting if passing.
“acceptTimeStep” was being read as a statement, "accept the timestep",
when it was meant as a question, “accept the timestep?”.  To reduce
this confusion, acceptTimeStep has been split into the determination
of the time step passing (now checkTimeStep()) and promotion of the
time step (now promoteWorkingState() is part of the Integrator time
loop).  Also two observers, observeAfterCheckTimeStep() and
observeEndTimeStep, have replaced the observeAcceptedTimeStep().
Work previously completed in observeAcceptedTimeStep() will likely
move into observeEndTimeStep(), unless it deals with the acceptance
of a time step …

Tempus: Improve Observer Names.

---

packages/muelu/CMakeLists.txt
packages/xpetra/CMakeLists.txt
packages/xpetra/test/BlockedCrsMatrix/CMakeLists.txt
packages/xpetra/test/BlockedMultiVector/CMakeLists.txt
packages/xpetra/test/Cloner/CMakeLists.txt
packages/xpetra/test/CrsMatrix/CMakeLists.txt
packages/xpetra/test/Map/CMakeLists.txt
packages/xpetra/test/Matrix/CMakeLists.txt
packages/xpetra/test/MatrixMatrix/CMakeLists.txt
packages/xpetra/test/MultiVector/CMakeLists.txt
packages/xpetra/test/Vector/CMakeLists.txt
packages/xpetra/test/Xpetra_UnitTests.cpp

MueLu/Xpetra: Kokkos_Refactor default changes; adding a native unit test wrapper to Xpetra which does Kokkos initialize/finalize

---

packages/muelu/test/scaling/conchas_milestone_zoltan2.xml
packages/muelu/test/scaling/conchas_milestone_zoltan2_complex.xml
packages/muelu/test/scaling/import.xml

Fixing a couple of tests as per issue #3717 simply changing logic in xml files to make them consistent with new kokkos refactor and removing a Chebyshev smoother call to avoid issue with complex type.
This fixes issue #3717 
* Part of #3717 
This has been tested locally using a build with `MUELU_ENABLE_KOKKOS_REFACTOR=ON` and `Trilinos_ENABLE_COMPLEX_DOUBLE=ON`

MueLu: kokkos openmp refactor tests fix

---

packages/muelu/src/Interface/MueLu_HierarchyManager.hpp

Auto-PR for SHA ccda718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3726)

MueLu: fix compiler warning

---

packages/muelu/src/Graph/MueLu_CoalesceDropFactory_kokkos_def.hpp
packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph.hpp

Auto-PR for SHA 380f868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3744)

Xpetra: fix compile error

---

packages/muelu/example/ParameterList/MLParameterList.cpp

Auto-PR for SHA 367881f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3747)

MueLu: fix build of example

---

packages/piro/test/Piro_MatrixFreeDecorator_UnitTests.cpp

Relaxed tolerance for test   Piro_MatrixFreeDecorator_UnitTests to fix issue #2474

Piro: Relax tolerance of MatrixFreeDecorator test to fix issue #2474

---

packages/muelu/utils/misc/makepr.sh

MueLu: makepr.sh updates

---

packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp
packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Epetra_main.cpp

@trilinos/muelu @trilinos/trilinoscouplings 
@jhux2 can you check this quickly, I have no clue why this started acting up recently, although the changes are fixing the build error in issue #3749.

TrilinosCouplings: fix issue #3749 by fully specifying template parameters of MueLu::Hierarchy

---

packages/muelu/src/Utils/MueLu_AvatarInterface.cpp

MueLu: Fixing Avatar interface warnings

---

packages/panzer/adapters-stk/example/CurlLaplacianExample/main.cpp
packages/panzer/adapters-stk/example/MixedPoissonExample/CMakeLists.txt
packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp
packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.cpp
packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOF_Functors.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOF_PointValues_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOF_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_FaceBasis.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_GatherNormals_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesTensorTimesVector.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_TransientBasisTimesScalar_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ProjectToEdges_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScalarToVector_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Sum.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Sum_impl.hpp
packages/panzer/disc-fe/src/responses/Panzer_ResponseScatterEvaluator_Probe_impl.hpp

This adds hierarchic parallelism to a subset of panzer.

Panzer hierarchic

---

packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp

Added an assert to catch an input error when the source field of an L2 projection is not in all element
blocks requested in the projection.
Also fixed a compiler warning and removed trailing whitespace.

Panzer: add error check to projection support

---

packages/panzer/disc-fe/src/Panzer_IntrepidOrientation.hpp

Went to all workset local index into orientation array

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake

Ctest: Rocketman eternal

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake

Ctest: Rocketman - A Sisyphean task?

---

packages/stk/stk_search/stk_search/Point.hpp

Fix nvidia compile issue in stk_search

---

packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp

MueLu: Fixes from rstumin

---

packages/teko/src/Teko_Utilities.cpp

Fixes to two Teko utilities functions:
- explicitMultiply with destination argument now writes to destOp for blocked linear ops
- modifiable blockedOp explicitAdd now returns a nonconst linear op
These functions were slightly wrong and use in EMPIRE exposed this.
All existing tests still pass. The functions work as expected now in EMPIRE.

Teko: Fixes in two utilities functions

---

packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.cpp
packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp

hierarchic support can now create a team policy

Panzer: hierarchic team policy

---

packages/seacas/libraries/ioss/src/visualization/ParaViewCatalystIossAdapter/parser/catalystParser.l
packages/seacas/libraries/ioss/src/visualization/ParaViewCatalystIossAdapter/parser/catalystParser.ypp

[changes from @tjotaha related to #3652 ]
Changed catalystParser.ypp interface to hide C++
class references for newer Bison versions > 2.7
Added C style comment for NTESS header in
catalystParser.l

Fixes for Catalyst Flex Bison parser

---

packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar.hpp

Slight reformatting.

---

cmake/ctest/drivers/trappist/CMakeLists.txt

Removing the tpetra build to see if trappist is posting correctly again.

MueLu fix trappist nightly

---

packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
packages/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp
packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_And.hpp
packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Or.hpp
packages/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
packages/kokkos/core/src/impl/Kokkos_Utilities.hpp
packages/sacado/src/Sacado_DynamicArrayTraits.cpp
packages/sacado/src/Sacado_DynamicArrayTraits.hpp

Another attempt at using Sacado with a CUDA device compiler and KOKKOS_ENABLE_CUDA=OFF

---

packages/belos/tpetra/src/solvers/Belos_Tpetra_Gmres.hpp
packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPipeline.hpp
packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp
packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp
packages/belos/tpetra/test/Native/CMakeLists.txt
packages/ifpack2/test/belos/CMakeLists.txt
packages/ifpack2/test/belos/tpetra_native.cpp

Fixes a few bugs in GMRES solvers in belos/tpetra/src/solvers
Preconditioned GMRES had a bug, and also with a non-zero initial guess.
Using ctest in belos/tpetra/test/Native and ifpack2/test/belos

Fixes a few bugs in Belos Native Tpetra solvers

---

packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_CrsProductTensor.hpp
packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_DeviceProp.hpp
packages/stokhos/src/kokkos/Cuda/Stokhos_Cuda_WarpShuffle.hpp

Fix warp shuffle instructions for volta.  Also fixed error in DeviceProp
for volta.
Fixes test failure observed here:
https://github.com/kokkos/kokkos/pull/1886#issuecomment-436840233

Stokhos:  Fixes for volta.

---

cmake/std/atdm/ride/tweaks/CUDA-9.2-DEBUG-CUDA-POWER8-KEPLER37.cmake
cmake/std/atdm/ride/tweaks/GNU-DEBUG-OPENMP-POWER8.cmake
cmake/std/atdm/waterman/tweaks/CUDA-9.2-DEBUG-CUDA-POWER9-VOLTA70.cmake
cmake/std/atdm/waterman/tweaks/CUDA-9.2-RELEASE_DEBUG-CUDA-POWER9-VOLTA70.cmake
cmake/std/atdm/waterman/tweaks/GNU-RELEASE_DEBUG-OPENMP-POWER9.cmake

The test failures for pseudo-block CG mostly stemmed from a incomplete
implementation of the condition estimation code, which was only tested
for Tpetra.  This has been fixed, per issue #3338 , so the tests should
be enabled again.
The issue causing the test failures has been resolved, so the tests should be enabled.
waterman/ride using testing environment

Re-enable Belos pseudo-block CG testing per issue #3338

---

packages/intrepid2/src/Discretization/Integration/Intrepid2_DefaultCubatureFactoryDef.hpp

Fixing bug in Intrepid2::DefaultCubatureFactory introduced in commit 36351ef
The factory was using the cell topology instead of the cell base topology.
This should fix issue encountered in Albany (thanks @ikalash for pointing it out)

Intrepid2: fixing bug in DefaultCubatureFactory

---

cmake/ctest/drivers/rocketman/cron_driver.sh

Ctest: Fixing Rocktman module issue

---

packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_C0_FEM.hpp
packages/intrepid2/src/Projection/Intrepid2_LagrangianInterpolationDef.hpp
packages/intrepid2/unit-test/Projection/test_interpolation_projection_HEX.hpp
packages/intrepid2/unit-test/Projection/test_interpolation_projection_QUAD.hpp
packages/intrepid2/unit-test/Projection/test_interpolation_projection_TET.hpp
packages/intrepid2/unit-test/Projection/test_interpolation_projection_TRI.hpp

Intrepid2: Modified Lagrangian Interpolation to work also with low order bases
Low order bases are used by Panzer (thanks to @egphill for pointing this out)
Increased tolerance for test InterpolationProjection_HEX to address Issue #3879
Related to Issue #3879

Intrepid2:  support first-order bases in interpolation class

---

packages/teko/tests/src/tLSCStabilized_tpetra.cpp

Trying to fix the testing to prevent frequent teko failures.
See recent exchange on #2712

Removing test that fails repeatedly on all platforms

---

packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp

@trilinos/tpetra @crdohrm 
* Closes #3898

Tpetra: Fix #3898 (unused typedefs)

---

cmake/ctest/drivers/enigma/sendTestSummary.sh

Auto-PR for SHA 36c2dd6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3902)

MueLu: enigma lives

---

packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp
packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp
packages/xpetra/test/Matrix/Matrix_UnitTests.cpp

Xpetra: BuildCopy Take 2

---

cmake/std/PullRequestLinuxDriver-Test.sh
cmake/std/PullRequestLinuxGCC7.3.0TestingSettings.cmake
cmake/std/sems/PullRequestGCC7.3.0TestingEnv.sh

@trilinos/Trilinos
Added sh and cmake files for GCC 7.3.0 as well as added needed elif lines in PullRequestLinuxDriver-Test.sh
Issue #3832: Add GCC 7.3 MPI dev->master and PR builds
Created Jenkins job Trilinos_pullrequest_gcc_7.3.0 to make sure everything was setup correctly.
- [n?] My change requires a change to the documentation.
- [^] I have updated the documentation accordingly.
- [n/a] I have added tests to cover my changes.
- [n] These changes break backwards compatibility.

Framework: Issue3832 d2m gcc7.3.0

---

packages/panzer/adapters-stk/test/projection/projection.cpp
packages/panzer/disc-fe/src/Panzer_L2Projection.hpp
packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_impl.hpp

Panzer: Change algorithm for lumped mass matrix in projection

---

packages/belos/src/BelosCGSingleRedIter.hpp

Fix recently introduced bug in BelosCGSingleRedIter that affects complex builds.

Belos SingleRedIter: Fix type bug

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake

Ctest: Fixing rocketman again

---

packages/intrepid2/src/Discretization/FunctionSpaceTools/Intrepid2_FunctionSpaceToolsDef.hpp

deep_copy cannot handle the case where the input and output views have
different types like double and FAD. Replacing deep_copy with clone in 
function HGRADtransformVALUE. This should fix a runtime bug in Albany.

Intrepid2: replace deep_copy with clone in FunctionSpaceTools

---

cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake

Ctest: This is ugly but does work

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp

@trilinos/tpetra Fix #3971 (minor build errors due to PR #3952).

Tpetra: Fix #3971

---

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp

Tpetra: Fix #3973 (build warnings in MultiVector unit test)

---

cmake/std/atdm/README.md

Auto-PR for SHA 738c6ba
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/3982)

ATDM: update mutrino instructions

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Import_Util2.hpp

Tpetra: Fix #3976 (build errors due to uint)

---

packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp
packages/tpetra/core/src/Tpetra_Assembly_Helpers.hpp

Tpetra: beginFill/endFill helper functions

---

packages/muelu/test/maxwell/Maxwell3D.cpp

MueLu: Fixing compiler error on trappist

---

packages/muelu/test/scaling/ImportPerformance.cpp

MueLu: Removing compiler warning in test

---

packages/tempus/src/Tempus_RKButcherTableau.hpp

Quick fix to latex error
doxygen was hanging as pointed out by M. Crockatt.

Tempus: fix doxygen error

---

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_SaPFactory_def.hpp
packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_SaPFactory_kokkos_def.hpp

This seems to be the issue in all the complex builds..

MueLu: Add check that prolongator damping factor is a finite number

---

packages/tpetra/core/src/Tpetra_CrsMatrixMultiplyOp.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp

@trilinos/tpetra @vbrunini 
* Closes #4017

Tpetra: Fix #4017 (CrsMatrixMultiplyOp::applyNonTranspose)

---

packages/muelu/adapters/amgx/MueLu_AMGXOperator_def.hpp
packages/muelu/research/mmayr/composite_to_regions/src/main.cpp

Correct things that got broken by PR #3986.

Muelu: Correct changes of PR #3986

---

packages/piro/src/Piro_NOXSolver_Def.hpp

When Piro performs a solve, the solution needs to be stored as the last response,
however this was not happening in the case of adjoint sensitivites. 
This PR fixes that behavior. 
Related to issue gahansen/Albany#402

Piro: fix for NoxSolver class. (related to issue gahansen/Albany#402)

---

packages/belos/epetra/src/BelosEpetraAdapter.hpp
packages/belos/epetra/src/BelosEpetraUtils.cpp
packages/belos/epetra/src/BelosEpetraUtils.h
packages/epetra/src/Epetra_CrsGraph.cpp
packages/epetra/src/Epetra_CrsGraph.h
packages/epetra/src/Epetra_MultiVector.h
packages/epetra/src/Epetra_Util.cpp
packages/epetra/src/Epetra_Util.h
packages/ifpack/src/Ifpack_PointRelaxation.cpp
packages/nox/src-epetra/NOX_Epetra_BroydenOperator.C
packages/nox/src-epetra/NOX_Epetra_FiniteDifference.C
packages/nox/src-epetra/NOX_Epetra_FiniteDifferenceColoring.C
packages/nox/src-epetra/NOX_Epetra_FiniteDifferenceColoring.H
packages/nox/src-epetra/NOX_Epetra_LinearSystem_AztecOO.C
packages/nox/src-epetra/NOX_Epetra_LinearSystem_Stratimikos.C
packages/nox/src-epetra/NOX_Epetra_MatrixFree.C
packages/nox/src/NOX_Direction_Broyden.C
packages/nox/src/NOX_Direction_Broyden.H
packages/thyra/adapters/epetra/src/Thyra_EpetraThyraWrappers.cpp

- mods to allow Trilinos to build with
-D Trilinos_NO_32BIT_GLOBAL_INDICES:BOOL=ON
-D Zoltan_ENABLE_ULONG_IDS:Bool=ON
*Reviewers @kddevin 
These changes allow epetra to compile with Epetra64 enabled (via -D Trilinos_NO_32BIT_GLOBAL_INDICES:BOOL=ON) and come from patches developed in Aleph.
The Eeptra64 solver stack will not comile without these, no less run tests, etc.
*Part of Issue #1909 
It has been tested in the Aleph application across several HPC platforms up to and including NOX in the solver stack.
- [x ] I have read the [code contribution guidelines](../blob/master/CONTRIBUTING.md) for this project.

Issue #1909 : Epetra64 gaps

---

packages/muelu/utils/misc/update_branch.sh

MueLu: Yet another git utility

---

packages/anasazi/src/AnasaziBlockKrylovSchur.hpp
packages/anasazi/src/AnasaziGeneralizedDavidson.hpp

Failures on ATDM platforms started after PR #3951, where the interaction
with the BKS and Generalized Davidson solver and LAPACK GEES changed to
address issues with MKL 18.0.[1-3].  While it seems that checking for the
optimal workspace size should be safe before performing the eigensolve using GEES,
it appears there are memory issues with GEES in MKL 17.0.x, where the use
of the optimal memory size is resulting in bad behavior and potential seg
faults.  So, it's a catch 22 and I am going back to the previous version
of these solvers that have been solid for years.
This should address ATDM test failures on CEE platforms.  It will likely reintroduce the test failures for Mutrino, but you can't have it all.
On Chama and CEE machines.
This is just a checkout of the …

Reverting changes to LAPACK GEES routines to address bugs #3992 and #3989

---

packages/tpetra/core/test/ImportExport/CMakeLists.txt
packages/tpetra/core/test/ImportExport/Issue_3968.cpp

@trilinos/tpetra @rppawlo 
This was originally part of PR #3996.  @rppawlo pushed an improved fix to #3968 first in PR #3999, which got merged.  I thus deleted PR #3996. This commit includes just the unit test that was part of PR #3996, but not part of PR #3999.
* Follows #3999 
* Related to #3968

Tpetra: Add unit test for #3968

---

packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp
packages/tpetra/core/test/Tpetra_TestingUtilities.hpp

Tpetra: Minor Tpetra testing and interface tweaks

---

packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp

Panzer: cuda fix

---

packages/muelu/CMakeLists.txt
packages/xpetra/CMakeLists.txt

Auto-PR for SHA b37f338
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4053)

MueLu: update how Kokkos code gets enabled

---

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.hpp
packages/panzer/adapters-stk/src/Panzer_STK_WorksetFactory.hpp
packages/panzer/disc-fe/src/Panzer_ModelEvaluator.hpp
packages/panzer/disc-fe/src/Panzer_SetupPartitionedWorksetUtilities.hpp
packages/panzer/disc-fe/src/Panzer_SubcellConnectivity.hpp
packages/panzer/disc-fe/src/Panzer_Workset.hpp

fixing clang warnings requested by empire

Panzer: fix clang warnings

---

packages/ml/src/Coarsen/ml_agg_genP.c
packages/ml/src/Operator/ml_operator.h

ML: Adding aux dropping diagnostic output

---

packages/ifpack2/example/RelaxationWithEquilibration.cpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxationPerf.cpp

Fix #4081.
Fix build of Ifpack2 tests for when Epetra is ON but AztecOO is OFF.
* Closes #4081

Ifpack2: Fix #4081 (build errors in tests)

---

packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_def.hpp

fix semicoarsening overflow

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Import_Util2.hpp

Instead of hard coding it to 3000 all over the place.

Tpetra: Use MM_TAFC_OptimizationCoreCount from Details::Behavior

---

packages/muelu/test/scaling/Driver.cpp

MueLu: Fixing ML support in Driver

---

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
packages/panzer/disc-fe/src/lof/Panzer_BlockedTpetraLinearObjFactory_impl.hpp

Cleanup panzer Tpetra use

---

packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp

Teuchos: fix for #4145

---

packages/muelu/src/Interface/MueLu_MLParameterListInterpreter_def.hpp
packages/teuchos/core/src/Teuchos_ScalarTraits.cpp

Auto-PR for SHA f751bf1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4165)

Teuchos: MueLu: fix warnings

---

packages/panzer/dof-mgr/src/Panzer_DOFManager_impl.hpp

Panzer: fix cuda builds

---

packages/tempus/src/Tempus_RKButcherTableau.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp

Ensure that Teuchos::ScalarTraits::squareroot is called with a type that the compiler
can infer.
Avoid NaNs
#4176

Changes to avoid NaNs with clang debug builds.

---

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests_Swap.cpp

Tpetra: Merge to Tpetra-FECrsMatrix Branch

---

packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp

@trilinos/tpetra @kyungjoo-kim 
* Closes #4186

Tpetra::BlockCrsMatrix: Fix #4186

---

packages/amesos2/test/solvers/Solver_Test.cpp
packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp
packages/tpetra/core/src/Tpetra_Import_def.hpp

@trilinos/amesos2 @rrdrake @theguruat12 
* Closes #4194

Amesos2: Fix #4194

---

packages/panzer/mini-em/example/BlockPrec/main.cpp

Auto-PR for SHA 2db50d1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4197)

Panzer miniem: fix for Kokkos profiling

---

packages/kokkos-kernels/Makefile.kokkos-kernels
packages/kokkos-kernels/src/CMakeLists.txt
packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_axpby_tpl_spec_decl.hpp
packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_dot_tpl_spec_decl.hpp
packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_nrm1_tpl_spec_decl.hpp
packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_nrm2_tpl_spec_decl.hpp
packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_nrminf_tpl_spec_decl.hpp
packages/kokkos-kernels/src/impl/tpls/KokkosBlas1_scal_tpl_spec_decl.hpp
packages/kokkos-kernels/src/impl/tpls/KokkosBlas2_gemv_tpl_spec_decl.hpp
packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp

@trilinos/tpetra @kyungjoo-kim 
Patch kokkos-kernels to fix BLAS mangling.  We'll also add these changes to kokkos-kernels.
Sierra needs Trilinos to build with XL.
* Related to https://github.com/kokkos/kokkos-kernels/issues/369

kokkos-kernels: Fix BLAS mangling

---

packages/belos/tpetra/test/BlockGmres/test_hybrid_gmres_hb.cpp

There are random test failures for this test, #4159, and I can only speculate
that it is happening because this test is using random vectors for both
the RHS of the linear system and initial vector for computing the polynomial
for polynomial-preconditioned Gmres.
Changing the default to just using one random vector for the linear system,
which will then be used as the initial vector for computing the Gmres/Arnoldi
polynomial.
Trying to stop the random failures from this test.
OSX, GCC 7.2, Serial.

Changing test default to use RHS as initial vector for Hybrid Gmres #4159

---

packages/shylu/shylu_dd/frosch/test/CMakeLists.txt

I have added another check for Tpetra_DefaultNode to resolve the EpetraNode errors reported in #3541.

Another check for Tpetra_DefaultNode.

---

packages/phalanx/example/FiniteElementAssembly/evaluators/Constant.hpp
packages/phalanx/example/FiniteElementAssembly/evaluators/ProjectGradientToQP.hpp
packages/phalanx/example/FiniteElementAssembly/evaluators/ProjectValueToQP.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/Constant.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ProjectGradientToQP.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ProjectValueToQP.hpp
packages/phalanx/example/FiniteElementAssembly_DeviceDag/evaluators/ScatterResidual.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/Constant.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/ProjectGradientToQP.hpp
packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/ProjectValueToQP.hpp
packages/phalanx/src/Phalanx_FieldManager.hpp
packages/phalanx/src/Phalanx_FieldManager_Def.hpp
packages/phalanx/test/EvaluatorMacros/EvaluatorWithMacros_Def.hpp
packages/phalanx/test/UnmanagedFields/MDField/MDField_TestEvaluators_Def.hpp
packages/phalanx/test/Utilities/Evaluator_MockDAG_Def.hpp
packages/sacado/src/Kokkos_ViewFactory.hpp
packages/sacado/src/Sacado_trad.hpp

fix clang shadow warnings in phalanx and sacado as requested by @CamelliaDPG 
Closes #4291 #4294

4291 4294 fix clang shadow warnings

---

packages/muelu/src/Utils/MueLu_Utilities.cpp
packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp
packages/muelu/src/Utils/MueLu_Utilities_decl.hpp
packages/muelu/test/scaling/Driver.cpp
packages/muelu/test/scaling/MatvecKernelDriver.cpp

MueLu: Adding experimental node comm support

---

packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_DOF_Functors.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_decl.hpp

Use special layout for scratch space on fad types

Panzer: fix scratch layout for fad

---

packages/muelu/test/unit_tests/CMakeLists.txt

Auto-PR for SHA 98a0856
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4315)

MueLu: reduce unit test runtimes

---

packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp
packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp

- Silence a warning in MueLu::Hierarchy.
- Fix segfault in Galeri that affects MueLu's unit tests. (Should help with #4263.)

Muelu fixes

---

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

Split the two cases in `Tpetra::Details::localDotWorkAround` using `std::enable_if`
such that the compiler doesn't try to compile the complex branch for a non-complex `Scalar type`.
Without this patch I get
```
include/Cuda/Kokkos_Cuda_Parallel.hpp(2461): error: calling a __host__ function("") from a __device__ function("Kokkos::Impl::ParallelReduce< ::Kokkos::Impl::CudaFunctorAdapter< ::,  ::Kokkos::RangePolicy< ::Kokkos::Cuda, int > ,         double, void> ,  ::Kokkos::RangePolicy< ::Kokkos::Cuda, int > ,  ::Kokkos::InvalidType,  ::Kokkos::Cuda> ::operator ()") is not allowed
```
caused by the call to `Kokkos::parallel_reduce` in `Tpetra::Details::localDotWorkAround`
for a non-complex `Scalar` type when compiling with `nvcc-8`. This is similar to the issue in #4264.
* …

Tpetra: Fix compiling Tpetra::Multivector::dot() with nvcc-8 for non-complex Scalar

---

packages/galeri/src-xpetra/Galeri_XpetraCartesian.hpp
packages/muelu/research/luc/region_algorithms/CMakeLists.txt
packages/muelu/research/luc/region_algorithms/Driver_Structured_Regions.cpp
packages/muelu/research/luc/region_algorithms/structured_1dof.xml

@rstumin @mayrmt @pohm01 
Adding driver for fully structured regions
We need this driver to check that the HHG implementation is correct.
* Blocks 
The code builds and does not introduces warnings.
It is not meant to be used at this team and is protected in an experimental folder

MueLu: HHG Structured Region Driver

---

packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp
packages/teuchos/numerics/src/Teuchos_SerialSymDenseMatrix.hpp
packages/teuchos/numerics/test/DenseMatrix/cxx_main.cpp
packages/teuchos/numerics/test/DenseMatrix/cxx_main_sym.cpp

This PR is motivated by the description in Issue #4183 
These changes have been tested in Dakota builds of Teuchos.

Issue #4183 : shallow swap method for Teuchos serial dense vector

---

packages/anasazi/tpetra/test/BlockDavidson/cxx_main_lap.cpp
packages/anasazi/tpetra/test/BlockKrylovSchur/cxx_main_lap.cpp
packages/anasazi/tpetra/test/IRTR/cxx_main_lap.cpp
packages/anasazi/tpetra/test/MVOPTester/cxx_main.cpp

This removes Tpetra::DynamicProfile from unit tests in anasazi
Deprecation of DynamicProfile in Tpetra's effect on downstream packages
Since this is a change in unit testing, the affected unit tests have been rerun to ensure that they are no longer using the deprecated code path.  Tests conducted on linux 2.6.32.
commented out and can be easily added by removing the comment delimiters.
Please make sure to mark:
* Reviewers
* Assignees
* Labels
Replace <teamName> below with the appropriate Trilinos package/team name.
-->

Issue 4283: update anasazi unit tests involving Tpetra to use StaticProfile

---

packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp
packages/anasazi/epetra/test/OrthoManager/cxx_mattest.cpp
packages/anasazi/src/AnasaziBlockDavidsonSolMgr.hpp
packages/anasazi/src/AnasaziIRTR.hpp
packages/anasazi/src/AnasaziSIRTR.hpp
packages/belos/src/BelosLSQRIter.hpp
packages/rol/adapters/teuchos/test/function/test_01.cpp
packages/rol/example/dense-hessian/example_01.cpp
packages/rythmos/src/Rythmos_ExplicitRKStepper_def.hpp
packages/rythmos/src/Rythmos_RKButcherTableau.hpp
packages/stokhos/src/Stokhos_GSReducedPCEBasisBaseImp.hpp
packages/stokhos/src/Stokhos_GramSchmidtBasisImp.hpp
packages/stokhos/src/Stokhos_MonomialProjGramSchmidtPCEBasis2Imp.hpp
packages/stokhos/src/Stokhos_ProductLanczosGramSchmidtPCEBasisImp.hpp
packages/stokhos/test/UnitTest/Stokhos_GramSchmidtUnitTest.cpp
packages/stokhos/test/UnitTest/Stokhos_HermiteBasisUnitTest.cpp
packages/stokhos/test/UnitTest/Stokhos_LanczosUnitTest.cpp
packages/stokhos/test/UnitTest/Stokhos_LegendreBasisUnitTest.cpp
packages/stokhos/test/UnitTest/Stokhos_NormalizedHermiteBasisUnitTest.cpp
packages/stokhos/test/UnitTest/Stokhos_NormalizedLegendreBasisUnitTest.cpp
packages/stokhos/test/UnitTest/Stokhos_StieltjesUnitTest.cpp
packages/tempus/src/Tempus_RKButcherTableau.hpp
packages/teuchos/numerics/example/DenseMatrix/cxx_main.cpp
packages/teuchos/numerics/example/DenseMatrix/cxx_main_sym.cpp
packages/teuchos/numerics/example/LAPACK/cxx_main.cpp
packages/teuchos/numerics/src/Teuchos_SerialBandDenseMatrix.hpp
packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp
packages/teuchos/numerics/src/Teuchos_SerialSymDenseMatrix.hpp
packages/teuchos/numerics/test/DenseMatrix/cxx_main.cpp

CC: @trilinos/teuchos 
Reverts trilinos/Trilinos#4259
Need to revert as per #4330.  Someone needs to create a new issue to make these changes that preserve the existing `operator<<()` function.

Revert "Issue4258 remove teuchos sdmatrix inheritance"

---

packages/muelu/research/luc/region_algorithms/Driver_Structured_Regions.cpp

Improving capabilities in the structured region driver namely: fixing 2D behavior and adding 3D capability.
The 3D case is of use for performance demonstration.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #4304
* Composed of 
The code has been tested locally and is protected with the experimental guard

MueLu: Fix 2D case and implement 3D case in structured region driver

---

packages/sacado/src/Sacado_DynamicArrayTraits.cpp
packages/sacado/src/Sacado_DynamicArrayTraits.hpp

@trilinos/Sacado
Correct ifdefs checking for whether or not relocatable device code is enabled.
Prior to this building Sacado with rdc enabled would lead to multiple definition errors at link time.

Sacado: Fix relocatable device code ifdefs.

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake

This turns on Warnings as Errors for Teuchos with the exception of:
-Wno-clobbered -Wno-vla -Wno-pragmas -Wno-unknown-pragmas -Wno-unused-local-typedefs -Wno-literal-suffix -Wno-deprecated-declarations -Wno-misleading-indentation -Wno-int-in-bool-context -Wno-maybe-uninitialized -Wno-nonnull-compare -Wno-address -Wno-inline 
This addresses Issue #4254 "Teuchos errors in Werror build".
This has been [built to develop without issue](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4534802).

Teuchos errors in Werror build

---

packages/muelu/src/Utils/MueLu_AlgebraicPermutationStrategy_decl.hpp
packages/muelu/src/Utils/MueLu_AlgebraicPermutationStrategy_def.hpp

Taking into account feedback from Mark on this issue.

MueLu: AlgebraicPermutationStrategy clean-up for issue #3492

---

packages/muelu/src/Rebalancing/MueLu_RepartitionFactory_def.hpp
packages/muelu/test/unit_tests/Repartition.cpp

Muelu: Fix to DeterminePartitionPlacement in RepartitionFactory

---

packages/ifpack2/example/RelaxationWithEquilibration.cpp
packages/tpetra/core/inout/Tpetra_Details_CooMatrix.hpp
packages/tpetra/core/src/CMakeLists.txt
packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_DualViewUtil.cpp
packages/tpetra/core/src/Tpetra_Details_DualViewUtil.hpp
packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
packages/tpetra/core/src/Tpetra_DistObject_def.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_def.hpp
packages/tpetra/core/src/Tpetra_Export_def.hpp
packages/tpetra/core/src/Tpetra_Import_def.hpp
packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

@trilinos/tpetra @ikalash 
1. Fix #4344, and document DistObject to clarify what DualViews can and should be sync'd
2. Fix build errors that show up only with ETI off: https://github.com/trilinos/Trilinos/issues/4334#issuecomment-462417954
* Closes #4344

Tpetra: Fix #4344 & ETI-OFF build errors

---

packages/tpetra/core/src/Tpetra_Import_def.hpp

Tpetra: Fix issue #4381

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake

Like PR #4374 for Issue #4254, this turns on Warnings as Errors for kokkos in the GCC 7.2.0 PR build.
This addresses Issue #3178 turning on another package for Werror.
This has been [built to develop without issue](https://testing-vm.sandia.gov/cdash/index.php?project=Trilinos&parentid=4544446).

Add WError for kokkos

---

packages/zoltan2/test/unit/util/findUniqueGids.cpp

@trilinos/zoltan2 @mhoemmen 
Fixed inconsistent output statement noticed in #4395 
(good catch, @mhoemmen )
Consistency is good.
Fix was delayed until PR testing for #4395 completed; user was waiting for fix that did not depend on this output statement.
PR testing

zoltan2:  fixed output error in #4395

---

packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
packages/tpetra/core/test/MultiVector/MultiVector_get2dView.cpp

Fix #4298 and other build warnings.  For the latter, see:
https://github.com/trilinos/Trilinos/issues/3178#issuecomment-463856074
* Closes #4298 
* Related to #3178

Tpetra: Fix #4298 & other build warnings

---

packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_decl.hpp
packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_def.hpp
packages/shylu/shylu_dd/frosch/test/LocalPartitionOfUnityBasis/main.cpp

This PR addresses #4276. In particular, I added some checks to make sure that we do not run into assertions in case a block is empty. 
@chochmuth, please check if the errors in your code still appear. I am not sure if this covers all your issues. For the FROSch tests, disabling a block seems to works now.
All FROSch tests complete successfully on my machine, even if a block is disabled.

ShyLU/FROSch: Adding a check for the block coarse map.

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp

Activate a test that was inactive due to a bug in the unit test.
I verified the test is now active and meaningfully tests norm-based termination.

Ifpack2: Fix #4343.

---

cmake/std/PullRequestLinuxDriver-Test.sh

Relates to #4425 
Adding the quotes around the variable from #4425, I figure it can't hurt and might improve compatibility a bit.
@prwolfe

Parameterized pr cdash track

---

packages/stokhos/src/CMakeLists.txt

Adding ETI for stokhos versions of FECrsMatrix and FEMultiVector

---

packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl_impl.hpp

In the DOFCurl evaluator the string "Curl" was used in an assertion check when "HCurl" should have been used.

Panzer: Fixing misspelled "Curl"

---

packages/muelu/test/scaling/CMakeLists.txt
packages/muelu/test/scaling/Driver.cpp
packages/muelu/test/scaling/DriverCore.hpp
packages/muelu/test/scaling/scaling-with-rerun.xml

MueLu: Refactor of Driver to allow for code reuse

---

packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix.hpp

Xpetra: Fixing Albany build fail

---

packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_def.hpp
packages/muelu/test/scaling/Driver.cpp
packages/muelu/test/unit_tests/Smoothers/Ifpack2Smoother.cpp

MueLu/Ifpack2: Improving interface to BlockRelaxation

---

packages/muelu/test/scaling/Driver.cpp

MueLu: Cleanups to driver error handling

---

packages/muelu/test/structured/Driver_Structured.cpp

Adding more fine grained control in the Structured Driver for HPC experimentation
This will allow me to utilize HPC resources more effectively when doing performance tests
I did a local build and tested the new options, they work just fine.

MueLu: adding options for rerun and operation: (matvec | setup | solve) in Structured driver

---

packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHCURL.hpp
packages/intrepid2/unit-test/Projection/test_DeRham_commutativity_QUAD.hpp
packages/intrepid2/unit-test/Projection/test_DeRham_commutativity_TRI.hpp
packages/piro/test/MockModelEval_A_Tpetra.cpp

Remove warnings addressing issues #4474 and #4477.

Remove Intrepid2 and Piro warnings

---

packages/ifpack2/example/RelaxationWithEquilibration.cpp
packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

Auto-PR for SHA 2a90922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4483)

Fix compiler warnings

---

packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp

These timers are providing finer grain data which can be used to optimize the kokkos_refactor path some more on NGPs.
More precisely, the prolongator factory now times the creation of the graph of the prolongator matrix separately from the insertion of values, the time spent building a set of coarse coordinates and a coarse near-nullspace is also timed using submonitors.
When hunting for performance, one needs more fine grain timers...
Local build and tests have been performed and the timers are reporting correctly.

MueLu: adding submonitor in GeometricInterpolationPFactory

---

packages/seacas/applications/epu/EP_Internals.C
packages/seacas/applications/exodiff/map.C
packages/seacas/libraries/exodus/src/ex_put_sets.c
packages/seacas/libraries/ioss/src/Ioss_NullEntity.h
packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C
packages/seacas/libraries/ioss/src/utest/Utst_ioel.C
packages/seacas/libraries/suplib_cpp/scopeguard.h

SEACAS should now build with no warnings and should be OK for a `-Werror` build.

SEACAS: Fix compiler warnings

---

packages/ifpack/test/OverlappingRowMatrix/cxx_main.cpp

@trilinos/ifpack 
Fix build errors blocking `-Werror` build.
* Closes #4508

Ifpack: Fix #4508

---

packages/amesos2/example/GappedMtxGIDs-1proc.cpp
packages/amesos2/src/Amesos2_MatrixAdapter_def.hpp
packages/amesos2/src/Amesos2_Umfpack_decl.hpp
packages/amesos2/src/Amesos2_Umfpack_def.hpp

Partially addresses issue #3647 reported by @vbrunini

Amesos2: Fix another code path for gapped row id case

---

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

This pull request removes `Tpetra::Details::localDotWorkAround` and calls `KokkosBlas::dot` unconditionally.
Similar to #4312, without this patch I get an error message similar to
```
include/Cuda/Kokkos_Cuda_Parallel.hpp(2461): error: calling a __host__ function("") from a __device__ function("Kokkos::Impl::ParallelReduce< ::Kokkos::Impl::CudaFunctorAdapter< ::,  ::Kokkos::RangePolicy< ::Kokkos::Cuda, int > ,         double, void> ,  ::Kokkos::RangePolicy< ::Kokkos::Cuda, int > ,  ::Kokkos::InvalidType,  ::Kokkos::Cuda> ::operator ()") is not allowed
```
caused by the call to `Kokkos::parallel_reduce` in `Tpetra::Details::localDotWorkAround`
for complex `Scalar` type when compiling with `nvcc`. I tried both `nvcc-8` and `nvcc-10`.
The workaround was first introduced in …

Tpetra: Fix compiling Tpetra::Multivector::dot() with CUDA for complex Scalar

---

packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits.hpp
packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixUQPCEUnitTest.hpp

Involves fixing a warning from the mask traits that was a true error.
For issue #4515

Stokhos:  Fix a few warnings reported in issue #4515

---

packages/amesos2/src/KLU2/Include/klu2_internal.h
packages/amesos2/src/KLU2/Source/klu2_analyze.hpp
packages/amesos2/src/KLU2/Source/klu2_dump.hpp
packages/amesos2/src/KLU2/Source/klu2_factor.hpp
packages/amesos2/src/KLU2/Source/klu2_kernel.hpp
packages/amesos2/src/KLU2/Source/klu2_refactor.hpp

Amesos2: Rename KLU2 NDEBUG Macro

---

cmake/std/atdm/sems-rhel7/environment.sh

This is a follow-up to PR #4554.

Fix some typos including some found in review (TRIL-255)

---

packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_GDSWCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp
packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_RGDSWCoarseOperator_def.hpp

With this, piecewise constant coarse basis functions are automatically introduced in cases when no interface dofs exist. This is important for discretizations with discontinuous basis functions.
@chochmuth Please check if this works with our in-house implementation.

ShyLU: Fixing the case of empty blocks.

---

packages/tempus/src/Tempus_AdjointAuxSensitivityModelEvaluator_impl.hpp
packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
packages/tempus/src/Tempus_SolutionState_impl.hpp
packages/tempus/src/Tempus_StepperBDF2_impl.hpp
packages/tempus/src/Tempus_StepperBackwardEuler_impl.hpp
packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
packages/tempus/test/BDF2/Tempus_BDF2Test.cpp
packages/tempus/test/BDF2/Tempus_BDF2_ASA.cpp
packages/tempus/test/BDF2/Tempus_BDF2_FSA.hpp
packages/tempus/test/BackwardEuler/Tempus_BackwardEulerTest.cpp
packages/tempus/test/BackwardEuler/Tempus_BackwardEuler_ASA.cpp
packages/tempus/test/BackwardEuler/Tempus_BackwardEuler_FSA.hpp
packages/tempus/test/DIRK/Tempus_DIRKTest.cpp
packages/tempus/test/DIRK/Tempus_DIRK_ASA.cpp
packages/tempus/test/DIRK/Tempus_DIRK_FSA.hpp
packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_ASA.cpp
packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_FSA.hpp
packages/tempus/test/ForwardEuler/Tempus_ForwardEulerTest.cpp
packages/tempus/test/HHTAlpha/Tempus_HHTAlphaTest.cpp
packages/tempus/test/Leapfrog/Tempus_LeapfrogTest.cpp
packages/tempus/test/Newmark/Tempus_NewmarkTest.cpp
packages/tempus/test/PhysicsState/Tempus_PhysicsStateTest.cpp
packages/tempus/test/TestModels/HarmonicOscillatorModel_impl.hpp
packages/tempus/test/TestModels/VanDerPol_IMEX_ExplicitModel_impl.hpp
packages/tempus/test/TestUtils/Tempus_ConvergenceTestUtils.hpp
packages/tempus/test/Trapezoidal/Tempus_TrapezoidalTest.cpp

* Fixed unsigned/signed comparisons.
* Fixed some shadowed variables.
* Fixed some unused parameters, but there are tons more!
Making Trilinos warning free.
Passed all Tempus tests.

Tempus: Remove Build Warnings

---

packages/seacas/libraries/ioss/src/Ioss_ScopeGuard.h

Addresses #4514 to alllow #4539

SEACAS: Fix more warnings due to throw()

---

packages/muelu/src/Graph/HybridAggregation/MueLu_HybridAggregationFactory_def.hpp
packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp
packages/muelu/src/Rebalancing/MueLu_NodePartitionInterface_def.hpp
packages/muelu/src/Transfers/BlackBox/MueLu_BlackBoxPFactory_def.hpp
packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_NullspaceFactory_kokkos_def.hpp
packages/muelu/test/scaling/Driver.cpp
packages/muelu/test/unit_tests/Aggregates.cpp
packages/muelu/test/unit_tests/BlackBoxPFactory.cpp

Pretty much just looked at the dashboard results linked in issue #4513 and fixed the apparent errors. I am not sure that this will be sufficient for a clean build of MueLu though?
This work is necessary to obtain ATDM builds with -Werror
* Closes #4513 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
I performed a local build

MueLu: -Werror

---

commonTools/framework/clean_workspace/clean_sentinel.py

I know I tested this, but apparently I had the file in place? grrr!!!!

clean_sentinel.py: add "w" mode to the open on the pickle file

---

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp

In `MultiVector::reduce`, instead of using two distinct buffers for a `MPI_Allreduce`, use `MPI_IN_PLACE` and save one allocation per call.

Tpetra MV: remove unneeded MPI buffer

---

packages/muelu/src/Rebalancing/MueLu_RepartitionHeuristicFactory_def.hpp

MueLu RepartitionHeuristicFactory: Fix bug

---

packages/nox/src-epetra/NOX_Epetra_BroydenOperator.C
packages/nox/src-loca/src-epetra/LOCA_BorderedSolver_EpetraHouseholder.C
packages/nox/src-loca/src-epetra/LOCA_Epetra_Group.C
packages/nox/src-loca/src-epetra/LOCA_Epetra_ModelEvaluatorInterface.C
packages/nox/test/epetra/FiniteDifferenceColoring/FiniteElementProblem_OwnedOnly.C
packages/nox/test/epetra/LOCA_Brusselator/Brusselator.C
packages/nox/test/epetra/LOCA_Brusselator/Brusselator.H

cleanup NOX/LOCA compiler warnings

---

cmake/std/atdm/cee-rhel6/environment.sh

CC: @trilinos/anasazi, @trilinos/rol, @fryeguy52 
This fixes long-failing Anaszzi (#3499) and ROL (#3914) tests!
I tested this on 'ceerws1113' with:
```
$ /scratch/rabartl/Trilinos.base/BUILDS/ATDM/CEE-RHEL6/CHECKIN/
$ ./checkin-test-atdm-cee-rhel6.sh cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt \
--enable-packages=Anasazi,ROL --local-do-all
```
and it gave the test results:
```
100% tests passed, 0 tests failed out of 219
Subproject Time Summary:
Anasazi    = 233.66 sec*proc (74 tests)
ROL        = 1216.54 sec*proc (145 tests)
Total Test time (real) = 183.48 sec
```
I verified that before this change it gave the test results:
```
98% tests passed, 5 tests failed out of 219
Subproject Time Summary:
Anasazi    = 11077.20 sec*proc (74 tests)
ROL        = 3765.17 sec*proc (145 tests) …
```

Use Intel MKL 18.0.5 instead of 18.0.2 (#3499, #3914)

---

packages/tpetra/CMakeLists.txt

Tpetra:  Makes disabling complex in Tpetra, but having it on in Teuchos a warning, not an error

---

packages/ml/src/Utils/ml_MultiLevelPreconditioner_Aux.cpp
packages/ml/src/Utils/ml_MultiLevelPreconditioner_Filtering.cpp
packages/ml/test/MatrixFree/MatrixFree.cpp
packages/ml/test/MultiLevelPreconditioner_Maxwell/MultiLevelPreconditioner_Maxwell.cpp

Auto-PR for SHA d966672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4625)

ML: Fix warnings reported in issue #4512.

---

packages/kokkos/Makefile.targets
packages/kokkos/core/src/Kokkos_HostSpace.hpp
packages/kokkos/core/src/impl/Kokkos_HostSpace_deepcopy.cpp
packages/kokkos/core/src/impl/Kokkos_HostSpace_deepcopy.hpp
packages/kokkos/core/unit_test/Makefile
packages/kokkos/core/unit_test/TestDeepCopy.hpp
packages/kokkos/core/unit_test/cuda/TestCuda_DeepCopyAlignment.cpp
packages/kokkos/core/unit_test/openmp/TestOpenMP_DeepCopyAlignment.cpp
packages/kokkos/core/unit_test/openmptarget/TestOpenMPTarget_DeepCopyAlignment.cpp
packages/kokkos/core/unit_test/qthreads/TestQthreads_DeepCopyAlignment.cpp
packages/kokkos/core/unit_test/rocm/TestROCm_DeepCopyAlignment.cpp
packages/kokkos/core/unit_test/serial/TestSerial_DeepCopyAlignment.cpp
packages/kokkos/core/unit_test/threads/TestThreads_DeepCopyAlignment.cpp

Auto-PR for SHA 3d3f2d0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4597)

Temporarily add Kokkos patch until next snapshot

---

packages/stratimikos/adapters/belos/src/Belos_Details_Thyra_registerSolverFactory.cpp
packages/stratimikos/adapters/belos/src/Belos_Details_Thyra_registerSolverFactory.hpp
packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_decl.hpp
packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp
packages/stratimikos/adapters/belos/src/Thyra_BelosSolverFactory.hpp

@trilinos/belos @trilinos/stratimikos 
Use the Belos solver factory in the Stratimikos adapter.
@mhoemmen Could you check if this is correct? I tried matching the pattern for the Tpetra solver manager, but I am not sure if I got the whole DII stuff right..

Belos Stratimikos adapter: Use solver factory

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake

This sets Werror for NOX.
This is work toward #3178 turning Werror on for all packages.
Allowed by work from Issue #4509 & PR #4575.

Set Werror for NOX

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/test/unit_tests/RAPShiftFactory.cpp

MueLu: RAPShiftFactory Changes (also how to get an array into MueLu)

---

packages/panzer/disc-fe/src/evaluators/Panzer_ProjectToFaces_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ProjectToFaces_impl.hpp

Clarify a use case in panzer by renaming an input flag

Panzer: clarify valid use of a ProjectToFace algorithm

---

packages/seacas/applications/nem_slice/elb_output.C

Eliminate a ScopeGuard ON_BLOCK_EXIT call which was calling `free` which had a `throw()` exception specification which was causing a build warning.  Replaced with a std::vector of std::string
Additional changes are due to clang-format reformatting some lines following the change.

NEM_SLICE: change char array to string vector

---

cmake/std/atdm/common/toss3/environment.sh

Whoops, needed to set to develop, not master,
@bartlettroscoe any issues?

Updated to intel18 on toss3

---

packages/panzer/disc-fe/src/evaluators/Panzer_ProjectToFaces_impl.hpp

Panzer: adding extra output to ProjectToFace

---

packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHGRAD.hpp
packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefCloneScale.hpp
packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefScalar.hpp
packages/intrepid2/unit-test/Projection/test_DeRham_commutativity_QUAD.hpp
packages/intrepid2/unit-test/Projection/test_DeRham_commutativity_TRI.hpp

Remove warnings in Intrepid2 to address issue #3178.

Intrepid2: remove warnings, issue #3178

---

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp
packages/tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp
packages/tpetra/core/test/FECrsMatrix/FECrsMatrix_UnitTests.cpp

Tpetra: FECrsGraph cleanup 

---

packages/muelu/src/Utils/MueLu_AvatarInterface.cpp

MueLu: More fixes to the Avatar interface

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
packages/ml/src/Utils/ml_MultiLevelPreconditioner_Filtering.cpp
packages/ml/test/MatrixFree/MatrixFree.cpp

Sets Werror for ML in the GC 7.2.0 PR build.
This is work toward #3178, setting -Werror for all packages.
Allowed by work from Issue #4512 & PR #4625.

Set Werror for ML

---

packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHDIV.hpp

Intrepid2: Use LAPACK GELS instead of GESV
Solve a local system in the HDIV  projection class in a least square sense
because the system is ill-posed. This should close issue   #4738

Intrepid2: Use LAPACK GELS instead in GESV for HDIV projection (issue #4738)

---

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp

Tpetra: Fixing incorrect use of memory space in CrsGraph::insertLocalIndicesImpl ArrayView Version

---

packages/tpetra/core/test/FECrsMatrix/FECrsMatrix_UnitTests.cpp

Tpetra: Adding local assembly to FECrsMatrix test

---

packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp
packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp
packages/muelu/test/structured/CMakeLists.txt
packages/muelu/test/structured/structured_1dof.xml
packages/muelu/test/structured/structured_2dof.xml
packages/muelu/test/structured/structured_interp_line.xml

This will provide an exmaple for potential users as well as further protect this capability against future changes.
This work supports current effort on structured grid capabilities in MueLu
* Closes #4802
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
All the MueLu tests have been run and passed on my local machine

MueLu: adding structured line detection example in MueLu structured test

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_decl.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_decl.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp

Tpetra: Refactor of Triple Product Code

---

packages/tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp
packages/tpetra/core/test/FECrsMatrix/FECrsMatrix_UnitTests.cpp

Tpetra: Support routines for tests Take 2 .

---

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp
packages/tpetra/core/ext/TpetraExt_MatrixMatrix_decl.hpp
packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_decl.hpp
packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp
packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp

Tpetra: Adding Reuse Triple-Product

---

packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp
packages/muelu/src/MueCentral/MueLu_FactoryManager_def.hpp
packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/test/structured/CMakeLists.txt
packages/muelu/test/structured/Driver_Structured.cpp
packages/muelu/test/structured/structured_1dof_shift.xml
packages/muelu/test/unit_tests/RAPShiftFactory.cpp

MueLu: Updating CFL limiting support

---

packages/tpetra/core/src/Tpetra_MultiVectorFiller.cpp
packages/tpetra/core/src/Tpetra_MultiVectorFiller.hpp
packages/tpetra/core/test/MultiVectorFiller/CMakeLists.txt

Tpetra: Deprecate MultiVectorFiller

---

packages/muelu/test/unit_tests_kokkos/StructuredAggregation_kokkos.cpp
packages/muelu/test/unit_tests_kokkos/TentativePFactory_kokkos.cpp
packages/xpetra/src/Map/Xpetra_EpetraMap.hpp
packages/xpetra/test/Map/Map_UnitTests.cpp

Auto-PR for SHA 66aff72
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4863)

Xpetra: fix issue #4038.

---

packages/panzer/mini-em/src/solvers/MiniEM_DiscreteGradient.hpp

The discrete gradient matrix used in MiniEM was not correctly built.

MiniEM: Fix discrete gradient

---

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp

This fixes the problem described in the issue #4858 .

Ifpack2 - fix issue 4858

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/src/Utils/MueLu_Utilities_decl.hpp

MueLu: Adding FE helper macro and removing ambiguity in RefMaxwell

---

packages/panzer/mini-em/example/BlockPrec/solverAugmentationEpetra.xml

Epetra and MueLu's Kokkos refactor do not play together nicely.

MiniEM: Do not run with Epetra and MueLu's Kokkos Refactor

---

packages/muelu/adapters/tpetra/MueLu_TpetraOperator_decl.hpp
packages/muelu/adapters/tpetra/MueLu_TpetraOperator_def.hpp
packages/muelu/test/maxwell/Maxwell3D.cpp

MueLu: Fixes for RefMaxwell usability

---

packages/xpetra/src/Map/Xpetra_EpetraMap.hpp

Auto-PR for SHA 26ce1e9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4892)

Fix issue #4891 (unused variable)

---

packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp

Auto-PR for SHA c13eb67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4917)

Fixes CUDA warning reported in issue 4078

---

packages/muelu/src/CMakeLists.txt

Auto-PR for SHA cd624b0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4926)

Fix issue 4925, undefined symbols in static build

---

packages/muelu/adapters/tpetra/MueLu_TpetraOperator_decl.hpp
packages/muelu/adapters/tpetra/MueLu_TpetraOperator_def.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_XpetraOperator_decl.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp
packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_decl.hpp
packages/muelu/src/Smoothers/MueLu_SmootherCloner.hpp
packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_decl.hpp

MueLu: More Deprecations

---

packages/xpetra/src/Map/Xpetra_TpetraMap.hpp

xpetra:  removed default types in deprecated code

---

packages/tpetra/CMakeLists.txt

@trilinos/tpetra @ajpowel
Try fixing #4857, by removing checks in `tpetra/CMakeLists.txt` that might be excessively strict now.
* Closes #4857

Tpetra: Fix #4857

---

packages/belos/tpetra/test/BlockGmres/test_bl_gmres_hb_df.cpp
packages/belos/tpetra/test/FixedPoint/test_fp_hb.cpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
packages/shylu/shylu_dd/bddc/src/shylu_DofManager.hpp

@trilinos/belos @trilinos/ifpack2 @trilinos/shylu @trilinos/tpetra 
Remove use of deprecated Tpetra functions in Belos, Ifpack2, and ShyLU.
* Related to #4900

Belos,Ifpack2,ShyLU: Fix use of deprecated Tpetra features

---

packages/seacas/libraries/exodus/src/ex_put_init.c
packages/seacas/libraries/exodus/src/ex_utils.c

Converted all strncpy to copy_string.  Both should take the same length, but several uses of strncpy were passing in a length shortened by 1 and then explicitly adding the null at end.  The automated conversion of strncpy to copy_string missed a few cases where the length needed to increased by 1.  This causes no memory issues since not overrunning buffer; instead it was not using the last position.

EXODUS: Fix a few off-by-one in copy_string

---

packages/muelu/CMakeLists.txt

MueLu: Better configure time checks for matlab

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp

MueLu: Fixing segfault in RefMaxwell matrix dump

---

packages/seacas/applications/mapvar-kd/mapvar-kd.f
packages/seacas/applications/mapvar/mapvar.f

Fix bad format statement which was causing issues on ARM systems as reported in #4973

MAPVAR: Fix bad format statement

---

packages/muelu/test/maxwell/Maxwell.xml
packages/muelu/test/maxwell/Maxwell3D.cpp

Make using MueLu's Maxwell test a bit easier.

RefMaxwell fixes

---

packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp
packages/muelu/test/unit_tests/RAPShiftFactory.cpp

MueLu: Fixing Helmholtz bug

---

packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C

Fix for SPARC 
* The ZoneGridConnectivity instances need to be unique for a zone.  In the file-per-processor case, there may be multiple ZGC with the same name that arise due to processor decomposition.  The previous code assumed a maximum of 26 instances and made them unique by appending a 'A' ... 'Z' to the name until found a unique name.  Failure was not detected.
New code tries 'A' .. 'Z' and if not unique, then tries 'AA' 'AB',...'ZZ' and if still not unique it will stop and output a meaningful error message. 
Also added some debugging output for the non-file-per-processor output to make sure that zgc consolidation is working correctly
Tested on actual mesh that was causing issues with original code.  A representation of this mesh is now in test suite (which will be …

SEACAS: cgns - fix zgc uniquification

---

packages/muelu/src/MueCentral/MueLu_ParameterListAcceptor.cpp
packages/muelu/src/MueCentral/MueLu_ParameterListAcceptor.hpp
packages/muelu/src/Utils/MueLu_Monitor.hpp
packages/muelu/test/paramlist/paramlist.cpp
packages/muelu/test/paramlist/paramlistAdv.cpp

MueLu: more work to reduce library size

---

packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TET_In_FEMDef.hpp

Adde a temp variable to avoid nvcc compiler error (thanks @bathmatt for the fix). 
Closes issue #4963

Intrepid2: simple workaround for nvcc compiler bug (issue #4963)

---

packages/xpetra/src/CMakeLists.txt

Should fix issue #5011.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5013)

Xpetra: fix header install problem

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/test/maxwell/Maxwell3D.cpp

Allow setting RHS and tolerance in Maxwell test.

Muelu Maxwell changes

---

packages/muelu/test/maxwell/Maxwell3D.cpp

Small fix in Maxwell3D-Tpetra test
This has been reported as a blocker issue in #4989
* Closes #4989
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of
A local build that reproduced this specific test failure has been performed.
The test now works fine with this correction.

MueLu: fixing bug in Maxwell3D Tpetra see #4989

---

packages/ifpack2/doc/UsersGuide/options.tex
packages/ifpack2/src/Ifpack2_AdditiveSchwarz_decl.hpp
packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp

Ifpack2: Add update damping to AdditiveSchwarz

---

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp

Fixed shadow warning reported in #5045
Reported by an important customer

Tpetra:  Fixing shadow warning for #5045

---

packages/stk/stk_unit_tests/stk_topology/topology_test_utils.hpp

A couple of stk-topology unit-test functions were using new and delete on device.
Surprisingly this failed only on some GPUs, not all... Very difficult to track down,
manifested as memory corruption. Finally found it with cuda-memcheck which
provided a clue which led us to replace the dynamically allocated array with a
stack array.

fix a stk-topology unit-test failure on gpu.

---

packages/xpetra/src/Vector/Xpetra_TpetraVector_def.hpp

Xpetra: Fixing Albany issue

---

packages/xpetra/src/Vector/Xpetra_TpetraVector_decl.hpp
packages/xpetra/src/Vector/Xpetra_TpetraVector_def.hpp

Xpetra: Fixes to Xpetra::TpetraVector

---

packages/muelu/test/scaling/MMKernelDriver.cpp

Guards raw openmp diagnostics and fixes some compiler warnings
Closes: #5025
@trilinos/muelu @lucbv 
Tested on White (Cuda)
- [] My code follows the code style of the affected package(s).

MueLu: Fix MMDriver OpenMP errors

---

cmake/ctest/drivers/atdm/README.md

Edits to atdm config install documentation

---

TPLsList.cmake

This adds a SEACAS dependency (ADIOS2) using the TPL file from the seacas package folder.
Seacas has a new TPL dependency that was added to their local CMake build but not to Trilinos in [this commit](https://github.com/trilinos/Trilinos/commit/3c19f3b5fb8b0589b3ba42f5ae64a521879ee5df). 
To test this patch:
* Download [Dockerfile.txt](https://github.com/trilinos/Trilinos/files/3139205/Dockerfile.txt)
* docker build -t trilinos -f Dockerfile.txt .
This will compile trilinos with the patch (succeed) and without the patch (fail)

SEACAS: Add ADIOS2 TPL for Seacas

---

Version.cmake

Updating to 12.17 for now because in Trilinos 13 we are going
to break backward compatibility and don't want to do so quite yet.
Also, we are planning to change the versioning approach. This change
does not indicate we are planning a 12.18 release.
I am updating the version of Trilinos on the development branch, which will eventually be promoted to the master branch, to make it clear that this is not the development version of Trilinos prior to 12.16.

Updating version file to reflect that 12.16 has been branched.

---

packages/xpetra/sup/CMakeLists.txt

Xpetra: fix header installation error

---

packages/muelu/utils/misc/makepr.sh

Upgrade PR script
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5108)

MueLu: upgrade auto PR script

---

packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp

MueLu: More RAPShift fixes

---

packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp

@trilinos/teuchos @prwolfe @rrdrake 
Fix #5127 (shadowing warning in Teuchos::ParameterList).
* Closes #5127

Teuchos::ParameterList: Fix #5127

---

packages/tpetra/core/src/Tpetra_RowMatrix_def.hpp

This changes an untested code path to a throw.
Without dynamic profile, the case of adding two row matrices is not as cut-and-dried as before.  The team reached the conclusion that we should throw instead of proceeding.
* Closes 5042
Current unit tests do not fail, as this is/was an untested code path.  Testing the added throw made certain that no currently-run unit tests will fail.
- [na] I have added tests to cover my changes.

#5042: add throw to row matrix add

---

packages/zoltan/src/driver/dr_main.c
packages/zoltan/src/driver/dr_mainCPP.cpp

Minor change to fix warning in test code (not Zoltan library code) reported in #5106.
I increased the size of the receiving string str to 32 bytes to more than comfortably hold an integer.
Provided in #5106

zoltan:  minor change to fix #5106

---

packages/muelu/src/Misc/MueLu_RAPShiftFactory_def.hpp

Csiefer 48785b1

---

packages/muelu/CMakeLists.txt
packages/xpetra/CMakeLists.txt

Xpetra: Making previous assumptions about Xpetra configuration very clear

---

packages/belos/xpetra/src/Belos_Details_Xpetra_registerSolverFactory.cpp

Belos: Fixing Xpetra Adapters for corner case where Xpetra_ENABLE_Epetra=OFF and Belos_ENABLE_Epetra=ON

---

packages/belos/xpetra/src/Belos_Details_Xpetra_registerSolverFactory.cpp
packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp

Teuchos: Fixes to one of the tests for Visual Studio

---

packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_decl.hpp
packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_def.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/mloptions_refmaxwell.tex
packages/muelu/doc/UsersGuide/options.tex
packages/muelu/doc/UsersGuide/options_maxwell.tex
packages/muelu/doc/UsersGuide/options_refmaxwell.tex
packages/muelu/doc/UsersGuide/paramlist.tex
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/doc/UsersGuide/update_params.sh
packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/test/maxwell/CMakeLists.txt
packages/muelu/test/maxwell/Maxwell.xml
packages/muelu/test/maxwell/Maxwell3D.cpp
packages/muelu/test/maxwell/Maxwell_ML.xml
packages/muelu/test/maxwell/Maxwell_ML_MueLu.xml
packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
packages/panzer/mini-em/example/BlockPrec/maxwell-bdot-large.xml
packages/panzer/mini-em/example/BlockPrec/maxwell-bdot-medium.xml
packages/panzer/mini-em/example/BlockPrec/maxwell-bdot-small.xml
packages/panzer/mini-em/example/BlockPrec/maxwell-exterior-large.xml
packages/panzer/mini-em/example/BlockPrec/maxwell-exterior-medium.xml
packages/panzer/mini-em/example/BlockPrec/maxwell-exterior-small.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml

@trilinos/panzer @trilinos/muelu 
- MiniEM: Set better smoother and rebalancing defaults on Cuda
- MiniEM: XML files for BDot and exterior meshes
- MueLu Maxwell test: Hook up ML RefMaxwell
- MueLu RefMaxwell: Allow ML style parameter lists
- MueLu RefMaxwell: Allow reuse

MiniEM & RefMaxwell changes

---

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp

MueLu: Relative diagonal boosting support bugfix

---

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp

Update doxygen parameter to match method definition

panzer: fix typo in doxygen

---

packages/teko/CMakeLists.txt
packages/teko/cmake/Teko_Config.h.in
packages/teko/src/Epetra/Teko_BlockedEpetraOperator.cpp
packages/teko/src/Epetra/Teko_BlockedEpetraOperator.hpp
packages/teko/src/Epetra/Teko_StridedEpetraOperator.cpp
packages/teko/src/Epetra/Teko_StridedEpetraOperator.hpp
packages/teko/src/Tpetra/Teko_BlockedTpetraOperator.cpp
packages/teko/src/Tpetra/Teko_BlockedTpetraOperator.hpp
packages/teko/src/Tpetra/Teko_StridedTpetraOperator.cpp
packages/teko/src/Tpetra/Teko_StridedTpetraOperator.hpp

closes #5181 
Adding a configure option to turn on/off debug messages. Off by default

Teko: Adding a configure time option to remove debug output

---

packages/teuchos/comm/src/Teuchos_StackedTimer.cpp

@csiefer2 
Fix code for MSVC
This helps Trilinos toward building on windows platforms

Teuchos: replacing not with ! for MSVC compiler

---

packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyBasis.hpp
packages/intrepid2/unit-test/Orientation/CMakeLists.txt
packages/intrepid2/unit-test/Orientation/Cuda/CMakeLists.txt
packages/intrepid2/unit-test/Orientation/Cuda/test_orientationtools_modify_basis_hcurl.cpp
packages/intrepid2/unit-test/Orientation/Cuda/test_orientationtools_modify_basis_hdiv.cpp
packages/intrepid2/unit-test/Orientation/Cuda/test_orientationtools_modify_basis_hgrad.cpp
packages/intrepid2/unit-test/Orientation/Cuda/test_orientationtools_modify_basis_lower_order.cpp

Cuda interface for orientation tools
This feature is requested from @mperego 
New tests on cuda are established and passed on white.

Intrepid2 - cuda orientation tools

---

packages/muelu/test/maxwell/Maxwell3D.cpp
packages/xpetra/src/Map/Xpetra_TpetraMap_def.hpp

Should fix #5194.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5196)

Xpetra: fix issue 5194

---

packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_decl.hpp
packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp
packages/muelu/utils/misc/makepr.sh

Fix for MueLu issue reported in issue #5120.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5205)

MueLu: break circular dependence between libmuelu and libmuelu_lgn

---

packages/muelu/test/structured/Driver_Structured.cpp

switch from Gmres solver manager to solver factory in Structured_Driver
This just allows a lot more flexibility in the testing that can be done using command line arguments.
* Closes #5198
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
I performed a local build and test

MueLu: interfacing Structured_Driver to more general iterative solver

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
packages/fei/base/SNL_FEI_Structure.cpp
packages/fei/base/fei_FEDataFilter.cpp
packages/fei/base/fei_TemplateUtils.hpp
packages/fei/base/snl_fei_RaggedTable.hpp
packages/fei/unit_tests_base/fei_UBase_set_shared_ids.cpp

@trilinos/fei 
Fixed warnings and set Werror for FEI in the GC 7.2.0 PR build.
Removed a handful of unused variables.
This completes #4507 and is work toward Issue #3178, eventually setting -Werror for all packages.
This was tested in debug and release Jenkins builds.

Fix warnings and set Werror for FEI in GCC 7.2.0 build

---

packages/ifpack2/src/Ifpack2_Details_CrsArrays.hpp

Ifpack2: Fixing compiler error w/ Cuda 10.1

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml

Reuse more matrix information in RefMaxwell

RefMaxwell: More reuse

---

packages/muelu/test/scaling/DriverCore.hpp

MueLu: Driver header cleanup

---

packages/xpetra/src/Map/Xpetra_Map.hpp

Addresses issue #5233.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5243)

Xpetra: fix for issue #5233

---

cmake/ctest/drivers/geminga/cron_driver.sh

Fixes issue #5247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5248)

MueLu: testing: fix timeouts in geminga nightly testing

---

packages/ifpack2/src/CMakeLists.txt
packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
packages/ifpack2/src/Ifpack2_Details_ScaledDampedResidual.hpp
packages/ifpack2/src/Ifpack2_Details_ScaledDampedResidual_decl.hpp
packages/ifpack2/src/Ifpack2_Details_ScaledDampedResidual_def.hpp
packages/ifpack2/src/Ifpack2_Relaxation_decl.hpp
packages/ifpack2/src/Ifpack2_Relaxation_def.hpp

1. Introduce a new "scaled damped residual" vector kernel.
2. Use this new kernel in `Ifpack2::Chebyshev`.
* Reduce the number of parallel kernel launches
* Avoid extra passes over vectors
* Closes #5249

Ifpack2::Chebyshev: Fix #5249 (fuse kernels)

---

cmake/ctest/drivers/geminga/cron_driver.sh

Update OpenMPI version on geminga. See #5251.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5266)

MueLu: testing: update openmpi on geminga

---

packages/muelu/research/regionMG/examples/structured/CMakeLists.txt
packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp

A couple formulae are adjusted in the receive/send GIDs calculations
These changes are fixing some logic mistakes in the experimental region driver.

MueLu: fix region driver 3 d

---

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp
packages/tpetra/core/test/CrsMatrix/CMakeLists.txt
packages/tpetra/core/test/CrsMatrix/CrsMatrix_StaticImportExport.cpp
packages/tpetra/core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp

Allow CrsMatrix with StaticProfile to resize during import/export
See #5164 
* Closes #5164 
Tpetra tests pass locally

Tpetra: Allow CrsMatrix with StaticProfile to resize during import/export

---

packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
packages/teuchos/core/src/Teuchos_ScalarTraits.hpp
packages/teuchos/core/test/ScalarTraits/ScalarTraits_test.cpp

@trilinos/ifpack2 @vbrunini @trilinos/muelu 
1. Clean up `Ifpack2::Relaxation` initialize and compute.
2. Remove use of try-catch as control flow in `Ifpack2::Chebyshev`.
* Closes #5260 
* Blocked by #4726

Ifpack2: Fix #5260 (Chebyshev using try-catch for control flow)

---

packages/tempus/src/Tempus_StepperExplicitRKObserver.hpp
packages/tempus/src/Tempus_StepperExplicitRKObserverComposite.cpp
packages/tempus/src/Tempus_StepperExplicitRKObserverComposite_decl.hpp
packages/tempus/src/Tempus_StepperExplicitRKObserverComposite_impl.hpp
packages/tempus/src/Tempus_StepperExplicitRK_decl.hpp
packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
packages/tempus/src/Tempus_StepperObserverComposite.cpp
packages/tempus/src/Tempus_StepperObserverComposite_decl.hpp
packages/tempus/src/Tempus_StepperObserverComposite_impl.hpp

Explicit ERK stepper observer -> composite observer.
Needs from applications.
No new test is necessary because if the cast fails, an exception will be thrown. Thus, the current tests are just sufficient.

Tempus: pactch from Empire

---

packages/trilinoscouplings/cmake/Dependencies.cmake
packages/trilinoscouplings/cmake/TrilinosCouplings_config.h.in

TrilinosCouplings: More updates for Avatar

---

packages/seacas/applications/blot/blot.f
packages/seacas/applications/blot/cgi/vdicps.f
packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.C

Fix a couple bugs that crept into last snapshot:
* Missing output parameter in warning message
* Bad string copy in fortran code
* Remove old comment (not a bug fix; just a change)

SEACAS: bug fix for may snapshot

---

packages/xpetra/sup/Utils/Xpetra_IO.hpp
packages/xpetra/test/BlockedCrsMatrix/BlockedCrsMatrix_UnitTests.cpp
packages/xpetra/test/BlockedCrsMatrix/ThyraBlockedOperator_UnitTests.cpp

Fixes issue #5311.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5313)

Xpetra: fix issue #5311

---

packages/epetra/src/Epetra_IntMultiVector.h
packages/epetra/src/Epetra_MultiVector.h

epetra: Fix for unguarded SuperLU macro

---

packages/belos/src/BelosGCRODRSolMgr.hpp
packages/belos/test/GCRODR/test_gcrodr_complex_hb.cpp
packages/teuchos/numerics/src/Teuchos_LAPACK.cpp

The generalized GEEV interface in Teuchos::LAPACK has been written
so that templated code can use a single call to LAPACK routines that
vary arguments based on real vs. complex arithmetic.  The GEEV and
GGEVX call both copy eigenvalues back from LAPACK only when the integer
(info) comes back zero.  Unfortunately, info is actually a pointer to
the integer.  So, when info is checked to be zero, the pointer is checked
to be zero.  It is not, so the values are not copied for calls to this
method that are complex-valued.  This commit fixes that error.
GEEV/GGEVX would not return eigenvalues in complex arithmetic.  This affects users of those routines, including solvers like Belos' GCRODR.
MacOSX, GCC7, Serial

Fix std::complex<> interface to GEEV/GGEVX in Teuchos::LAPACK

---

packages/muelu/src/Utils/MueLu_AvatarInterface.hpp
packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Tpetra_main.cpp
packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp

MueLu/TrilinosCouplings: More avatar stuff

---

packages/tpetra/core/src/Tpetra_withLocalAccess_MultiVector.hpp

@trilinos/tpetra @trilinos/ifpack2
If users enable both OpenMP and Serial in Tpetra, then for Tpetra's Serial back-end, Kokkos::DefaultHostExecutionSpace differs from the host execution space.  This was causing trouble with Tpetra::withLocalAccess, resulting in an Ifpack2 build error.  This commit fixes that.
* Closes #5336 
Set the following CMake options:
```
-D Trilinos_ENABLE_OpenMP:BOOL=ON
-D KOKKOS_ENABLE_DEPRECATED_CODE:BOOL=OFF
-D Tpetra_INST_OPENMP:BOOL=ON
-D Tpetra_INST_SERIAL:BOOL=ON
-D Kokkos_ENABLE_OPENMP:BOOL=ON
```

Tpetra: Fix #5336

---

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp
packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp

structured region fix

---

packages/xpetra/sup/Utils/Xpetra_IO.hpp

Xpetra: fix #5349

---

packages/stk/stk_unit_tests/CMakeLists.txt
packages/stk/stk_unit_tests/stk_mesh_fixtures/CMakeLists.txt

whether STKNGP_TEST is enabled.

Fix stk cmake error: stk_mesh_fixtures can be enabled regardless of

---

packages/muelu/test/scaling/DriverCore.hpp

MueLu: Driver updates

---

packages/muelu/test/scaling/DriverCore.hpp
packages/xpetra/src/Operator/Xpetra_TpetraOperator.hpp

MueLu: Fixing UMR in Driver

---

packages/panzer/disc-fe/src/Panzer_L2Projection_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_decl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_impl.hpp
packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp

Use of std::vector and other locals in parallel_for

---

cmake/ctest/drivers/atdm/utils/setup_env.sh

See comment in the script.
I tested this manually locally and I validated this process would work with Jenkins manually.  See:
* https://gitlab.kitware.com/snl/project-1/issues/74#note_583013

Unset http_proxy to fix submit to testing-dev.sandia.gov/cdash

---

packages/xpetra/src/Export/Xpetra_TpetraExport_def.hpp

Xpetra: Fix Xpetra_TpetraExport bug (#5340)

---

cmake/tribits/ci_support/CDashQueryAnalyzeReport.py
cmake/tribits/ci_support/filter-packages-list.py
cmake/tribits/ci_support/get-tribits-packages-from-files-list.py
cmake/tribits/python_utils/gitdist.py

Snapshot of TriBITS, mostly to fix Python3 stuff from @prwolfe.  See  details in https://github.com/trilinos/Trilinos/commit/dbc0ebcf84dc7cd1d0b731bf16a3d921ddd5a287

Fix TriBITS stuff for Python3

---

packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_decl.hpp
packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_def.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/options_refmaxwell.tex
packages/muelu/doc/UsersGuide/paramlist.tex
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/test/maxwell/Maxwell3D.cpp
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml

- Improve robustness of Chebyshev smoothing.
- Add option to visualize aggregates.
- Allow passing 'Ms' matrix for construction of nodal aggregates.
- Options for solving only using nodal or edge hierarchy.

RefMaxwell changes

---

packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory.cpp
packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
packages/panzer/mini-em/example/BlockPrec/solverAugmentation.xml
packages/panzer/mini-em/example/BlockPrec/solverAugmentationUseILU.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell2D.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellOpenMP.xml
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp

The MiniEM - Epetra tests were disabled in PR #5228. I made the necessary changes to re-enable them.

MiniEM: Re-enable Epetra tests

---

commonTools/framework/clean_workspace/clean_workspace.py
commonTools/framework/clean_workspace/unittests/test_clean_workspace.py

remove the directory tree. I know better of course
and python has done a nice job of complaining about
it at least.

I keep making the mistake of expecting unlink to

---

packages/teuchos/parameterlist/src/Teuchos_ParameterList.cpp

Fix 2 shadowing warnings in `Teuchos_ParameterList.cpp`.

Teuchos::ParameterList: Fix 2 shadowing warnings

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/doc/UsersGuide/masterList.xml
packages/muelu/doc/UsersGuide/paramlist_hidden.tex
packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp
packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
packages/muelu/src/MueCentral/MueLu_MasterList.cpp
packages/muelu/test/unit_tests/Hierarchy.cpp

- Add option for fused prolongation+update.
- Add option for explicit transpose in MueLu RefMaxwell

MueLu: Fused prolongation+update, explicit transpose in RefMaxwell

---

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_NonlocalAfterResume.cpp

... and profile type is StaticProfile.
Closes: #5440
How was it tested:
All Tpetra tests pass locally with and without deprecated code ON.

Tpetra: Fix for the case of import/export operations when the target is locally indexed

---

packages/tpetra/core/example/Finite-Element-Assembly/CMakeLists.txt
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_Element.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_FE_SP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_MeshDatabase.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_commandLineOpts.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp

Total Element Loop and FECrsMatrix are done.
Graph assembly is *not* Kokkos-ized.
Tested w/ SerialNode, OpenMP & Cuda.

Tpetra: Updating chunks of the FiniteElementAssembly Example to do Kokkos-ized Matrix Assembly

---

packages/muelu/src/Smoothers/MueLu_DirectSolver_def.hpp
packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_def.hpp

Avoid some unnecessary throws in the creation of smoothers and coarse solvers. Hopefully this makes debugging a bit easier.

MueLu: Avoid some try-catch in smoother and coarse solver creation

---

packages/intrepid2/src/Discretization/Integration/Intrepid2_CubatureControlVolumeBoundaryDef.hpp

Intrepid2: Deleted extraneous console output.

---

packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_Element.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_FE_SP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_MeshDatabase.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_commandLineOpts.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_main.cpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp
packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_utility.hpp
packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp

Fix #5457 and #5458.  These relate to Tpetra's finite-element assembly examples.
* Closes #5457, #5458

Tpetra: Fix #5457; fix #5458

---

packages/muelu/test/scaling/CMakeLists.txt
packages/muelu/test/scaling/SimpleDriver.cpp
packages/muelu/test/scaling/scaling.xml
packages/muelu/test/scaling/simple-scaling.xml
packages/muelu/test/scaling/simple-scaling.yaml

Adds a simplified version of the MueLu driver for use at the ATPESC training workshop.

MueLu: add simplified driver

---

packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp

Code inside #ifdef HAVE_TPETRA_MM_TIMINGS is broken, and will not compile. 
There is not issue number.

Fix broken code inside HAVE_TPETRA_MM_TIMINGS

---

packages/muelu/test/scaling/MatvecKernelDriver.cpp

Addresses issue #5463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5483)

MueLu: fix syntax error in MatvecKernelDriver

---

packages/galeri/src-xpetra/Galeri_StencilProblems.hpp
packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp

Adding support for system of equations in the structured region driver
This allows to test the robustness of the region multigrid implementation.
* Closes #4304 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
This was tested locally and the tests are running fine.

MueLu region driver multiple dofs per node

---

packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp

Thyra: Fix #5494

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
packages/epetra/src/Epetra_BasicDirectory.cpp
packages/epetra/src/Epetra_Util.h
packages/epetra/test/Bugs_LL/Bug_5791_StaticProfile_LL/cxx_main.cpp
packages/epetra/test/Bugs_LL/Bug_5794_IndexBase_LL/cxx_main.cpp
packages/epetra/test/Bugs_LL/Bug_5797_Sort_MakeColMap_LL/cxx_main.cpp
packages/epetra/test/FEVector/fevector.cpp
packages/epetra/test/MapColoring/cxx_main.cpp
packages/epetra/test/MapColoring_LL/cxx_main.cpp
packages/epetra/test/RowMatrix/cxx_main.cpp
packages/epetra/test/RowMatrixTransposer/cxx_main.cpp
packages/epetra/test/RowMatrix_LL/cxx_main.cpp
packages/epetra/test/VbrMatrix/cxx_main.cpp

@trilinos/epetra 
Fixed warning-errors and set `-Werror` for Epetra in the GCC 7.2.0 PR build.
Wrapped variables Werror sees as unused that are only used by asserts in `#ifndef NDEBUG`.
Wrapped or changed some `int` as `unsigned int` to fix the `always false [-Werror=strict-overflow]` Werrors.
This completes #4468 and is work toward Issue #3178, eventually setting `-Werror` globally.
This was tested sucessfully running the GCC 7.2.0 PR Jenkins job.

Fix warning-errors and set Werror for Epetra in GCC 7.2.0 PR build

---

cmake/std/atdm/sems-rhel7/environment.sh

@trilinos/EM-Plasma
Changed `Trilinos/cmake/std/atdm/sems-rhel7/environment.sh` lines that include:
```
export ATDM_CONFIG_LAPACK_LIBS="-L${LAPACK_ROOT};-llapack"
export ATDM_CONFIG_BLAS_LIBS="-L${BLAS_ROOT}/lib;-lblas" 
```
to:
```
export ATDM_CONFIG_LAPACK_LIBS="/usr/lib64/liblapack.so.3"
export ATDM_CONFIG_BLAS_LIBS="/usr/lib64/libblas.so.3"
```
Ran into an issue where Trilinos would not build successfully on a RHEL7 machine because it could not find the `lapack` and `blas` libraries.  This points to the right library files.
The configure command that was used:
```
cmake \
-GNinja \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake,cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake \
-DCMAKE_INSTALL_PREFIX=/home/josbrau/Documents/aaa/Trilinos_Install \ …
```

Fixed lapack and blas lib locations.

---

packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.cpp
packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.h
packages/ml/src/RefMaxwell/ml_RefMaxwell.cpp
packages/ml/src/RefMaxwell/ml_RefMaxwell.h
packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp
packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.h
packages/ml/src/Utils/ml_ValidateParameters.cpp
packages/ml/test/RefMaxwell/cxx_main.cpp

ML: Updates to RefMaxwell

---

packages/zoltan2/src/algorithms/partition/Zoltan2_TaskMapping.hpp

Very minor change to avoid division by zero in corner-case testing

zoltan2:  minor change to avoid divide-by-zero

---

packages/nox/src-thyra/NOX_Thyra_Group.C
packages/nox/src-thyra/NOX_Thyra_Group.H
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.cpp
packages/nox/src-thyra/Thyra_NonlinearSolver_NOX.hpp
packages/nox/test/epetra/Thyra/Thyra_1DFEM.C
packages/nox/test/epetra/Thyra/Thyra_2Dsim_JFNK.C
packages/nox/test/epetra/Thyra/Thyra_SingleStepSolver_1D.C
packages/nox/test/tpetra/Tpetra_1DFEM.cpp
packages/nox/test/tpetra/Tpetra_Heq.cpp
packages/nox/test/tpetra/Tpetra_OperatorTests.cpp

@trilinos/nox 
The `Right Scaling Vector` was normally initialized and never updated. So it makes sense to only compute its reciprocal once and not update it. 
Now that we are updating the scaling vector dynamically in Drekar, the reciprocal must be updated at as well to ensure correctness.
@egphill @rppawlo apart from testing in Drekar, what do you recommend?

NOX: update inv right scale vector

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
packages/rol/adapters/mpi/src/function/ROL_PinTConstraint.hpp
packages/rol/adapters/mpi/src/function/ROL_PinTHierarchy.hpp
packages/rol/adapters/mpi/src/vector/ROL_PinTVectorCommunication.hpp
packages/rol/adapters/mpi/test/function/test_hierarchy_coarse_rebalance.cpp
packages/rol/adapters/mpi/test/function/test_restrict_prolong.cpp
packages/rol/adapters/mpi/test/function/test_restrict_prolong_rebalance.cpp
packages/rol/adapters/mpi/test/function/test_timestamp_coarsening.cpp
packages/rol/adapters/mpi/test/vector/test_02.cpp
packages/rol/example/PDE-OPT/TOOLS/sysbuilder.hpp
packages/rol/example/PDE-OPT/dynamic/navier-stokes/AugmentedSystem.cpp
packages/rol/example/PDE-OPT/dynamic/navier-stokes/dynpde_navier-stokes.hpp
packages/rol/example/PDE-OPT/dynamic/navier-stokes/initial_condition.hpp
packages/rol/example/PDE-OPT/dynamic/navier-stokes/obj_navier-stokes.hpp
packages/rol/example/PDE-OPT/dynamic/thermal-fluids/dynpde_thermal-fluids.hpp
packages/rol/example/PDE-OPT/dynamic/thermal-fluids/initial_condition.hpp
packages/rol/example/PDE-OPT/dynamic/thermal-fluids/obj_thermal-fluids.hpp
packages/rol/example/tempus/example_parabolic_modeleval.hpp
packages/rol/example/tempus/example_parabolic_modeleval_forward-adjoint.hpp
packages/rol/example/tempus/example_parabolic_thyravec.hpp

@trilinos/rol 
Fixed warning-errors and set `-Werror` for ROL in the GCC 7.2.0 PR build.
Removed a number of unused variables.
Changed or cast a few variable types from `uint` to `long long` to avoid `Werror=sign-compare`.
Added a virtual dtor for PinTVectorCommunication.
Moved one varable so it would be initialized in the right order to quiet a `Werror=reorder`.
This completes #4469 and is work toward Issue #3178, eventually setting `-Werror` globally.
This was tested [sucessfully running the GCC 7.2.0 PR Jenkins job](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5322447&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20190718-2144-Experimental&filtercombine=and).

Fix Warning-Errors and set Werror for ROL in GCC 7.2.0 PR build

---

packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
packages/stokhos/test/UnitTest/Stokhos_KokkosViewMPVectorUnitTest.hpp
packages/stokhos/test/UnitTest/Stokhos_KokkosViewUQPCEUnitTest.hpp

Stokhos:  Add assign_data() to ViewMapping specializations.

---

cmake/ctest/drivers/rocketman/CMakeLists.txt
cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_tpetra_performance_rocketman.cmake
packages/tpetra/core/example/Finite-Element-Assembly/CMakeLists.txt

Tpetra/Ctest: Trying to set up performance testing

---

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
packages/anasazi/epetra/example/BlockDavidson/BlockDavidsonEpetraEx.cpp
packages/anasazi/epetra/example/BlockKrylovSchur/BlockKrylovSchurEpetraEx.cpp
packages/anasazi/epetra/example/BlockKrylovSchur/BlockKrylovSchurEpetraExSVD.cpp
packages/anasazi/epetra/example/LOBPCG/LOBPCGEpetraExSimple.cpp
packages/anasazi/epetra/test/BlockKrylovSchur/cxx_main_nh.cpp
packages/anasazi/epetra/test/BlockKrylovSchur/cxx_main_sym.cpp
packages/anasazi/epetra/test/Epetra64Driver/build_simple_matrices.hpp
packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp
packages/anasazi/epetra/test/OrthoManager/cxx_mattest.cpp

Fixed warnings and set Werror for Anasazi in the GC 7.2.0 PR build.
Wrapped variables only used by asserts Werror sees as unused in TEUCHOS_ASSERT().
Removed a few sections of unreachable code sitting behind always-false if statements.
This completes #4475 and is work toward Issue #3178, eventually setting -Werror for all packages.
This was tested in debug and release Jenkins builds.

Fix warnings and set Werror for Anasazi in GCC 7.2.0 build

---

packages/muelu/example/basic/stratimikos_ParameterList.xml

Updates for ATPESC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5586)

MueLu: updates for ATPESC

---

packages/tpetra/core/example/Finite-Element-Assembly/CMakeLists.txt

Tpetra: Fix performance test cmake logic

---

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp

Made it so you only turn on delayed fields if needed

Turned off delated fields unless needed

---

packages/belos/src/BelosGmresPolyOp.hpp

BelosGmresPolyOp: Build fix for float.

---

packages/muelu/src/Graph/MatrixTransformation/MueLu_UnsmooshFactory_def.hpp

A default nnz per row for the prolongator was originally hard-coded.
It is now replaced by a real upper bound for nnz per row.
This work will allow the code to work properly after deprecated code in Tpetra is permanently removed.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #5602
* Part of #5614
* Composed of 
A local test with the change has been performed and all tests pass properly.

MueLu: fixing the number of non-zeros per row in unsmoosh factory

---

packages/ifpack2/src/Ifpack2_Container_def.hpp

ifpack2: Fix use of deprecated execution_space::fence() static method.

---

packages/muelu/test/scaling/Driver.cpp

MueLu: Optional Stacked Timer output for MueLu Driver

---

packages/seacas/IossProperties.md
packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.C
packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.h

Make the setting of the flush interval work in serial.  Previously only affected parallel runs, but it also needs to work in serial.
If set to `0`, then no flushing; if `1`, then flush every step.  If `n>1`, then flush every `n` steps.  If unset (signified by `-1`), then flush every 10 seconds if serial or HISTORY file; else flush every step if parallel.
Related to #5479.  See that discussion for more details.

IOSS: Redo the flush interval calculations for serial

---

packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp

Ghosted worksets don't have a working partitioner. Old method was never used, however it contained a bug. This branch fixes the bug. A more thorough fix is in development in #5236.
All panzer tests pass.

Adding fix for partitioning worksets on ghosted meshes

---

packages/ml/src/Utils/ml_MultiLevelPreconditioner_NullSpace.cpp

ML: Fixing nullspace memory leak

---

packages/seacas/libraries/ioss/src/Ioss_SerializeIO.C

A previous snapshot had changed the Ioss_SerializeIO class by removing a member variable which was private and unused.  This removal resulted in an empty if block which was removed; however, it was part of an if/ifelse/else block and the removal of the empty if block was incorrect since entering that block would result in *not* entering the other blocks.  
Added back the if block which fixes the behavior of Nalu which is hanging due to this change.
PR also includes some clang-format changes.

SEACAS: ioss - Fix bad previous change in SerializeIO

---

cmake/ctest/drivers/rocketman/CMakeLists.txt

Ctest: Rocketman driver update

---

packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp

Added check for divide by 0

---

packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp

Fixes issue 5687.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5689)

MueLu: enable debugging in Zoltan2 MJ

---

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp
packages/muelu/research/regionMG/examples/structured/CMakeLists.txt

Adding Gauss-Seidel to region MG

---

packages/panzer/mini-em/example/BlockPrec/main.cpp
packages/panzer/mini-em/example/BlockPrec/solverAugmentation.xml
packages/panzer/mini-em/example/BlockPrec/solverAugmentationEpetra.xml
packages/panzer/mini-em/example/BlockPrec/solverAugmentationUseILU.xml
packages/panzer/mini-em/example/BlockPrec/solverMLRefMaxwell.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp
packages/panzer/mini-em/src/solvers/MiniEM_DiscreteGradient.hpp
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.hpp
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory_Augmentation.cpp
packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory_Augmentation.hpp
packages/panzer/mini-em/src/solvers/MiniEM_Utils.cpp
packages/panzer/mini-em/src/solvers/MiniEM_Utils.hpp

- Add discrete curl operator to MiniEM (thanks, @egphill !)
- Clean up Maxwell solver by moving old augmentation solver to its own file.

MiniEM solver updates

---

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp

This is a temporary workaround for the most reproducible error of the errors in #5179 .
As we debug the issue, we will reverse this workaround.
In response to user deadlines, we hope this workaround will enable users to make progress.
Tpetra tests on linux all pass
Using instructions for running MueLu_Driver.cpp in #5179, type 1 failures were eliminated.

Tpetra:  temporary workaround for #5179

---

packages/panzer/adapters-stk/test/evaluator_tests/gather_solution.cpp

Panzer: consistent ordinals

---

packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_Utilities_UQ_PCE.hpp
packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixUQPCEUnitTest.hpp

Stokhos: fix for #5742

---

packages/amesos2/src/Amesos2_KLU2_def.hpp
packages/amesos2/test/solvers/KLU2_UnitTests.cpp

This would previously just seg fault on the NULL ptr.
Provide better information if numeric factorization fails, for example if the matrix was singular.

Amesos2: Add throw for NULL numeric factorization (#5666)

---

packages/piro/test/MockModelEval_A_Tpetra.hpp

Piro: fix Tpetra ordinal issues.

---

packages/amesos2/example/GappedMtxGIDs-1proc.cpp

Amesos2: Count entries in matrix before allocating

---

cmake/ctest/drivers/geminga/CMakeLists.txt
cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc.cmake

Testing: change valgrind test days
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5761)

Testing: change valgrind test days / adding --leak-check=full

---

packages/shylu/shylu_dd/bddc/src/shylu_SolverMueLu.hpp

Closes: #5538
Part of: #5602 
Required to compile with Tpetra deprecated code off.

ShuLU: fix for #5538

---

packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp

In MueLu decoupled line smoothing, add dofs per node information to the Ifpack2 BlockRelaxation parameter list. This is necessary for decoupling to work (since Ifpack2 does not otherwise know the dofs/node) and was supposed to be included in PR #5587.

MueLu: set dofs/node for decoupled line smoothing

---

packages/seacas/libraries/exodus/test/test_ts_partial_nvar_rd.c
packages/seacas/libraries/ioss/src/main/CMakeLists.txt
packages/seacas/libraries/suplib_cpp/fmt/format-inl.h

Fixing test failures for thread-safe build
* one test was outputting debug output which messed up gold compare
* one test was using same output filename as another test; when run simultaneously, they would overwrite file causing problems.
Eliminating compiler warning for intel build

Seacas test fix

---

packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp
packages/xpetra/src/Import/Xpetra_TpetraImport_def.hpp

Xpetra: Fixing typo

---

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp

Panzer STK: Avoid integer conversion sign change warning

---

packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp
packages/ml/src/Utils/ml_MultiLevelPreconditioner_NullSpace.cpp

empty proc fix and recompute nPDE fix

---

packages/seacas/applications/exodiff/iqsort.C

The `cstdint` include was missing and is needed to define the `int64_t` type used in this file.  This is the same as PR 148 on SEACAS repository (https://github.com/gsjaardema/seacas/pull/148)

SEACAS: Add missing include

---

packages/tpetra/core/src/Tpetra_Import_def.hpp

Add extra debug checks and output to `Tpetra::Import::createRemoteOnlyImport`.  This is part of #5179 debugging.  I don't think anything is wrong with that function, but I suspect that its input may be wrong in some way.

Tpetra::Import: Add debug checks to createRemoteOnlyImport

---

packages/muelu/test/maxwell/CMakeLists.txt
packages/muelu/test/maxwell/Maxwell.xml

Apply nullspace fix in Maxwell test to avoid singular matrix.

MueLu Maxwell test: Fix issue #5850

---

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
packages/tpetra/core/test/Utils/behavior.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5856)

Tpetra: Add threshold for verbose printing

---

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp

- Use the command line parameter `--scale`/`--noscale` not only for the convergence check, but also for printing the scaled or unscaled residual history.
- Fix some mismatches in indentation.
We want to print the same residual norm to the screen, that is also used for the convergence check. This just makes sense and also makes comparisons to the fully structured MG easier.
I ran `ctest` locally and also verified both command line options `--scale`/`--noscale`.
Excerpt from convergence history for `--scale`:
```
0 | Running V-cycle ...
Using scaled residual norm.
0       1.00000000e+00
1       1.54793609e-02
2       2.25334164e-03
3       7.03979575e-04
4       2.63697628e-04
5       1.02842680e-04
6       4.07335984e-05
7       1.62554282e-05
8 …
```

MueLu: improve screen output of region MG residual history

---

packages/tpetra/core/src/Tpetra_Details_extractBlockDiagonal.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp

Tpetra: Adding block-diagonal extraction routine

---

packages/stk/stk_mesh/stk_mesh/baseImpl/EquivalentEntityBlocks.hpp

Fixed warning

---

packages/epetra/src/Epetra_CrsGraph.cpp
packages/epetra/src/Epetra_CrsMatrix.cpp
packages/epetra/src/Epetra_IntMultiVector.cpp
packages/epetra/src/Epetra_MultiVector.cpp

Add variables to shared clause. This fixes build errors in GCC 9
which is more strict about variable usage in parallel sections.
Fixes build on GCC 9 if Epetra_ENABLE_OpenMP=ON
Built on my workstation with GCC 9.1 and OpenMP enabled.

Epetra: fix GCC 9 OpenMP errors #5390

---

packages/muelu/adapters/epetra/MueLu_CreateEpetraPreconditioner.cpp
packages/muelu/adapters/tpetra/MueLu_CreateTpetraPreconditioner.hpp
packages/muelu/src/Graph/HybridAggregation/MueLu_HybridAggregationFactory_def.hpp
packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp
packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_kokkos_def.hpp
packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp
packages/muelu/src/Transfers/BlackBox/MueLu_BlackBoxPFactory_def.hpp
packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeneralGeometricPFactory_def.hpp
packages/muelu/src/Utils/MueLu_TimeMonitor.cpp
packages/muelu/src/Utils/MueLu_Utilities_decl.hpp
packages/muelu/src/Utils/MueLu_Utilities_def.hpp
packages/muelu/test/scaling/DriverCore.hpp
packages/muelu/test/unit_tests/ParameterList/FactoryFactory.cpp

Catching polymorphic exception types by reference, not value.
Prevents warnings on GCC 9.

MueLu: fix -Wcatch-value warnings (#5891)

---

packages/stk/stk_ngp/Jamfile
packages/stk/stk_ngp/stk_ngp/NgpField.hpp
packages/stk/stk_ngp/stk_ngp/NgpFieldParallel.hpp
packages/stk/stk_ngp/stk_ngp/NgpMesh.hpp
packages/stk/stk_ngp/stk_ngp/NgpMultistateField.hpp
packages/stk/stk_ngp/stk_ngp/NgpParallelComm.hpp
packages/stk/stk_unit_tests/stk_ngp/CMakeLists.txt
packages/stk/stk_unit_tests/stk_ngp/NgpMeshTest.cpp
packages/stk/stk_unit_tests/stk_ngp/NgpParallelCommTest.cpp
packages/stk/stk_unit_tests/stk_ngp/NgpParallelSumTest.cpp
packages/stk/stk_unit_tests/stk_ngp/howToNgp.cpp

Bring in ngp::Field versions of parallel_sum, copy_owned_to_shared, and
communicate_field_data.
Also fix some openmp compile issues reported by Roger Pawlowski.

Update stk to Trilinos

---

packages/ml/src/Coarsen/ml_agg_uncoupled.c
packages/ml/src/Coarsen/ml_aggregate.c
packages/ml/src/Coarsen/ml_aggregate.h
packages/ml/src/RefMaxwell/ml_RefMaxwell.cpp
packages/ml/src/RefMaxwell/ml_RefMaxwell.h
packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp
packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp
packages/ml/src/Utils/ml_ValidateParameters.cpp
packages/ml/test/MultiLevelPreconditioner_Sym/MultiLevelPreconditioner_Sym.cpp
packages/ml/test/RefMaxwell/cxx_main.cpp

ML: Experimental aggregation option

---

packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp

CLean up non-needed code in panzer

---

packages/muelu/test/scaling/DriverCore.hpp

MueLu: Fixing Driver coordinates issue

---

packages/trilinoscouplings/examples/scaling/HybridIntrepidPoisson3D_Pamgen_Tpetra_main.cpp
packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp

Fix missing typedefs of LO, GO when Tpetra deprecated off.
Fix is the same as @DrBooom used in fd78156078,
just added to these two other files.
Between this and #5963, the nightly deprecated=OFF build should now be clean.
- N/A My commit messages mention the appropriate GitHub issue numbers.

TrilinosCouplings: fix build errors w/o deprecated

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp

Fix an issue in the local indexing of the Amesos2Smoother nullspace fix. Only apply the fix when the coarse solver is a direct solve.
This should take care of #5928 @bathmatt

MueLu: Fix issue in nullspace fix

---

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp
packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp

fix find region bug

---

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
packages/muelu/src/MueCentral/MueLu_FactoryManager_decl.hpp
packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ScaledNullspaceFactory_def.hpp
packages/xpetra/src/CMakeLists.txt

MueLu/Xpetra: Fixing lingering ScaledNullspaceFactory issues

---

packages/muelu/utils/misc/makepr.sh

@trilinos/muelu @trilinos/xpetra
Upgrade makepr script
PRs generated with `makepr` now follow the Trilinos PR template.
I used the script to create *this* PR for the script....
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5976)

MueLu: upgrade PR script

---

packages/tempus/src/Tempus_TimeStepControl_decl.hpp

Adds setter functions for Output Time Index and Output Time Interval

---

packages/tempus/src/Tempus_StepperDIRK_impl.hpp
packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp

redundant declaration of rk stepper observer

Tempus: fix seg fault rk stepper observer

---

packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp

Round 2 of fixing the nullspace fix..

MueLu: Fix to nullspace fix

---

packages/stk/stk_mesh/stk_mesh/base/ConnectivityMap.hpp
packages/stk/stk_search/stk_search/KDTree.hpp
packages/stk/stk_search/stk_search/KDTree_impl.hpp
packages/stk/stk_unit_tests/stk_balance/UnitTestTransientFields.cpp
packages/stk/stk_unit_tests/stk_io/UnitTestWriteSTKMesh.cpp

Minor stk updates, primarily fix compile error in ConnectivityMap

---

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_ScaledNullspaceFactory_def.hpp
packages/tpetra/core/src/Tpetra_Details_scaleBlockDiagonal.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp
packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp
packages/xpetra/test/Matrix/Matrix_UnitTests.cpp

Somebody wanted the transpose
Stakeholder Feedback: Done in person
Testing: CrsUnitTests4

MueLu/Xpetra/Tpetra: Updates to block diagonal scaling

---

packages/tempus/src/Tempus_StepperDIRK_impl.hpp
packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp

composite observer
This was causing segfault in many applications

Tempus: StepperRKObserver - ensure no-null observer are added to the

---

.github/PULL_REQUEST_TEMPLATE.md

Trilinos: Updating PR template

---

packages/tpetra/core/src/Tpetra_Details_scaleBlockDiagonal.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp
packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp

Testing: Adding new test to check transpose (CrsMatrix_UnitTests4)
Stakeholder Feedback: In person (Tpetra); From myself (TrilinosCouplings)

Tpetra/TrilinosCouplings: Fixing scaling / 2D Feature Extraction

---

packages/muelu/src/Utils/MueLu_AvatarInterface.cpp

Testing: Not PS code; Stakeholder feedback: Internal conversation

MueLu: Fixes to Avatar Interface

---

packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp

Addresses:
https://github.com/trilinos/Trilinos/issues/6043

Add verbose mode to stacked timer

---

packages/fei/unit_tests_base/CMakeLists.txt
packages/fei/unit_tests_base/fei_UBase_DirBC.cpp
packages/fei/unit_tests_base/fei_UBase_Reducer.cpp
packages/fei/unit_tests_base/fei_UBase_SlaveReduce1.cpp
packages/fei/unit_tests_base/fei_UBase_impl_utils.cpp
packages/fei/unit_tests_base/fei_UBase_initSlaveConstraint.cpp

Change FEI_COUT to out in fei's TEUCHOS_UNIT_TESTs.

---

packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.cpp
packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp

ML: Fixing RefMaxwell corner cases

---

cmake/ctest/drivers/rocketman/ctest_linux_nightly_mpi_release_muelu_rocketman.cmake
cmake/ctest/drivers/rocketman/mpi_release_tpetra_deprecated_code_off_downstream_enabled_no_epetra.cmake

Try to speed up nightly testing on rocketman.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6056)

Testing: Tpetra: speed up testing on rocketman

---

packages/ml/examples/MLAPI/AdaptiveSA.cpp
packages/ml/src/MLAPI/MLAPI_MultiLevelAdaptiveSA.h

ML: Mods to AdaptiveSA to allow matrix reading

---

packages/ml/src/RefMaxwell/ml_RefMaxwell.cpp
packages/ml/src/Utils/ml_epetra_utils.cpp
packages/ml/src/Utils/ml_epetra_utils.h

ML: RefMaxwell code cleanup

---

packages/xpetra/test/Cloner/Cloner_UnitTests.cpp

Test failed with Tpetra deprecated off due to missing ifdef guard.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #5602 
* Composed of 
N/A
N/A; this change disables a test in a configuration where it shouldn't be expected to pass.

Xpetra: disable Map cloner test if no Tpetra deprecated

---

packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp

This PR solves issue #6059.
If the user specifies a combination of status tests, all of them are added one at a time.
It has been tested on both Blake and Bowman.

Belos: PR to solve Issue #6059

---

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeHexMeshFactory.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeTetMeshFactory.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_LineMeshFactory.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_MeshFactory.hpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareQuadMeshFactory.cpp
packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareTriMeshFactory.cpp
packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp

These changes ensure that a mesh centered around zero doesn't have a centroid
with a coordinate determined by roundoff error. For the line mesh, ensure that the
normal direction computation doesn't perform a divide by zero.

Panzer address mesh centroid roundoff

---

packages/tpetra/core/src/Tpetra_Details_scaleBlockDiagonal.hpp
packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp

Testing: Disabling incorrect tests; Stakeholder Feedback: Yes

Tpetra: Fixes so that #6076 can pass

---

packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp

Tpetra: Re-enable Test

---

cmake/ctest/drivers/rocketman/mpi_release_tpetra_deprecated_code_off_downstream_enabled_GO_int.cmake

No testing necessary, change to nightly driver only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6084)

Testing: Tpetra: make nightly build faster

---

packages/tempus/src/Tempus_StepperFactory.hpp

Fixed shadow warning

---

packages/seacas/libraries/ioss/src/Ioss_GroupingEntity.h

Fix incorrect variable type causing compiler warning; found right after last seacas snapshot.  Fixed in SEACAS github; applying manually to Trilinos.  Reported in #6106

SEACAS: IOSS - Fix compiler warning

---

packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
packages/muelu/test/unit_tests/Hierarchy.cpp

Testing: Added test in MueLu unit tests

MueLu: Better support for running without a pre smoother

---

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
packages/muelu/test/maxwell/CMakeLists.txt
packages/muelu/test/maxwell/Maxwell3D.cpp
packages/muelu/test/maxwell/Maxwell_ML1.xml
packages/muelu/utils/paramlist/xml2yaml.py
packages/panzer/mini-em/example/BlockPrec/main.cpp
packages/panzer/mini-em/example/BlockPrec/maxwell.xml

@trilinos/muelu @trilinos/panzer 
MueLu:
- script to convert xml input files to yaml
- Better timers for RefMaxwell
- Option to fuse prolongation+update
- Hook up ML-Maxwell1 in MueLu Maxwell test
MiniEM:
- Allow PamGen meshes

MueLu+MiniEM: Maxwell stuff

---

packages/ifpack2/src/Ifpack2_ConfigDefs.hpp
packages/ifpack2/src/Ifpack2_Relaxation_decl.hpp
packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp

Testing: New test in UnitTestRelaxation

Ifpack2: Adding Richardson support to Ifpack2::Relaxation

---

packages/ifpack2/src/Ifpack2_Details_ScaledDampedResidual_decl.hpp
packages/ifpack2/src/Ifpack2_Details_ScaledDampedResidual_def.hpp

Cache Vectors in Chebyshev. Should reduce view allocations.
#6159

Ifpack2 ScaledDampedResidual: Cache vectors

---

packages/anasazi/epetra/test/BlockKrylovSchur/CMakeLists.txt
packages/anasazi/epetra/test/BlockKrylovSchur/cxx_main_solvertest.cpp
packages/anasazi/epetra/test/LOBPCG/CMakeLists.txt
packages/anasazi/epetra/test/LOBPCG/cxx_main.cpp
packages/anasazi/src/AnasaziBlockKrylovSchurSolMgr.hpp
packages/anasazi/src/AnasaziLOBPCGSolMgr.hpp
packages/anasazi/tpetra/test/BlockKrylovSchur/CMakeLists.txt
packages/anasazi/tpetra/test/BlockKrylovSchur/cxx_main_lap.cpp
packages/anasazi/tpetra/test/LOBPCG/CMakeLists.txt
packages/anasazi/tpetra/test/LOBPCG/cxx_main_complex.cpp

The ICGS orthogonalization method has been an option in Anasazi, but has
not been available for some more commonly used eigensolvers, like BKS and
LOBPCG.  Similar to the study performed for Belos, it is of interest to
use this orthogonalization method to see if it improves performance on
more advanced architectures.
Tests were modified to include ICGS orthogonalization.
Tests pass on:  OSX, serial, GCC 9.x

Adds option to use ICGS as orthogonalization method in BKS and LOBPCG

---

cmake/ctest/drivers/rocketman/CMakeLists.txt
cmake/ctest/drivers/rocketman/crontab

Disable avatar testing.
Merge two cronjobs to eliminate gap between testing (hopefully).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6173)

Testing: rocketman: speed up nightly testing

---

packages/muelu/utils/misc/makepr.sh

Updates to makepr.sh; Testing: n/a
See Issue #6188

MueLu: Updates to makepr.sh

---

cmake/ctest/drivers/lightsaber/cron_driver.csh

More lightsaber driver updates

---

packages/tpetra/core/src/Tpetra_Details_residual.hpp

Tpetra: Implementing residual kernel

---

packages/ml/test/MultiLevelPreconditioner_Sym/MultiLevelPreconditioner_Sym.cpp

ML: Adding some memory tracking to a test

---

packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
packages/xpetra/src/Map/Xpetra_EpetraMapFactory.cpp

Xpetra: fixing missing ifdef for non-tpetra builds

---

packages/tpetra/core/src/Tpetra_Details_residual.hpp

Tpetra: Because GCC 5.3.0 hates valid C++

---

packages/tpetra/core/test/MultiVector/CMakeLists.txt
packages/tpetra/core/test/MultiVector/MultiVector_MixedNode.cpp

Testing: new MultiVector_MixedNode test

Tpetra: Sample MultiVector test using Serial and Cuda on different MPI ranks

---

packages/piro/src/Piro_NOXSolver_Def.hpp
packages/piro/src/Piro_ObserverBase.hpp
packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective.hpp

@trilinos/piro @trilinos/rol
Albany needs a method to identify whether an optimization variable has changed in order to determine whether calculations should be performed on the variable within the model evaluator. Albany stores these calculations anyways so it doesn't make sense to recompute functions that don't need to be recomputed. Using this information, Albany can recompute functions when necessary.
I also added some timers to Piro to give Albany more information about performance.

Piro/ROL: Modifications to pass optimization variable changes to apps

---

packages/piro/src/Piro_NOXSolver_Def.hpp

@trilinos/piro
Should fix compilation error

Piro: remove template form ParameterList get to avoid compilation error

---

packages/belos/src/BelosCGIter.hpp

Switch from MvTransMv to MvDot, since all MVs only have a single vector.

Belos CGIter: Use MvDot instead of MvTransMv
