packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter.hpp, packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter_Def.hpp, packages/piro/src/Piro_TempusSolver.hpp, packages/piro/src/Piro_TempusSolver_Def.hpp
The purpose of this PR is to simplify how Tempus time step control is specified in an Albany input file.     The various options in the Tempus Time Step Control were confusing to Albany users, and there was a request to have a simpler time-step control algorithm that is easy to specify in Albany, where the time-step is amplified if a solve is successful, and reduced if a solve fails.  The idea is to cut down the number of parameters Albany users need to set / understand (e.g., Maximum / Minimum Value of Monitoring Function) by hiding all the detailed Tempus Time Step Control values in Piro. 
To address the feature request, this PR adds an option in Piro::TempusSolver to take 'Albany Time Step Control Options' sublist, in place of the Tempus->Tempus Integrator->Time Step Control timelist. …
=> Albany Time Step Control through Piro 

cmake/std/atdm/ride/tweaks/CUDA_COMMON_TWEAKS.cmake
This disables tests already failing in the matching non-RDC build so those failures have nothing to do with RDC (see #4502).  This will allow us to promote this build to the "ATDM" group and maintain it.  This build is too expensive to run as a Trilinos PR build so the next best thing is to run it as a nightly build.
* Disables ROL tests from #3543
* Disables TrilinosCouplings tests from #3749
* Disables Zoltan tests from #4042
I tested this on 'ride' with:
```
$ cd /home/rabartl/Trilinos.base/BUILDS/RIDE/CHECKIN/
cuda-9.2-gnu-7.2.0-rdc-release-debug-pt \
--enable-all-packages=on --configure
```
which showed the disables:
```
$ grep _DISABLE cuda-9.2-gnu-7.2.0-rdc-release-debug-pt/configure.out
...
-- Zoltan_ch_ewgt_zoltan_parallel: NOT added test because …
```
=> Disable tests in cuda rdc PT build already failing in non-rdc build (#4502)

packages/tempus/src/Tempus_StepperDIRK_decl.hpp, packages/tempus/src/Tempus_StepperDIRK_impl.hpp, packages/tempus/src/Tempus_StepperExplicitRK_decl.hpp, packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
To better setup RK methods, it is nice to set the Butcher Tableau
directly instead of through a ParameterList.  Added set method for
the tableaus for both ExplicitRK and DIRK.  The IMEX and IMEX
partitioned already have these methods.
Thanks to Kris Beckwith for pointing out these missing methods.
#4821
=> Tempus: Add method to set Tableaus.

packages/kokkos-kernels/perf_test/graph/KokkosGraph_color_d2.cpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_color.hpp
=> KokkosKernels: Update d2_graph_color following deprecation

packages/muelu/test/scaling/MMKernelDriver.cpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_decl.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp
1) compute rowptr in place
2) optimize copy out for inplace rowptr + bulk val/ind copies
3) move thread local deallocations into the parallel region (each
thread owns their own dealloc.
4) Fix logic error in original MM driver.
5) Correct Teuchos timer creations
6) Update MM Driver
Closes: #4850
Driver changes not tested with TPL MKL and ViennaCL, or with DescriptiveStats
I will need to add another pull request that adds the descriptive stats
code, and then MM driver works correctly w/that enabled.
Updated Code: Ran on KNL, since that is the only thing I can actually get
through the queue.
Before:
```
OMP_NUM_THREADS=8 \
OMP_PROC_BIND=spread \
OMP_PLACES=cores \
$HOME/Trilinos-develop/build/packages/muelu/test/scaling/MueLu_MMKernelDriver.exe \
--matrixfileA=/tmp/Brick3D_50/A_0.m \ …
```
=> MueLu: update LTG Matrix kernels in TpetraExt

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp
- Make `Tpetra::CrsGraph` implement the "new" DistObject interface
- Fix build warning (unused variable) in `Tpetra::CrsMatrix`
* Closes #4852 
* Part of #4853 
- Lots of packages with GCC + OpenMP
- Some packages with CUDA 9.2 + GCC
=> Tpetra: Fix #4852 (make CrsGraph implement "new" DistObject interface)

cmake/std/atdm/sems-rhel7/environment.sh
It appears that changing the ctest parallel test level from the default of 10 to 4 on 'ascicgpu15' seems to have fixed all of the test failures in the build:
* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-static-release-debug`
and therefore I also suspect for the build:
* `Trilinos-atdm-sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug`
as the 'static' build has more errors than the 'shared' build.  These builds support the ATDM APP Gemma (see [TRIL-255](https://sems-atlassian-son.sandia.gov/jira/browse/TRIL-255)).
Therefore, this change this would seem to resolve the issues #4599, #4790, and #4801.
See [ATDV-144](https://sems-atlassian-srn.sandia.gov/browse/ATDV-144).
I tested this on 'ascicgpu15' which should be identical to 'ascicgpu14' that runs the builds:
* …
=> Use ctest -j4 for CUDA builds by default for sems-rhel7 (ATDV-144, #4599, #4790, #4801)

packages/tempus/src/Tempus_IntegratorBasic_impl.hpp, packages/tempus/src/Tempus_TimeStepControl_impl.hpp
In the output interval and the screen output interval, all the
intervals are placed in a vector along with the specified output
times or indices, and then sorted. This allowed all the output times
and indices to be in one vector and searched. However when the
number of time steps reaches millions, the sort is far too expensive.
This reworks the interval specification so that it is not part
of the vector or sorting.
#4836
Passes all tests on Mac.
=> Tempus: improve interval output setup

packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockReorderManager.hpp, packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp, packages/xpetra/src/BlockedMap/Xpetra_BlockedMap.hpp, packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector.hpp, packages/xpetra/src/BlockedVector/Xpetra_BlockedVector.hpp, packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp, packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp, packages/xpetra/src/Map/Xpetra_EpetraMap.hpp, packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp, packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp, packages/xpetra/src/Operator/Xpetra_Operator.hpp, packages/xpetra/src/Vector/Xpetra_EpetraIntVector.hpp, packages/xpetra/sup/StridedMap/Xpetra_StridedMap.hpp, packages/xpetra/sup/StridedMap/Xpetra_StridedMapFactory.hpp, packages/xpetra/sup/Utils/Xpetra_IO.hpp, packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
=> Xpetra:  Remove Unused Parameter Warnings

cmake/std/atdm/waterman/environment.sh, cmake/std/atdm/waterman/tweaks/ALL_COMMON_TWEAKS.cmake, cmake/std/atdm/waterman/tweaks/CUDA-9.2_RELEASE-DEBUG_CUDA_POWER9_VOLTA70.cmake, cmake/std/atdm/waterman/tweaks/CUDA_COMMON_TWEAKS.cmake
This PR branch extends the ATDM Trilinos builds on 'waterman' to add the extra TPLs and Trilinos packages needed by SPARC.  We need to be supporting SPARC on 'waterman' and extend the SPARC Trilinos Integration testing to include a CUDA build on 'waterman' (see [ATDV-151](https://sems-atlassian-srn.sandia.gov/browse/ATDV-151)).
I tested this on 'waterman' with:
```
$ cd /home/rabartl/Trilinos.base/BUILDS/WATERMAN/CTEST_S/
$ ./ctest-s-local-test-driver.sh cuda-9.2-release-debug
*** 
*** ./ctest-s-local-test-driver.sh cuda-9.2-release-debug
***
Hostname 'waterman11' matches known ATDM host 'waterman' and system 'waterman'
Setting compiler and build options for buld name 'default'
Using …
```
=> Extend ATDM Trilinos 'waterman' builds to support SPARC (ATDV-151)

packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_decl.hpp, packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp, packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_GDSWCoarseOperator_def.hpp
This PR changes the insert method from a local insert to a global insert for the coarse basis matrix in FROSch. Furthermore, the GDSWCoarseOperator now uses the different coarse components correctly; the correct boolean variables are used now. 
A local insert relies on the same local ordering of `rowMap` and `repeatedMap`.
The global insert to the coarse basis matrix always inserts at the correct position. 
All tests passed.
=> ShyLU/FROSch: Global insert for coarse basis instead of local insert

cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt.sh, cmake/ctest/drivers/atdm/ride/local-driver.sh
It seems this node times out the build at 12 hours every time this build is runs on the node 'ride7' so just don't run this (expensive) build on that node :-)  (See [ATDV-155](https://sems-atlassian-srn.sandia.gov/browse/ATDV-155)).
I tested this with on 'ride' with:
```
$ cd /home/rabartl/Trilinos.base2/BUILDS/RIDE/CTEST_S/
$ env Trilinos_PACKAGES=Kokkos \
./ctest-s-local-test-driver.sh cuda-9.2-gnu-7.2.0-rdc-release-debug-pt
...
```
The file:
* Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt/smart-jenkins-driver.out
showed:
```
+ bsub -x -Is -q rhel7F -n 16 -J Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt -W 12:00 -R 'hname!=ride7' /ascldap/users/rabartl/Trilinos.base2/BUILDS/RIDE/CTEST
***Forced exclusive execution
Job <855489> is submitted to queue …
```
=> Don't allow Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-rdc-release-debug-pt to run on 'ride7' (ATDV-155)

packages/muelu/src/Graph/MueLu_CoalesceDropFactory_def.hpp, packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_def.hpp, packages/muelu/src/Misc/MueLu_ThresholdAFilterFactory_def.hpp, packages/muelu/src/Rebalancing/MueLu_IsorropiaInterface_def.hpp
This removes Tpetra::DynamicProfile from muelu
Deprecation of DynamicProfile in Tpetra's effect on downstream packages
Since this is a change to tested code, the affected unit tests have been rerun to ensure that they are no longer using the deprecated code path.  Tests conducted on linux 2.6.32.
commented out and can be easily added by removing the comment delimiters.
=> Issue 4283: refactor muelu to not use dynamic profile when declaring crsgraph

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_copyConvert.hpp, packages/tpetra/core/src/Tpetra_DistObject_decl.hpp, packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_FECrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_FEMultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_FEMultiVector_def.hpp, packages/tpetra/core/src/Tpetra_Map_decl.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp, packages/tpetra/core/src/Tpetra_Vector_decl.hpp, packages/tpetra/core/src/Tpetra_Vector_def.hpp, packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorLocalDeepCopy.hpp, packages/tpetra/core/test/Block/BlockCrsMatrix.cpp, packages/tpetra/core/test/Block/BlockMultiVector2.cpp, packages/tpetra/core/test/MultiVector/CMakeLists.txt, packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp, packages/tpetra/core/test/MultiVector/aliased_deep_copy.cpp, packages/tpetra/core/test/Utils/CMakeLists.txt, packages/tpetra/core/test/Utils/copyConvert.cpp
@trilinos/tpetra @trilinos/stokhos @trilinos/anasazi 
This pull request supersedes #4828.
1. Fix #4827.
2. Make more Tpetra classes follow the Rule of Five (C++ Core Guidelines C.21).
3. Clean up FEMultiVector code, syntax, and documentation.
4. Make sure that `Tpetra::deep_copy` between partially aliasing MultiVectors works.
Regarding the last point: the only test in Trilinos that exercises `Tpetra::deep_copy` for partially aliasing `Tpetra::MultiVector` objects is one `Anasazi::TraceMinDavidson` test.  This PR fixes that issue and makes the Anasazi test pass.
* Closes #4827 
* Related to #4196, #3946, #3574
=> Tpetra: Fix #4827; make more Tpetra classes follow Rule of Five; fix Tpetra::deep_copy for aliasing MV arguments

cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-cuda-9.2-gnu-7.2.0-debug.sh, cmake/ctest/drivers/atdm/ride/drivers/Trilinos-atdm-white-ride-gnu-7.2.0-openmp-debug.sh
Seems that 'ride14' triggers several timeouts in the pure 'debug' builds but other nodes don't show any of these timeouts.  This occurred 3 different times and all on 'ride14' (see [ATDV-159](https://sems-atlassian-srn.sandia.gov/browse/ATDV-159)).
Seems that 'ride14' runs the other builds okay so this seems like a safe change to make.
I tested this on 'ride' with:
```
$ cd /home/rabartl/Trilinos.base/BUILDS/RIDE/CTEST_S/
$ env Trilinos_PACKAGES=Kokkos \
./ctest-s-local-test-driver.sh cuda-9.2-gnu-7.2.0-debug gnu-7.2.0-openmp-debug
***
*** ./ctest-s-local-test-driver.sh  cuda-9.2-gnu-7.2.0-debug gnu-7.2.0-openmp-debug
***
Hostname 'ride6' matches known ATDM host 'ride' and system 'ride' …
```
=> Exclude 'ride14' from running pure 'debug' builds (ATDV-159)

commonTools/framework/clean_workspace/clean_workspace.py, commonTools/framework/clean_workspace/unittests/test_clean_workspace.py
For whatever reason, the atdm module has a dependency
on a compiler set already being loaded. Not that this
is needed....
I am attempting to make sure we can rapidly and safely restart all compilation if incremental builds get locked up.  Then I will test and enable incremental PR builds.
=> clean_workspace.py: move from atdm  module for ninja to sems module

packages/tpetra/CMakeLists.txt, packages/tpetra/core/src/Tpetra_Details_DefaultTypes.hpp
#4907 turned into a mess with that merge conflict in terms of what GitHub thought was in the changelog for that PR.  Easier to just kill it and create a new clean PR on a fresh branch since I was only touching 2 files.
I don't plan to run all 18 of my test cases from before, but I'll run some representative cases to make sure the merge with @mhoemmen updates didn't break anything.
=> Tpetra: Fix default Global Ordinals

packages/ifpack2/example/RelaxationWithEquilibration.cpp, packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp, packages/ifpack2/src/Ifpack2_Relaxation_def.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRBILUK.cpp, packages/tpetra/core/example/advanced/Benchmarks/blockCrsMatrixMatVec.cpp, packages/tpetra/core/src/CMakeLists.txt, packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_def.hpp, packages/tpetra/core/test/Block/BlockCrsMatrix.cpp, packages/tpetra/core/test/Block/BlockMultiVector2.cpp
@trilinos/tpetra @trilinos/ifpack2 
This supersedes PR #4862.
- Make `Tpetra::BlockMultiVector` implement the "new" DistObject interface
- Avoid header file includes in BlockCrsMatrix and BlockMultiVector
- Fix some build warnings in Ifpack2 and Tpetra 
* Closes #4861 
* Blocks #4853 
* Follows #4854 
* Related to #3137
=> Tpetra: Fix #4861 (make BlockMultiVector implement "new" DistObject interface)

packages/muelu/CMakeLists.txt, packages/muelu/adapters/epetra/MueLu_CreateEpetraPreconditioner.cpp, packages/muelu/adapters/epetra/MueLu_CreateEpetraPreconditioner.hpp, packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_decl.hpp, packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_def.hpp, packages/muelu/adapters/tpetra/MueLu_CreateTpetraPreconditioner.hpp, packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp, packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp, packages/muelu/cmake/MueLu_config.hpp.in, packages/muelu/example/advanced/levelwrap/LevelWrap.cpp, packages/muelu/example/advanced/multiplesolve/ReuseSequence.cpp, packages/muelu/example/advanced/multiplesolve/StandardReuse.cpp, packages/muelu/research/mmayr/composite_to_regions/src/main.cpp, packages/muelu/research/tawiesn/aria/Driver.cpp, packages/muelu/src/Interface/MueLu_HierarchyManager.hpp, packages/muelu/src/Utils/MueLu_Utilities.cpp, packages/muelu/test/scaling/DriverCore.hpp, packages/muelu/test/scaling/ImportPerformance.cpp, packages/muelu/test/structured/Driver_Structured.cpp, packages/muelu/test/unit_tests/Adapters/AmgxOperatorAdapter.cpp, packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp, packages/muelu/test/unit_tests/Hierarchy.cpp, packages/muelu/test/unit_tests/RAPShiftFactory.cpp, packages/muelu/test/unit_tests/UserData/CreateXpetraPreconditioner.cpp, packages/muelu/test/vardofpernode/VarDofDriver.cpp, packages/trilinoscouplings/examples/fenl/MueLuPreconditioner.hpp, packages/trilinoscouplings/examples/scaling/HybridIntrepidPoisson2D_Pamgen_Tpetra_main.cpp, packages/trilinoscouplings/examples/scaling/HybridIntrepidPoisson3D_Pamgen_Tpetra_main.cpp, packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Tpetra_main.cpp, packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp
Deprecating all CreateT/E/XpetraConstructor except for one accepting an operator and a parameter list
This will give more uniformity and reduce maintenance
* Closes #4868
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #4728
* Composed of 
So far this is a work in progress but I plan on testing it with a local build of MueLu, all tests and examples should pass and compile without warnings.
=> MueLu: deprecate adapters

packages/xpetra/src/Map/Xpetra_EpetraMap.hpp, packages/xpetra/src/Map/Xpetra_TpetraMap.hpp
@trilinos/xpetra @etphipp 
Fix compilation error reported by @etphipp but not caught by PR tests.
Xpetra compilation error when Tpetra_ENABLE_DEPRECATED_CODE=OFF.
See #4888 
```
cmake \
-D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
-D Tpetra_INST_INT_INT:BOOL=ON \
-D Tpetra_INST_INT_LONG_LONG:BOOL=OFF \
-D CMAKE_BUILD_TYPE:STRING="DEBUG" \
-D CMAKE_INSTALL_PREFIX:FILEPATH="/Users/kddevin/code/Trilinos/Obj_node_dep" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
\
-D MPI_BIN_DIR:PATH="/Users/kddevin/InstalledSoftware/openmpi-1.8.3_clang/bin" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D MPI_EXEC_MAX_NUMPROCS:STRING=11 \
\
-D TPL_ENABLE_BinUtils:BOOL=OFF \
-D TPL_ENABLE_Pthread:BOOL=OFF \
\
-D CMAKE_C_FLAGS:STRING="-Wall  -pedantic -Wno-unknown-pragmas -Wno-narrowing -Wno-inline -Wshadow …
```
=> Xpetra:  deprecate node args in map construxtors (small fix for #4888)

packages/kokkos-kernels/unit_test/graph/Test_Graph_graph_color_distance2.hpp
@ndellingwood 
Patching in the [change from Kokkos-Kernels][1] that reduces the problem size for the D2GC problem by 10x.
Relates to #4847 
[1]: https://github.com/kokkos/kokkos-kernels/pull/415
=> KokkosKernels: Patching in test size reduction to D2GC unit test

packages/tpetra/core/inout/Tpetra_Details_CooMatrix.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_DistObject_decl.hpp, packages/tpetra/core/src/Tpetra_DistObject_def.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp, packages/tpetra/core/test/ImportExport/ImportExport_UnitTests.cpp
1. Deprecate "old" `Tpetra::DistObject` interface.
2. If deprecated code is disabled in Tpetra, rename copyAndPermuteNew to copyAndPermute, packAndPrepareNew to packAndPrepare, and unpackAndCombineNew to unpackAndCombine.
* Closes #4853 
I built Tpetra, both with and without deprecated Tpetra code enabled.  There appear to be no downstream subclasses of `Tpetra::DistObject` in Trilinos.
=> Tpetra: Fix #4853 (deprecate "old" DistObject interface)

packages/xpetra/src/Map/Xpetra_TpetraMap.hpp
Another small fix to the deprecation of Node args in methods.
#4943 
#4932 
See #4932
=> Xpetra:  deprecating Node args (one more small fix)

packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.C, packages/seacas/libraries/supes/ext_lib/exparm.c
Fixing off-by-one errors in recent change from using `strncpy` to using `copy_string`
there was a misunderstanding about how IOSS and exodus were using the "maximumNameLength" on an exodus file -- did it include trailing null or not (it doesn't). This is fixed.
Also fixed an off-by-one in the SUPES fortran/c interface routine.
The existing tests should have caught this issue, so will be looking at tests to see what they missed, but wanted to get this committed so clients are working again...
=> Seacas fix off by one

packages/tpetra/core/src/Tpetra_Details_normImpl.cpp
See #4951 
This fix adds scalar = int instantiation for normImpl.
Changes to the default ordinal types caused this class to lack an instantiation.
Need to build with Tpetra_ENABLE_DEPRECATED_CODE=OFF and with default ordinal types.
* Closes #4951
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Tpetra builds with and without Tpetra_ENABLE_DEPRECATED_CODE=OFF
=> Tpetra:  add additional ETI for normImpl when Tpetra_ENABLE_DEPRECATED_CODE=OFF

packages/tempus/src/Tempus_StepperImplicit_decl.hpp
For a segregated linear solve, EMPIRE needs access to the
WrapperModelEvaluator to get to alpha and beta. Adding simple
accessors to it.  All tests pass.
#4970
=> Tempus: Add accessor to WrapperModelEvaluator

packages/amesos2/cmake/Amesos2_config.h.in, packages/tpetra/core/cmake/TpetraCore_config.h.in
@trilinos/amesos2 @trilinos/tpetra
Remove definition of `HAVE_STD_NEW_COUNT_SYNTAX` macro from Amesos2 and Tpetra.
* Closes #3752
=> Amesos2,Tpetra: Fix #3752 (remove HAVE_STD_NEW_COUNT_SYNTAX macro)

packages/tempus/src/Tempus_TimeStepControl_decl.hpp, packages/tempus/src/Tempus_TimeStepControl_impl.hpp, packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_VanDerPol.xml, packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref.xml, packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref2.xml
Added a new parameter to the TimeStepControl, "Output Exactly On
Output Times", that controls if the timestep size will be adjusted
to exactly land on the output times for 'Variable' timestepping
(default=true).  When set to 'false' or for 'Constant' time stepping,
the timestep following the output time will be flagged for output,
and the timestep size will not be adjusted.
Modified Tempus_ExplicitRKTest::EmbeddedVanDerPol test to cover
new feature.  All tests pass.
#4964
=> Tempus: Tempus Output After Passing Output Time

packages/muelu/src/Utils/MueLu_Exceptions.cpp, packages/muelu/src/Utils/MueLu_Monitor.cpp, packages/muelu/src/Utils/MueLu_Monitor.hpp, packages/muelu/src/Utils/MueLu_TimeMonitor.cpp, packages/muelu/src/Utils/MueLu_TimeMonitor.hpp
This commit splits some MueLu classes into header and definition files.
Partially addresses #4984.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/4985)
=> MueLu: a start at reducing MueLu's library size

cmake/tribits/core/installation/TribitsProjectConfigTemplate.cmake.in
My last commit (for #2689) broke the use case where an optional component (TriBITS package) is missing (i.e. was not enabled).  This broke the SPARC use case where it looks for TriKota but TriKota can be missing.
I added tests for that use case and strengthened the existing test (in TriBITS).
I also made the indentation consistent (two spaces).
I added strong unit tests to TriBITS itself for this use case and I tested against SPARC itself.  See details below.
<details>
<summary><b>Detailed testing against SPARC</b> (Click to expand)</summary>
. 
**(4/23/2019)**
Looks like the changes I made in TriBITS commit TriBITSPub/TriBITS@3b02ce8:
```
3b02ce8 "Make usage of <Package>Config.cmake robust when there are broken packages (trilinos/Trilinos#2689)"
Author: Roscoe A. Bartlett …
```
=> Fix case for optional missing component (#2689)

packages/amesos2/CMakeLists.txt, packages/amesos2/example/CMakeLists.txt, packages/amesos2/src/Amesos2_AbstractConcreteMatrixAdapter_def.hpp, packages/amesos2/src/Amesos2_Basker.cpp, packages/amesos2/src/Amesos2_ConcreteMatrixAdapter_decl.hpp, packages/amesos2/src/Amesos2_Details_LinearSolverFactory.cpp, packages/amesos2/src/Amesos2_Details_LinearSolverFactory_def.hpp, packages/amesos2/src/Amesos2_Details_registerLinearSolverFactory.cpp, packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_decl.hpp, packages/amesos2/src/Amesos2_EpetraRowMatrix_AbstractMatrixAdapter_def.hpp, packages/amesos2/src/Amesos2_ExplicitInstantiationHelpers.hpp, packages/amesos2/src/Amesos2_KLU2.cpp, packages/amesos2/src/Amesos2_Lapack.cpp, packages/amesos2/src/Amesos2_MUMPS.cpp, packages/amesos2/src/Amesos2_MatrixTraits.hpp, packages/amesos2/src/Amesos2_PardisoMKL.cpp, packages/amesos2/src/Amesos2_ShyLUBasker.cpp, packages/amesos2/src/Amesos2_Superlu.cpp, packages/amesos2/src/Amesos2_Superlumt.cpp, packages/amesos2/src/Amesos2_Tacho.cpp, packages/amesos2/src/Amesos2_Umfpack.cpp, packages/amesos2/src/Amesos2_Util.cpp, packages/amesos2/src/Amesos2_Util.hpp, packages/amesos2/src/Amesos2_VectorTraits.hpp, packages/amesos2/src/CMakeLists.txt, packages/amesos2/test/adapters/CMakeLists.txt, packages/amesos2/test/adapters/CrsMatrix_Adapter_Consistency_Tests.cpp, packages/amesos2/test/adapters/Epetra_MultiVector_Adapter_UnitTests.cpp, packages/amesos2/test/adapters/Epetra_RowMatrix_Adapter_UnitTests.cpp
- Permit Amesos2_ENABLE_Epetra=ON with Tpetra_INST_INT_INT=OFF.
- Fix Amesos2's build for that case.
This took me about an hour to do and required only trivial index conversions.
@rppawlo needs this for Empire.  Tpetra developers want to deprecate and remove template parameters like GlobalOrdinal.  It's trivial to do index conversions, especially for a package like Amesos2, where the solves will take much longer than any index conversions that need to happen.
* Closes #4992 
* Related to #3234
=> Amesos2: Fix #4992

packages/tpetra/core/test/CrsMatrix/CrsMatrix_NodeConversion.cpp
Added TPETRA_ENABLE_DEPRECATED_CODE guards around test using CrsMatrix::clone
When compiling with clang and TPETRA_ENABLE_DEPRECATED_CODE=OFF, I got compiler errors.
```
/Users//code/Trilinos/packages/tpetra/core/test/CrsMatrix/CrsMatrix_NodeConversion.cpp:138:35: error: 'clone' following the 'template' keyword does not refer to a template
RCP<Mat2> A2 = A1->template clone<N2>(n2,plClone);
~~~~~~~~ ^~~~~
/Users//code/Trilinos/packages/tpetra/core/test/CrsMatrix/CrsMatrix_NodeConversion.cpp:138:40: error: expected unqualified-id
RCP<Mat2> A2 = A1->template clone<N2>(n2,plClone);
^
/Users//code/Trilinos/packages/tpetra/core/test/CrsMatrix/CrsMatrix_NodeConversion.cpp:138:41: error: 'N2' does not refer to a value
RCP<Mat2> A2 = A1->template clone<N2>(n2,plClone);
^ …
```
=> Tpetra: fix clang compilation of test using clone

packages/muelu/example/advanced/levelwrap/LevelWrap.cpp, packages/muelu/example/advanced/multiplesolve/StandardReuse.cpp, packages/muelu/test/interface/CreateOperator.cpp, packages/muelu/test/interface/ParameterListInterpreter.cpp, packages/muelu/test/scaling/ImportPerformance.cpp, packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp, packages/muelu/test/unit_tests/Hierarchy.cpp, packages/muelu/test/unit_tests/RAPShiftFactory.cpp, packages/muelu/test/unit_tests/UserData/CreateXpetraPreconditioner.cpp
We need to make sure that the ParameterListInterpreter does not call kokkos factories when we run with lib==Xpetra::UseEpetra
This will allow our nightly builds to have test passing.
* Closes #5019 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
This has been tested locally and all MueLu tests pass
=> MueLu: fixing call to kokkos refactor method in Xpetra::EpetraMap, closes #5019

packages/trilinoscouplings/examples/fenl/fenl_ensemble.hpp
@trilinos/trilinoscouplings
Fix #5029 (missing header file include in TrilinosCouplings example).
* Closes #5029
=> TrilinosCouplings: Fix #5029

packages/tpetra/core/src/CMakeLists.txt, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_iallreduce.cpp, packages/tpetra/core/src/Tpetra_Details_iallreduce.hpp, packages/tpetra/core/src/Tpetra_Details_makeValidVerboseStream.cpp, packages/tpetra/core/src/Tpetra_Details_makeValidVerboseStream.hpp, packages/tpetra/core/src/Tpetra_Distributor.cpp, packages/tpetra/core/src/Tpetra_ImportExportData_def.hpp
Fix spurious "unused function" build warnings in Tpetra.
The build warnings block Sierra/Trilinos integration.
* Closes #5038
=> Tpetra: Fix #5038 (spurious "unused function" build warnings)

cmake/std/atdm/README.md
Fixes some typos I found when looking at this documentation.
=> Fix some typos related to overriding parallel build and test levels

packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.h
The CGNS library will reorder (sort) zones based on their names,
so if an application defines zones to an output file; closes that
file and then reopens the file, the zones on the file will have
a different ordering or indexing than when they were originally
defined on the file.
This commit causes the IOSS library to update the `db_zone` property
on all StructuredBlocks and ElementBlocks when a CGNS database
is closed and then reopened.  It also verifies that all expected
zones (blocks) exist on the database.
Discovered by SPARC team. Verified that fix works for the issue
that they reported. Developing a test to make this continues to work.
=> SEACAS: IOSS--Update db_zone property after reopening cgns database

packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp
Adding the header: `<Teuchos_XMLParameterListHelpers.hpp>` in the unit-test `CreatePreconditioner.cpp`.
This will allow proper compilation of the unit-test when Tpetra is disabled.
* Closes #5074 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
I tested the fix on the machine that performs this nightly test. The change results in a passing build and test.
=> MueLu: fix bug in unit-test CreatePreconditioner for #5074

packages/panzer/disc-fe/src/evaluators/Panzer_ZeroContributedField.cpp, packages/panzer/disc-fe/src/evaluators/Panzer_ZeroContributedField.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ZeroContributedField_impl.hpp, packages/panzer/disc-fe/test/equation_set/user_app_EquationSet_MeshCoords_impl.hpp
Create an `Evaluator` for the sake of initializing a contributed field to zero.
This will make it such that we can switch more `Evaluator`s over to `CONTRIBUTES`-style evaluation.  This is currently needed by work underway in Drekar, but it will also benefit Charon and perhaps others.
=> Panzer:  Create ZeroContributedField Evaluator

packages/muelu/test/scaling/CMakeLists.txt, packages/muelu/test/scaling/DriverCore.hpp
Allows to use the new pipelined / communication avoiding Krylov solvers in the MueLu driver.
=> MueLu driver: Enable new Tpetra-only Krylov solvers

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Split setup and solve of the composite coarse level solver into two parts. Do the setup during hierarchy construction and just apply the solver during the V-cycle.
I also have removed commented and obsolete code from my previous unsuccessful attempts to create a coarse solver.
The matrix does not change, it's sufficient to create the solver once and then just re-use multiple times. This should save unecessary setup costs.
* Closes #5072 
Build and regionMG tests pass locally.
=> MueLu/regionMG: separate setup and apply of coarse solver

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_decl.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp
kokkoskernels removes experimental namespace. this patch includes appropriate fixes. it also includes the latest ifpack2 improvement. one possible thing that could happen in sparc is that norm interface needs to be modified. @jjwilke (github does not complete your id automatically). would you change sparc for that ? another major change would be separating tpetra memory space from the internal memory space. The internal memory space is either host space or cuda space. Tpetra memoryspace is right now assumed to be uvm.
=> Ifpack2 kokkos promotion preparation

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/regionMG/examples/structured/structured_linear_1dof.xml
The idea is to only look at what happens to point injected from the fine level to the coarse level as these are equivalent to root points. These nodes are easily detected as their corresponding rows in the prolongator contain only one entry.
Also adding a couple of command line options to drive the solver more finely and using command line argument in linear convergence criteria.
I am adding some logic in the function that creates coarse composite maps so that it can handle the case of piece-wise linear prolongator. This adds a good new capability to the code and might also allow to obtain faster convergence at large scale.
I am also hooking the MG parameters and the command line arguments more logically together which will allow us to drive the simulation more easily. …
=> MueLu: linear region mg capability

packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
This adds a target to install MiniEM as well as the needed input files
Closes: #5083
@trilinos/panzer @egphill @cgcgcg @bartlettroscoe 
Make performance tracking easier since most teams install Trilinos and need the apps to be usable from the install directory
Closes: #5083
Tested on White
@bartlettroscoe I could not find a way to get Tribits to install arbitrary files. In this case, we need to install the `xml` input files. They really don't make sense inside `lib/` or `include/`
If there is a better way to do this, please let me know. The motivation is to allow easier performance tracking, since the build tree is usually blown away.
=> Install MiniEM

packages/xpetra/src/Vector/Xpetra_TpetraVector_def.hpp
@trilinos/muelu @trilinos/xpetra @csiefer2 
Misplaced typedef created by the ShortName header...
Broke things: see #5061
Fixes: #5061
Using @kddevin cmake + sems clang atdm modules
```
source ..//cmake/std/atdm/load-env.sh Trilinos-atdm-clang-release-debug
cmake  -GNinja  -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake  -DTrilinos_ENABLE_TESTS=ON -D Trilinos_ENABLE_MueLu=ON -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON -D Tpetra_INST_INT_INT:BOOL=ON -D Tpetra_INST_INT_LONG_LONG:BOOL=OFF -D CMAKE_BUILD_TYPE:STRING="DEBUG" -D TPL_ENABLE_MPI:BOOL=ON -D TPL_ENABLE_BinUtils:BOOL=OFF -D TPL_ENABLE_Pthread:BOOL=OFF -D CMAKE_C_FLAGS:STRING="-Wall  -pedantic -Wno-unknown-pragmas -Wno-narrowing -Wno-inline -Wshadow -Wdeprecated-declarations -Wempty-body …
```
=> Xpetra: Fix xpetra tpetravector eti

packages/nox/src-lapack/NOX_LAPACK_Matrix.H
=> NOX:  Fix possible overflow when computing matrix size in NOX::LAPACK::Matrix

packages/stokhos/src/CMakeLists.txt
Fixes link errors reported in issue #5120.
Just had to reorder two of the tpetra sub-libraries.
=> Stokhos:  Fix tpetra link order.

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
Just before the actual solve, we check, if all necessary factorizations have actually been pre-computed, and print a message to the screen, if not.
The coarse solver is setup during the setup of the region hierarchy, where we also compute its symbolic and numeric factorization. To this end, the factorizations should be ready to use, when it comes to solving the coarse problem inside the V-cycle.
* Follows #5087 
I ran the regionMG tests locally.
=> MueLu: print msg if regionMG coarseSolver is not setup properly

cmake/std/atdm/sems-rhel6/environment.sh
@bartlettroscoe
swap the gcc version on rhel6 intel 17 atdm builds from gcc-4.8.4 to gcc-4.9.3. 
For motivation, see [ATDV-157](https://sems-atlassian-srn.sandia.gov/browse/ATDV-157) (allow EMPIRE to use C++14 features).
[this query](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2019-05-06&filtercount=5&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=sems&field2=site&compare2=63&value2=rhel6&field3=buildname&compare3=63&value3=intel&field4=buildstarttime&compare4=83&value4=2019-05-06&field5=buildstarttime&compare5=84&value5=2019-05-07) shows builds using each version of gcc and there are no test failures in either
=> swap gcc module in ATDM sems-rhel6 intel-17 builds

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
change 1.0 into scalar_type(1.0)
KokkosKernels does not allow simd<float> and double arithmetic operations.  The caller should match the type.
#5148
=> Ifpack2 - fix for #5148

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake, packages/triutils/src/Trilinos_Util_ReadHpc2Epetra.cpp, packages/triutils/src/Trilinos_Util_iohb.cpp
@trilinos/triutils 
Fixed warnings and set Werror for Triutils in the GC 7.2.0 PR build.
Wrapped variable in #ifdef DEBUG Werror sees as unused only by asserts and reversed NULL checks protecting strcpys.
This completes #4511 and is work toward Issue #3178, eventually setting -Werror for all packages.
=> Fix warnings and set Werror for Triutils in GCC 7.2.0 build

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake, packages/pamgen/mesh_spec_lt/pamgen_mesh_specification.C
@trilinos/pamgen @trilinos/framework 
This removes a couple of lines that are unused variables and sets Werror for Pamgen.
This is work towards #3178 and takes care of #5104.
=> Clean up a warning & set Werror for Pamgen

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
Sets Werror for Zoltan in the GC 7.2.0 PR build.
This completes #5106 and is work toward Issue #3178, eventually setting -Werror for all packages.
Allowed by work from #5138.
=> Set Werror for Zoltan in GCC 7.2.0 build

packages/triutils/src/Trilinos_Util_ReadHpc2Epetra.cpp
@trilinos/triutils 
Correcting `ifdef DEBUG` to `NDEBUG` for recent changes in #5153.
=> Fix ifdef DEBUGs to NDEBUG

packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.C
The `update_db_zone_property` function should only be called when the cgns database is closed and then reopened during an execution; not when appending to a database in a restart run.  In the first case, the region pointer is non-null since the region has already been constructed and we need to make sure the zone ordering is the same for the existing region and the newly-reopened cgns database.  In the restart case, we read the zones from the database so the order is correct by definition.
=> SEACAS: ioss/cgns - fix update_db_zone_property 

packages/piro/src/Piro_InvertMassMatrixDecorator_Def.hpp, packages/piro/src/Piro_NOXSolver_Def.hpp, packages/piro/src/Piro_TrapezoidRuleSolver_Def.hpp, packages/piro/test/MockModelEval_A_Tpetra.cpp
@trilinos/nox 
Make Piro::NOXSolver set the final point into the underlying model. If the underlying model overrides `reportFinalPoint`, then other customers of the model can grab the final solution for their own use.
I have two customers of a model ME: the NOXSolver, and another class, call it MyClass. Unfortunately, MyClass does not have access to the NOXSolver, so upon completion of the NOX solve, it can't get the solution from the NOX solver (in principle, it does not even know that the ME used to solve the model was Piro::NOXSolver either). With this modification, Piro::NOXSolver can set the solution in the model, so that MyClass can later access it (assuming that the underlying ME overrides `reportFinalPoint`, and can expose the reported final point, but that's not a concern of …
=> Piro: reporting final point to the wrapped ME at the end of NOX solve

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
When moving the residual from regional to composite, we need a scaling of interface values. This adds the scaling just prior to the convergence check in the outer fix-point iteration.
Maybe we need another scaling on the coarse level before entering the direct solver.
As reported in #5135, the composite residual is twice as large at the interface as expected. Not good. This should address this.
* Part of #5135
Builds locally. Compared composite residual as computed via r=b-Ax (with x=0) and computed via the region framework before entering the V-cycle. Now, they match.
=> MueLu: add inverse scaling of composite residual

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake, packages/isorropia/example/probe_tridiag.cpp
@trilinos/isorropia
Fixed warnings and set Werror for Isorropia in the GC 7.2.0 PR build.
Wrapped variable in #ifdef DEBUG Werror sees as unused only by asserts.
This completes #5105 and is work toward Issue #3178, eventually setting -Werror for all packages.
=> Fix warnings and set Werror for Isorropia in GCC 7.2.0 build

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp
Fixing coordinates in the region driver, the logic around them was never properly put in place...
This fixes a bug which prevents from computing the appropriate prolongator in region format
=> MueLu: region driver coordinates

packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
Fix Clang build error in test.
The build issue hinders ATDM-related `Ifpack2::Chebyshev` optimization work.
* Closes #5225 
Local build of Ifpack2 tests with stock Mac on Clang, with Kokkos deprecated code disabled.
=> Ifpack2: Fix #5225

cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake, packages/amesos/src/CrsMatrixTranspose.cpp, packages/amesos/test/TestOptions/CreateTridi.cpp, packages/amesos/test/TestOptions/NewMatNewMap.cpp, packages/amesos/test/TestOptions/PerformOneSolveAndTest.cpp, packages/amesos/test/TestOptions/TestOptions.cpp, packages/amesos/test/Test_Epetra_CrsMatrix/cxx_main.cpp, packages/amesos/test/Test_Epetra_RowMatrix/cxx_main.cpp
@trilinos/amesos 
Fixed warnings and set Werror for Amesos in the GC 7.2.0 PR build.
Wrapped variables only used by asserts in #ifndef NDEBUG Werror sees as unused.
This completes #5102 and is work toward Issue #3178, eventually setting -Werror for all packages.
This was tested in debug and release Jenkins builds.
=> Fix warnings and set Werror for Amesos in GCC 7.2.0 build

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Slight change to the structured region driver so that region created for the 3D problem have a lexicographic ordering.
The structured regions need lexicographical ordering.
=> MueLu: region driver lexicographic regions in 3D

packages/xpetra/src/Operator/Xpetra_TpetraOperator.hpp
Fix issue #5251.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/5252)
=> Xpetra: guard use of EpetraNode in Xpetra::TpetraOperator specialization.

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/tawiesn/aria/Driver.cpp, packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_def.hpp, packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp, packages/muelu/test/unit_tests/StructuredAggregationFactory.cpp
When one uses linear interpolation, the reference coarse point associated with a given fine point is not the same as the reference coarse point chosen for piece wise constant interpolation.
This should be fixed now.
The graph generated by structured aggregation is wrong when linear interpolation is requested.
This fixes an algorithmic bug that leads to severely degraded performance.
This has been tested on my local machine and algorithmic correctness is verified by checking a small example by hand.
=> MueLu: fix structured aggregation with linear interpolation

.gitignore, cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake, cmake/std/sems/PullRequestGCC4.8.4TestingEnv.sh
This is the changes needed to the PR environment and scripts to get the gcc 4.8.4 build to use static libraries. Note that the build still fails on some missing template instantiations so this cannot merge until those issues are resolved.
Builds for external customers should work withe either shared or static libraries
* Closes #5058 
I used the instructions at https://github.com/trilinos/Trilinos/wiki/Reproducing-PR-Testing-Errors to build this locally.
Additional issues for the template problems will be created directly.
=> Move the gcc 4.8.4 build to use static libraries

packages/xpetra/src/Operator/Xpetra_TpetraOperator.hpp
It looks like the guard in `Xpetra_TpetraOperator.hpp` for the specialization of the class on `EpetraNode` does not check that Epetra has been enabled.
I am observing build failures when Tpetra has no int and no serial instantiation and Epetra is not enabled.
* Closes #5293
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of
A local build was successfully performed with the problematic configuration.
=> Xpetra: fix Xpetra::Tpetra_operator specialization 

packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp, packages/xpetra/test/MultiVector/MultiVector_UnitTests.cpp
Also fixing small warning in MueLu unit-tests for Epetra=OFF build:
Moved a variable declaration around to make sure it is not un-used.
The MultiVector unit-test in Xpetra does not build properly if Epetra is turned OFF
This is a simple fix that adds a preprocessor guard around the Xpetra::EpetraNode check in the unit-test to avoid build error when Epetra is OFF.
* Closes #5300 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
I performed a local build with Epetra=OFF and the unit-test was built correctly.
=> Xpetra: fix MultiVector unit-test for Epetra=OFF configuration, see issue #5300

packages/muelu/test/unit_tests_kokkos/CMakeLists.txt
I am removing the `unit_tests_kokkos.exe --linAlgebra=Epetra` from CMakeLists.txt
These tests are somewhat misleading, it really runs Tpetra but with an EpetraNode.
I do not think that these tests are appropriate...
* Closes #4325
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of
=> MueLu: removing the Epetra path tests for unit-tests-kokkos, see issue #4325

packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockMultiVector_def.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockVector_decl.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockVector_def.hpp, packages/tpetra/core/test/Block/BlockMultiVector.cpp
@trilinos/tpetra @fnrizzi 
1. Add `= default` copy and move constructors and copy and move
assignment operators to both BlockMultiVector and BlockVector.
2. Add two-argument "copy constructors" to both BlockMultiVector and
BlockVector, just like MultiVector and Vector already have, that
give users the option to deep copy or shallow copy.
3. Add tests for the two-argument "copy constructors."  They pass.
SPARC wants this.
* Closes #4627
=> Tpetra: Fix #4627

packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp, packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
Apparently many of the ```ATS=Kokkos::ArithTraits<std::complex<T>>``` functions
can't be used in GPU kernels. Need to use ```Kokkos::ArithTraits<ATS::val_type>```
to get the versions that work on the GPU.
@trilinos/MueLu
* Closes #5151
=> MueLu: Fix #5151.

packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/test/unit_tests/StructuredAggregationFactory.cpp, packages/muelu/test/unit_tests_kokkos/TentativePFactory_kokkos.cpp
Three updates are made to the testing infrastructure of MueLu:
1) Fixing a bug in Structured Aggregation unit_test
2) Using more appropriate Teuchos macros in TentativePFactory_kokkos unit_test
3) reducing the amount of smoothing in StructuredRegion to speed up these tests
This should both lead to more verbose errors when these tests are failing and it should also lead to more passing tests.
* Closes #5310 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Local build and test passed fine
=> MueLu: updating some tests/unit_tests, see issue #5310

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Fixing an arthmetic issue in sendPID
This fixes the behavior of the region operator, i.e. it now behaves the same as a composite operator.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #5135
* Part of 
* Composed of 
Local tests done by @rstumin
=> MueLu: fixing an issue in the structured region driver data

packages/panzer/adapters-stk/example/MixedPoissonExample/CMakeLists.txt
This fixes the multiblock test and could account for some of the random failures mentioned in #5179  but does not explain why the other tests are failing.
=> Panzer: fix multiblock test for order check

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Two parts of the regionMG code are modified:
- `regionsPerGIDWithGhost` is now built using `rowMapPerGrp` instead of `AComp->getColMap()` which makes it independent of the discretization use to build `AComp`
- the construction of `quasiRegionMatrix` has been modified due to some logic error...
This fixes a logic error which could potentially lead to bugs down the road when running more complex problems.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #5135 
* Part of 
* Composed of 
I have done a local build and local test of my modifications.
=> MueLu: fixing some issues in MakeQuasiRegionMatrix logic

cmake/std/atdm/sems-rhel7/environment.sh, cmake/std/atdm/utils/set_build_options.sh
CC: @krcb 
This change switches Intel 18.0.5 with the GCC 7.2.0 backend to match the ABI
used with the SEMS-built Boost lib built with Intel 18.0.5 with the GCC 4.9.3
backend.
This appears to fix the link issues and all of the STK and Panzer tests build
and pass on the machine where there were problems (see #5335).
I tested this on 'ascicgpu15' with:
```
sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug \
--enable-packages=STK,Panzer --local-do-all --make-options=-j10 --ctest-options=j10
```
which returned:
```
1) sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug Results:
-----------------------------------------------------------------------
passed: Trilinos/sems-rhel7-intel-18.0.5-openmp-complex-shared-release-debug: passed=170,notpassed=0 …
```
=> Use -D_GLIBCXX_USE_CXX11_ABI=0 to allow using gcc-7.2.0 with intel-180.5 with boost (#5335)

cmake/std/PullRequestLinuxPython2.cmake, cmake/std/PullRequestLinuxPython3.cmake, cmake/std/sems/PullRequestPython2TestingEnv.sh, cmake/std/sems/PullRequestPython3TestingEnv.sh
Not sure why it still uses /usr/bin even though this one is
first in the path. This allow the tests to run, but they still need to be added to the autotester list.
I ran this by hand on my blade and will run this PR against the Jenkins jobs Trilinos_pullrequest_python_2 and Trilinos_pullrequest_python_3
=> Set python executable for cmake

commonTools/framework/clean_workspace/unittests/test_clean_sentinel.py, commonTools/framework/clean_workspace/unittests/test_clean_workspace.py
These tests would fail if run as trilinos and if the reference date
file was available. This adds a mock to  make the tests think no
reference file is available.
Needed for adding this to the PR testing.
=> Add a few more mocks.

cmake/std/PullRequestLinuxIntelTestingSettings.cmake
This was fixed some time back and I missed re-enabling this test
This just re-enables a test that was fixed in Kokkos and pulled into Trlinos in #3796
resolves #2846
=> Re-enable test KokkosCore_UnitTest_Serial

packages/anasazi/epetra/test/OrthoManager/cxx_gentest.cpp, packages/anasazi/epetra/test/OrthoManager/cxx_mattest.cpp, packages/anasazi/src/AnasaziBlockDavidsonSolMgr.hpp, packages/anasazi/src/AnasaziIRTR.hpp, packages/anasazi/src/AnasaziSIRTR.hpp, packages/belos/src/BelosLSQRIter.hpp, packages/rol/adapters/teuchos/test/function/test_01.cpp, packages/rol/example/dense-hessian/example_01.cpp, packages/stokhos/src/Stokhos_GSReducedPCEBasisBaseImp.hpp, packages/stokhos/src/Stokhos_GramSchmidtBasisImp.hpp, packages/stokhos/src/Stokhos_MonomialProjGramSchmidtPCEBasis2Imp.hpp, packages/stokhos/src/Stokhos_ProductLanczosGramSchmidtPCEBasisImp.hpp, packages/stokhos/test/UnitTest/Stokhos_GramSchmidtUnitTest.cpp, packages/stokhos/test/UnitTest/Stokhos_HermiteBasisUnitTest.cpp, packages/stokhos/test/UnitTest/Stokhos_LanczosUnitTest.cpp, packages/stokhos/test/UnitTest/Stokhos_LegendreBasisUnitTest.cpp, packages/stokhos/test/UnitTest/Stokhos_NormalizedHermiteBasisUnitTest.cpp, packages/stokhos/test/UnitTest/Stokhos_NormalizedLegendreBasisUnitTest.cpp, packages/stokhos/test/UnitTest/Stokhos_StieltjesUnitTest.cpp, packages/tempus/src/Tempus_RKButcherTableau.hpp, packages/teuchos/numerics/example/DenseMatrix/cxx_main.cpp, packages/teuchos/numerics/example/DenseMatrix/cxx_main_sym.cpp, packages/teuchos/numerics/example/LAPACK/cxx_main.cpp, packages/teuchos/numerics/src/Teuchos_SerialBandDenseMatrix.hpp, packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp, packages/teuchos/numerics/src/Teuchos_SerialDenseVector.hpp, packages/teuchos/numerics/src/Teuchos_SerialSymDenseMatrix.hpp
@trilinos/teuchos @rhoope @mseldre 
#5085 includes a suggested strategy for ostream deprecation in serial dense matrices.
This PR implements those suggestions.
See conversations in  #4430  #4330 #5085 
With deprecated code ON:
```
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Teuchos_ENABLE_TESTS:BOOL=ON \
-D Teuchos_ENABLE_EXAMPLES:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Anasazi_ENABLE_TESTS:BOOL=ON \
-D Anasazi_ENABLE_EXAMPLES:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Belos_ENABLE_TESTS:BOOL=ON \
-D Belos_ENABLE_EXAMPLES:BOOL=ON \
-D Trilinos_ENABLE_Tempus:BOOL=ON \
-D Tempus_ENABLE_TESTS:BOOL=ON \
-D Tempus_ENABLE_EXAMPLES:BOOL=ON \
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Stokhos_ENABLE_TESTS:BOOL=ON \
-D Stokhos_ENABLE_EXAMPLES:BOOL=ON \
-D TPL_ENABLE_Boost:BOOL=OFF \
``` …
=> Teuchos:  ostream deprecation following strategy in #5085

packages/tpetra/core/example/advanced/Benchmarks/CMakeLists.txt, packages/tpetra/core/example/advanced/Benchmarks/CrsMatrix_sumIntoLocalValues.cpp
Benchmark to test `Tpetra::CrsMatrix::sumIntoLocalValues` performance before and after first fillComplete.  Enabling TpetraCore examples just builds the executable; you must run it by hand.  It's fine to run on 1 MPI process.
Fuego and Nalu-Sierra reported significant performance degradation after pulling in the latest Trilinos.  Vtune reports all the time going into `sumIntoLocalValues`.
* Related to #5396
=> Tpetra: Add benchmark for CrsMatrix::sumIntoLocalValues

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
@trilinos/tpetra @rrdrake 
Fix build warning in release build.
Sierra builds with warnings as errors.
* Closes #5408
=> Tpetra: Fix #5408 (build warning in CrsGraph)

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Quick fix for #5407.  I just want to see if all the tests pass, so that I can apply this fix quickly to the version of Trilinos in Sierra.  We'll do some more extensive performance testing later.  I also have a restructuring of `sumIntoLocalValues` in progress that should reduce overhead by avoiding `getRowInfo` and the various "get a view" methods, but I want to test that more carefully.
* Closes #5407
=> Tpetra::CrsMatrix: Fix #5407

packages/tpetra/core/src/Tpetra_ConfigDefs.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_RowMatrix_def.hpp, packages/tpetra/core/test/CrsGraph/CrsGraph_Issue601.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_NonlocalAfterResume.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests2.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests3.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp, packages/tpetra/core/test/CrsMatrix/Regression/Albany182.cpp, packages/tpetra/core/test/TpetraUtils_MatrixGenerator.hpp, packages/tpetra/core/test/inout/Bug5800.cpp
#5117 
This PR reduces the number of uses of the enum value DynamicProfile in Tpetra source code.  It will reduce the number of warnings issued by Tpetra during compilation.  
Note that not all deprecation warnings in Tpetra and the rest of the software stack can be eliminated.  With explicit instantiation and deprecated code enabled, deprecated code gets compiled and warnings get issued, even if the code is not called anywhere.  Also, because DynamicProfile deprecation changes both a default behavior and a keyword, it is difficult to remove warnings due to the default behavior change.  Finally, since DynamicProfile is currently the Tpetra default, we need to retain its use in testing; tests exercising DynamicProfile should not be removed just to silence warnings.
ATDM …
=> Tpetra:  changes to reduce the number of deprecated warnings issued 

packages/pliris/test/vector_random/cxx_main.cpp
@trilinos/pliris 
While [checking the progress of Werror being set globally](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5203083&filtercount=1&showfilters=1&field1=buildstamp&compare1=61&value1=20190619-1725-Experimental&filtercombine=and), Pliris was found to have an unused variable, found under subproject Xpetra. There appears to be no other use for ierror and it's not used in assert statements either. So the variable has been removed.
This is work toward Issue #3178, eventually allowing -Werror to be set for all packages.
=> Remove unused variable in Pliris

cmake/std/atdm/ATDMDevEnvSettings.cmake, packages/piro/test/CMakeLists.txt
CC: @rppawlo, @trilinos/zoltan2 
This PR contains commits to disable the building and running of the test exectuables: 
* #5411: Zoltan2_XpetraEpertraMatrix: Commit e1cc0def95c7858a80b794d4777859fc313f2358
* #5412: Piro_ThyraSolver: Commit d1277996e6a8748113c2ab6ab33b9503cbb9edfb
This avoids the build errors in the new build `Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int` where the settings in the build will be used for all the ATDM Trilinos builds.
In fact, since Tpetra is deprecating instantiating multiple global ordinal types, all Trilinos builds will need to go need to do this in the future.
=> Disable one Zoltan2 and one Piro test for Tpetra_INST_INT_INT=OFF for ATDM builds (#5411, #5412)

packages/ifpack2/src/Ifpack2_ILUT_def.hpp, packages/ifpack2/src/Ifpack2_SparseContainer_decl.hpp, packages/ifpack2/src/Ifpack2_SparseContainer_def.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestDenseSolver.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestHelpers.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRILUK.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestTriDiSolver.cpp
Tpetra is deprecating DynamicProfile.  These changes allow Ifpack2 to work with StaticProfile.
The changes update Containers and ILUT.  ILUK is not yet done and is not included in this pull request.
This code discovers the nonzeros needed in ILUT as before, but rather than insert them immediately, it stores them in Teuchos Arrays.  Once all nonzeros are discovered, it creates L and U with StaticProfile and the number of entries per row.  Then it inserts the nonzeros.
These changes also update several tests and test helpers in the Ifpack2 test directory.
#5065 
ATDM Script:  All Ifpack2 tests pass with Tpetra_ENABLE_DEPRECATED_CODE=ON
```
source ../cmake/std/atdm/load-env.sh  gnu-7.2.0-openmp-release-debug
MPI_EXEC=`which mpiexec`
cmake \
-GNinja \
-DMPI_EXEC=${MPI_EXEC} …
```
=> Ifpack2:  revisions to support static profile 

cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt_no-global-int.sh, cmake/std/atdm/cee-rhel6/all_supported_builds.sh, cmake/std/atdm/ctest-s-local-test-driver.sh
This adds the build:
* `Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt_no-global-int`
which shows new build errors for Piro and ROL tests/examples that did not exist in the existing build `Trilinos-atdm-sems-rhel6-gnu-7.2.0-openmp-release-debug-no-global-int`.  This is likely because the 'cee-rhel6' builds enable extra packages and TPLs used by SPARC.
I tested this on 'ceerws1113' running:
```
$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/CEE-RHEL6/CTEST_S/
$ env Trilinos_PACKAGES=Piro,ROL \
./ctest-s-local-test-driver-cee-rhel6.sh \
cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt_no-global-int
***
*** /scratch/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/ctest-s-local-test-driver.sh
***
ATDM_TRILINOS_DIR = '/scratch/rabartl/Trilinos.base/Trilinos'
Load …
```
=> ATDM Add a cee-rhel6 no-global-int build to show additional Piro and ROL build errors

packages/kokkos-kernels/unit_test/graph/Test_Graph_graph_color_distance2.hpp
Reproduce #4940 submitted by @william76, clobbered by the 2.9 promotion.
Reduce test size due to very long test times in debug builds.
=> kokkos-kernels: Reduce d2 graph test size

packages/ifpack2/src/CMakeLists.txt, packages/ifpack2/src/Ifpack2_AdditiveSchwarz_decl.hpp, packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp, packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp, packages/ifpack2/src/Ifpack2_Details_getParamTryingTypes.hpp, packages/ifpack2/src/Ifpack2_ILUT_decl.hpp, packages/ifpack2/src/Ifpack2_ILUT_def.hpp, packages/ifpack2/src/Ifpack2_RILUK_def.hpp
1. Partially fix #4647 by removing almost all use of try-catch for `Teuchos::ParameterList` control flow (an antipattern) from Ifpack2.
2. Remove some unnecessary `Tpetra::MultiVector` allocations from `Ifpack2::AdditiveSchwarz::apply`.  Thanks to Robert Knaus for pointing this out.
3. Remove duplication from `Teuchos::ParameterList` processing in Ifpack2.
* Part of #4647
=> Ifpack2: Partial fix for #4647

packages/tpetra/core/src/Tpetra_Details_allReduceView.hpp
The prior logic had conditions based on whether the view was Cuda UVM or
not.  If UVM, you always end up creating 2 views and performance 2
copies. This unneeded.  Moreover, the logic for whether the input views
were contiguous was backwards (it trigged the code path for non-contig
cases when the views were actually contiguous!).
This fix enables a 2-3x speedup for small payload allreduces.
=> Tpetra: Fix logic used in all Reduce

packages/tpetra/core/src/Tpetra_Details_DefaultTypes.hpp, packages/tpetra/core/src/Tpetra_Details_Transfer_decl.hpp, packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp, packages/tpetra/core/src/Tpetra_DistObject_decl.hpp, packages/tpetra/core/src/Tpetra_DistObject_def.hpp, packages/tpetra/core/src/Tpetra_Experimental_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_ImportExportData_decl.hpp, packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
Currently, Tpetra uses `CudaSpace` as the Kokkos memory space for MPI communication buffers.  We want to try using `CudaHostPinnedSpace` instead, and compare performance of the two options.  (See #4757.)  Trivially changing the space (via the `buffer_memory_space` typedef that appears in a few places) does not build.  This PR fixes the build for that case.
NOTE: This PR does NOT change `buffer_memory_space` to `CudaHostPinnedSpace`.  It just makes sure that Tpetra can build with that change.  If you want to try `buffer_memory_space=CudaSpace`, just drop the last commit.
ATDM performance on GPU clusters.
* Part of #4757
=> Tpetra: Fix build for buffer_memory_space = CudaHostPinnedSpace (but don't change it)

packages/tpetra/core/example/advanced/Benchmarks/CrsMatrix_sumIntoLocalValues.cpp
Improve `Tpetra::CrsMatrix::sumIntoLocalValues` benchmark.  Here are some `MPI_RELEASE` results with GCC 4.9.3 and OpenMP.  Notice that calling `resumeFill` after first `fillComplete` causes `sumIntoLocalValues` to slow down to times comparable to that of `sumIntoLocalValues` before first `fillComplete`.
```
lclNumInds: 10000
maxNumEntPerRow: 28
numToInsert: 27
numTrials: 100
resumeFill: false
================================================================================
TimeMonitor results over 1 processor
Timer Name                                       Global time (num calls)
--------------------------------------------------------------------------------
CrsMatrix constructor                            4.196e-05 (1)
CrsMatrix fillComplete …
```
=> Tpetra: Improve CrsMatrix::sumInto benchmark

packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_decl.hpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp
@trilinos/thyra @trilinos/tpetra 
This deals with some of the performance issues seen on Cuda:
In every inner product call, Thyra created one temporary Tpetra map and one temporary Tpetra vector. These are now being cached.
=> Thyra+Tpetra: Inner products on Cuda

packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/regionMG/examples/structured/structured_1dof-complex.xml, packages/muelu/research/regionMG/examples/structured/structured_linear_1dof.xml, packages/muelu/research/regionMG/examples/structured/structured_unstructured_1dof.xml, packages/muelu/src/Graph/HybridAggregation/MueLu_HybridAggregationFactory_def.hpp, packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp, packages/muelu/src/Graph/StructuredAggregation/uncoupled/MueLu_UncoupledIndexManager_def.hpp, packages/muelu/src/Misc/MueLu_CoordinatesTransferFactory_def.hpp, packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_CoarseMapFactory_def.hpp, packages/muelu/test/unit_tests/Aggregates.cpp, packages/muelu/test/unit_tests/IndexManager.cpp
Primarily added an new xml file to drive the algorithm correctly.
Also cleaned up a bunch of aggregation related things that were not kept up to date with changes in structured aggregation.
Will probably go at it again especially to clean the constructor of UncoupledIndexManager.
Fixing tests that the changes to HybridAggregation beak.
Refreshing the HybridAggregationFactory to bring it up to date with the new StructuredAggregationFactory interface. Also checking that the structured region multigrid can support runs where one rank is considered unstructured.
This will prepare the driver and the hybrid aggregation for some work on interface aggregation that needs to happen for the region multigrid method.
* Closes 
* Blocks 
* Follows 
* Precedes 
* …
=> MueLu: adding logic in region driver for structured/unstructured runs

cmake/std/atdm/spack-rhel/custom_builds.sh, cmake/std/atdm/spack-rhel/environment.sh
Need to merge to this for the new module names for the updates spack modules (see [CDOFA-52](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-52)).
I also added support for a gnu-7.2.0-openmpi-2.1.2 env (just for some testing).
NOTE: This is just stepping stone toward a more general setup where the user can select any Spack-supported compiler and MPI and it will adjust automatically.
I tested this locally as is documented in [CDOFA-52](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-52).
=> Update for new module names for spack-rhel env (CDOFA-52)

packages/teuchos/comm/src/Teuchos_PerformanceMonitorBase.hpp, packages/teuchos/comm/src/Teuchos_TimeMonitor.cpp, packages/teuchos/comm/src/Teuchos_TimeMonitor.hpp
@trilinos/teuchos @DrBooom 
Delete default constructors of `Teuchos::PerformanceMonitorBase` and `Teuchos::TimeMonitor`.  Default construction is unsafe, since it creates an invalid reference that the destructor then uses as if it were valid.
Prevent `~TimeMonitor` from calling instance methods on an invalid timer reference.  See [discussion here](https://github.com/trilinos/Trilinos/pull/5473#discussion_r300179859).
* Closes #5480 
* Related to #5473
=> Teuchos: Fix #5480

cmake/std/atdm/waterman/environment.sh
The build Trilinos-atdm-waterman-cuda-9.2-rdc-release-debug is currently
crashing due to OOM errors with the linker.  This is making it more
conservative in hopes that it will fix the errors.  See [ATDV-182](https://sems-atlassian-srn.sandia.gov/browse/ATDV-182).
I did some local testing just loading the envs and grepping for these vars.
=> Turn down parallel build levels for waterman+cuda+rdc+debug (ATDV-182)

packages/muelu/test/scaling/MatvecKernelDriver.cpp
Fixes the following compilation errors when MKL is enabled:
```
/dev/shm/nolta/cleanenv.NzTEvz/Trilinos/packages/muelu/test/scaling/MatvecKernelDriver.cpp(770): error: identifier "AMKL" is undefined
MV_MKL(AMKL,xdouble,ydouble);
^
/dev/shm/nolta/cleanenv.NzTEvz/Trilinos/packages/muelu/test/scaling/MatvecKernelDriver.cpp(770): error: identifier "xdouble" is undefined
MV_MKL(AMKL,xdouble,ydouble);
^
/dev/shm/nolta/cleanenv.NzTEvz/Trilinos/packages/muelu/test/scaling/MatvecKernelDriver.cpp(770): error: identifier "ydouble" is undefined
MV_MKL(AMKL,xdouble,ydouble);
^
/dev/shm/nolta/cleanenv.NzTEvz/Trilinos/packages/muelu/test/scaling/MatvecKernelDriver.cpp(872): error: identifier "AMKL" is undefined
mkl_sparse_destroy(AMKL);
^
compilation aborted for …
```
=> MueLu: fix undefined vars in MatvecKernelDriver

packages/galeri/src-xpetra/Galeri_StencilProblems.hpp
The current implementation of `ScalarProblem` in Galeri constructs a MultiVector for the Nullspace_ but leaves it uninitialized.
This is a bug that ought to be fixed to avoid bad surprises when MueLu relies on nullspace information for smoothed aggregation.
* Closes #5490 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
-->
Local tests have been performed
=> galeri: fix #5490 by setting the entries in Nullspace_ equal to one

cmake/std/atdm/mutrino/environment.sh
The current settings for srun being used only allow for one srun command to
run a job at a time anyway so might as well avoid bogus timeouts and failures
due to srun timing out before it even starts a job.
The efforts to allow running in parllel on mutrino on the same node have not
worked out as of yet.  See:
https://gitlab.kitware.com/snl/project-1/issues/91
I tested this on 'mutrino' with:
```
[rabartl@mutrino Trilinos (atdm-knl-ctest-j1)]$ . cmake/std/atdm/load-env.sh default
Hostname 'mutrino' matches known ATDM host 'mutrino' and system 'mutrino'
Using mutrino compiler stack INTEL to build DEBUG code with Kokkos node type SERIAL and KOKKOS_ARCH=HSW
[rabartl@mutrino Trilinos (atdm-knl-ctest-j1)]$ set | grep ATDM_CONFIG_CTEST …
```
=> ATDM: Change from ctest -j8 to -j1 on mutrino

packages/ifpack2/test/unit_tests/Ifpack2_UnitTestAdditiveSchwarz.cpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp, packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
@trilinos/tpetra @trilinos/ifpack2 
Very minor changes to remove build warnings.  These warnings were visible when Tpetra's deprecated code is disabled.
https://testing.sandia.gov/cdash/index.php?project=Trilinos&subproject=Tpetra&filtercount=2&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=rocketman&field2=buildname&compare2=63&value2=DEPRECATED
=> Tpetra and Ifpack2:  Minor changes to remove build warnings 

cmake/std/atdm/ATDMDevEnvSettings.cmake
This disables the building of two test exectuables, one in Piro (#5446) and one in ROL (#5447) that don't build when Tpetra global int instantiations are disabled (see [ATDV-174](https://sems-atlassian-srn.sandia.gov/browse/ATDV-174)).  Merging this will allow us to set `Tpetra_INST_INT_INT=OFF` in all of the ATDM Trilinos builds and in all of the ATDM APPs.
I tested this using the (still in-development but useful) 'spack-rhel' env on my COE RHEL6 machine 'crf450' with:
```
./checkin-test-atdm-spack-rhel6.sh \
spack-rhel-gnu-7.2.0-openmpi-1.10.1-opt-dbg-no-global-int \
--enable-packages=Piro,ROL --local-do-all
```
Before the disables in the PR, this produced two build errors:
```
FAILED: packages/rol/adapters/tpetra/test/vector/CMakeFiles/ROL_adapters_tpetra_test_vector_SimulatedVectorTpet …
```
=> Disable on Piro and ROL test that does not build with no global int instantiation (#5446, #5447, ATDV-714)

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/regionMG/examples/structured/amg_1dof.xml, packages/muelu/research/regionMG/examples/structured/structured_1dof_3level.xml
- Allow to replace the direct solver on the coarsest regionML level by 1 sweep through an AMG hierarchy.
- Add a test.
This is a step towards "true HHG", where we use regionMG to coarsen partially structured meshes until they appear to be fully unstructured. Then, we use AMG for further coarsening.
* Part of #5503
A test with 3 levels of regionMG and then 3 levels of AMG on top has been added. Thorough testing of actual results has still to be done.
=> MueLu: use AMG as coarse solver for regionMG

packages/belos/tpetra/example/WrapTpetraSolver/wrapTpetraSolver.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp, packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp, packages/ifpack2/src/Ifpack2_Chebyshev_def.hpp, packages/ifpack2/src/Ifpack2_Container.hpp, packages/ifpack2/src/Ifpack2_Details_Amesos2Wrapper_def.hpp, packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp, packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp, packages/ifpack2/src/Ifpack2_Hiptmair_def.hpp, packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp, packages/ifpack2/src/Ifpack2_Relaxation_def.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestLocalSparseTriangularSolver.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraEuclideanScalarProd_def.hpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraMultiVector_def.hpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraVector_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/test/HashTable/computeOffsetsFromCounts.cpp
@trilinos/belos @trilinos/ifpack2 @trilinos/thyra @trilinos/tpetra @kddevin 
Remove use of `KOKKOS_ENABLE_DEPRECATED_CODE` macro.
In all cases I saw, both code paths (with or without the macro defined) now build fine.
=> Belos,Ifpack2,Thyra,Tpetra: Remove use of KOKKOS_ENABLE_DEPRECATED_CODE macro

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/main.cpp, packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
This header will provide a unique interface to all smoothers as well as some infrastructure to perform setup and apply phase of all smoothers.
The Jacobi smoother is now moved in the new infrastructure and the run time goes down as the inverse diagonal is cached during setup instead of being recomputed at run time.
Adding the "smootherType" option to the structured region driver to choose one of the available preconditioners.
Adding some infrastructure in region multigrid to implement multiple smoothers.
Also defining a setup and an apply phase for region smoothers.
This will allow to perform more comparison between region MG and classical MG.
It also improves performance through better setup/apply separation.
* Closes #5492
* Blocks 
* Follows 
* …
=> MueLu: region smoothers

packages/ifpack2/src/Ifpack2_IlukGraph.hpp
Needed to run with `Tpetra::StaticProfile` which will become default
after `Tpetra::DynamicProfile` is removed.
Closes: #5510
@trilinos/ifpack2 @trilinos/tpetra 
The heuristic is probably very bad.  Saad's "Iterative Methods for Sparse Linear Systems" says
> the amount of fill-in and computational work for obtaining the ILU(p) factorization is not predictable for p > 0. 
This statement is in relation to Algorithm 10.5 of the same text.  I'm not sure that is true of this algorithm.  I figured the heuristic would be faster/easier than counting.
All tests now pass
=> Ifpack2: Heuristic to set upper size of graphs in RILUK.

packages/muelu/src/Utils/MueLu_Utilities_decl.hpp, packages/muelu/src/Utils/MueLu_Utilities_def.hpp, packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp, packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp, packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp, packages/tpetra/core/src/Tpetra_Util.hpp, packages/tpetra/core/test/RowMatrixTransposer/CMakeLists.txt, packages/tpetra/core/test/RowMatrixTransposer/main.cpp, packages/tpetra/core/test/RowMatrixTransposer/sorted.cpp
@trilinos/tpetra @trilinos/muelu 
1. `Tpetra::RowMatrixTransposer::createTranspose*` methods now sort rows (by local column indices) of the result by default.  This fixes #4607.
2. As discussed [here](https://github.com/trilinos/Trilinos/issues/4607#issuecomment-472869688), the sparse matrix-matrix multiply routines do their own sorting.  Thus, we have changed those routines to tell RowMatrixTransposer not to sort rows.
3. Optimized local transpose: Fewer parallel kernel launches; don't initialize allocations unless needed.
4. Removed an unused code path in local transpose, where the input matrix is a RowMatrix but not a CrsMatrix.  In that case, createTransposeLocal now first converts the input to CrsMatrix.
* Closes #4607
=> Tpetra: Fix #4607 (sort rows in explicit transpose by default)

packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp
@trilinos/tpetra @rrdrake @vbrunini 
Fix build warnings in `Tpetra::RowMatrixTransposer` in a non-ETI GCC 7.2.0 OpenMPI 1.10.2 build.
Sierra currently uses this build to test Trilinos master candidates.
* Closes #5546
=> Tpetra: Fix #5546

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Interface.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_def.hpp
The idea is to allow the structured region driver to generate more complex test cases.
It can now set any rank as unstructured instead of only the last one.
It can also set multiple ranks as unstructured.
Found a bug in TentativePFactory for the calculation of coarse coordinates.
This was minor and an easy fix has been applied.
This enhancement and bug fix are part of the effort to have HHG algorithms within MueLu, here the idea is to push the algorithm further in terms of the complexity of the cases handled.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #5509
* Part of 
* Composed of 
Local tests have been performed with new enhancement and all tests still pass.
Structured/Unstructured aggregates on level 0:
Structured/Unstructured aggregates …
=> MueLu: structured region driver can now set any rank as unstructured

packages/belos/tpetra/src/solvers/Belos_Tpetra_Gmres.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPipeline.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov_parameters.hpp
This pull-request makes a couple of updates to Gmres solvers in belos/tpetra
- check explicit residual norm before restart
- an option to compute Ritz values without restart (for generating Newton basis)
- increase the default step size of s-step Gmres to five
=> Fixes for Belos "Native" Tpetra Gmres

packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.C
The CGNS library is addressing parallel scalability issues and has started using
a compact storage method available in HDF5. This can speed up parallel execution
by around two orders of magnitude.  
Prior to this fix, the SEACAS/IOSS/CGNS implementation had its own workaround which
sped up parallel execution by two orders of magnitude at low to medium processor counts
and an order of magnitude at "larger" processor counts.  This workaround has been removed since the CGNS compact storage usage is a much better and maintainable solution.  This was comitted to CGNS in https://github.com/CGNS/CGNS/commit/6199af200f0692d8da8ab5f7f0825d4100d54cee
There is also another issue in that CGNS had mistakenly applied another optimization which provided a little more speedup, but made the resulting …
=> CGNS: Move CGNS patch detection compile-time error to runtime warning

packages/galeri/example-fem/CMakeLists.txt, packages/galeri/example/CMakeLists.txt
I am adding appropriate checks in CMakeLists.txt to ensure that builds of galeri do not fail if Epetra is OFF but examples of galeri are ON.
Galeri fails to compile its examples if Epetra is OFF
This is part of on-going work to remove deprecated code in Tpetra
* Closes #5593 
* Blocks 
* Follows 
* Precedes 
* Related to #1033
* Part of #5602
* Composed of 
I performed a local build with Galeri and its examples ON while Epetra is OFF
=> Galeri: fix for issue #5593, protecting Epetra only examples in CMakeLists.txt

packages/muelu/test/unit_tests/PgPFactory.cpp, packages/muelu/test/unit_tests/Zoltan.cpp
The matrix in unit-test Zoltan_Build is now properly estimating the number of non-zeros per row which allows to be built without crashing with the new static allocation of the Tpetra::CrsGraph
This work will make the test pass after Tpetra removes its deprecated code.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #5614 
* Composed of 
I performed a local build and the test is now passing correctly.
=> MueLu: fixing the Zoltan unit-test for static allocation of Tpetra::CrsGraph see issue #5614

packages/tpetra/core/test/MatrixMatrix/AddProfilingTest.cpp
Fix AddProfilingTest failure on MPI+CUDA.
Changed the way the input matrices are constructed.
AddProfilingUnitTests.cpp was failing because the row/range map had 1000 global elements,
but every process was trying to global insert into all 1000 rows. Now each process
only adds entries to owned rows as intended.
This was failing on waterman in the nightly tests.
This test now passes on my machine with CUDA 9.2 (same as waterman) and CUDA-aware OpenMPI 4.0.1.
=> Tpetra: #5525 fix (AddProfilingUnitTest on MPI+CUDA)

packages/muelu/test/scaling/circ_nsp_dependency.xml, packages/muelu/test/scaling/iso_poisson.xml, packages/muelu/test/scaling/isorropia.xml
Mainly tweaking a bit the xml file to have coordinate flow through MueLu.
No idea why this pops up now?
This test showed up as broken during the testing of Trilinos with `Tpetra_Deprecated_Code=OFF`
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #5602 
* Part of #5614 
* Composed of 
Local build and tests have been performed and the offending test now passes
=> MueLu: fixing isorropia test before removal of Tpetra deprecated code issue #5614

cmake/std/atdm/spack-rhel/environment.sh
This PR matches the changes in the atdm-spack repo branches 'improvements 20190716-cleanup' and addresses a number of issues with the spack-rhel builds including:
* No more compiler name in modules for tools like 'cmake' and 'ninja-fortran'.
* Works for shared and static lib builds of Trilinos, EMPIRE, and SPARC
I did a bunch of testing with Trilinos, EMPIRE and SPARC as documented in [CDOFA-52](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-52) but I will do one more round of testing before merging these branches.
=> ATDM spack-rhel improvements starting 2019-07-16 (CDOFA-52)

packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp, packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp, packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp, packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_decl.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_decl.hpp, packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_def.hpp, packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_decl.hpp, packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_def.hpp, packages/xpetra/sup/Matrix/Xpetra_Matrix.hpp
Fixed test failures:
...IPOUHarmonic_DIM2_DPN2_ORD0_TPETRA_MPI_4 and
...IPOUHarmonic_DIM2_DPN2_ORD1_TPETRA_MPI_4 in ShyLu_DDFROSch
by changing Xpetra matrix construction to use StaticProfile.
At FROSch_CoarseOperator_def.hpp:235, changed the creation of Xpetra::Matrix to use StaticProfile and exact entry counts. This is effectively a deep copy from tmpCoarseMatrix to CoarseMatrix_, except with 1.0 inserted on the diagonal in rows which are empty in tmpCoarseMatrix.
As part of this, implemented
Xpetra::Matrix::getNumEntriesInGlobalRow(GO) because without it,
counting entries in each row of tmpCoarseMatrix requires an additional call to
getGlobalRowView() for every row. Like Xpetra::Matrix::getNumEntriesInLocalRow(LO),
this function is a trivial one-line …
=> ShyLU: fixed test failures with deprecated off (#5617)

packages/ifpack2/src/Ifpack2_BandedContainer_decl.hpp
Fixing an error in `Ifpack2_BandedContainer_Serial.cpp`:
```
packages/ifpack2/src/Ifpack2_BandedContainer_decl.hpp:131:32: error: dependent using declaration re
solved to type without 'typename'
using Container<MatrixType>::mv_type;
^
```
This affected me on clang compilers, but judging by the other `using Container<MatrixType>:: ...` lines nearby were using `typename`:
https://github.com/trilinos/Trilinos/blob/1bfa7b16c0eb5de6980ce552e7511caf34973a48/packages/ifpack2/src/Ifpack2_BandedContainer_decl.hpp#L128-L138
it seemed reasonable to make lines 131 and 132 consistent.  This removed my compiler error on my environment.
=> Ifpack2: Fixing an error that affects clang

packages/zoltan2/src/models/Zoltan2_HyperGraphModel.hpp, packages/zoltan2/src/models/Zoltan2_ModelHelpers.hpp, packages/zoltan2/test/helpers/UserInputForTests.hpp, packages/zoltan2/test/partition/TaskMappingProblemTest.cpp, packages/zoltan2/test/partition/TaskMappingTest.cpp, packages/zoltan2/test/unit/util/Metric.cpp, packages/zoltan2/test/unit/util/componentMetrics.cpp
#5615 #5609 
Tpetra is deprecating use of DynamicProfile construction for graphs and matrices.
This PR changes several uses of DynamicProfile to StaticProfile, by providing the number of entries for rows of the matrix.  
I do not use StaticProfile in the function call, as the default profile type will become StaticProfile.
Tested in linux with Tpetra_ENABLE_DEPRECATED_CODE=OFF and Tpetra_INST_INT_INT=ON.
=> zoltan2:  allow deprecation of dynamicProfile #5602

packages/teko/src/Tpetra/Teko_BlockingTpetra.cpp, packages/teko/tests/src/tGraphLaplacian_tpetra.cpp
#5602 
Changes to enable only static profile construction of Tpetra CrsMatrices.
Enables builds with Tpetra_ENABLE_DEPRECATED_CODE=OFF to succeed.
Changed one test to provide a maximum number of entries per row.  (Note that this test is rather odd in that it inserts into one matrix row twice, while not inserting at all into another matrix row.  But I digress.)
Changed the subblock constructor to count the number of nonzeros per row, then create the matrix, and then insert the nonzeros.
DynamicProfile construction of Tpetra CrsGraph and CrsMAtrix is deprecated and will disappear soon.
Tested on linux with
Tpetra_ENABLE_DEPRECATED_CODE=OFF
Xpetra_ENABLE_DEPRECATED_CODE=OFF
Tpetra_INST_INT_INT=ON
=> teko:  fixes to support staticProfile matrix construction in Tpetra #5602

packages/ifpack2/src/Ifpack2_Details_Amesos2Wrapper_def.hpp, packages/ifpack2/src/Ifpack2_RILUK_def.hpp
Fixed Ifpack2_AdditiveSchwarz_MPI_4 test when
Tpetra_ENABLE_DEPRECATED_CODE=OFF. Just changed the way
matrices were deep copied in Amesos2Wrapper and RILUK, by using
insertLocalValues() instead of doImport.
Ifpack2 Amesos2Wrapper and RILUK used Tpetra::CrsMatrix::doImport() to deep copy from the Ifpack2::ReorderFilter and Ifpack2::LocalFilter matrix wrappers, and these classes don't support getGraph(). getGraph() is required by doImport() for StaticProfile matrices, so this commit replaces the use of doImport with a manual copy.
Ifpack2 was built with tests enabled and Tpetra/Xpetra deprecated code off, and all tests passed.
=> Ifpack2: Fix AdditiveSchwarz test w/o deprecated

packages/amesos2/example/GappedMtxGIDs-1proc.cpp, packages/amesos2/test/solvers/KLU2_UnitTests.cpp
Changes the unit tests in Amesos2 to work with GO=int and GO=<default>
To further the removal of deprecated code
* Part of #5602 
Built unit tests against GO = int and GO = <default>, checked unit tests run
- [ na ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ na ] I have added tests to cover my changes.
=> Fix Amesos2 unit tests KLU2 and GappedMtxGIDs

packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_OverlappingOperator_def.hpp, packages/shylu/shylu_dd/frosch/test/Import_Tpetra/main.cpp, packages/shylu/shylu_dd/frosch/test/InterfacePartitionOfUnity/main.cpp, packages/shylu/shylu_dd/frosch/test/InterfaceSets/main.cpp, packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/main.cpp, packages/xpetra/src/Headers/Xpetra_UseDefaultTypes.hpp, packages/xpetra/src/Map/Xpetra_Map.hpp
Fixed link errors in several ShyLU_DDFROSch tests, where the global ordinal was
unknowingly hardcoded as int. Made Xpetra pick a reasonable default GlobalOrdinal.
Building with Tpetra GO=long long (but not GO=int) caused the failure, because Xpetra structrues were not instantiated with *_int_int_node. The reason why GO was hardcoded to int in ShyLU is because ShyLU used the Xpetra "default types" to define Scalar, LO, GO and NO. In Xpetra_DefaultTypes.hpp, GO was hardcoded to int, regardless of what was enabled in CMake. So this commit adds logic in Xpetra to choose a reasonable default GlobalOrdinal based on what is enabled: if Tpetra is enabled, the default GO of Tpetra is chosen. Then if Epetra 64-bit GO is enabled, long long is used. Otherwise, int …
=> ShyLU: Fixed test link errors #5618

packages/trilinoscouplings/examples/fenl/fenl_impl.hpp
For issue #5599
This doesn't fix similar usage in other TrilinosCouplings examples.
@trilinos/trilinoscouplings
=> TrilinosCouplings:  Fix hard-coded use of LO/GO=int in FENL.

packages/tpetra/core/src/Tpetra_RowMatrix_decl.hpp
Make sure that nothing in the class declaration of `Tpetra::RowMatrix` depends on any header file not included.
* Closes #5658
=> Tpetra::RowMatrix: Fix #5658

packages/phalanx/test/Field/MDField_Runtime.cpp
Name mangling issue. Teuchos demangle may need a specialization for
mutrino.
Addresses #5685
=> Phalanx: fix failing test on mutrino

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/main.cpp, packages/muelu/research/mmayr/hhg/Xpetra_RegionMatrix_decl.hpp, packages/muelu/research/q2q1/MueLu_Q2Q1PFactory.hpp, packages/muelu/research/q2q1/MueLu_Q2Q1uPFactory.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/test/structured/Driver_Structured.cpp
Adding a whole lot of monitors to find were time can be shaved off?
Also fixing a couple of issues in the experimental side of MueLu after default types in Xpetra have been removed.
Finally switching some of the data from `std::vector` to `Teuchos::Array`.
The main goal is to add time monitor for performance diagnostic, it already allowed to identify a target for refactor.
Using `Teuchos::Array` allows us to use parameter list more easily since std::vector cannot be stored natively on parameter list.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #5656
* Part of 
* Composed of 
Local build and test is successful, the monitors are reporting time appropriately
=> MueLu: adding time monitors in region MG

packages/panzer/adapters-stk/cmake/Dependencies.cmake, packages/panzer/adapters-stk/src/Panzer_STK_ModelEvaluatorFactory_impl.hpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.hpp, packages/panzer/adapters-stk/test/stk_interface_test/CMakeLists.txt, packages/panzer/adapters-stk/test/stk_interface_test/pamgen_test.gen, packages/panzer/adapters-stk/test/stk_interface_test/tExodusReaderFactory.cpp, packages/panzer/adapters-stk/test/stk_interface_test/tPamgenMeshFactory.cpp
* deprecated explicit pamgen reader (combined with exodus reader now)
* added unit tests for pamgen meshes
* verification of sideset data in output meshes
note: I have not removed the old pamgen exodus reader until the apps switch their code over to the new factory. This way we can prevent CI issues in app/trilinos integration.
=> Panzer: add sideset data to pamgen generated exodus output

packages/tempus/src/Tempus_TimeStepControl_decl.hpp
Bug fix for a null vector error in TimeStepControl_decl.hpp
This bug created issues when trying to setup a Tempus integrator from defaults.
=> Tempus: Fix for the null vector bug in TimeStepControl_decl.hpp

cmake/ctest/drivers/atdm/README.md, cmake/std/atdm/README.md
Noticed this while doing #4933.
=> Update documentation for change of 'chama' to 'tlcc2' (ATDV-173)

packages/zoltan2/test/driver/CMakeLists.txt, packages/zoltan2/test/driver/driverinputs/CMakeLists.txt, packages/zoltan2/test/driver/driverinputs/multijaggedVwgt2Test.xml
Sanity test for MJ with multiple weights
Zoltan2 accepts multiple weights per ID to be partitioned.
MJ accesses and migrates all weights, but uses only the first weight for partitioning.
This test exercises MJ with multiple weights
=> Zoltan2 test exercising multiple weights for MJ partitioner

packages/zoltan2/test/driver/driverinputs/sacer4320/CMakeLists.txt, packages/zoltan2/test/helpers/UserInputForTests.hpp
Changed behavior of test_driver program when file of vertices' processor assignments is provided for initial distribution.
Old behavior:  if comm->getSize() < number of processors in assignment
files, vtx assigned (by the file) to processors that are not in comm
were ignored (so a smaller problem was partitioned).
New behavior:  vtx assigned (by the file) to processors that are not in comm
are now randomly reassigned to processors in comm (so that all vtx are
partitioned).  A warning is issued that the file's max processor is
greater than the comm's max processor.
It was not intuitive or obvious that some vertices would be ignored when running a test with a smaller communicator than was used to generate an assignment file.  
Assignment files are usually provided for …
=> Zoltan2:  Changed behavior of driver when file of initial processor assignments is provided

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp, packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
The previous workaround #5715 for #5179 was not completely effective.  This workaround is better.
This workaround forces a deep_copy of counts before the parallel_scan in the computeOffsetsFromCounts function.
See #define Tpetra_Workaround5179 in Tpetra_Details_computeOffsets.hpp
This workaround reverses the workaround in #5715, which now is not needed.
Some questions remain, as we saw unusual behavior when debugging this issue.  For example, this workaround removes compilation of an if-test and the if-branch from the function.  In experiments that only forced the if-test to be false but allowed the if-branch to compile, we saw the same failures as in the original code.  It is not clear why removing the if-test and if-branch allows correct execution.  We will continue to …
=> tpetra:  a more effective workaround for #5179

packages/xpetra/sup/Cloner/Xpetra_Cloner.hpp
Closes: #5749
Part of: #5602 
Rather than compile out the call to `Tpetra::Map::clone`, perhaps a deep copy should be made instead?
=> Xpetra: remove Tpetra deprecated code

packages/panzer/core/cmake/Dependencies.cmake
Per the discussion in #5592, Panzer requires Epetra.
Closes: #5592
Part of: #5602
=> Panzer: require Epetra to build

packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson2DExample.cpp, packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson2DExample.hpp, packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson3DExample.cpp, packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson3DExample.hpp, packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.cpp, packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.hpp
=> Trilinos Couplings: Fix for #5754

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp
- rename setup routine of relaxation based smoothers, such that it reflects the fact to be used for both Jacobi and Gauss-Seidel
- move definition of list of valid region smoother types to a central routine
- use descriptive names
- remove code redundancy, avoid danger of copy-and-paste mistakes
* Follows #5701, in particular [this comment](https://github.com/trilinos/Trilinos/pull/5701#discussion_r313705754)
I ran all `MueLu_Structured_Region` tests locally.
=> MueLu: unify setup of region smoothers

cmake/ctest/drivers/atdm/smart-jenkins-driver.sh
In the previous refactoring to create get_system_info.sh for #4933, the
variable ATDM_CONFIG_SCRIPT_DIR was newly required to be set but was not set
from a fresh env.
I had tested this smart-jenkins-driver.sh locally but the env var
ATDM_CONFIG_SCRIPT_DIR must have been set in my local env which allowed it to
pass.
This should fix all of the ATDM Trilinos builds. (There have been no builds submitting to CDash since Saturday).
=> Fix smart-jenkins-driver.sh (#4933)

packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_def.hpp
In the default SPGEMM algorithm (SPGEMM_KK) on CUDA,
the symbolic phase produces an incorrect row map for some inputs
(see KokkosKernels issue 402). This bug has been tracked to
entry compression. So as a temporary workaround, compression has been
disabled on CUDA.
This bug affects EMPIRE.
=> KokkosKernels: CUDA SPGEMM symbolic workaround

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp, packages/muelu/doc/UsersGuide/masterList.xml, packages/muelu/doc/UsersGuide/paramlist_hidden.tex, packages/muelu/src/Interface/MueLu_HierarchyManager.hpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp, packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp, packages/muelu/src/MueCentral/MueLu_MasterList.cpp, packages/xpetra/src/Export/Xpetra_EpetraExport.hpp, packages/xpetra/src/Export/Xpetra_Export.hpp, packages/xpetra/src/Export/Xpetra_TpetraExport_decl.hpp, packages/xpetra/src/Export/Xpetra_TpetraExport_def.hpp, packages/xpetra/src/Import/Xpetra_EpetraImport.hpp, packages/xpetra/src/Import/Xpetra_Import.hpp, packages/xpetra/src/Import/Xpetra_ImportFactory.hpp, packages/xpetra/src/Import/Xpetra_TpetraImport_decl.hpp, packages/xpetra/src/Import/Xpetra_TpetraImport_def.hpp
@trilinos/muelu @trilinos/xpetra 
This PR adds the option to set a new sublist "matvec params" in the xml interface. The content of the sublist will be applied to the underlying Tpetra::Distributors for the solve phase. In particular, this allows to choose different communication options apart from the default Irecv-Send pattern.
=> Muelu: Allow to change distributor options

packages/tpetra/core/src/CMakeLists.txt, packages/tpetra/core/src/Tpetra_CrsMatrixMultiplyOp.hpp, packages/tpetra/core/src/Tpetra_CrsMatrixMultiplyOp_fwd.hpp
@trilinos/tpetra @vbrunini 
Add forward declaration header file for `Tpetra::CrsMatrixMultiplyOp`.
Sierra (specifically Chaparral) wants this in order to isolate the implementation and thereby keep build times low.
* Closes #5762
=> Tpetra: Fix #5762

packages/rol/adapters/teuchos/src/sol/ROL_SingletonTeuchosBatchManager.hpp, packages/rol/adapters/teuchos/src/sol/ROL_StdTeuchosBatchManager.hpp, packages/rol/adapters/teuchos/src/sol/ROL_TeuchosBatchManager.hpp, packages/rol/adapters/teuchos/test/sol/test_05.hpp, packages/rol/adapters/tpetra/src/sol/ROL_TpetraTeuchosBatchManager.hpp, packages/rol/example/PDE-OPT/0ld/adv-diff-react/data.hpp, packages/rol/example/PDE-OPT/0ld/poisson/data.hpp, packages/rol/example/PDE-OPT/0ld/stefan-boltzmann/data.hpp, packages/rol/example/PDE-OPT/0ld/stoch-adv-diff/data.hpp, packages/rol/example/PDE-OPT/TOOLS/assembler.hpp, packages/rol/example/PDE-OPT/TOOLS/assembler_def.hpp, packages/rol/example/PDE-OPT/TOOLS/batchmanager.hpp, packages/rol/example/PDE-OPT/dynamic/navier-stokes/initial_condition.hpp, packages/rol/example/PDE-OPT/dynamic/thermal-fluids/initial_condition.hpp, packages/rol/example/PDE-OPT/fractional/poisson/fractional_operator.hpp, packages/rol/example/PDE-OPT/obstacle/example_01.cpp, packages/rol/example/PDE-OPT/poisson-boltzmann/doping.hpp, packages/rol/example/burgers-control/example_06.hpp, packages/rol/example/burgers-control/example_07.hpp, packages/rol/example/burgers-control/example_08.hpp
=> ROL: fix for Tpetra_DEPRECATED_CODE=OFF

packages/teuchos/parser/src/CMakeLists.txt
This PR is to fix an issue with Teuchos that came up developing an installation test for Trilinos.
Teuchos fails to compile tests against an installed Trilinos because `Teuchos_string.hpp` isn't installed via `make install` when `CMAKE_INSTALL_PREFIX` is set. 
This update adds the file to the CMakeLists.txt file so that `make install` will transfer the file to the installation directory.
FYI @jwillenbring
=> Teuchos: Add Teuchos_string.hpp to CMakeLists.txt

packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_decl.hpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp, packages/thyra/core/src/interfaces/operator_vector/fundamental/Thyra_VectorSpaceBase_decl.hpp
@trilinos/thyra @trilinos/belos 
Caching the multivector used by `Thyra::createMembersView` did not always work correctly (https://github.com/SNLComputation/Albany/issues/503), probably because multiple MVs from`createMembersView` were active. I added a new member function to Thyra's vector space that does caching when the Tpetra backend is used, and use that function in the Belos Thyra adapter.
=> Thyra+Belos: Fix issue

packages/xpetra/src/BlockedMap/Xpetra_BlockedMap.hpp
A bug from the ETI of `Xpetra_MapFactory` popped up doing installation testing for the Framework team.  
It looks like the fix is to have Xpetra_BlockedMap  include `Xpetra_MapFactory_decl.hpp` rather than `Xpetra_MapFactory.hpp` because of some funny `#include` chaining caused an error that looked like:
```
[ 97%] Building CXX object packages/xpetra/src/CMakeFiles/xpetra.dir/MultiVector/Xpetra_EpetraMultiVectorFactory.cpp.o
In file included from /ascldap/users/wcmclen/dev-scratch/trilinos-dev/build/fmwk-bkw-compat-build/packages/xpetra/src/Xpetra_MapFactory.hpp:2:0,
from /ascldap/users/wcmclen/dev-scratch/trilinos-dev/source/Trilinos/packages/xpetra/src/BlockedMap/Xpetra_BlockedMap.hpp:55,
from …
```
=> Xpetra: Clean up BlockedMap includes

packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp
@searhein 
Add `#include <Tpetra_Distributor.hpp>` to `packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp`
The `Tpetra::Distributor` class is used in this file, so its declaration should be included. This fixes a compilation error on my machine. 
Build and `ctest` pass locally.
=> ShyLU/FROSch: include missing Tpetra header

packages/stk/stk_unit_tests/stk_simd/CMakeLists.txt
During the recent PR testing snafu a problem
was introduced in a stk_simd test. This just
turns that off until we can get it resolved.
@trilinos/stk
=> Reduce stk_simd tests until the team can resolve intel issue

packages/amesos2/src/Amesos2_KLU2_def.hpp
Remove a superfluous MPI_Bcast. The communicated error code is always zero, as far as I can tell.
=> Amesos2 Klu2: Remove superfluous MPI_Bcast

packages/rol/adapters/tpetra/src/mpi/ROL_PinTVectorCommunication_Tpetra.hpp
@trilinos/rol , @trilinos/tpetra
With deprecation of tpetra and kokkos for downstream packages, ROL does not compile because it uses dimension. This PR changes it with extent.
We are testing Tpetra downstream deprecation. The code does not compile.
=> ROL - change dimension to extent for kokkos deprecation

packages/xpetra/src/Headers/Xpetra_ConfigDefs.hpp, packages/xpetra/src/Map/Xpetra_Map.hpp, packages/xpetra/src/Map/Xpetra_MapFactory_decl.hpp, packages/xpetra/src/Map/Xpetra_MapFactory_def.hpp
@mayrmt @jhux2 
Addresses Issue #5813 
Xpetra headers weren't picking up the `TPETRA_ENABLE_DEPRECATED_CODE` preprocessor macro because `Tpetra_ConfigDefs.hpp` was not getting pulled in.
This commit adds a couple of cosmetic fixes but primarily addresses Issue #5813 by adding `Tpetra_ConfigDefs.hpp` into the `Xpetra_ConfigDefs.hpp` file so that Xpetra headers get the Tpetra information they need if they're building Tpetra.
FYI @trilinos/tpetra
=> Xpetra: Fix Issue #5813

packages/muelu/research/regionMG/examples/structured/compare_residual_history.py
`numpy` is not available on all systems. Hence, using it can lead to test failures. Since `numpy` is not used anyway, let's not import it.
The testing script should work on all systems. (Since it requires python, systems without python are excluded anyways.)
* Follows #5760
Tests pass on a system, that has not have `numpy` installed.
These tests are for experimental code, so they are only executed, if experimental code is enabled in MueLu. That's not the case for the autotester (and many other systems).
=> MueLu: don't use numpy in region MG regression testing python script

packages/epetra/src/CMakeLists.txt
The epetra use of OpenMP is broken for gcc 9 (see #5390 ). If we want to build trilinos with OpenMP support enabled (for kokkos and tpetra), we currently need to disable epetra. The work around to allow for epetra without openmp enabled would be to set:
```
-D EPETRA_HAVE_OMP:BOOL=OFF \
-D Epetra_HAVE_OMP:BOOL=OFF \
```
However these variables are ignored because the variables are set as normal instead of cached variables in epetra's CMakeLists.txt file. This PR changes the variables to cached so that users can override the default, allowing us to build trilinos with openmp support enabled and with epetra enabled.
NOTE: I think only the first variable listed above is used, but the second was kept around for backwards compatibility according to a comment in code.
=> Epetra: allow users to disable OpenMP support in Epetra.

packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
Fix a sign issue in the Maxwell preconditioner in MiniEM. Before we took two outer GMRES iterations per solve, now we're back to one.
=> MiniEM: fix sign issue in FullMaxwellPreconditionerFactory

packages/tempus/src/Tempus_StepperDIRK_decl.hpp, packages/tempus/src/Tempus_StepperDIRK_impl.hpp, packages/tempus/test/DIRK/Tempus_DIRKTest.cpp, packages/tempus/test/DIRK/Tempus_DIRK_SinCos.xml, packages/tempus/test/DIRK/Tempus_DIRK_SteadyQuadratic.xml, packages/tempus/test/DIRK/Tempus_DIRK_VanDerPol.xml
Tagging drekar team for visibility: @sconde @johnshadid @rppawlo 
The changes in this pull request are motivated by solver difficulties observed in Drekar. In certain situations, the nonlinear solve for a stage may become severely divergent. The resulting diverged solution is nevertheless returned and stored in the internal stage vector of the StepperDIRK class, and becomes the initial guess for the next nonlinear solve. When the timestep is cut and the step is attempted again, this diverged solution persists. Because this diverged solution is a very poor initial guess, subsequent solves will fail regardless of how far the timestep is reduced. The purpose of this pull request is to implement a mechanism to ensure that a reasonable initial guess is used for nonlinear …
=> Adding option to tempus DIRK stepper for resetting initial guess.

packages/amesos2/test/solvers/KLU2_UnitTests.cpp
Correct the value of max nonzeros per row from 1 to 2
in the KLU2 unit test "NumericFactorizationNullThrows".
Just fixed max nnz/row for static profile. This test adds diagonal entries, and then adds entries in opposite corners, so max nnz is 2.
Makes the test pass when Tpetra deprecated is off.
Built and run with Tpetra_ENABLE_DEPRECATED_CODE=OFF
=> Amesos2: Fix NNZ/row in KLU2 unit test

packages/kokkos/core/src/impl/Kokkos_Core.cpp
by picking a device at random we should be able to up the ctest -j level on machines like waterman..
@crtrott thoughts?
=> This patch makes it so ctest will be slightly more efficient on GPUs

packages/trilinoscouplings/examples/fenl/main_pce.cpp
Fixes the build error reported here:
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=5530425
I have no idea why this build is the only one that has ever come across
this error, nor why changing the include order fixes it.  The compiler
complains about a missing overload of Kokkos::create_mirror() with a
Sacado::UQ::PCE view, and the file that calls it is below where the file
that defines it is included.  Who knows.
=> TrilinosCouplings/FENL:  Change order of includes to fix overload error

packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_decl.hpp, packages/muelu/test/unit_tests_kokkos/CMakeLists.txt, packages/muelu/test/unit_tests_kokkos/LWGraph_kokkos.cpp
I am simply adding two host / device function that give access to the row pointers and entries from the `Kokkos::StaticCrsGraph`.
Accessing the underlying local data avoid having to use methods that transfer data to host which is not always the right thing to do.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #5838
* Composed of 
I did  a local build and things seem OK so far.
=> MueLu: extending the interface of LWGraph to give direct access to rowPtrs and entries

packages/muelu/src/Graph/Containers/MueLu_Aggregates_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase1Algorithm_kokkos_def.hpp, packages/muelu/test/scaling/CMakeLists.txt, packages/muelu/test/scaling/scaling_distance2_agg.xml, packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp
Adding a set and get methods to Aggregates_kokkos in order to store the coloring of the LWGraph used for aggregates creation.
This will allow to pass the colors to all phases of aggregation without reworking interfaces too much.
Using the new methods in LWGraph_kokkos avoids copying on host the data needed by
the coloring algorithm. This saves 2 communication: 1 DtoH and 1 HtoD.
Extra time monitors are added in AggregationPhase1 to account for coloring and
aggregation separately.
Adding a test that exercises the Distance2 algorithmic path in test/scaling
This work is part of a refactor to have MueLu SA-AMG setup performed on device
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #5838
* Composed of 
I did a local build with OpenMP, all …
=> MueLu: distance2 coloring, Aggregates_kokkos and Phase 1 aggregation

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp, packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp, packages/tpetra/core/src/Tpetra_createDeepCopy_CrsMatrix_def.hpp
Please don't merge this quite just yet, per request by @kddevin .
Per request by @kddevin , here are the changes I made to FixedHashTable and computeOffsetsFromCounts, that prevent the crash observed in the MueLu driver, per discussion in #5179.   The fix makes the code cleaner and simpler.
* Related to #5179 
On waterman, with the MueLu driver, and with Tpetra's tests.
=> Tpetra: More permanent fixes for FixedHashTable issue in #5179

packages/rol/example/PDE-OPT/TOOLS/assembler_def.hpp, packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
Clean up failed ROL tests with deprecation OFF. I also clean up one Tpetra function for computing offsets. When we use constant count, we don't need scan.
=> ROL - fix failed examples

packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_decl.hpp, packages/muelu/src/Graph/MueLu_AggregationAlgorithmBase_kokkos.hpp, packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase1Algorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase1Algorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_IsolatedNodeAggregationAlgorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_IsolatedNodeAggregationAlgorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_OnePtAggregationAlgorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_OnePtAggregationAlgorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_PreserveDirichletAggregationAlgorithm_kokkos_decl.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_PreserveDirichletAggregationAlgorithm_kokkos_def.hpp, packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp
The goal is to remove instances of `std::vector<>` from the interface in favor
of `Kokkos::View<>` even if the underlying implementation still uses a `std::vector<>`
This will facilitate pushing new algorithms through the stack.
This work is part of a refactor of the MueLu setup see issue #5838
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #5838
* Composed of 
I used a local build with OpenMP enabled, all tests are passing.
=> MueLu: modifying BuildAggregates signature in AggregationAlgorithmBase_kokkos

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp, packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp, packages/muelu/test/maxwell/Maxwell.xml, packages/muelu/test/maxwell/Maxwell_complex.xml, packages/panzer/mini-em/example/BlockPrec/maxwell.xml, packages/panzer/mini-em/example/BlockPrec/maxwell2D.xml
Automatically apply nullspace fix to avoid singular matrix in RefMaxwell when no boundary conditions were detected.
=> MueLu RefMaxwell: Apply nullspace fix when no BCs are detected

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
Allow a custom Kokkos memory space to be set as the Tpetra
comm_buffer_memory_space in Tpetra_Details_DefaultTypes.hpp (e.g. CudaHostPinnedSpace instead of
CudaSpace). The only thing preventing this was the use of
Kokkos::DualView::resize() in BlockCrsMatrix::packAndPrepare();
currently resize() doesn't allow using a different device memory space
than the device's default (this may change in the future).
@trilinos/tpetra @trilinos/kokkos 
in Tpetra::BlockCrsMatrix::packAndPrepare(), replace Kokkos::DualView::resize() with just constructing a new DualView and doing copy assignment.
This change expands the set of memory spaces that may be used as the Tpetra-wide space for communication buffers in Tpetra_Details_DefaultTypes.hpp. Previously, BlockCrsMatrix::packAndPrepare() called …
=> Tpetra: allow custom memory space (fix #5864)

packages/tempus/src/Tempus_StepperBDF2_impl.hpp, packages/tempus/src/Tempus_StepperBackwardEuler_impl.hpp, packages/tempus/src/Tempus_StepperDIRK_impl.hpp, packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp, packages/tempus/src/Tempus_StepperExplicit_decl.hpp, packages/tempus/src/Tempus_StepperExplicit_impl.hpp, packages/tempus/src/Tempus_StepperForwardEuler_impl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp, packages/tempus/src/Tempus_StepperImplicit_decl.hpp, packages/tempus/src/Tempus_StepperImplicit_impl.hpp, packages/tempus/src/Tempus_StepperLeapfrog_impl.hpp, packages/tempus/src/Tempus_StepperNewmarkExplicitAForm_impl.hpp, packages/tempus/src/Tempus_StepperTrapezoidal_impl.hpp
* Added new parameters for explicit evaluation, xDot = f(x,t,p).
Parameters for explicit steppers, p, are currently dt and stage number.
* Cleaned up implicit parameters (e.g., included stage number in
argument list).
* StepperTrapezoidal was missing the new solveImplicitODE().
Passes all tests on my Mac.
=> Tempus: Missing Args in explicit Steppers InArgs.

packages/belos/tpetra/src/Belos_Details_Tpetra_registerSolverFactory.cpp, packages/belos/tpetra/src/CMakeLists.txt, packages/belos/tpetra/src/solvers/Belos_Tpetra_BiCGStab.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_BlockCG.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_BlockGmres.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_FixedPoint.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GCRODR.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPoly.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_LSQR.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_Minres.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_PCPG.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_PseudoBlockCG.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_PseudoBlockGmres.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_PseudoBlockTFQMR.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_RCG.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_TFQMR.cpp, packages/belos/tpetra/test/LinearSolverFactory/SolverFactory.cpp
Break out Belos::SolverFactory Tpetra solver registration into separate files, to improve build time for Sierra building Trilinos.
* Closes #5904
=> Belos: Fix #5904

packages/tpetra/core/src/Tpetra_DirectoryImpl_decl.hpp, packages/tpetra/core/src/Tpetra_DirectoryImpl_def.hpp, packages/tpetra/core/src/Tpetra_Map_decl.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp, packages/tpetra/core/src/Tpetra_TieBreak.hpp
1. Add verbose output to Directory and createOneToOne.
2. Make `Tpetra::Map::lgMapHost_` a HostSpace View, not a HostMirror View.
Help with #5179 debugging.
* Related to #5179
=> Tpetra: Add verbose output to Directory & createOneToOne

packages/kokkos/core/src/impl/Kokkos_Core.cpp
Realized that get time returns time in seconds, so mpirun -np 4 assigns to the same device...  Moving to getpid()
=> Moved from gettime to getpid for parallel jobs

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Print the number of fixed point iterations to screen using the line
```
Number of iterations performed for this solve: <numberOfIterations>
```
This is the same line as for the structured MG driver. Having the same screen output simplifies scripted post processing of log files.
I verified screen output manually and also with some postprocessing scripts applied to the screen output log file.
=> MueLu: print total number of fixed-point iterations in region MG driver

packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/regionMG/examples/structured/structured_linear_3dof.xml, packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp, packages/muelu/test/structured/structured_2dof.xml
Properly constructing maps and importers for coordinates that take into account the number of degrees of freedom per node in the linear system being solved.
I think that to prevent this type of unexpected behavior I might remove the
coupled path in structured aggregation...
This fixes a couple of bugs related to the handling of coordinates in region MG and in GeometricInterpolationPFactory.
* Closes issue #5921
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
A local build and test has been performed and no failures has been observed
=> MueLu: fixing the construction of region coordinates in region driver

packages/muelu/research/q2q1/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
remove Q2Q1 experimental test and a debug statement in region structured driver
The Q2Q1 experimental test has been failing due to a Thyra error for a while and as no one seems to need this test it is removed from the experimental category. The executable will still be built in case someone want to fix it at some point.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Local build and test has been performed, all tests passed.
=> MueLu: small maintenance commit

packages/muelu/CMakeLists.txt, packages/muelu/cmake/MueLu_config.hpp.in, packages/muelu/src/Headers/MueLu_Details_DefaultTypes.hpp
-Fixes what was supposed to be included in #5697
-setting global CMake variables about which
integer type should be the default GO in MueLu
-this enables/disables #defines in MueLu_config.h
-#defines from MueLu_config.h are used to set the
default GO typedef in MueLu_Details_DefaultTypes.hpp
The changes that fixed the default GO selection were:
- fix misspelling of the MueLu ETI option in cmake: changed ``${${PACKAGE_NAME}_INST_DOUBLE_INT_LONG_LONG}`` to ``${${PACKAGE_NAME}_INST_DOUBLE_INT_LONGLONGINT}``
- include MueLu_config.hpp into MueLu_Details_DefaultTypes.hpp; without this, the preprocessor definitions were never seen by it
- use nested cmake "IF(...)" to set the boolean variables instead of trying to use boolean expressions as the right-hand side of GLOBAL_SET(). …
=> MueLu: Fix CMake/preprocessor logic for default GO (#5932)

packages/muelu/src/Transfers/Energy-Minimization/Solvers/MueLu_SteepestDescentSolver_def.hpp, packages/muelu/src/Transfers/Petrov-Galerkin-SA/MueLu_PgPFactory_def.hpp, packages/muelu/test/scaling/MMKernelDriver.cpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
MueLu: fix PgP, emin test failures when Tpetra deprecated is off.
Tpetra: fix MatrixMatrix::Multiply timer scope issue.
Also in MueLu, replaced one instance of deprecated Kokkos fence:
exec_space::fence() ==> exec_space().fence().
TpetraExt::MatrixMatrix::Multiply has two main code paths:
a fast one that does fillComplete() and one that doesn't. The
fast code path (mult_A_B_newmatrix()) for computing C=A*B also
allocates C to exactly the right size, avoiding the guesswork of
constructing C with enough entries per row.
However, Xpetra's wrapper for Multiply doesn't request
fillComplete unless optimizeStorage is also requested. So this commit
passes "optimizeStorage = true" to Xpetra::Multiply in the
PG and EMin transfers. This now uses the faster code …
=> Tpetra, MueLu: deprecated code fixes

cmake/std/PullRequestLinuxDriverMerge.py
@prwolfe I was hitting problems trying to test out my sandboxed Jenkins job for installation testing and the error in the console log looks something like this:
```
18:13:54 The SHA (0a17f129cb98cbd8241fa0d351a97df0aa6998d2
18:13:54 ) for the last commit on branch fmwk-installation-testing
18:13:54   in repo https://github.com/william76/Trilinos is different than the expected SHA,
18:13:54   which is: 0a17f129cb98cbd8241fa0d351a97df0aa6998d2.
18:13:54 Build step 'Execute shell' marked build as failure
```
The print message in `PullRequestLinuxDriverMerge.py` that generates this is the following:
```python
if actual_source_SHA != sourceSHA:
print('The SHA ({source_sha}) for the last commit on branch {source_branch}'.format(source_sha=actual_source_SHA, …
```
=> Framwork: Strip off whitespace from arguments

packages/kokkos-kernels/src/batched/KokkosBatched_Vector.hpp
For ARM vectorizations, we may want to use 256bit vector length (4 doubles) even if the hardware supports 128bit (2 doubles). Using 128bit length, it does not seem to hide latency well. This is a very rough estimation with experiments. We do this so that we can set up a baseline performance of the Ifpack2 block tridiagonal solver (SPARC). I will submit a separate PR for KK.
FYI: As we do not have have a PR test with ARM, the PR test would (should) not complain in this PR.
=> Ifpack2 vector length adjustment for ARM

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Remove screen output from debugging coordinates in region driver.
We don't need to print all region coordinates, especially not for larger problems.
* Follows #5924
Built and ran locally.
=> MueLu: remove regionMG coordinate debug output

packages/muelu/src/Interface/MueLu_HierarchyManager.hpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/src/MueCentral/MueLu_FactoryManager_decl.hpp, packages/muelu/test/interface/ParameterListInterpreter.cpp, packages/muelu/test/unit_tests_kokkos/CMakeLists.txt, packages/muelu/test/unit_tests_kokkos/UseKokkos_kokkos.cpp
The `useKokkos_` attribute of FactoryManager is not set appropriately set when using an easy xml.
For instance it is set to true in `muelu/example/basic/Simple.cpp` when `simple.xml` clearly sets:
```
<Parameter        name="use kokkos refactor"                  type="bool"     value="false"/>
```
This is a bug and as such should be fixed but it also blocks PR #5956 
* Closes #5961
* Blocks #5956 and #5838
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
A new unit-test is added to MueLu to make sure this parameter is consistently set between the parameter list interpreter and the factory manager.
=> MueLu: fixing bug with kokkos refactor in FactoryManager, see issue #5961

packages/muelu/research/CMakeLists.txt, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/regionMG/examples/structured/compare_residual_history.py
Change command line options for regionMG coarse solver to allow for "direct", "amg", or "smoother".
The purely boolean option `--use-direct-solver` is now replaced by `--coarseSolverType={amg,direct,smoother}`.
This is triggered by [this discussion in PR 5968](https://github.com/trilinos/Trilinos/pull/5968#discussion_r327364780).
* Related to discussion in #5968
Build and tests pass locally.
=> MueLu: clean-up region MG coarse solver options

packages/zoltan2/test/partition/CMakeLists.txt, packages/zoltan2/test/partition/mj_backwardcompat.cpp
This test exercises backward-compatibility in the vector adapter for the MultiJagged partitioner.
It includes two small adapters that do not use Kokkos; one adapter stores the coordinates contiguously by dimension; the other stores them in strided format.
It computes partitions with both formats and compares the results; the results should be identical.
It also operates with and without weights.
In #5332, Multijagged partitioning is being rewritten to operate with Kokkos.  Some interface changes were needed.  We do not want to break backward compatibility for existing applications that use the vector adapter.
#5332 
Run on linux server.
=> Zoltan2:  new backward compatibility test for Cuda MJ #5332

packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/regionMG/examples/structured/structured_linear_3dof.xml
- set default coarse level solver in region MG driver to be a direct solver
- add serial and parallel 3D elasticity tests for region MG
- change coarsening rate to 3 in `structured_linear_3dof.xml`
We fixed some issues with multipler DOFs per node in the region MG framework. Let's protect the current state by adding elasticity tests.
=> MueLu: add elasticity tests to region MG

cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_gnu-4.9.3_openmpi-1.10.2_serial_shared_opt.sh, cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_intel-17.0.1_intelmpi-5.1.2_serial_static_opt.sh, cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_intel-19.0.3_intelmpi-2018.4_serial_static_opt.sh, cmake/std/atdm/cee-rhel6/all_supported_builds.sh, cmake/std/atdm/cee-rhel6/custom_builds.sh, cmake/std/atdm/cee-rhel6/environment.sh
* Added new intel-19 build that SPARC is now using (replacing their intel-17 build)
* Removed intel-17 build SPARC was using
* Removed obsolete gnu-4.9.3 (which has not been run in months)
FYI: This will be the first and only Intel 19 build of Trilinos submitting to the CDash site.
I ran a full build of all the ATDM Trilinos packages from 'ceerws1113' with:
```
$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/CEE-RHEL6/CTEST_S/
$ ./ctest-s-local-test-driver-cee-rhel6.sh \
cee-rhel6_intel-19.0.3_intelmpi-2018.4_serial_static_opt
```
and submitted to CDash shown at:
* [Trilinos-atdm-cee-rhel6_intel-19.0.3_intelmpi-2018.4_serial_static_opt-exp](https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=5692657) (passed=2098)
I then ran the testing of Kokkos and Teuchos for all of …
=> ATDM: Add cee-rhel6 intel-19 build

packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp, packages/zoltan2/test/driver/CMakeLists.txt, packages/zoltan2/test/driver/driverinputs/CMakeLists.txt, packages/zoltan2/test/driver/driverinputs/multiJaggedPremigrateTest.xml
Zoltan2 did not have a test explicitly exercising MJ's premigration.  This PR adds such a test:  a small problem with small target number of parts that forces premigration.
This PR also corrects a Teuchos parameter getValue call to use the same argument and result value.  The old code was correct but subject to future errors if data types were changed.
All code should be exercised.  Other work in premigration code requires that we have a test.
built and run on cee-lan linux workstation; all tests (including the new one) pass
=> Zoltan2:  fix MJ parameter setting and add premigration test

doc/build_docs.pl
Sort input file list 
so that variables_f.js builds in a reproducible way
in spite of indeterministic filesystem readdir order.
See https://reproducible-builds.org/ for why this is good.
This PR was done while working on reproducible builds for openSUSE.
=> Sort input file list

packages/xpetra/CMakeLists.txt, packages/xpetra/src/Vector/Xpetra_TpetraVector_def.hpp
When Tpetra deprecated code is removed, its default GO will be long
long. Epetra is enabled by default but with 32-bit GO. Previously if
Epetra32 was enabled and Tpetra GO=int was off, Xpetra would error out
at configure time.
This means that without deprecated code, a Trilinos build with
MueLu/Xpetra enabled and every option default would fail to configure.
This change catches the situation above. If Epetra is explicitly
enabled by the user, it errors out like before. But if Epetra is
only implicitly enabled and GO=long long, Xpetra will just warn
and disable its Epetra support, so configuration will succeed
and Xpetra+downstream will just use Tpetra and GO=long long.
This will fix configure when deprecated code is disabled or removed, as shown in this
nightly on …
=> Xpetra: cmake logic to solve GlobalOrdinal conflict

packages/rol/example/PDE-OPT/0ld/TOOLS/PDE_FEM.hpp, packages/rol/example/PDE-OPT/0ld/TOOLS/dofmanager.hpp, packages/rol/example/PDE-OPT/0ld/TOOLS/elasticity.hpp, packages/rol/example/PDE-OPT/0ld/TOOLS/meshmanager.hpp, packages/rol/example/PDE-OPT/0ld/adv-diff-react/data.hpp, packages/rol/example/PDE-OPT/0ld/elasticity/data.hpp, packages/rol/example/PDE-OPT/0ld/elasticity/dataSIMP.hpp, packages/rol/example/PDE-OPT/0ld/elasticitySIMP_topologyOptimization/data.hpp, packages/rol/example/PDE-OPT/0ld/elasticitySIMP_topologyOptimization/filter.hpp, packages/rol/example/PDE-OPT/0ld/poisson/data.hpp, packages/rol/example/PDE-OPT/0ld/stefan-boltzmann/data.hpp, packages/rol/example/PDE-OPT/0ld/stoch-adv-diff/data.hpp, packages/rol/example/tempus/example_parabolic_modeleval_forward-adjoint.cpp
@trilinos/rol 
This fixes all the PDE-OPT 0ld examples (compile and runtime errors) with Tpetra deprecated code is off. The vast majority of the changes are just replacing any use of "int" with the default Tpetra global ordinal, when the value describes a global quantity (global number of cells, global dofs, etc.). Every ``FieldContainer<int>`` has been replaced by ``FieldContainer<GO>``. GO has been added as a private typedef in each "data" class of the various PDEs.
N/A; this is just part of the preparations for deprecated code removal by Tpetra.
This change fixes the following examples/tests (when Tpetra deprecated code is OFF):
- ROL_example_PDE-OPT_0ld_elasticity_example_01_MPI_1
- ROL_example_PDE-OPT_0ld_elasticity_example_02_MPI_1
- ROL_example_PDE-OPT_0ld_poisson_example_01_MPI_4 …
=> ROL: fixing PDE-Opt examples with deprecated code off

packages/sacado/src/CMakeLists.txt, packages/sacado/src/mpl/Sacado_mpl_has_equal_to.hpp, packages/sacado/src/mpl/Sacado_mpl_void.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp, packages/sacado/test/UnitTests/CMakeLists.txt, packages/sacado/test/UnitTests/ConditionalReturnTypeTest.cpp
Because of the way the conditional overloads (==, !=, ...) are written
using ConditionalReturnType, this trait can be instantiated with invalid
arguments when the compiler is going through its overload resolution
process for completely unrelated types.  This was observed in SPARC when
using the new Fad design.  This adds some SFINAE metaprogramming to
prevent those instantiations.  It also adds an essentially compile-time
test to make sure the overloads are dropped correctly using SFINAE.
=> Sacado:  Add some SFINAE to restrict instantiation of ConditionalReturnType

packages/teuchos/core/src/Teuchos_RCP.hpp, packages/teuchos/core/src/Teuchos_RCPDecl.hpp, packages/teuchos/core/src/Teuchos_RCPNode.hpp, packages/teuchos/core/test/MemoryManagement/RCPNodeHandle_UnitTests.cpp, packages/teuchos/core/test/MemoryManagement/RCP_UnitTests.cpp
This is a WIP PR to develop C++11 move functions for Teuchos Memory Management classes (see #6031).
This branch can be merged at any time if needed, even if all of the move operations have not been added yet since they are finished for Teuchos::RCP.
=> Add move functions to Teuchos::RCP (#6031)

cmake/std/atdm/README.md, cmake/std/atdm/cee-rhel6/environment.sh, cmake/std/atdm/ctest-s-local-test-driver.sh
This fixes the build error reported in #6040.  This also updates some documentation.
On 'ceerws1113' I ran:
```
$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/CEE-RHEL6/CTEST_S/
$ env \
ATDM_TRILINOS_INSTALL_PREFIX=install \
CTEST_DO_INSTALL=ON \
./ctest-s-local-test-driver-cee-rhel6.sh \
all
```
which posted to:
* https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-cee-rhel6
(see the more recent builds that passed.)
=> Fix build error for ATDM 'cee-rhel6' builds starting 2019-10-04

cmake/ctest/drivers/rocketman/mpi_release_tpetra_deprecated_code_off_downstream_enabled.cmake
Set testing variable Trilinos_CTEST_DO_ALL_AT_ONCE to true.  I've
confirmed that this speeds up the builds (~3x), at the price of
not disabling any upstream package that might fail.  But since there
are no build failures at the time of this commit, this should be ok.
This is a change to the nightly testing infrastructure, not a change to Tpetra itself.
No testing is required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6062)
=> Testing: Tpetra: speed up nightly testing

packages/phalanx/test/Kokkos/tKokkosAllocationTracker.cpp
Bug fix.
https://testing.sandia.gov/cdash/testDetails.php?test=91158793&build=5750566
=> Phalanx - wrong number of kokkos allocation arguments.

cmake/std/atdm/ride/environment.sh, cmake/std/atdm/waterman/environment.sh
As described in #6052, it is possible that running with ctest -j8 could cause
out-of-memory errors on the GPU and when using UVM the errors are delayed and
hard to diagnose.  Therefore, to be safe, we need to drop to ctest -j4.  That
will cause all of the 4-proc MPI tests to run by themselves and will allow
four 1-proc MPI tests to run.  Hopefully this will eliminate any possibility
of running out of mememory on the GPU.
Hopefully Kitware can help us create a system where we can more effectively
use the GPUs as part of #2422.
I did not test this.  But I think we can see they are correct by inspection.
=> Reduce ctest -j8 to -j4 for all CUDA builds (#6052)

packages/kokkos-kernels/src/batched/KokkosBatched_Trsm_Serial_Impl.hpp, packages/kokkos-kernels/src/batched/KokkosBatched_Trsm_Team_Impl.hpp
@csiefer2 uses trsm with transpose in muelu. The code does not produce a right solution (a bug). This PR fixed the problem.
In this PR, @csiefer2 confirms that the code works and his problem is resolved. Later, I will add more tests in the kokkoskernels repo.
=> KokkosKernels - trsm transpose does not solve the problem correctly.

cmake/std/atdm/spack-rhel/environment.sh
This matches the change to the atdm-spack/install-trilinos-env.sh script in the [atdm-spack](https://gitlab.sandia.gov/atdm/atdm-spack) gitlab repo.
The testing of this is documented in [CDOFA-66](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-66) and included testing with the ATDM Trilinos configuration (Amesos2 tests only) and SPARC.
=> Change Spack module from SuperLUDist 6.2.0 to 5.4.0 (CDOFA-66)

packages/tempus/src/Tempus_IntegratorBasic_decl.hpp, packages/tempus/src/Tempus_IntegratorObserverNoOp.cpp, packages/tempus/src/Tempus_IntegratorObserverNoOp_decl.hpp, packages/tempus/src/Tempus_IntegratorObserverNoOp_impl.hpp, packages/tempus/src/Tempus_StepperSubcycling_decl.hpp, packages/tempus/src/Tempus_StepperSubcycling_impl.hpp, packages/tempus/src/Tempus_TimeStepControlStrategyBasicVS.hpp, packages/tempus/src/Tempus_TimeStepControlStrategyConstant.hpp, packages/tempus/src/Tempus_TimeStepControlStrategyIntegralController.hpp, packages/tempus/src/Tempus_TimeStepControlStrategyPID.hpp, packages/tempus/src/Tempus_TimeStepControl_decl.hpp, packages/tempus/src/Tempus_TimeStepControl_impl.hpp, packages/tempus/test/Subcycling/Tempus_SubcyclingTest.cpp, packages/tempus/unit_test/Tempus_UnitTest_Subcycling.cpp
* Added ability to control printing of timestep changes.
* Added set function for "Output Index List" in TimeStepControl.
* Added ability to set the observer on the Subcycling Integrator.
* Added a no-op IntegratorObserver that does nothing, including
printing headers and timestep during integrator->advanceTime().
Primarily used for Subcycling integrator without printing, which
is the default.
* Added testing for setting the output on/off.
All tests pass on my Mac.
=> Tempus: Add Output Control to TimeStepControl.

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp, packages/panzer/disc-fe/src/Panzer_L2Projection.cpp, packages/panzer/disc-fe/src/lof/Panzer_BlockedTpetraLinearObjFactory_impl.hpp, packages/panzer/disc-fe/src/lof/Panzer_TpetraLinearObjFactory_impl.hpp
@trilinos/panzer @trilinos/tpetra 
Changed dynamic profile Tpetra::CrsGraph construction to static profile.
Static profile requires an upper bound on the number of entries per matrix row to be inserted.
In these changes, I counted the number of entries per row using the same loop structure as the original code to insert the entries.  The count was provided to the constructor and the graph was constructed with StaticProfile before entries are inserted.
Tpetra::DynamicProfile is deprecated.  See https://github.com/trilinos/Trilinos/wiki/Deprecation2
#5602 
Tested on cee-lan linux workstation with ATDM script 
Tested with and without Tpetra_ENABLE_DEPRECATED_CODE=OFF.
For example:
```
source ../cmake/std/atdm/load-env.sh  gnu-7.2.0-openmp-release-debug
MPI_EXEC=`which mpiexec`
cmake \ …
```
=> panzer:  change dynamic profile Tpetra::CrsGraph construction to static profile for #5602

packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
"partitioner: map" should always be `ArrayRCP<int>`, not
`ArrayRCP<GlobalOrdinal>` (this is OK as the elements are local row IDs).
Fixes a test for GO=long long.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #5602 
* Part of 
* Composed of 
Change just affects the test ``TrilinosCouplings_Poisson2D_pn=4_tpetra_MPI_1``, which now passes with GO long long.
=> TrilinosCouplings: fixed wrong type in BlockRelaxation paramlist

packages/muelu/src/CMakeLists.txt
Reverts MueLu to having a single library, "libmuelu", rather than two libraries, "libmuelu" and "libmuelu_lgn".
Should fix #5630.   *However*, the patch must be applied separately to the release candidate branch, trilinos-release-12-18-branch, once it (the patch) passes PR testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6100)
=> MueLu: fix issue #5630

cmake/std/atdm/ATDMDisables.cmake
Addresses #6017
However, we don't want to be enabling any Intrepid tests since Intrepid is
legacy code and we want Percept to change over to use Intrepid2 at some point
soon.  The usage of Intrepid by Percept will be tested through Panzer and that
is all.  Therefore, we disable the implicit enable of the Intrepid tests.
Testing details are given below.
<details>
<summary><b>Testing Details:</b> (click to expand)</summary>
.
Testing out enable of Percept implicitly through Panzer on 'ceerws1113':
```
$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/CEE-RHEL6/CHECKIN/
$ ./checkin-test-atdm-cee-rhel6.sh \
gcc-7.2.0-openmpi-opt-dbg \
--enable-packages=Panzer --local-do-all
PASSED (NOT READY TO PUSH): Trilinos: ceerws1113
Tue Oct 15 17:01:24 MDT 2019
Enabled Packages: Panzer …
```
=> Allow enable of Intrepid and therefore Percept in ATDM Trilinos builds (#6017)

packages/rythmos/src/Rythmos_ExplicitRKStepper_def.hpp, packages/rythmos/src/Rythmos_RKButcherTableau.hpp
PR #5374 changed the way Teuchos::SerialDense* objects are printed.  
These cases were missed in PR #5374.  They will be needed when Teuchos' deprecated code is removed.
@trilinos/tempus @trilinos/teuchos 
Removing deprecated code is good.  Having the remaining code compile correctly is even better.
See #5374 and related issues for discussion.
Giant build with almost every bit of deprecated code in Trilinos disabled.
On cee-lan linux workstation, using ATDM scripts.
```
source /home/tmp/code/Trilinos/cmake/std/atdm/load-env.sh  gnu-7.2.0-openmp-release-debug
module load sems-metis/5.1.0/base
cmake \
-GNinja \
-DMPI_EXEC=${MPI_EXEC} \
-DTrilinos_ENABLE_Domi:BOOL=OFF \ …
```
=> rythmos:  fixed printing of Teuchos::SerialDense* to remove deprecated behavior

cmake/RepositoryDependenciesSetup.cmake
@trilinos/stk @alanw0 @bartlettroscoe 
Some Cmake voodoo to detect STKBalance's insufficient global ordinal types (int, unsigned) at configure time rather than at build time.
If the user specifies Trilinos_ENABLE_STKBalance=ON with insufficient data types, a CMake error is issued.
If STKBalance is enabled only indirectly via enabling STK and the GOs are insufficient, a CMake warning is issued and STKBalance is disabled.
Thanks to @bartlettroscoe for instructions on making these changes and pointing me to the right file.
STKBalance requires global ordinal types long or long long.  It checks for these types at compile time.  But by then, users may have wasted a lot of time building with a global ordinal type that is no good.  It is better to check for sufficient GO types when configuring. …
=> STK:  fix for #5541  Detect insufficient global ordinal type at configure rather than build time

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
- Add a text-book Chebyshev implementation for region MG.
- Move `computeResidual()` utility from `SetupRegionHierarchy_def.hpp` to `SetupRegionMatrix_def.hpp`
- Cover Chebyshev smoother by two region MG completion tests in 2D.
Let's start as WIP-PR, so that we can discuss things.
=> MueLu: add Chebyshev for region MG

cmake/std/PullRequestLinuxDriver.sh
This is needed to allow reporting to CDash
from our cloud nodes.
=> Remove .sandia.gov from the no_proxy list

packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp, packages/tempus/src/Tempus_StepperSubcycling_impl.hpp, packages/tempus/src/Tempus_WrapperModelEvaluatorBasic_impl.hpp, packages/tempus/src/Tempus_WrapperModelEvaluatorPairIMEX_Basic_impl.hpp, packages/tempus/src/Tempus_WrapperModelEvaluatorPairPartIMEX_Basic_impl.hpp, packages/tempus/src/Tempus_WrapperModelEvaluatorSecondOrder_impl.hpp, packages/tempus/test/Subcycling/Tempus_SubcyclingTest.cpp
* Removed some shadow warnings.
* Replaced some double declaration types that should be Scalar.
* Fixed some "local variable will be copied despite being
returned by name [-Wreturn-std-move]" warnings using std::move().
All tests pass on my Mac.
Closes #6119
=> Tempus: Cleanup some warnings.

packages/piro/cmake/Piro_config.hpp.in, packages/piro/src/Piro_PerformAnalysis.hpp, packages/piro/test/Main_AnalysisDriver.cpp, packages/piro/test/_input_Analysis_Dakota.xml, packages/piro/test/_input_Analysis_MOOCHO.xml, packages/piro/test/_input_Analysis_ROL.xml, packages/piro/test/_input_Analysis_ROL_AdjointSensitivities.xml, packages/piro/test/_input_Analysis_ROL_AdjointSensitivities_Tpetra.xml, packages/piro/test/_input_Analysis_ROL_Tpetra.xml, packages/rythmos/src/Rythmos_ExplicitRKStepper_def.hpp, packages/rythmos/src/Rythmos_RKButcherTableau.hpp
Corrected the ifdef guards for testing whether OptiPack deprecated code should be included or hidden.  The old version did not really exclude the OptiPack calls, because include files were not handled correctly.  Now the Optipack calls and tests are excluded correctly (verified during testing with C++-preprocessor warning directives).
This branch also pulls in branch #6117 (rythmos) in order to compile correctly with all deprecated code hidden.
Optipack and GlobiPack are deprecated packages, slated to be removed from Trilinos. #4957
Confirmed removal of tests with @mperego 
cee-lan linux workstation with OptiPack_HIDE_DEPRECATED_CODE=ON
```
cmake \
-GNinja \
-DMPI_EXEC=${MPI_EXEC} \ …
```
=> Piro: remove deprecated tests with OptiPack and GlobiPack

packages/minitensor/src/MiniTensor_LinearAlgebra.i.h, packages/minitensor/src/MiniTensor_Tensor.i.h
The function declaration was in the correct file, but the
definition was left in the incorrect file for a long time.
Fix this.
=> MiniTensor: Move function to right file.

cmake/ctest/drivers/atdm/TrilinosCTestDriverCore.atdm.cmake
This will massively speed up the build times and will also test to see how robust the Trilinos CMake build system is to rebuilds.
```
$ ssh ceerws1113
$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CTEST_S
$  env Trilinos_PACKAGES=Kokkos
./ctest-s-local-test-driver.sh sems-rhel6-gnu-7.2.0-openmp-release-debug
```
The log file showed:
````
-- CTEST_START_WITH_EMPTY_BINARY_DIRECTORY='FALSE'
````
=> ATDM: Do rebuilds by default for all ATDM Trilinos builds

packages/sacado/src/new_design/Sacado_Fad_Exp_DynamicStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_GeneralFad.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_MemPoolStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_StaticFixedStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_StaticStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_VectorDynamicStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_ViewStorage.hpp, packages/sacado/test/UnitTests/CMakeLists.txt, packages/sacado/test/UnitTests/MoveTests.cpp
Adds move constructors/assignment operators to new Fad design, and associated tests.  Also removes use of std::addressof() in the new Fad design which is problematic on the GPU.
=> Sacado:  Add move semantics and fix GPU bug with new Fad design

cmake/std/atdm/waterman/tweaks/Tweaks.cmake
This got removed by accident as part of an earlier refactoring to a single Tweaks.cmake file.  This should allow this test to pass now (without this single unit test).
This should resolve #6166.  Also, see #2410.
On 'waterman' I did:
```
$ cd ~/Trilinos.base/BUILDS/WATERMAN/CHECKIN/
$ ./checkin-test-atdm.sh cuda-9.2-dbg --enable-packages=Teuchos --configure
$ grep TeuchosNumerics_DISABLE_STEQR_TEST cuda-9.2-dbg/configure.out 
-- Setting default TeuchosNumerics_DISABLE_STEQR_TEST=ON
```
**[PASSED]**
=> Add back TeuchosNumerics_DISABLE_STEQR_TEST=ON (#2410, #6166)

packages/muelu/test/scaling/MatrixMatrixMultiply.cpp, packages/tpetra/core/example/Finite-Element-Assembly/CMakeLists.txt, packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_DP.hpp, packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_FE_SP.hpp, packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_LocalElementLoop_DP.hpp, packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_DP.hpp, packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop_SP.hpp, packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_main.cpp, packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.hpp
Also increased the problem size for CGSolve and FE Assembly
strong scaling tests so that the 1-rank run takes roughly 30 seconds
(up from ~1 second)
This lets the automatic CDash output scraper parse the timings. StackedTimer was natural for these performance tests (MatrixMatrixMultiply, CGSolve, and FEAssembly) anyway, since they had all had "global" timers and then sub-timers for each phase of the test. StackedTimer naturally displays this hierarchy and computes the remainder (time not inside a sub-timer) which is useful.
Part of Tpetra stack performance testing effort.
These were just changes to tests.
=> Tpetra/MueLu: switched performance tests to StackedTimer

packages/tempus/src/Tempus_TimeStepControl_decl.hpp, packages/tempus/unit_test/Tempus_UnitTest_TimeStepControl.cpp
Tempus:  This closes issue 6141, no getter functions for output interval and output indices in time step control.  Adds getter functions for output interval and output indices and a unit test demonstrating their correctness.
=> 6141no getter functions for output interval and output indices in time step control

packages/tpetra/core/src/Tpetra_withLocalAccess.hpp
Fixing shadow warning between isValid function argument and isValid() member function.
Testing: No new tests, but code does build (without warnings) with deprecated off
=> Tpetra: Fixing shadow warning

cmake/std/atdm/waterman/tweaks/CUDA-9.2-GNU-7.2.0-OPENMPI-2.1.2_RELEASE_CUDA_POWER9_VOLTA70.cmake
Disables what should be the last failing ROL tests after allowing the enable of Intrepid (see #6017 and #6124).
These two tests are disabled only for the build `Trilinos-atdm-waterman_cuda-9.2_shared_opt`.
On `waterman` I did:
```
$ ssh waterman
$ cd ~/Trilinos.base/BUILDS/WATERMAN/CHECKIN/
$ ./checkin-test-atdm.sh cuda-dbg cuda-opt --enable-packages=ROL --configure
...
PASSED (NOT READY TO PUSH): Trilinos: waterman11
Sat Nov  2 09:50:23 MDT 2019
Enabled Packages: ROL
1) cuda-dbg => passed: configure-only passed => Not ready to push! (2.91 min)
2) cuda-opt => passed: configure-only passed => Not ready to push! (2.81 min)
```
I verified the tests should only be disabled in 'cuda-opt' builds with:
```
$ find . -maxdepth 2 -name configure.out -exec …
```
=> ATDM: Disable randomly hanging ROL_example_PDE-OPT_ginzburg-landau_example_0[1|2]_MPI_4tets (#6124)

cmake/std/atdm/utils/get_known_system_info.sh
A new system is being stood up and it matches systems we already support (cst1) 
On an attaway login node:
```console
jfrye@attaway-login5:[~]: source Trilinos/cmake/std/atdm/load-env.sh Trilinos-atdm-serrano-intel-debug-openmp
Hostname 'attaway-login5' matches known ATDM host 'attaway' and system 'serrano'
Setting compiler and build options for build-name 'Trilinos-atdm-serrano-intel-debug-openmp'
Using toss3 compiler stack INTEL to build DEBUG code with Kokkos node type OPENMP
The following have been reloaded with a version change:
1) mkl/18.0.0.128 => mkl/18.0.5.274
```
on a compute node:
```console
jfrye@swa1:[~]: source Trilinos/cmake/std/atdm/load-env.sh Trilinos-atdm-serrano-intel-debug-openmp
Hostname 'swa1' matches known ATDM host 'attaway' and system 'serrano' …
```
=> Add new cts1 machine attaway to known ATDM systems

cmake/ctest/drivers/atdm/README.md, cmake/std/atdm/README.md, cmake/std/atdm/cee-rhel6/environment.sh, cmake/std/atdm/ctest-s-local-test-driver.sh, cmake/std/atdm/utils/get_known_system_info.sh, cmake/std/atdm/utils/get_system_info.sh, cmake/std/atdm/utils/get_system_info_utils.sh
See the commits for what this does.  After merging this, the 'cee-rhel6' env will work on CEE LAN RHEL7 machines.
<details>
<summary><b>DETAILED TESTS:</b> (click to expand)</summary>
**On 'crf450' (SNL COE RHEL6 wtih SEMS NFS synced):**
```
$ . cmake/std/atdm/load-env.sh default
Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build DEBUG code with Kokkos node type SERIAL
$ . cmake/std/atdm/load-env.sh sems-rhel6-default
Hostname 'crf450.srn.sandia.gov' matches known ATDM host 'sems-rhel6' and system 'sems-rhel6'
Setting compiler and build options for build-name 'sems-rhel6-default'
Using SEMS RHEL6 compiler stack GNU-7.2.0 to build DEBUG …
```
=>  Refactor to more flexible/maintainable system matching and add cee-rhel6 for CEE RHEL7 (ATDV-228)

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp
Use std::map to temporarily store padding needed to resize CrsGraph and then pass to Kokkos::UnorderedMap.
Allows accumulation of new entries, since Kokkos::UnorderedMap does not allow reinsertion.
Broken Albany test shows as passed.
#6163
Broken Albany test passes
=> Tpetra: possible fix for #6163

packages/intrepid2/src/Shared/Intrepid2_Utils.hpp
Under certain circumstances (not entirely understood, but with a reproducing configuration provided by @stanmoore1), gcc gives errors for our existing typedef deprecation warnings.  
* Closes #6233
=> Intrepid2: fix a gcc error related to our typedef deprecation warnings.

.mailmap
This gives a more accurate count of the number of commits being made by Sandia and non-Sandia developers.
=> Update mapping of git users to remove duplicate and put in sandia.gov addresses

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
Fusing of prolongation and update was implemented in the hierarchy, but not exposed in the ParameterListInterpreter.
=> MueLu ParameterListInterpreter: fuse prolongation and update

cmake/std/atdm/utils/get_known_system_info.sh
This was a varaible that I did not test in my manual testing.  Very bad.
This killed the testing on a bunch of machines.
=> Fix setting of ATDM_CONFIG_BUILD_NAME when hostname match system is in build name (ATDV-228)

cmake/std/atdm/utils/get_known_system_info.sh
Turns out that you have to actually define the SEMS modules in order to hvae
SEMS_SYSTEM set.  Therefore, this adds back logic to look for the file:
/projects/sems/modulefiles/utils/get-platform
This should fix the 'sems-rhel7' builds on ascicgpu14 and other such machines.
I disabled the sourcing of:
```
. /projects/sems/modulefiles/utils/sems-modules-init.sh
```
in my `.bashrc` file and I was able to reproduce the problem where it did not recognize support for the system 'sems-rhel7' on ascicgpu14.  After this patch, it did.
=> ATDM: Fix detection of sems-rhel6 and sems-rhel7 when SEMS_SYSTEM is not set (ATDV-228)

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp
Now that the code is getting closer to being run at large scale output statement from all ranks should be used more cautiously.
Also adding a bit more profiling.
Testing was performed locally, the extra output is gone.
=> MueLu: removing some std::cout statments from region functions

cmake/std/atdm/apps/empire/EMPIRETrilinosEnables.cmake
Migrate two Trilinos configuration flags from EMPIRE's build scripts to those in Trilinos itself.  These flags have been included in EMPIRE's build scripts for some time, but if Trilinos developers are going to exactly replicate an EMPIRE build of Trilinos, these need to be in Trilinos instead.
=> Change EMPIRE Trilinos Configuration

packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp, packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp
- UncoupledAggregation_kokkos was ignoring Dirichlet nodes.
- TentativeP_kokkos did not compress the matrix correctly for nullspace of dim = 1.
=> MueLu: UncoupledAggregation_kokkos fixes

cmake/std/atdm/utils/get_known_system_info.sh
This should fix the bug reported in #6276 for systems where the ATDM system is not selected from the hostname (e.g. 'sems-rhel7').  It was just a bug on my part.
I also got rid of some unnecessary code so the should should be more uniform now and easier to maintain.
=> Fix bug in atdm/utils/get_know_system_info.sh (#6276)

packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
@trilinos/tpetra @vbrunini 
In the Tpetra::CrsMatrix unpack functor, assume that the local matrix's rows are sorted, when calling sumIntoValues and replaceValues.
* Closes #6282 
See Sierra Thermal Fluids issue TF-1264.
This should be exercised by existing Tpetra::CrsMatrix unpack / doExport / doImport tests.
=> Tpetra: Fix #6282 (in CrsMatrix unpack functor, assume matrix rows sorted)

packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp, packages/tpetra/core/example/advanced/Benchmarks/CMakeLists.txt, packages/tpetra/core/example/advanced/Benchmarks/CrsMatrixDenseRowUnpack.cpp, packages/tpetra/core/src/CMakeLists.txt, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_PackTraits.hpp, packages/tpetra/core/src/Tpetra_Details_ScalarViewTraits.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp, packages/tpetra/core/src/Tpetra_DirectoryImpl_decl.hpp, packages/tpetra/core/src/Tpetra_Map_decl.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
@trilinos/tpetra @trilinos/stokhos 
1. Fix #6300 (build warnings).
2. Add benchmark for `Tpetra::CrsMatrix::unpackAndCombine`, for the special case of dense rows (see #6282).
3. Reorganize `Tpetra::Details::PackTraits` to simplify code and reduce need for templating on Device type.  This touches Stokhos a bit.
Sierra (specifically Aria) discovered the performance issue that led to #6282. 
* Closes #6300 
* Related to #6282. 
See TF-1264 (in Aria's internal issue tracking system).
The new benchmark includes a test; the test always runs.
=> Tpetra: Fix #6300; add benchmark for CrsMatrix unpack

packages/kokkos-kernels/src/common/KokkosKernels_ExecSpaceUtils.hpp
Matches PR https://github.com/kokkos/kokkos-kernels/pull/499
Should fix https://github.com/trilinos/Trilinos/issues/6264
=> Fix suggested vector size when nr == 0

packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp, packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases/TensorViewFunctorTests.cpp
Closes #6307 (test failures when built with `KOKKOS_ENABLE_DEPRECATED_CODE=OFF`).
=> Intrepid2: Fix 6307

packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyBasis.hpp, packages/intrepid2/unit-test/Orientation/test_orientation_HEX.hpp, packages/intrepid2/unit-test/Orientation/test_orientation_QUAD.hpp, packages/intrepid2/unit-test/Orientation/test_orientation_TET.hpp, packages/intrepid2/unit-test/Orientation/test_orientation_TRI.hpp
Also, modified tests for hexahedron, quadrilateral, tetrahedron, and triangle so that these now exercise the new code path as well as the old.  Also tweaked those tests slightly to fix an issue where some code that was in a cell loop should not have been in a cell loop (the code was not wrong, but slightly less precise than it might have been).
See #6317.
Closes #6317.
The new code path is exercised by the Test_Orientation_{HEX,QUAD,TET,TRI} tests.
=> Intrepid2: tweaks to OrientationTools::modifyBasisByOrientation() to allow reference-space inputs.

cmake/std/atdm/README.md
To be safe, and to match with all of the CUDA builds, I reduced the default parallel level for ctest to ctest -j4.  This should avoid problems with GPU overloading.  (Part of #6052.)
=> Reduce to ctest -j4 in all documentation (#6052)

packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_kokkos_def.hpp, packages/muelu/test/interface/ParameterListInterpreter.cpp
A piece of logic is wrong in the algorithms that counts
how many nodes have been aggregated in Phase2a of aggregation.
This commit fixes that by individually counting every node
that is being aggregated instead of counting all the nodes in
a newly formed aggregate, at once.
All bugs shall be fixed, but this is also generating a failing test in Empire and blocking the adoption of the latest refactored setup of MueLu.
* Closes #6325
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Empire: @cgcgcg will check that the failing test is fixed after this modification is applied.
ExaWind: @lucbv checked that ExaWind is not negatively affected by these changes.
Local tests have been performed and @cgcgcg will apply locally these changes to …
=> MueLu: fixing the count of aggregated nodes in refactored Phase2a of aggregation, see #6325

packages/tpetra/core/test/Block/BlockCrsMatrix.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_PackUnpack.cpp, packages/tpetra/core/test/ImportExport2/ImportExport2_CrsSortingUtils.cpp
In #6314, @william76 noted that Tpetra tests failed to compile when he built with Trilinos_ENABLE_FLOAT and Trilinos_ENABLE_COMPLEX.  The problem was a multiplication of a double constant (2.) with a std::complex<float>.  These changes convert the double constant to scalar_type to allow successful compilation and execution.
At the same time, I loosened a tolerance in one test that failed with scalar_type=float.  
@william76 : please let me know whether this PR solves your compilation issue.  I do **not** expect these changes to fix the Xpetra issue in #6314, but they should allow you to make progress with compilation for your debugging of #6314 
Built and tested on linux workstation with Trilinos_ENABLE_FLOAT and Trilinos_ENABLE_COMPLEX, as well as the usual instantiated …
=> Tpetra:  conversions to allow compilation of tests when scalar=std::complex<float>

packages/sacado/src/Sacado_SFINAE_Macros.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_DynamicStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_GeneralFad.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_MemPoolStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_StaticFixedStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_StaticStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_VectorDynamicStorage.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_ViewStorage.hpp
The new design implementation was allowing conversions from other AD
types to ViewFad, which is not correct.  In addition to being generally
unsafe, this was causing compiler errors in Panzer when the two return
types of the ternary operator differ, with one being ViewFad.
It tooks some time to figure out a way to do this that NVCC accepted.
It seems to not handle inherited constructors disabled through SFINAE
correctly.
=> Sacado:  Fix ViewFad conversions for new design.

packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
DO NOT MERGE until we know that this doesn't break EMPIRE.
This change re-enables the fast codepath in ``Xpetra::MatrixMatrix::TwoMatrixAdd()`` that was originally merged in #6190, but which was reverted in #6266 because it appeared to break EMPIRE (see #6264). But now it seems that #6190 just exposed an existing bug in MueLu kokkos refactor uncoupled aggregation. So @rppawlo when it is confirmed that this patch (reverting the revert) doesn't break EMPIRE, we can put it back in develop.
* Closes 
* Blocks 
* Follows #6190 (which had this enabled originally), #6266 (which reverted this code path) 
* Precedes 
* Related to #6264
* Part of 
* Composed of 
See comments on #6264 for the discussion about the new EMPIRE failures from 11-12-19.
=> Xpetra: Re-enabled fast TwoMatrixAdd path

packages/muelu/test/interface/ParameterListInterpreter.cpp
After kokkos refactor of aggregation, non deterministic aggregates are formed.
This means that checking operator complexity against a gold file is wrong.
This commits implements logic to ignore OperatorComplexity for kokkos runs of
ParameterListInterpreter.
This PR fixes an issue in the ParameterListInerpreter that arose after the implementation of the refactored aggregation. It should fix the ATDM tests on GPU machines.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@bartlettroscoe please let us know if this change fixes test failures of the ATDM track observed in #6361 
Local build and tests have been performed.
=> MueLu: ignoring OperatorComplexity in ParameterListInterpreter for kokkos, see issue #6361

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
No need to set an importer in TAFC when column and domain map match.
=> Tpetra TAFC: Do not set importer when not needed

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionVector_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/main.cpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/test/unit_tests/RegionMatrix.cpp, packages/muelu/test/unit_tests/RegionVector.cpp
A debug build of trilinos reveals that a potentially wrong map is used when importing into a composite vector inside function: regionalToComposite(). This is fixed by using the maps stored in the import object instead of input arguments to regionalToComposite(). Further interface simplifications could be done in regionalToComposite() and compositeToRegional().
I am adding the gdb stack trace that I get when running the tests: [debug_build_gdb_trace.txt](https://github.com/trilinos/Trilinos/files/3889006/debug_build_gdb_trace.txt)
* Closes #6349
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Performed a local debug build and ran `ctest -R` on it, all tests are now passing.
=> MueLu: fixing regionalToComposite() for region vectors

packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp, packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
Reimplementation of  GetDiagonalInverse that uses proper
Kokkos parallel execution policies and that does not rely on UVM.
Also fixing some type comparison issues in a unit-test.
Prolongator smoothing relies on `MueLu::Utilities_kokkos::getDiagonalInverse()` to performed damped jacobi on a tentative prolongator. The Utility function is however written in serial and relies on UVM. This is neither good for performance nor for long term portability.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #6161
* Composed of 
ExaWind is requiring to run most of the setup on GPU so this needs to be done as it alleviate the implicit UVM copies.
Local tests using OpenMP has been performed and indicates good behavior.
=> MueLu: Refactoring Utilities_kokkos to avoid use of UVM, see issue #6161

packages/muelu/test/unit_tests/RegionVector.cpp
Using 1.0 in TEUCHOS_FLOATING_EQUALITY fails in a std::complex<> build because of template type deduction.
MueLu does not compile when both `Experimental` and `Complex` are turned on.
This should fix that specific build.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of
=> MueLu: region vector test fix

cmake/tribits/ci_support/CDashQueryAnalyzeReport.py, cmake/tribits/ci_support/cdash_analyze_and_report.py, cmake/tribits/ci_support/cdash_build_testing_date.py, cmake/tribits/python_utils/gitdist-setup.sh, cmake/tribits/python_utils/gitdist.py
The main update from this snapshot is the updated gitdist-setup.sh script that automatically sets and alias to the gitdist file in the same directory.  Makes it super easy to get setup to use gitidst (just a single  source command).  This brings this into Trilinos.
The update to cdash_analyze_and_report.py is to support `--date=today` and `--date=yesterday` which are the most common use cases.
=> Update cdash_analyze_and_report.py and gitdist-setup.sh

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionVector_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/main.cpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/test/unit_tests/RegionMatrix.cpp, packages/muelu/test/unit_tests/RegionVector.cpp
@lucbv 
First cut at cleaning up function interfaces. In particular, this PR removes function arguments
- that haven't been used anyway.
- that are kind of redundant, because their content can be easily extracted from other arguments.
This is experimental code. No applications use it right now.
The set of regionMG tests runs and passes.
For sure, there's more to do. In particular, we could/should think about getting rid of the concept of "groups"...
=> MueLu: cleanup function interfaces in regionMG

cmake/std/PullRequestLinuxDriverTest.py, cmake/std/README.md, cmake/std/unittests/TestPullRequestLinuxDriverTest.py
This is WIP - I want to see what the Python PR testing shows since I haven't been able to replicate it locally.
Mostly just some style and formatting cleanup to make some things more readable, but I also made a more generic memory information option that tries to use psutil, and if it's not available then we try to load `/proc/meminfo` which would only work on Linux machines.
=> Framework: Some cleanup and tweaks on PR testing script

packages/muelu/research/mmayr/composite_to_regions/src/main.cpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Review of #6376 brought up some possible compiler warnings in experimental code. So far, they don't cause trouble in PR testing, as they are guarded by `EXPERIMENTAL` flags. Still, let's fix this just to be safe.
* Follows comments in PR #6376
This is experimental code, so there's no external app.
Unit tests pass.
=> MueLu: fix some compiler warnings in experimental code

packages/belos/tpetra/src/BelosMultiVecTraits_Tpetra.hpp, packages/stokhos/src/sacado/kokkos/pce/tpetra/Tpetra_TsqrAdaptor_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/tpetra/Tpetra_TsqrAdaptor_MP_Vector.hpp, packages/stratimikos/adapters/belos/src/Thyra_TsqrAdaptor.hpp, packages/tpetra/core/src/Epetra_TsqrAdaptor.hpp, packages/tpetra/core/src/Tpetra_TsqrAdaptor.hpp, packages/tpetra/core/test/CMakeLists.txt, packages/tpetra/core/test/Node/Issue510.cpp, packages/tpetra/core/test/Tsqr/CMakeLists.txt, packages/tpetra/core/test/Tsqr/TsqrAdaptor.cpp, packages/tpetra/tsqr/src/Tsqr_NodeTsqrFactory.hpp
@trilinos/tpetra @trilinos/belos @trilinos/stokhos
1. TsqrAdaptor no longer calls the deprecated method
`Tpetra::Map::getNode`.  This includes the two partial
specializations of TsqrAdaptor in Stokhos.
2. Tpetra now has a test that builds and calls methods in TsqrAdaptor.
Before, the only tests for TsqrAdaptor were in Belos.
Albany reported build errors in its Tpetra develop build with deprecated code off.
* Closes #6354 
Reported by Albany in #6354.
=> Stokhos,Belos,Tpetra: Fix #6354 (part 2)

packages/amesos2/src/Amesos2_MUMPS_decl.hpp, packages/amesos2/src/Amesos2_MUMPS_def.hpp, packages/amesos2/test/solvers/MUMPS_UnitTests.cpp
I made some changes to the MUMPS interface to fix the following two issues:
1. Mumps data was not freed correct which resulted in memory leaks.
2. Input matrix was only converted to mumps compatible data when the internal variable was `MUMPS_MATRIX_LOAD=false`. As a consequence, the data was only correct if the solver was constructed for the first time. It was not possible to reuse the symbolic factorization of a previous matrix with the same pattern and only call the numeric factorization.
Furthermore, I added the error messages of the Amesos_MUMPS interface to the Amesos2_MUMPS interface.
The previous four test still work. Additionally, I added a fifth test where the numeric factorization and the solve is preformed twice without resetting the solver object.
=> Fixes to Amesos2_MUMPS interface

packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp, packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp, packages/galeri/src-xpetra/Galeri_StencilProblems.hpp, packages/zoltan2/src/algorithms/order/Zoltan2_AlgND.hpp, packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp, packages/zoltan2/test/directory/directoryTest_KokkosSimple.cpp, packages/zoltan2/test/helpers/UserInputForTests.hpp
@trilinos/zoltan2 @trilinos/galeri 
In #6295, @ZUUL42 is trying to stand up PR build with gcc 8.3 and warnings-as-errors.
These changes eliminate warnings reported in Zoltan2 tests.
#6295 
@ZUUL42 please let me know whether or not Zoltan2 comes back clean in your re-testing
Built and ran with gcc 8.3 and openmpi 1.10 on cee-lan.
```
module load sems-env
module load sems-cmake/3.10.3
module load sierra-devel/gcc-8.3.0-openmpi-1.10.2
```
Used Tpetra_ENABLE_DEPRECATED_CODE=OFF and KOKKOS_ENABLE_DEPRECATED_CODE=OFF
=> Zoltan2 and Galeri:  remove warnings reported by gcc8.3 

packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp
This PR contains an improved version of KokkosBlas::gemm for CUDA: DotBasedGEMM. DotBasedGEMM implements the optimization for C = betaC + alphaA^TB with A and B matrices both being tall and skinny. C matrix is assumably small, so each entry of C is computed by performing the dot product of respective columns of A and B matrices. Note that the dot products are performed on very long vectors, so each dot product is distributed among multiple teams.
When the conditions of having tall and skinny matrices in the form alpha*A^TB hold, instead of calling CUBLAS' gemm, DotBasedGEMM is called. This is considered as an improvement over CUBLAS' gemm, so DotBasedGEMM never takes place if CUBLAS is not enabled.
Respective PR for Kokkos-Kernels is …
=> KokkosKernels: Optimized GEMM for A^TB with tall and skinny matrices on CUDA.

packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Fix type mismatch introduced in #6382, since it caused problems when casting `std::complex<double>`.
* Follows #6382
* Related to #6401
`MueLu_Structured_Region` tests pass locally. However, I haven't tried the exact build, that was used when reporting the original issue.
=> MueLu: fix type mismatch reported in #6401

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
@cgcgcg 
TpetraExt::MatrixMatrix::add() was producing a fill-complete result matrix with unsorted local entries (invalid). It was doing setAllValues() followed by fillComplete(), but the fillComplete was not sorting indices because the graph's isSorted_ flag was still true.
- Fixed the actual problem in add() by sorting indices before calling setAllValues()
- Updated the documentation for CrsGraph::setAllIndices() and CrsMatrix::setAllValues() to say that the indices must be sorted on input, because they do not check for sorted
- setAllIndices() now sets isSorted_ and noRedundancies_ to true, since neither sorting nor merging will be done during fillComplete(). This was already happening in all the CrsGraph constructors that call setAllIndices().
Fixes a bug exposed by …
=> Tpetra: explicitly sort entries of add() result, make setAllIndices() expect sorted.

packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Resolve #6399.  Removes valgrind warnings due to uninitialized data in the array buffer. The buffer is used to eliminate some branching in the kernel so those elements are not actually used. But initializing the element will be negligible cost and removes the valgrind warning. This fix is not expected to have any side effects on the calculation.
=> Zoltan2: Fix valgrind warning for Multijagged (#6399)

cmake/std/atdm/ATDMDisables.cmake, cmake/std/atdm/shiller/tweaks/CUDA_COMMON_TWEAKS.cmake, cmake/std/atdm/shiller/tweaks/GNU_DEBUG_SERIAL_HSW.cmake, cmake/std/atdm/shiller/tweaks/GNU_RELEASE_SERIAL_HSW.cmake
This is an attempt to reduce the cost of maintaining the ATDM Trillinos builds
by not taking time to triage failing tests that don't protect functionality
used by the ATDM APPs.  In the past, we were asked to test more functionality
than is used by ATDM but we have to cut down on the cost of maintaining these
builds and disabling these tests is an easy way to do that that will not
negatively impact ATDM.
For more details, see [ATDV-261|https://sems-atlassian-srn.sandia.gov/browse/ATDV-261].
On my RHEL 6 machine I tested the disables with:
```
$ cd /home/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL6/CHECKIN/
$ ./checkin-test-atdm.sh gnu-openmp-opt --enable-all-packages=on --configure
```
The configure output showed:
```
$ grep "Final set of enabled packages" gnu-openmp-opt/configure.out …
```
=> ATDM: Disable all Ansazi and Piro tests, troublesome Belos tests related to ATDM (ATDV-261)

packages/minitensor/src/MiniTensor_Utilities.i.h, packages/sacado/src/Sacado_CacheFad_Ops.hpp, packages/sacado/src/Sacado_ELRCacheFad_Ops.hpp, packages/sacado/src/Sacado_ELRFad_Ops.hpp, packages/sacado/src/Sacado_Fad_Ops.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp, packages/sacado/test/UnitTests/CMakeLists.txt, packages/sacado/test/UnitTests/TernaryExprTests.cpp, packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_ops.hpp, packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp
This marks all unary operation constructors for
expression-template-based Sacado/Stokhos scalar types explicit,
preventing implicit conversions to these types.  An implicit conversion
to an expression template class should never happen, so this should have
been added a long time ago.  It also fixes compiler errors when using
the ternary operator with scalars and unary expressions, such as
conditional ? scalar : unary-expression ;
by preventing a possible implicit conversion of scalar to
unary-expression, and without having to put an explicit conversion to
scalar in the code.  Note that ternary involving two expressions
e.g., "conditional ? expression1 : expression2 ;" still
won't work because of limitations in the standard.
Related to Kokkos PR …
=> Sacado/Stokhos:  Make unary expression constructors explicit.

cmake/std/atdm/ATDMDisables.cmake
We don't have the human resources to continue to keep testing and trying to maintain builds and tests that ATDM does not use.  If ATDM APPs are not directly impacted, Trilinos developers mostly just ignore the GitHub issues we create so it is a waste of computer resources and human time maintaining them. 
For more details, see [ATDV-261](https://sems-atlassian-srn.sandia.gov/browse/ATDV-261), [ATDV-262](https://sems-atlassian-srn.sandia.gov/browse/ATDV-262), and [ATDV-265](https://sems-atlassian-srn.sandia.gov/browse/ATDV-265).
Doing configure of Trilinos with GEMMA packages:
```
$ ssh ascicgpu15
$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CHECKIN/
sems-rhel7-cuda-9.2-Volta70-complex-shared-release-debug \ …
```
=> ATDM: Disable packages GEMMA does not use in all cuda+complex builds (ATDV-265)

packages/teuchos/core/test/MemoryManagement/Array_Performance_UnitTests.cpp
For the CUDA debug builds on 'white' and 'ride', this ratio has gotten as high
as 123 (see #6429).  Not sure what changes on 'white' and 'ride' to trigger these timing
failures, but this particular test is not designed to be performance test per
say in an arbitrary (ebug) build.  It is hard to believe the ratio of
non-optimized Teuchos Array iterator operations is more than 100x slower than
raw pointer operations on this machine but I guess anything is possible.
NOTE: This just changes the default.  It does not change the proper
PERFORMANCE test.
=> Teuchos: Change default of maxArrayIterRatio from 100 to 200 (#6429)

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_Details_makeColMap_decl.hpp
At CrsMatrix/CrsGraph constructors and replaceColMap(),
document the GID ordering requirements of column maps:
-locals before remotes (determined by domain map)
-locals sorted
-remotes sorted first by proc and then by GID
Strongly recommending that Details::makeColMap() be
used instead of constructing it manually from raw GIDs.
Also, fix a typo in a makeColMap comment.
The requirements of column maps need to be codified, especially as more matrix/graph construction stuff gets rewritten using Kokkos. Having these comments here would have made #6190 a lot easier, for example.
* Closes 
* Blocks 
* Follows #6190  
* Precedes 
* Related to 
* Part of 
* Composed of 
Just documentation (doxygen/comment) changes.
=> Tpetra: document the requirements of column maps

packages/kokkos-kernels/src/impl/tpls/KokkosBlas3_gemm_tpl_spec_decl.hpp, packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp
This PR 
1) fixes the issue https://github.com/trilinos/Trilinos/issues/6418, which was caused by DotBasedGEMM in KokkosKernels, by excluding the conjugate transpose case for A from the optimized case and    
2) upgrades the initialization kernels in DotBasedGEMM to use MDRangePolicy.
https://github.com/trilinos/Trilinos/issues/6418
https://github.com/kokkos/kokkos-kernels/pull/510#discussion_r354566671
These tests (which were failing in https://github.com/trilinos/Trilinos/issues/6418) are passing now:
TpetraCore_gemm_m_eq_1_MPI_1
TpetraCore_gemm_m_eq_2_MPI_1
TpetraCore_gemm_m_eq_5_MPI_1
TpetraCore_gemm_m_eq_13_MPI_1
TpetraCore_MultiVector_UnitTests_MPI_4
=> KokkosKernels: Fix #6418 

packages/xpetra/src/Map/Xpetra_EpetraMapFactory.cpp
Just removing un-necessary type definition since the definitions are already available through the class templates.
This is should remove the current error in Xpetra from [this build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic166&field2=buildname&compare2=61&value2=PR-gcc_8.3-test-Trilinos_pullrequest_gcc_8.3.0-15&field3=buildstamp&compare3=61&value3=20191211-0033-Experimental)
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #6295 
* Composed of 
Local build and tests have been performed using gcc/8.3.0
=> Xpetra: fixing a -Wshadow warning for issue #6295

packages/rol/adapters/tpetra/src/mpi/ROL_PinTVectorCommunication_Tpetra.hpp
Convert templated calls getLocalView<Kokkos::HostSpace> to getLocalViewHost
modified:   packages/rol/adapters/tpetra/src/mpi/ROL_PinTVectorCommunication_Tpetra.hpp
@trilinos/rol 
These changes are necessary to successfully compile when disabling Kokkos' deprecated code.
Detected during Kokkos+KokkosKernels Trilinos Integration testing on Waterman with a configuration like the following:
```
module purge
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh cuda-9.2-opt
cmake \
-GNinja \
-DTrilinos_ENABLE_ALL_PACKAGES=ON \
-DKOKKOS_ENABLE_DEPRECATED_CODE=OFF \
$TRILINOS_DIR
```
Compilation now successfully continuing with the changes in the PR
=> rol: updates to fix compile errors with kokkos deprecated code off

packages/kokkos-kernels/src/graph/KokkosGraph_Distance1ColorHandle.hpp, packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp
Addresses issue #6450
update handle to call get_suggested_team_size with proper API, missed
during cherry pick as part of PR #6439
preemptively update Blas3_gemm unit test as done in PR
kokkos/kokkos-kernels#529
Fix bug reported in #6450
Confirmation from @ikalash that this resolve Albany issues reported in #6450 
a la PR tester
=> kokkos-kernels: update distance1 handle, gemm unit test

packages/tempus/src/Tempus_SolutionState_impl.hpp
Fixed a bug in SolutionState where the member data physicsState_
and physicsState_nc_ could be a null RCP.
Closes #6461 
Have tested against EMPIRE and passes all tests.
=> Tempus: Null RCP to PhysicsState

packages/piro/src/Piro_PerformAnalysis.cpp
Remove `#define HAVE_PIRO_ROL` accidentally added in commit 0cb8e1a
=> Fix  Piro::PerformAnalysis

packages/muelu/test/scaling/ImportPerformance.cpp, packages/xpetra/CMakeLists.txt, packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_decl.hpp, packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_def.hpp, packages/xpetra/src/BlockedMap/Xpetra_BlockedMap_def.hpp, packages/xpetra/src/BlockedVector/Xpetra_BlockedVector_def.hpp, packages/xpetra/src/Vector/Xpetra_EpetraVectorFactory.cpp, packages/xpetra/sup/StridedMap/Xpetra_StridedMap_def.hpp, packages/xpetra/test/BlockedMultiVector/ThyraBlockedMultiVector_UnitTests.cpp, packages/xpetra/test/Map/StridedMapFactory_UnitTests.cpp, packages/xpetra/test/Matrix/Matrix_UnitTests.cpp
- Xpetra cmake tried to pass type and docstring to set(), but that
isn't allowed (so HAVE_XPETRA_EXPLICIT_INSTANTIATION was really
being set to "OFF BOOL ..." which is truthy).
- Fixed some places where Y_decl.hpp was included in X_def.hpp.
Instead, including Y.hpp.
- Fixed some missing decl includes that caused missing short names
definitions.
- In MueLu ImportPerformance test, guard usage of Kokkos with macros
The [nightly geminga build that does this configuration](https://testing-dev.sandia.gov/cdash/viewBuildError.php?buildid=5097866) has been failing.
Only file includes were changed, not semantics.
=> Xpetra, MueLu: Fix no-tpetra, no-ETI build

cmake/tribits/ci_support/cdash_build_testing_date.py, cmake/tribits/python_utils/GeneralScriptSupport.py, cmake/tribits/python_utils/GenerateDocUtilsOutput.py, cmake/tribits/python_utils/gitdist-setup.sh
Mostly updating to provide a nice gitdist-show-full-repo-state function that can be used to give the status of a set of git repos in one shot.
This will be useful in testing Trilinos against SPARC and EMPIRE as part of the epic [ATDV-240](https://sems-atlassian-srn.sandia.gov/browse/ATDV-240).
=> Update TriBITS for updated gitdist-setup.sh script mostly

packages/belos/epetra/src/BelosEpetraAdapter.cpp, packages/belos/tpetra/test/Issue_3235.cpp, packages/teuchos/numerics/src/Teuchos_SerialDenseMatrix.hpp, packages/teuchos/numerics/src/Teuchos_SerialSymDenseMatrix.hpp
@trilinos/teuchos @trilinos/belos 
CUDA builds show lots of spurious warnings involving `Teuchos::SerialDenseMatrix` and `Teuchos::SerialSymDenseMatrix`.  This PR disables those warnings for the specific code that generates them.  I also took the opportunity to fix a few more warnings and clean up code in light of C++11.  The whitespace changes are just automatic conversion of tabs to spaces.
* Closes #3666
Sierra developers should appreciate this removal of spurious build warnings.
Changes already covered by existing tests.
=> Teuchos: Fix #3666

cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt.sh, cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_gnu-7.2.0_openmpi-4.0.1_serial_shared_opt.sh, cmake/std/atdm/cee-rhel6/all_supported_builds.sh, cmake/std/atdm/cee-rhel6/custom_builds.sh, cmake/std/atdm/cee-rhel6/environment.sh, cmake/std/atdm/ctest-s-local-test-driver.sh
This adds the ATDM Trilinos builds:
*   cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt
*  cee-rhel6_gnu-7.2.0_openmpi-4.0.1_serial_shared_opt
See [ATDV-237](https://sems-atlassian-srn.sandia.gov/browse/ATDV-237).
SPARC switched these builds form openmpi-1.10.2 to openmpi-4.0.1 many weeks ago and this change is needed to support SPARC, obviously.
On the machine 'ceerws1113' I ran:
```
$ env Trilinos_PACKAGES=Kokkos,Teuchos,Tpetra,Amesos2,SEACAS,Panzer \
./ctest-s-local-test-driver-cee-rhel6.sh \
cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt \
cee-rhel6_gnu-7.2.0_openmpi-4.0.1_serial_shared_opt
***
*** /scratch/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/ctest-s-local-test-driver.sh
***
ATDM_TRILINOS_DIR = '/scratch/rabartl/Trilinos.base/Trilinos'
Load some env to get …
```
=> ATDM: Add cee-rhel6 openmpi-4.0.1 builds (ATDV-237)

cmake/std/atdm/common/toss3/environment_new.sh
EMPIRE developers can't load 'sparc' modules.  Therefore, we replace
'sparc-git/2.19.1' with 'sems-git/2.10.1' which should be good enough.
Also, I replaced atdm-ninja_fortran/1.7.2 with sems-ninja_fortran/1.8.2 which
is newer and eliminates usage of the old 'atdv-env' modules (which will be
replaced by Spack modules when I get a chance).
On eclipse I did:
```
$ /nscratch/rabartl/Trilinos.base/BUILDS/CTS1/CTEST_S/
$  env Trilinos_PACKAGES=Kokkos,Teuchos \
./ctest-s-local-test-driver-cts1.sh \
cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_opt
***
*** /home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/ctest-s-local-test-driver.sh
***
Hostname 'eclipse-login8' matches known ATDM host …
```
=> ATDM: cts1: Eliminate usage of 'sparc' and old 'atdv' modules (ATDV-212)

cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-4.0.1_serial_static_opt.sh, cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_gnu-7.2.0_openmpi-4.0.1_serial_shared_opt.sh
I triaged the one randomly failing test in #6532.  I think it is appropriate to promote these builds given the other builds in the ATDM group are not 100% clean (and no one seems to care that much).
SPARC is using these builds in production so they need to be promoted.
=> Promote new cee-rhel6 openmpi-4.0.1 builds to ATDM group (ATDV-237)

packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp, packages/zoltan2/test/helpers/GeometricGenerator.hpp
This will resolve indeterminate behavior in the Multijagged calculation.
This is expected to resolve most of the cases where 6440 failed. However in one case, cdash showed a segfault and it's not clear yet why that would occur or if it would be impacted by this fix. This will at least get the test running in a consistent manner.
Eliminates indeterminate behavior. Will fix most but perhaps not all intermittent failures reported in #6440.
=> Zoltan2: Fixes for #6440

cmake/std/atdm/common/toss3/environment_tlcc2.sh, cmake/std/atdm/tlcc2/environment.sh
It looks like my editor cleaned up the whitespace in these files.
Developers desired newer cmake version.
None.
```
source cmake/std/atdm/load-env.sh default
Hostname 'chama-login5' matches known ATDM host 'chama' and system 'tlcc2'
Using toss3 compiler stack INTEL to build DEBUG code with Kokkos node type SERIAL
The following have been reloaded with a version change:
1) mkl/18.0.0.128 => mkl/18.0.5.274
```
```
source cmake/std/atdm/load-env.sh default
Hostname 'skybridge-login3' matches known ATDM host 'skybridge' and system 'tlcc2'
Using toss3 compiler stack INTEL to build DEBUG code with Kokkos node type SERIAL
The following have been reloaded with a version change: …
```
=> ATDM: Update cmake version to 3.12.2 in tlcc2 env

packages/amesos2/example/quick_solve.cpp, packages/amesos2/example/quick_solve_epetra.cpp, packages/amesos2/test/solvers/Solver_Test.cpp
Simply catching errors as `const reference` instead of `by value`, this removes the warnings coming out of Amesos2 in [this build](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=gcc_8.3.0&field2=buildstamp&compare2=63&value2=Experimental)
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #6295 
* Composed of 
@ZUUL42 let us know if this fixes the warnings from Amesos2 or if there is more that needs to be done?
Locally compiler and tested without problems
=> Amesos2: fixing gcc 8.3.0 warnings for #6295

packages/intrepid2/src/Shared/Intrepid2_Kernels.hpp
Using `Intrepid2::Impl::CellTools::Serial::mapToReferenceFrame()` when `Kokkos` has deprecated code disabled fails. That functions calls `Intrepid2::Kernels::Serial::copy()` with a rank-1 `Kokkos::View` object which assumes a rank-2 `Kokkos::View` object. However, accessing entries in `Kokkos::View` objects via the call operator is only allowed for matching ranks. It seems that this function is only used in  `Intrepid2::Impl::CellTools::Serial::mapToReferenceFrame()`. Hence, it seems like modifying the copy function to take a rank-1 `Kokkos::View` looks like another possible solution.
The change relaxes the constraints on using `Intrepid2::Kernels::Serial::copy()`. Hence, there should be no noticeable change.
=> Intrepid2: Allow using Kokkos with deprecated code

packages/panzer/adapters-stk/test/evaluator_tests/domain_interface.cpp, packages/panzer/disc-fe/src/Panzer_Evaluator_DomainInterface.cpp, packages/panzer/disc-fe/src/Panzer_Evaluator_DomainInterface.hpp
We need this to simplify the handling of interior sideset boundary conditions in EMPIRE.
Added test to ensure the proper indexes were selected with EXTERNAL domain selected
=> Panzer: Adding domain EXTERNAL to DomainEvaluator 

packages/ifpack/src/Ifpack_Utils.cpp
@trilinos/ifpack 
resizing buffer and filename to avoid overflow warning, this will allow us to setup a gcc 8.3.0 build with warnings as error aligned with what Sierra currently does.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #6295 
* Composed of 
@ZUUL42 let me know if this removes ifpack from the list of offending packages, if not I'll look into it further
Locally tested using sems-gcc/8.3.0 compiler and appropriate warnings
=> Ifpack: fixing gcc 8.3.0 warnings for #6295

cmake/ctest/drivers/atdm/cts1/drivers/Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_dbg.sh, cmake/ctest/drivers/atdm/cts1/drivers/Trilinos-atdm-cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_opt.sh
These replace the old 'serrano' builds that that were removed (but now these builds support SPARC as well).
For all of the resaons to to promote these builds but not the cts1 intel-18 builds see [ATDV-281](https://sems-atlassian-srn.sandia.gov/browse/ATDV-281).
=> ATDM: Promote new cts1 intel-19 builds to ATDM CDAsh group (ATDV-281)

cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_clang-5.0.1_openmpi-1.10.2_serial_static_opt.sh, cmake/ctest/drivers/atdm/cee-rhel6/drivers/Trilinos-atdm-cee-rhel6_gnu-7.2.0_openmpi-1.10.2_serial_shared_opt.sh, cmake/std/atdm/cee-rhel6/all_supported_builds.sh, cmake/std/atdm/cee-rhel6/custom_builds.sh
For motivation, see [ATDV-237](https://sems-atlassian-srn.sandia.gov/browse/ATDV-237).
Actually, I did not fully remove these builds, I just did the following:
* Made the new openmpi-4.0.1 builds the default builds
* Removed openmpi-1.10.2 ctest -S driver scripts
* Removed openmpi-1.10.2 builds from cee-rhel6/all_suupported_builds.sh
This way, developers can still access these old builds if they want but they
will no longer be tested and they will no longer be loaded by developers
unless the specifically put 'openmpi-1.10.2' in the build name.
On the CEE RHEL7 machine 'ews000232' I did:
```
$ . cmake/std/atdm/load-env.sh cee-rhel6-default
Hostname 'ews00232' matches known ATDM host 'cee-rhel6' and system 'cee-rhel6'
Setting compiler and build options for build-name 'cee-rhel6-default' …
```
=> Remove cee-rhel6 openmpi-1.10.2 builds (ATDV-237)

packages/trilinoscouplings/examples/fenl/main.cpp, packages/trilinoscouplings/examples/fenl/main_ensemble.cpp, packages/trilinoscouplings/examples/fenl/main_pce.cpp, packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
These changes remove unused typefefs that generate warning when compiled with modern compilers.
Local build returns without offending warnings
=> TrilinosCouplings: removing warnings related to unused local typedefs

packages/ml/src/MLAPI/MLAPI_Workspace.cpp, packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp, packages/ml/src/Utils/ml_epetra_utils.cpp
@trilinos/ml 
@rstumin @csiefer2 can you double check that the output after the string modification still looks OK?
Remove warning from ML due to string buffer overflow and unsafe use of sprintf
* Closes 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@ZUUL42 feel free to let us know if this fixes the warning you observe in ML?
Local build returns without warning
=> ML: fixing warnings for GCC 8.3.0

packages/percept/src/percept/RunEnvironment.cpp
@trilinos/percept 
Removing warning for upcoming gcc/8.3.0 build
* Closes 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@ZUUL42 as usual let me know if this resolves warnings in percept
Local build returns without warnings
=> Percept: removing warning related to exception catching see #6295

packages/panzer/dof-mgr/test/fe_assembly/test_fe_assembly_HEX.hpp
Small change in the exception catching syntax to avoid gcc 8.3.0 warning
This removes a warning associated with exception catching when building with gcc/8.3.0
* Closes 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Local build shows that the warning goes away after switching to `const reference` instead of catch by value
=> Panzer: swap catch by value with catch by reference for #6295

packages/rol/example/PDE-OPT/TOOLS/solver_def.hpp
Only a tiny change to catch exception by const reference instead of by value.
@trilinos/rol 
This removes a warning issued by gcc/8.3.0
* Closes 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@dridzal can a ROL developer port this change to the ROL repo?
Local build returns warning free
=> ROL: removing warning due to exception catching by value see #6295

packages/rythmos/src/Rythmos_ThetaStepper_def.hpp
Removing unnecessary type definition in Rythmos_ThetaStepper_def that was already declared in Rythmos_ThetaStepper_decl
@trilinos/rythmos 
This removes a warning from gcc/8.3.0 build with -Werror for Sierra
* Closes 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Local build with gcc/8.3.0 returns warning free
=> Rythmos: removing shadowed type definition, see issue #6295

packages/thyra/core/src/support/operator_vector/client_support/Thyra_MultiVectorStdOpsTester_def.hpp
Removing an unnecessary typedef in Thyra_MultiVectorStdOpsTester_def.hpp as the typedef is already made in Thyra_MultiVectorStdOpsTester_decl.hpp
@trilinos/thyra 
This modification removes a warning in the gcc/8.3.0 build with -Werror for Sierra
* Closes 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@ZUUL42 one more warning fix
Local build with relevant flag and compiler returns without warning
=> Thyra: removing shadowing typedef, see issue #6295

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_decl.hpp
Removed unused field from FixedHashTable.
Field objectLabel_ was completely unused, and instigated a compiler warning about calling a host function from a host device function. 
```
warning: calling a __host__ function("std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string") from a __host__ __device__ function("Tpetra::Details::LocalMap<int, long long,  ::Kokkos::Device< ::Kokkos::Serial,  ::Kokkos::HostSpace> > ::~LocalMap") is not allowed
```
#5698
Tested on doom to ensure warning went away.
Tested on cee-lan to ensure tests still passed.
```
module load sems-env
module load sems-cmake/3.10.3
module load sems-gcc/7.3.0
module load sems-openmpi/1.10.1
module load sems-parmetis/4.0.3/64bit_parallel
module load …
```
=> Tpetra: removed unused field and CUDA compiler warning

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
TpetraCore_MatrixMatrix_UnitTests has a case which uses partially filled matrices (cdt_tce.mtx for example).
This causes C_estimate_nnz to overflow with A.getNodeNumEntries() less than B.getNodeNumRows().
Then Aest = 0 and Best = 0 overflow this line with result: 18446744073709551615
size_t nnzperrow = (size_t)(sqrt((double)Aest) + sqrt((double)Best) - 1);
Then the following line overflows again to coincidentally bring the guess back to 1.
nnzperrow *= nnzperrow;
The submitted changes will fix the overflow.
Fixes an overflow which is probably not causing any defects.
Overflow occurred for TpetraCore_MatrixMatrix_UnitTests.
=> Tpetra: Fix overflow for TpetraCore_MatrixMatrix_UnitTests

cmake/std/atdm/waterman/tweaks/Tweaks.cmake
See #6463 and okay from @eric-c-cyr in https://github.com/trilinos/Trilinos/issues/6463#issuecomment-571208719.
On 'waterman' I did:
```
$ cd /home/rabartl/Trilinos.base/BUILDS/WATERMAN/CHECKIN/
$ ./checkin-test-atdm.sh cuda --enable-packages=Teko --configure
...
PASSED (NOT READY TO PUSH): Trilinos: waterman11
Fri Jan 17 06:04:15 MST 2020
Enabled Packages: Teko
1) cuda => passed: configure-only passed => Not ready to push! (2.19 min)
```
and the configure output showed:
```
$ grep Teko_testdriver_tpetra_MPI_4 cuda/configure.out 
-- Setting default Teko_testdriver_tpetra_MPI_4_DISABLE=ON
Disable Teko_testdriver_tpetra_MPI_4 in all atdm 'waterman' builds (#6426)
-- Teko_testdriver_tpetra_MPI_4: NOT added test because …
```
=> Disable Teko_testdriver_tpetra_MPI_4 in all atdm 'waterman' builds (#6463)

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
In #6598, @mhoemmen recommended using index jj instead of index j to compute offsets to communication buffers.  This PR implements that change.
Configuration and testing is identical to #6598 
ested on linux with Tpetra tests and downstream packages Belos, Ifpack2, MueLu, Zoltan2, and Teko.
```
source ../cmake/std/atdm/load-env.sh  gnu-7.2.0-openmp-release-debug
cmake \
-GNinja \
-DMPI_EXEC=${MPI_EXEC} \
-DTrilinos_ENABLE_TESTS=ON  \
-DTrilinos_ENABLE_Anasazi=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
.. |& tee OUTPUT.CMAKE
```
```
100% tests passed, 0 tests …
```
=> Tpetra:  index change from #6598

cmake/std/sems/PullRequestGCC4.9.3TestingEnv.sh, cmake/std/sems/PullRequestGCC4.9.3TestingEnvSERIAL.sh, cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh, cmake/std/sems/PullRequestGCC7.3.0TestingEnv.sh, cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
sems-env has added recent versions of cmake and ninja_fortran.
Thus we can remove the dependency on atdm-env which can be good long term.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
I performed a local build after sourcing `PullRequestGCC7.2.0TestingEnv.sh` and was able to configure and build correctly.
=> Framework: updating the autotester env to remove dependency on atdm-env

packages/tpetra/core/src/Epetra_TsqrMessenger.cpp, packages/tpetra/core/src/Epetra_TsqrMessenger.hpp, packages/tpetra/core/src/Tpetra_ApplyOp.hpp, packages/tpetra/core/src/Tpetra_Assembly_Helpers.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_decl.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_fwd.hpp, packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp, packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp, packages/tpetra/core/src/Tpetra_BlockMultiVector_fwd.hpp, packages/tpetra/core/src/Tpetra_ConfigDefs.hpp, packages/tpetra/core/src/Tpetra_Core.cpp, packages/tpetra/core/src/Tpetra_Core.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_Behavior.cpp, packages/tpetra/core/src/Tpetra_Details_Behavior.hpp, packages/tpetra/core/src/Tpetra_Details_copyOffsets.hpp, packages/tpetra/core/test/Behavior/Behavior_Default.cpp
- `Tpetra::CrsMatrix::unpackAndCombine` is slow on GPUs for rows with many entries.
- We first need to define what a "row with many entries" is.
- Logical thing to do is to add a new function to `Tpetra::Details::Behavior`.
- Also, clean up some data structures in CrsGraph and CrsMatrix that are no longer needed.  This will help with the effort by reducing the number of cases to consider.
* Part of #6603
Requested by @vbrunini based on Aria GPU L2 Milestone.
Tested on Linux GCC 4.9.3.  Added new tests for existing and new Behavior methods.
=> Tpetra: Start work on #6603 (optimize CrsMatrix GPU unpack for long rows)

packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases/AnalyticPolynomialsMatchTests.cpp, packages/intrepid2/unit-test/Shared/Polylib/LegendreJacobiPolynomials/IntegratedJacobiTests.cpp, packages/intrepid2/unit-test/Shared/Polylib/LegendreJacobiPolynomials/IntegratedLegendreTests.cpp, packages/intrepid2/unit-test/Shared/Polylib/LegendreJacobiPolynomials/LegendreTests.cpp
Guarding various floating point comparisons in tests with checks whether both values are small.
Some tests fail on some platforms due to near-zero floating point comparisons.
* Closes #6246
=> Intrepid2: making tests more robust to architectural differences.

packages/amesos2/src/Amesos2_SolverCore_def.hpp, packages/ifpack2/src/Ifpack2_Relaxation_def.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Compiling Trilinos (i.e. explicitly Tpetra, Amesos2 and Ifpack2 ) for GPUs fails due to
some const_cast.
The problem is fixed by using & in const_cast with *this pointer.
=> Fix const_cast in Tpetra, Amesos and Ifpack2

packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
gauss_seidel_symbolic() and gauss_seidel_numeric() take a "symmetric"
flag, but this refers to graph (structural) symmetry and not symmetry
as in forward+backward sweeps, which is what Ifpack2 was passing in.
Fixes incorrect behavior - if KokkosKernels gauss seidel setup is promised a symmetric graph, the input graph won't be symmetrized before doing coloring. This could potentially lead to adjacent rows being given the same color.
Code owner
This is tested in Ifpack2_UnitTestRelaxation under MTSGS and ClusterMTSGS.
=> Ifpack2: pass correct "symmetric" flag to MTSGS setup

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
=> Tpetra: Correcting unecessary extraction of remotes for A matrix in Jacobi

packages/kokkos-kernels/src/sparse/KokkosSparse_spadd.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
- Making sure last entry of rowcount view is correct, if Crowmap on input
wasn't initialized (a bug affecting Tpetra!)
- Remove unnecessary view initializations (@csiefer2 measured this was taking up to 50% of the
spadd time on vortex!)
- Remove unnecessary fences
- Still have fences at the end of user-facing functions,
so that timers on host accurately reflect kernel times
- Use idiomatic deep_copy to scalar for accessing views, rather than
making a host mirror of a single-element subview
- Negligible impact, but avoid View reference count increments (pass-by-ref to functor ctor)
There will be a PR in kokkos-kernels develop as well, but these changes couldn't wait until the next snapshot after 3.0.
Code owner
This code is tested by MatrixMatrix_UnitTests in …
=> spadd bugfix, cleanup for performance

packages/kokkos-kernels/src/sparse/impl/KokkosSparse_cluster_gauss_seidel_impl.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_partitioning_impl.hpp
Make cluster MTSGS ignore remote columns  - fixes crash  
- Requests from @cgcgcg , @iyamazaki and @lucbv for using this with Exawind
- Code owner
Tested in Ifpack2_UnitTestRelaxation
=> Fix cluster MTSGS crashing with remote neighbors/columnss

packages/anasazi/src/AnasaziMVOPTester.hpp, packages/belos/tpetra/test/BlockGmres/test_bl_gmres_hb_df.cpp, packages/kokkos-kernels/src/Kokkos_InnerProductSpaceTraits.hpp, packages/kokkos-kernels/src/blas/KokkosBlas1_dot.hpp, packages/kokkos-kernels/src/blas/impl/KokkosBlas1_dot_impl.hpp, packages/teuchos/numerics/src/Teuchos_MatrixMarket_generic.hpp, packages/tpetra/core/test/Block/BlockCrsMatrix.cpp, packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp, packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
@trilinos/tpetra @trilinos/anasazi 
1. Make Trilinos' tests build and pass with Mac Clang, so we can use it as a development platform.
2. Prevent spurious test failures with Scalar=`float` and `complex<float>`, by improving dot product accuracy.
* Closes #6611, #6612, #6633 
* Matching kokkos-kernels issue: https://github.com/kokkos/kokkos-kernels/issues/574
* Matching kokkos-kernels PR: https://github.com/kokkos/kokkos-kernels/pull/575
Tested on Mac Clang with the following version information:
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
```
Set the following build options:
```
-D Trilinos_ENABLE_COMPLEX_DOUBLE:BOOL=ON
-D Trilinos_ENABLE_COMPLEX_FLOAT:BOOL=ON
-D Trilinos_ENABLE_FLOAT:BOOL=ON
```
=> Tpetra,Anasazi: Fix #6611, #6612, & #6633

packages/sacado/src/Sacado_CacheFad_Ops.hpp, packages/sacado/src/Sacado_ELRCacheFad_Ops.hpp, packages/sacado/src/Sacado_ELRFad_Ops.hpp, packages/sacado/src/Sacado_Fad_Ops.hpp, packages/sacado/src/Sacado_Fad_SimpleFadOps.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp
See issue #6632.  Replace d(tanh(x))/dx = sech^2(x) with 1-tanh^2(x).
=> Sacado:  Use more overflow-safe implementation of d(tanh(x))/dx.

packages/tempus/src/Tempus_StepperBDF2_decl.hpp, packages/tempus/src/Tempus_StepperBackwardEuler_decl.hpp, packages/tempus/src/Tempus_StepperDIRK_decl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_Partition_decl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_decl.hpp, packages/tempus/src/Tempus_StepperImplicit_decl.hpp, packages/tempus/src/Tempus_StepperTrapezoidal_decl.hpp
No code changes, just new doxygen.  The iteration matrix, W,
for all the steppers, except IMEX-RK and IMEX-RK Partition,
have been documented.
Closes #6637 
Clearly document what is the iteration matrix and its expression for the first-order implicit ODEs.
Doxygen builds correctly.
=> Tempus: Initial Documentation for Iteration Matrix.

packages/shylu/shylu_node/tacho/src/Tacho_TaskFunctor_FactorizeChol.hpp, packages/shylu/shylu_node/tacho/src/Tacho_TaskFunctor_FactorizeCholPanel.hpp, packages/shylu/shylu_node/tacho/src/Tacho_TaskFunctor_SolveLowerChol.hpp, packages/shylu/shylu_node/tacho/src/Tacho_TaskFunctor_SolveUpperChol.hpp
On Cuda tasking, it seems to be dangerous to use a recursive function as kokkos tasking on cuda uses fixed size of stack size. With a recursive function, it causes illegal memory access error in a random place. This PR disable the recursive function on the CUDA active space.
=> Tacho - disable to use a recursive function

cmake/std/unittests/TestPullRequestLinuxDriverMerge.py, cmake/std/unittests/TestPullRequestLinuxDriverTest.py
Basically if I don't then running from
inside the unittest directory will fail.
=> Added os.path.abspath to find the full path to the tested file

cmake/std/sems/checkin-test-sems.sh
When the Claps package was removed in #4864, it actually broke the usage of
the checkin-test-sems.sh script for people that were using that script.  That
is because the file local-checkin-test-defaults.py was already written that
had Claps listed in --disabled-packages in that file.  This broke the sync of
ROL for a while to their subproject repo.
Given the current Trilinos GitHub PR testing system and the reduced usage of
the checkin-test.py script, there is no longer a need for adding an argument
like --disabled-packages to list out packages like PyTrilinos or TriKota.
These were listed many years ago so thaty if someone had edits in one of these
packages, then it would bascially bring their build down because packages like
PyTrilinos and TriKota would almost never be able to build. …
=> Remove --disable-packages argument

packages/tpetra/core/test/CrsGraph/CrsGraph_StaticImportExport.cpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_StaticImportExport.cpp
@mhoemmen reports that certain import/export operations fail during the copy and permute phase.  This PR is an attempt to fix the problem.
=> Tpetra: Fix export/import to local graph/matrix

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp, packages/tpetra/core/src/Tpetra_transform_MultiVector.hpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp, packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp, packages/tpetra/core/test/MultiVector/Transform.cpp
These changes allow all Tpetra tests in serial to pass with
env variable CUDA_LAUNCH_BLOCKING=0, except for these utility
tests which specificaly check CUDA_LAUNCH_BLOCKING to be on.
They have not been changed and will still fail as expected:
- 	 TpetraCore_Core_initialize_where_tpetra_initializes_kokkos
- 	 TpetraCore_Core_ScopeGuard_where_tpetra_initializes_kokkos
- 	 TpetraCore_Core_initialize_where_user_initializes_kokkos
- 	 TpetraCore_Core_ScopeGuard_where_user_initializes_kokkos
- 	 TpetraCore_Map_no_warn_on_pre_finalize_destruction_issue_2372
One exception is TpetraCore_Transform which has an issue caused by the setup for  withLocalAccess. A planned fix is expected to fix the test to also work for CUDA_LAUNCH_BLOCKING=0 but that will be handled separately.
Parallel tests which …
=> Tpetra: Resolve CUDA_LAUNCH_BLOCKING requirements for serial

packages/kokkos-kernels/src/common/KokkosKernels_Sorting.hpp, packages/kokkos-kernels/test_common/Test_Common_Sorting.hpp, packages/kokkos-kernels/unit_test/CMakeLists.txt, packages/kokkos-kernels/unit_test/cuda/Test_Cuda_Common_Sorting.cpp, packages/kokkos-kernels/unit_test/openmp/Test_OpenMP_Common_Sorting.cpp, packages/kokkos-kernels/unit_test/serial/Test_Serial_Common_Sorting.cpp, packages/kokkos-kernels/unit_test/threads/Test_Threads_Common_Sorting.cpp
- Requested by @mhoemmen 
- Files are identical to those that will be pulled in by the 3.0
snapshot, so they can be safely clobbered without affecting any usage in Tpetra
- Unit tests are included
- Currently not used anywhere outside kokkos-kernels
@mhoemmen needs a fast team-parallel sort (I believe for CRS pack/unpack)
This would also likely improve ``sortCrsEntries()`` performance on CUDA, both the graph (just sort) and matrix (sort and permute values) versions.
Feature request by Tpetra, in order to unpack long rows more efficiently (which was requested by Sierra)
Features are tested by kokkos-kernels unit tests test_common_x where x is serial/cuda/threads/openmp.
How I tested: built Trilinos locally with CUDA (10.1) and OpenMP enabled, …
=> Patching in team-level bitonic sort

packages/teuchos/core/src/Teuchos_RCP.hpp, packages/teuchos/core/src/Teuchos_RCPDecl.hpp, packages/teuchos/core/test/MemoryManagement/RCP_UnitTests.cpp
This PR adds an `operator bool()` to the `Teuchos::RCP` class.
* Closes #6608 
Since the `Teuchos::RCP` is so pervasive, and an improper `operator bool()` can interrupt the type system, I will defer to @bartlettroscoe to ensure proper testing.
=> Teuchos: Add operator bool() to Teuchos::RCP

packages/tpetra/core/src/Tpetra_transform_MultiVector.hpp, packages/tpetra/core/src/Tpetra_withLocalAccess.hpp, packages/tpetra/core/src/Tpetra_withLocalAccess_MultiVector.hpp, packages/tpetra/core/test/MultiVector/WithLocalAccess.cpp, packages/tpetra/core/test/Utils/withLocalAccess_generic.cpp
Applications want to run with `CUDA_LAUNCH_BLOCKING` unset.  PR https://github.com/trilinos/Trilinos/pull/6617 showed that `Tpetra::withLocalAccess` could not distinguish between accessing on `CudaUVMSpace` at host, and accessing on `CudaUVMSpace` at device.  This commit should fix that.
* Follows #6617 
SPARC already runs with `CUDA_LAUNCH_BLOCKING` unset.
I haven't tested CUDA yet; I just want to share this with @MicheldeMessieres and @kddevin .  I've tested on a Mac laptop.
=> Tpetra: Refactor withLocalAccess so we don't need CUDA_LAUNCH_BLOCKING or extra fences

cmake/ProjectCompilerPostConfig.cmake
@kokkos
Allows C++11 checks to pass for GCC4.9 and other compilers
=> Patch C++11 flag checks for GCC4

packages/moertel/src/mortar/Moertel_Tolerances.hpp, packages/moertel/src/mortar/mrtr_manager.H, packages/moertel/src/mortar/mrtr_overlap_Def.hpp
@trilinos/moertel
The motivation behind this PR is to:
- Create a function that return a map which links the Langrange multipliers and their associated primal dofs.
- Replace the perpendicular test with a relative one to not have an influence of the mesh size on the perpendicular test.
This PR is the second PR of a sequence of PRs intended to include the software developments of my thesis in Trilinos.
The first one (#6642 ) is independent of Moertel and not required for this PR.
**This PR is a duplicate of PR #6643 which has been closed due to a testing issue related to git.**
This branch has been tested on the Blake system.
=> Moertel: Small improvements linked to the perpendicular test (bis)

cmake/std/PullRequestLinuxCommonTestingSettings.cmake
The discussion on thie test was done in #3585 and
is properly labeled as having a disabled test.
This test fails intermittently and after significant discussion (see #3585) we are turning it off for all PR testing.
I used the replication instructions in the wiki to set up (configure and generate) 3 of the PR builds (GCC 7.2, Intel 17, and GCC 4.8.4) and confirmed that in each one the test is not put into the relevant CTestTestfile.cmake.
=> This turns off the Anasazi_Epetra_OrthoManagerGenTester_0_MPI_4 test

packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_def.hpp, packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_decl.hpp, packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp, packages/muelu/test/unit_tests/RegionVector.cpp
This is a first cut that performs reasonably well, the idea is to look at interpolation coefficient generated for each fine point.
If the coefficients are smaller than a given tolerance (1e-6), they are dropped.
This results in much sparser coarse grid as well as smaller P and R matrices.
If we want to keep this idea around we should rewritte the structured aggregation factory to obtain the correct graph directly instead of recomputing it in the prolongator factory.
* Closes #6681 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
The new algorithm has been tested locally, all MueLu examples and tests are passing.
Also performed a larger simulation using 3D elasticity with 100x100x100 nodes mesh which resulted in good performance.
=> MueLu: adding thresholding of the interpolation values in GeometricInterpolationPFactory, see issue #6681

cmake/std/atdm/sems-rhel7/environment.sh, cmake/std/atdm/utils/set_build_options.sh
Changed clang to be clang7 on rhel7 machines.  This gives us openmp
=> Made default clang7, tested with openmp and empire

packages/moertel/src/mortar/mrtr_manager.H, packages/moertel/src/mortar/mrtr_overlap_Def.hpp
Well this fixes the auto-tester gcc/7.2.0 build
* Closes #6698 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
I'm not sure maybe @bartlettroscoe 
Did a local build using the gcc/7.2.0 environment with -Werror, this builds fine.
=> Moertel: fix warnings due to signed/unsigned comparison, see issue #6698

packages/tpetra/core/example/advanced/Benchmarks/CMakeLists.txt, packages/tpetra/core/example/advanced/Benchmarks/CrsMatrixMatVec.cpp
This would just make life a little easier when I want to compare the performance of the matvec on different platforms. Also it seems somewhat surprising that we have a test for BlockCrsMatrix matvec but not for the regular CrsMatrix.
* Closes #6692 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
N/A
I have a local build and test that pass fine on rhel7 with gcc/7.2.0 auto-tester config
=> Tpetra: adding benchmark for CrsMatrix::apply, see issue #6692

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_crsUtils.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp, packages/tpetra/core/test/Utils/TpetraUtils_crsUtils.cpp
Add verbose debugging output to CrsGraph and CrsMatrix, to help diagnose and fix #6663 and #6648 in general.
Tested TpetraCore tests locally on my Mac laptop with Clang and OpenMPI, with `TPETRA_VERBOSE` both set and unset.
=> Tpetra::Crs{Graph,Matrix}: Add verbose debugging output for memory allocations 

packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.h, packages/seacas/libraries/ioss/src/main/CMakeLists.txt
Added a `Descriptor_t` node under the `GridConnectivity1_to1_t` node during decomposition
if the GridConnectivity node is created as the result of parallel decomposition (connectivity from one processor to another).  This is needed for periodic models in which, for example, the K_max face is connected to the K_min face.  The name of the Descriptor node is 'Decomp' and the value is (currently) unused.
Modified fpp output of Iocgns_DatabaseIO to add this descriptor to all models.  Models without this descriptor that worked previous to the change will continue to work post-change; it is only required for periodic models in which a zone is adjacent to itself.
A test is being developed with a smaller model to ensure that the behavior does not regress; it will be added at a …
=> IOSS: cgns - fix handling of periodic single-block models in parallel

cmake/ctest/drivers/atdm/ats2/drivers/Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_opt.sh
This build has been 100% clean last 3 days.
See [this query](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-01-26&end=2020-02-03&filtercount=1&showfilters=1&field1=buildname&compare1=61&value1=Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_opt).
=> Promoting ats2+gnu+opt build which is 100% clean (CDOFA-27)

cmake/ctest/drivers/atdm/ats2/drivers/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg.sh, cmake/ctest/drivers/atdm/ats2/drivers/Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg.sh, cmake/std/atdm/ats2/tweaks/Tweaks.cmake
This is just part of the process to get these builds cleaned up and promoted so that we can maintain them.
See the individual commits for details.
=> ATDM ATS-2 cleanup and promote some builds to 'Specialized' (CDOFA-72)

packages/trilinoscouplings/src/ml/NonlinML/nlnml_nonlinearlevel.cpp
@trilinos/nonlinML
Avoid some compiler warnings. It looks pretty clear that the scopes were intended to be a little different.
Compiling still works and avoids compiler warnings.
=> NonlinML: Fix some scopes in nlnml_nonlinearlevel.cpp

packages/shylu/shylu_node/tacho/unit-test/Tacho_TestCrsMatrixBase.hpp
According to #3276, there is a random test failure from the matrix market interface in Tacho. The apparent error message is "view bounds error". The matrix market code is sequential and run on host. I don't understand why this happens randomly as the code and algorithm are deterministic. I was not able to reproduce this error on openmp nor cuda.  I would like to disable this test for better PR testing. The matrix market code in Tacho is to interface sparse matrices for evaluations, which won't affect the core functionalities of Tacho. 
#3276
=> Tacho - disable matrix market reader/writer test to improve PR test stability

cmake/std/atdm/mutrino/environment.sh
This was requested by EMPIRE developer Nicole Lemaster Slattengren.
On 'mutrino', I did:
```
$ cd /lscratch1/rabartl/MUTRINO/Trilinos.base/BUILDS/CTEST_S/
$  env Trilinos_PACKAGES=Kokkos ./ctest-s-local-test-driver.sh intel-opt-openmp-HSW
```
The file
* Trilinos-atdm-mutrino-intel-opt-openmp-HSW/smart-jenkins-driver.out
showed:
```
Currently Loaded Modulefiles:
...
33) cmake/3.14.6
cmake in path:
/usr/projects/hpcsoft/cle6.0/common/cmake/3.14.6/bin/cmake
ninja in path:
/projects/netpub/atdm/ninja-1.8.2/bin/ninja
```
That posted to CDash:
* [](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=5215660) (passed=???)
and the [configure output](https://testing-dev.sandia.gov/cdash/viewConfigure.php?buildid=5215660) showed:
```
-- CMAKE_VERSION='3.14.6'
```
Good enough …
=> ATDM mutrino: switch from camke 3.11.4 to 3.14.6

cmake/std/atdm/ATDMDisables.cmake
* Disable ctest DISABLED test KokkosContainers_PerformanceTest_Cuda: This just
clutters up CDash and our CDash summary emails.
* Only disable OpenMP tests in OpenMP builds
On RHEL6 I ran:
```
$ ./checkin-test-atdm.sh gnu-openmp-dbg --enable-packages=Kokkos,KokkosKernels --configure
```
which showed:
```
$ grep "NOT added" configure.out  | grep DISABLE
-- KokkosCore_UnitTest_Serial_MPI_1: NOT added test because KokkosCore_UnitTest_Serial_MPI_1_DISABLE='ON'!
-- KokkosCore_UnitTest_OpenMP_MPI_1: NOT added test because KokkosCore_UnitTest_OpenMP_MPI_1_DISABLE='ON'!
-- KokkosContainers_PerformanceTest_OpenMP: NOT added test because KokkosContainers_PerformanceTest_OpenMP_DISABLE='ON'!
-- KokkosKernels_blas_openmp_MPI_1: NOT added test because KokkosKernels_blas_openmp_MPI_1_DISABLE='ON'!
-- …
```
=> ATDM: More cleanup after Kokkos 2.99 upgrade

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
This PR adds a check for the sync state of 'exports', and synchronizes
if necessary. This prevents issues where the reallocDualViewIfNeeded
call does not result in a resize of 'exports', and thus not clearing the
modify flags before being set in anticipation of computation later in
the routine.
Albany builds of Trilinos detected dual view errors, as reported in SNLComputation/Albany#555, following the kokkos 2.9.99 release.
These errors occurred in the `Tpetra::MultiVector::packAndPrepare` routine in cases where the `exports` variable is not resized during a call to `reallocDualViewIfNeeded` which also resulted in the modify flags not being reset. This causes problems later when setting the modify flags in preparation for computation later in the routine.
This PR add a …
=> tpetra: Add sync check in MV packAndPrepare

packages/kokkos-kernels/src/common/KokkosKernels_IOUtils.hpp, packages/kokkos-kernels/src/common/KokkosKernels_Utils.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_symbolic.hpp, packages/kokkos-kernels/unit_test/sparse/Test_Sparse_spgemm.hpp
Fixes SPGEMM for input with zero rows. This fixes the same problem as #5680 did before it got clobbered by the promotion, but it fixes it for multiple SPGEMM algorithms. Tests this case now. See https://github.com/kokkos/kokkos-kernels/pull/599 for more info.
EMPIRE needed this fixed because it broke many tests
Added an SPGEMM test for zero rows. This replicated the failure that was seen in EMPIRE tests, and this PR fixes it.
=> Fix kk spgemm zero row

cmake/std/atdm/ats2/environment.sh
This was requested by Matt B. for EMPIRE.  When we support other ats2 machines
like 'lassen' and 'rzansel', we will need to install ninja there too and point
to it there too.
On 'vortex' I did:
```
$ env Trilinos_PACKAGES=Kokkos,Teuchos \
./ctest-s-local-test-driver.sh \
ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg
***
***
Hostname 'vortex60' matches known ATDM host 'vortex' and system 'ats2'
Using ats2 compiler stack GNU-7.3.1_SPMPI-2019.06.24 to build DEBUG code with Kokkos node type SERIAL
Lmod is automatically replacing "xl/2019.12.23" with "gcc/7.3.1".
Due to MODULEPATH changes, the …
```
=> ATDM: ats2: switch to ninja (CDOFA-72)

packages/tpetra/core/src/Tpetra_for_each_MultiVector.hpp, packages/tpetra/core/src/Tpetra_transform_MultiVector.hpp
Changes the transform methods to pass the user specified execution
space to withLocalAccess.
This will then fence the reading of the source data which fixes
the test to run with CUDA_LAUNCH_BLOCKING unset.
Resolves last Tpetra serial test for CUDA_LAUNCH_BLOCKING unset.
Follows #6662 and #6617 
Tested on Cuda with CUDA_LAUNCH_BLOCKING unset.
=> Tpetra: Fix Transform test for CUDA_LAUNCH_BLOCKING unset

packages/PyTrilinos/src/Isorropia.Epetra.i
I fixed PyTrilinos to work with SWIG 4.0, while trying to maintain backward compatibility with SWIG 3.0.  I introduced one syntax error, accessible when the SWIG version is less than 4.0, which this fixes.
* Related to #6607
=> PyTrilinos: Fix syntax error for SWIG 3

packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp
Part of issue #6781
Tested that this resolved failing Panzer tests in host build with `-DKokkos_ENABLE_DEBUG_DUALVIEW_MODIFY_CHECK=ON`
=> panzer dof-mgr: add needed check and sync for MV dual view

packages/panzer/disc-fe/src/lof/Panzer_LinearObjFactory.hpp
Removed the getGlobalIndexer() method because Panzer is now differentiating range and domain global indexers.  The mitigation is to call getRangeGlobalIndexer() instead.
* Part of #6655
```bash
cmake \
-GNinja \
-DTrilinos_ENABLE_Epetra=ON \
-DTrilinos_ENABLE_Panzer=ON \
-DTrilinos_ENABLE_STK=ON \
-DTrilinos_ENABLE_Percept=ON \ …
```
=> Panzer: Removed Deprecated getGlobalIndexer()

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
MultiVectorFactory with default template arguments was used
to create a coordinates MultiVector, causing type mismatch errror.
Fixes build errors caused by using MultiVectorFactory (with default template arguments) to construct a multivector of coordinates, when the coordinate scalar type differs from the default scalar.
This only fixes the build; the RegionMG tests still fail with complex.
=> MueLu: fix compilation of RegionMG w/complex

packages/zoltan2/example/block/kokkosBlock.cpp, packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp, packages/zoltan2/src/algorithms/partition/Zoltan2_TaskMapping.hpp, packages/zoltan2/src/input/Zoltan2_BasicVectorAdapter.hpp, packages/zoltan2/src/input/Zoltan2_MeshAdapter.hpp, packages/zoltan2/test/unit/input/BasicKokkosIdentifierInput.cpp
@kddevin Apart from one change to make progress on #6422, this PR is not associated with any failures. It fixes various issues I had noticed while working on other MJ bugs over the past few weeks.
Changed doPostsAndWaits to get host ptrs and not uvm space ptrs. This was not causing any issue I am aware of but it seems it could cause an issue for some MPI implementations.
Changed deccltype declarations to use auto which cleans up code.
Removes a pointless #ifdef which can never do anything. This was leftover from an earlier refactor.
Removes a hack on one of the kernels to adjust team count for small test sizes. This was an issue a while back but it seems fine now. So perhaps it was caused by another bug (now fixed in MJ) or something was repaired in Kokkos.
Fixed an …
=> Zoltan2 mj clean up

cmake/std/atdm/ride/tweaks/Tweaks.cmake, cmake/std/atdm/waterman/tweaks/Tweaks.cmake
These started timing out every after Kokkos 2.99 upgrade starting 2020/02/04 but were timing out randomly before that as documented in #6464.
On 'ride' and 'waterman' I ran:
```
$ ./checkin-test-atdm.sh cuda-dbg --enable-packages=KokkosKernels --configure
```
and on both it showed:
```
$ grep "NOT added" configure.out 
-- KokkosKernels_blas_serial_MPI_1: NOT added test because KokkosKernels_blas_serial_MPI_1_DISABLE='ON'!
-- KokkosKernels_sparse_serial_MPI_1: NOT added test because KokkosKernels_sparse_serial_MPI_1_DISABLE='ON'!
```
=> Disable timing out KokkosKernels_sparse_serial_MPI_1 in pure debug builds on 'ride' and 'waterman' (#6464)

packages/kokkos-kernels/src/common/KokkosKernels_Utils.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_speed.hpp
Permanent fix to scalar_t memory alignment in scratch views.
Affected KKMEM and SPEED algorithms.
Use new Utils function "alignPtr" that adds a few bytes to an
arbitrary non-void pointer (char*, nnz_lno_t*, etc.) to
correctly align to another type T*.
Mirror of https://github.com/kokkos/kokkos-kernels/pull/602
In SPGEMM numeric phase, fixes incorrect alignment of ``scalar_t`` arrays in scratch buffers. On CPU this usually just degrades performance but on CUDA alignment is required and misalignment causes kernels to crash. This was observed with ``scalar_t = Kokkos::complex<double>`` where the complex was 16 byte aligned, but in principle the error could happen with ``scalar_t=double`` too.
This is tested in the SPGEMM unit tests in kokkos-kernels, and in …
=> kokkos-kernels: spgemm: fix scalar alignment

cmake/std/atdm/ats2/tweaks/Tweaks.cmake
Just a very expensive test in a pure debug build on the Power systems for some
reason.  Go figure.  See #6464 
On 'vortex' I did:
```
ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg \
--enable-packages=KokkosKernels --configure
...
1) ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg => passed: configure-only passed => Not ready to push! (0.38 min)
```
and the configure output showed:
```
[rabartl@vortex60 ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg]$ grep "NOT added" configure.out 
-- KokkosKernels_blas_serial_MPI_1: NOT added test because KokkosKernels_blas_serial_MPI_1_DISABLE='ON'!
-- KokkosKernels_sparse_serial_MPI_1: NOT added test because KokkosKernels_sparse_serial_MPI_1_DISABLE='ON'!
```
=> ATDM: ats2: Disable KokkosKernels_sparse_serial_MPI_1 for ats2 debug debug builds (#6464)

packages/tempus/src/Tempus_IntegratorBasic_decl.hpp, packages/tempus/src/Tempus_StepperSubcycling_decl.hpp, packages/tempus/src/Tempus_StepperSubcycling_impl.hpp, packages/tempus/unit_test/Tempus_UnitTest_Subcycling.cpp
The maxTimeStep was being changed within the
Stepper::Subcycling::takeStep(), which should not occur.
Removed the offending call, and added code and unit test
to ensure it does not happen again.
Passes all tests on my Mac.
Closes #6811 
=> Tempus: Fix for maxTimeStep in Subcycling.

cmake/std/atdm/ats2/tweaks/Tweaks.cmake
There is either some problem with binutils or with Teuchos code that uses
binutils to interpret the stack trace info.  We can fix this later if this is
really needed. 
See #6821 
On 'vortex' I did:
```
ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg \
--enable-packages=Teuchos --configure
...
PASSED (NOT READY TO PUSH): Trilinos: vortex60
Wed Feb 12 13:02:35 MST 2020
Enabled Packages: Teuchos
1) ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg => passed: configure-only passed => Not ready to push! (0.45 min)
REQUESTED ACTIONS: PASSED
```
and it showed:
```
[rabartl@vortex60 ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg]$ grep "TeuchosCore_show_stack" configure.out 
-- Setting default …
```
=> ATDM: ats2: Disable TeuchosCore_show_stack in debug builds (#6821)

packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Fixes compile issues if Kokkos::Serial not available.
Fixes inconsistent use of Kokkos::Serial and Kokkos::HostSpace.
#6816
Cuda on white
OpenMP on white with Kokkos::Serial enabled
OpenMP on white with Kokkos::Serial disabled
=> Zoltan2: Use HostSpace not Serial (#6816)

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
- Improving documentation
- First steps to reduce timings for scaling interface-related matrix entries in the region matrices. Main costs still have to be addressed.
- Minor changes to loop bounds in region MG Gauss-Seidel
* Follows PR #6694
This is experimental code, that is not used by any app or other users.
- Build passes
- `ctest -R MueLu_Structured_Region` passes
- `ctest -R UnitTestsRegion` passes
=> MueLu: several fixes to region MG

cmake/ctest/drivers/atdm/ats2/local-driver.sh, cmake/std/atdm/ats2/trilinos_jsrun, cmake/std/atdm/ats2/trilinos_jsrun_test_me.sh
This is a follow on to PR #6724 
This PR forces the wrapper to print the full jsrun command to stdout so one can easily replicate a run or see exactly what the command was.
This change was tested using provided test script.
@e10harvey @bartlettroscoe
=> Force jsrun wrapper to print the full cmd export ECHO_CMD=0 to disable

packages/kokkos/core/src/Kokkos_Core.hpp, packages/kokkos/core/src/impl/Kokkos_Core.cpp
As requested in https://github.com/kokkos/kokkos/issues/2757.
=> Cherry-pick Kokkos #2729 - Make Kokkos::initialize(/* no args */) honor environment variables

packages/rtop/src/support/RTOpPack_SPMD_apply_op.cpp, packages/rtop/src/support/RTOpPack_SPMD_apply_op_decl.hpp
@trilinos/rtop
Removing deprecated global variable show spmd_apply_op_dump.
* Part of #6655
```bash
cmake \
-GNinja \
-DTrilinos_ENABLE_Epetra=ON \
-DTrilinos_ENABLE_Panzer=ON \
-DTrilinos_ENABLE_STK=ON \
-DTrilinos_ENABLE_Percept=ON \
-DTrilinos_ENABLE_Intrepid=ON \
-DTrilinos_ENABLE_Zoltan2=ON \
-DTrilinos_ENABLE_Piro=ON \ …
```
=> RTOp: Remove Deprecated show_spmd_apply_op_dump

cmake/std/sems/PullRequestGCC8.3.0TestingEnv.sh, packages/muelu/src/Misc/MueLu_AggregateQualityEstimateFactory_def.hpp
I am also changing slightly the modules loaded by the gcc-8.3.0 env script
These changes will should allow to add "-Werror" flag to MueLu for the gcc/8.3.0 build
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #6295
* Composed of 
@ZUUL42 when this merges can you check that it fixes the last issue in MueLu?
It would be nice to take care of it quickly to avoid having a new warning creep in.
I performed local tests with the gcc/8.3.0 environment and the -Werror manually added to MueLu's compiler flags
=> MueLu: fix shadow warning for GCC-8.3.0 build to enable -Werror

packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp, packages/stokhos/src/CMakeLists.txt, packages/stokhos/src/sacado/kokkos/vector/KokkosBlas3_gemm_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/KokkosBlas_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/Teuchos_BLAS_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/belos/Belos_DGKS_OrthoManager_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/belos/Belos_ICGS_OrthoManager_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/belos/Belos_IMGS_OrthoManager_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/belos/Belos_PseudoBlockGmresIter_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/belos/Belos_StatusTest_GenResNorm_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/belos/Belos_StatusTest_ImpResNorm_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/tpetra/Stokhos_Tpetra_MP_Vector.hpp, packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp
The motivation behind this PR is to add partial template specializations of Belos classes for ensemble types to implement the ensemble GMRES without the ensemble reduction.
This implementation takes care of the occurrences of the control-flow divergence in the ensemble GMRES without ensemble reduction.
For instance, different samples of a same ensemble can face lucky breakdown at different iterations of the GMRES without generating NaN.
This PR includes a template specialization of the GEMM fallback function of Kokkoskernels for ensemble types in order to use the GEMV if applicable.
This has three reasons:
- A GEMM implementation is typically less optimal than a GEMV implementation when applicable. In the case of the GEMV, we cannot reuse data from the matrix as it is …
=> Stokhos: Add the ensemble GMRES without the ensemble reduction

cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake
Set WError for @trilinos/muelu in PR test build GCC 8.3.0
This is a continuation of PR #6824 and moves Issue #6295 forward.
This has been tested by running the changes through the PR build it will affect. [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic166&field2=buildname&compare2=61&value2=PR-gcc_8.3_werror_muelu_on-test-Trilinos_pullrequest_gcc_8.3.0-79&field3=buildstamp&compare3=61&value3=20200218-1633-Experimental)
=> Set WError for MueLu in GCC 8.3.0 PR build

packages/kokkos-kernels/src/sparse/impl/KokkosSparse_trsv_impl.hpp
addresses issue kokkos/kokkos-kernels#607 reported by @mwglass
replace /= compound assignment operators
Workaround intel/19.0.4 internal compiler error
This patch mirrors PR kokkos/kokkos-kernels#608
Reproduced error (kokkos-kernels standalone build) and tested fixes with intel/19.0.4 and sierra-devel module environment on Mutrino to confirm the fix.
=> trsv: workaround intel/19.0.4 interal compiler error

packages/muelu/adapters/belos/BelosXpetraStatusTestGenResSubNorm.hpp, packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp
The motivation behind this PR is to resolve issues #6765 and #6082.
Issue #6082 is resolved by correcting the typo.
Issue #6765 is resolved by computing the static size required to store the merged blocked crs matrix.
To do so, the implementation relies on the member function getNumEntriesInLocalRow which was not fully implemented yet.
The provided implementation of `getNumEntriesInLocalRow` relies on `getMapIndexForGID` to access the block id of a global id.
Therefore, this PR provides:
- An implementation of `getNumEntriesInLocalRow` and `getNumEntriesInGlobalRow` which supports both Thyra and Xpetra mode.
- The computation of the required memory which has to be allocated to store the merged blocked crs matrix.
This branch has been tested on the Blake …
=> Xpetra: PR to close #6082 and #6765

commonTools/framework/clean_workspace/clean_workspace.py, commonTools/framework/clean_workspace/unittests/test_clean_workspace.py
@dridzal had an issue with the gcc 7.2.0 builds over
the weekend where the clean_workspace script triggered
on machine that had never built that variant. This
happened because we rebuilt the cloud node on Thursday.
This just adds an "if isdir():" around the rmtree call
and a second test  for that branch.
This code keeps the build size from becoming a serious impact on available disk space. Stability of the testing harness is important for our development teams.
This commit includes it's own unit tests and a new test was added for this change.
=> Verify that the directory exists before cleaning

packages/tpetra/core/src/Tpetra_DistObject_def.hpp, packages/tpetra/core/src/Tpetra_Distributor.cpp, packages/tpetra/core/src/Tpetra_Map_decl.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp, packages/tpetra/core/src/Tpetra_Util.cpp, packages/tpetra/core/src/Tpetra_Util.hpp, packages/tpetra/core/test/Utils/CMakeLists.txt, packages/tpetra/core/test/Utils/createPrefix.cpp, packages/xpetra/test/BlockedMultiVector/BlockedMultiVector_UnitTests.cpp, packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp, packages/xpetra/test/Map/Map_UnitTests.cpp
@trilinos/tpetra @trilinos/xpetra 
1. Add more verbose output to Map.
2. Make more of Map's debug checks controlled by the run-time value of `Behavior::debug("Map")`, rather than by the `HAVE_TPETRA_DEBUG` macro.
3. Reduce code duplication and improve testing by factoring out `Tpetra::Details::createPrefix` function (with overloads); add tests for all the overloads.
4. Fix Xpetra test build errors with `Scalar=complex<float>`.
5. Fix Xpetra Map test so that it doesn't assume that `HAVE_TPETRA_DEBUG` specifies whether Map does debug checking.
Sierra TF is moving towards production-ization of Tpetra-based solvers.  This means we'll need more debugging.  We've seen errors in MueLu setup, so we want more verbose debug output for those parts of Tpetra that matter for MueLu setup, like Map and …
=> Tpetra: Factor out createPrefix; add verbose output to Map; fix Xpetra build errors

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp, packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
- Remove references to DynamicProfile from CrsGraph and CrsMatrix documentation
- Remove redundant initialization
- Remove a function that PR #6845 made redundant
- Make more CrsMatrix debug checks a run-time choice
- De-template some CrsMatrix methods that didn't need to be templated
Y'all thought it was a good idea to remove DynamicProfile from CrsGraph and CrsMatrix; this commit finishes the process by updating the documentation.
* Related to #4701, #4755, #6655 
Mac Clang, OpenMPI.
=> Tpetra: Remove "DynamicProfile" mentions from Doxygen documentation

packages/tpetra/core/test/Behavior/Behavior_Default.cpp
This PR removes comparisons of default behavior values with acquired ones for behaviors that are controlled by both CMake options and environment variables.
Trilinos testing is now setting environment variables explicitly, and those settings may differ from the configure-time values of the variables.  Thus, tests that compare the run-time settings with the configure-time settings no longer make sense and may fail.  #6883  #6796 
* Closes #6883 
* Blocks 
* Follows 
* Precedes 
* Related to #6796 #6881 
* Part of 
* Composed of 
@bartlettroscoe Let me know if you continue to see problems with this test.
cee-lan with TPETRA_ASSUME_CUDA_AWARE_MPI = 0 and 1, and TPETRA_DEBUG = 0 and 1
gcc 7.3.0, openmpi 1.10.1
This test does not use CUDA, so running on …
=> tpetra:  #6883 Removing behavior test with default values controlled by CMake options

packages/tpetra/core/src/Tpetra_Details_getEntryOnHost.hpp, packages/tpetra/core/src/Tpetra_Util.hpp, packages/tpetra/core/test/MultiVector/MultiVector_MicroBenchmark.cpp
* #3238: implement ``Tpetra::Details::getEntryOnHost`` using ``Kokkos::deep_copy`` from an arbitrary
0-D view to a host scalar.
* Fix lots of ``calling __host__ function from __host__ __device__ function``
warnings, due to ``Tpetra::merge2`` being declared as
``KOKKOS_INLINE_FUNCTION``, but being passed STL iterators. merge2 is
only used in a few places in Trilinos and none of them are in device
kernels, so this PR removes the ``KOKKOS_INLINE_FUNCTION`` marking.
* Fix shadow warning in a MultiVector test
- #3238 is an opportunity to remove redundant code
- fixes dozens of warnings on CUDA builds
- fixes one -Wshadow warning that should show up in any build
* Closes #3238
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of …
=> Tpetra: address #3238, fix warnings

packages/belos/src/BelosBlockGmresSolMgr.hpp, packages/belos/tpetra/test/BlockGmres/CMakeLists.txt, packages/belos/tpetra/test/BlockGmres/test_bl_gmres_hb.cpp
-     Use OrthoManagerFactory in Belos' block GMRES
-     One motivation is to make TSQR available from block GMRES
We added a tester for block GMRES with TSQR for ctest under belos/tpetra/test. It passed on blake using gcc/7.2.0.
=> Use OrthoManagerFactory in Belos' block GMRES

packages/muelu/test/scaling/CMakeLists.txt, packages/muelu/test/scaling/Driver.cpp, packages/muelu/test/scaling/MatrixMatrixMultiply.cpp, packages/teuchos/comm/src/Teuchos_StackedTimer.cpp, packages/teuchos/comm/src/Teuchos_StackedTimer.hpp, packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp, packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_main.cpp, packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.hpp
In order to use Watchr (the SEMS performance plugin for Jenkins) for performance testing, we need the Teuchos::StackedTimer to output XML files in a specific format. This PR adds functions ``reportXML()`` and ``reportWatchrXML()`` to StackedTimer. ``reportWatchrXML()`` is the one that's intended for performance tests - in the directory ``$WATCHR_PERF_DIR`` (environment variable), it creates an XML file with a name prefix, and a current datestamp. This makes it easy to add XML output to perf tests. It also makes it very easy to set up the performance testing on a given machine:
```
git clone $url_to_data/PerformanceData
export WATCHR_PERF_DIR=cwd/PerformanceData/$machine
cd $WATCHR_PERF_DIR
git add .
git commit -m "Testing for $machine …
```
=> StackedTimer XML output for Watchr

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp
The setup for region Chebyshev now uses the region smoother setup for the matrix diag.
This fixes the interface scaling on the diagonal matrix used in the region Chebyshev smoother. It also reduces duplicate code in region smoothers.
=> MueLu Region cheby switched to use existing region smoother setup

packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C1_FEM.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C1_FEMDef.hpp, packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp, packages/intrepid2/src/Shared/Intrepid2_ViewIterator.hpp, packages/intrepid2/unit-test/Discretization/Basis/BasisEquivalenceTests.cpp, packages/intrepid2/unit-test/Discretization/Basis/CMakeLists.txt, packages/intrepid2/unit-test/Discretization/Basis/HGRAD_HEX_C1_FEM/test_01.hpp, packages/intrepid2/unit-test/Discretization/Basis/UnitTestMain.cpp
Also added:
- BasisEquivalenceTests (one of which demonstrated the issue in #6924)
- location accessor features in ViewIterator
- rank-agnostic view comparison feature for testing (in Intrepid2_TestUtils)
Also fixed the test in
Discretization/Basis/HGRAD_HEX_C1_FEM/test_01.hpp
which enforced the incorrect zero values for OPERATOR_D3.
As part of the ongoing hierarchical basis development work (now adding simplices), I implemented some basis equivalence tests.  The way these work is that for two bases that span the same space, we compute a conversion matrix that allows one to convert values computed by one basis to those that should be generated by the other.  We compute this conversion matrix using `OPERATOR_VALUE`, and then we use it to compute expected values for …
=> Intrepid2: fixed #6924 (incorrect OPERATOR_D3 output for C1 Hex basis).

cmake/ctest/drivers/atdm/mutrino/drivers/Trilinos-atdm-mutrino-intel-complex-openmp-opt-KNL.sh, cmake/std/atdm/ATDMDisables.cmake, cmake/std/atdm/mutrino/all_supported_builds.sh
This build was specifically requested by GEMMA.  See [ATDV-296](https://sems-atlassian-srn.sandia.gov/browse/ATDV-296) and they reported it had a KokkosKernels build error but as of this version of Trilinos was 100% passing for the packages used by GEMMA.
NOTES:
* This changes the ATDM Trilinos builds so that adding `complex` to the build-name automatically disables all of the packages that GEMMA does not use.
* This build is promoted to the 'ATDM' CDash group since it was 100% clean (see below).
On 'mutrino' I ran:
```
./ctest-s-local-test-driver.sh intel-complex-openmp-opt-KNL
***
***
Hostname 'mutrino' matches known ATDM host 'mutrino' and system …
```
=> Add intel-complex-openmp-opt-KNL for ATS-1 'mutrino' for GEMMA (ATDV-296)

packages/kokkos-kernels/src/batched/KokkosBatched_Gemm_Serial_Impl.hpp, packages/kokkos-kernels/src/batched/KokkosBatched_Gemv_Serial_Impl.hpp, packages/kokkos-kernels/src/batched/KokkosBatched_LU_Serial_Impl.hpp, packages/kokkos-kernels/src/batched/KokkosBatched_Trsm_Serial_Impl.hpp, packages/kokkos-kernels/src/batched/KokkosBatched_Util.hpp, packages/kokkos-kernels/src/batched/KokkosBatched_Vector_SIMD_View.hpp
As reported in #6957, mkl header location in kokkos batched util file is problematic. It should go above kokkosbatched name space. 
This PR also replaces dimension with extent. 
A separate PR for kokkoskernels will be submitted.
=> KokkosKernels - replace dimension with extent

packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_Details_CrsPadding.hpp
The empty static constexpr methods "create_from_sames_and_permutes"
and "create_from_imports" were causing build failues for clang
shared (undefined symbols).  Addresses issue #6951.
Fixes build failure reported in #6951.
I replicated the failure locally, and verified that this PR fixes it. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6963)
=> Tpetra: remove unnecessary methods from CrsPadding

packages/kokkos/cmake/kokkos_install.cmake
Cherry-picking https://github.com/kokkos/kokkos/pull/2777: Without this, e.g. devices are not separated by semicolons.
Checking with a third-party library.
=> Kokkos: Make sure semicolons are not deleted in KokkosConfig_install.cmake

packages/muelu/test/unit_tests/Adapters/CreatePreconditioner.cpp
The methods:
- CreateEpetraPreconditioner
- CreateTpetraPreconditioner
- CreateXpetraPreconditioner
That take nullspace and/or coordinated directly as parameters were deprecated and removed in #6388.  This PR removes the deprecated tests that used these methods.
* Part of #6655  
```bash
cmake \
-GNinja \ …
```
=> MueLu: Remove Deprecated Tests

cmake/std/atdm/README.md, cmake/std/atdm/sems-rhel7/environment.sh
CC: @jmgate 
This should hopefully fix a problem with one of the 'ascic' machines that
EMPIRE is trying to run jenkins jobs on where the SEMS modules are not being
defined (see #6986).
ToDo: @jmgate to test this branch on 'ascic' machine where the current problem is occurring?
=> ATDM: sems-rhel7: Default define SEMS modules (#6986)

commonTools/test/utilities/compareTestOutput
This was failing on python 3 testing in prep
for that becoming the default in RHEL 8.
This now runs in 2.7 and 3.6
@trilinos/ml 
Several of the constructs in this script were built for much older python that is not in use and those are no longer available in python 3. As that will be the default starting in RHEL 8 we are working to run with that set now rather than at the last minute.
* Blocks #6878 
This was tested separately on my blade and as part of testing for #6878 in my branch as that PR has bootstrapping issues.
Anything else we need to know in evaluating this merge request?
=> Bring compareTestOutput up to python 2.7 or above

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_MatchConditions.hpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Parser.cpp, packages/panzer/adapters-stk/test/periodic_bcs/periodic_bcs.cpp
clean up the construction of the coordinate matcher for periodic wedge
This allows empire to run a new set of periodic problems. Documented in empire issue 662.
periodic_bc.exe test in panzer covers the new ctors.
=> Panzer: more changes for periodic wedge support

packages/tpetra/core/src/Tpetra_Distributor.cpp, packages/tpetra/core/src/Tpetra_Distributor.hpp, packages/tpetra/core/test/Distributor/Distributor_UnitTests.cpp
@csiefer2  was interested in having more timers in Distributor to determine whether applications were spending time in the so-called "slow" path (in which data to be sent must be reordered and buffered) or the so-called "fast" path (in which data to be sent are already ordered by destination processor, avoiding buffering).  
This PR provides those additional timers.  It also separates timers for interface calls using Teuchos::Arrays from those using Kokkos::Views.  
To activate the timers, one must define TPETRA_DISTRIBUTOR_TIMERS in Tpetra_Distributor.hpp (sufficient definition is in comments in the file) or add -DTPETRA_DISTRIBUTOR_TIMERS to CXX_FLAGS.
See #6977 and issues referenced there for more info on Distributor.
@csiefer2  are these the timers you can use? …
=> Tpetra:  Adding more Distributor timers

packages/intrepid2/unit-test/Discretization/Basis/BasisEquivalenceTests.cpp
Intrepid2: relaxed tolerances in two tests to allow intel builds to pass.
Fixes #6991.
* Closes #6991.
=> Intrepid2: relaxed tolerances in two tests to allow intel builds to pass.

packages/anasazi/tpetra/src/TsqrTpetraTest.hpp, packages/tpetra/tsqr/src/Tsqr_TestUtils.hpp
Anasazi's TpetraTsqrTest used Node object in a deprecated way.  This PR removes that usage.
However, TpetraTsqrTest is not used **anywhere**.  
@mhoemmen @hkthorn  Should I remove that file?
NA
Anasazi and Tpetra's TSQR build correctly on my mac with
```
module load sems-gcc/6.4.0
module load sems-openmpi/1.10.1
```
All tests pass.
The code changes in TsqrTpetraTest.hpp are not tested, however, as the file is not used anywhere.  Perhaps the file should be deleted.
=> Anasazi:  remove deprecated use of Node object

packages/belos/tpetra/test/Native/nonsymm_matrix.cpp
@trilinos/belos @iyamazaki 
Prevent random test failures that hinder pull requests.  See @bartlettroscoe 's [comment](https://github.com/trilinos/Trilinos/issues/3276#issuecomment-599759956).
* Closes #7029
Mac Clang + OpenMPI.
=> Belos: Fix #7029 (jumbled output causing random test failure)

CTestConfig.cmake
As explained in the documentation:
https://cmake.org/cmake/help/v3.13/manual/ctest.1.html?highlight=nightlystarttime#ctest-update-step
the CTest setting `NighltyStartTime` (global var `CTEST_NIGHTLY_START_TIME`) only
determines how central VCS like CVS and SVN checkout the code.  It does
nothing for DVCS like git.  Therefore, it is better to just take this out.
=> Remove CTEST_NIGHTLY_START_TIME is it does nothing with git

CTestConfig.cmake
This reverts commit 62e97b0d717fb60bd1c79d6aaeff21a039b7fc98.
See the detailed comment in the file CTestConfig.cmake for details and:
* https://gitlab.kitware.com/cmake/cmake/issues/20471
=> Revert "Remove CTEST_NIGHTLY_START_TIME is it does nothing with git"

packages/thyra/core/src/support/operator_vector/client_support/Thyra_TestingTools.cpp, packages/thyra/core/src/support/operator_vector/client_support/Thyra_TestingToolsDecl.hpp
@trilinos/thyra
The printTestResults method that takes pointers has been deprecated and replaced with a method that takes references to pointers for pointer safety.
* Part of #6655 
```bash
cmake \
-GNinja \
-DTrilinos_ENABLE_Epetra=ON \
-DTrilinos_ENABLE_Panzer=ON \
-DTrilinos_ENABLE_STK=ON \
-DTrilinos_ENABLE_Percept=ON \ …
```
=> Thyra: Removed Deprecated printTestResults

packages/zoltan2/src/algorithms/partition/Zoltan2_AlgPuLP.hpp, packages/zoltan2/test/unit/environment/AllParameters.cpp
@trilinos/Zoltan2
Addressing compilation bugs within shared-memory PuLP interface in Zoltan2.
1.) Fixed pointer bug when initializing pulp graph datatype.
2.) Updated number of parameter strings for testing compilation.
Testing validated as PASSED by Zoltan2 Test Driver. Tested with PuLP-0.2 and XtraPuLP-0.3.
=> PuLP interface in Zoltan2 bug fixes:

packages/tpetra/tsqr/test/Tsqr_TestNodeTsqr.cpp
@iyamazaki @jennloe @egboman @hkthorn @fnrizzi
"NodeTsqr" benchmark was omitting a label; this PR fixes that.
Pressio needs this for a deliverable.
Mac Clang + OpenMPI.
=> TSQR: Fix NodeTsqr benchmark output (NodeTsqr implementation labels)

cmake/std/atdm/ATDMDisables.cmake
Turns out that SPARC does not actually use ShyLU_NodeTacho.  It was only being
enabled indirectly by Amesos2.  In fact, the native SPARC Trilinos configure
scripts explicitly disable ShyLU_NodeTacho.  Also, EMPIRE is not using any
part of ShyLU so I think this is safe to disable for EMPIRE too.  And GEMMA
does not use any part of ShyLU and does not use Amesos2.
Therefore, we can safely disable this subpackage.  Less code to build, test,
and maintain.  Win, win, win.
For more context and proof for this, see [CDOFA-110](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-110).
I tested this with SPARC on the CEE RHEL6 machine 'ceerws1113':
```
$ time env \
SPARC_TRIL_MAKE_OPTIONS="-j 8" \
SPARC_TRIL_CTEST_ARGS="-j 4 -L test_regression" \
SPARC_TRIL_SKIP_NATIVE_BUILD=1 \ …
```
=> Disable ShyLU_NodeTacho in all ATDM Trilinos builds (CDOFA-110)

cmake/ctest/drivers/atdm/ats2/drivers/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_dbg.sh, cmake/ctest/drivers/atdm/ats2/drivers/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-2019.06.24_static_opt.sh, cmake/ctest/drivers/atdm/ats2/drivers/Trilinos-atdm-ats2-gnu-7.3.1-spmpi-2019.06.24_serial_static_dbg.sh
All of the failures have been triaged and there are no failures not also
occurring on other systems.  The 'opt' builds are currently 100% clean.
See [ATDV-311](https://sems-atlassian-srn.sandia.gov/browse/ATDV-311)
=> ATDM: ats2: Promote to 'ATDM' group (ATDV-311)

cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake, packages/stokhos/src/sacado/kokkos/vector/Teuchos_LAPACK_MP_Vector.hpp
This PR addresses the issue #7067.
The changes to the file `packages/stokhos/src/sacado/kokkos/vector/Teuchos_LAPACK_MP_Vector.hpp` address the compilation errors listed in the issue.
The change to the `cmake/std/PullRequestLinuxGCC4.8.4TestingSettings.cmake` has the purpose of testing the ensemble reduction in at least one PR build to maintain the Ensemble reduction in future release. 
These changes have been tested both with and without ensemble reduction.
=> Stokhos: maintain ER build

packages/tpetra/tsqr/src/Tsqr.hpp, packages/tpetra/tsqr/src/Tsqr_FullTsqrTest.hpp, packages/tpetra/tsqr/src/Tsqr_TestUtils.hpp, packages/tpetra/tsqr/test/Tsqr_TestFullTsqr.cpp, packages/tpetra/tsqr/test/Tsqr_TestNodeTsqr.cpp
@trilinos/tpetra @hkthorn @jennloe @iyamazaki @fnrizzi 
I was pretty sure I had a "full" TSQR benchmark, but it seems to have disappeared over the years.  This commit implements that benchmark.  "Full" TSQR means what one would normally run to implement TSQR over multiple MPI processes, using the TSQR::Tsqr class.  Tsqr uses a NodeTsqr subclass to implement the part of the TSQR algorithm in a single MPI process, and DistTsqr* to implement the part of the TSQR algorithm that runs across multiple MPI processes.
@fnrizzi needs this for a Pressio deliverable.
Pressio serves the needs of multiple applications that actually have some relevance to our mission.
Mac Clang + OpenMPI.  Existing tests provide compilation test coverage.  I ran the benchmark manually to verify correct output with …
=> TSQR: Finish "full" TSQR benchmark; update TSQR documentation

packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp, packages/tpetra/core/src/Tpetra_idot.hpp, packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
@mhoemmen @kddevin 
These changes are sufficient to get the Tpetra test suite passing on white with CUDA_LAUNCH_BLOCKING unset. (except for the trivial case of initialization tests which currently fail because they check CUDA_LAUNCH_BLOCKING).
White was down for a while so I started checking on a local machine running a GTX960 card. That revealed a few new issues which I will open as a separate PR to keep things organized.
For TpetraExt_TripleMatrixMultiply_def.hpp I added 4 fences, but also removed 1. I don't think we need the removed fence. If we do need it, then we may need it for all 4 spots in that file.
For KokkosBlas::dot and KokkosBlas::gemm fences, we likely need more fences for other KokkosBlas calls. This was discussed in …
=> Fix CUDA_LAUNCH_BLOCKING for Tpetra parallel tests on white

packages/tpetra/core/src/Tpetra_Details_Behavior.cpp, packages/tpetra/core/src/Tpetra_Details_Behavior.hpp, packages/tpetra/core/src/Tpetra_Details_Profiling.cpp, packages/tpetra/core/src/Tpetra_Details_Profiling.hpp
Does what you expect as applied to the MueLu Driver; See #7072
Tests: RHEL6
=> Tpetra: Adding environment variable to allow Teuchos::Timers in Tpetra::ProfilingRegion

packages/tempus/src/Tempus_SolutionStateMetaData_decl.hpp, packages/tempus/src/Tempus_SolutionStateMetaData_impl.hpp, packages/tempus/src/Tempus_Stepper_decl.hpp, packages/tempus/src/Tempus_Stepper_impl.hpp
Removed all TEMPUS_HIDE_DEPRECATED_CODE.
Passing all test on CEE LAN gcc.
* Related to #6914
=> Tempus: Remove Deprecated Code

cmake/ctest/drivers/atdm/ats2/local-driver-single-build.sh, cmake/ctest/drivers/atdm/ats2/local-driver.sh, cmake/std/atdm/ats2/environment.sh
See commit messages, comments in files and [ATDV-234](https://sems-atlassian-srn.sandia.gov/browse/ATDV-324) for details.
This was first reviewed and tested internally in:
* https://cee-gitlab.sandia.gov/atdm/Trilinos/merge_requests/3
See details there.
=> ATDM: ats2: build on login node instead of compute node

cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
Not having this set in at least one PR build has allowed a mass number of test
failures to slip through into ATDM Trilinos testing.  See #7046.
=> Set MueLu_ENABLE_Kokkos_Refactor_Use_By_Default=ON (#7046)

packages/shylu/shylu_node/tacho/example/Tacho_ExampleExternalInterface.cpp
External example code has a bug in openmp build. It uses a out-dated enum.
=> Tacho - fix external example for openmp and serial build

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
We had some timing issues with `Teuchos::getParametersFromXmlFile()`, so its is now replaced by `Teuchos::updateParametersFromXmlFileAndBroadcast()`.
- Change agreed upon with @rstumin and @lucbv 
- Experimental code, so no actual stakeholders yet.
This is experimental code, so it's not included in PR testing. Yet, tests passed locally.
=> MueLu: read xml files in region MG in parallel runs

packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml, packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml, packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellOpenMP.xml
Update MiniEM solver parameters to be more like EMPIRE.
@brian-kelley
=> MiniEM: Update solver parameters

packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
The new cut based aggregation in MueLu has not yet been kokkosified.
@jmgate
=> MiniEM: Don't use kokkos refactor code path

packages/kokkos-kernels/src/sparse/KokkosSparse_CrsMatrix.hpp, packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_decl.hpp, packages/phalanx/example/FiniteElementAssembly/LinearObjectFactory.hpp, packages/phalanx/test/Kokkos/tKokkos.cpp, packages/stokhos/src/sacado/kokkos/pce/linalg/Kokkos_CrsMatrix_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_CrsMatrix_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/linalg/Kokkos_CrsMatrix_MP_Vector_Cuda.hpp, packages/stokhos/test/Performance/MPVectorKernels/TestSpMv.hpp, packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixMPVectorUnitTest.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_LocalCrsMatrixOperator_decl.hpp, packages/trilinoscouplings/examples/fenl/fenl_functors.hpp, packages/trilinoscouplings/examples/fenl/fenl_functors_pce.hpp, packages/xpetra/src/CrsGraph/Xpetra_CrsGraph.hpp
Fix the KokkosSparse::CrsMatrix::StaticCrsGraphType specialization to
use the full device type, not just execution space. Was necessary for
some things in KokkosKernels to work with both <Cuda, CudaSpace> an
<Cuda, CudaUVMSpace> in the same build. (Mirror of https://github.com/kokkos/kokkos-kernels/pull/666)
Fix downstream errors in Tpetra, Xpetra and MueLu caused by that change.
This just involved passing the Kokkos::Device specialization
corresponding to Node in to the local_matrix_type/local_graph_type
template parameters.
This is needed by @iyamazaki to integrate the new two-stage GS into Ifpack2.
Just updates Tpetra stack in response to a necessary change to KokkosKernels.
* Closes 
* Blocks …
=> KokkosKernels/Tpetra stack: local CRS device types

cmake/std/atdm/common/toss3/environment_new.sh, cmake/std/atdm/common/toss3/environment_tlcc2.sh
For some reason, this seems to fix the compiler check on CTS-1 and TLCC-2
systems.  Something happened between testing day 2020-03-27 and 2020-03-28 to
break this.  See #7094 and [ATDV-328](https://sems-atlassian-srn.sandia.gov/browse/ATDV-328).
This is just a stop-gap measure to address this until we can see how to fix
the configure with the Ninja generator.
I manually tested this on CTS-1 system 'eclipse'.  I suspect it will also work on TLCC-2 systems as well (also a TOSS3 system).
=> cts1, tlcc2: Switch from Ninja to Unix Makefiles (#7094, ATDV-328)

packages/piro/src/CMakeLists.txt, packages/piro/src/Piro_InvertMassMatrixDecorator.hpp, packages/piro/src/Piro_InvertMassMatrixDecorator_Def.hpp, packages/piro/src/Piro_RythmosSolver.hpp, packages/piro/src/Piro_RythmosSolver_Def.hpp, packages/piro/src/Piro_SolverFactory.hpp, packages/piro/src/Piro_SolverFactory_Def.hpp, packages/piro/src/Piro_TempusSolver.hpp, packages/piro/src/Piro_TempusSolver_Def.hpp, packages/piro/src/Piro_TransientDecorator.hpp, packages/piro/src/Piro_TransientSolver.hpp, packages/piro/src/Piro_TransientSolver_Def.hpp, packages/piro/src/Piro_TrapezoidRuleSolver.hpp, packages/piro/src/Piro_TrapezoidRuleSolver_Def.hpp, packages/piro/src/Piro_VelocityVerletSolver.hpp, packages/piro/src/Piro_VelocityVerletSolver_Def.hpp
Some improvements to Piro package: 
- Piro::TempsSolver has been refactored into helper class called Piro::TransientSolver.  Transient sensitivities will go in the latter class, similar to Piro::NOXSolver and Piro::SteadyStateSolver.  
- Obsolete template arguments that used to be needed for Albany have been removed from various Piro classes.
=> Piro: TempusSolver refactor and cleanup

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/regionMG/examples/structured/CMakeLists.txt, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/research/regionMG/examples/structured/coarse_smoother.xml
1. no longer computing the coarse composite operator when a coarse grid smoother is used and not throwing on "coarse solver type = smoother".
2. adding a command line parameter to pass specific option to the coarse grid smoother since it might require more iterations than a regular level smoother.
* Closes #7129
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Added new input deck for coarse grid smoother and tested on local machine.
=> MueLu: modifying region coarse grid setup

packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp, packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_def.hpp
Fix compile issue, see https://testing.sandia.gov/cdash/viewBuildError.php?buildid=6688315
=> Xpetra_*CrsGraph: fix return of getLocalGraph

cmake/std/atdm/common/toss3/environment_new.sh, cmake/std/atdm/common/toss3/environment_tlcc2.sh
Reverts trilinos/Trilinos#7109
The configure with ninja is reported to be fixed and manually tested.
=> Revert "cts1, tlcc2: Switch from Ninja to Unix Makefiles (#7094, ATDV-328)"

packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasisFamily.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HGRAD_HEX.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HGRAD_QUAD.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_HEX_In_FEM.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_HEX_In_FEM.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TET_I1_FEMDef.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_WEDGE_C2_FEMDef.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_C0_FEM.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasisFamily.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_IntegratedLegendreBasis_HGRAD_TET.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_IntegratedLegendreBasis_HGRAD_TRI.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_NodalBasisFamily.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp, packages/intrepid2/src/Shared/Intrepid2_Polynomials.hpp, packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp, packages/intrepid2/unit-test/Discretization/Basis/BasisEquivalenceTests.cpp, packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases/AnalyticPolynomialsMatchTests.cpp, packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases/SubBasisInclusionTests.cpp, packages/intrepid2/unit-test/Shared/Polylib/LegendreJacobiPolynomials/IntegratedJacobiTests.cpp, packages/intrepid2/unit-test/Shared/Polylib/LegendreJacobiPolynomials/JacobiTests.cpp
Continuing the work implementing hierarchical bases, this PR adds support for H(grad) bases on triangles and tetrahedra. (These are the bases that EMPIRE expects to use for limiters soon.)
There are two types of tests included here:
1. Basis equivalence tests: these confirm that both the DG and CG variants of the bases are consistent with the existing nodal bases in Intrepid2.
2. Sub-basis inclusion tests: these confirm that the hierarchical bases do in fact nest.
In addition to those tests, an offline verification has been performed to confirm that this implementation agrees with the equivalent bases in ESEAS.
Addresses (but does not close) #6481.
=> Intrepid2: add support for hierarchical H(grad) bases on triangle and tetrahedron.

packages/teuchos/comm/src/Teuchos_StackedTimer.cpp, packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
- Use proper XML escape codes, e.g. ``&quot;`` for ``"``
(this was breaking MueLu Driver output, since some timer names have quotes)
- Disambiguate performance reports from differerent builds
- Read (optional) env var WATCHR_BUILD_NAME
- If set to e.g. "Vortex CUDA", then the root timer name in the XML
report will say "Vortex CUDA: Test XYZ", and the filename of the
report will be something like "$WATCHR_PERF_DIR/Vortex_CUDA-XYZ"
(spaces are replaced with underscore in filename)
- Filenames won't collide on different builds and top-level chart
titles will show the build name. Before, all builds would be
combined into a single data series which is definitely not what we
want.
@rppawlo 
Required to fix Watchr output when timers contain special XML …
=> Improve watchr output

packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp, packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp, packages/muelu/test/maxwell/CMakeLists.txt, packages/muelu/test/maxwell/Maxwell.xml
Remove 3 rounds of communication:
- Column map for D0_T and R11 matches, so for D0_T \* r and R11 \* r only import once.
- Fuse import from sub-problems with import into colmap for prolongators.
Also test Epetra code path on more systems.
=> MueLu RefMaxwell: Improve communication

packages/stokhos/CMakeLists.txt, packages/stokhos/cmake/Stokhos_config.h.in, packages/stokhos/src/CMakeLists.txt, packages/stokhos/src/sacado/kokkos/vector/KokkosBlas2_gemv_MP_Vector.hpp, packages/stokhos/src/sacado/kokkos/vector/KokkosBlas_MP_Vector.hpp
This PR adds a GEMV for the ensemble types in Stokhos.
This implementation has been optimized with the aim of reaching maximal memory bandwidth on CPU during the Arnoldi process occurring in the ensemble GMRES without the ensemble reduction.
The implementation relies on a tiling strategy to reuse data from cache and assume that the matrix is stored with a left layout (the implementation works with a right layout but is suboptimal in that case).
This PR branch has been tested on the Blake system without the ensemble reduction.
=> WIP: Stokhos: add an optimized GEMV for the ensemble GMRES without ensemble reduction

cmake/std/atdm/van1-tx2/custom_builds.sh
The van1-tx2 environment currently allows the matching of 'arm-' plus a
version number to determine the compiler.  This allows one to simply
specify 'arm' as the compiler instead of needing a version as well.
=> ATDM Config:  Match 'arm' Without Version

cmake/TPLs/FindTPLBoostAlbLib.cmake
boost_signals has been eliminated, and is no longer needed for Albany.
=> Removing "boost_signals" from REQUIRED_LIBS_NAMES in FindTPLBoostAlbLib.cmake

packages/muelu/src/Misc/MueLu_InterfaceAggregationFactory_def.hpp, packages/muelu/src/MueCentral/MueLu_HierarchyUtils_decl.hpp, packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp, packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp, packages/muelu/src/Utils/MueLu_Utilities.cpp, packages/muelu/src/Utils/MueLu_Utilities_decl.hpp, packages/muelu/test/meshtying/MeshTyingBlocked_SimpleSmoother.cpp, packages/muelu/test/meshtying/myXML.xml
@kliegeois 
This PR enables to pass user-specific data regarding the dual-to-primal node mapping required by the `InterfaceAggregationFactory` through the parameter list `"user data"` and removes the previous restriction, that the MueLu xml-file had to contain a very specific sublist with a hard-coded name.
* Closes #7164 
None
MueLu tests pass.
=> MueLu: pass primal/dual interface node mapping via user data sublist

cmake/std/atdm/van1-tx2/environment.sh
After the "upgrade" of the ATDM Trilinos parsing system to parse out the KOKKOS_ARCH in either upper or lower case (see #7202 ), now the 'tx2' in 'van1-tx2' matches the KOKKOS_ARCH 'TX2' (lower case 'tx2').  This broke the running of atdm/van1-tx2/environment.sh.  This broke the nightly ATDM Trilinos 'van1-tx2' builds and installs of Trilinos from 'stria' today, testing day 2020-04-21.
I updated the error message to show the KOKKOS_ARCH and then I updated the logic to accept the KOKKOS_ARCH of 'TX2'.  That is a bit of a hack but it gets us around this problem (and is harmless on this system).
I manually tested this on my Windows 10 Cygwin machine by manually running:
```
$ . cmake/std/atdm/load-env.sh Trilinos-atdm-van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_dbg
ostname 's1049009' …
```
=> ATDM: van1-tx2: Address problem of 'van1-tx2' matching KOKKOS_ARCH=TX2 (#4063, CDOFA-27)

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/test/scaling/DriverCore.hpp, packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp
Fix debug check in `CheckRepairMainDiagonal`. Seems to get rid of #6882. 
Hopefully fix #3041
=> Xpetra: Fix for CheckRepairMainDiagonal

cmake/std/PullRequestLinuxIntelTestingSettings.cmake
Addressing Issue #6570, and setting Tpetra_INST_INT_INT = ON in a PR test, Intel 17.
This has been run through merging the changes to fix any failing tests due to the change and run a test build.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-instintintON-test-Trilinos_pullrequest_intel_17.0.1-6228&field2=buildstamp&compare2=63&value2=Experimental)
=> set Tpetra_INST_INT_INT = ON in a PR test

cmake/std/atdm/utils/get_known_system_info.sh
@bartlettroscoe, @e10harvey, recently the vortex admins installed `/etc/profile.d/snlvariables.sh` on vortex to define `SNLSYSTEM`, `SNLCLUSTER`, etc.  Somehow that broke the `load_matching_env.sh` script that gets installed with Trilinos.  It winds up throwing
```
ERROR: Unrecognized cluster vortex
```
and running our scripts with `set -e` means we die.  It looks like the error's coming from `/projects/sems/modulefiles/utils/get-platform`.  This PR avoids the call to `get-platform` on vortex as you did with astra so we can avoid that error and be about our merry way.
=> ATDM Config:  Don't get-platform on Vortex

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp, packages/panzer/adapters-stk/test/panzer_workset_builder/check_rotation_matrices.cpp, packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp, packages/panzer/disc-fe/src/Panzer_IntegrationValues2.hpp, packages/panzer/disc-fe/src/Panzer_Workset.cpp
The rule is supposed to be that virtual cells have always have face ordinal 0 being the one that abuts the real cell, and that these have normals that are the negative of the normal on the real cell at the same point.  This commit makes the panzer Workset adhere to this rule.
=> Panzer: set virtual cells to have appropriate normals and rotation matrices

packages/kokkos/cmake/kokkos_install.cmake
Fixes https://github.com/kokkos/kokkos/issues/2779. When building `Kokkos` in `Trilinos` there is currently no version file such that detecting a specific `Kokkos` version via `CMake` is not possible. This pull request copies the relevant file in the correct location.
Mirrored from https://github.com/kokkos/kokkos/pull/2957, related to https://github.com/arborx/ArborX/pull/234.
Tested by building [ArborX](https://github.com/ArborX/ArborX) with the `Kokkos` package installed through `Trilinos`.
=> Kokkos: Configure and install version file when building Kokkos

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
Fixes #7264. Build failed with an undefined variable `switched` in an Epetra-only build using Zoltan, but no Zoltan2.
n/a
Building with Zoltan, but no Zoltan2 works now.
Also remove a bunch of trailing white spaces.
=> MueLu: fix build error w/ Zoltan but w/o Zoltan2

packages/tpetra/core/src/Tpetra_Distributor.cpp, packages/tpetra/core/src/Tpetra_Distributor.hpp, packages/tpetra/core/test/Distributor/Distributor_UnitTests.cpp, packages/xpetra/src/Export/Xpetra_TpetraExport_def.hpp, packages/xpetra/src/Import/Xpetra_TpetraImport_def.hpp
While working on a unit test for #7156, I realized that there is in fact already an access method for the reverse distributor. So I'm reverting the changes of #7156 and modifying the method `getReverse` instead. It's now also unit-tested.
=> Tpetra Distributor: getReverse changes

packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
Removed code that wasn't used anywhere.
The unused code sometimes caused compilation problems (that's how I noticed it).
Removed some comments that are no longer relevant (part of Kokkos::parallel_scan debugging effort).
Less code is good.
Built and ran tests on mac with clang.
=> tpetra:  removed unused code and comments that no longer are relevant

cmake/std/atdm/ATDMDisables.cmake
The ATDM APPs are not using this package so no reason to test this as part of ATDM Trilinos testing.
This got added due to #6934 which has nothing to do with ATDM (as far as I know).
NOTE: This is what you need to do when you use the "blacklisting" approach but new packages are added very rarely so this is no big deal.
=> ATDM: Remove new package Compadre from ATDM Trilinos testing (#6934)

packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp, packages/panzer/adapters-stk/test/panzer_workset_builder/check_rotation_matrices.cpp, packages/panzer/disc-fe/src/Panzer_Workset.cpp
PR 7225 broke some things in EMPIRE because it has some subtle reliance on the old behavior.  This PR is a compromise, reverting to the former definition of local face ordinal for virtual cells (not face 0, but the same local face id as the corresponding real cell), but keeping the reversal of the normal direction and still zeroing out the normals and rotation matrices for virtual cell faces that do not correspond to a real cell face.
All but one of the failing EMPIRE tests have been confirmed to pass with these changes.  The one that still fails aborts when it encounters a zero normal on a virtual cell face; this is easily fixed in EMPIRE.
=> Panzer: partial rollback/amendment of 7225 due to EMPIRE reliance on previous behavior.

cmake/std/atdm/ATDMDevEnvSettings.cmake, cmake/std/atdm/sems-rhel6/environment.sh, cmake/std/atdm/sems-rhel7/environment.sh
This should fix the NetCDF-related (or PnetCDF) failures seen on some shared-library builds. 
Note that the SEMS installs have shared/static NetCDF and HDF5 libraries, but for some reason, they use a static-only libpnetcdf.a.  This PR fixes the specification of the libpnetcdf library to always be .a in a shared or non-shared build.
It also correctly sets the NETCDF_ROOT CMake variable which is needed by the FindNetCDF.cmake package find module.
=> CONFIG: Fix pnetcdf and netcdf setting broke in #7197

cmake/std/atdm/ats2/environment.sh, cmake/std/atdm/common/toss3/environment_tlcc2.sh, cmake/std/atdm/sems-rhel6/environment.sh
I did not test these but these envs were all broken (due to PR #7197 as reported in #7275) so adding this back can't hurt.
=> ATDM: Add back removed BOOST_ROOT env vars (#7275)

packages/muelu/test/perf_tests_kokkos/KokkosKernels.cpp
The argument "pad" to the KokkosSparse::CrsMatrix has no effect and will be removed. It does have a default value now, so it's not needed to pass in anything. This will just save a change that would be needed at the next kokkos-kernels snapshot.
Just cleanup
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to https://github.com/kokkos/kokkos-kernels/pull/708
* Part of 
* Composed of 
Only affects build.
=> MueLu: remove unused arg to KokkosSparse::CrsMatrix

packages/tpetra/core/test/BugTests/BugTests.cpp
Minor changes to use Tpetra's default communicator rather than ifdefs for MPI; this code runs fine in serial builds.
Also better comments for SQA tracing of code, tests and issues.   
Follow-up to #7233 #7234
Tested with and without MPI on mac.
=> tpetra:  Minor change to use general communicator rather than MPI-ifdefs

packages/ifpack2/src/Ifpack2_Chebyshev_decl.hpp, packages/ifpack2/src/Ifpack2_Factory_decl.hpp, packages/ifpack2/src/Ifpack2_RILUK_decl.hpp, packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
KokkosClassic::DefaultNode is deprecated, along with functions that take a node object as an argument. Thus, clone methods are no longer needed
* Part of #6655  
```bash
cmake \
-GNinja \
-DTrilinos_ENABLE_Epetra=ON \
-DTrilinos_ENABLE_Panzer=ON \
-DTrilinos_ENABLE_STK=ON \
-DTrilinos_ENABLE_Percept=ON \ …
```
=> Ifpack2: Remove Deprecated Clone Methods

packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
Block size > 1 currently segfaults. With this change, we force blocks to all be on the same partition, ignoring the Zoltan2 solution for all but one rows per block.
=> MueLu Zoltan2Interface: Handle blockSize>1

packages/muelu/src/Interface/MueLu_ParameterListInterpreter_decl.hpp, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/test/interface/default/EasyParameterListInterpreter/CMakeLists.txt, packages/muelu/test/interface/default/EasyParameterListInterpreter/notay.xml, packages/muelu/test/interface/default/Output/notay_epetra.gold, packages/muelu/test/interface/default/Output/notay_tpetra.gold
=> MueLu: Adding Pairwise to easy parameterlist

packages/teuchos/comm/src/Teuchos_StackedTimer.cpp, packages/teuchos/comm/src/Teuchos_StackedTimer.hpp, packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp
Adding a timestamp option to the StackedTimer when verbose mode is enabled. The user can enable and export the number of levels to output with:
```
export TEUCHOS_ENABLE_VERBOSE_TIMESTAMP_LEVELS=2
```
This is going to be used for LDMS performance monitoring on HPC machines.
Performance monitoring for milestone runs
Planning to be used in ATDM L1 Milestone runs.
New unit test was added to stacked_timer.cpp.
=> Teuchos: add timestamp option to verbose stacked timer

cmake/std/atdm/van1-tx2/environment.sh
The hope is that this will avoid OOM conditions when linking ROL execs.  See [CDOFA-117](https://sems-atlassian-srn.sandia.gov/browse/CDOFA-117)
On 'stria' I ran:
```
$ cd /lustre/rabartl/Trilinos.base/BUILDS/STRIA/CTEST_S/
$ env Trilinos_PACKAGES=Kokkos,Teuchos \
./ctest-s-local-test-driver.sh van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_dbg
***
***
ATDM_TRILINOS_DIR = '/lustre/rabartl/Trilinos.base/Trilinos'
Hostname 'stria-login1' matches known ATDM host 'stria-login1' and system 'van1-tx2'
Using ARM ATSE compiler stack ARM-20.0_OPENMPI-4.0.2 to build DEBUG code with Kokkos node type SERIAL
Running builds: …
```
=> ATDM: van1-tx2: Reduced parallel link level for 'dbg' builds (CDOFA-117)

cmake/std/atdm/ats1/tweaks/Tweaks.cmake
I verified that the 'ats1' build passes via:
```bash
$ git log --pretty=oneline -1
7a74218d58456d0818e2f13dd8202451c1b133ac (HEAD -> develop, github-upstream/develop) Merge pull request #7313 from cgcgcg/epetraMueLuMaxwell
$ git status
On branch develop
Untracked files:
(use "git add <file>..." to include in what will be committed)
$ cmake -G Ninja -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake -DTrilinos_ENABLE_TESTS=ON -DTrilinos_ENABLE_MueLu=ON -DMueLu_Maxwell3D_EXE_DISABLE=OFF -DMueLu_Maxwell3D-Tpetra_MPI_4_DISABLE=OFF ../Trilinos &> configure.out &
$ ninja -j16 &> make.out &
```
make.out shows no errors.
Related to #7311
=> Re-enable Muelu_Maxwell3D

cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake, packages/panzer/CMakeLists.txt, packages/panzer/core/cmake/PanzerCore_config.hpp.in
I was seeing intermittent failures to build
with PANZER_FADTYPE undefined. The value was
set using TRIBITS_ADD_OPTION_AND DEFINE which
expects a bool and was passed a string. For
whatever reason, cmake is inconsistent about
how the passed string is interpreted and if the define
is set. Since there is no provision for this not being set
I just went to a direct SET statement.
Intermittent build failures due to mis-configuration
The configure was run in a loop of 100 iterations and the output to PanzerCore_config.h was verified via grep.
=> Set default for PANZER_FADTYPE at all points

packages/ifpack2/src/Ifpack2_ILUT_def.hpp
By making sure to free L & U prior to recomputing them.
This brings ifpack2 ILUT memory usage in line with aztec on several Aria test cases, saving ~30% high-water mark.
=> ifpack2: Reduce ILUT memory usage.

packages/intrepid2/src/Orientation/Intrepid2_Orientation.hpp, packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefContractions.hpp, packages/phalanx/src/Phalanx_DeviceEvaluator.hpp, packages/sacado/src/KokkosExp_View_Fad.hpp, packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp, packages/stk/stk_mesh/stk_mesh/base/DeviceMesh.hpp, packages/stk/stk_mesh/stk_mesh/base/NgpField.hpp, packages/stk/stk_mesh/stk_mesh/base/NgpReductions.hpp, packages/stk/stk_ngp/stk_ngp/NgpField.hpp, packages/stk/stk_ngp/stk_ngp/NgpFieldParallel.hpp, packages/stk/stk_ngp/stk_ngp/NgpMesh.hpp, packages/stk/stk_ngp/stk_ngp/NgpReductions.hpp, packages/stk/stk_search/stk_search/Box.hpp, packages/stk/stk_search/stk_search/KDTree_BoundingBox.hpp, packages/stk/stk_search/stk_search/Point.hpp, packages/stk/stk_util/stk_util/parallel/MPI.hpp, packages/stokhos/src/sacado/kokkos/Stokhos_StaticFixedStorage.hpp, packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp, packages/stokhos/src/sacado/kokkos/pce/Sacado_UQ_PCE.hpp, packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp, packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp, packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp, packages/trilinoscouplings/examples/fenl/fenl_functors.hpp
Fix warnings in several packages that happen in CUDA 9/10 builds,
by using ``KOKKOS_DEFAULTED_FUNCTION`` instead of ``KOKKOS_INLINE_FUNCTION``
for explicitly defaulted functions (default constructors, copy constructors, destructors, and ``operator=``).
``KOKKOS_DEFAULTED_FUNCTION`` is defined depending on the CUDA version (< 10.0, it's the same as ``KOKKOS_INLINE_FUNCTION``,  but for >= 10.0, it's empty). This is because starting in CUDA 10, the compiler can generate ``__device__`` versions of defaulted functions as needed, and warns if ``__host__`` and/or ``__device__`` annotations are added explicitly. CUDA 9 still requires the annotations, but also warns if they are added, so Kokkos adds flags to repress the warnings in that case.
@alanw0 There are some changes to STK, so those would …
=> Fix CUDA defaulted function warnings (#7314)

packages/muelu/adapters/xpetra/MueLu_CreateXpetraPreconditioner.hpp, packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp, packages/muelu/doc/UsersGuide/masterList.xml, packages/muelu/doc/UsersGuide/options_general.tex, packages/muelu/doc/UsersGuide/paramlist.tex, packages/muelu/doc/UsersGuide/paramlist_hidden.tex, packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp, packages/muelu/src/MueCentral/MueLu_HierarchyUtils_def.hpp, packages/muelu/src/MueCentral/MueLu_MasterList.cpp, packages/muelu/src/MueCentral/MueLu_VerboseObject.cpp, packages/muelu/src/MueCentral/MueLu_VerboseObject.hpp, packages/muelu/src/MueCentral/MueLu_VerbosityLevel.cpp, packages/muelu/src/MueCentral/MueLu_VerbosityLevel.hpp, packages/muelu/src/Utils/MueLu_Utilities.cpp
Refactor handling of 'verbosity' parameter. Allow use of developer options from easy interface. Fix verbosity bug in RefMaxwell.
Closes #2149
@rstumin
=> MueLu: Allow developer verbosity options in easy interface, fix RefMaxwell bug

packages/tpetra/core/src/Tpetra_Export_def.hpp, packages/tpetra/core/src/Tpetra_Import_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp, packages/tpetra/core/src/Tpetra_transform_MultiVector.hpp, packages/tpetra/core/test/Block/BlockCrsMatrix.cpp, packages/tpetra/core/test/MultiVector/WithLocalAccess.cpp
These are additional fixes identified on a machine with an Nvidia GTX960 card. These errors did not exhibit on white. So this PR extends #7069.
Make Tpetra run with CUDA_LAUNCH_BLOCKING unset.
#7069 
Tpetra tests - these CUDA_LAUNCH_BLOCKING issues were tracked down on a system with a GTX960 card.
=> Tpetra CUDA_LAUNCH_BLOCKING unset fixes

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp
@trilinos/trilinos
Solves a build error when both OpenMP and Cuda are enabled as execution spaces.
Fixes #7339.
=> Tpetra: build error related to default template arguments

packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp, packages/tpetra/core/src/Tpetra_Map_def.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Follows #7069. Changes fence placement to be at the point of error. This addresses comments in #7069 and is intended to make the next step of removing the fences easier.
Also added a modify_device() for the KokkosBlas::gemm call so subsequent host access will properly sync and fence.
Tpetra tests on white with CUDA_LAUNCH_BLOCKING unset.
=> Adjust fences to be at point of error

packages/muelu/src/Transfers/PCoarsen/MueLu_IntrepidPCoarsenFactory_def.hpp, packages/muelu/test/unit_tests/Hierarchy.cpp, packages/muelu/test/unit_tests/IntrepidPCoarsenFactory.cpp
Code failures when CUDA_LAUNCH_BLOCKING is set to 0 are being identified and fixed with addition of fences.
Note that a change to Kokkos is also required for the MueLu test suite to pass with CUDA_LAUNCH_BLOCKING=0. This has been requested:
[https://github.com/kokkos/kokkos/issues/3014](url)
Identify code that fails when CUDA_LAUNCH_BLOCKING is turned off.
Issues were identified by running the MueLu test suite on white.
=> Resolve CUDA_LAUNCH_BLOCKING issues for MueLu  from testing on white

packages/panzer/disc-fe/src/Panzer_FieldManagerBuilder.cpp, packages/panzer/disc-fe/src/Panzer_FieldManagerBuilder.hpp, packages/panzer/disc-fe/src/Panzer_InitialCondition_Builder.cpp, packages/panzer/disc-fe/src/Panzer_ModelEvaluator.hpp, packages/panzer/disc-fe/src/Panzer_ModelEvaluator_impl.hpp, packages/panzer/disc-fe/src/Panzer_PhysicsBlock.cpp, packages/panzer/disc-fe/src/Panzer_PhysicsBlock.hpp
Allow for runtime disable of evaluation types in ModelEvaluator, FieldManagerBuilder,
PhysicsBlock, and InitialConditionBuilder.
Some codes don't need all evaluation types allocated for each analysis. This commit allows codes to disable unneeded evaluation types at runtime.
Achieves memory reduction in EMPIRE.
The added memory structures are tested in all current examples.
=> Panzer: runtime disable of evaluation types

cmake/std/sems/PullRequestCuda9.2TestingEnv.sh
While debugging reproduction issues with #7201 I found that we were using an environment variable that is only set in Jenkins Jobs.  This just uses a built-in variable from bash instead.
@mperego 
This was run on ride-6 from several repositories in differing paths. Output of OMPI_CXX was verified in each case.
=> Remove WORKSPACE env variable as it's not set in most cases

cmake/std/PullRequestLinuxDriverTest.py, cmake/std/unittests/TestPullRequestLinuxDriverTest.py
If not present the testing parallelism will default
to the build parallelism.
This is in response to and closes #7330 
* Closes #7330 
* Blocks #7201 
The python tests have been updated and confirmed on both 2 and 3.
=> Add code to take JENKINS_TEST_WEIGHT from environment if present

cmake/std/atdm/cee-rhel6/environment.sh
So it seems that if you do:
```
$ module purge
$ module load sparc-dev
$ module load sparc-dev/clang-9.0.1_openmpi-4.0.3
```
you get the wrong MPI:
```
$ which mpicc
/usr/local/epd/canopy2/opt/Canopy/edm/envs/User/bin/mpicc
```
But if you just do:
```
$ module purge
$ module load sparc-dev/clang-9.0.1_openmpi-4.0.3
```
you get the correct MPI:
```
$ which mpicc
/sierra/sntools/SDK/mpi/openmpi/4.0.3-clang-9.0-RHEL6/bin/mpicc
```
I don't know how this was missed in my earlier testing.
I was able to reproduce the problem on my CEE RHEL6 machine 'ceerws1113' and then I verified that this change fixed it.
I tested all of the envs on 'ceerws1113' with:
```
$ env Trilinos_PACKAGES=Kokkos,Teuchos ./ctest-s-local-test-driver-cee-rhel6.sh all
***
*** …
```
=> ATDM: cee-rhel6: Remove 'module load sparc-dev' to fix clang-9.0.1-opempi-4.0.3 (ATDV-348)

packages/shylu/shylu_node/tacho/example/Tacho_ExampleExternalInterface.cpp, packages/shylu/shylu_node/tacho/example/Tacho_ExampleExternalInterface.hpp, packages/shylu/shylu_node/tacho/src/Tacho_Solver.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Solver_Impl.hpp
As part of @crdohrm solver work, supernodes interface needs to be exposed. This PR includes the interface. The use case is described in the example "Tacho_ExampleExternalExamplecpp".
=> Tacho - export supernodes info

packages/belos/epetra/test/OrthoManager/CMakeLists.txt, packages/belos/src/BelosOrthoManagerTest.hpp
Integration of the OrthoManager into Belos solvers requires that it is tested, which it hasn't been aside from being used by GCRODR.
The OrthoManagerTest had several typos in it, which were not found
because all tests that used it were essentially disabled.  The
OrthoManagerTest has been fixed and all TSQR-specific tests have
been placed behind an ifdef.  The Epetra interface test for the
OrthoManager has been enabled and the dependency on TSQR has been
removed due to the change in the tester.
Tested on OSX using GCC9
=> Fixes errors in OrthoManagerTest and enables Epetra testing

cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake
Issue 6968
Enabling C++14 for GCC 8.3 PR build.
This will enable C++14 for this PR build. This will not however allow use of C++14 in Trilinos, as other builds enforce C++11. This will merely ensure that changes do not break bulids for which C++14 is enabled.
=> Enable C++14 for GCC 8.3 PR build

packages/belos/epetra/test/BlockGmres/CMakeLists.txt, packages/belos/epetra/test/BlockGmres/test_bl_pgmres_hb.cpp, packages/belos/src/BelosICGSOrthoManager.hpp, packages/belos/src/BelosIMGSOrthoManager.hpp
In both the ICGS and IMGS orthogonalization the calculation of the
newDot values were missing in the blkOrthoSing method.  This method
is only used in block orthogonalization, when the operator for the
linear system is ill-conditioned such that the basis becomes degenerate.
So only BlockGmres and BlockCG could have encountered this issue with
block sizes larger than 1.
In both the ICGS and IMGS orthogonalization the calculation of the
newDot values were missing in the blkOrthoSing method.  This method
is only used in block orthogonalization, when the operator for the
linear system is ill-conditioned such that the basis becomes degenerate.
So only BlockGmres and BlockCG could have encountered this issue with
block sizes larger than 1.
A nightly regression test has been …
=> Adds missing norm in singular vector detector for block orthogonalization

packages/seacas/libraries/exodus/include/exodusII.h, packages/seacas/libraries/ioss/src/exodus/Ioex_IOFactory.C
Use the correct symbol to detect a parallel (MPI) build but a serial NetCDF library.
Should fix #7379
=> SEACAS: Fix parallel build with serial NetCDF issues

packages/sacado/src/Sacado_Traits.hpp
=> Sacado:  Add specializations for ScalarValue, Value for const types.

packages/tempus/src/Tempus_StepperRKAppActionComposite.hpp, packages/tempus/src/Tempus_TimeEventBase.hpp, packages/tempus/src/Tempus_TimeEventComposite.hpp, packages/tempus/src/Tempus_TimeEventList.cpp, packages/tempus/src/Tempus_TimeEventListIndex.cpp, packages/tempus/src/Tempus_TimeEventListIndex_decl.hpp, packages/tempus/src/Tempus_TimeEventListIndex_impl.hpp, packages/tempus/src/Tempus_TimeEventList_decl.hpp, packages/tempus/src/Tempus_TimeEventList_impl.hpp, packages/tempus/src/Tempus_TimeEventRange.cpp, packages/tempus/src/Tempus_TimeEventRangeIndex.cpp, packages/tempus/src/Tempus_TimeEventRangeIndex_decl.hpp, packages/tempus/src/Tempus_TimeEventRangeIndex_impl.hpp, packages/tempus/src/Tempus_TimeEventRange_decl.hpp, packages/tempus/src/Tempus_TimeEventRange_impl.hpp, packages/tempus/src/Tempus_TimeStepControl_impl.hpp, packages/tempus/unit_test/CMakeLists.txt, packages/tempus/unit_test/Tempus_UnitTest_TimeEventBase.cpp, packages/tempus/unit_test/Tempus_UnitTest_TimeEventComposite.cpp, packages/tempus/unit_test/Tempus_UnitTest_TimeEventList.cpp, packages/tempus/unit_test/Tempus_UnitTest_TimeEventListIndex.cpp, packages/tempus/unit_test/Tempus_UnitTest_TimeEventRange.cpp, packages/tempus/unit_test/Tempus_UnitTest_TimeEventRangeIndex.cpp
Add the ability to trigger temporal events, e.g.,
Solution output
Diagnostic output
Restart
Screen dump
Debug
In-situ visualization
User-specified (i.e., observer)
Others?
Ability to specify temporal “events” via
Time and/or time step index
Start and stop times and/or indices
Interval and/or number of “events”
List of times and/or indices
Specify when to trigger “event”
Exactly at the specified time, i.e., adjust timestep to hit output time
If within timestep, output the following timestep, i.e., do not adjust timestep.
Added unit tests to cover, the options.
* Closes #7396 
All tests pass on my Mac.
=> Tempus: Add TimeEvent Object

cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake, cmake/std/atdm/ATDMDisables.cmake, cmake/std/atdm/waterman/tweaks/Tweaks.cmake
Performs the disabled called out in #6329, #6799, #7090
Testing the the configure of everything on 'waterman' for one CUDA build:
```
$ bsub -x -Is -n 20 bash
***Forced exclusive execution
Job <294350> is submitted to default queue <rhel7W>.
<<Waiting for dispatch ...>>
<<Starting on waterman3>>
$ cd /home/rabartl/Trilinos.base/BUILDS/WATERMAN/CHECKIN/
cuda-opt \
--enable-all-packages=on \
--configure
***
*** ./checkin-test-atdm.sh  cuda-opt --enable-all-packages=on --configure
***
ATDM_TRILINOS_DIR = '/home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../..'
ATDM_TRIBITS_DIR = '/home/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/../../../cmake/tribits'
Hostname 'waterman3' matches known ATDM host 'waterman3' and …
```
=> ATDM: Set several CUDA disables (#6329, #6799, #7090)

packages/piro/src/CMakeLists.txt, packages/piro/src/Piro_LOCAAdaptiveSolver_Def.hpp, packages/piro/src/Piro_LOCASolver_Def.hpp, packages/piro/src/Piro_NOXSolver.hpp, packages/piro/src/Piro_NOXSolver_Def.hpp, packages/piro/src/Piro_SteadyStateSolver.hpp, packages/piro/src/Piro_SteadyStateSolver_Def.hpp, packages/piro/src/Piro_TempusSolver_Def.hpp, packages/piro/src/Piro_TransientSolver.hpp, packages/piro/src/Piro_TransientSolver_Def.hpp, packages/piro/test/CMakeLists.txt, packages/piro/test/Main_AnalysisDriver_Tpetra.cpp, packages/piro/test/_input_Analysis_ROL_AdjointSensitivities_OldReducedSpace_Tpetra.xml
Cleaned SteadyStateSolver and made it more similar to TransientSolver.
- Moved computation of adjoint sensitivities from `Piro::NOXSolver` into `Piro::SteadyStateSolver`.
- Renamed function `evalConvergedModel` to more descriptive `evalConvergedModelResponsesAndSensitivities`
Clean and make `Piro::SteadyStateSolver` more consistent in design to the recently added (PR #7359 ) `Piro::TransientSolver` .
Added additional test to exercise adjoint sensitivity computations.
=> Piro: cleaning/refactoring of steady sensitivities

packages/seacas/libraries/ioss/src/main/CMakeLists.txt
A previous commit tried to improve the setting of the path to the
exodiff binary, but mistakenly added a method that only worked on
a preexisting build.  On a clean build, it would result
in an empty symbol which resulted in an empty program name following
the CMND keyword.
This fixes that problem.
Fixes #7420.  We really need to add cgns to at least one of the Trilinos checkin builds.
=> IOSS: Fix setting of exodiff binary in tests

packages/amesos2/src/Amesos2_Factory.hpp
Fixes build errors when using an installed Trilinos that defined
HAVE_AMESOS2_CUSOLVER but not HAVE_AMESOS2_CUSPARSE.
@srajama1 @lucbv
=> amesos2: Fix build ifdef protection of Amesos2_cuSolver.hpp include.

packages/tpetra/core/src/Tpetra_Details_Behavior.cpp, packages/tpetra/core/src/Tpetra_Details_Behavior.hpp, packages/tpetra/core/src/Tpetra_MultiVector_def.hpp, packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
Implements @vbrunini 's changes in #7315 via Tpetra::Details::Behavior environment variables.  Defaults to his value of 10000, but allows anyone to change the threshold via the TPETRA_VECTOR_DEVICE_THRESHOLD environment variable.
* Closes #7315 
Added a couple of long multivector tests.  Existing and new unit tests pass on vesper and eclipse.
=> Tpetra:  Include multivector length in deciding where kernels should run

packages/piro/src/Piro_PerformAnalysis.cpp, packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Constraint_SimOpt.hpp, packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective.hpp, packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective_SimOpt.hpp, packages/rol/src/function/constraint/ROL_ConstraintDef.hpp, packages/rol/src/step/ROL_AugmentedLagrangianStep.hpp, packages/rol/src/step/augmentedlagrangian/ROL_QuadraticPenalty.hpp
@trilinos/rol 
Improve performance by carefully avoiding re-computation of the objective, residual and their gradients when the state and/or control variables are not updated.
improved output messages (mainly for debugging purposes).
Changes are tested in Piro test (collection of tests)  `Piro_AnalysisDriverTpetra`.
=> ROL: changes to Thyra Adapters for SimOpt interface

cmake/std/atdm/ats2/trilinos_jsrun
This retry logic did not generated unique .out file names since some "Command Lines" are exactly the same but post to different ctest "Test" names. To make the retry logic work, we need the ctest "Test" name in the environment in order to generate a uniqe .out file name. This change disables the retry logic and may result in the mass Errors we were trying to work around. The retry code has been commented out but left there in case we need it again in the future.
See atdv-351.
=> ATDM/ats2: Disable hack around error message

packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools.hpp
@crdohrm runs valgrind and the valgrind reports conditional jump based on uninitialized values. Examining the code together, the value is actually initialized where the array is used. However, valgrind misses it and reports it as conditional jump with uninitialized values. For a quality reason, this PR just initialize the temporary work buffer before it is used.
=> Tacho - remove valgrind error (not real error)

packages/epetra/src/Epetra_FECrsMatrix.cpp, packages/epetra/src/Epetra_FECrsMatrix.h
@trilinos/epetra 
This PR addresses issue #7349 . The behavior of GlobalAssemble in the cases where nonlocal matrix is used was slightly different from the case where it wasn't used. In particular, the nonlocal matrix was not zeroed out at the end. If the matrix was then reused later on, old entries were then going to pollute the matrix. Note that calling PutScalar(0.0) on the matrix has no effect on nonlocal entries, since there's no overridde inside the FECrs matrix class.
* Closes #7349 
There are no tests for FECrs matrix with more than 1 rank. I am not sure why that is, but the changes have no effect in case of single rank. Is it ok to run the FECrsMatrix test with 2 ranks?
I also added an override of the Print method, which also prints nonlocal rows. This helped me identifying what …
=> Epetra: zero out nonlocal matrix during GlobalAssemble, plus override Print method

cmake/ctest/drivers/atdm/ats2/drivers/Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_complex_static_opt.sh, cmake/std/atdm/ats2/all_supported_builds.sh
New cuda+complex build to support GEMMA (see [ATDV-300](https://sems-atlassian-srn.sandia.gov/browse/ATDV-300)).
This build initially begins life as a 'Specialized' build as it has some new failing tests that we don't see in other builds.  There we can clean it up.
On the machine 'vortex' I ran this build with:
```
$ cd /vscratch1/rabartl/Trilinos.base/BUILDS/VORTEX/CTEST_S/
$ ./ctest-s-local-test-driver.sh \
ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_complex_static_opt
***
***
Hostname 'vortex60' matches known ATDM host 'vortex60' and system 'ats2'
Using ats2 compiler stack …
```
=> ATDM: ats2: Add cuda+complex build to support GEMMA (ATDV-300)

packages/belos/src/BelosBiCGStabIter.hpp
Fixes #7462
The BiCGStab classes are tested, but not with multiple right hand sides.
=> Fix bicgstab's reinitialization after convergence of a single vector

packages/sacado/src/new_design/Sacado_Fad_Exp_GeneralFad.hpp, packages/sacado/src/new_design/Sacado_Fad_Exp_ViewFad.hpp
For issue #7445.  The new design broke the Albany build.  Two issues (so
far):
* setUpdateValue() disappeared.  I went ahead and re-added it as a
no-op.
* ScalarType<ViewFad<const T,...> >::type is no longer const T.  I fixed
fixed this by adding another partial specialization of ScalarType for
ViewFad.  I chose to go this route instead of adding
const_scalar_type, non_const_scalar_type to all of the Fad classes
because ViewFad is the only Fad type that can have a const
value/scalar type.
=> Sacado:  Fix some Albany build issues with the new design

cmake/std/atdm/common/toss3/environment_new.sh
This fixes the show tests and timeouts reported in [ATDV-357](https://sems-atlassian-srn.sandia.gov/browse/ATDV-357?focusedCommentId=60317&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60317).
I tested this on 'eclipse' with:
```
$ cd /nscratch/rabartl/Trilinos.base/BUILDS/CTS1/CTEST_S/
$ env SLURM_CTEST_TIMEOUT=4:00:00 \
./ctest-s-local-test-driver.sh \
cts1-intel-19.0.5_openmpi-4.0.1_openmp_static_opt
***
***
ATDM_TRILINOS_DIR = '/nscratch/rabartl/Trilinos.base/Trilinos'
Hostname 'eclipse-login1' matches known ATDM host 'eclipse-login1' and system 'cts1'
Using cts1 toss3 compiler stack INTEL-18.0.2_OPENMPI-4.0.1 to …
```
=> Move setting OMP_XXX vars after sparc-dev module loads (ATDV-357)

cmake/std/PullRequestLinuxCudaDriver.sh
Reverts trilinos/Trilinos#7473
I missed the required build changes. With a 9 hour cycle time and the need to set up testing on a fork this will take a bit to fix.
=> Revert "PullRequestLinuxCudaDriver.sh: change from Firestone to Garrison nodes"

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionUtilities.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionVector_def.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/test/unit_tests/RegionMatrix.cpp, packages/muelu/test/unit_tests/RegionVector.cpp
This should accelerate significantly the matvec costs associated with the region format as it now performs only one neighbor communication instead of tow.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #7175
* Composed of 
This work is part of an ASCR project with @rstumin and @lucbv 
Local tests have been performed and so far all are passing except for elasticity problems since this PR only addresses the scalar equation case. A follow-up PR will tackle the multiple dof per node case, in the meantime, a runtime parameter can be selected to use the "slow path" for matvec that works with system of PDEs.
Work remaining before this PR is complete:
1. add capabilities for multiple dofs per node
2. modify the matvec implementation to expose …
=> MueLu: region matvec, see issue #7175

packages/TriKota/test/CMakeLists.txt, packages/TriKota/test/Main_ParallelDiagonalThyraME.cpp, packages/TriKota/test/Main_SimpleEpetraExtME.cpp, packages/rol/adapters/trikota/src/sol/sparse_grids/ROL_QuadratureHelpers.hpp, packages/rol/adapters/trikota/test/sol/CMakeLists.txt
@trilinos/TriKota
These changes address Bug #7466, but more may be needed to preserve some TriKota/ROL tests.
* Part of #7466 
This affects anyone trying to build TriKota with the latest Dakota 6.12 release.
These tests exercise TriKota (run via `ctest -R TriKota`):
```
TriKota_SimpleEpetraExtME .........   Passed    0.05 sec
TriKota_ParallelDiagonalThyraME ...   Passed    0.05 sec
```
There are two additional tests related to trikota adapters in ROL, one which I made inactive via CMakeLists.txt changes, and the other compiles and runs but segfaults.
I'll need guidance from @trilinos/ROL on how to address the ROL tests exercising the trikota adapters.
=> TriKota Bug #7466 : Fixes to build TriKota with Dakota 6.12

packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
Previously, the XML output printed timing nodes as if every node deeper than 2 was a leaf. This meant that every descendant (not just direct children) was plotted in one page in Watchr. This fixes the tree structure. Leaf nodes are always closed with ``/>`` on the same line, and all non-leafs are closed with ``</timing>`` at the same indentation level as the opening ``<timing ...>``. Example output, from MueLu Driver:
```
<?xml version="1.0"?>
<performance-report date="2020-06-11T03:15:54" name="nightly_run_2020_06_11" time-units="seconds">
<timing name="Workstation: MueLu Setup-Solve 1 ranks" value="5.30173">
<timing name="Driver: 1 - Matrix Build" value="0.649667">
<timing name="Galeri: Laplace 3D generation" value="0.348656"/>
<timing name="Galeri: Laplace 3D …
```
=> Teuchos: Fix StackedTimer XML nesting

packages/tempus/doc/Doxyfile, packages/tempus/src/Tempus_StepperSubcycling_impl.hpp, packages/tempus/unit_test/Tempus_UnitTest_Subcycling.cpp
Some minor fixes to compile with and without
-D Tempus_HIDE_DEPRECATED_CODE=ON.
Also added the unit_test directory to the Doxygen.
Pass all tests with and without Tempus_HIDE_DEPRECATED_CODE.
Need to make sure Tempus compiles with Tempus_HIDE_DEPRECATED_CODE on and off.
* Closes #7523  
N/A
All tests pass with Tempus_HIDE_DEPRECATED_CODE on and off.
=> Tempus: Fixes for Subcycling and Deprecated Code

packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HCURL_HEX.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HCURL_QUAD.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HDIV_HEX.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HDIV_QUAD.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HGRAD_HEX.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HGRAD_QUAD.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DirectSumBasis.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_LegendreBasis_HVOL_LINE.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp, packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HCURL.hpp, packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HDIV.hpp, packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HGRAD.hpp
Some Intrepid2 components rely on basis names to track, for example, basis values in a map keyed on the basis name.  These can break if distinct bases return the same name.  This PR adds unique basis names for some recently added basis classes.
Along related lines, prior to this PR certain Intrepid2 components attempted to parse the basis name to determine e.g. function space and topology.  There are already direct methods provided by the basis that can be queried for these things, and the basis names added by this PR do not follow the naming convention assumed by these parsing strategies (tensor bases in this PR have names derived from their components).  In this PR, the direct methods are invoked, and the parsing strategy dropped.
Fixes #7071.
=> Intrepid2: ensure that derived basis classes have unique names

cmake/std/atdm/utils/get_known_system_info.sh
- Due to changes made to get_known_system_info.sh in order to unit test
this code, a bug was introduced on cee machines. The bug causes the script
to select cee-rhel6 instead of sems-rhel7.
```
$ git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
$ source cmake/std/atdm/load-env.sh clang
Hostname <snip> matches known ATDM host <snip> and system 'cee-rhel6'
Setting compiler and build options for build-name 'clang'
Using CEE RHEL6 compiler stack CLANG-9.0.1_OPENMPI-4.0.3 to build DEBUG code with Kokkos node type SERIAL
$ git checkout topic/atdm_swat_get_known_system_info_bug 
Switched to branch 'topic/atdm_swat_get_known_system_info_bug'
Your branch is up to date with 'github-evan/topic/atdm_swat_get_known_system_info_bug'.
$ source …
```
=> atdm/utils: Fix matching bug in get_known_system_info

packages/kokkos-kernels/src/common/KokkosKernels_SparseUtils.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
Remove fence, by moving the CRS row sorting to device.
This should also grant a big speedup, but I didn't measure it.
Fix bug in kokkos-kernels causing divide-by-zero in row sorting
(will copy fix to kokkos-kernels repo).
Fix sign compare warning in MatrixMatrix_Cuda.
Removes one of the Kokkos execution space fences in TpetraExt_MatrixMatrix_def.hpp. One step towards #7446 .
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #7446 
* Composed of 
Part of @MicheldeMessieres 's work to eliminate need for CUDA_LAUNCH_BLOCKING and also to remove unnecessary fences.
- ran all Tpetra tests with launch blocking on
- ran just the MatrixMatrix unit tests with launch blocking off
=> Tpetra: remove fence in add()

cmake/std/PullRequestLinuxCudaDriver.sh, cmake/std/PullRequestLinuxDriverMerge.py, cmake/std/PullRequestLinuxDriverTest.py
Cleaning up some of the Python scripting as I'm looking at installation testing + building an understanding of the Python scripts and how they work.
Executed the python testing suite locally for Python 2.x and 3.x
<details>
<summary>Local Testing Output</summary>
<pre>0 $ ./test_pr_python.sh
========================================================== test session starts ==========================================================
platform darwin -- Python 3.8.0, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/local/bin/python3
cachedir: .pytest_cache
rootdir: /Users/wcmclen/dev/trilinos/trilinos-dev-framework/source/Trilinos/cmake/std
collected 40 items
unittests/TestPullRequestLinuxDriverMerge.py::Test_header::test_writeHeader PASSED …
=> Pr python cleanup

cmake/std/atdm/utils/get_known_system_info.sh
On a compute node via:
```
$ ./get_known_system_info_unit_test.sh 
test_atdm_get_known_system_info
Hostname <snip> matches known ATDM host <snip> and system 'ats1'
Ran 1 test.
OK
$ source cmake/std/atdm/load-env.sh default
Hostname <snip> matches known ATDM host <snip> and system 'ats1'
Using ats1 compiler stack INTEL-18.0.5_MPICH-7.7.6 to build DEBUG code with Kokkos node type SERIAL and KOKKOS_ARCH=HSW
$ source cmake/std/atdm/load-env.sh intel-19
Hostname <snip> matches known ATDM host <snip> and system 'ats1'
Setting compiler and build options for build-name 'intel-19'
Using ats1 compiler stack INTEL-19.0.4_MPICH-7.7.6 to build DEBUG code with Kokkos node type SERIAL and KOKKOS_ARCH=HSW
$ source cmake/std/atdm/load-env.sh …
```
=> atdm/utils: Ensure that HOST does not match on ats1 unit tests

packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter_Def.hpp, packages/piro/src/Piro_TransientSolver_Def.hpp
A few minor cleanups to clarify output from Piro for transient problems.  In particular, gets ride of pesky and confusing "WorkingState is null" warnings.
=> Piro: a couple of cleanups to avoid warnings printed when running code.

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp
This simply uses the proper type for the loop counter.
I have observed that a build with gcc/8.3.0 and -Werror
fails due to the signed-unsigned comparison.
* Closes #7573 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
This is an internal bug fix, not stakeholder
I did a local build with gcc/8.3.0 and it went just fine, the error is gone
=> Tpetra: small type fix, see issue #7573

packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionMatrix_def.hpp, packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp, packages/muelu/test/unit_tests/RegionMatrix.cpp
- The "fast MatVec" reduces the amount of communication to be performed during a MatVec and also exploits the local character of the region data layouts.
- Storage of interface region LIDs is converted from `Array` to `ArrayRCP` so avoid deep copies during the apply phase.
* Closes #7175 
* Follows #7499 
This work is part of an ASCR project with @rstumin and @lucbv.
`ctest -R MueLu_Structured_Region` and regionMG unit tests pass.
=> MueLu: use fast MatVec also for regionMG level transfers

cmake/std/PullRequestLinuxDriverTest.py
@prwolfe 
There are some places where we're setting os environment vars but
using commands like `os.environ[key] = [value]` but a `TypeError`
will be thrown if the value is not a string.
This can happen easily if we set something in `environMap` to be
an integer vs. a string.  For example:
```python
"OMP_NUM_THREADS": 2
```
vs.
```python
"OMP_NUM_THREADS": "2"
```
The latter is what has been done but the first one can be done easily.
The easy solution to this is to try and force the values to strings
at assignment time, `os.environ[key] = str(value)`
See above description from commit comment.  I ran into this working on my installation testing stuff. I had just put the value in and got a `TypeError` from the `os.environ` setting instruction. I fixed my entry in …
=> Framework: PR Driver Script Fix

packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp
Fix the issue that MueLu does not compile when IFPACK2=OFF.
I testes Trilinos with IFPACK2=OFF and this fix
=> MueLu: Fix issues with IFPACK2=OFF in StratimikosSmoother

packages/piro/src/Piro_TempusSolver.hpp, packages/piro/src/Piro_TempusSolver_Def.hpp
Some minor enhancements to Piro::TempusSolver needed for the Albany/LCM code.  In particular, added option to pull initial condition for solution, solution_dot and solution_dotdot from underlying model evaluator, which can be necessary when doing restarts.  All Piro, Albany and LCM tests pass with these changes.
=> Piro: enhancements to TempusSolver for Albany/LCM 

packages/tempus/src/Tempus_IntegratorAdjointSensitivity_decl.hpp, packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
This adds the setObserver() and initialize() functions to the adjoint
sensitivity integrator as requested in issue #7357.  These just call the
corresponding functions on the forward and adjoint integrators.  Note it
is is unclear how observes should work with adjoint sensitivities, so I
did not add the observer to the adjoint integrator.  That can easily be
changed if required.
=> Tempus:  Add setObserver(), initialize() funcs for issue #7357

cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
This turns off one feature that allows these in about 24 minutes. Please remove
when issue #7532 is resolved.
See #7532 
* Part of #7532
I built this by hand on ride and saw the shortened build times expected.
=> The compile times for two Panzer files went up to over 6 hours.

packages/muelu/test/unit_tests/RegionVector.cpp
Fixes an issue with the RegionVector unit test failing.
The test passes on all ranks now.
=> MueLu: fix for RegionVector unit test failing

packages/stk/stk_simd/stk_simd/SimdConfig.hpp, packages/stk/stk_simd/stk_simd/disimd/DISimdBool.hpp, packages/stk/stk_simd/stk_simd/disimd/DISimdBoolF.hpp
Kokkos-SIMD simd_mask type uses a bool underneath in the scalar case.
This leads to uninitialized memory when casting directly to double/float.
@trilinos/stk
=> Fix stk::simd::Bool::operator[] for scalar SIMD.

cmake/std/PullRequestLinuxDriverTest.py, cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake
This will help to protect debug builds for downstream users. No tests will change until the fork on the attester_configs repo is merged.
* Is blocked by #7570 and #7582
This is marked WIP until the testing on my fork completes. That will actually run all the tests using the fork in the config repo.
=> Add gcc 7.2 debug PR setup

packages/belos/tpetra/src/Belos_Details_Tpetra_registerSolverFactory.cpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov.hpp, packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov_parameters.hpp, packages/belos/tpetra/test/Native/diagonal_matrix.cpp, packages/belos/tpetra/test/Native/nonsymm_matrix.cpp
This PR 
1. adds GmresSstep (and Gmres and Cg) to the list of registered native Tpetra solvers
2. adds a few tricks to improve the robustness of the GmresSstep
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Needed by ExaWind.  Related to https://github.com/Exawind/nalu-wind/pull/643.
I ran ctest for Belos on Blake
=> add GmresSstep to the list of registered native Tpetra solvers

cmake/std/PullRequestLinuxClang10.0.0TestingSettings.cmake, cmake/std/PullRequestLinuxDriverTest.py, cmake/std/sems/PullRequestClang10.0.0TestingEnv.sh, cmake/std/unittests/TestPullRequestLinuxDriverTest.py
This will add the capability to run a Clang 10.0.0 PR build.
Currently there are only Clang 7.0.1 and 9.0.0 PR builds available.
Closes #7589 
This has been tested by manually running a Clang 10.0.0 build in Jenkins successfully.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=clang_10.0.0&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=84&value3=NOW)
This leaves previously excluded tests as is. #6940 #6941 #6942
See associated cmake file.
=> Create Clang 10.0.0 PR Build

packages/tempus/src/Tempus_StepperRKButcherTableau.hpp
- SSPERK22
- SSPERK33
Add error estimator for selected explicit schemes to be available for applications.
=> Tempus: add error estimator for selected methods

packages/panzer/disc-fe/src/Panzer_PhysicsBlock.cpp
#7337 introduced the capability to disable evaluation types at runtime. However, there seemed to be some errors in panzer::PhysicsBlock::buildAndRegisterGatherAndOrientationEvaluators. This should hopefully fix that. Seems to be working to disable tangent evaluation types in drekar.
=> Panzer: Fixing evaluation type conditionals in equation set gather registration.

packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp
Was trying to scale a Scalar with double. This doesn't work if Scalar
is complex<float>, since that overload of ``operator*`` doesn't exist.
Now scaling with magnitudeType instead, which should work in all cases.
Fixes build error with ``Trilinos_ENABLE_COMPLEX_FLOAT`` and ``Tpetra_ENABLE_TESTS``.
Error was impacting @jennloe 's build.
Error was in a test. The semantics of the test didn't change.
=> Tpetra: fix scalar error in test

cmake/std/atdm/cee-rhel6/environment.sh
This should fix the mass
On 'ceerws1113' I ran:
```
$ env Trilinos_PACKAGES=Kokkos ./ctest-s-local-test-driver-cee-rhel6.sh all
***
*** /scratch/rabartl/Trilinos.base/Trilinos/cmake/std/atdm/ctest-s-local-test-driver.sh
***
ATDM_TRILINOS_DIR = '/scratch/rabartl/Trilinos.base/Trilinos'
Hostname 'ceerws1113' matches known ATDM host 'ceerws1113' and system 'cee-rhel6'
Setting compiler and build options for build-name 'cee-rhel6-default'
Using CEE RHEL6 compiler stack CLANG-9.0.1_OPENMPI-4.0.3 to build DEBUG code with Kokkos node type SERIAL
Running builds:
cee-rhel6_clang-9.0.1_openmpi-4.0.3_serial_static_opt
cee-rhel6_gnu-7.2.0_openmpi-4.0.3_serial_shared_opt
cee-rhel6_intel-18.0.2_mpich2-3.2_openmp_static_opt …
```
=> Put back the LD_LIBRARY_PATH to fix intel-18 test failures (ATDV-272)

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests0.cpp, packages/tpetra/core/test/CrsMatrix/Tpetra_Test_CrsMatrix_WithGraph.hpp, packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_def.hpp
@trilinos/tpetra @trilinos/ifpack2 
NOTE:  for the best reviewing experience,  hide diffs due to whitespace
(some loops went away, so loop bodies moved over two spaces)
While examining fences for #7446, we discovered that Tpetra was computing fields (involving two fences and reduceAll) that were no longer used.  Fields lowerTriangular_, upperTriangular_, nodeNumDiags_, and globalNumDiags_ were computed, but they were not used in Tpetra nor were accessors available for their use elsewhere. 
These fields should have been removed with the deprecations in #2630 and #2644.  
These changes remove computation of the fields in computeLocalConstants() and computeGlobalConstants().  They change the interface to computeGlobalConstants(), but this function seemed to be called only from Xpetra, so I …
=> tpetra:  removing computation of unused fields

packages/tpetra/core/src/Tpetra_DistObject_def.hpp, packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
@kyungjoo-kim Addresses comments in #7446 to move fence as late as possible. The second one (line 1141) I can confirm via testing. The first one (line 1080) does not fail tests if I remove it, but I think we need it as well.
white Cuda build
=> Tpetra: Better placement of pack fences

packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
This PR equips the MatrixMarket reader with more descriptive error messages in case of non-existing/non-open files to be read.
Check, if the file to be read could actually be opened. Throw exception, if not. 
This throws an exception right away, instead of causing downstream errors when trying to read a non-openend/non-existing file.
While I added these tests for debugging of some block methods in MueLu, this is rather general capability and is not associated with any particular project.
`ctest` with Tpetra tests enabled succeeds.
=> Tpetra: add safety check to matrix market reader

packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_FECrsMatrix_def.hpp, packages/tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp, packages/tpetra/core/test/MatrixMatrix/CMakeLists.txt, packages/tpetra/core/test/MatrixMatrix/FECrs_MatrixMatrix_UnitTests.cpp, packages/tpetra/core/test/Tpetra_TestingUtilities.hpp
This PR adds a set of constructors to FECrsGraph, which accept a domain map for the owned+shared graph. Before this PR, the owned+shared graph and the owned graph were both created with the same _domain_ map, which, by default, was taken to be the owned row map. This caused the owned+shared dof map in the owned+shared graph to not be locally fitted to the graph's column map, which can cause issues in FE codes assembly that partition the mesh by elements. In such codes, during FE assembly kernels, one may only have the owned+shared dofs map available (coming from a discretization or connectivity object), and not the col map of the matrix. When converting the GIDs of the dofs in the element to local ordinals (in order to assembly the local matrix) one _needs_ the local ids …
=> Tpetra: new constructor for FECrsGraph accepting owned+shared domain map

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp, packages/kokkos-kernels/src/common/KokkosKernels_Controls.hpp, packages/kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, packages/kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp, packages/kokkos-kernels/src/sparse/KokkosSparse_spmv.hpp, packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spmv_spec.hpp, packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_decl.hpp, packages/nox/test/tpetra/ME_Tpetra_1DFEM_def.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp, packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_decl.hpp, packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_Details_getGraphDiagOffsets_decl.hpp, packages/tpetra/core/src/Tpetra_Details_localDeepCopyRowMatrix_decl.hpp, packages/tpetra/core/src/Tpetra_Details_localDeepCopyRowMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_localRowOffsets_decl.hpp, packages/tpetra/core/src/Tpetra_LocalCrsMatrixOperator_decl.hpp, packages/tpetra/core/src/Tpetra_LocalCrsMatrixOperator_def.hpp, packages/xpetra/src/CrsGraph/Xpetra_CrsGraph.hpp, packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp
Because of the way ``CrsMatrix::local_matrix_type::size_type`` was chosen in Tpetra, the size_type was ``unsigned int`` for node type Cuda. This meant that all sparse kernel calls from Tpetra were silently falling back to the non-ETI'd, native Kokkos implementation, and never using cuSPARSE or the precompiled ETI versions.
Also instantiating the cuSPARSE spmv wrapper for CudaUVMSpace, which is required for Tpetra to use it. For cuSPARSE 10+, with the generic API, added int64_t/size_t ordinal/offset versions in addition to the int/int. Added single and double complex support (see https://github.com/kokkos/kokkos-kernels/issues/726). Checking that the "Controls" parameter exists before trying to get its value. Fixed the constness of the Controls …
=> Fix KokkosKernels/Tpetra ETI interaction

packages/belos/src/BelosCGSingleRedIter.hpp
@trilinos/Belos
When using the Belos - single reduction CG solver with a convergence folding option, a residual (`rHr_`) is using an incorrect array index which causes slower convergence of the solver.
Issued here: https://github.com/trilinos/Trilinos/issues/7680
Tested by comparing the number of iterations with the standard CG solver in Trilinos.
@agsalin  and @rstumin  confirmed this bug in other project meeting.
=> A residual bug fix in the Belos single CG solver (fix #7680)

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
modified:   Ifpack2_BlockTriDiContainer_impl.hpp
Silence unused var warnings when MPI is not enabled
=> ifpack2: silence warning when mpi is not enabled

packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
@jhux2 As discussed in #7446 I have moved the fence to allReduceView. I think we may only need the fence for the 1st allReduceView where need_sync_host is true. If the data was modified on host it should already be fenced regarding UVM access. I verified via testing.
Cuda build - confirmed using PR #7446 setup.
<!---
=> Tpetra: Update MultiVector fences

packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
The hierarchy description is cached. The first time it is used is in Hierarchy->Iterate. This change caches it already in setup.
=> MueLu: Cache hierarchy description in setup

packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp, packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp, packages/tpetra/core/src/Tpetra_DistObject_def.hpp, packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp, packages/tpetra/tsqr/test/Tsqr_TestDistTsqr.cpp, packages/tpetra/tsqr/test/Tsqr_TestNodeTsqr.cpp
Get rid of unused typedef warnings on EWS blades (CEE-LAN) using the default toolchain for Sierra builds.
Confirmed Tpetra test suite is still passing after these changes.
=> Tpetra: Fix some compile-time warnings with sierra-devel toolchain

packages/teuchos/comm/src/Teuchos_DefaultMpiComm.hpp, packages/teuchos/comm/test/Comm/DefaultMpiComm_UnitTests.cpp, packages/thyra/adapters/tpetra/src/Thyra_TpetraThyraWrappers.cpp
@trilinos/teuchos @trilinos/thyra 
Conversion from a Tpetra comminicator to a Thyra communicator resulted in a MPI_Bcast call to determine the tag of the new communicator. With this change, Tpetra and Thyra communicator use the same tag, and no MPI_Bcast is necessary.
=> Tpetra Thyra adapter: Avoid MPI_Bcast

packages/kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, packages/kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
In cuSPARSE SpMV wrapper, handle the mode ConjugateTranspose, which maps to CUSPARSE_OPERATION_CONJUGATE_TRANSPOSE. Before, this was being ignored and it had the same behavior as "normal" mode.
Gives expected behavior when mode is "H" (conjugate transpose). Now, the cusparse SPMV gives the same behavior as KokkosKernels native spmv when the mode is "H".
* Closes #7690 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Broke Thyra test. Also possibly broke EMPIRE but not sure about that yet (@cgcgcg).
This behavior is tested by Thyra
=> KokkosKernels: fix conjugate-transpose cusparse spmv (#7690)

packages/shylu/shylu_node/tacho/src/Tacho_Solver.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Blas_Team.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Copy_Internal.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Copy_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Internal.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Lapack_Team.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_LevelSetTools.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_ModifyDiagonals.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_ModifyDiagonals_Internal.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_ModifyDiagonals_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Solver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeChol.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveLowerChol.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveUpperChol.hpp
@crdohrm requested a feature of superpanel inversion version for triangular solve. This PR includes the implementation. This will match the performance to the target application needs.
=> Tacho solver algorithm variant 2.

packages/tpetra/core/src/Tpetra_idot.hpp, packages/tpetra/core/test/Comm/CMakeLists.txt, packages/tpetra/core/test/Utils/behavior.cpp
Refactor idot. Main things are factoring out duplicated code, avoiding redundant View allocation/initialization/copies, and ensuring correctness for non-CUDA aware MPI. 140 net lines of code removed.
Originally started with just reviewing Kokkos fences with #7446 (minimal fences but correctness without CUDA_LAUNCH_BLOCKING). Then I thought I could refactor to make it way shorter and simpler, but that mostly didn't pan out because of the UVM + MPI potential issue. But there's still a net removal of code, slight improvements to performance and a guarantee of correctness with CudaSpace or CudaUVMSpace and non-CUDA aware MPI. I don't think an error here has been observed, but @jjellio has told me that UVM and non-CUDA aware MPI can cause unpredictable failures on some …
=> Refactor idot

packages/shylu/shylu_node/tacho/src/impl/Tacho_LevelSetTools.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_SetIdentity_Internal.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_SetIdentity_OnDevice.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Solver_Impl.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeChol.hpp
While inverting super panels, this PR reduces a trsm one time. This also set the default algorithm variant as 2. The reason is that the particular application of our interest runs at least 10 times of solve runs. For such case, the cost of inverting panels can be amortized. 
@crdohrm
=> Tacho - improve variant 2 version and set the default algorithm as the variant 2

packages/piro/src/Piro_TempusSolver_Def.hpp
Updating list of Explicit steppers recognized by Piro::TempusSolver to reflect current explicit stepper supported in Tempus.  This is needed for Albany/LCM.
=> Piro: updating list of Explicit steppers recognized in TempusSolver

packages/kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_avail.hpp, packages/kokkos-kernels/src/impl/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp
Fix the version check used the type-generic cuSPARSE API:
replace ``CUDA_VERSION >= 10010`` with
``defined(CUSPARSE_VERSION) && CUSPARSE_VERSION >= 10300``
Fixes build error, where kokkos-kernels tried to use features of cuSPARSE 10.3 and above when the cuSPARSE version was lower. This fixes the version check to see if those features are available. I think out of commonly used CUDA versions, this issue only affects 10.1.105, as seen by @jewatkins .
* Closes #7723 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
This build error can only be triggered by building with CUDA 10.1.105, which isn't used in PR testing or nightly ATDM testing. But, I did a build with this version on RIDE, replicated #7723, and verified that this …
=> KokkosKernels: Fix cuSPARSE version check (#7723)

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp, packages/kokkos-kernels/src/batched/KokkosBatched_Copy_Internal.hpp
Using team parallel blas and lapack kernels, thread distribution over the matrix is better to remain the same so that we do not need to put a team barrier. Carefully examining the code, I put the barrier where is indeed necessary. The error due to this thread distributions over the matrix is not well caught in unit test as it only shows when threads are very busy and expericence context switching a lot (in my opinion).
@csiefer2 confirms that 1 gpu and 2gpu solutions are same.
=> Ifpack2 - fix race for thread mapping mismatch

cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_debug_muelu_coverage_geminga.cmake
Link was failing:
hidden symbol `__gcov_merge_add' in /mnt/watson/sems/install/rhel7-x86_64/sems/compiler/gcc/5.3.0/base/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/libgcov.a(_gcov_merge_add.o) is referenced by DSO
Adding "-lgcov" fixes the error for me locally.
This is a developer feature.
I reproduced the failure locally and verified that this patch fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/7746)
=> Muelu: fix coverage testing on geminga

packages/seacas/libraries/ioss/src/cgns/Iocgns_StructuredZoneData.C, packages/seacas/libraries/ioss/src/main/cgns_decomp.C, packages/seacas/libraries/ioss/src/main/io_info.C, packages/seacas/libraries/ioss/src/utest/Utst_structured_decomp.C
Improve the cgns structured mesh decomposition to produce more "squarish" slices.  It was creating decomp zones that were a single cell wide (128x57x1) which maximized surface area and failed SPARC sanity checks.  
The decomp is now better and tries to produce better decomp zones.  It is still possible to create a zone which is a single cell wide, but this should be very rare.  Will continue to improve decomp, but comitting this now so SPARC can try it.
=> IOSS: cgns - improve structured decomposition

packages/muelu/test/unit_tests/Hierarchy.cpp
@csiefer2 This PR just removes a comment. The test is working fine for the Pascal node and white. It's possible I was testing on Kepler before, which we recently decided is not relevant for CUDA_LAUNCH_BLOCKING=0. Or perhaps ongoing Tpetra work has fixed it. But it seems perfectly fine now.
=> MueLu: Remove outdated comment.

packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp, packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp, packages/muelu/test/interface/default/Output/MLsmoother4_tpetra.gold, packages/muelu/test/interface/default/Output/default_e3d_tpetra.gold, packages/muelu/test/interface/default/Output/default_p2d_tpetra.gold, packages/muelu/test/interface/default/Output/default_p3d_tpetra.gold, packages/muelu/test/interface/default/Output/driver_drekar1_np4_tpetra.gold, packages/muelu/test/interface/default/Output/driver_drekar1_tpetra.gold, packages/muelu/test/interface/default/Output/driver_drekar2_np4_tpetra.gold, packages/muelu/test/interface/default/Output/driver_drekar2_tpetra.gold, packages/muelu/test/interface/default/Output/smoother12_tpetra.gold, packages/muelu/test/interface/default/Output/smoother13_tpetra.gold, packages/muelu/test/interface/default/Output/smoother5_tpetra.gold, packages/muelu/test/interface/default/Output/smoother9_tpetra.gold, packages/muelu/test/interface/kokkos/Output/MLsmoother4_tpetra.gold, packages/muelu/test/interface/kokkos/Output/default_e3d_tpetra.gold, packages/muelu/test/interface/kokkos/Output/default_p2d_tpetra.gold, packages/muelu/test/interface/kokkos/Output/default_p3d_tpetra.gold, packages/muelu/test/interface/kokkos/Output/driver_drekar1_np4_tpetra.gold, packages/muelu/test/interface/kokkos/Output/driver_drekar1_tpetra.gold, packages/muelu/test/interface/kokkos/Output/driver_drekar2_np4_tpetra.gold, packages/muelu/test/interface/kokkos/Output/driver_drekar2_tpetra.gold, packages/muelu/test/interface/kokkos/Output/smoother12_tpetra.gold, packages/muelu/test/interface/kokkos/Output/smoother13_tpetra.gold, packages/muelu/test/interface/kokkos/Output/smoother5_tpetra.gold, packages/muelu/test/interface/kokkos/Output/smoother9_tpetra.gold
Remove some inner product and norm calls from Chebyshev power method, since they are not needed.
This can be done, since the power iteration performs a prescribed number of iterations.
Add parameter "chebyshev: eigenvalue normalization frequency" that allows to skip normalization in every step of the power method, reducing the number of global communication even further.
=> Ifpack2 Chebyshev: Remove unneeded global communication

packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
@kddevin @kyungjoo-kim 
For fences in Tpetra_CrsGraph.hpp we discussed the possibility of tracking the state of the graph to validate whether it needed fencing. This PR is a draft of how that might look so opening this so we can discuss if this is what we had in mind.
Having set this up, we can probably reduce the number of fence calls to about 1/2, as measured by running all unit tests. However I'm wondering if this extra complexity is worth it. It seems it would be better to just do the simple thing and always call  Kokkos::fence() before the various UVM host access places.
Note I removed the fence before maxDifference which is on device so I think that fence is not actually needed regardless of our plan for CrsGraph.
=> Tpetra: Add state tracking for graph to avoid extra fencing.

packages/ifpack2/src/Ifpack2_Details_MultiVectorLocalGatherScatter.hpp, packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestChebyshev.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRBILUK.cpp, packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
Adds fencing so that Ifpack2 unit tests will pass on white Cuda builds with CUDA_LAUNCH_BLOCKING=0.
Note this is tested stacked on top of ongoing work for Tpetra so this will not work stand alone with CUDA_LAUNCH_BLOCKING=0. I suggest we accept the addition of these fences and then address removal of individual fences with separate PRs that refactor as needed.
Tested on Cuda white builds stacked on ongoing Tpetra work to fix fences. Also tested on Mac parallel. This PR just adds fences and sync_host calls.
=> Ifpack2: Resolve CUDA_LAUNCH_BLOCKING=0

packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
@kddevin This fence is needed to pass the following Ifpack2 tests:
Ifpack2Relaxation_double_int_longlong_TestLowerTriangularBlockCrsMatrix_UnitTest
Ifpack2Relaxation_double_int_longlong_TestUpperTriangularBlockCrsMatrix_UnitTest
This is the only Tpetra change that came up while working on Ifpack2 so I'm adding it as a separate PR. I'll add this fence to our fence survey PR as we may want to follow up with changes to remove it.
=> Tpetra: Ifpack2 fence fix

packages/tpetra/core/CMakeLists.txt
...and Kokkos enables CUDA. 
Allow Tpetra to build without CUDA without implicitly assuming `Kokkos_ENABLE_CUDA` implies `Tpetra_ENABLE_CUDA`.
A Trilinos build with **serial** Tpetra was required that had `Kokkos_ENABLE_CUDA` without `Kokkos_ENABLE_CUDA_UVM`. Previously, a CMake assert error was not allowing this case. 
It is rare to need Kokkos CUDA but not a CUDA(w/ UVM) enabled Tpetra, so this change should impact no current users.
Tested on Waterman (P9/Volta). Ensured that the target build case builds.
=> Tpetra: Edit CMakeLists to not check for Kokkos UVM if Tpetra disables CUDA

packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp, packages/zoltan2/core/src/models/Zoltan2_CoordinateModel.hpp
Change empty subviews to be allocated with second extent.
So extent(0) and extent(1) could be 0,2 respectively, instead of 0,0.
Then MJ can still take the subview and proceed naturally
without making extra checks.
@kddevin This is to clean up an issue we had discussed months ago.
Cuda white and Mac parallel/serial builds. Zoltan2 MJ tests.
=> Zoltan2: Clean up subview issues

packages/rol/example/tempus/example_parabolic_modeleval_forward-adjoint.hpp
It looks to me like this assert is not always
valid as the test at line 529 will return false
if the trans requested is not Thyra::NOTRANS.
The test does in fact call it with Thyra::TRANS.
This is part of setting up debug builds for the PR testing system
* Closes #7582 
* Blocks #7581 
This was run in a gcc 7.2 build using DEBUG settings from PR 7581
=> I commented out an assert to get debug tests to run

cmake/std/atdm/van1-tx2/environment.sh
Fixes the build error with Sacado on van1-txt2 reported in #7778 
On 'stria' I did:
```
$ env Trilinos_PACKAGES=Sacado ./ctest-s-local-test-driver.sh \
van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_opt
***
***
ATDM_TRILINOS_DIR = '/lustre/rabartl/Trilinos.base/Trilinos'
Hostname 'stria-login1' matches known ATDM host 'stria-login1' and system 'van1-tx2'
Using ARM ATSE compiler stack ARM-20.0_OPENMPI-4.0.2 to build DEBUG code with Kokkos node type SERIAL
Running builds:
van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_opt
Wed Aug  5 10:51:47 MDT 2020
Running Jenkins driver Trilinos-atdm-van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_opt.sh ...
See log file …
```
=> ATDM: Unload yaml-cpp module for arm-20.1 env (#7778)

packages/tempus/src/Tempus_StepperDIRK_decl.hpp, packages/tempus/src/Tempus_StepperDIRK_impl.hpp, packages/tempus/src/Tempus_StepperExplicitRK_decl.hpp, packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_Partition_decl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp, packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp, packages/tempus/src/Tempus_StepperRKBase.hpp, packages/tempus/src/Tempus_StepperRKModifierXBase.hpp, packages/tempus/test/TestModels/DahlquistTestModel_decl.hpp, packages/tempus/test/TestModels/DahlquistTestModel_impl.hpp, packages/tempus/unit_test/Tempus_UnitTest_ERK.cpp
Add unit tests to further test the StepperRKAppActions for ExplicitRK
with FSAL on/off, with embedded error estimation, and solver failures.
Miscellaneous:
* Removed stageX_ as it was an alias to workingState in the RK methods,
and was causing confusion.
* Moved set/getUseEmbedded() and associated RK error data to RKBase.
* Cleaned up accessing xDot within the ExplicitRK methods.
* Removed stageZ_ from the IMEX methods as it was an alias to
workingState and was causing confusion.
All tests pass on a Mac/GCC.
Provide additional testing for the RKAppAction for Explicit RK methods, especially for FSAL, embedded error estimation, and timestep failure.
* Closes #7770 
@seamill is the requestor and stakeholder who wanted these additional tests.
New tests have been added to …
=> Tempus: Add Further Testing for Explicit RKAppAction

packages/muelu/adapters/aztecoo/MueLu_AztecEpetraOperator.cpp, packages/muelu/adapters/epetra/MueLu_EpetraOperator.cpp
Some functions in MueLu adapters were still using the the xpetra shortname `Xpetra::EpetraCrsMatrix`, which seems to have been mostly replaced by `Xpetra::EpetraCrsMatrixT<GO,NO>`. All functions in MueLu adapters now use the templated name.
Relates to the following Drekar issues:
rppawlo/DrekarBase#468
rppawlo/DrekarBase#455
=> MueLu: switch from shortname EpetraCrsMatrx to full EpetraCrsMatrixT

packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
@brian-kelley I expect we should use sync_host here instead of fence. Possibly this would eventually go to a kernel anyways.
I'm not sure about the proper application of modify_host here.
Tested on Cuda white.
=> Ifpack2: Use sync_host instead of fence

packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
Moves fence to be at the latest point for consistency with Tpetra conventions.
Tested via #7794.
=> Ifpack2: Move fence to be more consistent with Tpetra conventions.

packages/teuchos/numerics/src/Teuchos_SerialDenseHelpers.hpp
If you use an MPI build of Trilinos, but only perform single node execution, this class will crash in the situation where MPI has not been initialized.  So, a different communicator needs to be used for this situation.  Now the method checks if it's an MPI build and if MPI has been initialized before using an MPI communicator.  Otherwise, it uses a serial communicator. 
Tested on OSX, with OpenMPI and Clang compilers
=> Adds logic for MPI builds where MPI has not been initialized

packages/amesos2/src/Amesos2_Basker_def.hpp, packages/amesos2/src/Amesos2_Cholmod_def.hpp, packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_decl.hpp, packages/amesos2/src/Amesos2_KLU2_def.hpp, packages/amesos2/src/Amesos2_KokkosMultiVecAdapter_decl.hpp, packages/amesos2/src/Amesos2_Kokkos_View_Copy_Assign.hpp, packages/amesos2/src/Amesos2_MultiVecAdapter_decl.hpp, packages/amesos2/src/Amesos2_MultiVecAdapter_def.hpp, packages/amesos2/src/Amesos2_Superlu_def.hpp, packages/amesos2/src/Amesos2_Tacho_def.hpp, packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_decl.hpp, packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp, packages/amesos2/src/Amesos2_cuSOLVER_def.hpp
The solver gets the x and b data from the adapter and it may be directly assigned (no deep copy) if memory and types match. This PR adds a flag bInitialize so the 'get x' call can inform the adapter that initializing the data is not necessary. This means that when the adapter does not match and has to allocate the data for x, it won't deep copy its x values into the x space. That was a wasted copy before since the solve was going to overwrite x anyways.
Also the get x or get b calls now receive a bDidAssign flag to tell the solver if the data is pointing directly to the adapter memory space. If x is directly assigned, there is no need to 'put x' after the solver and this can now be skipped.
Also SuperLU and Klu2 may modify b during the solve under some conditions. If the …
=> Amesos2: Handle x and b copying more efficiently.

packages/shylu/shylu_node/tacho/src/Tacho_CrsMatrixBase.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_Blas_Team.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveLowerChol.hpp, packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveUpperChol.hpp
Some C++14 compilers have a compiler bug in lambda capturing. This PR includes the workaround.
@crdohrm
=> Tacho - c++14 compiler bug workaround

packages/panzer/dof-mgr/test/fe_assembly/test_fe_assembly_HEX.cpp, packages/panzer/dof-mgr/test/fe_assembly/test_fe_assembly_HEX.hpp
Improved Fe Assembly test by using new `Tpetra::FECrsGraph` constructor added by @bartgol in #7253. 
This constructor ensures that the local ids owned+shared row map and the matrix column map corresponds to the same global ids and allows to save computing the local ids of the column map.
This PR includes a couple of minor fixes suggested by @jewatkins and a sharper bound  on the max number of nonzeros per row.
=> Panzer: DofManager, use new Tpetra::FECrsMatrix constructor

packages/teko/src/Tpetra/Teko_BlockingTpetra.cpp, packages/teko/src/Tpetra/Teko_InterlacedTpetra.cpp
Don't assign -1 to `size_t` variables, instead use `OrdinalTraits<..>::invalid()`.
=> Teko: Fix sign warnings

packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp
@trilinos/tpetra @trilinos/muelu 
Change the default algorithm for Jacobi smoothing of MueLu prolongators from MSAK to the KK option implemented by @seheracer.
Tests on white P100, all matrices 1M rows, 100 setups each, timer "SaPFactory_kokkos: Xpetra::IteratorOps::Jacobi":
**one single rank, all computation, no communication**
|matrixType|MSAK|KK|
|--|--|--|
|Laplace2D | 3.863 |3.318  |
|Laplace3D |5.05  | 4.339 |
|Brick3D | 5.889 | 5.366 |
These cases give ~10-15% improvement.
**8 ranks, little computation, a lot of communication**
|matrixType|MSAK|KK|
|--|--|--|
|Laplace2D | 27.74 | 17.76 |
|Laplace3D |23.65  | 15.07 |
|Brick3D | 23.46 | 16.22 |
These cases give ~30-36% improvement.
@trilinos/muelu, what else should we test before merging?
=> Tpetra: Change default algorithm for matrix Jacobi from MSAK to KK

cmake/ctest/drivers/atdm/ats2/local-driver.sh, cmake/std/atdm/ats2/environment.sh, cmake/std/atdm/ats2/trilinos_jsrun
Fixes mass test failures on 'ats2' which started 2020-08-11.  (See commit and internal file comments and [ATDV-387](https://sems-atlassian-srn.sandia.gov/browse/ATDV-387).
On 'vortex' from the login node 'vortex60' I ran:
```
$ cd /vscratch1/rabartl/Trilinos.base/BUILDS/VORTEX/CTEST_S/
$ env Trilinos_PACKAGES=TeuchosCore \
./ctest-s-local-test-driver.sh \
ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_opt
***
***
Hostname 'vortex60' matches known ATDM host 'vortex60' and system 'ats2'
Using ats2 compiler stack GNU-7.3.1_SPMPI-ROLLING to build DEBUG code with Kokkos node type SERIAL
Due to …
```
=> ATDM: Remove checks for running on login and launch nodes (ATDV-387)

packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
This PR adjusts some of the MueLu parameters that Sphynx uses. 
Sphynx tests are passing in my CUDA build.
=> Zoltan2 Sphynx: Adjust MueLu parameters

cmake/std/PullRequestLinuxDriverTest.py, cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake
Found a missing config entry during testing
This was found when running the Debug job from Jenkins by hand. I will replicate that directly and note the results here.
=> Add Debug build into config map

packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp, packages/muelu/research/regionMG/src/SetupRegionMatrix_def.hpp, packages/muelu/research/regionMG/src/SetupRegionSmoothers_def.hpp, packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp, packages/muelu/test/unit_tests/RegionMatrix.cpp
A newer MatVec implementation for region MG is available, which pre-computes the communication pattern during the setup phase to save one round of communication during the apply phase. We have used both implementations in parallel for some time to gain confidence in the new one.
Now, this PR removes the old implementation, which always did two rounds of communication during the apply phase.
This work is part of an ASCR project with @rstumin and @lucbv.
Still some trouble w/ the unit tests... cf. #7832 
❗ This PR builds upon changes in PR #7830, so merge this PR only after PR #7830 has been merged.
=> MueLu: remove "old" regionMG MatVec w/ doubled communication

packages/fei/base/fei_EqnCommMgr.cpp
From his email -
I don't know if any other ASC apps are using the FEI package in Trilinos but we (Sierra) have come across a compiler issue on stria related to this package. We're using the ARMHPC 20.1 toolset. The following is our work around. Can this get incorporated into the Trilinos repo?
This is required for the 20.1 toolset on astra - see above
This came in from the Sierra project and was tested via their work. Currently none of the dashboard lines on astra build FEI, so any additional testing will need to be done by hand or fed added.
=> FEI patch for astra from Mike glass.

packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp, packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp
The user is now allowed to disable the check that ensures that for each
owned element, there is at least one owned node. This check is helpful
to keep the column map optimally sized, but for some application it might
be difficult to rearrange the mesh ownership, to the point that it might
be easier to accept a small performance hit during mat-vec product (due
to import of not needed gids).
Fixes #7697.
The FECrsGraph class checks (in debug mode) that there are no owned elements for which none of the nodes is owned, since it means we will import unnecessary entries during mat-vec products.
However, some apps (in this case, Albany) may be dealing with meshes coming from TPLs, and/or might have a hard time redistributing mesh entities, so that this does not occur. While we …
=> Tpetra: optionally disable ownership check in FECrsGraph

packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp, packages/stk/stk_mesh/stk_mesh/base/FieldParallel.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshCommImplUtils.cpp, packages/stk/stk_mesh/stk_mesh/baseImpl/MeshCommImplUtils.hpp
Also remove a debug-print statement that crept in recently.
=> Patch an issue that seems unique to certain clang builds.

cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake
Both of these work on a command line and the DART
variable has been shown not to work in PR testing.
About 70% of debug jobs are failing on 4 common timeouts.
This was tested by hand, but it is unknown how the results will perform in PR testing under ctest.
=> Change test timeouts from DART_TESTING_TIMEOUT to CTEST_TEST_TIMEOUT

packages/tempus/test/DIRK/Tempus_DIRK_ASA.cpp, packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_ASA.cpp, packages/tempus/test/HHTAlpha/Tempus_HHTAlphaTest.cpp
It appears that general changes (not an explicit Tempus change)
have increased the runtime on the debug runs, thus timing out.
These failing tests take 6-8 seconds on Mac Laptop in optimized mode,
but over 10 minutes on some platforms in debug mode?!
Reduced the runtime by eliminating the finest time resolution in the
order verification tests.  This reduced the runtime by about half.
Trilinos testing is timing out on supported platforms for these tests.  Need to fix in order to maintain tests/coverage on these platforms.
* Closes #7853 
Trilinos framework.
These are changes to tests.
=> Tempus: Timeouts on Explicit ASA, DIRK ASA and HHT-Alpha Tests

packages/sacado/src/Kokkos_DynRankView_Fad.hpp
These changes mirror the changes in:
https://github.com/kokkos/kokkos/pull/3244
Resolves a phalanx test to pass for CUDA_LAUNCH_BLOCKING=0. Keeps DynRankView_Fad consistent with DynRankView and View fence conventions.
Sacado and Phalanx unit tests on white.
=> Sacado: Make DynRankView_Fad fencing consistent

packages/intrepid2/unit-test/Cell/test_03.hpp, packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases/SubBasisInclusionTests.cpp, packages/intrepid2/unit-test/Discretization/FunctionSpaceTools/test_03.hpp, packages/intrepid2/unit-test/Discretization/Integration/test_util.hpp, packages/intrepid2/unit-test/Projection/test_convergence_HEX.hpp, packages/intrepid2/unit-test/Projection/test_convergence_QUAD.hpp, packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp, packages/intrepid2/unit-test/Projection/test_convergence_TRI.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_HEX.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_QUAD.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_TET.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_TRI.hpp, packages/intrepid2/unit-test/Shared/Polylib/LegendreJacobiPolynomials/IntegratedJacobiTests.cpp
To get Intrepid2 passing all unit tests with CUDA_LAUNCH_BLOCKING=0 in preparation for further work to analyze core fences in panzer.
White Cuda Intrepid2 test suite.
=> Intrepid2 fences for CUDA_LAUNCH_BLOCKING=0

packages/intrepid2/src/Cell/Intrepid2_CellToolsDefPhysToRef.hpp, packages/intrepid2/unit-test/Discretization/Basis/HGRAD_HEX_C1_FEM/test_02.hpp, packages/intrepid2/unit-test/Shared/ArrayTools/test_01.hpp, packages/intrepid2/unit-test/Shared/ArrayTools/test_02.hpp, packages/intrepid2/unit-test/Shared/ArrayTools/test_03.hpp, packages/intrepid2/unit-test/Shared/ArrayTools/test_04.hpp, packages/intrepid2/unit-test/Shared/ArrayTools/test_05.hpp, packages/intrepid2/unit-test/Shared/RealSpaceTools/test_01.hpp
I'm not sure we'd want to do things this way, but opening the PR for discussion.
We need to fence the Serial vectorNorm for UVM. However the Serial vectorNorm is also used as the core of the kernel form, when we would not want to fence. We could resolve as in this PR, or fence every call of Serial vectorNorm which I don't think we'd want, or perhaps design this a different way.
Potentially this is a backwards compatibility issue if external code is using Serial vectorNorm in device kernels.
To get Intrepid2 passing all unit tests with CUDA_LAUNCH_BLOCKING=0 in preparation for further work to analyze core fences in panzer.
White Cuda Intrepid2 test suite.
=> Intrepid2: vectorNorm fencing

packages/amesos2/src/Amesos2_Basker_TypeMap.hpp, packages/amesos2/src/Amesos2_Basker_decl.hpp, packages/stokhos/src/sacado/kokkos/vector/amesos2/Amesos2_Basker_MP_Vector.hpp
@trilinos/amesos2 @trilinos/stokhos 
Resolve inconsistency in Basker TypeMap. This change is potentially a backwards compatibility issue if users have customized the TypeMap (similar to how Stokhos changes it).
@ndellingwood This is the change I mentioned earlier. I think we will want to do this. This is not going to fix anything, as the change is just to make things conventionally consistent. I believe the original use of static may have been an artifact of copying from the SuperLU solvers.
=> Amesos2: Stokhos: Fix Basker TypeMap to not use static for dtype

packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp, packages/tempus/src/Tempus_StepperRKButcherTableau.hpp, packages/tempus/test/BDF2/Tempus_BDF2Test.cpp, packages/tempus/test/BDF2/Tempus_BDF2_ASA.cpp, packages/tempus/test/BDF2/Tempus_BDF2_FSA.hpp, packages/tempus/test/BDF2/Tempus_BDF2_SinCos_AdaptDt.xml, packages/tempus/test/BDF2/Tempus_BDF2_SinCos_SA.xml, packages/tempus/test/TestModels/DahlquistTestModel_decl.hpp, packages/tempus/test/TestModels/DahlquistTestModel_impl.hpp, packages/tempus/unit_test/Tempus_UnitTest_ERK_ForwardEuler.cpp
While debugging an issue with Albany, it turns out that for
useFSAL=true and with one stage, Explicit RK does not correctly
calculate the update for the next time step, i.e., evalModel() will
never be called.
* Changed the default useFSAL to true for RK Forward Euler.  This
matches Forward Euler stepper.
* Added xDot to Dahlquist test problem for unit testing.
- New constructor allows construction with or without xDot
- Added xDot to nominalValues() and getExactSolution().
* Added unit test to cover this bug.
* BDF2 used RK Forward Euler as a startup stepper. Switched it
to RK Explicit Midpoint, which is second order.  This allowed BDF2
to remain second order, but the overall error decreased.  With the
new default useFSAL=true, the workingState->getXDot() was updated
by …
=> Tempus: Bug in RK Forward Euler with FSAL

packages/muelu/test/unit_tests/NotayAggregationFactory.cpp
When using more than two ranks, as the mesh is
elongated in the y axis only, middle ranks do not
have boundary conditions and yield a different
number of aggregates compare to rank 0 and n-1.
One of MueLu's unit-test is failing... that's no good!
* Closes #7860
internal fix, not stakeholder
Tested the new unit-test implementation in serial and with 4 ranks.
Both versions of the test are passing.
=> MueLu: quick fix for NotayAggregates unit-test

packages/panzer/dof-mgr/src/Panzer_Filtered_GlobalIndexer.cpp
putScalar will by default write to device.
replaceGlobalValue will always write to host.
So we can sync_host like this after putScalar to make sure the device write
is synched for UVM to host before replaceGlobalValue.
Then since replaceGlobalValue does not call modify_host, I think we need
to call this afterwards. That won't be necessary for UVM, but later if
device is CudaSpace, then skipping that call means the export will be confused
about where the data is and try to pull it from device.
An alternative is to call modify_host before the putScalar calls.
Then the putScalar will write to host and we can skip the modify_host
calls after the replaceGlobalValue. This might be confusing as I'm not
sure calling modify_host to force putScalar to host is a normal pattern.
Also I think that is …
=> Panzer: Fix PanzerDofMgr_tFilteredUGI_MPI_2 test for CUDA_LAUNCH_BLOCKING=0

packages/panzer/disc-fe/test/evaluator_tests/dof_basistobasis.cpp, packages/panzer/disc-fe/test/evaluator_tests/dof_pointfield.cpp
Not sure if we want to use MDField in this way since it has a lot of built in support. Maybe we want to add some host support as well. But I think this can be a final solution.
Get Panzer tests passing for CUDA_LAUNCH_BLOCKING=0.
Cuda white disc-fe tests
=> Panzer: Fix MDField reads for host

packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
@rppawlo If we accept this PR, then I can proceed to get Panzer passing tests with CUDA_LAUNCH_BLOCKING=0. I'lll follow up with a PR which tags all fences in Panzer just for discussion purposes. Then we can return and fix these loops after discussion.
If we want to fix these loops now I'll need to discuss. This is clearly not a final solution. I expect we may do a single parallel_for kernel over the full range of all loops. Ifpack2 has some scatter methods with similar issues.
Get Panzer passing for CUDA_LAUNCH_BLOCKING=0 prior to analyzing and resolving fences in panzer which will be a second phase of the project.
Cuda white panzer DiscFE tests.
=> Panzer: Add fences for BasisValues2

packages/muelu/test/maxwell/CMakeLists.txt
@cgcgcg 
This PR adds a bit of CMake logic to enable a MueLu/Stratimikos test only, if Stratimikos is actually enabled in the CMake configuration.
None.
When enabling `Stratimikos` in the build, the test `MueLu_Maxwell3D-Tpetra-Stratimikos_MPI_4` is executed and passes. If `Stratimikos` is disabled, the test is not executed and the test suite passes.
=> Muelu: guard Stratimikos test via CMake

packages/phalanx/src/Phalanx_DAG_Manager_Def.hpp
Adds fence before the call to evaluateFields. Note this is not exactly what we discussed (which was the fence afterwards) but I think this is more correct, and temporary anyways. Either way will pass the tests. I see many evaluateFields use UVM directly so I think we want to protect all of them before. It may be a coincidence it passes the other way.
I suggest we merge this fence which will complete panzer to pass all unit tests with CUDA_LAUNCH_BLOCKING=0. Then I will open a discussion PR which adds a tag on all fences. Refactoring each of the evaluateFields to not use UVM might be the next logical thing for me to work on. As a first step I think we may want to remove this fence and add it in every evaluateFields method that uses UVM. Then we can refactor one at a time …
=> Panzer: Protect evaluateFields with fence

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp, packages/panzer/adapters-stk/test/stk_interface_test/CMakeLists.txt, packages/panzer/adapters-stk/test/stk_interface_test/tExodusRestartAndAppend.cpp
Exodus restarts always created a new file (different name or overwrite). This allows for appending directly to the restart file.
This capability is required for EMPIRE FY20 milestone. Verified with the team that this meets requirements. See EMPIRE issue 1508.
New unit tests added to exercise capability:
```
9/13 Test #10: PanzerAdaptersSTK_tExodusRestartAndAppend_MPI_2 ..........   Passed    0.59 sec
```
=> Panzer: add append to restart support for stk_interface and exodus

packages/sacado/src/KokkosExp_View_Fad.hpp, packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp
@etphipp For Tpetra we removed fences after kernels and placed them before the actual UVM reads. Removing these fences will still pass all unit tests with CUDA_LAUNCH_BLOCKING=0. These are the only core fences in Sacado. I am not sure if we want to remove them.
Removing fences from core code.
Sacado tests on white Cuda
=> Sacado: Fence review

cmake/std/PullRequestLinuxDriver.sh, cmake/std/PullRequestLinuxDriverMerge.py
@prwolfe @jwillenbring Since this is messing with the top level .sh driver script, let's chat about this one before we merge it.  Manual testing looks ok but we'll want to merge this when we know we'll be around to monitor it in case we need to revert. 😉 
The current set of scripts that drive the PR testing have a known issue that can cause problems when either of these two scripts are modified:
1. `cmake/std/PullRequestLinuxDriver.sh` - Top level script that is called by Jenkins in a PR test.
2. `cmake/std/PullRequestLinuxDriverMerge.py` - Python script that handles merging the incoming branch into the target branch.
When either of these two scripts are modified, the incoming changes do not actually get tested by the PR system since the scripts themselves are loaded …
=> Framework: PR Driver Script Change Detection

packages/kokkos/cmake/kokkos_tribits.cmake
Avoids double header installation of Kokkos files through TriBITS
Addresses header install issue in https://github.com/trilinos/Trilinos/issues/7907
=> keep TriBITS from double-installing Kokkos header files

packages/muelu/research/regionMG/CMakeLists.txt, packages/muelu/research/regionMG/example/CMakeLists.txt, packages/muelu/research/regionMG/example/amg_1dof.xml, packages/muelu/research/regionMG/example/elasticity_3d.xml, packages/muelu/research/regionMG/example/poisson_3d.xml, packages/muelu/research/regionMG/example/structured_unstructured_1dof.xml
@lucbv @pohm01 @rstumin 
Reproduce the examples, that we will include in the paper on region MG.
* Follows the source code restructuring done in PR #7830 
This work is part of an ASCR project with @rstumin and @lucbv.
All tests pass locally.
=> Muelu: add region MG examples

packages/piro/src/Piro_TrapezoidRuleSolver.hpp, packages/piro/src/Piro_TrapezoidRuleSolver_Def.hpp
=> Piro: Add accessors needed for Arctic Coastal Erosion thermomechanical coupling in Albany

packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp, packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp, packages/panzer/adapters-stk/test/stk_interface_test/tExodusRestartAndAppend.cpp
append only added new steps to the end of the file. apps requested ability to append anywhere in the file.
Approved by empire team in EMPIRE MR 1221.
Added unit tests in test/stk_interface_test/tExodusRestartAndAppend.cpp
=> Panzer: restart append can now overwrite previous exodus steps

packages/panzer/adapters-stk/example/CurlLaplacianExample/main.cpp, packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/main.cpp, packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp, packages/panzer/adapters-stk/example/ModelEvaluator/main_driver.cpp, packages/panzer/adapters-stk/example/PoissonExample/main.cpp, packages/panzer/adapters-stk/example/PoissonInterfaceExample/main.cpp, packages/panzer/adapters-stk/example/PoissonInterfaceTpetra/main.cpp, packages/panzer/adapters-stk/example/main_driver/main_driver.cpp, packages/panzer/adapters-stk/tutorial/siamCse17/main.cpp, packages/panzer/adapters-stk/tutorial/step01/main.cpp
Resolves failures on ride/white systems
@rppawlo I also tried with CUDA_LAUNCH_BLOCKING=0 and then just 2 examples failed:
PanzerMiniEM_MiniEM-BlockPrec_Augmentation_MPI_1
PanzerMiniEM_MiniEM-BlockPrec_Augmentation_MPI_4
I'll resolve those as a separate PR.
These examples were failing on ride/white. 
Ride Cuda build - Panzer tests and examples
=> Panzer: Kokkos::initialize after Teuchos::GlobalMPISession

cmake/std/PullRequestLinuxDriver.sh, cmake/std/PullRequestLinuxDriverMerge.py
@prwolfe 
@jwillenbring 
The calls to `subprocess.check_output()` in the Merge script do not return the same thing in python2 and python3 in this code:
https://github.com/trilinos/Trilinos/blob/6761d1a2013f02edd5dfbefbb3c7f2f1e7c62d9e/cmake/std/PullRequestLinuxDriverMerge.py#L93-L94
In python2 the output is a string object and the comparison in line 94 is valid, but in Python3 the type of `remote_list` will be a `bytes` object which throws a `TypeError` in the comparison in line 94.
The easiest way I know of to fix this that is both Python2 and 3 compatible is to `decode` the output from the `check_output()` call into a utf-8 object by adding `remote_list = remote_list.decode('utf-8')`. This will convert the `bytes` object into a `unicode` object in Python2 and a …
=> Framework: PullRequestLinuxDriverMerge.py py2-3 compatibility fix

packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasisFamily.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HCURL_HEX.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HCURL_QUAD.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HDIV_HEX.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HDIV_QUAD.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_DirectSumBasis.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasisFamily.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_NodalBasisFamily.hpp, packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp, packages/intrepid2/src/Projection/Intrepid2_LagrangianInterpolationDef.hpp, packages/intrepid2/unit-test/Orientation/test_orientation_HEX_newBasis.hpp, packages/intrepid2/unit-test/Orientation/test_orientation_QUAD_newBasis.hpp, packages/intrepid2/unit-test/Projection/test_convergence_HEX.hpp, packages/intrepid2/unit-test/Projection/test_convergence_TET.hpp, packages/intrepid2/unit-test/Projection/test_convergence_TRI.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_HEX.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_QUAD.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_TET.hpp, packages/intrepid2/unit-test/Projection/test_interpolation_projection_TRI.hpp
With this addition it is possible to use the new basis framework and in particular the Derived Nodal Basis similarly to the legacy basis
- added getDofCoeffs to the new basis famework
- added (legacy) triangle and tet basis to the DerivedNodalBasis
- added testing for interpolation/projection of DerivedNodalBasis
=> Intrepid2: enable interpolation with DerivedNodalBasis

packages/teko/tests/testdriver.cpp, packages/teko/tests/testdriver_tpetra.cpp
@rppawlo I was cleaning up and checking Teko as a dependence of Panzer. This is the same issue as the Panzer examples we just merged.
Some Teko tests would not pass on ride/white due to Kokkos::initialize out of order with the GlobalMPISession.
Teko tests for CUDA build on white
=> Teko: Fix tests to run on ride/white

packages/zoltan2/core/src/input/Zoltan2_InputTraits.hpp, packages/zoltan2/test/core/unit/input/InputTraitsBad.cpp, packages/zoltan2/test/core/unit/input/InputTraitsGood.cpp
Zoltan2 has tests to ensure scalar_type is usable by Zoltan2.
It had previously excluded scalar_type = long long.
But now Tpetra's default global ordinal type is long long.  So if we want to apply geometric partitioning to matrix / tensor indices as coordinates, we need to allow scalar_type long long.
Tested on mac with clang.
=> Zoltan2: allow scalar_type = long long when Tpetra instantiates it

packages/teko/src/Teko_Utilities.cpp
Resolves Teko to pass with CUDA_LAUNCH_BLOCKING=0
@rppawlo This gets Teko passing with launch blocking off and also resolves that one panzer example that was failing. We may want to refactor this code as a kernel in the next phase when we remove UVM usage.
Get Teko passing with CUDA_LAUNCH_BOCKING=0
Teko tests on white CUDA build
=> Teko: fix tests cuda launch blocking off

cmake/tribits/ReleaseNotes.txt, cmake/tribits/ctest_driver/TribitsCTestDriverCore.cmake, cmake/tribits/ctest_driver/TribitsCTestDriverCoreHelpers.cmake, cmake/tribits/doc/developers_guide/TribitsDevelopersGuide.rst, cmake/tribits/examples/TribitsExampleProject/cmake/ctest/CTestCustom.cmake.in, cmake/tribits/python_utils/gitdist-setup.sh
This pulls in the TriBITS changes shown at:
* https://github.com/TriBITSPub/TriBITS/compare/6165385bda2cb968e036530f9718bbcecbef704f..d953bd2620f1c94e22b96a977797758e45396c0a?expand=1
The addresses TriBITSPub/TriBITS#326  and https://github.com/TriBITSPub/TriBITS/commit/990ebeeb60be76433c64888cc508937c314f51ca and otherwise little other issues.  See the list of commits at:
* https://github.com/TriBITSPub/TriBITS/commits/d953bd2620f1c94e22b96a977797758e45396c0a
after the commit https://github.com/TriBITSPub/TriBITS/commit/6165385bda2cb968e036530f9718bbcecbef704f.
Merging this will give us full build stats for platforms like 'ats2' and 'cts1' as part of #7376 and #7508.
The TriBITS test suite was run and 100% passed (see evidence in commit …
=> Fix CDash test output truncation for ATDM Trilinos builds

packages/tpetra/core/test/Core/ScopeGuard_user_inits_mpi.cpp, packages/tpetra/core/test/Core/initialize_user_inits_mpi.cpp
These tests would have this output error:
Kokkos::Cuda ERROR: Failed to call Kokkos::Cuda::finalize()
If user called Kokkos::initialize user should also call Kokkos::finalize.
This will resolve the tests so they do not generate the above output.
Note this is not a pass/fail issue.
The test was passing but just had the error showing up in the log.
This came up while doing some work to clean up these tests to pass for CUDA_LAUNCH_BLOCKING=0.
Cuda white Pascal Tpetra unit tests
=> Tpetra: Fix initialize tests to call Kokkos::finalize

packages/muelu/src/Graph/HybridAggregation/MueLu_HybridAggregationFactory_def.hpp, packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_def.hpp
Fixes the interface aggregation for region structured-unstructured to allow for any structured coarsening rate. Before only a structured coarsening rate of 2 or 3 was supported.
Also fixes a typo in MueLu_TrilinosSmoother_def.hpp concerning a debugging message for Ifpack2.
Passes the region structured-unstructured tests.
The typo in MueLu_TrilinosSmoother_def.hpp came up in a build with both Epetra and Tpetra enabled related to rppawlo/DrekarBase#468
=> MueLu: region structured unstructured interface aggregate fix

packages/zoltan2/test/core/directory/directoryTest_Impl.hpp, packages/zoltan2/test/core/directory/directoryTest_KokkosSimple.cpp, packages/zoltan2/test/core/directory/directoryTest_findUniqueGids.cpp
Fix directory tests to run on white Cuda for Pascal nodes
white Cuda build
=> Zoltan2: Fix directory tests to run on ride/white with pascal node

packages/xpetra/src/Utils/Xpetra_Parameters.hpp
Previously, --help showed Epetra and Tpetra as valid --linAlgebra
options, even if Epetra was disabled in Xpetra.  Now Epetra will
show as a valid "linAlgebra" option only if Epetra is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/7970)
=> Xpetra: fix documentation

packages/xpetra/src/Map/Xpetra_EpetraMapFactory.cpp, packages/xpetra/src/Map/Xpetra_MapFactory_decl.hpp, packages/xpetra/src/Map/Xpetra_MapFactory_def.hpp, packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp, packages/xpetra/test/Map/CMakeLists.txt, packages/xpetra/test/Map/MapFactory_UnitTests.cpp
When creating blocked systems, it is useful to be able to create maps with GID offsets. This PR enhances an existing `MapFactory::Build()` variant to accept such an offset. For backwards compatibility, the offset defaults to `0`.
Summary of changes:
- add unit tests for `MapFactory::Build()`
- add possibility to pass a user-defined GID offset to `MapFactory::Build(nodeMap, numDofsPerNode)`
- add some documentation
None.
This PR adds unit tests.
~~I'm not sure, if I got the ETI stuff for the new unit test file right. Any suggestions for improvement are welcome!~~
EDIT: Squashed my attempts to fix compiler warnings into one commit.
=> Xpetra: update and test MapFactory

packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
Convert deep_copy to 3-arg
Cuda white Pascal node launch blocking off - Tpetra tests
=> Tpetra: Convert computeOffsets deep_copy to use 3-arg

packages/muelu/test/scaling/CMakeLists.txt
Always use SerialNode when comparing Tpetra vs. Epetra SpMV performance. This is to make a fair comparison, when CudaNode is enabled for Tpetra. Currently will just affect the performance testing build on Vortex, since Stria and Eclipse were already using SerialNode only.
N/A
=> MueLu: Use SerialNode for Epetra vs. Tpetra test

packages/sacado/src/KokkosExp_View_Fad.hpp, packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp, packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
@csiefer2 @kddevin Just FYI
@etphipp Adds 3-arg deep_copy specializations for Stokhos. This is needed for current work to refactor Tpetra to use 3-arg deep_copy. (#7975 #7971 for example).
2 questions for this:
(1) I duplicated a chunk of code which is not desirable. I can fix this but wanted to get some rough guidance from you first how you'd like this organized. If we accept this PR I could work on fixing that and proceed with Tpetra work in parallel.
(2) I see some other 3-arg deep_copy overloads for Stokhos don't use the ExecSpace.  For the new methods I added, I just changed all internal deep_copy calls to 3-arg using the ExecSpace. I wasn't sure if there might be reasons not to do this.
Refactor Tpetra deep_copy calls to use 3-arg deep_copy.
Mac serial build and …
=> Stokhos: Add 3-arg deep_copy specializations.

packages/tpetra/core/test/CMakeLists.txt, packages/tpetra/core/test/KokkosIntegration/CMakeLists.txt, packages/tpetra/core/test/KokkosIntegration/KokkosUVM.cpp
A simple UVM test that directly uses Kokkos can rule out some of the complexities of Tpetra proper as potential issues in understanding profiling results.
N/A
The basic concept of this test is to fill a UVM view on host, modify it on device, which I expect to force UVM to migrate the data to device, then modify again on host, which I expect to force a migration back to host.
Running on vortex, the Caliper output I got using David Poliakoff's formula which @csiefer2 passed on to me, does not clearly show this movement:
```
function                     alloc.label#cupti.fault.addr cupti.uvm.kind sum#sum#cupti.uvm.bytes
65536.000000
Kokkos::View::initialization                                                        65536.000000
modify on host …
```
=> Tpetra: Kokkos-only test for UVM data movement
