trilinos/Trilinos

- cmake/tribits/ci_support/CDashQueryAnalyzeReport.py
- cmake/tribits/doc/developers_guide/TribitsDevelopersGuide.rst
- cmake/tribits/python_utils/gitdist.py
Main purpose is to bring in TriBITSPub/TriBITS#287 so that @jmgate  and EMPIRE can use this. 
This also brings in some other minor TriBITS changes but they don't impact Trilinos at this point.
> Automatic snapshot commit from tribits at 83aecff

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
Experimental options for different prolongators in RefMaxwell and rebalancing.
> MueLu+RefMaxwell stuff

- packages/tempus/src/Tempus_StepperFactory.hpp
- packages/tempus/src/Tempus_StepperRKButcherTableau.hpp
- packages/tempus/test/DIRK/Tempus_DIRKTest.cpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
> Tempus add ssp rk methods

- packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
- packages/xpetra/test/Cloner/Cloner_UnitTests.cpp
> Partial6190 revert

- packages/ifpack2/src/CMakeLists.txt
- packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_Parameters.cpp
Fuse ScaledDampedResidual and update kernels into one Chebyshev kernel. This is a blatant rip-off of @mhoemmen's work.
> Ifpack2: Fuse all Chebyshev kernels into one

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Switch to 'mat=mat' algorithm instead of 'gustavson' for all node types.
> MueLu RefMaxwell: Run same algo for special prolongator for all node types

- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_decl.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp
> Ifpack2: Adding support for additional ext information for OverlappingRowMatrix

- packages/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp
- packages/kokkos/core/src/Kokkos_HPX.hpp
- packages/kokkos/core/src/Kokkos_Serial.hpp
- packages/kokkos/core/src/OpenMP/Kokkos_OpenMP_Team.hpp
- packages/kokkos/core/src/Threads/Kokkos_ThreadsTeam.hpp
- packages/kokkos/core/unit_test/TestTeamTeamSize.hpp
Compilation error when using `Kokkos::MinMax` with team/thread
parallel_reduce Trilinos Issue  #6000
> Apply Kokkos PR 2499 to Trilinos/develop

- packages/xpetra/src/Operator/Xpetra_TpetraOperator.hpp
> Xpetra: Fixing something that probably never worked #6293

- packages/ml/src/RefMaxwell/ml_RefMaxwell.cpp
- packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp
> ML: Fixes to RefMaxwell default behavior

- packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.cpp
- packages/ml/src/RefMaxwell/ml_FaceMatrixFreePreconditioner.cpp
> ML: Moving output to higher verbosity level

- packages/tempus/src/Tempus_SolutionStateMetaData_decl.hpp
- packages/tempus/src/Tempus_SolutionStateMetaData_impl.hpp
- packages/tempus/src/Tempus_SolutionState_decl.hpp
Prep work for error control for EMPIRE.
> Tempus: Add Cleanup of Error Tolerances.

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
This might help diagnose load-imbalance.
> MueLu RefMaxwell: Print more matrix stats

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
- packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
- packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp
- Add option to print rank with max time.
- Take min only over active ranks.
> Stacked timer changes

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Utils/MueLu_PerfUtils_def.hpp
- Print min/max ranks in PerfUtils.
- Add more control for sub-hierarchy placement in RefMaxwell
> MueLu: load balancing

- packages/ml/src/Utils/ml_MultiLevelPreconditioner_Aux.cpp
> ML: Fixing memory leak

- packages/tpetra/core/example/advanced/Benchmarks/CrsMatrixDenseRowUnpack.cpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_PackUnpack.cpp
Speed up unpack for dense CrsMatrix rows, corresponding to bulk nodes in Aria.
* Closes #6313 
* Related to #962 
See TF-1264.
> Tpetra: Fix #6313  (and build warnings)

- packages/tempus/src/Tempus_StepperIMEX_RK_decl.hpp
See Issue #6351 
Closes #6531
Tested with EMPIRE
> Tempus: Add getters to stepper imex rk

- packages/ml/src/Coarsen/ml_amg.c
- packages/ml/src/Coarsen/ml_amg.h
- packages/ml/src/Coarsen/ml_amg_MIS.c
- packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.cpp
- packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp
- packages/ml/test/RefMaxwell/cxx_main.cpp
> ML: More experimental coarsening hooks

- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_decl.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp
> Ifpack2: Return of the s-step PR

- packages/ml/src/Coarsen/ml_agg_genP.c
- packages/ml/src/Operator/ml_operator.c
- packages/ml/src/Operator/ml_operator.h
- packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp
- packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp
- packages/ml/test/MultiLevelPreconditioner_Sym/MultiLevelPreconditioner_Sym.cpp
- packages/ml/test/RefMaxwell/cxx_main.cpp
> ML: More experimental coarsening stuff

- packages/ml/examples/BasicExamples/ml_aztec_simple.c
- packages/ml/examples/Elasticity/ml_example_elasticity.c
- packages/ml/src/Main/ml_struct.c
- packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp
- packages/ml/src/Utils/ml_MultiLevelPreconditioner_Defaults.cpp
- packages/ml/src/Utils/ml_MultiLevelPreconditioner_Filtering.cpp
- packages/ml/src/Utils/ml_MultiLevelPreconditioner_Smoothers.cpp
- packages/ml/src/Utils/ml_ValidateParameters.cpp
- packages/ml/src/Utils/ml_amesos.c
- packages/ml/src/Utils/ml_amesos.h
- packages/ml/src/Utils/ml_amesos_wrap.cpp
- packages/ml/src/Utils/ml_amesos_wrap.h
- packages/ml/src/Utils/ml_aztec_utils.c
- packages/trilinoscouplings/src/ml/NonlinML/ml_nox_nonlinearlevel.cpp
- packages/trilinoscouplings/src/ml/NonlinML/ml_nox_preconditioner1.cpp
- packages/trilinoscouplings/src/ml/NonlinML/nlnml_nonlinearlevel.cpp
- packages/trilinoscouplings/src/ml/NonlinML/nlnml_preconditioner1.cpp
> ML: A kinder, gentler version of the Amesos MPI_Comm_split fix DO NOT MERGE

- packages/tempus/src/Tempus_StepperDIRK_decl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_Partition_decl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_decl.hpp
Add Getters to Stepper IMEX RK Partition and DIRK.
Also added getter for xTilde.
> Tempus: Add Getters to Stepper IMEX RK Partition

- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Removed an unused view and repair view allocations to indicate sizes according to dimension.
This resolves #6358 which could have errors or hang when KOKKOS_ENABLE_DEPRECATED_CODE was off.
Resolve #6374
Tested by the multijagged testes in zoltan2.
> Zoltan2: Fix view allocations for deprecated off (#6374)

- packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp
- packages/ml/src/Utils/ml_MultiLevelPreconditioner_Smoothers.cpp
> ML: Fixing comm split stuff

- packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
Prefix Zoltan2 MJ debug information with MueLu level number so that we can distinguish rebalancing on several levels.
> MueLu Zoltan2Interface: Dump Zoltan2 debug info prefixed by level number

- packages/zoltan2/test/correctness/zoltanCompare.cpp
Trilinos' default global ordinal type will soon switch to long long.
Test zoltanCompare compares Zoltan2 results with Zoltan results for PHG, RCB, RIB, etc.
Since PHG hashes global ordinals, all global ordinals must be passed to the library in the same format.  If Zoltan2 uses global ordinal = long long, Zoltan must use NUM_GID_ENTRIES=2 and pass each GID in an array of two ZOLTAN_ID_TYPE.
Previously, this test assumed global ordinal = int.  These changes allow it to work with global ordinal = int or long long.
Changes were required only in the test file; no changes to the Zoltan or Zoltan2 libraries were needed.
#6388 #5602 
N/A
Tested on cee lan with gcc 7.3 and gcc 8.3, with and without Tpetra_ENABLE_DEPRECATED_CODE (that is, with default global ordinal = int and …
> Zoltan2:  allow test using zoltan to pass with default long long global_ordinal type

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- Dump to file as soon as object has been created. This makes it easier to debug setup issues.
- Nuke edge BCs in D0 after creating (2,2) hierarchy
- Allow iterating more than 1 it on sub-hierarchies.
- Fix ETI off build.
- Display edge length stats in verbose output.
> MueLu RefMaxwell fixes

- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
This is expected to fix #6423. We meant to have the reduceAll calls on host and this was still using device buffers.
Zoltan2 has 17 tests which run this code.
> Expected to fix issue #6423

- packages/xpetra/src/BlockedCrsMatrix/Xpetra_MapExtractor_def.hpp
Closes issue #6322 .
@ccober6 reports that this fixes compile error on Macs.
Compile fix only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6437)
> Xpetra: fix issue 6322

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Add a timer that includes both sub-hierarchies for RefMaxwell, as well as data movement. This should help to better understand timings with rebalanced subsolves.
> MueLu RefMaxwell: Add timer for the two subsolves

- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgPuLP.hpp
- packages/zoltan2/test/driver/CMakeLists.txt
- packages/zoltan2/test/driver/driverinputs/CMakeLists.txt
- packages/zoltan2/test/driver/driverinputs/pulpVwgtTest.xml
- packages/zoltan2/test/driver/driverinputs/pulpVwgtTestNoDistrib.xml
- packages/zoltan2/test/driver/driverinputs/xtrapulpVwgtTest2.xml
- packages/zoltan2/test/driver/driverinputs/xtrapulpVwgtTest2NoDistrib.xml
- packages/zoltan2/test/unit/environment/AllParameters.cpp
Integration of multi-weight partitioning for XtraPuLP-0.3. 
Updates to Zoltan2_AlgPuLP.hpp and relevant testing files.
'ctest' completes successfully.
Most recent XtraPuLP version available via: https://github.com/HPCGraphAnalysis/PuLP
> Zoltan2:Zoltan2xtrapulp - integration of XtraPuLP-0.3 into Zoltan2 for multi-weight partitioning

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Tests: Maxwel3D (RHEL6,SerialNode)
> MueLu: Adding Aux Aggregation Support to RefMaxwell

- packages/belos/src/BelosGmresPolyOp.hpp
- packages/epetraext/src/restrict/EpetraExt_RestrictedMultiVectorWrapper.cpp
- packages/epetraext/src/transform/EpetraExt_Reindex_LinearProblem.cpp
- packages/epetraext/src/transform/EpetraExt_Reindex_LinearProblem2.cpp
- packages/galeri/src-epetra/Galeri_ReadHB.cpp
- packages/isorropia/utils/ispatest_lbeval_utils.cpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
Fix some random warnings I've been seeing:
-using uninitialized var
-misleading indentation
-set-but-unused var
-catch polymorphic object (std::exception) by value
@trilinos/isorropia 
@trilinos/epetraext 
No issue for these
> Fix misc. warnings

- packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp
> MueLu: Removing needless initialization

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp
- packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp
For transposed operands, Tpetra::MatrixMatrix::add() didn't request the RowMatrixTransposer to sort rows because it can work with unsorted rows. But the transpose graph still reported ``isSorted() == true``. Semi-related to #6405 
This was caught due to a test failure in Teko: #6455, though it actually has nothing to do with Teko or Cuda.
> Tpetra: Fix #6455

- packages/tpetra/core/test/Map/Map_Bug2431.cpp
@trilinos/tpetra @ZUUL42 
Super-minor change here to remove one compiler warning blocking -Werror build in #6295 
See #6295 ; we want to help @ZUUL42 
Configured/built/tested on cee-lan with gcc 8.3.
```
module load sierra-devel/gcc-8.3.0-openmpi-1.10.2
```
> tpetra:  remove a compiler warning that blocks #6295

- packages/zoltan/src/Utilities/shared/zoltan_util.h
- packages/zoltan/src/lb/lb_balance.c
- packages/zoltan/src/lb/lb_set_method.c
- packages/zoltan/src/params/set_param.c
- packages/zoltan/src/zz/zz_struct.c
Removing unneeded #ifdef ZOLTAN_HIER; it was always defined anyway so checking it didn't make sense (and we never tested without it).
Removing unneeded Allreduces; we were overly cautious for a case that never gets exercised on any of our machines.
Minor cleanup and simplication.
Remove two allreduces that aren't needed.
Tested on mac with clang.
> zoltan:  minor cleanup

- packages/PyTrilinos/doc/Doxygen/doxy2swig.py.in
- packages/PyTrilinos/src/PyTrilinos_Teuchos_Headers.hpp
- packages/PyTrilinos/src/Teuchos_ParameterList.i
- packages/PyTrilinos/src/gen_teuchos_rcp.py.in
It has been a while since PyTrilinos has been updated and there are a couple bugs in the build system now.  This pull request addresses those issues and restores PyTrilinos to building and testing correctly.
* Closes #6497
Note that in general, PyTrilinos is now tested using an Anaconda environment to support the python-related dependencies (python, swig, numpy, mpi4py, ...) and facilitate a conda-forge installer.  To test this PR, an Anaconda environment was used with the following packages installed: cmake, openblas, python=3, swig=3.0.11, numpy, openmpi-mpicc, openmpi-mpicxx, mpi4py, doxygen.  All PyTrilinos tests were run and passed.
> PyTrilinos: Update to build under latest Trilinos

- packages/piro/src/Piro_NOXSolver_Def.hpp
It fixes Albany issues related to increased number of time steps in Exodus mesh
> Piro: fix redundant calls to observeSolution

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
The logic will not work for a vector laplacian but will do just fine for scalar laplacian and elasticity 2D/3D
The proper nullspace is needed for elasticity problems, otherwise the prolongator is not constructed correctly in the coarse AMG solver.
* Closes #5503 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
None
Local tests are passing
> MueLu: implementing logic to build composite nullspace for Elasticity in SetupRegionHierarchy

- packages/teuchos/comm/utils/plotStackedTimers.py
* Parse output correctly.
* Add option to switch to another timer as root.
* Add option to display timer numbers in plot instead of labels.
> Teuchos utils: Improve stacked timer visualization script

- packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
@trilinos/tpetra @csiefer2 @stanmoore1
@stanmoore1 reports errors on stria akin to those we saw on GPU systems.
The errors on GPU systems were avoided if we serialized one parallel scan using some Kokkos magic.  This code serializes the same scan for experimentation on stria -- no Kokkos magic needed.
#6345 
@csiefer2 @stanmoore1  
To try this code, add -DTPETRA_AVOID_PARALLEL_SCAN  to your CMAKE_CXX_FLAGS in Cmake.
Tested on CEE LAN, with -DTPETRA_AVOID_PARALLEL_SCAN in CMAKE_CXX_FLAGS.
All Tpetra tests pass.
I do not know whether or not this PR needs to be pushed to the develop branch.  Since this branch is for experimentation only, it would probably be better to simply build with this branch.
It will be very interesting, indeed, if serializing this scan fixes the issues on stria.
> tpetra:  work around one parallel_scan as an experiment on stria for #6345

- packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
> MueLu: Exposing aggregation algorithm via easy parameterlist

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/examples/structured/CMakeLists.txt
- packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
- packages/muelu/research/regionMG/examples/structured/structured_1dof-complex.xml
- packages/muelu/research/regionMG/examples/structured/structured_1dof.xml
- packages/muelu/research/regionMG/examples/structured/structured_linear_1dof.xml
It is now a bit cleaner and coordinates are only created and propagated if needed.
The previous version require the coordinates to always be provided.
> MueLu: update region MG keep mechanism

- packages/seacas/libraries/ioss/src/fmt/format-inl.h
- packages/seacas/libraries/suplib_cpp/fmt/format-inl.h
Fix compilation error on vortex using nvcc compiler.
> SEACAS: Fix for nvcc compilation problems

- packages/phalanx/test/DataLayout/MDALayout.cpp
> Phalanx: fix data layout test #6554

- packages/zoltan2/src/input/Zoltan2_XpetraMultiVectorAdapter.hpp
- packages/zoltan2/test/partition/CMakeLists.txt
- packages/zoltan2/test/partition/mj_epetra.cpp
@trilinos/<zoltan2
Restore Epetra path for Zoltan2 Multijagged algorithm.
Fixes #6424
Added a new zoltan2 test Zoltan2_mj_epetra to protect the Epetra path for Multijagged.
> Zoltan2: Restore Epetra support for Multijagged (#6424)

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/examples/structured/amg_3dof_rebalance.xml
- packages/muelu/research/regionMG/examples/structured/structured_linear_3dof.xml
Fixing mistake in SetupRegionHierarchy related to the construction of composite coarse grid coordinates
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@rstumin let me know if things are working on NERSC machine.
Local build and tests are performing correctly
> MueLu: coarse coordinates

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp
- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_ExtraKernels_def.hpp
- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_OpenMP.hpp
- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
- packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp
Tests:  Code guarded by #define.  RHEL6.
> Tpetra: Making MMM_Timings play nicer with stacked timers

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
Help with Sierra SD debugging by improving exception messages on insert failure, to show information helpful for users, like the row's capacity.
Feature requested by Sierra.
Tested locally, Linux, GCC 4.9.3, debug build.  These are error messages.
> Tpetra::CrsGraph: Improve exception messages on insert failure

- packages/tpetra/core/src/Tpetra_Import_def.hpp
Tests: Vortex
Stacked timers from the MueLu driver now actually show on vortex.  Yay!
> Tpetra: More MMM Timings / StackedTimer fixes

- packages/zoltan2/src/input/Zoltan2_XpetraTraits.hpp
With changes to Xpetra's include files, non-ETI builds of Zoltan2 were broken.
Adding this include file fixed the non-ETI builds.
Linux, sems modules, with ETI, without ETI, with gno=int and with gno=long long
```
module load sems-env
module load sems-cmake/3.10.3
module load sems-gcc/4.9.3
module load sems-openmpi/1.10.1
```
> zoltan2:  add missing include file for non-ETI builds

- packages/teuchos/comm/utils/plotStackedTimers.py
Fix another parsing bug in the stacked timer script.
> Teuchos utils: fix another stacked timer plotting bug

- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_SaPFactory_kokkos_def.hpp
- packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
> MueLu: Adding timer granularity to Kokkos-ized prolongator smoothing

- packages/kokkos/core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
@Trilinos/tpetra @trilinos/kokkos 
This is a hot fix fixing a very rare race condition in the parallel_scan algorithm.
> Kokkos: fix threadfence issue in scan

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp
- packages/muelu/research/mmayr/composite_to_regions/src/main.cpp
- packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
> Remove some useless matvecs from region MG

- packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp
> Resolve 6652 Intrepid2: Renaming variable to avoid shadow warning.

- packages/muelu/test/unit_tests/RegionVector.cpp
Fixes a mistake in the region vector unit test causing the test to fail.
This test has been run locally and passes with 1 and 4 MPI ranks.
> MueLu: Fix to RegionVector unit test

- packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
Need to speed up some loops for workset construction.
Closes #6656
> Refactoring sideset construction to remove slow lookup calls.

- packages/ml/src/Smoother/ml_smoother.c
@trilinos/ml
Fixes https://github.com/trilinos/Trilinos/issues/6667
SCALE at ORNL is the stakeholder, and we'd like our Windows build to support Trilinos.
N/A
> ML: fix build on Windows Intel 2015

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/stokhos/src/CMakeLists.txt
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_ops.hpp
- packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits.hpp
- packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits_expr_relops_tmpl.hpp
- packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits_sfs_relops_tmpl.hpp
- packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits_vector_relops_tmpl.hpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest_MaskTraits.cpp
The motivation behind this PR is to change the implementation of the Mask class, i.e. the return type of ensemble type comparisons, to use mask assignments.
This PR is the first PR of a sequence of PRs intended to include the software developments of my thesis in Trilinos.
The implementation included in this PR is not relying on Intel Intrinsics.
A second PR might be created later to include a particular implementation for Intel architectures which support AVX-512. This has to be discussed with @etphipp.
Following PRs, based on this PR, will address:
- GEMV, TRSM, and ROTG for ensemble types,
- Ensemble GMRES without ensemble reduction.
This branch has been tested successfully on the Blake system.
> Stokhos: Update the Mask implementation to use mask_assign

- packages/phalanx/src/Phalanx_Kokkos_PrintViewValues.hpp
compiler warnings
Fixes warnings in Drekar and EMPIRE with gcc 9.2.
Touches base class default implementation for Evaluators. Impacts all tests that use evaluators.
> Phalanx fix gcc 9.2 warnings

- packages/zoltan2/src/algorithms/order/Zoltan2_Sort.hpp
- packages/zoltan2/src/problems/Zoltan2_OrderingProblem.hpp
@trilinos/zoltan2 @vbrunini 
See issue #6675.
I've verified that this change results in a matrix ordering that allows an Aria test problem to converge with GMRES/ILU(0) from Belos/Ifpack2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6676)
> Address #6675

- packages/muelu/test/interface/CMakeLists.txt
This should take care of autotester runs failing due to leftover input
xmls.
> MueLu ParameterListInterpreter test: Remove and regenerate xml

- packages/tempus/doc/Doxyfile
- packages/tempus/src/Tempus_StepperDIRK_decl.hpp
- packages/tempus/src/Tempus_StepperDIRK_impl.hpp
Added latex algorithm documentation to DIRK stepper.
Also did some algorithm cleanup, which basically swapped
FSAL work and checking for the need to compute the stageXDot.
This better handles some "corner cases".
Passes all tests.
Closes #6703
> Tempus: Add Improved Doc for DIRK

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp
- packages/muelu/research/regionMG/examples/structured/CMakeLists.txt
- packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
An update to the region MG Chebyshev relaxation so that it more closely resembles the implementation in Ifpack2.
mayrmt: added command line argument to control boost factor. Included this also into tests.
Matches Ifpack2 on single region for unsmoothed aggregation.
mayrmt: ran `ctest -R MueLu_Structured_Region` and `ctest -R UnitTestsRegion` locally. All passed.
> MueLu: region MG Chebyshev updated to match ifpack2

- packages/zoltan2/src/algorithms/order/Zoltan2_AlgRCM.hpp
This fixes issues reported by @vbrunini, specifically, GMRES/ILU(0) convergence failures for certain application test matrices.
* Fixes #6735.
* Related to #6675.
I think that the Zoltan2 test `ordering1.cpp` could be extended to check that after applying an ordering algorithm, the resulting bandwidth of the matrix matches some gold result.  A weaker check would be to see that an ordering like RCM improves the matrix bandwidth, which might have caught this bug.
I'll check whether one of the matrices I've been working with can be added as a new test input.
I've verified that this allows GMRES/ILU(0) to converge on the two test linear systems that were previously not converging.  It also drastically improved the bandwidth on matrices that I ran through …
> Zoltan2: fix 6735 (bug in RCM)

- packages/ifpack2/src/Ifpack2_Relaxation_decl.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
@trilinos/ifpack2 @vbrunini 
This supersedes PR #6722, and also fixes a failing Ifpack2 test when Scalar=float.
* Closes #5885 (perhaps?)
See PR #6722. 
Linux, GCC 4.9.3, OpenMPI.
> Ifpack2: Fix ApplyInverseSGS_BlockCrsMatrix import operations

- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
> TrilinosCouplings: Fix taper calculation

- packages/tpetra/core/example/advanced/Benchmarks/CrsMatrixMatVec.cpp
Small incremental improvment that should help understand output from timers
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of
> Tpetra: adding more fine grained timing in MatVec Benchmark

- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
In debug builds spgemm was still failing with FPE
Still breaking EMPIRE-PIC tests
> Fix div by zero

- packages/kokkos-kernels/src/blas/KokkosBlas3_gemm.hpp
xref: https://github.com/conda-forge/pytrilinos-feedstock/pull/22
> Enable builds on MacOSX

- packages/PyTrilinos/example/exIsorropia.py.in
- packages/PyTrilinos/src/Anasazi.i
- packages/PyTrilinos/src/Domi.i
- packages/PyTrilinos/src/Isorropia.Epetra.i
- packages/PyTrilinos/src/LOCA.Hopf.MinimallyAugmented.i
- packages/PyTrilinos/src/NOX.Epetra.i
- packages/PyTrilinos/src/PyTrilinos_Domi_Util.hpp
- packages/PyTrilinos/src/PyTrilinos_Epetra_Util.cpp
- packages/PyTrilinos/src/PyTrilinos_Isorropia_Headers.hpp
- packages/PyTrilinos/src/PyTrilinos_Tpetra_Util.hpp
- packages/PyTrilinos/src/Tpetra.i
- packages/teuchos/comm/src/Teuchos_Comm.hpp
PyTrilinos was building on my Mac laptop with a bunch of not-very-helpful warnings, so this pull request cleans them up.
> PyTrilinos: Clean up warnings

- packages/nox/test/tpetra/ME_Tpetra_1DFEM_def.hpp
Address issue #6790
modified:   test/tpetra/ME_Tpetra_1DFEM_def.hpp
@trilinos/nox 
Address issue #6790 
Reproduced the failure in test `NOX_Tpetra_1DFEM_MPI_4` in a host build, confirmed it passes with these changes.
> nox: add missing check for sync in dual view

- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Auto testing broken due to PR conflict. This is a temporary fix to put the threads back to 1, which is what it was doing before. Should resolve all the build errors. I'll follow up to fix properly once I see what is going on.
Fix #6809
> Fix #6809 

- cmake/std/atdm/load-env.sh
@bartlettroscoe (since I know you're on the ATDM team)
I saw this typo while configuring on White so I decided to open a quick PR since it's not worth opening an issue or having somebody else do it.
> Fix typo in cmake/std/atdm/load-env.sh

- cmake/ctest/drivers/geminga/crontab.txt
To make recovery easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6846)
> Testing: add geminga crontab

- packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
- packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_decl.hpp
- packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_def.hpp
This allows me to more finely observe where the structured multigrid code path might be slow in order to perform optimization.
I am also adding the option to report stacked timers to the region multigrid driver.
Mainly helping the performance tuning process by adding more fine grained timers.
> MueLu: adding timers in GeometricInterpolationPFactory

- packages/tempus/src/Tempus_IntegratorObserver.hpp
> removed warning

- packages/stk/stk_math/stk_math/StkMath.hpp
> Revert a change that appears to have broken stk_simd compilation for

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Interface/MueLu_MLParameterListInterpreter_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/Misc/MueLu_RAPFactory_def.hpp
- packages/muelu/test/scaling/DriverCore.hpp
- packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp
In debug mode, explicitly check whether the local parts of row and column maps match.
> MueLu: add debug check for matching local part of row and column map

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
> MueLu: add more region timers

- packages/ifpack2/src/Ifpack2_BandedContainer_decl.hpp
- packages/muelu/test/convergence/Convergence.cpp
Removes warnings when using clang 7.0.1.  The warnings are mostly of this type:
```
In file included from packages/ifpack2/src/Ifpack2_BandedContainer_Serial.cpp:49:
/scratch/jhu/trilinos/Trilinos/packages/ifpack2/src/Ifpack2_BandedContainer_decl.hpp:185:16: warning: 'setParameters' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual void setParameters (const Teuchos::ParameterList& List);
^
packages/ifpack2/src/Ifpack2_BandedContainer_Serial.cpp:61:25: note: in instantiation of template class 'Ifpack2::BandedContainer<Tpetra::RowMatrix<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >, double>' requested here
IFPACK2_INSTANTIATE_SLG(LCLINST)
^ …
```
> Ifpack2: MueLu: fix clang 7.0.1 warnings

- packages/belos/src/BelosGmresPolyOp.hpp
Avoid some FPEs coming out of log10.
@jennloe
> Belos GmresPolyOp: Avoid some FPEs.

- packages/ifpack2/src/Ifpack2_Details_Factory_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp
- packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_def.hpp
- packages/ifpack2/src/Ifpack2_Factory.cpp
- packages/ifpack2/src/Ifpack2_Factory_decl.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
Add a method to check whether a preconditioner is supported by Ifpack2, then use it in MueLu
> Ifpack2 Factory

- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_decl.hpp
- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_def.hpp
- packages/amesos2/src/Amesos2_EpetraRowMatrix_AbstractMatrixAdapter_decl.hpp
- packages/amesos2/src/Amesos2_TpetraRowMatrix_AbstractMatrixAdapter_decl.hpp
Fix #6897 
Partially tested by Amesos2_Tacho_Solver_Test. There are some unused Epetra paths here which will be engaged or cut out by forthcoming PRs. This should fix the build error on Albany.
> Amesos2: Fix some Serial dependencies.

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_MatchConditions.hpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Matcher.hpp
- packages/panzer/adapters-stk/test/periodic_bcs/periodic_bcs.cpp
apps need to query the stk_mesh wrapper for periodic bc information
Verified this allows for empire to move periodic support from specialized code into normal BCs.
EMPIRE 596
Tested in panzer periodic_bc unit test.
> Panzer: add accessors to periodic bc matchers

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp
Remove warnings
Tested in local build (OpenMP + gcc/6.5) with Amesos2 enabled
> Tpetra warning

- packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.cpp
- packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.h
- packages/ml/test/RefMaxwell/cxx_main.cpp
> ML: More experimental RefMaxwell stuff

- packages/muelu/adapters/CMakeLists.txt
- packages/muelu/src/Smoothers/MueLu_BelosSmoother_def.hpp
> MueLu: Require Belos-Xpetra adapter when using Belos in MueLu

- cmake/std/PullRequestLinuxClang7.0.1TestingSettings.cmake
- cmake/std/PullRequestLinuxDriverTest.py
- cmake/std/sems/PullRequestClang7.0.1TestingEnv.sh
- cmake/std/unittests/TestPullRequestLinuxDriverTest.py
This will put the build files in place for Clang 7.0.1 addressing Issue #6303.
This will have no effect as is until the PR testing set script is updated.
It will currently build and pass all tests as set, besides the 7 tests mentioned in the issue ticket that have been turned off.
> Add Clang 7.0.1 PR build

- packages/muelu/test/maxwell/Maxwell3D.cpp
> MueLu: Adding max iters control to Maxwell3D test

- packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp
- packages/ifpack2/src/Ifpack2_Details_OneLevelFactory_def.hpp
- packages/ifpack2/src/Ifpack2_Factory_decl.hpp
- packages/ifpack2/src/Ifpack2_Utilities.cpp
- packages/ifpack2/src/Ifpack2_Utilities.hpp
> Ifpack2: move canonicalize to utilities

- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp
> RHEL7 TrilinosCouplings: Fixing dynamic_profile issue

- packages/muelu/adapters/CMakeLists.txt
- packages/muelu/src/Smoothers/MueLu_BelosSmoother_decl.hpp
- packages/muelu/src/Smoothers/MueLu_BelosSmoother_def.hpp
- packages/muelu/test/unit_tests/Smoothers/BelosSmoother.cpp
Second attempt at fixing #6932.
> Belos smoother: Fix #6932

- packages/stokhos/src/CMakeLists.txt
- packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits.hpp
Fixes
* header not installed
* unused variable warning
> Fix two bugs associated with mask traits

- cmake/ctest/drivers/geminga/setSshEnv.py
Fix failing updates on geminga.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/6956)
> Testing: geminga: fix bug in ssh python script

- packages/muelu/test/interface/CMakeLists.txt
- packages/muelu/test/interface/default/Output/aggregatequalities_epetra.gold
- packages/muelu/test/interface/kokkos/Output/coarse1_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/coarse2_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/default_pg_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/driver_drekar1_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/driver_drekar1_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/driver_drekar2_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/driver_drekar2_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/repartition1_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/repartition3_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/repartition4_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-RAP-1_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-RAP-2_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-RP-2_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-S-1_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-full-1_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-none_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-tP-1_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-tP-2_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/reuse-tP-3_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/smoother12_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/transpose2_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/transpose3_np4_tpetra.gold
- packages/muelu/test/interface/rebase.sh
Run the ParameterListInterpreter test always using a single thread. This hopefully takes care of all non-deterministic results we're seeing.
> MueLu ParameterListInterpreter test: run single-threaded

- packages/muelu/matlab/bin/CMakeLists.txt
- packages/muelu/matlab/src/CMakeLists.txt
> MueLu: Matlab support improvements

- cmake/std/PullRequestLinuxClang9.0.0TestingSettings.cmake
- cmake/std/PullRequestLinuxDriverTest.py
- cmake/std/sems/PullRequestClang9.0.0TestingEnv.sh
- cmake/std/unittests/TestPullRequestLinuxDriverTest.py
Adding files for a Clang 9.0.0 Build for Issue #6303.
This will have no effect as is until the PR testing set script is updated.
For that, it has been run through with these changes being applied to the develop branch.
[CDash results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-clang9-test-Trilinos_pullrequest_clang_9.0.0-2&field2=buildstamp&compare2=63&value2=20200305-0020-Experimental)
> Create Clang 9.0.0 PR build

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/test/maxwell/Maxwell3D.cpp
- Test for corner case when all edges are boundary edges.
- Compute explicit residual in Maxwell test when using Block GMRES
> MueLu: Minor RefMaxwell changes

- packages/shylu/shylu_node/basker/src/shylubasker_def.hpp
- packages/shylu/shylu_node/basker/test/CMakeLists.txt
- packages/shylu/shylu_node/basker/test/simple_test_check.cpp
Fix shylubasker for transpose solves
Added simple test to check non-transpose and transpose solves, verified correctness
> shylubasker: fix transpose solve, add test

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_MatchConditions.hpp
- packages/panzer/adapters-stk/test/periodic_bcs/periodic_bcs.cpp
Add accessors to periodic wedge matcher to determine mirror plane and whether 2D or 3D.
> Panzer: added periodic matcher queries

- packages/tempus/src/Tempus_StepperDIRK_decl.hpp
- packages/tempus/src/Tempus_StepperDIRK_impl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_decl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_Partition_decl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_decl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
- packages/tempus/src/Tempus_StepperRKBase.hpp
- packages/tempus/unit_test/Tempus_UnitTest_SDIRK_5Stage5thOrder.cpp
Started an RK base class for RK methods and member data.
First methods are related to getting and setting the stage
number of the RK method.
Added simple test to ensure get/set are working.
All tests pass on Mac CLANG.
* Closes  #6993
> Tempus: Add Ability to Get the RK Stage Number

- packages/amesos2/example/CMakeLists.txt
- packages/amesos2/example/SimpleSolveTranspose.cpp
- packages/shylu/shylu_node/basker/src/shylubasker_def.hpp
Added example to test through Amesos2
Tested in local build to confirm changes address transpose solve correctness issues when calling shylubasker through amesos2
> shylubasker: fix shylubasker transpose solve correctness in amesos2

- packages/tempus/src/Tempus_StepperDIRK_decl.hpp
- packages/tempus/src/Tempus_StepperDIRK_impl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_decl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_decl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
- packages/tempus/src/Tempus_StepperRKBase.hpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
- add test for stage number accessor
- move `getStageX` to `StepperRKBase`
ERK test stage number accessor
> Tempus: ERK - test stage number accessor

- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_decl.hpp
- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp
> MueLu: Fix bad if-guard in StratimikosSmoother

- packages/tempus/src/Tempus_StepperFactory.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
- packages/tempus/src/Tempus_StepperRKButcherTableau.hpp
- packages/tempus/test/DIRK/Tempus_DIRKTest.cpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
- packages/tempus/test/IMEX_RK/Tempus_IMEX_RKTest.cpp
Add additional schemes used in other apps and update aliases.
Convergence order for the new schemes/aliases
> Tempus: clean tableaus for app

- packages/tpetra/tsqr/src/Tsqr.hpp
Fix #7016 (shadowing warning).
* Closes #7016 
Mac Clang + OpenMPI.
> TSQR: Fix #7016 (shadowing warning)

- packages/muelu/src/Misc/MueLu_RAPFactory_decl.hpp
- packages/muelu/src/MueCentral/MueLu_FactoryManager_decl.hpp
- packages/muelu/test/meshtying/myXML.xml
Fix some missing forward declarations and set a test with factory-style xml to 'use kokkos refactor' = false.
> MueLu: Bug fixes

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/test/meshtying/myXML.xml
Process "use kokkos refactor" for groups in factory style parameter lists. Fixes #7041.
> MueLu: Fix #7041

- packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
- packages/tempus/test/IMEX_RK/Tempus_IMEX_RKTest.cpp
use non-default `gamma` for `SSP2_222` to get a 2nd order, A-Stable scheme with lower principal error norm that is consistent with the app.
Tempus/IMEX RK test has been updated. App tests using the alias has all tests passing.
> Tempus: update `gamma` for SSP2_222

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Smoothers/MueLu_DirectSolver_def.hpp
- packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_decl.hpp
- packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_def.hpp
- Fix some bad ifdefs for StratimikosSmoother
- Silence a warning in RefMaxwell
> MueLu: Fixes

- packages/muelu/src/Smoothers/MueLu_DirectSolver_def.hpp
- packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_def.hpp
> MueLu BelosSmoother: Catch smoother construction exceptions

- packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp
Found a corner case in drekar. This check will help apps avoid writing incorrect kernels. This is  a temporary addition and we can remove once support for "allow_duplicate_evaluators" feature is removed.
Verified that this catches an issue in Drekar SUPG VMS evaluator.
> Phalanx: add safety check for corner case

- packages/tempus/src/Tempus_StepperFactory.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
> Tempus: imex rk - ARS 223 alias update

- packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_kokkos_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp
- packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp
Make sure that "aggregation: phase3 avoid singletons" and"aggregation: error on nodes with no on-rank neighbors" get set and passed to phase 3.
> MueLu UncoupledAggregationFactory_kokkos: Accept more params

- packages/percept/src/percept/mesh/mod/smoother/GenericAlgorithm_total_element_metric.cpp
> Move ETI to end of .cpp file

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
- packages/teuchos/comm/test/StackedTimer/CMakeLists.txt
- packages/teuchos/comm/test/StackedTimer/stacked_timer4.cpp
Fix the stacked timer histogram in the case when timers are not used on all ranks.
> Teuchos Stacked timer histogram fix

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Matcher.cpp
Change the matching algorithm for periodic bcs to use Tpetra instead of Epetra. This allows an application to run periodic bcs at scale.
App reports that this eliminated failures associated with 32-bit int limits. 
Panzer's periodic_bc unit test covers this functionality.
> Panzer periodic bc to tpetra v2

- packages/seacas/applications/conjoin/CJ_SystemInterface.C
- packages/seacas/applications/conjoin/CJ_SystemInterface.h
- packages/seacas/applications/conjoin/CJ_Version.h
- packages/seacas/applications/conjoin/Conjoin.C
- packages/seacas/libraries/ioss/src/Ioss_Decomposition.h
- packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.h
- packages/seacas/libraries/ioss/src/cgns/Iocgns_DecompositionData.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_Defines.h
- packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.h
- packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.h
Origin repo remote tracking branch: 'origin/master'
Origin repo remote repo URL: 'origin = https://github.com/gsjaardema/seacas'
At commit:
commit 7b9854a75a44963415a39e71cacab110b9ffa468
Author:  Greg Sjaardema <gsjaardema@gmail.com>
Date:    Tue Mar 31 10:16:16 2020 -0600
Summary: IOSS: cgns - use CGNSIntVector typedef
---------------------------------------
* CGNS - BC naming fixes applied to parallel input
* CGNS - BC naming -- use correct name for output BC's
* CGNS - Use CGNSIntVector typedef consistently
* CONJOIN - Add -sort_times option to sort input files in order of mimimum timestep time
> Automatic snapshot commit from seacas at 7b9854a75

- packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Tpetra_main.cpp
> TrilinosCouplings: Adding coordinate dump option to Tpetra Poisson example

- packages/muelu/test/maxwell/Belos.xml
- packages/muelu/test/maxwell/CMakeLists.txt
- packages/muelu/test/maxwell/Maxwell3D.cpp
* Refactor
* Load Belos params from file
* Add option for inital guess
* Fix missing tests
> MueLu Maxwell test: Spring cleaning

- packages/tempus/src/Tempus_StepperFactory.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
> Tempus imex ssp2 a l stable

- packages/amesos2/src/Amesos2_Cholmod.cpp
- packages/amesos2/src/Amesos2_Cholmod_FunctionMap.hpp
- packages/amesos2/src/Amesos2_Cholmod_TypeMap.hpp
- packages/amesos2/src/Amesos2_Cholmod_decl.hpp
- packages/amesos2/src/Amesos2_Cholmod_def.hpp
- packages/amesos2/src/Amesos2_Factory.hpp
- packages/amesos2/src/Amesos2_MatrixAdapter_decl.hpp
- packages/amesos2/src/Amesos2_MatrixAdapter_def.hpp
- packages/amesos2/src/Amesos2_Util.hpp
- packages/amesos2/test/solvers/CMakeLists.txt
- packages/amesos2/test/solvers/SolverFactory.cpp
- packages/amesos2/test/solvers/cholmod_test.xml
Adds GPU capability to Cholmod solver.
Refactor Cholmod solver to use Kokkos Views.
Fix ETI for Cholmod.
Fix Complex for Cholmod.
Epetra now working for Cholmod.
Add long long GO test for Cholmod to match Trilinos defaults.
Add new Kokkos Adapter tests for Cholmod.
Setup/clean up Cholmod float but Cholmod does not support it yet.
Amesos2_Cholmod_Solver_Test
> Amesos2: Upgrade Cholmod for GPU

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities.cpp
- packages/muelu/src/Utils/MueLu_Utilities_decl.hpp
Make 'verbosity' case-insensitive.
> MueLu: Make 'verbosity' parameter case-insensitive

- packages/muelu/cmake/Dependencies.cmake
Otherwise the set of built tests is pretty much useless.
Useful primarily for MueLu developers.
Does not affect any source code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/7148)
> MueLu: make Galeri a required test dependency

- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/teuchos/core/src/Teuchos_ScalarTraits.hpp
This fix is needed for empire on clang in opt mode
> Fix fpe in clang, not sure why this makes it go away, but it does

- packages/muelu/src/Interface/MueLu_FactoryFactory_decl.hpp
> Add SmooVecRandCoalesceDrop to long xml interface

- packages/tpetra/core/src/Tpetra_Distributor.cpp
- packages/tpetra/core/src/Tpetra_Distributor.hpp
- packages/xpetra/src/Export/Xpetra_TpetraExport_def.hpp
- packages/xpetra/src/Import/Xpetra_TpetraImport_def.hpp
Allows to set parameters on reverse distributor
> Tpetra Distributor: add method to get reverse distributor

- packages/muelu/src/Utils/MueLu_VisualizationHelpers_decl.hpp
- packages/muelu/src/Utils/MueLu_VisualizationHelpers_def.hpp
> MueLu: Agg Viz 2D convex hulls fix

- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_decl.hpp
- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
- packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp
- packages/muelu/test/scaling/CMakeLists.txt
- packages/muelu/test/scaling/pairwise.xml
- packages/muelu/test/unit_tests/NotayAggregationFactory.cpp
- packages/stokhos/src/sacado/kokkos/pce/muelu/MueLu_ETI_UQ_PCE.tmpl
- packages/stokhos/src/sacado/kokkos/vector/muelu/MueLu_ETI_MP_Vector.tmpl
This will allow true testing of pairwise aggregation.
Currently a single pass algorithm is available but it probably won't yield good hierarchies from a computation stand-point.
* Closes #7008 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
SPARC linear solvers, i.e. @rstumin 
Multiple unit-test are added to make sure this feature works.
It was tested on local platform using OpenMP and complex
> MueLu: pairwise multipass aggregation, see issue #7008

- packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/unit_tests_kokkos/CMakeLists.txt
- packages/muelu/test/unit_tests_kokkos/Utilities_kokkos.cpp
Wraps @brian-kelley's RCM code in Kokkos-Kernels
Tests: RHEL 6
> MueLu: Adding CM/RCM support to MueLu::Utilities_kokkos

- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/unit_tests/NotayAggregationFactory.cpp
> MueLu: Adding Cuthill-McKee ordering support to pairwise

- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/unit_tests/AggregateQualityEstimateFactory.cpp
> MueLu: Minor code / test cleanup

- packages/muelu/src/Utils/MueLu_Utilities_decl.hpp
> new matrix scaling utility for PDE systems

- packages/muelu/test/unit_tests/AggregateQualityEstimateFactory.cpp
> MueLu: Disabling very finicky test

- packages/stk/stk_search/integrationtest/MeshUtilsForBoundingVolumes.hpp
- packages/stk/stk_search/integrationtest/UnitTestNaluPerformance.cpp
- packages/stk/stk_search/integrationtest/UnitTestPerformance.cpp
- packages/stk/stk_search/stk_search/CommonSearchUtil.hpp
- packages/stk/stk_search/unit_tests/UnitTestCoarseSearch.cpp
- packages/stk/stk_search/unit_tests/UnitTestGhostingSearch.cpp
- packages/stk/stk_unit_tests/stk_util/command_line/UnitTestCommandLineParser.cpp
- packages/stk/stk_unit_tests/stk_util/diag/UnitTestTimer.cpp
- packages/stk/stk_unit_tests/stk_util/environment/UnitTestOptionsSpecification.cpp
- packages/stk/stk_util/stk_util/command_line/CommandLineParser.hpp
- packages/stk/stk_util/stk_util/diag/Timer.cpp
- packages/stk/stk_util/stk_util/environment/OptionsSpecification.cpp
- packages/stk/stk_util/stk_util/environment/OptionsSpecification.hpp
- packages/stk/stk_util/stk_util/environment/ParseCommandLineArgs.cpp
> STK snapshot as of 4/17/2020

- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
> TrilinosCouplings: Adding coordinates to solve ofr 2D poisson example

- cmake/RepositoryDependenciesSetup.cmake
> Fix capitalization of Kokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE in ShyLU dependencies.

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Instead of changing discrete gradient matrix supplied by user, create a copy.
> MueLu RefMaxwell: Copy D0 matrix

- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
> TrilinosCouplings: More Poisson2D cleanup

- packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp
- packages/muelu/src/Smoothers/MueLu_AmesosSmoother.cpp
- packages/muelu/src/Smoothers/MueLu_BelosSmoother_def.hpp
- packages/muelu/src/Smoothers/MueLu_DirectSolver_def.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_decl.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp
- packages/muelu/src/Smoothers/MueLu_SmootherBase.hpp
- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp
- packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_def.hpp
> MueLu: Avoid throwing exceptions in smoother construction

- packages/stk/stk_unit_tests/stk_util/diag/UnitTestTimer.cpp
Put the tolerance in terms of milliseconds and make it looser.
If this doesn't help we may need to rethink these tests.
This is to fix issue #7210 
> Make timer unit-tests more robust to prevent failures due to noise.

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/test/scaling/circ_nsp_dependency.xml
- Create RefMaxwell timers only when requested, same as rest of MueLu.
- Fix failing TrilinosCouplings examples, see #6570 
- Fix #6434
> RefMaxwell&Epetra stuff

- packages/tpetra/core/src/Tpetra_Apply_Helpers.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp
> Tpetra: batchedApply() prototype

- packages/stratimikos/adapters/belos/src/BelosThyraAdapter.hpp
Line 87 has a ST typedef, so I removed one.
> Warning dup st

- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
In a non-ETI build, the compiler was trying to find "Utilities_kokkos"
as a member of MueLu::NotayAggregationFactory. Adding "MueLu::" before
fixed it.
Noticed this when trying to see if #3041 was fixed in develop.
Fixes build
> MueLu: fix build error in Notay pairwise agg

- packages/pamgen/src/CMakeLists.txt
- packages/pamgen/src/element_density_function.h
- packages/pamgen/src/geometry_transform.h
- packages/pamgen/src/inline_mesh_desc.C
- packages/pamgen/src/inline_mesh_desc.h
> Pamgen: Exposing some innards

- packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp
- packages/muelu/test/unit_tests/MueLu_TestHelpers.hpp
- packages/muelu/test/unit_tests/Smoothers/Ifpack2Smoother.cpp
> MueLu/Ifpack2: Making BlockRelaxation+LinearPartitioner grab the FixedBlockSize by default

- packages/seacas/libraries/ioss/src/fmt/chrono.h
- packages/seacas/libraries/ioss/src/fmt/core.h
- packages/seacas/libraries/ioss/src/fmt/format-inl.h
- packages/seacas/libraries/ioss/src/fmt/format.h
- packages/seacas/libraries/suplib_cpp/fmt/chrono.h
- packages/seacas/libraries/suplib_cpp/fmt/core.h
- packages/seacas/libraries/suplib_cpp/fmt/format-inl.h
- packages/seacas/libraries/suplib_cpp/fmt/format.h
Eliminate several shadowed variable warnings from the lib::fmt library used by the IOSS and SEACAS suplib_cpp library.
> SEACAS: lib::fmt - fix shadow variable warnings

- packages/belos/src/BelosStatusTestGenResNorm.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
with FPE checking on we trip FPEs on clang and stria with bad branch prediction
> Stupid changes to resolve FPEs

- packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp
- packages/tpetra/core/test/BugTests/BugTests.cpp
> Tpetra: unit test to reproduce failure after kokkos 3.1 promotion

- packages/tempus/src/Tempus_StepperSubcyclingAppAction.hpp
- packages/tempus/src/Tempus_StepperSubcyclingAppActionComposite.hpp
- packages/tempus/src/Tempus_StepperSubcyclingModifierBase.hpp
- packages/tempus/src/Tempus_StepperSubcyclingModifierDefault.hpp
- packages/tempus/src/Tempus_StepperSubcyclingModifierXBase.hpp
- packages/tempus/src/Tempus_StepperSubcyclingModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperSubcyclingObserverBase.hpp
- packages/tempus/src/Tempus_StepperSubcyclingObserverDefault.hpp
- packages/tempus/src/Tempus_StepperSubcycling_decl.hpp
- packages/tempus/src/Tempus_StepperSubcycling_impl.hpp
- packages/tempus/unit_test/Tempus_UnitTest_Subcycling.cpp
> 7236 app action interface for subcyling stepper

- packages/compadre/CMakeLists.txt
- packages/compadre/cmake/Dependencies.cmake
- packages/compadre/examples/CMakeLists.tribits.cmake
- packages/compadre/src/Compadre_GMLS_ApplyTargetEvaluations.hpp
@trilinos/compadre 
Fixes CMake logic to be compatible with TPL_ENABLE_CUDA without requiring explicit setting of Compadre_USE_CUDA.
> Compadre package CMake logic update

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_aggregation.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Graph/BrickAggregation/MueLu_BrickAggregationFactory_decl.hpp
- packages/muelu/src/Graph/BrickAggregation/MueLu_BrickAggregationFactory_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/test/interface/default/Output/aggregation5_epetra.gold
- packages/muelu/test/interface/default/Output/aggregation5_np4_epetra.gold
- packages/muelu/test/interface/default/Output/aggregation5_np4_tpetra.gold
- packages/muelu/test/interface/default/Output/aggregation5_tpetra.gold
> MueLu: Adding Dirichlet Boundary support to BrickAggregation

- packages/ifpack2/src/Ifpack2_IlukGraph.hpp
In particular for the case where there are a small number of significantly
more dense rows. Rather than using the max number of entries from any
row as the heuristic for every row instead use the per-row values.
This reduces the memory use of a particular test case from ~1.2GB
down to ~350MB (which is consistent with the equivalent Aztec solver
memory use).
> ifpack2: Reduce memory usage of Ifpack2::IlukGraph::initialize().

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
> MueLu: Fixing Dirichlet handling for distance Laplacian

- packages/muelu/src/Graph/BrickAggregation/MueLu_BrickAggregationFactory_decl.hpp
- packages/muelu/src/Graph/BrickAggregation/MueLu_BrickAggregationFactory_def.hpp
Tests: RHEL7
And now, with the right target branch!
> MueLu: More fixes to BrickAggregation for Dirichlet handling

- packages/panzer/mini-em/example/BlockPrec/main.cpp
Adding extra level of timers and some verbosity flags for performance monitoring of mini-em.
These changes are tested in all mini-em unit tests as they were added to main.cpp.
> Add Panzer mini em timers for verbose mode

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
> MueLu: Correctly parse "aggregation: phase2a include root"

- packages/muelu/test/maxwell/Maxwell3D.cpp
> MueLu Maxwell test: Fix build error without SerialNode

- packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
Now can look at scaling from 4 to 16 ranks.
Will want to look at strong scaling of MiniEM on Vortex. 
Did a full performance test build+run on Vortex.
> MiniEM: add 16-rank version of performance test

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_decl.hpp
- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/interface/default/Output/notay_epetra.gold
- packages/muelu/test/interface/default/Output/notay_tpetra.gold
- packages/muelu/test/unit_tests/NotayAggregationFactory.cpp
> MueLu: Fixing issues in pairwise aggregation

- cmake/ctest/drivers/atdm/ats1/local-driver-on-allocation.sh
- cmake/std/atdm/ats1/all_supported_builds.sh
Please see [cdash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&begin=2020-05-07&end=2020-05-06&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ats1).
> ATDM/ats1: Prioritize builds and disable running tests (ATDV-347)

- packages/seacas/applications/conjoin/Conjoin.C
Assert in Conjoin was accessing a variable that had been removed in a recent refactor.  Change assert to use correct value.
Addresses #7331
> SEACAS: Fix debug build

- packages/muelu/test/scaling/ImportPerformance.cpp
This test was randomly crashing on white.
I think the Kokkos::ScopeGuard is not compatible/intended with Automatic_Test_ETI.
MueLu_ImportPerformance_Tpetra_MPI_4
> MueLu: Fix scope guard for ImportPerformance test

- packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
> TrilinosCouplings: Allowing choice of Belos solvers in 2D examples

- packages/tpetra/core/src/Tpetra_FECrsMatrix_def.hpp
- packages/tpetra/core/test/FECrsMatrix/FECrsMatrix_UnitTests.cpp
Tests: RHEL6. New test added Fix as suggested in #7348. Thanks @bartgol!
> Tpetra: Fix for #7348

- packages/seacas/libraries/ioss/src/Ioss_Field.h
The INFORMATION field type was changed to `MESH_REDUCTION`, but that
broke some existing users of IOSS.  Add back `INFORMATION` as alias
of `MESH_REDUCTION`
> IOSS: Fix backward compatibility

- packages/kokkos-kernels/src/CMakeLists.txt
header glob command was searching in source directory instead of binary
directory. This prevented generated files from being installed.
Fix broken install
> Kokkos-Kernels: fix install for autogenerated headers

- packages/belos/tpetra/test/OrthoManager/CMakeLists.txt
- packages/belos/tpetra/test/OrthoManager/belos_orthomanager_tpetra_util.hpp
This PR fixes a build error in the Tpetra OrthoManager Test.  It also enables the test for the standard orthogonalization options, rather than only for TSQR.  
Tested on RHEL7 with gcc compilers.
> Fix build error and add more tests for Tpetra OrthoManager Test

- packages/amesos2/example/GappedMtxGIDs-1proc.cpp
- packages/amesos2/example/SimpleSolveNonContigMap.cpp
- packages/amesos2/src/basker/basker_def.hpp
- packages/amesos2/test/solvers/Basker_UnitTests.cpp
- packages/amesos2/test/solvers/KLU2_UnitTests.cpp
- packages/amesos2/test/solvers/ShyLUBasker_UnitTests.cpp
Address issue #7274, fix tests and examples not tested by default
Tested locally on Mac laptop, confirmed tests pass with changes.
> Issue 7274

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Utils/MueLu_UtilitiesBase_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
Apply boundary conditions to A_nodal. Fixes an EMPIRE issue with a singular coarse (1,1) problem.
> MueLu RefMaxwell: BCs for A_nodal

- packages/sacado/CMakeLists.txt
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_EpetraIntrepidPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson2DExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson3DExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_BlockMaterials.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE_Epetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE_Tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
- packages/trilinoscouplings/examples/scaling/example_StabilizedADR.cpp
> Sacado:  Make the new Fad design the default.

- packages/minitensor/src/MiniTensor_LinearAlgebra.t.h
Loosen the absolute tolerance and add a relative tolerance test
for the projection from GL+(3) to SO(3) to satisfy tests
on Sierra/SM.
Changes made by Mike Veilleux (mgveill@sandia.gov)
> MiniTensor: Sierra/SM tolerance changes.

- packages/belos/epetra/test/OrthoManager/CMakeLists.txt
- packages/belos/src/BelosICGSOrthoManager.hpp
- packages/belos/src/BelosIMGSOrthoManager.hpp
- packages/belos/src/BelosOrthoManagerTest.hpp
The logic that checks if the norm of a vector is zero before normalizing
it needs to be inserted to avoid FPEs and bad solver behavior.  This conditional 
existed in DGKS, which is why this did not come up as a problem before the 
change to making ICGS[2] the default.
#7451 
The OrthoManager test has been amended to include a check for this
functionality, so that it does not come up again for customers.
> Fixes calls to normalize zero vectors in ICGS/IMGS

- packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp
- packages/ml/src/Utils/ml_MultiLevelPreconditioner_Smoothers.cpp
- packages/ml/src/Utils/ml_amesos_wrap.cpp
> ML: Adding comm restriction labels to Amesos output

- packages/tempus/src/Tempus_StepperRKButcherTableau.hpp
Found some additional poor uses of Teuchos::ScalarTraits::squareroot.
All tests pass.
Closes #4176
> Tempus: Additional Cleanup of Squareroot.

- packages/xpetra/sup/Utils/Xpetra_IO.hpp
Tpetra requires a static graph.  To do this with file reading,
my solution is to make two passes through the file, the first pass
to figure out the sparsity pattern, the second to populate the matrix.
Because the input file is binary, hopefully this isn't too expensive.
This is primarily for developers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/7487)
> Xpetra: fix binary reader

- cmake/std/PullRequestLinuxCudaDriver.sh
I am not sure this is out actual issue and will monitor
to see what results we get.
Unreproducable timeouts on the ride platform
> PullRequestLinuxCudaDriver.sh: change from Firestone to Garrison nodes

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_general.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_decl.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp
- packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
Sometimes it would be nice to test using W-cycles to improve coarse-grid correction, but not necessarily starting immediately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/7494)
> MueLu: add option to specify W-cycle start level

- packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp
- packages/ifpack2/src/Ifpack2_Details_ScaledDampedResidual_def.hpp
Use SpMV launch parameters and policies for Chebyshev and ScaledDampedResidual.
> Ifpack2: Chebyshev+Residual schedule

- packages/muelu/src/Smoothers/MueLu_Amesos2Smoother_def.hpp
Only manifests if no direct solver is enabled
Fixes a compile error that you would only see if no direct solver is enabled.
Confirmed on Summit with gcc 7.4.0 that this patch compiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/7502)
> MueLu: fix compile error

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp
- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
> Tpetra: MatrixMatrix Fence Relocation

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
> MueLu RefMaxwell: attempt fixing bug with cuda+complex

- packages/minitensor/src/MiniTensor_Matrix.h
- packages/minitensor/src/MiniTensor_Solvers.h
- packages/minitensor/src/MiniTensor_Tensor.h
- packages/minitensor/src/MiniTensor_Tensor3.h
- packages/minitensor/src/MiniTensor_Tensor4.h
- packages/minitensor/src/MiniTensor_Vector.h
Clang 10 flagged warnings about destructors
marked as final for some classes. Remove
the final keyword as other classes could be
derived from these.
@trilinos/discretizations
> MiniTensor: Fix Clang 10 warnings

- packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
User requested millisecond accuracy from StackedTimer timestamps.
All stacked timer tests touch this function. Unit tests cover this.
> Teuchos: increase resolution of StackedTimer timestamps

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
- packages/tpetra/core/src/Tpetra_replaceDiagonalCrsMatrix_def.hpp
@kyungjoo-kim As we discussed in meeting, adding comments from discussion (#7446) for fences we are keeping. This PR is trivial, just comment changes.
> Tpetra: Update comments from KJ for fences.

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_reallocDualViewIfNeeded.hpp
- packages/tpetra/core/src/Tpetra_DistObject_def.hpp
These are the fences discussed in #7446 which were confirmed to be ok to remove.
> Tpetra remove fences

- packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp
- packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp
> Galeri: Add matrix labels for elasticity problems

- packages/galeri/src-xpetra/Galeri_Elasticity2DProblem.hpp
- packages/galeri/src-xpetra/Galeri_Elasticity3DProblem.hpp
- packages/galeri/src-xpetra/Galeri_StencilProblems.hpp
- packages/galeri/src-xpetra/Galeri_XpetraMaps.hpp
- packages/galeri/src-xpetra/Galeri_XpetraParameters.hpp
- packages/galeri/src-xpetra/Galeri_XpetraUtils.hpp
- packages/muelu/test/convergence/Convergence.cpp
- packages/muelu/test/convergence/Convergence/Laplace2D/CMakeLists.txt
- packages/muelu/test/convergence/Convergence/Laplace2D/problem.xml
- packages/muelu/test/convergence/Convergence/Laplace2D/problem_i.xml
- packages/muelu/test/convergence/Convergence/Laplace2D/problem_l.xml
- packages/muelu/test/convergence/Convergence/Laplace2D/problem_x.xml
For the Convergence test, use the same input file, independent of GlobalOrdinal.
Not really sure why this was needed in the first place.
Hopefully addresses #3862.
> MueLu Convergence test: Use same input file for all GOs

- packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C
- packages/seacas/libraries/ioss/src/main/cgns_decomp.C
- packages/seacas/libraries/ioss/src/utest/Utst_structured_decomp.C
> Seacas snapshot june 2020 cgns

- packages/zoltan2/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Adds RangePolicy to some parallel_reduce calls which were missing it.
@cgcgcg This PR will fix the crash if you run MJ as serial on a CUDA build.
Repair MJ to respect device choice. Running Serial MJ on a Cuda build would crash because some parallel_reduce calls did not specify the execution space and defaulted incorrectly to CUDA.
Tested by Zoltan2 MJ tests.
Tested white CUDA parallel, a another CUDA machine modified to trigger the Serial MJ on CUDA build, Mac Parallel and Serial.
@kddevin I could easily add additional tests which run MJ Serial only for CUDA builds. We already have UVM on and off, so it would be just be an extension of that setup. That would cover this error.
> Zoltan2: Fix MJ parallel_reduce calls to specify RangePolicy

- packages/muelu/test/unit_tests/Hierarchy.cpp
> MueLu: Expand unit test for hierarchy write w/ repartitioning

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_multigrid.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/test/interface/default/Output/emin3_epetra.gold
- packages/muelu/test/interface/default/Output/emin3_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/emin1_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/emin2_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/emin3_tpetra.gold
> MueLu: Adding filtering to emin

- packages/phalanx/src/Phalanx_DAG_Manager.hpp
- packages/phalanx/src/Phalanx_DAG_Manager_Def.hpp
- packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp
- packages/phalanx/test/DagManager/DagManagerTest.cpp
- packages/phalanx/test/Utilities/Evaluator_MockDAG.hpp
- packages/phalanx/test/Utilities/Evaluator_MockDAG_Def.hpp
A shared memory safety check was failing in an app. Needed to fix the check for a specific use case.
While fixing that, also noticed a corner case that was incorrect. Fixed and added new tests.
Fix was verified in EMPIRE. Able to run problem to completion with shared memory enabled. EF-787
All covered under new tests.
> Phalanx: fix shared mem check and support corner case

- packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp
Part of ongoing work for #7446
> Tpetra remove unnecessary fence from TripleMatrixMultiply

- packages/stk/stk_simd/stk_simd/disimd/DISimdBool.hpp
> Patch stk_simd for issue with cuda+avx512 build.

- packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
> TrilinosCouplings: Upgrading STK example

- packages/piro/src/Piro_PerformAnalysis.cpp
- packages/piro/test/MockModelEval_A_Tpetra.cpp
- packages/piro/test/MockModelEval_A_Tpetra.hpp
- packages/piro/test/_input_Analysis_ROL_AdjointSensitivities_ReducedSpace_NOXSolver_Tpetra.xml
- packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Constraint_SimOpt.hpp
- packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective_SimOpt.hpp
- packages/rol/src/function/objective/ROL_Objective.hpp
@trilinos/rol
Added support to Thyra SimOpt adapters in ROL
Updated Piro::PerformAnalysis to support hessian 
thanks @kliegeois @etphipp  
Updated Piro_AnalysisDriverTpetra test to exercise hessian
> Piro/ROL: Adding and testing Hessian support to thyra adapters

- packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
> TrilinosCouplings: Fixing indexing bug

- packages/muelu/test/unit_tests/RegionVector.cpp
RegionVector unit test not working with complex. Now it does.
> MueLu: RegionVector unit test fixed to work with complex

- packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
> TrilinosCouplings: Fixing stk test

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
- packages/xpetra/src/Operator/Xpetra_TpetraOperator.hpp
While not the goal of issue #7616 these should still be fixed.
My build fails and that's always annoying...
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #7616
* Composed of 
None
It now actually builds without errors on my machine
> MueLu: fixing some random issues discovered in gcc/8.3.0 build

- packages/teuchos/comm/test/Comm/reduce.cpp
- packages/teuchos/comm/test/Comm/scatter.cpp
> Teuchos Comm test: remove duplicate 'using ...'

- packages/stk/stk_simd/stk_simd/SimdConfig.hpp
- packages/stk/stk_simd/stk_simd/disimd/DISimdBoolF.hpp
Fix SIMD configuration issues for AVX512, ARM, VSX platforms
@trilinos/stk
> Snapshot latest fixes to stk_simd platform-specific configuration

- packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C
- packages/seacas/libraries/ioss/src/main/io_modify.C
> Seacas fix io modify build no exodus

- packages/seacas/libraries/ioss/src/fmt/chrono.h
- packages/seacas/libraries/suplib_cpp/fmt/chrono.h
> IOSS: Fix build on intel-17 with *time_s routines

- cmake/std/atdm/cee-rhel6/environment.sh
> ATDM/cee-rhel6: Update LD_LIBRARY_PATH for git update (ATDV-272)

- packages/tempus/src/Tempus_StepperRKButcherTableau.hpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
Fix summation bug and add error estimator for `SSPERK54`
> Tempus: fix SSPERK54 bug and add error estimator

- packages/intrepid2/src/Shared/Intrepid2_Utils.hpp
> Intrepid2: Remove deprecation macros (issue #7070)

- packages/tpetra/core/guide/src/alabaster/static/alabaster.css_t
Comment wording needed improvement.
The need for this change was pointed out by a member of management.
This change impacts comments only.
> Fixed wording of 2 comments.

- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_def.hpp
> shylu/frosch: missing include statement

- packages/amesos2/src/Amesos2_Basker_decl.hpp
- packages/amesos2/src/Amesos2_Cholmod_decl.hpp
- packages/amesos2/src/Amesos2_KLU2_decl.hpp
- packages/amesos2/src/Amesos2_Superlu_decl.hpp
@ndellingwood Removes some unused variables that were left over from the refactors to Views.
> Amesos2: Remove some declarations no longer used.

- packages/trilinoscouplings/cmake/Dependencies.cmake
- packages/trilinoscouplings/examples/scaling/CMakeLists.txt
- packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Tpetra_main.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
- packages/trilinoscouplings/examples/scaling/rtpamgen.cpp
- packages/trilinoscouplings/examples/scaling/test.rtp
> TrilinosCouplings: Adding pamgen-to-exodus converter

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Minor compilation fix as specified in #7695 
Affects builds with LO != int.
* Closes #7695 
I confess -- I did not test this trivial change.
> tpetra:  LO type agreement fix #7695

- packages/zoltan2/sphynx/LICENSE
- packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
- packages/zoltan2/sphynx/src/Zoltan2_SphynxProblem.hpp
- packages/zoltan2/sphynx/src/Zoltan2_SphynxVersion.cpp
This PR updates the copyright statement in Sphynx source files.
> Zoltan2: Sphynx: Update copyright

- packages/muelu/example/basic/CMakeLists.txt
- packages/muelu/example/basic/mg-gpu.xml
- packages/muelu/example/basic/set1-cg.xml
- packages/muelu/example/basic/set1-gmres.xml
- packages/muelu/example/basic/set2-sgs1.xml
- packages/muelu/example/basic/set2-sgs3.xml
- packages/muelu/example/basic/set3-mg-chebyshev.xml
- packages/muelu/example/basic/set3-mg-gs.xml
- packages/muelu/example/basic/set3-mg-jacobi.xml
- packages/muelu/example/basic/set3-mg-sgs.xml
Add input files for ATPESC2020
> MueLu: Add input files for ATPESC2020

- packages/belos/src/BelosBlockCGSolMgr.hpp
- packages/belos/src/BelosCGIter.hpp
- packages/belos/src/BelosCGSingleRedIter.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/test/BlockCG/CMakeLists.txt
- packages/belos/test/BlockCG/test_bl_cg_real_hb.cpp
- packages/stokhos/src/sacado/kokkos/vector/belos/Belos_StatusTest_GenResNorm_MP_Vector.hpp
In Single Reduce CG:
* Remove one kernel call via memory layout.
* Fix iter counts so that they match standard Block CG.
* Save one vector.
Adds option "Fold Convergence Detection Into Allreduce" to standard (Pseudo)Block CG.
> Belos CG improvements

- packages/tempus/src/Tempus_RKButcherTableau.hpp
- packages/tempus/src/Tempus_StepperFactory.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_impl.hpp
- packages/tempus/src/Tempus_StepperRKButcherTableau.hpp
- packages/tempus/unit_test/Tempus_UnitTest_DIRK_General.cpp
- packages/tempus/unit_test/Tempus_UnitTest_ERK_General.cpp
Update to provide `isTVD` and `sspCoef` default values.
> Tempus ssp coeff fix

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_decl.hpp
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/test/unit_tests/CoalesceDropFactory.cpp
> MueLu: Adding first cut at a symmetrization option for scaled cut drop

- packages/amesos2/src/Amesos2_Cholmod_FunctionMap.hpp
- packages/amesos2/src/Amesos2_Cholmod_decl.hpp
- packages/amesos2/src/Amesos2_Cholmod_def.hpp
@ndellingwood @srajama1 Added CholmodInt as a parameter which controls Cholmod to use CHOLMOD_INT instead of CHOLMOD_LONG. If you enable this and enable useGPU it throws an error, since GPU requires CHOLMOD_LONG.
To set this up I duplicated the data structures for long and int and just pick the right one at runtime based on the parameter. It could probably be made more concise with additional templating but I think that will be more confusing and won't fit very well into the Amesos2 code patterns.
Also fixes some documentation of the Cholmod parameters.
Resolves #7215 to add Cholmod Int support.
Mac parallel and serial builds, white Cuda builds. Also tested triangular solves.
> Amesos2: Add option to use Int Cholmod

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/test/unit_tests/CoalesceDropFactory.cpp
> MueLu: More cut drop stuff

- packages/amesos2/test/solvers/CMakeLists.txt
- packages/amesos2/test/solvers/cholmod_int_test.xml
Cholmod Int support was recently added. This adds a unit test for it.
Note that Cholmod int does not support Cholmod GPU. So the test always runs host Cholmod.
Cuda on white, Mac builds.
> Amesos2: Add test for Cholmod Int

- packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp
- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp
Avoid some Allreduces in setup.
> MueLu: Avoid some global communication in setup

- packages/shylu/shylu_node/tacho/src/impl/Tacho_Chol.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_Gemm.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_Herk.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_SetIdentity_OnDevice.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_SupernodeInfo.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TaskFunctor_FactorizeChol.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TaskFunctor_FactorizeCholByBlocks.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TaskFunctor_FactorizeCholByBlocksPanel.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TaskFunctor_FactorizeCholPanel.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TaskFunctor_SolveLowerChol.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TaskFunctor_SolveUpperChol.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_FactorizeChol.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveLowerChol.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_TeamFunctor_SolveUpperChol.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_Trsm.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_withLocalAccess.hpp
@trilinos/tpetra @trilinos/ifpack2 @trilinos/tacho
These changes fix compiler errors when enabling -std=c++14 with Intel 19 and nvcc.
> C++14 build fixes for Sierra

- packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_decl.hpp
- packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp
adds bicgstab to Stratimikos/belos
> Stratimikos: add bicgstab to belos via stratimikos options

- Version.cmake
Updating the version of Trilinos on the development branch.
> Update to version 13.1

- Version.cmake
- cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
I am updating the version of Trilinos on the release branch.
> Update version for release 13.0.0

- packages/panzer/adapters-stk/test/panzer_workset_builder/check_sorted_face_quads.cpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/test/core_tests/integration_values2.cpp
> 7789 Panzer: Fixes for Quadrature point sorting to support periodic wedge

- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/mmayr/composite_to_regions/src/SetupRegionSmoothers_def.hpp
- packages/muelu/research/mmayr/composite_to_regions/src/main.cpp
- packages/muelu/research/regionMG/examples/structured/CMakeLists.txt
- packages/muelu/research/regionMG/examples/structured/Driver_Structured_Regions.cpp
Adds the options for a W-cycle and Symmetric Gauss-Seidel smoother for region multigrid.
> MueLu: region w-cycle and symmetric Gauss-Seidel

- packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_kokkos_def.hpp
@csiefer2 @kddevin I think this are not needed and testing in #7797 suggested it is ok to remove them.
> MueLu: Remove unnecessary fences.

- packages/stk/stk_mesh/stk_mesh/base/CreateFaces.cpp
> STK: fix clang build

- packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
- packages/zoltan2/test/sphynx/CMakeLists.txt
- packages/zoltan2/test/sphynx/Test_Sphynx.cpp
Add option for a blockwise constant initial guess and full/partial orthogonalization.
> Zoltan2 Sphynx: Add options for initial guess and full/partial ortho

- packages/seacas/IossProperties.md
- packages/seacas/libraries/ioss/src/Ioss_Decomposition.C
- packages/seacas/libraries/ioss/src/Ioss_Decomposition.h
> IOSS: Allow use of property to set parmetis kway common_node count

- packages/zoltan2/test/core/unit/util/Metric.cpp
This will add testing which uses the metrics in
Zoltan2_ImbalanceMetricsUtility.hpp for useDegreeAsWeights.
Previously nothing was actually running that code.
Zoltan2_Metric test
> Zoltan2: Add useDegreeAsWeight testing

- packages/ifpack2/example/RelaxationWithEquilibration.cpp
- packages/tpetra/core/src/Tpetra_Details_LocalMap.hpp
- packages/tpetra/core/src/Tpetra_Export_def.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
- packages/tpetra/core/src/Tpetra_Map_decl.hpp
- packages/tpetra/core/src/Tpetra_Map_def.hpp
- packages/tpetra/core/test/CrsGraph/DetermineLocalTriangularStructure.cpp
- packages/tpetra/core/test/Map/Map_Bug2431.cpp
- packages/tpetra/core/test/Map/Map_LocalMap.cpp
- packages/tpetra/core/test/Map/Map_getMyGlobalIndices.cpp
- packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp
- packages/xpetra/test/Map/Map_UnitTests.cpp
- packages/zoltan2/core/src/input/Zoltan2_XpetraMultiVectorAdapter.hpp
Give map a host hash and remove fences as discussed in #7446 
@kddevin Code in clone method was also updated but it is deprecated and not tested.
Fences are being evaluated and removed from Tpetra when possible.
Tpetra unit tests. Checked white Cuda parallel build and Mac parallel/serial builds.
Also tested these changes with #7446  to verify fence removal works for CUDA_LAUNCH_BLOCKING=0 after these changes.
> Tpetra: Make host version of map hash

- packages/muelu/test/scaling/CMakeLists.txt
- packages/muelu/test/scaling/SpMVPerformance.cpp
Add performance test to compare timing of SpMV using Tpetra vs Epetra.
Closes #7719
N/A -- this is itself a test which will run on the performance dashboard.
> Tpetra: SpMV performance comparison

- packages/ifpack2/src/Ifpack2_RILUK_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRILUK.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestSingleProcessRILUK.cpp
This PR hopefully addresses #7847. As discussed with @ndellingwood, the default iluk implementation is set to Serial. The Kokkos Kernels SPILUK is set as an option which can be set with ```params.set("fact: type", "KSPILUK") ```. Unit tests are changed accordingly.
Tests have been performed on ```white``` with CTest
> Set KSPILUK as an option

- packages/tempus/src/Tempus_StepperDIRK_impl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyPID.hpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
- using "WRMS norm"
Clean up the error estimator computation and the PID TSCS.
Update the explicit embedded test - number of time step taken is reduced.
> Tempus: update embedded error estimate norm

- packages/muelu/src/Graph/HybridAggregation/MueLu_HybridAggregationFactory_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_IndexManager_decl.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_IndexManager_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_StructuredAggregationFactory_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_GlobalLexicographicIndexManager_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/coupled/MueLu_LocalLexicographicIndexManager_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/uncoupled/MueLu_UncoupledIndexManager_decl.hpp
- packages/muelu/src/Graph/StructuredAggregation/uncoupled/MueLu_UncoupledIndexManager_def.hpp
- packages/muelu/test/structured/CMakeLists.txt
- packages/muelu/test/structured/structured_scp_1dof.xml
- packages/muelu/test/structured/structured_sparc_1dof.xml
- packages/muelu/test/unit_tests/IndexManager.cpp
- packages/muelu/test/unit_tests/StructuredAggregationFactory.cpp
This will allow structured aggregation algorithm to coarsen each direction down to a single point.
This can be useful in multiple situation especially when the algorithm is used to perform semi-coarsening.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@rstumin wants the feature to get better load balancing for SPARC simulations.
Multiple unit-tests have been added to check all the classes modified.
A new nightly test is also added for general performance and to check multi-levels behavior.
> MueLu: single point structured coarsening

- packages/stk/stk_doc_tests/stk_io/howToWriteMeshWithEdges.cpp
- packages/stk/stk_doc_tests/stk_io/howToWriteRestartWithEdges.cpp
- packages/stk/stk_io/stk_io/FillMesh.cpp
- packages/stk/stk_io/stk_io/FillMesh.hpp
- packages/stk/stk_io/stk_io/IossBridge.cpp
- packages/stk/stk_io/stk_io/OutputFile.cpp
- packages/stk/stk_io/stk_io/OutputFile.hpp
- packages/stk/stk_io/stk_io/OutputParams.hpp
- packages/stk/stk_io/stk_io/ProcessSetsOrBlocks.cpp
- packages/stk/stk_io/stk_io/ProcessSetsOrBlocks.hpp
- packages/stk/stk_io/stk_io/StkMeshIoBroker.cpp
- packages/stk/stk_io/stk_io/StkMeshIoBroker.hpp
- packages/stk/stk_io/stk_io/WriteMesh.cpp
- packages/stk/stk_io/stk_io/WriteMesh.hpp
- packages/stk/stk_mesh/Jamfile
- packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp
- packages/stk/stk_mesh/stk_mesh/base/CreateEdges.cpp
- packages/stk/stk_mesh/stk_mesh/base/CreateFaces.cpp
- packages/stk/stk_mesh/stk_mesh/base/SkinBoundary.cpp
- packages/stk/stk_mesh/stk_mesh/baseImpl/ConnectEdgesImpl.cpp
- packages/stk/stk_mesh/stk_mesh/baseImpl/ConnectEdgesImpl.hpp
- packages/stk/stk_mesh/stk_mesh/baseImpl/MeshImplUtils.cpp
- packages/stk/stk_mesh/stk_mesh/baseImpl/MeshImplUtils.hpp
- packages/stk/stk_performance_tests/stk_mesh/SkinningLargeCube.cpp
- packages/stk/stk_unit_test_utils/stk_unit_test_utils/GetMeshSpec.hpp
- packages/stk/stk_unit_tests/stk_io/UnitTestReadWriteEdges.cpp
- packages/stk/stk_unit_tests/stk_io/UnitTestReadWriteEdges.hpp
- packages/stk/stk_unit_tests/stk_io/UnitTestReadWriteEdgesForFieldIO.cpp
- packages/stk/stk_unit_tests/stk_mesh/UnitTestTextMesh.cpp
- packages/stk/stk_unit_tests/stk_mesh/edge_creation/UnitTestEdgeConnection.cpp
> STK snapshot 2020-08-18

- packages/tempus/src/Tempus_IntegratorObserverBasic_impl.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyPID.hpp
Fix a minor bug/typo.
Also log the number of steps and step failure.
> Tempus: just some minor bug fixes

- packages/panzer/adapters-stk/test/evaluator_tests/basis_times_vector.cpp
Fix panzer tests for CUDA_LAUNCH_BLOCKING=0
Cuda white build - panzer tests.
> Panzer: Fix basis_times_vector.cpp for CUDA_LAUNCH_BLOCKING=0

- cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake
These should be resolved with the changes in #7856
@ccober6 
Re-enable tests in debug after work to reduce the time
* Closes #7861
> Re-enable the three tempus tests listed in #7861

- packages/panzer/adapters-stk/test/evaluator_tests/point_basis_values_evaluator.cpp
Fix Panzer for CUDA_LAUNCH_BLOCKING=0
Cuda white tests
> Panzer: Fix point_basis_values_evaluator for CUDA_LAUNCH_BLOCKING=0

- packages/muelu/test/unit_tests/RegionRFactory.cpp
Previously the unit test assumed the coordinate map is the same as the row map. That is only true in the case of one DOF per node. This change is necessary to support multiple DOFs per node on the RegionRFactory unit tests.
I reran all MueLu unit tests on Skybridge and they pass.
> MueLu: Update RegionRFactory unit test to use coordinate maps

- README
- README.md
Fixes #7905 and #7911.
Fixes incorrect link to user documentation.
Documentation only.
> Trilinos: fix links in README

- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
> Tempus: set Rel/Abs to currentstate for optimal initdt

- packages/kokkos/containers/src/Kokkos_DynamicView.hpp
Patch matching kokkos/kokkos#3315 by @crtrott
Reported by @bathmatt
> kokkos: Fix DynamicView reporting correct sizes and labels

- README.md
Fixed link to logo
Fixes bad link in documentation.
* Related to #7911.
Documentation change only.
> Trilinos: Update README.md

- packages/piro/src/Piro_TrapezoidRuleSolver_Def.hpp
> Piro: fix incorrect calculation of trapezoid rule time step

- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_debug_valgrind_muelu_geminga.cmake
- cmake/ctest/drivers/geminga/ctest_linux_nightly_serial_debug_valgrind_muelu_geminga.cmake
> Testing: Fix valgrind path on geminga

- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
Let's see if this fixes the random test failures..
> MueLu: Fix out-of-bounds in Notay aggregation

- packages/panzer/disc-fe/src/Panzer_L2Projection.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_BlockedTpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_DivBasisTimesScalar_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisCrossVector_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisDotVector_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_GradBasisTimesScalar_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp
- packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp
- packages/panzer/dof-mgr/src/Panzer_FieldAggPattern.cpp
@rppawlo This is an initial pass to address core fences in panzer.
This will remove all of them except the fences I added to Panzer_BasisValues2_impl.hpp, where we do currently need them for UVM. This PR does not fix spots which depend on UVM and I can address those in future PRs after we discuss.
I removed fences after deep_copy which should not be necessary.
I removed fences after host writes via UVM, which should not be necessary.
I removed fences after sync_host (which fences). It didn't seem we also needed the PHX::Device fence in these cases.
I have not encountered the View of Views setup before so not sure if there was a special consideration there. But I don't think fencing after those copies should matter.
I removed other fences which seemed unnecessary and …
> Panzer fence updates

- packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp
> MueLu: Fix bug in NotayAgg

- packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
Get tests passing for CUDA_LAUNCH_BLOCKING=0
Xpetra tests on white Cuda build
> Xpetra: Fence for UVM access of getLocalRowView

- packages/piro/src/Piro_TrapezoidRuleSolver.hpp
- packages/piro/src/Piro_TrapezoidRuleSolver_Def.hpp
> Add needed accessors for ACE in Albany

- cmake/ctest/drivers/rocketman/sendTestSummary.sh
@trilinos/muelu @trilinos/tpetra 
The test machine rocketman had its OS updated.  Updating this script is necessary (but maybe not sufficient) to get specialized testing running again.
N/A
Will be evaluated by overnight cronjob testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/7968)
> Trilinos: testing: update rocketman script

- packages/tempus/src/Tempus_TimeStepControlStrategyPID.hpp
> Tempus tscs pid patch

- packages/tempus/src/Tempus_StepperTrapezoidalAppAction.hpp
- packages/tempus/src/Tempus_StepperTrapezoidalAppActionComposite.hpp
- packages/tempus/src/Tempus_StepperTrapezoidalModifierBase.hpp
- packages/tempus/src/Tempus_StepperTrapezoidalModifierDefault.hpp
- packages/tempus/src/Tempus_StepperTrapezoidalModifierXBase.hpp
- packages/tempus/src/Tempus_StepperTrapezoidalModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperTrapezoidalObserverBase.hpp
- packages/tempus/src/Tempus_StepperTrapezoidalObserverDefault.hpp
- packages/tempus/src/Tempus_StepperTrapezoidal_decl.hpp
- packages/tempus/src/Tempus_StepperTrapezoidal_impl.hpp
- packages/tempus/unit_test/Tempus_UnitTest_Trapezoidal.cpp
> 7890 app action for trapezoidal rule

- cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake
> Ctest: Rocketman update

- packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
This PR adds a function which determines the default values for some parameters in Sphynx: preconditioner type, eigenvalue problem type, tolerance, and initial guess.
Tests in the local CUDA builds are passing.
> Zoltan2 Sphynx: Set default values for parameters

- packages/rol/example/tempus/ROL_TempusReducedObjective.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_impl.hpp
- packages/tempus/test/BDF2/Tempus_BDF2Test.cpp
- packages/tempus/test/BackwardEuler/Tempus_BackwardEulerTest.cpp
- packages/tempus/test/DIRK/Tempus_DIRKTest.cpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
- packages/tempus/test/ForwardEuler/Tempus_ForwardEulerTest.cpp
- packages/tempus/test/HHTAlpha/Tempus_HHTAlphaTest.cpp
- packages/tempus/test/IMEX_RK/Tempus_IMEX_RKTest.cpp
- packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_PartitionedTest.cpp
- packages/tempus/test/Leapfrog/Tempus_LeapfrogTest.cpp
- packages/tempus/test/Newmark/Tempus_NewmarkTest.cpp
- packages/tempus/test/OperatorSplit/Tempus_OperatorSplitTest.cpp
- packages/tempus/test/Subcycling/Tempus_SubcyclingTest.cpp
- packages/tempus/test/Trapezoidal/Tempus_TrapezoidalTest.cpp
To get the method name in integrator consistent with the naming from the solutionstat - fix capitalization.
> Tempus: integrator getXDot name change

- packages/tempus/src/Tempus_StepperNewmarkImplicitAFormAppAction.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAFormAppActionComposite.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAFormModifierBase.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAFormModifierDefault.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAFormModifierXBase.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAFormModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAForm_decl.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAForm_impl.hpp
- packages/tempus/unit_test/CMakeLists.txt
- packages/tempus/unit_test/Tempus_NewmarkImplicitAForm_HarmonicOscillator_Damped_SecondOrder.xml
- packages/tempus/unit_test/Tempus_UnitTest_NewmarkImplicitAForm.cpp
> Tempus: app action for newmark implicit a form

- packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
Resolve #8010 
guard Kokkos::fence for Epetra only build
Mac Tpetra and Epetra-only builds.
> Xpetra: Guard Kokkos fences for Tpetra only

- cmake/ctest/drivers/rocketman/CMakeLists.txt
- packages/muelu/src/Utils/MueLu_AvatarInterface.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
> TrilinosCouplings/MueLu/Ctest: Adding Avatar to 2D tests, enabling rocketman tests

- packages/tempus/src/Tempus_StepperNewmarkExplicitAFormAppAction.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAFormAppActionComposite.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAFormModifierBase.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAFormModifierDefault.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAFormModifierXBase.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAFormModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAForm_decl.hpp
- packages/tempus/src/Tempus_StepperNewmarkExplicitAForm_impl.hpp
- packages/tempus/unit_test/CMakeLists.txt
- packages/tempus/unit_test/Tempus_NewmarkExplicitAForm_HarmonicOscillator_Damped.xml
- packages/tempus/unit_test/Tempus_UnitTest_NewmarkExplicitAForm.cpp
- add unit_test for modifier and modifierX
Add AppAction interface for Newmark Explicit A Form
> Tempus: app action for newmark explicit a form

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc-cuda.cmake
- cmake/ctest/drivers/geminga/cron_driver.sh
Attempt to fix cuda testing on geminga.
> Geminga: Change modules for cuda testing

- cmake/TPLs/FindTPLAvatar.cmake
This should get the Avatar test on rocketman configuring again  #7969
Tests: n/a
> TPL: Modifying Avatar TPL for Release Version

- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
This is to improve communication packing and unpacking of Block Tridiag container on CUDA using multiple streams.
TESTS: SPARC scaling, vortex, 32GPUs.  No negative performance effect.
> Ifpack2 develop2

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc-cuda.cmake
- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_debug_muelu_kokkos_refactor_cuda_geminga.cmake
- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_amgx_cuda_geminga.cmake
- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_kokkos_refactor_cuda_geminga.cmake
> Geminga: Next round of cuda fixes

- packages/tempus/src/Tempus_StepperHHTAlphaAppAction.hpp
- packages/tempus/src/Tempus_StepperHHTAlphaAppActionComposite.hpp
- packages/tempus/src/Tempus_StepperHHTAlphaModifierBase.hpp
- packages/tempus/src/Tempus_StepperHHTAlphaModifierDefault.hpp
- packages/tempus/src/Tempus_StepperHHTAlphaModifierXBase.hpp
- packages/tempus/src/Tempus_StepperHHTAlphaModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperHHTAlphaObserverBase.hpp
- packages/tempus/src/Tempus_StepperHHTAlphaObserverDefault.hpp
- packages/tempus/src/Tempus_StepperHHTAlpha_decl.hpp
- packages/tempus/src/Tempus_StepperHHTAlpha_impl.hpp
- packages/tempus/unit_test/Tempus_UnitTest_BDF2.cpp
- packages/tempus/unit_test/Tempus_UnitTest_HHTAlpha.cpp
> 7891 app action for hht

- packages/tempus/src/Tempus_StepperLeapfrogAppAction.hpp
- packages/tempus/src/Tempus_StepperLeapfrogAppActionComposite.hpp
- packages/tempus/src/Tempus_StepperLeapfrogModifierBase.hpp
- packages/tempus/src/Tempus_StepperLeapfrogModifierDefault.hpp
- packages/tempus/src/Tempus_StepperLeapfrogModifierXBase.hpp
- packages/tempus/src/Tempus_StepperLeapfrogModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperLeapfrogObserverBase.hpp
- packages/tempus/src/Tempus_StepperLeapfrogObserverDefault.hpp
- packages/tempus/src/Tempus_StepperLeapfrog_decl.hpp
- packages/tempus/src/Tempus_StepperLeapfrog_impl.hpp
- packages/tempus/unit_test/Tempus_UnitTest_Leapfrog.cpp
> App action interface for leapfrog 7334

- packages/ifpack/src/Ifpack_Hypre.cpp
- packages/ifpack/src/Ifpack_Hypre.h
@trilinos/ifpack 
Port fix for a memory leak by @ecoon from #7809. 
Checked with valgrind.
@ecoon This should be pretty close to what you had. Could you confirm, either by pulling this branch or once this hits develop that this still works for you?
> Ifpack Hypre: Port fix by @ecoon

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp
> Lower case diff

- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_amgx_cuda_geminga.cmake
> Tests: Fixing geminga test

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_checkView.hpp
- packages/tpetra/core/src/Tpetra_Map_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_idot.hpp
Fixes compile time warnings.
Confirmed locally with gcc 7.2.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/8089)
> Tpetra: fix warnings

- packages/trilinoscouplings/cmake/TrilinosCouplings_config.h.in
- packages/trilinoscouplings/examples/scaling/CMakeLists.txt
- packages/trilinoscouplings/examples/scaling/Maxwell_avatar.xml
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_Statistics.hpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
> TrilinosCouplings: Enabling machine learning tests

- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_amgx_cuda_geminga.cmake
> Geminga: Fix AMGx build

- packages/tempus/src/Tempus_StepperNewmarkImplicitDFormAppAction.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDFormAppActionComposite.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDFormModifierBase.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDFormModifierDefault.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDFormModifierXBase.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDFormModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDForm_decl.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDForm_impl.hpp
- packages/tempus/unit_test/Tempus_UnitTest_NewmarkImplicitDForm.cpp
- AppAction interface for Newmark ImplicitDForm
- update unit_test: test AppAction
* Closes #7894
> Tempus: AppAction for newmark implicit d form

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc.cmake
Try to suppress warnings due to MPI.
> Geminga: Set valgrind suppression file

- packages/tempus/src/Tempus_TimeStepControlStrategyComposite.hpp
- packages/tempus/src/Tempus_TimeStepControl_decl.hpp
Update documentation
* Closes #2228
> Tempus: update documentation for TSC

- packages/xpetra/test/MultiVector/MultiVector_UnitTests.cpp
@kddevin This resolves the issue which is blocking PR #8104 from passing.
> Xpetra: Fix output

- packages/sacado/src/KokkosExp_View_Fad.hpp
- packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
- packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
@etphipp The changes we discussed to resolve duplication in the deep_copy specializations. The diff looks more complex because I had to flip the order and put the 2-arg specialization after the 3-arg. But this change is simply changing the 2-arg version to call the 3-arg version with fences before and after.
Resolves #7988 
Cuda white build -  stokhos tests
> Stokhos: Remove duplication for deep_copy specializations

- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
> TrilinosCouplings: Adding diffusive CFL output to Maxwell example

- packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_decl.hpp
- packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_def.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_refmaxwell.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/test/maxwell/CMakeLists.txt
- packages/muelu/test/maxwell/Maxwell2.xml
- packages/muelu/test/maxwell/Maxwell3D.cpp
- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
Fix and test reuse of RefMaxwell.
> MueLu RefMaxwell solver reuse

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_aggregation.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
Fix typo and underscore that breaks LaTeX
User guide will not build cleanly.
Confirmed locally that this PR allows the User Guide to build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/8128)
> MueLu: fix user guide

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_EpetraAztecOO_main.cpp
- packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Epetra_main.cpp
- packages/xpetra/src/Utils/ForwardDeclaration/Xpetra_EpetraCrsMatrix_fwd.hpp
- packages/xpetra/test/BlockedMultiVector/BlockedMultiVector_UnitTests.cpp
> Xpetra+MueLu: Fix some warnings

- packages/ifpack2/src/Ifpack2_Hypre_decl.hpp
- packages/ifpack2/src/Ifpack2_Hypre_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestHelpers.hpp
TESTS: RHEL7, GO=int & GO=long long
> Ifpack2: Updating TPL support

- packages/muelu/example/ParameterList/MLParameterList.cpp
- packages/muelu/example/advanced/blockcrs/BlockCrs.cpp
- packages/muelu/example/advanced/clone/Clone-Tpetra.cpp
- packages/muelu/example/advanced/levelwrap/LevelWrap.cpp
- packages/muelu/example/advanced/multiplesolve/FixedMatrixPattern.cpp
- packages/muelu/example/basic/Stratimikos.cpp
- packages/muelu/test/blockedtransfer/BlockedTransfer.cpp
- packages/muelu/test/convergence/Convergence.cpp
- packages/muelu/test/interface/CreateOperator.cpp
- packages/muelu/test/longlong/TwoBillion.cpp
- packages/muelu/test/navierstokes/Navier2DBlocked_BraessSarazinSmoother.cpp
- packages/muelu/test/navierstokes/Navier2DBlocked_Epetra.cpp
- packages/muelu/test/navierstokes/Navier2DBlocked_SimpleSmoother.cpp
- packages/muelu/test/navierstokes/Navier2DBlocked_test2.cpp
- packages/muelu/test/navierstokes/Navier2DBlocked_xml.cpp
- packages/muelu/test/navierstokes/Navier2D_Epetra.cpp
- packages/muelu/test/permutation/Permutation.cpp
- packages/muelu/test/profiling/Aggregation.cpp
- packages/muelu/test/scaling/JacobiKernelDriver.cpp
- packages/muelu/test/scaling/ReadMatrix.cpp
- packages/muelu/test/scaling/Reuse.cpp
- packages/muelu/test/scaling/TwoMatrixMMKernelDriver.cpp
- packages/muelu/test/simple1D/Emin.cpp
- packages/muelu/test/simple1D/aggregation.cpp
- packages/muelu/test/simple1D/amesos2.cpp
- packages/muelu/test/simple1D/mainMergedSmoo.cpp
- packages/muelu/test/simple1D/simple1D-UncoupledAggregation.cpp
- packages/muelu/test/toggletransfer/main.cpp
- packages/muelu/test/vardofpernode/VarDofDriver.cpp
> MueLu: Fix types in Permutation test and silence warnings

- packages/muelu/research/regionMG/test/structured/CMakeLists.txt
Fixes failing regionMG tests by removing them from serial builds. The removed tests were for rebalancing and thus not as relevant to a serial build.
The failing tests no longer appear in serial builds on my machine, but still appear and pass on non-serial builds.
> MueLu: regionMG disable rebalance tests in serial build

- packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
The header execinfo.h is causing build failures under Windows.
It was introduced for debugging reasons and is no longer needed.
Fixes #8157.
Fix compile error under Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/8158)
> Xpetra: remove unused header

- cmake/ctest/drivers/geminga/CMakeLists.txt
- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_cuda_no_uvm_geminga.cmake
Add a build with UVM disabled. This build currently fails all over the place..
> Geminga: Add CUDA build with UVM disabled

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc.cmake
- cmake/ctest/drivers/geminga/valgrind_suppressions.txt
> Geminga valgrind: Next attempt at suppression

- cmake/std/atdm/contributed/kokkos-dev/environment.sh
This PR adds a contributed atdm environment script for the kokkos-dev
testing machine
Add script using the atdm environment framework for Trilinos integration testings with Kokkos+KokkosKernels on the kokkos-dev developer system
Sample testing configuration tested
```bash
export TRILINOS_DIR=${HOME}/trilinos/Trilinos
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/kokkos-dev
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh kokkos-dev-cuda-opt
cmake  \
-GNinja  \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake  \
-DTrilinos_ENABLE_Kokkos=ON \
-DTrilinos_ENABLE_KokkosKernels=ON \
-DTrilinos_ENABLE_TpetraCore=ON \
-DCMAKE_CXX_STANDARD=14 \
-DCMAKE_INSTALL_PREFIX="${PWD}/install" \
$TRILINOS_DIR
```
> atdm contributed script: kokkos-dev test machine

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Lost the block size of the matrix in the recent refactor..
> MueLu RefMaxwell: Fix rebalancing issue

- packages/sacado/src/Sacado_Fad_Ops.hpp
- packages/sacado/src/mpl/Sacado_mpl_for_each.hpp
- packages/sacado/src/mpl/Sacado_mpl_integral_nonzero_constant.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp
> Sacado:  Replace missed KOKKOS_INLINE_FUNCTION with SACADO_INLINE_FUNCTION

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
> MueLu RefMaxwell: Fix boundary conditions when using first level of (1,1) hierarchy

- CMakeLists.txt
@bartlettroscoe
This allows Trilinos to be added as a dependent cmake fetchcontent at config time.
See https://github.com/trilinos/Trilinos/issues/8177 for a detailed discussion
* Follows https://github.com/trilinos/Trilinos/issues/8177
> Use CMAKE_CURRENT_LIST_DIR instead of CMAKE_SOURCE_DIR or CMAKE_CURRENT_SOURCE_DIR

- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_amgx_cuda_geminga.cmake
- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_cuda_no_uvm_geminga.cmake
- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_kokkos_refactor_cuda_geminga.cmake
> Geminga: Fix testing cmake configuration

- INSTALL.rst
- packages/kokkos/CMakeLists.txt
I believe the correct Cmake variable name is `CMAKE_INSTALL_PREFIX` rather than `CMAKE_INSTALL_PATH`.
Not applicable since this is a documentation-only change.
> installation documentation fixed.

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/test/structured/CMakeLists.txt
- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
To determine number of ranks for coarse rebalancing. Can still specify manually as well.
Also timers for region coarse level rebalance.
No longer have to manually specify number of ranks for coarse level rebalancing for regionMG
Covered by the rebalancing tests in regionMG.
> MueLu: regionMG added use of rebalance heuristic factory

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
> MueLu: Add thread rebalancing options to ParameterListInterpreter

- packages/tempus/src/Tempus_StepperBDF2AppAction.hpp
- packages/tempus/src/Tempus_StepperBDF2AppActionCompsite.hpp
- packages/tempus/src/Tempus_StepperBDF2ModifierBase.hpp
- packages/tempus/src/Tempus_StepperBDF2ModifierDefault.hpp
- packages/tempus/src/Tempus_StepperBDF2ModifierXBase.hpp
- packages/tempus/src/Tempus_StepperBDF2ModifierXDefault.hpp
- packages/tempus/src/Tempus_StepperBDF2ObserverBase.hpp
- packages/tempus/src/Tempus_StepperBDF2ObserverDefault.hpp
- packages/tempus/src/Tempus_StepperBDF2_decl.hpp
- packages/tempus/src/Tempus_StepperBDF2_impl.hpp
- packages/tempus/unit_test/Tempus_UnitTest_BDF2.cpp
> AppAction interface for BDF2

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_refmaxwell.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- Refactor row sum criterion, allow use with fine (1,1) block.
- Propagate Dirichlet conditions to fine (1,1) block instead of detecting zero rows
> MueLu RefMaxwell: BC fixes

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
> MueLu RefMaxwell: Guard Kokkos use

- packages/muelu/matlab/bin/muemex.cpp
- packages/muelu/matlab/bin/muemex.h
- packages/muelu/matlab/src/MueLu_MatlabSmoother_def.hpp
- packages/muelu/matlab/src/MueLu_MatlabUtils_decl.hpp
- packages/muelu/matlab/src/MueLu_MatlabUtils_def.hpp
- packages/muelu/matlab/tests/Brick/BrickAggregationUnitTest.m
- packages/muelu/matlab/tests/Brick/BrickAggregationUnitTestEasy.m
- packages/muelu/matlab/tests/CustomP/CustomPTest.m
- packages/muelu/matlab/tests/JacobiSmooth/JacobiSmoother_UnitTest.m
- packages/muelu/matlab/tests/JacobiSmooth/getDiag.m
- packages/muelu/matlab/tests/JacobiSmooth/jacobi.m
- packages/muelu/matlab/tests/PCoarsen/PCoarsenTest.m
- packages/muelu/matlab/tests/ReentrantDemo/Reentrant_Test.m
- packages/muelu/matlab/tests/UnsmoothedP/PtentEasy_UnitTest.m
- packages/muelu/matlab/tests/UnsmoothedP/Ptent_UnitTest.m
Get MueMex (MueLu-Matlab interface) working again:
- Construct Tpetra matrices with StaticProfile
- Create nullspace and put in "user data" sublist if not provided by user
- Avoid Belos SolverFactory, instead construct solvers directly (using factory again could be a future TODO)
@dridzal wanted to use MueMex.
The MueMex unit tests all passed cleanly.
> MueLu: fix MueMex

- packages/nox/src-loca/src-tpetra/LOCA_Tpetra_LowRankUpdateRowMatrix.hpp
@trilinos/nox 
The types of views look wrong.
> Nox: Fix view types

- packages/ifpack2/src/Ifpack2_Experimental_RBILUK_decl.hpp
- packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionMatrix_def.hpp
- packages/muelu/src/Graph/Containers/MueLu_Aggregates_kokkos_def.hpp
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_kokkos_decl.hpp
- packages/muelu/src/Graph/StructuredAggregation/MueLu_AggregationStructuredAlgorithm_kokkos_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase1Algorithm_kokkos_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2aAlgorithm_kokkos_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase2bAlgorithm_kokkos_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_AggregationPhase3Algorithm_kokkos_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_PreserveDirichletAggregationAlgorithm_kokkos_def.hpp
- packages/muelu/src/Misc/MueLu_CoordinatesTransferFactory_kokkos_def.hpp
- packages/muelu/src/Transfers/GeneralGeometric/MueLu_GeometricInterpolationPFactory_kokkos_def.hpp
- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_NullspaceFactory_kokkos_def.hpp
- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp
MueLu:
Replace `getLocalView<DeviceType>` with `getDeviceLocalView`.
Ifpack2:
Fix view types in RBILUK
Should fix build errors in Ifpack2, MueLu, Xpetra without UVM.
> MueLu: Replace getLocalView<DeviceType> with getDeviceLocalView

- packages/tpetra/core/inout/MatrixMarket_TpetraNew.hpp
@kddevin 
This PR separates the file read from matrix creation in MatrixMarket_TpetraNew.hpp. This separation is needed to minimize the code duplication when the binary reader is added. 
After this PR is merged, I will push another PR that adds `readBinary` function, which is an alternative to `readMatrixMarket`.
The example `TpetraCore_NewReaderExample.exe` and my triangle counting driver work correctly.
> Tpetra: Separate the file read from matrix creation in the new reader

- packages/belos/epetra/test/BiCGStab/CMakeLists.txt
- packages/belos/epetra/test/BiCGStab/test_bicgstab_diag.cpp
- packages/belos/src/BelosBiCGStabIter.hpp
- packages/belos/src/BelosBiCGStabSolMgr.hpp
There are three coefficient calculations in this implementation
of the BiCGStab algorithm that need to be checked to see if the
denominator is less than the sfmin for that scalar type.  These
checks have been added to the algorithm and logic has been added
to the solver manager to check for breakdown if the iteration
exits before convergence or the maximum number of iterations.
There is now a test that solves an inner-outer linear system
with diagonal matrices that checks for one type of breakdown
(the good kind).  The solver has been checked for the other types
of breakdown.
This has been tested in serial and parallel using GCC 4.9.2 and OpenMPI 1.10
> Fixes BiCGStab algorithm so that it detects breakdown

- packages/teuchos/core/src/Teuchos_ArrayViewDecl.hpp
@trilinos/teuchos  
Private member size_ of ArrayView of T  has type size_type.
The same member of ArrayView of const T had type int.  Overflows resulted.  
This PR changes size_ to have type size_type for both specializations of ArrayView.
int overflows for big problems
Tested on mac with clang.
> Teuchos:  changed declaration of size_ to size_type for ArrayView<const T> (as it is for ArrayView<T>)

- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRBILUK.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
> Ifpack2: Fix tests to build with UVM disabled

- packages/fei/base/fei_EqnCommMgr.cpp
> Fix fei issue for clang compiler, fix provided by Mike Glass.

- packages/muelu/src/Graph/Containers/MueLu_Aggregates_kokkos_def.hpp
Motivation: UVM removal
See #8265.
> MueLu: Fix Aggregates when UVM=off

- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellCuda.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
> MiniEM: Update rebalancing parameters

- cmake/std/atdm/contributed/blake/environment.sh
Add testing script for Blake testbed
Successfully tested build with Kokkos and KokkosKernels enabled with two configurations:
```bash
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/blake
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh gnu-serial
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh intel-serial
```
> atdm/contributed: environment script for blake testbed

- packages/amesos2/src/Amesos2_Superlu_def.hpp
Update Amesos2 SuperLU row perm option for version 5.2.2 (and newer)
`LargeDiag` -> `LargeDiag_MC64`
> Amesos2: Update SLU LargeDiag row perm option for SLU >= 5.2.2

- packages/panzer/dof-mgr/src/Panzer_GlobalIndexer.hpp
> Panzer GlobalIndexer: Fix small issue for no-UVM build

- packages/muelu/src/Misc/MueLu_FilteredAFactory_def.hpp
> MueLu: Fix spread lumping when using BuildNew() version of filtered matrix

- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
> TrilinosCouplings: Updates to example_Maxwell

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeHexMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp
stk-mesh headers should be included with a relative path in order to
make sure that cmake support can be kept consistent.
stk cmake support will soon be improved and '-I' paths will be cleaned
up.
> Minor fix to includes.

- packages/tpetra/core/inout/Tpetra_DistributionLowerTriangularBlock.hpp
@kddevin 
This PR fixes a bug in chunk computation.
> Tpetra: NewReader: Fix bug in chunk computation

- packages/tpetra/core/src/Tpetra_applyDirichletBoundaryCondition.hpp
#8209
TESTS: RHEL7, Cuda no UVM
> Tpetra: applyDirichlet BCs helper routine update

- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
- packages/tpetra/core/test/HashTable/FixedHashTableTest.cpp
Remove code that is not used or needed.
Negative lines of code.
* Closes #8350
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Tested on cee-lan with gcc compiler
module load sems-env
module load sems-cmake/3.10.3
module load sems-gcc/7.3.0
module load sems-openmpi/1.10.1
> Tpetra:  Cleaning up FixedHashTable class #8350

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- Short circuit on diagonal matrix and just build a one-level preconditioner.
- Add new solve mode that does smoothing-11-smoothing-22-smoothing-11-smoothing.
> MueLu RefMaxwell: Short circuit on diagonal matrix, add new solve mode

- packages/zoltan2/doc/algorithm/partition.dox
- packages/zoltan2/doc/algorithm/sphynx.dox
This PR adds a first draft of Sphynx documentation.
> Zoltan2: Sphynx: Add a first draft of documentation.

- cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake
- cmake/std/PullRequestLinuxIntel19.0.5TestingSettings.cmake
- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
- cmake/std/trilinosprhelpers/unittests/trilinos_pr_test.ini
This will put an Intel 19.0.5 build in place.
Closes #6294 
[CDash results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-intel19ZoltanScotchOFF-test-Trilinos_pullrequest_intel_19.0.5-104&field2=buildstamp&compare2=63&value2=Experimental) from building these changes with the Jenkins job that will run it.
While this does turn off a few tests, it will get an Intel 19 build out there and a new issue will be created to follow up on that work.
> Create Intel 19.0.5 Build

- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
Fixes issue in basis setup when cuda launch blocking is off.
Verified that this fixes issue in EMPIRE.
Won't be tested until framework team stands up a PR test with cuda launch blocking off.
> Panzer: fix for cuda launch blocking off.

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
Update the regionMG code to use Hierarchy and level containers to pass information, reducing the number of input parameters for the region functions.
The region tests pass with same output as before these changes.
> MueLu: regionMG use hierarchy and level containers

- packages/percept/src/adapt/Percept_MOAB_SimplexTemplateRefiner.hpp
- packages/percept/src/adapt/Refiner.cpp
- packages/percept/src/percept/Stacktrace.hpp
Seems I somehow missed a couple files with the last snapshot...
> Percept snapshot 12/01/2020

- packages/tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_def.hpp
For issue #8382 for invalid device reads from the host.
> Tpetra:  Fix CrsMatrix::getLocalDiagCopy() for GPU.

- packages/anasazi/epetra/src-rbgen/RBGen_AnasaziPOD.cpp
- packages/piro/src/Piro_NOXSolver_Def.hpp
- packages/piro/test/Piro_UnitTests.cpp
@mperego
@ikalash  
This PR removes 3 warnings which are treated as errors by the gcc 7.2.0 Debug build of the Trilinos autotester.
This branch has been tested on Blake using a Debug build with gcc 7.2.0.
> Remove Trilinos warnings when building with gcc 7.2.0

- packages/tpetra/core/inout/Tpetra_DistributionLowerTriangularBlock.hpp
@kddevin 
This PR fixes a few minor issues about the computation of the LowerTriangularBlock distribution:
-  I added the `sortedOrder` array as we need both the original permutation (`sortedOrder`) and the inverse permutation (`permuteIndex`). 
- I changed how `nnz` is computed. It is now the number of local nonzeros in the lower triangular part.
- I set `currentRunningTotal`  to zero before each new chunk starts.
After these changes, the original triangle counting code and this reader are resulting in the exact same chunks.
Triangle counting driver works correctly and the tests are unaffected (all passing).
> Tpetra: LowerTriangularBlock: fix chunking issues

- packages/panzer/disc-fe/src/Panzer_Workset_Utilities.cpp
fixes #8407 
closes #8407 
Verified fixes Charon builds with gcc 10.
All panzer tests use this feature.
> Panzer: gcc 10 compiler fix

- packages/piro/src/Piro_NOXSolver_Def.hpp
> Piro: call ReducedHessian only when required by the outArgs

- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
Fixes what appears to be a real issue, flagged by clang compiler.
Confirmed that this change resolves the clang warning
```
[1337/2534] Building CXX object packages/ifpack2/src/CMakeFiles/ifpack2.dir/Ifpack2_Relaxation_Serial.cpp.o
In file included from packages/ifpack2/src/Ifpack2_Details_Chebyshev_Serial.cpp:50:
/scratch/jhu/trilinos/Trilinos/packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp:657:25: warning: assigning field to itself [-Wself-assign-field]
eigNormalizationFreq_ = eigNormalizationFreq_;
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/8434)
> Ifpack2: fix initialization error

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
The different region row maps and col maps being stored in the level containers is information already available on that level through Matrices and Importers. The row maps and col maps have been removed to clean up what information is passed using the level container.
Region tests run locally and give an output that matches the output before these changes.
> MueLu: regionMG remove rowMap and colMap from level container

- packages/amesos2/src/Amesos2_Superlu_def.hpp
Use enum SLU::LargeDiag_MC64 for SuperLu version >= 5.2.1 (instead of 5.2.2).
> Minor fix to SuperLu version used for enum

- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
> TrilinosCouplings: Minor mods to Maxwell driver

- cmake/std/atdm/sems-rhel7/environment.sh
We need this to go to the new resource management stuff.
@jmgate @rppawlo @bartlettroscoe
> Updated to cmake 19 for Ross' cuda schedule fixes

- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
> TrilinosCouplings: More Maxwell Driver fixes

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionSmoothers_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionVector_def.hpp
Making changes suggested in #8437 
Region tests run locally and produce same result as before these changes.
> MueLu: regionMG replacing Map with const Map where possible to avoid casting

- packages/amesos2/src/Amesos2_Superlu_def.hpp
PR #8454 and related commit was motivated by an issue with the installation of the SuperLU library on NERSC Cori machine, reporting the wrong version number.
Reverting the commit
* Closes #8462
> Revert commit 75febde9

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/test/maxwell/CMakeLists.txt
- packages/muelu/test/maxwell/Maxwell3.xml
- packages/xpetra/src/Map/Xpetra_EpetraMap.hpp
- packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp
* Fix an RCP issue in the Epetra-Xpetra-Thyra interface
* Allow arbitrary Stratimikos preconditioners for the two subsolves of RefMaxwell
> MueLu RefMaxwell: Stratimikos subsolves

- packages/ml/src/RefMaxwell/ml_EdgeMatrixFreePreconditioner.cpp
- packages/ml/src/RefMaxwell/ml_RefMaxwell.cpp
- packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.cpp
- packages/ml/src/RefMaxwell/ml_RefMaxwell_Utils.h
- packages/ml/src/Utils/ml_ValidateParameters.cpp
> ML: Tweaks for RefMaxwell

- packages/ifpack/src/Ifpack_Hypre.cpp
- packages/ifpack/src/Ifpack_ValidParameters.cpp
- packages/ifpack2/src/Ifpack2_Hypre_def.hpp
- packages/ifpack2/src/Ifpack2_Parameters.cpp
- packages/stratimikos/adapters/ifpack/src/Thyra_IfpackPreconditionerFactory.cpp
@trilinos/ifpack @trilinos/ifpack2 
* Fix parameter validation for Hypre
* Attempt fixing #8433
> Ifpack/Ifpack2: Hypre fix

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Fix ifdefs. Should take care of #8551
> MueLu RefMaxwell: Fix #8551

- packages/intrepid2/unit-test/Shared/RealSpaceTools/test_01.hpp
This fixes #8537 
tested cuda with debug ON.
> Intrepid2 - issue 8357

- packages/intrepid2/src/Shared/Intrepid2_Data.hpp
- packages/panzer/adapters-stk/test/evaluator_tests/domain_interface.cpp
> Removed warnings

- packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefL2.hpp
> Intrepid2: fix issue with L2 projection to run w/out CUDA UVM

- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp
- packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_decl.hpp
- packages/stratimikos/adapters/belos/src/Thyra_BelosLinearOpWithSolveFactory_def.hpp
@trilinos/stratimikos @trilinos/muelu 
Fix issue in the Stratimikos smoother, add Fixed Point to the Belos Stratimikos adapter.
> MueLu: Fix Stratimikos smoother

- packages/phalanx/test/Field/Field.cpp
- packages/phalanx/test/Kokkos/tKokkos.cpp
- packages/phalanx/test/UnmanagedFields/KokkosView/View_TestEvaluators.hpp
Fix tests for layout swap.
Covered by all phalanx tests.
> Phalanx: update tests for layout swap

- packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
- packages/panzer/adapters-stk/src/Panzer_STK_WorksetFactory.cpp
- packages/panzer/adapters-stk/test/local_mesh/CMakeLists.txt
- packages/panzer/adapters-stk/test/local_mesh/PanzerSTK_UnitTest_BuildMesh.cpp
- packages/panzer/adapters-stk/test/local_mesh/PanzerSTK_UnitTest_BuildMesh.hpp
- packages/panzer/adapters-stk/test/local_mesh/PanzerSTK_UnitTest_STKInterfaceGenerator.cpp
- packages/panzer/adapters-stk/test/local_mesh/PanzerSTK_UnitTest_STKInterfaceGenerator.hpp
- packages/panzer/adapters-stk/test/local_mesh/local_mesh_utilities.cpp
- packages/panzer/adapters-stk/test/local_mesh/parallel_local_mesh_utilities.cpp
- packages/panzer/adapters-stk/test/local_mesh/parallel_periodic_local_mesh_utilities.cpp
- packages/panzer/disc-fe/src/Panzer_BasisDescriptor.cpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_LocalMeshInfo.hpp
- packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp
- packages/panzer/disc-fe/src/Panzer_OrientationsInterface.cpp
- packages/panzer/disc-fe/src/Panzer_OrientationsInterface.hpp
- packages/panzer/disc-fe/src/Panzer_PointDescriptor.hpp
- packages/panzer/disc-fe/src/Panzer_PointGenerator.hpp
- packages/panzer/disc-fe/src/Panzer_SetupPartitionedWorksetUtilities.cpp
- packages/panzer/disc-fe/src/Panzer_SetupPartitionedWorksetUtilities.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.hpp
- packages/panzer/disc-fe/src/Panzer_WorksetDescriptor.hpp
- packages/panzer/disc-fe/src/Panzer_WorksetFactoryBase.hpp
- packages/panzer/disc-fe/src/Panzer_Workset_Builder_impl.hpp
- packages/panzer/disc-fe/test/local_mesh/setup_partitioned_workset_utilities.cpp
> 8541 Panzer: Lazy evaluation of intrepid components

- packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.hpp
> Added a reset call

- packages/tpetra/core/inout/MatrixMarket_TpetraNew.hpp
- packages/tpetra/core/inout/Tpetra_DistributionLowerTriangularBlock.hpp
@trilinos/tpetra @kddevin 
This PR adds the per-process binary reader into the new Tpetra reader. The details are as follows (included in the code as a comment as well):
```
//////////////////////////////////////////////////////////////////////////////                                                                                                                                     
//////////// PER-PROCESS BINARY FILE READER & RESPECTIVE FORMAT //////////////                                                                                                                                     
//   (This format is used by the upcoming readPerProcessBinary function)    // …
```
> Tpetra: Add per-process binary reader 

- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
> TrilinosCouplings: Maxwell enhancements

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp
- packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
- packages/muelu/test/unit_tests/CMakeLists.txt
- packages/muelu/test/unit_tests/Smoothers/StratimikosSmoother.cpp
- Unit test for Stratimikos smoother
- Improvements for reuse scenarios
- Fix FPE in cut-based distance Laplacian
> MueLu: various changes

- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
Cleaning up the region test example driver, removing unused code.
Region tests pass as before.
Unit tests and region tests pass locally on my machine.
> MueLu: RegionMG cleaning up test example driver

- CMakeLists.txt
- cmake/std/PullRequestLinuxClang10.0.0TestingSettings.cmake
- cmake/std/PullRequestLinuxClang7.0.1TestingSettings.cmake
- cmake/std/PullRequestLinuxClang9.0.0TestingSettings.cmake
- cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
- cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake
- cmake/std/PullRequestLinuxGCC7.2.0SerialTestingSettings.cmake
- cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
- cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake
- cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake
- cmake/std/atdm/common/toss3/environment_tlcc2.sh
- doc/build_ref/TrilinosBuildReferenceTemplate.rst
Resolves conflicts from #8317.
> Update Trilinos to C++14

- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
#8673 reports new compilation errors in old code.  This change should fix the compilation.
@ikalash 
clang, mac
> tpetra: removed duplicate "using" statement for #8673

- packages/seacas/applications/nas2exo/N2EExoWriter.C
Remove a non C++-11 construct from the code.
> SEACAS: Fix non C++-11 construct

- packages/piro/src/Piro_PerformAnalysis.cpp
@trilinos/piro
@mperego 
This very small PR is intended to solve the capitalization of a parameter name of Piro.
The tests passed on Blake.
> Piro: Update the 'Number Of Parameters' option

- packages/stk/stk_balance/stk_balance/balanceUtils.cpp
- packages/stk/stk_balance/stk_balance/balanceUtils.hpp
- packages/stk/stk_balance/stk_balance/internal/Vertices.cpp
- packages/stk/stk_balance/stk_balance/internal/Zoltan2ParallelGraph.cpp
- packages/stk/stk_balance/stk_balance/setup/DefaultSettings.hpp
- packages/stk/stk_balance/stk_balance/setup/Parser.cpp
- packages/stk/stk_balance/stk_balance/setup/Parser.hpp
- packages/stk/stk_integration_tests/cmake_install_test/cuda_recipe
- packages/stk/stk_tools/stk_tools/block_extractor/ParseCsv.hpp
- packages/stk/stk_tools/stk_tools/block_extractor/main.cpp
- packages/stk/stk_unit_tests/stk_balance/UnitTestBlockWeights.cpp
- packages/stk/stk_unit_tests/stk_balance/UnitTestCommandLineParsing.cpp
- packages/stk/stk_unit_tests/stk_tools/block_extractor/UnitTestParseCommandLine.cpp
- packages/stk/stk_unit_tests/stk_util/util/UnitTestStringUtils.cpp
- packages/stk/stk_util/stk_util/util/ParameterList.cpp
- packages/stk/stk_util/stk_util/util/string_utils.cpp
- packages/stk/stk_util/stk_util/util/string_utils.hpp
> STK: Snapshot patch 02-04-21

- packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
This PR will hopefully fix the random failure of Sphynx with polynomial preconditioner on the 25x25 test matrix (https://github.com/trilinos/Trilinos/issues/8540) by reducing the polynomial degree from 25 to 5 for matrices with less than 100 rows.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to https://github.com/trilinos/Trilinos/issues/8540
* Part of 
* Composed of
> Zoltan2: Sphynx: Reduce polynomial degree for small matrices

- packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
- packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgQuotient.hpp
- packages/zoltan2/core/src/models/Zoltan2_CommGraphModel.hpp
- packages/zoltan2/core/src/models/Zoltan2_Model.hpp
- packages/zoltan2/core/src/problems/Zoltan2_PartitioningProblem.hpp
- packages/zoltan2/core/src/problems/Zoltan2_Problem.hpp
- packages/zoltan2/test/core/partition/CMakeLists.txt
- packages/zoltan2/test/core/partition/partitioning1.cpp
This PR changes the Quotient Algorithm interface and testing as follows:
1) It makes the AlgQuotient class take InputAdapter as input instead of CommGraphModel and creates the CommGraphModel internally in the AlgQuotient class. It removes the creation of commGraphModel from PartitioningProblem class.
2) It extends the small quotient partitioning solution to the matrix size so that each local row has a separate entry in the resulting partitioning vector.  
3) It removes the flag migrated_ and its getter function because the migration is always performed. It also removes the untested else branch for the non-migrated case. 
4) It allows user to set the threshold_ parameter.
5) It adds new tests for the Quotient algorithm with different threshold values (1 and 2) and the …
> Zoltan2: Update the Quotient algorithm interface and add more tests

- packages/tpetra/core/inout/MatrixMarket_TpetraNew.hpp
- packages/tpetra/core/test/inout/CMakeLists.txt
- packages/tpetra/core/test/inout/MatrixMarket_Tpetra_CrsMatrix_Dist.cpp
In #7045 , we added a 2D matrix market reader.  It has an option to exclude or require matrix diagonal entries.  This PR adds tests for excluding diagonals with all matrix distributions supported.
Also changed option "ignore" to "exclude"; it sounds better.
@ndellingwood 
Tested on mac with clang
> Tpetra 2D reader:  add test for excluding diagonals

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Allow skipping of boundary condition enforcement in MueLu RefMaxwell
> MueLu RefMaxwell: Allow skipping enforcement of BCs

- packages/muelu/src/Misc/MueLu_FilteredAFactory_def.hpp
Fix an out-of-bounds error in FilteredA.
> MueLu FilteredAFactory: Fix out-of-bounds error

- cmake/std/PullRequestLinuxCuda10.1.105uvmTestingSettings.cmake
- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestCuda10.1.105uvmTestingEnv.sh
- cmake/std/unittests/TestPullRequestLinuxDriverTest.py
Just before #8633 was submitted, there were some cmake changes that it missed.
This will fix the issue with cmake that is currently causing the build to fail.
Since it was last tested, 21 more tests are failing. To get dev->master moving again, this will turn those off.
The also adds tests that were left out for both cuda 10.1 build uvm off & on.
Related to #8397
> cupdate cuda buidls

- packages/panzer/adapters-stk/src/Panzer_STK_WorksetFactory.cpp
- packages/panzer/adapters-stk/test/panzer_workset_builder/CMakeLists.txt
- packages/panzer/adapters-stk/test/panzer_workset_builder/apply_orientations.cpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/Panzer_WorksetContainer.cpp
- packages/panzer/disc-fe/src/Panzer_WorksetContainer.hpp
> 8686 Panzer: Adding WorksetOptions to Workset during setup

- cmake/ctest/drivers/enigma/cron_driver.sh
- cmake/ctest/drivers/geminga/cron_driver.sh
- cmake/ctest/drivers/trappist/cron_driver.sh
This should fix MueLu's nightly builds which we rely on for regression testing.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of #8730 
* Composed of 
No feedback on this internal change
No testing was performed but we will monitor the nightly build results once this merges
> MueLu: updating cron scrip on enigma, geminga and trappist

- packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp
Rename local variable to fix hidden variable warning.
> Intrepid2: fix warning

- cmake/std/trilinosprhelpers/unittests/trilinos_pr_test.ini
Updating CUDA unit tests in trilinos_pr_test.ini still using cmake 3.11.2 to use cmake 3.17.2 to pass version minimum check.
> Update CUDA unit tests in trilinos_pr_test.ini to use cmake 3.17.2.

- cmake/ctest/drivers/lightsaber/cron_driver.csh
> Ctest: Lightsaber module updates

- packages/zoltan2/doc/algorithm/sphynx.dox
- packages/zoltan2/sampleScripts/configure_sphynx_summit
This PR adds the documentation text and a sample Trilinos build script for Sphynx.
> Zoltan2: Add documentation for Sphynx

- packages/shylu/shylu_node/tacho/example/Tacho_ExampleCholPardiso.cpp
#8757 reports a compiling error. This fix the issue.
#8757 
Tested on blake with intel mkl as reported in the issue above.
> Tacho - fix the bug described in #8757

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/Misc/MueLu_AggregateQualityEstimateFactory_decl.hpp
- packages/muelu/src/Misc/MueLu_AggregateQualityEstimateFactory_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
> MueLu: Adding aggregate size percentiles to AggregateQuality

- cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake
@trilinos/framework @rppawlo @ccober6 @srajama1 
Trilinos will need to support C++17 in the near future with an updated version of Kokkos. This PR will test compatibility with C++17. It will not require C++17 as a minimum.
Closes #8391
> Switch GCC 8.3 PR build to C++17

- packages/muelu/src/Misc/MueLu_AggregateQualityEstimateFactory_def.hpp
> MueLu: Minor fix to AggregateQualityFactory

- packages/piro/src/Piro_SteadyStateSolver_Def.hpp
@trilinos/piro
@mperego
This PR is intended to solve a bug which arises when more than 1 response is used.
The commit has been tested on Blake.
> Piro: solve a bug when more than 1 response is used

- packages/stk/stk_integration_tests/mock_apps/SparcMesh.hpp
- packages/stk/stk_integration_tests/mock_apps/StkMesh.hpp
- packages/stk/stk_integration_tests/mock_apps/StkSendAdapter.hpp
- packages/stk/stk_integration_tests/mock_apps/mock_aria.cpp
- packages/stk/stk_integration_tests/mock_apps/mock_fuego.cpp
- packages/stk/stk_integration_tests/mock_apps/mock_salinas.cpp
- packages/stk/stk_integration_tests/mock_apps/mock_sparc.cpp
- packages/stk/stk_mesh/stk_mesh/base/BulkData.cpp
- packages/stk/stk_unit_tests/stk_coupling/UnitTestSyncInfo.cpp
> STK: Snapshot 02-24-21 10:53

- packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
- packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.hpp
- packages/panzer/adapters-stk/test/panzer_workset_builder/CMakeLists.txt
- packages/panzer/adapters-stk/test/panzer_workset_builder/parallel_apply_orientations.cpp
- packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp
- packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.hpp
- packages/panzer/disc-fe/src/Panzer_OrientationsInterface.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
> Fix for ghost orientations.

- packages/tempus/src/Tempus_Stepper.cpp
- packages/tempus/src/Tempus_Stepper_decl.hpp
- packages/tempus/src/Tempus_Stepper_impl.hpp
Move Stepper Helper functions to the implementation.
Take advantage ETI ON/OFF.
> Tempus: Move Stepper Helper Functions to Implementation

- packages/pamgen/rtcompiler/RTC_ArrayVarRTC.hh
@trilinos/pamgen 
There is an uninitialized memory issue pamgen. This seems to fix it.
> Pamgen rtc valgrind error fix

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_misc.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/test/unit_tests/MueLu_TestHelpers.hpp
> MueLu: Adding Aggregates Output

- packages/phalanx/src/Phalanx_VirtualFunctionOnDevice.hpp
- packages/phalanx/test/Kokkos/CMakeLists.txt
- packages/phalanx/test/Kokkos/tKokkos.cpp
- packages/phalanx/test/Kokkos/tKokkosVirtualFunctionOnDevice.cpp
Added utilities for putting a virtual function on device. Also serves as a simple tutorial example.
> Phalanx: utilities for virtual functions on device

- packages/zoltan/src/params/free_params.c
- packages/zoltan/test/misc_tests/copyZZ.c
Minor changes to make non-c99 compilers happy.
* Closes  #8816
@iulian787
Tested on mac with clang
> Zoltan : minor changes to make compliant with non-c99 compilers

- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/test/interface/ParameterListInterpreter.cpp
- packages/muelu/test/interface/default/Output/MLcoarse1b_epetra.gold
- packages/muelu/test/interface/default/Output/MLcoarse2b_epetra.gold
- packages/muelu/test/interface/default/Output/MLcoarse3b_epetra.gold
- packages/muelu/test/interface/default/Output/MLcoarse4b_epetra.gold
- packages/muelu/test/interface/default/Output/MLemptyb_epetra.gold
- packages/muelu/test/interface/default/Output/MLpgamg1b_epetra.gold
- packages/muelu/test/interface/default/Output/MLpgamg2b_epetra.gold
- packages/muelu/test/interface/default/Output/MLsmoother1b_epetra.gold
- packages/muelu/test/interface/default/Output/MLsmoother2b_epetra.gold
- packages/muelu/test/interface/default/Output/MLsmoother3b_epetra.gold
- packages/muelu/test/interface/default/Output/MLsmoother4b_epetra.gold
- packages/muelu/test/interface/default/Output/MLunsmoothed1b_epetra.gold
Special handling for "ML output" to MueLu's "verbosity" translation.
> MueLu ML2MueLuParameterTranslator: Correctly translate verbosity

- cmake/std/atdm/common/toss3/environment_tlcc2.sh
Fix broken atdm builds
* Closes #8861
> Correct gcc module loaded for tlcc2 builds

- packages/muelu/src/Graph/HybridAggregation/MueLu_HybridAggregationFactory_def.hpp
Adds missing aggregation parameter to parameter list for Hybrid aggregation.
Solves #8846 
Tests pass on my local machine.
> MueLu: Add phase2a agg factor to param list for hybrid aggregation

- packages/piro/src/CMakeLists.txt
- packages/piro/src/Piro_Epetra_NOXSolver.cpp
- packages/piro/src/Piro_LOCAAdaptiveSolver_Def.hpp
- packages/piro/src/Piro_LOCASolver_Def.hpp
- packages/piro/src/Piro_NOXSolver_Def.hpp
- packages/piro/src/Piro_PerformAnalysis.cpp
- packages/piro/src/Piro_PerformAnalysis.hpp
- packages/piro/src/Piro_ROL_ObserverBase.hpp
- packages/piro/src/Piro_SteadyStateSolver.hpp
- packages/piro/src/Piro_SteadyStateSolver_Def.hpp
- packages/piro/src/Piro_ThyraProductME_Constraint_SimOpt.hpp
- packages/piro/src/Piro_ThyraProductME_Objective_SimOpt.hpp
- packages/piro/test/Main_AnalysisDriver.cpp
- packages/piro/test/Main_AnalysisDriver_Tpetra.cpp
@trilinos/piro
@mperego 
This PR:
- adds the option to use the `Enable Explicit Matrix Transpose` in `Piro::PerformSolve`,
- adds the usage of observers in `Piro:: PerformAnalysis` while using ROL Thyra adapters in Piro. 
This branch has been tested on Blake.
> Piro: use observers while using ROL in PerformAnalysis and add an option to PerformSolve

- packages/kokkos-kernels/src/graph/KokkosGraph_Distance1ColorHandle.hpp
- packages/kokkos-kernels/src/graph/KokkosGraph_Distance2ColorHandle.hpp
This PR just fixed a very small bug. I just changed `std:cout` to `std::cout` in two files.
> KokkosKernels: std::

- packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
- packages/panzer/mini-em/example/BlockPrec/main.cpp
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwell.xml
- packages/panzer/mini-em/example/BlockPrec/solverMueLuRefMaxwellEpetra.xml
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.hpp
Enable and test reuse in MiniEM.
> MiniEM: Enable reuse, test it

- cmake/ctest/drivers/geminga/valgrind_suppressions.txt
> Geminga: Another attempt to get valgrind suppressions working

- packages/tempus/src/Tempus_StepperDIRK_decl.hpp
- packages/tempus/unit_test/CMakeLists.txt
- packages/tempus/unit_test/Tempus_DIRK_VanDerPol.xml
- packages/tempus/unit_test/Tempus_UnitTest_DIRK_BackwardEuler.cpp
Tempus was only using the default solver PL for steppers like
`RK Backward Euler`. This PR will check if the user has provided a
solver PL and make sure to override the default solver PL
> Tempus: set App nonlinear solver PL if available

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc.cmake
- cmake/ctest/drivers/geminga/valgrind_suppressions.txt
> Geminga: next attempt to get valgrind to work

- packages/stk/stk_balance/stk_balance/balanceUtils.hpp
- packages/stk/stk_balance/stk_balance/internal/StkBalanceUtils.cpp
- packages/stk/stk_balance/stk_balance/internal/Zoltan2ParallelGraph.cpp
- packages/stk/stk_balance/stk_balance/m2n_main/m2nMain.cpp
- packages/stk/stk_coupling/stk_coupling/OldCommSplitting.cpp
- packages/stk/stk_coupling/stk_coupling/OldCommSplitting.hpp
- packages/stk/stk_coupling/stk_coupling/OldSyncInfo.cpp
- packages/stk/stk_coupling/stk_coupling/SplitComms.cpp
- packages/stk/stk_coupling/stk_coupling/SplitComms.hpp
- packages/stk/stk_coupling/stk_coupling/SyncInfo.cpp
- packages/stk/stk_coupling/stk_coupling/SyncInfo.hpp
- packages/stk/stk_coupling/stk_coupling/impl_NamedValues.hpp
- packages/stk/stk_integration_tests/mock_apps/MockUtils.hpp
- packages/stk/stk_integration_tests/mock_apps/mock_aria.cpp
- packages/stk/stk_integration_tests/mock_apps/mock_fuego.cpp
- packages/stk/stk_integration_tests/mock_apps/mock_salinas.cpp
- packages/stk/stk_integration_tests/mock_apps/mock_sparc.cpp
- packages/stk/stk_integration_tests/stk_balance/IntegrationTestIncrementalRebalance.cpp
- packages/stk/stk_integration_tests/stk_balance/IntegrationTestLoadBalance.cpp
- packages/stk/stk_io/example/io_mesh_read_write_example.cpp
- packages/stk/stk_tools/stk_tools/scripts/test_coupling_today_to_yesterday.sh
- packages/stk/stk_unit_tests/stk_balance/UnitTestBoundingBoxSearch.cpp
- packages/stk/stk_unit_tests/stk_balance/UnitTestBoundingBoxSearch2D.cpp
- packages/stk/stk_unit_tests/stk_balance/UnitTestCrossProcessorEdge.cpp
- packages/stk/stk_unit_tests/stk_coupling/UnitTestNamedValues.cpp
- packages/stk/stk_unit_tests/stk_coupling/UnitTestOldCommSplitting.cpp
- packages/stk/stk_unit_tests/stk_coupling/UnitTestOldSyncInfo.cpp
- packages/stk/stk_unit_tests/stk_coupling/UnitTestSplitComm.cpp
- packages/stk/stk_unit_tests/stk_coupling/UnitTestSyncInfo.cpp
- packages/stk/stk_unit_tests/stk_coupling/UnitTestVersion.cpp
> STK: Snapshot 03-17-21 07:17

- cmake/ctest/drivers/ascicgpu031/drakify-email.pl
- cmake/ctest/drivers/ascicgpu031/sendTestSummary.sh
> Ctest: More ascicgpu031 updates

- .github/workflows/stale.yml
Update the version of the auto-closer **action** script to v3.0.18 from v3.0.17.  
@jwillenbring @prwolfe
> Framework: Update the auto-closer github action script to v3.0.18

- cmake/ctest/drivers/ascicgpu031/CMakeLists.txt
- cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.crs.cmake
- cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_release_nouvm_crs_ascicgpu031.cmake
Adding testing of tpetraCrsRefactor branch
NA:  for testing
> tpetra:  adding auto-testing for CrsRefactor branch

- packages/ifpack2/src/Ifpack2_Details_OverlappingRowGraph_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_OverlappingRowGraph_def.hpp
- packages/ifpack2/src/Ifpack2_Details_RowGraph.hpp
- packages/ifpack2/src/Ifpack2_DiagonalFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_DiagonalFilter_def.hpp
- packages/ifpack2/src/Ifpack2_DropFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_DropFilter_def.hpp
- packages/ifpack2/src/Ifpack2_LocalFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_LocalFilter_def.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_decl.hpp
- packages/ifpack2/src/Ifpack2_OverlappingRowMatrix_def.hpp
- packages/ifpack2/src/Ifpack2_ReorderFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_ReorderFilter_def.hpp
- packages/ifpack2/src/Ifpack2_SingletonFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_SingletonFilter_def.hpp
- packages/ifpack2/src/Ifpack2_SparsityFilter_decl.hpp
- packages/ifpack2/src/Ifpack2_SparsityFilter_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestHelpers.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_RowGraph_decl.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_createDeepCopy.cpp
@kddevin If you don't see anything you object to, just merge this.
> Tpetra/Ifpack2: Updates to get Ifpack2 to compile & link

- packages/nox/src-loca/src-tpetra/LOCA_Tpetra_ConstraintModelEvaluator.cpp
better error reporting in constraint ME
LOCA Tpetra Householder test exercises this change
> Nox better error message

- packages/seacas/libraries/exodus/include/ExodusLargeModel.md
- packages/seacas/libraries/ioss/src/Ioss_DBUsage.h
- packages/seacas/libraries/ioss/src/Ioss_Region.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_ParallelDatabaseIO.C
- packages/seacas/libraries/ioss/src/cgns/Iocgns_StructuredZoneData.C
- packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
- packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.h
- packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.C
- packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.h
- packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C
- packages/seacas/libraries/ioss/src/exodus/Ioex_ParallelDatabaseIO.C
- packages/seacas/libraries/ioss/src/exodus/Ioex_ParallelDatabaseIO.h
- packages/seacas/libraries/ioss/src/fmt
- packages/seacas/libraries/ioss/src/main/io_modify.C
- packages/seacas/libraries/ioss/src/visualization/catalyst/include/ParaViewCatalystCGNSAdapter.h
- packages/seacas/libraries/ioss/src/visualization/catalyst/include/ParaViewCatalystIossAdapter.h
- packages/seacas/libraries/ioss/src/visualization/catalyst/include/vtkCGNSMultiBlockDataSet.h
- packages/seacas/libraries/ioss/src/visualization/catalyst/include/vtkExodusIIMultiBlockDataSet.h
- packages/seacas/libraries/supes/ext_lib/exdate.c
Origin repo remote tracking branch: 'origin/master'
Origin repo remote repo URL: 'origin = https://github.com/gsjaardema/seacas'
At commit:
commit ba4155619b60e529d9bcc9535307c02ef439d29e
Author:  Greg Sjaardema <gsjaardema@gmail.com>
Date:    Fri Apr 2 14:00:36 2021 -0600
Summary: clang-format
* Add missing catalyst include files
* clang-format changes
* Add DB_MODIFY -- similar to DB_APPEND except for some metadata
differences. Used in io_modify
> Automatic snapshot commit from seacas at ba4155619b

- cmake/ctest/drivers/ascicgpu031/cron_driver.sh
Tests: Modifying nirhgtly test
> Ctest: Fixing TMPDIR issue

- cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.cmake
- cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.crs.cmake
If they don't build, @kddevin will fix them
Without Zoltan, some MueLu tests fail.  This PR enables Zoltan for the test builds on ascicgpu machines.
Comments in the files said Zoltan does not build; if they prove to be true, @kddevin will fix the issues ASAP.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to  #8821 #8930 
* Part of 
* Composed of 
NA:  these are files to create tests
> Tpetra:  zoltan enabled on ascicgpu tests

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/trilinoscouplings/examples/scaling/CMakeLists.txt
- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
- packages/trilinoscouplings/examples/scaling/stratimikos.xml
@trilinos/muelu @trilinos/trilinoscouplings 
- Fix crash with bad parameter in RefMaxwell sublist
- Allow arbitrary Stratimikos solver/preconditioner in TrilinosCouplings Maxwell
> RefMaxwell stuff

- packages/seacas/libraries/ioss/src/visualization/cgns/Iovs_cgns_DatabaseIO.h
- packages/seacas/libraries/ioss/src/visualization/exodus/Iovs_exodus_DatabaseIO.h
The include path should not specifiy the path from the base level of IOSS since that path is not valid when IOSS Visualization library is used with an installed Trilinos
Addresses #8967
Closes #8967
> SEACAS: Fix include path

- packages/ifpack2/src/Ifpack2_Details_GaussSeidel.hpp
PR #8787 rewrote local Gauss-Seidel and changed the order additions were
performed. That order was worse numerically, so this changes back to the
old order.
Bad (order from 8787):
```
(((b_i - A_i1 * x_1) - A_i2 * x_2) + ...)
```
Good (old order, and restored in this PR):
```
b_i - ((A_i1 * x_1 + A_i2 * x_2) + ...)
```
b_i may be a lot bigger than some of the Ax terms, so that was causing lost accuracy.
This fixes a numerical regression in Nalu: #8985 .
This code is tested in Ifpack2's unit and belos tests.
> Ifpack2: fix gauss-seidel numerical issues (#8985)

- packages/zoltan/README.md
- packages/zoltan/src/include/zoltan.h
Includes Zoltan Struct serialization needed by iMOAB for E3SM coupling.
#8476 #8646 
@iulian787 @vijaysm 
Zoltan is passing all Trilinos PR testing
Autotools build tested on mac with clang.
> Zoltan:  new release for iMOAB team

- cmake/std/PullRequestLinuxCuda10.1.105uvmTestingSettings.cmake
This will turn off two SEACAS tests that are not being run due to them being unable to find files after a major recent ROL merge.
These tests can be turned back on when the issue is corrected for the UVM = OFF build.
In response to #8991
> Turn off tests that are not running and causing dev2master to fail.

- packages/muelu/test/interface/CreateOperator.cpp
- packages/muelu/test/interface/default/Output/operator_solve_1_np1_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_1_np1_tpetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_1_np4_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_1_np4_tpetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_5_np1_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_5_np1_tpetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_5_np4_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_5_np4_tpetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_6_np1_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_6_np1_tpetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_6_np4_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_6_np4_tpetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_7_np1_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_7_np1_tpetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_7_np4_epetra.gold
- packages/muelu/test/interface/default/Output/operator_solve_7_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_1_np1_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_1_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_5_np1_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_5_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_6_np1_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_6_np4_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_7_np1_tpetra.gold
- packages/muelu/test/interface/kokkos/Output/operator_solve_7_np4_tpetra.gold
Ignore default values in CreateOperator test.
> MueLu: Gold files

- cmake/ctest/drivers/ascicgpu031/drakify-email.pl
> Ctest: Fixing emailer for ascicgpu031

- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_Element.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_FE.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_MeshDatabase.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_TotalElementLoop.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_typedefs.hpp
Fix the FEA example in tpetra so that it 1) works, and 2) is more in-line with our refactor using wrapped dual views.
This is a change to the test, so the test should actually work now.
> FEM assembly

- packages/galeri/src-xpetra/Galeri_StencilProblems.hpp
- packages/galeri/src-xpetra/Galeri_XpetraParameters.hpp
- packages/galeri/src-xpetra/Galeri_XpetraProblemFactory.hpp
- packages/muelu/test/scaling/MatrixLoad.hpp
Add a 2D anisotropic diffusion problem.
> Galeri Xpetra: Add anisotropic diffusion problem

- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
Kokko::Complex needs special handling (impl_scalar_type) for CUDA builds.  This PR gives some examples.
I have requested a Trilinos PR test with CUDA and Complex enabled #9025 , since the CUDA case is the driver for Kokkos::Complex.
Here's the error that appears when running in the develop branch:
```
147. Hierarchy_std_complex0double0_int_longlong_Kokkos_Compat_KokkosCudaWrapperNode_DescriptionCaching_UnitTest ... terminate called after throwing an instance of 'std::runtime_error'
what():  cudaDeviceSynchronize() error( cudaErrorLaunchFailure): unspecified launch failure Trilinos/packages/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:143
```
The issues arise when trying to access anything with std::complex<> on device.
This PR doesn't fix all problems; it merely shows an …
> MueLu:  changes needed to handle Kokkos::complex in Cuda builds

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/xpetra/src/Operator/Xpetra_EpetraOperator.hpp
Pass the correct nullspace to the coarse (1,1) hierarchy instead of constants.
> MueLu RefMaxwell: Pass corrected nullspace to coarse (1,1) hierarchy

- cmake/ctest/drivers/ascicgpu031/drakify-email.pl
> Ctest: Updating reporting script

- cmake/std/PullRequestLinuxCuda10.1.105uvmTestingSettings.cmake
Turning off a few tests for the UVM Off build per #9068.
This should get the Master Merge builds moving again.
> Disable tests in the UVM Off build

- packages/ifpack/src/Ifpack_PointRelaxation.cpp
- packages/ifpack2/src/CMakeLists.txt
- packages/ifpack2/src/Ifpack2_Details_InverseDiagonalKernel_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_InverseDiagonalKernel_def.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_decl.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
@trilinos/ifpack @trilinos/ifpack2 
Fix a tiny issue in the L1 option for relaxation smoothers
> Ifpack & Ifpack2: Fix tiny bug in L1 method

- cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake
- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
This branch will change the intel 17 PR build to use SuperLU_Dist instead of SuperLU as requested in #1091 
* Closes #1091
Built and tests run on ascic166 and my local blade.
> Add super lu dist pr test

- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- packages/muelu/test/unit_tests/Smoothers/Ifpack2Smoother.cpp
Enable reuse for Chebyshev smoother
> MueLu: Reuse Chebyshev smoother

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionMatrix_def.hpp
- packages/muelu/test/unit_tests/RegionMatrix.cpp
- packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp
- packages/xpetra/src/BlockedCrsMatrix/Xpetra_ReorderedBlockedCrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_decl.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_decl.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_def.hpp
- packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_decl.hpp
- packages/xpetra/sup/Matrix/Xpetra_CrsMatrixWrap_def.hpp
- packages/xpetra/sup/Matrix/Xpetra_Matrix.hpp
For use with the region mg. This is a first step towards further integration of the region mg method into MueLu, with the future goal of allowing the region mg to use preexisting functions and packages.
MueLu unit tests and region mg tests pass on my local machine.
The region matvec is tested in the region matrix unit tests.
> MueLu: regionMG add a region matvec to xpetra

- packages/piro/src/Piro_LOCAAdaptiveSolver.hpp
- packages/piro/src/Piro_LOCAAdaptiveSolver_Def.hpp
- packages/piro/src/Piro_LOCASolver.hpp
- packages/piro/src/Piro_LOCASolver_Def.hpp
Charon needs access to the underlying steppers to check for status.
> PIRO: add accessors to the underlying loca steppers

- cmake/ctest/drivers/geminga/cron_driver.sh
> Geminga: Run on Tesla K40 only

- packages/anasazi/src/AnasaziConfigDefs.hpp
- packages/anasazi/src/AnasaziHelperTraits.hpp
- packages/anasazi/test/ARPACKExamples/cdriver.cpp
- packages/anasazi/test/ARPACKExamples/zdriver.cpp
- packages/anasazi/test/BlockDavidson/cxx_main_complex.cpp
- packages/anasazi/test/BlockDavidson/cxx_main_complex_lap.cpp
- packages/anasazi/test/BlockKrylovSchur/cxx_main_complex.cpp
- packages/anasazi/test/BlockKrylovSchur/cxx_main_complex_lap.cpp
- packages/anasazi/test/IRTR/cxx_main_complex.cpp
- packages/anasazi/test/IRTR/cxx_main_complex_lap.cpp
- packages/anasazi/test/LOBPCG/cxx_main_complex.cpp
- packages/anasazi/test/LOBPCG/cxx_main_complex_lap.cpp
- packages/anasazi/test/MVOPTester/cxx_main_complex.cpp
- packages/anasazi/test/OrthoManager/cxx_gentest_complex.cpp
- packages/anasazi/test/OrthoManager/cxx_main_complex.cpp
- packages/anasazi/test/OrthoManager/cxx_mattest_complex.cpp
The HAVE_COMPLEX macro is a deprecated conditional from the days when
the complex<> class had non-uniform support across compilers. It can,
and should, be removed, as mentioned in Github issue #1995
OSX GCC10.x serial
> Anasazi: Removes HAVE_COMPLEX from complex-valued tests

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_multigrid.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_decl.hpp
- packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_def.hpp
> MueLu: piecwise constant semiCoarsening

- packages/panzer/dof-mgr/test/cartesian_topology/CartesianConnManager.cpp
- packages/panzer/dof-mgr/test/cartesian_topology/CartesianConnManager.hpp
- packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr.cpp
- packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DG.cpp
- packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_DynRankView.cpp
- packages/panzer/dof-mgr/test/cartesian_topology/tCartesianDOFMgr_HighOrder.cpp
- packages/panzer/dof-mgr/test/fe_assembly/CMakeLists.txt
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_assembly_HEX.hpp
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_projection.cpp
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_projection.hpp
Modified Cartesian Connectivity Manager to allow tet meshes (created by splitting each Hex into 6 Tets) and triangular meshes (created by splitting each quad into two triangles).
Added test for L2 projection to test Panzer DofMgr, testing L2 projection on (continuous) HGrad/HCurl/HDiv and HVol spaces and for Hex/Tet/Quad/Triangle shapes.
The new tet and triangle meshes are indirectly tested in the added projection test.
> Dof mgr projection test

- packages/ifpack2/src/Ifpack2_Details_ChebyshevKernel_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
In Ifpack2 Chebyshev:
- Allocate temporary memory during construction, not during first solve
- Keep vector for diagonal extraction, if appropriate
> Ifpack2 Chebyshev: memory optimizations

- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_def.hpp
Fix build error with ETI=off. Observed in https://github.com/trilinos/Trilinos/issues/5729#issuecomment-847221290
> Xpetra: Fix build error with ETI=off

- packages/percept/src/adapt/FixSideSets.cpp
- packages/percept/src/adapt/SerializeNodeRegistry.hpp
- packages/percept/src/adapt/TransitionElementAdapter.hpp
- packages/percept/src/adapt/UniformRefinerPattern.cpp
- packages/percept/src/adapt/main/MeshAdapt.cpp
- packages/percept/src/percept/PerceptMesh.cpp
- packages/percept/src/percept/ShardsInterfaceTable.hpp
- packages/percept/src/percept/YamlUtils.hpp
- packages/percept/src/percept/fixtures/BeamFixture.hpp
- packages/percept/src/percept/fixtures/HeterogeneousFixture.hpp
- packages/percept/src/percept/fixtures/PyramidFixture.hpp
- packages/percept/src/percept/fixtures/QuadFixture.hpp
- packages/percept/src/percept/fixtures/SingleTetFixture.hpp
- packages/percept/src/percept/fixtures/TetWedgeFixture.hpp
- packages/percept/src/percept/fixtures/TriQuadSurfaceMesh3D.hpp
- packages/percept/src/percept/fixtures/WedgeFixture.hpp
- packages/percept/src/percept/function/MDArray.hpp
- packages/percept/src/percept/mesh/gen/SweepMesher.cpp
- packages/percept/src/percept/mesh/gen/SweepMesher.hpp
- packages/percept/src/percept/mesh/geometry/stk_geom/3D/FitGregoryPatches.cpp
- packages/percept/src/percept/mesh/mod/smoother/ReferenceMeshSmootherBase.cpp
- packages/percept/src/percept/verifier/mesh/Verifier.hpp
- packages/percept/src/percept/xfer/LinInterp.hpp
@trilinos/percept
Percept was incorrectly using Intrepid, resulting in compile errors in debug builds. Also there have been fixes recently in Sierra.
> Percept: sync from Sierra repo

- packages/kokkos-kernels/src/graph/KokkosGraph_Distance2Color.hpp
See discussion in #5729. This fixes some of the build errors.
Doesn't change code semantics, just makes the namespaces more explicit.
> KokkosKernels: fix name lookup issue in non-ETI build

- packages/ifpack2/src/Ifpack2_Parameters.cpp
- packages/ifpack2/src/Ifpack2_Relaxation_decl.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
- packages/kokkos-kernels/src/common/KokkosKernels_Handle.hpp
- packages/kokkos-kernels/src/sparse/KokkosSparse_gauss_seidel_handle.hpp
- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
- packages/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp
- packages/kokkos-kernels/unit_test/sparse/Test_Sparse_block_gauss_seidel.hpp
- packages/kokkos-kernels/unit_test/sparse/Test_Sparse_gauss_seidel.hpp
Patch in https://github.com/kokkos/kokkos-kernels/pull/993, and add support in Ifpack2.
``relaxation: long row threshold`` controls the minimum nonzeros a row needs to be considered long.
Wait for the KokkosKernels PR to be merged before merging this, in case changes are needed.
See https://github.com/kokkos/kokkos-kernels/issues/923 : MTGS was previously very slow when there was a lot of row imbalance.
Needed by Sierra.  See performance numbers here: https://github.com/trilinos/Trilinos/pull/9174#issuecomment-848381721.
Added an Ifpack2 Relaxation unit test and the KokkosKernels gauss_seidel test to exercise this.
> KokkosKernels/Ifpack2: MTGS long row kernel (

- packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
Clean up debug output requested from @crdohrm 
This change is to remove print statement.
> Tacho - remove debug output overriding

- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestFactory.cpp
Tests: RHEL7 (new one added)
Issue: #9200
> Ifpack2: Adding unit test for BlockTriDi via the Ifpack2::Factory 

- packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_BasisDef.hpp
- packages/intrepid2/src/Discretization/Integration/Intrepid2_IntegrationToolsDef.hpp
- packages/intrepid2/src/Shared/Intrepid2_ArgExtractor.hpp
- packages/intrepid2/src/Shared/Intrepid2_Data.hpp
- packages/intrepid2/src/Shared/Intrepid2_TensorArgumentIterator.hpp
- packages/intrepid2/src/Shared/Intrepid2_TensorData.hpp
- packages/intrepid2/unit-test/MonolithicExecutable/DataTests.cpp
- packages/intrepid2/unit-test/performance/CMakeLists.txt
- packages/intrepid2/unit-test/performance/DataCombination/CMakeLists.txt
- packages/intrepid2/unit-test/performance/DataCombination/DataCombinationPerformance.cpp
This PR fills out some of the structured support recently added to Intrepid2.  In particular, it:
- adds support for "OPERATOR_Dn" operators to `Basis:: allocateOutputView()`
- replaces the use of the word "notional" (as in, a notional dimension of a `Data` object) in code and documentation with the more standard "logical"
- adds support for an arbitrary binary operator to be applied to two `Data` objects with a common logical shape, and stored in a third
- adds default implementations of basic binary operations: sum, difference, multiplication, and division
- tests performance of the new operations on several use cases, confirming on several platforms that for these use cases, the implementation provides good speedup relative to a baseline implementation that uses …
> Intrepid2: Data Combination support

- packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp
Fix build for ETI=off, see #5729.
> TrilinosCouplings: Fix instatiation

- packages/tempus/src/Tempus_Integrator.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorBasicOld_decl.hpp
- packages/tempus/src/Tempus_IntegratorBasicOld_impl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_impl.hpp
- packages/tempus/test/Integrator/Tempus_IntegratorTest.cpp
Add missing setter for the integrator status
* Closes #9221
> Tempus: add setter for integrator status

- packages/muelu/src/CMakeLists.txt
- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_decl.hpp
- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp
- packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_def.hpp
- packages/muelu/test/scaling/CMakeLists.txt
- packages/muelu/test/scaling/recurMG.xml
- packages/muelu/utils/misc/patchLinkForRecurMG
> MueLu: PlaneSmoothing via Stratimikos and recursive AMG

- packages/tpetra/core/test/Utils/TpetraUtils_WrappedDualView.cpp
Closes #9237 
Should fix nightly test https://testing.sandia.gov/cdash/build/9298244
@ndellingwood 
Built on ascicgpu030 with 
module load sierra-devel/nvidia-9.2.148-openmpi-4.0.1
> Tpetra:  fix cuda 9.2 compiler error reported in #9237 and nightly testing

- packages/intrepid2/src/Shared/Intrepid2_Data.hpp
EMPIRE's clang build is failing due to warnings as errors from recent intrepid2 changes.
Fixed with this PR
N/A
> Intrepid2: fix warning for empire sync

- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp
> MueLu Stratimikos Smoother: Fix include

- packages/thyra/adapters/tpetra/src/Thyra_TpetraVector_def.hpp
- packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_FECrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
- packages/tpetra/core/src/Tpetra_leftAndOrRightScaleCrsMatrix_def.hpp
I've removed unused typedefs that were throwing warnings in gcc-9, they were bugging me
> Tpetra warnings

- cmake/std/PullRequestLinuxDriver.sh
<@trilinos/framework
This just modifies the no_proxy setting to try and get cash submissions going again - Thanks @vasmith!
> Add .sandia.gov bacj into the no_proxy variable

- packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp
Xpetra's `toThyraVector` and `toThyraMultiVector` were creating new Tpetra/Epetra objects and deep-copying. With the change, they re-wrap to Thyra objects instead.
> Xpetra Thyra Utils: Wrap Xpetra (Multi)Vector instead of deepcopy

- packages/ifpack2/src/Ifpack2_Details_Amesos2Wrapper_def.hpp
@jhux2 @trilinos/ifpack2 
I found another deprecated tpetra call in a wrapper, fix is attached
> Ifpack2: fixed some deprecated code

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
> Ctest: Enabling Amesos2/Belos/Ifpack2 tests w/o UVM in PR

- packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_def.hpp
- packages/muelu/example/basic/Stratimikos.cpp
> MueLu Stratimikos adapter: Enable half precision for factory-style PLs

- packages/tpetra/classic/NodeAPI/KokkosCompat_ClassicNodeAPI_Wrapper.cpp
- packages/tpetra/classic/NodeAPI/KokkosCompat_ClassicNodeAPI_Wrapper.hpp
- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_HIP.hpp
Use HIPSpace, not HIPHostPinnedSpace. This required only copying a few changes
from Cuda to HIP in the matrix-matrix kernels. All tests still pass with ROCm 4.2.
Using HIPHostPinnedSpace was a temporary way to get UVM-like semantics with HIP, at the cost of much worse performance. Now that UVM removal is done within Tpetra, this no longer needed.
> Tpetra: Use HIPSpace for HIPWrapperNode

- packages/piro/src/Piro_NOXSolver_Def.hpp
- packages/piro/src/Piro_ThyraProductME_Constraint_SimOpt.hpp
- packages/piro/src/Piro_ThyraProductME_Objective_SimOpt.hpp
- packages/rol/adapters/thyra/src/vector/ROL_ThyraVector.hpp
Bugfix to Piro and some modifications due to changes in ROL
@trilinos/piro
@trilinos/rol
> Piro: minor changes related to sensitivities and optimization

- cmake/ctest/drivers/enigma/cron_driver.sh
- cmake/ctest/drivers/geminga/cron_driver.sh
- cmake/ctest/drivers/rocketman/cron_driver.sh
- cmake/ctest/drivers/rocketman/cron_driver_tpetra.sh
- cmake/ctest/drivers/trappist/cron_driver.sh
@trilinos/xpetra @trilinos/muelu
Attempt to use the system proxy settings instead of hard-coding a proxy.
> Xpetra/MueLu testing: change proxy settings

- cmake/ctest/drivers/rocketman/sendTestSummary.sh
- cmake/ctest/drivers/rocketman/setSshEnv.py
Reenable nightly testing on rocketman.  This has been disabled for a few months.
N/A
Will be verified by cdash nightly process.
> MueLu: fix rocketman testing

- packages/ifpack2/test/belos/CMakeLists.txt
This test is failing randomly in PR testing, so it is being
disabled until the cause is found.
> Disable test_Jacobi_bcsstk14_hb test due to random failure

- cmake/ctest/drivers/rocketman/cron_driver.sh
Reenable nightly testing.
* Part of #9327.
N/A
Will be confirmed by nightly dashboard results.
> MueLu: another fix for testing on rocketman

- packages/muelu/src/Interface/MueLu_FactoryFactory_decl.hpp
- packages/muelu/src/Misc/MueLu_BlockedCoordinatesTransferFactory_def.hpp
- packages/muelu/test/unit_tests/BlockedRepartition.cpp
BlockedCoordinatesTransferFactory was not properly setup when called from an xml input deck. Also updated to work for multiple dofs per node (per block). This now allows for blocked operators to use coordinate dependent factories, such as zoltan2 rebalancing.
This is related to work being done for MHD using Drekar to allow for rebalancing of the operators on the coarse levels:
https://github.com/rppawlo/DrekarBase/issues/546
To be added.
> MueLu: update blocked coord transfer fact

- packages/tpetra/core/src/Tpetra_Details_unpackCrsGraphAndCombine_def.hpp
> Tpetra: It's Over 9000!!! [Fixing bug 9332]

- packages/amesos2/src/Amesos2_Superlu_FunctionMap.hpp
- packages/amesos2/src/Amesos2_Superlu_decl.hpp
- packages/amesos2/src/Amesos2_Superlu_def.hpp
- packages/amesos2/src/Amesos2_Util.hpp
- packages/amesos2/src/Amesos2_cuSOLVER_def.hpp
This PR is to add a few new options for SpTRSV with SuperLU, and also an option to call METIS before SuperLU
> Amesos2: add new options for SuperLU

- packages/tpetra/core/src/Tpetra_Details_Transfer_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_Transfer_def.hpp
- packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
Compare imports with and without aliasing using randomized vectors.
> Tpetra: Strengthen unit test that skips unpack

- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_decl.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp
- packages/muelu/src/Smoothers/MueLu_IfpackSmoother.hpp
- packages/muelu/src/Smoothers/MueLu_TrilinosSmoother_def.hpp
- packages/muelu/test/unit_tests/Hierarchy.cpp
Stakeholder feedback: n/a (non-ASC)
TESTS: New test added for both Epetra and Tpetra
> MueLu: Adding aggregate-level smoothing

- packages/xpetra/src/MultiVector/Xpetra_TpetraMultiVector_decl.hpp
Fix build error in Albany, reported in #9341. 
https://github.com/trilinos/Trilinos/pull/9343#pullrequestreview-692158775
> Removed overrides to be consistent

- packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
* Closes #9336
Solo, OpenMP-only build
> Tpetra: Fix for #9336

- packages/ifpack/src/Ifpack_UserPartitioner.cpp
- packages/ifpack/src/Ifpack_UserPartitioner.h
- packages/ifpack/src/Ifpack_ValidParameters.cpp
- packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp
Adding singleton handling which Ifpack (not Ifpack2) didn't have
Stakeholder feedback: n/a (non-ASC)
TESTS: RHEL7
> MueLu/Ifpack: Aggregate Block Smoothing Singleton Handling

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
> enabled xpetra tests

- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- packages/muelu/src/Smoothers/MueLu_IfpackSmoother.cpp
- packages/muelu/test/unit_tests/Hierarchy.cpp
Stakeholder Feeback: n/a (non-ASC)
TESTS: New test added!
> MueLu: Aggregate smoothing for >1 PDE per node

- packages/muelu/cmake/MueLu_config.hpp.in
- packages/muelu/test/unit_tests/MueLu_Test_ETI.hpp
Create Kokkos-Kernels TPL handles up front, so that they don't mess up solve timings.
> MueLu: Create cuBLAS and cuSPARSE handles up front

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
Fix bug #9348 
The nightly test now compiles on enigma.
> MueLu: regionMG add missing Node templates

- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer.hpp
- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorerUtils.hpp
- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer_Zoltan.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybrid2GL.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1-2GL.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD2.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridPD2.hpp
- packages/zoltan2/core/src/input/Zoltan2_TpetraRowGraphAdapter.hpp
- packages/zoltan2/core/src/input/Zoltan2_TpetraRowMatrixAdapter.hpp
- packages/zoltan2/core/src/input/Zoltan2_XpetraMultiVectorAdapter.hpp
- packages/zoltan2/core/src/models/Zoltan2_HyperGraphModel.hpp
- packages/zoltan2/core/src/models/Zoltan2_ModelHelpers.hpp
- packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
- packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp
- packages/zoltan2/test/core/color/coloring1.cpp
- packages/zoltan2/test/core/correctness/zoltanCompare.cpp
- packages/zoltan2/test/core/helpers/UserInputForTests.hpp
- packages/zoltan2/test/core/order/ordering1.cpp
- packages/zoltan2/test/core/order/orderingScotch.cpp
- packages/zoltan2/test/core/partition/partitioning1.cpp
- packages/zoltan2/test/core/unit/models/GraphModel.cpp
Local commit to get the autotester to run
> Zoltan2 tpetra dep

- packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp
- packages/panzer/dof-mgr/src/Panzer_Filtered_GlobalIndexer.cpp
- packages/panzer/dof-mgr/src/Panzer_GlobalIndexer_Utilities.cpp
- packages/panzer/dof-mgr/src/Panzer_GlobalIndexer_Utilities_impl.hpp
- packages/panzer/dof-mgr/test/dofmngr_test/tFilteredUGI.cpp
- packages/panzer/dof-mgr/test/dofmngr_test/tGlobalIndexerUtilities.cpp
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_assembly_HEX.hpp
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_projection.hpp
Start of UVM removal in Panzer with the DOF Manager subpackage.
All tests in this subpackage are now passing with UVM off.
> Panzer: UVM removal from DofMgr subpackage

- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
This temorary change to the intel compiler licensing has been resolved by the sems team
* Follows #9297 
* Related to #9293
> Framework: Revert 9297

- packages/muelu/src/Misc/MueLu_LocalOrdinalTransferFactory_def.hpp
- packages/muelu/src/Transfers/Classical/MueLu_ClassicalMapFactory_def.hpp
- packages/muelu/src/Transfers/Classical/MueLu_ClassicalPFactory_def.hpp
- packages/muelu/test/unit_tests/ClassicalPFactory.cpp
- packages/xpetra/src/CrsGraph/Xpetra_CrsGraphFactory.hpp
- packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_decl.hpp
- packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_def.hpp
Fix a bug in Tpetra classical.
> MueLu: classical with Tpetra

- packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestFactory.cpp
- packages/muelu/test/unit_tests/Smoothers/Ifpack2Smoother.cpp
Tests: RHEL7; new tests added
Issue: #9200 
> Ifpack2/MueLu: Improving Tests

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
> Fixed deprecated code

- packages/teko/src/Teko_Utilities.cpp
- packages/teko/src/Tpetra/Teko_BlockingTpetra.cpp
- packages/teko/src/Tpetra/Teko_InterlacedTpetra.cpp
- packages/teko/src/Tpetra/Teko_TpetraHelpers.cpp
- packages/teko/tests/src/tExplicitOps_tpetra.cpp
- packages/teko/tests/src/tGraphLaplacian_tpetra.cpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
Let's see what the AT thinks..
FYI @bathmatt
> Teko: Replace use of deprecated Tpetra stuff

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
@cgcgcg fixed deprecated code, let's see if this passes with cuda-uvm off, doubtful but this PR will test that...
> enabled teko testing

- packages/ifpack2/src/Ifpack2_Details_GaussSeidel.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
Relaxation's local Gauss-Seidel was breaking Tpetra's DualView rules by holding onto a persistent view of BlockCrsMatrix's values. Now, getting it from the matrix each apply.
Since this wasn't caught by testing before, made the unit test check if the preconditioner kept the values/graph views of CrsMatrix or BlockCrsMatrix at each step (construction, initialize() and compute()).
* Closes #9400
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Was a blocker for MueLu uvm removal.
This case is now tested in Ifpack2.
> Ifpack2: Fix #9400 and add test

- packages/trilinoscouplings/examples/scaling/example_Maxwell_Tpetra.cpp
Fix some parallel issues.
Epetra and Tpetra drivers have matching residual history on 2 ranks.
> TrilinosCouplings: Fix some issue in Tpetra Maxwell example

- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.hpp
> Panzer: 8605 Updates to BasisValues2 to allow lazy evaluation

- packages/muelu/test/unit_tests/Hierarchy.cpp
Issue: #9200
Stakeholder feedback: n/a (testing only change)
Tests: Yes.  A new one.
> MueLu: Adding new unit test

- packages/tpetra/core/test/FECrsMatrix/FECrsMatrix_UnitTests.cpp
Issues: #8930;
Stakeholder feedback: n/a (test);
Tests: Fixing issue
> Tpetra: Removing deprecated code in test

- packages/piro/src/Piro_SteadyStateSolver_Def.hpp
This is related to #9415.
Enables the "Explicit Matrix Transpose" option for computing adjoint senstivies with the old code that does not rely on ROL.
At some point we will get rid of the old code, but for now we want to maintain it functional.
@trilinos/piro
> Piro: enable "Explicit Matrix Transpose" option when computing adjoint senstivies

- packages/PyTrilinos/util/copyWithCMakeSubstitutions.py.in
Ninja only write dummy Makefiles, so reading it in does not work.
> PyTrilinos: Get CMAKE_BINARY_DIR directly from CMake

- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
#9425 reports that the ifpack block tridiagonal solver fails with Intel 19.1.3 while other compilers are fine. 
I reproduced the problem using a CEE machine. The problem is gone when I add a print statement. GDB cannot pin-point the place where the segmentation fault happens. So, this solution is based on my guess work. I suspected that the ternary operator access a pointer which is not supposed to be accessed by the condition statement. This PR removes all ternary operators and separate the setup into two cases. This resolve the issue reported in #9425.
#9425 
Tested with Intel 19.1.3
> Ifpack2 - separate jacobi setup from tridiag setup

- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
Recently broken in UVM removal.
Fixes an EMPIRE test that broken last week.
Fixed failing test in EMPIRE.
N/A
> Panzer: fix surface rotation matrices

- packages/seacas/applications/epu/EP_Version.h
- packages/seacas/applications/epu/epu.C
> EPU: Fix nodal variable output after memory optimization

- packages/ml/src/Utils/ml_MultiLevelPreconditioner.cpp
- packages/ml/src/Utils/ml_ValidateParameters.cpp
Tests: n/a (Debug output only)
> ML: Adding debugging output

- packages/piro/src/Piro_TempusIntegrator_Def.hpp
- packages/rol/example/tempus/ROL_TempusReducedObjective.hpp
- packages/rol/example/tempus/example_01.cpp
- packages/rol/example/tempus/example_parabolic.xml
- packages/rol/example/tempus/example_parabolic_modeleval.cpp
- packages/rol/example/tempus/example_parabolic_modeleval_forward-adjoint.cpp
- packages/rol/example/tempus/example_sincos.xml
- packages/tempus/src/Tempus_IntegratorForwardSensitivity.cpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_impl.hpp
- packages/tempus/src/Tempus_StepperStaggeredForwardSensitivity_impl.hpp
- packages/tempus/test/BDF2/Tempus_BDF2Test.cpp
- packages/tempus/test/BDF2/Tempus_BDF2_FSA.hpp
- packages/tempus/test/BackwardEuler/Tempus_BackwardEuler_FSA.hpp
- packages/tempus/test/DIRK/Tempus_DIRK_FSA.hpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_FSA.hpp
- packages/tempus/test/IMEX_RK/Tempus_IMEX_RK_FSA.hpp
- packages/tempus/test/IMEX_RK_Partitioned/Tempus_IMEX_RK_Partitioned_FSA.hpp
Convert `IntegratorBasicOld` -> `IntegratorBasic`
* Closes #8932 
All previous tests are passing as expected
> 8932 tempus convert integrator fsa new

- packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
> Tempus: FSA - update the documentation

- packages/rol/example/tempus/ROL_TempusReducedObjective.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity.cpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_impl.hpp
- packages/tempus/test/BDF2/Tempus_BDF2_PseudoTransient_SA.cpp
- packages/tempus/test/BackwardEuler/Tempus_BackwardEuler_PseudoTransient_SA.cpp
- packages/tempus/test/DIRK/Tempus_DIRK_PseudoTransient_SA.cpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRK_PseudoTransient_SA.cpp
> 9362 tempus convert integrator pseudo transient forward sensitivity to integrator basic

- packages/trilinoscouplings/examples/fenl/BelosSolve.hpp
- packages/trilinoscouplings/examples/fenl/fenl_impl.hpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson2DExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson3DExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_p2_tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE_Tpetra.cpp
@jhux2 
this is the MR for teh deprecated code removal on the trilinos couplings
> TrilinosCouplings tpetra deprecated code removal

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
- packages/zoltan2/core/src/input/Zoltan2_BasicKokkosIdentifierAdapter.hpp
- packages/zoltan2/example/block/kokkosBlock.cpp
- packages/zoltan2/sphynx/src/Zoltan2_Sphynx.hpp
- packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp
- packages/zoltan2/test/core/partition/mj_backwardcompat.cpp
- packages/zoltan2/test/core/temp/ddirectoryTest.cpp
This is to trigger the auto-tester as we get close to being UVM free
The bulk of these commits are part of another PR so don't worry about reviewing yet
> Zoltan2 no UVM testing

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/trilinoscouplings/examples/scaling/example_Maxwell_Tpetra.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
Fixed any UVM stuff in trilinos couplings found some muelu bugs
> Trilinos couplings uvm

- packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.hpp
@jhux2. Jakob found this bug when compiling for int,int
> Xpetra: Fixed bug in return type

- packages/piro/test/Piro_TempusSolver_SensitivitySinCosUnitTests.cpp
- packages/rythmos/src/Rythmos_BackwardEulerStepper_def.hpp
- packages/rythmos/src/Rythmos_ThetaStepper_def.hpp
- piro: Add missing include
- rythmos: Fix build warnings (needed for -Werror)
* Related to issue27 and issue13
Verified 100% test pass rate with gcc and clang auto-tester configs.
> Fixes for building piro and rythmos

- packages/muelu/doc/UsersGuide/MueLu_MasterList.cpp
- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_aggregation.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/test/unit_tests/Aggregates.cpp
Add and option to treat a node as Dirichlet if any of the DOFs on that node are Dirichlet (the default behavior is that nodes are marked as Dirichlet only if all DOFs on the node are Dirichlet).
Observed convergence benefits in some Drekar simulations rppawlo/DrekarBase#546. Further investigation could be useful.
> MueLu: add greedy Dirichlet option

- packages/muelu/adapters/stratimikos/Thyra_MueLuPreconditionerFactory_def.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Graph/Containers/MueLu_LWGraph_decl.hpp
- packages/muelu/src/Smoothers/MueLu_StratimikosSmoother_def.hpp
- packages/trilinoscouplings/examples/scaling/example_Maxwell_Tpetra.cpp
- packages/xpetra/sup/Utils/Xpetra_IO.hpp
Random collection of MueLu changes:
- Fix a type bug in MueLu Stratimikos adapter, add a timer
- Hook up Stratimikos to TrilinosCouplings Maxwell Tpetra example.
- Allow conversion of LWGraph to CrsGraph.
- Add file output of CrsGraph to Xpetra::IO
- RefMaxwell fixes for running with Stratimikos subsolvers
- StratimikosSmoother: don't rely on uppercase smoother type string
> MueLu changes

- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/test/core_tests/basis_values2.cpp
- packages/phalanx/src/Phalanx_Field.hpp
- packages/phalanx/src/Phalanx_Field_Def.hpp
- packages/phalanx/src/Phalanx_MDField.hpp
- packages/phalanx/test/Field/Field.cpp
- packages/phalanx/test/Field/MDField_Compiletime.cpp
- packages/phalanx/test/Field/MDField_Runtime.cpp
> Panzer: remove UVM use in BasisValues object

- packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp
- packages/panzer/disc-fe/test/local_mesh/setup_sublocal_mesh_info.cpp
This gets one more test done, local_mesh in panzer
> panzer: Fixed local mesh computation for UVM

- packages/panzer/disc-fe/src/Panzer_LocalPartitioningUtilities.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Normals_impl.hpp
- packages/panzer/disc-fe/test/evaluator_tests/normals.cpp
- packages/panzer/disc-fe/test/local_mesh/setup_sublocal_mesh_info.cpp
> panzer: Normals test

- packages/panzer/disc-fe/src/Panzer_PointValues2.hpp
- packages/panzer/disc-fe/src/Panzer_PointValues2_impl.hpp
- packages/panzer/disc-fe/test/core_tests/point_values2.cpp
> Panzer: remove uvm from point values

- packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory.cpp
- packages/panzer/adapters-stk/src/Panzer_STK_Utilities.cpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgQuantity_impl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgVector_impl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellQuantity_impl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterFields_impl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterVectorFields_impl.hpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CustomMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CustomMeshFactory.hpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
- packages/panzer/adapters-stk/test/stk_interface_test/tExodusEdgeBlock.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tExodusFaceBlock.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tSTK_IO.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.hpp
- packages/panzer/disc-fe/src/Panzer_Workset_Builder_impl.hpp
- packages/phalanx/src/CMakeLists.txt
Fixed tests:
- tExodusFaceBlock
- tExodusEdgeBlock
- PanzerAdaptersSTK_initial_condition_builder
- tSTK_IO
> Remove UVM from PanzerAdaptersSTK (partially)

- packages/muelu/src/Misc/MueLu_InterfaceAggregationFactory_decl.hpp
The paper has been published, so let's add the bibliography details to the documentation of the implementation (done in PR #8593).
- Related to #8586
Following-up on an existing implementation.
Change to documentation. Existing tests pass. No new tests required.
> MueLu: update details of bibliographic reference

- packages/panzer/disc-fe/src/evaluators/Panzer_DOF_PointField_impl.hpp
- packages/panzer/disc-fe/test/evaluator_tests/dof_pointfield.cpp
Fixed the last failing disc_fe unit test
> panzer: Fixed poinrfield test for UVM

- packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_decl.hpp
- packages/muelu/src/Graph/Containers/MueLu_LWGraph_kokkos_def.hpp
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_decl.hpp
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_decl.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_def.hpp
- packages/xpetra/src/Export/Xpetra_TpetraExport_decl.hpp
- packages/xpetra/src/Import/Xpetra_TpetraImport_decl.hpp
@trilinos/muelu @trilinos/xpetra 
MueLu's matrix filtering (CoalesceDropFactory) wasn't working on the Kokkos code path when a new filtered matrix was used.  See #8603.
I've tested this locally and will be pushing a unit test in a subsequent PR.
> MueLu: Xpetra: improve matrix filtering 

- packages/panzer/disc-fe/src/evaluators/Panzer_GatherBasisCoordinates_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherIntegrationCoordinates_impl.hpp
- packages/panzer/disc-fe/test/evaluator_tests/gather_coordinates.cpp
Removed UVM from a couple evaluators and a test.
> panzer: fixed gather coords test for UVM removal

- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_Scalar_decl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_Scalar_impl.hpp
- packages/panzer/disc-fe/test/evaluator_tests/integrator_scalar.cpp
- packages/phalanx/src/Phalanx_KokkosDeviceTypes.hpp
> Panzer: fix view of views for integrator scalar

- packages/phalanx/test/Kokkos/CMakeLists.txt
- packages/phalanx/test/Kokkos/tKokkosViewOfViews.cpp
Add example code for view of views without UVM.
> Phalanx: add example of View of Views for no-UVM

- packages/phalanx/src/Phalanx_MDField.hpp
- packages/phalanx/test/Field/Field.cpp
- packages/phalanx/test/Field/MDField_Compiletime.cpp
- packages/phalanx/test/Field/MDField_Runtime.cpp
This merge allows one to deep copy from a MDField without having to get the view out
> phalanx: Mdfield cast

- packages/panzer/adapters-stk/test/evaluator_tests/RandomFieldEvaluator.hpp
- packages/panzer/adapters-stk/test/evaluator_tests/point_basis_values_evaluator.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_PointValues_Evaluator_impl.hpp
This is blocked by a PR for code in phalanx, #9569, and will be moved from WIP when that code is done and we can rebase off develop.  Putting this up so I don't lose it.
> panzer: Fixed PanzerAdaptersSTK_tPointBasisValuesEvaluator.exe from UVM errors

- packages/panzer/adapters-stk/test/face_to_elem/Panzer_Relations.cpp
Another simple test to get uvm free
> panzer: Face to elem

- packages/panzer/adapters-stk/test/evaluator_tests/basis_times_vector.cpp
> Panzer: Fixed basis_times_vector for UVM

- packages/panzer/adapters-stk/test/panzer_workset_builder/apply_orientations.cpp
- packages/panzer/adapters-stk/test/panzer_workset_builder/hdiv_basis.cpp
- packages/panzer/adapters-stk/test/panzer_workset_builder/parallel_apply_orientations.cpp
- packages/panzer/adapters-stk/test/projection/projection.cpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_L2Projection.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.hpp
- packages/panzer/disc-fe/src/Panzer_WorksetContainer.cpp
- packages/panzer/disc-fe/src/Panzer_WorksetContainer.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFDiv_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFGradient_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOF_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesTensorTimesVector.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesTensorTimesVector_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector_impl.hpp
> 9547 panzer default lazy basis values from workset

- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgQuantity_impl.hpp
- packages/panzer/adapters-stk/test/gather_scatter_evaluators/scatter_field_evaluator.cpp
fixed another unit test for UVM
> panzer: Gather scatter1

- packages/tempus/src/Tempus_StepperDIRK_decl.hpp
- packages/tempus/src/Tempus_StepperDIRK_impl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_decl.hpp
- packages/tempus/src/Tempus_StepperExplicitRK_impl.hpp
- packages/tempus/src/Tempus_StepperRKBase.hpp
- packages/tempus/src/Tempus_Stepper_ErrorNorm.cpp
- packages/tempus/src/Tempus_Stepper_ErrorNorm_decl.hpp
- packages/tempus/src/Tempus_Stepper_ErrorNorm_impl.hpp
> Tempus: Stepper_ErrorNorm - initial add

- packages/teuchos/core/src/Teuchos_as.hpp
- packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp
- packages/tpetra/core/src/Tpetra_MixedScalarMultiplyOp.hpp
@trilinos/teuchos @trilinos/tpetra 
Fix #9572
> Teuchos/Tpetra: Fix for #9572

- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_Helpers_def.hpp
- packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
Adding converter and test for said converter
Issues: #9584
Stakeholder Feedback: n/a (non-ASC)
Tests: New test added!
> Tpetra: BlockCrsMatrix -> CrsMatrix Converer

- packages/ifpack2/adapters/thyra/Thyra_Ifpack2PreconditionerFactory_def.hpp
@trilinos/thyra  @trilinos/ifpack2 
Hopefully fixes #9572
> Thyra-Ifpack2 Mixed Precision: Deal with complex

- packages/muelu/adapters/tpetra/MueLu_TpetraOperator_def.hpp
- packages/muelu/adapters/xpetra/MueLu_XpetraOperator_decl.hpp
> MueLu: Bug out when mode!=NO_TRANS

- packages/intrepid2/src/Projection/Intrepid2_ProjectionToolsDefHCURL.hpp
@mperego @dridzal 
Fixing shadow variable warning.
> Intrepid2: rename variable to fix shadow warning

- packages/zoltan2/doc/Doxyfile
When the zoltan2 directory structure changed to accommodate sphynx, the Doxyfile was not updated to reflect the new structure.  The class diagrams were no longer generated.  This change attempts to fix the problem by updating the class structure.
NA; documentation change only.
> Zoltan2:  update doxygen main file to reflect new directory structure

- packages/panzer/adapters-stk/test/panzer_workset_builder/check_rotation_matrices.cpp
- packages/panzer/adapters-stk/test/panzer_workset_builder/check_sorted_face_quads.cpp
- packages/panzer/adapters-stk/test/panzer_workset_builder/hdiv_basis.cpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOF_impl.hpp
Fixed tests:
- PanzerAdaptersSTK_check_rotation_matrices
- PanzerAdaptersSTK_hdiv_basis
- PanzerAdaptersSTK_check_sorted_face_quads
- PanzerAdaptersSTK_field_manager_builder
> Fix Panzer's tests with UVM off

- packages/framework/pr_tools/pr_python_test_driver.sh
- packages/framework/pr_tools/trilinosprhelpers/unittests/config-specs.ini
- Update pacakge setup to use python3 -m pip.
- Fix config-specs.ini typo
PR tests started failing last night with:
```
trilinos-folder/python-3/Trilinos/packages/framework/pr_tools/common.bash: line 213: pip3: command not found
```
python-3 autotester job.
> packages/framework: pip3 is no longer in PATH

- packages/panzer/adapters-stk/test/evaluator_tests/gather_solution.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Epetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_Epetra.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherTangent_Epetra_impl.hpp
updated test and code to gather epetra tangents.
> panzer: Tangent gather

- packages/panzer/adapters-stk/example/PoissonInterfaceExample/Example_SimpleSource_impl.hpp
- packages/panzer/adapters-stk/example/PoissonInterfaceExample/Example_Solution_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOFCurl_impl.hpp
Fixed a couple of UVM issues in the examples directory
> Panzer: have more examples running

- packages/piro/src/Piro_PerformAnalysis.cpp
@trilinos/piro
@mperego 
This small PR allows Piro to return the status of the ROL algorithm.
All the tests passed on Blake.
> Piro: Return the status of the ROL algorithm

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_CoordinatesEvaluator_impl.hpp
Fixed some code with mesh motion
> Panzer: mesh motion

- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
> Panzer: Stops virtual orientations from being applied

- packages/panzer/adapters-stk/example/CurlLaplacianExample/Example_SimpleSource_impl.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_SimpleSource_impl.hpp
some minor fixes I don't wanna lose,
> panzer: Minor fixes in some of the source terms for examples

- packages/panzer/adapters-stk/example/PoissonInterfaceTpetra/Example_SimpleSource_impl.hpp
- packages/panzer/adapters-stk/example/PoissonInterfaceTpetra/Example_Solution_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_Tpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Tpetra.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Tpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_impl.hpp
Have the tpetra gather scatter working for a simple test. main_driver.
> panzer: Tpetra gather

- packages/panzer/adapters-stk/example/CurlLaplacianExample/Example_CurlSolution_impl.hpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/Example_CurlSolution_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_EdgeBasis.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_EdgeBasis.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_EdgeBasis_impl.hpp
worked around the orientation code being only on host, got several more tests passing
> panzer: Fixed Dirichlet resid for edge basis and UVM

- packages/panzer/disc-fe/src/Panzer_Workset_Builder_impl.hpp
> panzer: Fixed uvm error with building the sideset coords

- packages/panzer/disc-fe/src/evaluators/Panzer_Parameter.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Parameter_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_Epetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Epetra_impl.hpp
Have all the model eval tests passing now,
> panzer: Fixed up model evaluator test, tanget scatters

- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_impl.hpp
> Panzer: fix interface conditions

- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
Fixed missing deep copy if conditional was not set to true
> found missing deep copy

- packages/panzer/disc-fe/src/Panzer_Workset_Builder_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_DOF_PointField_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherBasisCoordinates_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherIntegrationCoordinates_impl.hpp
> Panzer: cleanup cuda warnings from lambda capture of mdfields

- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesScalar_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_CurlBasisDotVector_impl.hpp
found some places that needed views to be unmanaged
> panzer: Create mirror fixes

- packages/nox/src/NOX_StatusTest_Factory.C
- packages/nox/src/NOX_StatusTest_Factory.H
- packages/nox/src/NOX_StatusTest_RelativeNormF.C
- packages/nox/src/NOX_StatusTest_RelativeNormF.H
Drekar team asked for a new option in RelativeNormF status test. Took the opportunity to add parameter list validation to all the status tests as well.
Fixes issue.
All objects modified in this PR are tested in the unit test for NOX_StatusTest_Factory.cpp
> NOX: added plist validation to status tests and new option

- packages/shylu/shylu_node/tacho/example/Tacho_ExampleExternalInterface.cpp
- packages/shylu/shylu_node/tacho/example/Tacho_ExampleExternalInterface.hpp
- packages/shylu/shylu_node/tacho/src/Tacho_Driver.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_Driver_Impl.hpp
@crdohrm 
This PR provides a solver capability to create multiple solver objects sharing the same symbolic factors with different input matrix values.
The example explains the corresponding workflow.
> Tacho - user request for providing a capability to create and solve multiple problems sharing the same sparse pattern 

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/test/interface/default/MLParameterListInterpreter/MLaux.xml
- packages/muelu/test/maxwell/Maxwell3D.cpp
- Translate aux aggregation parameters from ML to MueLu.
- Fix #9715
> ML2MueLu translation of aux aggregation

- packages/muelu/src/Interface/MueLu_MLParameterListInterpreter_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/scaling/MatvecKernelDriver.cpp
This is to fix #9725, build errors in MueLu's experimental dashboard.
> Muelu: fix experimental nightlies

- packages/panzer/adapters-stk/example/main_driver/main_driver.cpp
- packages/phalanx/src/Phalanx_GetNonConstDynRankViewFromConstMDField.hpp
- packages/phalanx/test/Field/NonConstDynRankViewFromConstMDField.cpp
Calling a TPL that does not respect const correctness. Need utility to remove const from kokkos views.
Also added stacked timer to an example in panzer.
Fixes issue.
tested in phalanx/test/Field/NonConstDynRankViewFromConstMDField.cpp.
> Phalanx: add conversion utility

- .github/workflows/muelu_label_to_project.yml
> Workflow: MueLu

- packages/tpetra/core/inout/Tpetra_Distribution2D.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
This PR removes some compiler warnings, moves some error checking to debug runs only, and reuses a localMatrixDevice instead of generating a new one.
NA
Tested on ascicgpu with serial node.
> Tpetra:  minor changes and some cleanup

- packages/framework/pr_tools/PullRequestLinuxDriver.sh
- packages/framework/pr_tools/PullRequestLinuxDriverTest.py
- packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationBase.py
- packages/framework/pr_tools/trilinosprhelpers/TrilinosPRConfigurationStandard.py
- packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py
- packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationInstallation.py
- packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py
- packages/framework/pr_tools/unittests/test_PullRequestLinuxDriverTest.py
Support posting to different cdash servers.
Trilinos auto-tester.
The framework ctest driver scripts will need to be updated after this merges.
> Framework: packages/framework: add --ctest-drop-site

- packages/trilinoscouplings/examples/scaling/IntrepidPoisson_Pamgen_Tpetra_main.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_IntrepidPoissonExampleHelpers.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_IntrepidPoissonExampleHelpers.hpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidPoissonExample.cpp
> TrilinosCouplings: Adding support for rotated diffusion

- packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
Reported by @eric-c-cyr 
Tests: Code is deprecated
Stakeholder feedback: See below
Issue: #9803
>  Tpetra: Removing const to allow deprecated code to compile

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/test/unit_tests/CoalesceDropFactory.cpp
- packages/trilinoscouplings/examples/scaling/CMakeLists.txt
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_IntrepidPoissonExampleHelpers.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_IntrepidPoissonExampleHelpers.hpp
- packages/trilinoscouplings/examples/scaling/example_Poisson2D_pn_tpetra.cpp
TESTS: new one
Stakeholder feedback: n/a (non-ASC)
> MueLu/TrilinosCouplings: Adding signed SA style dropping option / Adding Anisotropic Diffusion Example

- Version.cmake
- packages/ifpack/src/Ifpack_Hypre.cpp
@cgcgcg 
Per @cgcgcg only one commit is needed for the Hpyre deprecation fix for the xSDK release. This PR includes that fix, and the increment in version number.
Apply Hypre deprecation fix needed for xSDK release to the 13.2 release branch.
This fix was previously applied to the develop branch.
> Apply Hypre deprecation fix to 13.2 release branch for xSDK release

- packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
- packages/muelu/test/scaling/DriverCore.hpp
Allow to use MueLu as a stand-alone solver again.
> MueLu: Fix standalone solve

- packages/belos/tpetra/src/solvers/Belos_Tpetra_CgPipeline.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_Gmres.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPipeline.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresS.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_UpdateNewton.hpp
- packages/belos/tpetra/test/Native/nonsymm_matrix.cpp
This PR fixes some compilation warnings in Belos native Tpetra solvers
Tested on ascicgpu031 with UVM and Tpetra deprecated code
> Belos native Tpetra : fix compilation warnings

- packages/kokkos/core/src/SYCL/Kokkos_SYCL_Instance.cpp
Match PR kokkos/kokkos#4505
See also kokkos/kokkos#4504
Hotfix SYCL to use in-order queues
Matching PRs to kokkos repo already tested; autotester will test this PR
> kokkos: Hotfix SYCL to use in-order queues

- packages/kokkos-kernels/perf_test/blas/blas3/KokkosBlas3_gemm_perf_test.hpp
- packages/kokkos-kernels/perf_test/blas/blas3/KokkosBlas3_trmm_perf_test.hpp
- packages/kokkos-kernels/perf_test/blas/blas3/KokkosBlas_trtri_perf_test.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas3_trmm_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas3_trsm_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas_trtri_impl.hpp
Pattern match of kokkos/kokkos-kernels#1177
Addresses issue kokkos/kokkos-kernels#1170
Matching PRs to kokkos-kernels repo already tested, autotester will test this
> KokkosKernels: scope using namespace to prevent clashes

- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.hpp
- packages/seacas/applications/ejoin/EJ_SystemInterface.h
- packages/tpetra/core/src/Tpetra_Import_def.hpp
@trilinos/MueLu
@trilinos/SEACAS
@trilinos/Tpetra
@GrahamBenHarper (nalu-wind @overfelt @alanw0 )
I ran into some compiler errors in these packages while trying to build Trilinos with c++17 using gcc8, gcc8+cuda11 and apple-clang.  These were the fixes. This is for the Exawind project where we are looking at moving Nalu-Wind up to c++17.
closes #9959
> MueLu, Tpetra, SEACAS: Cpp17 Fixes

- packages/ifpack2/src/Ifpack2_Hiptmair_def.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/src/Interface/MueLu_MLParameterListInterpreter_def.hpp
- Read Hiptmair settings from ML parameter lists.
- In MueLu RefMaxwell, use the smoother factory to create Hiptmair.
> MueLu: Enable Hiptmair translation from ML

- packages/ml/README-ML
@trilinos/ML
Most of the information in the ML is outdated.
> ML: removed outdated information for ML

- packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/unit_tests_kokkos/Utilities_kokkos.cpp
Related to https://github.com/trilinos/Trilinos/issues/9743
> MueLu: Add more unittests for MueLu Utilities_kokkos

- cmake/std/PullRequestLinuxDriver.sh
- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestClang10.0.0TestingEnv.sh
- cmake/std/sems/PullRequestClang7.0.1TestingEnv.sh
- cmake/std/sems/PullRequestClang9.0.0TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.8.4TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnvSERIAL.sh
- cmake/std/sems/PullRequestGCC7.2.0SerialTestingEnv.sh
- cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh
- cmake/std/sems/PullRequestGCC8.3.0TestingEnv.sh
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
- cmake/std/sems/PullRequestPython2TestingEnv.sh
- cmake/std/sems/PullRequestPython3TestingEnv.sh
- cmake/std/sems/get_default_modules.sh
- cmake/std/trilinosprhelpers/setenvironment/unittests/setenvironment_config.ini
- cmake/std/trilinosprhelpers/setenvironment/unittests/test_ModuleHelper.py
- cmake/std/trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py
- cmake/std/trilinosprhelpers/unittests/trilinos_pr_test.ini
The current TPLs used for the autotester are moving locations.
This code change will move to that archived set of TPLs to allow for more time to move to the new set of spack-cm released TPLs.
> Framework: Migrate Autotester TPLs

- packages/trilinoscouplings/examples/scaling/StructuredIntrepidPoisson_Pamgen_Tpetra_main.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/muelu_geometric_interpolation.xml
- packages/trilinoscouplings/examples/scaling/muelu_structured_aggregation.xml
@trilinos/muelu @trilinos/trilinoscouplings 
Fix trilinos couplings examples using structured aggregation to work with recent structured aggregation changes. 
On my machine, muelu_geometric_interpolation.xml and muelu_structured_aggregation.xml can now be run as xml inputs for TrilinosCouplings_StructuredIntrepidPoisson_Pamgen_Tpetra.exe.
> MueLu: fix structured examples in trilinos couplings

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/test/scaling/comp_rotations.xml
> MueLu: fixed parameter bug with rotation option

- packages/sacado/src/Kokkos_DynRankView_Fad.hpp
- packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
- packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp
- packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
- packages/trilinoscouplings/examples/fenl/fenl_impl.hpp
Issue: #9994
Tests: Kokkos deprecated off
Stakeholder Feedback:n/a
> Stokhos/Sacado/TrilinosCouplings: Remove deprecated use of Kokkos::Impl::SpaceAccessibility

- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestChebyshev.cpp
Increase tolerance in unit test so that it passes on all systems, see #10016.
> Ifpack2: Bump up tolerance in Chebyshev unit test

- packages/framework/pr_tools/PullRequestLinuxDriver.sh
When the rest of the builds were moved to use sems-archive TPLs, one was missed because it uses a different PullRequestLinuxDriver.sh.
Why it does, that can be addressed at a later time.
In testing I realized this PR is going to require we sneak it past the relevant Python3 test. These changes are used before the branch is merged in.
So, to test, I setup [another branch based on this one with an inconsequential comment](https://github.com/ZUUL42/Trilinos/compare/python3_fix...ZUUL42:python3_fix_test) to use at the source and this branch as the target. That builds fine, see [Jenkins](https://ascic-jenkins.sandia.gov/job/trilinos-folder/job/python-3/853/console) & [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilter …
> Framework: Python3 build: Fix/move to SEMS-archive TPLs

- packages/muelu/utils/misc/setSshEnv.python
Update a MueLu utility that checks for a running ssh-agent.
Support python 2 and 3.  Fix a corner-case bug.
> MueLu: update ssh-agent utility script

- packages/piro/src/Piro_TempusIntegrator.hpp
- packages/piro/src/Piro_TempusIntegrator_Def.hpp
- packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/deprecated/CMakeLists.txt
- packages/tempus/src/deprecated/Readme.txt
- packages/tempus/src/deprecated/Tempus_IntegratorBasicOld.cpp
- packages/tempus/src/deprecated/Tempus_IntegratorBasicOld_decl.hpp
- packages/tempus/src/deprecated/Tempus_IntegratorBasicOld_impl.hpp
Because of a force push, creating a new PR for the original PR #10025 in order to pass CI.
See #10025.
* Closes #10023
> Tempus: Remove IntegratorBasicOld PART 2

- packages/muelu/test/unit_tests_kokkos/Utilities_kokkos.cpp
This "fix" removes the problematic checks. 
See https://github.com/trilinos/Trilinos/issues/10026 for more information
> MueLu: Fix failing CuthillMcKee tests

- packages/framework/pr_tools/trilinos_pr.ini
The paths to the ini files have changed.
This should address some master merge failures too (see below).
All the master merge projects were run with this branch.
The master merge projects were updated to use the PR driver scripts from `master_merge_YYYY_MM_DD` rather than `master` (related to https://github.com/trilinos/Trilinos/pull/10038).
> packages/framework: Update ini file

- packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp
@trilinos/ifpack2 @trilinos/tpetra 
I couldn't reproduce #10080 on my system, but the multivector access looks wrong.
> Ifpack2 FastILU: Fix MV access

- packages/tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_def.hpp
In future release of Kokkos this will be checked against the execution
space of the policy, and this was erroring out (policy is on host, but
typedef was for device). See https://github.com/kokkos/kokkos/issues/4677.
> Tpetra: remove unused device_type typedef in functor

- packages/muelu/adapters/xpetra/MueLu_Maxwell1_def.hpp
- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/test/maxwell/CMakeLists.txt
- packages/muelu/test/maxwell/Maxwell3D.cpp
- packages/muelu/test/maxwell/Maxwell_ML1_MueLu.xml
Translate ML style parameter lists for use with MueLu's Maxwell1 solver.
> MueLu: Add parameter translation for ML Maxwell1

- packages/framework/pr_tools/PullRequestLinuxCudaVortexDriver.sh
- packages/framework/pr_tools/PullRequestLinuxDriver.sh
- Limit -j to 10 for rdc
For a non incremental build, this reduces the dev2master cuda 10.1.243 rdc build time from 34 hours to 32 hours.
This was tested via a jenkins project which runs the cuda 10.1.243 rdc build.
> packages/framework:

- packages/zoltan/src/matrix/matrix_distribute.c
See the title and discussion in #10139
Thanks to @nate945 for reporting and suggesting the fix.
> zoltan:  the MPI standard says message tags should have numbers <= 32767

- .github/workflows/tpetra_muelu_label_to_project.yml
> Workflow: Fixing the auto-project for Tpetra

- packages/zoltan/docs/Zoltan.html
- packages/zoltan/docs/Zoltan_FAQ.html
- packages/zoltan/docs/Zoltan_bugreport.html
- packages/zoltan/docs/Zoltan_cite.html
- packages/zoltan/docs/Zoltan_phil.html
- packages/zoltan/docs/Zoltan_pubs.html
- packages/zoltan/docs/dev_html/dev.html
- packages/zoltan/docs/ug_html/ug.html
The previous link to Zoltan downloads took users to Sandia's github page, which required people to find the release link.
With this PR, users will instead go directly to the release page -- a better experience.
NA; documentation only.
I did test that the link was correct.
> zoltan:  better link to downloads for stand-alone zoltan

- .github/workflows/tpetra_muelu_label_to_project.yml
> Workflow: Updating Tpetra and MueLu auto-project

- packages/teuchos/comm/src/Teuchos_DefaultMpiComm.hpp
New compiler and MPI version doesn't work with zero-sized Allreduce.
See #10154 
@nate945, thank you for contributing this fix
Compiles on mac with clang
> teuchos recommended by @nate945 for #10154

- packages/stokhos/src/sacado/kokkos/Stokhos_Tpetra_Utilities.hpp
- packages/stokhos/src/sacado/kokkos/pce/amesos2/Amesos2_Solver_UQ_PCE.hpp
- packages/stokhos/src/sacado/kokkos/pce/belos/Belos_TpetraAdapter_UQ_PCE.hpp
- packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_UQ_PCE.hpp
- packages/stokhos/src/sacado/kokkos/pce/tpetra/Stokhos_Tpetra_Utilities_UQ_PCE.hpp
- packages/stokhos/src/sacado/kokkos/vector/amesos2/Amesos2_Solver_MP_Vector.hpp
- packages/stokhos/src/sacado/kokkos/vector/tpetra/Stokhos_Tpetra_Utilities_MP_Vector.hpp
- packages/stokhos/test/UnitTest/Stokhos_TpetraCrsMatrixMPVectorUnitTest.hpp
Fixes build errors when Tpetra deprecated code is turned off.
> Stokhos:  Remove use of deprecated code

- packages/muelu/example/advanced/multiplesolve/ReuseSequence.cpp
- packages/muelu/example/advanced/multiplesolve/StandardReuse.cpp
Tests: RHEL7
Issue: n/a; Stakeholder feedback: n/a
> MueLu: Fixing repeated using error generated by GCC 10

- packages/panzer/dof-mgr/src/Panzer_GlobalIndexer.hpp
Closes #10140
Fixes issue in Drekar 
Almost all tests/examples in adapters-stk subpackage exercise this change.
> 10140 panzer out of bounds error in li ds

- packages/shylu/shylu_dd/bddc/CMakeLists.txt
- packages/shylu/shylu_dd/bddc/cmake/ShyLU_DDBDDC_config.h.in
This PR adds deprecation messages to ShyLU_DD/BDDC.
> ShyLU_DD, BDDC: add deprecation message

- .github/workflows/tpetra_muelu_label_to_project.yml
Changing column from "Feature request" to "Backlog", as the latter is more appropriate.
> MueLu: update project action

- packages/nox/test/tpetra/1DFEM_Functors.hpp
Related to #8492
Ok I think I finally fixed it.
> NOX: Fix race condition in HouseholderBorderedSolve unit test

- packages/zoltan2/test/core/TpetraCrsColorer/Bug9500.cpp
- packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp
More inclusive output that was handy in debugging #9500 
As the person doing the debugging, I say this code was helpful.  :)
ascicgpu machines
> zoltan2:  better output control

- packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
- packages/tpetra/core/inout/MatrixMarket_TpetraNew.hpp
Tests: n/a
Issue: #10168
The "maybe uninitialized" compiler warnings annoyed me
> Tpetra: Fixing compiler warnings

- packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/core.h
- packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/format.h
- packages/seacas/libraries/suplib_cpp/fmt/core.h
- packages/seacas/libraries/suplib_cpp/fmt/format.h
This fixes the build problems related to lib::fmt on the intel-19 compiler.  The fixes were developed from discussions in https://github.com/fmtlib/fmt/issues/2746
* Closes #10172
> FMT: Fixes for intel-19 compiler

- packages/panzer/adapters-stk/example/CurlLaplacianExample/main.cpp
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/main.cpp
- packages/panzer/adapters-stk/example/MixedPoissonExample/main.cpp
- packages/panzer/adapters-stk/example/main_driver/energy-ss-blocked-tp.xml
- packages/panzer/disc-fe/src/evaluators/Panzer_GatherSolution_BlockedTpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp
- packages/panzer/dof-mgr/src/Panzer_GlobalIndexer.hpp
Fix an issue with dof-manager lid accessor.
Closes #10140 
reverted #10141 due to issues in an application
Fixes both Charon and Drekar
N/A
> Panzer fix dof manager

- packages/muelu/adapters/xpetra/MueLu_Maxwell1_def.hpp
- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/test/maxwell/Maxwell3D.cpp
Fix some MueLu Maxwell 1 issues:
- Allow dumping matrices
- Allow fixing small diagonal entries of Kn matrix regardless of how it was generated
- Handle case where all edges are on the boundary
> MueLu: Maxwell1 improvements

- packages/tpetra/core/example/Lesson02-Map-Vector/lesson02_init_map_vec.cpp
#10178 reports an error in documentation (actually, in an example).
This PR makes the example do what its comments say.
Tested with gcc on ascicgpu
> Tpetra:  Fixed example 

- cmake/ctest/drivers/enigma/ctest_linux_nightly_mpi_release_muelu_no_int_openmp_experimental_enigma.cmake
Improves nightly testing.
n/a
Will verify on dashboard.
> MueLu: testing: fix enigma nightlies

- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer_Zoltan.hpp
- packages/zoltan2/core/src/algorithms/Zoltan2_TPLTraits.hpp
- packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
- packages/zoltan2/core/src/algorithms/zoltan/Zoltan2_AlgZoltan.hpp
- packages/zoltan2/core/src/algorithms/zoltan/Zoltan2_AlgZoltanCallbacks.hpp
- packages/zoltan2/core/src/problems/Zoltan2_PartitioningSolution.hpp
- packages/zoltan2/test/core/helpers/UserInputForTests.hpp
Minor changes to reduce the number of warnings in PR builds.
ascicgpu with sems gcc compilers
> Zoltan2:  fewer compiler warnings in PR builds

- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/ParameterLists/ParameterList_TwoLevelPreconditioner_IPOUHarmonic_GDSW_Klu.xml
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/ParameterLists/ParameterList_TwoLevelPreconditioner_IPOUHarmonic_GDSW_Klu_ML.xml
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/ParameterLists/ParameterList_TwoLevelPreconditioner_IPOUHarmonic_RGDSW_Klu_ML.xml
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/ParameterLists/ParameterList_TwoLevelPreconditioner_IPOUHarmonic_GDSW_ML.xml
The parameterlists for the 3-level tests were outdated for the recent changes to FROSch, therefore these have been updated in this PR.
> Update 3-Level ParameterLists

- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_def.hpp
- packages/amesos2/src/Amesos2_MatrixAdapter_def.hpp
- packages/amesos2/src/Amesos2_STRUMPACK_def.hpp
- packages/amesos2/src/Amesos2_Superludist_def.hpp
- packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp
- packages/amesos2/src/Amesos2_TpetraRowMatrix_AbstractMatrixAdapter_def.hpp
- packages/amesos2/src/Amesos2_Util.hpp
- packages/amesos2/test/solvers/SolverFactory.cpp
- packages/amesos2/test/tklu_simple/tklu_simple.cpp
Attempts to address issue #10247
Related to #10189
Address #10247
@ikalash please test with these changes after merge
Autotester plus stakeholder feedback
> Amesos2: update Tpetra getNode* names to getLocal*

- packages/muelu/src/Utils/MueLu_Utilities_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/scaling/JacobiKernelDriver.cpp
- packages/muelu/test/scaling/MMKernelDriver.cpp
- packages/muelu/test/scaling/TwoMatrixMMKernelDriver.cpp
Missed some deprecated things for other template args.
> MueLu: Fix more deprecated issues

- packages/panzer/adapters-stk/src/Panzer_STK_LocalMeshUtilities.cpp
- packages/panzer/adapters-stk/test/face_to_elem/Panzer_Relations.cpp
- packages/panzer/disc-fe/src/Panzer_FaceToElement_impl.hpp
- packages/panzer/disc-fe/src/Panzer_L2Projection.cpp
- packages/panzer/disc-fe/src/lof/Panzer_BlockedTpetraLinearObjFactory_impl.hpp
- packages/panzer/disc-fe/src/lof/Panzer_TpetraLinearObjFactory_impl.hpp
- packages/panzer/disc-fe/test/la_factory/tTpetraLinearObjFactory.cpp
- packages/panzer/disc-fe/test/la_factory/tTpetra_GlbEvalData.cpp
- packages/panzer/dof-mgr/src/Panzer_DOFManager.cpp
- packages/panzer/dof-mgr/test/dofmngr_test/tGlobalIndexerUtilities.cpp
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_assembly_HEX.hpp
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_projection.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_DiscreteGradient.hpp
Remove deprecated code
Allows empire to compile with deprecated code disabled
N/A
> Panzer: remove tpetra deprecated code

- packages/PyTrilinos/example/exEpetra_DAP.py.in
- packages/PyTrilinos/src/PyTrilinos_Tpetra_Util.cpp
- packages/PyTrilinos/test/testTpetra_Map.py.in
- packages/piro/test/MockModelEval_A_Tpetra.cpp
- packages/piro/test/MockModelEval_B_Tpetra.cpp
@trilinos/piro
remove Tpetra deprecated code
> Piro/PyTrilinos: remove tpetra deprecated code

- packages/nox/test/tpetra/ME_Tpetra_1DFEM_def.hpp
- packages/nox/test/tpetra/ME_Tpetra_Heq_def.hpp
- packages/nox/test/tpetra/Tpetra_OperatorTests.cpp
remove use of deprecated tpetra code
No more warnings in nox.
N/A
> NOX: remove use of tpetra deprecated code

- packages/panzer/adapters-stk/test/stk_interface_test/tExodusReaderFactory.cpp
Add more testing to the optional integration with UMR and SGM in Panzer. 
Specifically, check that the total number of faces in each sideset matches the expected values. Also check that the number of nodesets and sidesets is correct.
> Update UMR integration unit test in Panzer
