trilinos/Trilinos

- packages/sacado/src/mpl/Sacado_mpl_is_convertible.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_ViewStorage.hpp
- packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
Requested by Nate Roberts.  This was only done for the new design.
Supporting this in the old design would be very painful.  Added a unit
test to verify it works.
> Sacado:  Allow copy-assign of ViewStorage<T,...> to ViewStorage<const T,...>

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/test/structured/CMakeLists.txt
- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
Following structured coarsening in the region format, each rank may only own a few dofs. Here we rebalance the coarse grid operator before constructing the coarser grid AMG hierarchy in an attempt to reduce communication.
Also, fixes the call to iterate on the coarse AMG hierarchy.
Tests have been added to the regionMG tests that utilize this rebalancing. 
The number of partitions for the coarse gird repartitioning is an input (default is 1).
When more than one iteration of the coarse grid AMG iteration are used (so deviating from a V-cycle structure, and approaching the AMG as a coarse level solve), the convergence of rebalancing before building the coarse AMG is nearly identical to the converge of not rebalancing (convergence is not identical since different partitions …
> Muelu: regionMG add rebalance before coarse AMG iterations

- packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
This adjustment is based on experimental observations of kernel behaviors on vortex.  The performance inflection point between running on host and device is about 22,000.
* Follows https://github.com/trilinos/Trilinos/pull/7387
This touches nothing that isn't already unit-tested.
Experimental data, using thresholds of 0 and 1,000,000,000:
> Adjust runKernelOnHost threshold

- cmake/std/atdm/contributed/kokkos-dev-2/environment.sh
this PR adds kokkos-dev-2 environment.sh script
system has sems modules available and very similar to sems-rhel7
environment, along with local installs of modules
To expand scope of atdm testing framework to a kokkos developers' workstation for Trilinos testing
Tested loading of various configurations and a cuda/9.2 build with subset of packages enabled
```
export TRILINOS_DIR=${HOME}/Trilinos
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/kokkos-dev-2
source ~/Trilinos/cmake/std/atdm/load-env.sh kokkos-dev-2-cuda-opt
cmake  \
-GNinja  \
-DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake  \
-DTrilinos_ENABLE_Kokkos=ON \
-DTrilinos_ENABLE_TpetraCore=ON \
-DCMAKE_CXX_STANDARD=14 \
$TRILINOS_DIR
```
> atdm/contributed: add script for kokkos-dev-2 test bed

- packages/tpetra/core/test/CrsMatrix/Equilibration.cpp
Add work-around in unit test
tpetra/core/test/CrsMatrix/Equilibration.cpp
to resolve internal compiler errors of type
`internal compiler error: in maybe_undo_parenthesized_ref, at cp/semantics.c:1705`
Workaround compilation error with cuda/9.2+gcc/7.2 with c++14 support enabled
This is an internal gcc compiler error that pops up with c++14 support, see for example
https://github.com/kokkos/kokkos-kernels/issues/349
Tested with a contributed atdm script I am working (essentially the same as sems-rhel7 env instead of kokkos-dev-2)
```bash
export TRILINOS_DIR=${HOME}/Trilinos
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/kokkos-dev-2
source ~/Trilinos/cmake/std/atdm/load-env.sh kokkos-dev-2-cuda-opt
#source …
```
> tpetra: workaround gcc/7.2.0 bug with c++14

- cmake/ctest/drivers/atdm/tlcc2/drivers/Trilinos-atdm-tlcc2-intel-debug-openmp.sh
See [ATDV-392](https://sems-atlassian-srn.sandia.gov/browse/ATDV-392).
I just directly ran the script on a RHEL6 machine as:
```
$ ~/Trilinos.base/Trilinos/cmake/ctest/drivers/atdm/tlcc2/drivers/Trilinos-atdm-tlcc2-intel-debug-openmp.sh 
/ascldap/users/rabartl/Trilinos.base/Trilinos/cmake/ctest/drivers/atdm/tlcc2/drivers/Trilinos-atdm-tlcc2-intel-debug-openmp.sh: line 11: /Trilinos/cmake/ctest/drivers/atdm/tlcc2/local-driver.sh: No such file or directory
```
It did not crash, so it am sure it set the time limit correctly since this is pretty simple code.  I could have tested on a tlcc2 machine but this is a very low risk change.
> ATDM: tlcc2: Change time limit from 1:30 to 3:00 for debug build (ATDV-392)

- packages/muelu/research/regionMG/test/structured/CMakeLists.txt
- packages/muelu/research/regionMG/test/structured/structured_linear_R_3dof.xml
- packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_def.hpp
#7979 accidentally broke some MueLu experimental code. This fixes a majority of the issues, but the linear solve for the region Elasticity3D problem still seems to act strange. You can see this when watching the verbose test output.
There may still be some functionality related to these tests that forgets the number of DOFs per node internally. Setting the Xpetra block size for R and P when they are computed in RegionRFactory helped it remember what A's block size should be on the next level, but this other strange behavior is still being investigated.
This time I made sure to run the experimental tests in addition to the unit tests on a debug build, and the tests are not failing, which is an improvement.
> MueLu: Improve RegionRFactory and Tests

- packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
This code existed as a workaround to a Kokkos::parallel_scan bug (the so-called "UVM bug" of 2019).
The bug is fixed so this workaround is no longer needed.
cee-lan, gcc 7.3
> Tpetra:  remove Kokkos::parallel_scan workaround implemented for 2019 parallel_scan bug

- packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp
- packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp
- packages/amesos2/src/Amesos2_Superludist_decl.hpp
- packages/amesos2/test/solvers/CMakeLists.txt
- packages/amesos2/test/solvers/superludist_test.xml
Use superludist config to get int_t size 32 or 64.
Fix superlu dist test to run for long long go.
Remove --refactor option which needs to be resolved and fails.
Modify SuperLuDist to use int_t so it works for size 32 or 64.
@ndellingwood I disabled the --refactor option. This is failing right now but not resolved yet. There was a prior error in the refactor setup causing it to test an all 0 vector. I fixed that a few months ago at which point SuperLUDist would have started failing. If it's ok to disable this fo now I can investigate as a separate issue. There are some other refactor issues in #7216 and I added a comment there on this.
@srajama1 FYI - These are the fixes from the recent user issue regarding SuperLUDist with size 64.
Resolve Amesos2 SuperLUFDist so it …
> Amesos2: SuperLUDist fixes

- cmake/std/atdm/van1-tx2/environment.sh
I would like to push a minor tweak to `cmake/std/atdm/van1-tx2/environment.sh` to load python/3.6.8-arm which provides a newer version of numpy that EMPIRE requires.  Previously, python/3.6.8 got loaded.
> Minor tweak to van1-tx2 environment

- cmake/std/PullRequestLinuxClang10.0.0TestingSettings.cmake
- cmake/std/PullRequestLinuxClang9.0.0TestingSettings.cmake
A coming release of Kokkos will require C++14.
This will test that requirement in the builds for Clang 9.0.0 & 10.0.0 used in PR & Dev to Master testing.
This closes #8017
This has been manually run though the clang 9 & 10 PR tests.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=4&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=c14&field2=buildname&compare2=63&value2=clang&field3=buildstamp&compare3=63&value3=Experimental&field4=buildstarttime&compare4=83&value4=2020%2F09%2F15)
> Set standard to C++14 on Clang builds

- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
This frees some memory, as we don't need the composite operator on the fine level anymore, once we have created the region matrix.
Tests pass locally.
> MueLu: free fine-level composite operator as soon as possible

- packages/phalanx/example/FiniteElementAssembly/evaluators/GatherSolution_Def.hpp
- packages/phalanx/example/FiniteElementAssembly/evaluators/ScatterResidual_Def.hpp
- packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/GatherSolution_Def.hpp
- packages/phalanx/example/FiniteElementAssembly_MixedFieldTypes/evaluators/ScatterResidual_Def.hpp
c++14 builds are broken with intel that uses gcc 5/6 due to lambda capture bug.
Closes https://github.com/trilinos/Trilinos/issues/8048
c++14 PR testing will cover this.
> Phalanx: fix for gcc 5/6 lambda bug on cuda

- packages/zoltan2/core/src/directory/Zoltan2_Directory.hpp
- packages/zoltan2/core/src/directory/Zoltan2_Directory_Comm.cpp
- packages/zoltan2/core/src/directory/Zoltan2_Directory_Comm.hpp
- packages/zoltan2/test/core/directory/directoryTest_Impl.hpp
- packages/zoltan2/test/core/directory/directoryTest_KokkosSimple.cpp
- packages/zoltan2/test/core/directory/directoryTest_findUniqueGids.cpp
@kddevin These are the conversions to Teuchos comm we discussed a while back. Most of this is just straight forward conversion from the MPI version to the Teuchos version.
Teuchos didn't have logical or (LOR) for reduce and I switched to bitwise (BOR). We're using int as 0 or 1 to represent bool logic in this case. I'm not sure it matters so much which we use but I could easily add LOR to Teuchos.
The only complication was Teuchos does not have waitAny. What I did as a short term fix was serialize that segment to just call wait on each request in order (would be some loss of performance) and left a note describing how we can convert this back to waitAny when available. I started looking at what Teuchos needs and it should be pretty easy to set up since we can just copy the waitAll method …
> Zoltan2: Refactor directory to use Teuchos comm

- packages/tpetra/tsqr/src/Tsqr_FullTsqrTest.hpp
- packages/tpetra/tsqr/test/Tsqr_TestNodeTsqr.cpp
Apparently some gcc compilers with std=c++14 don't handle usage of const variables inside lambda expressions well.
See details in #8047 and https://github.com/kokkos/kokkos-kernels/issues/349
This PR works around such errors in three cases.  I remove the const specification from variables used inside the lambdas.
A better solution would have been to rewrite the code not to use lambdas (the same can be said for #8031).  The lambdas aren't in a parallel_for; they are just for convenience.  This code is primarily test code, though, so it didn't seem worth the time to rewrite.  
* Closes #8047 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@ZUUL42  Let me know whether this works for you.
Compiled Tpetra on ride with Trilinos' PR …
> Tpetra:  workarounds to compiler bug in #8047

- cmake/std/PullRequestLinuxDriverTest.py
- cmake/std/PullRequestLinuxGCC7.2.0SerialTestingSettings.cmake
- cmake/std/sems/PullRequestGCC7.2.0SerialTestingEnv.sh
- cmake/std/unittests/TestPullRequestLinuxDriverTest.py
This will add the needed code for a new Serial GCC 7.2.0 C++14 PR build.
This addresses and closes #8071 
This is work moves to a configuration that is c++14 ready making the PR testing scheme ready for Kokkos 3.3 to be merged in.
A new Jenkins job was created and tested building with this new code.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-gcc72c14serial-test-Trilinos_pullrequest_gcc_7.2.0_serial-1&field3=buildstamp&compare3=61&value3=20200922-1624-Experimental)
A few WError flags had to be turned off to get a clean build.
```
-Wno-unused-but-set-variable
-Wno-unused-variable
-Wno-unused-label
```
This …
> Create new Serial GCC7.2.0 PR build with C++14 set

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc.cmake
The option redirects valgrind output to file. I'm hoping this is the reason why not valgrind results are getting posted.
> Geminga: Remove valgrind option

- cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake
- cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
This will add the needed flags to set the standard to C++14 for the GCC 7.2.0 build.
Associated with #6260.
This work moves to a configuration that is c++14 ready making the PR testing scheme ready for Kokkos 3.3 to be merged in.
This has been tested by manually running the GCC 7.2.0 Jenkins job with the updated code.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-gcc72c14-test-Trilinos_pullrequest_gcc_7.2.0-5703&field3=buildstamp&compare3=61&value3=20200924-2050-Experimental)
> Set standard to C++14 for GCC 7.2.0 PR build

- packages/seacas/libraries/ioss/src/cgns/Iocgns_StructuredZoneData.C
- packages/seacas/libraries/ioss/src/main/cgns_decomp.C
Fixes error in last seacas snapshot which resulted in non-symmetric ZGC (communication interfaces) between zones.  This fixes the issue and adds a `validate_symmetric_communication` function to the `cgns_decomp` program which will catch this in the future.  Verified that the validate function correctly found the 4 bad interfaces prior to the fix and found no problems after the fix.
> Seacas fix symmetric communication

- packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
@csiefer2 I plan to put all the 3-arg deep_copy comments and current refactor work in a single PR which I think will make it easier for someone to continue in the future, either by using it as a reference or a starting point for a submission.
This PR rolls back the one 3-arg conversion we actually merged: #7972. I'm realizing now this is probably not safe for CUDA_LAUNCH_BLOCKING=0 and HostSpace inputs. I'll send some further notes on this.
Since it's the only one we merged, I think rolling it back would make sense so I can leave things in a well-defined state for future work.
Leave Tpetra in a well-defined state with no 3-arg deep_copy conversions until other issues are resolved.
Mac parallel build - this rolls back a prior change
> Tpetra: Rollback #7972

- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
- packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
While reviewing deep copy in tpetra, I thought that this method does not have to be too complicated as previously. I also would like to discuss a couple of things
1. Do we really need to follow the last touch rule in dual view ? 
I believe that the dual view is for convenience to keep the data both places and communicate more easily. I do not think that using the host view of the dual view is for a performance reason. We probably may want to use devices as much as possible. However, the last touch rule makes the code complicated and it can result in using inefficient host kernels. As seen in #7985, we can get better performance when we select where to execute the kernel considering the problem size or other aspects. I also think that there is a reason that tpetra chose to follow the last …
> Tpetra - change the logic in set all to scalar

- packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefCloneScale.hpp
- packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefContractions.hpp
- packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefDot.hpp
- packages/intrepid2/src/Shared/Intrepid2_ArrayToolsDefScalar.hpp
- packages/intrepid2/src/Shared/Intrepid2_RealSpaceToolsDef.hpp
- packages/intrepid2/src/Shared/Intrepid2_Utils.hpp
- packages/intrepid2/unit-test/Shared/ArrayTools/Cuda/test_01.cpp
- packages/intrepid2/unit-test/Shared/ArrayTools/Cuda/test_02.cpp
- packages/intrepid2/unit-test/Shared/ArrayTools/Cuda/test_03.cpp
- packages/intrepid2/unit-test/Shared/ArrayTools/test_01.hpp
- packages/intrepid2/unit-test/Shared/ArrayTools/test_02.hpp
- packages/intrepid2/unit-test/Shared/ArrayTools/test_03.hpp
We do not like uvm. This is a first test modification from using Kokkos::Cuda to Kokkos::Device<Kokkos::Cuda, Kokkos::CudaSpace>. There are lots of places to change the tests where they assume uvm. This seems to take more time. 
Tested on weaver.
> Intrepid2 - uvm removal on test

- cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainerUtil.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp
- packages/kokkos-kernels/src/batched/KokkosBatched_SetTriangular_Internal.hpp
- packages/kokkos-kernels/unit_test/batched/Test_Batched_TeamVectorSolveUTV.hpp
- packages/kokkos-kernels/unit_test/batched/Test_Batched_TeamVectorSolveUTV2.hpp
- packages/kokkos-kernels/unit_test/batched/Test_Batched_TeamVectorUTV.hpp
This will add the needed flags to set the standard to C++14 for the CUDA 9.2.88 build.
It also fixes a few build errors that come up in ifpack2 and kokkos-kernels.
Associated with #6260
Closes #8016
This work moves to a configuration that is c++14 ready making the PR testing scheme ready for Kokkos 3.3 to be merged in.
Tested by running the CUDA 9.2.88 PR build job manually, merging this branch into develop.
Results: [CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ride12&field2=buildname&compare2=61&value2=PR-cuda9c14fix-test-Trilinos_pullrequest_cuda_9.2-5629&field3=buildstamp&compare3=61&value3=20200928-0300-Experi …
> Framework/ifpack2/kokkos-kernels: Set standard to C++14 for CUDA 9.2 PR build

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
This will show up in the mouseover for each datapoint, making it much
easier to match performance changes with code changes.
This is used by setting environment variable ``TRILINOS_GIT_SHA`` to `` `git rev-parse HEAD` `` in the testing scripts.
This is optional - if the variable is not set, the XML files just won't contain this metadata.
This will increase the usability of the Jenkins performance dashboards. Right now, if there's a big swing in some measurement, you have to manually look at the date/time the build ran and find it in the git history. With this change, the chart will already have that info (e.g. for bisecting, datapoints N-1 and N will give the start and end).
This idea came from Tpetra meetings where we were trying to figure out which code changes caused …
> Teuchos: Add Git SHA as Watchr metadata

- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
- packages/tpetra/core/src/Tpetra_Map_def.hpp
@kddevin @csiefer2 Resolves FixedHashTable so it can construct on CudaSpace. Previously it assumed UVM. This is the repair we discussed earlier and it cleans up the setup in Map.
The next step would be to write a parallel kernel version of the search for the first non-continuous key. We may not want to merge this PR until that is resolved since my change can impact performance. But I think it's ok to treat that as a separate issue because even though I added a copy in FixedHashTable, I was able to remove the extra copy in Map.
I could start working on a parallel kernel version. I am wondering if a simple parallel for loop with atomic comparison checks for non-contiguous neighbors might actually do unexpectedly well, based on prior experience with Multijagged kernels.  That would be much …
> Tpetra: Allows FixedHashTable to build on CudaSpace

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
Also a fix to rebalancing the coords for the coarse level solve that was causing some regionR tests to not work with rebalancing.
Addresses Issue #8131 
It compiles in serial now.
> MueLu: Fix to guard region coarse rebalance in serial

- cmake/std/PullRequestLinuxCuda9.2TestingSettings.cmake
Intrepid2: SET_RUN_SERIAL to true for one test in CUDA PR testing; should resolve random timeouts.
See #3276.
> Intrepid2: SET_RUN_SERIAL to true for one test in CUDA PR testing.

- packages/muelu/research/regionMG/src/SetupRegionMatrix_def.hpp
- packages/muelu/src/Transfers/GeneralGeometric/MueLu_RegionRFactory_def.hpp
- packages/muelu/test/unit_tests/RegionRFactory.cpp
~~Please do not merge this yet. I want to squash the commits down, but I don't want to do so until I see how it turns out.~~
Edit: everything has been squashed.
There was a flaw in the logic in `RegionRFactory` that was the source of the issue. For a restrictor, the block size should be the outer loop. In addition, `MakeRegionMatrices` was throwing away the block size of the matrix A from which it was created, which caused some region tests to look like they were correctly preparing the 3 DOF per node version, when in fact the matrices in `regionGrpMats` were not treated as having 3 DOFs per node.
I noticed a significant improvement in the iterations to solve the related regression tests. ~~I haven't run other tests yet because I want to see how this impacts the …
> MueLu: Correct logic in RegionRFactory and update MakeRegionMatrices to not forget block size

- cmake/std/PullRequestLinuxClang10.0.0TestingSettings.cmake
- cmake/std/PullRequestLinuxClang7.0.1TestingSettings.cmake
- cmake/std/PullRequestLinuxClang9.0.0TestingSettings.cmake
- cmake/std/PullRequestLinuxGCC7.2.0DebugTestingSettings.cmake
- cmake/std/PullRequestLinuxGCC7.2.0SerialTestingSettings.cmake
- cmake/std/PullRequestLinuxGCC7.2.0TestingSettings.cmake
- cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake
- cmake/std/PullRequestLinuxIntelTestingSettings.cmake
A little clean up after the C++14 changes:
- The `CMAKE_CXX_FLAGS "-std=c++14` are uneseccary and [can cause issues](https://github.com/trilinos/Trilinos/pull/8114#discussion_r496124370), so they are removed.
- `CMAKE_CXX_STANDARD "14"` is moved to a standardized place on top of all cmake files.
- The order of `-DTRILINOS_HIDE_DEPRECATED_HEADER_WARNINGS -Werror` [was causing warnings](https://github.com/trilinos/Trilinos/issues/8071#issuecomment-697743665), so it has been reversed in all applicable locations.
- Set C++14 for the Clang 7 build.
> C++14 clean up

- packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp
- packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases/AnalyticPolynomialsMatchTests.cpp
Intrepid2: modifications to avoid unnecessary copies of Fad types during test comparisons.
See #8148.
> Intrepid2: modifications to avoid unnecessary copies of Fad types during test comparisons.

- packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp
- packages/intrepid2/unit-test/Discretization/Basis/HierarchicalBases/AnalyticPolynomialsMatchTests.cpp
Following on #8148, this PR prototypes a new mechanism for performing error measurements, shifting more of the burden to the device.  In the Fad test we're working with, this reduced the runtime on ride by a factor of about 6.  (#8148 itself had reduced the runtime by about a factor of 5, so this represents a cumulative 30x speedup.)
The ultimate idea is to revise the testFloatingEquality() methods that we define in TestUtils to take advantage of this new mechanism, thereby speeding up all tests that take advantage of those.
> Intrepid2: prototype faster Fad comparisons for tests

- packages/muelu/test/toggletransfer/CMakeLists.txt
PR #8115 remove the duplication of a (Tpetra) test. The second instance was meant to be run using Epetra.
> MueLu ToggleP tests: Test Epetra same as Tpetra

- packages/panzer/adapters-stk/example/main_driver/energy-ss-blocked.xml
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareQuadMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareQuadMeshFactory.hpp
Added an option to the inline quad mesh generator to shift the element
and node gids in stk to all be greater than the 32-bit int limit. This
allows small meshes to be used to test certain code paths "at scale"
for ordinal type issues.
Help debug an issue an application is seeing for large problems.
Changed the main_driver/energy steady state problem to exercise this capability.
> Panzer: add option to shift mesh gids above 32-bit int limit for testing

- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/test/maxwell/CMakeLists.txt
Instead of throwing when rebalancing is enabled in a serial run, just warn about it.
This allows running XMLs that have rebalancing enabled in serial.
> MueLu: Don't throw when rebalancing is enabled in serial run, just warn

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_decl.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
Make skipping of the finest level in the (1,1) hierarchy optional (parameter `refmaxwell: skip first (1,1) level`). The default behavior has not changed.
> MueLu RefMaxwell: Make skipping of first (1,1) level optional

- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_cuda_no_uvm_geminga.cmake
- packages/tpetra/core/CMakeLists.txt
Allow to configure Tpetra without UVM by setting `Kokkos_ENABLE_CUDA_UVM` and `Tpetra_ENABLE_NO_UVM`.
This is only so that we can start working on removing UVM. Building without UVM does currently not work.
> Tpetra: Allow configuration without UVM

- cmake/ctest/drivers/apollo/TrilinosCTestDriverCore.perseus.generic.cmake
The test machine apollo is pulling from a defunct repo:
*** Base Git Repo: Trilinos
4442eef [Mon Jul 15 16:53:15 2019 -0600] <trilinos-autotester@trilinos.org>
Merge Pull Request #5529 from rppawlo/Trilinos/phalanx-remove-dim-tags-files
This commit points to a repo that's synced at the same time every night
@trilinos/muelu @trilinos/framework @crtrott 
Get tests running again on nightly test machine.
Will be verified on dashboard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/8196)
> Testing: apollo: fix repo error

- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_BlockVector_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockVector_def.hpp
- packages/tpetra/core/src/Tpetra_idot.hpp
- packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
- packages/tpetra/core/test/Block/BlockMultiVector.cpp
@trilinos/tpetra @cgcgcg 
Tpetra currently fails to build when the default memory space for `Kokkos::Cuda` is `Kokkos::CudaSpace`.  Fixing the build issues is the first step towards removal of the requirement that the default Cuda memory space be `Kokkos::CudaUVMSpace`.
Closes #8151, #8164
Using `Kokkos::CudaSpace` as the default Cuda memory space will currently cause failing tests, and this is documented in the configure script.  Future PR's will fix the failing tests so we can guarantee support for this memory space.
> Tpetra: Fix compile-time issues with using Kokkos::CudaSpace as the default Cuda memory space

- packages/panzer/adapters-stk/example/main_driver/CMakeLists.txt
- packages/panzer/adapters-stk/example/main_driver/energy-periodic-32bit-limit.xml
- packages/panzer/adapters-stk/src/Panzer_STKConnManager.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Matcher.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareQuadMeshFactory.cpp
FEM^3 reported seg fault for large scale problems using periodic bcs.
Application now passes at scale.
New test added that shifts mesh GIDs above 32-bit int limit to reproduce failure. Test is:
panzer/adapters-stk/example/main_driver/energy-periodic-32bit-limit.xml
> Panzer: fix periodic bc matcher for 32 bit int limit

- packages/amesos2/src/Amesos2_Kokkos_Impl.hpp
When UVM is disabled we don't need to instantiate twice.
#8238
> Amesos2: Do not instantiate twice when UVM off

- cmake/ctest/drivers/geminga/ctest_linux_nightly_mpi_release_muelu_cuda_no_uvm_geminga.cmake
- packages/muelu/test/unit_tests/MueLu_Test_ETI.hpp
- packages/muelu/test/unit_tests_kokkos/MueLu_UnitTests_kokkos.cpp
Add printing of stack traces to MueLu test ETI. (Requires TPL BinUtils.)
Use it in the no-UVM nightly build to get spots with inaccessible memory spaces.
> MueLu: Print stack traces

- commonTools/gtest/gtest/README
- commonTools/gtest/gtest/gtest-all.cc
- commonTools/gtest/gtest/gtest.h
@trilinos/framework @trilinos/stk @jhux2 
Update Gtest to 1.10.0 to match the version in Sierra for consistency with STK.  This also adds functionality desired by the ExaWind project.  This PR only updates the fused-source googletest, and does not include googlemock, so may not completely address the use cases @etphipp and @rppawlo raised in #7698 and #4421.
* Closes #8001 
* Related to #7698, #4421 
This package is part of the testing suite, so is not directly tested and no new tests are added.  The Trilinos tests are expected to continue to pass.
> Gtest: Update to version 1.10.0

- packages/muelu/src/Graph/Containers/MueLu_Aggregates_kokkos_def.hpp
Small modifcation that extracts the number of nnz from the row_map
view to then allocate column_indices view.
Removing UVM is good for the moral
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Locally tested on my workstation
> MueLu: removing a UVM access from MueLu_Aggregates_kokkos_def.hpp

- packages/piro/src/Piro_PerformAnalysis.cpp
- packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Constraint_SimOpt.hpp
- packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective_SimOpt.hpp
- packages/rol/cmake/ROL_config.h.in
- packages/rol/src/step/trustregion/ROL_TrustRegion.hpp
@trilinos/rol 
@mperego 
The initial goal of this PR was to configure the definition of the HAVE_ROL_DEBUG macro using cmake.
After that, when running ctest with HAVE_ROL_DEBUG defined, some issues in Piro_PerformAnalysis with Thyra adapters have been observed.
It has been observed that, in at least some optimization algorithm implementations, the update function is not always called before the computation of the Hessian or the gradient when either x (called u in ROL) or p (called z in ROL) has been updated.
There were two options to overcome this:
1. To revisit ROL functions and add update if required,
2. To add a check at the beginning of the Thyra adapters to test if x or p has changed, if it is the case, the values are updated.
It is the latest solution which is implemented in this …
> ROL: solve issues related to falling checks when HAVE_ROL_DEBUG is defined

- packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp
This changes fixes the false assignment of the method to Doxygen groups. Move the method `numParams()` to the Doxygen group "Attribute Functions", where it fits in better than in the "Constructors" group.
Existing `Teuchos` unit tests are passing.
> Teuchos: fix Doxygen group in ParameterList

- packages/amesos/src/Amesos_Superludist.cpp
- packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp
- packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp
- packages/amesos2/src/Amesos2_Superludist_decl.hpp
This is a fix required by xSDK-0.6.0 release ( #8062 ), which includes the new SuperLU_DIST-6.3.
https://github.com/xiaoyeli/superlu_dist
@trilinos/amesos
SuperLU_DIST-6.3 introduced a few API changes. We are adding an extra support to adapt the changes.
Related Issues
#8062
#8067
#8137 
xSDK team, in particular deal.II developers, want to keep the support of the latest SuperLU_DIST and SuperLU for the 1st generation packages.
##Testing
The tester needs SuperLU_DIST-6.3. Please add this to the TPL lists being tested.
xSDK team will test the build process of the whole Trilinos library and example programs (Amesos2 and Amesos).
The approval is pending on the confirmation of #8137 fix.
> Fix for #8062.

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
Make nullspace normalization in RefMaxwell optional.
It seems to be more harmful to convergence to normalize.
@csiefer2 @rstumin
> MueLu RefMaxwell: Make nullspace normalization optional

- packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp
This is a fix for bug #8258.  When SuperLU_DIST-6.2 or earlier is set, it picks up wrong TypeMap declaration. (See line 252 of Amesos2_Superludist_TypeMap.hpp )
> Fix for #8258.  (Fixing typo in TypeMap declaration.)

- packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp
This is a fix for #8258. There is a typo in the TypeMap declaration for older SuperLU_DIST (6.2 or earlier).  See the line 252 of Amesos2_Superlumt_TypeMap.hpp.
> Fix for #8258. (Fixing typo in TypeMap declaration.) in 13.x release

- packages/tpetra/core/test/Core/ScopeGuard_tpetra_inits_kokkos.cpp
- packages/tpetra/core/test/Core/ScopeGuard_tpetra_inits_mpi.cpp
- packages/tpetra/core/test/Core/ScopeGuard_tpetra_inits_mpi_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_mpi.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_mpi_and_provides_comm.cpp
- packages/tpetra/core/test/Core/ScopeGuard_user_inits_mpi_tpetra_inits_kokkos.cpp
- packages/tpetra/core/test/Core/initialize_tpetra_inits_kokkos.cpp
- packages/tpetra/core/test/Core/initialize_tpetra_inits_mpi.cpp
- packages/tpetra/core/test/Core/initialize_tpetra_inits_mpi_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_kokkos.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_mpi.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_mpi_and_provides_comm.cpp
- packages/tpetra/core/test/Core/initialize_user_inits_mpi_tpetra_inits_kokkos.cpp
- packages/tpetra/core/test/Core/issue_434_already_initialized.cpp
- packages/tpetra/core/test/Core/issue_434_not_yet_initialized.cpp
Addressing #7966, #3453, #6748.
These tests exercises various combinations of MPI, Kokkos and Tpetra  initialization.  They checked the combinations for correctness (e.g., that Tpetra::ScopeGuard initialized TPLs if needed and finalized them upon destruction).  All good!
But the tests also captured warnings from Kokkos::initialize, and failed if Kokkos produced any warnings.  The problem is, we can't control what warnings Kokkos chooses to issue, and some Kokkos warnings had nothing to do with whether or not these tests worked correctly.  In particular, this check caused problems with CUDA_LAUNCH_BLOCKING=0 testing (see #7966).
I removed the check for output from Kokkos::initialize.  
All other checks (various combinations of initialized/finalized for MPI and Kokkos) in …
> Tpetra:  remove check of Kokkos warning output in Tpetra tests

- cmake/std/pr_config/pullrequest.ini
The clang 7.0.1 build loads `sems-cmake/3.10.3` from the SEMS-DEFAULT section but then it tries to load
`sems-cmake/3.12.2` which will fail because a `sems-cmake` module is already loaded.
I added a `module-remove sems-cmake:` rule prior to loading the changed version. This should fix that issue.
@prwolfe
> Framework: PR Configuration fix for Clang 7.0.1 build

- cmake/std/PullRequestLinuxDriverTest.py
- cmake/std/common.bash
- cmake/std/trilinosprhelpers/TrilinosPRConfigurationBase.py
- cmake/std/trilinosprhelpers/TrilinosPRConfigurationInstallation.py
- cmake/std/trilinosprhelpers/TrilinosPRConfigurationStandard.py
- cmake/std/trilinosprhelpers/setenvironment/SetEnvironment.py
- cmake/std/trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py
Clean up Markdown Interpretation of Console Log Output
--------
This is a style update for the PR scripts. Mostly changing occurrences of `print("---")` lines because when this part of the console log gets put into a PR job it causes the Markdown generator in github to generate a header out of the previous line.
Better Messaging when CTest Fails
---------
The 2nd thing here is a change to how the exit status is handled from the ctest run.
In the `TrilinosPRConfigurationStandard.py` file we add a `try ... except` block around the `subprocess.checked_call()` call to catch the error that is thrown when the exit status is not zero from the ctest call.
https://github.com/william76/Trilinos/blob/8f3d7d78b09fa4462b1341d90869609b7d8c3a51/cmake/std/trilinosprhelpers/TrilinosPRC …
> Framework: PR Driver Console Log Cleanup

- packages/shylu/shylu_node/tacho/example/Tacho_ExampleSolver.hpp
- packages/shylu/shylu_node/tacho/src/Tacho_Solver.hpp
- packages/shylu/shylu_node/tacho/src/impl/Tacho_Solver_Impl.hpp
For solving multiple problems in parallel, we want to try a different ordering strategy which maintain independent graphs separately. This PR allows the option.
This is requested from ASC customer. 
This option is the default ordering option now for testing and it passes the unit test.
> Tacho - customer feature request for ordering connected graph separately.

- packages/teuchos/core/src/Teuchos_ScalarTraits.hpp
- packages/teuchos/core/src/Teuchos_as.hpp
- packages/teuchos/core/test/TypeConversions/TypeConversions_UnitTest.cpp
This is to resolve issue #8210
The clang compiler issues a significant number of warnings due to the implicit casts in these files. This makes those casts explicit to handle this warnings
* Closes #8210 
Teuchos was built against GCC7.2 and Clang 10 and all tests passed
> Reduce clang warning from Teuchos

- packages/tpetra/core/test/MultiVector/Vector_offsetViewCtor.cpp
Replace TEUCHOS_UNIT_TEST_TEMPLATE_4_DECL with TEUCHOS_UNIT_TEST_TEMPLATE_4_INSTANT
at the bottom of Vector_offsetViewCtor.cpp. the ...DECL macro is already called for this test above, at the bottom it needs to be instantiated with the ...INSTANT macro. Note that this file is not actually compiled (@mhoemmen had commented out it in CMakeLists.txt) but it's tripping up the automatic LO/GO removal script.
Just allows the LO removal script to run on this file. It doesn't change any behavior or affect testing, since this file is never compiled.
> Tpetra: fix typo in test instantiation

- packages/teuchos/core/src/Teuchos_CompilerCodeTweakMacros.hpp
Display code fragments in the proper code environment within Doxygen.
Now, code fragment looks like:
Local build of `Teuchos`' Doxygen works and was used to generate the screenshot given above.
> Teuchos: proper rendering of code examples in Doxygen html page

- packages/percept/CMakeLists.txt
@trilinos/percept
The current install of percept does not put the header files in their correct directories. This fix does this using the top level CMakeLists.txt file.
> Percept: Fix install paths for headers

- cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake
GCC 4.8.4 had flags set for:
- OpenMP = ON
- Tpetra INTA Serial = ON
- Build Share Libs = OFF
Since GCC 4.8.4 was removed as the PR testing scheme changed to support C++14, these flags will be placed in the GCC 8.3.0 PR build.
Related to #6968
This has been tested by building this branch with the GCC 8.3.0 PR build manually.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-lostflags-test-Trilinos_pullrequest_gcc_8.3.0-2722&field2=buildstamp&compare2=63&value2=Experimental)
> Add flags left behind in GCC 4.8.4 when moving to C++14

- packages/muelu/research/regionMG/src/SetupRegionHierarchy_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionMatrix_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionSmoothers_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionUtilities.hpp
- packages/muelu/research/regionMG/src/SetupRegionVector_def.hpp
- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
Removes the old std:vectors used to handle multiple regions per rank, since multiple regions per rank is not currently supported and will not be done using these vectors in the future.
regionMG tests pass and have the same result as before.
> MueLu: regionMG remove multiple regions per proc std::vector

- packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
- packages/muelu/src/MueCentral/MueLu_VerbosityLevel.cpp
- packages/muelu/src/MueCentral/MueLu_VerbosityLevel.hpp
Print individual levels with data pointers during setup.  This is useful for developers.
useful for MueLu developers
N/A
Adds a new verbosity level, `developer`.  This is also part of the `extreme` verbosity level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/trilinos/trilinos/8330)
> MueLu: option to print level data info

- packages/muelu/test/unit_tests/RegionMatrix.cpp
- packages/muelu/test/unit_tests/RegionRFactory.cpp
- packages/muelu/test/unit_tests/RegionVector.cpp
Fix compilation and test execution for `-D MueLu_ENABLE_Experimental:BOOL=ON`.
In particular, the region unit tests needed to be adapted to the removal of the `std::vector` clutter stemming from the abandoned "group" concept (c.f. PR #8319).
* Follows PR #8319
Related to an ASCR project by @rstumin, @lucbv 
Region unit tests are building and passing again.
> MueLu: fix region unit tests

- packages/xpetra/CMakeLists.txt
We don't have to exclude the directory `src/test/BlockedCrsOperator`, since it does not exist.
n/a.
Build and existing tests pass.
> Xpetra: remove obsolete CMake commands

- packages/sacado/src/CMakeLists.txt
- packages/sacado/src/Sacado.hpp
- packages/sacado/src/Sacado_DynamicArrayTraits.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Atomic.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_MathFunctions.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_ViewFad.hpp
- packages/sacado/test/UnitTests/CMakeLists.txt
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests.hpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Cuda.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Cuda_Hierarchical.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Cuda_Hierarchical_DFad.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Cuda_Hierarchical_SFad.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_NoViewSpec_Cuda.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_NoViewSpec_OpenMP.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_NoViewSpec_Serial.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_NoViewSpec_Threads.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_OpenMP.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Serial.cpp
- packages/sacado/test/UnitTests/Fad_KokkosAtomicTests_Threads.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_Cuda.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_Cuda_Hierarchical.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_Cuda_Hierarchical_SFad.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_NoViewSpec_Cuda.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_NoViewSpec_OpenMP.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_NoViewSpec_Serial.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_NoViewSpec_Threads.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_OpenMP.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_Serial.cpp
- packages/sacado/test/UnitTests/Fad_KokkosTests_Threads.cpp
This adds atomic implementations (for the new design) for more functions
of the form Kokkos::atomic_oper_fetch/Kokkos::atomic_fetch_oper where
oper is in {add, sub, mul, div, min, max}.  Since no architecture
supports atomic operations on objects as large as a typical AD type,
this duplicates the Kokkos implementation for arbitrarily large types,
which really uses locks instead of atomics (the default Kokkos
implementation doesn't work directly because the types of the two
arguments are often different).
@jewatkins
> Sacado:  Add atomic implementations for +,-,*,/,max,min

- cmake/tribits/ReleaseNotes.txt
- cmake/tribits/core/package_arch/TribitsGlobalMacros.cmake
- cmake/tribits/doc/build_ref/TribitsBuildReferenceBody.rst
- cmake/tribits/doc/developers_guide/TribitsDevelopersGuide.rst
This brings in an updated TriBITS snapshot primarily for updating the ETI default from OFF to ON.  (See https://github.com/TriBITSPub/TriBITS/pull/336).
This also brings up TriBITS updates for:
* TriBITS PR https://github.com/TriBITSPub/TriBITS/pull/324 (trilinos/Trilinos#7642)
* TriBITS commit TriBITSPub/TriBITS@8d696d0
I passed the TriBITS test suite as recorded in TriBITSPub/TriBITS@5e674ad.  Otherwise, this is one-line changes to TriBITS functionality (i.e. ETI default from 'OFF' to 'ON').  But since all of the Trilinos PRs and all of the ATDM Trilinos builds and every customer I know about all explicitly enabled ETI, this will not likely impact any important builds of Trilinos.  (This really just makes Trilinos easier to build for new Trilinos users.)
> Change Trilinos/TriBITS default of ETI to ON (#8130)

- packages/intrepid/src/Shared/Intrepid_BurkardtRulesDef.hpp
- packages/intrepid/src/Shared/Intrepid_PointToolsDef.hpp
- packages/intrepid/src/Shared/Intrepid_PolylibDef.hpp
- packages/intrepid2/src/Shared/Intrepid2_PointToolsDef.hpp
- packages/rythmos/test/ConvergenceTest/Rythmos_ConvergenceTestHelpers.cpp
- packages/sacado/test/tradoptest/tradoptest_47.cpp
This TriBITS-distributed file seems to have been necessary at some point in the distant past for successful Windows builds, but it now causes build errors:
```
D:\nfr\scale\TriBITS\tribits\win_interface\include\winmath.h(155): error: function "tgammal" has alread
inline long double tgammal(long double z){
```
Without the winmath includes, Intrepid successfully builds on VS2015 (with an older Trilinos version) and VS2017.
Building on Windows with newer versions of Visual Studio.
> Windows: remove obsolete winmath.h

- packages/ifpack2/src/Ifpack2_BlockRelaxation_decl.hpp
- packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_def.hpp
- packages/muelu/src/Graph/UncoupledAggregation/MueLu_UncoupledAggregationFactory_kokkos_def.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
@trilinos/ifpack2 @trilinos/muelu
I'd like to collect more timing/profiling data from muelu and ifpack2 for Albany Land Ice performance tests. This adds timers to the muelu ifpack2 smoother and the ifpack2 BlockRelaxation class. The timers I added to the BlockRelaxation class follow the same convention used in the Relaxation class.
I also removed some quotation marks from muelu timers because they were causing issues with the kokkos chrome tracing tool.
@mperego
> Ifpack2/MueLu: Add timers

- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
- packages/tpetra/core/src/Tpetra_DirectoryImpl_decl.hpp
- packages/tpetra/core/src/Tpetra_DirectoryImpl_def.hpp
Some functions in FixedHashTable assumed UVM.  This commit follows what @MicheldeMessieres did in #8104 by adding mirror views.  @MicheldeMessieres did suggest in a code comment that we might want an alternative solution to host copies, but this does get more tests passing with no UVM.
* Closes #8261
* Related to #8209
Previously failing tests that now pass without UVM are:
* TpetraCore_Map_Bug2431_MPI_4
* TpetraCore_Issue_607_MPI_4
* TpetraCore_Map_Bug5822_2_MPI_2
* TpetraCore_Map_Bug6051_MPI_2
* TpetraCore_CooMatrix_MPI_2
* TpetraCore_Map_OneToOne_MPI_2
> Tpetra: Fix some illegal device accesses in FixedHashTable

- packages/zoltan/doc/Zoltan_html/Zoltan.html
- packages/zoltan/doc/Zoltan_html/Zoltan_FAQ.html
- packages/zoltan/doc/Zoltan_html/Zoltan_bugreport.html
- packages/zoltan/doc/Zoltan_html/Zoltan_cite.html
- packages/zoltan/doc/Zoltan_html/Zoltan_phil.html
- packages/zoltan/doc/Zoltan_html/Zoltan_pubs.html
- packages/zoltan/doc/Zoltan_html/dev_html/dev.html
- packages/zoltan/doc/Zoltan_html/ug_html/ug.html
The classic 1400 download page is being retired.  The Zoltan stand-alone downloads have moved to SNL's github space.
This PR updates the links on Zoltan's webpages.
> zoltan: 1400 download page is being retired

- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
- packages/panzer/disc-fe/src/Panzer_PointValues2.cpp
- packages/panzer/disc-fe/test/core_tests/point_values2.cpp
In debug builds, IntegrationValues2 and PointValues2 object files were taking multiple hours to compile. 
Fixes #7532
All regression tests use integration and (optionally) point values. PointValues has its own unit test as well.
> Panzer: speed up cuda builds of IntegrationValues and PointValues

- packages/tpetra/core/src/Tpetra_Details_getEntryOnHost.hpp
- packages/tpetra/core/test/Utils/getEntryOnHost.cpp
Similar to existing `getEntryOnHost`, but allows us to bring up more than one value at a time for efficiency in cases when we know for sure we need multiple consecutive values from a device view.
Added two new unit tests for the new function `getEntriesOnHost`.  Also refactored the existing test for `getEntryOnHost` for clarity.
> Tpetra:  add getEntriesOnHost

- packages/muelu/research/regionMG/test/structured/CMakeLists.txt
@pohm01 
This cuts the time down for `MueLu_Structured_Region_Linear_R_Elasticity3D_Tpetra_MPI_4` in a debug build from 48 seconds to 15 seconds.
* Part of #8374 
I ran `ctest -R "Structured_Region_Linear_R_Elasticity3D_Tpetra"` to confirm that it speeds this test up.
> MueLu: Reduce the size of an elasticity test to speedup the testsuite

- .github/workflows/stale.yml
See #8306 for more information about this work.
This PR pulls in the initial github runner script that will mark issues and PR's as stale after 365 days of inactivity and then close them after another 30 days from being marked for closure.
I've been testing this out in a test repository at https://github.com/william76/workflowTest/
This is in **debug mode** (`debug-only: true`) currently so it should not actually affect any issues or PR's. We should get this in place so we can watch what it does in our repository before we enable it.
> Framework: Add GitHub Actions script to close stale issues and PR's

- cmake/std/atdm/apps/sparc/SPARCMiniTrilinosPackagesList.cmake
- cmake/std/atdm/cee-rhel6/environment.sh
- cmake/std/atdm/utils/atdm_config_helper_funcs.sh
This is a first set of changes to the ATDM Trilinos configuration to support having the SPARC TPL installer.
The commits and the changes should be self explanatory.
The controlling story for this in [ATDV-408](https://sems-atlassian-srn.sandia.gov/browse/ATDV-408).
More PRs after this one will be created to finish out  ADV-408.
This was tested locally on the CEE RHEL7 machine 'ceerws1113' with a branch of the SPARC TPL installer and testing against SPARC locally.  For details, see  [ATDV-408](https://sems-atlassian-srn.sandia.gov/browse/ATDV-408).
ToDo: I will merge this branch into 'atdm-nightly-manual-updates' so that this will run in the ATDM Trilinos builds posting to CDash.
> First set of changes to facilitate adoption of ATDM Trilinos configuration into SPARC TPL installer (ATDV-408)

- packages/sacado/src/KokkosExp_View_Fad.hpp
- packages/sacado/src/KokkosExp_View_Fad_Contiguous.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_StaticFixedStorage.hpp
* Allow assignments of the form `View<Fad**> = View<Fad*[n]>`
* Fix `create_mirror()` for `LayoutStride`
* Order value after derivative array in new design SFad (as it was in
the old design) to be consistent with ordering in `View<Fad*>` and allow
reinterpret cast of `View<SFad<double,N>*>::data()` to `SFad<double,N>*`.
> Sacado:  A few fixes for converting SPARC to use the Sacado View spec.

- packages/muelu/example/basic/Simple.cpp
- packages/muelu/example/basic/Stratimikos.cpp
- packages/muelu/test/scaling/Driver.cpp
- packages/muelu/test/scaling/MatrixLoad.hpp
- packages/muelu/test/scaling/MatvecKernelDriver.cpp
- packages/muelu/test/scaling/SpMVPerformance.cpp
This is useful when the coordinate map doesn't match the rowmap of the matrix, as is the case for "number of equations" > 1.
> MueLu: Add option to read coordinate map to Driver

- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer_Zoltan.hpp
Fixed case of parameter.
Sigh.  Teuchos parameters are still case sensitive, after all these years.
Tested on mac with clang
> Zoltan2 Fixed case of Teuchos parameter

- packages/zoltan2/core/src/models/Zoltan2_GraphModel.hpp
@ibogle detected an overflow in the edge counter in GraphModel.
ecnt type should be offset_t instead of lno_t.
We want to work with large irregular graphs.
Tested on cee-lan
> zoltan2:  fix edge cnt overflow in GraphModel

- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorerUtils.hpp
- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer_Zoltan.hpp
- packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp
#8356 #8411 #8416 
The TpetraCrsColorer should work with Domain and Range maps that are not the default Trilinos contiguous map.
This PR re-enables the tests that use cyclic Domain and Range maps.
This PR changes the Range map used by the transpose_graph when bipartite symmetrization is used.
Normally, for a transpose graph, we'd use
-  original matrix's RangeMap as the DomainMap, and
-  original matrix's DomainMap as the RangeMap.
Moreover, we're not doing SpMV with the transpose graph, so
you might think we wouldn't care about RangeMap and DomainMap.
But we DO care, because exportAndFillCompleteCrsGraph uses the
shared (overlapped) transpose matrix's RangeMap as the RowMap of the
transpose matrix, while the Zoltan callbacks are assuming the
transpose matrix's RowMap …
> Zoltan2:  fix map used for transpose_graph in TpetraCrsColorer

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
Host function insertCrsIndices should not use device memory 
Testing on ride
> Tpetra:  wrong memory space used for host function

- packages/amesos2/src/Amesos2_Superludist_TypeMap.hpp
Fixes compiler errors on systems using superlu_dist tpl major version 4
Confirmed this resolves compilation errors on weaver testbed with devpacks loading superlu_dist v. 4.3
> amesos2: guard include file based on slu_dist version

- cmake/std/sems/PullRequestClang10.0.0TestingEnv.sh
- cmake/std/sems/PullRequestClang7.0.1TestingEnv.sh
- cmake/std/sems/PullRequestClang9.0.0TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.8.4TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnvSERIAL.sh
- cmake/std/sems/PullRequestGCC7.2.0SerialTestingEnv.sh
- cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh
- cmake/std/sems/PullRequestGCC8.3.0TestingEnv.sh
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
With the updates to the PR drivers, the scripts to [reproduce PR errors][1] have become outdated. Especially where Python has been concerned. The main problem it appears from #8429 is that these scripts encounter a problem trying to load the right version of Python which conflicts with the work we put in to remove the use of Python 2.x from our PR scripts.
One problem is that loading the SEMS boost module also loads the `sems-python/2.7.x` module as a side-effect, so when we tried to load a Python 3.x module we got conflicts. 
I went in and modified the non CUDA scripts to perform a `module purge` in the beginning as well as a `module unload sems-python` before we load`sems-python/3.5.2`.  
* Related to #8429 
Ran tests on a RHEL COE system using a …
> Issue 8429

- packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_Vector_decl.hpp
- packages/tpetra/core/src/Tpetra_Vector_def.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
* Change behavior of replaceLocalValue/sumIntoLocalValue to call modify_host and sync_host internally, which feels safer for users.
* Remove a modify_device call inside multiVectorSingleColumnDot (since a dot product shouldn't change the values of the input vectors).
* Also fixes some const inconsistencies and updates some debug ifdefs to use the Behavior class instead.
* Closes #8361 
* Related to #8209 
MultiVector unit tests now passing in a non-UVM build on ascicgpu24.
> Tpetra: Fix modify/sync issues in MultiVector and unit tests

- packages/kokkos/core/src/impl/Kokkos_ViewMapping.hpp
Hotpatch of PR kokkos/kokkos#3422 by @masterleinad
Apply patch from kokkos/kokkos#3422 to silence -Wextra messages as required for Sierra project
CC: @mwglass
> kokkos: Replace enums in Kokkos_ViewMapping.hpp

- .github/workflows/stale.yml
This PR enables the Issue/PR autocloser action for Trilinos.
* Closes #8306
See #8306 for detailed information.
> Framework: Enabling the 'autocloser' github actions script

- packages/intrepid/src/Discretization/Basis/Intrepid_HDIV_TRI_In_FEMDef.hpp
Note: this regards Intrepid, *not* Intrepid2.  Since there is no intrepid team as such, sending to intrepid2.
Fixes a bug in face tag initialization for high-order H(div) Triangle elements; some face tag entries were left uninitialized.  This was exhibiting as a hang during tag initialization for a Camellia user, when attempting to use a degree-3 H(div) triangle basis.
> Intrepid: fix bug in face tag initialization for high-order H(div) Triangle elements.

- packages/PyTrilinos/cmake/FindMpi4Py.cmake
This is a small PR to update the FindMpi4Py.cmake to support Python 3.
> PyTrilinos: Update FinMpi4Py.cmake to support Python 3

- packages/panzer/disc-fe/src/Panzer_TpetraVector_ReadOnly_GlobalEvaluationData_impl.hpp
The empire sync with Trilinos failed with launch blocking off due to a single panzer test for the GED accessor. Turned out to be a race condition that needed fencing.
Fixes EMPIRE Trilinos update.
Covered by the test: ```PanzerDiscFE_LinearObjFactory_Tests_MPI_2```
> Panzer: fix race condition with launch blocking off in GED accessor.

- .github/workflows/stale.yml
Reduced the rate limiter for the issue/pr auto closer from 100 to 50 to reduce the # of hits it makes against the Github access rate.  @allevin noted to us that Trilinos was hitting the rate limit today, so in case our action script is the culprit, I'll cut its rate in half.
The script runs at 12:00 AM UTC which is around 5 or 6 AM mountain time, depending on whether or not we're in DST. I think right now it's running at 5am our time so if this is the culprit, we would see the rate limit happening sometime within an hour of this script running until Github clears the count.
> Framework: Reduce rate limit for stale job actionscript

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.hpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
- packages/panzer/adapters-stk/test/stk_interface_test/tPamgenMeshFactory.cpp
@rppawlo 
Querying mesh family tree information from the underlying uniformly refined PerceptMesh object will allow for more advanced solving and preconditioning strategies, such as the region multigrid approach.
It builds and 125/125 tests pass on my workstation.
Ideally the `keepPerceptData` test would also check that the "Keep Percept Parent Elements" flag is working properly. Currently the lines (L358 and L382 in tPamgenMeshFactory.cpp) are commented out because I wasn't able to find a nice and simple command to do so. Perhaps @bricar could provide a suggestion?
> Panzer STK: Add functionality and tests for querying the underlying PerceptMesh

- packages/kokkos-kernels/src/sparse/KokkosSparse_spadd.hpp
Remove static constexpr member variables from SpADD functors.
In official C++ pre 17, these need out-of-class definitions just like
non-constexpr static members, but I didn't add them here.
GCC/Clang let this work anyway, but XL goes by the
standard so this fixes building with XL.
Here's what I don't understand: Kokkos_ArithTraits.hpp and KokkosSparse_gauss_seidel_impl.hpp both also have static constexpr member variables, but those didn't cause linker errors with XL. They also didn't show up as symbols in executables, whereas this "ORDINAL_MAX" does. Not sure what's going on, but I didn't do a workaround for those since they aren't causing problems.
* Closes #8418 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
I …
> KokkosKernels: remove static constexpr member (#8418)

- packages/ifpack2/src/Ifpack2_AdditiveSchwarz_def.hpp
- packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
- packages/ifpack2/src/Ifpack2_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Amesos2Wrapper_def.hpp
- packages/ifpack2/src/Ifpack2_Details_DenseSolver_def.hpp
- packages/ifpack2/src/Ifpack2_Details_TriDiSolver_def.hpp
- packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
- packages/ifpack2/src/Ifpack2_Hiptmair_def.hpp
- packages/ifpack2/src/Ifpack2_Hypre_def.hpp
- packages/ifpack2/src/Ifpack2_ILUT_def.hpp
- packages/ifpack2/src/Ifpack2_RILUK_def.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
- packages/ifpack2/src/supportgraph/Ifpack2_SupportGraph_def.hpp
- Don't do e.g. "ApplyTime_ += timer->totalElapsedTime()" since this
will re-count time from all previous applies.
- Replace totalElapsedTime() with a wallTime() interval for this
instead, since if two preconditioner objects A and B are used in
the same StackedTimer scope, B's times will include A's
times.
Here's an example output from before these changes, showing both issues. I looped over a setup+solve 3 times in the Ifpack2+Belos driver:
```
Every proc reading parameters from xml_file: test_MTGS_calore1_mm.xml
Matrix Market file for sparse matrix A: /ascldap/users/bmkelle/MatrixCollection/bodyy5.mtx
Configuring, initializing, and computing Ifpack2 preconditioner
Time Init: 0.0451295
Finished computing Ifpack2 preconditioner
Time (s): 0.00254004
Converged in 196 iterations. …
```
> Ifpack2: fix timers

- cmake/std/pr_config/pullrequest.ini
- cmake/std/trilinosprhelpers/setenvironment/SetEnvironment.py
- cmake/std/trilinosprhelpers/setenvironment/unittests/setenvironment_config.ini
- cmake/std/trilinosprhelpers/setenvironment/unittests/test_SetEnvironment.py
The cycle-detection logic in the PR driver `setenvironment` module had a minor bug that resulted in an overly aggressive 'cycle prevention' mode.
For example, section dependencies like this would be blocked:
```
A -> B -> C -> B
```
but we also blocked this:
```
A -> B -> C
A -> B
```
This fixes the issue by popping off the sections from the 'seen list' as we pop out of scope during the recursive module that scans through the configurations.
This generally didn't affect any of our configurations but I could see a scenerio where we do something like this:
```ini
[MODULE-MANUAL-CONFIG]
setenv ENVVAR1: foo
setenv ENVVAR2: bar
setenv ENVVAR3: baz
[SEMS-DEFAULT]
use MODULE-MANUAL-CONFIG:
[SOME_BUILD_CONFIG]
use SEMS-DEFAULT:
use MODULE-MANUAL-CONFIG:
```
Generally, I think …
> Framework: Bugfix for cycle detection PR configurations

- packages/tpetra/core/test/Block/BlockMultiVector.cpp
These tests operate on primarily on host, but without explicit sync/modify calls, data added on host using non-const Views handed out from the BlockMultivector was being overwritten.  Also, in the Import test, without X being marked modify_host after modifications were made to a host view of X's data, the correct data was not brought over to Y.
* Related to #8209
Now passing in a non-UVM build on an x86/V100 platform (ascicgpu).
> Tpetra:  Add missing syncs/modifies in BlockMultiVector unit tests

- packages/thyra/adapters/tpetra/src/Thyra_TpetraLinearOp_def.hpp
Two Teko tests are failing with CUDA_LAUNCH_BLOCKING=OFF. This fixes the tests by adding required fences in the Thyra/Tpetra adapters.
Closes #8497 
Tests are covered by:
- Teko_testdriver_tpetra_MPI_1
- Teko_testdriver_tpetra_MPI_4
> Teko: fix tests for CUDA_LAUNCH_BLOCKING=OFF

- cmake/std/PullRequestLinuxCuda10.1.105TestingSettings.cmake
- cmake/std/pr_config/pullrequest.ini
Environment change to `setenv CUDA_LAUNCH_BLOCKING: 0`
This change does cause two @trilinos/teko tests to fail, so those have been turned off until they can be adjusted.
Issue #8396
These changes have been run with the Jenkins job, successful with the two tests turned off.
[CDash Results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cuda_10.1.105&field2=buildname&compare2=63&value2=launchblocking&field3=buildstamp&compare3=63&value3=Experimental)
> Turn CUDA Launch Blocking OFF

- .github/workflows/stale.yml
Changing the CRON for the issue autocloser to `0 12 * * 0,6` which will make it run around 5 or 6am mountain time (depending on daylight savings) on Saturday and Sunday only.
Reduces the frequency the autocloser runs, from once daily to just once on Saturday, Sunday, and Wednesday.
* Closes #8509
> Framework: Set issue autocloser to weekends

- doc/build_ref/TrilinosBuildReferenceTemplate.rst
Trivial fix related to #7376.  Fixes:
* https://docs.trilinos.org/files/TrilinosBuildReference.html#enabling-and-viewing-build-statistics
> Fix typo messing up formatting (#7376)

- packages/muelu/src/CMakeLists.txt
#8155 didn't actually make the regionMG header files accessible to the rest of MueLu or to outside packages, although I thought it did. This PR might be a silly way to do things since I sometimes don't fully understand what CMake is doing, but it adds the regionMG headers in the CMakeLists file in `muelu/src` if `${PACKAGE_NAME}_ENABLE_Experimental`, and I believe my testing is sufficient to say it works.
Of course, there is no need to have the headers accessible to other MueLu functionality, since we wouldn't base production code on experimental research code, but it allows for the headers to be accessed within TrilinosCouplings, which is what I care about for the region multigrid & panzer code.
I don't think this affects anything. Everything builds fine in debug mode, …
> MueLu: Add research/regionMG/src to include directories if ENABLE_Experimental

- cmake/std/PullRequestLinuxCuda10.1.105TestingSettings.cmake
This will turn 3 Teko tests on for the CUDA 10.1.105 build.
- `ModALPreconditioner_MPI_1`
- `testdriver_tpetra_MPI_1`
- `testdriver_tpetra_MPI_4`
Closes #8497
I manually ran a build with 4 tests turned on. These 3 now finish successfully.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ride17&field2=buildname&compare2=61&value2=PR-teko_tests_ON-test-Trilinos_pullrequest_cuda_10.1.105-67&field3=buildstamp&compare3=61&value3=20201221-1656-Experimental)
> Turn Teko tests back on.

- packages/muelu/test/unit_tests/RegionMatrix.cpp
UnitTestsRegion does not pass with AMGX or Cuda builds because of a single entry that is barely outside the acceptable tolerance. This should fix those tests.
Also, @lucbv suggested using Xpetra to hide Kokkos goo at a later date.
> MueLu: Update UnitTestRegion tolerance for Elas3D so GPU tests pass

- packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_decl.hpp
- packages/muelu/adapters/stratimikos/Thyra_MueLuRefMaxwellPreconditionerFactory_def.hpp
- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Misc/MueLu_RAPFactory_def.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
- packages/xpetra/src/Headers/Xpetra_UseShortNamesScalar.hpp
- packages/xpetra/src/Operator/Xpetra_EpetraOperator.hpp
- packages/xpetra/src/Operator/Xpetra_TpetraHalfPrecisionOperator.hpp
- packages/xpetra/src/Utils/ClassList/SC-LO-GO-NO.classList
- packages/xpetra/src/Utils/ForwardDeclaration/Xpetra_TpetraHalfPrecisionOperator_fwd.hpp
@trilinos/muelu @trilinos/xpetra 
- Ifpack2Smoother: Only call `SetPrecParameters` when they actually change
- RAPFactory: Fix repair threshold parameter when Scalar != double
- RefMaxwell: When requested, use average edge length for nullspace normalization
- Xpetra: Add an operator that wraps an operator with ScalarTraits<Scalar>::halfPrecision into a Scalar one.
- Allow running RefMaxwell in half precision through Stratimikos interface
Let's see what the AT thinks of this..
> MueLu: Mixed precision RefMaxwell

- packages/sacado/src/Sacado_DynamicArrayTraits.hpp
- packages/sacado/test/GTestSuite/CMakeLists.txt
Fixes build errors when compiled with Kokkos or Teuchos disabled
> Sacado:  Fix two errors when configured without Kokkos or Teuchos.

- packages/sacado/src/Sacado_Fad_Ops.hpp
- packages/sacado/src/new_design/Sacado_Fad_Exp_Ops.hpp
Visual Studio wants 'using Sacado::if_then_else' in several places it
shouldn't be required.  This adds them anyway to fix errors with that
compiler.
> Sacado:  Add 'using Sacado::if_then_else' in several places for MS Visual Studio

- cmake/ctest/drivers/atdm/sems-rhel7/local-driver.sh
This fixes the inner git fetch errors reported in [ATDV-416](https://sems-atlassian-srn.sandia.gov/browse/ATDV-416).
This fixes the ATDM Trilinos 'sems-rhel7' builds which have been offline for weeks.
I verified this manually by running:
* https://jenkins-srn.sandia.gov/view/Trilinos%20ATDM/job/Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release-debug/1/console
and by locally running:
```
$ cd /scratch/rabartl/Trilinos.base/BUILDS/ATDM/SEMS-RHEL7/CTEST_S/
$ ./ctest-s-local-test-driver.sh sems-rhel7-clang-7.0.1-openmp-shared-release  # Killed it after a few seconds!
$ grep Trilinos_REPOSITORY_LOCATION Trilinos-atdm-sems-rhel7-clang-7.0.1-openmp-shared-release/smart-jenkins-driver.out
-- ENV_Trilinos_REPOSITORY_LOCATION='git@github.com:trilinos/Trilinos.git'
-- …
```
> Switch to SSH github authentication for inner Trilinos repo to fix 'sems-rhel7' builds (ATDV-416)

- packages/shylu/shylu_node/tacho/src/impl/Tacho_Solver_Impl.hpp
@crdohrm reports warning of uninitialized variables from his code. This fixes the uninitialized member varialbes.
This is requested from the stakeholder.
Locally I tested on my MBP before pushing it for the PR test.
> Tacho - remove uninitialized variable warnings

- cmake/std/atdm/ats2/environment.sh
Via atdm-nightly. See [cdash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-01-13&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=ats2) for results.
> ATDM/ats2: Update to CMake 3.18

- packages/intrepid2/unit-test/MonolithicExecutable/AnalyticPolynomialsMatchTests.cpp
Intrepid2: Fix #8516.
Eliminated a couple of test cases (OPERATOR_D9, OPERATOR_D10) in 3D tests (unit test "HierarchicalNodalComparisons") during CUDA debug builds, due to occasional allocation (out-of-memory, presumably) errors when testing with Fad types.
Addresses #8516.
N/A (changes to tests).
> Intrepid2: Fix #8516.

- packages/intrepid2/src/Cell/Intrepid2_CellGeometry.hpp
- packages/intrepid2/src/Cell/Intrepid2_CellGeometryDef.hpp
- packages/intrepid2/src/Shared/Intrepid2_Data.hpp
Intrepid2: resolve warnings under CUDA.
As part of the warning resolution, fixed some issues with the safety of using CellGeometry objects on device under CUDA.
Some warnings issued during CUDA debug builds (see #8554) indicated that lambda captures, etc. of CellGeometry as implemented could lead to indeterminate behavior on device, due to host code being called during construction and destruction of the device copy of the objects.  This PR resolves that by isolating the host-only "members" of CellGeometry in a separate, static class.
Tested by the CellGeometry group of unit tests in Intrepid2, among other unit tests.
> Intrepid2: resolve warnings under CUDA.

- cmake/std/atdm/ATDMDisables.cmake
@eric-c-cyr 
EMPIRE’s heading in the direction of removing its use of Tempus.  This PR is to make that change to the ATDM DevOps infrastructure that EMPIRE uses, and also to coordinate making this change with corresponding changes on the EMPIRE side.
> **Note:**  This isn’t intended to be merged soon.
@eric-c-cyr, I think this might be all that’s needed on the Trilinos side of things.  On the EMPIRE side, I don’t know what all will be required, but I assume you do.  To make the changes, we’ll need to:
* Test this branch with corresponding branches in the EMPIRE repositories.
* Merge this branch into `EM-Plasma/Trilinos:develop`, while simultaneously merging the corresponding branches into `develop` in the EMPIRE repositories.
* Wait for EMPIRE’s D2M to get those changes into `master`.
* …
> Disable Tempus for EMPIRE

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Fix a compiler warning about an unused local `typedef` of `MultiVector`
Build and existing tests pass locally. No new tests necessary, as no functionality has been added.
> Tpetra: fix warning about unused local typedef

- packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.cpp
- packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.hpp
@rppawlo this is so you can use team and vector size of 123, 321 and it will round down and limit by max values.
> Added code which rounds down the vector length

- packages/nox/src-loca/src-tpetra/LOCA_Tpetra_ConstraintModelEvaluator.cpp
- packages/nox/test/tpetra/ME_Tpetra_1DFEM_def.hpp
- packages/nox/test/tpetra/tTpetra_1DFEM_ME_UnitTests.cpp
Fixes Tpetra Householder constraints case when ME is wrapped in a decorator.
Fixes issue in Charon.
> LOCA: Update householder constraints for case with model evaluator decorator

- packages/muelu/src/Rebalancing/MueLu_Zoltan2Interface_def.hpp
- packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgParMETIS.hpp
- packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgQuotient.hpp
- packages/zoltan2/core/src/algorithms/partition/Zoltan2_PartitioningAlgorithms.hpp
- packages/zoltan2/core/src/models/Zoltan2_CommGraphModel.hpp
- packages/zoltan2/core/src/models/Zoltan2_Model.hpp
- packages/zoltan2/core/src/problems/Zoltan2_PartitioningProblem.hpp
- packages/zoltan2/core/src/problems/Zoltan2_Problem.hpp
- packages/zoltan2/test/core/partition/CMakeLists.txt
- packages/zoltan2/test/core/partition/partitioning1.cpp
This PR adds two major contributions in the following files: 
1) model/Zoltan2_CommGraphModel.hpp
CommGraphModel (communication graph model) creates a graph representing the communication topology of the MPI ranks for a given XpetraCrsGraphAdapter object. If there are n MPI ranks in the given communicator, then this model contains n vertices so that each vertex represents an MPI rank. If rank i sends a message to rank j (during the mat-vec on the matrix corresponding to the given adapter), then there is a directed edge from vertex i to vertex j in the graph. The weight of the edge is the number of nonzeros that cause that message. The weight of vertex i is the number of nonzeros …
> Zoltan2: Add quotient algorithm and communication graph model

- cmake/std/trilinosprhelpers/TrilinosPRConfigurationBase.py
The autotester driver does some filtering on whether or not it prints out the _value_ of an envvar in the logs because some envvars have a lot of content that's not relevant. Generally it prints out the envvar names, but not the value unless we include a partial string match to the envvar name in `TrilinosPRConfigurationBase.py`.
We missed adding envvars such as `CXX`, `CC`, `FC`, etc. to the list of envvars we should fully print out in the logs.
This PR addresses this by adding the flags `CC`, `CXX`, `F77`, `F90`, `FC`, `MODULESHOME` so that their values will be printed out to the console during a PR run in the future.
- Related to #8401
- Related to #8520
- Related to #8521
> Framework: Expand the envvars that get fully printed out in PR's

- packages/tpetra/core/src/Tpetra_replaceDiagonalCrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_replaceDiagonalCrsMatrix_def.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_ReplaceDiagonal.cpp
Tpetra's code to replace diagonal values assumed 1D row-wise distribution of the matrix.  It was incorrect when other distributions were used.   These changes fix replaceDiagonalCrsMatrix to remove the assumption of 1D row-wise matrix distribution.
These changes are needed to use Tpetra in Grafiki. Power-law matrices (e.g., social networks) perform better using 2D matrix distributions than 1D (row-wise) distributions.
* Closes 
* Blocks  #8472 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
@ndellingwood @seheracer 
Needed by #8472 
Added new test ReplaceDiagonalOverlapRowMap added to CrsMatrix_ReplaceDiagonal.cpp that creates 2D block-wise distribution of tridiagonal matrix and replace diagonal values with row's globalID.
Also …
> Tpetra:  enable ReplaceDiagonal to work for CrsMatrix with overlapped row map

- cmake/std/atdm/common/toss3/environment_tlcc2.sh
EMPIRE ran into a problem deploying on Chama, and the culprit looks like
it's using an older CMake version.  When the environment for Chama was
created, 3.12 was the best available, but now we can update to 3.19, so
we'll go ahead and do that.
Testing now.
> ATDM:  Update CMake on Chama to 3.19.1

- packages/teuchos/comm/src/Teuchos_TimeMonitor.cpp
Print the exception message coming out of the stacked timers, since it says which two timers are overlapping. This makes debugging a bit easier.
> Teuchos TimeMonitor: Print more info on overlapping timers

- packages/intrepid2/src/Discretization/Integration/Intrepid2_CubatureTensorDef.hpp
@mperego @kyungjoo-kim 
* closes #8614
Triggered by exception handling...
> intrepid2: fix clang warning autological overlap compare.

- cmake/std/atdm/ATDMDisables.cmake
> cmake/std/atdm: Disable Kokkos timing based test

- cmake/std/atdm/ATDMDisables.cmake
> cmake/std/atdm: Run Kokkos interOp tests in serial

- packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedGaussSeidelSmoother_def.hpp
- packages/muelu/src/Smoothers/BlockedSmoothers/MueLu_BlockedJacobiSmoother_def.hpp
- packages/muelu/test/unit_tests/Smoothers/BlockedSmoother.cpp
The logic with `InitialGuessIsZero` int BlockedGaussSeidel and BlockedJacobi smoothers resulted in the use of a solution from the previous V-cycle as an initial guess instead of an actual zero initial guess.
This also fixes a bug where BlockedJacobi would update the residual after each block, resulting in a Gauss-Seidel-like method.
Appears to resolve convergence issues discussed in:
rppawlo/DrekarBase#505
> MueLu: Fix BGS and Blocked Jacobi logic when InitialGuessIsZero

- packages/piro/src/Piro_PerformAnalysis.cpp
- packages/piro/test/CMakeLists.txt
- packages/piro/test/Main_AnalysisDriver_Tpetra.cpp
- packages/piro/test/MockModelEval_A_Tpetra.cpp
- packages/piro/test/MockModelEval_A_Tpetra.hpp
- packages/piro/test/MockModelEval_B_Tpetra.cpp
- packages/piro/test/MockModelEval_B_Tpetra.hpp
- packages/piro/test/_input_Analysis_ROL_Tpetra.xml
- packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective_SimOpt.hpp
- packages/rol/adapters/thyra/src/vector/ROL_HessianScaledThyraVector.hpp
- packages/thyra/core/src/support/nonlinear/model_evaluator/client_support/Thyra_ModelEvaluatorDelegatorBase.hpp
@mperego
@trilinos/rol 
This PR adds the capability to use a dot product which uses the Hessian w.r.t a parameter while using ROL with Thyra vectors.
The modifications included in this PR are:
- Thyra:
- `packages/thyra/core/src/support/nonlinear/model_evaluator/client_support/Thyra_ModelEvaluatorDelegatorBase.hpp` has been modified to enable to call the member function `create_hess_g_pp` of the underlying model.
- ROL:
- `packages/rol/adapters/thyra/src/vector/ROL_HessianScaledThyraVector.hpp` has been added. This header defines the Thyra vector which the dot product is scaled by the Hessian.
- `packages/rol/adapters/thyra/src/function/ROL_ThyraProductME_Objective_SimOpt.hpp` has been updated to add the capability to evaluate the Hessian w.r.t a parameter.
- Piro:
- …
> Piro: add HessianScaledThyraVector to ROL adapters and use it in Piro_PerformAnalysis

- packages/phalanx/example/FiniteElementAssembly/FiniteElementAssembly.cpp
- packages/phalanx/src/Phalanx_DAG_Manager.hpp
- packages/phalanx/src/Phalanx_DAG_Manager_Def.hpp
- packages/phalanx/src/Phalanx_EvaluationContainer.hpp
- packages/phalanx/src/Phalanx_EvaluationContainer_Def.hpp
- packages/phalanx/src/Phalanx_FieldManager.hpp
- packages/phalanx/src/Phalanx_FieldManager_Def.hpp
Application requested ability to query information from DAG manager.
new code is tested in:
```phalanx/example/FiniteElementAssembly/FiniteElementAssembly.cpp```
> Phalanx: add queries to DAG Manager

- cmake/std/atdm/apps/empire/EMPIRETrilinosPackagesList.cmake
EMPIRE needs to turn Anasazi on in order to solve eigen systems to obtain TE and TM modes on surfaces.
Testing manually now.
> ATDM:  Turn Anasazi on for EMPIRE

- packages/minitensor/src/MiniTensor_Geometry.t.h
- packages/minitensor/src/MiniTensor_Mechanics.t.h
@trilinos/MiniTensor
@lxmota 
Fix warnings coming from KOKKOS_INLINE_FUNCTION markings on functions that use C++ STL constructs.
* Closes #8650
N/A
> MiniTensor: Fix inconsistent KOKKOS_INLINE_FUNCTION markings

- packages/tpetra/core/test/Block/BlockView.cpp
The BlockView.cpp test exercises LAPACK functions provided by Tpetra (GETF2, GETRS, etc.).
It had used Kokkos::Views declared using the device_type, but in truth, the tests run on host.  The device_type declaration was misleading (fake news) and didn't work without UVM.
This PR changes the view declarations to use HostSpace memory.
This test probably *should* exercise the Tpetra LAPACK implementations on device, since the intent of the functions likely is to be applied with parallelism over many small blocks.  Such an extension would be a nice addition to this test, but it is not provided in this PR.   This PR checks only the correctness of the functions for a single block.
Fixed while working on #8591 
CEE-LAN GPU machine, CUDA build, with and without UVM
> tpetra:  removed use of device_type in BlockView test

- CMakeLists.txt
- cmake/std/PullRequestLinuxIntel17.0.1TestingSettings.cmake
- cmake/std/PullRequestLinuxIntel19.0.5TestingSettings.cmake
- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestClang7.0.1TestingEnv.sh
- cmake/std/sems/PullRequestClang9.0.0TestingEnv.sh
- cmake/std/sems/PullRequestCuda10.1.105TestingEnv.sh
- cmake/std/sems/PullRequestCuda9.2TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.8.4TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnv.sh
- cmake/std/sems/PullRequestGCC4.9.3TestingEnvSERIAL.sh
- cmake/std/sems/PullRequestGCC7.2.0SerialTestingEnv.sh
- cmake/std/sems/PullRequestGCC7.2.0TestingEnv.sh
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
- cmake/std/sems/PullRequestPython2TestingEnv.sh
- cmake/std/sems/PullRequestPython3TestingEnv.sh
- cmake/std/sems/get_default_modules.sh
This is a Work in Progress.
This is part of Issue #8520 to prepare the way for upgrading the minimum CMake required version to 17.0.0
* Part of #8520
The PR updates will be tested through the usual PR driver.
The updates to the manual replication scripts will need to be tested manually.
This is due by January 29th, 2021.
These will need to be manually tested on an appropriate system.  See [Reproducing PR Testing Errors][1] for detailed instructions.
- ~~PullRequestClang7.0.1TestingEnv.sh~~
- ~~PullRequestClang9.0.0TestingEnv.sh~~
-  ~~PullRequestGCC4.8.4TestingEnv.sh~~
- ~~PullRequestGCC4.9.3TestingEnv.sh~~
- ~~PullRequestGCC4.9.3TestingEnvSERIAL.sh~~
- ~~PullRequestGCC7.2.0SerialTestingEnv.sh~~
- ~~PullRequestPython3TestingEnv.sh~~
Update: marked out .sh files that we …
> Framework: Preparation for CMake minimum required version update

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeHexMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
- packages/panzer/adapters-stk/test/stk_interface_test/tCubeHexMeshFactory.cpp
This PR improves the performance of CubeHexMeshFactory in two ways.  First, it replaces multiple calls to addEntityToEdgeBlock() 
with a single call to addEntitiesToEdgeBlock() that adds a vector of entities all at once.  The same is done for addEntityToFaceBlock().  Second, it groups multiple mesh modifications into a single block with only one call to beginModification() and endModification().
This could impact subclasses of CubeHexMeshFactory that call addSideSets(), addNodeSets(), addEdgeBlocks() and addFaceBlocks().  These methods now expect that beginModification() has been called externally prior to entry.  They also expect that endModification() will be called externally after exit.
This PR also adds a disable_subcells test to tCubeHexMeshFactory.  This test …
> Panzer: Improve the performance of the the CubeHexMeshFactory

- cmake/std/common.bash
- cmake/std/pr_python_test_driver.sh
- commonTools/framework/CMakeLists.txt
The pytest checker when we do the python tests returns a summary
line that is formatted like this:
All tests passed:
```
============================================= 36 passed in 0.79s =============================================
```
Some test(s) failed:
```
======================================== 1 failed, 35 passed in 0.80s ========================================
```
A regular expression that can match a testing scenerio where there are
zero failures might look like this:
`^=+ [0-9]+ passed in`
This can be tested at: https://regexr.com/
Get Pip Removed
-----------------
I also removed the `get_pip` bash function since it's not needed anymore since we removed Python2 based testing for the PR driver. The `get_pip` stuff isn't needed since we don't test Python2 anymore and our Python3 …
> Framework: Fix PyTest regex checker

- cmake/std/pr_config/pullrequest.ini
We missed setting `LDFLAGS=-lifcore` envvar in the push that fixed the trivial compilation of a fortran program with the intel compiler and cmake 3.17.x ... issue we had last week. 
Since the intel 19 compiler is only tested in the dev->master builds this got missed on our earlier PR.
* Closes #8669
* Relates to #8664
FYI @prwolfe @jwillenbring @ZUUL42 @e10harvey
> Framework: Issue 8669 - Fix CMake 3.17 bug with Intel 19 compiler

- packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HCURL.hpp
- packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HDIV.hpp
- packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HGRAD.hpp
Tried to pull these files into empire, but had compile failures. Unit tests probably are declaring "using namespace Intrepid2" to work around this.
> Intrepid2: fix namespaces in orientation tools

- cmake/std/PullRequestLinuxIntel19.0.5TestingSettings.cmake
- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
A previous PR had set this up for intel 17 and
subsequent testing showed a problem with intel 19
as well. This also adds the environment variables
to the evn.sh scripts for reproducing builds.
This is blocking develop->master promotions and will be needed in general.
> Add environment variable for intel configure with intel 19

- CMakeLists.txt
Updates the minimum CMake requirement for Trilinos to 3.17.0
- Part of #8401 
- Part of #8520
- Depends on #8521
> Framework: Update CMake minimum requirement to 3.17.x

- packages/ifpack2/src/Ifpack2_RILUK_def.hpp
- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
This PR is to fix two bugs reported by @vbrunini: (i) the RILUK preconditioner not taking the new matrix values when preconditioner->compute() is called in the reuse case; (ii) seg fault when dealing with empty matrix
Tests were performed on ```white``` with CTest. The two changes were confirmed fixing the bugs by @vbrunini .
> Ifpack2: Fix bugs in RILUK that not clearing old matrix values in reuse case and seg fault with empty matrix

- cmake/std/atdm/cee-rhel7/environment.sh
Trilinos now requires CMake 3.17 or greater
Part of #8675 
This updates the rhel7 cee environment to use a supported version of CMake.
> ATDM rhel7 cmake 3.19

- cmake/std/atdm/ats1/environment.sh
Related to #8599.
I tried this out and got similar results which crtrott reported:
```bash
export OMP_NUM_THREADS=8
srun "--mpi=pmi2" "--ntasks-per-node=8" "--ntasks" "1" "--hint=nomultithread" "-c 8" "KokkosContainers_UnitTest_Serial.exe"
<snip>
[==========] 28 tests from 1 test case ran. (74841 ms total)
[  PASSED  ] 28 tests.
srun "--mpi=pmi2" "--ntasks-per-node=8" "--ntasks" "1" "--hint=nomultithread" "-c 8" "KokkosContainers_UnitTest_OpenMP.exe"
<snip>
[==========] 28 tests from 1 test case ran. (245189 ms total)
[  PASSED  ] 28 tests.
```
> ATDM/ats1: Set OMP_NUM_THREADS=8 for KNL

- cmake/std/atdm/common/toss3/environment_new.sh
Trilinos now requires CMake 3.17 or greater
Part of #8675
This updates the toss3 environment to use a supported version of CMake. I based the version used on another environment file for this platform.
> Issue 8675 updating ATDM toss3 build to use CMake 3.19

- cmake/std/atdm/ats2/environment.sh
This is the remaining build that needs c++14 changes. The test build is at https://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=8638278 and has a single failure due to the new seacas pushed in #8637 
* Closes #6260 
* Is blocked by seacas build failure
> Environment and flags for getting c++14 build using xlC

- packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_OverlappingOperator_def.hpp
This PR adds an option to use Kokkos parallel-for for the local restriction (to avoid moving data between CPU/GPU)
I ran ctest shylu-dd/frosch on Vortex
> use Kokkos parallel-for for the local restriction

- cmake/std/atdm/cee-rhel7/environment.sh
- cmake/std/atdm/cts1empire/environment_new.sh
- cmake/std/atdm/van1-tx2/environment.sh
Related to #8675.
https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-02-03&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=sems-rhel7&field2=groupname&compare2=63&value2=Experimental
https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-02-03&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cts1empire&field2=groupname&compare2=63&value2=Experimental
https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-02-03&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=van1-tx2&field2=groupname&compare2=63&value2=Experimental
> ATDM: Upgrade to CMake 3.17+ and fix intel compiler checks 

- packages/tpetra/core/inout/Tpetra_DistributionLowerTriangularBlock.hpp
The LowerTriangularBlockOperator assumes that the matrix's Range and Domain map are the same.
This PR adds an error check to the operator's constructor to enforce the assumption.
@seheracer @ndellingwood 
Tested on mac with clang
> Tpetra: add error check to enforce assumption about maps

- cmake/std/atdm/contributed/weaver/environment.sh
Update contributed weaver script's cmake for nightly testing with kokkos and kokkos-kernels
> weaver: update cmake used in atdm/contributed env script

- cmake/std/atdm/cee-rhel7/environment.sh
Related to #8675 and caused by #8685.
https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-02-04&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=cee-rhel7&field2=groupname&compare2=63&value2=Experimental
The reason Sems-rhel7 builds were run in #8685 was due to running:
`nohup env Trilinos_PACKAGES=Kokkos,Teuchos,TrilinosATDMConfigTests ./ctest-s-local-test-driver.sh all`
instead of:
`nohup env Trilinos_PACKAGES=Kokkos,Teuchos,TrilinosATDMConfigTests ATDM_CTEST_S_DEFAULT_ENV=cee-rhel7-default ./ctest-s-local-test-driver.sh all`
> ATDM/cee-rhel7: Update LDFLAGS export

- cmake/ctest/drivers/atdm/ats2/local-driver.sh
- cmake/ctest/drivers/atdm/cee-rhel7/local-driver.sh
When running `env Trilinos_PACKAGES=Kokkos,Teuchos,TrilinosATDMConfigTests ATDM_CTEST_S_DEFAULT_ENV=cee-rhel7-default ./ctest-s-local-test-driver.sh` the mini builds produce:
```
CMake Error at /path/to/TribitsCTestDriverCore.cmake:1723 (MESSAGE):
ERROR: Both Trilinos_PACKAGES and Trilinos_PACKAGE_ENABLES_FILE cannot be
non-empty! Set one or the other to select the set of packages to be
processed/tested.
```
Paul and I saw this while working on the ats2 xl build.
https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=6129661&filtercount=1&showfilters=1&field1=groupname&compare1=63&value1=Experimental&filtercombine=and
https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&parentid=6129666&filtercount=1&showfilters=1&field1=groupname&compare1=63&value1=Experimenta …
> ATDM: Fix ats2 and cee-rhel7 drivers

- packages/panzer/adapters-stk/example/main_driver/energy-ss-blocked-tp.xml
- packages/panzer/adapters-stk/example/main_driver/energy-ss-tp.xml
- packages/panzer/disc-fe/src/Panzer_ModelEvaluator.hpp
- packages/panzer/disc-fe/src/Panzer_ModelEvaluator_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterDirichletResidual_BlockedTpetra_impl.hpp
Drekar users reported exception throw with a certain blocked dirichlet scatter use case. 
Fixed the issue.
The test energy-ss-blocked-tp.xml has been modified to cover this use case.
> Panzer fix block dirichlet scatter

- packages/tpetra/core/inout/MatrixMarket_TpetraNew.hpp
This PR fixes the error reported by @kddevin in the following tests:
157 - TpetraCore_MatrixMarket_Tpetra_CrsMatrix_Dist_BinaryPerProcess_simple_MPI_6 (Failed)
158 - TpetraCore_MatrixMarket_Tpetra_CrsMatrix_Dist_BinaryPerProcess_simple_MPI_10 (Failed)
The issue arises when `fread` tries to read `0` entries from the binary file. 
All of the BinaryPerProcess tests are passing:
```
Start 22: TpetraCore_MatrixMarket_Tpetra_CrsMatrix_Dist_BinaryPerProcess_simple_MPI_1
22/41 Test #22: TpetraCore_MatrixMarket_Tpetra_CrsMatrix_Dist_BinaryPerProcess_simple_MPI_1 ....   Passed    0.68 sec
Start 23: TpetraCore_MatrixMarket_Tpetra_CrsMatrix_Dist_BinaryPerProcess_simple_MPI_3
23/41 Test #23: TpetraCore_MatrixMarket_Tpetra_CrsMatrix_Dist_BinaryPerProcess_simple_MPI_3 ....   Passed …
```
> Tpetra: readPerProcessBinary: Do not read any nonzeros if nnz=0

- packages/intrepid2/src/Discretization/Basis/Intrepid2_BasisValues.hpp
- packages/intrepid2/src/Discretization/Integration/Intrepid2_CubatureTensor.hpp
- packages/intrepid2/unit-test/MonolithicExecutable/BasisValuesTests.cpp
By adding a constructor that allows a tensorial extension of an existing CubatureTensor object, we allow the use of CubatureTensor in dimensions beyond 3.  This has applications for space-time finite elements, as well as for Boltzmann models (which may be up to 6D).
Additionally, this PR includes a default constructor for BasisValues, which was missing.
Both CubatureTensor and BasisValues are tested by existing unit tests, as well as one new one that explicitly tests the new default constructor for BasisValues.
> Intrepid2: Allow CubatureTensor in more dimensions

- packages/kokkos-kernels/src/sparse/KokkosSparse_sptrsv_handle.hpp
- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_sptrsv_solve_impl.hpp
Fixes build with devices other than Serial and KokkosKernels supernodal SpTRSV enabled. Uses explicit exec+mem space pair to match correct ETI versions of SpMV, while before would get an undefined reference link time error.
Issue reported by @iyamazaki 
Just a build change, but SpTRSV is tested in KokkosKernels
> KokkosKernels: patch in supernodal fix

- packages/tpetra/core/src/Tpetra_Access.hpp
- packages/tpetra/core/src/Tpetra_withLocalAccess.hpp
- packages/tpetra/core/src/Tpetra_withLocalAccess_MultiVector.hpp
- packages/tpetra/core/test/MultiVector/WithLocalAccess.cpp
- packages/tpetra/core/test/Utils/withLocalAccess_generic.cpp
Make WithLocalAccess use these tags instead of internal Details:: ones:
```
#include "Tpetra_Access.hpp"
...
do_thing(Tpetra::Access::ReadOnly());
do_thing(Tpetra::Access::ReadWrite());
do_thing(Tpetra::Access::WriteOnly());
```
These will also be used for the new MultiVector view access interface.
Tested through withLocalAccess multivector tests.
> Tpetra: make access tags public

- packages/teuchos/parameterlist/src/Teuchos_ParameterList.cpp
- packages/teuchos/parameterlist/src/Teuchos_ParameterList.hpp
- packages/teuchos/parameterlist/test/ParameterList/ParameterList_UnitTests.cpp
Add a flag to `ParamterList::PrintOptions` that toggles the printing of default options.
The default behavior has not changed: defaults are printed.
> Teuchos ParameterList: Add option to toggle printing of default values

- cmake/std/atdm/cts1empire/environment_new.sh
@bathmatt, @e10harvey 
Something changed with the SPARC environment modules such that the NetCDF libs are now located in `lib64`.  Adjusting the environment script accordingly.
Closes #8722
> Fix cts1empire env

- cmake/std/atdm/ats2/environment.sh
Analogous to #8724, but for `ats2` instead of `cts1`.
> Fix ats2 env

- cmake/std/PullRequestLinuxCuda10.1.105uvmTestingSettings.cmake
- packages/teuchos/kokkoscompat/test/linkTest.cpp
This PR fixes Teuchos tests that failed when UVM is disabled.
It re-enables Teuchos tests that had been disabled.
I did not see failures in the Teuchos_stackedTimer tests, so I re-enabled them as well.
If they fail in the dev->master test, please mention me and I'll take a second look at them.
* Related to  #8633
Tested on cee-lan GPU machine with sierra-devel/nvidia module and 
```
-D Kokkos_ENABLE_CUDA_UVM=OFF
-D Tpetra_ENABLE_CUDA_UVM=OFF
```
All Teuchos tests passed.
> teuchos:  fix tests to pass without CUDA UVM  #8633

- packages/belos/tpetra/src/solvers/Belos_Tpetra_Gmres.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp
- packages/belos/tpetra/test/Native/CMakeLists.txt
- packages/belos/tpetra/test/Native/nonsymm_matrix.cpp
This PR adds the single-reduce MGS & CGS2 options into GmresSingleReduce under Belos "Native Tpetra" solvers
Added new options into ctest under belos/tpetra/Native, and ran ctest on blake
> Add single-reduce MGS & CGS2 options into GmresSingleReduce

- cmake/ctest/drivers/trappist/cron_driver.sh
trappist was using the archaic clang 3.9.0, it will now jump
into the present with a new clang 10.0.0 until even higher
versions are needed for OpenMP Target and other NGP stuff
comes along.
trappist was using the archaic clang 3.9.0 which no longer supported by Trilinos (guessing 3.9.0 does not implement c++14 fully).
It will now jump into the present with a new clang 10.0.0 until even higher versions are needed for OpenMP Target and other NGP stuff comes along.
The MueLu team is happy to see this build not failing at configure time anymore!
> MueLu: updating trappist nightly clang build

- packages/muelu/src/Utils/MueLu_PerfUtils_def.hpp
Adds printing of matrix entry statistics to PerfUtils. Disabled by default.
```
SM_Matrix size =  3630 x 3630, nnz = 103230
SM_Matrix diag min      : avg = 1.01e+00,  dev =   0.0%,  min =   +0.0% (    1.01 on    0),  max =   +0.0% (    1.01 on    0)
SM_Matrix diag max      : avg = 2.68e+01,  dev =   0.0%,  min =   +0.0% (   26.76 on    0),  max =   +0.0% (   26.76 on    0)
SM_Matrix abs(diag) min : avg = 1.01e+00,  dev =   0.0%,  min =   +0.0% (    1.01 on    0),  max =   +0.0% (    1.01 on    0)
SM_Matrix abs(diag) max : avg = 2.68e+01,  dev =   0.0%,  min =   +0.0% (   26.76 on    0),  max =   +0.0% (   26.76 on    0)
SM_Matrix entry min      : avg = -6.67e+00,  dev =  -0.0%,  min =   +0.0% (   -6.67 on    0),  max =   +0.0% (   -6.67 on    0)
SM_Matrix entry max      : …
```
> MueLu PerfUtils: Add option for entry statistics

- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C2_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_QUAD_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_QUAD_C2_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_C2_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_C2_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_WEDGE_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_WEDGE_C2_FEMDef.hpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_HEX_C2_FEM/Cuda/test_01.cpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_HEX_C2_FEM/test_01.hpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_QUAD_C2_FEM/Cuda/test_01.cpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_QUAD_C2_FEM/test_01.hpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TET_C2_FEM/Cuda/test_01.cpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TET_C2_FEM/test_01.hpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_C2_FEM/Cuda/test_01.cpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_TRI_C2_FEM/test_01.hpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_WEDGE_C2_FEM/Cuda/test_01.cpp
- packages/intrepid2/unit-test/Discretization/Basis/HGRAD_WEDGE_C2_FEM/test_01.hpp
UVM removal on HGRAD C2 basis functions
#8310 
Intrepid2 unit tests are passed on Weaver with ``Kokkos::Device<Kokkos::Cuda,Kokkos::CudaSpace>``
> Intrepid2 develop

- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_def.hpp
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/CMakeLists.txt
@searhein 
To cover the use of MueLu as inexact subdomain solver, two tests are re-activated. They solve a Laplace problem with FROSch, while using a MueLu hierarchy as subdomain solver.
As reported in #6390, MueLu does not accept `const` operators as input to the hierarchy construction. Hence, let's do a
`Teuchos::rcp_const_cast()` to get rid of the const qualifier prior to handing the matrix to MueLu.
* Closes #8762 
* Related to #6390 
@searhein and I are looking into the use of MueLu as inexact subdomain solver within FROSch.
Two tests have been reactivated.
> Shylu: re-enable tests w/ MueLu as inexact subdomain solver

- packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_HEX_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_HEX_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_QUAD_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_QUAD_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_QUAD_In_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TET_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TET_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TRI_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_TRI_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_WEDGE_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_HEX_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_HEX_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_HEX_In_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_QUAD_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_QUAD_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_QUAD_In_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TET_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TET_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TRI_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_TRI_In_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_WEDGE_I1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_Cn_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_QUAD_C1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_QUAD_Cn_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_C1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_Cn_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_C1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_Cn_FEM.hpp
Add host basis function interface. This is required for orientation tools. I also expect that this can be useful for other purpose as well. 
#8310 
#8772 - This PR is closed as it depends on the get host basis interface of all.
tested on weaver.
> Intrepid2 - add host basis function interface

- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- packages/muelu/test/unit_tests/Hierarchy.cpp
- packages/muelu/test/unit_tests/MueLu_TestHelpers.hpp
- packages/muelu/test/unit_tests/Smoothers/Ifpack2Smoother.cpp
- packages/stokhos/src/CMakeLists.txt
TESTS: RHEL7 (including two new ones)
Notes for reviewers:  BlockCrsMatrix is for small blocks (e.g. 3x3 elasticity), rather than BlockedMatrix, which is for big blocks (e.g. velocity/pressure for Navier-Stokes).
> MueLu/Ifpack2:  Pushing BlockCrsMatrix Smoother support to coarse levels

- packages/kokkos-kernels/src/common/KokkosKernels_SparseUtils.hpp
- packages/kokkos-kernels/test_common/Test_Common_Sorting.hpp
(fix #8727, TeamPolicy team size too large in sort_crs_*)
Adds the KokkosKernels unit test that replicated this issue.
Fixes bug in sort_crs_matrix/sort_crs_graph for an input graph with a high average degree. It was constructing a TeamPolicy with the desired number of threads per team, just to ask Kokkos for the recommended team size. Instead, this policy should just use 1 thread per team.
* Closes #8727 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of https://github.com/kokkos/kokkos-kernels/pull/872
This bug was affecting Exawind.
This PR includes a unit test in KokkosKernels which calls sort_crs_graph and sort_crs_matrix with a matrix with very long rows, which replicated the bug before the fix was applied.
> Patch in KokkosKernels #872

- packages/muelu/CMakeLists.txt
During configure, MueLu prints out the type combinations to ETI.
Add <complex-double, int, long long> to this, since it was missing.
If the build enables GO = long long and scalar = complex, this line was missing from the ETI summary that prints out during configure.
```
-- MueLu: Enabling ETI support
--    <float,   int, int>       : OFF
--    <double,  int, int>       : OFF
--    <double,  int, long>      : OFF
--    <double,  int, long long> : ON
--    <complex, int, int>       : OFF
--    <complex, int, long long> : ON   <----- This line
--    HAVE_MUELU_SERIAL       : ON
--    HAVE_MUELU_OPENMP       : OFF
--    HAVE_MUELU_CUDA         : OFF
```
It's just a ``MESSAGE(STATUS "...")`` line in CMake which isn't something we test. The variable …
> MueLu: in configure, add missing line to ETI summary

- packages/shylu/shylu_dd/frosch/src/SchwarzPreconditioners/FROSch_TwoLevelBlockPreconditioner_def.hpp
- packages/shylu/shylu_dd/frosch/src/SchwarzPreconditioners/FROSch_TwoLevelPreconditioner_def.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp
@searhein 
As @searhein and I discovered today, some places don't use the `enum`, but an `int` to encode the type of nullspace. By introduction of an `enum class NullSpaceType`, one is forced to use the scoped `enum` instead of the plain `int`.
This also adapts all calls to `BuildNullSpace()`.
All existing tests pass.
> Shylu: use scoped enum to encode NullSpaceType

- cmake/std/atdm/sems-rhel7/all_supported_builds.sh
- cmake/std/atdm/sems-rhel7/environment.sh
- cmake/std/atdm/utils/set_build_options.sh
From @rppawlo:
> Trilinos is looking to retire the clang 7 PR build. We are already running clang 10 in PR testing. I notice that the empire testing is using clang 7. Can Trilinos drop clang 7 testing? Should we wait until empire upgrades? What kind of schedule would that look like?
This PR updates the default clang in the `sems-rhel7` environment from `7.0.1` to `10.0.0`.
Trying this out on an ascic machine, it seems to work just fine.
* @e10harvey, I don't know if `sems-rhel7/all_supported_builds.sh` should be updated as well&mdash;I'm not sure what that file is used for.  If you want me to update it, let me know.
* Additionally, I wasn't sure if we should update the `cee-rhel7` environment as well, as the initial request was just for the sake of EMPIRE.  If you want me to update that …
> sems-rhel7 env:  Add clang-10.0.0

- packages/nox/src-loca/src-tpetra/LOCA_BorderedSolver_TpetraHouseholder.cpp
NOX:NodeType not specified in type being cast to.
Fixes inability to compile using clang. 
NOX:NodeType not being specified was producing a cast-to type with Kokkos::Serial, while specifying it produces a cast-to type with Kokkos::Threads.
@trilinos/nox
> Fix to NOX/LOCA

- packages/intrepid2/src/Discretization/Basis/Intrepid2_Basis.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasisFamily.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HCURL_HEX.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HCURL_QUAD.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HDIV_HEX.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HDIV_QUAD.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HGRAD_HEX.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HGRAD_QUAD.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HVOL_HEX.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DerivedBasis_HVOL_QUAD.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_DirectSumBasis.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_LINE_C1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_LINE_Cn_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_LINE_Cn_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_LINE_Cn_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasisFamily.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_IntegratedLegendreBasis_HGRAD_LINE.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_IntegratedLegendreBasis_HGRAD_TET.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_IntegratedLegendreBasis_HGRAD_TRI.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_LegendreBasis_HVOL_LINE.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp
- packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp
- packages/intrepid2/unit-test/MonolithicExecutable/BasisValuesTests.cpp
This is part of #8310.
Intrepid2: added getHostBasis() implementations for several Basis subclasses, along with support for DeviceType template arguments in the same.
Specifically, the following classes now support getHostBasis and DeviceType template arguments:
- DerivedBasis_HCURL_HEX
- DerivedBasis_HCURL_QUAD
- DerivedBasis_HDIV_HEX
- DerivedBasis_HDIV_QUAD
- DerivedBasis_HGRAD_HEX
- DerivedBasis_HGRAD_QUAD
- DerivedBasis_HVOL_HEX
- DerivedBasis_HVOL_QUAD
- HGRAD_LINE_Cn_FEM
- HVOL_LINE_Cn_FEM
- IntegratedLegendreBasis_HGRAD_LINE
- LegendreBasis_HVOL_LINE
Other changes:
- added typedef Intrepid2::DefaultTestDeviceType to TestUtils; this is UVM-free on CUDA, and Kokkos::DefaultExecutionSpace::device_type otherwise.
- Made use of DefaultTestDeviceType as well as …
> Implement getHostBasis() in newer Basis subclasses

- .github/workflows/stale.yml
This ups the version of the issue autocloser to 3.0.17 from 3.0.14
I increased the rate-limit threshold from 50 to 52 -- I'd like to see if we can find a value that gets us to about 100 issues / month that we can autoclose.  Right now I think it gets about 86 in a batch.
I also added a new feature to the .yml file. The `start-date` parameter is new and lets us set a threshold for the checker to only consider issues / PR's submitted _after_ some date.  I set this initially to 1/1/2001 so that we won't limit ourselves, but it's there in case we need it sometime in the future.
FYI @prwolfe @jwillenbring 
[1]: https://github.com/trilinos/Trilinos/labels/MARKED_FOR_CLOSURE
> Framework: Update STALE issue closer

- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
- packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_FECrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_FEMultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_Vector_decl.hpp
- packages/tpetra/core/src/Tpetra_Vector_def.hpp
- packages/tpetra/core/src/Tpetra_replaceDiagonalCrsMatrix_decl.hpp
Users of Tpetra should include Tpetra_ClassName.hpp.
If users are using ETI builds and need to instantiate a non-ETI template type, they should also include Tpetra_ClassName_def.hpp.
These comments recommend include Tpetra_ClassName_decl.hpp; that advice is wrong and can lead to errors.  Just ask @tasmith4, @shardest, @crdohrm , @kddevin.
@mmwolf  found this bad documentation; I am removing it.
N/A -- changes to comments only
> tpetra:  removed Doxygen comments with incorrect advice on including _decl files

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
`smoother: use l1 Gauss-Seidel` and `ML label` were not translated.
> MueLu: Fix missing parameters in ML2MueLuParameterTranslator

- packages/teuchos/core/src/Teuchos_TestForException.hpp
Reorder so [[noreturn]] precedes TEUCHOSCORE_LIB_DLL_EXPORT in
exception testers to restore DLL builds on MSVS 2015 and 2019.
Fixes #8818
@ibaned 
* Closes  #8818 
Problem manifests on Windows MSVS, DLL builds only, so likely not covered by current PR testing. All other builds enabling Teuchos should hit the edited line of code, though.
> Teuchos core: Reorder noreturn and DLL export

- packages/intrepid2/src/Cell/Intrepid2_CellGeometry.hpp
- packages/intrepid2/src/Cell/Intrepid2_CellGeometryDef.hpp
- packages/intrepid2/src/Cell/Intrepid2_ProjectedGeometry.hpp
- packages/intrepid2/src/Shared/Intrepid2_Data.hpp
- packages/intrepid2/unit-test/MonolithicExecutable/CellGeometryTests.cpp
- packages/intrepid2/unit-test/MonolithicExecutable/ProjectedGeometryTests.cpp
- packages/intrepid2/unit-test/MonolithicExecutable/StructuredIntegrationTests.cpp
- packages/intrepid2/unit-test/performance/StructuredIntegration/StructuredIntegrationPerformance.cpp
#8801 notes a test failure in Intrepid2 when built for CUDA 10.1.243 opt.  This appears to be a compiler bug related to a couple lambda functions.  (Among other evidence, the error does not present in a debug build.)  This PR's main motivation is to rewrite to avoid that apparent compiler bug.
To that end, we have two changes to CellGeometry: 
1. Modified CellGeometry `setJacobian()` implementations to allow reuse of reference-space basis gradients.  This is a change that I wanted to make anyway; it allows more efficient Jacobian computations when using the same reference-space points across multiple worksets.
2. Modified one lambda within `computeCellMeasure()`, making it use a one-dimensional range rather than a 2D MDRangePolicy.  This was purely for the purpose of working around the …
> Intrepid2: modifications for CUDA 10.1.243 opt build

- cmake/std/PullRequestLinuxCuda10.1.243TestingSettings.cmake
These SEACAS tests diff the stderr output with a known stderr gold file.  On vortex, the stderr is polluted with some jsrun output that messes up the comparisions.  It would be possible to do some grepping and other filtering to clean up the stderr, but these tests are well covered on other systems.
Should fix #8797, 
> SEACAS: Disable tests that are failing on vortex

- cmake/std/PullRequestLinuxCommonTestingSettings.cmake
- cmake/std/atdm/ATDMDisables.cmake
Related to #3282 
On a cee-rhel7 machine via:
```
nohup env Trilinos_PACKAGES=Kokkos ATDM_CTEST_S_DEFAULT_ENV=cee-rhel7-default ./ctest-s-local-test-driver.sh cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_dbg &> ctest-s-local-test-driver.out &
```
Evidence of the disable for `Random_XorShift64` is shown in [this](https://testing-dev.sandia.gov/cdash/queryTests.php?project=Trilinos&date=2021-02-11&filtercount=4&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Experimental&field2=buildname&compare2=65&value2=Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_dbg&field3=testname&compare3=63&value3=KokkosAlgorithms_UnitTest_MPI_1&field4=testoutput&compare4=95&value4=Random_XorShift) query by clicking "Show Matching Output".
> Disable Kokkos unit test Random_XorShift64 and Random_XorShift1024

- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
These were copied from the ini file without interpretation
which of course is incorrect.
Fails in Production - reported by Ross.
> Correct setenv left in bash scripts

- cmake/std/PullRequestLinuxCuda10.1.243TestingSettings.cmake
Basically the set command was missed on this line
which leaves cmake very confused.
* Follows #8829
* Related to #8797
> Fix an error introduced in PR 8829

- cmake/ctest/drivers/atdm/utils/setup_env.sh
On van1-tx2 and cts1 via:
```bash
nohup env Trilinos_PACKAGES=Kokkos,Teuchos,TrilinosATDMConfigTests ./ctest-s-local-test-driver.sh all &>ctest-s-local-test-driver.out &
```
See https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=cts1 and https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=van1.
Related to #8837.
> drivers/atdm: Fix proxy environment

- packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
Added assignment operator to Zoltan2_MJArrayType to fix error compiling with Clang on mac.
Error this fixes below:
```
=====================
/Users/pakuber/Compadre/trilinos/packages/kokkos/core/src/Threads/Kokkos_ThreadsTeam.hpp:312:25: error: no viable
overloaded '='
reducer.reference() = *((type volatile const*)local_value);
~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/pakuber/Compadre/trilinos/packages/kokkos/core/src/Threads/Kokkos_ThreadsTeam.hpp:975:26: note: in
instantiation of function template specialization
'Kokkos::Impl::ThreadsExecTeamMember::team_reduce<Zoltan2::ArrayCombinationReducer<Kokkos::TeamPolicy<Kokkos::Threads>,
double, int> >' requested here
loop_boundaries.thread.team_reduce(reducer, value);
^ …
```
> Added viable overload '=' for Zoltan2_AlgMultiJagged

- packages/rythmos/test/UnitTest/Rythmos_StepperBuilder_UnitTest.cpp
Some compiler/versions have trouble with testing throw
exceptions with setting RCP to Teuchos::null.
Excluding test for CLANG 7.0.
@trilinos/rythmos 
Get Rythmos passing on Astra.
* Closes #8489
> Rythmos: null test failing

- cmake/std/atdm/ats2/environment.sh
Basically the added c++14 flags for xl (-qxflag=disable__cplusplusOverride)
and the nvcc_wrapper flag needed to allow that (-ccbin xlc++)
need to be split.
See issue #8756 
* Closes #8756 
This was tested by hand agains the Trilinos-atdm-ats2-cuda-10.1.243-xl-2020.03.18_spmpi-rolling_static_opt and Trilinos-atdm-ats2-xl-2020.03.18_spmpi-rolling_serial_static_opt builds by hand using the process outlined at https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md
> This will resolve #8756  by changing CXX_FLAGS

- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_impl.hpp
- packages/tempus/src/Tempus_SolutionHistory_decl.hpp
- packages/tempus/src/Tempus_SolutionHistory_impl.hpp
- packages/tempus/src/Tempus_SolutionState_impl.hpp
- packages/tempus/src/Tempus_StepperStaggeredForwardSensitivity_impl.hpp
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref.xml
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref2.xml
- packages/tempus/unit_test/CMakeLists.txt
- packages/tempus/unit_test/Tempus_UnitTest_SolutionHistory.cpp
* SolutionHistory is no longer inherits from ParameterListAcceptor.
* Moved SolutionHistory constructor with ParameterList to a
nonmember constructor, createSolutionHistoryPL(pl).
* Added function to set the history, setHistory().
* Simplified the internal management of "Storage Type".
- Can set with enum StorageType or a string.
- Removed ParameterList validator for enum storageType.
* Added methods to initialize SolutionHistory similar to
other Tempus objects.
* Added checks to addState to ensure new state's index does not
match an index already in the SolutionHistory. This can
be turned off.
* Fixed bug in addWorkingState, where state was added to
history (chronologically) and then the TIME was changed.
* Added unit tests.
> Tempus: Remove ParameterList from SolutionHistory

- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorObserverBasic_impl.hpp
- packages/tempus/src/Tempus_IntegratorObserverSubcycling_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_impl.hpp
- packages/tempus/src/Tempus_PhysicsState_impl.hpp
- packages/tempus/src/Tempus_SolutionHistory_impl.hpp
- packages/tempus/src/Tempus_SolutionStateMetaData_impl.hpp
- packages/tempus/src/Tempus_SolutionState_impl.hpp
- packages/tempus/src/Tempus_StepperBDF2_impl.hpp
- packages/tempus/src/Tempus_StepperHHTAlpha_impl.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAForm_impl.hpp
- packages/tempus/src/Tempus_Stepper_impl.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyComposite.hpp
- packages/tempus/src/Tempus_TimeStepControl_impl.hpp
- packages/tempus/src/Tempus_WrapperModelEvaluatorPairPartIMEX_Basic_impl.hpp
When in parallel, the warnings are printed by each rank. On small number processor count, this is not an issue. However, on large number of processor counts, this fills up the log file ( space issue ) and burdens the user.
So to fix it, define the output stream to be a Teuchos fanceOSstream and set output to root only to true.
> Tempus output to root only

- packages/piro/src/Piro_NOXSolver_Def.hpp
@trilinos/piro
@mperego 
Before this PR, the `Piro::NOXSolver` was the only child class of `Piro::SteadyStateSolver` which was not using the nominal parameter values by default.
This branch has been tested on Blake successfully.
> Piro: use nominal parameter values by default in NOXSolver

- cmake/std/atdm/ats2/environment.sh
- cmake/std/atdm/ats2/trilinos_jsrun
This should avoid a known defect with Spectrum MPI with MPI collectives and complex data-types (see #8474).
On 'vortex', I ran:
```
$ ssh vortex
$ . .bash_profile
$ cd vscratch1/rabartl/Trilinos.base/BUILDS/VORTEX/CHECKIN//
$  ./checkin-test-atdm.sh ats2-cuda-complex-opt --enable-packages=TeuchosComm --configure --build
$ cd ats2-cuda-complex-opt/
$ . load-env.sh
$  bsub -Is -W 2:00 ctest -j4 -E TeuchosCore_testTeuchosTestForTermination
...
99% tests passed, 1 tests failed out of 118
Subproject Time Summary:
Teuchos    = 205.18 sec*proc (118 tests)
Total Test time (real) =  51.95 sec
The following tests FAILED:
91 - TeuchosComm_UnitTestHarness_Parallel_UnitTests_MPI_4 (Failed)
Errors while running CTest
```
The jsrun command commandline showed:
```
BEFORE: jsrun  '--smpiargs' '-HCOLL -FCA …
```
> ats2: Disable IBM optimized collectives for complex builds (#8474)

- packages/muelu/research/regionMG/src/SetupRegionMatrix_def.hpp
- packages/muelu/research/regionMG/src/SetupRegionUtilities.hpp
- packages/muelu/research/regionMG/test/structured/Driver_Structured_Regions.cpp
- packages/muelu/research/regionMG/test/structured/compare_residual_history.py
- packages/muelu/test/unit_tests/RegionMatrix.cpp
- packages/muelu/test/unit_tests/RegionRFactory.cpp
Calling functions such as getLocalRowCopy() and replaceLocalValues()
are very slow for some reason. Rewritting loops over the matrix
rows without using these yields large code speed ups.
The change in implementation yields a two order of magnitude speed up.
This allows unit-tests and at scale runs to improve dramatically in run time
as the driver runtime is dominated by matrix scaling at the moment.
* Closes 8374
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
People running the unit-tests are very happy with reduced runtime.
This has been tested locally on my workstation.
> MueLu: only loop interface rows in MakeQuasiRegionMatrices

- packages/panzer/disc-fe/src/Panzer_SetupPartitionedWorksetUtilities.cpp
Found bug relating to uniquely identifying worksets constructed using the partitioned workset path.
> Adding unique identifier to partitioned worksets

- packages/panzer/mini-em/example/BlockPrec/CMakeLists.txt
- packages/panzer/mini-em/example/BlockPrec/main.cpp
For performance tests (with Watchr output enabled), the ``--test-name=...`` parameter
can be used to change the output filename and chart name. Before, no way to distinguish the
regular and Reuse perf tests.
Disambiguates the filename for the reuse and non-reuse perf tests. Otherwise, they would collide so the one that ran first would get overwritten.
> MiniEM: add test-name param to BlockPrec

- packages/panzer/disc-fe/src/Panzer_HierarchicParallelism.hpp
- packages/panzer/disc-fe/test/core_tests/CMakeLists.txt
- packages/panzer/disc-fe/test/core_tests/hierarchic_team_policy.cpp
VT requires support for multiple cuda streams in EMPIRE. The team policy builder in panzer needs to support this as well for compatibility.
new test added to panzer/disc-fe/tests/core_tests/hierarchic_team_policy.cpp
> Panzer cuda stream support

- cmake/ctest/drivers/geminga/CMakeLists.txt
This seems to put too much of a burden on Geminga.
> Geminga: Stop testing Valgrind+MPI

- packages/sacado/src/new_design/Sacado_Fad_Exp_StaticFixedStorage.hpp
This reverts to the previous ordering of the val and dx fields
in the StaticFixedStorage type for SFad (with val first and dx
second) to workaround compiler seg faults on stria.
> Sacado:  Reorder SFad<> val and dx fields for stria

- packages/belos/src/BelosGmresPolyOp.hpp
- packages/belos/src/BelosGmresPolySolMgr.hpp
This is a very minor fix so that all three versions (Gmres, Arnoldi, and Roots) of the Gmres polynomial solver/preconditioner have consistent degree implementations.  Previously, the Gmres version was 'off by one'.  The GMRES polynomial would apply "max-degree" to p(A), while the other versions let "max-degree" indicate the degree of Ap(A).  Now all three versions do the latter.  
This code is tested in Belos_Tpetra_HybridGMRES_hb_test.exe.
> Belos: Update Gmres polynomial so degrees match in all versions

- packages/belos/src/BelosGmresPolyOp.hpp
This PR is in response to issue #8540. This outputs an error message to the user in the event that one of the GMRES polynomial roots is near zero and gives instructions to reduce the polynomial degree or shift the matrix.  I have verified that this error check does catch the issue presented with the singular Laplacian in Zoltan2.
> Belos: Add error message to avoid divide by zero crash. 

- packages/tpetra/core/example/Lesson04-Sparse-Matrix-Fill/index.doc
This change closes an unclosed `<tt>` tag in the Tpetra lesson 04 documentation.
The problem can be seen at the bottom of https://docs.trilinos.org/dev/packages/tpetra/doc/html/Tpetra_Lesson04.html
N/A
> Fix unclosed <tt> in tpetra lesson04 documentation

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_Cuda.hpp
- packages/tpetra/core/ext/TpetraExt_TripleMatrixMultiply_def.hpp
- packages/tpetra/core/test/MatrixMatrix/MatrixMatrix_UnitTests.cpp
Much of the CUDA mat-mat stuff is running on host.
This PR adds create_mirror_view_and_copy for device views needed on host
It would be better to use KokkosKernels.
@csiefer2 @lucbv or @brian-kelley  would you please take a look?  For full effect, you have to compare the branch against develop.  This PR compares only against tpetraCrsRefactor; there are other changes to these files (already in tpetraCrsRefactor) that you'll see if you compare with develop.  
If it looks OK to you, please feel free to merge into tpetraCrsRefactor.  If it doesn't look OK, let me know what's needed.
An alternate implementation might convert the views to host in the calls to these functions, rather than in these functions themselves.    Let me know if that makes more sense. …
> tpetra:  fixes for MatrixMatrix products

- packages/rythmos/test/UnitTest/Rythmos_StepperBuilder_UnitTest.cpp
Test fails in debug for various compilers. See #8489.
Disable portion of test that fails.
@trilinos/rythmos 
Get a stable test.
* Closes #8952 
* Related to #8489
> Rythmos:  StepperBuilder test failing

- packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
When we get the host view of a WrappedDualView with OverwriteAll, a device kernel is potentially still changing values on the device view, but we don't care because we're overwriting them anyway.  In UVM though, we need to wait to overwrite on host until device is done writing, because otherwise the things we write on host could be overwritten by the device kernel that hasn't finished yet.
The need for this change was exposed by an existing WrappedDualView test.
> Tpetra: add missing fence in WrappedDualView

- cmake/std/sems/get_default_modules.sh
The checkin-test-sems.sh script no longer works due to the gcc 5.3.0 requirement.
* Related to #8980 
Ran the checkin-test-sems.sh script locally and all tests passed.
> Update get_default_modules.sh, second attempt.

- cmake/std/atdm/ats1/environment.sh
- cmake/std/atdm/ats2/environment.sh
- cmake/std/atdm/common/toss3/environment_new.sh
- cmake/std/atdm/van1-tx2/environment.sh
This should be the last of the changes to the existing ATDM Trilinos configurations that will allow the SPARC TPL installer to switch over to the ATDM Trilinos configuration (other than updating the 'tlcc2' configuration to support the current sparc-dev module being used by SPARC).  This is mostly just responding to the new env var `ATDM_CONFIG_DONT_LOAD_SPARC_MODULES_PLEASE` that is set by the SPARC TPL installer.
SPARC will be upgrading Trilinos very soon (the last time it was upgraded from 'develop' version  3857fba from way back in 11/6/2020).
See [ATDV-408]
I manually tested these on the various machines.  See Sub-Tasks of [ATDV-408].
[ATDV-408]: https://sems-atlassian-srn.sandia.gov/browse/ATDV-408
> Allow ATDM Trilinos 'ats1', 'ats2', 'cts1', and 'van1-tx2' envs to be used with SPARC TPL installer (ATDV-408)

- cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.cmake
- cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.crs.cmake
- cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_debug_nouvm_ascicgpu031_crs.cmake
- cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_debug_uvm_deprecated_ascicgpu031_crs.cmake
- cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_debug_uvm_nodeprecated_ascicgpu031_crs.cmake
- cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_release_nouvm_ascicgpu031.cmake
- cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_release_uvm_deprecated_ascicgpu031.cmake
- cmake/ctest/drivers/ascicgpu031/ctest_linux_nightly_mpi_release_uvm_nodeprecated_ascicgpu031.cmake
Trying to get tpetra's nightly tests to run.
Removing flag CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS allows the Zoltan tests to builds.
Kokkos-kernels  seems to build fine as well, without the concerns in #2115.
Built on ascicgpu with shared libraries, complex double instantiated, and no flag CMAKE_CXX_USE_RESPONSE_FILE_FOR_OBJECTS
> Tpetra:  another test update to allow Zoltan tests to build

- packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
- packages/shylu/shylu_node/hts/src/shylu_hts_impl_def.hpp
Running hts_test on a new architecture revealed a bug: one omp flush line was
incorrectly placed, the one after s.n1Axpy. Fix this; the flush release should
be before the s_done lock is set, not after.
This achitecture is quite sensitive to omp flush, so I also took the opportunity
to rearrange placement of some others.
Also fix two cases of using int instead of size.
Closes #8485.
> ShyLU/HTS: Fix incorrect placement of omp flush.

- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_dbg.sh
- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_opt.sh
- cmake/ctest/drivers/atdm/van1-tx2/local-driver.sh
- cmake/std/atdm/van1-tx2/all_supported_builds.sh
- cmake/std/atdm/van1-tx2/custom_builds.sh
- cmake/std/atdm/van1-tx2/custom_builds_unit_tests.sh
- cmake/std/atdm/van1-tx2/environment.sh
CC: @jwillenbring, @tcfisher
@sebrowne: Thank you for all your hard work on this. Apologies for the delay due to testing and proxy issues. When testing the tip of https://github.com/sebrowne/Trilinos/tree/develop, I saw all the builds fail [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-04-9&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=van1&field2=groupname&compare2=63&value2=Experiment) on cdash. I rebased your changes on-top of the Trilinos develop branch and things are running smoothly now. We can either merge this PR and close #8850 or close this one and update your PR accordingly.
Since `van1-tx2_arm-20.1_openmpi-4.0.3_openmp_static_opt` is marked as a 'Primary Build' I have marked …
> ATDM/van1-tx2: Add openmpi 4.0.5 toolchain

- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
Enable reuse of some Ifpack2 preconditioners. This is only the plumbing on the MueLu side. Ifpack2 might still require some work.
> MueLu: Enable reuse of Ifpack2 smoothers

- packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockVector_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
pull out the deprecated warnings so that downstream doesn't see warnings while building with a "normal" build.
> comment out all the instances of TPETRA_DEPRECATED

- cmake/std/PullRequestLinuxCuda10.1.243TestingSettings.cmake
See #8798 for the discussion
Cleaning up testing for the vortex Dev->Master build
Tested by a manual build and ctest run on vortex
> Turn off 3 Zoltan tests that fail  due to a bug in spectrummpi

- packages/trilinoscouplings/examples/scaling/example_Maxwell.cpp
curl-curl term needs to be scales by 1/mu.
> TrilinosCouplings: Fix scaling of CurlCurl in Maxwell example

- packages/muelu/src/Utils/MueLu_AggregationExportFactory_def.hpp
Aggregation export gives garbage when used for problems with multiple dofs per node (like elasticity). To fix this, ghost coordinates are no longer added when aggregates don't cross processors (no need for ghosts), which fixes the problems when there are multiple dofs per node.
As far as I know, aggregation export is not tested.
Looking at the output in paraview, the aggregates for elasticity now resemble aggregates instead of a crazy blob of things. Scalar equations look the same as before (except for the "point cloud" which is also better now because it now gives aggregate labels to the nodes on processor interfaces).
The map that is used to find ghost coordinates in the aggregation export might be wrong, in which case this just circumvents the problem instead of …
> MueLu: fix agg export for multiple dofs per node

- packages/intrepid2/src/Cell/Intrepid2_CellGeometryDef.hpp
- packages/intrepid2/src/Cell/Intrepid2_CellToolsDefJacobian.hpp
The test failure when building optimized with CUDA 10.1.243, documented in #8801, has recurred.  This is an issue that is sensitive to compilation details: it does not occur in debug builds, and the previous fix was to replace a 2D MDRangePolicy with a 1D RangePolicy in the Kokkos::parallel_for.  Adding console output immediately prior to the parallel_for can make the issue go away.  Switching back to a 1D RangePolicy does not fix it.  What I found does fix it, at least for the moment, is to replace the lambda in the body of the parallel_for with a functor.  That's what this PR does.
While I was at it, I also resolved a few uninitialized variable warnings.
Closes #8801 (for now).
> Intrepid2: fix 8801 (second attempt)

- packages/belos/tpetra/src/solvers/Belos_Tpetra_Gmres.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov_parameters.hpp
This PR adjusts the default parameters for GmresSingleReduce in belos/tpetra (to make it more robust/efficient):
- Previously, single-reduce CGS with Newton basis was the default
- Now, single-reduce MGS with delayed normalization is the default, without Newton basis
> Adjust default parameters of GmresSingleReduce

- cmake/std/PullRequestLinuxCuda10.1.105uvmTestingSettings.cmake
@trilinos/framework @trilinos/intrepid2 
Per #8310, Intrepid2 is now UVM free.
So, this will reenable it for the dev to master Trilinos_pullrequest_cuda_10.1.105_uvm [off] PR build.
Since this doesn't affect PR testing, it was manually tested. [CDash results](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=61&value1=PR-Intrepid2_UVM_Free-test-Trilinos_pullrequest_cuda_10.1.105_uvm-103&field2=buildstamp&compare2=61&value2=20210426-0539-Experimental) show it's building and testing successfully.
> Turn on Intrepid2 in UVM = OFF build

- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
Use offsets for diagonal extraction when the the matrix is fill completed, not just when `isStaticGraph` returns true.
> Ifpack2 Relaxation&Chebyshev: Use offsets in more cases

- .github/workflows/stale.yml
In some cases, when the issue autocloser bot flags an issue for removal people are posting responses to the bot in the issue to confirm that "yes, it can be closed"... they may not realize that what they're _actually_ doing is telling the bot "oh no, please don't close this issue... we'd like to reset that clock for another year".
This update just adds more content to the text from the bot to be a bit more explicit to tell the users that if they're ok with the issue being closed out that they can either go ahead and close the issue (the best option) or they can let the autocloser do it after 30 days... but they **should not touch the issue** unless they want to reset that clock for another year.
This is actually a problem because the autocloser bot looks at issues …
> Framework: update messaging on issue autocloser bot

- packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgMultiJagged.hpp
When compiling with IBM Clang 11 + Cuda, Zoltan2 MJ captures 'this' inside lambdas
This patch
* Marks 1 function static, which was class const (but used not class variables).
* addresses this-> being used inside a nested team lambda (which clang doesn't like)
To remove this, I moved sEpsilon as parameter to the function being called and
was able to mark the function static as well (removing its use of this->sEpsilon)
This entails creating a function-locally copy of sEpsilon so that it may be
captured by the default [=] capture.
Both changes entail adding a `using` statement within the function so that the
now static class functions can be called (e.g., AlgMJ< ... >::)
* Closes #9049
Tested on:
*  ATS2 (lassen) IBM Clang 11.0.1 (w/ Cuda)
*  Cray CCE 11.0.4  (clang based …
> Zoltan2:  MultiJagged captures this in a lambda which breaks Clang 11 + Cuda

- packages/tpetra/scripts/PerformanceTesting/README.txt
- packages/tpetra/scripts/PerformanceTesting/eclipse/JenkinsAction.sh
- packages/tpetra/scripts/PerformanceTesting/eclipse/configBuildTest.sh
- packages/tpetra/scripts/PerformanceTesting/eclipse/launch.sh
- packages/tpetra/scripts/PerformanceTesting/stria/JenkinsAction.sh
- packages/tpetra/scripts/PerformanceTesting/stria/configBuildTest.sh
- packages/tpetra/scripts/PerformanceTesting/stria/launch.sh
- packages/tpetra/scripts/PerformanceTesting/vortex/JenkinsAction.sh
- packages/tpetra/scripts/PerformanceTesting/vortex/configBuild.sh
- packages/tpetra/scripts/PerformanceTesting/vortex/launch.sh
- packages/tpetra/scripts/PerformanceTesting/vortex/test.sh
eclipse, vortex and stria env/build scripts for performance testing of Tpetra, MueLu and MiniEM.
These are used on SRN Jenkins to do performance testing, with the data visualized using Watchr.
This is just a backup of the scripts that are stored in the trilinos-performance SEMS data store. The copies in the data store are what actually get run on the clusters, and those can only be changed manually by someone with data store access.
We thought it would be a good idea for the data store to not be the only place these are saved.
Not a code change. These scripts are currently being used in the nightly performance testing on these 3 machines.
> Tpetra: add backup of scripts for perf testing

- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spmv_impl.hpp
Will only hit spmvs with a beta of exactly -1 using the Serial backend.
Bug reported by some apps after the last release. Could be the reason for: #9070
> KokkosKernels: Fix bug in Serial specialization of spmv

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestCuda10.1.105uvmOffTestingEnv.sh
- cmake/std/trilinosprhelpers/unittests/trilinos_pr_test.ini
Naming the UVM = OFF build as `Trilinos_pullrequest_cuda_10.1.105_uvm` is a bit of a misnomer as it sounds like the opposite, UVM = On. #9068 So, to avoid confusion, this will change the name to `Trilinos_pullrequest_cuda_10.1.105_uvm_off` in the code.
Once the PR is tested and reviewed, I'll merge it manually as to time it with changing of the job name itself.
> Change name of the UVM PR build to include UVM Off

- packages/ifpack2/src/Ifpack2_Details_GaussSeidel.hpp
- packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRBILUK.cpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestRelaxation.cpp
- packages/tpetra/core/example/advanced/Benchmarks/blockCrsMatrixMatVec.cpp
- packages/tpetra/core/src/Tpetra_BlockMultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_BlockVector_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockVector_def.hpp
- packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
- packages/tpetra/core/test/Block/BlockMultiVector.cpp
- packages/tpetra/core/test/Block/BlockMultiVector2.cpp
Functions getLocalRowView and getGlobalRowView were removed without deprecation from BlockMultiVector and BlockVector.  This removal without deprecation was reported in #9082.  This PR restores the functions.  
However, users should migrate away from use of BlockMultiVector's getLocalRowView and getGlobalRowView, as they are deprecated.  These functions are completely unsafe with UVM is disabled; their returning of a raw data pointer is not allowed in non-UVM Tpetra.
This PR also renames getLocalBlock to getLocalBlockHost, to more accurately reflect what is returned (and, indeed, what has always been returned by getLocalBlock, getLocalRowView and getGlobalRowView).
Following Trilinos' deprecation policy.
* Closes  #9082
@tcfisher please let us know whether this PR …
> Tpetra:  restore deprecated BlockMultiVector and BlockVector functions for #9082

- packages/PyTrilinos/src/Teuchos_ParameterList.i
The Teuchos::ParameterList was updated to utilize a Teuchos::ParameterListModifier class, which was not wrapped, so SWIG did not know how to handle it.  The temporary fix implemented here is that all methods (including a constructor) that reference ParameterListModifier are now ignored.  A better fix might be to wrap the ParameterListModifier and not ignore those methods.
Bug report in Trillinos issue #9013
* Closes #9013
> PyTrilinos: Fix PyTrilinos.Teuchos build error

- packages/ifpack2/src/Ifpack2_AdditiveSchwarz_decl.hpp
- packages/ifpack2/src/Ifpack2_BlockRelaxation_decl.hpp
- packages/ifpack2/src/Ifpack2_Chebyshev_decl.hpp
- packages/ifpack2/src/Ifpack2_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_Hiptmair_decl.hpp
- packages/ifpack2/src/Ifpack2_Parameters.cpp
- packages/ifpack2/src/Ifpack2_Preconditioner.hpp
- packages/ifpack2/src/Ifpack2_Relaxation_decl.hpp
- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
- Add `supportsZeroStartingSolution` and `setZeroStartingSolution` methods to Ifpack2 and use them in MueLu. Simplifies MueLu's code and avoids calling `setParameters` for each smoother apply.
- Add additional options to Ifpack2 Chebyshev that should speed up repeated setups.
> Ifpack2 cheby reuse

- cmake/tribits/win_interface/include/gettimeofday.c
- packages/amesos/CMakeLists.txt
In tribits/win_interface/include/gettimeofday.c:
Remove spaces around time.h in its include, which spaces clang some version did not
like.
In packages/amesos/CMakeLists.txt:
With TPL_ENABLE_SuperLUDist_Without_ParMETIS=true, one can now
configure with superlu_dist and without parmetis - for the case where
superlu_dist is built without parmetis as is now possible with
-Denable_parmetislib:BOOL='OFF' when configuring superlu_dist.
@trilinos/<Tribits>
@trilinos/<Amesos>
These changes allow compilation of gettimeofday.c on Windows with LLVM,
and they allow building of Trilinos with superlu_dist and without parmetis, as
superlu_dist can now be built without parmetis.
* Closes #9094
> Tribits, Amesos: Remove spaces around time.h, allow superlu_dist without parmetis

- packages/belos/tpetra/src/solvers/Belos_Tpetra_Cg.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_CgPipeline.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_CgSingleReduce.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_Gmres.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresPipeline.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresS.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSingleReduce.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_GmresSstep.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_Krylov_parameters.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_SolverManager.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_SolverManagerBase.hpp
- packages/belos/tpetra/src/solvers/Belos_Tpetra_UpdateNewton.hpp
This PR adds missing copyright statements to header files of some belos Native tpetra solver
> Add missing copyright statements

- packages/tpetra/core/src/Tpetra_DistObject_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/CrsMatrix/Bug8794.cpp
In https://github.com/Exawind/nalu-wind/issues/858, @rcknaus reported export errors when TPETRA_ASSUME_CUDA_AWARE_MPI=0 after #8821 was merged.
Similar errors were exposed by tpetra/core/test/CrsMatrix/Bug8794.cpp.
In Bug8794.cpp, many multivector elements are imported, due to the dense rows in the test matrix.
With TPETRA_ASSUME_CUDA_AWARE_MPI=0, DistObject decides to do communication on host.
With long rows, the number of imports is large, so MultiVector decides to unpack on device.
However, the sync of the import buffer between the communication and unpack was missing.
This PR adds the sync.
I still need to investigate what changed in #8821 to cause this error.  We should also set up nightly tests with TPETRA_ASSUME_CUDA_AWARE_MPI=0; Trilinos PR testing has …
> Tpetra:  adding syncs of import buffers in MultiVector

- packages/kokkos-kernels/src/blas/KokkosBlas3_gemm.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas2_gemv_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas2_gemv_spec.hpp
- packages/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas2_gemv.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas3_gemm.hpp
Patch in KokkosKernels PRs #939 and #948. These are to improve
general GEMV performance on GPUs, and GEMM performance in a certain case:
C=AB where B and C have 1 column. Trilinos issue #8923 is about this
GEMM case.
- Improves general GEMV performance by using 2-level parallelism. Except for extreme tall-skinny cases, KokkosKernels GEMV now gets performance very close to cuBLAS (see https://github.com/kokkos/kokkos-kernels/pull/939), and performs equally well for both matrix layouts.
- Significantly improves GEMM performance for a case that appears in ICGS orthogonalization (see #8923 for request, https://github.com/kokkos/kokkos-kernels/issues/929 for results)
The GEMV work was requested by @vbrunini for Sierra TF. The GEMM …
> KokkosKernels: gemv/gemm perf improvements

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Remove unnecessary check from `MV::isSameSize`. This avoids a potential memcopy to host.
> Tpetra MultiVector: Remove unnecessary check from isSameSize

- cmake/std/PullRequestLinuxCuda10.1.105TestingSettings.cmake
- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
This will enable complex data types for the CUDA 10.1.105 [UVM ON] and CUDA 10.1.105 UVM OFF PR builds.
This should close #9025 
After a couple last updates, these changes have passed manual testing on the two builds affected.
[CDash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=complex-test-Trilinos_pullrequest_cuda_10.1.105&field2=buildstamp&compare2=63&value2=Experimental&field3=buildstarttime&compare3=83&value3=2021-05-10)
> Enable Complex Data Types in CUDA 10.1.105 PR Builds

- packages/teko/tests/unit_tests/tDiagonallyScaledPreconditioner.cpp
Relax tolerance for test, so that it passes on CUDA.
Should help avoid failures as seen in #9134 
https://testing.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=9177412
> Teko DiagonallyScaledPreconditioner test: Relax tolerance for CUDA

- packages/belos/test/BlockCG/test_bl_cg_complex_hb.cpp
- packages/belos/test/BlockGmres/test_bl_gmres_complex_diag.cpp
- packages/belos/test/BlockGmres/test_bl_gmres_complex_hb.cpp
- packages/belos/test/BlockGmres/test_hybrid_gmres_complex_hb.cpp
- packages/belos/test/GCRODR/test_gcrodr_complex_hb.cpp
- packages/belos/test/MINRES/test_minres_complex_hb.cpp
- packages/belos/test/MVOPTester/cxx_main_complex.cpp
- packages/belos/test/TFQMR/test_pseudo_tfqmr_complex_hb.cpp
- packages/belos/test/TFQMR/test_tfqmr_complex_diag.cpp
- packages/belos/test/TFQMR/test_tfqmr_complex_hb.cpp
The HAVE_COMPLEX macro is a deprecated conditional from the days when
the complex<> class had non-uniform support across compilers.  It can,
and should, be removed, as mentioned in Github issue #1995
Serial OSX GCC10.x
> Removes HAVE_COMPLEX from complex-valued tests

- cmake/std/atdm/van1-tx2/environment.sh
CC: @sebrowne, @jwillenbring
```bash
$ source cmake/std/atdm/load-env.sh default
Hostname 'van1-tx2' matches known ATDM host 'van1-tx2' and system 'van1-tx2'
Using ARM ATSE compiler stack ARM-20.1_OPENMPI-4.0.5 to build DEBUG code with Kokkos node type SERIAL
$ source cmake/std/atdm/load-env.sh arm-20.0
Hostname 'van1-tx2' matches known ATDM host 'van1-tx2' and system 'van1-tx2'
Setting compiler and build options for build-name 'arm-20.0'
Using ARM ATSE compiler stack ARM-20.0_OPENMPI-4.0.2 to build DEBUG code with Kokkos node type SERIAL
***
*** DEPRECATION NOTICE:
****   WARNING: "ARM-20.0_OPENMPI-4.0.2" will no longer be supported on 07-15-2021.
***
```
Related to #9100.
> van1-tx2: Add deprecation notice

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/MultiVector/deep_copy_from_SDM.cpp
- packages/tpetra/core/test/MultiVector/deep_copy_to_SDM.cpp
Copies between Tpetra MultiVector and Teuchos SerialDenseMatrix used the device MultiVector if the device data was most up-to-date.  But when the MultiVector is a subset of the rows of a MultiVector (i.e., obtained by offsetView), device copies to/from host SerialDenseMatrix failed. 
This PR changes all copies between SDM and MV to use MV's host view.
It also adds tests of this use-case to deep_copy_*_SDM.cpp tests; the added tests fail with the original code but pass with the host-only copies.
Since SerialDenseMatrix is a host-only data structure, it makes sense to do the copies from MV's host view.  MV's getLocalViewHost and access tags correctly manage needed synchronization.
* Closes  #9164 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* …
> tpetra:  added test and correction for MV copies to/from Teuchos::SerialDenseMatrix for #9164

- packages/belos/epetra/test/MINRES/CMakeLists.txt
- packages/belos/epetra/test/MINRES/test_pminres_hb.cpp
- packages/belos/src/BelosMinresIter.hpp
The MINRES solver had been written to work with left preconditioning,
but doesn't work with right-preconditioning or preconditioning on both
sides.  That has been corrected with this commit, using the same 
preconditioning strategy as CG.  A test including preconditioning on 
either left or right-side has been added for Epetra.
Tpetra tests for all solvers, that includes preconditioners, will be
added in a future commit.
Test added to Epetra/test/MINRES directory
OSX GCC10.x Serial testing used to confirm passing
> Belos:  Fixes MINRES solver to perform correctly for right-hand preconditioning

- packages/amesos2/src/Amesos2_Factory.cpp
- packages/amesos2/src/KLU2/Include/klu2_ordinaltraits.h
- packages/epetra/src/Epetra_Comm.h
- packages/epetra/src/Epetra_MpiComm.h
- packages/epetra/src/Epetra_SerialComm.h
- packages/ifpack2/adapters/thyra/Thyra_Ifpack2PreconditionerFactory_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Factory_def.hpp
- packages/ifpack2/src/Ifpack2_Utilities.cpp
- packages/intrepid2/src/Shared/Intrepid2_PointToolsDef.hpp
- packages/intrepid2/src/Shared/Intrepid2_PolylibDef.hpp
- packages/muelu/src/Transfers/PCoarsen/MueLu_IntrepidPCoarsenFactory_def.hpp
This should close out Issue #8202.
* Getting git date fails
* std::to{low,upp}er does not exist
* trilinos_btf_l_order and siblings use long, but the correct type on Win64 is ptrdiff_t (long long)
* Epetra_*Comm have problems because CreateDirectory is a macro in Winbase.h
* Need to define _USE_MATH_DEFINES to get M_PI defined on Windows.
An index of packages affected by commit is below.
Package    commit
@trilinos/tribits 94fe325cd4fcd6fd3de2e21454d3825bda07803a
@trilinos/epetra ed5b0c26006e87cb7ec88cf93b8a82bb0ec0af8e
@trilinos/amesos2 @trilinos/ifpack2 @trilinos/muelu 1c858848df7caecc8bbbe254cfdb5a09d40a9061
@trilinos/amesos2 c46ef3fd0bcef35f4b9fd1d993bef09f24587b5a
@trilinos/intrepid2 5b901c3a5cf1737db1959746288d3102a83241d6
Need to build trilinos on Windows with LLVM
Will not be done …
> 8202 llvmwinbld: Fix miscellaneous windows build issues with llvm-clang

- packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
@crdohrm 
Cuda 11 allows bigger team size compared to cuda 10. To make code working for both versions, I added different team parameters.
Confirmed/resolved the problem on kokkos-dev-2 with cuda 10 and cuda 11.
> Tacho - team size adjustment for cuda 11 and cuda 10

- packages/nox/src-loca/src-tpetra/LOCA_BorderedSolver_TpetraHouseholder.cpp
- packages/nox/src-loca/src-tpetra/LOCA_BorderedSolver_TpetraHouseholder.hpp
- packages/nox/src-loca/src-tpetra/LOCA_Tpetra_LowRankUpdateRowMatrix.hpp
- packages/nox/src-thyra/NOX_Thyra_Group.C
- packages/nox/src-thyra/NOX_Thyra_Group.H
- packages/nox/test/tpetra/CMakeLists.txt
- packages/nox/test/tpetra/tTpetra_HouseholderBorderedSolve_WithUVInPrec.cpp
Improves preconditioning matrix
Requested for Charon2 problem
New test added:  nox/test/tpetra/tTpetra_HouseholderBorderedSolve_WithUVInPrec.cpp
> NOX: Tpetra householder solver can optionally update prec with U*V^T

- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybrid2GL.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1-2GL.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD2.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridPD2.hpp
- packages/zoltan2/core/src/problems/Zoltan2_ColoringProblem.hpp
- packages/zoltan2/test/core/color/CMakeLists.txt
- packages/zoltan2/test/core/color/coloring1.cpp
This fixes a  performance bug in the distance-1 coloring in Zoltan2, as well as adding the capability to report accurate times without any other output to all coloring implementations.
These changes are covered by existing tests.
> Zoltan2: (Coloring) Fixed D1 performance bug, added timing argument to coloring code

- cmake/ctest/drivers/atdm/ats2/local-driver.sh
- cmake/std/atdm/ats2/tweaks/Tweaks.cmake
- Skip Adelus tests when TPETRA_ASSUME_CUDA_AWARE_MPI is 0.
Related to #8477.
On ats2 via:
```
nohup env Trilinos_PACKAGES=Kokkos,Adelus ./ctest-s-local-test-driver.sh all &>ctest-s-local-test-driver.out &
```
Test results posted [here](https://testing-dev.sandia.gov/cdash/index.php?project=Trilinos&date=2021-03-29&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=ats2&field2=groupname&compare2=63&value2=Experimental).
> atdm/ats2: Only run Adelus tests with TPETRA_ASSUME_CUDA_AWARE_MPI=1

- packages/panzer/doc/Doxyfile
Thanks to Curt for finding this!
doxygen file had a cut and paste error for path to phalanx tags
> Panzer: fix doxygen tag file

- packages/muelu/test/scaling/CMakeLists.txt
- packages/muelu/test/unit_tests/CMakeLists.txt
CMake >= 3.20 complains about missing extensions for source files https://cmake.org/cmake/help/git-stage/policy/CMP0115.html
> MueLu: Avoid CMake warning about source file extensions

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Speed up ``CrsMatrix::sortAndMergeIndicesAndValues`` (host, unpacked storage, called during fillComplete) by skipping the RowInfo interface.
sortAndMergeIndicesAndValues measured on my RHEL machine, Cuda + UVM, matrix StocF-1465:
Before all UVM removal: 0.0743
After #9038: 0.717
With this PR: 0.0696
Fixing #9228 performance regression.
> Tpetra: speed up sortAndMerge (#9228)

- packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp
- packages/tpetra/core/test/TpetraUtils_MatrixGenerator.hpp
``generate_miniFE_vector`` was only setting values owned by rank 0 (higher ranks locally got all zeros).
This is used to generate the RHS (b) in PerformanceCGSolve, so this caused
the initial residuals and number of CG iterations to go down as ranks increased.
So it wasn't really a valid strong scaling study. Now the vector is always the same for a given grid size, as it should be.
Also got rid of the x, r, Ap vector initialization using replaceLocalValue(). @jennloe pointed out that r and Ap are
actually completely overwritten by apply/update before they are read, and
x is a freshly constructed (0-initialized) vector. This saves a
significant amount of time and makes the StackedTimer total more
representative of SpMV/BLAS time that it's supposed to be measuring.
It's good of course that …
> Tpetra: fix MiniFE example vectors for >1 rank

- packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
A BlockCrs test is failing with deprecated code OFF, UVM OFF. The problem is to use const version of accessor when the test is modifying the values of the matrix. This PR changes the accessor from const to non const.
Tested on kokkos-dev-2.
> Tpetra - fix failing test in block crs

- packages/belos/src/BelosBiCGStabIter.hpp
- packages/belos/src/BelosBiCGStabSolMgr.hpp
- packages/belos/src/BelosBlockCGIter.hpp
- packages/belos/src/BelosBlockCGSolMgr.hpp
- packages/belos/src/BelosBlockGCRODRSolMgr.hpp
- packages/belos/src/BelosBlockGmresSolMgr.hpp
- packages/belos/src/BelosFixedPointIteration.hpp
- packages/belos/src/BelosFixedPointSolMgr.hpp
- packages/belos/src/BelosLSQRIter.hpp
- packages/belos/src/BelosLSQRIteration.hpp
- packages/belos/src/BelosLSQRSolMgr.hpp
- packages/belos/src/BelosMinresIter.hpp
- packages/belos/src/BelosMinresIteration.hpp
- packages/belos/src/BelosMinresSolMgr.hpp
- packages/belos/src/BelosPCPGIter.hpp
- packages/belos/src/BelosPCPGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockCGIter.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp
- packages/belos/src/BelosPseudoBlockStochasticCGIter.hpp
- packages/belos/src/BelosPseudoBlockStochasticCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockTFQMRIter.hpp
- packages/belos/src/BelosPseudoBlockTFQMRSolMgr.hpp
- packages/belos/src/BelosRCGIter.hpp
- packages/belos/src/BelosRCGSolMgr.hpp
- packages/belos/src/BelosTFQMRIter.hpp
- packages/belos/src/BelosTFQMRSolMgr.hpp
- packages/belos/src/BelosTsqrOrthoManagerImpl.hpp
This is just a small clean up of the solvers in Belos to remove
the unnecessary inclusion of BLAS/LAPACK classes and exception handling
that likely resulted from copying old solvers to create new ones.
The impending refactor of the code to address the dense matrix
object used internally by most solvers necessitates a clear understanding
of the dependencies of each solver on BLAS/LAPACK methods.
> Removes unnecessary BLAS/LAPACK class usage and exception handling

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
- packages/teuchos/comm/src/Teuchos_StackedTimer.hpp
- packages/teuchos/comm/test/StackedTimer/stacked_timer.cpp
We have applications that are now using cuda streams. If tasks are launched asynchronously, the stop() call to stacked timers can trigger errors due to stopping out of sequence. We've added a method to pause timers by making the start() and stop() methods no-op. A second method can reenable. This will be used to pause timers when using tasking with cuda streams.
EMPIRE 1088
Fixes issue!
new unit test added to packages/teuchos/comm/tests/stacked_timer.cpp
> Teuchos: add hooks to disable/reenable stacked timers for async tasks.

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
@trilinos/tpetra @trilinos/framework 
PR #9240 fixed the last Tpetra testing error with UVM disabled.  (Thanks, @kyungjoo-kim )
Thus, all Tpetra tests should now be enabled in UVM-free testing.
N/A -- this change enables more PR tests
> Tpetra: enable block crs matrix tests in UVM-free PR builds

- packages/belos/src/BelosBiCGStabSolMgr.hpp
- packages/belos/src/BelosBlockCGSolMgr.hpp
- packages/belos/src/BelosBlockGmresSolMgr.hpp
- packages/belos/src/BelosFixedPointSolMgr.hpp
- packages/belos/src/BelosGCRODRSolMgr.hpp
- packages/belos/src/BelosGmresPolyOp.hpp
- packages/belos/src/BelosGmresPolySolMgr.hpp
- packages/belos/src/BelosPCPGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp
- packages/belos/src/BelosPseudoBlockStochasticCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockTFQMRSolMgr.hpp
- packages/belos/src/BelosRCGSolMgr.hpp
- packages/belos/src/BelosTFQMRSolMgr.hpp
- packages/muelu/src/Utils/MueLu_Utilities.cpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybrid2GL.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1-2GL.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD2.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridPD2.hpp
- packages/zoltan2/core/src/input/Zoltan2_InputTraits.hpp
Failure to build on Windows with LLVM
Closes issues #8202 and #9184
The problems were:
Belos: uses addressof to create a constexpr, which is not allowed, but for which there is a workaround.
Zoltan2: Need to use time.h instead of sys/time.h on Windows.  Need to define ssize_t on Windows.
MueLu: Need implementation to get host-order IP address without using inet_network, which does not exist on windows.
> 9184 winllvmparbuild: fix winllvm parallel builds with modification to muelu, zoltan2, belos

- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp
- packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp
- packages/ifpack2/src/Ifpack2_RILUK_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockTriDiContainer.cpp
- RILUK: move some host views into smaller scope that doesn't overlap with
scope of device views.
- BlockTriDi: make A values view unmanaged so that holding it doesn't
increment use count. This code is still responsible for managing syncs.
Make RILUK, BlockTriDiContainer obey the new Tpetra DualView semantics (don't hold host and device view simultaneously). Fixes tests for UVM off: ``Ifpack2_RILUK_HTS_hb_belos``, ``Ifpack2_BlockTriDiContainerUnitAndPerfTests``
> Ifpack2: fix refcount related errors

- cmake/std/PullRequestLinuxDriver-old.sh
- cmake/std/PullRequestLinuxDriver.sh
- cmake/std/common.bash
Now that the python systems are using the correct proxies and cert files we are failing due to the internal script settings. This just changes them to the new proxy.
> New proxy setting to match the change Friday

- cmake/std/pr_config/pullrequest.ini
- cmake/std/sems/PullRequestIntel17.0.1TestingEnv.sh
- cmake/std/sems/PullRequestIntel19.0.5TestingEnv.sh
Currently the sems module for intel compilers
does not find a license. This uses the info from
the system compilers modules instead.
This is a temporary resolution until the module becomes useable again.
* Part of #9293 
I was able to confirm both the problem and the solution at the command line by doing 'icc --version' and compiling a simple test source.
> Change The intel license info temporarily

- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_LocalCrsMatrixOperator_decl.hpp
- packages/tpetra/core/src/Tpetra_LocalCrsMatrixOperator_def.hpp
Lazily generate and cache the LO-typed rowptrs in CrsMatrix,
instead of recomputing every apply.
After UVM removal, ``CrsMatrix::getLocalMultiplyOperator`` would construct a new LocalCrsMatrixOperator every time it was called. This constructor would convert the rowptrs from size_type to LocalOrdinal (int) in a parallel_for so that cuSparse SpMV can be used, but this is a nontrivial amount of work and shouldn't be done every apply.
This PR just caches the int-typed rowptrs in CrsMatrix, and then passes that to a new low-overhead constructor for LocalCrsMatrixOperator.
@jennloe noticed this performance regression in Belos driver.
> Tpetra: fix performance in LocalCrsMatrixOp

- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_gauss_seidel_impl.hpp
in Gauss-Seidel long rows, with CUDA 9.2. Passing ``Kokkos::AUTO()`` for team size resulted in too many threads per team, but using ``TeamPolicy::team_size_recommended`` instead gives a working value.
For more details, SortIntoLongRowsFunctor is a TeamPolicy reduce functor. With ``Kokkos::AUTO()`` as the team size, and ordinal/offset = int/size_t, this was trying to use 544 threads per team. But this throws "Kokkos::Impl::ParallelReduce< Cuda > requested too large team size" at launch. ``team_size_recommended`` returns 512, and the kernel runs successfully with that. Will open a kokkos issue, hopefully with a simpler reproducer.
Fix #9272.
> Work around team size AUTO issue on kepler

- CMakeLists.txt
Disabling support for `Makefile.export.*` files in Trilinos while TriBITS is refactored in TriBITSPub/TriBITS#299 that will remove support for this permanently (see #8498).  The agreement was to remove support from Trilinos 'develop' on 6/10/2021 so I am 4 days late here.
I tested this manually locally and verified that even configuring with `-DTrilinos_ENABLE_EXPORT_MAKEFILES=ON` sets:
```
$ grep -B 1 ENABLE_EXPORT_MAKEFILES CMakeCache.txt 
//Support being removed from TriBITS (see trilinos/Trilinos#8498)
Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=OFF
--
Trilinos_ENABLE_EXPLICIT_INSTANTIATION-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Trilinos_ENABLE_EXPORT_MAKEFILES
Trilinos_ENABLE_EXPORT_MAKEFILES-ADVANCED:INTERNAL=1
```
and results in no `Makefile.export.*` files:
```
$ find . …
```
> Disable support for Makefile.export.* files (#8498)

- packages/tpetra/core/src/Tpetra_EpetraRowMatrix.hpp
- packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp
- EpetraRowMatrix: don't call ArrayView version of getLocalRowCopy, and un-deprecate ExtractMyRowCopy since it can just call the Kokkos::View version.
- RowMatrixTransposer: don't call getLocalMatrix
Fix build of Tpetra (library+tests) with deprecated code off.
@jennloe ran into the build error of RowMatrixTransposer in a build of Albany. Our nightly deprecated-off build on ascicgpu031 has been hitting it too, but I think we all ignored that :P
> Tpetra: remove some deprecated stuff

- packages/tpetra/core/test/MultiVector/Bug7758.cpp
@trilinos/tpetra @bartlettroscoe 
Some test output was overlapping with the "TEST PASSED" printout, likely due
to different buffering from different streams, and causing passing tests
to report failures on the dashboard.
This PR removes all printouts to std::cout from these tests, except those that
only print in case of a failure.
Thanks @bartlettroscoe for pointing this out.
* Closes #9307 
N/A -- this is a fix for a flaky test.
> Tpetra: Remove some output from the Bug7758 test

- packages/zoltan2/core/src/algorithms/partition/Zoltan2_AlgScotch.hpp
In #9312 @tasmith4 reported a memory leak when using 32-bit Scotch.
When Scotch's IDs (SCOTCH_Num) differ from the offset_type in the Zoltan2 Adapter, Zoltan2 deep copies vertex and adjacency arrays into arrays of type SCOTCH_Num to be passed to Scotch.  Templating helps Zoltan2 determine whether or not the copy is necessary, and then whether the deep copies need to be freed. 
In this bug, the template types used in the free differed from those in the alloc, so the vertloctab array was allocated but never freed.  This PR makes the template types agree.
* Closes #9312
@tasmith4 
ascicgpu machines, serial node, gcc7.2, Scotch 6.0.4 with 32-bit indices (provided by @tasmith4 from sierra build), OpenMPI 4.0.5, valgrind, np=1 and 4
Reproduced error; verified that PR …
> Zoltan2: fixed memory leak when using 32-bit Scotch

- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/muelu/adapters/tpetra/MueLu_TpetraOperator_def.hpp
- packages/muelu/adapters/xpetra/MueLu_XpetraOperator_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_normImpl.hpp
@trilinos/tpetra @trilinos/ifpack2 @trilinos/muelu 
- Skip unneeded view initializations.
- Tpetra global norm: use in-place reduction, similar to https://github.com/trilinos/Trilinos/blob/5242864373cc43d2fd8bedfd775c236daddeaf2c/packages/tpetra/core/src/Tpetra_MultiVector_def.hpp#L1962-L1982
> Skip view initializations

- packages/teuchos/comm/src/Teuchos_Comm.hpp
- packages/teuchos/comm/src/Teuchos_DefaultMpiComm.hpp
- packages/teuchos/comm/test/Comm/DefaultMpiComm_UnitTests.cpp
This new method is implemented on MpiCommRequestBase to call MPI_Test
and check whether an asynchronous MPI Send/Receive operation is completed.
Support a Tpetra use case for a non-blocking check whether an Import/Export operation has completed.
* Blocks #9145
Added 3 new Teuchos unit tests in the DefaultMpiComm unit test suite (NonblockingSendReceive_isReady*).
> Teuchos: Add "isReady" method to CommRequest

- cmake/std/PullRequestLinuxDriver-old.sh
- cmake/std/PullRequestLinuxDriver.sh
- cmake/std/common.bash
The changes made to get proxies working for develop are needed to get master working again as well. These will need to be force pushed for the same reason that we had to do a force push into develop (bootstrapping problem as the failure happens before the merge - often during the initial fetch.)
* Part of #9293
> Framework: Master new proxies

- packages/tpetra/core/example/Lesson07-Kokkos-Fill/05_solve.cpp
- packages/tpetra/core/example/advanced/Benchmarks/blockCrsMatrixMatVec.cpp
- packages/tpetra/core/example/advanced/Benchmarks/localView.cpp
- packages/tpetra/core/guide/src/Examples/SourceCode/power_method_1.cpp
- packages/tpetra/core/src/Tpetra_Details_scaleBlockDiagonal.hpp
- packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
- packages/tpetra/core/src/Tpetra_RowMatrixTransposer_def.hpp
- packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_LeftRightScale.cpp
- packages/tpetra/core/test/CrsMatrix/Regression/Albany182.cpp
- packages/tpetra/core/test/MultiVector/Issue46.cpp
- packages/tpetra/core/test/MultiVector/MultiVector_get2dView.cpp
- packages/tpetra/core/test/RowMatrixTransposer/main.cpp
- packages/tpetra/core/test/inout/MatrixMarket_Tpetra_CrsMatrix_FileTest.cpp
- packages/tpetra/core/test/inout/MatrixMarket_Tpetra_CrsMatrix_InOutTest.cpp
- packages/tpetra/core/test/inout/MatrixMarket_Tpetra_OperatorTest.cpp
GCC compiler warnings for "unused typedefs" were getting very noisy.
Continues to pass all Tpetra tests.
> Tpetra: fix several warnings

- packages/tpetra/scripts/PerformanceTesting/eclipse/JenkinsAction.sh
- packages/tpetra/scripts/PerformanceTesting/stria/JenkinsAction.sh
- packages/tpetra/scripts/PerformanceTesting/timingPercentages/timing_extractor.py
- packages/tpetra/scripts/PerformanceTesting/vortex/JenkinsAction.sh
This brings the percentage of overall time spent in each stage of the teuchos timers instantiated in the performance tests on the various platforms into the xml files generated at the end of each run.
This is a testing framework addition, it was tested against historical .xml files.
> Tpetra: Performance script timing percentage support

- packages/ifpack2/src/Ifpack2_IlukGraph.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestHelpers.hpp
When using arithmetic functions on device we must be careful to
call the proper Kokkos::Experimental::fun() to avoid portability
issues between device runtime libraries.
@trilinos/amesos2 @trilinos/belos @trilinos/ifpack2 
Some tests are still failing with Kokkos::HIPSpace enabled, these need to be fixed.
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #9317
* Part of 
* Composed of 
All testing is performed on Spock using rocm/4.2.0
> Ifpack2: fix arithmetic error on device

- packages/tpetra/core/src/Tpetra_Details_Transfer_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_Transfer_def.hpp
- packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
- packages/tpetra/core/src/Tpetra_DistObject_def.hpp
- packages/tpetra/core/src/Tpetra_Export_def.hpp
- packages/tpetra/core/src/Tpetra_ImportExportData_decl.hpp
- packages/tpetra/core/src/Tpetra_Import_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/ImportExport2/ImportExport2_UnitTests.cpp
Allow to skip `unpackAndCombine` in the following (common) situation:
- import of a MV
- MV has single column
- from a 1-to-1 map into an overlapping map
- CombineMode == INSERT
- off-rank entries are grouped by rank
- memory spaces for comm and data buffers match
- no additional syncs are required, i.e. copyAndPermute and communication are both either on host or on device
If these conditions hold, then the `imports_` view can be aliased to part of the MV's data view, and `unpackAndCombine` can be skipped.
> Tpetra: Skip unpackAndCombine

- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/test/unit_tests/CMakeLists.txt
- packages/muelu/test/unit_tests/RAPShiftFactory.cpp
- packages/muelu/test/unit_tests/Smoothers/BelosSmoother.cpp
- Recognize MLS in ML2MueLu translator. @skennon10 
- Fix some tolerances so that unit tests pass with float.
- Disable StratimikosSmoother unit test for no-Tpetra builds.
> MueLu stuff

- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestOverlappingRowMatrix.cpp
- packages/tpetra/core/src/CMakeLists.txt
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_Behavior.cpp
- packages/tpetra/core/src/Tpetra_Details_Behavior.hpp
- packages/tpetra/core/src/Tpetra_Details_Transfer_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_Transfer_def.hpp
- packages/tpetra/core/src/Tpetra_Details_getGraphOffRankOffsets.cpp
- packages/tpetra/core/src/Tpetra_Details_getGraphOffRankOffsets_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_getGraphOffRankOffsets_def.hpp
- packages/tpetra/core/src/Tpetra_Details_residual.hpp
- packages/tpetra/core/test/CrsGraph/CrsGraph_UnitTests1.cpp
- packages/tpetra/core/test/ImportExport/ImportExport_UnitTests.cpp
- Add `isLocallyFitted` to `Details::Transfer` (and hence `Import` and `Export`). This can be cheaper than calling `Map`'s `isLocallyFitted`, since comparison of local indices is avoided.
- Skip `copyAndPermute` in `Details::residual` if domain and column map are locally fitted (OFF by default).
- Add method `computeLocalOffRankOffsets` to `CrsGraph`.
- Use Kokkos Kernels SpMV launch parameters for Tpetra's residual, they currently are a copy anyways, except for the HIP part that was recently added to Kokkos Kernels.
- Implement communication/computation overlap for Tpetra's residual (OFF by default).
- Add environment variables `TPETRA_SKIP_COPY_AND_PERMUTE` and `TPETRA_OVERLAP`
I ran `MueLu_Driver.exe` on 2 nodes, 8 GPUs of Lassen, UVM=OFF:
```
jsrun -M "-gpu" -p 8 -r 4 …
```
> Tpetra: residual changes

- cmake/ctest/drivers/atdm/utils/setup_env.sh
CC: @sebrowne, @tcfisher, @dc-snl, @glhenni, @jwillenbring
An application team is reporting failures in their integration builds due to the build stat wrappers. It's not clear to me whether something has changed recently but when the application tries to build, the `CMAKE_AR` vars point to build stat wrapper scripts in the original build directory (outside of the install directory); however, the build directory is not readable by group or world. This PR works around this permission issue by simply disabling the wrappers for now; @bartlettroscoe or @jjellio can you please work with the application team and look into re-enabling the wrappers at a later point?
On ats2 via:
```bash
source cmake/std/atdm/load-env.sh  Trilinos-atdm-ats2-cuda-10.1.243-gnu-7.3.1-spmpi-rolling_static_opt
mkdir …
```
> Framework: Disable build stats

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
Fixes an ALEGRA test, and does not seem to adversely affect any MiniEM or EMPIRE results. 
@skennon10
> MueLu RefMaxwell: Change default behavior for applying BCs to A_nodal

- packages/trilinoscouplings/examples/scaling/Maxwell.xml
MueLu's QR uses too much L0 scratch memory on GPU.
> TrilinosCouplings: Skip QR in Maxwell example

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp
@trilinos/xpetra @trilinos/muelu 
Second attempt to switch the default for applying BCs to A_nodal. The code should now match ML.
The diagonal fix in Xpetra now avoids creating a second matrix if possible.
> MueLu: Switch default for enforcing BCs on auxiliary matrix

- cmake/std/PullRequestLinuxDriver.sh
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_assembly_HEX.hpp
- packages/tpetra/core/example/Finite-Element-Assembly/fem_assembly_InsertGlobalIndices_FE.hpp
- packages/tpetra/core/src/Tpetra_Assembly_Helpers.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_FECrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_FECrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_FECrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_FECrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_FEMultiVector_decl.hpp
- packages/tpetra/core/src/Tpetra_FEMultiVector_def.hpp
- packages/tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp
- packages/tpetra/core/test/FECrsMatrix/FECrsMatrix_UnitTests.cpp
- packages/tpetra/core/test/FEMultiVector/FEMultiVector_UnitTests.cpp
- packages/tpetra/core/test/FEMultiVector/Fix3101.cpp
- packages/tpetra/core/test/MatrixMatrix/FECrs_MatrixMatrix_UnitTests.cpp
- packages/trilinoscouplings/examples/scaling/example_Maxwell_Tpetra.cpp
- packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrixFactory.hpp
Adds separate Assembly and Modify stages to FECrsMatrix objects.  These replace usage of `beginFill`, `endFill`, and `resumeFill` in client code.  Example usage:
```c++
Tpetra::FECrsMatrix<> A = Tpetra::FECrsMatrix(domain_map, range_map);
A.beginAssembly();
// Assembly
A.endAssembly();
A.beginModify();
// Apply boundary conditions to A
A.endModify();
```
@ikalash - can you mention/tag any Albany developers that will be impacted?
Make semantics between `FECrsGraph`, `FECrsMatrix`, and `FEMultiVector` consistent with each other and consistent with FE literature.
> Tpetra: FECrsMatrix: add separate Assemble and Modify stages

- packages/sacado/test/UnitTests/Fad_CommTests.hpp
- packages/sacado/test/performance/fenl_assembly/fenl_functors.hpp
- packages/sacado/test/performance/fenl_assembly_view/fenl_functors.hpp
Fixes possible seg-faults in the Fad Kokkos Comm tests on CUDA when not using CUDA-aware MPI and UVM is disabled.  This is a kludge and should really be addressed at a higher level in Trilinos/Teuchos.
> Sacado fix non cuda aware mpi

- packages/piro/src/Piro_NOXSolver_Def.hpp
- packages/piro/src/Piro_PerformAnalysis.cpp
- packages/piro/src/Piro_SteadyStateSolver.hpp
- packages/piro/src/Piro_SteadyStateSolver_Def.hpp
- packages/piro/src/Piro_ThyraProductME_Constraint_SimOpt.hpp
- packages/piro/src/Piro_ThyraProductME_Objective_SimOpt.hpp
- passing directly the Piro parameterList to ThyraROL objects, to simplify code
- enbabling the option of explicitly transposing the matrix when computing the reduced Hessian
@trilinos/piro
Missing support for explicitly transposing the matrix when computing the reduced Hessian.
relevant Piro and Albany tests pass
> Piro: changes related to the option of explicitly transposing the Jacobian

- packages/panzer/disc-fe/src/Panzer_ConvertNormalToRotationMatrix.hpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.hpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_IntrepidOrientation.cpp
- packages/panzer/disc-fe/src/Panzer_L2Projection.cpp
- packages/panzer/disc-fe/src/Panzer_SubcellConnectivity.cpp
- packages/panzer/disc-fe/src/Panzer_SubcellConnectivity.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
- packages/panzer/disc-fe/src/evaluators/Panzer_Sum_impl.hpp
- packages/panzer/disc-fe/test/core_tests/evaluators.cpp
- packages/panzer/disc-fe/test/core_tests/hierarchic_team_policy.cpp
- packages/panzer/disc-fe/test/core_tests/integration_values2.cpp
- packages/panzer/disc-fe/test/core_tests/zero_sensitivities.cpp
All IntegrationValues2 tests updated to run without UVM.
> Panzer: remove UVM use from IntegrationValues

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
* Closes #9160
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of 
Originally reported by Sierra although it wasn't a blocker for them. 
There were already lots of unit tests for offset view MVs, just none that took offset views of column subviews. So I added a test for that in MultiVector_UnitTests.
Mark had left this comment in the offset view constructor:
```
// FIXME (mfh 29 Sep 2016) If we just use X.view_ here, it breaks
// Ifpack2's Gauss-Seidel implementation (which assumes the
// ability to create domain Map views of column Map MultiVectors,
// and then get the original column Map MultiVector out again).
// If we just use X.origView_ here, it breaks the fix for #46.
// The test for rowOffset == 0 is a hack that makes both …
```
> Tpetra: add test and fix for #9160

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
- packages/panzer/adapters-stk/test/stk_interface_test/tSTK_IO.cpp
Implement an addInformationRecords() method that adds a vector of strings
to the Panzer STK Interface.  The strings are depuped as they are added
and then added to the STK mesh during setupExodusFile().
* Closes #9436 
addInformationRecords() is tested by PanzerAdaptersSTK_tSTK_IO.exe.
> Panzer: implemet a method to add IOSS information records to the output

- packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp
We can only take the shortcut in `CheckRepairDiagonal` if all diagonal entries are present on all ranks.
Should fix #9455
> Xpetra: Fix bug in CheckRepairMainDiagonal

- cmake/std/PullRequestLinuxCuda10.1.243TestingSettings.cmake
The build PR-cuda10.1.243-test-Trilinos_pullrequest_cuda_10.1.243
is set to be added to the nightly Develop->master builds and needs
to be clean. These tests have been detailed in #8129 and the referenced
tickets therein for some time. This will disable them while the teams
sort out remaining issues.
* Closes $8129
> This turns off the tests failing on the Vortex build

- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
Change the PL validation depth to 1 from the default value of 1000. This
is ensure the 'Time Step Control Strategy' sublist is not validated
because Tempus has no way of validating the application sublist TSCS.
The idea is to leave the validation to the each individual TSCS class.
When an application code (e.g. Drekar) provides a sublist defining its own TSCS, the Integrator PL validation fails since the additional sublist is not found in the default PL. This PR changes the depth of the PL validation to 1 from the default value of 1000. This will limit the `Time Step Control Strategy` sublist from being validated. 
The sublist validation from the `Time Step Control Strategy` is now left to the TSCS class to validate the PL. This means each application will be responsible …
> Tempus: change integrator pl validation depth to 1

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.hpp
@rppawlo 
This follows our discussion in the Drekar meeting today. This is an initial PR to change the framework to allow for more options when it comes to rebalancing. A following PR will add an option to the list to rebalance the mesh according to Percept family trees if the information is available.
Testing it on my end now so I won't set automerge, but also the autotester should catch any issues, and I designed the code to make sure it's backwards compatible.
> Panzer: Allow for multiple types of mesh rebalancing in ExodusReaderFactory

- packages/intrepid2/src/Shared/Intrepid2_Kernels.hpp
Fixes https://github.com/xsdk-project/xsdk-issues/issues/141, most likely broken by https://github.com/trilinos/trilinos/commit/2dd64d20e518ab2694aa2534981abe35146a7b64, i.e, https://github.com/trilinos/Trilinos/pull/8917. Before that pull request `Intrepid2::Impl::CellTools::Serial::mapToReferenceFrame` could be used for rank-1 views.
Fixes https://github.com/xsdk-project/xsdk-issues/issues/141.
In combination with https://github.com/ORNL-CEES/DataTransferKit/pull/600 `DataTransferKit`'s tests run successfully with a recent Trilinos commit.
Since this only allows using `norm` for rank-1 Kokkos::Views, this pull request should be backward-compatible.
> [Intrepid2]  Allow using Intrepid2::Kernels::Serial::norm also for rank-1 views 

- packages/tempus/src/Tempus_AdjointAuxSensitivityModelEvaluator_decl.hpp
- packages/tempus/src/Tempus_AdjointAuxSensitivityModelEvaluator_impl.hpp
- packages/tempus/src/Tempus_AdjointSensitivityModelEvaluator_decl.hpp
- packages/tempus/src/Tempus_AdjointSensitivityModelEvaluator_impl.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity.cpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity.cpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_decl.hpp
- packages/tempus/src/Thyra_ImplicitAdjointModelEvaluator.hpp
- packages/tempus/src/Thyra_TpetraExplicitAdjointModelEvaluator.hpp
- packages/tempus/test/BackwardEuler/Tempus_BackwardEuler_ASA.cpp
- packages/tempus/test/TestModels/SinCosModel.cpp
- packages/tempus/test/TestModels/SinCosModel_decl.hpp
- packages/tempus/test/TestModels/SinCosModel_impl.hpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraExplicitAdjointModelEvaluator.hpp
Very few Trilinos solvers/preconditioners support solving transposed
linear systems, therefore we often have to resort to explicitly
transposing the matrix or assembling a transposed matrix directly for
adjoint sensitivities.  To better support this case, I extended the
Tempus adjoint integrator implementations to accept an additional
"adjoint" model evaluator for computing the adjoint W/W_op.  This is
necessary because there is currently no adjoint outArg that can be
requested.  I also included an adapter for the case of an implicitly
computed transpose, allowing for a single implementation.  I also
included a prototype Tpetra implementation that explicitly forms the
transpose, but it isn't tested.  Finally I modified the SinCosModel to
provide an explicit adjoint ME, and modified one of …
> WIP Tempus:  Add support for specifying the adjoint through a 2nd ME

- packages/xpetra/src/CrsGraph/Xpetra_EpetraCrsGraph.cpp
- packages/xpetra/src/CrsMatrix/Xpetra_CrsMatrix.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.cpp
- packages/xpetra/src/Export/Xpetra_EpetraExport.cpp
- packages/xpetra/src/Import/Xpetra_EpetraImport.cpp
- packages/xpetra/src/Map/Xpetra_EpetraMap.cpp
- packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.cpp
- packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.cpp
- packages/xpetra/src/MultiVector/Xpetra_MultiVector_decl.hpp
- packages/xpetra/src/Vector/Xpetra_EpetraIntVector.cpp
- packages/xpetra/src/Vector/Xpetra_EpetraVector.cpp
- packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
- packages/xpetra/test/MultiVector/MultiVector_UnitTests.cpp
Enabling HIP support in Xpetra to allow propagation of HIP backend to Zoltan2 and MueLu
* Closes 
* Blocks 
* Follows 
* Precedes 
* Related to #9322 
* Part of 
* Composed of 
ExaWind, SPARC and EMPIRE care about this feature as they are targeting AMD architectures 
All testing was performed on Spock (OLCF pre-Frontier AMD testbed)
> Xpetra: HIP support

- packages/tpetra/core/src/Tpetra_Distributor.hpp
- packages/tpetra/core/test/Distributor/Issue1454.cpp
- packages/tpetra/core/test/PerformanceCGSolve/cg_solve_file.cpp
The changes in this pull request are necessary to pass the tests when building with `Tpetra` and `MPI` enabled using the `SYCL` backend in `Kokkos`. In particular, there were some changes necessary to run the PerformanceCGTest benchmark. This pull request also adds the corresponding changes for `HIP`.
It's debatable if we just want to allow using `SYCLSharedUSMSpace` for MPI communication or not, but I decided to mirror `CUDA` instead of `HIP` here since `SYCLSharedUSMSpace` corresponds to `SYCLSharedUSMSpace` whereas `HIPHostPinnedSpace` is somewhat different.
I checked that the tests run correctly on Intel GPUs.
> Tpetra: Fix compiling and running with SYCL and MPI

- packages/panzer/adapters-stk/test/stk_interface_test/CMakeLists.txt
- packages/panzer/adapters-stk/test/stk_interface_test/tSTKRebalancing.cpp
@rppawlo 
I'm working on Percept-based mesh rebalancing for use with multigrid for Drekar (i.e. next PR will add the "percept" option for the "Rebalancing" parameter), but I'd like to add new tests first so that I can make sure this is the right direction for testing. I'm setting this test to use only 4 MPI ranks because rebalancing really doesn't make sense on 1 MPI rank, and later I will need 4 MPI ranks to make sure it's behaving as I'd like. I'm using Pamgen meshes for the tests because it doesn't make sense to regularly refine an inline mesh, but I cannot open an exodus file in emacs.
I've tested this on my machine, vaporwave, and it runs and passes.
> Panzer: Add tests to cover mesh rebalancing options

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.hpp
This PR fixes typos in `faceGlobalId()` that reference edge instead of face.  The first is just a parameter with the wrong name.  The second is the use of the wrong lookup vector which could cause a crash.
* Blocks #9491
* Precedes #9491 
These changes are tested by tExodusEdgeBlock and tExodusFaceBlock which have been updated in the related PR.
> Panzer: fix edge vs face typo that could crash in faceGlobalId()

- packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp
This fixes a view space so you can compile miniEM without UVM on for cuda, there are a lot of bugs still in the code so it won't run/pass but this is a small step for that end.
> Have space correct for get orientations

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeHexMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeHexMeshFactory.hpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeTetMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_CubeTetMeshFactory.hpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareQuadMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareQuadMeshFactory.hpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareTriMeshFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_SquareTriMeshFactory.hpp
- packages/panzer/adapters-stk/test/stk_interface_test/tCubeHexMeshFactory.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tCubeTetMeshFactory.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tExodusEdgeBlock.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tExodusFaceBlock.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tExodusReaderFactory.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tSquareQuadMeshFactory.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tSquareTriMeshFactory.cpp
The CubeHex, CubeTet, SquareQuad and SquareTri mesh factories and Exodus reader had inconsistent parameter names and defaults for the creation of edge and face blocks.  This PR gives all of them 2 parameters (`Create Edge Blocks` and `Create Face Blocks`) which default to `false`.  In addition, if the CubeHex parameter `Build Subcells` is `false` both of the new parameters will forced to `false` and a message printed to `out`.
* Closes #9447
* Is blocked by #9490
* Follows #9490
Each factory has an associated test that has been updated with new tests to cover the new parameters.  The `tExodusEdgeBlock` and `tExodusFaceBlock` tests have been updated also.
> Panzer: make the edge/face block parameters consistent across mesh factories

- packages/piro/src/Piro_PerformAnalysis.cpp
- packages/piro/src/Piro_ThyraProductME_Objective_SimOpt.hpp
- packages/piro/test/_input_Analysis_ROL_Tpetra.xml
Generalization of  the parameter list for defining Hessian based dot product.
Now the parameter list looks like:
```
Matrix Based Dot Product:
Matrix Type: Hessian Of Response
Matrix Types:
Hessian Of Response:
Response Index: 0
Block Diagonal Solver:
Block 0:
Linear Solver Type: Belos
```
At the moment `Matrix Type` can either be `Identity` (usual l2 dot product) or the `Hessian Of Response`.
The user also has to provide the Index of the Reponse used to compute the Hessian dot product
@trilinos/piro
This makes the input file easier to read and allows to future extension to different matrix based dot product.
Modified Piro test input file to exercise the new syntax.
> Piro: work on the Hessain based implementation of ROL dot product

- cmake/TPLs/FindTPLCholmod.cmake
Related to https://github.com/kokkos/kokkos-kernels/pull/1066.
This change is required to link `KokkosKernels_sparse_sptrsv_cholmod.exe`.
This was tested via:
```
$ cmake -DTPL_ENABLE_METIS:STRING=ON -DMETIS_LIBRARY_DIRS=$METIS_ROOT/lib -DTrilinos_ENABLE_OpenMP:BOOL=ON -DKokkos_ENABLE_OPENMP:BOOL=ON -DKokkosKernels_ENABLE_TESTS=ON -DTrilinos_ENABLE_KokkosKernels:BOOL=ON -DTPL_ENABLE_SuperLU:STRING=ON -DSuperLU_LIBRARY_DIRS=$SUPERLU_ROOT/lib -DSuperLU_INCLUDE_DIRS=$SUPERLU_ROOT/include -DTPL_ENABLE_BLAS=ON -DBLAS_LIBRARY_DIRS=$BLAS_ROOT/lib -DBLAS_INCLUDE_DIRS=$BLAS_ROOT/include -DKokkosKernels_ENABLE_SUPERNODAL_SPTRSV=ON -DTPL_ENABLE_Cholmod:STRING=ON -DCholmod_LIBRARY_DIRS=${SUITESPARSE_ROOT}/lib ..
<snip>
make -j
<snip>
$ …
```
> cmake/TPLS: Update libs for linking KokkosKernels_sparse_sptrsv

- packages/intrepid2/src/Shared/Intrepid2_Data.hpp
See Issue #9523.
Closes #9523.
Various Intrepid2 unit tests exercise Data construction.
> Intrepid2: eliminate extra zero view allocations in Data construction

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Interface/MueLu_HierarchyManager.hpp
- packages/muelu/src/MueCentral/MueLu_Hierarchy_decl.hpp
- packages/muelu/src/MueCentral/MueLu_Hierarchy_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
If you set:
```
<Parameter name="debug: graph level" type="int" value="-1"/>
```
you now get *all* the levels.
Tests: n/a (debugging capability)
Stakeholder feedback: n/a (developer-only feature).
> MueLu: Adding complete hierarchy Factory graph dump capability

- packages/framework/pr_tools/pullrequest-specs.ini
- packages/framework/pr_tools/trilinosprhelpers/unittests/pullrequest-specs.ini
- packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py
- packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py
Without this the python job will build and test
everything the gcc 7.2 job does as we do not
generate a specific packageEnables.cmake file
but instead use the one based on the diffs.
Too much testing 
Used the unit testing after changing the default
> This just changes the python job name to match the jenkins job

- packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp
- packages/belos/src/BelosStatusTestOutputFactory.hpp
This PR addresses issue #9522 where the PseudoBlockGmresSolMgr was crashing due to an attempt to change the Output Style.  The Output Factory was getting invalid input.  I have fixed the pseudoblock GMRES solver manager to pass in the correct input.  I have also added a 'default' case to the output factory so that it cannot crash due to an invalid output style. 
I checked the other Belos solver managers, and none of them seem to have the same issue of passing invalid input to the Output Factory.  
Note: An alternative (possibly more 'correct') fix for this issue would have been to change the Output Factory to accept a `Belos::OutputType` instead of `int`.  Since this change would require updating all the solver managers, I did not make that change at this time.
> Belos: Fix Output Style Crash, Issue #9522

- packages/muelu/test/unit_tests/MapTransferFactory.cpp
Fix mismatch in indentation and curly braces around the body of an `if`-statement in a unit test of the `MapTransferFactory`.
* Closes #9484 
n/a
Existing tests pass. I also have verified, that the intention of the modified test is not altered and that it still tests the same feature of the `MapTransferFactory`.
> MueLu: fix misleading indentation in unit test

- packages/panzer/adapters-stk/test/gather_scatter_evaluators/gs_evaluators.cpp
@alanw0 reported a compiler issue due to missing system header. The code in question was not being used. Just deleted it.
> Panzer: remove unused code

- packages/panzer/adapters-stk/test/panzer_workset_builder/d_workset_builder.cpp
- packages/panzer/adapters-stk/test/panzer_workset_builder/d_workset_builder_3d.cpp
- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
Tests fixed:
There're lots of whitespace trim changes, so for easier readability I'd suggest using GitHub's "Hide whitespace changes" option.
Main workset_builder test will be added in separate PR.
> Fix Panzer's workset_builder tests with UVM disabled (1/2)

- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/src/Interface/MueLu_MLParameterListInterpreter_def.hpp
Using the defaults from ML shouldn't require Epetra.
> MueLu: Don't require Epetra for ML defaults

- packages/seacas/applications/aprepro/CMakeLists.txt
- packages/seacas/applications/aprepro/test.stderr.gold
- packages/seacas/libraries/aprepro_lib/CMakeLists.txt
- packages/seacas/libraries/aprepro_lib/test.stderr.gold
Replaced the last test that was relying on a robust diff of stderr to no longer do that.  Many HPC platforms were polluting the stderr output and that resulted in non-robust testing.  The test no longer relies on a diff of stderr and instead just checks the contents of files that apepro itself writes directly.
> SEACAS: Aprepro - do not diff stderr in tests

- cmake/std/atdm/ATDMDisables.cmake
Per our discussion in the meeting today, attempt to address intermittent timeout reported in #6805.
Verified change via `nohup env ATDM_CTEST_S_DEFAULT_ENV=cee-rhel7-default Trilinos_PACKAGES=KokkosKernels ./ctest-s-local-test-driver.sh cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_opt &> ctest-s-local-test-driver.out &` - see [cdash](https://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2021-08-24&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=Trilinos-atdm-cee-rhel7_cuda-10.1.243_gnu-7.2.0_openmpi-4.0.3_shared_opt&field2=groupname&compare2=63&value2=Experimental). Looking in the cmake cache shows:
```
$ grep -i run_serial CMakeCache.txt
KokkosCore_UnitTest_CudaInterOpInit_MPI_1_SET_RUN_SERIAL:BOOL=ON …
```
> atdm: mark KokkosKernels_sparse_cuda as RUN_SERIAL

- packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestChebyshev.cpp
- packages/muelu/src/Interface/MueLu_ML2MueLuParameterTranslator.cpp
- packages/muelu/test/interface/default/Output/MLsmoother4b_epetra.gold
Add option to compute the spectral radius of D^-1 A using CG. Can be selected via "eigen-analysis: type" = "cg".
ML uses CG by default. This will simplify transitioning from ML to MueLu.
> Ifpack2 Chebyshev: Add CG option for computation of spectral radius

- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/CrsMatrix/CMakeLists.txt
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_ReplaceDomainMapAndImporter.cpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_ReplaceRangeMapAndExporter.cpp
Implementing replaceDomainMap, replaceRangeMap, replaceRangeMapAndExporter to complement existing replaceDomainMapAndImporter, as recommended in #9451 
Unfortunately, these methods do not resolve the issue #9391 (creating a new matrix with the same local graph, rowMap and columnMap as an existing matrix, but different Range and Domain maps).  See further notes in re-opened issue #9391.
New tests added to CrsMatrix_replaceDomainMapAndImporter.cpp to exercise new replaceDomainMap (both with a different map and the same map).
New file of tests CrsMatrix_replaceRangeMapAndExporter.cpp to exercise new replaceRangeMap (both with a different map and the same map) and replaceRangeMapAndExporter.
Tested on mac with gcc 8.5 and openmpi 1.10.7.
> Tpetra:  added methods to replace Domain and Range maps in CrsMatrix and CrsGraph

- packages/intrepid2/src/Discretization/Basis/Intrepid2_TensorBasis.hpp
@mperego @kyungjoo-kim
Shadowed declaration of `DeviceType` in class scope; there are several other declarations in function scope which seem to be no longer needed.
N/A
N/A
> Intrepid2: fix shadowed DeviceType declarations in function scope

- packages/tpetra/core/test/CrsMatrix/Bug7745.cpp
The test Bug7745.cpp has more than normal false-alarm failures.  It spewed a lot of output, which would sometimes mess up the output that the Teuchos test harness seeks to determine pass/fail.
This PR reduces the amount of output produced by the test, with the hope that reducing the output will reduce the false alarms.
Tested on ascicgpu033
> Tpetra:  reduce false alarms from test Bug7745.cpp

- cmake/std/PullRequestLinuxCuda10.1.105uvmOffTestingSettings.cmake
Both `TrilinosCouplings_Example_Maxwell_MueLu_MPI_1` and `TrilinosCouplings_Example_Maxwell_MueLu_MPI_4` seem to be fixed already. We can re-enable them.
> Re-enable TrilinosCouplings tests that were previously disabled for Cuda UVM off

- packages/nox/src/NOX_Solver_LineSearchBased.C
- packages/nox/src/NOX_Solver_LineSearchBased.H
@trilinos/nox @rppawlo 
A number of packages inside the linear/nonlinear solver stack will throw an exception if a bad state is encountered. For time-dependent simulations that we are running in drekar, it is often possible to recover from such errors by reducing the timestep size and trying again. This pull request adds a boolean option `"Catch Throws During Solve"` for the line-search based solver in NOX that will:
- Catch an exception that is thrown during the call to `solve`.
- Print out a warning containing the text string defined within the exception that is thrown.
- Mark and return a solver status of `Failed`, so that the time integrator can make adjustments as needed.
* Closes rppawlo/DrekarBase#375
Brief testing in drekar gives the expected behavior with and without the flag …
> Adding flag to NOX line search solver to enable catching of exceptions thrown by linear solvers

- packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_kokkos_def.hpp
- packages/muelu/test/unit_tests_kokkos/SemiCoarsenPFactory_kokkos.cpp
MueLu can again be compiled with `Tpetra_ENABLE_DEPRECATED_CODE=OFF`
> MueLu: Make MueLu free of Tpetra deprecated code

- packages/tempus/src/Tempus_SolutionStateMetaData_decl.hpp
- packages/tempus/src/Tempus_SolutionStateMetaData_impl.hpp
- packages/tempus/src/Tempus_SolutionState_decl.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyIntegralController.hpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeStepControlStrategyIntegralController.cpp
In TimeStepControlStrategyIntegralController, there was member
data (relative error norms for current timestep and the last
two timesteps) being stored that is related to the solution.
This data should be stored in SolutionStateMetaData, so that
when restart data is being written, it can be with the other
solution metadata and read back in.
Unit tests were added to cover the new functionality.
See above.
* Closes #8399
See above.
> Tempus: Make TimeStepControlIntegralController Restartable

- packages/nox/src-thyra/NOX_Thyra_Group.C
@trilinos/nox @rppawlo 
Certain tests in drekar have run into an issue when right scaling weights are used that results in a null pointer dereference and segfault. This has been traced back to `scaled_x_vec_` not being initialized in all cases. This pull request resolves the issue by making sure `scaled_x_vec_` gets allocated whenever `right_weight_vec_` is not null.
* Closes rppawlo/DrekarBase#583
> Fix RCP initialization in NOX thyra group to avoid null pointer dereference

- packages/phalanx/test/Field/CMakeLists.txt
- packages/phalanx/test/Field/NonConstDynRankViewFromConstMDField.cpp
Example on converting const MDFields to non-const DynRankViews. Needed for some changes to basis values.
Fixes issue
New test added to cover this capability: phalanx/test/example/NonConstDynRankViewFromConstMDField.cpp
> Panzer: example for converting const MDField to nonconst DRV

- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_decl.hpp
- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_Tpetra_impl.hpp
- packages/panzer/dof-mgr/src/Panzer_GlobalIndexer.hpp
@trilinos/panzer @rppawlo 
The existing implementations of the Jacobian specializations of the ScatterResidual evaluators for Tpetra in panzer make use of temporary arrays with a fixed size of 256 elements. When running problems with large numbers of equations, it is possible to exceed this limit. This pull request modifies the implementation of these evaluators to use Kokkos::Views as scratch space, in order to support arbitrary system sizes.
* Closes rppawlo/DrekarBase#379
Existing tests are passing on a serial CPU build. The performance impact on CUDA builds has not yet been evaluated.
> Update panzer Tpetra (blocked and non-blocked) ScatterResidual evaluators to handle arbitrary numbers of LIDs

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/test/unit_tests/CoalesceDropFactory.cpp
- packages/muelu/test/unit_tests_kokkos/CoalesceDropFactory_kokkos.cpp
When `CoalesceDrop` is dropping quite aggressively, it can happen that only the diagonal element of a row remains. In that case, this row should also be tagged as a Dirichlet boundary.
> MueLu: Tag isolated nodes as Dirichlet

- packages/tempus/src/Tempus_IntegratorBasic.cpp
- packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
- packages/tempus/test/BDF2/Tempus_BDF2Test.cpp
- packages/tempus/test/BackwardEuler/Tempus_BackwardEulerTest.cpp
- packages/tempus/test/ExplicitRK/Tempus_ExplicitRKTest.cpp
- packages/tempus/test/ForwardEuler/Tempus_ForwardEulerTest.cpp
- packages/tempus/test/Subcycling/Tempus_SubcyclingTest.cpp
- packages/tempus/test/Trapezoidal/Tempus_TrapezoidalTest.cpp
Edge case: when app is only using its own TSCS in a composite, TSC
fails initialization because the app has not had the chance to add its
TSCS to the compose vector yet. So this `runInitialize` (default: true)
allow the app to delay the initialization until it has populated the
composite vector and explicitly calls the initialization.
In Drekar when only using `TimeScale` TSCS, Tempus tries initializing TSC but the vector size is zero since Drekar has not had the chance to add the App's own TSCS. This is not the case if the `Time Step Control Strategy List` contains at least one TSCS that Tempus can add to the composite vector. But if all the strategies are unique to the App, the composite vector size is zero and fails the assertion and the initialization.
> Tempus: add default flag to delay initialization

- cmake/tribits/core/package_arch/TribitsConstants.cmake
- packages/epetra/src/Epetra_C_wrappers.h
- packages/epetra/src/Epetra_Import_Util.h
- packages/epetra/src/Epetra_LinearProblemRedistor.h
- packages/epetra/src/Epetra_SerialDenseSVD.h
- packages/epetra/src/Epetra_Util.h
- packages/ifpack/src/Ifpack_SerialTriDiMatrix.h
- packages/ifpack/src/Ifpack_SerialTriDiSolver.h
- packages/teuchos/numerics/src/Teuchos_BLAS.cpp
- packages/teuchos/parameterlist/src/Teuchos_ParameterListAcceptorDefaultBase.hpp
@trilinos/epetra @trilinos/teuchos @trilinos/ifpack
Fixes a number of minor issues when building for windows (in particular a MinGW cross compile from linux - though most of the issues are applicable to MSVC also). Details of each particular change are in the commit message. With these changes, my specific configuration of Trilinos builds fully for Windows.
Automated build testing for all platforms I have access to was done in https://github.com/JuliaPackaging/Yggdrasil/pull/3569. No functional changes expected.
> Fix various windows build issues

- packages/amesos2/src/Amesos2_Superlumt_def.hpp
This PR disables NON_CONTIGUOUS_AND_ROOTED option for SuperLU_MT interface in Amesos2. This option does not exist anywhere else in Amesos2, and this change allows me to build Amesos2 with SuperLU-MT (< version 3).
I am running a stand-alone solver test with SuperLU on Blake.
> Amesos2: disable NON_CONTIGUOUS_AND_ROOTED option for SuperLU_MT

- .github/workflows/stale.yml
The stale issue/pr actions bot has updated to v4.x
This PR updates the version number of the bot to the 4.x branch.
> Framework: Update the stale bot to use v4.x

- packages/muelu/src/Transfers/Energy-Minimization/Solvers/MueLu_CGSolver_def.hpp
- packages/muelu/src/Transfers/Energy-Minimization/Solvers/MueLu_GMRESSolver_def.hpp
- packages/panzer/disc-fe/src/lof/Panzer_TpetraLinearObjContainer.hpp
- packages/panzer/disc-fe/test/la_factory/tBlockedTpetraLinearObjFactory.cpp
- packages/panzer/disc-fe/test/la_factory/tTpetraLinearObjFactory.cpp
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
- packages/teko/examples/BuildPreconditioner/example-driver-belos.cpp
- packages/teko/tests/src/Tpetra/tBlockedTpetraOperator.cpp
- packages/teko/tests/src/Tpetra/tStridedTpetraOperator.cpp
- packages/teko/tests/src/tExplicitOps_tpetra.cpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests4.cpp
- packages/tpetra/core/test/inout/MatrixMarket_Tpetra_CrsMatrix_Dist_Binary.cpp
- packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
- packages/zoltan2/test/core/TpetraCrsColorer/TpetraCrsColorer.cpp
@trilinos/muelu @trilinos/panzer @trilinos/teko @trilinos/xpetra @trilinos/zoltan2
Code changes to address #9640 and #9658 .
Removed tests for isFillActive() in scale() and setAllToScalar(), removing need for resumeFill/fillComplete around calls to these functions #9640
tpetra:  removed caching of Frobenius norm value; there was no way to guarantee that the cached value would be correct since resumeFill/fillComplete is not required to change matrix values. #9658
muelu, panzer, teko, xpetra, zoltan2:  removed resumeFill/fillComplete that are no longer needed in light of these changes.  Not calling fillComplete should reduce execution time.
* Closes #9640 #9658
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
Tested with clang PR test script on …
> Tpetra:  removed need for matrix to have isFillActive()=true in scale() and setAllToScalar()

- packages/tempus/src/Tempus_TimeEventBase.hpp
- packages/tempus/src/Tempus_TimeEventComposite.hpp
- packages/tempus/src/Tempus_TimeEventList.cpp
- packages/tempus/src/Tempus_TimeEventListIndex.cpp
- packages/tempus/src/Tempus_TimeEventListIndex_decl.hpp
- packages/tempus/src/Tempus_TimeEventListIndex_impl.hpp
- packages/tempus/src/Tempus_TimeEventList_decl.hpp
- packages/tempus/src/Tempus_TimeEventList_impl.hpp
- packages/tempus/src/Tempus_TimeEventRange.cpp
- packages/tempus/src/Tempus_TimeEventRangeIndex.cpp
- packages/tempus/src/Tempus_TimeEventRangeIndex_decl.hpp
- packages/tempus/src/Tempus_TimeEventRangeIndex_impl.hpp
- packages/tempus/src/Tempus_TimeEventRange_decl.hpp
- packages/tempus/src/Tempus_TimeEventRange_impl.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyComposite.hpp
- packages/tempus/src/Tempus_TimeStepControl_decl.hpp
- packages/tempus/src/Tempus_TimeStepControl_impl.hpp
- packages/tempus/test/ForwardEuler/Tempus_ForwardEulerTest.cpp
- packages/tempus/test/ForwardEuler/Tempus_ForwardEuler_SinCos.xml
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref.xml
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref2.xml
- packages/tempus/test/Integrator/Tempus_IntegratorTest.cpp
- packages/tempus/test/TestModels/SinCosModel_impl.hpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeEventBase.cpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeEventComposite.cpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeEventList.cpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeEventListIndex.cpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeEventRange.cpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeEventRangeIndex.cpp
- packages/tempus/unit_test/Tempus_UnitTest_TimeStepControl.cpp
* Added nonmember contructors for ParamterLists, getValidParameters(),
and changed full constructors signatures for
- TimeEventRange
- TimeEventRangeIndex
- TimeEventList
- TimeEventListIndex
- TimeEventComposite
* Added TimeEvents to TimeStepControl::getValidParameters().
* Added reading TimeEvents to createTimestepControl().
* Added timeEventType_ member data to identify the type of TimeEvent.
* In TimeStepControl
- Default construction of TimeEvents match previous specification
of output times and indices.
* Ensured the timeOfNextEvent(time) returns the NEXT event and not
event at current time.
* In TimeEventComposite
- Added means to find and replace a TimeEvent.
- Added method to return names on TimeEvents in composite.
* Added doxygen commments for many TimeEvent funcitons.
* Added …
> Tempus: Utilize TimeEvent in TimeStepControl

- packages/tempus/src/Tempus_AdjointAuxSensitivityModelEvaluator_decl.hpp
- packages/tempus/src/Tempus_AdjointAuxSensitivityModelEvaluator_impl.hpp
- packages/tempus/src/Tempus_AdjointSensitivityModelEvaluator_decl.hpp
- packages/tempus/src/Tempus_AdjointSensitivityModelEvaluator_impl.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_SolutionHistory_impl.hpp
For issue #9737:
* Add a fudge factor in findState() to allow for round-off
* Reset timeFinal in the adjoint model evaluators after the forward integration, because it may not match the final time requested.
> Tempus:  Fix two more adjoint sensitivity problems when t0 != 0

- packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_decl.hpp
- packages/xpetra/src/BlockedMultiVector/Xpetra_BlockedMultiVector_def.hpp
- packages/xpetra/src/BlockedVector/Xpetra_BlockedVector_decl.hpp
- packages/xpetra/src/BlockedVector/Xpetra_BlockedVector_def.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_EpetraCrsMatrix.hpp
- packages/xpetra/src/MultiVector/Xpetra_EpetraIntMultiVector.hpp
- packages/xpetra/src/MultiVector/Xpetra_EpetraMultiVector.hpp
- packages/xpetra/src/MultiVector/Xpetra_MultiVector_decl.hpp
- packages/xpetra/src/MultiVector/Xpetra_MultiVector_def.hpp
- packages/xpetra/src/MultiVector/Xpetra_TpetraMultiVector_decl.hpp
- packages/xpetra/src/MultiVector/Xpetra_TpetraMultiVector_def.hpp
- packages/xpetra/src/Vector/Xpetra_EpetraIntVector.hpp
- packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
- Add `randomize` method with limits to Xpetra's MV.
- Don't throw from `Xpetra::EpetraMultiVectorT::getDeviceLocalView`, but return a host view, add `setAllValues`.
- `EpetraCrsMatrixT` was caching its local matrix, since the rowptr had the wrong type and hence needed to be converted. I ran into some issue where the cache wasn't invalidated on reuse, so I removed the caching entirely.
> Xpetra: Epetra changes

- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybrid2GL.hpp
- packages/zoltan2/core/src/algorithms/color/Zoltan2_AlgHybridD1.hpp
#9615 reports compilation warnings due to mismatched printf formats and arguments.
This PR replaces printf with std::cout<<, allowing C++ to determine the print format.
This PR replaces PR #9764; rather than remove the warning-generating print statements, this PR replaces them with equivalent C++ statements.
@djglaze @tasmith4 
Tested on ascicgpu with serial node, sems gcc compilers.
Tested with GO = int and GO = long long.
> Zoltan2:  remove compiler warnings by using std::cout<< instead of printf

- doc/build_ref/TrilinosBuildReferenceTemplate.rst
The site trac.trilinos.org no longer exists. 
Resolves [TRILINOSHD-11](https://sems-atlassian-srn.sandia.gov/browse/TRILINOSHD-11).
> Remove link to trac.trilinos.org (TRILINOSHD-11)

- packages/kokkos-kernels/src/common/KokkosKernels_HashmapAccumulator.hpp
- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_impl_compression.hpp
(patching in changes from KokkosKernels #1118)
Note: already reviewed and merged in KokkosKernels. Just patching it in rather than waiting for next release.
Fixes SpGEMM on Nvidia Turing and Ampere by enabling the codepath for "independent thread scheduling", where a subset of threads in a warp can make progress while others are blocked.
SpGEMM unit tests (in sparse) failed on Perlmutter A100 without this change, but pass with this change.
> KokkosKernels: Fix #9155: spgemm on ampere

- cmake/RepositoryDependenciesSetup.cmake
- packages/seacas/CMakeLists.txt
- packages/seacas/cmake/SeacasDisableSubpackagesDependingOnFortran.cmake
@gsjaardema, @trilinos/seacas 
As per the TriBITS User's Guide section [How to check for and tweak TriBITS 'ENABLE' cache variables](https://tribitspub.github.io/TriBITS/users_guide/index.html#how-to-check-for-and-tweak-tribits-enable-cache-variables), logic that enables/disables subpackages needs to be performed before the package's `CMakeLists.txt` files start getting processed since this disable info needs to be feed into the global enable/disable logic. For example, if there is a downstream subpackage in say Panzer that depends on a specific subpackage in SEACAS, then we need to know that that SEACAS subpackage is disabled when processing the full set of enable/disable logic so we can disable the downstream Panzer subpackage that depends on that disabled
SEACAS subpackage.  Otherwise, …
> SEACAS: Move logic to disable SEACAS subpackages that depend on Fortran (trilinos/Trilinos#3346)

- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
This avoids NaNs in debug builds for linear solvers that don't zero out
or overwrite the initial guess.  Thanks to @ikalash for figuring this
out.  For Albany issue [#746](https://github.com/sandialabs/Albany/issues/746).
> Tempus:  Zero out initial guess for adjoint initial conditions solve

- packages/panzer/disc-fe/src/Panzer_IntegrationValues2.cpp
empire's trilinos sync was was failing due to recent changes to panzer integration rules.
Tests are now passing
> Panzer: fix 1D line mesh issue on cuda

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
TESTS: clang debug
Stakeholder feedback: pending
Issue: #9796
> Tpetra: Fixing subtle Kokkos use error

- packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
- packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
- packages/tpetra/core/src/Tpetra_Details_checkGlobalError.cpp
- packages/tpetra/core/src/Tpetra_HashTable_decl.hpp
- packages/tpetra/core/src/Tpetra_HashTable_def.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_Util.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_UnitTests.cpp
To me, it was weird to control Tpetra code with Teuchos' DEBUG macros.
This PR changes HAVE_TEUCHOS_DEBUG to HAVE_TPETRA_DEBUG in Tpetra code.
It also changes HAVE_TEUCHOS_MPI to HAVE_TPETRA_MPI in some cases.
In a few examples that also use Epetra, I let HAVE_TEUCHOS_MPI remain.
I removed a few never-used things, too.
Tested on ascicgpu030 with sems compilers, serial node.
> tpetra:  #9799 changed HAVE_TEUCHOS_DEBUG to HAVE_TPETRA_DEBUG

- packages/tpetra/core/inout/Tpetra_DistributionLowerTriangularBlock.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
As we removed UVM dependence from Tpetra, we saw that CrsGraph::getNodePackedIndices returned k_lclInds1D_, which was packed iff fillComplete was called with storageOptimized. Thus, if not storageOptimized, this function might return unpacked indices. However, unpacked indices aren't useful without the number of entries in each row, so the function's intent (indicated by its name) was more appropriate.
In the first round of UVM removal, we kept the existing behavior by returning views of the unpacked indices.
Now, with this PR, we change the behavior of CrsGraph's getNodePackedIndices and getNodeRowPtrs, and CrsMatrix's getAllValues (which uses the CrsGraph functions) to truly return packed indices, row pointers, and values, respectively, in all use cases.
Tested on …
> tpetra:  return packed indices always in getNodePackedIndices

- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spgemm_mkl_impl.hpp
PR fixes errors reported by @hkthorn of type:
```
/ascldap/users/ndellin/trilinos/Trilinos/Build/XyceConfig/packages/kokkos-kernels/src/impl/generated_specializations_cpp/spgemm_symbolic/Sparse_spgemm_symbolic_eti_DOUBLE_ORDINAL_INT_OFFSET_INT_LAYOUTLEFT_EXECSPACE_SERIAL_MEMSPACE_HOSTSPACE_MEMSPACE_HOSTSPACE.cpp(53): error: expected a "}"
```
Resolve compilation error with intel compilers and mkl tpls
@hkthorn please report that this resolves the problem in your builds as well
Reproduced error and tested that compilation succeeds with this change
> Fix bug with mkl spgemm

- packages/belos/tpetra/test/Native/diagonal_matrix.cpp
Belos's diagonal matrix apply was using Tpetra's ``MultiVector::getLocalView<device_type>(...)``
but this was incorrectly setting the "modified on host" flag when the device is
Cuda/CudaUVMSpace. The resulting view's execution space is Cuda, so it should definitely be considered a device view even though (being UVM) it's accessible from host. Instead, using ``MultiVector::getLocalViewDevice(...)`` correctly sets the
"modified on device" flag. This fixes 2 Belos test failures for when UVM
enabled in Tpetra, but this doesn't fix the behavior of ``getLocalView<device_type>`` for UVM - that can be a separate issue.
In a build with ``Tpetra_ENABLE_CUDA_UVM=ON``, these two tests were failing:
```
Belos_Tpetra_Native_CG_PIPELINE_diagonal_matrix_MPI_4 …
```
> Belos: fix issue with MultiVector modify flags

- packages/shylu/shylu_dd/frosch/src/InterfaceSets/FROSch_InterfaceEntity_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp
This PR specifies that FROsch is using Xpetra for Matrix, Vector, MultiVector types. 
- Kokkos-Kernels [Issue 1170](https://github.com/kokkos/kokkos-kernels/issues/1170)
- Corresponding [PR 1171](https://github.com/kokkos/kokkos-kernels/pull/1171) 
- Albany [Issue 758](https://github.com/sandialabs/Albany/issues/758)
@mperego has tested the fix with Albany for us.
This is a minimum patch to fix the build issue, and may require more consistent fix later.
> ShyLU -DD Frosch : fix build error with new Kokkos-Kernels

- packages/tpetra/core/CMakeLists.txt
During the UVM removal process, a configure option was added to allow developers to build Tpetra without UVM, even though it (UVM-off) was not guaranteed to work.  Now that it works, this option is obsolete and redundant -- users and developers can build with/without UVM by changing the value of Kokkos_ENABLE_CUDA_UVM.
N/A -- this is a build system change.
> Tpetra: remove obsolete configure option

- packages/kokkos-kernels/master_history.txt
- packages/kokkos/algorithms/src/Kokkos_Sort.hpp
- packages/kokkos/algorithms/unit_tests/TestSort.hpp
- packages/kokkos/bin/nvcc_wrapper
- packages/kokkos/containers/src/Kokkos_DynamicView.hpp
- packages/kokkos/core/src/Kokkos_CopyViews.hpp
- packages/kokkos/master_history.txt
Final 3.5.0 snapshot containing updates and fixes for issues reported by users
Autotester
> Kokkos snapshot

- packages/amesos2/src/Amesos2_Superlu_def.hpp
This PR fixes the option to use METIS with SuperLU (sequential).
- skip calling get-perm-c when use-METIS option is selected
- check for empty graph of A+A^T used to call METIS before freeing it
> Amesos2::SuperLU fix with option to use Metis

- packages/tpetra/core/inout/MatrixMarket_Tpetra.hpp
- packages/xpetra/sup/Utils/Xpetra_IO.hpp
@trilinos/tpetra @trilinos/xpetra 
This fixes two bugs in matrix reading:
1) The Tpetra matrix reader was allocating space based on a scalar max nnz per row, which could cause an out-of-memory error if one of the rows is (nearly) dense.
2) The Xpetra binary reader was calculating the number of nonzeros per row incorrectly.
Used primarily by developers.
> Tpetra: Xpetra: fix matrix reader

- packages/ifpack2/test/belos/belos_solve_longdouble.cpp
Something in Trilinos changed that changed slightly the matrices / vectors defined in this problem.  The problem signed up in the ST = long double build in the Trilinos tests: https://sems-cdash-son.sandia.gov/cdash/test/1838303.  Verified that precision of result given new matrix/vector is correct.
> Ifpack2: rebaselining long double test

- packages/piro/src/Piro_TempusSolver_Def.hpp
This PR corrects some logic that was incorrectly attempting to create an adjoint ME even when the adjoint ME passed in (from e.g., Albany) was null.  
@lxmota , can you please review, since this affects LCM?
> Piro: correcting logic

- packages/tempus/src/Tempus_Stepper_ErrorNorm_decl.hpp
- packages/tempus/src/Tempus_Stepper_ErrorNorm_impl.hpp
- packages/tempus/test/TestUtils/Tempus_UnitTestMainUtils.hpp
- packages/tempus/unit_test/CMakeLists.txt
- packages/tempus/unit_test/Tempus_UnitTest_Stepper_ErrorNorm.cpp
Investigated failing tests from Tempus_*_MPI_1 failing in Trilinos-atdm-ats1-knl_intel-19.0.4_mpich-7.7.15_openmp_static_opt build starting 2021-10-15 #9881
* Excluded the Intel compiler for FPE testing.
* Fixed an FPE divide-by-zero in Stepper_ErrorNorm
- Added unit test to cover it
* Added some doxygen on Stepper_ErrorNorm
Failing tests noted in #9881 
* Related to #9881 
Added unit test to cover discovered divide-by-zero.
> Tempus: Fix Failing Tests Due to FPE

- packages/nox/src/NOX_Observer_Print.cpp
- packages/nox/src/NOX_SolverStats.hpp
- packages/nox/test/tpetra/Tpetra_Heq.cpp
Two of the solver statistics were not being logged. This update fixes the issue.
new unit test added using H eqn
> NOX: update solver stats

- packages/tpetra/core/test/FECrsGraph/FECrsGraph_UnitTests.cpp
1. Check for number of rows in graph was checking number of rows against number of entries
2. Assignment of success from one test was being overwritten by further assignments of success
so that if an evaluation failed and the next succeeded the test would report as succeeding
overall.
Closes: #9886
> Tpetra: Fixed two errors in Tpetra::FECrsMatrix test

- packages/piro/src/Piro_TempusSolver_Def.hpp
In trying to understand why Explicit-Implicit and Explicit-Explicit Schwarz coupling does not work anymore in Albany-LCM, I came across some things that can be improved within Piro.  This PR implements those fixes/additions.
> Piro: some fixes / additions relevant to Schwarz coupling in Albany-LCM.

- packages/muelu/doc/UsersGuide/masterList.xml
- packages/muelu/doc/UsersGuide/options_aggregation.tex
- packages/muelu/doc/UsersGuide/paramlist.tex
- packages/muelu/doc/UsersGuide/paramlist_hidden.tex
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/src/Interface/MueLu_ParameterListInterpreter_def.hpp
- packages/muelu/src/MueCentral/MueLu_MasterList.cpp
- packages/muelu/test/unit_tests/Aggregates.cpp
This commit adds an option `aggregation: dropping may create Dirichlet` to control whether filtering during aggregation can create new Dirichlet rows.  The default value is `true`.
For certain problems (SPE10) with very small/jumpy coefficients, solver convergence is much better if dropping during aggregation isn't allowed to lead to new Dirichlet rows.
Requested by @rstumin.
This PR includes a unit test, and @rstumin has confirmed that when this option is set to `false`, certain SPE10 linear systems can be solved effectively.
> MueLu: add option to control whether dropping can lead to additional Dirichlet rows

- packages/zoltan2/core/src/TpetraCrsColorer/Zoltan2_TpetraCrsColorer_Zoltan.hpp
- packages/zoltan2/test/core/TpetraCrsColorer/Bug9500.cpp
- packages/zoltan2/test/core/TpetraCrsColorer/CMakeLists.txt
- packages/zoltan2/test/core/helpers/UserInputForTests.hpp
In #9500, @kliegeois reported incorrect results from TpetraCrsColorer when using matrices in non-contiguous row maps.
This PR fixes the problem.
The bipartite symmetrization used the number of global entries in the row map as the first index of the column vertices.  However, for a non-contiguous map with the largest index greater than the global number of entries, the number of global entries is incorrect.  Using the maximum global ID instead solves the problem, at least for the new test Bug9500.cpp.
#9500 
@kliegeois 
New test added:  Bug9500.cpp -- builds row maps with GIDs that are multiples of a specified "multiple"; does coloring for matrices with contiguous (multiple=1) and non-contiguous (multiple=2, 5) row maps.  
Test failed for multiple > 1; this PR allows the …
> Zoltan2:  fix indexing for non-contiguous row maps in TpetraCrsColorer's bipartite symmetrization

- packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
- packages/tpetra/core/test/MultiVector/MultiVector_LocalViewTests.cpp
Use compile-time logic to figure out whether WrappedDualView::getView<T>
will return a host or device view. Add test to make sure the correct
modify flags based on the device type T. #9897 fixed one example of incorrect modify flags, but this is a permanent fix for the general issue.
The general issue was, for a MultiVector with the device and host being the same (e.g. UVM), doing
``mv.template getLocalView<DeviceType>(ReadWrite)`` would set the host modify flag. But now, plugging in the device consistently sets the device modify flag.
* Closes 
* Blocks 
* Follows #9897
* Precedes 
* Related to 
* Part of 
* Composed of 
Added a test in MultiVector/LocalViewTests to replicate the previous issue and make sure the modify flags are set correctly.
> Tpetra: fix modify flags of WDV::getView<T>

- packages/panzer/disc-fe/src/evaluators/Panzer_ScatterResidual_BlockedTpetra_impl.hpp
@trilinos/panzer @rppawlo 
Incorporate additional checks to support response vectors into ScatterResidual_BlockedTpetra for the Residual evaluation type. The Jacobian evaluation already does this, and the non-blocked version also does this for both Residual and Jacobian evaluations currently.
> Panzer: Make sure that panzer::ScatterResidual_BlockedTpetra checks for LOCir_GlobalEvaluationData for Residual evaluation.

- cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.crs.cmake
- cmake/ctest/drivers/ascicgpu031/TrilinosCTestDriverCore.ascicgpu031.gcc-cuda.sake.cmake
After consulting with @crtrott, disabling nightly testing of KokkosCore_UnitTest_CudaTimingBased to follow what PR testing does.  This test should not be run at the same time as other tests.
> Ctest: Disabling KokkosCore_UnitTest_CudaTimingBased on ascicgpu031

- packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
> Tpetra: Modifying WDV to catch resizing one but not both child views a little easier

- packages/muelu/test/unit_tests/NullspaceFactory.cpp
This PR puts getDataNonConst in a separate scope to avoid "Cannot access data on device while a host view is alive" in NullSpaceFactor unit test.
I've tested on an ASCICGPU machine without UVM.
> MueLu : fix NullspaceFactor unit test

- packages/xpetra/test/BlockedCrsMatrix/CMakeLists.txt
- packages/xpetra/test/BlockedMultiVector/CMakeLists.txt
- packages/xpetra/test/CrsMatrix/CMakeLists.txt
- packages/xpetra/test/Map/CMakeLists.txt
- packages/xpetra/test/MapExtractor/CMakeLists.txt
- packages/xpetra/test/Matrix/CMakeLists.txt
- packages/xpetra/test/MatrixMatrix/CMakeLists.txt
- packages/xpetra/test/MatrixUtils/CMakeLists.txt
- packages/xpetra/test/MultiVector/CMakeLists.txt
- packages/xpetra/test/Vector/CMakeLists.txt
CMake complains about tests that have source files that don't have their extension specified.
https://cmake.org/cmake/help/git-stage/policy/CMP0115.html
> Xpetra: Fix CMake warnings about missing source file extensions

- packages/amesos2/src/Amesos2_Superlumt_def.hpp
This PR likes to adjust the default parameter value for `nprocs` such that it is the current number of threads, e.g., OMP_NUM_THREADS (the default value was always one).
> Amesos2 : SuperLU_MT adjusts 'nprocs' default parameter

- packages/stokhos/src/kokkos/Stokhos_CrsProductTensor.hpp
- packages/stokhos/src/kokkos/Stokhos_Multiply.hpp
Kokkos removed Kokkos::Impl::power_of_two with kokkos/kokkos#4578
This update moves the routines to Stokhos for compatibility
Compatibility change
* Replaces #9985
Autotester
> Stokhos: Include power_of_two from Kokkos

- packages/tempus/src/Tempus_Integrator.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorBasicOld_decl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
- packages/tempus/src/Tempus_IntegratorForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity_decl.hpp
- packages/tempus/src/Tempus_SolutionState_decl.hpp
- packages/tempus/src/Tempus_StepperHHTAlpha_impl.hpp
- packages/tempus/src/Tempus_StepperIMEX_RK_Partition_impl.hpp
- packages/tempus/src/Tempus_StepperImplicit_decl.hpp
- packages/tempus/src/Tempus_StepperImplicit_impl.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitAForm_impl.hpp
- packages/tempus/src/Tempus_StepperNewmarkImplicitDForm_impl.hpp
- packages/tempus/src/Tempus_Stepper_decl.hpp
- packages/tempus/src/Tempus_Stepper_impl.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategy.hpp
- packages/tempus/src/Tempus_TimeStepControl_decl.hpp
Several functions can be labelled for deprecation in preparation
for the next major release.
* IntegratorBasic::getTempusParameterList() and
IntegratorBasic::setTempusParameterList. IntegratorBasic is no
longer a ParameterList Acceptor. One can still get a ParameterList
from IntegratorBasic::getValidParameters(), but setting the
ParameterList is essentially resetting the IntegratorBasic, so
just recreate it with createIntegratorBasic(pl).
* Three constructors for SolutionState. These have been replaced with
non-member constructor functions.
* Stepper::solveImplicitODE(x).  This has been replaced with
Stepper::solveImplicitODE(x, xDot, t, p) which includes many
steps needed for the solve. Some steppers are not ready for
the new solveImplicitODE(x, xDot, t, p), so the solveImplicitODE(x) …
> Tempus: Deprecate Some Functions

- packages/sacado/src/Sacado_Traits.hpp
- packages/sacado/test/UnitTests/Fad_KokkosTests.hpp
Sacado has always provided ScalarValue<T>::eval() for extracting the
scalar value of any Fad type, but being a class template specialization
isn't always the easiest to call (since it requires explicitly
specifying the type).  This commit adds a template function to make
it easier to call, leveraging the compilers template deduction
mechanisms.  Also added a test for it.
> Sacado:  Add overloaded function scalarValue() for extracting scalars.

- packages/zoltan2/test/core/unit/models/GraphModel.cpp
The GraphModel unit test produces spurious test failures in nightly testing.  The code executes correctly, but output of the "PASS" keyword gets interrupted by other output.  Teuchos reports a test failure when it cannot find "PASS" in the output.
This change attempts to reduce the incidence of these spurious failures by reducing the amount of output.
Compiled on mac with gcc8, openmpi 1.10.7
> Zoltan2:  reduce output in GraphModel unit test

- packages/tpetra/core/src/Tpetra_CrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp
The optional argument `CM` (`ADD` by default) allows to replace existing values instead of summing into them. The default behavior of `insertLocalValues` is not changed. Setting `CM=INSERT` instead replaces already existing values.
This is for example useful for constructing the strong form the gradient operator as used in MiniEM. The entry corresponding to a pair of HGrad and HCurl dofs is identical on each element that contains these dofs. It would be possible to track which entries have already been set in the sub-assembly, but this can be avoided by simply overwriting the entries in `insertLocalValues`.
> Tpetra CrsMatrix: Add CombineMode option to "insertLocalValues"

- cmake/ctest/drivers/cron_driver.py
The cron driver fails since SEMS switched to Python3. Additional changes in TriBITS might be required to get our testing back up, e.g.
https://github.com/trilinos/Trilinos/blob/5a67b70fb3816e1cea26554c650b4dc7ca26747d/cmake/tribits/dashboard_driver/tdd_driver.py#L204-L206
> Make cron driver Python3 compatible

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Quad8ToQuad4MeshFactory.cpp
Uninitialized variable caused random failure of application unit test. 
Verified fixes the issue.
Covered under tQuad8ToQuad4Factory.cpp unit test
> Panzer: fix uninitialized variable

- cmake/load_sems_dev_env.sh
This completes the transition started in the commit 18c4a2015d4:
```
18c4a2015d4 "change calls for sems-[TPLname] to sems-archive-[TPLname]."
Author: Henry Swantner <HRSwant@sandia.gov>
Date:   Mon Nov 22 16:52:04 2021 -0700
```
I tested this on a CEE RHEL7 machine manually and it seems to work correctly.
Note that I had to put in special logic to load source the script:
```
/projects/sems/modulefiles/utils/sems-archive-modules-init.sh
```
if it has not already been sourced.  This logic was the most robust test could figure out.
This should address [SEHELPD-2963](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/4/SEHELPD-2963).
I manually tested this on a CEE RHEL7 machine and it seems to work correctly.
> Finish transition from sems-xyz to sems-archive-xyz (SEHELPD-2963)

- packages/anasazi/tpetra/test/MVOPTester/MultiVecTraitsTest2.cpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_dot_mv_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_dot_spec.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_iamax_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm1_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm2_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm2w_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrminf_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_sum_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas3_gemm_dotbased_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas_util.hpp
Patching in https://github.com/kokkos/kokkos-kernels/pull/1204 :
Remove runtime-sized array reductions from BLAS-1 MV functions. Where
possible, use the same approach as dot-based GEMM (have multiple teams
work on a reduction, and use atomics to contribute to the final result).
If that is not possible, just process each column one at a time. Both
approaches give better performance than array reductions, and also work
for any number of columns (before, both Cuda and HIP had limits, see #9856).
I checked that the tests to replicate the issue (from #9860), pass with these changes.
All the changes are within Kokkos Kernels. KokkosKernels_blas_* has unit tests for each of these functions.
> Patch in Kokkos Kernels #1204 to fix #9856

- packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_decl.hpp
- packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp
This PR fixes the build error of FROSch without Tpetra deprecated code
* Closes #10078 
Tested on Weaver without deprecated code
> ShyLU_DDD/FROSch: fix build without Tpetra deprecated code

- packages/piro/src/Piro_ObserverToTempusIntegrationObserverAdapter_Def.hpp
Removing extraneous print statement that somehow made it into Piro develop/master some time back.
> Piro: remove extraneous print statement.

- packages/piro/src/Piro_TrapezoidRuleSolver.hpp
- packages/piro/src/Piro_TrapezoidRuleSolver_Def.hpp
This PR adds some routines to Piro that enable one to disable the initial acceleration solve within the TrapezoidalRule stepper.  This capability is of interest to Albany-LCM.
> Piro: add routines to disable initial acceleration solve in Trap. Rule stepper

- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
- packages/tempus/src/Tempus_SolutionHistory_impl.hpp
- packages/tempus/src/Tempus_TimeEventComposite.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyBasicVS.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyConstant.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyIntegralController.hpp
- packages/tempus/src/Tempus_TimeStepControl_impl.hpp
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref.xml
- packages/tempus/test/Integrator/Tempus_IntegratorBasic_ref2.xml
- packages/tempus/unit_test/Tempus_UnitTest_TimeStepControl.cpp
During normal construction, TimeStepControl::getValidParameters()
could contruct a ParameterList with a TimeEventComposite sublist
without any events.  Later, createTimeEventComposite would warn
that the ParameterList did not have any TimeEvents to construct.
Fix:
* TimeStepControl::getValidParameters() no longer contructs
a ParameterList with an empty TimeEventComposite.
* createTimeStepControl can now handle ParameterLists with
the optional "Time Step Control Events" sublist.
* Adjusted tests and unit tests to reflect these changes.
* Added capability to handle some cases where the ParameterList
is empty.
See #10116.  Remove warnings that are Tempus generated.
* Closes #10116 
@etphipp noted this in SPARC and will follow-up that this warning is no longer appearing. …
> Tempus: Fix Erroneous Warning from TimeEventComposite

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
Unescaped curly braces are allowed in XML strings, but Watchr has a bug
with parsing them. Replace with parentheses as quick workaround.
Tested on my RHEL machine.
> Teuchos: replace curly braces with parens in Watchr

- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_decl.hpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientAdjointSensitivity_impl.hpp
Added flags to control whether the forward and/or adjoint integrations
are done in advanceTime() for the pseudo-transient adjoint integrator.
Using the update() methods of ROL-2.0, this eliminates the duplicate
forward evaluation when ROL calls value() and gradient() for the
objective function with the same set of parametes, when using the
pseudo-transient adjoint integrator to compute gradients.
> Tempus:  Allow separating forward and adjoint psuedo-transient evaluations

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Distributor.cpp
- packages/tpetra/core/src/Tpetra_Distributor.hpp
Deleted the getLastDoStatistics functionality of Distributor since it was largely unused.  We could deprecate instead, but the only user of this function was the printMultiplicationStatistics function in MatrixMatrix, which is not currently used in production.  As per team request, I've commented out printMultiplicationStatistics instead of deleting it, in case someone wants to refer back to it.
Tpetra builds and tests pass on a local CPU build.
> Tpetra: Remove statistics from Distributor

- packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_decl.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_def.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_matrix_def.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor_blk.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor_col.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor_diag.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order_amd.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order_btf.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order_scotch.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_sfactor.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_solve_rhs.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_structs.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_tree.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_types.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_util.hpp
Fix some bugs with threaded-factorizations
-  reseting workspaces for solving sequence of problems using multiple threads
Add new options for threaded performance
-  an option to use METIS_NodeNDP for computing ND partition
-  an option to use AMD instead of ND on the leaf nodes (for smaller matrices)
> ShyLU,Basker : fix threaded factorization

- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_def.hpp
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp
- packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp
This commit adds a CoalesceDrop option (Kokkos factory path) to control
whether filtering can create new Dirichlet rows.
This option is already available in the non-Kokkos aggregation path.  (PR #9993.)
N/A
This PR includes a unit test.
> MueLu: control if dropping creates new Dirichlet

- packages/piro/src/Piro_InvertMassMatrixDecorator_Def.hpp
Overwriting Epetra-based solver set by default in Piro::InvertMassMatrixDecorator to prevent cast error (since this routine is Tpetra-based).  Needed for Albany-LCM.
> Piro: overwriting solver defaults w/o mass lumping

- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_Tools_def.hpp
This PR try fixing the FROSch build errors with deprecated codes off.
* Closes https://github.com/trilinos/Trilinos/issues/10202
Tested on Weaver with Tpetra/Xpetra deprecated code off
> ShyLU, FROSch : fix compile errors with deprecated codes off

- packages/PyTrilinos/src/gen_teuchos_rcp.py.in
This should fix 1eaf4cb0ee266d9e8ba309a8ee07a68dc4e6e988, which currently appears to do nothing.
> Pytrilinos: Actually use MPI_BASE_DIR

- packages/piro/src/Piro_TempusSolverForwardOnly.hpp
- packages/piro/src/Piro_TempusSolverForwardOnly_Def.hpp
- packages/piro/test/CMakeLists.txt
- packages/piro/test/Piro_TempusSolverForwardOnly_UnitTests.cpp
An application requires a forward only version of TempusSolver. We
will derive it from RythmosSolver and replace Rythmos calls with
Tempus calls.  Removed all the Rythmos solver portions and the
sensitivities are not needed.
Help application move from Rythmos to Tempus.
* Closes #10225 
Stakeholder will test this feature in their application.
Added unit tests covering the basic usage.
> Piro: Create a Forward Only Tempus Solver

- packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp
@trilinos/teuchos @trilinos/tpetra @trilinos/zoltan2 @seheracer @kddevin 
The source of the slowdown observed in #10194 seems to be that `KokkosCompat::deep_copy_offset` used the 2-arg version of `deep_copy`, which fences across all execution spaces.  Experiments with fencing seem to indicate that Zoltan2 was trying to overlap host-side communication with device-side work, and the fences in `deep_copy` were causing the communication to block until the device-side work had completed.  Changing to 3-arg deep copy, which doesn't unconditionally fence, seems to yield roughly equivalent performance to the `memcpy` solution in #10194.
* Closes #10194
Tpetra unit tests continue to pass in a Cuda (non-UVM) build on ascicgpu.
> Teuchos: Convert KokkosCompat::deep_copy_offset to use 3-arg deep_copy to avoid fences

- cmake/ctest/drivers/geminga/cron_driver.sh
Disable the AMGX build, since it seems to crash the machine, and the no-UVM build, since it's no longer needed.
> Geminga: Disable AMGX build

- packages/tpetra/core/src/Tpetra_Details_DistributorActor.cpp
- packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
- packages/tpetra/core/src/Tpetra_DistObject_decl.hpp
- packages/tpetra/core/src/Tpetra_DistObject_def.hpp
- packages/tpetra/core/test/ImportExport2/AsyncTransfer_UnitTests.cpp
@trilinos/tpetra @vbrunini 
Provides a transferArrived function for DistObject, that will return true once the data from transfer started by beginImport etc. has been communicated appropriately and is ready for the unpack and combine step performed by endImport etc.
This is a repost of #9902 to attempt to work around autotester issues.
* Related to #9251
This PR includes unit tests for the new transferArrived function.  There are no specific tests that transferArrived returns false for CrsMatrix when beginImport is only called on one rank, because CrsMatrix uses the "variable number of packets per LID" code path, which requires a blocking communication across all ranks to establish the number of packets each rank should expect to receive.  However, the conditions under which …
> Tpetra: add transferArrived function to DistObject

- packages/amesos2/src/Amesos2_Superludist_decl.hpp
- packages/amesos2/src/Amesos2_Superludist_def.hpp
This PR tries fixing the compilation errors with Amesos2/SuperLU_DIST when Tpetra's deprecated codes are turned off.
This may fix https://github.com/trilinos/Trilinos/issues/9639.
Tested on Weaver with SuperLU_DIST 6.00 and Tpetra deprecated code off.
> Amesos2, Superludist : fixing compilation errors with Tpetra deprecatated code off

- packages/muelu/src/Smoothers/MueLu_Ifpack2Smoother_def.hpp
If the user __supplies__ an eigenvalue estimate for Chebyshev smoothing, cache it for later use in prolongator smoothing. (There is already an option to force a new eigenvalue estimate in the SaPFactory.)
This is a bit of corner case, since MueLu already has the capability to cache an eigenvalue estimate __calculated__ by Chebyshev for later use in the SaPFactory.
Tested locally on ascicgpu031.
> MueLu: enable user-supplied eigen-value for SaP

- packages/stokhos/src/sacado/Sacado_ETPCE_OrthogPoly.hpp
- packages/stokhos/src/sacado/Sacado_ETPCE_OrthogPolyImp.hpp
- packages/stokhos/src/sacado/Sacado_PCE_OrthogPoly.hpp
- packages/stokhos/src/sacado/Sacado_PCE_OrthogPolyImp.hpp
A couple of Stokhos classes have static data members that internally have RCP's
in them.  On blake with the clang compiler, these static data members were
being initialized before some static data used internally within RCP, leading
to exceptions and failed tests.  This removes the static data to workaround
this problem.
For issue #10228.
> Stokhos:  Fix static initialization

- cmake/tribits/core/package_arch/TribitsPackageSetupCompilerFlags.cmake
- cmake/tribits/core/package_arch/TribitsSubPackageMacros.cmake
- cmake/tribits/doc/build_ref/TribitsBuildReferenceBody.rst
Fixes #10111
This brings in just the commit https://github.com/TriBITSPub/TriBITS/pull/453/commits/8ddc37c53fc67b28167d09c56bdd56db3572052f from PR TriBITSPub/TriBITS#453:
* TriBITSPub/TriBITS#453 (see the detailed automated tests there)
I could not sync all of TriBITS due to outstanding Trilinos PR #9978 (see TriBITSPub/TriBITS#433).  This make the Git work more tricky.
The git gymnastics to cherry-pick and snapshot just the commit https://github.com/TriBITSPub/TriBITS/pull/453/commits/8ddc37c53fc67b28167d09c56bdd56db3572052f were a bit involved but I will explain it in detail below.  (I need to document this workflow in a technical document about how to patch a snapshot with just cherry-picked commits from the other repo being snapshotted in.)
<details>
<summary><b>Git operations to …
> Add support for subpackage-specific compiler flags (#10111)

- packages/amesos2/src/Amesos2_Superlu_FunctionMap.hpp
- packages/amesos2/src/Amesos2_Superlu_decl.hpp
Building drekar under clang/12.0.1 with superlu/5.2.1 enabled results in a compilation error in Amesos2:
```
FAILED: packages/amesos2/src/CMakeFiles/amesos2.dir/Amesos2_Superlu.cpp.o
/home/mmcrock/spack/opt/ubuntu18.04-skylake/clang-12.0.1/openmpi-3.1.6-r2obqojc4zs57voilrpsbigtrf4ey7si/bin/mpicxx  -I. -I/mnt/array/drekar/builds/master/drekar/src/Trilinos -Ipackages/amesos2/src -I/mnt/array/drekar/builds/master/drekar/src/Trilinos/packages/amesos2/src -I/mnt/array/drekar/builds/master/drekar/src/Trilinos/packages/amesos2/src/KLU2/Include -I/mnt/array/drekar/builds/master/drekar/src/Trilinos/packages/amesos2/src/KLU2/Source -I/mnt/array/drekar/builds/master/drekar/src/Trilinos/packages/common/auxiliarySoftware/SuiteSparse/src/AMD/Include …
```
> Implementing fix to resolve compilation error in Amesos2 with SuperLU 5 and clang 12

- packages/tpetra/core/src/CMakeLists.txt
- packages/tpetra/core/src/Tpetra_Details_localDeepCopyRowMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_localDeepCopyRowMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_localRowOffsets_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_localRowOffsets_def.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests_LocalAccessors.cpp
PR #10189 merged after #10188.  This PR removes deprecations in #10189 from the new test in #10188.  
It also deprecates some code in Details namespace that will not be needed once deprecated code is removed.  Details::localRowOffsets was called only by other deprecated code.
Compiled on ascicgpu machines, sems gcc7.2 modules, with and without Tpetra deprecated code enabled.
> Tpetra:  fixed used of deprecated code

- packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_DiscreteGradient.hpp
- DiscreteCurl: Don't copy back and forth between host and device and launch tiny kernels, just stay on host.
- DiscreteGradient: Do not use `ownedIndices`.
> MiniEM: Speed up assembly of discrete ops

- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_def.hpp
- packages/amesos2/src/Amesos2_MatrixAdapter_def.hpp
- packages/amesos2/src/Amesos2_Util.hpp
- packages/ifpack2/src/Ifpack2_Hypre_def.hpp
- packages/muelu/example/advanced/memory/Tpetra1DLaplace.cpp
- packages/muelu/research/caglusa/main.cpp
- packages/muelu/research/q2q1/Q2Q1.cpp
- packages/muelu/src/Transfers/Smoothed-Aggregation/MueLu_TentativePFactory_kokkos_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_decl.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_decl.hpp
- packages/muelu/test/meshtying/MeshTyingBlocked_SimpleSmoother.cpp
- packages/muelu/test/scaling/CMakeLists.txt
- packages/muelu/test/scaling/MMKernelDriver.cpp
- packages/muelu/test/unit_tests_kokkos/Utilities_kokkos.cpp
- packages/teko/src/Teko_Utilities.cpp
- packages/teko/src/Tpetra/Teko_BlockingTpetra.cpp
- packages/teko/src/Tpetra/Teko_InterlacedTpetra.cpp
- packages/teko/src/Tpetra/Teko_TpetraHelpers.cpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraLinearOp_def.hpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraVectorSpace_def.hpp
- packages/thyra/adapters/tpetra/test/TpetraThyraWrappers_UnitTests.cpp
- packages/xpetra/src/CrsGraph/Xpetra_TpetraCrsGraph_def.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraBlockCrsMatrix_def.hpp
- packages/xpetra/src/CrsMatrix/Xpetra_TpetraCrsMatrix_def.hpp
- packages/xpetra/src/Map/Xpetra_TpetraMap_def.hpp
- packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
- packages/xpetra/test/Map/Map_UnitTests.cpp
@trilinos/xpetra @trilinos/ifpack2 @trilinos/amesos2 @trilinos/teko @trilinos/thyra @trilinos/muelu 
Replace use of deprecated Tpetra methods "getNode*".
Should address #10255.
> Deprecation fixes

- packages/amesos2/src/Amesos2_Umfpack_decl.hpp
- packages/amesos2/src/Amesos2_Umfpack_def.hpp
Update umfpack wrapper for compatibility with tpetra when deprecated code is disabled
Followed similar pattern to that of #10232 and naming conventions of that PR and #7503
Related to #10153 
Tested locally before changes with tpetra deprecated code on/off as baseline, retested the same cases after tests changes
Configuration:
```bash
cmake \
\
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D CMAKE_MAKE_PROGRAM:STRING="make" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D TPL_ENABLE_MPI:BOOL=ON \
-D CMAKE_CXX_COMPILER:FILEPATH="`which mpicxx`" \
-D CMAKE_C_COMPILER:FILEPATH="`which mpicc`" \
-D …
```
> amesos2: update umfpack wrapper for Tpetra deprecated code changes

- packages/muelu/adapters/xpetra/MueLu_RefMaxwell_def.hpp
- packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp
- packages/muelu/src/Transfers/SemiCoarsen/MueLu_SemiCoarsenPFactory_def.hpp
- packages/muelu/src/Utils/MueLu_AlgebraicPermutationStrategy_def.hpp
- packages/muelu/src/Utils/MueLu_LocalPermutationStrategy_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
- packages/muelu/test/unit_tests/SemiCoarsenPFactoryWithSemiRestriction.cpp
- packages/tpetra/core/src/Tpetra_BlockView.hpp
- packages/tpetra/core/src/Tpetra_Details_extractBlockDiagonal.hpp
- packages/xpetra/sup/Utils/Xpetra_MatrixUtils.hpp
@trilinos/muelu @trilinos/tpetra
MueLu:
- Bump up tolerance in SemiCoarsen test so that it passes on vortex.
- Silence some warnings.
- Fix errors in `Utilities_kokkos::Detect*` routines for complex.
- Fix a couple of issues for complex + CUDA/HIP
Tpetra:
- Fix a build error in Tpetra:
https://testing.sandia.gov/cdash/viewBuildError.php?buildid=10676857
I don't understand it, it only pops up with a recent CUDA. (I'm using GCC 8.3.0 and CUDA 11.4.2)
- Fix error in `extractBlockDiagonal` for complex
> MueLu & Tpetra: Fix bugs

- packages/adelus/src/BlasWrapper_copy.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_Experimental_RBILUK_def.hpp
- packages/teuchos/kokkoscomm/src/Kokkos_TeuchosCommAdapters.hpp
- packages/teuchos/kokkoscompat/src/KokkosCompat_View.hpp
- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_BlockMultiVector_def.hpp
- packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
- packages/tpetra/core/src/Tpetra_Details_computeOffsets.hpp
- packages/tpetra/core/src/Tpetra_Details_copyConvert.hpp
- packages/tpetra/core/src/Tpetra_Details_copyOffsets.hpp
- packages/tpetra/core/src/Tpetra_Details_getDiagCopyWithoutOffsets_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_getGraphDiagOffsets_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_iallreduce.hpp
- packages/tpetra/core/src/Tpetra_Details_lclDot.hpp
- packages/tpetra/core/src/Tpetra_Details_normImpl.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_Details_packCrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Distributor.hpp
- packages/tpetra/core/src/kokkos_refactor/Tpetra_KokkosRefactor_Details_MultiVectorDistObjectKernels.hpp
- packages/tpetra/core/test/CrsMatrix/assembleElement.cpp
- packages/tpetra/core/test/MultiVector/Issue364.cpp
Other packages should not use functionality in the `Kokkos::Impl` namespace (with few exceptions).
Kokkos::is_view has existed for some time already as a replacement for `Kokkos::Impl::is_view`.
This pull request replaces all occurrences other than those in `packages/kokkos*`.
We don't promise backward compatibility for `Kokkos::Impl` and `Kokkos::Impl::is_view` will be deprecated in the upcoming Kokkos release.
> Kokkos::Impl::is_view -> Kokkos::is_view

- packages/piro/src/Piro_TempusSolverForwardOnly.hpp
- packages/piro/src/Piro_TempusSolverForwardOnly_Def.hpp
Fix a const issue in getValidTempusParameters() and make guard variable consistent.
This would not compiler for @glhenni and was clearly an issue.  Not sure why it slipped through the testing?!
* Closes #10281 
Will check back with @glhenni that this fixes his build failure.
Not sure why this slipped through the testing.
> Piro: Const Issue In getValidTempusParameters

- packages/intrepid2/src/Discretization/Basis/Intrepid2_HCURL_QUAD_I1_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_HEX_In_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HDIV_QUAD_In_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_HEX_Cn_FEMDef.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_QUAD_Cn_FEMDef.hpp
- packages/intrepid2/src/Shared/Intrepid2_TestUtils.hpp
- packages/intrepid2/unit-test/CMakeLists.txt
- packages/intrepid2/unit-test/MonolithicExecutable/StructuredIntegrationTests.cpp
- packages/sacado/src/Sacado.hpp
- packages/sacado/src/Sacado_DynamicArrayTraits.hpp
- packages/sacado/src/Sacado_StaticArrayTraits.hpp
Testing the code in compiling with AMD and hip compiler.
@rppawlo I confirmed that the all unit tests in Intrepid2 pass on caraway. Current Intrepid2 unit test may not cover all SACADO use case though. 
@CamelliaDPG The hip compiler gets an error while compiling your test.
```
/ascldap/users/kyukim/Work/lib/trilinos/kyukim/packages/intrepid2/unit-test/MonolithicExecutable/StructuredIn\
tegrationTests.cpp:101:44: error: cannot pass non-trivial object of type 'basic_string<char>' to variadic fun\
ction; expected type from format string was 'char *' [-Wnon-pod-varargs]
"cellMeasures point dimension (" + std::to_string(cellMeasures.ext\
ent_int(1)) +
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
~~~~~~~~~~~~~
``` 
Currently I fix this issue by removing the …
> Intrepid2 - compiling on hip compiler

- packages/nox/src-loca/src-tpetra/LOCA_BorderedSolver_TpetraHouseholder.cpp
- packages/nox/src-loca/src-tpetra/LOCA_Tpetra_ConstraintModelEvaluator.cpp
- packages/nox/src-loca/src-tpetra/LOCA_Tpetra_ConstraintModelEvaluator.hpp
- packages/nox/test/tpetra/CMakeLists.txt
- packages/nox/test/tpetra/ME_Tpetra_1DFEM.hpp
- packages/nox/test/tpetra/ME_Tpetra_1DFEM_def.hpp
- packages/nox/test/tpetra/ME_Tpetra_Heq_def.hpp
- packages/nox/test/tpetra/tTpetra_1DFEM_ME_UnitTests.cpp
- packages/nox/test/tpetra/tTpetra_HouseholderBorderedSolve.cpp
- packages/nox/test/tpetra/tTpetra_HouseholderBorderedSolve_Continuation.cpp
- packages/nox/test/tpetra/tTpetra_HouseholderBorderedSolve_WithUVInPrec.cpp
Requested new feature.
Fixes issue. Charon issue #300
Added new tests in: tests/tpetra/tTpetra_HouseholderBorderedSolve_Continuation.cpp
> LOCA: Add support for arc-length continuation with tpetra Housholder constraints

- packages/stk/stk_mesh/stk_mesh/base/DeviceField.hpp
- packages/stk/stk_mesh/stk_mesh/base/DeviceMesh.cpp
- packages/stk/stk_util/stk_util/util/StkNgpVector.hpp
In the upcoming Kokkos release, the syntax for `Kokkos::create_mirror_view` without initializing the new `Kokkos::View` slightly changes. The overload taking `Kokkos::WithoutInitializing` as last argument is deprecated in favor of an overload taking `Kokkos::WithoutInitializing` as first argument to be conforming to other library functions that take `Kokkos::WithoutInitializing` as an argument, see https://github.com/kokkos/kokkos/pull/4486.
It seems `STK` is the only package using this overload in `Trilinos` at the moment.
The pull request currently targets the `kokkos-promotion` branch. I don't have a strong opinion if it should be merged into that one or if it should be retargeted for the `develop` branch after `kokkos-promotion` has been merged.
@trilinos/stk
@ndellingwood 
* Follows …
> STK: Replace deprecated Kokkos::create_mirror_view overload

- packages/amesos2/src/Amesos2_Superludist_def.hpp
This PR adjusts Amesos2 to follow SuperLU_DIST
`anorm` is used to determine tiny pivots.
> Amesos2_Superludist : to be consistent with SuperLU_DIST

- packages/tpetra/CMakeLists.txt
Fix #4370: At configure time, if Tpetra can't automatically figure out for certain that the MPI is CUDA-aware, and the user hasn't set the configure-time option either way, remind the user that they can still assume CUDA-aware with a runtime environment variable.
See #4370 for motivation
> Tpetra: tell user about runtime CUDA-aware setting

- packages/nox/src/NOX_Solver_TensorBased.C
@trilinos/rppawlo@sandia.gov
This fix is required in order to avoid conditional execution of coded based on not initialized variables which could lead to random failures. For example adding the following code in a user program causes the NOX solver to fail:
void* operator new(size_t n)
{
void* p = malloc(n);
memset(p, 0xFF, n);
return p;
}
That modified version of Trilinos has been tested inside the free open source software MBDyn developed by the Politecnico di Milano.
All tests have been executed using trilinos release 12.14.1-3. However, there should be no difference compared to the development branch.
Below you can find the output from valgrind executing the test problem:
==11214== Conditional jump or move depends on uninitialised value(s)
==11214==    at 0x1A5E4FD: …
> NOX: Fix missing initialization of variables in NOX::Solver::TensorBased

- packages/panzer/disc-fe/src/Panzer_IntrepidBasisFactory.hpp
- packages/panzer/disc-fe/test/evaluator_tests/dof_basistobasis.cpp
@trilinos/panzer @trilinos/intrepid2 
HGRAD_*_C2 is missing some method implementations, and Intrepid2 would like to deprecate the quadratic elements in favor of n-th order elements.
> Panzer: Use HGRAD_*_Cn instead of HGrad_*_C2

- packages/piro/src/Piro_TempusSolverForwardOnly_Def.hpp
- packages/tempus/src/Tempus_IntegratorBasic_decl.hpp
- packages/tempus/src/Tempus_IntegratorBasic_impl.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyBasicVS.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyComposite.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyConstant.hpp
- packages/tempus/src/Tempus_TimeStepControlStrategyIntegralController.hpp
- packages/tempus/src/Tempus_TimeStepControl_impl.hpp
- packages/tempus/test/DIRK/Tempus_DIRKTest.cpp
Validation of Parameters in ParameterLists is done through
each objects "create" function for the given ParameterList,
e.g., createIntegratorBasic, createStepper, and
createTimeStepControl.  This allows multiple sub-ParameterLists
with different names to exist (e.g., multiple integrators, and
steppers).  Only sub-ParameterLists being used will be validated.
This allows multiple sub-ParameterLists to coexist and be easily
switched between.
Improve validation of ParameterLists.
* Closes #10371 
Will have @glhenni look at this.
Fixed existing test, which should sufficient.
> Tempus: Cleanup Validation of ParameterLists

- packages/PyTrilinos/cmake/PyTrilinos_config.h.in
- packages/PyTrilinos/src/CMakeLists.txt
- packages/PyTrilinos/src/Tpetra.i
Fixes #10362
Closes #10363
I tested the build with the configuration described in #10362 as well as the configuration that exposed the original issue.
> PyTrilinos: Add a cmake define for HAVE_TPETRA_INST_INT_LONG_LONG.

- packages/panzer/disc-fe/src/evaluators/Panzer_Integrator_BasisTimesVector_impl.hpp
One ctor was missing the allocation of temporary memory. This commit moves the initialization into the postRegistrationSetup routine so that all ctors are initialized correctly.
Fixes issue. Drekar issue #640
> Panzer fix initialization issue in Integrator_BasisTimesVector

- packages/nox/src/NOX_LineSearch_MoreThuente.H
Fix error in doxygen documentation for More'-Thuente line search.
Closes #1520 
N/A
> NOX: fix doxygen documentation for MT linesearch

- packages/krino/krino/unit_tests/Akri_Unit_main.cpp
Thanks to Evan Harvey for help diagnosing and fixing this issue.
MPI_Init must be called before any Kokkos or cuda code.
Fix for krino in PR# 10365.
> Fix for krino on vortex

- packages/shylu/shylu_node/basker/src/shylubasker_order.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order_btf.hpp
- packages/shylu/shylu_node/basker/test/CMakeLists.txt
- packages/shylu/shylu_node/basker/test/singular_matrix_check.cpp
This PR fixes a couple of issues that @hkthorn reported in ShyLU-Basker
- It should not throw exception "need Metis or Scotch" when running with one thread
- "replace tiny pivot" option is turned off when we only have one block (to identify singular matrix)
We added `singular_matrix_check` to ctest.
We also removed some commented-out code.
> ShyLU Basker : 

- packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
safety check
Enforces that inners views are unmanaged - needed when UVM is disabled.
covered by view of views unit test
> Phalanx: static_assert that inner view in a view-of-views is unmanaged

- packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
- packages/phalanx/test/Kokkos/tKokkosViewOfViews.cpp
- packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
Improve the view of view utilities for users.
Works for both cuda and hip backends!
phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
> Phalanx: improve view of view utilities

- packages/belos/src/BelosGmresPolySolMgr.hpp
@jennloe 
In trying to use the `BelosGmresPolySolMgr` object in Sierra/Aria, it was uncovered that the "Outer Solver Param" argument was not in the set of valid arguments provided. This was causing the object to throw when trying to give non-default outer solver parameters,
Tested by running this change through the testing infrastructure.
> belos: add missing parameter to getValidParameters in GmresPolySolMgr

- packages/tpetra/core/ext/TpetraExt_MatrixMatrix_def.hpp
Issue #10416 appears to be caused by `import_and_extract_views` not being ETI'd. `import_and_extract_views` is used in a MueLu's ImportPerformance test.
> Tpetra: ETI for import_and_extract_views

- packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_PowerMethod.hpp
Honestly, it just bothers me to see 5+ versions of a simple power method reimplemented across Trilinos within different packages, and I can't really use any of them for a Trilinos-based code. This is meant to be a more public interface and the "official" power method that supports the most general case of petra operators. It adds Ifpack2::PowerMethod::powerMethod, Ifpack2::PowerMethod::powerMethodWithInitGuess,  Ifpack2::PowerMethod::computeInitialGuessForPowerMethod. 
The transfer out of the Chebyshev class is not as pretty as I'd like because there are things like Chebyshev restarts that need to be cleanly preserved, and my choice of using only some input arguments as Teuchos::RCPs may have been a little random, so I'm happy to use some feedback and make this …
> Ifpack2: Move power method routines into their own publicly accessible namespace

- packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
- packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
add default ctor and initialization method to follow empire object construction path.
improved documentation
Unit test for V-of-V udpated for changes.
> Phalanx: more v-of-v support

- packages/tpetra/core/src/Tpetra_Details_normImpl.hpp
Use the KokkosKernels specialization for 1-vector MVs for the local parts of norms.
For a run on 32 GPUs, I see 
**Before**
```
Belos::MVT::MvNorm: 1.4864 - 3.84499% [3604] {min=1.47393, max=1.49435, std dev=0.00603344} <1, 4, 1, 1, 3, 3, 7, 3, 1, 8>
```
**After**
```
Belos::MVT::MvNorm: 0.19496 - 0.527566% [3604] {min=0.177702, max=0.205975, std dev=0.00839741} <2, 2, 2, 1, 5, 5, 0, 2, 9, 4>
```
> Tpetra: Use numVectors==1 specialization for local parts of norms

- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_ops.hpp
This patches solves #10388: Stokhos: avoid deprecation warnings when compiling with cuda >= 10.0
> Stokhos: Fixing #10388

- packages/belos/src/BelosGmresPolySolMgr.hpp
- packages/belos/test/BlockGmres/test_hybrid_gmres_complex_hb.cpp
A user request has been received for the Gmres polynomial preconditioned
solver to return the achieved tolerance from the outer iterative method.
This is best done through the achievedTol() method in the abstract solver
manager interface, that is utilized by most of the iterative methods.
This commit implements that function call and includes a test of that call
to ensure it works.
OSX GCC11 Serial
> Implements the achievedTol interface for the GmresPolySolMgr

- packages/ifpack2/test/belos/build_precond.hpp
In Ifpack2_tif_belos (performance test driver), add comm/MPI barriers around the preconditioner initialize and compute. For e.g. RILUK, the init/compute on each rank runs independently, and also can vary a lot between ranks. Processes that finished earlier would enter a different TimeMonitor block and wait a long time at collectives, so that waiting time would appear under the other timer. This caused the StackedTimer output to be misleading. With these barriers, the preconditioner setup is now timed as the max over all processors so any bottlenecks there will show up clearly in the StackedTimer.
Needed to set up Belos+Ifpack2 performance testing on SierraTF problems.
> Ifpack2: add comm barriers separating perf regions

- packages/ifpack2/src/Ifpack2_Details_FastILU_Base_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Fic_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Fildl_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Filu_def.hpp
- packages/ifpack2/test/belos/5w_bel_tif_FIC_sptrsv.xml
- packages/ifpack2/test/belos/5w_bel_tif_FILDL_sptrsv.xml
- packages/ifpack2/test/belos/5w_bel_tif_FILU_sptrsv.xml
- packages/ifpack2/test/belos/CMakeLists.txt
- packages/ifpack2/test/belos/test_FIC_calore1_mm_sptrsv.xml
- packages/ifpack2/test/belos/test_FIC_small_sym_sing_sptrsv.xml
- packages/ifpack2/test/belos/test_FIC_tfqmr_small_sym_mm_sptrsv.xml
- packages/ifpack2/test/belos/test_FILDL_calore1_mm_sptrsv.xml
- packages/ifpack2/test/belos/test_FILDL_small_sym_sing_sptrsv.xml
- packages/ifpack2/test/belos/test_FILDL_tfqmr_small_sym_mm_sptrsv.xml
- packages/ifpack2/test/belos/test_FILU_calore1_mm_sptrsv.xml
- packages/ifpack2/test/belos/test_FILU_small_sym_sing_sptrsv.xml
- packages/ifpack2/test/belos/test_FILU_tfqmr_small_sym_mm_sptrsv.xml
- packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp
- packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp
- packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
@trilinos/ifpack2, @trilinos/shylu 
This PR adds an option to use KokkosKernels::sptrsv with FastILU
This new option has been added to ctest in ifpack2/belos
It also tries removing `Arguments are being passed in but not used.  UNPARSED_ARGUMENTS =` warning in CMakeLists.txt of ifpack2/test/belos with fastilu
> Ifpack2, FastILU : add an option to use KokkosKernels::sptrsv

- packages/shylu/shylu_node/tacho/unit-test/Tacho_TestDenseLinearAlgebra.hpp
Resolve namespacing issues with Kokkos for post-3.6.00 release
See issue kokkos/kokkos#4817
@trilinos/shylu @kyungjoo-kim 
Resolve compilation errors with namespacing issues with kokkos' develop branch (post version 3.6.00)
Locally tested with intel/18 build with Trilinos as well as source-override to test with Kokkos' develop branch
> tacho: updates to drop using namespace Kokkos in tests

- packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
- packages/tpetra/core/src/Tpetra_Distributor.cpp
Since the default is to use distinct tags for each code path,
this deprecation effectively is taking away the option for users
to ask Distributor to always use the same tag.
The more robust strategy of giving one unique tag per DistributorActor
should make useDistinctTags unnecessary.  Deprecating the option to
pass it in the parameter list lets us change it as needed later.
* Related to #10308
Manually tested a Tpetra build with deprecated code off on GCC 7.2.0, and did not see any failing tests.
> Tpetra: Deprecate Distributor's useDistinctTags option

- packages/kokkos-kernels/src/blas/KokkosBlas1_nrm2w.hpp
- packages/kokkos-kernels/src/blas/KokkosBlas1_nrm2w_squared.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_dot_mv_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_dot_spec.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm1_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm1_spec.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm2_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm2_spec.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm2w_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_nrm2w_spec.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_sum_impl.hpp
- packages/kokkos-kernels/src/blas/impl/KokkosBlas1_sum_spec.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_dot.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_nrm1.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_nrm2_squared.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_nrm2w.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_nrm2w_squared.hpp
- packages/kokkos-kernels/unit_test/blas/Test_Blas1_sum.hpp
- packages/tpetra/core/src/Tpetra_Details_normImpl.hpp
This patches in Kokkos Kernels PR #1354, which restores the special
path in BLAS-1 MV reduction-like kernels for when there is only one
column. This path just calls the single-column kernel, which is a simple
parallel_reduce. This path existed before but I accidentally removed it.
This also reverts #10415 since Tpetra won't need to intercept the special path
if Kokkos Kernels is taking care of it.
For multivectors (rank-2 views) with a single column, the single-column kernels use a simple parallel_reduce and get much better performance than the general multivector kernel. This restores the single-column path for all the BLAS-1 reduction-like kernels.
* Closes 
* Blocks 
* Follows #10415
* Precedes 
* Related to #10463
* Part of …
> KokkosKernels/Tpetra: Restore numVecs=1 BLAS path

- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
Issue: #10433
Tests: CUDA
Stakeholder Feedback: Via email
> Tpetra: Moving selected deep_copy calls back to 2-arg for Panzer

- packages/sacado/src/Kokkos_DynRankView_Fad.hpp
This fixes a build error with Cuda 11 in Sacado about certain variables being
undefined in device code.  The cause is taking a reference to certain
static constexpr variables, which according to this:
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#const-variables
is not allowed in device code.  Passing by value appears to resolve it.
For issue #10342
> Sacado:  Fix Cuda 11 error about variables being undefined in device code

- cmake/std/PullRequestLinuxCommonTestingSettings.cmake
- cmake/std/PullRequestLinuxWeaverTestingSettings.cmake
- cmake/std/PullRequestLinuxWeaverUvmOffTestingSettings.cmake
Tests in Panzer and Krino are blocking PRs across the board.
Issues:#10412, #10420
> Ctest: Disabling randomly failing tests

- packages/stokhos/src/Stokhos_SDMUtils.hpp
This patch solves #10389: Stokhos: compilation error when linking with Intel One API MKL version >= 2021.
> Stokhos: Fixing #10389

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_ExodusReaderFactory.cpp
- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_Interface.cpp
- packages/panzer/adapters-stk/test/stk_interface_test/tPamgenMeshFactory.cpp
- packages/panzer/dof-mgr/test/fe_assembly/test_fe_projection.hpp
Deprecated warnings from changes to stk and kokkos prevent trilinos sync to empire due to warnings as error builds.
EMPIRE 2282
Fixes the sync
N/A
> Panzer: remove use of deprecated stk and kokkos code

- packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
Adding a new unit test that protects a view-of-views use case in empire.
New test added to ViewOfViews unit test.
> Phalanx: add unit test for alternate view-of-views use case

- packages/intrepid2/src/Cell/Intrepid2_CellGeometry.hpp
- packages/intrepid2/src/Cell/Intrepid2_CellGeometryDef.hpp
- packages/intrepid2/unit-test/MonolithicExecutable/CellGeometryTests.cpp
@CamelliaDPG 
The `Intrepid2::CellGeometry` class allows `cellToNodes_` to be unallocated. In which case, `nodes_` is expected to be a `(C,N,D)` container for mesh nodes. One of the ways such a `(C,N,D)` container is commonly obtained is through `panzer_stk::STK_Interface.getElementVertices()`, so this also makes it slightly easier to pair with a `panzer_stk::STK_Interface` mesh.
The node-based constructor for straight-edge geometry previously checked the extents of `cellToNodes` to set the number of `numCells_` and `numNodesPerCell_` and vertices per cell. This updates it to check the allocation of `cellToNodes` first and then set `numCells_` and `numNodesPerCell_` using either the `cellToNodes` or `nodes`, accordingly.
I tested this in an external code I'm using and …
> Intrepid2 CellGeometry node-based constructor may take (C,N,D) containers for indexing

- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_Statistics.hpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_stk.cpp
Originally, this code assembled the same element over and over again.  Oops
> TrilinosCouplings: Fixing bug in STK driver

- packages/belos/src/BelosBiCGStabSolMgr.hpp
- packages/belos/src/BelosBlockCGSolMgr.hpp
- packages/belos/src/BelosBlockGmresSolMgr.hpp
- packages/belos/src/BelosFixedPointSolMgr.hpp
- packages/belos/src/BelosGCRODRSolMgr.hpp
- packages/belos/src/BelosGmresPolyOp.hpp
- packages/belos/src/BelosGmresPolySolMgr.hpp
- packages/belos/src/BelosPCPGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockGmresSolMgr.hpp
- packages/belos/src/BelosPseudoBlockStochasticCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockTFQMRSolMgr.hpp
- packages/belos/src/BelosRCGSolMgr.hpp
- packages/belos/src/BelosTFQMRSolMgr.hpp
Addresses #10535
Fix issue with Clang gpu compilation.
Clang does not like dynamic initialization of a class variable when
using a gpu/device target. It may be possible to address this in
other ways; namely adding an explicit initialization when the class ETI
is processed.  Given that most (every?) solver replicated this default
pattern, and all use std::cout as the default, this change removes the
explicit variable with the default variable (which was const anyway).
This potentialy may causes issues with Windows, which was already using
a workaround to capture a pointer to cout.
```
packages/belos/src/BelosBlockGmresSolMgr.hpp:340:37:
error: dynamic initialization is not supported for __device__,
__constant__, __shared__, and __managed__ variables.
static constexpr …
```
> Fix issue with Clang gpu compilation.

- packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
- packages/phalanx/test/Kokkos/tKokkosViewOfViews.cpp
- packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
Another use case for v-of-v construction to protect. In this case the outer view is a Kokkos:Array
New test added to ViewOfViews tests
> Phalanx: Array of Views acceptance test.

- packages/muelu/src/Misc/MueLu_LowPrecisionFactory_decl.hpp
- packages/muelu/src/Misc/MueLu_LowPrecisionFactory_def.hpp
Enabling double, float and complex<double>, but not complex<float> resulted in linking issues.
> MueLu LowPrecisionFactory: Fix for other combos of enables Scalar types

- packages/muelu/src/Misc/MueLu_InverseApproximationFactory_decl.hpp
- packages/muelu/src/Misc/MueLu_InverseApproximationFactory_def.hpp
- packages/muelu/src/Misc/MueLu_SchurComplementFactory_decl.hpp
- packages/muelu/src/Misc/MueLu_SchurComplementFactory_def.hpp
- packages/muelu/test/unit_tests/InverseApproximationFactory.cpp
- packages/xpetra/src/BlockedCrsMatrix/Xpetra_BlockedCrsMatrix.hpp
- packages/xpetra/sup/Matrix/Xpetra_MatrixFactory.hpp
- packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp
- packages/xpetra/sup/Utils/Xpetra_ThyraUtils.hpp
- packages/xpetra/test/BlockedCrsMatrix/BlockedCrsMatrix_UnitTests.cpp
- packages/xpetra/test/CrsMatrix/CrsMatrix_UnitTests.cpp
For future modifications to the inverse approximation factory it makes sense to
change the inverse data type from a vector to a matrix. This of course has small 
drawbacks regarding performance of the schur complement factory (one additional matrix-matrix multiplication,
instead of a matrix-vector one), but gives greater flexibility on how an inverse is approximated.
- Changing the datatype of the inverse from a vector to a matrix
- Add a blocked version to the matrix constructor for diagonal matrices initialized by a vector
I had some issues regarding the blocked unit tests, due to data type incompatibilities (CrsMatrix / BlockedCrsMatrix) and therefore included some kind of unwrapping check inside the blocked matrix multiplication. Maybe there's a better way to do it, …
> MueLu: Change schur complement inverse data type

- packages/krino/krino/CMakeLists.txt
This is needed to successfully build and install Trilinos and then build SPARC when enabling all ATDM Trilinos packages with the new TriBITS 'master' branch.
See the commit log message for details on why this is needed.
For details on the build errors this fixes, see [internal tribitsrefactoring#6](https://cee-gitlab.sandia.gov/rabartl/tribitsrefactoring/-/issues/6#note_2442260).
> Only add Krino tests when tests are enabled (TriBITSPub/TriBITS#299)

- packages/shylu/shylu_dd/frosch/src/Adapters/Stratimikos_FROSch_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Adapters/Stratimikos_FROSch_def.hpp
- packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_CoarseOperator_def.hpp
- packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_OverlappingOperator_def.hpp
- packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_ThyraPreconditioner_def.hpp
- packages/shylu/shylu_dd/frosch/src/SolverInterfaces/FROSch_ThyraSolver_def.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_decl.hpp
- packages/shylu/shylu_dd/frosch/src/Tools/FROSch_SubdomainSolver_def.hpp
- packages/shylu/shylu_dd/frosch/test/Overlap/main.cpp
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Elasticity/main.cpp
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Laplace/main.cpp
- packages/shylu/shylu_dd/frosch/test/Thyra_Xpetra_Stokes_HDF5/main.cpp
Enable use of Scalar types != double in FROSch by using the Stratimikos interfaces for general scalar type.
In my local testing I changed one of the tests that is hard-coded to double to float, and it still passed. I also had to disable Epetra for that. Otherwise I was getting build errors.
> FROSch: Propagate changes for Scalar!=double to FROSch

- packages/panzer/disc-fe/src/Panzer_BasisValues2.hpp
- packages/panzer/disc-fe/src/Panzer_BasisValues2_impl.hpp
- packages/panzer/disc-fe/src/Panzer_Workset.cpp
The orientations were not properly applied when different worksets
were used on a processor. This was because the orientations vector
was not subindexed to the workset cells. So always the same
cells on the processor were used for defining orientations. This
resulted in failed interpolation schemes.
> Panzer: Fixing orientations in lazy evaluation path

- packages/common/Doxyfile
Currently, the online Doxygen documentation's title is "version of the day". Without neither the commit SHA nor the generation timestamp, it is hard to determine for what version of Trilinos the documentation is.
This PR adds the generation timestamp to the bottom of the HTLM documentation page (see also https://doxygen.nl/manual/config.html#cfg_html_timestamp).
* https://github.com/trilinos/Trilinos/issues/10511
> documentation(html) : add timestamp to html doc

- packages/framework/pr_tools/pullrequest-specs.ini
- packages/framework/pr_tools/trilinosprhelpers/unittests/pullrequest-specs.ini
- packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationBase.py
- packages/framework/pr_tools/trilinosprhelpers/unittests/test_TrilinosPRConfigurationStandard.py
The new Trilinos_PR_python3 build is not overriding the dynamic set of package enables causing mass PR failures as reported in #10622.
#10622 and everyone with PRs touching anything outside of `packages/framework`
Replaying the failing pipeline reported via https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&parentid=183234&filtercount=1&showfilters=1&field1=buildstarttime&compare1=84&value1=NOW&filtercombine=and with these changes on top of the #10614 source branch. [Here are those pipeline results on cdash](https://trilinos-cdash.sandia.gov/index.php?project=Trilinos&display=project&filtercount=3&showfilters=1&filtercombine=and&field1=site&compare1=61&value1=ascic158&field2=buildname&compare2=61&value2=PR-test-issue10622-test-rhel7_sems-gnu-7.2.0-anaconda3-se …
> packages/framework: Try to override dynamic package enables

- .gitdist.default
- packages/framework/get_dependencies.sh
Final tweaks to GenConfig repo handling following on from PR #10620.  This is the same branch as PR https://github.com/bartlettroscoe/Trilinos/pull/7 but with a new name and pushed to the main Trilinos GitHub repo.
It is important to merge this PR ASAP,  otherwise, the srn-ini-files and son-ini-files repos will not be getting updated after their initial clone (see commit https://github.com/trilinos/Trilinos/commit/bc80cdf57d5256c96f3f51a0b18f239c520b46da).  See the individual commit log messages for details about other changes.
NOTE: [stacked  PR](https://blog.logrocket.com/using-stacked-pull-requests-in-github/) https://github.com/bartlettroscoe/Trilinos/pull/7 was meant to be merged to the PR branch  for #10620 before merging #10620.  A new PR has to be created to allow changing the …
> Address a real defect, use GenConfig without generated symlink version tracking, improve maintainability, improve readability of STDOUT

- cmake/std/PullRequestLinuxGCC8.3.0TestingSettings.cmake
@trilinos/Framework
This was originally requested by @mperego and filed as #7441. That system has been migrated to Jira.
The request was to have this added to the GCC 4.8.4 PR build. Since that has been retired, GCC 8.3.0 was suggested.
The Kokkos_ENABLE_SERIAL OFF flag conflicts with the Tpetra_INST_SERIAL ON.
It appears the Tpetra_INST_SERIAL ON flag was only added to 8.3.0 because the GCC 4.8.4 build that use it was being retired when we moved to C++14. #8324
I did check to make sure at least one PR build still uses Tpetra_INST_SERIAL ON. It still exists in the Cuda PR builds, Cuda 10.1.105, Cuda 10.1.105 UVM OFF, and Cuda 10.1.243.
This flag can be added with minimal build issues. However, those issues will need to be taken care of before this can be merged.
As of [the last time I ran …
> Framework: Add the Kokkos_ENABLE_SERIAL=OFF option to the GCC 8.3.0 PR build

- packages/teuchos/core/src/Teuchos_RCPDecl.hpp
- packages/teuchos/core/test/MemoryManagement/RCP_UnitTests.cpp
- packages/teuchos/core/test/MemoryManagement/TestClasses.hpp
This PR addresses:
* https://github.com/trilinos/Trilinos/issues/10642
It introduces `Teuchos::make_rcp`, similar to `std::make_shared`.
> Teuchos : make_rcp (#10642)

- packages/ml/test/MultiLevelPreconditioner_Sym/MultiLevelPreconditioner_Sym.cpp
On Apple clang builds of ML tests, I see errors relating to the include of `malloc.h`.  This one-line PR replaces this with `stdlib.h` in `packages/ml/test/MultiLevelPreconditioner_Sym/MultiLevelPreconditioner_Sym.cpp`, which I believe is the standard thing to include, and which resolves it for me.
> Fix ML test build failure

- packages/zoltan2/core/src/problems/Zoltan2_OrderingSolution.hpp
Set ``haveInverse_`` to true after computing the reverse permutation of an OrderingSolution. This looks like it might have been a copy-paste bug, since the functions computePerm and computeInverse are identical except for having "perm" and "inverse" swapped.
``haveInverse_`` should be set to true after computing the reverse permutation. ``havePerm_`` is already true since it's in an ``if(havePerm_)`` branch.
> Zoltan2: fix inverse permutation logic

- packages/stratimikos/test/CMakeLists.txt
@trilinos/stratimikos
Some Stratimikos tests that require Galeri are CMake-enabled even if Galeri is not enabled.  This PR adds a CMake check to disable those tests if Galeri (more specifically, `Galeri_ENABLE_Xpetra`) is not enabled.
> Resolve stratimikos/Galeri test build issue

- packages/ifpack2/test/belos/belos_solve.cpp
- packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
This PR adds an option to use Kokkos-Kernels SpMV for FastSpTRSV, which should improves the solve time.
Tested on Weaver host build.
> ShyLU FastILU : add an option to use Kokkos-Kernels SpMV for FastSpTRSV

- packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp
@brian-kelley
This PR concerns the file `packages/tpetra/core/src/Tpetra_computeRowAndColumnOneNorms_def.hpp`.  The code in this file applies mathematical functions to values in Kokkos::Views underlying Tpetra objects.  But the code is currently missing the distinction between the scalar type and the implementation scalar type.  This PR thus instantiates `Kokkos::ArithTraits` for the implementation scalar type so that the mathematical functions corresponding to the implementation scalar type are called.
This PR is related to one of two issues raised in #10612 (the other issue is solved in PR #10651).  
These changes are tested e.g.  in `tpetra/core/test/CrsMatrix/Equilibration.cpp`.
Thanks!
> Tpetra local row scaled column norms

- packages/tempus/doc/index.doc
- packages/tempus/examples/00_Basic_Problem/00_Basic_Problem.cpp
- packages/tempus/examples/01_Utilize_Thyra/01_Utilize_Thyra.cpp
- packages/tempus/src/Tempus_StepperImplicit_decl.hpp
- packages/tempus/src/Tempus_StepperRKButcherTableau.hpp
The format of Tempus tutorials can be improved by using a table
format that explains the changes from previous coding to the new
coding.
* Converted Basic Problem and Utilize Thyra tutorials to a table
format.
* Added links between the tutorial listings and individual tutorials.
* Fixed a few Doxygen/Latex bugs.  Primarily, within the Doxygen
text, one cannot have blank lines within the Latex equations.
It fails to build those equations and therefore produces no
output for Doxygen to display.
Improve format of documentation for examples.
* Closes #10691 
Generates correct doxygen output and passes all tempus tests.
> Tempus: Improve Format of Examples

- packages/belos/epetra/test/BlockCG/test_pseudo_pcg_hb.cpp
- packages/belos/src/BelosCGIter.hpp
- packages/belos/src/BelosCGIteration.hpp
- packages/belos/src/BelosCGSingleRedIter.hpp
- packages/belos/src/BelosPseudoBlockCGIter.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockStochasticCGIter.hpp
- packages/belos/tpetra/test/BlockCG/test_pseudo_bl_cg_hb.cpp
The getEigenEstimates() method returns all the eigenvalues computed
by LAPACK during the condition estimate computation.  The condition
estimate code is only provided by the pseudo-block CG solver at this
time.  There are Epetra and Tpetra tests updated to call this method.
A new CGPositiveDefiniteFailure error class created to enable users
to trap iteration errors that are specifically due to the positive
definiteness checks in the CG solvers.  Any CG iteration that uses
the errors provided in the BelosCGIteration header have been changed
to throw this new error.  The error inherits from the CGIterateFailure
class to address backwards compatibility.
This commit addresses the user request in this issue:
https://github.com/trilinos/Trilinos/issues/10446
These changes were …
> Adds getEigenEstimates() method and changes positive-definite error

- packages/belos/src/BelosFixedPointIteration.hpp
- packages/belos/src/BelosLSQRIteration.hpp
- packages/belos/src/BelosMinresIteration.hpp
- packages/belos/src/BelosPCPGIter.hpp
- packages/belos/src/BelosPCPGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockCGSolMgr.hpp
- packages/belos/src/BelosPseudoBlockGmresIter.hpp
- packages/belos/src/BelosPseudoBlockTFQMRIter.hpp
- packages/belos/src/BelosRCGIter.hpp
- packages/belos/src/BelosRCGSolMgr.hpp
- packages/belos/src/BelosTFQMRIter.hpp
There are many Failure classes that are defined in the iteration
classes and solver managers that are not used.  Many of these are
the result of general code copying during the development of new
solvers.  However, if they are not being used, they should be
removed to improve the general clarity of the code.
Mac OSX GCC11 serial and CLANG parallel
> Belos: Removes unused Failure classes inheriting from Belos::Error

- packages/tempus/src/Tempus_IntegratorForwardSensitivity.cpp
- packages/tempus/src/Tempus_IntegratorPseudoTransientForwardSensitivity.cpp
Fixes linking errors seen in some builds.  Apparently this wasn't caught by the autotester.  For issue #10699.
> Tempus:  Add missing instantiations for non-member ctor's

- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_HEX_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_LINE_C1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_QUAD_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TET_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_TRI_C2_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_WEDGE_C1_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HGRAD_WEDGE_C2_FEM.hpp
Following the pattern found in the other basis classes, this PR adds a getHostBasis() implementation to:
- Basis_HGRAD_HEX_C2_FEM
- Basis_HGRAD_LINE_C1_FEM
- Basis_HGRAD_QUAD_C2_FEM
- Basis_HGRAD_TET_C2_FEM
- Basis_HGRAD_TRI_C2_FEM
- Basis_HGRAD_WEDGE_C1_FEM
- Basis_HGRAD_WEDGE_C2_FEM
* Closes #10701
> Intrepid2: add getHostBasis() implementation to HGrad Basis classes

- packages/panzer/adapters-stk/test/periodic_bcs/periodic_32bit_int_limit.cpp
Replace Kokkos::initialize/finalize with ScopeGuard to prevent future
test failures with kokkos@3.7.00 of the form:
0. periodic_bcs_32_bit_int_limit_UnitTest ... Calling OpenMP::initialize after OpenMP::finalize is illegal
@trilinos/panzer @rppawlo 
Prevent runtime failures of the test with OpenMP backend with future kokkos@3.7.00 release of the form:
```
Calling OpenMP::initialize after OpenMP::finalize is illegal
```
Use of ScopeGuard helps allow order of initialize and finalize to be handled appropriately
Locally tested on weaver testbed with kokkos and kokkos-kernels' develop branches via source override
**Configure**:
```bash
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_PATH/cmake/std/atdm/contributed/weaver
source $TRILINOS_PATH/cmake/std/atdm/load-env.sh …
```
> panzer: use Kokkos::ScopeGuard in periodic_32bit_int_limit.cpp test

- packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
- packages/phalanx/src/design/ViewOfViewsDarmaSerialization.hpp
- packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp
Need darma serialization support for PHX::ViewOfViews in empire.
New tests added to ViewOfViews unit test.
> Phalanx: add darma serialization support to vov

- packages/phalanx/src/Phalanx_KokkosViewFactoryFunctor.hpp
Fix phalanx include guard that was prefixed with "KOKKOS_" as mentioned in #10715 
This code change is tested by almost all unit tests in phalanx. It is used by the FieldManager class.
> Phalanx: rename include guard that used KOKKOS_ prefix

- packages/tpetra/core/test/ImportExport2/AsyncTransfer_UnitTests.cpp
Test that we can do asynchronous transfers across many MultiVectors at the same time (use case for #9251).
* Closes #9251 
Now working on ascicgpu in the following builds:  CPU, Cuda UVM, Cuda no-UVM
> Tpetra:  Added a test for multiple asynchronous transfers

- packages/tpetra/core/src/Tpetra_Details_unpackCrsMatrixAndCombine_def.hpp
Change TeamThread lambda to use capture-by-value [=] explicitly. Semantically all Kokkos nested loop bodies must capture by value, but we often just make sure captures aren't modified and use [&] to avoid extra copies. In this case, using [&] triggered an NVCC internal compiler error that evaded PR testing. See nightly build error in https://testing.sandia.gov/cdash/viewBuildError.php?buildid=11137806
Compiler bug in #10724
* Closes #10724
* Blocks 
* Follows #10697 (changes in this PR triggered the internal compiler error) 
* Precedes 
* Related to 
* Part of 
* Composed of 
@csiefer2 says: "As the stakeholder, I approve this fix"
> Tpetra: address Cuda 10 compiler bug

- packages/intrepid2/src/Orientation/Intrepid2_OrientationTools.hpp
- packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefCoeffMatrix_HVOL.hpp
- packages/intrepid2/src/Orientation/Intrepid2_OrientationToolsDefModifyPoints.hpp
A view was created without specifying the default space, creating issues when not using UVM.
Fixes #10714
> Intrepid2: fix for #10714

- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
Relax a bit-by-bit error check. Should fix a failure in the chama nightly:
https://testing.sandia.gov/cdash/test/136817886
> Ifpack2 Relaxation: Don't check for bit-by-bit identity

- packages/ifpack2/src/Ifpack2_Details_FastILU_Base_def.hpp
- packages/ifpack2/src/Ifpack2_Details_Filu_def.hpp
- packages/shylu/shylu_node/fastilu/src/shylu_fastic.hpp
- packages/shylu/shylu_node/fastilu/src/shylu_fastildl.hpp
- packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
This PR adds a check to call Metis only with non-empty local matrix, for FastILU, and add an option to skip sorting matrix if the matrix has been already sorted.
> FastILU : metis-chec & skip-sort options

- packages/framework/ini-files/config-specs.ini
Reverts trilinos/Trilinos#10763
This appears to possibly be causing issues for PR #10777. We are considering temporarily reverting this commit until the issues can be dealt with.
> Revert "Add C++17 standard for GCC 7.2.0 and GCC 7.2.0 serial"

- packages/ifpack2/src/Ifpack2_Details_Filu_def.hpp
- packages/muelu/src/Utils/MueLu_Utilities_kokkos_def.hpp
The AdditiveSchwarzFilter gets passed in directly as the FastILU input matrix, so a dynamic cast to CrsMatrix isn't what we want. Use getCrsMatrix helper instead to extract the filtered&sorted CrsMatrix when using AdditiveSchwarzFilter.
Now, the sort skipping path added in #10736 is taken correctly when calling AdditiveSchwarz with FastILU as inner solver.
@vbrunini 
Tested by running Ifpack2+Belos driver with this configuration, and checking which path is taken:
```
<ParameterList name="test_params">
<Parameter name="mm_file"     type="string" value="/ascldap/users/bmkelle/MatrixCollection/Laplace3D_100.mtx"/>
<Parameter name="solver_type" type="string" value="Block Gmres"/>
<ParameterList name="Belos">
<Parameter name="Num Blocks" type="int" value="40"/>
<Parameter …
```
> Ifpack2: fix Schwarz+FastILU sort skipping

- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_ops.hpp
https://github.com/kokkos/kokkos/issues/5216.](https://github.com/kokkos/kokkos/pull/5170 promoted, among others, `Kokkos::Experimental::max` to `Kokkos::max`. This caused `Stokhos_SacadoMPVectorUnitTest_MPI_1` to fail since now the `Kokkos` function was selected in overload resolution for the unqualified `max()` call. Note that this was already happening for `Experimental` backends, like `HIP` before, since then `Kokkos::Experimental::max` was selected. This pull request fixes this by providing a better overload for `Vector` that doesn't require implicit conversion from `Expr`.
The last paragraph in https://github.com/trilinos/Trilinos/issues/10740#issuecomment-1180885529 might be related.
* Closes https://github.com/kokkos/kokkos/issues/5216
Compiling and running the …
> Stokhos: Provide algorithm and math overloads for Sacado::MP::Vector

- packages/amesos2/src/Amesos2_Control.cpp
- packages/amesos2/src/Amesos2_Control.hpp
- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_decl.hpp
- packages/amesos2/src/Amesos2_EpetraMultiVecAdapter_def.hpp
- packages/amesos2/src/Amesos2_KokkosMultiVecAdapter_decl.hpp
- packages/amesos2/src/Amesos2_KokkosMultiVecAdapter_def.hpp
- packages/amesos2/src/Amesos2_MultiVecAdapter_decl.hpp
- packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp
- packages/amesos2/src/Amesos2_SolverCore_decl.hpp
- packages/amesos2/src/Amesos2_SolverCore_def.hpp
- packages/amesos2/src/Amesos2_Solver_decl.hpp
- packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_decl.hpp
- packages/amesos2/src/Amesos2_TpetraMultiVecAdapter_def.hpp
- packages/amesos2/test/solvers/KLU2_UnitTests.cpp
- packages/amesos2/test/solvers/ShyLUBasker_UnitTests.cpp
- packages/shylu/shylu_node/basker/src/shylubasker_decl.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_def.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_matrix_decl.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_matrix_def.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor_blk.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor_col.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor_diag.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order_btf.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order_scotch.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_sfactor.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_solve_rhs.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_structs.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_tree.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_util.hpp
This PR contains options to improve the stability of ShyLU_Basker threaded factorization
- Iterative-refinement in Amesos2
- gather vectors on rank-0 and performs iterative-refinements (using solver-specific `solve`) 
- stops when reaching `maxNumIters` or the solution did not change much (the norm of the correction is less than eps*norm(initial computed solution)) 
- available through parameter `Iterative refinement` but only for solvers inheriting `SolverCore`
- threaded nested-dissection factorization within ShyLU_Basker
- matrix-scaling, either symmetric diagonal scaling, or non-symmetric row-max and then col-max
- replace tiny pivots, which are less than tol, with tol, where tol = sqrt(eps) ||A||
> ShyLU_Basker : improve numerical stability of threaded factorization

- packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
@trilinos/stokhos @etphipp
https://github.com/kokkos/kokkos/pull/5209 added a check for the layout to be used in Kokkos::View constructors to be constructible from just extents. The only standard layout for which this property doesn't hold is `LayoutStride`. The cases fixed below mean to create a contiguous representation of a given `View` in case the View is not contiguous in memory but the newly created Views just copy the layout from the old ones which makes the new Views also non-contiguous in memory in case of `LayoutStride`. In the end, the new `View` is initialized only from extents which again doesn't do the right thing for `LayoutStride` since its constructor expects extents and strides alternating.
The proposed fix is to just take the preferred layout of the associated execution …
> Stokhos: Make sure deep_copy uses contiguous layouts where intended

- packages/ifpack2/src/Ifpack2_Details_AdditiveSchwarzFilter_def.hpp
@trilinos/Ifpack2
Fixes an uninitialized read on MPI ranks with 0 local rows in Ifpack2::AdditiveSchwarz.
> Ifpack2 uninitialized read fix

- packages/amesos2/src/Amesos2_ShyLUBasker.cpp
- packages/amesos2/src/Amesos2_ShyLUBasker_FunctionMap.hpp
- packages/amesos2/src/Amesos2_ShyLUBasker_TypeMap.hpp
- packages/amesos2/src/Amesos2_ShyLUBasker_decl.hpp
- packages/amesos2/src/Amesos2_ShyLUBasker_def.hpp
Shift to usage of Kokkos::View's in place of Teuchos::Array's
Addresses issue #10743
Update ShyluBasker compiler to compile with removal of deprecated code
@hkthorn this should allow Xyce to resume compiling with Trilinos' develop branch
Configuration script (extra boiler plate pasted in for various tpls):
```bash
cmake \
\
-D CMAKE_INSTALL_PREFIX:PATH="${INSTALL_LOCATION}" \
-D CMAKE_CXX_FLAGS:STRING="-g" \
-D CMAKE_MAKE_PROGRAM:STRING="make" \
-D CMAKE_BUILD_TYPE:STRING=DEBUG \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
-D BUILD_SHARED_LIBS:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
-D TPL_ENABLE_MPI:BOOL=ON \
-D CMAKE_CXX_COMPILER:FILEPATH="`which mpicxx`" \
-D CMAKE_C_COMPILER:FILEPATH="`which mpicc`" \
-D CMAKE_Fortran_COMPILER:FILEPATH="`which mpifort`" \
\ …
```
> amesos2: update shylubasker for removed deprecated code

- packages/amesos2/src/Amesos2_PardisoMKL_TypeMap.hpp
- packages/amesos2/src/Amesos2_PardisoMKL_decl.hpp
- packages/amesos2/src/Amesos2_PardisoMKL_def.hpp
This PR updates Amesos2 interface to Pardiso for the deprecated codes that have been removed.
On Blake using `intel/compilers/20.2.254`:
```
Test project /ascldap/users/iyamaza/github/basker/forks/trilinos-build-intel/packages/amesos2/test/solvers
Start 1: Amesos2_Pardiso_MKL_Solver_Test
1/2 Test #1: Amesos2_Pardiso_MKL_Solver_Test ...   Passed    0.05 sec
Start 2: Amesos2_SolverFactory_UnitTests
2/2 Test #2: Amesos2_SolverFactory_UnitTests ...   Passed    0.15 sec
100% tests passed, 0 tests failed out of 2
```
> Amesos2 : Update Pardiso interface for deprecated codes

- packages/amesos2/example/CMakeLists.txt
- packages/amesos2/example/SimpleSolve_IR.cpp
- packages/shylu/shylu_node/basker/src/shylubasker_nfactor_blk.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_order_btf.hpp
@trilinos/shylu @trilinos/amesos2 
- Amesos2 : this PR adds an example of using iterative refinements
- ShyLU-Basker : this PR also fixes the singularity detection when BTF has only one block (by turning the replace-zero-pivot flag off)
```
Start 1: ShyLU_NodeBasker_singular_matrix_check
1/6 Test #1: ShyLU_NodeBasker_singular_matrix_check .............   Passed    0.02 sec
Start 2: ShyLU_NodeBasker_basker_test_1
2/6 Test #2: ShyLU_NodeBasker_basker_test_1 .....................   Passed    1.03 sec
Start 3: ShyLU_NodeBasker_basker_amesos_test_1
3/6 Test #3: ShyLU_NodeBasker_basker_amesos_test_1 ..............   Passed    0.72 sec
Start 4: ShyLU_NodeBasker_basker_test_4
4/6 Test #4: ShyLU_NodeBasker_basker_test_4 .....................   Passed    1.32 sec
Start 5: …
```
> Amesos2 : adds iterative refinement example (plus ShyLU-Basker singularity-check fix)

- packages/amesos2/src/Amesos2_SolverCore_def.hpp
This PR tries to fix the errors when building Amesos2 IR with a non-standard scalar type.
> Amesos2 : support non-standard scalar type for IR

- packages/shylu/shylu_node/tacho/src/impl/Tacho_NumericTools_LevelSet.hpp
hip stream is used when kokkos execution space instances are destroyed. so, the stream should be defalcated afterward. cuda stream does not have this problem even if the stream is deleted first. for consistency, cuda destruction order is also changed.
Tested on caraway03 with ROCM 5.2
> Tacho - change hip stream destruction order.

- packages/framework/ini-files/config-specs.ini
Addresses #10865 
See commit log for details
Using the scripts:
**load-env-and-cmake-frag-file.sh:**
```
export TRILINOS_DIR=/fgs/rabartl/Trilinos.base/Trilinos
FULL_BUILD_NAME=rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables
if [[ -e GenConfigSettings.cmake ]] ; then
echo "Remvoing existing file GenConfigSettings.cmake ..."
rm GenConfigSettings.cmake
fi
export WORKSPACE=$TRILINOS_DIR/..
source $TRILINOS_DIR/packages/framework/GenConfig/gen-config.sh \
--cmake-fragment GenConfigSettings.cmake \
$FULL_BUILD_NAME \
--force \
$TRILINOS_DIR
unset FULL_BUILD_NAME
unset WORKSPACE
```
and:
**do-configure:**
```
if [[ -e CMakeCache.txt ]] ; then
echo "Removing CMakeCache.txt ..."
rm …
```
> Disable pseudo package ShyLU in ATS-2 builds (#10865)

- packages/framework/ini-files/config-specs.ini
CC: @trilinos/tpetra
* [TRILINOSHD-168](https://sems-atlassian-son.sandia.gov/jira/servicedesk/customer/portal/7/TRILINOSHD-168)
This PR disables the randomly failing tests `TpetraTSQR_SequentialTsqr_[non]contiguousCacheBlocks_MPI_1` that is taking out all kinds of PR iterations (see #10847).  The PR also removes 'FORCE' from all test disables (see #10870).
Using the scripts:
**load-env-and-cmake-frag-file.sh:**
```
export TRILINOS_DIR=/fgs/rabartl/Trilinos.base/Trilinos
FULL_BUILD_NAME=rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables
if [[ -e GenConfigSettings.cmake ]] ; then
echo "Remvoing existing file GenConfigSettings.cmake ..."
rm GenConfigSettings.cmake
fi
export …
```
> Disable randomly failing Tpetra test (#10847), remove FORCE from all test disables (#10870)

- packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HDIV_TRI.hpp
Minor fix, shadowed using for ExecutionSpace already available in the class definition.
> Intrepid2: fix shadowed ExecutionSpace using

- packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
- packages/tpetra/core/test/Distributor/Distributor_UnitTests.cpp
Adds a command line arg and a loop so we can run the "doPostsNonContig" test several times and get performance data on the slow path of the 3-arg doPostsAndWaits.
This is itself a test.
> Tpetra: Additions to get performance data from Distributor unit test

- packages/tpetra/core/test/MultiVector/Bug7745.cpp
- packages/tpetra/core/test/MultiVector/MultiVector_LocalViewTests.cpp
@trilinos/tpetra @bartlettroscoe 
Informational output is of limited utility when tests are passing, and can randomly break automated PR testing when it overlaps with and breaks up the "test passed" output.
* Closes #10885 
Update to tests to improve robustness.
> Tpetra: Remove informational output from passing tests

- packages/teuchos/core/src/Teuchos_Utils.hpp
- packages/teuchos/parser/src/Teuchos_FiniteAutomaton.cpp
- packages/teuchos/parser/src/Teuchos_FiniteAutomaton.hpp
@bartlettroscoe @cgcgcg 
Fix https://github.com/trilinos/Trilinos/issues/10892
It passed on my workstation.
> Fix #10892

- packages/amesos2/src/Amesos2_Control.cpp
- packages/amesos2/src/Amesos2_SolverCore_def.hpp
- packages/shylu/shylu_node/basker/src/shylubasker_def.hpp
@trilinos/amesos2, @trilinos/shylu 
- Fixes the iterative refinements in Amesos2
- Improve performance of ShyLU-Basker with MWM (by applying AMD ordering on block D)
Tested using test matrices from Xyce
> Amesos2-IR & ShyLU-Basker fixes

- packages/TrilinosInstallTests/CMakeLists.txt
Duplicate of https://github.com/trilinos/Trilinos/pull/10897 but with an even-numbered PR ID so it will get run by the PR tester (see https://github.com/trilinos/Trilinos/issues/10858#issuecomment-1221454400) :-)
> Improve TrilinosInstallTests to make more clear (#10896)

- packages/muelu/src/Graph/Containers/MueLu_Aggregates_def.hpp
- packages/muelu/src/Graph/Containers/MueLu_Aggregates_kokkos_decl.hpp
- packages/muelu/src/Graph/Containers/MueLu_Aggregates_kokkos_def.hpp
- packages/muelu/test/unit_tests_kokkos/Aggregates_kokkos.cpp
This addresses an inconsistency between `Aggregates` and `Aggregates_kokkos`. As an added bonus, this enables matrix-free restriction grid transfers. With how non-parallel the algorithm is, I think I can see why nobody did this before 🙂 
I have a couple bits of tidying to do before the final test, but I figured I'd open this now anyway. Mainly I'm really trying to figure out if the main couple loops can be turned into some more parallel-friendly algorithm. Otherwise I'll just copy everything to host and do the serial thing.
> MueLu: Add ComputeNodesInAggregate for Aggregates_kokkos

- packages/tpetra/CMakeLists.txt
The `CMakeLists.txt` was testing for
```
DEFINED Tpetra_INST_INT_LONG AND Tpetra_INST_INT_UNSIGNED_LONG
```
instead of
```
DEFINED Tpetra_INST_INT_LONG AND Tpetra_INST_INT_LONG
```
which resulted in `-DTpetra_INST_INT_LONG=ON` requiring the explicit `-DTpetra_INST_INT_LONG_LONG=OFF` to prevent the build failing from two ordinal types being specified.
> Tpetra: Fix CMake test for default ordinal type

- INSTALL.rst
- doc/DocumentingParameterLists/memo/SMemo_PListDoc.tex
- doc/DocumentingParameterLists/memo/smemo.cls
- doc/build_docs.pl
- doc/build_ref/TrilinosBuildReferenceTemplate.rst
Found via `codespell -q 3 -S ./packages,./commonTools/gtest`
> Fix typos in some docs 

- packages/tpetra/core/test/ImportExport2/AsyncTransfer_UnitTests.cpp
Test refactoring and consolidation.  Copy of #10851 since odd-numbered PRs are backed up.
Test refactoring -- tests should continue to pass
> Tpetra: code reduction in MultiVector async group transfer tests

- packages/panzer/adapters-stk/src/stk_interface/Panzer_STK_PeriodicBC_Matcher.hpp
- packages/panzer/adapters-stk/test/periodic_bcs/periodic_search.cpp
typedef collision with app 
Fixes
periodic_search.cpp
> Panzer: move periodic helper typedefs into namespace

- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_decl.hpp
- packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp
- packages/tpetra/core/test/Block/BlockCrsMatrix.cpp
Adds a `BlockCrsMatrix::importAndFillComplete()` function.
BlockCrsMatrix does not currently have a Matrix-Matrix multiple. This import function is necessary for that.
#10748
Test added
@csiefer: "This is good!"
> Tpetra: add BlockCrsMatrix::importAndFillComplete

- cmake/ctest/drivers/geminga/ctest_linux_nightly_serial_debug_muelu_epetra_geminga.cmake
Kokkos is a required MueLu dependency.
> Testing on Geminga: Do not disable Kokkos in Epetra build

- packages/amesos2/src/Amesos2_PardisoMKL_TypeMap.hpp
This PR is trying to fix the issues with including MKL header files from Amesos2 PardisoMKL.
Tested PardisoMKL with and without MKL TPL.
> Amesos2 : trying to fix issues with including MKL headers..

- packages/intrepid2/src/Shared/Intrepid2_TensorData.hpp
In the sum factorization case where the remaining number of elements is smaller than the workset size, this routine is usually called to resize the data. This sets the member variable for the extents so that any subsequent queries to `extent(0)` will return a size that is consistent with the underlying data.
> Intrepid2: Update TensorData.setFirstComponentExtentInDimension0 to modify extents_[0]

- packages/kokkos-kernels/src/sparse/KokkosSparse_spiluk_handle.hpp
- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spiluk_numeric_impl.hpp
- packages/kokkos-kernels/src/sparse/impl/KokkosSparse_spiluk_symbolic_impl.hpp
This PR matching changes in kokkos-kernels kokkos/kokkos-kernels#1480:
- Two views level_nchunks and level_nrowsperchunk are now allocated on host memory, instead of device memory, in the symbolic phase
- Allocation of device view iw is moved to the symbolic phase, to reduce some overheads in the numeric phase
- iw's layout is changed to LayoutRight for better memory coalescing
> Move host allocations to symbolic and change layout of iw

- packages/muelu/test/unit_tests/MueLu_Test_ETI.hpp
By default, MueLu's test ETI command line processor uses the default node type, but this code path was missing the call to Kokkos' `print_configuration`.
> MueLu: Allow to print Kokkos config when default node type is used

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc-cuda.cmake
Geminga gets somehow stuck on them, and the only other way to fix appears to be a reboot.
> Geminga: Disable Intrepid2 tests on CUDA

- packages/tpetra/core/src/Tpetra_Details_DistributorActor.hpp
@trilinos/tpetra @trilinos/zoltan2 
Recover performance of deleted host-only overload.  Discussion with @crtrott on Slack suggests the time difference between a single operation of the Kokkos-only solution and a specialized solution is too small to be able to recover the performance with Kokkos-only code.  This PR only changes the "3-arg slow path" in order to be minimally invasive, since that's the specific portion of code where meaningful slowdowns were noted.
* Closes #10194
Tpetra tests still pass in CPU, Cuda-UVM, and Cuda-No-UVM builds.
> Tpetra: specialize deep_copy_offset on Distributor::doPosts 3-arg slow path

- packages/framework/pr_tools/common.bash
Early exit from the execute_command() function due to a missing "color" command leads to weird behavior in our CI scripts.  Remove the "color" command and restore the coloring by using the "${normal}" variable instead.
> common.bash: remove missing "color" command

- packages/kokkos-kernels/src/graph/impl/KokkosGraph_Distance2MIS_impl.hpp
(Patch for KK PR #1528). Fixes bug #10950 where uninitialized memory was used in MIS-2 aggregation phase3. This didn't break the validity of the aggregation, but it did break determinism and potentially decreased the quality (size balance) of the aggregates.
Fixes a real bug, see description above
* Closes #10950 
* Blocks 
* Follows 
* Precedes 
* Related to 
* Part of 
* Composed of https://github.com/kokkos/kokkos-kernels/pull/1528
Bug showed up as Valgrind errors (conditional branch on uninitialized values) in the KokkosKernels graph unit tests and the MueLu Kokkos refactor unit tests.
> KokkosKernels: Fix #10950

- packages/shylu/shylu_node/fastilu/src/shylu_fastilu.hpp
With https://github.com/kokkos/kokkos-kernels/pull/1463, KokkosSparse::trsv (called StandardHost in FastILU) does not require the input matrix to have sorted rows. So skip sorting U^T when using StandardHost.
> FastILU: skip sorting U^T if using serial trsv

- packages/phalanx/src/Phalanx_KokkosViewOfViews.hpp
Add a static assert to make sure the number if indices used in VoV.addView() is the same as the outer view rank
Fixes issue observed in empire.
ViewOfViews unit test covers this.
> Phalanx: add static assert check for vov addView indices

- packages/muelu/test/unit_tests/ParameterList/ParameterListInterpreter/Comparison1.xml
Issue: #11019
Tests: This
Stakeholder feedback:n/a
Root cause was a comparison test which used non-deterministic aggregation on OpenMP.  Oops.  We probably shouldn't have our default OpenMP aggregation algorithm be non-deterministic, but that's a discussion for another time.
> MueLu: Fixing random test fail in #11019

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_makeColMap_def.hpp
Add a fence to `makeColMap`. Without it, Tpetra crashes on Cuda, UVM=on. With UVM=off it seems to work regardless.
> Tpetra: Add a fence in makeColMap and setAllToScalar

- packages/compadre/examples/CMakeLists.tribits.cmake
@trilinos/compadre 
Addresses issue with advanced tests using Python like:
```cmake
TRIBITS_ADD_ADVANCED_TEST(
${testName}
TEST_0 CMND ${PYTHON_EXECUTABLE} ARGS ${CMAKE_CURRENT_BINARY_DIR}/GMLS_Manifold_Multiple_Evaluation_Sites.py --porder=3 --grids=3 --in-trilinos=True
PASS_REGULAR_EXPRESSION "Passed."
COMM mpi serial
ADDED_TEST_NAME_OUT ${testName}_CREATED
)
```
Addresses issue https://github.com/trilinos/Trilinos/issues/10975 when `${PYTHON_EXECUTABLE}` is not defined.
> Compadre tests conditional on python

- packages/framework/ini-files/config-specs.ini
- packages/ifpack2/src/Ifpack2_Relaxation_def.hpp
- packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockCrsUtil.hpp
On some OpenMP runs, fast and slow path for diagonal extraction differ by (1e-14).
Fixes the Ifpack2 / CUDA 11 compilation issue, where the compiler can't figure out what "auto" really ought to be.  
Issue:#11048
> Ifpack2: Bump up tolerance

- commonTools/framework/ProjectCiFileChangeLogic.py
- commonTools/framework/ProjectCiFileChangeLogic_UnitTests.py
- commonTools/framework/get-changed-trilinos-packages.sh
These changes can break the PR build and/or tests in any Trilinos package so, to be safe, everything needs to be enabled when changing files under this directory (see #10881).
I tested this locally by using the local commits:
```
$ git log-short --name-status HEAD --not github/develop 
f5ecd341e85 "REMOVE ME: Change a file under packages/framework/"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Sep 23 08:28:33 2022 -0600 (5 minutes ago)
M       packages/framework/get_dependencies.sh
0bc59ef04ee "Make changes under packages/framework/ trigger enable of all packages (#10881)"
Author: Roscoe A. Bartlett <rabartl@sandia.gov>
Date:   Fri Sep 23 08:24:00 2022 -0600 (10 minutes ago)
M       commonTools/framework/ProjectCiFileChangeLogic.py
M …
```
> Make changes under packages/framework/ trigger enable of all packages (#10881)

- packages/stokhos/test/UnitTest/Stokhos_HermiteBasisUnitTest.cpp
> Stokhos:  Loosen tolerance to resolve failures on Intel19 + C++17

- packages/adelus/src/Adelus_factor.hpp
- packages/adelus/src/Adelus_perm_mat.hpp
- packages/adelus/src/Adelus_perm_rhs.hpp
This PR adds some changes to allow the permute view value type to be other than ```int``` type for the ```Adelus::Factor``` and ```Adelus::Solve``` interfaces
Tests are performed on Lassen and Weaver, and are confirmed by @jdkotul .
> Adelus: Fix to allow permute view value type rather than int

- packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_C0_FEM.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HVOL_C0_FEMDef.hpp
Orientation tools require basis functions to have unique names.
`Intrepid2_HVOL_C0_FEM` basis function has the same name independently of the basis topology, which create issues in 2d `HCurl` and `HDiv` boundary projections. 
Fixing this by including the topology name into the basis name, e.g. 
`Intrepid2_HVOL_Line_2_C0_FEM`
`Intrepid2_HVOL_Quad_4_C0_FEM`
In this way basis functions with different topologies have different names, which is required by orientations.
> Intrepid2: rename basis function Intrepid2_HVOL_C0_FEM

- packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HCURL_TET.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HDIV_TET.hpp
- packages/intrepid2/src/Discretization/Basis/Intrepid2_LegendreBasis_HVOL_TET.hpp
- remove private kokkos headers
- move kernel label to first argument of parallel_for
Updates to compile with disable of kokkos deprecated code
NA
Locally testing confirmed successful compilation with Kokkos' deprecated code disabled; AT for more testing
> intrepid2: updates to compile with disable of kokkos deprecated code

- packages/ifpack2/src/Ifpack2_BlockRelaxation_decl.hpp
- packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
- packages/ifpack2/src/Ifpack2_Container_def.hpp
- packages/muelu/test/scaling/CMakeLists.txt
- packages/muelu/test/scaling/Driver.cpp
- Don't catch exceptions in the MueLu driver unless we run several input decks. This avoids getting passing tests with failing input decks.
- Fix a bug in Ifpack2::BlockRelaxation for singletons.
> Ifpack2&MueLu: Block Relaxation fixes

- packages/belos/tpetra/src/BelosMultiVecTraits_Tpetra.hpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraMultiVector_def.hpp
- packages/thyra/adapters/tpetra/src/Thyra_TpetraVector_def.hpp
@trilinos/belos @trilinos/thyra 
Sierra developers had complained about slow performance from "extra Kokkos::fences" in Belos/Tpetra, so I went digging. 
The only fence in the Belos-Tpetra (non-Thyra) interface was the one after tpetra's mv.multiply in the `MvTimesMatAddMv` interface in the Belos-Tpetra adapter.  That fence came with this note indicating it might be extraneous: "Belos with Thyra's MvTimesMatAddMv allowed failures when fence was not applied after mv.multiply; adding the fence fixed the tests in Thyra. Out of an abundance of caution (and with blessing from @hkthorn), we add the fence here as well. #8821 KDD "
This fence, and corresponding fences in the Thyra-Belos interface, were added in this commit: …
> Belos/Thyra: Remove extra fences after Tpetra multiply in Belos and Thyra interfaces.

- packages/intrepid2/unit-test/MonolithicExecutable/BasisEquivalenceTests_Wedge.cpp
> Intrepid2: loosen tolerance of HVol basis equivalent test

- packages/seacas/applications/epu/pepu.C
Fix the ordering of the `mpi.h` include so it comes prior to the `epu.C` include.
Fixes #11126
> SEACAS: Fix pepu build

- packages/teuchos/comm/test/ParameterList/ParameterList_UnitTest_Parallel.cpp
- packages/teuchos/comm/test/ParameterList/inputSpecialChars.xml
- packages/teuchos/parameterlist/src/Teuchos_XMLObjectImplem.cpp
Fixes parallel reading XML input decks with special characters in them:
```
<Parameter name="sigma" type="string" value="if (x >= 0.0 &amp;&amp; y >= 0.0 &amp;&amp; x &lt;= 0.5 &amp;&amp; y &lt;= 0.5)"/>
```
> Teuchos: Fix parallel XML reader to correctly handle special characters

- packages/framework/ini-files/config-specs.ini
- packages/tpetra/tsqr/test/Tsqr_TestNodeTsqr.cpp
In TSQR's LAPACK wrappers, ``compute_QR`` and ``compute_explicit_Q`` each have their own function to compute the work length (lwork). Since the TSQR test reuses the same work array for both computations, its length needs to be the max of the two lworks. Not just the lwork for ``compute_QR`` since it might be too small to do the explicit Q.
There is already a function ``lworkQueryLapackQr`` to do this max, but it can't be used with cuSOLVER because ``cusolverDnXorgqr_bufferSize`` needs the actual A/tau pointers.
Fixes #10847.
The actual bug was just in the test.
> Tpetra TSQR: fix lwork in LAPACK tester

- packages/shylu/shylu_dd/frosch/src/CoarseSpaces/FROSch_CoarseSpace_def.hpp
- packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_decl.hpp
- packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_HarmonicCoarseOperator_def.hpp
- packages/shylu/shylu_dd/frosch/src/SchwarzOperators/FROSch_OverlappingOperator_def.hpp
This PR uses Kokkos::View instead of Teuchos::Array for accessing local part of MultiVector
Tested on Spock (not sure how this was not, and still isn't, crashing on my CUDA runs)
> Frosch : fix how MV is accessed from Kokkos execution space

- packages/tpetra/core/CMakeLists.txt
- packages/tpetra/core/cmake/TpetraCore_config.h.in
- packages/tpetra/core/src/Tpetra_ConfigDefs.hpp
- packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
- packages/tpetra/core/src/Tpetra_Util.hpp
- packages/tpetra/core/test/CrsMatrix/CrsMatrix_UnitTests.cpp
- packages/tpetra/core/test/Distributor/Distributor_UnitTests.cpp
Tpetra: Remove HAVE_TPETRA_THROW_EFFICIENCY_WARNINGS macros and associated code
Closes: #11005
> Tpetra: Remove HAVE_TPETRA_THROW_EFFICIENCY_WARNINGS

- packages/rol/adapters/tpetra/src/function/ROL_TpetraBoundConstraint.hpp
Compatibility update following kokkos@3.7
See kokkos/kokkos#4077 kokkos/kokkos#5194
@trilinos/rol 
A couple more removal of volatile from join in ROL_TpetraBoundConstraint.hpp. This should be the last PR with cleanup (I didn't catch this in previous PR)
> rol: remove volatile from join in ROL_TpetraBoundConstraint.hpp

- cmake/ctest/drivers/geminga/TrilinosCTestDriverCore.geminga.gcc.cmake
Should clean up Valgrind Intrepid2 report.
See #10945.
> Geminga: Pass max-stracktrace to Valgrind to avoid Intrepid2 issues

- packages/intrepid2/src/Discretization/Basis/Intrepid2_HierarchicalBasis_HDIV_TET.hpp
Fix shadow warnings that show up in Sierra builds, caused by some new headers in Intrepid2
@CamelliaDPG @mperego
> Intrepid2: Fix some shadow variable warnings

- packages/teko/src/Epetra/Teko_EpetraHelpers.cpp
- packages/teko/src/Epetra/Teko_EpetraHelpers.hpp
const char * function returns address to temporary variable
```make
/trilinos/packages/teko/src/Epetra/Teko_EpetraHelpers.hpp:167:12: warning: returning address of local temporary object [-Wreturn-stack-address]
{return ("zeroed( "+std::string(epetraOp_->Label())+" )").c_str(); }
```
This PR adds a `label_` std::string that is set at construction (all info needed is there at that time) and the c_str() is then returned for label. This is consistent with `/trilinos/packages/teko/src/Epetra/Teko_EpetraOperatorWrapper.hpp`
> Teko fix return of temporary address

- TPLsList.cmake
Added a few optional TPLs that can be used with the SEACAS IOSS library to provide additional capabilities.  These include:
* DataWarp -- Cray's burst buffer library
* Faodel -- a collection of data management tools that Sandia is developing to improve how datasets migrate between memory and storage resources in a distributed system.
* Cereal -- used by Faodel for serialization
* Catalyst2 -- Embedded visualization capability
* Related to #11154
> SEACAS: Add optional TPLs used by Seacas

- packages/kokkos/containers/src/Kokkos_DynRankView.hpp
- packages/kokkos/core/src/Kokkos_View.hpp
- packages/sacado/src/KokkosExp_View_Fad.hpp
- packages/sacado/src/Kokkos_DynRankView_Fad.hpp
- packages/sacado/src/Kokkos_View_Fad_Fwd.hpp
- packages/stokhos/src/sacado/kokkos/pce/KokkosExp_View_UQ_PCE_Contiguous.hpp
- packages/stokhos/src/sacado/kokkos/pce/Kokkos_View_UQ_PCE_Fwd.hpp
- packages/stokhos/src/sacado/kokkos/vector/KokkosExp_View_MP_Vector_Contiguous.hpp
- packages/stokhos/src/sacado/kokkos/vector/Kokkos_View_MP_Vector_Fwd.hpp
This pulls in the changes from Kokkos PR [5491](https://github.com/kokkos/kokkos/pull/5491) to allow as_view_of_rank_n to be overloaded for Sacado and Stokhos, and implements the necessary overloads for these packages.  This fixes issue #11018 which was causing problems in Albany.
> Overload Kokkos::Impl::as_view_of_rank_n for Sacado/Stokhos scalar types

- packages/teuchos/core/src/Teuchos_RCP.hpp
- packages/teuchos/core/src/Teuchos_RCPDecl.hpp
- packages/teuchos/core/test/MemoryManagement/RCP_UnitTests.cpp
`Teuchos::RCP` is currently missing one constructor of the `std::shared_ptr` ([constructor (8) here](http://en.cppreference.com/w/cpp/memory/shared_ptr/shared_ptr)) used for instance by pybind11 with multiple inheritance  https://github.com/pybind/pybind11/issues/1306 .
This PR adds the extra constructor.
> Teuchos: Add a constructor to Teuchos::RCP

- packages/nox/src/NOX_Multiphysics_Solver_Generic.H
- packages/nox/src/NOX_Multiphysics_Solver_Manager.C
- packages/nox/src/NOX_Multiphysics_Solver_Manager.H
- packages/nox/src/NOX_Solver_Generic.H
- packages/piro/test/MockModelEval_A_Tpetra.cpp
Two tests were failing cuda 11 builds. Had to fix the lifetimes of temporary local views of tpetra views.
Fixes #11169 
Fixes failing tests.
Covered under tests:
```
Piro_ThyraSolverTpetra_MPI_4
Piro_AnalysisDriverTpetra_MPI_4
```
> Piro: fix tests for cuda 11 builds

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Currently, `CrsMatrix< SCALAR , LO , GO , NODE >::convert< SCALAR >` is ETI'ed' twice.
This PR removes one of them.
> Tpetra: Avoid double instantiation of CrsMatrix< SCALAR , LO , GO , NODE >::convert< SCALAR >

- packages/sacado/example/trad_dfad_example.cpp
- packages/sacado/example/trad_example.cpp
- packages/sacado/src/Sacado_trad.hpp
Rad does its own memory management, but doesn't know anything about it when its nested scalar type is also dynamically allocated, which was causing massive memory leaks when using, e.g., Rad< DFad<double> >.  The only way to fix this without a major overhaul in Rad is to ask the user to call a new function to zero out all of Rad's internally stored data, which as a side-effect will deallocate DFad derivative arrays.  Also added this new function to the trad-dfad example.
For issue #7741.
> Sacado:  Fix memory leaks in Rad when using DFad nested scalar type.

- cmake/tribits/common_tpls/FindTPLHDF5.cmake
- cmake/tribits/common_tpls/FindTPLNetcdf.cmake
- cmake/tribits/common_tpls/FindTPLNetcdfDependencies.cmake
- cmake/tribits/core/package_arch/TribitsTplFindIncludeDirsAndLibraries.cmake
- cmake/tribits/core/std_tpls/FindTPLMPI.cmake
@trilinos/tribits 
This is motivated by issues TriBITSPub/TriBITS#533 and TriBITSPub/TriBITS#534, which are respectively:
1. The desire for the Netcdf TriBITS TPL to load only the CMake config files installed by NetCDF and HDF5, using the most modern CMake approach to bringing in those packages (using the targets that those projects define)
2. The desire to be able to use a custom implementation of MPI (not a compile wrapper but actually an include dir and library) to supply the TriBITS MPI TPL
As both the TriBITS contributor and also the ASC IC PI stakeholder, I would really like the capabilities listed in Motivation.
That's what this branch is for!
> Improve the TriBITS Netcdf and MPI TPLs

- packages/muelu/adapters/CMakeLists.txt
- packages/muelu/adapters/muelu-trivial-adapter.cpp
If no adapters are enabled, add the object file "muelu-trivial-adapter" to libmuelu-adapters.a.  In this way, TRIBITS_ADD_LIBRARY will always be invoked and install necessary header files.
Addresses #11192.
Supercedes #11180, which was an incorrect fix.
Reproduced problem locally, confirmed that this PR fixes.
> MueLu: reenable libmuelu-adapters.a

- packages/stratimikos/src/Stratimikos_LinearSolverBuilder_def.hpp
When this file was converted from a *.cpp file to a *_def.hpp file when Stratimikos::LinearSolverBuilder was templated in PR #10507, include guards did not get added to this file.
> Add include guards for *_def.hpp file (#10507)

- packages/framework/ini-files/config-specs.ini
Fixes #11205 
The PR testing will show that this is working (after examining the configure output on the 'ats2' build).
> Don't unconditionally enable STK subpackages (#11205)

- packages/stokhos/src/sacado/kokkos/Stokhos_DynamicStorage.hpp
- packages/stokhos/src/sacado/kokkos/Stokhos_DynamicStridedStorage.hpp
- packages/stokhos/src/sacado/kokkos/Stokhos_DynamicThreadedStorage.hpp
- packages/stokhos/src/sacado/kokkos/Stokhos_StaticFixedStorage.hpp
- packages/stokhos/src/sacado/kokkos/Stokhos_StaticStorage.hpp
- packages/stokhos/src/sacado/kokkos/Stokhos_StorageHelpers.hpp
- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_ops.hpp
- packages/stokhos/test/UnitTest/CMakeLists.txt
- packages/stokhos/test/UnitTest/Stokhos_ExponentialRandomFieldUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixMPVectorUnitTest_Serial.cpp
- packages/stokhos/test/UnitTest/Stokhos_KokkosCrsMatrixUQPCEUnitTest_Serial.cpp
- packages/stokhos/test/UnitTest/Stokhos_KokkosViewFadMPVectorUnitTest_Serial.cpp
- packages/stokhos/test/UnitTest/Stokhos_KokkosViewMPVectorUnitTest_Serial.cpp
- packages/stokhos/test/UnitTest/Stokhos_KokkosViewUQPCEUnitTest_Serial.cpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest_MaskTraits.cpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoUQPCECommTests.cpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoUQPCESerializationTests.cpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoUQPCEUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_UnitTestBase.cpp
- packages/stokhos/test/UnitTest/Stokhos_UnitTestHelpers.hpp
@trilinos/Stokhos
@etphipp
Stokhos is now able to perform basic mathematical operations with ensembles of `std::complex` and `Kokkos::Complex`.
The main fix brought by this PR is the addition of `using std::matop` in the macros of `packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector_ops.hpp`. This brings a behavior that is similar to `packages/sacado/src/Sacado_Fad_Ops.hpp` for instance.
Moreover, the test `packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp` has been adapted to ensure that `Kokkos::Complex` now works with ensembles.
This PR was already discussed and reviewed in [uliegecsm/Trilinos/1.](https://github.com/uliegecsm/Trilinos/pull/1)
As a side quest, I also added a `Stokhos_UnitBaseTestLib` (static) that contains the `int main(...)` entrypoint. Only the …
> Stokhos: support for custom types in `Sacado::MP::Vector`

- packages/amesos2/src/Amesos2_Superludist_FunctionMap.hpp
- packages/amesos2/src/Amesos2_Superludist_def.hpp
@balay
@masterleinad 
@balos1
The xSDK 0.8 release is potentially going to include Trilinos 13.4 as Trilinos 14.0 is delayed. Some other xSDK packages are not ready to use a newer version of Trilinos. However, some packages require superlu_dist version 8, which is not supported by Trilinos 13.4. This patch applies superlu_dist 8 support, which was previously added to the develop branch, to the 13.4 branch.
There is some relevant conversation in this issue:
https://github.com/xsdk-project/xsdk-issues/issues/177
This would be tested as part of the xSDK 0.8.0 release testing. It would also go through Trilinos PR testing if there are sufficient resources to do so.
> Trilinos 13 4 superlu dist 8 patch

- packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_EdgeBasis_impl.hpp
In UVM=off builds, the Dirichlet_Residual_EdgeBasis evaluator was broken. The mirror view needed a deep_copy of the values from device.
Fixes EMPIRE solver_interface unit tests
> Panzer: fix issue with uvm=off in Dirichlet_Residual_EdgeBasis

- packages/tpetra/core/src/Tpetra_CrsGraph_decl.hpp
- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
- packages/tpetra/core/src/Tpetra_Details_WrappedDualView.hpp
- packages/tpetra/core/src/Tpetra_MultiVector_def.hpp
- packages/tpetra/core/test/Block/BlockMultiVector.cpp
This results in a decent (up to 3x) performance improvement on non-UVM builds for CUDA/ROCm for problems with large matrices (e.g. >1 GB). Changes include:
- WrappedDualView initialization from device view no longer initializes host dataspace using the device data.
- CrsGraph/CrsMatrix have duplicate calls to copy the same row ptrs view from device to host 5-6 times in a row. This is now reduced to 1 time for trivial constructions (i.e. packed == unpacked).
> Tpetra: Reduce device-to-host memcpy calls in non-uvm builds

- packages/ifpack2/doc/UsersGuide/options.tex
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_decl.hpp
- packages/ifpack2/src/Ifpack2_Details_Chebyshev_def.hpp
- packages/ifpack2/src/Ifpack2_PowerMethod.hpp
- packages/ifpack2/test/belos/CMakeLists.txt
- packages/ifpack2/test/belos/test_Cheby_calore1_nospectralradius_mm.xml
I was able to reproduce the Ifpack2 Cheby test failure reported in #11204 on my machine, and thanks to help from @cgcgcg after banging our heads together for a bit, we realized this is a strange combination of several things.
1. $D^{-1}A$ for this problem ( $A$ is in `calore1.mtx`) has two dominant eigenvalues, 12.5839 and -10.6639.
2. The power method uses a random initial guess with a default of 10 iterations.
3. The loop computing `lambdaMax` is computed using $\\|D^{-1}Ax\\|_2$, but the final computation after the loop instead uses $x^T D^{-1}A x$.
There are all sorts of strange things that can happen. For this particular example, the eigenvalue history when using `<Parameter name="debug" type="bool" value="true"/>` will look like it's converging to something in the …
> Ifpack2: Make the Chebyshev power method consistent with itself

- packages/aztecoo/src/az_gmres_condnum.c
- packages/aztecoo/src/az_scaling.c
- packages/belos/tpetra/src/solvers/Belos_Tpetra_SolverManagerBase.hpp
- packages/epetraext/src/coloring/EpetraExt_MapColoring.cpp
- packages/ml/src/Operator/ml_op_utils.c
- packages/ml/src/Operator/ml_rap_utils.c
- packages/stratimikos/adapters/belos/src/Thyra_BelosTpetrasSolverAdapter.hpp
- packages/zoltan/src/lb/lb_init.c
- packages/zoltan/src/params/free_params.c
@trilinos/aztecoo 
@trilinos/epetraext 
@trilinos/ml 
Clean up a number of warnings and deprecated code:
```make
/Users/pakuber/Compadre/trilinos/packages/zoltan/src/lb/lb_init.c:128:28: warning: initializing 'struct Zoltan_LB_Struct *' with an expression of type 'const struct Zoltan_LB_Struct *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
[ 31%] Building C object packages/aztecoo/src/CMakeFiles/aztecoo.dir/az_matvec_mult.c.o
/Users/pakuber/Compadre/trilinos/packages/aztecoo/src/az_gmres_condnum.c:835:9: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
if( abs(Er[i])>largest_inv_A2 ) largest_inv_A2 = abs(Er[i]);
vi:1379:16: warning: equality comparison with …
```
> Cleanup warnings and refactor deprecated code

- packages/kokkos-kernels/src/sparse/KokkosSparse_Utils_mkl.hpp
Do not emit compile-time error if attemping to use MKL utils with unsupported scalar types. These changes were suggested by @maartenarnst .
This can be considered a temporary fix because the proper TPL wrappers using unification layer will not instantiate MKL wrappers for unsupported types in the first place. In particular, this is coming for SpGEMM.
Replaces compile-time error with runtime exception. When using Tpetra::CrsMatrix with Scalar being something other than float/double/complex_float/complex_double (which is perfectly fine), KokkosKernels shouldn't be trying to instantiate any MKL utils/wrappers for those scalar types. But since it is, replacing with runtime error instead is a reasonable fix for now.
For the 4.0 release, the MKL SpGEMM wrappers will go …
> KokkosKernels: Fix #11033

- packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
Fix for https://github.com/trilinos/Trilinos/issues/11253
> tpetra: make distributor plan createFromSends throw on bad proc ID when `TPETRA_DEBUG=1`

- packages/amesos2/doc/Doxyfile
- packages/intrepid2/doc/Doxyfile
We want to have better links from our Doxygen documentation to Trilinos.
For that sake, we use tag files.
As of now, we are able to use tag file of `Tpetra`, mainly. As we use Doxygen with the "fail if any warning occurs" option, the other tag files (when available) lead to errors.
This PR will:
* Change `amesos2` tag file location. Indeed, it is not in https://docs.trilinos.org/dev/packages/common/tag_files/ as I think it should.
* Generate a tag file for `intrepid2`
Similar to:
* https://github.com/trilinos/Trilinos/issues/10511
> doxygen: improvements for amesos2, intrepid2 and kokkos

- packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp
Previously, were comparing against unpacked row pointer array, which is filled w.r.t the allocated size of the matrix, not the number of entries actually used.
The code is not covered by automatic testing, though testing locally with `TPETRA_DEBUG=1` will exercise it.
> tpetra: compares no. of packed values to packed row pointers

- packages/piro/src/Piro_PerformAnalysis.cpp
@mperego 
Recent change to piro is causing compile failures on all empire builds. The error is in an ifdef that apparently is not exercised by PR builds but is used by empire.
N/A
> PIRO: fix bug with ostream

- cmake/ctest/drivers/atdm/cee-rhel7/drivers/Trilinos-atdm-cee-rhel7_mini-no-mpi_clang-9.0.1_serial_static_opt.sh
- cmake/ctest/drivers/atdm/cee-rhel7/drivers/Trilinos-atdm-cee-rhel7_mini-no-mpi_cuda-10.1.243_gnu-7.2.0_static_opt.sh
- cmake/ctest/drivers/atdm/cee-rhel7/drivers/Trilinos-atdm-cee-rhel7_mini-no-mpi_gnu-7.2.0_serial_static_opt.sh
- cmake/ctest/drivers/atdm/tlcc2/drivers/Trilinos-atdm-tlcc2-intel-debug-openmp.sh
- cmake/ctest/drivers/atdm/tlcc2/drivers/Trilinos-atdm-tlcc2-intel-opt-openmp.sh
- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_dbg.sh
- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.0_openmpi-4.0.2_openmp_static_opt.sh
- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.3_openmp_static_dbg.sh
- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.3_openmp_static_opt.sh
- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_dbg.sh
- cmake/ctest/drivers/atdm/van1-tx2/drivers/Trilinos-atdm-van1-tx2_arm-20.1_openmpi-4.0.5_openmp_static_opt.sh
- cmake/std/atdm/ATDMDisables.cmake
Disabled builds and tests that have failed for all recorded history on CDash (see https://github.com/trilinos/Trilinos/issues/10355#issuecomment-1303693318).
See individual commits for details.
> Clean up ATDM builds for CMake upgrade (#10355)

- packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson2DExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidHybridPoisson3DExample.cpp
- packages/trilinoscouplings/examples/scaling/TrilinosCouplings_TpetraIntrepidStructuredPoissonExample.cpp
- packages/trilinoscouplings/examples/scaling/example_Poisson_NoFE_Tpetra.cpp
Fixes simultaneous host/device access in Ifpack2 block relaxation as seen in proposed PR test using CUDA 11.4.2 ([dashboard link](https://trilinos-cdash.sandia.gov/build/609006)).
Also eliminates some sign-change compiler warnings in some TrilinosCouplings examples.
@trilinos/ifpack2 @trilinos/trilinoscouplings @trilinos/muelu 
Part of standing up new PR test using CUDA 11.4.2, as described in #11239 and https://sems-atlassian-son.sandia.gov/jira/browse/TRILFRAME-491.
N/A
I reproduced the MueLu/Ifpack2 block relaxation test errors locally and verified that this PR allows the tests to complete successfully.
> Ifpack2: fix wrapped dualview error

- packages/piro/src/Piro_TempusSolver_Def.hpp
- packages/piro/test/Piro_TempusSolver_AdjointSensitivitySinCosUnitTests.cpp
This PR allows using Tempus implicitly defined adjoint model evaluator when the user provided adjoint model is null. 
@trilinos/piro
Added test case to exercise use of implicitly defined adjoint model evaluator.
> Piro: use implicitly defined adjoint model evaluator for transient sensitivities

- packages/panzer/disc-fe/src/Panzer_FaceToElement_impl.hpp
Fix the lifetime of local views of Tpetra vectors. Views were not being released before export and import calls. Mainly just adding braces around sections to release views before the import export calls.
> Panzer: fix lifetimes of local views in FaceToElement

- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_decl.hpp
- packages/tpetra/core/src/Tpetra_Details_FixedHashTable_def.hpp
- packages/tpetra/core/src/Tpetra_Details_LocalMap.hpp
- packages/tpetra/core/test/Map/Map_LocalMap.cpp
@trilinos/Tpetra
Suggested reviewer: @brian-kelley 
`Tpetra::Details::LocalMap` and `Tpetra::Details::FixedHashTable` had no device default constructor, leading to issues when using them in a `Kokkos::DualView` with `cuda uvm`. See related issue for more information.
* Related to #11186
We tested the patch for both `cuda` and `rocm`.
> Tpetra: (local map) device default constructor fix for #11186

- packages/kokkos-kernels/src/sparse/KokkosSparse_Utils_cusparse.hpp
This change removes the compile-time static-assert on valid scalar types for the cuSPARSE TPL.  The run-time check is still there, and this mimics the behavior for the interface to the older (CUDA-10) cuSPARSE interface.  Making this a compiler error makes it very difficult for packages such as Ifpack2 to support scalar types that cuSPARSE might not, since it can't even instantiate Kokkos-Kernels when cuSPARSE is eanbled and fixes several compiler errors when Ifpack2 is instantiated on Stokhos scalar types.
For issue #11297.
> Kokkos-Kernels:  Disable compile-time check on supported scalar types for cuSPARSE

- packages/ifpack2/src/Ifpack2_LocalSparseTriangularSolver_def.hpp
As per the suggestion of @etphipp in #11297, this PR adds another condition of scalar types supported by cuSPARSE for Ifpack2 calling cuSPARSE SPTRSV. Otherwise, Ifpack2 calls Kokkos Kernels's SPTRSV implementation.
> Ifpack2: Call cuSPARSE SPTRSV if scalar type is supported by cuSPARSE

- packages/teuchos/numerics/src/Teuchos_BLAS_wrappers.hpp
The BLAS wrappers require C-linkage, and std::complex is not allowed. This avoids warning about using C++ complex types in the return value.
This patch keeps the original check (from the lapack wrappers) to not do this for Microsoft Visual C++ compiler.
Fixes #11010
> Use C99 Datatype for return value of complex blas functions

- packages/panzer/disc-fe/src/evaluators/Panzer_Dirichlet_Residual_FaceBasis_impl.hpp
Allows for kernel to be run UVM free.
> Panzer: move dirichlet residual face basis computation to device

- packages/panzer/adapters-stk/src/Panzer_STK_IOClosureModel_Factory.cpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgQuantity_decl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgQuantity_impl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgVector_decl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellAvgVector_impl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellQuantity_decl.hpp
- packages/panzer/adapters-stk/src/evaluators/Panzer_STK_ScatterCellQuantity_impl.hpp
- packages/panzer/adapters-stk/src/responses/Panzer_STK_ResponseEvaluatorFactory_SolutionWriter_impl.hpp
Allow the user to scale the output exodus fields.
> Panzer: allow users to scale the output exodus fields

- packages/tpetra/core/src/Tpetra_Map_def.hpp
Potential fix for https://github.com/trilinos/Trilinos/issues/11316
> tpetra: Remove unused `execSpace` parameter from checkMapInputArray

- README.md
This is one of many things that may help external users reach package owners. It relies on the wiki page being as up-to-date as possible, which isn't much of a limitation, as it is easy to edit the wiki.
This helps external users mention the correct parties because external users may not mention teams for a project.
> README: Update the README to point users to the Trilinos package owners wiki

- packages/stokhos/test/UnitTest/CMakeLists.txt
Apparently including NUM_MPI_PROCS N with N > 1 prevents the test from running in a serial build, which is not desired behavior.  I don't remember this being the case years ago when this option was added, but appears to be now.
> Stokhos:  Remove NUM_MPI_PROCS from parallel-enabled tests

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/question.md
Related to #11319.
This will help external users identify and mention package owners by their Github handles because external users cannot mention Github teams.
> Github: Update issue templates to refer external users to the package owners wiki

- packages/muelu/src/Rebalancing/MueLu_RepartitionHeuristicFactory_def.hpp
- packages/muelu/test/scaling/JacobiKernelDriver.cpp
- packages/muelu/test/scaling/MatvecKernelDriver.cpp
- packages/muelu/test/scaling/TwoMatrixMMKernelDriver.cpp
This changes our uses of `ExecSpace::concurrency()` to `ExecSpace().concurrency()` as requested in #11331 to prepare for https://github.com/kokkos/kokkos/issues/5655.
> MueLu: Update ExecSpace::concurrency() for the non-static case

- packages/stokhos/src/sacado/kokkos/vector/Sacado_MP_Vector.hpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest.cpp
- packages/stokhos/test/UnitTest/Stokhos_SacadoMPVectorUnitTest_MaskTraits.cpp
Closes #11337.  
These changes are tested in `Stokhos_SacadoMPVectorUnitTest_MPI_1` and `Stokhos_SacadoMPVectorUnitTestMaskTraits_MPI_1`.
> Device version of MP vector constructor with initialiser list.

- packages/tpetra/core/src/Tpetra_Details_DistributorPlan.cpp
`index` is set but unused in two places in Tpetra_Details_DistributorPlan.cpp
> Tpetra: cleanup: set-but-unused variable in Details_DistributorPlan.cpp

- packages/framework/pr_tools/trilinosprhelpers/unittests/environment-specs.ini
Not needed for testing, and confusing for people trying to ensure that CUDA_LAUNCH_BLOCKING is not set anymore.
User Support Ticket(s) or Story Referenced: TRILINOSHD-227
Real variables should not be used in capability testing, for pretty much this exact reason (Roger was concerned that it may have been used "for real").
> Remove CUDA_LAUNCH_BLOCKING from testing

- packages/framework/ini-files/config-specs.ini
- packages/framework/pr_tools/LaunchDriver.py
- packages/framework/pr_tools/unittests/test_LaunchDriver.py
- Increase parallel levels for rdc build
- Always use build stats and the ninja generator
Increase parallel build levels for the cuda 11 rdc build in an effort to get nightly rdc results posted every 24 hours.
Tested via:
```
source ../packages/framework/GenConfig/gen-config.sh --ci-mode --cmake-fragment frag.cmake rhel7_sems-cuda-11.4.2-sems-gnu-10.1.0-sems-openmpi-4.0.5_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_rdc_uvm_deprecated-on_all ..
```
Enable build stats for all PR and MM builds.
Select Ninja generator for all PR and MM builds since that is what PR testing scripts are using already. It is confusing that Unix Makefiles are used when running GenConfig outside of PR testing.
> packages/framework:

- packages/framework/ini-files/config-specs.ini
We can then inherit from that configuration when running our `rhel7_sems-intel-2021.3-sems-openmpi-4.0.5_release-debug_shared_no-kokkos-arch_no-asan_no-complex_fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all` configuration.
This should return the Intel-2021.3 compiler to the testing lineup.
> disable failing tests in base Intel 2021.3 config

- .github/workflows/title_to_mention.yml
Because github won't let non-team members do team mentions.
This is the "test" version of this utility, just targeting Ifpack2 and MueLu.  We can add more packages later, assuming it works.
> Actions: Adding a title/label to mention utility for Ifpack2, MueLu

- packages/framework/ini-files/config-specs.ini
User Support Ticket(s) or Story Referenced: TRILFRAME-517
Want the RDC builds to use a full 4 GPU machine to get results faster from testing.
> Use 2x4 (slots x GPUs) for RDC build

- packages/panzer/adapters-stk/example/CurlLaplacianExample/CMakeLists.txt
- packages/panzer/adapters-stk/example/MixedCurlLaplacianExample/CMakeLists.txt
- packages/panzer/adapters-stk/example/MixedPoissonExample/CMakeLists.txt
- packages/panzer/adapters-stk/src/Panzer_STK_ParameterListCallbackBlocked.cpp
- packages/panzer/adapters-stk/src/Panzer_STK_ParameterListCallbackBlocked.hpp
- packages/panzer/adapters-stk/src/Panzer_STK_SetupLOWSFactory.cpp
- packages/panzer/mini-em/example/BlockPrec/main.cpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_MassMatrix_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_ProjectedSchurComplement_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_SchurComplement_impl.hpp
- packages/panzer/mini-em/src/eqn_sets/MiniEM_AuxiliaryEquationSet_WeakGradient_impl.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_DiscreteCurl.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_DiscreteGradient.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory.cpp
- packages/panzer/mini-em/src/solvers/MiniEM_FullMaxwellPreconditionerFactory_Augmentation.cpp
- packages/panzer/mini-em/src/solvers/MiniEM_Interpolation.hpp
- packages/panzer/mini-em/src/solvers/MiniEM_Utils.cpp
- packages/panzer/mini-em/src/solvers/MiniEM_Utils.hpp
make epetra stack optional for panzer
N/A
> Panzer: make epetra optional in stk adapters and mini-em

- packages/teuchos/comm/src/Teuchos_StackedTimer.cpp
This fixes segfaults when repeatedly exercising stacked timer reports with different options. This can happen when timing summaries are printed to both terminal and Watchr XML.
> Teuchos StackedTimer: Fix for repeated reports with different options

- packages/panzer/dof-mgr/src/Panzer_ElemFieldPattern.cpp
- packages/panzer/dof-mgr/test/field_pattern/CMakeLists.txt
- packages/panzer/dof-mgr/test/field_pattern/tEntityFieldPattern.cpp
The class `ElemFieldPattern` was hard-coding `3` in one of its method, as the value for element dimension. This PR changes the check to use `getDimension()`, so that it works for Elem fields in meshes of arbitrary dimension. The behavior is unchanged if the mesh dimension is 3.
In Albany, we are checking `getSubcellIndices(dim,0).size()` (for `dim=0,...,getDimensions()`), to determine if the field in the mesh is a NODE or ELEM field. With the current master, on (n<=2)-dimensional elements, ElemFieldPattern shows no dofs for all `dim`. Things would work correctly if we used a `FaceFieldPattern`, but it'smore concise to always use `ElemFieldPatter` for fields that have one value per cell, regardless of mesh dimension.
Added a unit test to verify indices counts for basic …
> Panzer: remove hard-coded 3d dim in ElemFieldPattern method

- packages/intrepid2/src/Discretization/Integration/Intrepid2_CubatureDirect.hpp
- packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits.hpp
- packages/teuchos/core/src/Teuchos_UnitTestHelpers.hpp
- packages/tpetra/core/inout/MatrixMarket_TpetraNew.hpp
Following issue #11247, we now compile our PDE code using Trilinos as a regular include, rather than as a system include. This allows us to see and solve more compiler warnings in our PDE code.  
When we compile our PDE code in this way, we also see compiler warnings that seem to be related to Trilinos itself.  For some of those compiler warnings, there seem to be rather straightforward fixes, which we would like to propose as a PR:
- The fix around line 531 in `packages/stokhos/src/sacado/kokkos/vector/Stokhos_MP_Vector_MaskTraits.hpp` solves a warning about deprecated implicit generation of a copy constructor.
```
error: implicitly-declared 'constexpr Mask<Sacado::MP::Vector<Stokhos::StaticFixedStorage<int, double, …
```
> stokhos/tpetra/teuchos/intrepid2: Fix warnings

- commonTools/framework/CMakeLists.txt
Can revisit this later, but a new deprecated code warning is blocking PRs now (and manual inspection reveals that it's due to code coverage).  I changed the regex to be a little bit less restrictive (warnings show up after the test passes, so this should allow them to be there).
User Support Ticket(s) or Story Referenced: N/A
Framework test warnings (and manifested as failures) are blocking all PRs.
#11435
> Framework: Ignore warnings in pytest tests

- packages/compadre/src/Compadre_KokkosParser.cpp
- packages/compadre/src/Compadre_Typedefs.hpp
See https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Compatibility.html#user-defined-macros-compatibility
@kuberry
> Compadre: Do not define `KOKKOS_*` macros, add `COMPADRE_` prefix

- packages/seacas/libraries/ioss/src/private_copy_fmt/fmt/format.h
- packages/seacas/libraries/suplib_cpp/fmt/format.h
> SEACAS: temporary fix to fmt TPL for gcc 7.2

- cmake/ExtraRepositoriesList.cmake
- cmake/ctest/drivers/rocketman/ctest_linux_experimental_mpi_release_avatar_rocketman.cmake
@cgcgcg 
This should hopefully clean up some of the Rocketman nightly dashboard.
Also, Avatar_repo used to point to Mark's gitlab, so I updated it to point to the sandialabs github repo.
> CMake: Update Rocketman Avatar nightly, update Avatar repository location

- packages/shards/src/Shards_BasicTopologies.cpp
- packages/shards/src/Shards_BasicTopologies.hpp
- packages/shards/src/Shards_CellTopologyTraits.hpp
@trilinos/shards 
The fact that a Particle was 1-dimensional created issues when using it as a "cell" topology in Panzer's dof manager stack. Although no Finite Elements can be defined on a Particle, being able to use it allows to avoid treating special cases everywhere, and keep a uniform code.
Will considerably help Albany to switch to Panzer::DOFManager class(es).
No additional tests required. Shards existing tests already cover Particle.
> Shards: make Particle topology 0-dimensional

- packages/framework/ini-files/config-specs.ini
- packages/framework/ini-files/supported-config-flags.ini
Prototype code coverage collection via a nightly build:
- Added the `debug-coverage` option and `rhel7_sems-gnu-8.3.0-openmpi-1.10.1-serial_debug-coverage_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_all`
- See accompanying ctest changes.
Fixed appending `opt-set-cmake-var` commands. CMake cache variables are sticky. If appending in config-specs.ini, use the `FORCE` option. This applies to raw CMake as well.
Manually via our pipeline scripts (pending). See TRILFRAME-23.
> TRILFRAME-23: Add nightly coverage build

- packages/tpetra/core/src/Tpetra_CrsGraph_def.hpp
Broken in #11422. Changing back to what it was while avoiding shadow warnings.
> Tpetra: Fix wrong execution space in CrsGraph
